### ISSUE TITLE
Crash on refreshing file list in Photos

### ISSUE THREAD

**Issue by njakes** [nextcloud/android#8485] opened 2021-05-27 00:41 UTC
### Steps to reproduce
1. Upload tons of photos using windows client (several GB worth)
2. Sort photos from InstantUpload folder into appropriate albums.

### Expected behaviour
- properly update file list on android device

### Actual behaviour
- cannot open Photos folder on android app anymore. It crashes to the below log. 
- autosync is failing complaining about a conflict. Using browser shows the folder as empty with no conflicting image.

### Can you reproduce this problem on https://try.nextcloud.com?
No it requires the android app
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model:  pixel 4a

Stock or customized system: Calyx OS

Nextcloud app version: current fdroid as of bug report date.

Nextcloud server version: nextcloudpi 20.0.8

Reverse proxy: none

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 967, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProvider.delete(ContentProvider.java:1757)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:389)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:352)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2413)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:403)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:576)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:564)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:2196)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:438)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:528)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:410)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:238)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Android
Device: sunfish
Model: Pixel 4a
Id: RQ2A.210505.002
Product: calyx_sunfish

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2021.05.05.12

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by njakes** [comment] 2021-05-27 01:31
Deleting the F-Droid 'Nextcloud' app and installing the F-Droid 'Nextcloud Dev' app seemed to fix this issue. The folder refreshes properly and I can open newly added photos.
Automatic upload also works now.

**Comment by AndyScherzinger** [comment] 2021-05-27 07:55
> Deleting the F-Droid 'Nextcloud' app and installing the F-Droid 'Nextcloud Dev' app seemed to fix this issue. The folder refreshes properly and I can open newly added photos.
Automatic upload also works now.

It would also work with a fresh install of the stable app. Unfortunately when "too many" files have been moved and thus the index/listing in the database need to be updated for a large amount of files (several 100s) then the database interactions will simply fail since we would need to do this in smaller blocks where we don't do such things in blocks at all at the moment. :/

@tobiasKaminsky do you know a way how this can be solved (while we would need to do this for several db update routines I guess.

**Comment by arnwas** [comment] 2021-11-18 10:58
I keep seeing this. Any solution for this yet?

**Comment by AlvaroBrey** [comment] 2022-03-03 16:36
Duplicate of #6103

**Closed by AlvaroBrey** 2022-03-03 16:36 UTC
Labels: bug, approved
