### ISSUE TITLE
Auto upload stopped working

### ISSUE THREAD

**Issue by miodzicho** [nextcloud/android#759] opened 2017-03-18 21:11 UTC
### Actual behaviour
AutoUpload stopped working, I have files waiting in the queue, but nothing happened.

### Expected behaviour
Photos should be uploaded into Nextcloud server as usual
 
### Steps to reproduce
1. take picture
2. go to autoupload queue
3. check progress

### Environment data
Android version: 7.0.

Device model: 
HTC10
Stock or customized system:
stock
Nextcloud app version:
1.4.2
Nextcloud server version:
11.0.2
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by AndyScherzinger** [comment] 2017-03-18 21:26
@miodzicho in the upload view what is the status of the the to be uploaded items? Are they pending? Waiting for wifi? Failed?

**Comment by miodzicho** [comment] 2017-03-18 21:27
Waiting for upload

**Comment by mario** [comment] 2017-03-18 21:31
@miodzicho Did you set them to upload only on wifi, and took them when you weren't on wifi?

**Comment by miodzicho** [comment] 2017-03-18 21:33
@mario I do have them upload on wifi, indeed, but taken when I was on wifi, at least few of them.

**Comment by mario** [comment] 2017-03-18 21:33
weird ... I thought it was a requirement issue :-/

If I build a new APK for you, can you test?

**Comment by miodzicho** [comment] 2017-03-18 21:34
@mario sure I can

**Comment by mario** [comment] 2017-03-18 21:42
@miodzicho will be ready in a few mins.

**Comment by mario** [comment] 2017-03-18 21:45
@miodzicho https://github.com/nextcloud/android/raw/small-change/nextcloud-android-debug.apk

**Comment by mario** [comment] 2017-03-18 21:55
@miodzicho will get you a better one in a sec as well, with same url :)

**Comment by mario** [comment] 2017-03-18 21:56
@miodzicho done. @jasonbayton you're more than invited to try as well!

**Comment by mario** [comment] 2017-03-18 22:52
@miodzicho let me know when you get a chance to test, I"m done for today! thanks!

**Comment by miodzicho** [comment] 2017-03-19 07:17
Good day. I've installed provided app. Same issue. Photos are stuck in queue. But funny enough, in old app I saw, they were uploaded after all overnight. Weird.

**Comment by mario** [comment] 2017-03-19 07:58
@miodzicho so they did upload, ok. That's actually a "feature" of the Android system where the system itself decides when to upload files, and not us. *shrug*

**Comment by miodzicho** [comment] 2017-03-19 08:00
May I stay with debug app, or shall I rollback to public release ?

**Comment by mario** [comment] 2017-03-19 08:07
Rollback to public, since debug isnt any better

**Comment by miodzicho** [comment] 2017-03-20 07:53
I did rollback to public release, auto upload still doesn't work. Even overnight, so now I have files in queue for last 24 hours, and nothing being uploaded.

**Comment by Mickael-Martin** [comment] 2017-03-22 21:33
Same issue here. Can I help ?

**Comment by mario** [comment] 2017-03-23 12:58
@miodzicho and @Mickael-Martin : https://github.com/nextcloud/android/blob/read-access/nextcloud-android-generic-debug.apk

**Comment by mario** [comment] 2017-03-24 11:33
Also if that one doesn't work, try this:

**Comment by miodzicho** [comment] 2017-03-25 18:06
No link attached?

Am 24.03.2017 12:33 schrieb "Mario Đanić" <notifications@github.com>:

**Comment by mario** [comment] 2017-03-25 18:08
miodzicho https://github.com/nextcloud/android/blob/fix-issue-with-wifi/nextcloud-android-generic-debug.apk?raw=true

**Comment by tobiasKaminsky** [comment] 2017-06-26 13:19
@all do you still experience the problems?

**Comment by jasonbayton** [comment] 2017-06-26 13:21
I can't replicate on the Play Beta branch.

**Comment by shieldwed** [comment] 2017-06-26 15:37
I am on Play Beta branch as well, but having set the auto upload to upload on wifi only it seems my pictures are only uploaded after a device restart.

**Comment by tobiasKaminsky** [comment] 2017-06-27 07:58
@shieldwed what device do you have? Maybe there is a problem detection wifi status? (we are relying on a library for that, so it is not that easy to know)

**Comment by mario** [comment] 2017-06-27 08:01
@tobiasKaminsky no, that's not the issue. Here's what the "problem" is:

- take yourself off wifi
- take some pictures
- wait half an hour

By now, the job scheduled time has grown exponentially so it will run again in a few hours. If you're not on wifi after few hours once it wants to execute, it will schedule it again even further ahead.

Reboot "fixes" this because it runs a job right away if you're on wifi when booting. 

So technically, this is not an issue - UX-wise, I know it can be so I'm solving it for the new auto upload.

**Comment by tobiasKaminsky** [comment] 2017-06-27 08:09
Ah, did not know that the jobscheduler increases the time between job execution and thought also that a job will run "immediately" once a requirement is met, e.g. switch from mobile data to wifi.

**Comment by jasonbayton** [comment] 2017-06-27 08:32
That'd be the expectation, but alas..

**Comment by shieldwed** [comment] 2017-06-27 18:33
@tobiasKaminsky I've got a Sony Xperia XZ (F8331), Android Version 7.1.1 (Patch Level June 1, 2017) Nextcloud App version 1.4.3, Nextcloud version 12.0.0

@mario I'll have a look at that scheduler ...

**Comment by jasonbayton** [comment] 2017-06-27 22:41
As @mario has described it as intended behaviour, I've gone ahead and removed bug in favour of enhancement as it's something to be improved rather than fixed.

**Comment by shieldwed** [comment] 2017-07-05 06:16
You are right @mario, the upload is working with the current release (1.4.3) but it depends on how the files are scheduled for at what time the files are uploaded (and in my case) after the wifi connection is established.

Is the upload intended to happen immediately after specified conditions (connected to wifi, device recharging, mobile internet connection reestablished) are met?

**Comment by mario** [comment] 2017-07-05 06:41
@shieldwed unfortunately no. While that would be ideal, the Android platform makes this kind of impossible. One could say there are workarounds (and there indeed are), but all those workarounds are being closed by Google with each passing day.

The end goal: battery life.

**Comment by mario** [comment] 2017-07-06 02:02
I wouldn't suggest reboot just to start uploads :) Anyway, I promise to get it "fixed" for 1.5, and this will significantly improve user experience.

**Comment by Kaliumhexacyanoferrat** [comment] 2017-07-07 11:56
@ferdiga: Force-closing the app works as well without the need to reboot the device.

**Comment by ferdiga** [comment] 2017-07-07 20:15
@Kaliumhexacyanoferrat 
I think I force-stopped the app, some images were uploaded , but then it hanged again.
but lets hope for 1.5 ....

**Comment by mario** [comment] 2017-07-26 08:22
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by TE7** [comment] 2017-07-30 05:29
I installed this dev APK and Autoupload is not working at all. In version 1.4.3 autoupload did not work but pictures will be shown and stuck in Uploads menu. Now it doesn't show any pictures or videos there and it doesn't Autoupload anything at all.
I removed 1.4.3 and installed dev APK only and it doesn't work. I restarted phone several times and it didn't help either. 
Autoupload is set to Only upload on Wi-Fi and phone is connected to the Wi-Fi.

Phone is Nubia Z11mini with Nubia UI 4.0 based on Android 6.0.1

The same issue is on the Redmi Note 3 phone (running MIUI Global 7.1 based on Android 5.1.1) 

Anothe issue is that application will always show briefly No Files Here when visiting any folder on the server including ones with files in it.

**Comment by mario** [comment] 2017-07-30 05:44
@TE7 you need to wait up to 20 minutes before files will show in the upload queue. Can you please confirm you've done that?

**Comment by TE7** [comment] 2017-07-30 06:12
Hi Mario,

I just got notification on Redmi Note 3 that Autoupload is pending reset. After the phone is reset pictures were uploaded automatically.
So far no joy on Nubia Z11mini.

**Comment by TE7** [comment] 2017-07-30 06:13
I'll test it more tomorrow morning and let you know if there are any changes.
If uou need something please let me know and I'll try to help.

**Comment by mario** [comment] 2017-07-30 06:20
@TE7 "pending reset"? There's no such thing o.O

Are you sure you're using the right APK?

**Comment by TE7** [comment] 2017-07-30 13:20
I downloaded it from the link in your post above. 
It is version 20170727 Next cloud dev Android app 

This morning it shows Failed/pending restart (108) and all videos and pictures are listed for upload. 
The last night it was only pictures I took after installing dev app. 

On Nubia Z11 mini there's still nothing listed to upload.

**Comment by TE7** [comment] 2017-07-30 13:27
If I click on download the latest dev version I see that 20170730 is available. 
I'll try it on Nubia Z11 and see how it works.

**Comment by TE7** [comment] 2017-07-30 13:32
After I checked server all pictures from Redmi Note 3 were uploaded even app was showing Failed /pending restart.

**Comment by TE7** [comment] 2017-07-30 14:53
Pictures are stuck on Waiting for upload on Nubia Z11 mini - app version 20170730
This is after waiting for more than one hour, restarting the phone and reconnecting Wi-Fi. 
Pictures appear in Uploads list as soon as they are taken but never get uploaded.

**Comment by mario** [comment] 2017-07-30 16:18
This is definitely not the right APK then. With the new APK images would not appear in the queue right away. :-/

**Comment by TE7** [comment] 2017-07-30 16:47
Where do I get the right APK?
 I used option under Dev ==> Download latest dev version

![screenshot_2017-07-30-12-43-13](https://user-images.githubusercontent.com/30563906/28755285-310b78a4-7525-11e7-87cb-3f2ef25994a4.png)

**Comment by mario** [comment] 2017-07-30 16:55
Delete that, and install one from here:

**Comment by mario** [comment] 2017-07-30 16:56
(See above comment via web browser, in case you're reading via mail)

**Comment by TE7** [comment] 2017-07-30 18:43
I installed it and app works same as before - no Autoupload activity at all.
Here is log file from the phone. I hope that will help.
[currentLog.zip](https://github.com/nextcloud/android/files/1185903/currentLog.zip)

**Comment by TE7** [comment] 2017-07-30 18:50
![1](https://user-images.githubusercontent.com/30563906/28756122-6beeb15a-7536-11e7-868c-2392e6e7b229.png)
![2](https://user-images.githubusercontent.com/30563906/28756126-70abf478-7536-11e7-8797-7bbf5bc90aa5.png)
![3](https://user-images.githubusercontent.com/30563906/28756129-757ef518-7536-11e7-979e-77395daeb74b.png)

**Comment by mario** [comment] 2017-07-30 18:56
Can you try this one?

https://cloud.nextcloud.com/s/pAbCOxR71TEhGgR

**Comment by TE7** [comment] 2017-07-31 04:33
That one didn't work either.

**Comment by mario** [comment] 2017-07-31 05:06
:-/ do you have time for a teamviewer + android studio + vysor at some time?

**Comment by shieldwed** [comment] 2017-07-31 05:11
I beg to differ. I installed https://cloud.nextcloud.com/s/ftZraTruRQjTe0R and auto upload works at least as good as with the regular version. I'll upload a picture of my upload queue later.

**Comment by mario** [comment] 2017-07-31 05:22
Given how new auto upload works, phone/os would have to be pretty screwed
for this not to work :-/

That is why I asked him for a remote debugging session.

**Comment by TE7** [comment] 2017-07-31 13:19
I'm at work now and can't do it. Maybe we can setup some other time. Here is 9:18am now FYI.
I think we can chat in non-English version too. (hvala Mario)

**Comment by mario** [comment] 2017-07-31 13:54
Yup, sure. You prepare all the things I asked for and we can agree on some time. :)

You're most welcome! ;)

**Comment by TE7** [comment] 2017-07-31 14:34
I'm having new internet installed today so I expect some interruptions in the service.
When that is done I'll prepare everything and I'll let you know my availability.

**Comment by mario** [comment] 2017-07-31 14:39
Thanks!

**Comment by TE7** [comment] 2017-07-31 18:58
Just checked and there is an update available for my phone on the manufacturer's web site. 
I'll flash it tonight and see if that improves anything. It looks like they fixed a quite bit of bugs as they released 4 updates this year and hopefully this will be easy fix for my problem.
Also, phone is scheduled for update to Android 7 sometimes in August so I might decide to wait and see how or if that will affect Nextcloud app. 
I'll keep you posted and thank you for all your help.

**Comment by cbm755** [comment] 2017-07-31 19:24
I haven't seen it mentioned so maybe I'm stating the obvious but I've been working around this by downgrading to `1.4.1`.  My package manager (F-Droid) bothers me to upgrade every couple days, but I just ignore it ;-)

Anyway, maybe that helps someone out there.

**Comment by mario** [comment] 2017-07-31 23:20
Based on comments from others, new Auto Upload works magically. I understand it does not work for @TE7, but that seems awfully strange so we'll do a remote debugging session eventually.

In the mean time, I'm removing this from the milestone.

**Comment by TE7** [comment] 2017-08-01 19:01
I updated phone and some bugs are fixed. Still no luck with Autoupload yet.
If you are not in a rush we could do remote debugging sometimes next week. My family is going away on the next Monday and I'll have more time to do it after that.

**Comment by TE7** [comment] 2017-08-05 02:32
Hi Mario,

I just installed debug version from the link in this discussion and I'm happy to report that Autoupload worked as intended.

[Call for testing - Android client version 1.5!](https://help.nextcloud.com/t/call-for-testing-android-client-version-1-5/18755)

**Great job and thank you one more time.** 

![1](https://user-images.githubusercontent.com/30563906/28992216-b34e1a72-7964-11e7-88f8-21912171f27c.png)

**Comment by mario** [comment] 2017-08-05 03:41
Excellent, thank you for testing :)

**Closed** 2017-08-05 04:48 UTC
Labels: AutoUpload, enhancement
