### ISSUE TITLE
Unexpected error on image details check

### ISSUE THREAD

**Issue by lapers** [nextcloud/android#14211] opened 2024-12-21 00:43 UTC
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to read from field 'com.google.android.material.tabs.TabLayout com.owncloud.android.databinding.FileDetailsFragmentBinding.tabLayout' on a null object reference in method 'void com.owncloud.android.ui.fragment.FileDetailFragment.lambda$setupViewPager$0()'
    at com.owncloud.android.ui.fragment.FileDetailFragment.lambda$setupViewPager$0(FileDetailFragment.java:355)
    at com.owncloud.android.ui.fragment.FileDetailFragment.$r8$lambda$Sp-VmtMx2q_HeyzGV0P1GEAXBvw(Unknown Source:0)
    at com.owncloud.android.ui.fragment.FileDetailFragment$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:9063)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300690`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `g0s`
* Model: `SM-S906B`
* Id: `UP1A.231005.007`
* Product: `g0sxxx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S906BXXUDEXK5`

**Comment by joshtrichards** [comment] 2024-12-28 15:08
Duplicate of #13933

**Closed by joshtrichards** 2024-12-28 15:08 UTC
Labels: bug, feature: files, performance: NPE :no_entry_sign:
