### ISSUE TITLE
Cannot use widget

### ISSUE THREAD

**Issue by gauravmane713** [nextcloud/android#13893] opened 2024-10-28 03:41 UTC
### Cause of error
```java
Exception in thread "DefaultDispatcher-worker-1" java.lang.RuntimeException: Accessing result data after operation failed!
    at com.owncloud.android.lib.common.operations.RemoteOperationResult.getResultData(RemoteOperationResult.java:489)
    at com.nextcloud.client.widget.DashboardWidgetConfigurationActivity$loadWidgets$1$2.invokeSuspend(DashboardWidgetConfigurationActivity.kt:164)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at android.os.Handler.handleCallback(Handler.java:1000)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loopOnce(Looper.java:242)
    at android.os.Looper.loop(Looper.java:362)
    at android.app.ActivityThread.main(ActivityThread.java:8441)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `motorola`
* Device: `vienna`
* Model: `motorola edge 50 neo`
* Id: `U4UIS34.8-40-1-1`
* Product: `vienna_g_sys`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `2de76-58212`

**Comment by joshtrichards** [comment] 2024-10-28 13:51
Duplicate of #13228

**Closed by joshtrichards** 2024-10-28 13:51 UTC
