### ISSUE TITLE
After canceled the action of register in screen new host

### ISSUE THREAD

**Issue by carlos-braz** [nextcloud/android#13976] opened 2024-11-07 14:56 UTC
### Cause of error
```java
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property currentAccount has not been initialized
    at com.nextcloud.client.mixins.SessionMixin.getCurrentAccount(SessionMixin.kt:32)
    at com.nextcloud.client.mixins.SessionMixin.onRestart(SessionMixin.kt:100)
    at com.nextcloud.client.mixins.MixinRegistry.onRestart(MixinRegistry.kt:48)
    at com.owncloud.android.ui.activity.BaseActivity.onRestart(BaseActivity.java:118)
    at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1520)
    at android.app.Activity.performRestart(Activity.java:8700)
    at android.app.ActivityThread.performRestartActivity(ActivityThread.java:5914)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:244)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:183)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:132)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8762)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `r8q`
* Model: `SM-G780G`
* Id: `TP1A.220624.014`
* Product: `r8qxx`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `G780GXXSCEXI1`

**Comment by joshtrichards** [comment] 2024-11-07 15:34
Duplicate of #13241

**Closed by joshtrichards** 2024-11-07 15:34 UTC
