### ISSUE TITLE
REDMI K40 CAN NOT USE IT.

### ISSUE THREAD

**Issue by lighterEB** [nextcloud/android#9492] opened 2021-12-09 09:33 UTC
### Steps to reproduce

### Expected behaviour
- input the URL and next step

### Actual behaviour
- but the app exited

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: 104.207.131.247:9326
	at java.net.URI.create(URI.java:849)
	at com.owncloud.android.authentication.AuthenticatorUrlUtils.normalizeScheme(AuthenticatorUrlUtils.java:103)
	at com.owncloud.android.authentication.AuthenticatorActivity.checkOcServer(AuthenticatorActivity.java:774)
	at com.owncloud.android.authentication.AuthenticatorActivity.lambda$initOverallUi$0$com-owncloud-android-authentication-AuthenticatorActivity(AuthenticatorActivity.java:543)
	at com.owncloud.android.authentication.AuthenticatorActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7517)
	at android.view.View.performClickInternal(View.java:7494)
	at android.view.View.access$3600(View.java:845)
	at android.view.View$PerformClick.run(View.java:28752)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8168)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0: 104.207.131.247:9326
	at java.net.URI$Parser.fail(URI.java:2894)
	at java.net.URI$Parser.checkChars(URI.java:3067)
	at java.net.URI$Parser.checkChar(URI.java:3077)
	at java.net.URI$Parser.parse(URI.java:3093)
	at java.net.URI.<init>(URI.java:585)
	at java.net.URI.create(URI.java:847)
	... 15 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: alioth
Model: M2012K11AC
Id: RKQ1.200826.002
Product: alioth

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 21.9.17

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by lighterEB** [comment] 2021-12-09 09:41
perhaps was causes of ":"

**Comment by AlvaroBrey** [comment] 2021-12-09 09:46
Duplicate of #9338

**Closed by AlvaroBrey** 2021-12-09 09:46 UTC
Labels: bug
