### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by asterling8516** [nextcloud/android#13148] opened 2024-06-19 07:13 UTC
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Parameter specified as non-null is null: method com.owncloud.android.ui.dialog.SyncedFolderPreferencesDialogFragment$setupListeners$1$6.onItemSelected, parameter view
    at com.owncloud.android.ui.dialog.SyncedFolderPreferencesDialogFragment$setupListeners$1$6.onItemSelected(Unknown Source:2)
    at android.widget.AdapterView.fireOnSelected(AdapterView.java:957)
    at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946)
    at android.widget.AdapterView.selectionChanged(AdapterView.java:935)
    at android.widget.AdapterView.checkSelectionChanged(AdapterView.java:1119)
    at android.widget.AdapterView.handleDataChanged(AdapterView.java:1095)
    at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:193)
    at android.widget.Spinner.onMeasure(Spinner.java:615)
    at androidx.appcompat.widget.AppCompatSpinner.onMeasure(AppCompatSpinner.java:444)
    at android.view.View.measure(View.java:27423)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
    at android.view.View.measure(View.java:27423)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
    at android.view.View.measure(View.java:27423)
    at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1525)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.widget.ScrollView.onMeasure(ScrollView.java:472)
    at android.view.View.measure(View.java:27423)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
    at android.view.View.measure(View.java:27423)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:27423)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:27423)
    at androidx.appcompat.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:134)
    at androidx.appcompat.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:64)
    at android.view.View.measure(View.java:27423)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
    at android.view.View.measure(View.java:27423)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:27423)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:27423)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
    at android.view.View.measure(View.java:27423)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at com.android.internal.policy.DecorView.onMeasure(DecorView.java:768)
    at android.view.View.measure(View.java:27423)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4409)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2922)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3289)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2659)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9789)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1399)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)
    at android.view.Choreographer.doCallbacks(Choreographer.java:1008)
    at android.view.Choreographer.doFrame(Choreographer.java:938)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)
    at android.os.Handler.handleCallback(Handler.java:959)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8501)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290090`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `felix`
* Model: `Pixel Fold`
* Id: `AP1A.240405.002.A2`
* Product: `felix`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `11677426`

**Comment by joshtrichards** [comment] 2024-06-19 15:44
What activity were you performing at the time? Some context would be helpful. Preferably steps to reproduce/etc. Thanks!

**Comment by joshtrichards** [comment] 2024-07-05 20:03
May be fixed by #13070

**Comment by joshtrichards** [comment] 2024-07-05 20:04
Duplicate of #12586

**Closed by joshtrichards** 2024-07-05 20:04 UTC
Labels: bug, needs info, performance: NPE :no_entry_sign:, Version/3029

**Comment by joshtrichards** [comment] 2024-09-01 15:19
@asterling8516 Are you still seeing this behavior in newer versions of the client?
