### ISSUE TITLE
Nextcloud upload crash

### ISSUE THREAD

**Issue by lkjasdf9kl** [nextcloud/android#11063] opened 2022-11-21 12:33 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

> auto upload is setup so as to be completed when plugged in

> this happens during upload

### Expected behaviour

Upload without crashing

### Actual behaviour

The app crashes continuously 

### Android version

13

### Device brand and model

Samsung galaxy s22

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.3

### Nextcloud server version

24.0.5

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 5336616 free bytes and 5211KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
    at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:303)
    at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8741)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220390`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `r0q`
* Model: `SM-S901U`
* Id: `TP1A.220624.014`
* Product: `r0qsqw`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `S901USQU2BVK1`

**Comment by Aizmansor** [comment] 2022-11-21 14:59
Dihantar daripada telefon saya-------- Mesej asal --------Daripada: lkjasdf9kl ***@***.***>Tarikh: Isn, 21 Nov 2022, 8:33 PTGKepada: nextcloud/android ***@***.***>Sk: Subscribed ***@***.***>Tajuk: [nextcloud/android] Nextcloud upload crash (Issue #11063)

⚠️ Before posting ⚠️

 This is a bug, not a question or an enhancement. I've searched for similar issues and didn't find a duplicate. I've written a clear and descriptive title for this issue, not just "Bug" or "Crash". I agree to follow Nextcloud's Code of Conduct.

Steps to reproduce



auto upload is setup so as to be completed when plugged in





this happens during upload



Expected behaviour

Upload without crashing

Actual behaviour

The app crashes continuously

Android version

13

Device brand and model

Samsung galaxy s22

Stock or custom OS?

Stock

Nextcloud android app version

3.22.3

Nextcloud server version

24.0.5

Using a reverse proxy?

No

Android logs

Cause of error

Exception in thread "main" java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 5336616 free bytes and 5211KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.

    at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:303)

    at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)

    at android.os.Handler.dispatchMessage(Handler.java:106)

    at android.os.Looper.loopOnce(Looper.java:226)

    at android.os.Looper.loop(Looper.java:313)

    at android.app.ActivityThread.main(ActivityThread.java:8741)

    at java.lang.reflect.Method.invoke(Native Method)

    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)

    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

App information

ID: com.nextcloud.clientVersion: 30220390Build flavor: gplay

Device information

Brand: samsungDevice: r0qModel: SM-S901UId: TP1A.220624.014Product: r0qsqw

Firmware

SDK: 33Release: 13Incremental: S901USQU2BVK1

Server error logs

No response

Additional information

No response

**Comment by kcastner** [comment] 2022-11-22 09:13
Looks Like the Same issue with Reverse proxy - Ticket #11066 

Got Same Error with and without Reverse Proxy:

### Cause of error
```java
Exception in thread "Thread-5" java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 5315192 free bytes and 5190KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
    at sun.security.x509.X500Name.parseDER(X500Name.java:803)
    at sun.security.x509.X500Name.<init>(X500Name.java:317)
    at javax.security.auth.x500.X500Principal.<init>(X500Principal.java:226)
    at com.android.org.conscrypt.OpenSSLX509Certificate.getSubjectX500Principal(OpenSSLX509Certificate.java:502)
    at okhttp3.internal.tls.BasicTrustRootIndex.<init>(BasicTrustRootIndex.kt:28)
    at okhttp3.internal.platform.Platform.buildTrustRootIndex(Platform.kt:163)
    at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.kt:160)
    at okhttp3.internal.platform.Android10Platform.buildCertificateChainCleaner(Android10Platform.kt:82)
    at okhttp3.internal.tls.CertificateChainCleaner$Companion.get(CertificateChainCleaner.kt:42)
    at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:870)
    at com.nextcloud.common.PlainClient$Companion.createDefaultClient(PlainClient.kt:62)
    at com.nextcloud.common.PlainClient$Companion.access$createDefaultClient(PlainClient.kt:47)
    at com.nextcloud.common.PlainClient.<init>(PlainClient.kt:45)
    at com.nextcloud.client.network.ClientFactoryImpl.createPlainClient(ClientFactoryImpl.java:94)
    at com.nextcloud.client.network.ConnectivityServiceImpl.isInternetWalled(ConnectivityServiceImpl.java:79)
    at com.owncloud.android.files.services.FileUploader.retryFailedUploads(FileUploader.java:1072)
    at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:240)
    at com.owncloud.android.utils.FilesSyncHelper$$ExternalSyntheticLambda0.run(Unknown Source:10)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220390`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `c2s`
* Model: `SM-N986B`
* Id: `SP1A.210812.016`
* Product: `c2sxeea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `N986BXXS5FVI5`

**Comment by SakshiT25** [comment] 2022-11-22 14:04
Hi, I would like to work on this issue if it is not assigned to somebody yet. Thanks.

**Comment by kcastner** [comment] 2022-11-22 14:11
> Hi, I would like to work on this issue if it is not assigned to somebody yet. Thanks.

Im not sure if #10730 is related to this... i updated to beta at my android; now the app wont crash anymore - the automatic sync now wont work 👍 

im not sure hot to debug this - its hanging at upload; i got there 2913 items with status of failed/waiting; if i click restart, the app starts hanging and crashes; the feedback windows opens up, i klick report -> market feedback service is hanging...

**Comment by AlvaroBrey** [comment] 2022-11-23 12:09
Duplicate of #10653

**Closed by AlvaroBrey** 2022-11-23 12:09 UTC
Labels: bug, performance
