### ISSUE TITLE
login loop after new media folder was found on device

### ISSUE THREAD

**Issue by JimmyKater** [nextcloud/android#13055] opened 2024-05-31 04:32 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

A new media folder was found on device
Clicked on configure in the message
Needed to authenticate (fingerprint)
Needed to authenticate (fingerprint)
Needed to authenticate (fingerprint)
... Etc

### Expected behaviour

Well... After ONE successfully authetication the configuration should have opened

### Actual behaviour

You end up in an authetication loop

### Android version

see below

### Device brand and model

Google Pixel 6a

### Stock or custom OS?

Stock

### Nextcloud android app version

see below

### Nextcloud server version

28.0.4

### Using a reverse proxy?

I don't know

### Android logs

See below

### Server error logs

```bash
See below
```

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1632)
    at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1672)
    at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
    at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
    at androidx.fragment.app.DialogFragment.show(DialogFragment.java:524)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onSyncFolderSettingsClick(SyncedFoldersActivity.kt:587)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$load$1$1.invokeSuspend(SyncedFoldersActivity.kt:317)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at android.os.Handler.handleCallback(Handler.java:959)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8501)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290090`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `bluejay`
* Model: `Pixel 6a`
* Id: `AP1A.240505.004`
* Product: `bluejay`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `11583682`

**Comment by PoxyDoxy** [comment] 2024-05-31 05:09
I just experienced the same fingerprint login loop on my android mobile, however it was when I clicked on the auto-upload notification.

**Comment by joshtrichards** [comment] 2024-06-13 14:03
Duplicate of #10791

**Closed by joshtrichards** 2024-06-13 14:03 UTC
Labels: bug, performance: ISE/IAE :confused:
