### ISSUE TITLE
App crasht auch nach mehrfachen Neuinstallation und ist seit dem November Update nicht mehr nutzbar bitte um Hilfe.

### ISSUE THREAD

**Issue by Stoony1** [nextcloud/android#7518] opened 2020-11-27 03:49 UTC
### Steps to reproduce
1. Start der App 
2. Passwort eingeben
3. App Crasht 

Leider hilft auch eine Neuinstallation nicht.

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=3, totalRows=4
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4657)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4690)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=3, totalRows=4
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1196)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:173)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:134)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:249)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:281)
	at android.database.CursorWrapper.moveToNext(CursorWrapper.java:206)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:913)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:185)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:938)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1278)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1231)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1220)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onActivityCreated(OCFileListFragment.java:397)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2718)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
	at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:447)
	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:458)
	at com.owncloud.android.ui.activity.BaseActivity.onResume(BaseActivity.java:91)
	at com.owncloud.android.ui.activity.DrawerActivity.onResume(DrawerActivity.java:893)
	at com.owncloud.android.ui.activity.FileActivity.onResume(FileActivity.java:240)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1119)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
	at android.app.Activity.performResume(Activity.java:8111)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4647)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140152
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: d2s
Model: SM-N975F
Id: QP1A.190711.020
Product: d2seea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: N975FXXU6DTJ4

**Comment by Stoony1** [comment] 2020-11-27 04:05
Auch nach dem leeren des Caches bleibt das Problem bestehen, die App öffnet sich dann zwar kurzzeitig aber stürzt dann mit dem selben Fehler wieder ab. Hab das nun mehrere Male probiert inklusive Handy Neustart hat alles nichts gebracht.

**Comment by tobiasKaminsky** [comment] 2020-11-27 06:03
This seems to be a duplicate of #6688, as you might have too many files in your folder?
(we need to fix this…)

**Closed by tobiasKaminsky** 2020-11-27 06:03 UTC
Labels: bug
