### ISSUE TITLE
App error after playing MP3 file from self hosted cloud

### ISSUE THREAD

**Issue by coxa** [nextcloud/android#8947] opened 2021-09-06 23:53 UTC
### Steps to reproduce
1. Open mobile app
2. Navigate to folder with MP3 files
3. Play one file fully from start to end
4. After playing. Go back

### Expected behaviour
I should see list files like on step 2

### Actual behaviour
App show's following information
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{a77432d u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1946)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7403)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: jasmine_sprout
Model: Mi A2
Id: QKQ1.190910.002
Product: jasmine

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V11.0.28.0.QDIMIXM

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2021-09-07 10:03
This is for me the only 100% reproducible way of triggering this bug.

**Comment by AlvaroBrey** [comment] 2021-09-07 10:48
Duplicate of #8686

**Closed by AlvaroBrey** 2021-09-07 10:48 UTC
Labels: bug, approved
