### ISSUE TITLE
Crash when opening the "All Files" tab during uploads 

### ISSUE THREAD

**Issue by resvis** [nextcloud/android#12827] opened 2024-04-05 00:13 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Upload some files
2. During uploading, open the App via the notifications, and enter the "Uploads" window of the APP
3. Click the menu and switch to the "All Files" window

### Expected behaviour

Open the window without crashing 

### Actual behaviour

Crash most of the times

### Android version

14

### Device brand and model

Samsung galaxy A8 SM-X205

### Stock or custom OS?

Stock

### Nextcloud android app version

30280090

### Nextcloud server version

28.0

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.Stack.push(java.lang.Object)' on a null object reference
    at com.owncloud.android.ui.activity.FileDisplayActivity.setSortListGroup(FileDisplayActivity.java:2496)
    at com.owncloud.android.ui.activity.FileDisplayActivity.setLeftFragment(FileDisplayActivity.java:616)
    at com.owncloud.android.ui.activity.FileDisplayActivity.setLeftFragment(FileDisplayActivity.java:604)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onNewIntent(FileDisplayActivity.java:571)
    at android.app.Activity.performNewIntent(Activity.java:8978)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1556)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1569)
    at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:4362)
    at android.app.ActivityThread.handleNewIntent(ActivityThread.java:4369)
    at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8913)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30280090`
* Build flavor: `gplay`

**Comment by joshtrichards** [comment] 2024-06-13 14:13
Duplicate of #12649

**Closed by joshtrichards** 2024-06-13 14:13 UTC
Labels: bug
