### ISSUE TITLE
App photos crash

### ISSUE THREAD

**Issue by a7mad7aydar** [nextcloud/android#7438] opened 2020-11-22 12:48 UTC
Hi guys! Thanks for the amazing work! 

I am facing two problems.
1. The app is loading only 39 photos for some reason and whenever I refresh asking for more it get stuck loading. 
2. The app crashes always when I navigate files. At first I thought it was because I don't have GMS (I have HMS) but then I tried it on my tablet with GMS and the same happens. 

Nextcloud is sitting on a raspberry pi 4

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d4d22c3 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWLIO
Model: LIO-L29
Id: HUAWEILIO-L29
Product: LIO-L29

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.1.0.270C432

**Comment by paulbastian** [comment] 2020-11-23 07:57
I'm facing problem number 2 as well, also rpi4

**Comment by AndyScherzinger** [comment] 2020-11-23 09:07
Duplicate of #6905

**Closed by AndyScherzinger** 2020-11-23 09:07 UTC
Labels: bug
