### ISSUE TITLE
Get Camera Video Function On File Upload

### ISSUE THREAD

**Issue by axel-rank** [nextcloud/android#5415] opened 2020-02-06 10:00 UTC
### Is your feature request related to a problem? Please describe.
Uploading files has the option to choose Upload from Camera.
But there is only the option to take pictures.
No option to take videos from camera.
(using Firefox Mobile to login to nextcloud there is a camcorder option on file uploads)

### Describe the solution you'd like
Option to get access to the camcorder function of the camera on file uploads.

**Comment by joshtrichards** [comment] 2023-10-13 19:52
Duplicate of #7358 

I encourage you to subscribe to that Issue and/or upvote it.

**Closed by joshtrichards** 2023-10-13 19:52 UTC
Labels: enhancement
