### ISSUE TITLE
Request to move delete local copy from delete dialog popup

### ISSUE THREAD

**Issue by 31337-4554551n** [nextcloud/android#11173] opened 2022-12-16 05:52 UTC
The buttons for "delete" and "local only" are dangerously close together. Can accidentally ireversably delete a file

### Describe the solution you'd like
I would like a separate option to remove local file. Or "unsync" or something. So clicking delete is for permanent deletion. And this other option is just for the phone copy only. Which then lead into their separate confirmation dialogues. 

### Describe alternatives you've considered
Have the confirmation dialogue to delete delete local and cancel spread buttons further apart, but even then it's a dangerous game

**Comment by joshtrichards** [comment] 2023-12-20 15:43
Duplicate of #3342

Please feel free to contribute to that discussion and/or subscribe to it and/or upvote (:+1: ) it.

**Closed by joshtrichards** 2023-12-20 15:43 UTC
Labels: enhancement, feature: files
