### ISSUE TITLE
Error messages since a few days

### ISSUE THREAD

**Issue by stefan-franz** [nextcloud/android#12605] opened 2024-02-26 14:51 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Since some days i have error messages like this. Closind and reopening the app works.

![Screenshot_20240226-102637](https://github.com/nextcloud/android/assets/96744684/65f8a4fb-905f-473f-908c-6ada613e0e35)

### Expected behaviour

Working with the app with no error logs

### Actual behaviour

Error log as on the screenshot

### Android version

11

### Device brand and model

Moto G 5G

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.0

### Nextcloud server version

27.1.5

### Using a reverse proxy?

I don't know

**Comment by joshtrichards** [comment] 2024-03-26 16:42
Duplicate of #12528

**Closed by joshtrichards** 2024-03-26 16:42 UTC
Labels: bug
