### ISSUE TITLE
version 3.30.1 constantly try to sync all files

### ISSUE THREAD

**Issue by mart-ch** [nextcloud/android#13814] opened 2024-10-18 14:13 UTC
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Hello Team,

Just updated to version 3.30.1 and it immediatly started to sync all folders/files.

Tried to cancel all syncs, deleted local files.
Restarted nextcloud and it syncs again ALL content.
Thats too much for my little phone 🔥

### Expected behaviour

No auto sync of all content

### Actual behaviour

All server files will be synced localy

### Android version

15

### Device brand and model

pixel 6

### Stock or custom OS?

Stock

### Nextcloud android app version

3.30.1

### Nextcloud server version

28.0.9

### Using a reverse proxy?

I don't know

**Comment by joshtrichards** [comment] 2024-10-18 14:18
Duplicate of #13738

**Closed by joshtrichards** 2024-10-18 14:18 UTC
Labels: bug, 0. Needs triage
