### ISSUE TITLE
delayed / scheduled auto-upload

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/android#7815] opened 2021-01-12 22:13 UTC
I've enabled auto-upload for everything (Camera, WhatsApp, Pics & Vids).
Mostly the upload is too fast, to send a pic or a vid with a messenger, mail or similar.
I have to enter the NC-Android-App download the file again. Then I can send it.
A delay for auto-upload would be nice to avoid this.

**Comment by Markerer** [comment] 2021-03-21 07:51
It would be a really useful feature also when you want to edit the image before upload (for e.g. cropping screenshots).

**Comment by zion2k** [comment] 2021-09-19 19:36
> It would be a really useful feature also when you want to edit the image before upload (for e.g. cropping screenshots).

Yep, that's exactly my problem. I often take a screenshot and afterwards I crop it or mark s.th.
Very often I get a sync error with these initial screenshot. Then I can choose if I want to keep the 0 byte file from the phone or the 0 byte file from the server. And even if I choose a file, the error seems to reappear.

**Comment by pedrom38** [comment] 2021-12-01 13:09
+1
Like marki555, if I take multiple photos, sometimes there are bad, so I delete them on my phone. But it's too late, they are already send to nextcloud so I have to do the clean job also on nextcloud.
As my nextcloud is an automated backup, I'd prefer that delay can be adjusted from minutes (even zero) up to hours !
Thanks a lot for the job

**Comment by BatPio** [comment] 2022-12-12 16:53
Hi, I'm trying to implement this feature. The use case I need for myself is the same as in the previous comments. I want to make it as simple as possible with no unnecessary configuration options, but I also want it to be useful to others. I'll try to implement this feature with only one configuration option - relative delay (days/hours/minutes). Anyone need something more? e.g. date range, absolute dates?

**Comment by kangaroo72** [comment] 2022-12-12 21:30
from my point of view, days/hours/minutes would be great. Other Options are a nice to have, but not really important, I think. Thanks.

**Comment by BatPio** [comment] 2023-01-11 19:59
I have the first working version.

I added a simple dialog to pick the delay:
![sync_delay](https://user-images.githubusercontent.com/23415958/211904737-f2b55dbf-bbbb-495e-9bc0-e358c882341d.png)

If anyone wants to test, here is the dev build: https://drive.google.com/file/d/1sAkdAUUWhQ4PZp0kBNS3roDI2Tv30NXS/view?usp=sharing

**Comment by andreapx** [comment] 2023-03-17 16:08
> I added a simple dialog to pick the delay:

Cool! Is the delay relative to every single file? I mean, a 10 minutes delay is valid for the pictures that I take now and the ones I will take the next hours and in the future, or is it a one time thing?

**Comment by netlink128** [comment] 2023-10-14 12:04
OMG! I am waiting for this feature so much! It is a stopper to public my cloud to my relatives and friends.

**Comment by joshtrichards** [comment] 2023-12-11 21:37
Duplicate of #2323.
Not sure the state of the existing PR, but I'll link it to that issue so it doesn't get lost.
I suggest following that issue to track progress.

**Closed by joshtrichards** 2023-12-11 21:37 UTC
Labels: enhancement, feature: auto upload
