### ISSUE TITLE
Vertical mode to landscape mode and backwards end up with a crash

### ISSUE THREAD

**Issue by mucke5** [nextcloud/android#7449] opened 2020-11-23 07:25 UTC
### Steps to reproduce
1. Open specific folder with several files in vertical mode
2. Switch to landscape mode and delete a file
3. Switch to vertical mode

### Expected behaviour
- vertical mode showing the content of the specific folder

### Actual behaviour
- crash log showed up

### Environment data
Android version: 11
Stock or customized system: Stock

#### Web server error log
```
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{91ad985 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: blueline
Model: Pixel 3
Id: RP1A.201105.002
Product: blueline

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 6869500

```

**Comment by AndyScherzinger** [comment] 2020-11-23 09:06
Duplicate of #6905

**Closed by AndyScherzinger** 2020-11-23 09:06 UTC
Labels: bug
