### ISSUE TITLE
1500 photos/videos (40gb) fail to upload on S22+ 512Gb

### ISSUE THREAD

**Issue by privettoli** [nextcloud/android#10807] opened 2022-10-17 06:36 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I have collected 1500 photos & videos for the past month with failed uploads. Now I fixed DNS and the photos began uploading. Every 5-10 mins the app crashes.

### Expected behaviour

The media should upload flowlessly.

### Actual behaviour

It crashes 

### Android version

12

### Device brand and model

Samsung S22+ 512Gb

### Stock or custom OS?

Stock

### Nextcloud android app version

30210290

### Nextcloud server version

24.0.0

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "OkHttp TaskRunner" java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 5237544 free bytes and 5114KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
    at java.util.ArrayList.iterator(ArrayList.java:834)
    at okhttp3.internal.concurrent.TaskRunner.awaitTaskToRun(TaskRunner.kt:168)
    at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:60)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `b0q`
* Model: `SM-S908U1`
* Id: `SP1A.210812.016`
* Product: `b0quew`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `S908U1UES2AVI5`

**Comment by privettoli** [comment] 2022-10-17 06:37
https://github.com/nextcloud/android/issues/10802 seems to be similar

**Comment by ErikParawell-SiFive** [comment] 2022-10-17 19:35
This PR [#10703](https://github.com/nextcloud/android/pull/10730) seems to temporary workaround.

**Comment by StealthBadger747** [comment] 2022-10-17 19:37
This PR [#10703](https://github.com/nextcloud/android/pull/10730) seems to be a temporary workaround.

**Comment by AlvaroBrey** [comment] 2022-11-23 12:07
Duplicate of https://github.com/nextcloud/android/issues/10653

**Closed by AlvaroBrey** 2022-11-23 12:07 UTC
Labels: bug, performance
