### ISSUE TITLE
Crash in Android App 

### ISSUE THREAD

**Issue by farouk-mokrani** [nextcloud/android#8608] opened 2021-06-20 18:31 UTC
Hi,
The app crashed after login screen and we have a screen that contains this error 
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OPPO
Device: OP4C4BL1
Model: CPH1989
Id: QP1A.190711.020
Product: CPH1989

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2021040100

**Comment by tobiasKaminsky** [comment] 2021-06-21 07:28
Duplicate of #8730

**Closed by tobiasKaminsky** 2021-06-21 07:28 UTC
Labels: bug
