### ISSUE TITLE
Removing folders from Automatic upload

### ISSUE THREAD

**Issue by timmersr** [nextcloud/android#3343] opened 2018-12-11 09:36 UTC
I have about 50 folders in my Automatic upload section, and can disable the Automatic upload per folder.

However, I can not remove folders from the Automatic upload section.
Could you create this?

**Comment by AndyScherzinger** [comment] 2018-12-11 09:45
@timmersr please follow up on the discussion in #3263 - at the moment it is not plannedd to have such a feature but you might be able to shed some light on the 50 folders and their content which might clarify your need for such a feature and how an alternative might look like.

Duplicate of #3263

**Closed by AndyScherzinger** 2018-12-11 09:45 UTC
