### ISSUE TITLE
App Error in Android 12

### ISSUE THREAD

**Issue by gerdchen8** [nextcloud/android#10295] opened 2022-05-29 06:47 UTC
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 522640 bytes
    at android.app.ActivityClient.activityStopped(ActivityClient.java:86)
    at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:346)
    at android.os.Looper.loop(Looper.java:475)
    at android.app.ActivityThread.main(ActivityThread.java:7889)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
Caused by: Exception in thread "main" android.os.TransactionTooLargeException: data parcel size 522640 bytes
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(BinderProxy.java:571)
    at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1297)
    at android.app.ActivityClient.activityStopped(ActivityClient.java:83)
    at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:346)
    at android.os.Looper.loop(Looper.java:475)
    at android.app.ActivityThread.main(ActivityThread.java:7889)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `Sony`
* Device: `XQ-BT52`
* Model: `XQ-BT52`
* Id: `62.1.A.0.587`
* Product: `XQ-BT52_EEA`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `062001A000058703746677387`

**Comment by AlvaroBrey** [comment] 2022-05-30 07:41
Duplicate of #9621

**Closed by AlvaroBrey** 2022-05-30 07:41 UTC
Labels: bug

**Comment by ParishMills** [comment] 2022-06-07 18:50
I ran into this same problem. 

THE FIX: I uninstalled the Nextcloud app that I had installed from the Google Play Store, and installed the version on F-Droid. I was then able to login to Nextcloud without any error messages. I know this doesn't solve the problem with the Play Store's version, but it does get us up and running.
