### ISSUE TITLE
Error by changing account

### ISSUE THREAD

**Issue by Alex4eb** [nextcloud/android#4383] opened 2019-08-22 14:49 UTC
************ CAUSE OF ERROR ************

java.lang.ClassCastException: com.owncloud.android.ui.adapter.AccountListAdapter cannot be cast to android.widget.ListAdapter
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity$DialogMultipleAccount.onCreateDialog(ReceiveExternalFilesActivity.java:313)
	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:330)
	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1308)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HONOR
Device: HWCOL
Model: COL-L29
Id: HUAWEICOL-L29
Product: COL-L29RU

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 325C10

**Comment by AndyScherzinger** [comment] 2019-08-22 16:50
Likely to be fixed via #4381

**Comment by tobiasKaminsky** [comment] 2019-08-23 05:16
Yes, this is the cause and #4381 is the fix.
I hoped to release yesterday so that I am faster than bug reports,but drone again ;-)

**Comment by Alex4eb** [comment] 2019-08-23 05:37
Problem with fixed version - when I add second account, first account is
disappearing

пт, 23 авг. 2019 г., 8:17 Tobias Kaminsky <notifications@github.com>:

**Closed** 2019-08-23 05:45 UTC
Labels: bug, pr exists, release candidate

**Comment by tobiasKaminsky** [comment] 2019-08-23 06:10
> when I add second account, first account is disappearing

Please open up new issue, so we can track it better.
