### ISSUE TITLE
Android Client 3.18 Server not available

### ISSUE THREAD

**Issue by UMenter** [nextcloud/android#9599] opened 2021-12-21 20:52 UTC
### Steps to reproduce
1. At some divices (I checked out three) the 3.18.0 is not sycronising.
2. After installing 3.17.1 it is working fine.
3. 

### Expected behaviour
- always syncronising (and sharing) via the App 3.18.0

### Actual behaviour
- A grey bar is showing up and says inside "server not available" in 3.18.0

### Environment data
Android version: 10

Device model: Samsung Galaxy S9+

Stock or customized system:

Nextcloud app version: 3.18.0 not syncronising / 3.17.1 working perfect

Operating system: Linux 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64

Webserver: nginx/1.18.0 (fpm-fcgi)

Database: mysql 10.5.12

PHP version: 8.0.14

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

Nextcloud version: 22.2.3 - 22.2.3.0

https://user-images.githubusercontent.com/96498917/146995371-faa4def1-4535-4a82-bdd2-f5379258df73.jpeg

**Comment by AndyScherzinger** [comment] 2021-12-21 22:43
Hi @UMenter - I guess your username contains a space? This is an issue present in 3.18.0 which will be fixed with the upcoming 3.18.1

**Comment by UMenter** [comment] 2021-12-21 23:44
Yes, and thanks, many other user of our server do have a space in the user
name.

So, just to keep 3.17.1 until 3.18.1 occur.

BR Ulrich

Andy Scherzinger ***@***.***> schrieb am Di., 21. Dez. 2021,
23:43:

**Comment by AlvaroBrey** [comment] 2021-12-22 08:08
Duplicate of #9331

**Closed by AlvaroBrey** 2021-12-22 08:08 UTC
Labels: bug
