### ISSUE TITLE
Media Tab Crashes App when loading media

### ISSUE THREAD

**Issue by townsste** [nextcloud/android#10875] opened 2022-10-21 02:51 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Open nextcloud android app
Select Media Tab
Attempted to scroll and it crashed the app while media attempted to load. 

### Expected behaviour

Should load and display videos and pictures

### Actual behaviour

Crashes after trying to load all my media

### Android version

13

### Device brand and model

Google Pixel 5

### Stock or custom OS?

Stock

### Nextcloud android app version

version 3.22.1

### Nextcloud server version

25.0.0

### Using a reverse proxy?

Yes

### Server error logs

```bash
### Cause of error

Exception in thread "main" java.lang.IllegalStateException: Couldn't read row 702, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetString(Native Method)
    at android.database.CursorWindow.getString(CursorWindow.java:465)
    at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:54)
    at android.database.CursorWrapper.getString(CursorWrapper.java:141)
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:968)
    at com.owncloud.android.datamodel.FileDataStorageManager.getGalleryItems(FileDataStorageManager.java:2241)
    at com.owncloud.android.datamodel.FileDataStorageManager.getAllGalleryItems(FileDataStorageManager.java:2186)
    at com.owncloud.android.ui.preview.PreviewImagePagerAdapter.<init>(PreviewImagePagerAdapter.java:124)
    at com.owncloud.android.ui.preview.PreviewImageActivity.initViewPager(PreviewImageActivity.java:151)
    at com.owncloud.android.ui.preview.PreviewImageActivity.onStart(PreviewImageActivity.java:211)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1510)
    at android.app.Activity.performStart(Activity.java:8315)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3701)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7898)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)



### App information
* ID: `com.nextcloud.client`
* Version: `30220190`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `redfin`
* Model: `Pixel 5`
* Id: `TP1A.221005.002`
* Product: `redfin`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `9012097`
```

**Comment by AlvaroBrey** [comment] 2022-10-21 07:46
Duplicate of #9948

**Closed by AlvaroBrey** 2022-10-21 07:46 UTC
Labels: bug
