### ISSUE TITLE
Auto-Upload does not Work sometimes

### ISSUE THREAD

**Issue by Jebop** [nextcloud/android#8644] opened 2021-06-30 13:35 UTC
It seems as if the Auto-Upload does not syncronise all Files or is inconsitent in what files it synconises. 
I Open, Edit and Save several PDF Files on my Tablet/s but the Auto-Upload does not syncronise all of them after that. 
If i look at the File in the Web interface some of the Files look like i never worked on them while some other Files that i worked on shortly befor/after are syncronised and up to date. 

is there a obvious user error that can lead to that behaviour that im not aware of or is that a bug? 

### Steps to reproduce
1. Set up Auto-Upload for a Specific Folder
2. Open, Edit & Save a PDF File or Multiple Files in that Folder
3. Wait for Auto-Upload to Syncronise the File

### Expected behaviour
- Auto-Upload syncronises all Files that i worked on and all files are up to date.  

### Actual behaviour
- Auto-Upload only syncronises 6 out of 10 Files, sometimes 8/10 and sometimes it works just fine. 

### Environment data
Android version: 9.0 / 8.1.0

Device model: SM-T510 / SM-T580

Nextcloud app version: 3.16.1

Nextcloud server version: 20.0.8

**Comment by WarmChocolateCake** [comment] 2021-07-01 07:05
Maybe you're seeing the same as this: [https://github.com/nextcloud/android/issues/8285](url)

**Comment by zukunft** [comment] 2021-07-16 13:43
I have a similar issue with Nextcloud dev Version 20210709 on a OnePlus 5t with Lineage 15.1. It would be nice, if the app has a "force sync now" button like the desktop app has.

**Comment by thejohnha** [comment] 2021-12-29 13:42
Also experiencing same behavior. PDFs saved to Downloads folder used to auto-upload fine, but no longer. Pixel 6 Pro and Pixel 4a both exhibit same behavior. v3.18.1 client, v23.0.0 server.

**Comment by AlvaroBrey** [comment] 2022-01-03 16:23
Duplicate of #8525

**Closed by AlvaroBrey** 2022-01-03 16:23 UTC
Labels: bug
