### ISSUE TITLE
auto upload > battery saver

### ISSUE THREAD

**Issue by InFuzzz** [nextcloud/android#14215] opened 2024-12-21 21:54 UTC
### Cause of error
```java
Exception in thread "main" android.content.res.Resources$NotFoundException: Resource ID #0x7f0a0420 type #0x12 is not valid
    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2587)
    at android.content.res.Resources.getLayout(Resources.java:1338)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:542)
    at androidx.appcompat.app.AlertController.setupCustomContent(AlertController.java:644)
    at androidx.appcompat.app.AlertController.setupView(AlertController.java:475)
    at androidx.appcompat.app.AlertController.installContent(AlertController.java:233)
    at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:278)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:841)
    at android.app.Dialog.show(Dialog.java:462)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.showPowerCheckDialog(SyncedFoldersActivity.kt:234)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onDisablePowerSaveCheckClicked(SyncedFoldersActivity.kt:218)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onCreateOptionsMenu$lambda$1(SyncedFoldersActivity.kt:211)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.$r8$lambda$q58-_n5tvnvo7t7SwBQVBpaIAdU(Unknown Source:0)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$$ExternalSyntheticLambda4.onMenuItemClick(D8$$SyntheticClass:0)
    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:984)
    at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
    at android.widget.AdapterView.performItemClick(AdapterView.java:376)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1287)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3563)
    at android.widget.AbsListView.onTouchUp(AbsListView.java:4733)
    at android.widget.AbsListView.onTouchEvent(AbsListView.java:4448)
    at android.widget.ListView.onTouchEvent(ListView.java:1709)
    at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:230)
    at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:138)
    at android.view.View.dispatchTouchEvent(View.java:15544)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3310)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2974)
    at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:10733)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
    at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2851)
    at android.view.View.dispatchPointerEvent(View.java:15803)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8153)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7877)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7213)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7270)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7236)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7434)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7244)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7491)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7217)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7270)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7236)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7244)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7217)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10788)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10676)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10632)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10926)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:285)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:335)
    at android.os.Looper.loopOnce(Looper.java:186)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8762)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300690`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `p3q`
* Model: `SM-G998U`
* Id: `TP1A.220624.014`
* Product: `p3qsqw`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `G998USQS9EWI1`

**Comment by joshtrichards** [comment] 2024-12-28 14:46
Duplicate of #13404

**Closed by joshtrichards** 2024-12-28 14:46 UTC
