### ISSUE TITLE
share to Nextcloud from Gallery app doesn't upload (java.lang.IllegalArgumentException: column 'last_modified' does not exist)

### ISSUE THREAD

**Issue by lmamane** [nextcloud/android#7752] opened 2020-12-29 20:52 UTC
1. select one (or more) picture(s) in the Gallery app
2. tap the share button
3. select a directory

### Expected behaviour
- picture(s) should be uploaded to Nextcloud

### Actual behaviour
- no picture is uploaded

### Remarks

Note that share from Gallery to other share service works correctly, as well as share from other app to Nextcloud.

### Can you reproduce this problem on https://try.nextcloud.com?
- yes
### Environment data
Android version: 10

Device model: OnePlus 7 Pro (guacamole)

Stock or customized system: LineageOS 17.1 of 27 December 2020

Nextcloud app version: 3.14.1 (from F-Droid)

Nextcloud server version: 18.0.12

Reverse proxy: no

#### Web server error log
none: no entry in web server error log

#### Nextcloud log (data/nextcloud.log)
none: no entry in web server error log

### Android app logcat
```
12-29 20:43:37.597  1287  2785 I ActivityTaskManager: START u0 {act=android.intent.action.CHOOSER cmp=android/com.android.internal.app.ChooserActivity (has extras)} from uid 10101
12-29 20:43:35.323   893   893 E Layer   : [Surface(name=AppWindowToken{c24cfda token=Token{d1f6fef ActivityRecord{b5634ce u0 com.android.launcher3/.lineage.LineageLauncher t2}}})/@0x979d8b2 - animation-leash#0] No local sync point found
12-29 20:43:37.611  1894  1894 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@b0b0a54
12-29 20:43:37.616  1894  1894 W ChooserActivity: Ignoring intent's EXTRA_TITLE, deprecated in P. You may wish to set a preview title by using EXTRA_TITLE property of the wrapped EXTRA_INTENT.
12-29 20:43:37.645  1894  1894 W ContextImpl: Failed to ensure /data/system/shared_prefs: mkdir failed: EACCES (Permission denied)
12-29 20:43:37.672  1894  1894 W View    : requestLayout() improperly called by android.widget.ListView{6d0e533 VFED..C.. ......ID 0,3120-1440,5830 #10203e5 android:id/resolver_list} during layout: running second layout pass
12-29 20:43:37.724  1894  1894 W View    : requestLayout() improperly called by android.widget.LinearLayout{e1c778b V.E...... ......I. 0,553-1440,553 #1020206 android:id/chooser_action_row} during second layout pass: posting in next frame
12-29 20:43:39.676  1287  6476 I ActivityTaskManager: START u0 {flg=0x3000000 cmp=com.android.systemui/.chooser.ChooserActivity (has extras)} from uid 1000
12-29 20:43:39.699  1898  1898 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@e4cd1b5
12-29 20:43:39.708  1287  6476 I ActivityTaskManager: START u0 {act=android.intent.action.SEND typ=image/* flg=0xb080001 cmp=com.nextcloud.client/com.owncloud.android.ui.activity.ReceiveExternalFilesActivity clip={image/* U:content://media/external/images/media/446} (has extras)} from uid 10101
12-29 20:43:39.728  4790  4790 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@2ee39ab
12-29 20:43:39.763  2235  2235 D ImageWallpaper: wallpaper visibility changes to: true
12-29 20:43:39.767  4790  4790 D ReceiveExternalFilesActivity: onCreate(Bundle) starting
12-29 20:43:39.780  4790  4790 D ReceiveExternalFilesActivity: onStart() starting
12-29 20:43:39.797  4790  6732 D ExternalLinks: links disabled
12-29 20:43:39.809  4790  4790 D ReceiveExternalFilesActivity: Populating view with content of : /
12-29 20:43:39.833  4790  6011 W System  : A resource failed to call close. 
12-29 20:43:39.847  3286  5995 D NfcService: applyRouting enter
12-29 20:43:39.862  3286  3469 E libnfc_nci: [ERROR:NativeNfcManager.cpp(1509)] nfaConnectionCallback: unknown event ????
12-29 20:43:39.862   782   782 D vendor.nxp.nxpnfc@1.0-impl: ioctl: enter
12-29 20:43:39.862   782   782 D vendor.nxp.nxpnfc@1.0-impl: ioctl: exit
12-29 20:43:39.862  3286  3469 E libnfc_nci: [ERROR:NativeNfcManager.cpp(1509)] nfaConnectionCallback: unknown event ????
12-29 20:43:39.909  4790  4790 D ReceiveExternalFilesActivity: onResume() starting
12-29 20:43:39.910  3286  5995 D NfcService: applyRouting enter
12-29 20:43:39.911  3286  5995 D NfcService: Discovery configuration equal, not updating.
12-29 20:43:39.913  4790  4790 W DrawerActivity: setDrawerMenuItemChecked has been called with invalid menu-item-ID
12-29 20:43:39.958  4790  4790 D FileActivity: Operations service connected
12-29 20:43:39.965  4790  4790 W extcloud.clien: Accessing hidden field Landroid/widget/TextView;->mCursorDrawableRes:I (greylist-max-p, reflection, denied)
12-29 20:43:39.965  4790  4790 W extcloud.clien: Accessing hidden field Landroid/widget/Editor;->mSelectHandleLeft:Landroid/graphics/drawable/Drawable; (greylist-max-p, reflection, denied)
12-29 20:43:39.965  4790  4790 E ThemeUtils: Error setting TextView handles color
12-29 20:43:39.965  4790  4790 E ThemeUtils: java.lang.NoSuchFieldException: No field mSelectHandleLeft in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes3.dex)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at java.lang.Class.getDeclaredField(Native Method)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at com.owncloud.android.utils.ThemeUtils.setTextViewHandlesColor(ThemeUtils.java:838)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at com.owncloud.android.utils.ThemeUtils.setEditTextColor(ThemeUtils.java:588)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at com.owncloud.android.utils.ThemeUtils.themeSearchView(ThemeUtils.java:601)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onCreateOptionsMenu(ReceiveExternalFilesActivity.java:1042)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at android.app.Activity.onCreatePanelMenu(Activity.java:4092)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:324)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3070)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at android.os.Handler.handleCallback(Handler.java:883)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at android.os.Looper.loop(Looper.java:214)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at java.lang.reflect.Method.invoke(Native Method)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
12-29 20:43:39.965  4790  4790 E ThemeUtils: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
12-29 20:43:40.354  2235  2235 D ImageWallpaper: wallpaper visibility changes to: false
12-29 20:43:40.391  1893  1893 V StateManager: saveState
12-29 20:43:40.391  1893  1893 V StateManager: saveState class com.android.gallery3d.app.TimeLinePage
12-29 20:43:40.391  1893  1893 V StateManager: saveState class com.android.gallery3d.app.SinglePhotoPage
12-29 20:43:46.118  4790  4790 D ReceiveExternalFilesActivity: Populating view with content of : /
12-29 20:43:46.154  4790  6028 D OpenGLRenderer: endAllActiveAnimators on 0x6fc722ed00 (MaterialCardView) with handle 0x6fded8a300
12-29 20:43:46.161  4790  4790 W extcloud.clien: Accessing hidden field Landroid/widget/TextView;->mCursorDrawableRes:I (greylist-max-p, reflection, denied)
12-29 20:43:46.161  4790  4790 W extcloud.clien: Accessing hidden field Landroid/widget/Editor;->mSelectHandleLeft:Landroid/graphics/drawable/Drawable; (greylist-max-p, reflection, denied)
12-29 20:43:46.162  4790  4790 E ThemeUtils: Error setting TextView handles color
12-29 20:43:46.162  4790  4790 E ThemeUtils: java.lang.NoSuchFieldException: No field mSelectHandleLeft in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes3.dex)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at java.lang.Class.getDeclaredField(Native Method)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at com.owncloud.android.utils.ThemeUtils.setTextViewHandlesColor(ThemeUtils.java:838)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at com.owncloud.android.utils.ThemeUtils.setEditTextColor(ThemeUtils.java:588)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at com.owncloud.android.utils.ThemeUtils.themeSearchView(ThemeUtils.java:601)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onCreateOptionsMenu(ReceiveExternalFilesActivity.java:1042)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at android.app.Activity.onCreatePanelMenu(Activity.java:4092)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:324)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3070)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at android.view.Choreographer.doFrame(Choreographer.java:722)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at android.os.Handler.handleCallback(Handler.java:883)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at android.os.Looper.loop(Looper.java:214)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at java.lang.reflect.Method.invoke(Native Method)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
12-29 20:43:46.162  4790  4790 E ThemeUtils: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
12-29 20:43:48.225  4790  4790 D ReceiveExternalFilesActivity: Uploading file to dir /
12-29 20:43:48.241  4790  4790 D FileActivity: show loading dialog
12-29 20:43:48.269  4790  6205 E CopyAndUploadContentUrisTask: Exception while copying content://media/external/images/media/446 to temporary file
12-29 20:43:48.269  4790  6205 E CopyAndUploadContentUrisTask: java.lang.IllegalArgumentException: column 'last_modified' does not exist. Available columns: [instance_id, duration, description, picasa_id, latitude, orientation, height, is_drm, bucket_display_name, owner_package_name, volume_name, date_modified, date_expires, _display_name, datetaken, mime_type, _id, _data, _hash, _size, title, width, longitude, is_trashed, group_id, document_id, is_pending, date_added, mini_thumb_magic, primary_directory, secondary_directory, isprivate, original_document_id, bucket_id, relative_path]
12-29 20:43:48.269  4790  6205 E CopyAndUploadContentUrisTask: 	at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:352)
12-29 20:43:48.269  4790  6205 E CopyAndUploadContentUrisTask: 	at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:91)
12-29 20:43:48.269  4790  6205 E CopyAndUploadContentUrisTask: 	at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:156)
12-29 20:43:48.269  4790  6205 E CopyAndUploadContentUrisTask: 	at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:49)
12-29 20:43:48.269  4790  6205 E CopyAndUploadContentUrisTask: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
12-29 20:43:48.269  4790  6205 E CopyAndUploadContentUrisTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-29 20:43:48.269  4790  6205 E CopyAndUploadContentUrisTask: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
12-29 20:43:48.269  4790  6205 E CopyAndUploadContentUrisTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-29 20:43:48.269  4790  6205 E CopyAndUploadContentUrisTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-29 20:43:48.269  4790  6205 E CopyAndUploadContentUrisTask: 	at java.lang.Thread.run(Thread.java:919)
12-29 20:43:48.292  4790  4790 D FileActivity: dismiss loading dialog
12-29 20:43:48.301  1287  1314 W ActivityTaskManager: Finishing task with all activities already finished
12-29 20:43:48.301  1287  1314 W ActivityTaskManager: Duplicate finish request for ActivityRecord{de7af4b u0 com.nextcloud.client/com.owncloud.android.ui.activity.ReceiveExternalFilesActivity t21 f}
```

**Comment by R0Wi** [comment] 2020-12-30 10:43
I think this is a duplicate of https://github.com/nextcloud/android/issues/7617 and https://github.com/nextcloud/android/issues/7587 which should be fixed by https://github.com/nextcloud/android/pull/7649 with the next release. Correct me if i'm wrong @AndyScherzinger @ezaquarii ? I think this can be closed then ...

**Comment by ezaquarii** [comment] 2020-12-30 10:44
@R0Wi yes this is a duplicate.

**Closed** 2020-12-30 10:45 UTC
Labels: bug

**Comment by lmamane** [comment] 2020-12-30 12:53
Ah, sorry for the duplicate, I looked for "gallery" in the open issues, so I missed "picture" in ... the closed issues.
