### ISSUE TITLE
Odd behaviour when setting up "Auto upload"

### ISSUE THREAD

**Issue by zell-mbc** [nextcloud/android#10130] opened 2022-04-29 09:59 UTC
For context, I wanted to document how to best use Nextcloud as a backup location for my own app and ran into some confusing behaviour with the Nextcloud App. Given that this issue will apply to any document/folder no matter how it's created I thought I'd open this bug.

### Steps to reproduce
Nextcloud Server
1. Create a remote folder to receive the file(s) for auto upload, to match the screenshots, Documents/MedilogBackup

Android phone
1. Create a local folder of your choice, e.g. Documents/MedilogBackup with an Android file manager
![image](https://user-images.githubusercontent.com/29018767/165921311-639acccb-75a7-401f-a3c1-24736e7f6abe.png)

3. Open Nextcloud client
4. Settings
5. Auto Upload
6. Set up a custom folder, 3 dots menu upper right hand corner
7. Select local folder
![image](https://user-images.githubusercontent.com/29018767/165921579-3e853f7c-efc0-44bd-b1c1-083abeaec0f5.png)

9. Select remote folder
-> My expectation would be that when the desired folder is checked as shown in the picture that it's selected folder which gets used as local folder. But after saving it turns out the top level folder "Documents/" is used instead of "Documents/MedilogBackup"

Next attempt, delete the folder sync created just now and start all over but navigate into the Documents/MedilogBackup folder in step 6
-> The NC client reports that there are 0 files in this folder which is not correct because a ZIP file does exist. And it's somehow not possible to select this folder, "Choose" won't do anything.
![image](https://user-images.githubusercontent.com/29018767/165921984-25719b0e-babe-42a9-9f51-380ca271110a.png)

Next attempt, create another subfolder in Documents/MedilogBackup/NewFolder
Repeat all steps up to 6, navigate into Documents/MedilogBackup/ and it's now possible to chose Documents/MedilogBackup/ as source folder. The file which was in that folder but not visible get's synced fine.
![image](https://user-images.githubusercontent.com/29018767/165922228-4385bfaf-8f91-49d9-bda0-4e560643040a.png)

Delete Documents/MedilogBackup/NewFolder as it's not required any longer after things are set up.
### Expected behaviour
- I would have expected that ticking the box while choosing the local folder would select that folder and not the parent folder (1st attempt)
- I would have expected to be able to choose the folder once navigated into, no matter if it's empty or not. (2nd attempt)
- The ZIP file not showing is a minor issue, maybe due to access rights(?), but it gets synched fine so it may be something else.

### Environment data
Android version:

Device model: 
OnePlus 8 Pro
Android 11

Stock or customized system:
Stock

Nextcloud app version:
3.19.1 / F-Droid
Nextcloud server version:
23.0.3

Reverse proxy:
Nginx

**Comment by AlvaroBrey** [comment] 2022-04-29 10:04
Duplicate of #8940, will be fixed on next release.

The ZIP not showing is intended, as only folders show up when trying to select folders. However I agree that in this mode, the message "No files here" is probably confusing, and should instead show something like "Tap Select to choose this folder".

**Closed by AlvaroBrey** 2022-04-29 10:04 UTC
Labels: bug
