### ISSUE TITLE
Nextcloud crashes on initial startup

### ISSUE THREAD

**Issue by mrfrankly** [nextcloud/android#11390] opened 2023-02-15 23:00 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Install from playstore
Enter url to filerun server
Acknowledge prompts etc

### Expected behaviour

Successfully logged into Nextcloud with @home folder displayed.

### Actual behaviour

After briefly being shown this page :
![Screenshot_20230216-055324392](https://user-images.githubusercontent.com/100745765/219179174-e16dd28c-1988-4507-aa39-c98cbeeeac2e.jpg)

The following crash report is displayed:
### Cause of error
```java
Exception in thread "Thread-8" java.lang.StringIndexOutOfBoundsException: begin 0, end 8, length 5
    at java.lang.String.checkBoundsBeginEnd(String.java:3942)
    at java.lang.String.substring(String.java:2467)
    at com.owncloud.android.datamodel.OCFile.getLocalId(OCFile.java:606)
    at com.owncloud.android.datamodel.FileDataStorageManager.createContentValuesBase(FileDataStorageManager.java:461)
    at com.owncloud.android.datamodel.FileDataStorageManager.createContentValuesForFolder(FileDataStorageManager.java:478)
    at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:392)
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:538)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:409)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:239)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240090`
* Build flavor: `gplay`

### Device information
* Brand: `asus`
* Device: `ASUS_I006D`
* Model: `ASUS_I006D`
* Id: `TKQ1.220807.001`
* Product: `WW_I006D`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `33.0210.0210.210`

### Android version

13

### Device brand and model

Asus ZenFone 8

### Stock or custom OS?

Stock

### Nextcloud android app version

30240090

### Nextcloud server version

Filerun running in Unraid docker

### Using a reverse proxy?

Yes

### Android logs

The is no data folder at this location

**Comment by AlvaroBrey** [comment] 2023-02-16 08:16
Duplicate of #11389

**Closed by AlvaroBrey** 2023-02-16 08:16 UTC
Labels: bug
