### ISSUE TITLE
No Thumbnails shown in Auto Upload dialogue

### ISSUE THREAD

**Issue by boldt** [nextcloud/android#671] opened 2017-02-20 19:11 UTC
### Actual behaviour

- I cannot see Thumbnails in the Auto Uplaod dialogue.

![screenshot_20170220-200213](https://cloud.githubusercontent.com/assets/750793/23138601/9f5f72b0-f7a8-11e6-865b-d91c14af4c0a.png)

### Expected behaviour

- See Thumbnais in the Auto Uplaod dialogue.
 
### Environment data

Android version: 7.0
Device model: Xperia Z5
Stock or customized system: Default from Sony
Nextcloud app version: 1.4.1
Nextcloud server version: 10.0.1

**Comment by tobiasKaminsky** [comment] 2017-02-20 19:20
@AndyScherzinger I also experienced this from time to time. Then it helped to turn the device to force a refresh...?

**Comment by boldt** [comment] 2017-02-20 19:30
Turning the device doesn't help for me.

**Comment by AndyScherzinger** [comment] 2017-02-20 22:28
@boldt is it like that all the time or just from time to time?

**Comment by boldt** [comment] 2017-02-20 23:01
With 1.4.1 it was all the time. I never saw a thumbnail. 
Now I have 1.4.2 RC1 installed (from #656), and I do have thumbnails now.

**Comment by AndyScherzinger** [comment] 2017-02-21 14:43
@boldt That is quite strange since the code for finding and displaying the thumbnails in the auto upload view hasn't been changed at all...

**Comment by OlivierS1** [comment] 2017-02-22 00:38
I experienced this issue and cretaed a ticket back then #511 .
If you leave it for a while it should eventually update the thumbnails.
I had also this issue when my server was down.

**Comment by boldt** [comment] 2017-02-22 08:30
The main thing I changed was to disable the brute force detection, since it made my login/uploads slow/failing (30s). Maybe it's somehow related to the thumbnail generation, since @OliverS1 had this issue while his server was down.

**Comment by AndyScherzinger** [comment] 2017-02-23 17:26
> I had also this issue when my server was down.

The reason for is likely because before the thumbnails get loaded from the device we load the avatar images from the server...
It is definitely not related to a thumbnail generation since that is on the server. The files you see here are on the client only.

**Comment by tobiasKaminsky** [comment] 2017-02-23 20:27
Shouldn't this be both two async task that are independent?

**Comment by AndyScherzinger** [comment] 2017-02-23 20:51
Imho yes, was just an idea for the possible cause.

**Comment by tobiasKaminsky** [comment] 2017-03-01 09:05
Can you have a look into this the next few days?

**Comment by AndyScherzinger** [comment] 2017-03-01 09:47
I'll try, yes!

**Comment by tobiasKaminsky** [comment] 2017-04-21 06:45
@AndyScherzinger ping ;-)

**Comment by AndyScherzinger** [comment] 2017-04-21 10:49
@tobiasKaminsky my impression is that it is related to the drawer... If the avatars and the quota fetching is blocked or waiting for an answer the thumbnails fetching even though it's local doesn't get started :/

**Comment by tobiasKaminsky** [comment] 2017-04-21 11:44
This should be both in async tasks, or?

**Comment by tobiasKaminsky** [comment] 2017-05-15 13:24
I cannot reliable reproduce it...So I do not have any idea how to fit it.

**Comment by tobiasKaminsky** [comment] 2017-06-21 12:38
I tried it again:
- clear cache to have no thumbnails
- turn on flight mode
- access "auto upload" 
- see that pictures are generated 
This was tested on emulator and on s5 neo with android 6.0.1

**Comment by tobiasKaminsky** [comment] 2017-06-21 13:17
> https://developer.android.com/reference/android/os/AsyncTask.html
Order of execution: 
Starting with HONEYCOMB, tasks are executed on a single thread to avoid common application errors caused by parallel execution.

So if any other async task is blocking it will also block the generation of the thumbnails.
With this I finally could reproduce it :tada: 

- enable bruteforce and force it to a delay of 30s
- update a folder to get some async tasks in queue 
- open auto upload view
- thumbnails will be created once all other async tasks are finished

**Comment by tobiasKaminsky** [comment] 2017-06-21 13:27
The solution I see is to cancel all async tasks once we exit an activity, eg. switch from FileDisplayActivity to FolderSyncActivity.

@mario @AndyScherzinger

**Comment by tobiasKaminsky** [comment] 2017-06-28 12:51
PR might be #1149

**Comment by tobiasKaminsky** [comment] 2017-12-20 14:07
#1149 is merged, closing.
Please respond or re-open if it happens again.

**Closed by tobiasKaminsky** 2017-12-20 14:07 UTC
Labels: bug, pr exists
