### ISSUE TITLE
change hostname of the Server for an specific account

### ISSUE THREAD

**Issue by PascalHeynmoeller** [nextcloud/android#11308] opened 2023-01-27 08:52 UTC
### Is your feature request related to a problem? Please describe.
After an update of my router which switchted from an letsencrypt protected topleveldomain to an full qualified domain name (hostname added), I can't change the fqdn in the account settings of the app to match the new name.
### Describe the solution you'd like
Make the hostname of the server for an specific account in the Nextcloud app editable (like in SFOS or by settings editor in thunderbird).
### Describe alternatives you've considered
The alternative is to add an new profile with the new fqdn and syncronize 100GB again?
### Additional context
AVM Fritz!Box routers now supports multiple hosts with Letsencrypt so using an fqdn with hostname instead of topleveldomain only is now how the router works.
I will clone this feature request for the desktop client also.

**Comment by AlvaroBrey** [comment] 2023-01-27 09:36
Duplicate of #4157

**Closed by AlvaroBrey** 2023-01-27 09:36 UTC
Labels: enhancement
