### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by lemmy04** [nextcloud/android#4674] opened 2019-10-13 09:32 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: android.database.SQLException: ERROR content://org.nextcloud/file
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
 at android.app.ActivityThread.-wrap11(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
 at android.os.Handler.dispatchMessage(Handler.java:105)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6938)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: android.database.SQLException: ERROR content://org.nextcloud/file
 at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:280)
 at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:248)
 at android.content.ContentProvider$Transport.insert(ContentProvider.java:269)
 at android.content.ContentResolver.insert(ContentResolver.java:1545)
 at com.owncloud.android.datamodel.FileDataStorageManager.saveFile(FileDataStorageManager.java:245)
 at com.owncloud.android.datamodel.FileDataStorageManager.createRootDir(FileDataStorageManager.java:888)
 at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:109)
 at com.owncloud.android.ui.activity.FileDisplayActivity.onAccountSet(FileDisplayActivity.java:450)
 at com.owncloud.android.ui.activity.BaseActivity.onStart(BaseActivity.java:197)
 at com.owncloud.android.ui.activity.DrawerActivity.onStart(DrawerActivity.java:1414)
 at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:207)
 at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2632)
 at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
 at android.app.Activity.performStart(Activity.java:7200)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2918)
 ... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: dream2lte
Model: SM-G955F
Id: R16NW
Product: dream2ltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G955FXXU4CRI5

**Comment by lemmy04** [comment] 2019-11-10 10:42
The request did not receive any update in the last 4 weeks *because not one of the developers has acknowledged it*

**Comment by AndyScherzinger** [comment] 2019-11-13 16:27
and can be closed since it is a duplicate of #4559

**Closed by AndyScherzinger** 2019-11-13 16:27 UTC
Labels: bug

**Comment by lemmy04** [comment] 2019-11-13 17:16
> and can be closed since it is a duplicate of #4559

that's at least something.

**Comment by AndyScherzinger** [comment] 2019-11-13 20:24
Sorry for not having much time recently to dig into things. Hope @tobiasKaminsky or @ezaquarii may find the time to do so.

**Comment by lemmy04** [comment] 2019-11-13 21:29
might be worth a thought to turn off that "stale" bot, if you guys are so busy... or at least configure it for a much longer wait time.
