### ISSUE TITLE
Nextcloud App aborts Autoupload

### ISSUE THREAD

**Issue by Kletzen** [nextcloud/android#10778] opened 2022-10-04 16:39 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Installed Nextcloud App
Specified local and remote folders for autoupload
Upload Not succesful, see Error report

### Expected behaviour

Upload should start

### Actual behaviour

Upload does Not start

### Android version

8.1

### Device brand and model

AGM x3

### Stock or custom OS?

Stock

### Nextcloud android app version

30210290

### Nextcloud server version

Unknown

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to start service com.owncloud.android.files.services.FileUploader@e773038 with Intent { cmp=com.nextcloud.client/com.owncloud.android.files.services.FileUploader (has extras) }: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3495)
    at android.app.ActivityThread.-wrap20(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6527)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: Exception in thread "main" android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
    at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
    at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:735)
    at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
    at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
    at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1653)
    at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1599)
    at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:677)
    at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:650)
    at android.content.ContentProvider$Transport.update(ContentProvider.java:439)
    at android.content.ContentResolver.update(ContentResolver.java:1675)
    at com.owncloud.android.datamodel.UploadsStorageManager.updateUpload(UploadsStorageManager.java:131)
    at com.owncloud.android.files.services.FileUploader.retryUploads(FileUploader.java:562)
    at com.owncloud.android.files.services.FileUploader.onStartCommand(FileUploader.java:344)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3478)
    at android.app.ActivityThread.-wrap20(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6527)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210290`
* Build flavor: `gplay`

### Device information
* Brand: `AGM`
* Device: `T91EUE1`
* Model: `AGM X3`
* Id: `OPM1.171019.026`
* Product: `T91EU`

### Firmware
* SDK: `27`
* Release: `8.1.0`
* Incremental: `T91_4.4.1`

**Comment by avinashyadav0027** [comment] 2022-10-05 12:08
I would like to work on this. Can you assign me?

**Comment by AlvaroBrey** [comment] 2022-10-05 13:20
> I would like to work on this. Can you assign me?

Hello @avinashyadav0027 , if you want to work on this feel free to do so, comment here with your findings or open a PR directly if you  have code to contribute. We generally don't assign issues to users outside our organization.

**Comment by joshtrichards** [comment] 2023-10-08 02:00
Duplicate of #8569

**Closed by joshtrichards** 2023-10-08 02:00 UTC
Labels: bug
