### ISSUE TITLE
Couldn't read row ... Make sure the Cursor is initialized at `getFolderContent` via `swapDirectory`

### ISSUE THREAD

**Issue by kylinlau** [nextcloud/android#13022] opened 2024-05-20 05:11 UTC
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Couldn't read row 561, col 20 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetLong(Native Method)
    at android.database.CursorWindow.getLong(CursorWindow.java:539)
    at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:78)
    at com.nextcloud.client.database.dao.FileDao_Impl.getFolderContent(FileDao_Impl.java:2025)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:917)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:225)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:733)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1327)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1292)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1281)
    at com.owncloud.android.ui.activity.FileDisplayActivity.updateListOfFilesFragment(FileDisplayActivity.java:651)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoveFileOperationFinish(FileDisplayActivity.java:1668)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1610)
    at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:786)
    at com.owncloud.android.services.OperationsService$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:224)
    at android.os.Looper.loop(Looper.java:318)
    at android.app.ActivityThread.main(ActivityThread.java:8747)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290090`
* Build flavor: `gplay`

### Device information
* Brand: `Redmi`
* Device: `sky`
* Model: `23076RA4BC`
* Id: `UKQ1.230917.001`
* Product: `sky`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `V816.0.5.0.UMWCNXM`

**Comment by joshtrichards** [comment] 2024-08-30 23:00
Duplicate of #13339

**Closed by joshtrichards** 2024-08-30 23:00 UTC
Labels: bug, performance: ISE/IAE :confused:, stable-3.29
