### ISSUE TITLE
app crashes while syncinc

### ISSUE THREAD

**Issue by tpapp** [nextcloud/android#6124] opened 2020-05-21 10:51 UTC
### Steps to reproduce

This is not a reproducer, I suspect that something is specific to my setup. However, nothing on the server was changed when this started happening, maybe the app was auto-updated by Android.

1. open Nextcloud app
2. wait for it to sync (with my local server), the little tickmarks at the top are moving
3. crash happens (see backtrace below)

Also, using any of the menu buttons (hamburger button, settings) just freezes the app (w/o the backtrace message below).

### Expected behaviour

- It should sync normally.

### Actual behaviour

- The app crashes with
```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 1156, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:538)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:180)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:135)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:185)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:135)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:185)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:135)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:185)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:135)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:115)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:299)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:671)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:319)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:474)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1629)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:407)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:478)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:369)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:228)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:357)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: daisy_sprout
Model: Mi A2 Lite
Id: PKQ1.180917.001
Product: daisy

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V10.0.20.0.PDLMIXM
```

### Can you reproduce this problem on https://try.nextcloud.com?

- If not, please verify server setup and ask for help on forum

I cannot change any settings in the app since it just freezes if I touch any of the buttons.

### Environment data

Android version: see above

Device model: see above

Stock or customized system: stock

Nextcloud app version: 3.11.1

Nextcloud server version: 18.0.4

Reverse proxy: none

#### Web server error log

This is the log from a minute before I open the app until the crash; I removed access by other users; no error messages.
```
46.139.70.254 - tamas [21/May/2020:10:43:56 +0000] "PROPFIND /nextcloud/remote.php/dav/files/tamas/ HTTP/1.1" 207 4951 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)"
46.139.70.254 - tamas [21/May/2020:10:44:05 +0000] "PROPFIND /nextcloud/remote.php/dav/files/tamas/ HTTP/1.1" 207 4952 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)"
46.139.70.254 - - [21/May/2020:10:44:20 +0000] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1505 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
46.139.70.254 - tamas [21/May/2020:10:44:26 +0000] "PROPFIND /nextcloud/remote.php/dav/files/tamas/ HTTP/1.1" 207 4951 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)"
46.139.70.254 - tamas [21/May/2020:10:44:26 +0000] "GET /nextcloud/ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 1897 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.1"
46.139.70.254 - tamas [21/May/2020:10:44:26 +0000] "GET /nextcloud/ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 1897 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.1"
46.139.70.254 - tamas [21/May/2020:10:44:27 +0000] "GET /nextcloud/status.php HTTP/1.1" 200 1113 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.1"
46.139.70.254 - tamas [21/May/2020:10:44:27 +0000] "GET /nextcloud/ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 3505 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.1"
46.139.70.254 - tamas [21/May/2020:10:44:27 +0000] "GET /nextcloud/ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 1349 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.1"
46.139.70.254 - tamas [21/May/2020:10:44:27 +0000] "PROPFIND /nextcloud/remote.php/webdav/ HTTP/1.1" 207 1522 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.1"
46.139.70.254 - tamas [21/May/2020:10:44:28 +0000] "PROPFIND /nextcloud/remote.php/webdav/ HTTP/1.1" 207 14666 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.1"
46.139.70.254 - tamas [21/May/2020:10:44:38 +0000] "PROPFIND /nextcloud/remote.php/dav/files/tamas/ HTTP/1.1" 207 4952 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)"
46.139.70.254 - - [21/May/2020:10:44:50 +0000] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1505 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
46.139.70.254 - tamas [21/May/2020:10:44:56 +0000] "PROPFIND /nextcloud/remote.php/dav/files/tamas/ HTTP/1.1" 207 4951 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)"
46.139.70.254 - tamas [21/May/2020:10:45:09 +0000] "PROPFIND /nextcloud/remote.php/dav/files/tamas/ HTTP/1.1" 207 4952 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)"
46.139.70.254 - - [21/May/2020:10:45:20 +0000] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1505 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
46.139.70.254 - tamas [21/May/2020:10:45:26 +0000] "PROPFIND /nextcloud/remote.php/dav/files/tamas/ HTTP/1.1" 207 4951 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)"
46.139.70.254 - tamas [21/May/2020:10:45:41 +0000] "PROPFIND /nextcloud/remote.php/dav/files/tamas/ HTTP/1.1" 207 4952 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)"
46.139.70.254 - - [21/May/2020:10:45:50 +0000] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1505 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
46.139.70.254 - tamas [21/May/2020:10:45:56 +0000] "PROPFIND /nextcloud/remote.php/dav/files/tamas/ HTTP/1.1" 207 4951 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)"
46.139.70.254 - tamas [21/May/2020:10:45:57 +0000] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications?format=json HTTP/1.1" 304 267 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)"
46.139.70.254 - tamas [21/May/2020:10:46:13 +0000] "PROPFIND /nextcloud/remote.php/dav/files/tamas/ HTTP/1.1" 207 4952 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)"
46.139.70.254 - - [21/May/2020:10:46:20 +0000] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1505 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
46.139.70.254 - tamas [21/May/2020:10:46:26 +0000] "PROPFIND /nextcloud/remote.php/dav/files/tamas/ HTTP/1.1" 207 4951 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)"
46.139.70.254 - tamas [21/May/2020:10:46:45 +0000] "PROPFIND /nextcloud/remote.php/dav/files/tamas/ HTTP/1.1" 207 4952 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)"
46.139.70.254 - - [21/May/2020:10:46:50 +0000] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1505 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
46.139.70.254 - tamas [21/May/2020:10:46:56 +0000] "PROPFIND /nextcloud/remote.php/dav/files/tamas/ HTTP/1.1" 207 4951 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)"
46.139.70.254 - tamas [21/May/2020:10:47:17 +0000] "PROPFIND /nextcloud/remote.php/dav/files/tamas/ HTTP/1.1" 207 4952 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)"
46.139.70.254 - - [21/May/2020:10:47:20 +0000] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1505 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
```

#### Nextcloud log (data/nextcloud.log)

There are no messages in the log when this crash happens. I can increase the debug level to generate some if needed.

**Comment by tpapp** [comment] 2020-05-21 14:42
I installed the Nextcloud dev from F-droid (20190316) and it works fine.

Then I upgraded to 20200513 from F-droid it is fine too.

So this may be a dup of a bug that has been fixed (could not find anything though). In any case, I am unfamiliar with the Android SDK but I would be happy to invest in learning to build the Nextcloud App if any kind of bisection would make sense.

**Comment by tobiasKaminsky** [comment] 2020-05-22 06:12
Duplicate of #6103

**Closed** 2020-05-22 08:13 UTC
Labels: bug
