### ISSUE TITLE
Android app keeps crashing after updating server to version 30.0.2

### ISSUE THREAD

**Issue by mmattq** [nextcloud/android#14174] opened 2024-12-12 23:55 UTC
### Cause of error
```java
Exception in thread "Syncfolder thread" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getEtag()' on a null object reference
    at com.owncloud.android.operations.SynchronizeFolderOperation.checkForChanges(SynchronizeFolderOperation.java:172)
    at com.owncloud.android.operations.SynchronizeFolderOperation.run(SynchronizeFolderOperation.java:131)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
    at com.owncloud.android.services.SyncFolderHandler.doOperation(SyncFolderHandler.java:106)
    at com.owncloud.android.services.SyncFolderHandler.handleMessage(SyncFolderHandler.java:79)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loopOnce(Looper.java:238)
    at android.os.Looper.loop(Looper.java:357)
    at android.os.HandlerThread.run(HandlerThread.java:85)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300690`
* Build flavor: `generic`

### Device information
* Brand: `motorola`
* Device: `pstar`
* Model: `motorola edge 20 pro`
* Id: `T1RAS33.55-15-10-6`
* Product: `pstar_retaile`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `2b5db-18379`

**Comment by joshtrichards** [comment] 2024-12-28 15:13
Duplicate of #13784

**Closed by joshtrichards** 2024-12-28 15:13 UTC
Labels: 0. Needs triage
