### ISSUE TITLE
Concurrent Uploads

### ISSUE THREAD

**Issue by SuperApollo** [nextcloud/android#8257] opened 2021-04-09 09:19 UTC
- 安卓客户端上传问价貌似是单线程的，每次只能上传一个文件，而iOS客户端是可以5个文件同时上传，速度快很多
- 希望安卓客户端能够像iOS那样并发上传文件，提升效率

**Comment by AndyScherzinger** [comment] 2021-04-09 10:10
Hi @SuperApollo please post any issue/ticket in English. Thanks for your efforts! ❤️

**Comment by sirliu** [comment] 2021-04-22 15:06
> Hi @SuperApollo please post any issue/ticket in English. Thanks for your efforts! ❤️

He said hope the Android NextCloud client support Concurrent uploading which the iOS client already supported，so do I。Hope you can understand my poor English。

**Comment by AndyScherzinger** [comment] 2021-04-22 15:51
Perfect, thanks @sirliu ❤️

**Comment by szaimen** [comment] 2021-04-22 23:04
Duplicate of https://github.com/nextcloud/android/issues/6794

**Closed by szaimen** 2021-04-22 23:04 UTC
Labels: enhancement
