### ISSUE TITLE
Nextcloud widget crashing when being created

### ISSUE THREAD

**Issue by hoymccoy** [nextcloud/android#12955] opened 2024-04-30 23:31 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Try to add the Nextcloud widget to your Android screen.

### Expected behaviour

The widget will be added to the screen and work properly

### Actual behaviour

The widget is not added to the screen, crashing instead.

### Android version

14

### Device brand and model

Samsung S21 FE

### Stock or custom OS?

Stock

### Nextcloud android app version

30290090

### Nextcloud server version

28.0.5

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "DefaultDispatcher-worker-1" java.lang.RuntimeException: Accessing result data after operation failed!
    at com.owncloud.android.lib.common.operations.RemoteOperationResult.getResultData(RemoteOperationResult.java:489)
    at com.nextcloud.client.widget.DashboardWidgetConfigurationActivity$loadWidgets$1$2.invokeSuspend(DashboardWidgetConfigurationActivity.kt:166)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8893)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `r9q`
* Model: `SM-G990B`
* Id: `UP1A.231005.007`
* Product: `r9qxeea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `G990BXXS7FXD2`

**Comment by joshtrichards** [comment] 2024-06-13 14:17
Duplicate of #12948

**Closed by joshtrichards** 2024-06-13 14:17 UTC
Labels: bug
