### ISSUE TITLE
external-storage with "save credentials in session" and configured ldap-integration fails

### ISSUE THREAD

**Issue by selfisch** [nextcloud/android#5469] opened 2020-02-14 07:43 UTC
### Steps to reproduce
1. add LDAP/AD-integration to NC instance
2. remove all local user accounts
3. create an external-storage, f.e. smb/cifs with auth-methon "save credentials in session" and link one user to it

### Expected behaviour
- files and folders at the external-storage should be listed and accessible like via webui or with none ldap, but local users

### Actual behaviour
- by accessing external storage like mentioned above, android app will show "server in maint mode" message and the NC log will throw the attached error

### Environment data
Android version:
- Oxygen 9.0.10

Device model: 
- OnePlus 5t and OnePlus 3

Stock or customized system:
- stock OnePlus

Nextcloud app version:
- 3.10.1

Nextcloud server version:
- 17.0.3

#### Web server error log
After starting the app and first listing of users root dir, the following error occurs:
```
[no app in context] Error: Icewind\SMB\Exception\ForbiddenException: Invalid request for / (ForbiddenException) at <<closure>>

 0. /var/www/html/apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php line 62
    Icewind\SMB\Exception\Exception::fromMap({1: "Icewind\\SM ... "}, 1, "/")
 1. /var/www/html/apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php line 74
    Icewind\SMB\Native\NativeState->handleError("/")
 2. /var/www/html/apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php line 184
    Icewind\SMB\Native\NativeState->testResult(false, "smb://domnas/gemeinsame-dateien/")
 3. /var/www/html/apps/files_external/3rdparty/icewind/smb/src/Native/NativeShare.php line 133
    Icewind\SMB\Native\NativeState->stat("smb://domnas/gemeinsame-dateien/")
 4. /var/www/html/apps/files_external/3rdparty/icewind/smb/src/Native/NativeShare.php line 112
    Icewind\SMB\Native\NativeShare->getStat("/")
 5. /var/www/html/apps/files_external/lib/Lib/Storage/SMB.php line 178
    Icewind\SMB\Native\NativeShare->stat("/")
 6. /var/www/html/apps/files_external/lib/Lib/Storage/SMB.php line 296
    OCA\Files_External\Lib\Storage\SMB->getFileInfo("/")
 7. /var/www/html/lib/private/Files/Storage/Common.php line 454
    OCA\Files_External\Lib\Storage\SMB->stat("")
 8. /var/www/html/apps/files_external/lib/Lib/Storage/SMB.php line 612
    OC\Files\Storage\Common->test()
 9. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 472
    OCA\Files_External\Lib\Storage\SMB->test()
10. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 472
    OC\Files\Storage\Wrapper\Wrapper->test()
11. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 472
    OC\Files\Storage\Wrapper\Wrapper->test()
12. /var/www/html/lib/private/Files/Storage/Wrapper/Availability.php line 66
    OC\Files\Storage\Wrapper\Wrapper->test()
13. /var/www/html/lib/private/Files/Storage/Wrapper/Availability.php line 80
    OC\Files\Storage\Wrapper\Availability->updateAvailability("*** sensitive parameters replaced ***")
14. /var/www/html/lib/private/Files/Storage/Wrapper/Availability.php line 89
    OC\Files\Storage\Wrapper\Availability->isAvailable()
15. /var/www/html/lib/private/Files/Storage/Wrapper/Availability.php line 438
    OC\Files\Storage\Wrapper\Availability->checkAvailability()
16. /var/www/html/lib/private/Files/Cache/Scanner.php line 112
    OC\Files\Storage\Wrapper\Availability->getMetaData("")
17. /var/www/html/lib/private/Files/Cache/Scanner.php line 150
    OC\Files\Cache\Scanner->getData("")
18. /var/www/html/lib/private/Files/View.php line 1482
    OC\Files\Cache\Scanner->scanFile("")
19. /var/www/html/apps/dav/lib/Connector/Sabre/Directory.php line 265
    OC\Files\View->getDirectoryContent("/")
20. /var/www/html/apps/dav/lib/Connector/Sabre/TagsPlugin.php line 224
    OCA\DAV\Connector\Sabre\Directory->getChildren()
21. <<closure>>
    OCA\DAV\Connector\Sabre\TagsPlugin->handleGetProperties(Sabre\DAV\PropFind {}, OCA\DAV\Connector\Sabre\Directory {})
22. /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([OCA\DAV\Connect ... "], [Sabre\DAV\PropF ... }])
23. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1059
    Sabre\Event\EventEmitter->emit("propFind", [Sabre\DAV\PropF ... }])
24. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 981
    Sabre\DAV\Server->getPropertiesByNode(Sabre\DAV\PropFind {}, OCA\DAV\Connector\Sabre\Directory {})
25. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1666
    Sabre\DAV\Server->getPropertiesIteratorForPath("", ["{http://ownclo ... "], 1)
26. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 355
    Sabre\DAV\Server->generateMultiStatus(Generator {}, false)
27. <<closure>>
    Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
28. /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPropFind"], [Sabre\HTTP\Requ ... }])
29. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:PROPFIND", [Sabre\HTTP\Requ ... }])
30. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
31. /var/www/html/apps/dav/appinfo/v1/webdav.php line 80
    Sabre\DAV\Server->exec()
32. /var/www/html/remote.php line 163
    undefinedundefinedrequire_once("/var/www/html/a ... p")

PROPFIND /remote.php/webdav/
from 10.0.1.99 by d7bcdabb-6951-43e3-a350-f1fa9f481a28 at 2020-02-14T07:23:55+00:00
```
After a refresh, this error wont come back until comlpete closure of the app.

On browsing to this share, the following error occurs:
```
[webdav] Fatal: Sabre\DAV\Exception\ServiceUnavailable: Storage is temporarily not available at <<closure>>

0. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 967
   OCA\DAV\Connector\Sabre\ObjectTree->getNodeForPath("gemeinsame-dateien")
1. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1666
   Sabre\DAV\Server->getPropertiesIteratorForPath("gemeinsame-dateien", ["{DAV:}creation ... "], 0)
2. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 355
   Sabre\DAV\Server->generateMultiStatus(Generator {}, false)
3. <<closure>>
   Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
4. /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
   undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPropFind"], [Sabre\HTTP\Requ ... }])
5. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 479
   Sabre\Event\EventEmitter->emit("method:PROPFIND", [Sabre\HTTP\Requ ... }])
6. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 254
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
7. /var/www/html/apps/dav/appinfo/v1/webdav.php line 80
   Sabre\DAV\Server->exec()
8. /var/www/html/remote.php line 163
   undefinedundefinedrequire_once("/var/www/html/a ... p")

PROPFIND /remote.php/webdav/gemeinsame-dateien/
from 10.0.1.99 by d7bcdabb-6951-43e3-a350-f1fa9f481a28 at 2020-02-14T07:41:21+00:00
```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"YKAVIqWfDUgu9iZsswVc","level":4,"time":"2020-02-14T07:32:35+00:00","remoteAddr":"client_ip","user":"d7bcdabb-6951-43e3-a350-f1fa9f481a28","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/gemeinsame-bilder\/","message":{"Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Message":"Storage is temporarily not available","Code":0,"Trace":[{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":967,"function":"getNodeForPath","class":"OCA\\DAV\\Connector\\Sabre\\ObjectTree","type":"->","args":["gemeinsame-bilder"]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1666,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->","args":["gemeinsame-bilder",["{DAV:}creationdate","{DAV:}getetag","{DAV:}displayname","{http:\/\/owncloud.org\/ns}permissions","{DAV:}getlastmodified","{DAV:}getcontenttype","{http:\/\/nextcloud.org\/ns}has-preview","{http:\/\/owncloud.org\/ns}id","{http:\/\/owncloud.org\/ns}size","{DAV:}getcontentlength","{http:\/\/owncloud.org\/ns}favorite","{DAV:}resourcetype"],0]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":355,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Generator"},false]},{"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"http:\/\/10.0.1.9\/remote.php\/webdav\/gemeinsame-bilder\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPropFind"],[{"absoluteUrl":"http:\/\/10.0.1.9\/remote.php\/webdav\/gemeinsame-bilder\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PROPFIND",[{"absoluteUrl":"http:\/\/10.0.1.9\/remote.php\/webdav\/gemeinsame-bilder\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"http:\/\/10.0.1.9\/remote.php\/webdav\/gemeinsame-bilder\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/html\/apps\/dav\/appinfo\/v1\/webdav.php","line":80,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/html\/remote.php","line":163,"args":["\/var\/www\/html\/apps\/dav\/appinfo\/v1\/webdav.php"],"function":"require_once"}],"File":"\/var\/www\/html\/apps\/dav\/lib\/Connector\/Sabre\/ObjectTree.php","Line":162,"Previous":{"Exception":"OCP\\Files\\StorageNotAvailableException","Message":"Storage with mount id 7 is not available","Code":1,"Trace":[{"file":"\/var\/www\/html\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":527,"function":"getAvailability","class":"OC\\Files\\Storage\\FailedStorage","type":"->","args":[]},{"file":"\/var\/www\/html\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":527,"function":"getAvailability","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":[]},{"file":"\/var\/www\/html\/lib\/private\/Files\/Storage\/Wrapper\/Availability.php","line":78,"function":"getAvailability","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":[]},{"file":"\/var\/www\/html\/lib\/private\/Files\/Storage\/Wrapper\/Availability.php","line":89,"function":"isAvailable","class":"OC\\Files\\Storage\\Wrapper\\Availability","type":"->","args":[]},{"file":"\/var\/www\/html\/lib\/private\/Files\/Storage\/Wrapper\/Availability.php","line":379,"function":"checkAvailability","class":"OC\\Files\\Storage\\Wrapper\\Availability","type":"->","args":[]},{"file":"\/var\/www\/html\/lib\/private\/Files\/Cache\/Watcher.php","line":126,"function":"hasUpdated","class":"OC\\Files\\Storage\\Wrapper\\Availability","type":"->","args":["",null]},{"file":"\/var\/www\/html\/lib\/private\/Files\/View.php","line":1340,"function":"needsUpdate","class":"OC\\Files\\Cache\\Watcher","type":"->","args":["",{"__class__":"OC\\Files\\Cache\\CacheEntry"}]},{"file":"\/var\/www\/html\/lib\/private\/Files\/View.php","line":1382,"function":"getCacheEntry","class":"OC\\Files\\View","type":"->","args":[{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OC\\Files\\Storage\\Wrapper\\Availability"},"","gemeinsame-bilder"]},{"file":"\/var\/www\/html\/apps\/dav\/lib\/Connector\/Sabre\/ObjectTree.php","line":156,"function":"getFileInfo","class":"OC\\Files\\View","type":"->","args":["\/d7bcdabb-6951-43e3-a350-f1fa9f481a28\/files\/gemeinsame-bilder"]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":967,"function":"getNodeForPath","class":"OCA\\DAV\\Connector\\Sabre\\ObjectTree","type":"->","args":["gemeinsame-bilder"]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1666,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->","args":["gemeinsame-bilder",["{DAV:}creationdate","{DAV:}getetag","{DAV:}displayname","{http:\/\/owncloud.org\/ns}permissions","{DAV:}getlastmodified","{DAV:}getcontenttype","{http:\/\/nextcloud.org\/ns}has-preview","{http:\/\/owncloud.org\/ns}id","{http:\/\/owncloud.org\/ns}size","{DAV:}getcontentlength","{http:\/\/owncloud.org\/ns}favorite","{DAV:}resourcetype"],0]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":355,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Generator"},false]},{"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"http:\/\/10.0.1.9\/remote.php\/webdav\/gemeinsame-bilder\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPropFind"],[{"absoluteUrl":"http:\/\/10.0.1.9\/remote.php\/webdav\/gemeinsame-bilder\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PROPFIND",[{"absoluteUrl":"http:\/\/10.0.1.9\/remote.php\/webdav\/gemeinsame-bilder\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"http:\/\/10.0.1.9\/remote.php\/webdav\/gemeinsame-bilder\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/html\/apps\/dav\/appinfo\/v1\/webdav.php","line":80,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/html\/remote.php","line":163,"args":["\/var\/www\/html\/apps\/dav\/appinfo\/v1\/webdav.php"],"function":"require_once"}],"File":"\/var\/www\/html\/lib\/private\/Files\/Storage\/FailedStorage.php","Line":209,"Hint":"Storage is temporarily not available","Previous":{"Exception":"OCP\\Files\\StorageNotAvailableException","Message":"Storage with mount id 7 is not available","Code":1,"Trace":[{"function":"OCA\\Files_External\\Config\\{closure}","class":"OCA\\Files_External\\Config\\ConfigAdapter","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/html\/apps\/files_external\/lib\/Config\/ConfigAdapter.php","line":142,"function":"array_map","args":[{"__class__":"Closure"},{"7":"*** sensitive parameter replaced ***","9":{"cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_External\\Lib\\SessionStorageWrapper"},"10":{"cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_External\\Lib\\SessionStorageWrapper"}},{"7":"*** sensitive parameter replaced ***","9":{"__class__":"OCA\\Files_External\\Lib\\StorageConfig"},"10":{"__class__":"OCA\\Files_External\\Lib\\StorageConfig"}}]},{"file":"\/var\/www\/html\/lib\/private\/Files\/Config\/MountProviderCollection.php","line":103,"function":"getMountsForUser","class":"OCA\\Files_External\\Config\\ConfigAdapter","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\Files\\Storage\\StorageFactory"}]},{"file":"\/var\/www\/html\/lib\/private\/Files\/Filesystem.php","line":447,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\Files\\Mount\\Manager"}]},{"file":"\/var\/www\/html\/lib\/private\/Files\/Filesystem.php","line":376,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::","args":["d7bcdabb-6951-43e3-a350-f1fa9f481a28"]},{"file":"\/var\/www\/html\/lib\/private\/legacy\/util.php","line":309,"function":"init","class":"OC\\Files\\Filesystem","type":"::","args":["d7bcdabb-6951-43e3-a350-f1fa9f481a28","\/d7bcdabb-6951-43e3-a350-f1fa9f481a28\/files"]},{"file":"\/var\/www\/html\/apps\/dav\/lib\/Connector\/Sabre\/Auth.php","line":124,"function":"setupFS","class":"OC_Util","type":"::","args":["d7bcdabb-6951-43e3-a350-f1fa9f481a28"]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Backend\/AbstractBasic.php","line":105,"function":"validateUserPass","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/html\/apps\/dav\/lib\/Connector\/Sabre\/Auth.php","line":253,"function":"check","class":"Sabre\\DAV\\Auth\\Backend\\AbstractBasic","type":"->","args":[{"absoluteUrl":"http:\/\/10.0.1.9\/remote.php\/webdav\/gemeinsame-bilder\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/html\/apps\/dav\/lib\/Connector\/Sabre\/Auth.php","line":155,"function":"auth","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->","args":[{"absoluteUrl":"http:\/\/10.0.1.9\/remote.php\/webdav\/gemeinsame-bilder\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","line":200,"function":"check","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->","args":[{"absoluteUrl":"http:\/\/10.0.1.9\/remote.php\/webdav\/gemeinsame-bilder\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","line":150,"function":"check","class":"Sabre\\DAV\\Auth\\Plugin","type":"->","args":[{"absoluteUrl":"http:\/\/10.0.1.9\/remote.php\/webdav\/gemeinsame-bilder\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"function":"beforeMethod","class":"Sabre\\DAV\\Auth\\Plugin","type":"->","args":[{"absoluteUrl":"http:\/\/10.0.1.9\/remote.php\/webdav\/gemeinsame-bilder\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"autoRequireLogin":true,"__class__":"Sabre\\DAV\\Auth\\Plugin"},"beforeMethod"],[{"absoluteUrl":"http:\/\/10.0.1.9\/remote.php\/webdav\/gemeinsame-bilder\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":466,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["beforeMethod",[{"absoluteUrl":"http:\/\/10.0.1.9\/remote.php\/webdav\/gemeinsame-bilder\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"http:\/\/10.0.1.9\/remote.php\/webdav\/gemeinsame-bilder\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/html\/apps\/dav\/appinfo\/v1\/webdav.php","line":80,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/html\/remote.php","line":163,"args":["\/var\/www\/html\/apps\/dav\/appinfo\/v1\/webdav.php"],"function":"require_once"}],"File":"\/var\/www\/html\/apps\/files_external\/lib\/Config\/ConfigAdapter.php","Line":147,"Hint":"Storage is temporarily not available"}},"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.10.1","version":"17.0.3.1"}
```

Mention, this behavior is only with ldap integration and ldap users.
With local NC configured users, external-storage like described above works like a charm.
Also, this behavior ist only via Android App. Browsing via PC and browser, or via the same android device and browser, also works like a charm.
But that is not useable for auto-upload etc.

**Comment by AndyScherzinger** [comment] 2020-02-14 09:50
Cc @tobiasKaminsky @rullzer @icewind1991 for feedback ❤️

**Comment by tobiasKaminsky** [comment] 2020-03-26 07:11
@nextcloud/server-triage what can we do here?

**Comment by blizzz** [comment] 2020-03-26 10:39
I don't see a reason why this should affect LDAP users only, while it is working on Web UI. @selfisch can you see whether the credentials are correct, when Nextcloud tries to connect to the SMB storage? For instance by checking SMBs log.

**Comment by kesselb** [comment] 2020-03-26 11:02
Sounds like https://github.com/nextcloud/server/issues/19561

**Comment by selfisch** [comment] 2020-03-26 12:15
> I don't see a reason why this should affect LDAP users only, while it is working on Web UI. @selfisch can you see whether the credentials are correct, when Nextcloud tries to connect to the SMB storage? For instance by checking SMBs log.

I dont see smb log complains/errors.
1. The NAS where smb is running, is configured to block login for 1 hour if there are to many login attempts in a short row. That is not happening
2. Also(like I described) when users are configured via LDAP and local NC users are removed completely, Web UI works like a charm while android app wont work, with above described behavior.

**Comment by dbrown1111** [comment] 2020-03-26 19:54
@selfisch Can you provide what NAS software you're using? (A Linux distro? Freenas? XigmaNAS?) cause looking at a similar one @kesselb linked I wonder if it a Ubuntu-specific issue or not.

**Comment by selfisch** [comment] 2020-03-27 07:37
Hey @dbrown1111,
I am using a QNAP TS-431X. 
Current software release is: 4.4.1.1216(2020/02/14)

**Comment by dbrown1111** [comment] 2020-03-27 20:33
After doing some testing and research. The only thing that I could come down to is the NC app having some issues with LDAP alone. This seemed to be a common issue with NC and I'm not sure how the android app handles LDAP requests.

**Comment by blizzz** [comment] 2020-03-28 00:06
> android app handles LDAP requests

it doens't. the server does. the android app just sends up credentials.

**Comment by kesselb** [comment] 2020-03-28 11:51
- This report is actually a duplicate of https://github.com/nextcloud/android/issues/3810
- Some technical details: https://github.com/nextcloud/android/issues/1267
- Feature Request for server: https://github.com/nextcloud/server/issues/18168
- Same problem but iOS: https://github.com/nextcloud/ios/issues/500

**Closed** 2023-12-01 16:06 UTC
Labels: bug, approved
