### ISSUE TITLE
Crash: RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by Bubu** [nextcloud/android#8907] opened 2021-08-27 22:14 UTC
Not exactly sure whats going on, but as the app showed this error reporting screen I wanted to add this here:

```
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170053
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: google
Device: bullhead
Model: Nexus 5X
Id: OPM7.181205.001
Product: bullhead

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 711b03ba58
```

**Comment by tobiasKaminsky** [comment] 2021-08-30 06:14
Do you know when this happens?

**Comment by Bubu** [comment] 2021-08-30 12:59
I'm not exactly sure and I can't reliably reproduce this but it did happen a few more times on a different device as well.

I was playing some audiobooks/music via nextcloud and put the phone away during that time when going back to nc app and trying to navigate it sometimes threw this exception then.

**Comment by AlvaroBrey** [comment] 2021-09-07 10:47
Closing as duplicate of #8686, will consolidate reports on that one.

**Closed by AlvaroBrey** 2021-09-07 10:47 UTC
Labels: bug, needs info/discussion
