### ISSUE TITLE
Click on shared

### ISSUE THREAD

**Issue by FreshFoxyHD** [nextcloud/android#10235] opened 2022-05-12 12:55 UTC
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'com.owncloud.android.utils.FileSortOrder$SortType com.owncloud.android.utils.FileSortOrder.getType()' on a null object reference
    at com.owncloud.android.ui.adapter.OCFileListAdapter.getPopupText(OCFileListAdapter.java:905)
    at me.zhanghai.android.fastscroll.RecyclerViewHelper.getPopupText(RecyclerViewHelper.java:136)
    at me.zhanghai.android.fastscroll.FastScroller.onPreDraw(FastScroller.java:198)
    at me.zhanghai.android.fastscroll.FastScroller.$r8$lambda$fhoCEu3yFeBM02d2QCiuR_Ev5oo(Unknown Source:0)
    at me.zhanghai.android.fastscroll.FastScroller$$ExternalSyntheticLambda1.run(Unknown Source:2)
    at me.zhanghai.android.fastscroll.RecyclerViewHelper$1.onDraw(RecyclerViewHelper.java:52)
    at androidx.recyclerview.widget.RecyclerView.onDraw(RecyclerView.java:4668)
    at android.view.View.draw(View.java:23898)
    at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
    at android.view.View.updateDisplayListIfDirty(View.java:22767)
    at android.view.View.draw(View.java:23628)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
    at android.view.View.draw(View.java:23901)
    at android.view.View.updateDisplayListIfDirty(View.java:22767)
    at android.view.View.draw(View.java:23628)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
    at android.view.View.updateDisplayListIfDirty(View.java:22753)
    at android.view.View.draw(View.java:23628)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
    at android.view.View.updateDisplayListIfDirty(View.java:22753)
    at android.view.View.draw(View.java:23628)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
    at android.view.View.draw(View.java:23901)
    at android.view.View.updateDisplayListIfDirty(View.java:22767)
    at android.view.View.draw(View.java:23628)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
    at android.view.View.updateDisplayListIfDirty(View.java:22753)
    at android.view.View.draw(View.java:23628)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
    at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
    at android.view.View.draw(View.java:23901)
    at android.view.View.updateDisplayListIfDirty(View.java:22767)
    at android.view.View.draw(View.java:23628)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
    at android.view.View.updateDisplayListIfDirty(View.java:22753)
    at android.view.View.draw(View.java:23628)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
    at android.view.View.updateDisplayListIfDirty(View.java:22753)
    at android.view.View.draw(View.java:23628)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
    at android.view.View.updateDisplayListIfDirty(View.java:22753)
    at android.view.View.draw(View.java:23628)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
    at android.view.View.updateDisplayListIfDirty(View.java:22753)
    at android.view.View.draw(View.java:23628)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
    at android.view.View.draw(View.java:23901)
    at com.android.internal.policy.DecorView.draw(DecorView.java:1378)
    at android.view.View.updateDisplayListIfDirty(View.java:22767)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:602)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:608)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:684)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:5432)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5140)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4204)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2911)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10458)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
    at android.view.Choreographer.doCallbacks(Choreographer.java:866)
    at android.view.Choreographer.doFrame(Choreographer.java:797)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `y2s`
* Model: `SM-G985F`
* Id: `SP1A.210812.016`
* Product: `y2seea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `G985FXXUEFVDB`

**Comment by FreshFoxyHD** [comment] 2022-05-12 12:55
Nextcloud v24

**Comment by AlvaroBrey** [comment] 2022-05-12 14:58
Duplicate of #10227

**Closed by AlvaroBrey** 2022-05-12 14:58 UTC
