### ISSUE TITLE
App crashes for no apparent reason

### ISSUE THREAD

**Issue by trendzetter** [nextcloud/android#5408] opened 2020-02-05 11:25 UTC
### Steps to reproduce
Unknown

### Expected behaviour
I don't know, resume from sleep? 

### Actual behaviour
Error popping above other apps

### Environment data
Android version:
9.1.0.317
Device model: 
Huawei P30 lite
Stock or customized system:
Stock
Nextcloud app version:
3.10.0
Nextcloud server version:
17.0.3 but also earlier versions
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2020-02-05 11:31
Do you see any crash info? 
Otherwise it is really hard to hunt this bug down… :S

**Comment by trendzetter** [comment] 2020-02-26 12:55
thank you for your interest. It's appearing but pressing anything and it disappears, so far I only managed to press the "report issue" button. I will try to make a screenshot if it's possible.

**Comment by trendzetter** [comment] 2020-02-26 22:14
@tobiasKaminsky  ![Screenshot_com nextcloud client](https://user-images.githubusercontent.com/6834530/75393060-9942b280-58ed-11ea-87b3-6a15d02cefd7.jpg)

**Comment by trendzetter** [comment] 2020-02-27 09:24
probably also a duplicate of https://github.com/nextcloud/android/issues/4586 
Sorry for bothering you again but why is it closed if it's unresolved?

**Comment by tobiasKaminsky** [comment] 2020-03-23 05:23
Duplicate of #4675

**Closed by tobiasKaminsky** 2020-03-23 05:23 UTC
Labels: bug
