### ISSUE TITLE
App does not not log in on Android or crashes

### ISSUE THREAD

**Issue by MathiasRenner** [nextcloud/android#3427] opened 2019-01-05 16:14 UTC
### Actual behaviour
Cannot login into nextcloud with official app. This bug has been filed here https://github.com/nextcloud/android/issues/1738 for app version 2, but now I have a similar issue with the latest app.

### Expected behaviour
1. Provide server URL and credentials to the app
2. After I pressed the button "grant access": see list of files of my Nextcloud

### Steps to reproduce
Provide server URL and credentials to the app via the wizard. The credentials seem to be accepted,  this screen is shown:
[<img src="http://mathias-renner.com/dl/screenshot5000.png" height="500">](http://mathias-renner.com/dl/bug-screenie.png)

### Environment data
Android version:
LineageOS 14.1, Android 7.1.2

Device model: 
Samsung S7, SM-G930F

Stock or customized system:
Stock system with MariaDB. Docker images fresh from upstream, no relevant changes in config.

Nextcloud app version:
3.4.1

Nextcloud server version:
15.0.0

### Logs
Neither in Nextcloud server nor in App are relevant log entries.  I used LogCat to record the log while reproducing this issue.

### Fun facts
Several notebooks are connected with the same account I'd like to use on the phone to the app and work fine. 
Also the "Notes" app with the same Account works fine. The Nextcloud app is the only part in the ecosystem I have an issue with.
I had the same issue with version 13 of Nextcloud. Updating to v 15 unfortunately did not help.

**Comment by MathiasRenner** [comment] 2019-01-07 22:31
@tobiasKaminsky Test account created and credentials just sent via Email.

Interestingly, the problem does not occur with the test account! I am confused.

Hmm... my own user was a fresh one, I did not import any backup which could have imported old problems... 
The difference is only that the test user does not have admin rights.

**Comment by tobiasKaminsky** [comment] 2019-01-08 08:34
If the problem does not occur on the test account, I cannot try to reproduce it.
Can you temporary disable admin rights from your account to see if this helps?

**Comment by MathiasRenner** [comment] 2019-01-09 18:04
@tobiasKaminsky Tried that today. Same error without admin rights. Still no log entry in the settings when the issue occurs on the phone.

I don't wanna invest more time here bugfixing it, especially because it seems I cannot make it reproducible for you. I probably create a new user for me and take the effort of migrating the configuration (esp. calender, contacts).
Gonna do this in the upcoming days - except you have another idea :-)

**Comment by tobiasKaminsky** [comment] 2019-01-10 15:23
Is the problematic username something special? Like special chars, whitespaces, etc?

**Comment by MathiasRenner** [comment] 2019-01-10 18:13
@tobiasKaminsky: Nope, just normal chars.

**Comment by MorrisJobke** [comment] 2019-01-14 10:17
> @nextcloud/server-triage do you have an idea?

@tobiasKaminsky Could you reproduce this on your device? Because I'm not aware of something related to this. It looks like the HTTP header is not correctly send over.

**Comment by MathiasRenner** [comment] 2019-01-31 22:01
Update: For me this is reproducible now. **Any** new user I create and try to log in with in the Android App fails. It's always the same error as above.

I did not change the environment, just added and deleted new users to try out...

This is really frustrating :-(

@tobiasKaminsky I just sent you new login infos.

**Comment by tobiasKaminsky** [comment] 2019-02-01 07:12
@MorrisJobke thinks to the credentials by @MathiasRenner I can now reproduce it.
Do we wanna try to debug this together?

**Comment by tobiasKaminsky** [comment] 2019-02-01 07:15
As we get "Error
Access Forbidden

Invalid request" I assume that somewhere the header is not correctly passed and thus it refuses to login.

**Comment by tobiasKaminsky** [comment] 2019-02-01 10:22
There is something strange happening during weblogin flow, we cannot debug this from here.

Can you give us a bit more insight on your server? apache/nginx? config, etc?

**Comment by MathiasRenner** [comment] 2019-02-06 00:11
@tobiasKaminsky Figured out that this bug is introduced with server version 15 and higher.
Testing with 14.0.6 -> all OK. As soon as I upgrade to 15.0 the bug comes in.

I deleted my testing env (incl. your test account) and will go down to 14.0.6 now, waiting until v 15 is of higher quality.

I am not that eager in testing more, wanna use the system eventually :-)
Thanks for having beeing in touch with me, I hope you find the issue soon!

**Comment by tobiasKaminsky** [comment] 2019-02-06 09:22
@nextcloud/server-triage do you have an idea how we can help @MathiasRenner to get this working on 15+?
Seems to be a strange regression…

**Comment by rullzer** [comment] 2019-02-06 09:40
Not really. Since this is working as advertised on all the instances I have access to. And without a test system there is not really a way to fix this.

Only thing that might be is it that `overwriteprotocol` in config.php is not set (seems people forget that behind a reverse proxy).

**Comment by tobiasKaminsky** [comment] 2019-02-06 10:48
Ok, then I'll close this for now, as I read that the test system is deleted.

**Closed by tobiasKaminsky** 2019-02-06 10:48 UTC
Labels: bug, needs info/discussion
