### ISSUE TITLE
Don't know why

### ISSUE THREAD

**Issue by kidexx** [nextcloud/android#13833] opened 2024-10-20 20:08 UTC
### Cause of error
```java
Exception in thread "main" android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{8a4bd7 u0 com.nextcloud.client/androidx.work.impl.foreground.SystemForegroundService}
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2389)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8393)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300190`
* Build flavor: `generic`

### Device information
* Brand: `HONOR`
* Device: `HWYAL`
* Model: `YAL-L21`
* Id: `HUAWEIYAL-L21`
* Product: `YAL-L21EEA`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `10.1.0.241C431`

**Comment by joshtrichards** [comment] 2024-10-20 20:09
Duplicate of #13798

**Closed by joshtrichards** 2024-10-20 20:09 UTC
Labels: bug, performance: general/non-specific, stable-3.30
