### ISSUE TITLE
Removing account from nextcloud android app results in crash. Restarting the app works

### ISSUE THREAD

**Issue by Samalbert977** [nextcloud/android#14138] opened 2024-12-06 19:27 UTC
### Cause of error
```java
Exception in thread "Thread-32" java.lang.IllegalArgumentException: Trying to execute a sync operation with a storage manager for an anonymous account
    at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:49)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$fetchExternalLinks$9(DrawerActivity.java:1231)
    at com.owncloud.android.ui.activity.DrawerActivity.$r8$lambda$oHM2j1MZkviAIdyIFWoI2kSeF9c(Unknown Source:0)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus6`
* Model: `ONEPLUS A6003`
* Id: `AP2A.240905.003`
* Product: `OnePlus6`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `87c1fc8cb5`

**Comment by joshtrichards** [comment] 2024-12-28 14:57
Duplicate of #13323

**Closed by joshtrichards** 2024-12-28 14:57 UTC
Labels: 0. Needs triage
