### ISSUE TITLE
OOM in `ReadFolderRemoteOperation`/ `fetchAndSyncRemoteFolder`

### ISSUE THREAD

**Issue by gortium** [nextcloud/android#13161] opened 2024-06-20 15:13 UTC
### Cause of error
```java
Exception in thread "Thread-28" java.lang.OutOfMemoryError: Failed to allocate a 13200 byte allocation with 408736 free bytes and 399KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
    at org.apache.jackrabbit.webdav.MultiStatus.getResponses(MultiStatus.java:128)
    at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.readData(ReadFolderRemoteOperation.java:131)
    at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:70)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:413)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:247)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:387)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290090`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `cheetah`
* Model: `Pixel 7 Pro`
* Id: `AP1A.240505.005`
* Product: `cheetah`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `11677807`

**Comment by joshtrichards** [comment] 2024-11-02 13:10
Duplicate of #9903

**Closed by joshtrichards** 2024-11-02 13:10 UTC
Labels: bug, performance: OOM :brain:, stable-3.29
