### ISSUE TITLE
Fehler

### ISSUE THREAD

**Issue by weinic** [nextcloud/android#7189] opened 2020-10-31 16:39 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e5f0d24 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2039)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5
Model: ONEPLUS A5000
Id: QKQ1.191014.012
Product: OnePlus5

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2006012143

Keine Ahnung was hier passiert ist...
Der Fehler ist aufgetreten als ich ein paar mal hintereinander bei verschiedenen Ordner die drei Punkte für das Menü auf der rechten Seite angeklickt habe.

**Comment by weinic** [comment] 2020-10-31 16:41
Ich habe es gerade nochmal probiert. 
Kann den Fehler leider nicht reproduzieren.

**Comment by AndyScherzinger** [comment] 2020-10-31 17:37
Dann warten wir mal ab 👍

**Comment by AndyScherzinger** [comment] 2020-10-31 17:38
@ezaquarii any ideas maybe? The start foreground service exception in combination with the PlayerService has been reported couple of times by now while nobody could describe a reproducable crash pattern 😔

**Comment by ezaquarii** [comment] 2020-10-31 17:45
@AndyScherzinger sadly, i have no solution for this.

I have a theory that some rapid GUI actions can cause some commands to be sent but but the service is not put in foreground.

I plan to take a closer look on this issue for quite some time now, but i have little bandwidth for any oss work atm. :(

**Comment by AndyScherzinger** [comment] 2020-10-31 19:00
@ezaquarii no worries and as always: no pressure 👍

Maybe @tobiasKaminsky has an idea

**Comment by AndyScherzinger** [comment] 2020-11-03 08:15
Duplicate of #6905

**Closed by AndyScherzinger** 2020-11-03 08:15 UTC
Labels: bug
