### ISSUE TITLE
Crash when allowed calendar permission

### ISSUE THREAD

**Issue by Artaud** [nextcloud/android#9388] opened 2021-11-28 12:26 UTC
I did enable calendar sync, gave permission, then it crashed.

************ CAUSE OF ERROR ************
```
java.lang.NullPointerException: Attempt to read from field 'com.google.android.material.button.MaterialButton com.owncloud.android.databinding.BackupFragmentBinding.contactsDatepicker' on a null object reference
	at com.owncloud.android.ui.fragment.contactsbackup.BackupFragment$1.onPostExecute(BackupFragment.java:281)
	at com.owncloud.android.ui.fragment.contactsbackup.BackupFragment$1.onPostExecute(BackupFragment.java:252)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Nokia
Device: DDV_sprout
Model: Nokia 7.2
Id: QKQ1.191014.001
Product: Daredevil_00EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 00WW_2_410_SP06

**Comment by joshtrichards** [comment] 2023-10-14 00:18
Duplicate of #9595 
Fixed in #9606

**Closed by joshtrichards** 2023-10-14 00:18 UTC
Labels: bug, feature: contacts and calendar backup
