### ISSUE TITLE
Android QR code login crash 

### ISSUE THREAD

**Issue by RandomDennisLee** [nextcloud/android#9077] opened 2021-10-09 04:45 UTC
Crash when attempting to login with QR code. 

************ CAUSE OF ERROR ************

android.database.SQLException: ERROR content://org.nextcloud/file
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:289)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:255)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:325)
	at android.content.ContentResolver.insert(ContentResolver.java:1844)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFile(FileDataStorageManager.java:275)
	at com.owncloud.android.datamodel.FileDataStorageManager.createRootDir(FileDataStorageManager.java:926)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:130)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByEncryptedRemotePath(FileDataStorageManager.java:112)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:108)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2414)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1440)
	at android.app.Activity.performStart(Activity.java:8109)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3806)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWMAR
Model: MAR-LX2
Id: HUAWEIMAR-L22B
Product: MAR-LX2

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.280C636

**Comment by RandomDennisLee** [comment] 2021-10-09 05:27
Unable to reproduce, 2nd attempt logged in as expected.

**Comment by AlvaroBrey** [comment] 2022-08-26 08:15
Closed as I am also unable to reproduce and there's no info to go off of. Will reopen if I run into this

**Closed by AlvaroBrey** 2022-08-26 08:15 UTC
Labels: bug
