### ISSUE TITLE
Crash on sharing file

### ISSUE THREAD

**Issue by robbah** [nextcloud/android#11332] opened 2023-01-30 19:22 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open file explorer
2. Select file
3. Share -> Nextcloud 
4. It open my last location
5. Return to folder overview
6. Crash...

### Expected behaviour

Open folders from root location 

### Cause of error
```java
Exception in thread "Thread-9" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230191`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `r0s`
* Model: `SM-S901B`
* Id: `TP1A.220624.014`
* Product: `r0sxeea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `S901BXXS2BWA2`

### Android version

Android 13

### Device brand and model

Samsung Galaxy S22

### Stock or custom OS?

Stock

### Nextcloud android app version

3.23.1

### Nextcloud server version

25.0.1

### Using a reverse proxy?

I don't know

**Comment by AlvaroBrey** [comment] 2023-01-31 07:57
Duplicate of #11207

**Closed by AlvaroBrey** 2023-01-31 07:57 UTC
Labels: bug
