### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by FlyingEagle** [nextcloud/android#5790] opened 2020-04-01 22:11 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
	at android.widget.Toast$TN.<init>(Toast.java:680)
	at android.widget.Toast.<init>(Toast.java:157)
	at android.widget.Toast.makeText(Toast.java:441)
	at android.widget.Toast.makeText(Toast.java:399)
	at android.widget.Toast.makeText(Toast.java:493)
	at com.owncloud.android.ui.activity.ConflictsResolveActivity.showErrorAndFinish(ConflictsResolveActivity.java:229)
	at com.owncloud.android.ui.activity.ConflictsResolveActivity.lambda$onStart$0$ConflictsResolveActivity(ConflictsResolveActivity.java:192)
	at com.owncloud.android.ui.activity.-$$Lambda$ConflictsResolveActivity$EM0Z1Vrhvmim7X4XXFnNqL4vK1A.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: herolte
Model: SM-G930F
Id: R16NW
Product: heroltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G930FXXS7ESL9

**Comment by AndyScherzinger** [comment] 2020-04-02 07:26
Duplicate of #5789

**Closed by AndyScherzinger** 2020-04-02 07:26 UTC
Labels: bug
