### ISSUE TITLE
User information screen

### ISSUE THREAD

**Issue by mario** [nextcloud/android#554] opened 2017-01-19 10:38 UTC
I would like to implement the read-only user information (phone, email, etc) screen. (as far as I understand, there's no way to update most of the data via API, but please let me know if I'm wrong).

My suggestion for changes:

- Under Manage account remove "Reconnect" (or the key icon, this option is not straightforward btw) and the trash icon 
- Once you click the name of the account, you get a user information screen and both options should be put in the options menu top right for consistency with the rest of the app

The reason for this change is that you can switch accounts already from the sidebar, so there's no point in having two places to do the same operation.

I appreciate all the suggestions and comments on this approach and also welcome the mockup for the user information screen. 

cc @nextcloud/designers @AndyScherzinger @tobiasKaminsky

**Comment by eppfel** [comment] 2017-01-19 12:41
Yes, I think the account switching duplication came up before somewhere. I totally are for removing this 👍 

What was the reconnect option (key) for...? What are the use cases for that? @AndyScherzinger @tobiasKaminsky ?

**Comment by jancborchardt** [comment] 2017-01-19 14:23
@mario @eppfel yes, I brought up before that the whole »Manage accounts« flow can be done exclusively in the sidebar. We have two ways in the sidebar alone for switching: 1) clicking the avatars and 2) using the dropdown directly below. In that dropdown list we can also have a settings icon to get to the connection settings and the user profile info.

**Comment by tobiasKaminsky** [comment] 2017-01-19 16:07
> What was the reconnect option (key) for...? What are the use cases for that? 

I guess if you want to change your password.

**Comment by tobiasKaminsky** [comment] 2017-01-19 16:12
> @jancborchardt In that dropdown list we can also have a settings icon to get to the connection settings and the user profile info.

As far as I remember the problem is/was that this list of accounts is from android predefined and cannot be changed. And it is just only a plain list which cannot (easy) be expanded to show all those ideas you have. That was the reason to have the separate account management screen.
(@AndyScherzinger please confirm?)

**Comment by tobiasKaminsky** [comment] 2017-01-19 16:13
Is there a API to get the user details?

**Comment by MorrisJobke** [comment] 2017-01-19 17:36
@schiessle @ChristophWurst  Is there an OCS api for updating this information? Is this documented?

**Comment by ChristophWurst** [comment] 2017-01-19 17:39
I don't know, but I can take a look at this if you want :-)

**Comment by mario** [comment] 2017-01-19 18:10
@ChristophWurst any and all info is more than appreciated :)

@tobiasKaminsky OCS api docs mention something like /v1/person/self for getting the data.

**Comment by tobiasKaminsky** [comment] 2017-01-19 20:18
Do we want to update it? I thought this is "just" about showing the infos?

**Comment by MorrisJobke** [comment] 2017-01-19 21:01
> Do we want to update it? I thought this is "just" about showing the infos?

The current user settings also allow to update them and it seems that the API supports this, but I need to check if this should be updatable.

**Comment by mario** [comment] 2017-01-19 21:02
Cool, let me know.

**Comment by AndyScherzinger** [comment] 2017-01-19 21:14
Yes, I can confirm that the drawer menu items are Android menu items by Google design/api and thus single action.
To actually change that one would have to implement a completely custom view part for user listing in the drawer which is possible AFAIK.

The key icon is for changing the password.

**Comment by mario** [comment] 2017-01-24 12:43
@MorrisJobke can you please confirm the endpoint for getting this information?

**Comment by mario** [comment] 2017-01-24 12:50
Including @schiessle because it looks like he needs to do an endpoint for this.

**Comment by MorrisJobke** [comment] 2017-01-24 19:12
> @MorrisJobke can you please confirm the endpoint for getting this information?

I guess that's what @schiessle is working on: #3232

**Comment by mario** [comment] 2017-01-24 21:38
Yup :)

**Comment by AndyScherzinger** [comment] 2017-03-31 14:24
this has been merged to master for the next release.

**Closed by AndyScherzinger** 2017-03-31 14:24 UTC
Labels: design, enhancement, green, pr exists
