### ISSUE TITLE
App Crashed

### ISSUE THREAD

**Issue by zwwko** [nextcloud/android#4412] opened 2019-08-24 17:15 UTC
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Fragment PreviewMediaFragment{cea372e} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:696)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:760)
	at androidx.fragment.app.Fragment.getString(Fragment.java:782)
	at com.owncloud.android.ui.preview.PreviewMediaFragment$LoadStreamUrl.onPostExecute(PreviewMediaFragment.java:564)
	at com.owncloud.android.ui.preview.PreviewMediaFragment$LoadStreamUrl.onPostExecute(PreviewMediaFragment.java:531)
	at android.os.AsyncTask.finish(AsyncTask.java:660)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1534)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1424)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20190810
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: zerofltectc
Model: SM-G9209
Id: NRD90M
Product: zerofltectc

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: G9209KEU2ERI2

**Comment by tobiasKaminsky** [comment] 2019-08-26 13:14
hu, strange I've never saw this.
It seems like a race condition, e.g. opening up media/video, waiting to get an url in background, but in foreground the app was already closed/navigated to something else.

Can this be the cause?

**Comment by ezaquarii** [comment] 2019-09-22 20:15
@tobiasKaminsky This is most likely the problem. This is fixed in #4208 where such operations are no longer running in the UI.

**Closed** 2019-10-01 05:45 UTC
Labels: bug
