### ISSUE TITLE
OOM Crash when moving files to different folder

### ISSUE THREAD

**Issue by SeineEloquenz** [nextcloud/android#12352] opened 2024-01-10 05:39 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Select a number of files (I used about 50)
2. Move them to a different folder

### Expected behaviour

The files are moved successfully

### Actual behaviour

Some files are moved, then the app crashes

### Android version

12

### Device brand and model

Samsung a41

### Stock or custom OS?

Stock

### Nextcloud android app version

3.26.0

### Nextcloud server version

28.0.1

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "Thread-24" java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 424 free bytes and 424B until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
    at org.conscrypt.ConscryptEngine.newResult(ConscryptEngine.java:1370)
    at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:940)
    at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:751)
    at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:716)
    at org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:833)
    at org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:799)
    at org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:772)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:239)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:258)
    at org.apache.commons.httpclient.ChunkedInputStream.getChunkSizeFromInputStream(ChunkedInputStream.java:250)
    at org.apache.commons.httpclient.ChunkedInputStream.nextChunk(ChunkedInputStream.java:221)
    at org.apache.commons.httpclient.ChunkedInputStream.read(ChunkedInputStream.java:176)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at org.apache.commons.httpclient.AutoCloseInputStream.read(AutoCloseInputStream.java:108)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
    at java.io.InputStreamReader.read(InputStreamReader.java:180)
    at com.android.org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1516)
    at com.android.org.kxml2.io.KXmlParser.readName(KXmlParser.java:1563)
    at com.android.org.kxml2.io.KXmlParser.readEndTag(KXmlParser.java:967)
    at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:375)
    at com.android.org.kxml2.io.KXmlParser.nextToken(KXmlParser.java:317)
    at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:329)
    at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:296)
    at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:296)
    at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:296)
    at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:296)
    at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:296)
    at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:128)
    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
    at org.apache.jackrabbit.webdav.xml.DomUtil.parseDocument(DomUtil.java:104)
    at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.getResponseBodyAsDocument(DavMethodBase.java:113)
    at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.getRootElement(DavMethodBase.java:137)
    at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.processResponseBody(DavMethodBase.java:282)
    at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1749)
    at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
    at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
    at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
    at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:197)
    at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:80)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:205)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:405)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:239)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30260090`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `a41`
* Model: `SM-A415F`
* Id: `SP1A.210812.016`
* Product: `a41eea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `A415FXXS5DWI1`

**Comment by jtbx** [comment] 2024-05-10 02:54
Encountering the same issue here. To be fair I was trying to move 2900 files.

[Crash message](https://paste.sr.ht/~jeremy/c3d2a0e6f245d7b5e76a032cdde5489fe85e9d71)

**Comment by joshtrichards** [comment] 2024-07-10 20:19
Duplicate of #9903

**Closed by joshtrichards** 2024-07-10 20:19 UTC
Labels: bug, Version/3026, performance: OOM :brain:
