### ISSUE TITLE
Stürzt ab 

### ISSUE THREAD

**Issue by sevencrazy** [nextcloud/android#5580] opened 2020-03-04 17:57 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e0d7734 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2300)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8147)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWMAR
Model: MAR-LX1A
Id: HUAWEIMAR-L21A
Product: MAR-LX1AEEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.167C431

**Comment by thgoebel** [comment] 2020-03-05 09:12
Duplicate of #2010 ?

**Comment by AndyScherzinger** [comment] 2020-03-09 09:51
Duplicate of #2010

**Comment by AndyScherzinger** [comment] 2020-03-09 09:52
@thgoebel thanks for the report and yes, I very much think that it is a duplicate of #2010, nevertheless thanks for reporting and looking for duplicates ❤️

**Closed by AndyScherzinger** 2020-03-09 09:51 UTC
Labels: bug
