### ISSUE TITLE
Nextcloud Android client crash grid view

### ISSUE THREAD

**Issue by JohannesStroebel** [nextcloud/android#6232] opened 2020-06-06 11:24 UTC
### Steps to reproduce
1. Select "Upload Media"
2. Choose "Grid view"

### Expected behaviour
- grid view

### Actual behaviour
- App crashes

Android version: Android 11

Device model:  Xiaomi Mi 9t

Stock or customized system: Stock

Nextcloud app version: 3.11.1

Nextcloud server version: 18.0.4

Reverse proxy: Nginx

nPN64vuLYxU7SJHRpkU4

**Comment by strugee** [comment] 2020-06-09 05:21
Duplicate of #6133, I believe. If that doesn't sound right, feel free to comment and I can reopen!

**Closed by strugee** 2020-06-09 05:21 UTC
Labels: bug

**Comment by JohannesStroebel** [comment] 2020-06-09 06:37
Yep, I also think so. It is fixed in the latest Dev version 20200530
