### ISSUE TITLE
Device screen sleeps/locks while video is playing

### ISSUE THREAD

**Issue by seanthegeek** [nextcloud/android#9452] opened 2021-12-04 04:35 UTC
### Steps to reproduce
1.  Start playing a video that is longer than the sleep/lock timeout set on your device
2. Do not tap anything or press any buttons

### Expected behaviour
- The app should prevent the device from sleeping/locking while a video is actively playing (i.e., not paused, stopped, or switched to a different app)

### Actual behaviour
- The device locks/sleeps

### Environment data
Android version: 11

Device model: Samsung Galaxy S20

Stock or customized system: Stock

Nextcloud app version: 3.18.0

**Comment by AlvaroBrey** [comment] 2021-12-09 09:31
Duplicate of #9059

**Closed by AlvaroBrey** 2021-12-09 09:31 UTC
Labels: bug
