### ISSUE TITLE
docx restore older version

### ISSUE THREAD

**Issue by ristein** [nextcloud/android#10461] opened 2022-06-30 07:04 UTC
when I click on a docx-file on three dots, details, activities, turning arrow besides new version was created, following error message appears, document gets reverted anyways, app closes after closing error message:

### Cause of error
```java
Exception in thread "Thread-20" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:363)
    at java.lang.Thread.run(Thread.java:923)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `generic`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus7Pro`
* Model: `GM1917`
* Id: `RQ3A.211001.001`
* Product: `OnePlus7Pro`

rooted lineageos4microg

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `eng.root.20220616.195529`

**Comment by joshtrichards** [comment] 2023-10-09 00:08
Duplicate of #11207

Fixed in #11410

Released in v3.26.

**Closed by joshtrichards** 2023-10-09 00:08 UTC
Labels: bug
