### ISSUE TITLE
Crash with null pointer exception

### ISSUE THREAD

**Issue by andreassch** [nextcloud/android#10246] opened 2022-05-14 18:34 UTC
### Steps to reproduce
1. open Nextcloud app
2. hamburger menu > Shared
3. Nextcloud app crashes with null pointer exception

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'com.owncloud.android.utils.FileSortOrder$SortType com.owncloud.android.utils.FileSortOrder.getType()' on a null object reference
    at com.owncloud.android.ui.adapter.OCFileListAdapter.getPopupText(OCFileListAdapter.java:905)
    at me.zhanghai.android.fastscroll.RecyclerViewHelper.getPopupText(RecyclerViewHelper.java:136)
    at me.zhanghai.android.fastscroll.FastScroller.onPreDraw(FastScroller.java:198)
    at me.zhanghai.android.fastscroll.FastScroller.$r8$lambda$fhoCEu3yFeBM02d2QCiuR_Ev5oo(Unknown Source:0)
    at me.zhanghai.android.fastscroll.FastScroller$$ExternalSyntheticLambda1.run(Unknown Source:2)
    at me.zhanghai.android.fastscroll.RecyclerViewHelper$1.onDraw(RecyclerViewHelper.java:52)
    at androidx.recyclerview.widget.RecyclerView.onDraw(RecyclerView.java:4668)
    at android.view.View.draw(View.java:22350)
    at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
    at android.view.View.updateDisplayListIfDirty(View.java:21226)
    at android.view.View.draw(View.java:22081)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
    at android.view.View.draw(View.java:22353)
    at android.view.View.updateDisplayListIfDirty(View.java:21226)
    at android.view.View.draw(View.java:22081)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
    at android.view.View.updateDisplayListIfDirty(View.java:21217)
    at android.view.View.draw(View.java:22081)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
    at android.view.View.updateDisplayListIfDirty(View.java:21217)
    at android.view.View.draw(View.java:22081)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
    at android.view.View.draw(View.java:22353)
    at android.view.View.updateDisplayListIfDirty(View.java:21226)
    at android.view.View.draw(View.java:22081)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
    at android.view.View.updateDisplayListIfDirty(View.java:21217)
    at android.view.View.draw(View.java:22081)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
    at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
    at android.view.View.draw(View.java:22353)
    at android.view.View.updateDisplayListIfDirty(View.java:21226)
    at android.view.View.draw(View.java:22081)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
    at android.view.View.updateDisplayListIfDirty(View.java:21217)
    at android.view.View.draw(View.java:22081)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
    at android.view.View.updateDisplayListIfDirty(View.java:21217)
    at android.view.View.draw(View.java:22081)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
    at android.view.View.updateDisplayListIfDirty(View.java:21217)
    at android.view.View.draw(View.java:22081)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
    at android.view.View.updateDisplayListIfDirty(View.java:21217)
    at android.view.View.draw(View.java:22081)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
    at android.view.View.draw(View.java:22353)
    at com.android.internal.policy.DecorView.draw(DecorView.java:806)
    at android.view.View.updateDisplayListIfDirty(View.java:21226)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:4106)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3833)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3104)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
    at android.view.Choreographer.doCallbacks(Choreographer.java:796)
    at android.view.Choreographer.doFrame(Choreographer.java:731)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7664)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `generic`
* installed from F-Droid

### Device information
* Brand: `Fairphone`
* Device: `FP2`
* Model: `FP2`
* Product: `FP2`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `10043091`

**Comment by AlvaroBrey** [comment] 2022-05-16 08:14
Duplicate of #10227

**Closed by AlvaroBrey** 2022-05-16 08:14 UTC
Labels: bug
