### ISSUE TITLE
App stoped

### ISSUE THREAD

**Issue by Cruguer** [nextcloud/android#13991] opened 2024-11-10 12:23 UTC
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.db.OCUpload.setUploadStatus(com.owncloud.android.datamodel.UploadsStorageManager$UploadStatus)' on a null object reference
    at com.nextcloud.client.jobs.upload.FileUploadHelper.cancelFileUpload(FileUploadHelper.kt:195)
    at com.owncloud.android.ui.adapter.UploadListAdapter.lambda$onBindHeaderViewHolder$1(UploadListAdapter.java:118)
    at com.owncloud.android.ui.adapter.UploadListAdapter.$r8$lambda$Fb3k_Fm9PEVXtymj6A3B7UA69vU(Unknown Source:0)
    at com.owncloud.android.ui.adapter.UploadListAdapter$$ExternalSyntheticLambda18.onClick(D8$$SyntheticClass:0)
    at android.view.View.performClick(Unknown Source:17)
    at android.view.View.performClickInternal(Unknown Source:3)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(Unknown Source:8)
    at android.os.Handler.handleCallback(Unknown Source:2)
    at android.os.Handler.dispatchMessage(Unknown Source:4)
    at android.os.Looper.loopOnce(Unknown Source:182)
    at android.os.Looper.loop(Unknown Source:82)
    at android.app.ActivityThread.main(Unknown Source:123)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
    at com.android.internal.os.ZygoteInit.main(Unknown Source:312)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `Xiaomi`
* Device: `lisa`
* Model: `2109119DG`
* Id: `TKQ1.220829.002`
* Product: `lisa`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `V14.0.13.0.TKOCNXM`

**Comment by joshtrichards** [comment] 2024-11-10 15:32
Duplicate of #13781

If possible, post reproduction steps there. Thanks!

**Closed by joshtrichards** 2024-11-10 15:32 UTC
