### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Bodenseematze** [nextcloud/android#4831] opened 2019-11-14 14:30 UTC
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-0gPLQPfAdPGtPntD4KqBQA==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-0gPLQPfAdPGtPntD4KqBQA==/lib/arm64, /data/app/com.nextcloud.client-0gPLQPfAdPGtPntD4KqBQA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: bq
Device: zangyapro_sprout
Model: Aquaris X2 Pro
Id: PKQ1.190118.001
Product: zangyapro_bq

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 537

**Comment by AndyScherzinger** [comment] 2019-12-02 07:35
Duplicate of #4675, so closing in favor

Brand: Huawei
Device: hwALE-H
Model: ALE-L21

**Closed by AndyScherzinger** 2019-12-02 07:35 UTC
Labels: bug
