### ISSUE TITLE
Photos not loading

### ISSUE THREAD

**Issue by andyxh** [nextcloud/android#1890] opened 2017-12-21 17:18 UTC
### Actual behaviour
-Photos under app never load just says loading

### Expected behaviour
-Photos should load and keep them cached not load all the time from the beginning.

### Environment data
Android version: 8.1.0

Device model: Google Pixel

Nextcloud app version: 2.0.0

Nextcloud server version: 13.0 Beat 3

**Comment by armaccloud** [comment] 2017-12-21 19:25
Duplicate of #1586

**Comment by AndyScherzinger** [comment] 2017-12-22 09:17
Closing this in favor of #1586

The photos might load though while depending on the amount of images on the server this could literally take forever since afaik it is a design flaw in the API due to the fact that atm we do have to load all images at once since the server doesn't offer a paginated API (yet). 
Is this correct @tobiasKaminsky ?

**Closed by AndyScherzinger** 2017-12-22 09:17 UTC

**Comment by mario** [comment] 2017-12-23 11:57
Pagination is not possible for search results

**Comment by andyxh** [comment] 2018-01-03 00:22
The same function works on IOS app. So I think that the android team should figure out a solution

**Comment by tobiasKaminsky** [comment] 2018-01-03 14:39
One possible solution is #1901

**Comment by influenist** [comment] 2018-01-15 19:18
I guess this has to do with gigantic file lists. Might it not be a good option to cache this? Similar like the occ preview app?

In this case, with proper setup the list and the thumbnails would pop up. I mean, now the bottle neck is within fetching the list / do mysql queries. Which slows down the process.

**Comment by galandilias** [comment] 2019-09-28 00:26
Why status is closed? I think that this problem is quite severe - using Photos option in android mobile app generates a long lasting thread on server side consuming one of the cores 100%...
