### ISSUE TITLE
Ability to download/save file/image to device

### ISSUE THREAD

**Issue by fisher60** [nextcloud/android#9956] opened 2022-03-10 18:10 UTC
### Summary
Saving a file to your device requires third party apps that can save an image via a share link. There appears to be now way to download/save a file from the app directly to your device.

### Suggested Change
Add the ability to "save" or "save as" an image from the details/settings/properties options related to a file, rather than just the current sync/download option which does not make a file accessible to the user on a device.

### Alternatives Attempted
My current method to save a file to my device is to send a share link to a third party app/service that will then allow me to download the image. There is also a third party app that will save a share link to a file on android. This is tedious and very unlike any other cloud/media apps.

### Additional context
A very common operation for me on any cloud storage platform is to upload and share content. Nextcloud has sharing functionality built-in, but does not provide any way to save a file to an android device. Sometimes it is far more convenient to send an actual file, rather than a link to that file. Many individuals, services, companies, etc. will not trust a link to an individual's domain to download a file.

**Comment by AlvaroBrey** [comment] 2022-03-10 18:11
Duplicate of #9519

**Closed by AlvaroBrey** 2022-03-10 18:11 UTC
Labels: enhancement
