### ISSUE TITLE
3.0.0 RC1: Crash in grid view when selecting share photo before it has loaded thumbnail

### ISSUE THREAD

**Issue by macau23** [nextcloud/android#1974] opened 2018-01-17 08:13 UTC
### Actual behaviour
The Nextcloud Android app crashes if I select a photo from the grid view before the thumbnail has loaded.

### Expected behaviour
No crash.
 
### Steps to reproduce
1. Open folder with photos
2. Switch to grid view
3. If thumbnails have not been loaded: crash

### Environment data
Android version: 7.0

Device model: S8

Stock or customized system: Stock

Nextcloud app version: 3.0.0 RC1

Nextcloud server version: 13.0.0 RC1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2018-01-17 08:25
I tried it and opened multiple images where no thumbnail is available.
Right after clicking on it I see the default image thumbnail and shortly after that the screen adapted image is downloaded.

Can you provide us some LogCat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by macau23** [comment] 2018-01-17 15:09
I will create a new image directory (it's not crashing any more on the current one) and send you a logcat.

**Comment by macau23** [comment] 2018-01-18 14:35
Having some problems with LogCat because my phone is not rooted, and I cannot run it from a terminal at the moment.

However I can consistently crash the app: the trick is to click on the sharing icon in the top-right corner of the unloaded thumbnail in the grid view.

**Comment by tobiasKaminsky** [comment] 2018-01-19 06:30
I tried to reproduce it, but cannot. For me it is working.
It also should be no difference if the thumbnail is loaded or not as sharing is done with file infos and those are available, otherwise you would not see the file.
A logcat would really really be valuable here. With a computer it is possible to have a logcat without root.

**Comment by AndyScherzinger** [comment] 2018-02-08 14:54
@macau23 hard to tell without a log file but yes it is possible that it is a duplicate of #2085

**Comment by macau23** [comment] 2018-02-13 08:59
Thanks @AndyScherzinger soon I will be able to uninstall Dropbox :)

**Comment by macau23** [comment] 2018-02-13 08:59
Oops wrong button

**Comment by AndyScherzinger** [comment] 2018-02-13 10:43
@macau23 could this folder be shared (as is non-sensitive data)? If so could you create a test account on the server and send it to android at nextcloud dot com, with a reference to this issue please?

**Comment by macau23** [comment] 2018-02-13 11:00
It's got family photos in it, I can't share it. Can I give you anything else instead?

**Comment by AndyScherzinger** [comment] 2018-02-13 11:11
@macau23 hard to say, the issue with crashing folders is that it is often related to sorting issues with Java8 (not Android 8) while non of the devs ever could reproduce a crashing folder due to this issue. We just see stack traces while that doesn't offer a hint since these crashes are based on the underlying data :/
So in case you have any other folder with non-sensitive data, that would be awesome (for debugging).

**Comment by macau23** [comment] 2018-02-13 11:20
I had other folders that crashed, but they don't crash any more since I re-created them with the same data. I will try moving the contents of the folder elsewhere, then accessing it. If it doesn't crash I will move the contents back again and test again.

**Comment by macau23** [comment] 2018-02-19 12:12
@AndyScherzinger I recreated the folder and now the problem is gone.

**Comment by AndyScherzinger** [comment] 2018-02-19 12:40
@macau23 hmm, too bad. Is there anything that changed? Only thing I can think of is the timestamp of the creation date of the folder itself... :/

**Comment by macau23** [comment] 2018-02-19 13:26
@AndyScherzinger The contents are identical (they are synced from elsewhere).

**Comment by tobiasKaminsky** [comment] 2018-03-20 06:41
Closing it for now, if it happens again, we have to debug this harder...

**Closed by tobiasKaminsky** 2018-03-20 06:41 UTC
Labels: bug, needs info/discussion
