### ISSUE TITLE
Nextcloud Crash when clicking on "geteilt"

### ISSUE THREAD

**Issue by LuftschloesserUser** [nextcloud/android#10326] opened 2022-06-02 16:43 UTC
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'com.owncloud.android.utils.FileSortOrder$SortType com.owncloud.android.utils.FileSortOrder.getType()' on a null object reference
    at com.owncloud.android.ui.adapter.OCFileListAdapter.getPopupText(OCFileListAdapter.java:905)
    at me.zhanghai.android.fastscroll.RecyclerViewHelper.getPopupText(RecyclerViewHelper.java:136)
    at me.zhanghai.android.fastscroll.FastScroller.onPreDraw(FastScroller.java:198)
    at me.zhanghai.android.fastscroll.FastScroller.$r8$lambda$fhoCEu3yFeBM02d2QCiuR_Ev5oo(Unknown Source:0)
    at me.zhanghai.android.fastscroll.FastScroller$$ExternalSyntheticLambda1.run(Unknown Source:2)
    at me.zhanghai.android.fastscroll.RecyclerViewHelper$1.onDraw(RecyclerViewHelper.java:52)
    at androidx.recyclerview.widget.RecyclerView.onDraw(RecyclerView.java:4668)
    at android.view.View.draw(View.java:22528)
    at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
    at android.view.View.updateDisplayListIfDirty(View.java:21389)
    at android.view.View.draw(View.java:22254)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
    at android.view.View.draw(View.java:22538)
    at android.view.View.updateDisplayListIfDirty(View.java:21389)
    at android.view.View.draw(View.java:22254)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
    at android.view.View.updateDisplayListIfDirty(View.java:21380)
    at android.view.View.draw(View.java:22254)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
    at android.view.View.updateDisplayListIfDirty(View.java:21380)
    at android.view.View.draw(View.java:22254)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
    at android.view.View.draw(View.java:22538)
    at android.view.View.updateDisplayListIfDirty(View.java:21389)
    at android.view.View.draw(View.java:22254)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
    at android.view.View.updateDisplayListIfDirty(View.java:21380)
    at android.view.View.draw(View.java:22254)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
    at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
    at android.view.View.draw(View.java:22538)
    at android.view.View.updateDisplayListIfDirty(View.java:21389)
    at android.view.View.draw(View.java:22254)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
    at android.view.View.updateDisplayListIfDirty(View.java:21380)
    at android.view.View.draw(View.java:22254)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
    at android.view.View.updateDisplayListIfDirty(View.java:21380)
    at android.view.View.draw(View.java:22254)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
    at android.view.View.updateDisplayListIfDirty(View.java:21380)
    at android.view.View.draw(View.java:22254)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
    at android.view.View.updateDisplayListIfDirty(View.java:21380)
    at android.view.View.draw(View.java:22254)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
    at android.view.View.draw(View.java:22538)
    at com.android.internal.policy.DecorView.draw(DecorView.java:812)
    at android.view.View.updateDisplayListIfDirty(View.java:21389)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:647)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:4407)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4134)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3387)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2178)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8712)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
    at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
    at android.view.Choreographer.doFrame(Choreographer.java:1049)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:245)
    at android.app.ActivityThread.main(ActivityThread.java:8024)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `Nord`
* Model: `AC2003`
* Id: `RP1A.201005.001`
* Product: `Nord_EEA`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `2203101723`

**Comment by AlvaroBrey** [comment] 2022-06-03 11:59
Duplicate of https://github.com/nextcloud/android/issues/10227

**Closed by AlvaroBrey** 2022-06-03 11:59 UTC
