### ISSUE TITLE
`OutOfMemoryError` in `ReadFolderRemoteOperation`

### ISSUE THREAD

**Issue by tlianza** [nextcloud/android#13353] opened 2024-08-03 22:40 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open a folder with thousands of files (in my case instant upload/camera)
2. Multiple spinners
3. Crash

### Expected behaviour

Not crash

### Actual behaviour

Stack trace:

### Cause of error
```java
Exception in thread "Thread-18" java.lang.OutOfMemoryError: Failed to allocate a 144 byte allocation with 4424016 free bytes and 4320KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
    at java.util.Arrays.copyOf(Arrays.java:3553)
    at java.util.Arrays.copyOf(Arrays.java:3522)
    at java.util.ArrayList.grow(ArrayList.java:244)
    at java.util.ArrayList.grow(ArrayList.java:251)
    at java.util.ArrayList.add(ArrayList.java:461)
    at java.util.ArrayList.add(ArrayList.java:474)
    at org.apache.harmony.xml.dom.NodeListImpl.add(NodeListImpl.java:47)
    at org.apache.harmony.xml.dom.InnerNodeImpl.getChildNodes(InnerNodeImpl.java:59)
    at org.apache.jackrabbit.webdav.xml.ElementIterator.seek(ElementIterator.java:130)
    at org.apache.jackrabbit.webdav.xml.ElementIterator.<init>(ElementIterator.java:56)
    at org.apache.jackrabbit.webdav.xml.ElementIterator.<init>(ElementIterator.java:82)
    at org.apache.jackrabbit.webdav.xml.DomUtil.getChildren(DomUtil.java:345)
    at org.apache.jackrabbit.webdav.MultiStatusResponse.createFromXml(MultiStatusResponse.java:453)
    at org.apache.jackrabbit.webdav.MultiStatus.createFromXml(MultiStatus.java:185)
    at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.processResponseBody(DavMethodBase.java:282)
    at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1749)
    at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
    at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
    at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
    at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:192)
    at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:62)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:413)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:247)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:387)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `shiba`
* Model: `Pixel 8`
* Id: `AP2A.240705.005`
* Product: `shiba`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `11942872`

### Android version

14

### Device brand and model

Pixel 8

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.2

### Nextcloud server version

29.0.3

### Using a reverse proxy?

Yes

**Comment by joshtrichards** [comment] 2024-11-02 13:11
Duplicate of #9903

**Closed by joshtrichards** 2024-11-02 13:11 UTC
Labels: bug, performance: OOM :brain:, stable-3.29
