### ISSUE TITLE
continuos/heavy data transfer

### ISSUE THREAD

**Issue by mega-stoffel** [nextcloud/android#13824] opened 2024-10-19 14:56 UTC
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Since upgrading to 3.30.1 my Nextcloud app is using WiFi and mobile data like crazy and I see a Nextcloud message all the time on my phone.
Before the upgrade, everything was fine.

What's wrong here?!
[Image](https://github.com/user-attachments/assets/54ccc654-fa1d-4827-bba8-5f3629b49722)

### Expected behaviour

it should only transfer new files.

### Actual behaviour

it transfers way too much data.

### Android version

latest GrapheneOS

### Device brand and model

Pixel 6

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.30.1

### Nextcloud server version

Hub 9

### Using a reverse proxy?

No

**Comment by aikencz** [comment] 2024-10-19 15:00
I can confirm this. It obviously synchronizes all files although it is configured to not do so. This synchronization quickly consumes the storage space, generate network load, drains battery, and causes heating of the device. I had to uninstall Nextcloud completely for now.

**Comment by aikencz** [comment] 2024-10-19 15:04
It can be a duplicate of https://github.com/nextcloud/android/issues/13738.

**Comment by joshtrichards** [comment] 2024-10-19 15:47
Duplicate of #13738

**Closed by joshtrichards** 2024-10-19 15:47 UTC
Labels: bug, 0. Needs triage

**Comment by mega-stoffel** [comment] 2024-10-28 13:13
still the same behavoir for me, even with 3.30.3.
It's not syncing all my Nextcloud, but only one folder, again and again.
