### ISSUE TITLE
Random "Preparing auto upload" notification

### ISSUE THREAD

**Issue by viktorix** [nextcloud/android#13490] opened 2024-08-29 17:43 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Notification randomly shows up. All auto-uploading is disabled. Notification will popup even when I'm not using the phone. I don't know how to reproduce it.

### Expected behaviour

If auto uploading is disabled, no notifications should randomly popup.

### Actual behaviour

Randomly auto upload notification will appear. 
![Screenshot_20240826_224227_Maps](https://github.com/user-attachments/assets/9505c414-9f09-46ed-a91d-a5406ca8cf83)

### Android version

14

### Device brand and model

Samsung Galaxy s24 Ultra

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.2

### Nextcloud server version

30 RC3 (latest on c.nc.c)

### Using a reverse proxy?

I don't know

### Android logs

I'm a beta tester in Play Store, but I can't find any logs.

### Additional information

Never had this issue before until recently. I always had my auto-uploads disabled. Nothing was set to upload. This notification issue began after I tried testing auto-upload and restrictions on auto-uploads: Wifi, battery, etc. Someone mentioned on Reddit the app wasn't respecting Wifi/battery settings and uploading regardless of those options. I couldn't replicate that issue. After I finished testing, I disabled auto uploads. They are still disabled. Yet randomly, maybe 2-3 times per day, the notification will show up and then disappear after a few minutes. Nothing is uploaded as far as I can tell.

**Comment by joshtrichards** [comment] 2024-08-30 22:20
Duplicate of #12596 
PR merged #13015 for v3.30.x

**Closed by joshtrichards** 2024-08-30 22:20 UTC
Labels: bug
