### ISSUE TITLE
Photo loading spinner does not stop

### ISSUE THREAD

**Issue by mohasi** [nextcloud/android#6410] opened 2020-07-04 12:17 UTC
### Steps to reproduce
1. Have some photos in cloud
2. Select "photos" from hamburger menu

### Expected behaviour
Load photo thumbnails and be done with it.

### Actual behaviour
Loads thumbnails but keeps the loading spinner spinning forever.

### Environment data
Android version: 10
Device model: lavender
Stock or customized system: Lineage OS 17.1
Nextcloud app version: 3.12.0
Nextcloud server version: 18.0.6

**Comment by tobiasKaminsky** [comment] 2020-07-06 08:58
How many images do you have roughly? 
It seems that your server cannot generate the results quickly enough.

**Comment by jakobroehrl** [comment] 2020-07-06 11:41
The spinner is always on the bottom. So if you have only some pics you will always see it. 
Shot from try.nextcloud:
![Screenshot_20200706-133850](https://user-images.githubusercontent.com/24530680/86589656-575a0500-bf8e-11ea-823f-fa67a62e617e.jpg)

**Comment by mohasi** [comment] 2020-07-06 13:43
I always have it, it never goes away no matter how long you wait. I only have like 10 or so smallish pictures.

**Comment by jakobroehrl** [comment] 2020-07-06 15:16
It's not a bug, its how it is implemented this time. 
Maybe the photos view should be overworked, there are some issues about it

**Comment by mohasi** [comment] 2020-07-06 16:35
@jakobroehrl So if a loading spinner spins all the time it is a normal feature? Wow. So why not add another spinner on every page and keep it spinning, if its good for photos its good for all the pages. It defeats the meaning of it, the spinner is meant to mean "loading", if its loading all the time then its obviously not loading, if it is then it should be a bug.

**Comment by jakobroehrl** [comment] 2020-07-07 05:13
Absolutly right. I'm only posting how it is implemented now. 
I'm happy it's working and there are always things to improve...

**Comment by AndyScherzinger** [comment] 2020-07-07 07:45
> So if a loading spinner spins all the time it is a normal feature? Wow.

No, not a feature. No worries. This is a bug.

@tobiasKaminsky easy to reproduce, just create a new user on your server, login, go to the photos view via the menu, see the pictures been loaded as per the screenshot in https://github.com/nextcloud/android/issues/6410#issuecomment-654182323
- Just reproduced this (running Nc19)

**Comment by AndyScherzinger** [comment] 2020-10-31 17:47
@axheli we do not assign work to releases (as in planning) but schedule releases and what is done until the date gets shipped. Same for 3.14.1 any fix done until the release will ship.

Not sure though if @tobiasKaminsky did a fix already 🤔

**Comment by tobiasKaminsky** [comment] 2020-11-12 14:41
Hm. I tested it, and it seems that the endless spinner is shown only if there are too few images, so that it is directly finished with one query from server…
Can you confirm that this does not happen if you have e.g. 40 images?

**Comment by axheli** [comment] 2020-11-12 15:01
on 3.14.0 RC2 works with no issues. The program is laggy but photos are loading with no issues.

**Comment by tobiasKaminsky** [comment] 2020-11-13 07:58
Thanks for confirmation, then I close this.

**Closed by tobiasKaminsky** 2020-11-13 07:58 UTC
Labels: approved, bug
