### ISSUE TITLE
collabora 4.0.1 or richdocuments 3.2.2 broke android document editing

### ISSUE THREAD

**Issue by himpierre** [nextcloud/android#3690] opened 2019-03-02 09:04 UTC
### Actual behaviour
- When loading an office document via android app circle is spinning forever. Document does
not open. 

### Expected behaviour
- Document opens.

### Environment data
Android version: 9

Device model: LG G6

Stock or customized system: Customized. Havoc OS.

Nextcloud app version: 3.5.0

Nextcloud server version: 15.0.5

cheers
t.

**Comment by tobiasKaminsky** [comment] 2019-03-04 07:41
When the spinner loads forever then the url/collabora server is not loading correct.
Is this working via web ui?

**Comment by himpierre** [comment] 2019-03-04 07:48
>Is this working via web ui?

Yes. Absolutely.

**Comment by himpierre** [comment] 2019-03-04 07:49
It feels like https://github.com/nextcloud/richdocuments/issues/390

**Comment by tobiasKaminsky** [comment] 2019-03-04 09:14
According to @juliushaertl this is fixed via https://github.com/nextcloud/richdocuments/pull/426 and a new version will be available soon.

**Comment by himpierre** [comment] 2019-03-04 11:19
Thanks.

**Comment by e-alfred** [comment] 2019-03-04 14:58
I can reproduce the problem with both the Nextcloud Android dev app as well as 3.5.0 and Collabora CODE 4.0.1 and Richdocuments 3.2.2.

**Comment by himpierre** [comment] 2019-03-04 16:48
3.2.3 works as expected (aside from https://bugs.documentfoundation.org/show_bug.cgi?id=123437). Thanks.

**Comment by kopierschnitte** [comment] 2019-03-04 17:13
Yes, seems to be fixed. Working as expected here.

**Closed** 2019-03-04 18:40 UTC
Labels: bug
