### ISSUE TITLE
Auto upload configuration screen shows all images in a folder

### ISSUE THREAD

**Issue by yoyko** [nextcloud/android#9604] opened 2021-12-22 11:59 UTC
### Steps to reproduce
1. Open Settings -> Auto upload
2. Add a folder with enough images if there is none

### Expected behaviour
- Two lines of images for each folder are show, the last image has a `+1234` number overlayed if there are more

### Actual behaviour
- All images are shown, the ones after the second line have the `+1234` overlay on them.
![Screenshot_20211222-122202-1](https://user-images.githubusercontent.com/1326093/147088336-8b755452-6b30-4cd2-9b72-282ca8496459.png)

This makes it actually impossible to get to the configured folders after a large one (well, disabling a folder moves it after all enabled... but if you have two big folders...)

### Can you reproduce this problem on https://try.nextcloud.com?
Didn't try, as I don't expect this to be a server issue...

### Environment data
Android version: 9

Device model: Sony XZ1 Compact (G8441)

Stock or customized system: stock

Nextcloud app version: 3.18.0 (Nov 18 2021, Google play store)

Nextcloud server version: 21.0.5

Reverse proxy:

### Logs
I can upload if needed ;)

**Comment by AlvaroBrey** [comment] 2021-12-22 14:04
Duplicate of #9311

**Closed by AlvaroBrey** 2021-12-22 14:04 UTC
Labels: bug

**Comment by yoyko** [comment] 2021-12-22 14:09
Ahh, sorry, forgot to search through closed issues ;(.
Will know better next time...
