### ISSUE TITLE
Impossible to reproduce any video in Android App

### ISSUE THREAD

**Issue by byVilla** [nextcloud/android#7602] opened 2020-12-04 13:35 UTC
### Steps to reproduce
1. Through Android App, I'm going to Photos folder and click on a video. The video format is MP4.
2. The application try to load the video.
3. I always retrieve the same error message "The built-in media player can not play the file".

### Expected behaviour
- The application must load and play the video.

### Actual behaviour
- I always retrieve the same error message "The built-in media player can not play the file".

### Environment data
Android version: 10

Device model: Xiaomi A2

Nextcloud app version: 3.14.1

Nextcloud server version: 19.0.5

**Comment by tobiasKaminsky** [comment] 2020-12-16 09:26
Duplicate of #7460

**Closed by tobiasKaminsky** 2020-12-16 09:26 UTC
Labels: bug
