### ISSUE TITLE
URI scheme matches non-Nextcloud websites

### ISSUE THREAD

**Issue by siccovansas** [nextcloud/android#9856] opened 2022-02-17 22:48 UTC
### Steps to reproduce
1. Open https://is.gd/YN6F19 in Firefox for Android

### Expected behaviour
- The is.gd URL shortener should redirect to https://www.gofundme.com/f/fv92rh-handprothese?qid=e83e8ec53d51bf809f81e50e0585e82e which should be viewed in Firefox for Android 

### Actual behaviour
- Nextcloud app opens saying "Invalid URL"

### Environment data
Android version: 12

Device model: Samsung Galaxy S10

Stock or customized system: stock

Nextcloud app version: 3.19.0

Nextcloud server version: 22.2.4

Reverse proxy: Nginx

The URI scheme code is here: https://github.com/nextcloud/android/blob/41d1698ea339afca345aced6b691b35c9ed3f32e/src/main/AndroidManifest.xml#L110

It matches on any URL with `/f/` somewhere in its path. As you can see GoFundMe uses this pattern as well. So redirects/links to GoFundMe are opened in Nextcloud which doesn't work :).

**Comment by AlvaroBrey** [comment] 2022-02-18 08:44
Duplicate of #9703

**Closed by AlvaroBrey** 2022-02-18 08:44 UTC
Labels: bug
