### ISSUE TITLE
Crash when Clicking through Images

### ISSUE THREAD

**Issue by maximaximal** [nextcloud/android#10405] opened 2022-06-16 15:00 UTC
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Fragment PreviewImageFragment{330cb57} (a10c0a4f-14cf-483f-800e-2a899a2fb06b) not attached to a context.
    at androidx.fragment.app.Fragment.requireContext(Fragment.java:919)
    at androidx.fragment.app.Fragment.getResources(Fragment.java:983)
    at com.owncloud.android.ui.preview.PreviewImageFragment.lambda$setErrorPreviewMessage$2$com-owncloud-android-ui-preview-PreviewImageFragment(PreviewImageFragment.java:723)
    at com.owncloud.android.ui.preview.PreviewImageFragment$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
    at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java:351)
    at android.view.View.performClick(View.java:7448)
    at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
    at android.view.View.performClickInternal(View.java:7425)
    at android.view.View.access$3600(View.java:810)
    at android.view.View$PerformClick.run(View.java:28309)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7715)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `Fairphone`
* Device: `FP4`
* Model: `FP4`
* Id: `RKQ1.210503.001`
* Product: `FP4eea`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `FP3W`

**Comment by Tiam-Abderezai** [comment] 2022-06-17 03:09
@tobiasKaminsky May I please have your permission to be assigned to this issue?

**Comment by maximaximal** [comment] 2022-06-17 09:52
Thank you for your quick response!

Okay, here is my setup: Nextcloud has external storage mounted into some users. This external storage is a local folder, which is a mounted NFS share from a different host. On this share I have a bunch of images, each being between 10-15MB big JPEGS. Next to the images I also have some RAWs and .xmp files from darktable, which should not be an issue though I think. 

When now quickly scrolling through these images, it always took some time to load them, and the Android Nextcloud App showed me a warning of not getting a preview image and if I wanted to download the full image. Regardless of this warning, the image loaded after a few seconds. Now, after opening and closing some images, scrolling between them quickly (around 2 to 3 images per second), the UI started to lag a bit, afterwards it crashed. I clicked on the small image previews that were slowly loading into the app and then swiped between the mix of already loaded (and locally cached) images and still loading ones.

If I have to guess what is going on, it looked like some mix up in locally caching the images, getting new ones and mixing them with the previews, as the images are quite big. Maybe some concurrency issue with futures or something, where it gets messed up when the image is arriving but something else is already in the place? I don't know exactly of course, this is just how it felt like when it happened. After re-opening and scrolling a bit slower, everything worked fine again though :)

Yes, of course I give you my permission! Thanks again!

**Comment by AlvaroBrey** [comment] 2022-06-17 10:09
@Tiam-Abderezai assigned. Should be as easy as adding a null check for `getContext` in the affected method

**Comment by Tiam-Abderezai** [comment] 2022-06-19 04:48
@maximaximal thank you for the detailed explanation! Can you also please provide the following:
- NextCloud app version:
- NextCloud server version:
- Android version:
- Device model:
- Stock or customized system:

**Comment by Tiam-Abderezai** [comment] 2022-06-19 05:41
@AlvaroBrey according to the crash logs this seems to be the affected area in **PreviewImageFragment.java** for method **setErrorPreviewMessage()**:

```java
if (activity != null) {
                 activity.requestForDownload(getFile());
           } else {
                  Snackbar.make(binding.emptyListView,
                  getResources().getString(R.string.could_not_download_image),
                  Snackbar.LENGTH_INDEFINITE).show();
}
```
So I'd have to provide some exception handling in the else statement, does that sound right? Please correct me if I'm wrong or where I can look for.

@maximaximal Can you provide the steps you take that cause the crash? for example: 
1) open the app
2) click on the "On device" or "Media"
3) scroll up and down through the pictures
4) suddenly crashes with message "xyz"

This way I can try to reproduce the error as accurately as possible :slightly_smiling_face: thanks!

**Comment by Tiam-Abderezai** [comment] 2022-06-21 10:30
@AlvaroBrey Thanks!!! I made the change, but I'm trying to figure out the [contribution process](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#contribution-process). Please forgive my ignorance, but I'm unsure how to exactly proceed: do I 1) create a new branch from master (forked) 2) what do I name the bugfix branch 3) what commit message do I include (is there a standard to follow for commit messages / branch names).

**Comment by tobiasKaminsky** [comment] 2022-06-21 12:20
> 1) create a new local branch from master (forked and cloned locally)

yes :)



> 2) what do I name the local bugfix branch

some call it bugfix/10405/check-context or something like "check-context" only



> what commit message do I include (is there a standard to follow for commit messages / branch names).

I usually add the issue number, so maybe something like:
Fix #10405
Show only error snackbar if context is available

**Comment by Tiam-Abderezai** [comment] 2022-06-21 13:35
Super!!! Thanks @tobiasKaminsky !

**Comment by andyxheli** [comment] 2022-07-06 19:41
Hi All, not sure if this is similar https://github.com/nextcloud/android/issues/9302 but I'm having the same issue when scrolling throw the media tab and clicking on images

**Closed** 2022-08-03 14:30 UTC
Labels: bug, approved, pr exists
