### ISSUE TITLE
Android client v3.5.0 auto upload custom folder selection

### ISSUE THREAD

**Issue by parthdmaniar** [nextcloud/android#3619] opened 2019-02-13 18:28 UTC
### Actual behaviour
- This happens when setting up custom folder for auto-upload. Once your browse to root ( / ) folder, you can't browse back to the file system (including memory card). This behavior continues perpetually and I'm unable to add any new custom  folders. Only automatically detected folders are now available for synchronization set-up. 

### Expected behaviour
- User should be able to browse back in the file system.
 
### Steps to reproduce
1. Open nextcloud application.
2.  Go to auto upload
3. Set up a custom folder
4. Select local folder
5. Browse to root folder ( / ).

After this I am unable to browse back or to any folder. I am now unable to add any custom folder.

### Environment data
Android version: 9.0

Device model: Samsung Galaxy S9+ (SM-G965F)

Stock or customized system: No

Nextcloud app version: 3.5.0

Nextcloud server version: 15.0.4.0

#### Web server error log
None as this is not a web server issue.

#### Nextcloud log (data/nextcloud.log)
None as this is not a nextcloud server issue.

**Comment by tobiasKaminsky** [comment] 2019-02-14 07:36
Duplicate of https://github.com/nextcloud/android/issues/3449

**Closed by tobiasKaminsky** 2019-02-14 07:36 UTC
Labels: bug
