### ISSUE TITLE
Media Tab loading issues

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/android#7245] opened 2020-11-06 13:16 UTC
It will not load more when I go to the bottom it only loads 134 and under the media tab there's no option to categorize by date etc under the file tab I've already selected by newest first #6820

**Comment by axheli** [comment] 2020-11-06 13:16
#6820

**Comment by tobiasKaminsky** [comment] 2020-11-11 09:37
It should automatically load more once you reached bottom.
You should see a spinning circle there.
If not, it means that server does not give client any more new images…

You have more than 134 images?

**Comment by jakobroehrl** [comment] 2020-11-11 10:36
I know the problem, too. I have it since month. 
On my setting I have a image folder but it shows only 41 images in android. In the browser with the Photo App it's working. 
When I share the image folder with another user, android shows all the images on the other user account.
Is there a way to see, which data the server returns?

**Comment by axheli** [comment] 2020-11-11 13:24
Yes I have alot more then 134 pictures this only happens via android app no issues with ios and web ui

**Comment by tobiasKaminsky** [comment] 2020-11-13 07:27
So it happens with dev version, but not with 3.14.0 RC2?

**Comment by jakobroehrl** [comment] 2020-11-13 07:53
I still have the issue in 3.14.0 RC2

**Comment by axheli** [comment] 2020-11-19 03:42
@tobiasKaminsky  I just updated to 3.14.0 and photos tab not working

**Comment by tobiasKaminsky** [comment] 2020-11-19 07:04
Only 8? It should at least try to fetch 30…
I fear that this is a server problem, but the devs are currently too busy to look into it.

**Comment by axheli** [comment] 2020-11-19 12:37
> Only 8? It should at least try to fetch 30…
> I fear that this is a server problem, but the devs are currently too busy to look into it.

I don't have this issue on the IOS platform and it just started when I updated to 3.14.0 I don't think this is a server issue

**Comment by axheli** [comment] 2020-11-20 02:57
@tobiasKaminsky  just downgraded back to 3.14.0 RC2  from 3.14.0 and the photos tab is now working

**Comment by tobiasKaminsky** [comment] 2020-11-20 06:40
> I don't think this is a server issue

Sort of…We changed the way to query the server for images and videos (media instead of photos) and thus this breaks somehow on some servers.

**Comment by axheli** [comment] 2020-11-20 13:18
@tobiasKaminsky the server is a fresh new install and why don't I not have issues on the IOS platform?

**Comment by axheli** [comment] 2020-11-21 00:34
> > I don't think this is a server issue
> 
> Sort of…We changed the way to query the server for images and videos (media instead of photos) and thus this breaks somehow on some servers.

I uninstalled the program and reinstalled it it's working on 8.1.0. but we still need to keep this ticket open for the new media tab

**Comment by axheli** [comment] 2020-11-21 03:21
> > I don't think this is a server issue
> 
> Sort of…We changed the way to query the server for images and videos (media instead of photos) and thus this breaks somehow on some servers.

I'm not sure! All I can say is that I'm not having any issues with the ios app.

**Comment by tobiasKaminsky** [comment] 2020-11-23 09:59
@marinofaggiana what photos/video do you how on iOS app in "media" tab?

**Comment by marinofaggiana** [comment] 2020-11-23 10:15
@tobiasKaminsky the search query ?

**Comment by tobiasKaminsky** [comment] 2020-11-23 10:45
> @tobiasKaminsky the search query ?

Yes

**Comment by marinofaggiana** [comment] 2020-11-24 10:16
https://github.com/nextcloud/ios-communication-library/blob/3abaa65cf70f7dfa8a7d0df2277d4eda14d7cfd1/NCCommunication/NCCommunicationModel.swift#L529

but I use different query :  

1 for detect the news images (from #now to first date image)
2 for detect new images in the period from the first visible image to last visible image 
3 for detect old images with a recursive called: 
  - start search last data -30 gg
  - if not find search last data -90 gg
  - if not find search last data -180 gg
  - if not find search last data distantPast

**Comment by tobiasKaminsky** [comment] 2020-11-25 11:10
As far as I can read this, you also include shared files, right?
But this then takes either very long on Android (even when I limit it to 50 items) or it even crashes the server.
Can you see how long those query takes for you, on our c.nc.c server?

**Comment by marinofaggiana** [comment] 2020-11-25 11:18
First question, you use a date limit ? <d:lt> ... <d:gt> ?

**Comment by tobiasKaminsky** [comment] 2020-11-25 11:29
Yes, via getlastmodified less than $timestamp.

**Comment by marinofaggiana** [comment] 2020-11-25 12:50
No, for the "old" images, 

example lt = time last image, gt ?

> As far as I can read this, you also include shared files, right?

sure

> Can you see how long those query takes for you, on our c.nc.c server?

this night because now is slow (for me)

**Comment by axheli** [comment] 2020-11-25 15:13
@tobiasKaminsky Just an update when you first install the app and go under the photos tab its starts to load the content properly but once you close then app and go back into the photos tab it will only show 29 files. Very wired

**Comment by marinofaggiana** [comment] 2020-11-25 16:20
Tested now after a clear cache for c.nc.c practically instant for 300 images

**Comment by axheli** [comment] 2020-11-25 16:24
@marinofaggiana I cleared cache under my app  3.14.1 RC2 and still shows 28 files under the photos tab. Also, wanted to comment never has issues on the IOS platform it works rock solid.

**Comment by axheli** [comment] 2020-11-25 19:27
Sorry please disregard the two  open references I accidently added them to this ticket. Sorry about that.

**Comment by tobiasKaminsky** [comment] 2020-11-26 08:02
Looping in @skjnldsv 
It seems that this query is fast enough: 5-10s on first query:
```
<?xml version="1.0" encoding="UTF-8"?>
<d:searchrequest xmlns:d="DAV:" xmlns:oc="http://nextcloud.com/ns">
    <d:basicsearch>
        <d:select>
            <d:prop>
                <d:getcontenttype/>
                <d:resourcetype/>
                <d:getcontentlength/>
                <d:getlastmodified/>
                <d:getetag/>
                <oc:permissions xmlns:oc="http://owncloud.org/ns"/>
                <oc:id xmlns:oc="http://owncloud.org/ns"/>
                <oc:size xmlns:oc="http://owncloud.org/ns"/>
                <oc:favorite xmlns:oc="http://owncloud.org/ns"/>
            </d:prop>
        </d:select>
        <d:from>
            <d:scope>
                <d:href>/files/{{ username  }}</d:href>
                <d:depth>infinity</d:depth>
            </d:scope>
        </d:from>
        <d:where>
					<d:and>
						<d:or>
            <d:like><d:prop><d:getcontenttype/></d:prop><d:literal>image/%</d:literal></d:like>
							<d:like><d:prop><d:getcontenttype/></d:prop><d:literal>video/%</d:literal></d:like>
						</d:or>
						<d:gt><d:prop><d:getlastmodified/></d:prop><d:literal>1604994646</d:literal></d:gt>
						</d:and>
        </d:where>
        <d:orderby>
            <d:order>
                <d:prop>
                    <d:getlastmodified/>
                </d:prop>
                <d:descending/>
            </d:order>
        </d:orderby>
        <d:limit>
            <d:nresults>10</d:nresults>
        </d:limit>
    </d:basicsearch>
</d:searchrequest>
```
This searches for any image/video type, but only for files which were modified in last 10 days.

Next query could then be 10-20 days ago, as @marinofaggiana suggests.

What do you think?

**Comment by skjnldsv** [comment] 2020-12-02 14:50
> What do you think?

We don't get all images and videos.
We don't know if they can be displayed at all. Photos only get jpeg/png/heic.
https://github.com/nextcloud/photos/blob/7c718eae57b2a5a9a27ce3e0bce2d3bffff7057e/lib/AppInfo/Application.php#L36-L54
You also do't filter by owner, meaning you will include external storage and shares. And this will blow up in a lot of instances. ping @icewind1991 and @rullzer 
Ref https://github.com/nextcloud/server/pull/17941

**Comment by tobiasKaminsky** [comment] 2020-12-04 12:28
> It seems that this query is fast enough: 5-10s on first query:
> 

I tried above query on our instance and it does not fail.
So if it turns out that this query works, it would be good to change it also on photos app, or?

Can you please try it?

**Comment by axheli** [comment] 2021-01-08 13:44
@marinofaggiana any updates on this ?

**Comment by saywebsolutions** [comment] 2021-02-14 21:52
my media/photos tab is broken now too; i can supply any debug/version/log info as well if needed, just let me know. thank you

**Comment by tobiasKaminsky** [comment] 2021-02-18 07:12
I asked over at https://github.com/nextcloud/server/issues/20839#issuecomment-781111092 again, so get feedback.

**Comment by kuzmos** [comment] 2021-03-01 11:09
After updating the Nextcloud server to 21 a new error started appearing in server log while trying to display Media from Android app:
`Doctrine\DBAL\Query\QueryException: More than 1000 expressions in a list are not allowed on Oracle.`

**Comment by tobiasKaminsky** [comment] 2021-03-01 12:49
Android client itself only starts one query to server, so this is something @nextcloud/server-triage needs to look into why the query explodes…

**Comment by rlalak** [comment] 2021-04-01 21:31
Similar problems. Media tab stopped at some point and now there is no new photos. Additionally when I scroll down sometimes I see 132 photos, sometimes 89 and can't load more.
Everything works fine on web.

**Comment by axheli** [comment] 2021-04-02 01:16
@tobiasKaminsky any updates on this ? Can we have someone look into this issue ? This issue only seems to happen on the android app no issues on the IOS platform.

**Comment by svenb1234** [comment] 2021-04-02 05:59
> Tested now after a clear cache for c.nc.c practically instant for 300 items

I also fail to understand why "almost instant" is possible on iOS for 300 items and **including** shared files

> Looping in @skjnldsv
> It seems that this query is fast enough: 5-10s on first query:

but for the Android user experience, 5-10 seconds is good enough with less items and shared files have to be excluded.

What makes it technically impossible to have the same instant user experience on Android, including shared files?

Why does the product owner of the Android app accept that the media tab is broken for that long? Not only in terms of speed but also in terms of usability, i.e. not loading all images and not showing the latest images first without any possibility to navigate. The latter two are even regressions.

Please remove the commits that introduced the change from the photos to the media tab if it is not possible to fix the media tab in the short term. The photos tab was slow it did fail but, as sad as that might sound given its performance, it did work a lot better than the current media tab.

> seems like Nextcloud dose not seem to focus too hard on Android platform and focuses more on the IOS platform I hope there can be a resolution to this soon.

Either no one within the nextcloud team is using the Android app or those that do, do not use the photos/media tab. Otherwise I cannot explain how it can happen that it is so slow compared to iOS and now even completely broken. Adding to that, the iOS/Android devs do not seem to communicate and compare their apps' UX and functionality regularly. Neither does there seem to be a product owner that takes over that job for them and sets priorities for the sprint planning in order to achieve that goal.

**Comment by axheli** [comment] 2021-04-02 12:09
@svenb1234 well said 👏 hopefully they will fix the app on the android platform because it sucks nothing but crashes and issues. Waiting on a resolution!

**Comment by Exist2Resist** [comment] 2021-04-10 06:49
> > Tested now after a clear cache for c.nc.c practically instant for 300 items
> 
> I also fail to understand why "almost instant" is possible on iOS for 300 items and **including** shared files
> 
> > Looping in @skjnldsv
> > It seems that this query is fast enough: 5-10s on first query:
> 
> but for the Android user experience, 5-10 seconds is good enough with less items and shared files have to be excluded.
> 
> What makes it technically impossible to have the same instant user experience on Android, including shared files?
> 
> Why does the product owner of the Android app accept that the media tab is broken for that long? Not only in terms of speed but also in terms of usability, i.e. not loading all images and not showing the latest images first without any possibility to navigate. The latter two are even regressions.
> 
> Please remove the commits that introduced the change from the photos to the media tab if it is not possible to fix the media tab in the short term. The photos tab was slow it did fail but, as sad as that might sound given its performance, it did work a lot better than the current media tab.
> 
> > seems like Nextcloud dose not seem to focus too hard on Android platform and focuses more on the IOS platform I hope there can be a resolution to this soon.
> 
> Either no one within the nextcloud team is using the Android app or those that do, do not use the photos/media tab. Otherwise I cannot explain how it can happen that it is so slow compared to iOS and now even completely broken. Adding to that, the iOS/Android devs do not seem to communicate and compare their apps' UX and functionality regularly. Neither does there seem to be a product owner that takes over that job for them and sets priorities for the sprint planning in order to achieve that goal.

Well said man, the whole idea of commits is that if something is broken you roll it back. It seems to me like the devs here don't understand that. How are you going to expect people to pay for your hosting when your eco system is broken, and then provide an experience like that. It's funny because I was going to recommend nextcloud at work for an enterprise solution but with this, forget it man. Mickey Mouse show over here.

**Comment by axheli** [comment] 2021-04-12 15:03
@tobiasKaminsky any updates on this?

**Comment by blizzz** [comment] 2021-04-26 13:12
> : More than 1000 expressions in a list are

@kuzmos if that is not reported in the server repository yet (please search), do it there and please include the backtrace (should be logged along).

**Comment by andyxheli** [comment] 2021-04-26 20:25
> More than 1000 expressions in a list are

There's already a ticket for the 1000 expressions i put that in a while back but that has nothing to do with this issue or the root cause of this issue.

**Comment by saywebsolutions** [comment] 2021-04-26 20:50
@tobiasKaminsky have you investigated this anymore? maybe you could roll back the breaking changes until you have a chance to test more, or work with @marinofaggiana or the other IOS app devs to find why their media area still works but the android app doesn't? i fear otherwise the media tab on android will be broken indefinitely

**Comment by andyxheli** [comment] 2021-05-21 12:33
@AndyScherzinger anyway you can help with this issue please 🙂

**Comment by AndyScherzinger** [comment] 2021-05-21 19:06
Hi @andyxheli, how could I help?

**Comment by andyxheli** [comment] 2021-05-21 19:15
> Hi @andyxheli, how could I help? 

Thank you so much for your response! Is there a way someone from dev can looking into this media issue currently the media tab dose not display the photos it loads a few and it stops loading.

**Comment by tobiasKaminsky** [comment] 2021-05-26 09:59
Can you test the apk in https://github.com/nextcloud/android/pull/8482 ?
This will search for images/videos only in your local cloud, no shares, no federated shares.
It should be the same like photos app on web.

(that was the reason why it was delayed so long, to find a better solution to also have results for shared files, but server is too busy right now, so we maybe better go with this query, which is also in sync with photos app).

**Comment by craig0990** [comment] 2021-05-26 10:50
👋🏻 I'm wandering in to just say: I also have this issue (although I haven't attempted any serious debugging, I can poke my server and the Android client if anyone has any pointers on what would help).

And having just tried: the APK linked by @tobiasKaminsky in https://github.com/nextcloud/android/pull/8482#issuecomment-848641271 immediately fixes this for me.

I don't have any other users / federated connections at the moment, so I couldn't say whether it affects that functionality or not.

Photos that didn't previously appear are now appearing, and the previous limit of about 135 files (after about three infinite scroll loads) is now extended to ...well, I have 15,000 photos, so I'm not sure 😛 But over 500 so far.

**Comment by andyxheli** [comment] 2021-05-26 20:14
@tobiasKaminsky Thank you very much! The APK looks good the media tab is now working.

**Comment by svenb1234** [comment] 2021-05-26 20:52
> (that was the reason why it was delayed so long, to find a better solution to also have results for shared files, but server is too busy right now, so we maybe better go with this query, which is also in sync with photos app).

I still do not get why the same server serves the iOS app like a breeze but not the Android app for the same feature.

**Comment by tobiasKaminsky** [comment] 2021-05-27 04:53
iOS is caching the results and then retrieves only the newest ones, whereas Android does not cache it and therefore it is as fast as the server is.
As this issue is about not loading at all, I would consider this as fixed.
Enhancing it to cache is then a potential next step at some point, but it is not that easy, if you e.g. upload an old image (with old timestamp) and you would then not see it, as it is cached…

**Comment by tobiasKaminsky** [comment] 2021-05-27 04:59
PR is: https://github.com/nextcloud/android-library/pull/632

**Comment by tobiasKaminsky** [comment] 2021-05-27 07:14
Will be in 3.16.1

**Closed by tobiasKaminsky** 2021-05-27 07:14 UTC
Labels: approved, bug
