### ISSUE TITLE
Continuous crashes (SQLiteBlobTooBigException) in FileSyncAdapter

### ISSUE THREAD

**Issue by didierm** [nextcloud/android#5481] opened 2020-02-16 19:15 UTC
Many crashes, every day.
Started with client version **30090290** (if I remember well), still occuring with version **30100190**.

Sync'ing involves about ~ 2300 files, dispersed over ~ 260 folders, for a total of ~ 4GB.

May be related to issues #3358 , #4409 , #4414 ?
(all these issues were closed due to 'staleness', but the problem is clearly not fixed).

```
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=6758, totalRows=5122
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:895)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:157)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:190)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:299)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:669)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:320)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:474)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:410)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:478)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:369)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:228)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:181)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:268)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.onPerformSync(FileSyncAdapter.java:180)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: davinci
Model: Mi 9T
Id: PQ3A.190801.002
Product: lineage_davinci

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.append.20191021.233716
```

**Comment by tobiasKaminsky** [comment] 2020-02-19 14:27
> Sync'ing involves about ~ 2300 file

What do you mean with "sync"? 
- click on folder and select sync to actually download them
- click on top right "sync account"

**Comment by ezaquarii** [comment] 2020-02-19 17:42
@tobiasKaminsky what kind of blobs are we pushing through cursor? Cursors have some strict memory limits.

**Comment by didierm** [comment] 2020-02-19 17:50
> > Sync'ing involves about ~ 2300 file
> 
> What do you mean with "sync"?
> 
>     * click on folder and select sync to actually download them

Indeed, that is my use case : usually, after files have been uploaded from another (e.g. PC) platform to my cloud instance, I manually select the data I want to have available on my Android phone.

(the other way around, new photographs or other image data are automatically uploaded from my phone to my cloud instance (backup function).)

**Comment by ezaquarii** [comment] 2020-02-19 22:01
This is the source of exception:
https://android.googlesource.com/platform/frameworks/base.git/+/master/core/jni/android_database_SQLiteConnection.cpp#770

So I looked inside and here is how it works:
1. it tries to fill the window with row data
2. if it fails before it reached interesting data, it resets the cursor window and tries to add it again
3. if it fails to add a row at this stage (with empty window), it assumes that the row is too big and throws

Copy function doesn't do anything particularly interesting. It can fail in 2 places:
1. beginning, where it tries to allocate new row [where it tries to allocate new row](https://android.googlesource.com/platform/frameworks/base.git/+/master/core/jni/android_database_SQLiteConnection.cpp#583)
2. copying data, most likely of `TEXT` type [during putStringOrBlob()](https://android.googlesource.com/platform/frameworks/base.git/+/master/core/jni/android_database_SQLiteConnection.cpp#597
)

Now, failing mode for 1 can be deduced from here:
https://android.googlesource.com/platform/frameworks/base/+/master/libs/androidfw/CursorWindow.cpp#180

I don't believe we're dealing with read-only window, so I'll skip this avenue.

It can most probably fail duling call to `allocRowSlot()` or `putStringOrBlob() -> alloc()`
[`putStringOrBlob() -> alloc()`](https://android.googlesource.com/platform/frameworks/base/+/master/libs/androidfw/CursorWindow.cpp#312)


Note that there is no dynamic memory allocation anywhere there - all works by moving pointers pointing to a fixed-sized memory region. We can exclude memory fragmentation issues. So - as long as the housekeeping is ok - this should be deterministic.

I believe we deal with 2 possible issues:
1. either our database contain large `TEXT` fields that cannot fit into a cursor window
2. the cursor logic has a bug or it's state is somehow corrupted
3. sqlite returns rubbish size of the `TEXT` field (unlikely - it's very well tested)

@tobiasKaminsky Let's try exploring 2 options:

1. Do we have any - even hypothetically - large entities in that table?
2. If this is a random corruption in platform code, maybe we can retry the operation?

**Comment by ezaquarii** [comment] 2020-02-19 22:35
@tobiasKaminsky Also, please note the recursive calls to `deleteDirectory()` and `delete()`. I'm not sure what are the consequences of this, but it looks scary.

**Comment by ezaquarii** [comment] 2020-02-19 22:39
@didierm can you tell us how deep is the directory hierarchy and how many files are in each directory? Order of magnitude is enough. I'm thinking if we could re-create similar conditions somehow.

Also, please tell us if those files have some atypical names, maybe very long paths are involved?

**Comment by donou** [comment] 2020-03-26 13:50
This might be a temporary, nontechnical sollution.
 
In my case:
- **the issue** was caused by a combination of deleted folders on the server and not synced with the client and a "bad" stored data (undiagnosed)
- and **the solution** was to delete the client "data" and not simply the cache.
 
Initialy I avoided the error by disabling the network connection and enabling it in a safe location af the app, in order to check settings and current uploads and, after cleaning up, multiple "delete data" actions were needed to actualy delete the data.
  
### Failures

- Reinstalling or relogin used the same old stored data
- Other time consuming steps were applied but without succes (force sync and a combo of network disable-enable)
 
### Configuration

- MI8
- MIUI 11.0.6
- 3.10.1 client / 3.11.beta client
- disabled MIUI optimizations

**Comment by didierm** [comment] 2020-04-27 08:52
Updating the BR to prevent closing.
This issue still occurs with version 30110151.

@ezaquarii 
In reply to https://github.com/nextcloud/android/issues/5481#issuecomment-588510182 : 
NC top user directory (= _data/{username}/_) : 
* 346 directories
* 2522 files
* maximum folder depth (including _./files/_) : 7
* maximum filename length (including subfolders, relative to top user directory) : 211 characters
* maximum filename length (full path) : 244 characters
* largest filesize : 288483661 bytes



```
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=6758, totalRows=5122
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:895)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:157)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:191)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:135)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:185)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:135)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:185)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:135)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:115)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:299)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:671)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:320)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:474)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:410)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:478)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:369)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:228)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:181)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:268)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.onPerformSync(FileSyncAdapter.java:180)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110151
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: davinci
Model: Mi 9T
Id: PQ3A.190801.002
Product: lineage_davinci

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.append.20191021.233716
```

**Comment by tobiasKaminsky** [comment] 2020-04-28 09:48
Duplicate of #5891

**Closed by tobiasKaminsky** 2020-04-28 09:48 UTC
Labels: bug, needs info/discussion
