### ISSUE TITLE
Directory deleted

### ISSUE THREAD

**Issue by crashcoq** [nextcloud/android#11841] opened 2023-07-26 15:17 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Created a directory in nextcloud
Share a file with android app
Delete dir on nextcloud 
Share a file with android app
On change directory (not exist), crash nextcloud 

### Cause of error
```java
Exception in thread "Thread-8" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30250090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a52sxq`
* Model: `SM-A528B`
* Id: `TP1A.220624.014`
* Product: `a52sxqeea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `A528BXXS4EWG1`

### Actual behaviour

Created a directory in nextcloud
Share a file with android app
Delete dir on nextcloud 
Share a file with android app
On change directory (not exist), crash nextcloud 

### Android version

12

### Device brand and model

SAMSUNG

### Stock or custom OS?

Stock

### Nextcloud android app version

Latest 

### Nextcloud server version

Latest

### Using a reverse proxy?

I don't know

**Comment by joshtrichards** [comment] 2023-08-03 14:35
Hi @crashcoq - Thanks for the report.

This is a duplicate of #11207. It was recently addressed in #11410 pending the next release. Please close this issue out to avoid confusion, if you agree you report looks like #11207. Thanks!

**Closed** 2023-08-03 20:21 UTC
Labels: bug
