### ISSUE TITLE
Indeed and Nextcloud Android app

### ISSUE THREAD

**Issue by pmatra** [nextcloud/android#11396] opened 2023-02-17 21:50 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Click on an Indeed URL or button in Outlook and it opens the Nextcloud app. 

### Expected behaviour

It should open the Indeed app or chrome. 

### Actual behaviour

Opens the Nextcloud app. 

### Android version

13

### Device brand and model

Z fold 3 

### Stock or custom OS?

Stock

### Nextcloud android app version

Most recent 

### Nextcloud server version

25.0.3

### Using a reverse proxy?

No

### Android logs

Not available

### Server error logs

```bash
Nil
```

### Additional information

Nil

**Comment by AlvaroBrey** [comment] 2023-02-18 12:04
Duplicate of #9703

**Closed by AlvaroBrey** 2023-02-18 12:04 UTC
Labels: bug
