### ISSUE TITLE
Nextcloud android app c|ash after updrade

### ISSUE THREAD

**Issue by digver** [nextcloud/android#13886] opened 2024-10-26 12:11 UTC
### Cause of error
```java
Exception in thread "main" android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2e6f935 u0 com.nextcloud.client/androidx.work.impl.foreground.SystemForegroundService c:com.nextcloud.client}
    at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2271)
    at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2239)
    at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2557)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8705)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300290`
* Build flavor: `generic`

### Device information
* Brand: `google`
* Device: `cheetah`
* Model: `Pixel 7 Pro`
* Id: `AP3A.241005.015`
* Product: `cheetah`

### Firmware
* SDK: `35`
* Release: `15`
* Incremental: `12366759`

**Comment by joshtrichards** [comment] 2024-10-26 13:04
Duplicate of #12706

**Closed by joshtrichards** 2024-10-26 13:04 UTC
