### ISSUE TITLE
"RuntimeException: Unable to pause activity" while hitting Back in the login flow

### ISSUE THREAD

**Issue by pmartis** [nextcloud/android#8682] opened 2021-07-09 10:36 UTC
I just tried the app, select the option of my own server and go back because it is not what I am looking for. I want to synchronize to a NFS server.

But as I got this error message, I send it to you, if it can help.

```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to pause activity {com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@82f3fff
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4622)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4573)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4525)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:228)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2065)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7631)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@82f3fff
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1435)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1564)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:664)
	at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.onInactive(UsbConnectionDispatcher.java:131)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.ensureStateInactive(SecurityKeyManager.java:316)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.refreshActiveState(SecurityKeyManager.java:290)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.onActivityPaused(SecurityKeyManager.java:333)
	at android.app.Application.dispatchActivityPaused(Application.java:474)
	at android.app.Activity.dispatchActivityPaused(Activity.java:1306)
	at android.app.Activity.onPause(Activity.java:2233)
	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:388)
	at com.owncloud.android.ui.activity.BaseActivity.onPause(BaseActivity.java:84)
	at com.owncloud.android.ui.activity.FileActivity.onPause(FileActivity.java:253)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onPause(FileDisplayActivity.java:1254)
	at android.app.Activity.performPause(Activity.java:8011)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1508)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4612)
	... 13 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210704
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: lge
Device: mdh40lm
Model: LM-Q630
Id: QKQ1.200730.002
Product: mdh40lm_fne

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2113120400e9f.OPEN_EU_DS
```

**Comment by strugee** [comment] 2021-07-17 06:58
Possible duplicate of #8585, although I'm really not sure. https://github.com/nextcloud/android/issues/8585#issuecomment-880642685 seems to indicate yes?

**Comment by AlvaroBrey** [comment] 2021-09-02 13:23
Yes, this is a duplicate of https://github.com/nextcloud/android/issues/8585

**Closed by AlvaroBrey** 2021-09-02 13:23 UTC
Labels: bug
