### ISSUE TITLE
Mirror of Nextcloud Web Application to Android

### ISSUE THREAD

**Issue by Pavithra-S1** [nextcloud/android#10671] opened 2022-08-24 05:25 UTC
Hello,

I need a solution for Nextcloud Web application of all apps in single bundled Mobile application for  Android.

Nextcloud has separate applications for Files, Talk, Deck etc… I want all those applications in a single application how can we make this solution workaround.

1.Is there any possibility to get a single bundled application of Nextcloud
2.Can we convert it as a hybrid mobile app from Web
3.How we can build a native apps which is clubbed together of Nextcloud

**Comment by AlvaroBrey** [comment] 2022-08-24 07:03
Duplicate of #10617

**Closed by AlvaroBrey** 2022-08-24 07:03 UTC
Labels: enhancement

**Comment by Pavithra-S1** [comment] 2023-01-23 07:49
Hello all , 

Finally I have found a solution for the above query . 

The theme is to have a single Nextcloud Mobile application which should have all the apps like Talk , Files etc .,( a replica of Nextcloud Browser application) And one of the simplest ways to implement this is "WebView". By using this method we can bring the exact browser interface in our Android and IOS devices .

Here I have given my source code file , Please check it out  and it will help you


[test29.zip](https://github.com/nextcloud/android/files/10477623/test29.zip)

**Comment by joshtrichards** [comment] 2023-10-11 22:38
@Pavithra-S1 There's nothing stopping you from using the shortcut function in, say, Mobile Chrome to add an icon to your Android device that opens up the web based version of NC. I use various things that way and mix and match as deemed appropriate for my own workflows.
