### ISSUE TITLE
nextcloud android 3.30.1 began syncing all files to phone without user interaction

### ISSUE THREAD

**Issue by motsu35** [nextcloud/android#13825] opened 2024-10-19 20:49 UTC
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

My phone auto-updated nextcloud to 3.30.1 last night (f-droid version of nextcloud if that matters). After arriving home, i noticed my phone start to get warm. Im unsure if i opened the nextcloud app at some point before this, but i assume so since this didnt happen immediately after the update. After unlocking my phone, i saw 100+ files being synced with nextcloud in the notification drawer. This was odd since i only push files to nextcloud (camera auto uploads mostly), so to see so many files listed in the notification drawer was alarming.

I checked the all files main view, and saw the little blue arrow circle next to all of the files. Checking in the "on device" view, it has almost all of the folders in nextcloud as being on my device. these include old photos not taken on my cellphone, as well as word documents and OS installer iso files that i would have never chosen to sync to my phone.

I selected all of the "on device" files and chose to delete the local copy. I closed nextcloud and reopened it, and there were folders already being re-added to the on device page. Uninstalling 3.30.1 and installing 3.30.0 fixed the issue.

the only one odd thing about my nextcloud setup is that I changed domain names at one point and did so with a rewrite rule on my reverse proxy instead of changing it in the nextcloud settings. I don't think this would cause any weird behavior, but if the reproduction isn't apparent, that might be part of the puzzle

### Expected behaviour

don't auto sync files that i dont explicitly try and sync. my nextcloud data is larger than my phones storage... auto syncing everything is a great way to have a non functional phone!

### Actual behaviour

most of this is in the repro section. nextcloud started auto syncing ALL files to my phone erroneously. 

### Android version

14

### Device brand and model

fairphone 5

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.30.1

### Nextcloud server version

29.0.7

### Using a reverse proxy?

Yes

### Additional information

phone OS: calyxOS 5.12.1

unable to add logs since i had to force stop / uninstall the new nextcloud android app since it was using up all my storage and heating the phone up badly.

**Comment by mrnicelliott** [comment] 2024-10-19 21:06
I have exactly the same issue.

Came to my phone about half an hour ago and if was burning hot.

I can't even work out how you would trigger a sync of all files at once, even by accident.  Definitely a bug.

I have two nextcloud servers connected. One personal, one work. Both AIO and up to date. But it's currently only attempting to sync the work one.

I may have to uninstall the app as its not responding when I try to "cancel sync".

This needs serious attention.

I'm on Fairphone4

**Comment by Alifoss** [comment] 2024-10-19 21:10
This is a duplicate, join the club on #13738

**Comment by solonovamax** [comment] 2024-10-19 21:24
> This is a duplicate, join the club on #13738 
> 
> For now there's yet to be an official statement to be made regarding this small inconvenience.

it is very much not a "small" inconvenience.

**Comment by spaetz** [comment] 2024-10-20 06:46
I just used up 60GB of mobile data out of my monthly allowance of 12GB. Outch.

**Comment by DonQ99** [comment] 2024-10-20 09:06
Same issue. 

Fairphone 4
Android 13
Nextcloud 3.30.1

Is there a way to know, if this in fact is a **SPY ATTACK?** 
I need an official statement (error? corruption?) and a way to know that this statement is from a trustworthy source. 

Can you help @joshtrichards  ?

Somebody made this list of apparently connected (if not the same) issues:

https://github.com/nextcloud/android/issues/13780
https://github.com/nextcloud/android/issues/13773
https://github.com/nextcloud/android/issues/13772
https://github.com/nextcloud/android/issues/13771
https://github.com/nextcloud/android/issues/13752
https://github.com/nextcloud/android/issues/13747
https://github.com/nextcloud/android/issues/13738

**Comment by bristow** [comment] 2024-10-20 10:46
Same here...

**Comment by joshtrichards** [comment] 2024-10-20 11:31
Duplicate of #13738

**Closed by joshtrichards** 2024-10-20 11:31 UTC
Labels: bug, 0. Needs triage

**Comment by wazoox** [comment] 2024-10-21 11:03
I've uninstalled 3.30.1 and installed 3.30. Now ALL MEDIA (several thousands pictures) are popping with an "upload conflict" error. So the battery still going down though the phone is plugged in... So I'm desinstalling again and go fishing for the 3.29.2 (which works fine on another phone I have).

**Comment by canoine** [comment] 2024-10-21 11:52
> For now there's yet to be an official statement to be made regarding this **small** inconvenience.
Enough. You guys are so arrogant for months, please go down your piedestal quickly.

No, this is NOT a "SMALL" inconvenience. Some people are paying this "small" inconvenience, a high price. Cellphones contracts and overcharging could be very expensive in some countries, and you don't care.

**Comment by spaetz** [comment] 2024-10-21 12:24
> > For now there's yet to be an official statement to be made regarding this **small** inconvenience.
> 
> Enough. You guys are so arrogant for months, please go down your piedestal quickly.

*Sigh*,  the person who has written above comment seem not seem to be affiliated in the slightest with Nextcloud, so careful with assuming anything about Nextcloud's attitude from it.

Also, it seems very much written in a sarcastic manner, so careful with assuming someone actually considers this a triviality.
☮️✌️

**Comment by canoine** [comment] 2024-10-21 12:27
> _Sigh_, the person who has written above comment seem not seem to be affiliated in the slightest with Nextcloud, so careful with assuming anything about Nextcloud's attitude from it.
> 
> Also, it seems very much written in a sarcastic manner, so careful with assuming someone actually considers this a triviality. ☮️✌️

Oh, dear. Please forgive me.
Nextcloud guys drive me crazy.

**Comment by joshtrichards** [comment] 2024-10-21 12:28
Please see #13738, as already noted, where this matter is being tracked.
