### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by gvfnk** [nextcloud/android#10318] opened 2022-06-01 22:08 UTC
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter <set-?>
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
    at android.app.ActivityThread.access$900(ActivityThread.java:153)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5451)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: Exception in thread "main" java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter <set-?>
    at com.owncloud.android.lib.resources.status.OCCapability.setRichDocumentsProductName(OCCapability.kt)
    at com.owncloud.android.datamodel.FileDataStorageManager.createCapabilityInstance(FileDataStorageManager.java:2121)
    at com.owncloud.android.datamodel.FileDataStorageManager.getCapability(FileDataStorageManager.java:2029)
    at com.owncloud.android.utils.theme.CapabilityUtils.getCapability(CapabilityUtils.java:83)
    at com.owncloud.android.utils.theme.CapabilityUtils.getCapability(CapabilityUtils.java:51)
    at com.owncloud.android.utils.theme.ThemeUtils.getDefaultDisplayNameForRootFolder(ThemeUtils.java:46)
    at com.owncloud.android.ui.activity.ToolbarActivity.updateActionBarTitleAndHomeButton(ToolbarActivity.java:132)
    at com.owncloud.android.ui.activity.DrawerActivity.updateActionBarTitleAndHomeButton(DrawerActivity.java:647)
    at com.owncloud.android.ui.activity.FileDisplayActivity.updateActionBarTitleAndHomeButton(FileDisplayActivity.java:1576)
    at com.owncloud.android.ui.activity.ToolbarActivity.setupToolbar(ToolbarActivity.java:98)
    at com.owncloud.android.ui.activity.ToolbarActivity.setupHomeSearchToolbarWithSortAndListButtons(ToolbarActivity.java:122)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onCreate(FileDisplayActivity.java:264)
    at android.app.Activity.performCreate(Activity.java:6323)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
    at android.app.ActivityThread.access$900(ActivityThread.java:153)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5451)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `asus`
* Device: `ASUS_Z010`
* Model: `ASUS_Z010D`
* Id: `MMB29P`
* Product: `WW_Phone`

### Firmware
* SDK: `23`
* Release: `6.0.1`
* Incremental: `WW_Phone-13.8.26.76-20161230`

**Comment by AlvaroBrey** [comment] 2022-06-02 15:38
Duplicate of #10197

**Closed by AlvaroBrey** 2022-06-02 15:38 UTC
