### ISSUE TITLE
[ crash ] android.view.InflateException: Binary XML file line #7: Error inflating class android.webkit.WebView

### ISSUE THREAD

**Issue by leela52452** [nextcloud/android#5303] opened 2020-01-25 03:24 UTC
************ CAUSE OF ERROR ************

android.view.InflateException: Binary XML file line #7: Error inflating class android.webkit.WebView
	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
	at com.owncloud.android.authentication.AuthenticatorActivity.onNewIntent(AuthenticatorActivity.java:908)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1211)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1223)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2482)
	at android.app.ActivityThread.performNewIntents(ActivityThread.java:2494)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2503)
	at android.app.ActivityThread.access$1600(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5358)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	... 24 more
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x2040003
	at android.content.res.Resources.getText(Resources.java:299)
	at android.content.res.Resources.getString(Resources.java:385)
	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:686)
	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:610)
	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:632)
	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:781)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:620)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:557)
	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:316)
	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:268)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:265)
	at android.webkit.WebView.<init>(WebView.java:561)
	at android.webkit.WebView.<init>(WebView.java:496)
	at android.webkit.WebView.<init>(WebView.java:479)
	at android.webkit.WebView.<init>(WebView.java:466)
	... 27 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: LYF
Device: u220_tsl_011
Model: LS-4001
Id: LMY47D
Product: u220_tsl_011

************ FIRMWARE ************
SDK: 22
Release: 5.1
Incremental: eng.root.20161122.200724

**Comment by KaratekHD** [comment] 2020-01-25 15:24
Same problem here.

**Comment by AndyScherzinger** [comment] 2020-01-26 19:13
Duplicate of #4943

**Closed by AndyScherzinger** 2020-01-26 19:13 UTC
Labels: bug
