### ISSUE TITLE
Request: deleting uploaded photos after a specified time.

### ISSUE THREAD

**Issue by sosed213** [nextcloud/android#8070] opened 2021-02-26 11:25 UTC
Please make it possible to configure the deletion of uploaded photos from your smartphone after a specified time.

After I take the pictures, I may need them on the device for another month, and then I delete them. But doing it manually is not convenient.

And when a lot of photos accumulate on the device, the application starts to slow down and freeze.

I beg you, thanks in advance!

**Comment by joshtrichards** [comment] 2023-12-21 18:36
Duplicate of #2323

**Closed by joshtrichards** 2023-12-21 18:37 UTC
Labels: enhancement, feature: auto upload
