### ISSUE TITLE
Username autocomplete for comments

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/android#4599] opened 2019-10-02 12:11 UTC
Would be nice if we can `@mention` other people in comments on files :smile: 

Currently, this isn't implemented.

A common use case is when you want to call somebody's attention to a file that is shared with them in a bigger folder share, or a file that has been shared some time ago.  You just `@mention` them and they will be notified by the awesomeness that is our notifications system :+1:

**Comment by AndyScherzinger** [comment] 2019-10-07 18:48
I think @mario did something similar for the talk client already 😃

**Comment by DavidMndz** [comment] 2019-10-10 22:25
This would also resolve the problem for users that have different username and display name. 

In the web interface the comments work with the autocomplete even if we use the display name instead of the user name. Something like this in the Android app would be perfect.

**Comment by jospoortvliet** [comment] 2019-10-23 14:12
Hi @DavidMndz - if you are doing a PoC to test Nextcloud in a enterprise environment, I suggest you get in contact with our sales team so we can prioritize fixing issues that you encounter. It can otherwise take a long time before they get fixed.

**Comment by DavidMndz** [comment] 2020-03-29 21:58
Hi @jospoortvliet, sorry for the long delay but I did not saw your comment until now.

I am not working on the Nextcloud as a enterprise environment but for personal purposes. However in my instance I have that use case in order to follow same naming convention than the user id for the email. Said that, I think this might be also interesting for companies working with Nextcloud as usually the user id follows some rules that are not just 'the name'.

Right now I do not have enough time to dig into the code but I will be glad to help with testing if needed.

**Comment by joshtrichards** [comment] 2023-10-13 20:33
Duplicate of #3999

**Closed by joshtrichards** 2023-10-13 20:33 UTC
Labels: enhancement
