### ISSUE TITLE
Nextcloud App crashes when sharing image files to an E2E encrypted folder

### ISSUE THREAD

**Issue by Rex-0x7CB** [nextcloud/android#13548] opened 2024-09-11 06:16 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open gallery app
2. Select 2 images (Multi Select)
3. Share -> Nextcloud
4. There's already an E2E encrypted folder. I created a new folder under this encrypted folder
5. The app crashed.
6. I repeated steps 1-3 again, the new folder I created had been successfully created but when I selected it, the app crashed again. 

### Expected behaviour

App shouldn't crash

### Actual behaviour

App crashes

### Android version

Check attached logs

### Device brand and model

Samsung M33

### Stock or custom OS?

Stock

### Nextcloud android app version

Check attached logs

### Nextcloud server version

29.0.6

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.canWrite()' on a null object reference
    at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onCreateOptionsMenu(ReceiveExternalFilesActivity.java:1023)
    at android.app.Activity.onCreatePanelMenu(Activity.java:4633)
    at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:520)
    at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3429)
    at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
    at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
    at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
    at android.view.Choreographer.doFrame(Choreographer.java:1069)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8919)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290390`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `m33x`
* Model: `SM-M336BU`
* Id: `UP1A.231005.007`
* Product: `m33xins`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `M336BUXXS9EXH1`

**Comment by joshtrichards** [comment] 2024-11-01 20:52
Duplicate of #13498

**Closed by joshtrichards** 2024-11-01 20:52 UTC
Labels: bug, feature: encryption (client-side), feature: sharing to/from other apps, performance: NPE :no_entry_sign:, stable-3.29
