### ISSUE TITLE
NEXTCLOUD APP uploade error

### ISSUE THREAD

**Issue by Hydropolis** [nextcloud/android#9778] opened 2022-01-30 10:04 UTC
************ CAUSE OF ERROR ************

android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
	at android.database.CursorWindow.<init>(CursorWindow.java:108)
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
	at androidx.room.InvalidationTracker$1.checkUpdatedTable(InvalidationTracker.java:417)
	at androidx.room.InvalidationTracker$1.run(InvalidationTracker.java:388)
	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:776)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWVNS-H
Model: HUAWEI VNS-L31
Id: HUAWEIVNS-L31
Product: VNS-L31

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: C432B418

**Comment by AlvaroBrey** [comment] 2022-01-31 09:54
Hello @Hydropolis, thanks for your report. Can you give us some steps to reproduce this crash? Does it happen every time?

**Comment by AlvaroBrey** [comment] 2022-01-31 10:31
Duplicate of https://github.com/nextcloud/android/issues/8853

If you have extra info please post it there.

**Closed by AlvaroBrey** 2022-01-31 10:31 UTC
Labels: bug, needs info/discussion
