### ISSUE TITLE
Sorting in Upload Filebrowser not working

### ISSUE THREAD

**Issue by realthargor** [nextcloud/android#2568] opened 2018-05-10 11:07 UTC
### Actual behaviour
- selecting a sorting method in the file selection dialog to upload doesn't change the order of the files

### Expected behaviour
- Files a sorted by selected method
 
### Steps to reproduce
1. Open the upload dialog
2. navigate to a folder with multiple files
3. change sorting method

### Environment data
Android version: 7.1.2

Device model: OnePlus X

Stock or customized system: Lineagos 14.1

Nextcloud app version: 3.1.0

Nextcloud server version: 13.0.1

**Comment by AndyScherzinger** [comment] 2018-05-10 13:14
Hi @realthargor, thanks for reporting this issue, it is a duplicate of #2467 though and has been fixed for the next stable release 3.2.0 via #2566

**Closed by AndyScherzinger** 2018-05-10 13:14 UTC
