### ISSUE TITLE
Crash, unable to recover app. 

### ISSUE THREAD

**Issue by ReisinJ** [nextcloud/android#8364] opened 2021-05-07 13:57 UTC
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: F5321
Model: F5321
Id: 34.4.A.2.118
Product: F5321

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 1631208121

**Comment by AndyScherzinger** [comment] 2021-05-07 16:11
Duplicate of #8252

**Closed by AndyScherzinger** 2021-05-07 16:11 UTC
Labels: bug
