### ISSUE TITLE
Crash on Mobile Device

### ISSUE THREAD

**Issue by axel-rank** [nextcloud/android#5090] opened 2020-01-03 08:59 UTC
Created a text document with an image.
- image (png) isn't displayed if you open the file.
- If you click on details the nextcloud app crashes.

Working on desktop.
Nextcloud 17.0.2
Text 1.1.1

**Comment by juliushaertl** [comment] 2020-01-03 12:11
Moving to the android repo since this seems related to the markdown preview there. 

cc @tobiasKaminsky @AndyScherzinger

**Comment by AndyScherzinger** [comment] 2020-01-09 17:27
it is, it's a duplicate of #4836 - thus closing in favor

**Closed by AndyScherzinger** 2020-01-09 17:27 UTC
Labels: bug
