### ISSUE TITLE
android client crashes

### ISSUE THREAD

**Issue by prime-minister-of-fun** [nextcloud/android#8458] opened 2021-05-24 06:09 UTC
### Steps to reproduce
1. Attempt to use Android client

### Expected behaviour
I can use the client to upload pictures, etc. 

### Actual behaviour
I get the following dump.  

TBH, this Samsung Android tablet is a POS.  If you get other errors on other  android devices, maybe this bug is warranted. 

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gta3xlwifi
Model: SM-T510
Id: QP1A.190711.020
Product: gta3xlwifixx

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: T510XXS5BUC4

**Comment by AndyScherzinger** [comment] 2021-05-25 10:33
Duplicate of #8370

**Closed by AndyScherzinger** 2021-05-25 10:33 UTC
Labels: bug
