### ISSUE TITLE
Cause of Error 

### ISSUE THREAD

**Issue by 1ZachM** [nextcloud/android#5276] opened 2020-01-22 01:59 UTC
### Steps to reproduce
1. Not sure
2. Was using Android back button
3. Cause of error log popped up

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{ff03ef2 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: google
Device: blueline
Model: Pixel 3
Id: QQ1A.200105.003
Product: blueline

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 6079943

**Comment by AndyScherzinger** [comment] 2020-01-22 06:52
Thanks for the report. Duplicate of #2010

**Closed by AndyScherzinger** 2020-01-22 06:52 UTC
Labels: bug
