### ISSUE TITLE
When i click personal file on android app 

### ISSUE THREAD

**Issue by 9M2PJU** [nextcloud/android#13751] opened 2024-10-09 16:33 UTC
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at com.owncloud.android.ui.adapter.OCFileListAdapter.limitToPersonalFiles(OCFileListAdapter.java:1074)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:741)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1359)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1308)
    at com.owncloud.android.ui.fragment.OCFileListFragment.refreshDirectory(OCFileListFragment.java:1304)
    at com.owncloud.android.ui.activity.FileDisplayActivity.showFiles(FileDisplayActivity.java:2224)
    at com.owncloud.android.ui.activity.DrawerActivity.onNavigationItemClicked(DrawerActivity.java:497)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$setupDrawerMenu$4(DrawerActivity.java:459)
    at com.owncloud.android.ui.activity.DrawerActivity.$r8$lambda$avHXP34Kh0TDBHMWmR2kRM7pnyQ(Unknown Source:0)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Unknown Source:2)
    at android.os.Handler.dispatchMessage(Unknown Source:4)
    at android.os.Looper.loopOnce(Unknown Source:182)
    at android.os.Looper.loop(Unknown Source:82)
    at android.app.ActivityThread.main(Unknown Source:123)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
    at com.android.internal.os.ZygoteInit.main(Unknown Source:312)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `POCO`
* Device: `marble`
* Model: `23049PCD8G`
* Id: `TKQ1.221114.001`
* Product: `marble`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `V14.0.25.0.TMRCNXM`

**Comment by joshtrichards** [comment] 2024-10-09 17:42
Duplicate of #12908 
Fixed in #12930

**Closed by joshtrichards** 2024-10-09 17:42 UTC
