### ISSUE TITLE
Can not auto upload to external storage

### ISSUE THREAD

**Issue by b-m-f** [nextcloud/android#6613] opened 2020-08-02 10:01 UTC
### Steps to reproduce
1. Configure auto upload remote folder
2. Select external Storage folder
3. App crashes

### Expected behaviour
- should be able to auto upload to external storage

### Actual behaviour
- crashes

### Environment data

Stock or customized system:
Stock 
Nextcloud app version:
3.13 RC2
Nextcloud server version:
18.0.7
Reverse proxy:
No

#### Nextcloud app log
```
************ CAUSE OF ERROR ************

java.lang.ClassCastException: com.owncloud.android.ui.activity.FolderPickerActivity cannot be cast to com.owncloud.android.ui.activity.FileDisplayActivity
	at com.owncloud.android.ui.fragment.OCFileListFragment.resetHeaderScrollingState(OCFileListFragment.java:1867)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:906)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.lambda$onBindViewHolder$1$OCFileListAdapter(OCFileListAdapter.java:379)
	at com.owncloud.android.ui.adapter.-$$Lambda$OCFileListAdapter$pouWgEOOHT1aDFHaHM0Ifm3xWtY.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7201)
	at android.view.View.performClickInternal(View.java:7170)
	at android.view.View.access$3500(View.java:806)
	at android.view.View$PerformClick.run(View.java:27562)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5T

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2005130017
```

**Comment by AndyScherzinger** [comment] 2020-08-03 18:56
Hi @b-m-f  and thank you for the report.

This issue will be fixed via #6632 and ship with 3.13.0 RC3

Duplicate of #6616

**Closed by AndyScherzinger** 2020-08-03 18:56 UTC
Labels: bug
