### ISSUE TITLE
Can't enter address

### ISSUE THREAD

**Issue by DIeMONdello** [nextcloud/android#4463] opened 2019-09-04 17:01 UTC
### Actual behaviour
Can't enter https address

### Expected behaviour
When i start app and push login app restart
 
### Steps to reproduce
1. Delete old account, server not have https
2. Make a new connections to new account on server with https
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
	at android.widget.Editor.updateCursorPositionMz(Editor.java:6964)
	at android.widget.Editor.updateCursorsPositions(Editor.java:1760)
	at android.widget.TextView.getUpdatedHighlightPath(TextView.java:5689)
	at android.widget.TextView.onDraw(TextView.java:5882)
	at com.owncloud.android.ui.components.CustomEditText.onDraw(CustomEditText.java:71)
	at android.view.View.draw(View.java:16539)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.draw(View.java:16551)
	at com.google.android.material.textfield.TextInputLayout.draw(TextInputLayout.java:1577)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.draw(View.java:16551)
	at android.widget.ScrollView.draw(ScrollView.java:1745)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2839)
	at android.view.View.draw(View.java:16551)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2820)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:286)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:292)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:327)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3051)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2855)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2464)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1337)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6819)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
	at android.view.Choreographer.doCallbacks(Choreographer.java:696)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5969)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:830)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:720)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080053
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Meizu
Device: M5s
Model: M5s
Id: MRA58K
Product: meizu_M5s

************ FIRMWARE ************
SDK: 23
Release: 6.0
Incremental: 1495063419

*NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by DIeMONdello** [comment] 2019-09-10 16:21
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
	at android.widget.Editor.updateCursorPositionMz(Editor.java:6964)
	at android.widget.Editor.updateCursorsPositions(Editor.java:1760)
	at android.widget.TextView.getUpdatedHighlightPath(TextView.java:5689)
	at android.widget.TextView.onDraw(TextView.java:5882)
	at com.owncloud.android.ui.components.CustomEditText.onDraw(CustomEditText.java:71)
	at android.view.View.draw(View.java:16539)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.draw(View.java:16551)
	at com.google.android.material.textfield.TextInputLayout.draw(TextInputLayout.java:1577)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.draw(View.java:16551)
	at android.widget.ScrollView.draw(ScrollView.java:1745)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2839)
	at android.view.View.draw(View.java:16551)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2820)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:286)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:292)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:327)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3051)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2855)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2464)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1337)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6819)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
	at android.view.Choreographer.doCallbacks(Choreographer.java:696)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5969)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:830)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:720)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080055
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Meizu
Device: M5s
Model: M5s
Id: MRA58K
Product: meizu_M5s

************ FIRMWARE ************
SDK: 23
Release: 6.0
Incremental: 1495063419

**Comment by DIeMONdello** [comment] 2019-09-10 16:23
Then i push on line web link it's broke, but i now copy error, when i clean any data app and error on up message

**Comment by DIeMONdello** [comment] 2019-09-14 17:42
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
	at android.widget.Editor.updateCursorPositionMz(Editor.java:6964)
	at android.widget.Editor.updateCursorsPositions(Editor.java:1760)
	at android.widget.TextView.getUpdatedHighlightPath(TextView.java:5689)
	at android.widget.TextView.onDraw(TextView.java:5882)
	at com.owncloud.android.ui.components.CustomEditText.onDraw(CustomEditText.java:71)
	at android.view.View.draw(View.java:16539)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.draw(View.java:16551)
	at com.google.android.material.textfield.TextInputLayout.draw(TextInputLayout.java:1577)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.draw(View.java:16551)
	at android.widget.ScrollView.draw(ScrollView.java:1745)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2839)
	at android.view.View.draw(View.java:16551)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2820)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:286)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:292)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:327)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3051)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2855)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2464)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1337)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6819)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
	at android.view.Choreographer.doCallbacks(Choreographer.java:696)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5969)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:830)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:720)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Meizu
Device: M5s
Model: M5s
Id: MRA58K
Product: meizu_M5s

************ FIRMWARE ************
SDK: 23
Release: 6.0
Incremental: 1495063419

**Comment by DIeMONdello** [comment] 2019-10-02 20:24
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
	at android.widget.Editor.updateCursorPositionMz(Editor.java:6964)
	at android.widget.Editor.updateCursorsPositions(Editor.java:1760)
	at android.widget.TextView.getUpdatedHighlightPath(TextView.java:5689)
	at android.widget.TextView.onDraw(TextView.java:5882)
	at com.owncloud.android.ui.components.CustomEditText.onDraw(CustomEditText.java:71)
	at android.view.View.draw(View.java:16539)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.draw(View.java:16551)
	at com.google.android.material.textfield.TextInputLayout.draw(TextInputLayout.java:1577)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.draw(View.java:16551)
	at android.widget.ScrollView.draw(ScrollView.java:1745)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2839)
	at android.view.View.draw(View.java:16551)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2820)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:286)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:292)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:327)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3051)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2855)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2464)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1337)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6819)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
	at android.view.Choreographer.doCallbacks(Choreographer.java:696)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5969)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:830)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:720)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080151
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Meizu
Device: M5s
Model: M5s
Id: MRA58K
Product: meizu_M5s

************ FIRMWARE ************
SDK: 23
Release: 6.0
Incremental: 1495063419

**Comment by tobiasKaminsky** [comment] 2019-10-08 13:31
Duplicate of #4619

**Closed by tobiasKaminsky** 2019-10-08 13:31 UTC
Labels: bug
