### ISSUE TITLE
keys can not be archived yet

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#2137] opened 2018-02-10 10:24 UTC
Because when I try to access an e2e encrypted folder for the first time 
and I accept the 12 words created 
I exit then the written keys can not be archived yet.
 application for android
on Huawei smartphone everything goes well on Nexus 6 Nexus 6p and Samsung s8 plus I get instead the error that fails to store the newly generated keys.

**Comment by AndyScherzinger** [comment] 2018-02-10 15:56
@tobiasKaminsky is this on purpose or a feature yet to be implemented?

**Comment by ardevd** [comment] 2018-02-13 08:58
@tigernero79 is this a duplicate of #2134 ?

**Comment by tigernero79** [comment] 2018-02-13 09:30
Yes.

**Comment by AndyScherzinger** [comment] 2018-02-13 10:31
Closing in favor of #2134

**Comment by AndyScherzinger** [comment] 2018-02-13 10:32
Thanks for all the effort regarding analysis and fixing 🥇

**Closed** 2018-02-13 10:32 UTC
Labels: E2E, needs info/discussion
