### ISSUE TITLE
App does not open Collabora on the server to read/edit files.

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/android#12411] opened 2024-01-25 13:23 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open NC android app
2. Navigate to a folder with e.g. an *.ocs file (in a group folder in my instance but should not make a difference)
3. Tap on the file in order to open collabora on mobile

### Expected behaviour

Collabora loads and shows the document

### Actual behaviour

The file starts to open with a splash screen (see below for a screenshot). Nothing ore happens visually, especially there is no error message printed about the request taking too long (c.f. nextcloud/richdocuments#2873).

### Android version

10

### Device brand and model

Doogee S96Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.27.0

### Nextcloud server version

28.0.1

### Using a reverse proxy?

Yes

### Android logs

These logs show up _after_ navigating to the corresponding folder. I clipped everything before I clicked the actual file.

```
01-25 14:10:52.207 24601 24601 V FileDisplayActivity: onPause() start
01-25 14:10:52.207 24601 24601 D FileDisplayActivity: onPause() ending
01-25 14:10:52.208 24601 24601 V FileDisplayActivity: onPause() end
01-25 14:10:52.214 24601 24601 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@b82ebd8
01-25 14:10:52.221 24601 24601 V ExternalSiteWebView: onCreate() start
01-25 14:10:52.270 24601 24601 D RichDocumentsEditorWebView: onCreate(Bundle) starting
01-25 14:10:52.293 24601 24601 D RichDocumentsEditorWebView: onStart() starting
01-25 14:10:52.294 24601 12393 I System.out: [socket]:check permission begin!
01-25 14:10:52.296 24601 24601 W ActionBarDrawerToggle: DrawerToggle may not show up because NavigationIcon is not visible. You may need to call actionbar.setDisplayHomeAsUpEnabled(true);
01-25 14:10:52.305 24601 24601 D RichDocumentsEditorWebView: onResume() starting
01-25 14:10:52.317 24601 24601 V PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@33cc2cc[]
01-25 14:10:52.317 24601 24601 D ViewRootImpl[RichDocumentsEditorWebView]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
01-25 14:10:52.323 24601 24601 I InputTransport: Create ARC handle: 0x72924bc120
01-25 14:10:52.324 24601 24601 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@da3b21b, this = DecorView@33cc2cc[RichDocumentsEditorWebView]
01-25 14:10:52.334 24601 31349 D Surface : Surface::connect(this=0x7235e10000,api=1)
01-25 14:10:52.335 24601 31349 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
01-25 14:10:52.335 24601 31349 D Surface : Surface::setBufferCount(this=0x7235e10000,bufferCount=3)
01-25 14:10:52.336 24601 31349 D Surface : Surface::allocateBuffers(this=0x7235e10000)
01-25 14:10:52.368 24601 24601 D FileActivity: Operations service connected
01-25 14:10:52.750 24601 31349 D Surface : Surface::disconnect(this=0x7267d41000,api=1)
01-25 14:10:52.761 24601 24601 D FileDisplayActivity: onStop() ending
01-25 14:10:52.762 24601 24601 V FileDisplayActivity: onSaveInstanceState() start
01-25 14:10:52.763 24601 24601 D FileDisplayActivity: onSaveInstanceState(Bundle) starting
01-25 14:10:52.763 24601 24601 D ExtendedListFragment: onSaveInstanceState()
01-25 14:10:52.764 24601 24601 V FileDisplayActivity: onSaveInstanceState() end
01-25 14:10:52.764 24601 24601 V PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@460c175, this = DecorView@5b94194[FileDisplayActivity]
```

### Additional information

I checked with the same device and using a browser (Firefox). There, the file can be opened without problems.

Looking at the logs of the reverse proxy, I see both for browser and mobile app the navigation to the corresponding location (aka the PROPFIND calls). In the android app, there is no call to the collabora client nor to the cloud host made after clicking on the file. In the browser a cascade of further calls are made (get service worker and token, somehow start collabora in a browser and then something with wopi).

In the server there are no logs, most probably as the actual calls are not triggered at all.

I checked the issues, there are several issues sounding similarly: #6097 #11284 #11979 #11975 and nextcloud/richdocuments#2873.

I tried the trick with `occ config:app:set richdocuments mobile_editing --value="yes"` with no success.

I am just seeing this screen if the problem happens:
![Screenshot_20240125-110659](https://github.com/nextcloud/android/assets/8202922/ddf8fe40-f34c-4f20-98ae-05aedf865230)

**Comment by joshtrichards** [comment] 2024-01-25 14:40
Duplicate of #12338 
Fixed in #12350 
Will be in v3.27.1

It was a regression specific to v3.27.0.

**Closed by joshtrichards** 2024-01-25 14:40 UTC
Labels: bug
