### ISSUE TITLE
Allow to set default behaviour for conflicting files and upload errors

### ISSUE THREAD

**Issue by flexagoon** [nextcloud/android#10773] opened 2022-10-01 21:12 UTC
### Is your feature request related to a problem? Please describe.

Whenever a file conflict or an upload error happens, Nextcloud starts sending me multiple warning notifications every minute, and they are persistent, so they can't be swiped away. This is incredibly annoying and ruins my entire mobile app experience.

### Describe the solution you'd like

I'd like to be able to set a default behaviour for file conflicts (either "use file on the server" or "use local file"), and the default behaviour for upload errors ("retry" or "skip"). It would also be great to be able to set this per-folder. For example, I want to retry if an autoupload of a photo fails, but I don't care if an auto upload of my seedvault backup fails.

### Describe alternatives you've considered

You can just not repeat the same persistent error notification every single minute. But even if that's fixed, it would still be nice to be able to set default error actions.

**Comment by AlvaroBrey** [comment] 2022-10-03 08:45
This is already possible on a per-folder basis for autoupload folders (check "Configure" in the three dot menu for each folder).  For a default behaviour, this issue is a duplicate of #10082

**Closed by AlvaroBrey** 2022-10-03 08:45 UTC
Labels: enhancement

**Comment by flexagoon** [comment] 2022-10-03 09:01
@AlvaroBrey I do not have a "configure" button in the three dot menu.

**Comment by flexagoon** [comment] 2022-10-03 09:03
@AlvaroBrey the "configure" button is only there for folders managed by Nextcloud's auto upload feature. Some apps upload their data to Nextcloud automatically (eg. Seedvault, Joplin), and it is thus not possible to configure the default behaviour for such folders.
