### ISSUE TITLE
Was not able to create a new file while offline

### ISSUE THREAD

**Issue by DimanNe** [nextcloud/android#10809] opened 2022-10-17 09:26 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

* Open the app
* Disable the internet
* Try to create a new/empty file.

### Expected behaviour

A new file is created.

### Cause of error

```java

Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.lib.common.Template.getExtension()' on a null object reference

at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.checkEnablingCreateButton(ChooseTemplateDialogFragment.kt:263)

at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.access$checkEnablingCreateButton(ChooseTemplateDialogFragment.kt:71)

at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$onCreateDialog$2.afterTextChanged(ChooseTemplateDialogFragment.kt:162)

at android.widget.TextView.sendAfterTextChanged(TextView.java:11066)

at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:14164)

at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1278)

at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:578)

at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:314)

at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)

at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:304)

at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:48)

at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:941)

at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:712)

at android.view.inputmethod.InputConnectionWrapper.setComposingText(InputConnectionWrapper.java:154)

at com.android.internal.inputmethod.RemoteInputConnectionImpl.lambda$setComposingText$25$com-android-internal-inputmethod-RemoteInputConnectionImpl(RemoteInputConnectionImpl.java:724)

at com.android.internal.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda19.run(Unknown Source:8)

at android.os.Handler.handleCallback(Handler.java:942)

at android.os.Handler.dispatchMessage(Handler.java:99)

at android.os.Looper.loopOnce(Looper.java:201)

at android.os.Looper.loop(Looper.java:288)

at android.app.ActivityThread.main(ActivityThread.java:7904)

at java.lang.reflect.Method.invoke(Native Method)

at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)

at com.android.internal.os.ExecInit.main(ExecInit.java:49)

at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)

at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)


```

### App information

* ID: `com.nextcloud.client`

* Version: `30210290`

* Build flavor: `gplay`

### Device information

* Brand: `google`

* Device: `raven`

* Model: `Pixel 6 Pro`

* Id: `TP1A.221005.002`

* Product: `raven`

### Firmware

* SDK: `33`

* Release: `13`

* Incremental: `2022101500`

### Android version

13

### Device brand and model

Google Pixel 6 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

30210290

### Nextcloud server version

24.0.6

### Using a reverse proxy?

I don't know

**Comment by AlvaroBrey** [comment] 2023-01-17 13:56
Duplicate of #10668

**Closed by AlvaroBrey** 2023-01-17 13:56 UTC
Labels: bug
