### ISSUE TITLE
automatic upload: sync existing files in folder

### ISSUE THREAD

**Issue by Gifford47** [nextcloud/android#3875] opened 2019-04-10 13:50 UTC
With the automatic upload only new images are transferred. Existing pictures in the folder are not, if the automatic upload is activated only after the existing pictures.
I would like to have an option in the upload menu which decides if already existing images should be synchronized.

**Comment by briner** [comment] 2019-05-01 15:41
This is even more true when promoting people to use nextcloud for privacy reason and not being able to push the images in one step.

**Comment by martinruenz** [comment] 2019-07-05 09:04
For reference, the same discussion came up in the help forum and one user made a good point about the misleading UI (which makes you belief that existing images **are** uploaded. Hence, one could even argue that this is a bug):
https://help.nextcloud.com/t/autoupload-how-to-sync-existing-files/10149

**Comment by tobiasKaminsky** [comment] 2019-10-08 08:40
To do this in a proper way, we need to have checksums on server, which are not yet there.

**Comment by martinruenz** [comment] 2019-10-08 18:03
For the case that there are conflicting files? How is a new picture different from an existing one for this particular use case?

**Comment by lemmy04** [comment] 2019-10-09 06:39
how is "we can't properly sync fotos without having checksums on the server" different from "we can't properly sync any files without having checksums on the server"...

Seriously, I understand your concern, I'm guessing you're picturing someone who has more than one mobile, and by some means creates a photo with exactly the same name on both devices - which one will end up in the cloud?

But that extends to any situation where soneone acesses their nextcloud account with more than one device with any client on it at the same time... two laptops, two desktop clients...

For example: I'm running the desktop client on four different computers, two of them dualboot linux/windows.... so that is SIX "different entities" of the desktop client alone, and (i think) 8 mobile devices if I count all my old phones and freebie tablets that I don't "really" use but have to fool around with. If there was no "proper" sync right now because of the lack of server side checksums, my files would be toast since long ago...

**Comment by lemmy04** [comment] 2019-10-09 06:43
Seriously, the "flow" here from a user POV is this:

- user installs and configures nextcloud client on mobile
- user snaps a picture
- nextcloud client says "i detected a new picture folder, wanna sync that?"
- user says yes
- user finds that that new picture that was the reason for him to say "i want my pictures in my nextcloud" is ... **not** in his nextcloud.
I don't see how this is not a BUG, as simple as that.

**Comment by pbaesse** [comment] 2019-10-10 13:54
Exactly! That really fells like a bug. @lemmy04 makes two really good points:

First one

> user finds that that new picture that was the reason for him to say "i want my pictures in my nextcloud" is ... not in his nextcloud.

Second one, and everyone whats to know:

> what I'm trying to get at here is: the desktop client can deal with this kind of situation without server side checksums, and detects sync conflicts just fine since the last release, so what is the big deal here?

**Comment by AndyScherzinger** [comment] 2020-02-18 17:21
to be released with 3.11. via #4788

**Closed by AndyScherzinger** 2020-02-18 17:21 UTC
Labels: enhancement
