### ISSUE TITLE
F-Droid version of nextcloud Android app out of date

### ISSUE THREAD

**Issue by linuxclowns** [nextcloud/android#2495] opened 2018-04-21 16:26 UTC
### Actual behaviour
- installs version 3.0.3

### Expected behaviour
- current version appears to be 3.1.0
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2018-04-22 09:43
Hi @linuxclowns I just checked https://f-droid.org/packages/com.nextcloud.client/ and 3.1.0 is already available there so closing the issue. Have fun with 3.1 :)

**Comment by Spartachetto** [comment] 2018-04-22 14:41
@AndyScherzinger 3.1.0 us indeed available, yet it is  NOT marked as the "current" version. F-Droid always provides me the current version, excluding for example the RC releases.  

Maybe you marked 3.1.0 as not a "final" release?

**Comment by AndyScherzinger** [comment] 2018-04-22 16:06
@tobiasKaminsky any idea why f-droid isn't marking 3.1.0 as the latest stable release? Within GH the tag is marked as a stable release.

**Comment by tobiasKaminsky** [comment] 2018-04-23 13:25
Yes, due to our automated semantic schema version, fdroid does not detect 3.1.0 as a newer version than 3.0.3, so it 1) does not generate a build receipt and 2) if a build receipt is added manually, it reverts back to 3.0.3.
So I provided a merge request, which disables automatic updating. We will now have to manually add a build receipt and adjust "current" version.
--> added to roadmap.

**Comment by Spartachetto** [comment] 2018-04-24 19:55
The problem is solved for me. Now the current version is 3.1.0.

Thank you @tobiasKaminsky !!!

**Comment by AndyScherzinger** [comment] 2018-04-24 20:45
Thanks for the feedback @Spartachetto. Closing the issue then :)

**Closed by AndyScherzinger** 2018-04-24 20:45 UTC
