### ISSUE TITLE
Crash after entering server-url

### ISSUE THREAD

**Issue by Zniets** [nextcloud/android#10876] opened 2022-10-21 07:51 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Install Nextcloudapp on android(Version 3.22.1)
2. Enter Server-URL
3. Crash-rebort

### Expected behaviour

Get to the Login

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.LinearLayout [com.owncloud.android](http://com.owncloud.android/).databinding.SslUntrustedCertLayoutBinding.getRoot()' on a null object reference
at [com.owncloud.android](http://com.owncloud.android/).ui.dialog.SslUntrustedCertDialog.onCreateDialog([SslUntrustedCertDialog.java:173](http://ssluntrustedcertdialog.java:173/))
at [androidx.fragment.app](http://androidx.fragment.app/).DialogFragment.prepareDialog([DialogFragment.java:665](http://dialogfragment.java:665/))
at [androidx.fragment.app](http://androidx.fragment.app/).DialogFragment.onGetLayoutInflater([DialogFragment.java:579](http://dialogfragment.java:579/))
at [androidx.fragment.app](http://androidx.fragment.app/).Fragment.performGetLayoutInflater([Fragment.java:1752](http://fragment.java:1752/))
at [androidx.fragment.app](http://androidx.fragment.app/).FragmentStateManager.createView([FragmentStateManager.java:493](http://fragmentstatemanager.java:493/))
at [androidx.fragment.app](http://androidx.fragment.app/).FragmentStateManager.moveToExpectedState([FragmentStateManager.java:261](http://fragmentstatemanager.java:261/))
at [androidx.fragment.app](http://androidx.fragment.app/).FragmentManager.executeOpsTogether([FragmentManager.java:1899](http://fragmentmanager.java:1899/))
at [androidx.fragment.app](http://androidx.fragment.app/).FragmentManager.removeRedundantOperationsAndExecute([FragmentManager.java:1817](http://fragmentmanager.java:1817/))
at [androidx.fragment.app](http://androidx.fragment.app/).FragmentManager.execPendingActions([FragmentManager.java:1760](http://fragmentmanager.java:1760/))
at [androidx.fragment.app](http://androidx.fragment.app/).FragmentManager$[5.run](http://5.run/)([FragmentManager.java:547](http://fragmentmanager.java:547/))
at android.os.Handler.handleCallback([Handler.java:900](http://handler.java:900/))
at android.os.Handler.dispatchMessage([Handler.java:103](http://handler.java:103/))
at android.os.Looper.loop([Looper.java:219](http://looper.java:219/))
at [android.app](http://android.app/).ActivityThread.main([ActivityThread.java:8668](http://activitythread.java:8668/))
at java.lang.reflect.Method.invoke(Native Method)
at [com.android](http://com.android/).internal.os.RuntimeInit$[MethodAndArgsCaller.run](http://methodandargscaller.run/)([RuntimeInit.java:513](http://runtimeinit.java:513/))
at [com.android](http://com.android/).internal.os.ZygoteInit.main([ZygoteInit.java:1109](http://zygoteinit.java:1109/))

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220190`
* Build flavor: `gplay`

### Device information
* Brand: `HUAWEI`
* Device: `HWELE`
* Model: `ELE-L29`
* Id: `HUAWEIELE-L29`
* Product: `ELE-L29EEA`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `10.1.0.150C431`

### Android version

-

### Device brand and model

Huawei

### Stock or custom OS?

Stock

### Nextcloud android app version

30.22.1

### Nextcloud server version

19

### Using a reverse proxy?

No

**Comment by AlvaroBrey** [comment] 2022-10-21 08:29
Duplicate of #10868

**Closed by AlvaroBrey** 2022-10-21 08:29 UTC
Labels: bug
