### ISSUE TITLE
App can't reach server

### ISSUE THREAD

**Issue by kruemelnerd** [nextcloud/android#10250] opened 2022-05-15 20:34 UTC
### Actual behaviour
- App is crashing every few seconds producing the following error when connected to wifi
- with mobile data i get the info that the server is in maintenance mode (the server is working fine)

### Cause of error
```java
Exception in thread "Thread-7" java.lang.IllegalStateException: network interceptor com.nextcloud.common.IPv4FallbackInterceptor@13ee2b0 must call proceed() exactly once
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:99)
    at com.nextcloud.common.IPv4FallbackInterceptor.retryWithIPv4(IPv4FallbackInterceptor.kt:74)
    at com.nextcloud.common.IPv4FallbackInterceptor.intercept(IPv4FallbackInterceptor.kt:54)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
    at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
    at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:171)
    at com.nextcloud.client.network.ConnectivityServiceImpl.isInternetWalled(ConnectivityServiceImpl.java:81)
    at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:239)
    at com.owncloud.android.utils.FilesSyncHelper$$ExternalSyntheticLambda0.run(Unknown Source:10)
    at java.lang.Thread.run(Thread.java:764)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `dreamlte`
* Model: `SM-G950F`
* Id: `PPR1.180610.011`
* Product: `dreamltexx`

### Firmware
* SDK: `28`
* Release: `9`
* Incremental: `G950FXXUCDUD1`

### Setup
hosted Nextcloud at https://www.hosting.de

**Comment by AlvaroBrey** [comment] 2022-05-16 08:35
Duplicate of #10039

**Closed by AlvaroBrey** 2022-05-16 08:35 UTC
Labels: bug
