### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by fairking** [nextcloud/android#10293] opened 2022-05-27 21:26 UTC
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'com.owncloud.android.utils.FileSortOrder$SortType com.owncloud.android.utils.FileSortOrder.getType()' on a null object reference
    at com.owncloud.android.ui.adapter.OCFileListAdapter.getPopupText(OCFileListAdapter.java:905)
    at me.zhanghai.android.fastscroll.RecyclerViewHelper.getPopupText(RecyclerViewHelper.java:136)
    at me.zhanghai.android.fastscroll.FastScroller.onPreDraw(FastScroller.java:198)
    at me.zhanghai.android.fastscroll.FastScroller.$r8$lambda$fhoCEu3yFeBM02d2QCiuR_Ev5oo(Unknown Source:0)
    at me.zhanghai.android.fastscroll.FastScroller$$ExternalSyntheticLambda1.run(Unknown Source:2)
    at me.zhanghai.android.fastscroll.RecyclerViewHelper$1.onDraw(RecyclerViewHelper.java:52)
    at androidx.recyclerview.widget.RecyclerView.onDraw(RecyclerView.java:4668)
    at android.view.View.draw(View.java:21482)
    at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
    at android.view.View.updateDisplayListIfDirty(View.java:20359)
    at android.view.View.draw(View.java:21214)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4391)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
    at android.view.View.draw(View.java:21485)
    at android.view.View.updateDisplayListIfDirty(View.java:20359)
    at android.view.View.draw(View.java:21214)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4391)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
    at android.view.View.updateDisplayListIfDirty(View.java:20350)
    at android.view.View.draw(View.java:21214)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4391)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
    at android.view.View.updateDisplayListIfDirty(View.java:20350)
    at android.view.View.draw(View.java:21214)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4391)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
    at android.view.View.draw(View.java:21485)
    at android.view.View.updateDisplayListIfDirty(View.java:20359)
    at android.view.View.draw(View.java:21214)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4391)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
    at android.view.View.updateDisplayListIfDirty(View.java:20350)
    at android.view.View.draw(View.java:21214)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4391)
    at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
    at android.view.View.draw(View.java:21485)
    at android.view.View.updateDisplayListIfDirty(View.java:20359)
    at android.view.View.draw(View.java:21214)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4391)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
    at android.view.View.updateDisplayListIfDirty(View.java:20350)
    at android.view.View.draw(View.java:21214)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4391)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
    at android.view.View.updateDisplayListIfDirty(View.java:20350)
    at android.view.View.draw(View.java:21214)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4391)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
    at android.view.View.updateDisplayListIfDirty(View.java:20350)
    at android.view.View.draw(View.java:21214)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4391)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
    at android.view.View.updateDisplayListIfDirty(View.java:20350)
    at android.view.View.draw(View.java:21214)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4391)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
    at android.view.View.draw(View.java:21485)
    at com.android.internal.policy.DecorView.draw(DecorView.java:840)
    at android.view.View.updateDisplayListIfDirty(View.java:20359)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:3701)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3509)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2839)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1799)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7750)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
    at android.view.Choreographer.doCallbacks(Choreographer.java:791)
    at android.view.Choreographer.doFrame(Choreographer.java:726)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
    at android.os.Handler.handleCallback(Handler.java:914)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:241)
    at android.app.ActivityThread.main(ActivityThread.java:7582)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `generic`

### Device information
* Brand: `motorola`
* Device: `lima`
* Model: `motorola one macro`
* Id: `QMDS30.47-33-5`
* Product: `lima_reteu`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `7e278`

**Comment by AlvaroBrey** [comment] 2022-05-30 07:03
Duplicate of #10227

**Closed** 2022-05-30 07:03 UTC
