### ISSUE TITLE
Zooming in/out of files in gallry view doesn't change the size of the thumbnails

### ISSUE THREAD

**Issue by yurividal** [nextcloud/android#12708] opened 2024-03-20 06:52 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1 open a folder with images
2 pinch in/out to change number of items per row
3 number changes but thumbnails remain the same size.

![Screen_Recording_20240320_064531_Nextcloud_1](https://github.com/nextcloud/android/assets/8555749/25cb0995-e8f5-4034-899b-00f08a277cfc)

### Expected behaviour

File thumbnails should increase slightly in size to use the extra space. That's how all gallery apps work.

### Actual behaviour

Thumbnails remain exact same size

### Android version

14

### Device brand and model

Samsung Galaxy s23

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.0

### Nextcloud server version

:latest

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment] 2024-03-20 13:04
Duplicate of #12627

**Closed by joshtrichards** 2024-03-20 13:04 UTC
Labels: bug
