### ISSUE TITLE
视频添加预览图功能

### ISSUE THREAD

**Issue by SuperApollo** [nextcloud/android#8254] opened 2021-04-09 09:04 UTC
### 希望能为视频添加预览图功能

- 浏览媒体时，照片类型可以显示预览图，但是视频类型无法显示，希望能加入预览图功能

**Comment by SuperApollo** [comment] 2021-04-09 09:15
![Screenshot_20210409-171341_Nextcloud](https://user-images.githubusercontent.com/17996455/114158305-1d6fc200-9957-11eb-8ab8-486ab3e032fe.jpg)

**Comment by AndyScherzinger** [comment] 2021-04-09 10:11
Hi @SuperApollo please post any issue/ticket in English. Thanks for your efforts! ❤️

**Comment by joshtrichards** [comment] 2023-10-16 20:10
Duplicate of #490
(presumably)
Also may need to configure video previews on your server.

**Closed by joshtrichards** 2023-10-16 20:10 UTC
Labels: enhancement, needs info
