### ISSUE TITLE
Sync doesn't work

### ISSUE THREAD

**Issue by QuAzI** [nextcloud/android#10755] opened 2022-09-22 21:27 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Try to sync a lot of files or write something for a long time right in sync folder and synchronization stucks because of "version conflict" with new file
![Screenshot_20220922-074948_Nextcloud](https://user-images.githubusercontent.com/1897605/191853020-f1ac42a1-ebfb-4d74-8f3c-fb6619f4046b.jpg).
Obsidian with dynamic notes throws this bug each time. And Cube ACR.
Also if you removed something from server side it is never been removed from phone.

### Expected behaviour

Sync in both directions

### Actual behaviour

From phone side: sync stucks.
From server side: removed files not removed on phone.

### Android version

12

### Device brand and model

Samsung Note10+

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.2

### Nextcloud server version

21.0.5

### Using a reverse proxy?

No

**Comment by strugee** [comment] 2022-09-23 01:44
Duplicate of #285, I believe? And I think the sync conflict dialog is expected behavior unless you aren't expecting it for some reason? (It _does_ show up sometimes when it probably shouldn't; for example, when the server and local files are identical - I suggest you search open issues for these cases.)

**Comment by QuAzI** [comment] 2022-09-23 04:35
It does show up for NEW files which mobile client just uploaded to the server. Of course they are identical

**Comment by AlvaroBrey** [comment] 2022-09-23 09:29
Duplicate of #9026

**Closed by AlvaroBrey** 2022-09-23 09:29 UTC
Labels: bug, needs info
