### ISSUE TITLE
'On This Day' on Mobile

### ISSUE THREAD

**Issue by omnath0** [nextcloud/android#10959] opened 2022-10-30 19:45 UTC
### Is your feature request related to a problem? Please describe.
In the web browser under the Photo, we have this tab 'On This Day' which basically list out the previous media of same date. It's a really useful feature and would like to see I on Mobile device. 

### Describe the solution you'd like
In the web browser under the Photo, we have this tab 'On This Day' which basically list out the previous media of same date. It's a really useful feature and would like to see I on Mobile device. 

### Describe alternatives you've considered
N.A

### Additional context
![image](https://user-images.githubusercontent.com/29405032/198898469-6668fe56-d0ac-4648-85b1-5ec845a81307.png)

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by joshtrichards** [comment] 2023-10-08 03:06
Duplicate of #10562

**Closed by joshtrichards** 2023-10-08 03:06 UTC
Labels: enhancement
