### ISSUE TITLE
Crash on nextcloud update

### ISSUE THREAD

**Issue by cab404** [nextcloud/android#8233] opened 2021-04-02 13:30 UTC
### Steps to reproduce
1. Get stable nextcloud
2. Log in
3. Install latest RC

### Expected behaviour
- Tell us what should happen

### Actual behaviour
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter userId
	at com.nextcloud.common.NextcloudClient.<init>(Unknown Source:8)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:185)
	at com.owncloud.android.lib.common.OwnCloudClientManager.getNextcloudClientFor(OwnCloudClientManager.java:220)
	at com.owncloud.android.ui.activity.DrawerActivity.lambda$getAndDisplayUserQuota$4$DrawerActivity(DrawerActivity.java:743)
	at com.owncloud.android.ui.activity.-$$Lambda$DrawerActivity$drdUCYgYHawhhF_lMrqiK8ir7OE.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160052
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: laurel_sprout
Model: Mi A3
Id: RKQ1.200903.002
Product: laurel_sprout

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: V12.0.7.0.RFQMIXM
```

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2021-05-05 11:50
> , parameter userId

This indicates that somehow your userId/account is not working.
Can you still see it in Android's settings?

**Comment by AndyScherzinger** [comment] 2021-05-17 09:36
Duplicate of #8370

**Closed by AndyScherzinger** 2021-05-17 09:36 UTC
Labels: bug, needs info/discussion
