### ISSUE TITLE
Enhance FolderPickerActivity: start in folder

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#6217] opened 2020-06-04 14:35 UTC
- go into subfolder
- copy/move file
- see that you are root folder
--> should start in selected folder
--> needs to update UI
  - on top: show folder
  - on bottom: move/copy
--> replace getCurrentFolder() / mFile with getListOfFiles().getCurrentFile()

- test afterwards with FilePickerActivity

**Comment by Michele64** [comment] 2021-02-04 08:24
That was the behaviour in some previous versions, but disappeared

**Comment by joshtrichards** [comment] 2023-12-13 21:18
Missed this earlier when I started consolidating issues for this into #11831. Oh well. 

Duplicate of #11831 :P

**Closed** 2023-12-13 21:18 UTC
Labels: enhancement

**Comment by Michele64** [comment] 2023-12-13 21:22
hmm, care to explain why? I still think it's the expected behaviour

**Comment by joshtrichards** [comment] 2023-12-13 21:43
Explain why what? Their is an issue tracking this - I'm just eliminating duplicate issues. See #11831 as I stated. :-)
