### ISSUE TITLE
When go back button click error. It's while I shared file to nextcloud from any app

### ISSUE THREAD

**Issue by usagitstate** [nextcloud/android#11494] opened 2023-03-31 11:22 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. It's while I shared file to nextcloud from any app. Click share
2. Go to nextcloud last folder, click back. When go back button click error appears 

### Expected behaviour

Go back folder inside nextcloud 

### Actual behaviour

Error

### Android version

Last

### Device brand and model

OnePlus 

### Stock or custom OS?

Stock

### Nextcloud android app version

Last

### Nextcloud server version

Last

### Using a reverse proxy?

No

**Comment by zzyzx-dc** [comment] 2023-03-31 13:57
Same here. There seem to be related bugs related to trying to navigate within the share menu to a folder which has been deleted. However imo this is a different issue. When you share to Nextcloud Android, and then click the back arrow to navigate up to a higher directory, it crashes. Navigation within the Android app itself occurs correctly. 

```
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.canWrite()' on a null object reference
    at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onCreateOptionsMenu(ReceiveExternalFilesActivity.java:1034)
    at android.app.Activity.onCreatePanelMenu(Activity.java:4387)
    at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:521)
    at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3429)
    at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
    at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
    at android.view.Choreographer.doCallbacks(Choreographer.java:899)
    at android.view.Choreographer.doFrame(Choreographer.java:827)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7891)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ExecInit.main(ExecInit.java:49)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240190`
* Build flavor: `generic`

### Device information
* Brand: `google`
* Device: `bluejay`
* Model: `Pixel 6a`


### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `2023032600`
```

**Comment by joshtrichards** [comment] 2023-04-09 15:16
@zzyzx-dc : Yours may be #9321? Can't say for certain on this issue without stack trace from OP @usagitstate

**Comment by zzyzx-dc** [comment] 2023-04-16 01:37
@joshtrichards I don't believe encryption is the issue for me. Not sure. For me it's simple act of sharing via the Android app that crashes if I try to change directories from within the share menu.

**Comment by joshtrichards** [comment] 2023-10-07 22:41
Duplicate of #9321

**Closed by joshtrichards** 2023-10-07 22:41 UTC
Labels: bug
