### ISSUE TITLE
Auto upload not working on WiFi and VPN

### ISSUE THREAD

**Issue by heinhuiz** [nextcloud/android#7017] opened 2020-09-26 19:27 UTC
### Steps to reproduce
1. Set up a folder for auto upload
2. Check Only upload on unmetered Wi-Fi
3. Connect to an unmetered WiFi network 
4. Connect to VPN
5. Add a file to the folder

### Expected behaviour
- The file should upload

### Actual behaviour
- The file stays in the upload queue, with status Waiting for unmetered network

### Environment data
Android version: 10

Device model: Samsung Galaxy A70 & Mi A1

Stock or customized system: stock & LineageOS

Nextcloud app version: 3.13.1 / F-droid build
Version 3.13.0 does not have this bug, it must be introduced with the 'obey metered network' fix.

Nextcloud server version: 19.0.3

**Comment by heinhuiz** [comment] 2020-09-28 08:50
Note: edited version numbers in opening post. The bug exists since 3.13.1.

**Comment by heinhuiz** [comment] 2020-10-18 12:35
I've done more investigations: the connection only does not work while connected to unmetered WiFi and VPN. Disconnect the VPN and the connection is recognized again.
Title and OP adjusted accordingly.

**Comment by tobiasKaminsky** [comment] 2020-10-19 07:34
Duplicate of #6449

**Closed by tobiasKaminsky** 2020-10-19 07:34 UTC
Labels: bug

**Comment by heinhuiz** [comment] 2020-11-04 15:46
The bug still exists in version 3.14.0 RC1, although this report and all duplicates are closed.

**Comment by Mageti** [comment] 2020-12-07 10:40
FYI, the problem can be reproduced with a "fake" VPN, like personalDNSFilter (https://www.zenz-solutions.de/personaldnsfilter-wp/). I personaly use it to filter out ads and tracking. I installed it from fdroid https://f-droid.org/en/packages/dnsfilter.android/.
If I exclude the nextcloud app from using the VPN, the sync is OK (on wifi or not), and If I do not exclude the nextcloud app, the sync is paused (on wifi or not).
