### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by NotSoImportant** [nextcloud/android#7938] opened 2021-02-05 10:01 UTC
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Credentials.kt)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Credentials.kt)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:330)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:304)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:276)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:761)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210130
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Motorola
Device: athene_f
Model: Moto G4 Plus
Product: lineage_athene

************ FIRMWARE ************
SDK: 25
Release: 7.?.?

**Comment by tobiasKaminsky** [comment] 2021-02-22 14:58
Duplicate of #7996

**Closed** 2021-02-25 07:49 UTC
Labels: bug
