### ISSUE TITLE
Sporadic SQLiteBlobTooBigException on mobile

### ISSUE THREAD

**Issue by cbcoutinho** [nextcloud/android#7911] opened 2021-02-01 07:01 UTC
### Steps to reproduce
1. Delete large directory using mobile app
2. Wait for job to complete (it crashed on me with a timed out error)
3. Close app and try to re-open

### Expected behaviour

App re-opens correctly

### Actual behaviour
The server is able to delete the directory, but for some reason I'm unable to re-open the app. It keeps mentioning some large exception is causing problems

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

I can try, am I allowed to upload large amounts of data to the server to test these timeouts?

```
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=5181, totalRows=3240
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:948)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:161)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:131)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:249)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:281)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:190)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:332)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:309)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2117)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:371)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:532)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:520)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1878)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:438)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:519)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:401)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:237)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140390
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: J9210
Model: J9210
Id: 55.1.A.12.28
Product: J9210_EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 055001A012002800442216154
```

**Comment by tobiasKaminsky** [comment] 2021-02-23 07:28
Duplicate of #6688

**Closed by tobiasKaminsky** 2021-02-23 07:28 UTC
Labels: bug
