### ISSUE TITLE
Transaction too large

### ISSUE THREAD

**Issue by zaza7** [nextcloud/android#12929] opened 2024-04-24 10:28 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open nextcloud app
2. Browse to folder made for phone sync
3. Tap the + button
4. Tap on upload files
5. Select pictures folder with keep source files in folder
6. Tap upload
7. Crash 
Pictures folder is about 1.7GiB with 9,326 files according to FX

### Expected behaviour

Start uploading files to server

### Actual behaviour

App crashes and spits out an error that says transaction too large

### Android version

13

### Device brand and model

LG V60 ThinQ 5G UW

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.2

### Nextcloud server version

28.0.4

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1102352 bytes
    at android.app.ActivityClient.finishActivity(ActivityClient.java:167)
    at android.app.Activity.finish(Activity.java:6695)
    at android.app.Activity.finish(Activity.java:6712)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:530)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:72)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:34)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:8022)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: Exception in thread "main" android.os.TransactionTooLargeException: data parcel size 1102352 bytes
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(BinderProxy.java:584)
    at android.app.IActivityClientController$Stub$Proxy.finishActivity(IActivityClientController.java:1391)
    at android.app.ActivityClient.finishActivity(ActivityClient.java:164)
    at android.app.Activity.finish(Activity.java:6695)
    at android.app.Activity.finish(Activity.java:6712)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:530)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:72)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:34)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:8022)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30280290`
* Build flavor: `gplay`

### Device information
* Brand: `lge`
* Device: `timelm`
* Model: `LM-V600`
* Id: `TKQ1.220829.002`
* Product: `timelm`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `2319315083708`

**Comment by joshtrichards** [comment] 2024-06-13 14:23
Duplicate of #10242

**Closed by joshtrichards** 2024-06-13 14:23 UTC
Labels: bug, performance: TTLE
