### ISSUE TITLE
Not handling revoked token

### ISSUE THREAD

**Issue by n-gerber** [nextcloud/android#12201] opened 2023-11-27 05:45 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Add useraccount to app
2. Revoke app token from browser
3. Reopen app

### Expected behaviour

The app should detect the revoked access and the user should be able to login and create new token.

### Actual behaviour

The app trys to login repeatetly.
It tried it so much it triggered the automatic lockig of the user and triggered login timeout for my ip.

### Android version

12

### Device brand and model

Samsung Galaxy S10 5G

### Stock or custom OS?

Stock

### Nextcloud android app version

3.26.0

### Nextcloud server version

27.1.3

### Using a reverse proxy?

Yes

### Server error logs

```bash
{"reqId":"NEhkFzrQSbDlOWKEhsqG","level":2,"time":"2023-11-26T20:31:52+00:00","remoteAddr":"192.168.1.47","user":"--","app":"core","method":"GET","url":"/ocs/v2.php/cloud/user?format=json","message":"Session token is invalid because it does not exist","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.26.0","version":"27.1.3.2","exception":{"Exception":"OC\\Authentication\\Exceptions\\InvalidTokenException","Message":"Token does not exist: token does not exist","Code":0,"Trace":[{"file":"/var/www/html/lib/private/Authentication/Token/Manager.php","line":133,"function":"getToken","class":"OC\\Authentication\\Token\\PublicKeyTokenProvider","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/User/Session.php","line":782,"function":"getToken","class":"OC\\Authentication\\Token\\Manager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/User/Session.php","line":352,"function":"validateToken","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/User/Session.php","line":452,"function":"login","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/User/Session.php","line":580,"function":"logClientIn","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/base.php","line":1150,"function":"tryBasicAuthLogin","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/ocs/v1.php","line":61,"function":"handleLogin","class":"OC","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/ocs/v2.php","line":23,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Authentication/Token/PublicKeyTokenProvider.php","Line":163,"Previous":{"Exception":"OCP\\AppFramework\\Db\\DoesNotExistException","Message":"token does not exist","Code":0,"Trace":[{"file":"/var/www/html/lib/private/Authentication/Token/PublicKeyTokenProvider.php","line":172,"function":"getToken","class":"OC\\Authentication\\Token\\PublicKeyTokenMapper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/Authentication/Token/Manager.php","line":133,"function":"getToken","class":"OC\\Authentication\\Token\\PublicKeyTokenProvider","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/User/Session.php","line":528,"function":"getToken","class":"OC\\Authentication\\Token\\Manager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/User/Session.php","line":438,"function":"isTokenPassword","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/User/Session.php","line":580,"function":"logClientIn","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/base.php","line":1150,"function":"tryBasicAuthLogin","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/ocs/v1.php","line":61,"function":"handleLogin","class":"OC","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/ocs/v2.php","line":23,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Authentication/Token/PublicKeyTokenMapper.php","Line":89},"message":"Session token is invalid because it does not exist","user":"nikolas","exception":{},"CustomMessage":"Session token is invalid because it does not exist"}}
```

### Additional information

Only workaround I found is to remove the account add re add it.

This deletes the whole configuration of the auto upload.

**Comment by joshtrichards** [comment] 2023-12-11 22:22
Duplicate of #9341 
And related to #893

**Closed by joshtrichards** 2023-12-11 22:22 UTC
Labels: bug, feature: authentication, hotspot: auth failure mgmt
