### ISSUE TITLE
Upload loop (same files again and again)

### ISSUE THREAD

**Issue by rchovan** [nextcloud/android#6043] opened 2020-05-11 09:41 UTC
Hi, 
after update my NC Android client try to upload all my photos again and again, then it crashes.
I have disabled auto upload, but app still want to upload all 5k files. I have uninstalled app, deleted all data from internal storage and sdcard, but after new installation and login app again start uploading all files again, 
 
### Steps to reproduce
1. Install app
2. login
3. upload started

### Expected behaviour
- do not upload already uploaded files

### Actual behaviour
- app upload same files again and again in loop

### Environment data
Android version: 9
Device model: Samsuns S8
Stock or customized system: stock

Nextcloud app version: 3.11.1
Nextcloud server version: 18.0.3

Reverse proxy: nginx

### Logs
```
************ CAUSE OF ERROR ************
java.lang.RuntimeException: An error occurred while executing doInBackground() at android.os.AsyncTask$3.done(AsyncTask.java:354) at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383) at java.util.concurrent.FutureTask.setException(FutureTask.java:252) at java.util.concurrent.FutureTask.run(FutureTask.java:271) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:764)Caused by: java.lang.SecurityException: Caller no longer running, last stopped +4s905ms because: timed out while starting at android.os.Parcel.createException(Parcel.java:1966) at android.os.Parcel.readException(Parcel.java:1934) at android.os.Parcel.readException(Parcel.java:1884) at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:195) at android.app.job.JobParameters.dequeueWork(JobParameters.java:243) at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315) at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640) at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390) at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383) at android.os.AsyncTask$2.call(AsyncTask.java:333) at java.util.concurrent.FutureTask.run(FutureTask.java:266) ... 3 moreCaused by: android.os.RemoteException: Remote stack trace: at com.android.server.job.JobServiceContext.assertCallerLocked(JobServiceContext.java:481) at com.android.server.job.JobServiceContext.doDequeueWork(JobServiceContext.java:359) at com.android.server.job.JobServiceContext$JobCallback.dequeueWork(JobServiceContext.java:160) at android.app.job.IJobCallback$Stub.onTransact(IJobCallback.java:83) at android.os.Binder.execTransact(Binder.java:739)

************ APP INFORMATION ************ID: com.nextcloud.clientVersion: 30110190Build flavor: gplay
************ DEVICE INFORMATION ************Brand: samsungDevice: dreamlteModel: SM-G950FId: PPR1.180610.011Product: dreamltexx
************ FIRMWARE ************SDK: 28Release: 9Incremental: G950FXXS8DTCB```

**Comment by tobiasKaminsky** [comment] 2020-05-12 06:41
Duplicate of #5805

**Closed by tobiasKaminsky** 2020-05-12 06:41 UTC
Labels: bug
