### ISSUE TITLE
Shared section is empty

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#9174] opened 2021-10-29 08:24 UTC
Sometimes it takes a long time to display the files here. 
A loading spinner could be better then showing "no files here", while loading the data in background:
![image](https://user-images.githubusercontent.com/24530680/139401792-a87db86c-a9a5-4766-aaf8-d8b44cc1d5e5.png)

**Comment by jakobroehrl** [comment] 2021-12-03 11:37
Now there is a spinner, nice!

**Comment by AlvaroBrey** [comment] 2021-12-03 14:35
Duplicate of #9373

**Closed by AlvaroBrey** 2021-12-03 14:35 UTC
Labels: enhancement

**Comment by jakobroehrl** [comment] 2021-12-05 10:00
Thanks for looking over it.
I don't think it's exactly the same. 
This issue is about not showing the content after opening the shared section
The issue #9373 is about a refresh in the shared section

**Comment by AlvaroBrey** [comment] 2021-12-09 09:34
@jakobroehrl same thing, the "refresh" process also runs when opening the section.
