### ISSUE TITLE
Cannot Open Hamburger Menu

### ISSUE THREAD

**Issue by umarag4** [nextcloud/android#8906] opened 2021-08-27 09:07 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Canvas: trying to draw too large(106328180bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:1018)
	at android.widget.ImageView.onDraw(ImageView.java:1436)
	at android.view.View.draw(View.java:22354)
	at android.view.View.updateDisplayListIfDirty(View.java:21230)
	at android.view.View.draw(View.java:22085)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22357)
	at android.view.View.updateDisplayListIfDirty(View.java:21230)
	at android.view.View.draw(View.java:22085)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21221)
	at android.view.View.draw(View.java:22085)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22357)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
	at android.view.View.updateDisplayListIfDirty(View.java:21230)
	at android.view.View.draw(View.java:22085)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22357)
	at com.google.android.material.internal.ScrimInsetsFrameLayout.draw(ScrimInsetsFrameLayout.java:109)
	at android.view.View.updateDisplayListIfDirty(View.java:21230)
	at android.view.View.draw(View.java:22085)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22357)
	at android.view.View.updateDisplayListIfDirty(View.java:21230)
	at android.view.View.draw(View.java:22085)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21221)
	at android.view.View.draw(View.java:22085)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21221)
	at android.view.View.draw(View.java:22085)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21221)
	at android.view.View.draw(View.java:22085)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21221)
	at android.view.View.draw(View.java:22085)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22357)
	at com.android.internal.policy.DecorView.draw(DecorView.java:806)
	at android.view.View.updateDisplayListIfDirty(View.java:21230)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4103)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3830)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3101)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1954)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8180)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
	at android.view.Choreographer.doCallbacks(Choreographer.java:878)
	at android.view.Choreographer.doFrame(Choreographer.java:811)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7698)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: laurel_sprout
Model: Mi A3
Id: RKQ1.200903.002
Product: laurel_sprout

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: V12.0.12.0.RFQMIXM

**Comment by tobiasKaminsky** [comment] 2021-08-30 06:16
Can you tell us when this happens?
Is it the navigation drawer, opening from left side?

**Comment by umarag4** [comment] 2021-08-30 07:01
Yes, both when sliding from left or when tapping the drawer button.

30 Aug 2021, 2:16 pm by ***@***.***:

**Comment by AlvaroBrey** [comment] 2021-09-09 09:03
Duplicate of #8862

**Closed by AlvaroBrey** 2021-09-09 09:03 UTC
Labels: bug, needs info/discussion
