### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dimitar8080** [nextcloud/android#10262] opened 2022-05-17 21:17 UTC
### Cause of error
```java
Exception in thread "AsyncTask #2" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:415)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)
Caused by: Exception in thread "AsyncTask #2" java.lang.RuntimeException: Accessing result data after operation failed!
    at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:512)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.doInBackground(GallerySearchTask.java:102)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.doInBackground(GallerySearchTask.java:48)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a52sxq`
* Model: `SM-A528B`
* Id: `SP1A.210812.016`
* Product: `a52sxqeea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `A528BXXS1CVD1`

**Comment by AlvaroBrey** [comment] 2022-05-18 09:10
Duplicate of #10198

**Closed by AlvaroBrey** 2022-05-18 09:10 UTC
