### ISSUE TITLE
Java Exception 

### ISSUE THREAD

**Issue by archithn1** [nextcloud/android#13059] opened 2024-06-01 06:02 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I uploaded 120 GB of Photos to directory and did occ scan file photos appeared but nextcloud getting too slow and throws error

### Expected behaviour

If I opened folder it has to load it's throwing java Exception 

### Actual behaviour

Unable to open photos it throws error

### Android version

13

### Device brand and model

Samsung Galaxy S20 FE 5G

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.0

### Nextcloud server version

Nextcloud Hub 8 (29.0.1)

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "Thread-15" java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 1161864 free bytes and 1134KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
    at org.apache.harmony.xml.dom.InnerNodeImpl.getChildNodes(InnerNodeImpl.java:56)
    at org.apache.jackrabbit.webdav.xml.DomUtil.hasContent(DomUtil.java:377)
    at org.apache.jackrabbit.webdav.property.DefaultDavProperty.createFromXml(DefaultDavProperty.java:127)
    at org.apache.jackrabbit.webdav.MultiStatusResponse.createFromXml(MultiStatusResponse.java:463)
    at org.apache.jackrabbit.webdav.MultiStatus.createFromXml(MultiStatus.java:185)
    at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.processResponseBody(DavMethodBase.java:282)
    at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1749)
    at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
    at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
    at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
    at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:192)
    at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:62)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:413)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:247)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:387)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `r8q`
* Model: `SM-G781B`
* Id: `TP1A.220624.014`
* Product: `r8qxxx`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `G781BXXSBHXE7`

**Comment by Humol-e** [comment] 2024-06-20 02:03
Based on what the error says
`java.lang.OutOfMemoryError`
It may be that your storage on the cloud is full.

**Comment by joshtrichards** [comment] 2024-07-09 19:33
Duplicate of #11627

**Closed by joshtrichards** 2024-07-09 19:33 UTC
Labels: bug, performance: OOM :brain:, Version/3029
