### ISSUE TITLE
Media tab pictures preview doesn't shows up on One UI 4 (Samsung Galaxy s21)

### ISSUE THREAD

**Issue by SofianeLasri** [nextcloud/android#10547] opened 2022-07-21 07:29 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Login to your next loud account on the mobile client (Android). Be sure to have a Samsung Galaxy S21 that is up to date to have the same condition as me.
2. Go into the media tab on the sidebar.

### Expected behaviour

The media tab should shows you previews of your pictures but not videos. It could be used just like a simpler version of a famous photo gallery app of a very big company that made the most visited website in the world.

### Actual behaviour

Previews don't load at all.

### Android version

12

### Device brand and model

SM-G991B/DS

### Stock or custom OS?

Stock

### Nextcloud android app version

3.20.3

### Nextcloud server version

24.0.3

### Using a reverse proxy?

No

### Additional information

I am unable to access a computer during this week, sorry.
The previews shows up on a old 2014 Samsung Galaxy Tab S10.5, and 2013 Samsung Galaxy S4 Advance (and on desktop through web browser).

**Comment by AlvaroBrey** [comment] 2022-07-21 08:59
Can you give an estimate of the amount of pictures you might have in your account? As in: dozens, hundreds, thousands...? It might just be that the device is overwhelmed by loading so many at once, but I find it weird that it would work on other, older devices

Thanks!

P.S.: You're allowed to say Google Photos 😂

**Comment by SofianeLasri** [comment] 2022-07-21 16:30
Hi, thx for your fast answer. I have a thousand of pictures in my account. Pictures represent a great part of my used storage.

It's ok for saying Google Photo. xD

**Comment by ifelixculpa** [comment] 2022-07-23 16:02
can images/videos on the nextcloud be viewed in samsung native gallery ?

**Comment by SofianeLasri** [comment] 2022-07-24 08:05
Yes they can.

**Comment by ifelixculpa** [comment] 2022-07-24 08:12
> Yes they can. But I don't have all my pictures synchronized on my device, only ones that were took through the camera.

if you can share how , would be amazing sir

**Comment by SofianeLasri** [comment] 2022-07-24 09:36
![Screenshot_20220724-113120_Gallery.jpg](https://user-images.githubusercontent.com/43948827/180641178-2257267a-291e-4704-93e4-acc85f848add.jpg)
![Screenshot_20220724-113109_Gallery.jpg](https://user-images.githubusercontent.com/43948827/180641184-177d2173-a349-479a-8965-a42c3a16c96d.jpg)
https://user-images.githubusercontent.com/43948827/180641193-39e2415f-9fc8-4ea3-8dbc-b7e4fa955b31.mp4

**Comment by ifelixculpa** [comment] 2022-07-24 12:07
> ![Screenshot_20220724-113120_Gallery.jpg](https://user-images.githubusercontent.com/43948827/180641178-2257267a-291e-4704-93e4-acc85f848add.jpg) ![Screenshot_20220724-113109_Gallery.jpg](https://user-images.githubusercontent.com/43948827/180641184-177d2173-a349-479a-8965-a42c3a16c96d.jpg) https://user-images.githubusercontent.com/43948827/180641193-39e2415f-9fc8-4ea3-8dbc-b7e4fa955b31.mp4
> 
> My network isn't very fast, but previews loads on my two tablets and on web browser.

cant thankyou enough , thankyou sir ... you dint do anything special just setup normally and can see inside phone gallery right sir ?

**Comment by ifelixculpa** [comment] 2022-07-24 12:26
> ![Screenshot_20220724-113120_Gallery.jpg](https://user-images.githubusercontent.com/43948827/180641178-2257267a-291e-4704-93e4-acc85f848add.jpg)
> ![Screenshot_20220724-113109_Gallery.jpg](https://user-images.githubusercontent.com/43948827/180641184-177d2173-a349-479a-8965-a42c3a16c96d.jpg)
> https://user-images.githubusercontent.com/43948827/180641193-39e2415f-9fc8-4ea3-8dbc-b7e4fa955b31.mp4
> 
> My network isn't very fast, but previews loads on my two tablets and on web browser.

Also sir having this upload issue while uploading

https://user-images.githubusercontent.com/13099434/180646928-71f91128-290e-4155-811a-d390254b9ef9.mp4

**Comment by SofianeLasri** [comment] 2022-07-24 12:54
No I didn't do anything special, just go into the gallery app as usual.

**Comment by ifelixculpa** [comment] 2022-07-24 13:30
> No I didn't do anything special, just go into the gallery app as usual.

thanks alot sir il take a look again

**Comment by ifelixculpa** [comment] 2022-07-24 18:25
> Yes they can. But I don't have all my pictures synchronized on my device, only ones that were took through the camera.

Got working sir one last thing if u could help with sorry for being a pain...can i share these uploads to someone outside my home network ? If yes how sir

**Comment by SofianeLasri** [comment] 2022-07-24 21:23
![Screenshot_20220724-113120_Gallery.jpg](https://user-images.githubusercontent.com/43948827/180641178-2257267a-291e-4704-93e4-acc85f848add.jpg)
![Screenshot_20220724-113109_Gallery.jpg](https://user-images.githubusercontent.com/43948827/180641184-177d2173-a349-479a-8965-a42c3a16c96d.jpg)
https://user-images.githubusercontent.com/43948827/180641193-39e2415f-9fc8-4ea3-8dbc-b7e4fa955b31.mp4

I'm not sure to understand, you want share my two pictures and the video I sent on this bug report?

**Comment by ifelixculpa** [comment] 2022-07-25 05:53
> I'm not sure to understand, you want share my two pictures and the video I sent on this bug report?

no sir i mean if there is a file on nextcloud how do i share it with someone outside myhome network , i am trying but other then my no one can open that link

i have also forwarded port 80 and 443 still no luck
it still shows this sir

![image](https://user-images.githubusercontent.com/13099434/180707533-852c2c61-43cc-4d53-a1ba-932a23f47531.png)

**Comment by SofianeLasri** [comment] 2022-07-25 07:10
Oh ok, but I don't think it's the correct place to ask this.
You have to open ports 80 and 443 on your isp box, why not linking a domain name with your IP, and you should be able to share files with nextcloud.

**Comment by ifelixculpa** [comment] 2022-07-25 07:19
> Oh ok, but I don't think it's the correct place to ask this. You have to open ports 80 and 443 on your isp box, why not linking a domain name with your IP, and you should be able to share files with nextcloud.

ye sir, i am extremely sorry for my actions but I have been trying for many days and nothing is working, i even tried to add you on discord sir ...sorry again

**Comment by SofianeLasri** [comment] 2022-07-25 07:23
> > Oh ok, but I don't think it's the correct place to ask this. You have to open ports 80 and 443 on your isp box, why not linking a domain name with your IP, and you should be able to share files with nextcloud.
> 
> ye sir, i am extremely sorry for my actions but I have been trying for many days and nothing is working, i even tried to add you on discord sir ...sorry again

No problem, add me again I'll accept. 👍

**Comment by ifelixculpa** [comment] 2022-07-25 07:28
> > > Oh ok, but I don't think it's the correct place to ask this. You have to open ports 80 and 443 on your isp box, why not linking a domain name with your IP, and you should be able to share files with nextcloud.
> > 
> > 
> > ye sir, i am extremely sorry for my actions but I have been trying for many days and nothing is working, i even tried to add you on discord sir ...sorry again
> 
> No problem, add me again I'll accept. 👍

sent sir , thanks alot

**Comment by AlvaroBrey** [comment] 2022-08-03 11:12
@SofianeLasri @ifelixculpa be aware that none of the people in this ticket (except me) is a Nextcloud maintainer. So be wary of sharing credentials, etc on that discord or whatever. I'll mark all of your extra conversation as offtopic. Please keep the comments relevant to this issue or I'll lock it.

**Comment by svenb1234** [comment] 2022-09-03 06:28
Isn't this a duplicate of #10389 ?

**Comment by SofianeLasri** [comment] 2022-12-04 22:33
Problem solved when doing a clean re-install of the app.

**Closed** 2022-12-04 22:33 UTC
Labels: bug
