### ISSUE TITLE
App crashes while syncing keepass file from /e/cloud documents folder

### ISSUE THREAD

**Issue by theSilverFisch** [nextcloud/android#9441] opened 2021-12-03 10:01 UTC
### Steps to reproduce
1. Open app
2. Tab on .kdbx file in documents
3. See crash log

### Expected behaviour
- synchronising file

### Actual behaviour
- crashes with null pointer

### Environment data
Android version: 9

Device model:  fairphone 3

Stock or customized system: /e/ 

Nextcloud app version: 20211119

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.nextcloud.java.util.Optional.get()' on a null object reference
	at com.owncloud.android.files.services.FileDownloader.downloadFile(FileDownloader.java:486)
	at com.owncloud.android.files.services.FileDownloader.access$500(FileDownloader.java:87)
	at com.owncloud.android.files.services.FileDownloader$ServiceHandler.handleMessage(FileDownloader.java:422)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20211119
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Fairphone
Device: FP3
Model: FP3
Id: PQ3A.190801.002
Product: FP3

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.root.20211027.143336

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2021-12-03 10:29
Duplicate of #9349. Should be fixed in the latest dev version, and it's not broken in the stable version either.

**Closed by AlvaroBrey** 2021-12-03 10:29 UTC
Labels: bug
