### ISSUE TITLE
NEW_NOTIFICATION

### ISSUE THREAD

**Issue by rubrik** [nextcloud/android#2110] opened 2018-02-06 18:14 UTC
### Actual behaviour
-Just got a notification, it said NEW_NOTIFICATION NEW_NOTIFICATION
-Selected it, NextCloud opened on the main page
-That was it
-Looked in Notifications area, read most recent message about the upgrade to 13.0

### Expected behaviour
-Get a notification with a subject and text
-Select it, go to full notification text
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version: 3.0 RC3

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2018-02-06 18:16
@mario @tobiasKaminsky any ideas? I can only think of the server sending this to the client (which than would have to be a server issue)

**Comment by mario** [comment] 2018-02-06 18:16
It's the server sending this, but on purpose. This will be fixed by me in 3.1 :)

**Comment by tobiasKaminsky** [comment] 2018-02-07 07:36
Duplicate of #1964

**Closed by tobiasKaminsky** 2018-02-07 07:36 UTC

**Comment by xXSTrikeXx** [comment] 2018-02-08 15:42
Hell, year! Good work. For me the first notification was sent to me on v.3.0 and server v.13.0. Good work that it finally works (had never done it before) :) I´m very happy :D
