### ISSUE TITLE
Problem downloading files from phone

### ISSUE THREAD

**Issue by ArtemDrach** [nextcloud/android#9198] opened 2021-11-04 03:06 UTC
Hello everyone.

The situation is as follows:

1. Take a picture on your phone
2. I click send
3. I choose the Nextcloud application
4. Choose a folder to save
5. I press the send button
6. I get the error: Error transferring to the server. You do not have permission to transfer to this folder
7. The file does not load

Another scenario.

1. Take a picture on your phone
2. I click send
3. I choose the WhatsApp application
4. I send a picture to the WhatsApp chat
5. In the chat, I select this picture and press share
6. I choose the Nextcloud application
7. Choose a folder to save
8. I press the send button
9. The file is loaded

Why it happens?

**Comment by ArtemDrach** [comment] 2021-11-05 11:08
Another situation

1. I receive a file in the chat whatsapp (pdf)
2. Select the file and click send
3. I choose the NextCloud application
4. I get the error: Error transferring to the server. You do not have permission to transfer to this folder
5. File not loaded

Another scenario:
1. I receive a file in the chat whatsapp (pdf)
2. I save the file on my computer
3. I go to the NextCloud application through the browser
4. I choose to download the file
5. The file is loading

Why is this happening with the same file?
There is nothing in the logs.

**Comment by AlvaroBrey** [comment] 2022-11-23 14:19
Duplicate of #6570

**Closed by AlvaroBrey** 2022-11-23 14:19 UTC
Labels: bug
