### ISSUE TITLE
highlight synced folders

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#4719] opened 2019-10-22 20:30 UTC
Whenever a file is synced it gets a small icon indicating it is available offline. The same icon should be used on folders too, I think. 

![Screenshot_20191022-222905_Nextcloud](https://user-images.githubusercontent.com/1469150/67329660-72c5d280-f51b-11e9-9302-f28b5b842468.jpg)

![Screenshot_20191022-222926_Nextcloud](https://user-images.githubusercontent.com/1469150/67329686-7bb6a400-f51b-11e9-8b45-5d4a937d6714.jpg)

**Comment by joshtrichards** [comment] 2023-12-14 16:16
Duplicate of #6785

**Closed by joshtrichards** 2023-12-14 16:16 UTC
Labels: enhancement, design, feature: files, feature: sync and upload
