### ISSUE TITLE
Clicked on Shared in the Menu

### ISSUE THREAD

**Issue by NIronwolf** [nextcloud/android#10264] opened 2022-05-19 18:12 UTC
I was just looking around the app and when I clicked "Shared" in the laft menu it immediately crashed. 

Running v22 through a Docker container. 

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'com.owncloud.android.utils.FileSortOrder$SortType com.owncloud.android.utils.FileSortOrder.getType()' on a null object reference
    at com.owncloud.android.ui.adapter.OCFileListAdapter.getPopupText(OCFileListAdapter.java:905)
    at me.zhanghai.android.fastscroll.RecyclerViewHelper.getPopupText(RecyclerViewHelper.java:136)
    at me.zhanghai.android.fastscroll.FastScroller.onPreDraw(FastScroller.java:198)
    at me.zhanghai.android.fastscroll.FastScroller.$r8$lambda$fhoCEu3yFeBM02d2QCiuR_Ev5oo(Unknown Source:0)
    at me.zhanghai.android.fastscroll.FastScroller$$ExternalSyntheticLambda1.run(Unknown Source:2)
    at me.zhanghai.android.fastscroll.RecyclerViewHelper$1.onDraw(RecyclerViewHelper.java:52)
    at androidx.recyclerview.widget.RecyclerView.onDraw(RecyclerView.java:4668)
    at android.view.View.draw(View.java:23187)
    at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
    at android.view.View.updateDisplayListIfDirty(View.java:22062)
    at android.view.View.draw(View.java:22917)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
    at android.view.View.draw(View.java:23190)
    at android.view.View.updateDisplayListIfDirty(View.java:22062)
    at android.view.View.draw(View.java:22917)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
    at android.view.View.updateDisplayListIfDirty(View.java:22048)
    at android.view.View.draw(View.java:22917)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
    at android.view.View.updateDisplayListIfDirty(View.java:22048)
    at android.view.View.draw(View.java:22917)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
    at android.view.View.draw(View.java:23190)
    at android.view.View.updateDisplayListIfDirty(View.java:22062)
    at android.view.View.draw(View.java:22917)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
    at android.view.View.updateDisplayListIfDirty(View.java:22048)
    at android.view.View.draw(View.java:22917)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
    at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
    at android.view.View.draw(View.java:23190)
    at android.view.View.updateDisplayListIfDirty(View.java:22062)
    at android.view.View.draw(View.java:22917)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
    at android.view.View.updateDisplayListIfDirty(View.java:22048)
    at android.view.View.draw(View.java:22917)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
    at android.view.View.updateDisplayListIfDirty(View.java:22048)
    at android.view.View.draw(View.java:22917)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
    at android.view.View.updateDisplayListIfDirty(View.java:22048)
    at android.view.View.draw(View.java:22917)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
    at android.view.View.updateDisplayListIfDirty(View.java:22048)
    at android.view.View.draw(View.java:22917)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
    at android.view.View.draw(View.java:23190)
    at com.android.internal.policy.DecorView.draw(DecorView.java:1154)
    at android.view.View.updateDisplayListIfDirty(View.java:22062)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:588)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:594)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:667)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:4293)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4077)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3345)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2222)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9123)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
    at android.view.Choreographer.doCallbacks(Choreographer.java:797)
    at android.view.Choreographer.doFrame(Choreographer.java:732)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:8167)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `crownqltesq`
* Model: `SM-N960U`
* Id: `QP1A.190711.020`
* Product: `crownqltesq`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `N960USQS9FVC5`

**Comment by AlvaroBrey** [comment] 2022-05-20 07:12
Duplicate of #10227

**Closed by AlvaroBrey** 2022-05-20 07:12 UTC
