### ISSUE TITLE
Shared folder check mark missing for "Allow editing"

### ISSUE THREAD

**Issue by billie80** [nextcloud/android#7021] opened 2020-09-27 20:01 UTC
### Steps to reproduce
1. Share a folder
2. Enable "Allow editing"

### Expected behaviour
- After enable editing the setting should have a visible checkmark

### Actual behaviour
- No visible checkmark although editing seems to be allowed
- Tapping again "Allow editing" does not seem to disable it again
- The setting below "Hide download" can be toggled as expected

### Environment data
Android version: 10

Device model: SHIFT6mq

Stock or customized system: Stock

Nextcloud app version: 3.13.1

Nextcloud server version: 18.0.3

Reverse proxy:

![Screenshot_Nextcloud](https://user-images.githubusercontent.com/9938306/94374652-07628880-010e-11eb-962d-ee254ed7dfaa.png)

**Comment by tobiasKaminsky** [comment] 2020-09-29 10:48
This will be fixed with 3.14.

**Comment by billie80** [comment] 2020-09-29 12:13
Thanks for letting me know. Any ETA for the 3.14 release?

**Comment by AndyScherzinger** [comment] 2020-09-29 12:48
Release Candidate might be available next week, so ETA of the final release is ~3 weeks

**Comment by billie80** [comment] 2020-09-29 19:47
I just tested Nextcloud Dev 20200927 and for me the problem is still there.
The buttons have changed. Now one can radio between 'Read only', 'Allow upload and editing' and 'File drop (Upload only). When selecting 'Allow upload and editing' there is still the empty button. The buttons for the other two options work.

**Comment by tobiasKaminsky** [comment] 2020-10-19 09:06
![2020-10-19-110613](https://user-images.githubusercontent.com/5836855/96424538-1ca57100-11fb-11eb-8401-d5b50ea2820a.png)


Can you give me a screenshot, so that we can compare?

**Comment by billie80** [comment] 2020-10-19 10:45
Looks like this is not necessary anymore! It works now as expected with the latest dev version 20201017. However it also works with 3.13.1.
Yesterday the cloud was updated to version 20.0.0. So I guess this is an issue with the server version!

**Closed** 2020-10-21 05:54 UTC
Labels: bug, needs info/discussion

**Comment by mrAceT** [comment] 2022-01-28 21:44
nextcloud version: 22.2.3

When I check the box 'allow editing' the box is set.. when I reload the browser and check again the box is unset..

I tred to use https://github.com/tavinus/cloudsend.sh

But I get the message:
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
  <s:message/>
</d:error>
```
And I fear that checkbox might be the cause?
