### ISSUE TITLE
Nextcloud app didn't use thumbnail generated by preview generator

### ISSUE THREAD

**Issue by BVEsun** [nextcloud/android#2850] opened 2018-07-26 02:09 UTC
### Actual behaviour
Very slow image viewing experience even all image thumbnail generated by preview generator

### Expected behaviour
Faster Image viewing experience after pre-generate all thumbnail.
 
### Steps to reproduce
1. Using preview generator: https://github.com/rullzer/previewgenerator
2. preview:generate-all
3. Confirmed all thumbnail generated in appdata / preview folder

### Environment data
Android version:
8.0.0
Device model: 
Sony Xperia XZ2
Stock or customized system:
No
Nextcloud app version:
3.2.1
Nextcloud server version:
13.0.5
#### Web server error log
No error
Insert your webserver log here
[26/Jul/2018:10:07:57 +0800] "GET /nextcloud/index.php/apps/files/api/v1/thumbnail/256/256/Photo/2015/06/IMG_20150620_103208.jpg HTTP/1.1" 200 18874 "-" "Mozilla/5.0 (Android) ownCloud-android/3.2.1" "-"

#### Nextcloud log (data/nextcloud.log)
No new message
Insert your Nextcloud log here
No new message
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by BVEsun** [comment] 2018-07-28 14:11
As I try to solve the problem, I think the issue is that android app didn't pull all thumbnail simultaneously. It pull the thumbnail one by one, which make it much slower compare webpage version.

**Comment by nero120** [comment] 2018-07-29 21:18
I noticed this as well, the mobile app is **very** slow when displaying image thumbnails in tile view, even though the thumbnails have been pregenerated and display immediately in web view. It doesn't feel like the mobile app is using the pregenerated thumbnails, because how can it take 15 seconds to display a single tiny thumbnail?? It feels like it's generating each thumbnail, not using the pre-generated ones.

**Comment by AndyScherzinger** [comment] 2018-07-31 09:07
I'd expect the app to use the pre-generated thumbnails but can't say for sure. Maybe @rullzer and @tobiasKaminsky know more about it.
It might in some cases come to some waiting time due to other asynchronous server calls and I know that @tobiasKaminsky is working on a rewrite of the thumbnail fetching/caching on the Android client which might improve the situation.

**Comment by Gatak** [comment] 2018-08-27 11:10
Is there maybe a way to improve things with HTTP/2 and push content? I.e the server can preemptively push thumbnails when a directory is opened in the app. This might need tweaking in case of thousands of files, but should otherwise be very fast.

**Comment by elpedriyo** [comment] 2018-11-03 22:55
No fix yet on displaying photos quicker on the android app?

**Comment by rullzer** [comment] 2018-11-04 21:42
The endpoint in use does use the pregenerated previews. Of course it all still has to be fetched

**Comment by Gatak** [comment] 2018-11-05 15:36
> The endpoint in use does use the pregenerated previews. Of course it all still has to be fetched

That's really good. However the speed isn't so good. About 20 seconds to load a folder with 28 thumbnails for 28 jpegs over fast WiFi on a local server.  Using Opera browser with the same folder takes about 8-10 seconds, including scrolling to see all pictures.

**Comment by nero120** [comment] 2018-11-05 15:43
@rullzer out of interest which component is the bottleneck here, redis? Surely it should be a matter of nanoseconds for the server to return a preview that has already been generated?

**Comment by rullzer** [comment] 2018-11-05 21:59
@nero120 are you 100% certain the previews for that file are all properly generated already? Because on my production sytem retruning a preview is <300ms

**Comment by nero120** [comment] 2018-11-06 11:14
@rullzer I believe so, if I browse to the list view of a folder (with browser cache disabled) most of the previews do appear pretty much immediately, however there seems to be always one that takes ages to appear. If I then browse directly to the link of the slow preview image (as above) it takes ~11 seconds to appear:

![image](https://user-images.githubusercontent.com/4236238/48060849-0ab89800-e1b5-11e8-9070-9f0d872bdef0.png)

I don't want to take this off topic but I wondered if this was related at all to the title issue.

**Comment by rullzer** [comment] 2018-11-06 13:58
@nero120 no that is not the fault of android. Please open an issue in the server repo. And maybe attach the image that is causing trouble.

The android client just fetches this from the server there is no magic involved there.

**Comment by nero120** [comment] 2018-11-06 16:44
Ok thanks @rullzer.

**Comment by tobiasKaminsky** [comment] 2018-11-07 05:51
So this can be closed as Roeland pointed out that this is a server issue.
If you find out that this is related to Android, please re-open.

**Closed by tobiasKaminsky** 2018-11-07 05:51 UTC
Labels: bug

**Comment by Gatak** [comment] 2018-11-07 09:13
I guess the issue is really the extreme slowness in loading previews. Perhaps the topic is just badly worded. It feels like pre-generated previews aren't used because it is so slow, while in fact it is the way how the android client fetches them.

**Comment by DougParker1992** [comment] 2018-11-07 11:45
I gave Nextcloud a try and left after just a couple of days because of the Android App in specific. Don't worry, it's not just you. I also used that recommended thumbnail preview generation app which helped with Desktop/Web but didn't do jack for the Android client.

---
Douglas Parker

________________________________

**Comment by mathiasmoeller** [comment] 2019-10-01 15:31
Sorry for anyone who receives a notification now but: @nero120 did you open an issue on the server side and did anything happen? Could not find anything in the server repository issues. The speed in the android app is insanely slow while the web app is fast

**Comment by nero120** [comment] 2019-10-01 15:36
@mathiasmoeller ack no I didn't, must have slipped my mind completely 😦

**Comment by mathiasmoeller** [comment] 2019-10-02 07:55
> @nero120 no that is not the fault of android. Please open an issue in the server repo. And maybe attach the image that is causing trouble.
> 
> The android client just fetches this from the server there is no magic involved there.

@rullzer Might it be that the android client fetches every preview image one by one in a single connection? Even if the previews are generated and small this might cause the long waiting time.

**Comment by Gatak** [comment] 2019-10-02 08:34
> Might it be that the android client fetches every preview image one by one in a single connection? Even if the previews are generated and small this might cause the long waiting time.
It is likely. I do think previews are used, but the sequential way they are downloaded is very slow. about 0.5-1 second per picture.

So technically, the bug report is probably incorrect in that the app is using the pre-generated previews (can someone verify?). However the meaning of the report is that the images load really slowly, so in that context I think this bug report should be re-opened. I don't think it is a server issue.

**Comment by nero120** [comment] 2019-10-02 09:34
> So technically, the bug report is probably incorrect in that the app is using the pre-generated previews (can someone verify?).

I don't know the android app codebase well, I can see that it has a class [`ThumbnailsCacheManager`](https://github.com/nextcloud/android/blob/master/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java) that does [request the correct endpoint](https://github.com/nextcloud/android/blob/master/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java#L316), but whether that line is triggered correctly by the thumnbnail view, and whether it is using a thread per thumbnail I'm not entirely sure.

**Comment by AndyScherzinger** [comment] 2019-10-02 10:57
@tobiasKaminsky likely to knows best while I think they are loaded sequentially and also there is a older PR that not quite fully working to switch to glide for fetching and caching images from the server.

**Comment by Gatak** [comment] 2019-10-03 07:26
#4558 is related to this I guess.

**Comment by tobiasKaminsky** [comment] 2019-10-08 13:34
Yes, pictures are handled one by one, but still it should not take 1s per photo as each thumbnail is ~30kb at most.

**Comment by Gatak** [comment] 2019-10-08 16:04
Yup. But it does, even when I have very fast WiFi connection on the same LAN as the server.

**Comment by dgtlmoon** [comment] 2019-11-12 10:15
Poking at the server code (for the first time!), I can see that it's not using any advanced mechanism for using the _existing_ thumbnail that already exists in the file, there's no check for using the thumbnail that's already present in the metadata of the image.

https://stackoverflow.com/questions/10349622/extract-thumbnail-from-jpeg-file

```
private function generatePreview(ISimpleFolder $previewFolder, ISimpleFile $maxPreview, $width, $height, $crop, $maxWidth, $maxHeight, $prefix) {
                $preview = $this->helper->getImage($maxPreview);
....
                                $preview->preciseResize((int)round($scaleW), (int)round($scaleH));
....
                        $preview->resize(max($width, $height));
                }
```

**Comment by tobiasKaminsky** [comment] 2019-11-12 13:03
@dgtlmoon please move discussion to server repo, as this has to be fixed / discussed there.

**Comment by sosed213** [comment] 2021-07-07 03:54
The problem with slow loading of image previews in the Android application persists to this day.
Nextcloud Server 21.0.3 and Nextcloud 22.0.0.
Nextcloud App for Android 3.16.1

Google Pixel 3 smartphone, Android 11.

Slowly works over wifi in the local network with the Nextcloud server, and over the LTE network.

**Comment by colyro** [comment] 2021-07-08 07:39
The same to me too:

NC 21.xx and NC 22.0 as server, centos 8, apache in http/2 mode.

Huawei P20 android 10.
Previews are not shown and a loading icon is showing in the app and freezes it.

**Comment by vnhirenko** [comment] 2022-02-05 06:42
+1 still occurs on Android device.

**Comment by tobiasKaminsky** [comment] 2022-02-10 08:57
Can you check in nextcloud.log which thumbnail sizes are requested and which are generated by generator?
