### ISSUE TITLE
Search focus reset after loading all files

### ISSUE THREAD

**Issue by szaimen** [nextcloud/android#10037] opened 2022-04-01 23:31 UTC
### Steps to reproduce
1. Log into the app
2. See the standard files view
3. Click in the search field while it is loading

### Expected behaviour

4. After it has loaded all files I want to stay in the search field

### Actual behaviour
4. After it loaded all files, the focus gets reset and I am no longer in the search field

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 12

Device model: Samsung Galaxy S10e

Stock or customized system: Stock

Nextcloud app version: 3.20 RC1

Nextcloud server version: 22.2.6

Reverse proxy: no

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by szaimen** [comment] 2022-04-02 20:54
cc @AlvaroBrey as discussed :)

**Comment by XueSheng-GIT** [comment] 2022-05-07 14:22
Seems to be the same issue as https://github.com/nextcloud/android/issues/9481

**Comment by AlvaroBrey** [comment] 2022-05-09 07:19
Duplicate of #9481

**Comment by AlvaroBrey** [comment] 2022-05-09 07:19
Thanks @XueSheng-GIT

**Closed by AlvaroBrey** 2022-05-09 07:19 UTC
Labels: bug, approved
