### ISSUE TITLE
Error while synchronizing  (file reception )

### ISSUE THREAD

**Issue by demetreCh** [nextcloud/android#9178] opened 2021-10-30 09:21 UTC
### Steps to reproduce
1. Nothing special was done, I uploaded a file twice in a while from another device.  
2. My android device is showing a notification  : file reception in progress (translated)
3. When tapping on the notification,  nextcloud opens up, and shows a stack trace (attached)

### Expected behaviour
- expected the file view to be opened normally

### Actual behaviour
- got an ap crash instead 
![Screenshot_20211030-112856](https://user-images.githubusercontent.com/26851138/139527698-d34341cc-120f-46d7-a145-233086c20d23.png)

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: Nokia 5.1 plus

Stock or customized system: stock

Nextcloud app version: 3.16.1

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2021-11-02 07:45
Duplicate of #8370

**Closed by AlvaroBrey** 2021-11-02 07:45 UTC
Labels: bug
