### ISSUE TITLE
encrypted folder inaccessible

### ISSUE THREAD

**Issue by michaelfliegner** [nextcloud/android#13901] opened 2024-10-30 07:55 UTC
### Cause of error
```java
Exception in thread "Thread-30" java.lang.IllegalStateException: metadata is null!
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:498)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:418)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:247)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:387)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `motorola`
* Device: `cofud`
* Model: `moto g31(w)`
* Id: `S3RWDS32.123-29-8-2-9`
* Product: `cofud_ge`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `c02de7`

Cannot delete once encrypted folder on Linux. The only context menu entry is 'edit ignored files" Get Exception in android cient on accessing the folder.

Is this the first time you've seen this error? _(Y)_:

Steps to replicate it:

1. Not sure. Start with error, when I tried to ecrypt non empty folder. Tried to 
2. 
3. 

The output of your Nextcloud log in **Admin > Logging**:
[Log](https://steilo.michaelfliegner.de/s/tw6Feq9JjPGGzkf)

**Comment by joshtrichards** [comment] 2024-10-30 12:41
Duplicate of #13646

**Closed** 2024-10-30 12:42 UTC

**Comment by michaelfliegner** [comment] 2024-10-30 12:57
![Image](https://github.com/user-attachments/assets/b2ab2552-119a-4bcc-8cd9-274fcd214bf6)
