### ISSUE TITLE
Android Navigation Bar gets turned completely white

### ISSUE THREAD

**Issue by fredddd1** [nextcloud/android#8280] opened 2021-04-14 12:14 UTC
### Steps to reproduce
1. Have a Nextbit Robin with the latest stock software
2. Use Nextcloud from F-Droid

### Expected behaviour
- Tell us what should happen
For the navigation bar at the bottom to not be white so I can see the icons on it.

### Actual behaviour
- Tell us what happens
Navigation bar is completely white.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 7.1.1

Device model: Nextbit Robin

Stock or customized system: Stock

Nextcloud app version: 3.15.1

Nextcloud server version: Irrelevant

Reverse proxy: No

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

![Screenshot_20210414-141029](https://user-images.githubusercontent.com/80743272/114708525-bd4c9780-9d2b-11eb-8b8e-d950b10547d0.png)

![Screenshot_20210414-141020](https://user-images.githubusercontent.com/80743272/114708526-bde52e00-9d2b-11eb-9a69-438e043b3b8e.png)

**Comment by szaimen** [comment] 2021-04-14 13:53
Duplicate of #7736

**Closed by szaimen** 2021-04-14 13:53 UTC
Labels: bug
