### ISSUE TITLE
App crashes when scanning qr code with provisioning link

### ISSUE THREAD

**Issue by LiamHD** [nextcloud/android#2307] opened 2018-03-07 07:14 UTC
### Actual behaviour
I created a qr-code containing a provisioning link like this:
nc://login/user:test?server:docs.myserver.de
When the qr code is scanned android ask if I want to open this url with nextcloud. After saying yes to that question the nextcloud app crashes.

If I have the provisioning link in a HTML-Link <a href="...">..</a>. The app does not crash.

### Expected behaviour
App should not crash but should log in
 
### Steps to reproduce
1. Create provisioning link
2. Create qr code
3. Scan qr code

### Environment data
Android version:
7.0

Device model: 
Samsung Galaxy Tab S3
Stock or customized system:
stock
Nextcloud app version:
3.0.3
Nextcloud server version:
13.0.0

**Comment by xXSTrikeXx** [comment] 2018-03-07 12:32
In the end a duplicate of #2308.
But this shouldnt crash the app. Could you provide us the nextcloud android app (settings->protocol) which includes the crash?

**Comment by LiamHD** [comment] 2018-03-07 12:46
settings->protocol unfortunately does not include any entry for the crash

**Comment by LiamHD** [comment] 2018-03-07 13:05
I just get this error dialog in the QR-code scanner app:
![image](https://user-images.githubusercontent.com/6286072/37093699-94081028-2210-11e8-9d49-95f353b2a37d.png)

**Comment by xXSTrikeXx** [comment] 2018-03-07 14:19
Other method:
https://github.com/nextcloud/android#with-a-computer

**Comment by LiamHD** [comment] 2018-03-08 09:54
`03-08 10:51:55.070 23428-23428/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.nextcloud.client, PID: 23428
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.authentication.ModifiedAuthenticatorActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2981)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3042)
                                                       at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1639)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6780)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
                                                       at com.owncloud.android.authentication.AuthenticatorActivity.onCreate(AuthenticatorActivity.java:289)
                                                       at com.owncloud.android.authentication.ModifiedAuthenticatorActivity.onCreate(ModifiedAuthenticatorActivity.java:31)
                                                       at android.app.Activity.performCreate(Activity.java:6948)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2924)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3042) 
                                                       at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1639) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6780) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386) `

**Comment by xXSTrikeXx** [comment] 2018-03-08 11:33
ping @AndyScherzinger @tobiasKaminsky

**Comment by AndyScherzinger** [comment] 2018-03-08 15:11
Would need to check the code but I guess there is some issue with the data being transferred to the activity (well, in this case not being transferred.

**Comment by LiamHD** [comment] 2018-03-28 10:29
Any progress on this?

**Comment by tobiasKaminsky** [comment] 2019-03-07 12:07
This is fixed and should work, if not please re-open.

**Closed by tobiasKaminsky** 2019-03-07 12:07 UTC
Labels: bug, medium
