### ISSUE TITLE
Need restarting when changing proxy

### ISSUE THREAD

**Issue by Sekhy2** [nextcloud/android#8625] opened 2021-06-24 21:01 UTC
### Steps to reproduce
1. Make sure the app is closed
2. Go to a place where your WiFi connection requires a proxy (and set the proxy properly), and start the app.
3. Connect to another WiFi that does not require a proxy (or use mobile data)
4. Try to get your files

### Expected behaviour
The application should automatically use the system proxy at any time (and no proxy when there is no proxy). And get your files.

### Actual behaviour
The app can't connect, 
It still tries to connect with the proxy that was used at startup (and is not needed anymore).
(the bug probably happens the other way around).
The only way to get rid of it is to force-stop the nextcloud app, and restart it.

### Environment data
OS version:  3.18.131-lineageos-g22175f5b2cee(a338f0f019)

Device model: Xiaomi Redmi 4X (lineage_santoni)

Nextcloud app version: 3.4.10

Nextcloud server version: 18

### Logs
App Version: 3.4.10
App Version Code: 3004010
App Flavor: fdroid

Files App Version Code: 30160190

---

OS Version: 3.18.131-lineageos-g22175f5b2cee(a338f0f019)
OS API Level: 27
Device: santoni
Manufacturer: Xiaomi
Model (and Product): Redmi 4X (lineage_santoni)

---

java.lang.Exception: com.nextcloud.android.sso.exceptions.UnknownErrorException: failed to connect to /10.0.0.1 (port 3128) from /:: (port 42726) after 60000ms: connect failed: ENETUNREACH (Network is unreachable)
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:174)
 at 
[...]

*Note : 10.0.0.1 (port 3128) is the said proxy. It was not supposed to use this proxy on this connection, and other apps were working normally.*

**Comment by joshtrichards** [comment] 2023-10-08 16:51
Duplicate of #7138

**Closed by joshtrichards** 2023-10-08 16:51 UTC
Labels: bug, approved
