### ISSUE TITLE
Crash when clicking on disable energy safe mode on poco handy

### ISSUE THREAD

**Issue by roadfox** [nextcloud/android#14201] opened 2024-12-18 16:03 UTC
### Cause of error
```java
Exception in thread "main" android.content.res.Resources$NotFoundException: Resource ID #0x7f0a0420 type #0x12 is not valid
    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2518)
    at android.content.res.Resources.getLayout(Resources.java:1281)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
    at androidx.appcompat.app.AlertController.setupCustomContent(AlertController.java:644)
    at androidx.appcompat.app.AlertController.setupView(AlertController.java:475)
    at androidx.appcompat.app.AlertController.installContent(AlertController.java:233)
    at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:278)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:453)
    at android.app.Dialog.show(Dialog.java:334)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.showPowerCheckDialog(SyncedFoldersActivity.kt:234)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onDisablePowerSaveCheckClicked(SyncedFoldersActivity.kt:218)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onCreateOptionsMenu$lambda$1(SyncedFoldersActivity.kt:211)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.$r8$lambda$q58-_n5tvnvo7t7SwBQVBpaIAdU(Unknown Source:0)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$$ExternalSyntheticLambda4.onMenuItemClick(D8$$SyntheticClass:0)
    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:984)
    at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
    at android.widget.AdapterView.performItemClick(AdapterView.java:330)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1220)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3213)
    at android.widget.AbsListView$3.run(AbsListView.java:4227)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:299)
    at android.app.ActivityThread.main(ActivityThread.java:8319)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300690`
* Build flavor: `gplay`

### Device information
* Brand: `POCO`
* Device: `surya`
* Model: `M2007J20CG`
* Id: `SKQ1.211019.001`
* Product: `surya_global`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `V14.0.2.0.SJGMIXM`

**Comment by joshtrichards** [comment] 2024-12-28 14:46
Duplicate of #13404

**Closed by joshtrichards** 2024-12-28 14:46 UTC
