### ISSUE TITLE
Error while deleting photos 

### ISSUE THREAD

**Issue by axheli** [nextcloud/android#6270] opened 2020-06-11 02:50 UTC
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 1133, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetString(Native Method)
	at android.database.CursorWindow.getString(CursorWindow.java:469)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
	at android.database.CursorWrapper.getString(CursorWrapper.java:141)
	at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:964)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:874)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:156)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:816)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1252)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1197)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1186)
	at com.owncloud.android.ui.activity.FileDisplayActivity.updateListOfFilesFragment(FileDisplayActivity.java:701)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoveFileOperationFinish(FileDisplayActivity.java:1824)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1744)
	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:738)
	at com.owncloud.android.services.-$$Lambda$OperationsService$2BVgsxDpOpa4JqgzeD7OGZBLSiI.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7Pro
Model: GM1910
Id: QKQ1.190716.003
Product: OnePlus7Pro

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2005132200

**Comment by heinhuiz** [comment] 2020-06-12 17:18
I'm not sure if this is what I am experiencing with the same build, where auto upload with the option to delete the original file leaves an empty 0B file with the same filename behind?

**Comment by tobiasKaminsky** [comment] 2020-06-15 10:48
Duplicate of #5891

**Closed by tobiasKaminsky** 2020-06-15 10:48 UTC
Labels: bug
