### ISSUE TITLE
crash when clicking on the share link symbol

### ISSUE THREAD

**Issue by pagdot** [nextcloud/android#13779] opened 2024-10-13 09:09 UTC
Can reproduce by Clicking on the share/link symbol in the file browser fir links created before

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
    at com.owncloud.android.datamodel.OCFile.isInternalFolderSync(OCFile.java:1058)
    at com.owncloud.android.datamodel.FileDataStorageManager.isPartOfInternalTwoWaySync(FileDataStorageManager.java:2504)
    at com.owncloud.android.ui.fragment.FileDetailFragment.updateFileDetails(FileDetailFragment.java:572)
    at com.owncloud.android.ui.fragment.FileDetailFragment.onViewCreated(FileDetailFragment.java:266)
    at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3152)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:608)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2059)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:702)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7924)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300090`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `crownlte`
* Model: `SM-N960F`
* Id: `TQ3A.230901.001`
* Product: `lineage_crownlte`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `36fd58b0dd`

**Comment by nautik1** [comment] 2024-10-13 11:42
Same here with up-to-date app and server (stable)... 

It also crashes when trying to display the "properties" menu, so I cannot share anything through the app now... Makes the app unusable :/

**Comment by pagdot** [comment] 2024-10-13 14:34
It works for me when sharing using the sharing menu, just the button for an already created link is broken for me. Right now my server is on 29.0.7. I host my own server, so I can provide more info about the server if required

**Comment by pagdot** [comment] 2024-10-13 14:36
May be a duplicate/related to https://github.com/nextcloud/android/issues/13502

**Comment by joshtrichards** [comment] 2024-10-14 17:43
Duplicate of #13502

**Closed by joshtrichards** 2024-10-14 17:43 UTC
