### ISSUE TITLE
bug at the new maj 30160090 of nextcloud

### ISSUE THREAD

**Issue by rateur42** [nextcloud/android#8464] opened 2021-05-24 18:57 UTC
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Credentials.kt)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Credentials.kt)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:761)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Amlogic
Device: p281
Model: HK1
Id: NHG47L
Product: p281

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: 20180825

```

**Comment by AndyScherzinger** [comment] 2021-05-25 10:33
Duplicate of #8370

**Closed by AndyScherzinger** 2021-05-25 10:33 UTC
Labels: bug
