### ISSUE TITLE
Crash when opening pdf

### ISSUE THREAD

**Issue by mikelauskas** [nextcloud/android#7255] opened 2020-11-07 18:14 UTC
### Steps to reproduce
1. On Android app, open a pdf
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.swiperefreshlayout.widget.SwipeRefreshLayout.setVisibility(int)' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.populateList(FileDetailActivitiesFragment.java:415)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$null$3$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:370)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$ZzLUj33qKg0e1Ki8Vd5bki8I6B4.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7560)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: cepheus
Model: MI 9
Id: QKQ1.190825.002
Product: cepheus_eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.2.0.QFAEUXM

**Comment by AndyScherzinger** [comment] 2020-11-08 16:00
Duplicate of #7188

**Closed by AndyScherzinger** 2020-11-08 16:00 UTC
Labels: bug
