### ISSUE TITLE
Access failed: Operation finished with HTTP status code -1 (fail) on Android App V3.16.0

### ISSUE THREAD

**Issue by ex3me4me** [nextcloud/android#8387] opened 2021-05-12 05:31 UTC
### Steps to reproduce
1.  Install Android App 3.16.0
2.  try to log in in the instance 

### Expected behaviour
- expect to log in in my instance 

### Actual behaviour
- actual behavior error Access failed: Operation finished with HTTP status code -1 (fail)

### Can you reproduce this problem on https://try.nextcloud.com?
No, it's related only to Android App V 3.16.0

### Environment data
Android version: 
11

Device model:  
Samsung S20

Stock or customized system: 
Stock

Nextcloud app version:
3.16.0

Nextcloud server version:
21.0.1

Reverse proxy:
Ngnx

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
``` No logs related to this matter

Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2021-05-12 08:40
@ex3me4me could this by any chance be related (or a duplicate of):  #8355

**Comment by ex3me4me** [comment] 2021-05-12 13:23
@AndyScherzinger yes, it is a copy of #8355. After reading through #8355, i recreated the error and then lower the Minimum TLS Version to 1.2 in SSL/TLS > Edge Certificates at CloudFlare and now app v 3.16.0 is working. Thank You.

**Comment by AndyScherzinger** [comment] 2021-05-13 08:33
Happy to hear that, also we will ship a fix with the next feature release.

**Closed by AndyScherzinger** 2021-05-13 08:33 UTC
Labels: bug
