### ISSUE TITLE
Crash after syncing

### ISSUE THREAD

**Issue by not-implemented** [nextcloud/android#5070] opened 2019-12-28 07:48 UTC
### Steps to reproduce
1. Syncing a bigger folder
2. Leaving the Nextcloud App (not really reproducable)

### Expected behaviour
- No crash

### Actual behaviour
Crash:
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1881)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: herolte
Model: SM-G930F
Id: R16NW
Product: heroltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G930FXXS7ESK7

**Comment by AndyScherzinger** [comment] 2020-01-09 17:29
duplicate of #2010

**Closed by AndyScherzinger** 2020-01-09 17:29 UTC
Labels: bug
