### ISSUE TITLE
Sharing photos to Nextcloud Android 3.14.1 no longer works, 3.14.0 works as expected.

### ISSUE THREAD

**Issue by bitmagewb** [nextcloud/android#7665] opened 2020-12-14 19:18 UTC
### Steps to reproduce
1.  Update Nextcloud Android app to 3.14.1
2. Go to Google Photos App, select picture, share to Nextcloud app 
3. Nextcloud app displays 'Choose upload folder', click on Upload.
4. You are returned to Photos app, no upload occurs.
If I restore a backup of the 3.14.0 client, everything works as expected again.

### Expected behaviour
- Photo should be uploaded to Nextcloud server.

### Actual behaviour
- Upload does not occur.

### Environment data
Android version:  Android 11, Dec 5 2020 security update, Oct 1 Play System update.

Device model: Pixel 3XL

Stock or customized system: Stock, rooted.

Nextcloud app version: 3.14.1

Nextcloud server version: 19.0.6

Reverse proxy: no

#### Web server error log
Insert your Nextcloud log here
No activity is seen in apache or nextcloud logs during the upload attempt.

**Comment by AndyScherzinger** [comment] 2020-12-14 21:17
Duplicate of #7587

**Closed by AndyScherzinger** 2020-12-14 21:17 UTC
Labels: bug
