### ISSUE TITLE
Some error when I change language from Ukraine to Russian

### ISSUE THREAD

**Issue by White0wl** [nextcloud/android#8540] opened 2021-06-07 09:49 UTC
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: daisy
Model: Mi A2 Lite
Id: RQ2A.210505.003
Product: lineage_daisy

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: eng.hukad.20210524.175325

**Comment by AndyScherzinger** [comment] 2021-06-07 14:01
Duplicate of #8370

**Closed by AndyScherzinger** 2021-06-07 14:01 UTC
Labels: bug
