### ISSUE TITLE
Java OOM crash when opening a specific folder

### ISSUE THREAD

**Issue by b02860de585071a2** [nextcloud/android#11960] opened 2023-09-12 07:55 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open Nextcloud app
2. Attempt to open a very large (~200GB) folder
3. Crash

### Expected behaviour

I should be able to open the folder without crashing. 

### Actual behaviour

Attempting to open one specific folder causes a crash 100% of the time. This is my photos folder, with ~200 gigs of mixed photo and video. 

It takes a while to load in the web client, but will always open eventually. 

### Android version

13

### Device brand and model

Samsung S22 Ultra (SM-S908U1)

### Stock or custom OS?

Stock

### Nextcloud android app version

3.25.0

### Nextcloud server version

27.0.2

### Using a reverse proxy?

No

### Android logs

```java
FATAL EXCEPTION: Thread-15
Process: com.nextcloud.client, PID: 4390
java.lang.OutOfMemoryError: Failed to allocate a 76576 byte allocation with 2256920 free bytes and 2204KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at org.apache.jackrabbit.webdav.MultiStatus.getResponses(MultiStatus.java:128)
	at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.readData(ReadFolderRemoteOperation.java:151)
	at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:88)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:205)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:405)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:239)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
	at java.lang.Thread.run(Thread.java:1012)
```

### Server error logs

```bash
None
```

### Additional information

I saw quite a few similar reports linked in #11076, but none that were triggered by simply opening a folder. 

**Things I have already done:**  
- Verify integrity of files
- Confirm working on web client
- `occ files:scan --all` and `occ fulltextsearch:index` (to rule out the possibility of it being a filesysten issue)

**Comment by joshtrichards** [comment] 2024-07-09 19:47
Duplicate of #11912

**Closed by joshtrichards** 2024-07-09 19:47 UTC
Labels: bug, performance: OOM :brain:, Version/3025
