### ISSUE TITLE
Crash scrolling media view

### ISSUE THREAD

**Issue by ne20002** [nextcloud/android#10192] opened 2022-05-06 16:47 UTC
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Couldn't read row 912, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetString(Native Method)
    at android.database.CursorWindow.getString(CursorWindow.java:469)
    at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
    at android.database.CursorWrapper.getString(CursorWrapper.java:141)
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:957)
    at com.owncloud.android.datamodel.FileDataStorageManager.getGalleryItems(FileDataStorageManager.java:2220)
    at com.owncloud.android.datamodel.FileDataStorageManager.getAllGalleryItems(FileDataStorageManager.java:2165)
    at com.owncloud.android.ui.adapter.GalleryAdapter.showAllGalleryItems(GalleryAdapter.kt:149)
    at com.owncloud.android.ui.fragment.GalleryFragment.handleSearchEvent(GalleryFragment.java:156)
    at com.owncloud.android.ui.fragment.GalleryFragment.onRefresh(GalleryFragment.java:126)
    at androidx.swiperefreshlayout.widget.SwipeRefreshLayout$1.onAnimationEnd(SwipeRefreshLayout.java:195)
    at androidx.swiperefreshlayout.widget.CircleImageView.onAnimationEnd(CircleImageView.java:107)
    at android.view.ViewGroup.finishAnimatingView(ViewGroup.java:7057)
    at android.view.View.draw(View.java:21469)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4448)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4209)
    at android.view.View.draw(View.java:21573)
    at android.view.View.updateDisplayListIfDirty(View.java:20405)
    at android.view.View.draw(View.java:21284)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4448)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4209)
    at android.view.View.updateDisplayListIfDirty(View.java:20396)
    at android.view.View.draw(View.java:21284)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4448)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4209)
    at android.view.View.updateDisplayListIfDirty(View.java:20396)
    at android.view.View.draw(View.java:21284)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4448)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4209)
    at android.view.View.draw(View.java:21573)
    at android.view.View.updateDisplayListIfDirty(View.java:20405)
    at android.view.View.draw(View.java:21284)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4448)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4209)
    at android.view.View.updateDisplayListIfDirty(View.java:20396)
    at android.view.View.draw(View.java:21284)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4448)
    at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4209)
    at android.view.View.draw(View.java:21573)
    at android.view.View.updateDisplayListIfDirty(View.java:20405)
    at android.view.View.draw(View.java:21284)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4448)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4209)
    at android.view.View.updateDisplayListIfDirty(View.java:20396)
    at android.view.View.draw(View.java:21284)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4448)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4209)
    at android.view.View.updateDisplayListIfDirty(View.java:20396)
    at android.view.View.draw(View.java:21284)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4448)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4209)
    at android.view.View.updateDisplayListIfDirty(View.java:20396)
    at android.view.View.draw(View.java:21284)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4448)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4209)
    at android.view.View.updateDisplayListIfDirty(View.java:20396)
    at android.view.View.draw(View.java:21284)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4448)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4209)
    at android.view.View.draw(View.java:21573)
    at com.android.internal.policy.DecorView.draw(DecorView.java:808)
    at android.view.View.updateDisplayListIfDirty(View.java:20405)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:3754)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3558)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2878)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1788)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7867)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
    at android.view.Choreographer.doCallbacks(Choreographer.java:791)
    at android.view.Choreographer.doFrame(Choreographer.java:726)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7399)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `Lenovo`
* Device: `X606F`
* Model: `Lenovo TB-X606F`
* Id: `QP1A.190711.020`
* Product: `LenovoTB-X606F_EEA`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `TB-X606F_USR_S300554_2203030006_V9.56_BMP_ROW`

**Comment by AlvaroBrey** [comment] 2022-05-09 07:29
Duplicate of #9948

**Closed by AlvaroBrey** 2022-05-09 07:29 UTC
Labels: bug
