### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Jack-genius** [nextcloud/android#4879] opened 2019-11-23 02:57 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { (has extras) }} to activity {com.nextcloud.client/com.owncloud.android.ui.activity.SyncedFoldersActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4046)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4089)
	at android.app.ActivityThread.access$1400(ActivityThread.java:186)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1632)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:200)
	at android.app.ActivityThread.main(ActivityThread.java:5877)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:987)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.ui.activity.SyncedFoldersActivity.onActivityResult(SyncedFoldersActivity.java:590)
	at android.app.Activity.dispatchActivityResult(Activity.java:6282)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4042)
	... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Meizu
Device: m1metal
Model: m1 metal
Id: LMY47I
Product: m1metal

************ FIRMWARE ************
SDK: 22
Release: 5.1
Incremental: 1520236126

**Comment by AndyScherzinger** [comment] 2019-12-02 07:52
might by a duplicate of #4792  so closing in favor.

Thanks for reporting.

**Closed by AndyScherzinger** 2019-12-02 07:52 UTC
Labels: bug
