### ISSUE TITLE
Unwanted download (2-way sync) drains battery and occupies drive on Android phone

### ISSUE THREAD

**Issue by Chatter35** [nextcloud/android#13772] opened 2024-10-11 18:22 UTC
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Stable version 3.30.1
Unwanted download (2-way sync) drains battery and occupies drive on Android phone. I have discovered this as my phone got hot while downloading files from my managed Nexcloud server. No way to toggle 2-way sync off in the APK. I have now deinstalled the app (and I am absolutely not amused).

### Expected behaviour

I can control 2-way sync myself.

### Actual behaviour

Stable version 3.30.1
Unwanted download (2-way sync) drains battery and occupies drive on Android phone. I have discovered this as my phone got hot while downloading files from my managed Nexcloud server. No way to toggle 2-way sync off in the APK. I have now deinstalled the app (and I am absolutely not amused).

### Android version

14

### Device brand and model

Google Pixel 8 Pro

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

Stable version 3.30.1

### Nextcloud server version

28.0.10

### Using a reverse proxy?

I don't know

### Additional information

GrapheneOS

**Comment by phoropter** [comment] 2024-10-12 00:01
Same issue. The android app decided to start syncing *everything* from my server. Didn't notice until I got a notification that the space on my phone was running out. The the Internal two way sync menu in settings gives absolutely no way to manage despite saying that's what it's for. It only shows what files are currently being synced.

**Comment by alxrdn** [comment] 2024-10-12 06:49
Same here.
Somehow the app started sending sync or auto-upload notifications infinitely.
I also noticed it because the smartphone became so hot !
I rebooted the phone, it started back again.
I had to uninstall this release and I reinstalled the previous 3.30.0
Complete fuss generated, lots of empty files created on the phone, I had to manually clean all the mess.
No fun

**Comment by kaibagley** [comment] 2024-10-13 07:40
I also had the same thing happen. Updated Nextcloud, GrapheneOS update today and NC started syncing stuff rapidly automatically. I don't want to keep any of my NC data on my phone, and the only way to prevent it was to uninstall NC. Where does the NC app download the files to? I can't find them on my phone, which may mean that they were removed when I uninstalled, but I'm not sure.

**Comment by spiritualcrab** [comment] 2024-10-14 00:24
I maybe wrong, but all of this reported error is on GrapheneOS. Not sure if regular Android also has the same issue?

I too have the same issues. 

Server Nextcloud: 29.0.7
Device: Google Pixel 6a
GrapheneOS

**Comment by alxrdn** [comment] 2024-10-14 05:17
> I maybe wrong, but all of this reported error is on GrapheneOS. Not sure if regular Android also has the same issue?
> 
> I too have the same issues. 
> 
> Server Nextcloud: 29.0.7
> Device: Google Pixel 6a
> GrapheneOS
> 
> 

Hello
Yes you are wrong: I'm running vanilla Google Android 15.

**Comment by RITFW** [comment] 2024-10-14 14:44
I can confirm the behaviour after updating to the latest version. Randomly, the app started syncing everything to the device after I used the app for the first time after the update. 

**What I already tried:**

- To cancel the sync in the UI (Folder -> details -> uncheck sync) seems to have no affect.
- When I try to change the settings in settings -> Internal two way sync I can only see a folder list, but can't change anything.
- After the sync was complete, i've deleted all local files, but it did a full sync again.
- **Workaround that worked:** Cleaning the cache and storage of the app and setting everything back up again seems to solve the problem. Like @Chatter35 reported Settings - Internal 2-Way-Sync: No internal folders can be selected.

**App**

- F-Droid build
- com.nextcloud.client, versionCode 30300151

**Device**

- Pixel 6a with GrapheneOS 2024101200, (Google Play services, Google Play Store *not* installed)

**Server**
* Nextcloud Hub 6 (27.1.11)

Beside Nextcloud I have Nextcloud Notes installed

- F-Droid build
- it.niedermann.owncloud.notes, versionCode 40030190

The behaviour is kind of annoying as it empties the battery and fills the device storage.

Please note: I basically have to experience when it comes to bug reports. In case I can provide you with more information or do anything else, please let me know. Thanks a lot for all your hard work and great infrastructure.

**Comment by RITFW** [comment] 2024-10-15 07:22
> I also had the same thing happen. Updated Nextcloud, GrapheneOS update today and NC started syncing stuff rapidly automatically. I don't want to keep any of my NC data on my phone, and the only way to prevent it was to uninstall NC. Where does the NC app download the files to? I can't find them on my phone, which may mean that they were removed when I uninstalled, but I'm not sure.

I found the synced data at /storage/emulated/0/Android/media/com.nextcloud.client

**Comment by joshtrichards** [comment] 2024-10-15 13:25
Duplicate of #13738

**Closed by joshtrichards** 2024-10-15 13:25 UTC
Labels: bug, 0. Needs triage, stable-3.30, feature: sync
