### ISSUE TITLE
Download also subfolders

### ISSUE THREAD

**Issue by Spartachetto** [nextcloud/android#3379] opened 2018-12-17 08:33 UTC
My scenario: I often create a folder with all the files related to _x_ via webclient and then download them via android client to have them "on the go".

I just happened to create one folder like that, but this time I had some subfolders.  There is no way to download everything (included the content of subfolders) together. If I am in the first folder and I select everything I do not have the option "Download" if I have some folders in the selection. If I select the folder (being one level up) I do not have the option "Download all the content". 

Is there any reason not to have the possibility that select all includes the possibility to download also the content of folders. It could be really practical.

Thanks in advance

**Comment by AndyScherzinger** [comment] 2018-12-17 08:48
Hi @Spartachetto, 
tahnks for the report. To answer your question, there is  no particular reason for this not being present in the Android client. It is just that nobody had the time or took the time to implement this.

**Comment by tobiasKaminsky** [comment] 2019-01-22 13:55
I agree with it, but we should have either two menu items 
- download folder
- download folder with subfolders

or 
- some "fancy" menu entry with checkbutton for subfolders
or
- a dialog after download which is shown if there are subfolders, maybe then also with total size, like: 
"do you want to download only the files in this folder (123Mb) or download folder with alls subfolders (500Mb)?"
- only folder
- with subfolder

I would prefer the later one, as it does not change the UI.

**Comment by AndyScherzinger** [comment] 2019-01-22 15:08
I'd be fine with the dialog approach, while I'd appreciate some input from @nextcloud/designers on how to handle this situation. To some extend I would suspect any kind of app in case I hit download on a folder that it'll always downloads the whole thing, same would apply for the fact that for multi-select download is hidden, when you mark folders...

**Comment by jancborchardt** [comment] 2019-01-23 11:52
> To some extend I would suspect any kind of app in case I hit download on a folder that it'll always downloads the whole thing

Absolutely agree. To keep stuff simple, there is no need for a choice. If you download a folder through the web app or anywhere else, it also always includes all subfolders.

> same would apply for the fact that for multi-select download is hidden, when you mark folders...

Yep. Download should simply also be available in multiselect when folders are part of the selection.

**Comment by tobiasKaminsky** [comment] 2019-01-30 10:40
Web UI is a bit different case, as there you normally have enough data space and no limited traffic.
Having a dialog if there are subfolders is not that bad, I think.
Or how would an user then can download a complete folder without subfolder? (go into folder, select all, manually deselect all subfolders, click on download)

**Comment by joshtrichards** [comment] 2024-10-19 01:12
Duplicate of #269

**Closed by joshtrichards** 2024-10-19 01:12 UTC
Labels: enhancement, feature: sync
