### ISSUE TITLE
Photo folder selection crashes

### ISSUE THREAD

**Issue by rkolja76** [nextcloud/android#13929] opened 2024-11-01 17:23 UTC
### Cause of error
```java
Exception in thread "Thread-15" java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 1113776 free bytes and 1087KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
    at java.util.HashMap.newNode(HashMap.java:1907)
    at java.util.HashMap.putVal(HashMap.java:636)
    at java.util.HashMap.put(HashMap.java:617)
    at org.apache.jackrabbit.webdav.property.DavPropertySet.add(DavPropertySet.java:51)
    at org.apache.jackrabbit.webdav.property.DavPropertySet.addContent(DavPropertySet.java:189)
    at org.apache.jackrabbit.webdav.MultiStatusResponse.add(MultiStatusResponse.java:336)
    at org.apache.jackrabbit.webdav.MultiStatusResponse.createFromXml(MultiStatusResponse.java:464)
    at org.apache.jackrabbit.webdav.MultiStatus.createFromXml(MultiStatus.java:185)
    at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.processResponseBody(DavMethodBase.java:282)
    at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1749)
    at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
    at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
    at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
    at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:192)
    at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:62)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:413)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:247)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:387)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300490`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `e3q`
* Model: `SM-S928B`
* Id: `UP1A.231005.007`
* Product: `e3qxeea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S928BXXS3AXI8`

**Comment by joshtrichards** [comment] 2024-11-02 13:12
Duplicate of #9903

**Closed by joshtrichards** 2024-11-02 13:12 UTC
