### ISSUE TITLE
Client-Side Authentication does not work

### ISSUE THREAD

**Issue by rstemmer** [nextcloud/android#6472] opened 2020-07-14 05:11 UTC
I try to access my Nextcloud via Andorid but having an Issue with the setup process of the App.

My server uses Client-Side Authentication with self-signed certificates.
The desktop apps for Windows, MacOS and Linux are working without any issues, asking me for the certificate when setting up the connection for the first time.
The Android app seems to have an issue with this security strategy.

The certificate for authentication is installed in the Android system (User Certificates).
When I use the Chrome-Webbrowser to access the Nextcloud web UI, android asks me to permit to use this certificate. Accepting it, I can successfully login into Nextcloud web UI.

### Steps to reproduce
1. Start fresh installed app (Setup-Assistant)
2. Enter URL to server that that uses SSL with Client-side authentication with self-signed certificates

### Expected behaviour
- Asks if I trust the URL
- Should ask for the certificate file or find the certificated installed in the Android system

### Actual behaviour
- Asks if I trust the URL
- Error message: SSL-Initialization failed

### Environment data
Android version: 10

Device model: Samsung Galaxy Note10+

Stock or customized system: Stock Samsung Android OS (One UI 2.1, Linux 4.14.113, Knox 3.4.1)

Nextcloud app version: 3.12.1

Nextcloud server version: 19.0.0

Apache: 2.4.43-1

**Comment by AndyScherzinger** [comment] 2020-07-14 15:31
The Nextcloud Android client doesn't support client side authentication via certificates atm.

Cc @tobiasKaminsky

**Comment by mkofahl** [comment] 2020-09-02 19:26
Duplicate of #603

**Closed** 2020-09-03 05:40 UTC
Labels: enhancement
