### ISSUE TITLE
Excessive data usage / All files downloaded

### ISSUE THREAD

**Issue by bessman** [nextcloud/android#13747] opened 2024-10-09 10:50 UTC
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I don't know what caused the issue. It started soon after installing version 20241005.

### Expected behaviour

Nextcloud shouldn't download gigabytes upon gigabytes of mystery data, especially not on a mobile connection.

### Actual behaviour

This morning Nextcloud downloaded just over 15 GB of data to my phone:

![Image](https://github.com/user-attachments/assets/7baf7e70-a012-4fe1-b154-fa1774f0c12e)

The server contains just over 1 GB of data, total:

![Image](https://github.com/user-attachments/assets/b0c31a40-a57b-403a-9eab-eb2d28520381)

This used up my entire data quota for the month of October. It would probably have kept downloading even more data had my ISP not cut me off.

### Android version

14

### Device brand and model

Samsung Galaxy S22

### Stock or custom OS?

Stock

### Nextcloud android app version

20241005

### Nextcloud server version

25.0.13.2

### Using a reverse proxy?

I don't know

### Android logs

I immediately uninstalled Nextcloud when I noticed the problem, so I have no logs to share.

**Comment by joshtrichards** [comment] 2024-10-09 17:40
Did you have any syncing or auto-uploads set up?

**Comment by bessman** [comment] 2024-10-09 17:54
I had auto-upload enabled for one folder, containing a few photos totaling maybe 50 MB.

I'm not sure what you mean by syncing. Nextcloud unconditionally syncs whatever files are on the server, no? I hadn't configured any special syncing beyond the defaults.

**Comment by bermeitinger-b** [comment] 2024-10-10 07:27
I have the same experience. It tries to download/sync the whole Nextcloud. All folders.

**Comment by vandman** [comment] 2024-10-10 10:52
I have got the same issue.
It used almost all my data. It look like it tries to download files from the server. I think the problem is linked to the internal 2 way sync new feature. When you go inside you have a bunch of file and nothing else. It is not possible to deactivate it or set it up???
Look at the screen capture.
![Image](https://github.com/user-attachments/assets/af1e9574-c5bd-45df-a103-9802a5380366)
![Image](https://github.com/user-attachments/assets/5a1054ee-bf83-4446-b916-d03a6506702f)

**Comment by bermeitinger-b** [comment] 2024-10-10 10:54
Yes, definitely. I have a similar list with all folders, including my whole photos archive with 200GB. I don't think that's the intention here, right?

**Comment by vandman** [comment] 2024-10-10 11:10
It looks like folder, but it is actually files?

**Comment by AdamLeyshon** [comment] 2024-10-10 11:51
Yes, every single file in our NextCloud accounts are in these lists, it's killing all our phone batteries and data usage, how to disable two-way sync? I can't click on any of those items to remove them.

**Comment by d00r5** [comment] 2024-10-10 12:48
I think there's no way atm but if you don't want to uninstall and you have the option (grapheneOS for instance) you can remove the "network" permission for this app and only enable it when you want a sync.

**Comment by noconnor29** [comment] 2024-10-11 16:56
Mine (v3.30.1) seems to be endlessly downloading the contents of the same Signal backup folder. On wifi so the data isn't costly but it's eating my battery alive. I'm on Graphene so I'm going to remove network permission temporarily.

**Comment by phoropter** [comment] 2024-10-12 00:15
Same issue on 3.30.1. Didn't notice until I got a notification that the space on my phone was running out. The the Internal two way sync menu in settings gives absolutely no way to manage despite saying that's what it's for. It only shows what files are currently being synced.

Blew through my mobile data too, so thanks for that.

**Comment by Valdnet** [comment] 2024-10-13 10:36
Potwierdzam. Ten sam problem na wersji 3.30.1.

@tobiasKaminsky Can you check it?

**Comment by Valdnet** [comment] 2024-10-13 14:27
> unsure whether 3.30.0 is affected

Version 3.30.0 works fine.

**Comment by acress1** [comment] 2024-10-14 10:33
Hi,
Same problem in 3.30.1 ! :/

**Comment by joshtrichards** [comment] 2024-10-15 13:25
Duplicate of #13738

**Closed by joshtrichards** 2024-10-15 13:25 UTC
Labels: bug, 0. Needs triage, feature: transfers, stable-3.30, feature: sync
