### ISSUE TITLE
Add Scanning Support

### ISSUE THREAD

**Issue by c0fe** [nextcloud/android#2436] opened 2018-04-06 18:12 UTC
I would like to propose adding support for the Nextcloud app to be able to take a picture of whatever item, let's say a receipt and "scan" it into a select folder the user chooses in PDF format.

So user does the following

1. Opens Nextcloud App
2. Goes to the folder that they wish to upload the scan to
3. Press the "+" button
4. Select "scan" option
5. Take picture
6. Ok the preview
7. File is converted to PDF and uploaded

I was thinking maybe taking a look at this application and forking it?

https://github.com/ctodobom/OpenNoteScanner

**Comment by mario** [comment] 2018-04-06 18:14
Not a big fan of the request to be honest :-/ This would just clutter the app.

**Comment by c0fe** [comment] 2018-04-06 19:26
@mario it is a feature at least from personal experience i know would be used.

**Comment by emresaracoglu** [comment] 2018-04-11 09:43
I believe that such features will enrich the application. I currently use [Microsoft Office Lens](https://itunes.apple.com/tr/app/office-lens/id975925059?mt=8) application for this on iOS

**Comment by AndyScherzinger** [comment] 2018-04-11 10:51
While it would enrich the app like any feature in some way will always enrich an app it also takes away the focus of an app in this it being a files app not a documents/scanner app. Besides it is also not the typical use case for mobile app, else you could argue all office apps should be just a single app.

I myself use scan bot since I want to have a document management / scanning app + using a private cloud, thus I simply use the app with its WebDAV connector. Other than that the philosophy behind the Android app  or the whole Nextcloud ecosystem is to not reinvent/copy existing feature sets but to integrate which e.g. for scanbot is given, same goes for DAVdroid.

Pinging @tobiasKaminsky @jospoortvliet for their feedback while I'd guess they have the same opinion.

**Comment by c0fe** [comment] 2018-04-11 12:07
@AndyScherzinger here is my take on this:

Nextcloud is a files/documents management application. The scanner portion is an extension that allows you to start to manage physical documents as well which comes in just as important. If Nextcloud is to manage files it should have the capability of managing all files.

The second argument is that Dropbox has this feature and it is one that is fairly useful. Dropbox is a competitor to Nextcloud.

**Comment by AndyScherzinger** [comment] 2018-04-11 12:40
> Though I understand if my opinion on any of this stuff is rather worthless.

Not at all, your opinion matters as much as anyone else's! So if let's say "enough people" and devs agree on this feature it'll likely make it to a roadmap.

**Comment by mario** [comment] 2018-04-11 12:43
I also agree this is not needed at this point. There are so many things we can do to improve the app in the files portion and that's where efforts are.

If somebody REALLY comes forward and implements this (ideally via a plugin mechanism that needs to be developed) then we can discuss this.

Bloating the app when we don't have enough man-power even for things we NEED to do is not something I'd encourage.

**Comment by beankylla** [comment] 2018-06-06 21:42
This is the kind of feature that brings users to a platform. Making things quick easy and cool. Effortless. As a user these are some of the things I like. Now I totally get the manpower / priorities issues. But if things loosen up a bit there is no doubt that this will be a huge plus. The thing is the users that would really use this are really likely to be the users NOT commenting here. As we know they like it simple and easy..

**Comment by tobiasKaminsky** [comment] 2018-06-07 06:12
I installed the app and tested our current workflow with it and for me it is really quick and easy:

- open up open note
- take image
- share image to nextcloud
- select folder or create a new folder
- upload

![2018-06-07-080958](https://user-images.githubusercontent.com/5836855/41081234-5c56fc40-6a2a-11e8-8bcb-681f80a66ce2.png) ![2018-06-07-080949](https://user-images.githubusercontent.com/5836855/41081237-5c7646fe-6a2a-11e8-9de0-b75f85982dad.png)

I am not sure if the other workflow (starting nc app, select folder, press "+" for scanning) is this faster.

@c0fe @beankylla is/was the first workflow know to you? If not, then we need to enhance the UX in this area…

**Comment by c0fe** [comment] 2018-06-07 12:11
@tobiasKaminsky I am not sure what you mean here, but if you are asking as to whether or not I was aware of other scanning applications that can share to Nextcloud, I was aware but that was more cumbersome for me which is why I made the suggestion that I did.

**Comment by cwmke** [comment] 2018-11-28 05:30
I would like to mention that Nextcloud iOS already has this implemented and it works great. I have an Android phone but go use my wife's iPad when I want to scan a document or receipt. 

I think feature parity between OS's would be a plus.

**Comment by AndyScherzinger** [comment] 2018-11-28 07:30
Feature parity would be nice, sure. While I think iOS can simply provide this based on iOS features so the app doesn't have to implement much. A requested feature is to have a direct camera upload which is something I started working on a while ago, see https://github.com/nextcloud/android/tree/cameraDirectUpload branch which would still "just" be a taking photos implementation, no scanning no pdf conversion (since that is something Android doesn't provide out-of-the-box). So this might help but isn't the exact same thing. Proper "scan" support needs a huge effort to be implemented and might be something we won't implement since there are already applications that cover suche use cases very nicely so we would (same applies to some other feature requests) duplicate features of other apps that actually support working with a Nc server.

**Comment by cwmke** [comment] 2018-11-28 14:38
Thanks for the explanation @AndyScherzinger. I didn't realize that was built into iOS.

**Comment by lwerner-lshigh** [comment] 2021-03-31 07:10
I was wondering what the status of this feature is as I do not really want to carry a second device for scanning documents. I do see that there are 2 prs but then dont seem to have been merged yet...

**Comment by gerroon** [comment] 2022-03-21 04:36
This seems to be in Android-Dev version. Thanks for implemeting it, I always was jealous of the IOS app due to the missing scanning on Android.

**Comment by AlvaroBrey** [comment] 2022-03-21 09:02
This was implemented in #9717

**Closed by AlvaroBrey** 2022-03-21 09:02 UTC
Labels: enhancement

**Comment by lbdroid** [comment] 2022-05-07 14:30
Is this feature not added to the F-Droid build? I can't find it OR built in PDF viewer, despite having v. 3.20.0 installed.

**Comment by AndyScherzinger** [comment] 2022-05-07 17:28
No, since it relies on a library which has a part that ships as a binary which is forbidden by f-droid, so they leave you with the choice of removing it or building the libraries binary packages yourself during your own apps build time which we do not have the capacity to do thus f-droid users very unfortunately have to live with the features missing, which is also true for push notifications.

However if anybody is willing to contribute such a build pipeline to the project we are happy to add this to the code base to be able to ship this feature on f-droid also.

**Comment by S1SYPHOS** [comment] 2022-09-05 16:38
Could you outline the build steps needed to implement these features for F-Droid builds? I guess this would make it clearer for future contributors to pick up the topic! Furthermore, I couldn't find the binary in question, any pointers are welcome :+1:

**Comment by AndyScherzinger** [comment] 2022-09-05 22:03
I can't else we would probably have implemented it (given the available time of course). From my understanding the issue is that the scanner library in use

https://github.com/nextcloud/android/blob/5ceffab31b4752adc87fe5ed4be71ee9103d80d4/app/build.gradle#L256

has an arbitrary dependency to a binary which contains some of the scanning logic, so in order to have f-droid approve the feature you would have to find the original code of the binary compile it yourself within the build of this app. No idea how this should even work since it it part of a dependency or even a dependency or a dependency.
