### ISSUE TITLE
Edit on the fly possible (*.xlsx, *.docx, *.txt ...)?

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/android#751] opened 2017-03-16 11:19 UTC
Hello,

I've encountered following ...

Opening an excel-file from nc-android-app, editing and saving to cloud works directly on Android 6.0.1

The same procedure with Android 7.0 doesn't work anymore, 'cause the document is opened as "write-protected". Are privileges changed in 7.0??

Cheers,

Tom

Tested with Android App 1.4.2 on Android 6.0.1 & Android 7.0

**Comment by AndyScherzinger** [comment] 2017-03-16 12:53
Hi Tom,

at least we didn't change anything here or implemented any Android version specific things, so my guess would then be an Android introduces permission change where we would have to look into then.

**Comment by AndyScherzinger** [comment] 2017-03-16 12:59
Hi Tom,

actually just tested it with a Word document and it works like a charm, did you since it a a different device then also set the excel file as available offline in the Nextcloud app? I did so and my local changes I can do are synced back and forth even though I didn't have an Excel file at hand so I used a Word file.

**Comment by kangaroo72** [comment] 2017-03-16 13:19
Just opened a word-file ... made available offline before ... but it's write protected in word (Samsung S7 - Android 7). Any other setting??

**Comment by kangaroo72** [comment] 2017-03-16 13:28
Checked on Note 5 (Android 6.0) - works ...

**Comment by kangaroo72** [comment] 2017-03-16 13:51
@AndyScherzinger are you using Word or an other app? I think the problem is "Word" ...

**Comment by AndyScherzinger** [comment] 2017-03-16 18:23
@kangaroo72 yes, I use the Google Docs app to open/edit the Word document.

**Comment by johnripper1** [comment] 2017-04-02 09:18
I can confirm this on a Galaxy S7 with Android 7.0 latest pache level and latest Nextcloud client.

The MS Office Mobile Apps (Word, Excel, Powerpoint) only open there files in read only mode. With Google Docs, Tabels etc it works "on the fly".

I noted this since change to Android 7, but was sure if this is related to Nextcloud, Android or a changed behavior by the MS Office MObile Apps itself.
But it worked with MS Office Mobile Apps in Android 6.

Unless the MS Office Mobile Apps work better than Google I would be happy if you bring them back.

**Comment by tiggerfan** [comment] 2017-04-12 01:02
My phone was just upgraded to 7 last week.  my android tablet 6 can edit documents and save the changes, when android 7 goes to save the changes are quietly lost so the client doesn't see any updates to upload. i don't have word, i use ES Note Editor for text doc updates.

**Comment by mario** [comment] 2017-04-12 23:18
Unfortunately, this is a problem with MS Office apps that we cannot workaround :( Sorry folks!

Closing for now until they fix it.

**Comment by tiggerfan** [comment] 2017-04-12 23:42
i do not use MS crap.  i can reproduce it without MS crap.  so while it may be a v7 issue it is not a MS issue

**Comment by kangaroo72** [comment] 2017-04-12 23:46
@tiggerfan ... You're using Android 7.0? On which mobile? Why I'm asking??
WebDav was also not working on 7.0 (using NGINX) 'cause 7.0 has the bug with ssl_curves ...
But I don't know if this is coherently ...
Would be interesting to know what a 7.1-device is doing ...

**Comment by tiggerfan** [comment] 2017-04-12 23:53
i have a moto G4 plus and they just pushed out Andriod 7.0 last week and i upgraded.  i didn't have issues before the upgrade

**Comment by kangaroo72** [comment] 2017-04-12 23:55
same here ... but I'm using the Samsung Note 5 ...
I'm thinking 'bout downgrading to 6.0.1 - there're more problems with Nougat which I have ...

**Comment by tiggerfan** [comment] 2017-04-13 00:04
i haven't had any other issues. just not able to save documents in the nextcloud location when i change using "ES Note Editor"

**Comment by kangaroo72** [comment] 2017-04-13 00:38
are U using webdav-sync for contacts too?

**Comment by tiggerfan** [comment] 2017-04-13 00:51
no, switch from owncloud to next a month ago and was using calDAV-Sync and CardDAV-Sync and kept them after i switched, they still work so i don't see any need to use webdav-sync

**Comment by kangaroo72** [comment] 2017-04-13 00:54
yep - that was what I mean - sorry. I've used DavDroid for this, and it was unable to connect to my nextcloud. This was that problem ... [https://forums.bitfire.at/topic/1242/elliptic-curve-ciphers-not-available-on-android-7](url)

**Comment by mario** [comment] 2017-04-13 02:09
Will re-open and investigate more...

**Comment by mario** [comment] 2017-04-13 02:56
From everything I've seen this is an issue with the other apps. If you try opening a Word file even from Google drive it will open only read only because it doesnt respect the intent. Same with some other apps...

**Comment by yamajo** [comment] 2017-04-27 13:41
Hello,
I use Android 7.0 on Samsung S7edge Stock and Nextcloud client 1.4.2.

I encounter the same issue :
- open nextcloud client
- select or open a txt file
- menu "open with"
- select a txt editor like "ES text Editor"
- the file is opened in read only. (I'd like to write.)
It was working with the previous NC version.

A other similar change occurred since the last NC version :
- open nextcloud client
- select or open a txt file
- menu "open with"
- the text editor Coastline is not displayed in the list of editors, but It was working with the previous NC version.

Thanks

**Comment by mario** [comment] 2017-04-27 13:42
Were you using the previous version with Android 7.0 as well?

**Comment by yamajo** [comment] 2017-04-27 13:52
I updated to Android 7 before 29/03/2017 (my last system check update date).
I think it worked with Android 7 and the previous NC version. But it's a two weeks window, so I won't swear on it.
Thanks

**Comment by tobiasKaminsky** [comment] 2017-04-27 14:35
@yamajo is the app on internal storage or external?

**Comment by mario** [comment] 2017-04-27 14:40
Has nothing to do with it afaik. Its an issue with some apps not using
requested permissions.

**Comment by yamajo** [comment] 2017-04-27 14:46
@tobiasKaminsky the app is on internal storage. On external storage it was always "read only" from the beginning and even when I was under OwnCloud.
@mario yes, but it has been working for the previous months.

In waiting for a solution, I can use an external text editor to access directly the downloaded files on the data folder, without going through NC. And the offline available files I change like that are automaticaly uploaded. 

Thanks for your concern.

**Comment by mario** [comment] 2017-04-27 14:50
Android 7 changed quite a lot in how files are accessed though :-/

**Comment by mario** [comment] 2017-05-03 20:51
Unfortunately closing :( All my investigations lead me to believe this is really a problem with 3rd party apps that we cannot workaround.

**Comment by jeffsf** [comment] 2017-06-06 06:08
@mario I would definitely like to know what problems you've found with app permissions to be the root cause of this. I have been experiencing problems with _pwsafe_ not being able to open files except in read-only mode. The program needs to be able to read, write, and create files (backups) in the directory in which the data file exists. 

If it is a problem with the app, being able to guide the developer in a direction to resolve the issue would be very helpful. Any documented insight from you would be appreciated.

Thanks!

Android 7 (OmniROM) on Nexus 5x

https://play.google.com/store/apps/details?id=com.jefftharris.passwdsafe

**Comment by kangaroo72** [comment] 2017-06-06 08:34
That's what I wonder ... I'm still not satisfied in this direction. I don't use it often, so I can live with it. But in my eyes it's not (only) an 3rd-party problem. But I'm sorry - I'm only (advanced-)user.
-Tom-

**Comment by yamajo** [comment] 2017-06-06 11:36
I finally found a text editor that can open and write files: QuickEdit Pro.
Also it works with Keepass2Android.

**Comment by tiggerfan** [comment] 2017-06-06 12:38
i'm not a android developer but as a linux admin i do know something about file permissions. i also know how to do research into issues and look for possible resolutions.  Android seems to limit apps to use only their data.  so netcloud client has no problem access the files it has copied locally.  The issue seems to be when another app wants to access files that are "owned" by netcloud.  This seems to be a known issue in android that i would think any android developer would be well aware of.  It seems these restrictions are becoming more restrictive as each major release of android is released.  so a quick search comes up with this info about sharing files and data been android apps.  Why isn't the developer for this app looking at this issue to make sure they are doing it properly?  

https://developer.android.com/training/secure-file-sharing/index.html
https://developer.android.com/training/secure-file-sharing/share-file.html
https://stackoverflow.com/questions/18986611/access-permissions-during-android-file-sharing
https://stackoverflow.com/questions/5745243/data-sharing-between-two-applications
https://medium.com/google-developers/sharing-content-between-android-apps-2e6db9d1368b

cheers,
m.

**Comment by jeffsf** [comment] 2017-06-06 13:32
It's not just file permissions, but also SELinux security contexts. To the benefit of app developers, it isn't a wildly unreasonable assumption that your "working directory" is something that you have rwx privileges for, not some other user/app. That's the working assumption for just about every `nix program out there that accesses the file system, be it physical storage or device access. 

The "file sharing" references, above, are more about sharing files by intent, _through your app_, not on the filesystem. The two apps need to have intimate knowledge of each other, and it is active IPC that is used, not that one directly opens the file that another has written. This is more for providing either high-level access to information (a calendar provider, for example), or the "share this" functionality ("send this photo by MMS/email/Bluetooth/...")


I'm still digging into the _why_ with _PasswdSafe_, but the file permissions themselves set by _nextcloud_ look reasonable. The files aren't "owned" by the _nextcloud_ app, but appear to have reasonable permissions and SELinux context when exposed through /data/media/0/Android/data/com.nextcloud.android.beta/files/nextcloud/

> -rw-rw-r-- 1 media_rw media_rw u:object_r:media_rw_data_file:s0

as well as when exposed through /storage/emulated/0/Android/data/com.nextcloud.android.beta/files/nextcloud/

> rw-rw---- 1 u0_a141 sdcard_rw u:object_r:fuse:s0

At this point, I'm guessing that it will matter which path is used to access the data directory/file, as well as the contexts that the accessing app is permitted to use.

I've noted that _PasswdSafe_ uses content://org.nextcloud.beta.files/external_files/emulated/0/Android/data/com.nextcloud.andriod.beta/files/nextcloud/... which _may_ have something to do with its inability to write to the file/directory.

**Comment by mario** [comment] 2017-06-06 13:36
There is something called "FLAG_GRANT_WRITE_URI_PERMISSION" through which you give third-party apps temporary access to your files. We use that (just like every other sane app), and it works for some applications, while (as of recently) it stopped working for some others.

We are looking into all issues, and have looked into this one as well. All debugging efforts hit a brick wall, and all help is appreciated.

**Comment by jeffsf** [comment] 2017-06-06 16:23
I examined the source for passwdsafe app and found that it was looking for .isWritable() which should return "true"

The version I was running off FDroid was very outdated. Current Play store version works as expected, allowing write, at least of the primary file (the one in the context passed from NextCloud to the "opener" app). At least in this case, the problem was with the app itself.

I haven't been able to configure/write backups in passwdsafe at this time, so I am unsure if the "directory-write" is a problem or not.

**Comment by mario** [comment] 2017-06-06 17:48
@jeffsf ;)

**Comment by tiggerfan** [comment] 2017-06-06 23:43
this issue is marked as closed, i think it should be reopened since this is still being investigated.

**Comment by mario** [comment] 2017-06-07 02:31
I still think this is an issue with 3rd party apps. If you find it otherwise, I'm happy to re-open.

**Comment by jeffsf** [comment] 2017-06-07 04:52
The version from FDroid is identified as 5.2.0 by Titanium Backup and FDroid shows "Added on 2/11/15"

The version from Play is identified as 6.8.1 by Titanium Backup.

I don't immediately see a difference between the two in the code that determines the UI reflecting the ability to edit the target file. Both call `uri.isWritable()` in similar ways (though class and variable names have changed). 

I am _guessing_ that the difference in behavior may be related to the _build_ as the Nougat SDK wasn't available in early 2015, as far as I know.

**Comment by mario** [comment] 2017-06-07 05:04
Yes, I was just checking that.

If the app that tries to open the file from NC has a lower build/target sdk
it will open them read only.

Thanks for the testing!

**Comment by kangaroo72** [comment] 2017-09-17 00:16
Now I sold my Samsung Note 5 (which I've downgraded to Android 6.0.1 'causing this issue). I'm using the Note 8 with Android 7.1.1 now, and again I have this issue ... but it seems that doesn't matter :-(

**Comment by DaDirnbocher** [comment] 2017-09-25 07:55
I think there must have been a change from android 6.x to Android 7.x how opening files are passed to 3rd Party apps.

I have tried this with different settings:
- Devices: ASUS Zenfone Max (model ASUS_Z010D) with Android 6.0.1, Lenovo P2 (model LENOVO P2a42) with Android 7.0
- Android apps: nextcloud 1.4.3, nextcloud dev 20170903, owncloud 2.4.0, ocloud.de 1.7.2
- 3rd Party apps: DocsToGo (DataViz), SmartOffice, Microsoft Excel
- Clouds: one nextcloud 11 Installation, one owncloud 9.1.3

All (*) combinations (android Version, android app, 3rd party app, cloud) are working except 
nextcloud app or owncloud app on android 7. It does not depend on the 3rd party app, it does not depend on the cloudversion. And it is working on Android 7 using ocloud.de-app.

The issue (in my case) is not that files are opened read only, the issue is that the are opened from another place (which is read only). 

For example using nextcloud 1.4.3 with an account  on a nextcloud 11-cloud and opening a *.xls file with DocsToGo is ...

- ... working on the Android 6 device, because the file is opened from the path where the nc-app usually stores the files on the local device
- ... not working on the Android 7 device, because the file is opened from a temporary path 
(see attached screeshots)

my current workarounds on android 7 are:
- using ocloud.de app instead of nextcloud-app (preferred Version at the moment)
- mark the xls-Flie as "offline available", switch to the 3rd party app and open the file  directly from the path where it is stored by the nextcloud app, in this case i have to do the sync to the cloud manually.


(*) to be fair: i didn't really test all combinations but enough of them to be sure about this.

![nc_andr6](https://user-images.githubusercontent.com/11771553/30797699-3a42ab66-a1d7-11e7-94df-f929dc9a1b05.png)
![nc_andr7](https://user-images.githubusercontent.com/11771553/30797698-3a400b36-a1d7-11e7-8d2c-bef3be8599f6.png)

**Comment by mario** [comment] 2017-10-10 16:39
I found a workaround for this: https://github.com/nextcloud/android/pull/1651

**Comment by kangaroo72** [comment] 2017-10-19 15:47
"pr exists" - does this mean "Pre Release exists"?? If so, where is this release? :-)

**Comment by AndyScherzinger** [comment] 2017-10-19 16:58
@kangaroo72 atm you could compile https://github.com/nextcloud/android/pull/1651 and install it on your device. It is also part of dev builds but for some reasons no new dev builds get created/published but we need @tobiasKaminsky for that so this won't happen before end of next week. :/ 
Sorry :(

**Comment by kangaroo72** [comment] 2017-10-19 18:06
@AndyScherzinger I've just installed the SDK and took a look ... without coding skills no chance :-(

**Comment by AndyScherzinger** [comment] 2017-10-19 18:25
You don't need the coding skills ;) You just need to install the latest Android Studio 3 RC1 and open the cloned branch in Android Studio. At the top is a play button and in case Android Studio detects your device you ca install the app.

**Comment by kangaroo72** [comment] 2017-10-19 18:29
I'll try again later :-)

**Comment by kangaroo72** [comment] 2017-10-19 20:58
Is this the right URL for android-studio? https://github.com/nextcloud/android.git ?
Have I to checkout from git or github?

**Comment by AndyScherzinger** [comment] 2017-10-19 21:18
both should be fine and URL is correct, yes

**Comment by kangaroo72** [comment] 2017-10-19 21:22
I've compiled to an emulated device ... can I copy the apk to my physical one (if I can find it) ;-)

**Comment by AndyScherzinger** [comment] 2017-10-19 21:36
Yes, that can be done and and can also be installed. Beware though that it will demand a deinstallation of the old Nextcloud client since the signature will differ (GPlay or f-droid versions are signed with Nextclouds publishing key). Don't worry, this is an Android security matter and will happen again when you switch back to a pusblished version via GPlay or F-Droid.

**Comment by kangaroo72** [comment] 2017-10-20 19:45
@AndyScherzinger I've built yesterday, and the Apps says 2.0.0 - shouldn't it be 2.0.1?

**Comment by AndyScherzinger** [comment] 2017-10-20 19:58
@kangaroo72 no, it’s 2.0.0 since 2.0.1 is an f-droid only release which is on a special hotfix branch, so all good 👍

**Comment by kangaroo72** [comment] 2017-10-20 20:42
Thanks for info, but the issue (opening files) seems not be fixed here :-(
(Galaxy Note 8)

**Comment by kangaroo72** [comment] 2017-10-20 23:21
Ok - now it really seems not be a problem to compile to my smartphone, but the fix isn't working.
Do I have to integrate it before compiling??

**Comment by mario** [comment] 2017-10-21 05:51
Are you sure sou compiled the right branch and NOT the master?

**Comment by kangaroo72** [comment] 2017-10-21 09:17
Yay - I'm not sure :-)))
Can you tell me how to change the branch in Android Studio?
I've just put in the URL ....
Thanks

**Comment by AndyScherzinger** [comment] 2017-10-21 09:35
Right click on the project:
![2017-10-21 11_22_22-errorfeedback - c__dev_src_android_nextcloud_errorfeedback - android studio 3](https://user-images.githubusercontent.com/1315170/31850461-57f730b6-b652-11e7-8654-c63efca97288.png)

navigate to the right branch (you might have to click a "show all" somewhere in the pop up) - choose "fix-word-opening":
![2017-10-21 11_33_15-errorfeedback - c__dev_src_android_nextcloud_errorfeedback - android studio 3](https://user-images.githubusercontent.com/1315170/31850528-b300f90a-b653-11e7-9546-f9546fdb719c.png)

I'd hope that should do the trick (I am not using the Git integration in Android Studio). Using "just" the git URL defaults you to the master branch.

**Comment by kangaroo72** [comment] 2017-10-21 09:47
That's it!!!!! *woooot* - Thanks :-)

**Comment by kangaroo72** [comment] 2017-10-21 10:25
Well ... up to now I can confirm the fix for Galaxy Note 8 (7.1.1) and Galaxy S7 (7.0)
👍 👍

**Closed** 2017-10-27 06:18 UTC
Labels: bug, pr exists
