### ISSUE TITLE
Upload via share not working

### ISSUE THREAD

**Issue by mjohenneken** [nextcloud/android#7721] opened 2020-12-23 11:15 UTC
### Steps to reproduce
1. Open WhatsApp chat with an image
2. Share that image via nextcloud
3. Select folder and upload

### Expected behaviour
- a notification should appear with upload status
- file should be uploaded 

### Actual behaviour
- nothing happens, no errors, no message, file is not uploaded and not shown in nextcloud android app.

### Can you reproduce this problem on https://try.nextcloud.com?
- No, because click the "take me there" button is doing nothing

### Environment data
Android version:
10
Device model: 
Samsung A50
Stock or customized system:
Stock
Nextcloud app version:
3.14.1
Nextcloud server version:
Storage Share 19.0.3
Hosted @ Strato
Reverse proxy:
No idea

#### Web server error log
No logs written on server

### Observations
- selecting different a newly created folder doesn't make a difference
- Upload inside nextcloud app works
- no notification appears, looks to me that the problem inside the app before the actual upload, maybe a permission issue?
- space is readily available
- stable 40mbit upstream connection 
- It's not specific to WhatsApp. Sharing images from the gallery app doesn't work aswell

**Comment by KwonEunKyung** [comment] 2020-12-23 13:17
I think it's a duplicate of #7587.

**Comment by AndyScherzinger** [comment] 2020-12-23 13:19
Duplicate of #7587

**Closed by AndyScherzinger** 2020-12-23 13:19 UTC
Labels: bug
