### ISSUE TITLE
Media browsing crash on MIUI 13,12.6

### ISSUE THREAD

**Issue by 0x7c9** [nextcloud/android#10303] opened 2022-05-30 11:44 UTC
### Steps to reproduce
1. open app on android
2. open Media from left.
3. wait and bug happens

### Expected behaviour
Load photos and can browse, but not due to bug.

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Couldn't read row 746, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetString(Native Method)
    at android.database.CursorWindow.getString(Unknown Source:9)
    at android.database.AbstractWindowedCursor.getString(Unknown Source:7)
    at android.database.CursorWrapper.getString(Unknown Source:2)
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:957)
    at com.owncloud.android.datamodel.FileDataStorageManager.getGalleryItems(FileDataStorageManager.java:2220)
    at com.owncloud.android.datamodel.FileDataStorageManager.getAllGalleryItems(FileDataStorageManager.java:2165)
    at com.owncloud.android.ui.preview.PreviewImagePagerAdapter.<init>(PreviewImagePagerAdapter.java:124)
    at com.owncloud.android.ui.preview.PreviewImageActivity.initViewPager(PreviewImageActivity.java:149)
    at com.owncloud.android.ui.preview.PreviewImageActivity.onStart(PreviewImageActivity.java:209)
    at android.app.Instrumentation.callActivityOnStart(Unknown Source:0)
    at android.app.Activity.performStart(Unknown Source:31)
    at android.app.ActivityThread.handleStartActivity(Unknown Source:22)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(Unknown Source:124)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(Unknown Source:10)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(Unknown Source:25)
    at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:76)
    at android.app.ActivityThread$H.handleMessage(Unknown Source:127)
    at android.os.Handler.dispatchMessage(Unknown Source:19)
    at android.os.Looper.loopOnce(Unknown Source:176)
    at android.os.Looper.loop(Unknown Source:76)
    at android.app.ActivityThread.main(Unknown Source:138)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
    at com.android.internal.os.ZygoteInit.main(Unknown Source:309)
```
### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`
### Device information
* Brand: `POCO`
* Device: `lmi`
* Model: `POCO F2 Pro`
* Id: `SKQ1.220303.001`
* Product: `lmi`
### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `22.5.25

affected MIUI 13, miui 12.6

**Comment by AlvaroBrey** [comment] 2022-05-30 13:18
Duplicate of #9948

**Closed by AlvaroBrey** 2022-05-30 13:18 UTC
Labels: bug
