### ISSUE TITLE
First time user

### ISSUE THREAD

**Issue by Yujkore** [nextcloud/android#9570] opened 2021-12-16 05:10 UTC
************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: 192.168.0.245:444
	at java.net.URI.create(URI.java:848)
	at com.owncloud.android.authentication.AuthenticatorUrlUtils.normalizeScheme(AuthenticatorUrlUtils.java:103)
	at com.owncloud.android.authentication.AuthenticatorActivity.checkOcServer(AuthenticatorActivity.java:774)
	at com.owncloud.android.authentication.AuthenticatorActivity.onEditorAction(AuthenticatorActivity.java:1382)
	at android.widget.TextView.onEditorAction(TextView.java:6543)
	at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:360)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6854)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0: 192.168.0.245:444
	at java.net.URI$Parser.fail(URI.java:2893)
	at java.net.URI$Parser.checkChars(URI.java:3066)
	at java.net.URI$Parser.checkChar(URI.java:3076)
	at java.net.URI$Parser.parse(URI.java:3092)
	at java.net.URI.<init>(URI.java:584)
	at java.net.URI.create(URI.java:846)
	... 13 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: judyln
Model: LM-G710VM
Id: PKQ1.181105.001
Product: judyln_vzw

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 202251246e1a8

**Comment by AlvaroBrey** [comment] 2021-12-16 08:36
Duplicate of #9338

**Closed by AlvaroBrey** 2021-12-16 08:36 UTC
Labels: bug
