### ISSUE TITLE
App Crash on android when sharing to deleted external storage

### ISSUE THREAD

**Issue by apoger** [nextcloud/android#11369] opened 2023-02-10 10:15 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Add external share like sftp NAS
2. Share something into a folder on that NAS via Android app
3. Delete or rename the external share
4. Share another file on android
5. The app starts within the now missing folder in the former location
6. After click "move folder up" to reach the new destination the app crashes 

### Expected behaviour

App should jump to root or something similar I stead of crashing cause of the missing location 

### Actual behaviour

App crashes with error log and gets stuck. Has to be force quitted.

The error stays for the android sharing function! Only opening the app directly works again till next android sharing try. 

### Android version

android 12

### Device brand and model

Fairphone 4

### Stock or custom OS?

Stock

### Nextcloud android app version

3.23.1

### Nextcloud server version

25.0.3

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "Thread-15" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230191`
* Build flavor: `gplay`

### Device information
* Brand: `Fairphone`
* Device: `FP4`
* Model: `FP4`
* Id: `SKQ1.220201.001`
* Product: `FP4eea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `SP1Y`

### Additional information

No workaround found yet. Maybe deleting app data and setting it up freshly could work...

**Comment by AlvaroBrey** [comment] 2023-02-13 11:32
Duplicate of https://github.com/nextcloud/android/issues/11207

**Closed by AlvaroBrey** 2023-02-13 11:32 UTC
Labels: bug
