### ISSUE TITLE
Upload files

### ISSUE THREAD

**Issue by matkomek** [nextcloud/android#8912] opened 2021-08-29 16:38 UTC
### Steps to reproduce
1. Select upload files from the nextcloud menu

### Expected behaviour
- Tell us what should happen
The app should open a file explorer to select files to upload

### Actual behaviour
- Tell us what happens
The app crashed and show the error message

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
10

Device model: 
Nokia 7.1

Stock or customized system:
Stock

Nextcloud app version:
30170090

Nextcloud server version:
21.0.4

Reverse proxy:
No

#### Web server error log
```
No web server log
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to pause activity {com.nextcloud.client/com.owncloud.android.ui.activity.ReceiveExternalFilesActivity}: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@1bb8a39
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4504)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4455)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4407)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@1bb8a39
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1429)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1543)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:664)
	at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.onInactive(UsbConnectionDispatcher.java:131)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.ensureStateInactive(SecurityKeyManager.java:316)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.refreshActiveState(SecurityKeyManager.java:290)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.onActivityPaused(SecurityKeyManager.java:333)
	at android.app.Application.dispatchActivityPaused(Application.java:466)
	at android.app.Activity.dispatchActivityPaused(Activity.java:1301)
	at android.app.Activity.onPause(Activity.java:2221)
	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:388)
	at com.owncloud.android.ui.activity.BaseActivity.onPause(BaseActivity.java:84)
	at com.owncloud.android.ui.activity.FileActivity.onPause(FileActivity.java:253)
	at android.app.Activity.performPause(Activity.java:7978)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1501)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4494)
	... 12 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Nokia
Device: CTL_sprout
Model: Nokia 7.1
Id: QKQ1.190828.002
Product: Crystal_00WW

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 00WW_4_15T

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2021-09-02 13:27
Duplicate of https://github.com/nextcloud/android/issues/8585

**Closed by AlvaroBrey** 2021-09-02 13:27 UTC
Labels: bug
