### ISSUE TITLE
how to fix it? please

### ISSUE THREAD

**Issue by robertaccess11** [nextcloud/android#14214] opened 2024-12-21 16:56 UTC
### Cause of error
```java
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 9
    at java.lang.String.checkBoundsBeginEnd(String.java:4500)
    at java.lang.String.substring(String.java:2527)
    at com.nextcloud.client.account.UserAccountManagerImpl.exists(UserAccountManagerImpl.java:119)
    at com.nextcloud.client.mixins.SessionMixin.onRestart(SessionMixin.kt:100)
    at com.nextcloud.client.mixins.MixinRegistry.onRestart(MixinRegistry.kt:48)
    at com.owncloud.android.ui.activity.BaseActivity.onRestart(BaseActivity.java:118)
    at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1592)
    at android.app.Activity.performRestart(Activity.java:9140)
    at android.app.ActivityThread.performRestartActivity(ActivityThread.java:6062)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:250)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2693)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:9063)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300690`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `b0s`
* Model: `SM-S908B`
* Id: `UP1A.231005.007`
* Product: `b0sxeea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S908BXXUDEXK5`

**Comment by joshtrichards** [comment] 2024-12-28 15:05
Duplicate of #13828

**Closed by joshtrichards** 2024-12-28 15:05 UTC
