### ISSUE TITLE
Android App fails in on first access

### ISSUE THREAD

**Issue by mikedixson** [nextcloud/android#8425] opened 2021-05-16 19:22 UTC
### Steps to reproduce
1. Open Android app
2. Tap a folder
3. This error pops up:

************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=3405, totalRows=2128
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1001)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:161)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:131)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:248)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:280)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:190)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProvider.delete(ContentProvider.java:1820)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:389)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:352)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2476)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:421)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:586)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:574)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:2234)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:438)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:528)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:410)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:238)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus8T
Model: KB2003
Id: RP1A.201005.001
Product: OnePlus8T_EEA

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2103221832

### Expected behaviour
- Tell us what should happen
Folder should open and list contents

### Actual behaviour
- Tell us what happens

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2021-05-17 11:56
Duplicate of #6688

**Closed by tobiasKaminsky** 2021-05-17 11:56 UTC
Labels: bug
