### ISSUE TITLE
App stürzt immer ab

### ISSUE THREAD

**Issue by Karsten55** [nextcloud/android#6718] opened 2020-08-17 12:46 UTC
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/data/app/com.nextcloud.client-Aa9Ll7pnWLMtVv9yj3cT8A==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-Aa9Ll7pnWLMtVv9yj3cT8A==/lib/arm, /data/app/com.nextcloud.client-Aa9Ll7pnWLMtVv9yj3cT8A==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: sanders_n
Model: Moto G (5S) Plus
Id: OPS28.65-36-14
Product: sanders_n

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 63857

### Steps to reproduce
1. Öffne den Browser und melde dich in der Cloud an
2. Lösche die angezeigten Benachrichtigung
3. 

### Expected behaviour
- nichts

### Actual behaviour
- App stürzt ab

**Comment by AndyScherzinger** [comment] 2020-08-17 14:39
Duplicate of #4675

**Closed by AndyScherzinger** 2020-08-17 14:39 UTC
Labels: bug
