### ISSUE TITLE
Break on first connectio

### ISSUE THREAD

**Issue by bapjg** [nextcloud/android#5227] opened 2020-01-18 09:21 UTC
### Steps to reproduce
************ CAUSE OF ERROR ************

android.view.InflateException: Binary XML file line #7: Error inflating class android.webkit.WebView
	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
	at com.owncloud.android.authentication.AuthenticatorActivity.onGetServerInfoFinish(AuthenticatorActivity.java:1319)
	at com.owncloud.android.authentication.AuthenticatorActivity.onRemoteOperationFinish(AuthenticatorActivity.java:1218)
	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:716)
	at com.owncloud.android.services.-$$Lambda$OperationsService$2BVgsxDpOpa4JqgzeD7OGZBLSiI.run(lambda)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5349)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	... 21 more
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x3040002
	at android.content.res.Resources.getText(Resources.java:275)
	at android.content.res.Resources.getString(Resources.java:361)
	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:702)
	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:619)
	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:758)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:608)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:546)
	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:312)
	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:97)
	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:264)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:124)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:111)
	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:108)
	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:261)
	at android.webkit.WebView.<init>(WebView.java:548)
	at android.webkit.WebView.<init>(WebView.java:483)
	at android.webkit.WebView.<init>(WebView.java:466)
	at android.webkit.WebView.<init>(WebView.java:453)
	... 24 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: e9wifi
Model: LG-V700
Id: LRX22G
Product: e9wifi_open_com

************ FIRMWARE ************
SDK: 21
Release: 5.0.2
Incremental: 15286143492ab
. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-01-20 09:24
Duplicate of #4943

**Closed by AndyScherzinger** 2020-01-20 09:24 UTC
Labels: bug
