### ISSUE TITLE
Nextcloud app (f-droid version) is syncronizing all my files to the phone

### ISSUE THREAD

**Issue by soc7** [nextcloud/android#13818] opened 2024-10-19 07:22 UTC
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

After upgrading to latest version 3.30.1 from f-droid on my pixel 8 running grapheneOS stable the app started syncronizing all my files from the server to the phone, downloading everything.

### Expected behaviour

Only syncronize what is requested

### Actual behaviour

Syncronizing everything regardless of settings

### Android version

14

### Device brand and model

google pixel 8

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.30.1

### Nextcloud server version

29.0.7

### Using a reverse proxy?

I don't know

**Comment by Skealz** [comment] 2024-10-19 07:40
Same ! It happened after installing the 3.30.1 version

May be linked to https://github.com/nextcloud/android/pull/13494

**Comment by soc7** [comment] 2024-10-19 08:11
> Same ! It happened after installing the 3.30.1 version
> 
> May be linked to [#13494](https://github.com/nextcloud/android/pull/13494)

How do I deactivate that? I never activate it

**Comment by Spreadcat** [comment] 2024-10-19 08:21
I experience the same. The full sync just ate my mobile-data on an unstable wifi-connection when it started to sync everything. Not a problem though for my data, but it's synching now for quite a while and I cannot find the setting where to disable it - there is a new entry in the settings for manging the two-ways-sync though (but it does nothing while still syncing).

This might become interesting for other users as well.

**Comment by maximilianovermeyer** [comment] 2024-10-19 08:43
Same here since there update. 
Quite confusing: My instance holds about 75 GB of data, the nextcloud app used more than four times that amount.
![Image](https://github.com/user-attachments/assets/f19696b1-454d-43e4-ad8a-d56286d63220)
![Image](https://github.com/user-attachments/assets/610a9f2e-bd92-4ecf-8d57-580821936afa)

**Comment by cyberwolfie1** [comment] 2024-10-19 09:09
Same issue here. Have not found a way of disabling it other than enabling Airplane mode.  On 3.30.1.

**Comment by severindupouy** [comment] 2024-10-19 09:24
Same here.

**Comment by sogutwie** [comment] 2024-10-19 09:25
Same issue under android 14. Only solution by now was deactivating the app in the phone app settings.

**Comment by slm85kbh** [comment] 2024-10-19 09:25
I had to reboot my phone and uninstall the app to stop it, the notifications blocked my UI completely. Unfortunately this meant I couldn't get any logs out of it. 
After a re-installation of 3.30.1 the problem hasn't reappeared so far (3 hours).

3.30.1 (F-Droid) on LineageOS for microG AP2A.290905.003

**Comment by maximilianovermeyer** [comment] 2024-10-19 09:54
I just saw that this is a duplicate of a pinned bug.
https://github.com/nextcloud/android/issues/13738

**Comment by joshtrichards** [comment] 2024-10-19 12:17
Duplicate of #13738

**Closed by joshtrichards** 2024-10-19 12:17 UTC
Labels: bug, 0. Needs triage
