### ISSUE TITLE
Smaller chunk size on wi-fi

### ISSUE THREAD

**Issue by gjedeer** [nextcloud/android#3938] opened 2019-04-29 17:55 UTC
### Is your feature request related to a problem? Please describe.

In https://github.com/nextcloud/android/issues/1238 owncloud-android has introduced chunked upload with 10MB chunks for wi-fi and 1MB chunks on mobile. Whenever I'm on wi-fi, I get a lot of failed uploads, Nextcloud keeps retrying which puts load on the server, and as a result there are always 3-4 php processes running.

Some uploads don't complete for days, despite being retried all the time. I still have an upload from April 10 in the queue. It was a relatively small file of about 30 MB. In the same queue, 500MB files sometimes passed at 2nd or 3rd try.

Today I did a manual build, replacing CHUNK_SIZE_WIFI in android-library with 1MB and magically, all the files are uploaded correctly for the first time. The load on my server is under 1.0 for the first time in a long time.

Android app was usually showing "unconfigured server" (which, as I've found in source code, is just error 500). The errors I've been getting in my owncloud server were `Stream from assembly node shorter than expected, got 0 bytes, expected 10240000`, full error pasted below.

### Describe the solution you'd like

If there was a checkbox to always use 1MB chunks, that would be very helpful.

### Describe alternatives you've considered

I checked my server configuration but it seems the issue just comes from network being slow.

### Additional context

Server error:
```
{
  "reqId": "ZinRJr75P4hDbYAGVxsW",
  "level": 4,
  "time": "2019-04-29T17:16:30+00:00",
  "remoteAddr": "192.168.xxx",
  "user": "user",
  "app": "webdav",
  "method": "MOVE",
  "url": "/remote.php/dav/uploads/user/15736891724f1e0e9d52ecdcc25e3b08/.file",
  "message": {
    "Exception": "Sabre\\DAV\\Exception",
    "Message": "Stream from assembly node shorter than expected, got 0 bytes, expected 10240000",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/apps/dav/lib/Connector/Sabre/File.php",
        "line": 231,
        "function": "convertToSabreException",
        "class": "OCA\\DAV\\Connector\\Sabre\\File",
        "type": "->",
        "args": [
          {
            "__class__": "Exception"
          }
        ]
      },
      {
        "file": "/var/www/apps/dav/lib/Connector/Sabre/Directory.php",
        "line": 156,
        "function": "put",
        "class": "OCA\\DAV\\Connector\\Sabre\\File",
        "type": "->",
        "args": [
          null
        ]
      },
      {
        "file": "/var/www/3rdparty/sabre/dav/lib/DAV/Tree.php",
        "line": 316,
        "function": "createFile",
        "class": "OCA\\DAV\\Connector\\Sabre\\Directory",
        "type": "->",
        "args": [
          "VID_20190414_071922.mp4",
          null
        ]
      },
      {
        "file": "/var/www/3rdparty/sabre/dav/lib/DAV/Tree.php",
        "line": 130,
        "function": "copyNode",
        "class": "Sabre\\DAV\\Tree",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\DAV\\Upload\\FutureFile"
          },
          {
            "__class__": "OCA\\DAV\\Connector\\Sabre\\Directory"
          },
          "VID_20190414_071922.mp4"
        ]
      },
      {
        "file": "/var/www/3rdparty/sabre/dav/lib/DAV/Tree.php",
        "line": 161,
        "function": "copy",
        "class": "Sabre\\DAV\\Tree",
        "type": "->",
        "args": [
          "uploads/user/15736891724f1e0e9d52ecdcc25e3b08/.file",
          "files/user/InstantUpload/Camera/VID_20190414_071922.mp4"
        ]
      },
      {
        "file": "/var/www/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 642,
        "function": "move",
        "class": "Sabre\\DAV\\Tree",
        "type": "->",
        "args": [
          "uploads/user/15736891724f1e0e9d52ecdcc25e3b08/.file",
          "files/user/InstantUpload/Camera/VID_20190414_071922.mp4"
        ]
      },
      {
        "function": "httpMove",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->",
        "args": [
          {
            "absoluteUrl": "https://myinstance/remote.php/dav/uploads/user/15736891724f1e0e9d52ecdcc25e3b08/.file",
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      },
      {
        "file": "/var/www/3rdparty/sabre/event/lib/EventEmitterTrait.php",
        "line": 105,
        "function": "call_user_func_array",
        "args": [
          [
            {
              "__class__": "Sabre\\DAV\\CorePlugin"
            },
            "httpMove"
          ],
          [
            {
              "absoluteUrl": "https://myinstance/remote.php/dav/uploads/user/15736891724f1e0e9d52ecdcc25e3b08/.file",
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        ]
      },
      {
        "file": "/var/www/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 479,
        "function": "emit",
        "class": "Sabre\\Event\\EventEmitter",
        "type": "->",
        "args": [
          "method:MOVE",
          [
            {
              "absoluteUrl": "https://myinstance/remote.php/dav/uploads/user/15736891724f1e0e9d52ecdcc25e3b08/.file",
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        ]
      },
      {
        "file": "/var/www/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 254,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          {
            "absoluteUrl": "https://myinstance/remote.php/dav/uploads/user/15736891724f1e0e9d52ecdcc25e3b08/.file",
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      },
      {
        "file": "/var/www/apps/dav/lib/Server.php",
        "line": 301,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/remote.php",
        "line": 163,
        "args": [
          "/var/www/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/apps/dav/lib/Connector/Sabre/File.php",
    "Line": 622,
    "Previous": {
      "Exception": "Exception",
      "Message": "Stream from assembly node shorter than expected, got 0 bytes, expected 10240000",
      "Code": 0,
      "Trace": [
        {
          "function": "stream_read",
          "class": "OCA\\DAV\\Upload\\AssemblyStream",
          "type": "->",
          "args": [
            8192
          ]
        },
        {
          "file": "/var/www/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php",
          "line": 91,
          "function": "fread",
          "args": [
            null,
            8192
          ]
        },
        {
          "file": "/var/www/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php",
          "line": 98,
          "function": "stream_read",
          "class": "Icewind\\Streams\\Wrapper",
          "type": "->",
          "args": [
            8192
          ]
        },
        {
          "function": "stream_read",
          "class": "Icewind\\Streams\\CallbackWrapper",
          "type": "->",
          "args": [
            8192
          ]
        },
        {
          "file": "/var/www/lib/private/Files/Storage/Local.php",
          "line": 467,
          "function": "file_put_contents",
          "args": [
            "/srv/owncloud-data/user/files/InstantUpload/Camera/VID_20190414_071922.mp4.ocTransferId1574916193.part",
            null
          ]
        },
        {
          "file": "/var/www/lib/private/Files/Storage/Wrapper/Wrapper.php",
          "line": 630,
          "function": "writeStream",
          "class": "OC\\Files\\Storage\\Local",
          "type": "->",
          "args": [
            "files/InstantUpload/Camera/VID_20190414_071922.mp4.ocTransferId1574916193.part",
            null,
            null
          ]
        },
        {
          "file": "/var/www/apps/dav/lib/Connector/Sabre/File.php",
          "line": 185,
          "function": "writeStream",
          "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
          "type": "->",
          "args": [
            "files/InstantUpload/Camera/VID_20190414_071922.mp4.ocTransferId1574916193.part",
            null
          ]
        },
        {
          "file": "/var/www/apps/dav/lib/Connector/Sabre/Directory.php",
          "line": 156,
          "function": "put",
          "class": "OCA\\DAV\\Connector\\Sabre\\File",
          "type": "->",
          "args": [
            null
          ]
        },
        {
          "file": "/var/www/3rdparty/sabre/dav/lib/DAV/Tree.php",
          "line": 316,
          "function": "createFile",
          "class": "OCA\\DAV\\Connector\\Sabre\\Directory",
          "type": "->",
          "args": [
            "VID_20190414_071922.mp4",
            null
          ]
        },
        {
          "file": "/var/www/3rdparty/sabre/dav/lib/DAV/Tree.php",
          "line": 130,
          "function": "copyNode",
          "class": "Sabre\\DAV\\Tree",
          "type": "->",
          "args": [
            {
              "__class__": "OCA\\DAV\\Upload\\FutureFile"
            },
            {
              "__class__": "OCA\\DAV\\Connector\\Sabre\\Directory"
            },
            "VID_20190414_071922.mp4"
          ]
        },
        {
          "file": "/var/www/3rdparty/sabre/dav/lib/DAV/Tree.php",
          "line": 161,
          "function": "copy",
          "class": "Sabre\\DAV\\Tree",
          "type": "->",
          "args": [
            "uploads/user/15736891724f1e0e9d52ecdcc25e3b08/.file",
            "files/user/InstantUpload/Camera/VID_20190414_071922.mp4"
          ]
        },
        {
          "file": "/var/www/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
          "line": 642,
          "function": "move",
          "class": "Sabre\\DAV\\Tree",
          "type": "->",
          "args": [
            "uploads/user/15736891724f1e0e9d52ecdcc25e3b08/.file",
            "files/user/InstantUpload/Camera/VID_20190414_071922.mp4"
          ]
        },
        {
          "function": "httpMove",
          "class": "Sabre\\DAV\\CorePlugin",
          "type": "->",
          "args": [
            {
              "absoluteUrl": "https://myinstance/remote.php/dav/uploads/user/15736891724f1e0e9d52ecdcc25e3b08/.file",
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        },
        {
          "file": "/var/www/3rdparty/sabre/event/lib/EventEmitterTrait.php",
          "line": 105,
          "function": "call_user_func_array",
          "args": [
            [
              {
                "__class__": "Sabre\\DAV\\CorePlugin"
              },
              "httpMove"
            ],
            [
              {
                "absoluteUrl": "https://myinstance/remote.php/dav/uploads/user/15736891724f1e0e9d52ecdcc25e3b08/.file",
                "__class__": "Sabre\\HTTP\\Request"
              },
              {
                "__class__": "Sabre\\HTTP\\Response"
              }
            ]
          ]
        },
        {
          "file": "/var/www/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 479,
          "function": "emit",
          "class": "Sabre\\Event\\EventEmitter",
          "type": "->",
          "args": [
            "method:MOVE",
            [
              {
                "absoluteUrl": "https://myinstance/remote.php/dav/uploads/user/15736891724f1e0e9d52ecdcc25e3b08/.file",
                "__class__": "Sabre\\HTTP\\Request"
              },
              {
                "__class__": "Sabre\\HTTP\\Response"
              }
            ]
          ]
        },
        {
          "file": "/var/www/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 254,
          "function": "invokeMethod",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": [
            {
              "absoluteUrl": "https://myinstance/remote.php/dav/uploads/user/15736891724f1e0e9d52ecdcc25e3b08/.file",
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        },
        {
          "file": "/var/www/apps/dav/lib/Server.php",
          "line": 301,
          "function": "exec",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/apps/dav/appinfo/v2/remote.php",
          "line": 35,
          "function": "exec",
          "class": "OCA\\DAV\\Server",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/remote.php",
          "line": 163,
          "args": [
            "/var/www/apps/dav/appinfo/v2/remote.php"
          ],
          "function": "require_once"
        }
      ],
      "File": "/var/www/apps/dav/lib/Upload/AssemblyStream.php",
      "Line": 123
    },
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (Android) ownCloud-android/3.6.0",
  "version": "15.0.7.0"
}

```

**Comment by gjedeer** [comment] 2019-04-29 18:06
Alternative idea: not a checkbox, but activate "small chunk mode" when there's a lot of failures in a given time span.

**Comment by tobiasKaminsky** [comment] 2019-04-30 13:46
I would rather rate this as a bug, as uploading 10Mb should be something every server  needs to handle.

Can you give us some more insights on your server?

**Comment by gjedeer** [comment] 2019-04-30 15:14
I have never-ending performance issues with my Nextcloud server, it used to be on an 8-core xeon in a datacenter and it was very slow with just 2 users, redis, MySQL and all other good practices followed. Now it's running on a dedicated EspressoBin with SSD and it's just as slow. I guess it's because I kept upgrading it since ownCloud 4 or 5 and it kept getting slower with every upgrade. I've set up a fresh instance on that Xeon for comparison and it was lightning fast in comparison.

One day I'll just export data and import onto a fresh instance, there's no point debugging this.

Anyway, I don't think it's because of the server slowness. It happens on slower links. For example 10 MB at 1 Mbit/s is around 100 seconds. If the connection is flaky, there's a good chance something will break during these 2 minutes. Ideally, chunk size would be adaptive based on previous upload speed, targetting 20 or 30 seconds per chunk.

**Comment by be-ndee** [comment] 2019-08-12 17:33
As a possible alternative solution: I had the same problem. Upload with wifi was only working for files smaller than 1MB. Mobile upload works for every file size. I set the `client_max_body_size` to 11MB in my nginx config like `client_max_body_size 11MB;`. Now it is working.

**Comment by joshtrichards** [comment] 2024-10-15 18:35
> For example 10 MB at 1 Mbit/s is around 100 seconds. If the connection is flaky, there's a good chance something will break during these 2 minutes.

This part makes sense, but all of your errors from the provided logs are at the assembly stage. That doesn't take place until all the chunks have been uploaded successfully.

I suspect something else was going on here at the time.

**Comment by gjedeer** [comment] 2024-10-16 08:31
I gave up on trying to use Nextcloud on a phone entirely, I've migrated my data to a fresh Docker setup on a real server between 2019 and now. A fresh install with all the recommended docker-compose settings, just moved the files and the calendars. Nextcloud was still quite slow, and the mobile app was still unusable with the same problem as described here.

I've demonstrated with a build with a smaller chunk size that this problem can be fixed easily, whether you choose to implement it or not does not concern me any more. Judging by reading forums, talking to people and your issue tracker, many people are having similar issues though.

**Comment by joshtrichards** [comment] 2024-10-27 16:41
> I've demonstrated with a build with a smaller chunk size that this problem can be fixed easily, whether you choose to implement it or not does not concern me any more. 

I understand you saw a correlation. And I believe you that it resolved your situation. That does not mean that is the root cause of things.

My concern is that in the stack trace, that operation takes place *after* all chunks have already been uploaded *successfully*. The chunking is already done. All the uploading is already done. 

Even if chunking were/is a blocker for uploading in situations such as yours, things should never get far enough to hit the error you posted.

All that is happening during that operation is the assembly of the various already uploaded chunks for placement in their final resting place as the real (single) file within the user home directory. That's all happening entirely on the server. The client isn't even involved at that point (other than waiting to hear from the server that the operation is done).

The error indicates one of the chunk files on disk *server-side* is zero bytes (though it is supposed to be 10240000 bytes).

Even if changing the chunk size fixed things for you, the error indicates a chunk was uploaded supposedly "successfully", but in reality is empty on disk.

> Judging by reading forums, talking to people and your issue tracker, many people are having similar issues though.

Your error, a stream assembly problem within  `stream_read()` due to a 0 byte file being found has been reported exactly _one_ time (your report).

If you're not willing to troubleshoot it any further at this point, I understand. Unfortunately without seeing the client-side logs of all the chunk uploads and/or the web server logs of same, it's basically impossible to work out what happened at this point. There is also some already in progress work to make the chunking more adaptive across all the clients. See point 2 in https://github.com/nextcloud/server/issues/47682#issuecomment-2361976785

I'll close this out on the basis, but it's here recorded in case if ever is reported again.

**Closed by joshtrichards** 2024-10-27 16:41 UTC
Labels: bug, feature: transfers, connectivity, needs review
