### ISSUE TITLE
Nextcloud Client Android Dev “last_upload” not proper updated

### ISSUE THREAD

**Issue by Winlere** [nextcloud/android#11357] opened 2023-02-07 02:28 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. upload some files to some location via system's share interface 
2. remove or move this folder.
3. upload some other file to that location via system's share interface, wait and tap "return" on the top left before you tap upload

Then, it will produce a `NullPointerException`

By looking into the 工程模式(Engineer mode I guess), I found the "last_upload_path" stays the same before the removal of the folder

### Expected behaviour

upload successful

### Actual behaviour

nullpointerexception

### Android version

HarmonyOS 2(Android 10)

### Device brand and model

Huawei MatePad 10.4 5G

### Stock or custom OS?

Stock

### Nextcloud android app version

20220202

### Nextcloud server version

25.0.3

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "Thread-15" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:929)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20230203`
* Build flavor: `versionDev`

### Device information
* Brand: `HUAWEI`
* Device: `HWBAH3-H`
* Model: `BAH3-AN10`
* Id: `HUAWEIBAH3-AN10`
* Product: `BAH3-AN10`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `102.0.0.275C00`

### Additional information

```
ETM -设置偏好
 autoUploadEntriesSplitOut : true autoUploadlnit : true 
 autoUploadPathUpdate : true darkMode : SYSTEM 
 grid _ columns :3.0
 keysReinit : true 
 lastSeenVersionCode :20221008
 last _ upload _ path :(emitted to protect my privacy) 
 legacyClean : true 
 lock : none 
 prefs _ uploader _ behaviour :2
 select _ oc _ account :(emitted to protect my privacy)
 storagePathFix : true 
 storage _ path : (emitted to protect my privacy)
```

**Comment by AlvaroBrey** [comment] 2023-02-07 08:10
Duplicate of #11207

**Closed by AlvaroBrey** 2023-02-07 08:10 UTC
Labels: bug
