### ISSUE TITLE
Crash when back in folder.histiry of a rented folder (send to, share )

### ISSUE THREAD

**Issue by hangrun** [nextcloud/android#11598] opened 2023-05-07 12:45 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Make a picture oder PDF
Use share with next cloud

Next cloud will open last folder. 
If you renamed  the.meanwhile the folder and go back in client to choose new directory  , the client crashes 

### Expected behaviour

Should go back to home directory or last root 

### Actual behaviour

Crash

### Android version

12

### Device brand and model

Poco x3

### Stock or custom OS?

Stock

### Nextcloud android app version

Current version

### Nextcloud server version

No idea

### Using a reverse proxy?

I don't know

### Additional information

IDIOTs

**Comment by ZetaTom** [comment] 2023-05-26 12:34
This behaviour seams to be covered in #11207

**Comment by joshtrichards** [comment] 2023-10-07 22:16
Duplicate of #11207

Fixed in #11410

Released in v3.26.

**Closed by joshtrichards** 2023-10-07 22:16 UTC
Labels: bug
