### ISSUE TITLE
Can not log in with the Android application

### ISSUE THREAD

**Issue by bergentroll** [nextcloud/android#2390] opened 2018-03-22 11:26 UTC
### Actual behaviour
When credentials are typed and I type "log in" window dessapers and nothing happens. Also if I type incorrect credentials, it is error password attention.

### Expected behaviour
After tapping "log in" with propper username and password Nextcloud app  window should be opened and new account should exists.
 
### Steps to reproduce
1. Log in in the NC application.
2. Switch down the NC server for some time. (I am not sure that it is actually necessary step, but at last time I marked that trouble happened after my server's reboot).
3. NC app loses setted account.
4. Now it is impossible to log in again.

One time I supposed that there is some incorrect redirect in my phone memory (some time ago I changed the domain name). So I purged nextcloud and all browsers data, but it did not help. Then I make factory reset and for some time application workd find until server's reboot.

### Environment data
Android version:
7.1.2

Device model: 
Wileyfox Swift

Stock or customized system:
Official LinageOS image

Nextcloud app version:
3.0.3 from f-droid. Also I tried dev version.

Nextcloud server version:
13.0.0 (also trouble was on 12 branch)

#### Web server error log
Empty.

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"n1Lp\/Lw8H0PtHZZZJyWi","remoteAddr":"*HERE WAS AN IP ADDRESS*","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_root\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'cloud'@'localhost' for table 'user'","level":3,"time":"2017-01-02T18:30:36+00:00","method":"POST","url":"\/index.php","user":"--","version":"11.0.0.10"}
{"reqId":"+cRNAieqqHPp0sBxZFq6","remoteAddr":"192.168.10.230","app":"PHP","message":"touch(): Utime failed: Permission denied at \/var\/www\/nextcloud\/lib\/private\/Config.php#229","level":3,"time":"2017-08-31T09:50:29+00:00","method":"GET","url":"\/index.php\/apps\/files\/?dir=\/&fileid=41","user":"--","version":""}
{"reqId":"+cRNAieqqHPp0sBxZFq6","remoteAddr":"192.168.10.230","app":"PHP","message":"fopen(\/var\/www\/nextcloud\/config\/config.php): failed to open stream: Permission denied at \/var\/www\/nextcloud\/lib\/private\/Config.php#230","level":3,"time":"2017-08-31T09:50:29+00:00","method":"GET","url":"\/index.php\/apps\/files\/?dir=\/&fileid=41","user":"--","version":""}
{"reqId":"+cRNAieqqHPp0sBxZFq6","remoteAddr":"192.168.10.230","app":"PHP","message":"chmod(): Operation not permitted at \/var\/www\/nextcloud\/lib\/private\/Config.php#233","level":3,"time":"2017-08-31T09:50:29+00:00","method":"GET","url":"\/index.php\/apps\/files\/?dir=\/&fileid=41","user":"--","version":""}
{"reqId":"3XHLNi6n1UOhSWh7GOmD","remoteAddr":"192.168.10.230","app":"PHP","message":"touch(): Utime failed: Permission denied at \/var\/www\/nextcloud\/lib\/private\/Config.php#229","level":3,"time":"2017-08-31T10:06:10+00:00","method":"GET","url":"\/index.php\/settings\/apps?category=enabled","user":"--","version":""}
{"reqId":"3XHLNi6n1UOhSWh7GOmD","remoteAddr":"192.168.10.230","app":"PHP","message":"fopen(\/var\/www\/nextcloud\/config\/config.php): failed to open stream: Permission denied at \/var\/www\/nextcloud\/lib\/private\/Config.php#230","level":3,"time":"2017-08-31T10:06:10+00:00","method":"GET","url":"\/index.php\/settings\/apps?category=enabled","user":"--","version":""}
{"reqId":"3XHLNi6n1UOhSWh7GOmD","remoteAddr":"192.168.10.230","app":"PHP","message":"chmod(): Operation not permitted at \/var\/www\/nextcloud\/lib\/private\/Config.php#233","level":3,"time":"2017-08-31T10:06:10+00:00","method":"GET","url":"\/index.php\/settings\/apps?category=enabled","user":"--","version":""}
```

Also it was my thread on [help.nextcloud.com](https://help.nextcloud.com/t/trouble-with-android-app/26526/9). Not actually useful.

**Comment by AndyScherzinger** [comment] 2018-03-22 13:24
@bergentroll looking at the server logs you posted there seems to be a filesystem permission issue:
Your server isn't allowed to read the config file and thus any database query will fail and thus the clients won't be able to talk to the server. This should also be the case for any other client and even for your web interface!

**Comment by amas01** [comment] 2018-03-22 13:26
This looks to me like it is the same as #2032 

See the workaround I posted at [#2032 comment](https://github.com/nextcloud/android/issues/2032#issuecomment-370811027).

**Comment by bergentroll** [comment] 2018-03-22 14:00
@AndyScherzinger, I certanly have no any files owned by someone but www-data in my Nextcloud dir, also there is write permission on ./lib/private/Config.php.

@amas01, indeed my issue is the same. I will try this workaround now, thank you!

**Comment by bergentroll** [comment] 2018-03-22 14:23
@amas01, it works! Thank you, hacker! =)
Also I needed to exec `adb root` before `adb pull`.

**Comment by AndyScherzinger** [comment] 2018-03-22 15:21
@bergentroll so closing the issue as a duplicate of #2032

**Closed by AndyScherzinger** 2018-03-22 15:21 UTC
