### ISSUE TITLE
Add image editing functions

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/android#11891] opened 2023-08-09 20:57 UTC
The mobile app deals with pictures and images, however it doesn't have any tools to post-process them, eg crop, change brightness/contrast, sharpen the picture, place some overlay text. This demands to use external tools to edit them, which is less comfortable, and less secure. The closest solution is Signal, which has embedded functions to edit the image, which has been shot.

**Comment by joshtrichards** [comment] 2023-10-15 14:24
Duplicate of #11608 
Added in #11746 
Released in v3.26.0

**Closed by joshtrichards** 2023-10-15 14:24 UTC
Labels: enhancement
