### ISSUE TITLE
App crash while viewing images

### ISSUE THREAD

**Issue by miloleoelia** [nextcloud/android#5505] opened 2020-02-22 18:21 UTC
### Steps to reproduce
1. Open Nextcloud App
2. Open a folder with at least 200/300 photos (2/3MB per photo)
3. Tap on a photo to see the preview
4. Swipe right to see the next photo preview
5. Wait until you see the preview and then do point 4 again (repeat until app crash)

### Expected behaviour
- App not crash and I can see the other photo previews

### Actual behaviour
- App crash

### Environment data
```
************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError: Failed to allocate a 50331660 byte allocation with 16777216 free bytes and 36MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:650)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:626)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:664)
	at com.owncloud.android.ui.adapter.DiskLruImageCache.getBitmap(DiskLruImageCache.java:121)
	at com.owncloud.android.datamodel.ThumbnailsCacheManager.getBitmapFromDiskCache(ThumbnailsCacheManager.java:225)
	at com.owncloud.android.ui.preview.PreviewImageFragment.onStart(PreviewImageFragment.java:254)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2632)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
	at androidx.fragment.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManagerImpl.java:713)
	at androidx.fragment.app.FragmentManagerImpl.startPendingDeferredFragments(FragmentManagerImpl.java:1325)
	at androidx.fragment.app.FragmentManagerImpl.doPendingDeferredStart(FragmentManagerImpl.java:2178)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1703)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:299)
	at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:259)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager.onInterceptTouchEvent(ViewPager.java:2130)
	at com.owncloud.android.ui.components.CustomViewPager.onInterceptTouchEvent(CustomViewPager.java:35)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:417)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3194)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:379)
	at android.view.View.dispatchPointerEvent(View.java:10261)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4503)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4368)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3908)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3961)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3927)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4054)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3935)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4111)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3908)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3961)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3927)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3935)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3908)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6346)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6320)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6281)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6452)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: santoni
Model: Redmi 4X
Id: N2G47H
Product: santoni

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: V11.0.2.0.NAMMIXM

```

**Comment by tobiasKaminsky** [comment] 2020-03-21 19:16
Are the images downloaded?

**Comment by miloleoelia** [comment] 2020-03-22 12:37
Not most of them.
-------- Messaggio originale --------
On 21 mar 2020, 20:17, Tobias Kaminsky ha scritto:

**Comment by tobiasKaminsky** [comment] 2020-03-23 14:02
Duplicate of #5479

**Closed by tobiasKaminsky** 2020-03-23 14:02 UTC
Labels: bug, needs info/discussion
