### ISSUE TITLE
When trying to open menu on Google Pixel 6 Pro

### ISSUE THREAD

**Issue by laserguy2020** [nextcloud/android#9381] opened 2021-11-26 14:40 UTC
### Steps to reproduce
1. Use a Google Pixel 6 Pro
2. Open up the hamburger menu
3. Crash

### Expected behaviour
- Tell us what should happen
A menu opens
### Actual behaviour
- Tell us what happens
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Canvas: trying to draw too large(268435456bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:1019)
	at android.widget.ImageView.onDraw(ImageView.java:1442)
	at android.view.View.draw(View.java:22644)
	at android.view.View.updateDisplayListIfDirty(View.java:21519)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22647)
	at android.view.View.updateDisplayListIfDirty(View.java:21519)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21510)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22647)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
	at android.view.View.updateDisplayListIfDirty(View.java:21519)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22647)
	at com.google.android.material.internal.ScrimInsetsFrameLayout.draw(ScrimInsetsFrameLayout.java:109)
	at android.view.View.updateDisplayListIfDirty(View.java:21519)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22647)
	at android.view.View.updateDisplayListIfDirty(View.java:21519)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21510)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21510)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21510)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21510)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22647)
	at com.android.internal.policy.DecorView.draw(DecorView.java:820)
	at android.view.View.updateDisplayListIfDirty(View.java:21519)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4421)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4149)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3309)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8653)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:780)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: raven
Model: Pixel 6 Pro
Id: SD1A.210817.037
Product: raven

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: 7862242

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2021-11-26 15:01
Duplicate of #8862

**Closed by AlvaroBrey** 2021-11-26 15:01 UTC
Labels: bug
