### ISSUE TITLE
App Auto Upload feature settings

### ISSUE THREAD

**Issue by wookie73** [nextcloud/android#9781] opened 2022-01-31 09:16 UTC
### Steps to reproduce
1. Installed nextcloud app on new phone OnePlus 9T
2. Set up nextcloud including auto upload feature
3.now when I go to settings / auto upload, nextcloud app hangs momentarily then restarts.

### Expected behaviour
- Tell us what should happen
You should get the settings screen for auto upload

### Actual behaviour
- Tell us what happens
Nextcloud hangs for a couple of seconds, then restarts.
After many trys instead of restarting the app now switches to the Uploads folder.

Seems very similar to issue #8863

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

N/A

### Environment data
Android version:
12
Device model: 
Le2125
Stock or customized system:
Stock
Nextcloud app version:
3.19 RC2
Nextcloud server version:
23.0
Reverse proxy:
No
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2022-01-31 14:44
Yes, this looks like a duplicate of #8863. Closing for now

**Closed by AlvaroBrey** 2022-01-31 14:44 UTC
Labels: bug
