### ISSUE TITLE
possibility to change the local path where the nextcloud app stores the local file at android to any folder of your choice not only the predefined ones

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [nextcloud/android#8799] opened 2021-08-02 04:50 UTC
possibility to change the local path where the nextcloud app stores the local file at android to any folder of your choice not only the predefined ones.
Reason: 

On Samsung Phones it is nearly impossible to find the folder where the downloaded files are located in.

**Comment by joshtrichards** [comment] 2023-12-21 23:02
Duplicate of #4223

**Closed by joshtrichards** 2023-12-21 23:02 UTC
Labels: enhancement, hotspot: device storage
