### ISSUE TITLE
Nextcloud crashes when there is too many pictures to upload

### ISSUE THREAD

**Issue by matyaash** [nextcloud/android#6544] opened 2020-07-25 17:51 UTC
### Steps to reproduce
1. point auto upload to folder with many pictures (1200 in my case) 
2. set it to upload pictures already there
3. after a while crash report appears (several minutes) 
4. folders with smaller amount of pictures work fine (300)

### Expected behaviour
- app should upload files or at least notify that there is too many pictures in one folder 

### Actual behaviour
- app crashes 

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 9

Device model: nokia 8 TA-1004

Stock or customized system:Stock

Nextcloud app version: 3.12.1

Nextcloud server version: 19

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
Nextcloud app crash report:

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-aHDCyBROiF-y-ytOXVnwjA==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-aHDCyBROiF-y-ytOXVnwjA==/lib/arm64, /data/app/com.nextcloud.client-aHDCyBROiF-y-ytOXVnwjA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Nokia
Device: NB1
Model: TA-1004
Id: PPR1.180610.011
Product: TA-1004_00WW

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 00WW_5_15I

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2020-07-28 09:40
Stacktrace seems to be unrelated to issue description, thus closing as duplicate of #6290

**Closed by tobiasKaminsky** 2020-07-28 09:40 UTC
Labels: bug
