### ISSUE TITLE
Crash when navigating to upload

### ISSUE THREAD

**Issue by llucax** [nextcloud/android#12004] opened 2023-10-06 15:42 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I'm guessing here

1. Upload a file to a directory via sharing (so go to an app, share something, select nexcloud, navigate to the directory, tap upload)
2. Remove the directory from the server (possibly the parent directory too)
3. Share a file again to nextcloud
4. Now the removed directory is shown as the default location
5. Navigate to the parent directory
6. Get the crash 

### Expected behaviour

Get to the root directory or some existing path instead of crashing.

### Actual behaviour

Crash

### Android version

13 and 14

### Device brand and model

Pixel 6a

### Stock or custom OS?

Stock

### Nextcloud android app version

3.25.0

### Nextcloud server version

27.1.1

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "Thread-39" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30250090`
* Build flavor: `generic`

### Device information
* Brand: `google`
* Device: `bluejay`
* Model: `Pixel 6a`
* Id: `UP1A.231005.007`
* Product: `bluejay`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `10754064`

**Comment by joshtrichards** [comment] 2023-10-07 16:48
Duplicate of #11207

Fixed in #11410

Released in v3.26.

**Closed** 2023-10-07 16:48 UTC
Labels: bug
