### ISSUE TITLE
Android APK not in latest release

### ISSUE THREAD

**Issue by mkyrd** [nextcloud/android#12073] opened 2023-10-21 08:14 UTC
I see the latest stable release of the Android app did not include an apk like previous releases. Was this intentional? As a degoogled android user I really appreciate developers publishing the apk themselves rather than relying on a third-party like f-droid. I'm sure I can figure out how to compile it myself but I'd rather leave that to the experts.

Thanks

**Comment by joshtrichards** [comment] 2023-10-21 12:54
Duplicate of #12020 :-)

**Closed by joshtrichards** 2023-10-21 12:54 UTC
Labels: enhancement
