### ISSUE TITLE
Sort does not work when choosing files to upload

### ISSUE THREAD

**Issue by tinwasp** [nextcloud/android#2699] opened 2018-06-11 09:28 UTC
### Actual behaviour
- When picking files for uploading, sort has no effect

### Expected behaviour
- Items should be sortable in upload view the same way as throughout the rest of the app
 
### Steps to reproduce
1. Open Nextcloud app. Press round button (+), then arrow pointing up for upload.
2. Press three dots, then sort
3. Pick any sort order; it won't have any effect

### Environment data
Android version: 8.0.0
Nextcloud app version: 3.1.0

**Comment by AndyScherzinger** [comment] 2018-06-11 09:35
hi @tinwasp,

thanks for reporting this issue. it is a duplicate of #2467 fixed via #2566 and will be part of the upcoming 3.2.0 release.

Please reopen if the issue still occurs for you after 3.2.0 is out.

**Closed by AndyScherzinger** 2018-06-11 09:35 UTC
