### ISSUE TITLE
Nextcloud fail upload file: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by svitrol** [nextcloud/android#5743] opened 2020-03-26 09:44 UTC
************ CAUSE OF ERROR ************
```java
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)
	at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1558)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:317)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:282)
	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:155)
	at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:516)
	at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:72)
	at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:34)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: davinci
Model: Mi 9T
Id: QKQ1.190825.002
Product: davinci_eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V11.0.4.0.QFJEUXM

**Comment by tobiasKaminsky** [comment] 2020-03-27 05:37
Do you know what you did exactly?

**Comment by svitrol** [comment] 2020-03-27 07:19
I press the button to add file then it took to file manager. There i pick PDF file a press the button upload. But that moment it all freezed so i terminated  the app and repeat the whole process. When i press the upload button for the second time the app again stop working and it showed me bug report. But when i tried upload the file for the third time it showed some dialog if the file should be copied or moved that there is not enough place. So i went with the option move. I hope it will help.

**Comment by tobiasKaminsky** [comment] 2020-03-30 13:33
hm. I cannot reproduce this, but something similar:

- add 10s delay in CheckAvailableSpaceTask in doInBackground
- return false, so that dialog pops up
- start app
- upload a file
- rotate device
--> 
```
 Process: com.nextcloud.client, PID: 14029
    java.lang.IllegalStateException: Fragment IndeterminateProgressDialog{482e9e1 (bd7c5d0e-2962-4cea-a75a-04309989e324)} not associated with a fragment manager.
        at androidx.fragment.app.Fragment.requireFragmentManager(Fragment.java:910)
        at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:245)
        at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:202)
        at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:473)
        at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:80)
```

**Comment by andypfau** [comment] 2022-12-31 09:50
Hi,

I get the same with Android 8.0.0 and SDK 26 (the latest my phone supports):

```
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1610)
    at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1711)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1754)
    at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:854)
    at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:805)
    at com.zynksoftware.documentscanner.ui.scan.InternalScanActivity$compressFiles$1$6.run(InternalScanActivity.kt:166)
    at android.os.Handler.handleCallback(Handler.java:869)
    at android.os.Handler.dispatchMessage(Handler.java:101)
    at android.os.Looper.loop(Looper.java:206)
    at android.app.ActivityThread.main(ActivityThread.java:6760)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)

### App information
* ID: `com.nextcloud.client`
* Version: `30230191`
* Build flavor: `gplay`

### Device information
* Brand: `SHIFT`
* Device: `SHIFT6m`
* Model: `SHIFT6m`
* Id: `O00623`
* Product: `SHIFT6m_EEA`

### Firmware
* SDK: `26`
* Release: `8.0.0`
* Incremental: `1658816935`
```

I verified that Google play does not have any updates for the app.

Steps to reproduce on my side:

1. Scan document
2. Align the corner markers, click the "check" button
3. Click the "check" button again
4. It now goes dark for about a minute, with a "timer" animation in the middle of the screen (I suspect it crops the photo or whatever)
5. The crash appears.

Some more notes:
- It does not happen every time (but as Murphy dictates, it happens 100% of the times when I actually need it).
- This problem existed since few months now, but it works on my iPad (same NC account).
- All other features of the NC app seem to work (it auto-uploads photos taken with my camera app, it syncs files, etc.).

**Comment by joshtrichards** [comment] 2024-07-09 20:44
Duplicate of #10791

**Closed by joshtrichards** 2024-07-09 20:44 UTC
Labels: bug, approved, feature: sync and upload, performance: ISE/IAE :confused:
