### ISSUE TITLE
Nextcloud app crashes under work profile on Huawei P30 with EMUI 9.1

### ISSUE THREAD

**Issue by fabiomercuri** [nextcloud/android#5131] opened 2020-01-09 13:02 UTC
### Steps to reproduce
1. open nextcloud app
2. login
3. app crashes

### Expected behaviour
- Tell us what should happen
the app should show the server content
### Actual behaviour
- Tell us what happens
App crashes
### Environment data
Android version: 9.1

Device model: Huawei P30

Stock or customized system: EMUI 9.1

Nextcloud app version: 3.9.2

Nextcloud server version: 12

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x2010 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@f3222db
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1546)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=3426, uid=1010340 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1953)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3897)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1556)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1415)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1533)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWELE
Model: ELE-L29
Id: HUAWEIELE-L29
Product: ELE-L29EEA

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.260C431

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-01-09 14:46
Duplicate of #4661as well as #4931 and is not supported (Android Work)

**Closed by AndyScherzinger** 2020-01-09 14:46 UTC
Labels: bug

**Comment by AndyScherzinger** [comment] 2020-10-12 15:34
Duplicate of #6654
