### ISSUE TITLE
dev版本崩溃

### ISSUE THREAD

**Issue by running-grass** [nextcloud/android#7336] opened 2020-11-17 02:50 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b9ca909 u0 com.nextcloud.android.beta/com.nextcloud.client.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201114
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWTAS
Model: TAS-AL00
Id: HUAWEITAS-AL00
Product: TAS-AL00

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.1.0.160C00

**Comment by tobiasKaminsky** [comment] 2020-11-17 07:22
Duplicate of #6905

**Closed by tobiasKaminsky** 2020-11-17 07:22 UTC
Labels: bug
