### ISSUE TITLE
Constant failed download

### ISSUE THREAD

**Issue by krakra9** [nextcloud/android#13839] opened 2024-10-21 09:01 UTC
I removed the cache because the app kept notifying me of an error with download. I opened it after the removal and got this error after going through my folders.

### Cause of error
```java
Exception in thread "Syncfolder thread" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getEtag()' on a null object reference
    at com.owncloud.android.operations.SynchronizeFolderOperation.checkForChanges(SynchronizeFolderOperation.java:169)
    at com.owncloud.android.operations.SynchronizeFolderOperation.run(SynchronizeFolderOperation.java:127)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
    at com.owncloud.android.services.SyncFolderHandler.doOperation(SyncFolderHandler.java:106)
    at com.owncloud.android.services.SyncFolderHandler.handleMessage(SyncFolderHandler.java:79)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:257)
    at android.os.Looper.loop(Looper.java:368)
    at android.os.HandlerThread.run(HandlerThread.java:67)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300190`
* Build flavor: `generic`

### Device information
* Brand: `OnePlus`
* Device: `OP516FL1`
* Model: `NE2213`
* Id: `UKQ1.230924.001`
* Product: `NE2213EEA`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S.19ed398-1-530c2`

**Comment by joshtrichards** [comment] 2024-10-21 12:52
Duplicate of #13784

**Closed by joshtrichards** 2024-10-21 12:52 UTC
