### ISSUE TITLE
Sendinblue email link opens in Nextcloud

### ISSUE THREAD

**Issue by LucaDiba** [nextcloud/android#9386] opened 2021-11-27 00:12 UTC
### Steps to reproduce
1. Receive a marketing email sent using Sendinblue provider (the link has the format `https://6joh9.r.bh.d.sendibt3.com/mk/cl/f/...`
2. Click on the link

### Expected behaviour
- Android uses the default browser to open the link

### Actual behaviour
- Android opens the Nextcloud app (asking for total file permission, if not given already)
- After opening, Nextcloud shows a toast message that says that the URL is not valid

### Can you reproduce this problem on https://try.nextcloud.com?
- N/A: this is strictly related to the Android app

### Environment data
Android version: 12

Device model: Pixel 3 XL

Stock or customized system: Stock

Nextcloud app version: 3.18.0

Nextcloud server version: 22.1.1

**Comment by devplan44** [comment] 2022-04-17 17:15
Same here. I click on a link-button (URL) in my Outlook mail app mail on android 12 and then my Nextcloud app (version 3.19.1) opens with "invalid URL"

**Comment by AlvaroBrey** [comment] 2022-04-18 08:46
More discussion in #9703. I'll close this one as there's more info there

**Comment by AlvaroBrey** [comment] 2022-04-18 08:46
Duplicate of #9703

**Closed by AlvaroBrey** 2022-04-18 08:46 UTC
Labels: bug

**Comment by devplan44** [comment] 2022-04-18 10:09
Hey AlvaroBrey - #9703 is in-concise and offers no solution.
