### ISSUE TITLE
Browsing files on Pixel 4 XL

### ISSUE THREAD

**Issue by alleybeachelectric** [nextcloud/android#7419] opened 2020-11-21 10:41 UTC
### Steps to reproduce
1. Open next cloud app
2. Go through photos/videos
3. Watch the app craah

### Expected behaviour
- Tell us what should happen
Be able to view files without the app crashing
### Actual behaviour
- Tell us what happens
App crashes
### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b23634f u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: coral
Model: Pixel 4 XL
Id: RP1A.201105.002
Product: coral

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 6869500

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-11-23 09:08
Duplicate of #6905

**Closed by AndyScherzinger** 2020-11-23 09:08 UTC
Labels: bug
