### ISSUE TITLE
Autoupload file conflict loop

### ISSUE THREAD

**Issue by andreapx** [nextcloud/android#6887] opened 2020-09-03 10:04 UTC
### Steps to reproduce
I don't know how to reproduce it, it happened once

### Expected behaviour
If a conflict happens, it should ask which version to keep

### Actual behaviour
It keeps asking me which version I want even if it has already uploaded the image (more than once), see screenshot
![Screenshot_20200903-081448](https://user-images.githubusercontent.com/13846728/92099345-ae3b5980-edda-11ea-886c-d695a713566a.jpg)

I don't know how to stop. I've already killed the app, but it keeps happening.

### Can you reproduce this problem on https://try.nextcloud.com?
It doesn't happens even in the release app with my server...normally!

### Environment data
Android version: 10

Device model: OnePlus 67 (A6013)

Stock or customized system: Stock (PxygenOS 10.3.5)

Nextcloud app version: 3.13.0

Nextcloud server version: 18.0.3

Reverse proxy: nginx

#### Web server error log
```2020/09/03 11:48:58 [error] 1340#1340: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53
2020/09/03 11:48:58 [error] 1340#1340: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53
2020/09/03 11:49:03 [error] 1340#1340: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53
2020/09/03 11:49:08 [error] 1340#1340: ocsp.int-x3.letsencrypt.org could not be resolved (110: Operation timed out) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/letsencrypt/live/nextcloud.
xxxxxxxxxx.com/fullchain.pem"
```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"3AvDU6Fa5Cp799LaAuCQ","level":0,"time":"2020-09-03T08:40:41+00:00","remoteAddr":"xx.xx.xx.xx","user":"Andrea","app":"no app in context","method":"HEAD","url":"/remote.php/webdav/InstantUpload/Screenshots/Screenshot_20200902-212958.jpg","message":"Deprecated event type for {\"[object] (OCP\\Sa
brePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sa
bre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xm
l\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.13.0","version":"18.0.3.0"}
{"reqId":"3AvDU6Fa5Cp799LaAuCQ","level":0,"time":"2020-09-03T08:40:41+00:00","remoteAddr":"xx.xx.xx.xx","user":"Andrea","app":"no app in context","method":"HEAD","url":"/remote.php/webdav/InstantUpload/Screenshots/Screenshot_20200902-212958.jpg","message":"Deprecated event type for {\"[object] (OCP\\Sa
brePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sa
bre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":\"head\",\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV
\\Xml\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.13.0","version":"18.0.3.0"}
{"reqId":"3lhEnc356Fm0RncZxiG5","level":0,"time":"2020-09-03T08:40:46+00:00","remoteAddr":"xx.xx.xx.xx","user":"Andrea","app":"no app in context","method":"HEAD","url":"/remote.php/webdav/InstantUpload/Screenshots/Screenshot_20200902-212958.jpg","message":"Deprecated event type for {\"[object] (OCP\\Sa
brePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sa
bre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xm
l\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.13.0","version":"18.0.3.0"}
{"reqId":"3lhEnc356Fm0RncZxiG5","level":0,"time":"2020-09-03T08:40:46+00:00","remoteAddr":"xx.xx.xx.xx","user":"Andrea","app":"no app in context","method":"HEAD","url":"/remote.php/webdav/InstantUpload/Screenshots/Screenshot_20200902-212958.jpg","message":"Deprecated event type for {\"[object] (OCP\\Sa
brePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sa
bre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":\"head\",\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV
\\Xml\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.13.0","version":"18.0.3.0"}
```

**Comment by tobiasKaminsky** [comment] 2020-09-04 05:18
Duplicate of #6888 
If not please re-open.

**Closed by tobiasKaminsky** 2020-09-04 05:18 UTC
Labels: bug

**Comment by andreapx** [comment] 2020-09-04 15:07
It is, thanks!
