### ISSUE TITLE
Fix For no server available?

### ISSUE THREAD

**Issue by awptechnologies** [nextcloud/android#12730] opened 2024-03-24 08:05 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Open App

### Expected behaviour

Folder should show Photos

### Actual behaviour

No server available

### Android version

14

### Device brand and model

s22 ultra

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.0

### Nextcloud server version

Nextcloud Hub 7 (28.0.3)

### Using a reverse proxy?

Yes

### Additional information

I cannot fix this issue i have tried multiple suggestions. I know there has to be a solution because everything was working fine and now its not. Some dev has to have a suggestion for this issue. At least something for me to try.

**Comment by awptechnologies** [comment] 2024-03-24 16:33
downgrading to nextcloud 3.25.0 Fixed it. Turned of auto updates.

**Comment by joshtrichards** [comment] 2024-03-24 19:30
I requested logs in #12648 weeks ago from you yet don't see any provided. Is this just a duplicate report about that?

(Please refrain from opening multiple reports on the same matter; it just takes away from time otherwise spent addressing problems).

**Comment by daukus** [comment] 2024-03-24 22:21
In my case it was about some old pictures taken with an lg phone. Pictures removed and all looking good again when reading folders.

![Screenshot 2024-03-25 001621](https://github.com/nextcloud/android/assets/78567609/0581be63-2ec8-4bb0-8e59-9cdf22ebdb15)

**Comment by awptechnologies** [comment] 2024-03-25 05:53
How do I get logs from android app? As far as I know there is no error on server side.

**Comment by awptechnologies** [comment] 2024-03-25 05:55
@joshtrichards I posted this to let people know what I did to fix issue for now.

**Comment by joshtrichards** [comment] 2024-03-25 11:45
> How do I get logs from android app? As far as I know there is no error on server side.

See https://github.com/nextcloud/android/issues/12648#issuecomment-1981658398

**Comment by joshtrichards** [comment] 2024-03-25 11:45
Duplicate of #12648

**Closed by joshtrichards** 2024-03-25 11:45 UTC
Labels: bug, needs info
