### ISSUE TITLE
Custom folder creation error (Samsung S10)

### ISSUE THREAD

**Issue by Veltix** [nextcloud/android#5223] opened 2020-01-17 19:57 UTC
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.ui.dialog.CreateFolderDialogFragment.onClick(CreateFolderDialogFragment.java:139)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond2
Model: SM-G975F
Id: QP1A.190711.020
Product: beyond2lteeea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G975FXXS3BSL4

I just wanted auto upload and create new folder to server

**Comment by AndyScherzinger** [comment] 2020-01-20 22:06
Duplicate of #4792

@Veltix where do you create the folder? in the root directory or a sub-directory of the user?

**Closed by AndyScherzinger** 2020-01-20 22:06 UTC
Labels: bug

**Comment by Veltix** [comment] 2020-01-20 23:01
It doesnt matter, it just crashes when i try create in root or sub.
