### ISSUE TITLE
Auto-Upload not working whilst vpn is on

### ISSUE THREAD

**Issue by bcatly** [nextcloud/android#6449] opened 2020-07-09 21:54 UTC
### Steps to reproduce
1. Turn SurfShark vpn on.
2. Take a picture that is set to auto-upload

### Expected behaviour
- The file should be uploading automatically when on a wifi network.

### Actual behaviour
- Even though I am connected to my wifi, I am being told "Waiting for Wi-Fi." On disabling the vpn, the files will then automatically upload, which is counter productive and insecure. 

### Environment data
Android version: 10

Device model: OnePlus 6

Stock or customized system: Stock

Nextcloud app version: 3.12.1

Nextcloud server version: 19

**Comment by 120e314** [comment] 2020-07-13 06:35
Hello,

same problem here -.-

I'm not sure...but i think its maybe not a vpn problem...more like a problem with android 10.
@tobiasKaminsky please check out this problem and pllsss find a solution, it is such annoying to upload all pics manually, because the auto-upload is not working -.- (and yes the energy-saving mode is disabled).

120e314

**Comment by tobiasKaminsky** [comment] 2020-07-16 09:52
While on wifi we try to check if wifi is behind a payed wall, so we ping http://$yourserver/index.php/204
It might be that this fails.
But I wonder why this would happen on VPN.

**Comment by 120e314** [comment] 2020-07-16 11:44
I had disabled the function "Upload only via free WiFi" and it doesnt't worked, but if I go in the menu -> Uploads and refresh the upload-site the pic will be uploaded.

Check https://github.com/nextcloud/android/issues/6469 out for a better description of this problem.

120e314

**Comment by MrDrMcCoy** [comment] 2020-12-09 00:27
@tobiasKaminsky or another contributor: would you please do us a favor and re-open this? The issue persists for myself and others.

## Steps to reproduce

1. Activate VPN
2. Forcibly set WiFi network to identify as unmetered in system settings
3. Uncheck `Only upload on unmetered WiFi` for camera folder
4. Take picture 

## Expected behavior

The new files should upload.

## Actual behavior

The files get stuck in the upload queue, stating they are waiting for non-metered WiFi.

## Environment data

Android version: 10
Device model: ASUS RoG Phone II
Stock or customized system: Custom (OmniROM with MicroG)
Nextcloud app version: 3.14.1 RC2 (from F-Droid)
Nextcloud server version: 19

**Comment by AndyScherzinger** [comment] 2020-12-09 10:40
cc @tobiasKaminsky

**Comment by tobiasKaminsky** [comment] 2020-12-16 14:27
With which vpn can I test this?

**Comment by MrDrMcCoy** [comment] 2020-12-16 21:00
> With which vpn can I test this?
@tobiasKaminsky I personally experienced this with Mullvad, but I have seen others are reporting the same issue with ProtonVPN, SurfShark, and potentially others.

**Comment by tobiasKaminsky** [comment] 2020-12-18 07:07
This is fixed with https://github.com/nextcloud/android/pull/7488 and will be in 3.15.
You can test also our dev version to verify that it is working correct.

**Closed by tobiasKaminsky** 2020-12-18 07:07 UTC
Labels: bug, needs info/discussion
