### ISSUE TITLE
App crashes when trying to upload large amount of data (about 60 GB) 

### ISSUE THREAD

**Issue by steffen-moser** [nextcloud/android#12334] opened 2023-12-29 12:44 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open Nextcloud App on Huawei P20 Pro running EMUI 10. 
2. Selecting the whole "camera" folder containing about 60 GB of data for upload to the cloud.

### Expected behaviour

Upload should start and backup all camera results on my smartphone. 

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=2, data=Intent { (has extras) }} to activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1114320 bytes
    at android.app.ActivityThread.deliverResults(ActivityThread.java:5471)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5512)
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:213)
    at android.app.ActivityThread.main(ActivityThread.java:8178)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
Caused by: Exception in thread "main" java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1114320 bytes
    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1725)
    at android.app.ContextImpl.startForegroundService(ContextImpl.java:1681)
    at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:674)
    at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:674)
    at com.owncloud.android.files.services.FileUploader.uploadNewFile(FileUploader.java:946)
    at com.owncloud.android.ui.activity.FileDisplayActivity.requestUploadOfFilesFromFileSystem(FileDisplayActivity.java:966)
    at com.owncloud.android.ui.activity.FileDisplayActivity.requestUploadOfFilesFromFileSystem(FileDisplayActivity.java:931)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onActivityResult(FileDisplayActivity.java:859)
    at android.app.Activity.dispatchActivityResult(Activity.java:8413)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:5464)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5512)
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:213)
    at android.app.ActivityThread.main(ActivityThread.java:8178)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
Caused by: Exception in thread "main" android.os.TransactionTooLargeException: data parcel size 1114320 bytes
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(BinderProxy.java:526)
    at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:5183)
    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1705)
    at android.app.ContextImpl.startForegroundService(ContextImpl.java:1681)
    at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:674)
    at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:674)
    at com.owncloud.android.files.services.FileUploader.uploadNewFile(FileUploader.java:946)
    at com.owncloud.android.ui.activity.FileDisplayActivity.requestUploadOfFilesFromFileSystem(FileDisplayActivity.java:966)
    at com.owncloud.android.ui.activity.FileDisplayActivity.requestUploadOfFilesFromFileSystem(FileDisplayActivity.java:931)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onActivityResult(FileDisplayActivity.java:859)
    at android.app.Activity.dispatchActivityResult(Activity.java:8413)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:5464)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5512)
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:213)
    at android.app.ActivityThread.main(ActivityThread.java:8178)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30260090`
* Build flavor: `gplay`

### Device information
* Brand: `HUAWEI`
* Device: `HWCLT`
* Model: `CLT-L29`
* Id: `HUAWEICLT-L29`
* Product: `CLT-L29`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `10.0.0.171C432`

### Android version

10

### Device brand and model

Huawei P20 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.26.0

### Nextcloud server version

Nextcloud 27.1.5 on Solaris 11.4 SRU 64 and PHP 8.1.23

### Using a reverse proxy?

No

**Comment by steffen-moser** [comment] 2023-12-29 19:53
Unfortunately, I can't find the "nextcloud.log" file in the mentioned directory on my phone.

**Comment by hbqdev** [comment] 2024-01-22 01:26
I ran into this issue as well. Android 13 on Galaxy S22+ Latest app version

**Comment by joshtrichards** [comment] 2024-11-07 19:50
Duplicate of #11202

**Closed by joshtrichards** 2024-11-07 19:50 UTC
Labels: bug, feature: transfers, stable-3.26, performance: TTLE
