### ISSUE TITLE
File conflicts persists after unchecking auto-upload for every folder

### ISSUE THREAD

**Issue by f1o1f** [nextcloud/android#12066] opened 2023-10-18 22:20 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Sync (picture)-folders in the Android app
2. Leave the setting for handling file conflicts as is
3. receive hundreds of file conflict notifications (in itself not helpful. This should come in one bulk-message, but that would be a feature request)
4. change settings for all folders or uncheck syncing for all folders
5. the notifications still pop up, eventhough nothing is supposed to be uploaded

### Expected behaviour

- The settings for handling file conflicts should change the app's behavior for all queued files of respective folders
- if I deactivate syncing for (all) folders, I would expect the app to stop uploads for those (all) folders. In turn, there should not be any more file conflict messages

### Actual behaviour

Nothing changes

### Android version

13

### Device brand and model

Fairphone 4

### Stock or custom OS?

Stock

### Nextcloud android app version

3.26.0

### Nextcloud server version

27.1.2

### Using a reverse proxy?

I don't know

**Comment by Heistergand** [comment] 2023-10-19 00:18
This might be a duplicate of issue #11974

**Comment by f1o1f** [comment] 2023-12-07 07:10
> This might be a duplicate of issue #11974

the referenced issue is about the app trying to re-upload files that already exist. Mine is about the app trying to sync folders that aren't toggled to sync anymore. I suspect this has to do with the sync- or notification-queue, but my opinion is that disabling sync for a folder should also retroactively disable notifications about syncing that folder

**Comment by joshtrichards** [comment] 2023-12-27 21:00
Duplicate of #2018

**Closed by joshtrichards** 2023-12-27 21:00 UTC
Labels: bug, feature: auto upload, hotspot: sync conflicts
