### ISSUE TITLE
Auto-upload pauses for every conflicting file, regardless of changed setting.

### ISSUE THREAD

**Issue by politas** [nextcloud/android#7950] opened 2021-02-07 21:42 UTC
### Problem: 
If "Ask me every time" is the setting for auto-upload conflicts, and an upload is started that includes a lot of conflicts, it pauses the upload over and over again. Changing the setting from "Ask me every time" to a predefined choice doesn't impact the current upload. If uploading a collection of large files, this can can stretch the process out for many days.

### Preferred Solution: 
When an upload is paused due to a conflict, it should recheck the conflict resolution setting before continuing after the user makes a choice.

### Describe alternatives you've considered
Another option would be for the resolution dialog to include options for all remaining conflicts in the current upload

**Comment by BUFU1610** [comment] 2021-07-21 21:46
> Another option would be for the resolution dialog to include options for all remaining conflicts in the current upload

This.

**Comment by joshtrichards** [comment] 2023-12-25 03:06
Duplicate of #2018

Let's consolidate discussion and tracking there. I also encourage you to subscribe and/or upvote 👍 that issue.

**Closed by joshtrichards** 2023-12-25 03:06 UTC
Labels: enhancement, feature: auto upload, hotspot: sync conflicts
