### ISSUE TITLE
Automatic folder scan feature

### ISSUE THREAD

**Issue by manshaman** [nextcloud/android#3108] opened 2018-10-03 05:33 UTC
### Actual behaviour
- Tell us what happens
Nextcloud automatically scanns new folders for media. 

### Expected behaviour
- Tell us what should happen
A possibility to disable automatic scan feature and manually set up folders what nextcloud use. For example, i set up one folder what nextcloud uses and nothing else don't show up in the nextcloud application :-)

### Environment data
Android version: 7.1.2

Device model: Oneplus1

Stock or customized system: LineageOS

Nextcloud app version: 3.3.0

Nextcloud server version: ---

**Comment by AndyScherzinger** [comment] 2019-01-12 17:46
duplicate of #3263 when it comes to display in the auto upload screen, duplicate of #3080 when it comes to the notifications shown by the app.

**Closed by AndyScherzinger** 2019-01-12 17:46 UTC
Labels: enhancement
