### ISSUE TITLE
stops upon opening in Lenovo yoga pad YT-X705F

### ISSUE THREAD

**Issue by edumerco** [nextcloud/android#7298] opened 2020-11-11 14:51 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@7b099df
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1410)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6859)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=23693, uid=1010146 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3904)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1346)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1311)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1400)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:22224)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:183)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3323)
	at com.android.server.am.WosActivityManagerService.onTransact(WosActivityManagerService.java:89)
	at android.os.Binder.execTransact(Binder.java:731)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Lenovo
Device: YT-X705F
Model: Lenovo YT-X705F
Id: PKQ1.181218.001
Product: YT-X705F

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: X705F_S001038_200827_ROW

**Comment by AndyScherzinger** [comment] 2020-11-11 16:22
Duplicate of #6654

**Comment by AndyScherzinger** [comment] 2020-11-11 16:23
Fixed via #6748 shipping with the upcoming release

**Closed by AndyScherzinger** 2020-11-11 16:23 UTC
Labels: bug

**Comment by AndyScherzinger** [comment] 2020-11-11 16:25
Thanks for the report @edumerco 

As a work round until 3.14.0 final has been released you can simply install the app on the primary user (just install) since the issue you reported has something to do with multi-OS user management and how apps need to work in order to not break in secondary user scenarios.

**Comment by edumerco** [comment] 2020-11-11 17:28
Hi Andy.

> As a work round until 3.14.0 final has been released you can simply
> install the app on the primary user (just install) since the issue you
> reported has something to do with multi-OS user management and how
> apps need to work in order to not break in secondary user scenarios.

Great work and information!
I'll do that and report back only if something still is amiss.

Thanks a lot. :)

Best regards...
-- 
eduardo mercovich

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. 
 (Anónimo)

**Comment by AndyScherzinger** [comment] 2020-11-12 08:08
Thanks for the feedback @edumerco 👍

**Comment by edumerco** [comment] 2020-11-12 14:32
> Thanks for the feedback @edumerco 👍

Thank you for your work here. :)
Your solution worked -initially-: installing it from the 1st User made
the error go away.

Now it works, but it it doesn't show the real Nextcloud content, but the
initial one (a couple files, a Doc directory, etc.).


-- 
eduardo mercovich

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. 
 (Anónimo)

**Comment by AndyScherzinger** [comment] 2020-11-12 17:34
> Now it works, but it it doesn't show the real Nextcloud content, but the initial one (a couple files, a Doc directory, etc.).

Try a "pull-down-to-refresh" which enforces a reloading of the server content

**Comment by edumerco** [comment] 2020-11-12 17:53
>> Now it works, but it it doesn't show the real Nextcloud content, but
the initial one (a couple files, a Doc directory, etc.).

> Try a "pull-down-to-refresh" which enforces a reloading of the server content

I did it, but still, nothing refreshes.
I don't want to bother, and may wait till the release, if it's already scheduled...

-- 
eduardo mercovich

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. 
 (Anónimo)
