### ISSUE TITLE
Crash after clicking download media on Android app

### ISSUE THREAD

**Issue by leo852** [nextcloud/android#13496] opened 2024-08-31 10:42 UTC
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Fragment PreviewMediaFragment{5015257} (506168ed-06e5-4c0d-9f1e-ace152543fbe) not attached to a context.
    at androidx.fragment.app.Fragment.requireContext(Fragment.java:972)
    at com.owncloud.android.ui.preview.PreviewMediaFragment.lambda$onStart$1(PreviewMediaFragment.java:367)
    at com.owncloud.android.ui.preview.PreviewMediaFragment.$r8$lambda$AkxMJlf2KgePzqOIh5h57BVdLW8(Unknown Source:0)
    at com.owncloud.android.ui.preview.PreviewMediaFragment$$ExternalSyntheticLambda0.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:247)
    at android.app.ActivityThread.main(ActivityThread.java:8656)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30280290`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `f2q`
* Model: `SM-F9160`
* Id: `RP1A.200720.012`
* Product: `f2qzhx`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `F9160ZSS2EUJ1`

**Comment by joshtrichards** [comment] 2024-08-31 16:19
Duplicate of #13256

**Closed by joshtrichards** 2024-08-31 16:19 UTC
