### ISSUE TITLE
Crash when entering settings Android 12

### ISSUE THREAD

**Issue by meson11** [nextcloud/android#9184] opened 2021-11-01 08:07 UTC
### Steps to reproduce
1. Press on hamburger menu
2. Crash

### Expected behaviour
- open settings

### Actual behaviour
- crash

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Canvas: trying to draw too large(362048000bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:1019)
	at android.widget.ImageView.onDraw(ImageView.java:1442)
	at android.view.View.draw(View.java:22644)
	at android.view.View.updateDisplayListIfDirty(View.java:21519)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22647)
	at android.view.View.updateDisplayListIfDirty(View.java:21519)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21510)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22647)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
	at android.view.View.updateDisplayListIfDirty(View.java:21519)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22647)
	at com.google.android.material.internal.ScrimInsetsFrameLayout.draw(ScrimInsetsFrameLayout.java:109)
	at android.view.View.updateDisplayListIfDirty(View.java:21519)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22647)
	at android.view.View.updateDisplayListIfDirty(View.java:21519)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21510)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21510)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21510)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21510)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22647)
	at com.android.internal.policy.DecorView.draw(DecorView.java:820)
	at android.view.View.updateDisplayListIfDirty(View.java:21519)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4421)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4149)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3309)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8653)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:780)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: raven
Model: Pixel 6 Pro
Id: SD1A.210817.036
Product: raven

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: 7805805

**Comment by AlvaroBrey** [comment] 2021-11-02 08:26
Duplicate of #8862

**Closed by AlvaroBrey** 2021-11-02 08:26 UTC
Labels: bug
