### ISSUE TITLE
NexCloud crashed. 

### ISSUE THREAD

**Issue by skidnik** [nextcloud/android#4942] opened 2019-12-04 14:32 UTC
NextCloud app crashed and asked me to leave this here.

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{6ea255a u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: markw
Model: Redmi 4 Prime
Id: PQ3A.190801.002
Product: aosp_markw

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.granra.20190925.010525

**Comment by InfamousUser** [comment] 2019-12-04 18:42
There is a typo!

**Comment by AndyScherzinger** [comment] 2019-12-20 07:28
duplicate of #2010

**Closed by AndyScherzinger** 2019-12-20 07:28 UTC
Labels: bug
