### ISSUE TITLE
Problem with auto upload

### ISSUE THREAD

**Issue by dlozev** [nextcloud/android#4410] opened 2019-08-24 14:23 UTC
### Actual behaviour
The auto upload don't working.

### Expected behaviour
Must upload my photos to nextcloud
 
### Steps to reproduce
1. Install the app
2. Connect the app to the server
3. Configure the auto upload

### Environment data
Android version: MIUI global 10.2

Device model: Xiaomi Redmi Note 4

Stock or customized system:

Nextcloud app version: Latest

Nextcloud server version: Latest

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ingomc** [comment] 2019-08-24 19:11
I have the same issue: Samsung Galaxy S7, Android 8.0.0
Nextcloud v3.7.1

**Comment by dlozev** [comment] 2019-08-25 12:40
With iOS app the problem is same. (iPhone 5c)

**Comment by ingomc** [comment] 2019-08-26 07:51
So as i found out, it is probably not a bug... if you put new images in the folder you want to autoupload (autoupload camera folder, shoot new photos), it works for me, but older images are not uploaded automaticaly, so this is the expected behavior of the app, it is supposed to work like that. But i think most people expect to sync to whole Folder with older Picture etc inside, so that would be a feature request

**Comment by tobiasKaminsky** [comment] 2019-08-27 06:46
@ingomc then this is a duplicate of #285, which we are aware of, but still had no time to do it…

**Closed by tobiasKaminsky** 2019-08-27 06:46 UTC
Labels: bug
