### ISSUE TITLE
Files app top text box text illegible in dark mode

### ISSUE THREAD

**Issue by InfamousUser** [nextcloud/android#5492] opened 2020-02-19 20:45 UTC
### Steps to reproduce
1. Add text to the top of the Files app
2. Open the Android app
3. Use dark mode
4. Witness black on less black text appear on top (or rather don't witness it, depending on your eyesight)

### Expected behaviour
- Text should be legible irrespective of the lightness mode

### Actual behaviour
- Text isn't legible irrespective of the lightness mode

### Environment data
Android version: 10

Device model: Google Pixel 2

Stock or customized system: stock

Nextcloud app version: 3.10.1

Nextcloud server version: 18.0.1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

![Bug](https://user-images.githubusercontent.com/47887158/74875119-0b514f80-5362-11ea-81fe-7c9926227096.jpg)

**Comment by AndyScherzinger** [comment] 2020-02-20 07:49
Thanks for the report @InfamousUser

**Comment by AndyScherzinger** [comment] 2020-02-20 07:50
Duplicate of #5232

**Closed by AndyScherzinger** 2020-02-20 07:50 UTC
Labels: bug, feature:Theming

**Comment by InfamousUser** [comment] 2020-02-20 09:10
Ah sorry I tried to see if it was reported but didn't know what to search for. Great to see it reported already.

**Comment by AndyScherzinger** [comment] 2020-02-20 10:41
No worries, again thanks for reporting and for taking the time to look for already existing reports 👍
