### ISSUE TITLE
Upload from other apps (via share) stops after a dozens on files

### ISSUE THREAD

**Issue by major-mayer** [nextcloud/android#8328] opened 2021-04-29 08:12 UTC
### Steps to reproduce
0. I disabled battery optimizations and kept the phone active the whole time, so that the Nextcloud app shouldn't get closed
1. Open you favorite gallery app (i tried MIUI Gallery and Cx File Explorer to make sure, that it's not app dependent)
2. Select many pictures (~30)
3. Upload them into a folder on your Nextcloud account using the share button and the Nextcloud Android app

### Expected behaviour
- After a while all images should be on the server

### Actual behaviour
- The upload progress (visible in the notifications) stops  after about 10 - 15 images
- No error is thrown, but the majority of the images are missing on the server
- The upload list in the Nextcloud App only shows the images that were uploaded, the rest is simply missing

### Can you reproduce this problem on https://try.nextcloud.com?
- Yes I tried tried it on the demo server. The logs I generated are from demo2.nextcloud.com

### Environment data
Android version: 11 MIUI 12.0.5

Device model: Poco F3

Stock or customized system: Stock

Nextcloud app version: 3.16.0 RC2

Nextcloud server version: Latest i guess? The demo version

Reverse proxy: Probably?

#### Web server error log
```
unfortunately i don't have web server logs from the demo server, but I guess they are not that important anyway
```

#### Nextcloud log (data/nextcloud.log)
I've deleted the logs before I began uploading the images, but still they are huuge. 
So I decided to put them in the attachments, to keep the issue compact.
[TryNextcloud Error.txt](https://github.com/nextcloud/android/files/6397159/TryNextcloud.Error.txt)

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2021-05-04 08:19
Duplicate of https://github.com/nextcloud/android/issues/3301#issuecomment-675918488, but as this one is closed, we keep this open.

**Comment by major-mayer** [comment] 2021-05-04 10:16
Indeed, this could be the case. 
I actually opened a bug report a few months ago (https://github.com/nextcloud/android/issues/6706), which was closed in favor of the referenced issue, but as I experience almost the same behavior again (on a different device, using a different android version) I decided to open an issue again.

Hopefully this time it finally get's fixed.

**Comment by kofaysi** [comment] 2021-05-23 07:18
I experience the same issue on

Model: LG-H850
Brand: lge
Product: h1_global_com
Device: h1
Version-Codename: REL
Version-Release: 10

I'm selecting the same 19 images to upload (a batch camera shot) and each time the same images fail to upload. Parts of the log follow:

successful upload:
```
2021-05-23T08:18:19.392+0200;I;UploadFileOperation;Upload of /storage/emulated/0/Android/media/com.nextcloud.android.beta/nextcloud/tmp/user.name@e.email@ecloud.global/IMG_20210503_093833.jpg to /IMG_20210503_093833.jpg: Operation finished with HTTP status code 201 (success)
2021-05-23T08:18:19.546+0200;D;OwnCloudClient #1;REQUEST PROPFIND /remote.php/webdav/IMG_20210503_093833.jpg
2021-05-23T08:18:19.800+0200;D;ThumbnailsCacheManager;generate thumbnail: IMG_20210503_093833.jpg URI: https://ecloud.global/index.php/apps/files/api/v1/thumbnail/256/256/IMG_20210503_093833.jpg
2021-05-23T08:18:19.801+0200;D;OwnCloudClient #1;REQUEST GET /index.php/apps/files/api/v1/thumbnail/256/256/IMG_20210503_093833.jpg
2021-05-23T08:18:19.802+0200;V;UploadsStorageManager;Updating /storage/emulated/0/Android/media/com.nextcloud.android.beta/nextcloud/tmp/user.name@e.email@ecloud.global/IMG_20210503_093833.jpg with status:UPLOAD_SUCCEEDED and result:UPLOADED (old:/storage/emulated/0/Android/media/com.nextcloud.android.beta/nextcloud/tmp/user.name@e.email@ecloud.global/IMG_20210503_093833.jpg status:UPLOAD_IN_PROGRESS result:-1)
2021-05-23T08:18:19.802+0200;V;UploadsStorageManager;Updating /storage/emulated/0/Android/media/com.nextcloud.android.beta/nextcloud/tmp/user.name@e.email@ecloud.global/IMG_20210503_093833.jpg with status=UPLOAD_SUCCEEDED
2021-05-23T08:18:19.819+0200;D;UploadsStorageManager;updateUpload returns with: 1 for file: /storage/emulated/0/Android/media/com.nextcloud.android.beta/nextcloud/tmp/user.name@e.email@ecloud.global/IMG_20210503_093833.jpg
2021-05-23T08:18:20.451+0200;D;ThumbnailsCacheManager;add thumbnail to cache: IMG_20210503_093833.jpg
```

unsuccessful upload (2x):
```
2021-05-23T08:18:17.284+0200;V;UploadsStorageManager;Inserting /storage/emulated/0/Android/media/com.nextcloud.android.beta/nextcloud/tmp/user.name@e.email@ecloud.global/IMG_20210503_093652.jpg with status=UPLOAD_IN_PROGRESS
2021-05-23T08:18:17.306+0200;D;UploadsStorageManager;storeUpload returns with: content://org.nextcloud.beta.provider/uploads/235 for file: /storage/emulated/0/Android/media/com.nextcloud.android.beta/nextcloud/tmp/user.name@e.email@ecloud.global/IMG_20210503_093652.jpg
```

```
2021-05-23T08:18:17.377+0200;V;UploadsStorageManager;Inserting /storage/emulated/0/Android/media/com.nextcloud.android.beta/nextcloud/tmp/user.name@e.email@ecloud.global/IMG_20210503_093843.jpg with status=UPLOAD_IN_PROGRESS
2021-05-23T08:18:17.401+0200;D;UploadsStorageManager;storeUpload returns with: content://org.nextcloud.beta.provider/uploads/236 for file: /storage/emulated/0/Android/media/com.nextcloud.android.beta/nextcloud/tmp/user.name@e.email@ecloud.global/IMG_20210503_093843.jpg
```

no log entry for some images!

**Comment by kofaysi** [comment] 2021-05-23 07:27
Uploading the same 19 image to a different ecloud.global account on the same device and same NC dev app proceeded with no failure and upload happened swiftly, with no delays.

**Comment by kofaysi** [comment] 2021-05-23 10:06
Later I have found a message about failed upload. The list of items in 

Uploads > Failed/pending restart

contain all 4 images.

- filename.jpg
- sezi in KB, local file not found
- user.name@ecloud.global
- /

The files are still in the photo folder and available for preview and edit.

**Comment by major-mayer** [comment] 2022-05-01 21:45
This issue still happens to me also with other apps like when i try to share a bunch of images from Google Photos

**Comment by piratenpanda** [comment] 2022-07-17 05:28
Same here. The amount of pictures which are uploaded via Google Photos seems random and is very frustrating

**Comment by Hoffmann77** [comment] 2022-09-13 09:44
Experiencing the same issue on a Pixel 6 with the Google photos app. From my experience around ~6 Images get uploaded.

**Comment by ModischFabrications** [comment] 2022-11-25 20:56
Coming back from the older linked issue: This is still a problem for me two years later and seems to be more or less ignored. The last investigation took weeks and multiple logs without fixing anything, it's one of the few reasons that really kills "recommendability" of nextcloud for me. Mobile usage seems really inferior compared to other cloud platforms. I don't think it's a problem with the device either, as I personally found that both GDrive and Mega.nz were running flawless.

**Comment by kofaysi** [comment] 2022-11-25 23:45
A workaround for me: use the Nextcloud client to select items for upload (within the NC client) instead of sharing items from the Gallery (or else) with the NC client. No upload failure or delay detected.

**Comment by major-mayer** [comment] 2022-11-26 07:34
I can confirm this, uploading via Nextcloud app works reliable.
Nevertheless, it's a pity that the share function is so useless...

26.11.2022 00:45:39 kofaysi ***@***.***>:

**Comment by tobiasKaminsky** [comment] 2023-01-30 12:08
I cannot find my debug session.
Out of my head, I remember that this is what happens:
- another app calls NC upload "endpoint"
- upload starts
- if upload takes too long (it is about time, not size), then Android OS will kill receiving app

I outlined in another ticket a possible solution:
NC app could show an active activity that states "receiving files, uploading it…" and this is kept open until all uploads are done.

Queuing them in our upload process would not work, as far as I remember, as those files are only shared temporarily.

**Comment by AubinF** [comment] 2023-07-18 14:47
Same problem here, but with audio files. Upload stops after 3 files.

**Comment by joshtrichards** [comment] 2023-12-24 23:05
Let's centralize tracking for this in #10937.
I encourage those following here to subscribe and/or upvote :+1: that issue.

**Closed by joshtrichards** 2023-12-24 23:05 UTC
Labels: bug, approved, feature: sharing to/from other apps
