### ISSUE TITLE
App was terminated error

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/android#653] opened 2017-02-13 21:00 UTC
I see this on both the beta and production versions of the NC app, 

This is not reproducible by myself, it happens randomly despite the apps being excluded from Android's battery optimisations. 

Typically it'll look something like this: 

- Take lots of photos, or upload lots of files in one go
- Leave the app (home/app switch buttons, not back usually - so the app is "open" still)
- The notification bar shows the files uploading
- Suddenly it stops. You'd assume it's finished, but when opening the uploads screen again:

![screenshot_20170213-184603](https://cloud.githubusercontent.com/assets/3178412/22897802/fd1fd6e2-f21c-11e6-8039-a0e6a227cb12.png)

At the point of opening the uploads screen I'd expect the "failed" uploads to resume as the app is no longer terminated, however they have to be manually restarted.

Android 6.0.1, though I've seen it on prior versions too (though not nougat, as I don't have a test device)

**Comment by jasonbayton** [comment] 2017-02-13 21:01
I've discussed this previously with @AndyScherzinger so perhaps he can also add a voice to the issue. Thanks @mario!

**Comment by AndyScherzinger** [comment] 2017-02-13 21:16
@tobiasKaminsky if I remember correctly this is due to the fact that we do not have a auto resume or restart implemented yet.

**Comment by tobiasKaminsky** [comment] 2017-02-14 06:56
You can say "retry failed" which is a manual auto resume.
But the real question is: why is the app terminated? Auto resume is nice to have, but it never should happen that the app terminates in such a way.
@jasonbayton can you provide us with some logs? This would be really helpful

**Comment by mario** [comment] 2017-02-14 07:22
I'll look into this if I can, but auto-resume will probably be there only for 1.5. Dunno, have to think about it - since it's easy to implement, maybe I'll add it - thoughts @AndyScherzinger @tobiasKaminsky ?

**Comment by tobiasKaminsky** [comment] 2017-02-14 07:53
I vote for keeping the current auto-upload-branch/fix as small as possible and include new functionality in a later version. This way we can release it quicker.
(if we want to discuss this further we should open a new issue "auto resume/ retry" as this issue is about sudden app termination, which is a bug and, if we have the time and know the cause, should be fixed in 1.4.2.

**Comment by tobiasKaminsky** [comment] 2017-02-14 09:07
There is already such an issue: #282, so please any further discussion and implementation in this issue.

**Comment by jasonbayton** [comment] 2017-02-14 09:09
Unfortunately the logs in the app are from 06/02 and only that day. I could try to get logcat but that'd require piping them to a file for _however long_ before the issue presents itself.

When logging in the app works again I can provide as often as you like.

**Comment by tobiasKaminsky** [comment] 2017-02-14 09:16
Regarding the logs in beta, I assume, can you please open a new issue? I am on train and cannot verify it.

**Comment by mario** [comment] 2017-02-14 12:00
I think I found the issue, but dunno where/why it's happening - investigating! :)

**Comment by jasonbayton** [comment] 2017-02-14 12:32
You're a machine @mario

**Comment by mario** [comment] 2017-02-14 12:51
@jasonbayton please try the new apk :)

**Comment by mario** [comment] 2017-02-14 12:53
Keep in mind that on Android, one can never GUARANTEE that something won't die - but newest changes reduced the chances of that to a minimum.

**Comment by jasonbayton** [comment] 2017-02-14 13:27
Oh no, not a persistent notification :p 
(If that's what it takes, so be it..)

**Comment by mario** [comment] 2017-02-14 13:28
@jasonbayton you'll tell me if it helps.

**Comment by jasonbayton** [comment] 2017-02-14 13:31
I'll let you know

**Closed** 2017-02-15 08:49 UTC
Labels: bug
