### ISSUE TITLE
Nextcloud App crashing creating directory in Autoupload menu

### ISSUE THREAD

**Issue by j1lgs0n** [nextcloud/android#5250] opened 2020-01-20 10:25 UTC
### Steps to reproduce
1. Select Auto upload and Open the menu to select the folder to sync
2. Create a folder as the prefered path does not exist yet
3. Confirm folder creation and the App will crash

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data
Android version: See below

Device model: See below

Stock or customized system: stock

Nextcloud app version: See below

Nextcloud server version: 17

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.ui.dialog.CreateFolderDialogFragment.onClick(CreateFolderDialogFragment.java:140)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: jasmine_sprout
Model: Mi A2
Id: PKQ1.180904.001
Product: jasmine

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V10.0.18.0.PDIMIXM

**Comment by AndyScherzinger** [comment] 2020-01-20 10:38
Duplicate of #4792

@j1lgs0n where do you create the folder? in the root directory or a sub-directory of the user?

**Closed by AndyScherzinger** 2020-01-20 10:38 UTC
Labels: bug

**Comment by j1lgs0n** [comment] 2020-01-20 10:55
True, its duplicate, creating the folder in a subdirectory as mentioned in the issue linked by you will also work for me. In my users root it will lead to the crash
