### ISSUE TITLE
Nullpointer at file upload

### ISSUE THREAD

**Issue by DietmarMa** [nextcloud/android#9613] opened 2021-12-23 11:07 UTC
### Expected behaviour
- Tell us what should happen

```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.canWrite()' on a null object reference
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onCreateOptionsMenu(ReceiveExternalFilesActivity.java:1037)
	at android.app.Activity.onCreatePanelMenu(Activity.java:4212)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:287)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3084)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
	at android.view.Choreographer.doFrame(Choreographer.java:1040)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6013
Id: RKQ1.201217.002
Product: OnePlus6T

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2111252327

```

I try to upload a file what is shared from another app. And i get this Nullpointer Exception. Its possible thets a file with the same name is existings on the server.

**Comment by quietwalker-libre** [comment] 2021-12-30 13:41
I'm having the same problem when I try to upload a file into a subfolder of an encrypted folder using the "share" button in android file manager.

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.canWrite()' on a null object reference
 at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onCreateOptionsMenu(ReceiveExternalFilesActivity.java:1037)
 at android.app.Activity.onCreatePanelMenu(Activity.java:4277)
 at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:287)
 at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
 at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3084)
 at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
 at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
 at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
 at android.view.Choreographer.doCallbacks(Choreographer.java:845)
 at android.view.Choreographer.doFrame(Choreographer.java:775)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7839)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: sunfish
Model: Pixel 4a
Id: XXX
Product: sunfish

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: 7888514

The workaround that worked for me was to open the Nextcloud app, enter the encrypted folder and then enter the subfolder where I wanted to upload the file. Once I was in the encrypted subfolder I clicked on "Upload File" button and so I was able to upload the file in the disered directory.

**Comment by joshtrichards** [comment] 2023-04-09 15:11
Dup of #9321 ?

**Comment by joshtrichards** [comment] 2023-10-07 22:38
Duplicate of #9321

**Closed by joshtrichards** 2023-10-07 22:38 UTC
Labels: bug
