### ISSUE TITLE
App Crash at creating new folder at server

### ISSUE THREAD

**Issue by kcastner** [nextcloud/android#5103] opened 2020-01-06 15:26 UTC
Hi there!

### Steps to reproduce
1. I successfully installed nextcloud installed nextcloud to my mobile.
2. I tried to create a custom sync path from local to server. (/storage/emulated/0/WhatsApp)
3. Clicked choose remote path and there I want to create a new folder. At this point it will crash.

### Expected behaviour
- a new folder should be created

### Actual behaviour
- crashed with log file

### Environment data
Android version: 10

Device model: OnePlus 6T

Stock or customized system: Stock - OOS 10.3.0

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
No error there
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
 at com.owncloud.android.ui.dialog.CreateFolderDialogFragment.onClick(CreateFolderDialogFragment.java:139)
 at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7682)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6013
Id: QKQ1.190716.003
Product: OnePlus6T

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 1912142009
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-01-09 15:12
duplicate of #4792

**Closed by AndyScherzinger** 2020-01-09 15:12 UTC
Labels: bug
