### ISSUE TITLE
App crash almost every morning

### ISSUE THREAD

**Issue by hartsberger** [nextcloud/android#7053] opened 2020-10-06 08:18 UTC
### Steps to reproduce
1. Not Sure, but often in the morning after disabeling flight mode and unlocking the screen. 
2. I want to mention, that I have configured several accounts to different servers (local Raspberry Pi Dicker + remote company Nextcloud Server installed from Nextcloud employee)
I have the feeling, that this is more likely to Happen, the more accounts are configured in the app. 

### Expected behaviour
- App should not crash

### Actual behaviour
- after unlocking the screen, the following message appears: 

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/data/app/com.nextcloud.client-1/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-1/lib/arm, /data/app/com.nextcloud.client-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Fairphone
Device: FP2
Model: FP2
Id: 19.11.2
Product: FP2

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: gms-24df0be9

### Environment data
Android version: 7.1.2

Device model: Fairphone 2

Stock or customized system: Fairphone OS

Nextcloud server version: 19.0.3

Reverse proxy: nginx + Other (Sophos UTM)

#### Web server error log
Will have an look in the evening...

#### Nextcloud log (data/nextcloud.log)
No errors

**Comment by AndyScherzinger** [comment] 2020-10-06 08:27
Duplicate of #4675

**Comment by AndyScherzinger** [comment] 2020-10-06 08:27
Fix is shipping with next feature release

**Closed by AndyScherzinger** 2020-10-06 08:27 UTC
Labels: bug
