### ISSUE TITLE
Fully synchronize folder with subfolders

### ISSUE THREAD

**Issue by jamincollins** [nextcloud/android#1920] opened 2018-01-03 20:23 UTC
### Actual behaviour
- The Android client starts synchronizing some of the folder subtree.
- At some point later it simply stops.

### Expected behaviour
- All files should be transferred
 
### Steps to reproduce
1. Upload nested directory and file structure from desktop client to server 
2. select top folder of structure in Android client, select synchronize from three dot menu
3. wait

## Server configuration detail
**Operating system:** Linux 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64

**Webserver:** nginx/1.10.3 (fpm-fcgi)

**Database:** mysql 5.7.20

**PHP version:** 7.0.22-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, ldap, exif, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 12.0.4 - 12.0.4.3

**Updated from an older Nextcloud/ownCloud or fresh install:**  updated

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - bruteforcesettings: 1.0.3
 - comments: 1.2.0
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.3.0
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0
Disabled:
 - encryption
 - external
 - files_accesscontrol
 - files_automatedtagging
 - files_external
 - files_retention
 - templateeditor
 - user_external
 - user_saml

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "updatechecker": false,
    "instanceid": "ocppx3gt680c",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.asgardsrealm.net"
    ],
    "memcache.local": "\\OC\\Memcache\\APCu",
    "datadirectory": "\/opt\/nextcloud\/data",
    "overwrite.cli.url": "https:\/\/cloud.asgardsrealm.net",
    "dbtype": "mysql",
    "version": "12.0.4.3",
    "dbname": "owncloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "maintenance": false,
    "loglevel": 2,
    "appstore.experimental.enabled": true,
    "htaccess.RewriteBase": "\/",
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
+-------------------------------+--------------------------------------------+
| Configuration                 |                                            |
+-------------------------------+--------------------------------------------+
| hasMemberOfFilterSupport      |                                            |
| hasPagedResultSupport         |                                            |
| homeFolderNamingRule          | attr:cn                                    |
| lastJpegPhotoLookup           | 0                                          |
| ldapAgentName                 |                                            |
| ldapAgentPassword             | ***                                        |
| ldapAttributesForGroupSearch  |                                            |
| ldapAttributesForUserSearch   |                                            |
| ldapBackupHost                |                                            |
| ldapBackupPort                |                                            |
| ldapBase                      | ***REMOVED SENSITIVE VALUE***                     |
| ldapBaseGroups                | ***REMOVED SENSITIVE VALUE***                     |
| ldapBaseUsers                 | ***REMOVED SENSITIVE VALUE***                     |
| ldapCacheTTL                  | 600                                        |
| ldapConfigurationActive       | 1                                          |
| ldapDefaultPPolicyDN          |                                            |
| ldapDynamicGroupMemberURL     |                                            |
| ldapEmailAttribute            | mail                                       |
| ldapExperiencedAdmin          | 0                                          |
| ldapExpertUUIDGroupAttr       |                                            |
| ldapExpertUUIDUserAttr        |                                            |
| ldapExpertUsernameAttr        |                                            |
| ldapGidNumber                 | gidNumber                                  |
| ldapGroupDisplayName          | cn                                         |
| ldapGroupFilter               |                                            |
| ldapGroupFilterGroups         |                                            |
| ldapGroupFilterMode           | 0                                          |
| ldapGroupFilterObjectclass    |                                            |
| ldapGroupMemberAssocAttr      | uniqueMember                               |
| ldapHost                      | ***REMOVED SENSITIVE VALUE***             |
| ldapIgnoreNamingRules         |                                            |
| ldapLoginFilter               | (&(|(objectclass=posixAccount))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                            |
| ldapLoginFilterEmail          | 0                                          |
| ldapLoginFilterMode           | 0                                          |
| ldapLoginFilterUsername       | 1                                          |
| ldapNestedGroups              | 0                                          |
| ldapOverrideMainServer        |                                            |
| ldapPagingSize                | 500                                        |
| ldapPort                      | 636                                        |
| ldapQuotaAttribute            |                                            |
| ldapQuotaDefault              |                                            |
| ldapTLS                       | 0                                          |
| ldapUserDisplayName           | displayname                                |
| ldapUserDisplayName2          |                                            |
| ldapUserFilter                | (|(objectclass=posixAccount))              |
| ldapUserFilterGroups          |                                            |
| ldapUserFilterMode            | 1                                          |
| ldapUserFilterObjectclass     | posixAccount                               |
| ldapUuidGroupAttribute        | auto                                       |
| ldapUuidUserAttribute         | auto                                       |
| turnOffCertCheck              | 0                                          |
| turnOnPasswordChange          | 1                                          |
| useMemberOfToDetectMembership | 1                                          |
+-------------------------------+--------------------------------------------+

```
</details>

## Client configuration

**Android version:** 7.0

**Device model:** Samsung Galaxy S6 Edge+

**Stock or customized system::** stock

**Nextcloud app version::** 2.0.0

**Nextcloud server version::** 12.0.4

## Logs

<details><summary>Browser log</summary>

```
Insert your webserver log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

**Comment by jamincollins** [comment] 2018-01-03 20:34
```
$ find mobile/ -type f | wc -l
31547
$ find mobile/ -type d | wc -l
169
$ du -sh mobile/
2.6G    mobile/
```

**Comment by tobiasKaminsky** [comment] 2018-01-04 06:51
Folder synchronization currently is only within the same folder, not for subfolders.
I am changing the title to have a feature request.

**Comment by Whisper40** [comment] 2021-12-11 06:58
Hope to see this feature !

**Comment by joshtrichards** [comment] 2024-10-19 01:11
Duplicate of #269

**Closed by joshtrichards** 2024-10-19 01:11 UTC
Labels: enhancement, feature: sync
