### ISSUE TITLE
Media Player crashes

### ISSUE THREAD

**Issue by DudeDudeDudeDudeDude** [nextcloud/android#9034] opened 2021-09-29 14:27 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{506585c u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1984)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7615)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: judyln
Model: LM-G710
Id: QKQ1.191222.002
Product: judyln_lao_com

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2032918019cf0

**Comment by AlvaroBrey** [comment] 2021-09-29 15:01
Duplicate of #8686

**Closed by AlvaroBrey** 2021-09-29 15:01 UTC
Labels: bug
