### ISSUE TITLE
file templates not shown in new file dialog

### ISSUE THREAD

**Issue by szaimen** [nextcloud/android#10798] opened 2022-10-13 11:46 UTC
However it seems like that templates are not shown anymore. Not sure though if that bug is already present in master.

| 3.21.2 | this pr |
|---|---|
|  ![Screenshot_20221012-094927_Nextcloud](https://user-images.githubusercontent.com/42591237/195282858-b9627be6-6e5c-4daa-aec4-39d70fcf3a3b.png) | ![Screenshot_20221012-094854_Nextcloud QA](https://user-images.githubusercontent.com/42591237/195282911-5ea77199-bd6e-4456-b1cc-0cc01fefdac0.png) |

_Originally posted by @szaimen in https://github.com/nextcloud/android/issues/10717#issuecomment-1275741207_

**Comment by AlvaroBrey** [comment] 2022-10-13 12:02
I can't reproduce this. What are the app versions in both screenshots, and what is the device?

**Comment by szaimen** [comment] 2022-10-13 12:07
3.21.2 on the left and the pr 10717 on the right. It is both on a samsung galaxy s10e with the same account on the same server

**Comment by AlvaroBrey** [comment] 2022-10-13 15:33
Can you test the master branch, and see if it works there? I find it odd that the M3 changes would cause this (and can't reproduce it)

**Comment by AlvaroBrey** [comment] 2022-10-13 15:40
> > Can you test the master branch, and see if it works there? I find it odd that the M3 changes would cause this (and can't reproduce it)
> 
> how? Do you have an apk for me that I can install for testing?

Sent APK via chat

**Comment by szaimen** [comment] 2022-10-13 15:51
I tried with reinstalling and on master it works, with the M3 branch not.

**Comment by AlvaroBrey** [comment] 2022-10-13 16:09
Two more PRs to test when the QA build is done:

https://github.com/nextcloud/android/pull/10799 this will tell me if it's a logic error, or a UI bug

https://github.com/nextcloud/android/pull/10800 to check if capability handling changes are the culprit

**Comment by szaimen** [comment] 2022-10-14 09:40
> #10799 this will tell me if it's a logic error, or a UI bug

this one makes it work again. Is maybe the problem that I have onlyoffice installed and enabled on the server and not richdocuments? But this is probably not the reason since it should at least show the text templates, no?

> #10800 to check if capability handling changes are the culprit

I couldn't test this since it didn't generate an apk for me...

**Comment by AlvaroBrey** [comment] 2022-10-14 10:08
Nah, I'm guessing it's more of a race condition with capability handling. Sent the second APK via chat so you can test it.

**Comment by szaimen** [comment] 2022-10-14 10:18
I tested it and it didn't made the templates visible for me

**Comment by AlvaroBrey** [comment] 2022-10-14 13:29
Fixed by https://github.com/nextcloud/android/pull/10717/commits/e9ae7dccce1e40144434d504d858d0fff046a423

**Closed by AlvaroBrey** 2022-10-14 13:29 UTC
Labels: bug, regression, 0. Needs triage
