### ISSUE TITLE
No progress bar visible when playing .mp3 files

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#7324] opened 2020-11-15 07:45 UTC
### Steps to reproduce
1. Open a downloaded .mp3 file
2. no progress bar is visible (thus giving no indication if the file is 2 mins or 1 hour long) 

### Expected behaviour
- progress bar be visible

Nextcloud Android app 3.13.1

**Comment by tobiasKaminsky** [comment] 2020-11-16 07:06
Duplicate of #7323 as it is the same UI?

**Comment by elpraga** [comment] 2020-11-16 21:11
No, is not a dumplings. 

When playing audio files, progress bar is missing altogether.

**Comment by Kuuuna98** [comment] 2020-11-17 06:11
I think it's a duplicate.

video(mp4 file) does not display the progress bar on the initial screen. However, if you click on the video screen, the progress bar is displayed  after it becomes refresh.
Like the video, music(mp3 file) does not display the progress bar on the initial screen. Music is not refresh because there is no screen. so the progress bar does not seem to be displayed.

#### Initialization screen that appears when I play the .mp3 file (No progress bar)
![Screenshot_20201117-145613_Nextcloud](https://user-images.githubusercontent.com/26339069/99352762-855d3780-28e6-11eb-9f5d-3585ebc24551.jpg)

#### Initialization screen that appears when I play the .mp4 file (No progress bar)
![Screenshot_20201116-171545_Nextcloud](https://user-images.githubusercontent.com/26339069/99352735-7d04fc80-28e6-11eb-8316-3a1b92b51d17.jpg)

#### the progress bar is displayed  after it becomes refresh
![Screenshot_20201116-171616_Nextcloud](https://user-images.githubusercontent.com/26339069/99352751-80988380-28e6-11eb-8510-32b794c953f9.jpg)

**Comment by tobiasKaminsky** [comment] 2020-11-17 07:19
I added info that it also happens on audio files to #7323, so we can close this one.

**Closed by tobiasKaminsky** 2020-11-17 07:19 UTC
Labels: bug, needs info/discussion
