### ISSUE TITLE
App hangs/crashes on startup

### ISSUE THREAD

**Issue by enishii** [nextcloud/android#6096] opened 2020-05-16 21:42 UTC
### Steps to reproduce
1. Open the app with a network connection.
2. Tried reinstalling the app as well.

### Expected behaviour
Open the app to enable browsing of folders. 

### Actual behaviour
The app just hangs 15sec after starting it and the error log is shown. It seems related to listing of the folders as the "progress bar" on top keeps moving until the app crashes.

### Can you reproduce this problem on https://try.nextcloud.com
Didn't try this. 

### Environment data
Android version: 9
Device model: OnePlus 5

Stock or customized system: stock

Nextcloud app version: 3.11.1

Nextcloud server version: 18.0.4

Reverse proxy: no

#### Web server error log
N/A

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=3681, totalRows=1609
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:859)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:157)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:191)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:135)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:185)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:135)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:115)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:327)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:671)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:344)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:474)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1705)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:407)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:478)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:369)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:228)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:357)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5
Model: ONEPLUS A5000
Id: PKQ1.180716.001
Product: OnePlus5

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 2002242003

```

**Comment by tobiasKaminsky** [comment] 2020-05-20 15:04
Duplicate of #5926

**Closed by tobiasKaminsky** 2020-05-20 15:04 UTC
Labels: bug
