### ISSUE TITLE
Null reference while downloading a file

### ISSUE THREAD

**Issue by volhovm** [nextcloud/android#7219] opened 2020-11-03 12:59 UTC
### Steps to reproduce
0. Use a self-hosted server.
1. Trying to download a PDF (or .org, or .epub) file by clicking on it from android app.

### Expected behaviour
- It should get downloaded and auto-opened in my editor of choice.

### Actual behaviour
- In about a second (or less, or sometimes more) after the download starts, the app crashes with the error.
- Happens on both my phone and tablet. 
- Seems to affect all the externally opened files. Small files sometimes succeed to get downloaded and opened (epub files), but then the app crashes right after the epub viewer is opened.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

#### Web server error log

```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.populateList(FileDetailActivitiesFragment.java:418)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$null$3$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:370)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$ZzLUj33qKg0e1Ki8Vd5bki8I6B4.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:173)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: clover
Model: MI PAD 4 PLUS
Id: OPM1.171019.019
Product: clover

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: V10.3.2.0.ODJCNXM
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by volhovm** [comment] 2020-11-03 13:08
This seems the same:
https://github.com/nextcloud/android/issues/7208

**Comment by AndyScherzinger** [comment] 2020-11-03 17:10
Duplicate of #7208

**Comment by AndyScherzinger** [comment] 2020-11-03 17:11
Thanks for the hint and report ❤️

**Closed by AndyScherzinger** 2020-11-03 17:10 UTC
Labels: bug
