### ISSUE TITLE
crash when listening to music

### ISSUE THREAD

**Issue by debian-user-france1** [nextcloud/android#9000] opened 2021-09-23 10:28 UTC
![Screenshot_20210923-122243_Nextcloud](https://user-images.githubusercontent.com/72965843/134491653-ea6ad6e7-c7aa-4742-ad6d-c45d10c01bef.png)

I was listening to a 201KB hook from stay - The Kid Laroy
After pressing the button to go back this happened .. It doesn't matter if I press the triangle on the bottom or the button from Nextcloud

**Comment by debian-user-france1** [comment] 2021-09-23 10:29
Happens every time

**Comment by AlvaroBrey** [comment] 2021-09-23 10:56
Duplicate of #8686

**Closed by AlvaroBrey** 2021-09-23 10:56 UTC
Labels: bug
