### ISSUE TITLE
Screen sleeps while video is playing

### ISSUE THREAD

**Issue by Pravi21** [nextcloud/android#11038] opened 2022-11-15 09:50 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open the nextcloud app
2. Play any length video. 
3. The screen dims and lock after the screen timeout time expires

### Expected behaviour

The video should play till the end without the screen diming or locking.

### Actual behaviour

The screen dims and lock after the screen timeout time expires

### Android version

Android 13

### Device brand and model

Samsung S8 Tablet 

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.3

### Nextcloud server version

24.0.7

### Using a reverse proxy?

No

**Comment by AlvaroBrey** [comment] 2022-11-15 10:47
Duplicate of #9059

**Closed by AlvaroBrey** 2022-11-15 10:47 UTC
Labels: bug
