### ISSUE TITLE
Possibility of locking the app with fingerprint with PIN fallback

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/android#2447] opened 2018-04-09 19:03 UTC
Currently the Nextcloud App can be locked only with either fingerprint or pin. This is an issue if for some reason fingerprint reader is not available but the pin can be known. Usually apps use the fingerprint first/pin or passcode fallback. 
Nextcloud could use this with enforcing a pin to be set then fingerprint be enabled.

**Comment by AndyScherzinger** [comment] 2018-04-09 20:43
Hi @gradinaruvasile thanks for reporting this. The issue is already known and there is also an implementation which needs some further polishing before ready for a release: #1657

So I am closing this issue for that reason. Since we are already in feature freeze for the next release it have to wait at least until the feature release after 3.1. which will be 3.2.

**Closed by AndyScherzinger** 2018-04-09 20:43 UTC
