### ISSUE TITLE
README.md from root directory not clearing

### ISSUE THREAD

**Issue by jj49er** [nextcloud/android#11836] opened 2023-07-25 10:41 UTC
The README.md from the root directory is staying when opening a new folder. The new folder README.md is showing on top of the root README.md

Android 12
Nextcloud version 3.25.0

**Comment by parneet-guraya** [comment] 2023-09-03 19:36
Hi, I solved this issue, Here's what was causing it -->
### Actual Behaviour ->
- `OCFileListFragment` which is the main view when launched, starts with fragment transaction (add) without call to addToBackStack(), It means no reverse transaction can happen thus pressing back exits the app (fragment goes in to onStop()).
- While launching `PreviewTextStringFragment` which opens when clicked upon `Readme.md` (preview at the top) adapter item , with transaction (replace) with addToBackStack(), so `replace` cause the `OCFileListFragment` to Destroy and `PreviewTextStringFragment` launches.
- This line [`else if (leftFragment instanceof PreviewTextStringFragment) {
            createMinFragments(null);
        }`](https://github.com/nextcloud/android/blob/266e27f9ddd5e33fa59d6ee2ee345ccb5549c3ae/app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java#L1098) is the main issue first of all it's not calling super.onBackPressed(); which lead to non reversal of replace transaction, so neither the current `PreviewTextStringFragment` destroys nor `OCFileListFragment` gets created.

- What [createMinFragments(Bundle savedInstanceState)](https://github.com/nextcloud/android/blob/266e27f9ddd5e33fa59d6ee2ee345ccb5549c3ae/app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java#L500) method doing is creating new `OCFileListFragment` with fragment transaction (add) without addToBackStack(), so no reversals.

- So, now when user click on Preview and it opens up and upon pressing back it does not destroy the Preview Fragment and also create new  `OCFileListFragment`, which shows us the Preview Fragment in the fragment and the new `OCFileListFragment` on top of it that's why we are seeing persistent Readme file in the background.

But, In fact we should be calling onBackPressed() as well as not calling the createMinFragments(null); since it's creating the new `OCFileListFragment` and  because if we call this one at this point (along with onBackPressed()) then we will end up with two `OCFileListFragment` showing since one is from reversal transaction and other one is created by function.

And this is what right now we're seeing is the persistent Preview Fragment (due to not calling onBackPressed) and the function creating a new one on top of it.

Linking the PR for this issue.
Thanks!

**Comment by joshtrichards** [comment] 2023-12-01 17:51
Appears to be a duplicate of #9701 :)

**Closed** 2023-12-12 18:45 UTC
Labels: bug, pr exists, feature: files
