### ISSUE TITLE
Media open error

### ISSUE THREAD

**Issue by jorometala** [nextcloud/android#11231] opened 2023-01-07 07:38 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Sync folder on the device
Open media and open one of the photos without thumbnail
Error comes

### Expected behaviour

To see all thumbnails correctly

### Actual behaviour

Got an error
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Couldn't read row 604, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetString(Native Method)
    at android.database.CursorWindow.getString(CursorWindow.java:462)
    at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:54)
    at android.database.CursorWrapper.getString(CursorWrapper.java:141)
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:968)
    at com.owncloud.android.datamodel.FileDataStorageManager.getGalleryItems(FileDataStorageManager.java:2241)
    at com.owncloud.android.datamodel.FileDataStorageManager.getAllGalleryItems(FileDataStorageManager.java:2186)
    at com.owncloud.android.ui.adapter.GalleryAdapter.showAllGalleryItems(GalleryAdapter.kt:168)
    at com.owncloud.android.ui.fragment.GalleryFragment.showAllGalleryItems(GalleryFragment.java:380)
    at com.owncloud.android.ui.fragment.GalleryFragment.handleSearchEvent(GalleryFragment.java:213)
    at com.owncloud.android.ui.fragment.GalleryFragment.onRefresh(GalleryFragment.java:183)
    at androidx.swiperefreshlayout.widget.SwipeRefreshLayout$1.onAnimationEnd(SwipeRefreshLayout.java:208)
    at androidx.swiperefreshlayout.widget.CircleImageView.onAnimationEnd(CircleImageView.java:121)
    at android.view.ViewGroup.finishAnimatingView(ViewGroup.java:7174)
    at android.view.View.draw(View.java:22919)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
    at android.view.View.draw(View.java:23019)
    at android.view.View.updateDisplayListIfDirty(View.java:21883)
    at android.view.View.draw(View.java:22741)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
    at android.view.View.updateDisplayListIfDirty(View.java:21874)
    at android.view.View.draw(View.java:22741)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
    at android.view.View.updateDisplayListIfDirty(View.java:21874)
    at android.view.View.draw(View.java:22741)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
    at android.view.View.draw(View.java:23019)
    at android.view.View.updateDisplayListIfDirty(View.java:21883)
    at android.view.View.draw(View.java:22741)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
    at android.view.View.updateDisplayListIfDirty(View.java:21874)
    at android.view.View.draw(View.java:22741)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
    at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
    at android.view.View.draw(View.java:23019)
    at android.view.View.updateDisplayListIfDirty(View.java:21883)
    at android.view.View.draw(View.java:22741)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
    at android.view.View.updateDisplayListIfDirty(View.java:21874)
    at android.view.View.draw(View.java:22741)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
    at android.view.View.updateDisplayListIfDirty(View.java:21874)
    at android.view.View.draw(View.java:22741)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
    at android.view.View.updateDisplayListIfDirty(View.java:21874)
    at android.view.View.draw(View.java:22741)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
    at android.view.View.updateDisplayListIfDirty(View.java:21874)
    at android.view.View.draw(View.java:22741)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
    at android.view.View.draw(View.java:23019)
    at com.android.internal.policy.DecorView.draw(DecorView.java:880)
    at android.view.View.updateDisplayListIfDirty(View.java:21883)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:542)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:625)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:4645)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4363)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3474)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2265)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9019)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1142)
    at android.view.Choreographer.doCallbacks(Choreographer.java:946)
    at android.view.Choreographer.doFrame(Choreographer.java:875)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:299)
    at android.app.ActivityThread.main(ActivityThread.java:8118)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230191`
* Build flavor: `gplay`

### Device information
* Brand: `Xiaomi`
* Device: `vili`
* Model: `2107113SG`
* Id: `SKQ1.211006.001`
* Product: `vili_eea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `V13.0.20.0.SKDEUXM`

### Android version

12

### Device brand and model

Mi 11t pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.23.1

### Nextcloud server version

25.0.2

### Using a reverse proxy?

No

**Comment by AlvaroBrey** [comment] 2023-01-07 12:41
Duplicate of #9948

**Closed by AlvaroBrey** 2023-01-07 12:41 UTC
Labels: bug
