### ISSUE TITLE
Show the whole filename on the details page

### ISSUE THREAD

**Issue by Sogolumbo** [nextcloud/android#6393] opened 2020-06-30 11:10 UTC
### Current Behaviour
In the folder view long filenames are shortened. E.g.: Verylong...name.mp3
There is no way of finding out the full file name without renaming the file.
The details page also shows a shortened Version.
E.g.: Verylongfilena...

### Wanted behaviour
It should be possible to find out the name of the file without opening the "rename" dialog.

### Solution
Show the full name of files on the details page. There's a lot of space left for that.

### Options
If the name is short enough to fit into the title bar it's not necessary to show it again. It would be an option to hide the name in this case.
Pro-hiding:
Looks clean.
Contra-hiding:
Less predictable for users.

### Screenshot
Details page
![IMG_20200630_130850](https://user-images.githubusercontent.com/33571916/86119527-f2f0fe80-bad2-11ea-9c99-7b9f627829e0.png)

**Comment by AndyScherzinger** [comment] 2020-07-02 08:01
looping in @nextcloud/designers / @jancborchardt since as stated by @Sogolumbo we don't have a convenient way to see the complete file name except when hitting rename (applies like mentioned for the file list as well as for the details page.

**Comment by tobiasKaminsky** [comment] 2020-07-02 10:45
In this detail view a scrolling would be ok IMHO.
As then we have only one animated line…

**Comment by AndyScherzinger** [comment] 2020-07-02 11:19
maybe, yes would have to check if this is possible in the toolbar for headlines

**Comment by jancborchardt** [comment] 2020-07-02 11:47
Is there a common pattern for cases like this? The scrolling animated line is something which I find quite annoying in VLC player for example. Is it done at all to e.g.: Make it possible to tap the title, which then shows a modal with the full title on multiple lines (that could even have a "Rename" button there).

**Comment by Sogolumbo** [comment] 2020-07-03 14:08
I agree with @jancborchardt. I specifically opened the "Details" page to find out the name of the file. I don't want to have to wait for the animation.
I understand that from a design point of view it makes sense to leave it in the same place.
But for power users this would be an annoying delay.

I suggest to detect long file names and then add something like
`Full file name:`
`Very long file name which goes on forever.txt`
at the top of the white area.
The font in the white area is smaller so it's more likely that the name fits into one line.

**Comment by joshtrichards** [comment] 2023-10-16 12:13
Duplicate of #2305 

Let's centralize discussion/tracking of long filename handling there.

**Closed by joshtrichards** 2023-10-16 12:13 UTC
Labels: enhancement
