### ISSUE TITLE
AutoUpload: Allow keeping most recent files on device

### ISSUE THREAD

**Issue by ckocyigit** [nextcloud/android#10635] opened 2022-08-17 15:06 UTC
I'am really loving the AutoUpload function and I'am basically uploading everything from my phone to my server to send my pictures on a save place rather than staying on my phone which could in any moment fall from a window :) But I would also like to have an option to keep e.g. the last month of data on my phone and upload anything older, because obviously recent items are used more frequently and always opening the slow nextcloud galery is a pain.

It would be nice if the AutoUpload configuration menu had a selection box to select a minimal age for the file to be uploaded.
Eg.

1 Week
2 Weeks
1 Month
3 Month
Or even precisely selectable (Which is not really necessary I think)

**Comment by joshtrichards** [comment] 2023-12-14 20:32
Duplicate of #2323 

I suggest subscribing to that issue to track progress and/or giving it an upvote :+1:

**Closed by joshtrichards** 2023-12-14 20:32 UTC
Labels: enhancement, feature: auto upload
