### ISSUE TITLE
  Synchronization function

### ISSUE THREAD

**Issue by wangyifan349** [nextcloud/android#8996] opened 2021-09-22 23:27 UTC
Nextcloud synchronization function, only upload new pictures. Do not upload old pictures.
If the upload fails and you click Clear Failure Record, nextcloud will never upload these files

I recommend that you modify these strange strategies later

**Comment by InfamousUser** [comment] 2021-09-23 07:32
Strange strategies ahahahah! Definitely strange, autoupload is fractured, it never worked correctly since its release.

**Comment by joshtrichards** [comment] 2024-11-01 20:06
> Nextcloud synchronization function, only upload new pictures. Do not upload old pictures.

It will if you configure it to do so.

> If the upload fails and you click Clear Failure Record, nextcloud will never upload these files

Duplicate of #3931

**Closed by joshtrichards** 2024-11-01 20:06 UTC
Labels: enhancement, feature: auto upload, needs review
