### ISSUE TITLE
Error while sincronize

### ISSUE THREAD

**Issue by maquiavs** [nextcloud/android#4825] opened 2019-11-12 17:48 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{df4ca64 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1760)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: platina
Model: MI 8 Lite
Id: PKQ1.181007.001
Product: platina

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V11.0.5.0.PDTMIXM

**Comment by AndyScherzinger** [comment] 2019-12-03 15:00
duplicate of #2010, so closing in favor

**Closed by AndyScherzinger** 2019-12-03 15:00 UTC
Labels: bug
