### ISSUE TITLE
Client crash 30130190

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/android#7167] opened 2020-10-29 19:21 UTC
************ CAUSE OF ERROR ************
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/data/app/com.nextcloud.client-krqTWDN53hpVHPwcbwcavA==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-krqTWDN53hpVHPwcbwcavA==/lib/arm64, /data/app/com.nextcloud.client-krqTWDN53hpVHPwcbwcavA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more
```
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: jasmine_sprout
Model: Mi A2
Id: QKQ1.190910.002
Product: jasmine

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V11.0.12.0.QDIMIXM

**Comment by kolorafa** [comment] 2020-10-29 19:45
Same here :

### Steps to reproduce
1. Using phone normally 
2. Nextcloud app running in background
3. Get error on foreground stopping me from doing my task with error


### Can you reproduce this problem on https://try.nextcloud.com?
- No, bit it happened second time, from nowhere just popped up message with the a stack trace  (previously few months ago)

### Environment data
Android version: 9

Device model: moto z3 play

Stock or customized system: Stock

Nextcloud app version: 30130190

### Logs
#### Nextcloud app log
```

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-oZnkuYm-cOSMn4NQQZO9FQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-oZnkuYm-cOSMn4NQQZO9FQ==/lib/arm64, /data/app/com.nextcloud.client-oZnkuYm-cOSMn4NQQZO9FQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: beckham
Model: Moto Z3 Play
Id: PPWS29.131-27-1-27
Product: beckham

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 34b6d

```

**Comment by AndyScherzinger** [comment] 2020-10-29 21:51
Duplicate of #4675

**Closed by AndyScherzinger** 2020-10-29 21:51 UTC
Labels: bug

**Comment by tobiasKaminsky** [comment] 2020-10-30 06:21
Duplicate of #4675, there you can see that it is fixed, and will be in next version.
