### ISSUE TITLE
App Crash 

### ISSUE THREAD

**Issue by OfficialMuffin** [nextcloud/android#8426] opened 2021-05-16 23:52 UTC
### Steps to reproduce
1. Open app with biometrics

### Expected behaviour
- App should open with no error

### Actual behaviour
- App crashes after using biometrics to unlock app

### Environment data
Android version: 11

Device model: Samsung Note20

Stock or customized system: Stock 

Nextcloud app version: 3.16.0

Nextcloud server version: Latest

#### Nextcloud App Log
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: c1s
Model: SM-N980F
Id: RP1A.200720.012
Product: c1seea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: N980FXXU2DUDA
```

**Comment by AndyScherzinger** [comment] 2021-05-17 09:37
Duplicate of #8370

**Closed by AndyScherzinger** 2021-05-17 09:37 UTC
Labels: bug
