### ISSUE TITLE
Exclude "cache" folder from auto upload / Exclude subfolders from auto upload

### ISSUE THREAD

**Issue by msrv** [nextcloud/android#1692] opened 2017-10-19 09:42 UTC
### Actual behaviour
- On my Huawei P10, the Nextcloud App (2.0), the app is configured to auto-upload my pictues. My P10 saves a "cache" folder within the "camera" folder, that shall be uploaded. As the cache folder changes constantly, auto upload is triggered all the time and uploads the cache folders's content, which will fail because it changes constantly (files get deleted and created)

### Expected behaviour
- Either exclude subfolders in "auto upload" or
- Provide an option to select which folders to auto upload

### Environment data
Android version: 7.0

Device model: Huawei P10

Stock or customized system: No, EMUI 5.1 Stock launcher from Huawei 

Nextcloud app version: 2

Nextcloud server version: 12.0.3

**Comment by PurifyPioneer** [comment] 2023-07-18 22:51
I can confirm this issue on my Mate 20 Pro with Android Anroid/EMUI 12, App-Version 3.25.0 and Server-Version 26.0.3.

I tried putting a ".nomedia" file in the "cache" folder but to no avail.

**Comment by joshtrichards** [comment] 2024-10-19 01:42
Duplicate of #8770

**Closed by joshtrichards** 2024-10-19 01:42 UTC
Labels: enhancement, feature: auto upload, hotspot: media scanner
