### ISSUE TITLE
Fixed/Configurable delay in delete aspect of auto upload

### ISSUE THREAD

**Issue by scalderwood1** [nextcloud/android#3696] opened 2019-03-04 13:19 UTC
### Is your feature request related to a problem? Please describe.
Similar to #2922, I'm frustrated when I want to take a photo, share it in multiple locations, but have auto upload/delete configured. Literally if it waited even a minute, it'd be a perfect solution. I'd like to revisit the feature request, despite others having had it closed, as I think its really not as much of an edge case as was suggested in the comments. The auto delete is a hugely useful for ensuring you know everything was properly synced and never having to worry about cleaning up your phone, but the only pain point it adds is the one I've suggested above. Fixing that would make it a ton more attractive to me.

### Describe the solution you'd like
An option of a fixed delay or configurable delay to the delete aspect of the syncing - ie mark each uploaded item for deletion at next n interval defined by user.

### Describe alternatives you've considered
The only other alternative is to wait for it to upload and share it from there (extra steps) or turn off auto delete (inconvenient device maintenance)

Again, I've read these have been closed previously, but perhaps continuing to have community outreach on it would give a greater sense of the # of people that might be interested in this type of feature.

**Comment by tobiasKaminsky** [comment] 2019-03-08 09:17
I am fine with having a delay.
This way it will also help if you take 5 images, but "instantly" delete 3 (maybe because they are blurry).

In opposite of #2922 we do not delay deletion, but delay complete upload by a given timestamp (1 min)?
This then should also be no option, but simply default.

What do you think, @AndyScherzinger?

**Comment by AndyScherzinger** [comment] 2019-03-08 10:18
I agree with your assessment @tobiasKaminsky. Would be good to have some delay (1 minute like you mentioned) and also simply the behavior, no configurable option (like you mentioned too).

**Comment by bruennlein** [comment] 2019-07-22 14:47
Hi Guys,

the delay would be good. Delete for removed files would be also very important, so we don't have to clean-up the auto-upload folder manually. This would then represent the behavior of the desktop-client, which would make the behavior of the different clients more consistent.

Cheers...

**Comment by joshtrichards** [comment] 2023-12-11 21:38
Related: #2323

**Comment by joshtrichards** [comment] 2024-07-09 13:07
Duplicate of #2323

**Closed by joshtrichards** 2024-07-09 13:07 UTC
Labels: enhancement, approved, feature: auto upload
