### ISSUE TITLE
crash since last update

### ISSUE THREAD

**Issue by kollix** [nextcloud/android#13973] opened 2024-11-07 12:52 UTC
### Cause of error
```java
Exception in thread "main" android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{c7be07c u0 com.nextcloud.client/androidx.work.impl.foreground.SystemForegroundService}
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1872)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7050)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300490`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `dreamlte`
* Model: `SM-G950F`
* Id: `PPR1.180610.011`
* Product: `dreamltexx`

### Firmware
* SDK: `28`
* Release: `9`
* Incremental: `G950FXXUCDVG4`

**Comment by joshtrichards** [comment] 2024-11-07 14:48
Duplicate of #13798

**Closed by joshtrichards** 2024-11-07 14:48 UTC
