### ISSUE TITLE
Exception is thrown when clicking on "shared"

### ISSUE THREAD

**Issue by Mastercuber** [nextcloud/android#10271] opened 2022-05-21 10:41 UTC
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'com.owncloud.android.utils.FileSortOrder$SortType com.owncloud.android.utils.FileSortOrder.getType()' on a null object reference
    at com.owncloud.android.ui.adapter.OCFileListAdapter.getPopupText(OCFileListAdapter.java:905)
    at me.zhanghai.android.fastscroll.RecyclerViewHelper.getPopupText(RecyclerViewHelper.java:136)
    at me.zhanghai.android.fastscroll.FastScroller.onPreDraw(FastScroller.java:198)
    at me.zhanghai.android.fastscroll.FastScroller.$r8$lambda$fhoCEu3yFeBM02d2QCiuR_Ev5oo(Unknown Source:0)
    at me.zhanghai.android.fastscroll.FastScroller$$ExternalSyntheticLambda1.run(Unknown Source:2)
    at me.zhanghai.android.fastscroll.RecyclerViewHelper$1.onDraw(RecyclerViewHelper.java:52)
    at androidx.recyclerview.widget.RecyclerView.onDraw(RecyclerView.java:4668)
    at android.view.View.draw(View.java:21979)
    at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
    at android.view.View.updateDisplayListIfDirty(View.java:20856)
    at android.view.View.draw(View.java:21711)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.draw(View.java:21982)
    at android.view.View.updateDisplayListIfDirty(View.java:20856)
    at android.view.View.draw(View.java:21711)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.updateDisplayListIfDirty(View.java:20847)
    at android.view.View.draw(View.java:21711)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.updateDisplayListIfDirty(View.java:20847)
    at android.view.View.draw(View.java:21711)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.draw(View.java:21982)
    at android.view.View.updateDisplayListIfDirty(View.java:20856)
    at android.view.View.draw(View.java:21711)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.updateDisplayListIfDirty(View.java:20847)
    at android.view.View.draw(View.java:21711)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.draw(View.java:21982)
    at android.view.View.updateDisplayListIfDirty(View.java:20856)
    at android.view.View.draw(View.java:21711)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.updateDisplayListIfDirty(View.java:20847)
    at android.view.View.draw(View.java:21711)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.updateDisplayListIfDirty(View.java:20847)
    at android.view.View.draw(View.java:21711)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.updateDisplayListIfDirty(View.java:20847)
    at android.view.View.draw(View.java:21711)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.updateDisplayListIfDirty(View.java:20847)
    at android.view.View.draw(View.java:21711)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.draw(View.java:21982)
    at com.android.internal.policy.DecorView.draw(DecorView.java:808)
    at android.view.View.updateDisplayListIfDirty(View.java:20856)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:581)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:587)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:664)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:3765)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3493)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2777)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1743)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7772)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
    at android.view.Choreographer.doCallbacks(Choreographer.java:864)
    at android.view.Choreographer.doFrame(Choreographer.java:798)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7397)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `Fairphone`
* Device: `FP3`
* Model: `FP3`
* Id: `8901.3.A.0136`
* Product: `FP3`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `gms-7c69ec7e`

**Comment by AlvaroBrey** [comment] 2022-05-23 07:22
Duplicate of #10227

**Closed by AlvaroBrey** 2022-05-23 07:22 UTC
