### ISSUE TITLE
Crash app

### ISSUE THREAD

**Issue by amsaravi** [nextcloud/android#8901] opened 2021-08-26 14:09 UTC
### Steps to reproduce
1. Play media
2. Comeback to playing media sometimes later
3. The media won't stop and nextcloud app crashes

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- nextcloud app crashes

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e5a03bd u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2074)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8056)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: POCO
Device: vayu
Model: M2102J20SG
Id: RKQ1.200826.002
Product: vayu_global

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: V12.5.3.0.RJUMIXM

**Comment by AlvaroBrey** [comment] 2021-09-09 08:22
Duplicate of #8686

**Closed by AlvaroBrey** 2021-09-09 08:22 UTC
Labels: bug
