### ISSUE TITLE
Empty folder info not shown anymore

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#1185] opened 2017-07-14 07:01 UTC
on the actual master when you open an empty folder the message and icon (folder) aren't shown anymore but the loading message and round progress bar stays on the view.

@tobiasKaminsky can you have a look at this since @mario in going to be on vaca? :)

**Comment by tobiasKaminsky** [comment] 2017-07-20 08:50
Duplicate of #1084

**Closed by tobiasKaminsky** 2017-07-20 08:50 UTC
Labels: bug, high
