### ISSUE TITLE
Issue on Android 

### ISSUE THREAD

**Issue by gaelalso** [nextcloud/android#6094] opened 2020-05-16 02:55 UTC
### Steps to reproduce
1. No step: the crash log or  unlock screen app, appear  without  that user start the app nextcloud. 
When you want to start the nextcloud apk app, there are no problem. 

### unExpected behaviour
- sporadic screen of crash log app from nextcloud, without I use the app. 
-sporadic unlock screen with password , without start the app initially, with a infinity loop, however I put the good password. (I have to lock my phone  to exit the loop) 

### Environment data
Android version: 9

Device model:  P20 pro Huawei 

Stock or customized system: Stock 

Nextcloud app version: 3.12.rc1

Nextcloud server version: 16

Reverse proxy: Letsencrypt 

### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-uak5D_IOAOy03572N1a9gQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-uak5D_IOAOy03572N1a9gQ==/lib/arm64, /data/app/com.nextcloud.client-uak5D_IOAOy03572N1a9gQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWCLT
Model: CLT-L29
Id: HUAWEICLT-L29
Product: CLT-L29

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.372C33

**Comment by tobiasKaminsky** [comment] 2020-05-20 15:03
Duplicate of #4586

**Closed by tobiasKaminsky** 2020-05-20 15:03 UTC
Labels: bug
