### ISSUE TITLE
Collabora: edit problem with number

### ISSUE THREAD

**Issue by zedpro** [nextcloud/android#4718] opened 2019-10-22 14:04 UTC
### Actual behaviour
While I edit a document (.odt) when I insert a number (from 0 to 9), previous character is repeated. For example: I digit ab4c  => result is ab4bc
I have this problem with LG K8
My customer has the same problem with a diffent device (sansung s9)

### Expected behaviour
ab4c => ab4c
 
### Steps to reproduce
1. open a document .odt
2. edit document
3. digit ab4c

### Environment data
Android version: 6.0

Device model: LG K8

Stock or customized system:

Nextcloud app version: 3.8.1

Nextcloud server version: 16.0.5

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2019-10-23 08:19
@tobiasKaminsky this sounds like a server side collabora issue6

**Comment by zedpro** [comment] 2019-10-23 08:34
It could be...
This doens't happen in nextcloud web (with firefox or chrome)

**Comment by Bubu** [comment] 2019-11-04 12:38
I can confirm this Problem as well, like https://github.com/nextcloud/android/issues/3980 it seems to be related to AOSP keyboard. (I can always reproduce this on phones running Lineage with AOSP keyboard but just tried with a 'normal' Android phone with GBoard and had no problem there.)

**Comment by tobiasKaminsky** [comment] 2019-11-06 13:10
Thanks for linking the upstream bug, @Bubu.
So I close this here, as we cannot do anything on our side.

**Closed by tobiasKaminsky** 2019-11-06 13:10 UTC
Labels: bug
