### ISSUE TITLE
"Monitor files for changes" permanent notification !

### ISSUE THREAD

**Issue by vincegre** [nextcloud/android#2112] opened 2018-02-07 06:25 UTC
### Actual behaviour
-Tell us what happens

After last update of app, I have now permanently in notification drawer of my phone a notification from the app stating this:
"monitor files for changes"
Notification can't be removed and comes back each time I reboot phone !

### Expected behaviour
-Tell us what should happen

It should be possible to remove it and/op option in app to display or not that boring notification
 
### Steps to reproduce
1. Use version 20180201

### Environment data
Android version: Oreo 8.0.0

Device model: One Plus 3

Stock or customized system: stock rom

Nextcloud app version: 20180201

Nextcloud server version: 12.0.5

Thanks

Vincèn

**Comment by AndyScherzinger** [comment] 2018-02-07 06:36
Duplicate of #2083

Hi @vincegre, please check within the apps settings dialog for a new dev version since this has been fixed. Except when running Android 8 and making use of the available offline feature.

**Closed by AndyScherzinger** 2018-02-07 06:36 UTC
