### ISSUE TITLE
When creating existing directory during loading app crashes

### ISSUE THREAD

**Issue by willem640** [nextcloud/android#1934] opened 2018-01-08 19:40 UTC
### Actual behaviour
When you create an existing directory while the app is not yet showing the files, it crashes

### Expected behaviour
Message box: folder already exists or so
 
### Steps to reproduce
1. Close the app completely
2. Open it
3. While loading, press create directory
4. It will crash

### Environment data
Android version:
7.0
Device model: 
Huawei Honor 6X (europe)
Stock or customized system:
Stock EMUI 5
Nextcloud app version:
2.0.0
Nextcloud server version:
11
#### Web server error log
```
I do not have access to the log
```

#### Nextcloud log (data/nextcloud.log)
```
No access to logs
```
I am sorry that I could not post the webserver errors, but I think it is an issue in the app, so it wouldn't matter anyway

**Comment by tobiasKaminsky** [comment] 2018-01-09 07:48
I cannot reproduce it:
- set emulator to very poor internet connection
- created a folder with 5000 images to have a very long loading folder
- entered the folder for the very first time, so really all data needs to be fetched
- meanwhile I created a folder
- while still waiting for folder listing to show up, folder was already shown on user UI

Tested with latest master and NC13.
If you can give us some kind of app debugging (https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat), then we can try to figure it out, otherwise closing it for now as it works as intended.

**Closed by tobiasKaminsky** 2018-01-09 07:48 UTC
Labels: bug

**Comment by willem640** [comment] 2018-01-09 16:20
I cannot reproduce it too, so leave it closed
