### ISSUE TITLE
error window poping up

### ISSUE THREAD

**Issue by fernandoc2021** [nextcloud/android#7142] opened 2020-10-26 14:14 UTC
### Steps to reproduce
1. just pops up

### Expected behaviour
- Tell us what should happen: Not aware of any

### Actual behaviour
- Tell us what happens: Just the pop up warning

### Can you reproduce this problem on https://try.nextcloud.com?
no

### Environment data

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.AnalyticsConnector
... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWVOG
Model: VOG-L04
Id: HUAWEIVOG-L04
Product: VOG-L04

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.1.0.151C605
 

Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-10-26 18:50
Duplicate of #4675

**Comment by AndyScherzinger** [comment] 2020-10-26 18:50
Fix will roll out with upcoming feature release 3.14.0

**Closed by AndyScherzinger** 2020-10-26 18:50 UTC
Labels: bug
