### ISSUE TITLE
Notifications are broken on Play Store version

### ISSUE THREAD

**Issue by iniOr** [nextcloud/android#10381] opened 2022-06-13 13:10 UTC
### Steps to reproduce
1. Install latest Nextcloud version from Google Play Store
2. Get a notification from server

### Expected behaviour
- Content of the notification should be readable

### Actual behaviour
- Notification is the following text : `NEW_NOTIFICATION`

### Environment data
Android version: 12

Device model: Samsung Galaxy S21+

Stock or customized system: Stock

Nextcloud app version: 3.20.2

Nextcloud server version: 23.0.5

Reverse proxy: none

![image](https://user-images.githubusercontent.com/43171930/173361703-9a9e7756-b733-46a9-b284-bda8bd3791c4.png)

**Comment by AlvaroBrey** [comment] 2022-06-13 13:22
Duplicate of #1964

**Closed as not planned by AlvaroBrey** 2022-06-13 13:22 UTC
Labels: bug

**Comment by iniOr** [comment] 2022-06-13 13:36
Why making a search of open issues with the exact term "notifcation" does not give #1964 as result ?

This is a bug that came with the latest version of the app on the G appstore, my server nor its setup had changed only the Android app have.
