### ISSUE TITLE
Graphic bug on upload screen when folder is empty

### ISSUE THREAD

**Issue by Apodasch** [nextcloud/android#10756] opened 2022-09-23 05:37 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Share picture or file from another application
2. You get to the "Upload" screen of the Nextcloud application - destination folder should be picked and then Upload button in the bottom should be pressed.
3. If you browse to empty folder or creqte a new folder for your new files, folder content list is not refreshed, so you think you stayed in the parrent folder.

### Expected behaviour

When you select empty folder as a upload destination, the content list should refresh so that you see the folder you have selected is empty. 

### Actual behaviour

Now only the folder name in the very top is changing but the content list remains from the parrent folder - graphic bug.
In my case I pick folder "Shared", then folder "Test" but the test folder content is not refreshed so it looks I stayed in the same folder.

(Other folder names were deleted from the screenshots because of privacy)

![IMG_20220923_072752](https://user-images.githubusercontent.com/69112899/191897272-b8b9784a-19b1-441c-a9d4-541fb5f12283.jpg)

![IMG_20220923_071720](https://user-images.githubusercontent.com/69112899/191897302-81beb680-d9cf-48eb-941e-dce747062ca5.jpg)

### Android version

11

### Device brand and model

Xiaomi Mi 9 SE

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.2

### Nextcloud server version

FileRun server used - unknown version

### Using a reverse proxy?

I don't know

**Comment by AlvaroBrey** [comment] 2022-09-23 09:33
Duplicate of #10728

**Closed by AlvaroBrey** 2022-09-23 09:33 UTC
Labels: bug
