### ISSUE TITLE
Mobile App crashed on file share/upload

### ISSUE THREAD

**Issue by Link2hossam** [nextcloud/android#14197] opened 2024-12-17 20:51 UTC
### Cause of error
```java
Exception in thread "Thread-4" java.lang.IllegalArgumentException: Trying to execute a sync operation with a storage manager for an anonymous account
    at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:49)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$fetchExternalLinks$9(DrawerActivity.java:1231)
    at com.owncloud.android.ui.activity.DrawerActivity.$r8$lambda$oHM2j1MZkviAIdyIFWoI2kSeF9c(Unknown Source:0)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `e3q`
* Model: `SM-S928B`
* Id: `UP1A.231005.007`
* Product: `e3qxxx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S928BXXU4AXK4`

**Comment by blueskyfeeling** [comment] 2024-12-28 14:12
NC 30.0.4
Apache2
PHP 8.3.12
Nextcloud App 3.30.6

Same issue at the moment with a Samsung Galaxy S20 FE and Android 13.  

When uploading via the gallery, not all files are uploaded. Once out of 15, 6, in a new attempt only 4...very unreliable and therefore this method is unusable.

**Comment by joshtrichards** [comment] 2024-12-28 14:58
Duplicate of #13323

**Closed by joshtrichards** 2024-12-28 14:58 UTC
Labels: 0. Needs triage
