### ISSUE TITLE
Huawei p30 work profile - crash

### ISSUE THREAD

**Issue by fabiomercuri** [nextcloud/android#4931] opened 2019-12-03 22:44 UTC
### Actual behaviour
- Tell us what happens
I have nextcloud app installed in my android work profile. I launch the app and I insert username and password. After looking for files in the Cloud, it crashes unexpectedly. 

### Expected behaviour
- Tell us what should happen
 It should get my files in the Cloud. 

### Steps to reproduce
1. Launch app
2. Get access by username and password
3. Wait for loading

### Environment data
Android version: 9 pie

Device model: huawei p30

Stock or customized system:

Nextcloud app version: 3.9.0

Nextcloud server version: 

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@2411b77
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1546)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=3451, uid=1010340 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1953)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3897)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1556)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1415)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1533)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:24004)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:183)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3654)
	at com.android.server.am.HwActivityManagerService.onTransact(HwActivityManagerService.java:609)
	at android.os.Binder.execTransact(Binder.java:739)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWELE
Model: ELE-L29
Id: HUAWEIELE-L29
Product: ELE-L29EEA

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.240C431

**Comment by tobiasKaminsky** [comment] 2019-12-04 10:57
Duplicate of #4661

**Closed by tobiasKaminsky** 2019-12-04 10:57 UTC
Labels: bug

**Comment by AndyScherzinger** [comment] 2020-10-12 15:34
Duplicate of #6654
