### ISSUE TITLE
get error via notification ....

### ISSUE THREAD

**Issue by EricThi** [nextcloud/android#7028] opened 2020-09-29 04:44 UTC
### Steps to reproduce
1. Clic on notifcation nextcloud or nextcloud talk (to back on conversation)
2. change app to nextcloud or nextcloud talk
3. keep nextcloud or nextcloud talk on background (and get notification, no sé)

### Expected behaviour
- Tell us what should happen

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-6UhyMcFuqYDowf17URo2Dw==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-6UhyMcFuqYDowf17URo2Dw==/lib/arm, /data/app/com.nextcloud.client-6UhyMcFuqYDowf17URo2Dw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a3xeltexx
Model: SM-A310F
Id: PQ3A.190801.002
Product: lineage_a3xelte

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.root.20200813.232152 

Stock or customized system: System e.foundation

Nextcloud server version: 19.0.3

Reverse proxy: Nginx

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-09-29 09:44
Duplicate of #4675

**Closed by AndyScherzinger** 2020-09-29 09:44 UTC
Labels: bug
