### ISSUE TITLE
Crashing in background 1 h after uploading some data from mobile

### ISSUE THREAD

**Issue by WeirdCircumstances** [nextcloud/android#10695] opened 2022-09-01 11:04 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Uploaded some data
Wait for about 1 h
Got crash screen

### Expected behaviour

no crash

### Actual behaviour

Crash

### Android version

12

### Device brand and model

Google Pixel 3 XL

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.1

### Nextcloud server version

24.0.4

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "Thread-4" android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.nextcloud.client/com.owncloud.android.files.services.FileUploader
    at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
    at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
    at android.os.Parcel.readParcelable(Parcel.java:3333)
    at android.os.Parcel.createExceptionOrNull(Parcel.java:2420)
    at android.os.Parcel.createException(Parcel.java:2409)
    at android.os.Parcel.readException(Parcel.java:2392)
    at android.os.Parcel.readException(Parcel.java:2334)
    at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:5971)
    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1847)
    at android.app.ContextImpl.startForegroundService(ContextImpl.java:1823)
    at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:779)
    at com.owncloud.android.files.services.FileUploader.retryUpload(FileUploader.java:1051)
    at com.owncloud.android.files.services.FileUploader.retryFailedUploads(FileUploader.java:1095)
    at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:240)
    at com.owncloud.android.utils.FilesSyncHelper$$ExternalSyntheticLambda0.run(Unknown Source:10)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210190`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `crosshatch`
* Model: `Pixel 3 XL`
* Id: `SP1A.210812.016.C2`
* Product: `crosshatch`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `8618562`

**Comment by AlvaroBrey** [comment] 2022-09-01 11:46
Duplicate of #10692

**Closed by AlvaroBrey** 2022-09-01 11:46 UTC
Labels: bug
