### ISSUE TITLE
nextcloud always stopping when upload on android apps

### ISSUE THREAD

**Issue by eatmaja** [nextcloud/android#6642] opened 2020-08-04 14:57 UTC
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.AnalyticsConnector
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gta3xl
Model: SM-T515
Id: QP1A.190711.020
Product: gta3xlxx

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: T515XXU4BTFK

**Comment by tobiasKaminsky** [comment] 2020-08-05 06:20
Duplicate of #4675

**Closed** 2020-08-05 13:52 UTC
Labels: bug
