### ISSUE TITLE
Error message appeares out of nowhere

### ISSUE THREAD

**Issue by mipla23** [nextcloud/android#7136] opened 2020-10-24 20:58 UTC
### Steps to reproduce
1. Error message appears randomly about 5-10 times a day
Everytime the App isn't running at all.

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-DWCQwqoDlvVatcP9KDz2Aw==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-DWCQwqoDlvVatcP9KDz2Aw==/lib/arm64, /data/app/com.nextcloud.client-DWCQwqoDlvVatcP9KDz2Aw==/base.apk!/lib/arm64-v8a, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: d2x
Model: SM-N976B
Id: *removed*
Product: d2xxx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: *removed*

2. After dismissing the error message nothing happens
3. Nextcloud App and Server seems both to be working fine.
4. Still happens after server upgrade from 19.0.3 to 19.0.4

### Expected behaviour
- This message shouldn't appear

### Actual behaviour
- The message does appear

### Can you reproduce this problem on https://try.nextcloud.com?
- not working, as this problem occours in android

### Environment data
Android version:
9
Device model: 
SM-N976B
Stock or customized system:
Stock
Nextcloud app version:
3.13.1
Nextcloud server version:
19.0.3
Reverse proxy:
Apache2

**Comment by AndyScherzinger** [comment] 2020-10-24 23:48
Duplicate of #4675

**Comment by AndyScherzinger** [comment] 2020-10-24 23:48
Fix will roll out with upcoming feature release 3.14.0

**Closed by AndyScherzinger** 2020-10-24 23:48 UTC
Labels: bug
