### ISSUE TITLE
Import/Export Settings File

### ISSUE THREAD

**Issue by trymeouteh** [nextcloud/android#5521] opened 2020-02-25 20:42 UTC
I think the desktop clients need to have a import/export settings file which can be saved in a unencrypted or encrypted format. This settings file will save the settings and auto upload folders.

The reason I think this is needed is for when one wants to go though border security such as at an airport. One can easily export their settings to the cloud or on their phone. Logout of Nextcloud, uninstall Nextcloud app, go through security and then install Nextcloud app, login and import the settings and have Nextcloud setup the same way it was before.

This will make it easy to setup Nextcloud again once your passed security. And is a useful feature to protects ones privacy.

**Comment by strugee** [comment] 2020-02-27 07:30
I wonder if it would make sense to automatically save settings to the cloud and then offer to restore them when signing in again. That would provide a nice experience for new devices too - although maybe the settings in the app are too device-specific for that to make sense?

**Comment by trymeouteh** [comment] 2020-02-27 18:34
> I wonder if it would make sense to automatically save settings to the cloud and then offer to restore them when signing in again. That would provide a nice experience for new devices too - although maybe the settings in the app are too device-specific for that to make sense?

Not a bad idea, this will need to work for all clients, (Windows, Mac, Linux, Android & iOS). And have the ability to export multiple settings even for the same OS. If you have two Android phones Nextcould will need to be able to save multiple Android settings exports.

I think a file is better so the user can choose were to store the file and manage it better.

**Comment by markus2330** [comment] 2020-07-17 14:39
Elektra https://www.libelektra.org is a library for configuration which supports encryption of configuration settings using gpg. Furthermore, it also supports import/export in any of its supported configuration file formats.

Elektra's goal is to avoid that every application needs to reinvent how configuration works and features like requested in this issue can be implemented in one place (and not in every application). The encryption features alone took several months of implementation effort. Unfortunately, it is not yet 1.0.0, so API might still change a bit.

**Comment by trymeouteh** [comment] 2021-07-22 16:42
https://github.com/nextcloud/desktop/issues/1814

**Comment by sstefanov** [comment] 2021-09-16 06:55
For android client also will be very useful to export/import settings in some file, locally or on the cloud.

**Comment by PascalHeynmoeller** [comment] 2023-01-27 11:45
This would be an solution for changed host or domain / generally server names or also urls!

**Comment by joshtrichards** [comment] 2023-10-15 14:40
Duplicate of #11090 

Let's consolidate this into #11090 which seems to be where most of the voting is happening on this topic.

**Closed by joshtrichards** 2023-10-15 14:40 UTC
Labels: enhancement
