### ISSUE TITLE
Große Ordner mit Fotos stürzt in Nextcloud-App ab

### ISSUE THREAD

**Issue by Christina6565** [nextcloud/android#6688] opened 2020-08-10 21:27 UTC
### Steps to reproduce
1. 
### Expected behaviour
Ordner öffnen, Unterordner auflisten und bei Öffnen des jeweiligen Unterordners Fotos anzeigen

### Actual behaviour
Direkt bei Öffnen eine großen Ordners mit Fotos stürzt die nextcloud App auf dem Handy ab. Alle anderen Ordner lassen sich problemlos nutzen.

Bei Zugriff über Internet funktioniert alles einwandfrei. 

Folgende Fehlermeldung erscheint

************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=10, totalRows=11
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:986)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:858)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:161)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:131)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:249)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:281)
	at android.database.CursorWrapper.moveToNext(CursorWrapper.java:206)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:878)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:156)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:817)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1252)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1197)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:949)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.lambda$onBindViewHolder$1$OCFileListAdapter(OCFileListAdapter.java:383)
	at com.owncloud.android.ui.adapter.-$$Lambda$OCFileListAdapter$pouWgEOOHT1aDFHaHM0Ifm3xWtY.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7213)
	at android.view.View.performClickInternal(View.java:7187)
	at android.view.View.access$3500(View.java:828)
	at android.view.View$PerformClick.run(View.java:27675)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8347)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWVOG
Model: VOG-L29
Id: HUAWEIVOG-L29
Product: VOG-L29EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.1.0.140C431

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: 

Stock or customized system:

Nextcloud app version: 3.12.1

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by jakobroehrl** [comment] 2020-08-18 11:40
duplicate of https://github.com/nextcloud/android/issues/6436 ?

**Comment by AndyScherzinger** [comment] 2020-08-18 13:48
@jakobroehrl yes, while I closed the other ticket (due to lack of infos like a stacktrace) in favor of this one.

**Comment by johnwmail** [comment] 2020-09-25 12:05
Can you please roll back to previous version?

**Comment by johnwmail** [comment] 2020-10-18 03:29
So, it seems a well known bug(s), is there any workaround?
I still cannot access my nextcloud on my android phone.
Please help, thanks.

**Comment by tobiasKaminsky** [comment] 2020-10-19 07:36
No workaround I can think of, sorry.
It is also problematic to fix this, as it is not reproducable on any of my test devices…

**Comment by szaimen** [comment] 2020-10-19 11:50
Maybe it is good to know how many files are in the effected folder?

**Comment by johnwmail** [comment] 2020-10-20 06:33
Hi, how to erase all settings/files/anything for nextcloud on android?
I removed the app(NC on android), and re-install it, but it seems remember my settings(eg: autoupload)..
I want completely remove the NC android app and settings, then re-try it....
because I re-installed the server today, and the result is same (crash)

**Comment by borispetkov** [comment] 2020-11-19 07:58
One thing I noted for my crash on #7362 was that I had the external storage set by the admin user and with a user group access. When I was accessing it from the phone logged as admin, it was working fine. When I was logged as one of the users from that group, it was crashing.

**Comment by ok2zar** [comment] 2020-12-19 22:43
Does exist a way how fix the issue? Split folder content into subfolders with 1000 files should be workarround but it expects manual change on phone file-system and then let it synchronize to server.

**Comment by Jigsaw5279** [comment] 2021-02-15 14:27
Looking at the code, the issue seems to be that too many rows are retrieved for recursive folder deletion while syncing with the server instance, right?

https://github.com/nextcloud/android/blob/d6d8435b964a37661e3a7fdf88afbb1e7c4bb6bd/src/main/java/com/owncloud/android/providers/FileContentProvider.java#L170-L203

Could this be mitigated by limiting the amount of rows returned and running the delete until no more rows are returned?

I'd love to PR this, but I have no idea how to test it..

**Comment by tobiasKaminsky** [comment] 2021-02-17 12:21
> I'd love to PR this, but I have no idea how to test it..

It would be awesome if you do the PR, I can then try to create some tests

**Comment by viba1** [comment] 2021-04-19 07:41
Duplicate of https://github.com/nextcloud/android/issues/8231 ; https://github.com/nextcloud/android/issues/8231 and  https://github.com/nextcloud/android/issues/8293 ?

Lot of people seems encounter this issue.

**Comment by mpfz0r** [comment] 2021-11-02 15:00
+1
seeing this as well. currently the app is not usable to me.
Let me know if you need any more infos to debug this.

**Comment by AlvaroBrey** [comment] 2021-11-23 11:58
Closing this in favor of #5926 , which this is a duplicate of. All tracking will be done there.

**Comment by AlvaroBrey** [comment] 2021-11-23 11:58
Duplicate of #5926

**Closed by AlvaroBrey** 2021-11-23 11:58 UTC
Labels: bug, approved
