### ISSUE TITLE
Samsug gallery app creates dummy photos every time nextcloud uploads a photo.

### ISSUE THREAD

**Issue by DrekiDegga** [nextcloud/android#6754] opened 2020-08-19 22:51 UTC
### Steps to reproduce
1. Upload a photo to a nextcloud server via the nextcloud android app using either auto-upload or manual.
2. 
3. 

### Expected behaviour
- The photo uploads
### Actual behaviour
- The photo uploads but a blank dummy photo appears in the samsung gallery app that eventually deletes itself or can be deleted manually.

### Can you reproduce this problem on https://try.nextcloud.com?
- I didn't try but it only happens on the one phone.
### Environment data
Android version:
10
Device model: 
Samsung galaxy s10+
Stock or customized system:
Stock
Nextcloud app version:
3.12.1
Nextcloud server version:
18.0.7

**Comment by tobiasKaminsky** [comment] 2020-08-20 08:01
Can you give us some details on this dummy photo? Storage path, etc?

**Comment by DrekiDegga** [comment] 2020-08-20 17:10
![20200819_183925](https://user-images.githubusercontent.com/47491036/90803128-4ec35100-e2e6-11ea-82b4-37fb03cc460a.jpg)

There is no information given by the Samsung app except the filename, which matches the uploaded file name, and the size which is always 0kb

**Comment by invario** [comment] 2020-08-21 02:10
This was reported here recently:
https://github.com/nextcloud/android/issues/6558

**Comment by invario** [comment] 2020-08-21 02:11
Duplicate of #6558

**Comment by tobiasKaminsky** [comment] 2020-08-21 06:17
Normally you could also click on such 0kb picture and choose "details" to see the file location. That would be interesting.

**Comment by DrekiDegga** [comment] 2020-08-25 15:50
I did click on details but it only shows the file name and size, not the path.

**Comment by tobiasKaminsky** [comment] 2020-08-26 08:53
Without knowing where this file is, and how it is related to NC, I cannot help :-(

**Comment by Natalcia** [comment] 2020-08-26 09:57
On my phone it always shows /storage/emulated/0/Pictures/<correct original filename> on ghost file even when during uploading file was in different directory. I have checked logcat and there are no errors too. Really weird and annoying issue. I'm on LineageOS though, not Samsung. All galleries that I have used, so: AOSP gallery, LineageOS gallery and Sony Album are showing these ghost files. 
In gallery these files are at bottom of list because of it's date being beggining of unix epoch so it's not that annoying when we browse gallery. Worse thing is when we for example use Discord which in it's uploading gallery prioritizes when file showed in media storage and not it's fake creation date.

**Comment by invario** [comment] 2020-08-26 12:50
> Without knowing where this file is, and how it is related to NC, I cannot help :-(



> Without knowing where this file is, and how it is related to NC, I cannot help :-(

This is the exact same issue I mentioned above and in the other thread I post detailed photos and information

https://github.com/nextcloud/android/issues/6558

**Comment by tobiasKaminsky** [comment] 2020-08-27 05:29
Then let us close this in favor of #6558

**Closed by tobiasKaminsky** 2020-08-27 05:29 UTC
Labels: bug, needs info/discussion
