### ISSUE TITLE
Cannot select a search result while search is still processing

### ISSUE THREAD

**Issue by TtuxX** [nextcloud/android#11539] opened 2023-04-19 13:17 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

On my android phone: 

1. I launch Nextcloud app
2. I type a music name in the search bar
3. Search starts 
4. First results appear while search is still going on
5. I try to click on the music that was found
6. Nothing happens and search still goes on
7. At the end of the search process, I can finally click any of the displayed results and it works

### Expected behaviour

1. I launch Nextcloud app
2. I type a music name in the search bar
3. Search starts 
4. First results appear while search is still going on
5. I try to click on the music that was found
6. Search interrupts and brings me to the selected file's parent folder OR music is opened on click, directly from the search page

### Actual behaviour

It appears to be impossible to open any file that is displayed as a search result as long as the search process is not over.

### Android version

11

### Device brand and model

Samsung Galaxy A20e

### Stock or custom OS?

Stock

### Nextcloud android app version

Nextcloud Dev version 20230414 + Nextcloud vesion 3.24.1

### Nextcloud server version

Nextcloud 25.0.5

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment] 2023-10-19 16:40
Duplicate of #11170 

Let's consolidate tracking for this there. Feel free to subscribe/upvote there. Thanks for contributing!

**Closed by joshtrichards** 2023-10-19 16:40 UTC
Labels: bug, feature: search

**Comment by TtuxX** [comment] 2023-10-19 20:50
Ooops, thank you very much and sorry for the duplicate !! :x
