### ISSUE TITLE
Share multiple files with other apps

### ISSUE THREAD

**Issue by johnnyasantoss** [nextcloud/android#7977] opened 2021-02-13 22:00 UTC
### Is your feature request related to a problem? Please describe.
It's expected that when you select multiple files you should be able to share them to whatever else application that you want to, but this isn't true for this app.

### Describe the solution you'd like
Select multiple files and share them with any other app. It shouldn't matter whether the file is downloaded or not. In the case that the file is missing it should show a progress bar of some kind in a modal representing the download of the missing files out of the selected ones. After downloading or if the files were already synced then it should open the default android sharing activity.

### Describe alternatives you've considered
Sharing one-by-one, but that has limitations and its just expected this to work as described above.

### Additional context
![20210125_080246](https://user-images.githubusercontent.com/14189387/107862737-85110180-6e2d-11eb-8b31-56299eef6852.png)
![20210125_080455](https://user-images.githubusercontent.com/14189387/107862738-86422e80-6e2d-11eb-8db7-ce5c0f21a870.png)

**Comment by major-mayer** [comment] 2021-12-25 09:45
I would also like to know what is the status on this.
Sharing files over via other (messenger) apps is very complicated without this possibility.

**Comment by thorgrin** [comment] 2022-12-15 08:23
I'd also be interested in this feature. I'm used to sharing an ad-hoc set of photos in the Google app and i miss this feature in Nextcloud.

**Comment by joshtrichards** [comment] 2023-10-11 15:03
Duplicate of #677

**Closed** 2023-10-11 15:04 UTC
Labels: enhancement
