### ISSUE TITLE
Make User info editable

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#642] opened 2017-02-09 20:04 UTC
Just had a nice chat with @AndyScherzinger and we came up with the idea that the user info should be editable in the app, so that the new values are stored on the server.

**Comment by mario** [comment] 2017-02-09 20:04
That's all good, but maybe for one of the future versions. :)

**Comment by tobiasKaminsky** [comment] 2017-02-09 20:05
Of course. Just as a reminder that we do not forget it :)

**Comment by AndyScherzinger** [comment] 2017-02-09 21:13
👍

**Comment by szaimen** [comment] 2021-05-20 09:41
Duplicate of #1925

**Closed by szaimen** 2021-05-20 09:41 UTC
Labels: approved, enhancement
