### ISSUE TITLE
Fingerprint unlocking crashing app on startup

### ISSUE THREAD

**Issue by SuperSandro2000** [nextcloud/android#2688] opened 2018-06-05 23:17 UTC
### Actual behaviour
App crashes. Log attached.

### Expected behaviour
 Unlock the app with fingerprint

### Steps to reproduce
1. Activate fingerprint unlocking
2. Close app
3. Reopen app

### Environment data
Android version: 8.0.0

Device model: SM-G950F (Galaxy S7)

Stock or customized system: Renovate Ice ROM (modified stock TouchWiz ROM)

Nextcloud app version: 3.2.0 RC2

Nextcloud server version: 13.0.2 Docker image

#### Web server error log
Does not apply.
#### Nextcloud log (data/nextcloud.log)
Can't find it.
Android logcat instead
[2018-06-06-01-09-00.txt](https://github.com/nextcloud/android/files/2074301/2018-06-06-01-09-00.txt)

**Comment by AndyScherzinger** [comment] 2018-06-06 11:11
```java.lang.RuntimeException: 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3788)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3828)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3036)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1696)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6938)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
Caused by: java.security.ProviderException: 
  at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey (AndroidKeyStoreKeyGeneratorSpi.java:322)
  at javax.crypto.KeyGenerator.generateKey (KeyGenerator.java:604)
  at com.owncloud.android.ui.activity.FingerprintActivity.generateKey (FingerprintActivity.java:203)
  at com.owncloud.android.ui.activity.FingerprintActivity.startFingerprint (FingerprintActivity.java:118)
  at com.owncloud.android.ui.activity.FingerprintActivity.onResume (FingerprintActivity.java:158)
  at android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1361)
  at android.app.Activity.performResume (Activity.java:7344)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3763)
Caused by: android.security.KeyStoreException: 
  at android.security.KeyStore.getKeyStoreException (KeyStore.java:1112)
  at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey (AndroidKeyStoreKeyGeneratorSpi.java:323)
```

**Comment by AndyScherzinger** [comment] 2018-06-06 11:12
Hopefully to be fixed via #1657 which unfortunately won't make it into the next release :(

**Comment by SuperSandro2000** [comment] 2018-06-06 11:56
Great to hear that! I subscribed to the PR and look when it gets merged in some Alpha/Beta build and test it then again.

**Comment by AndyScherzinger** [comment] 2018-06-06 12:06
Thanks @SuperSandro2000

**Comment by SuperSandro2000** [comment] 2018-07-04 17:28
Can confirm that the crash is fixed in the latest update and as far as I tested it out works like a charm! Thanks for the fix.

**Closed** 2018-07-04 17:28 UTC
Labels: bug, pr exists

**Comment by AndyScherzinger** [comment] 2018-07-04 18:45
Thanks for the feedback :heart:

**Comment by zgulser** [comment] 2019-09-25 14:49
I receive exactly the same error but it's very rare. So, I can't reproduce it. I've checked the commits but seems like a fix to me. Were you able to find the root cause for this bug?
