### ISSUE TITLE
Unknown sync error

### ISSUE THREAD

**Issue by lapers** [nextcloud/android#14212] opened 2024-12-21 00:55 UTC
### Cause of error
```java
Exception in thread "Syncfolder thread" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getEtag()' on a null object reference
    at com.owncloud.android.operations.SynchronizeFolderOperation.checkForChanges(SynchronizeFolderOperation.java:172)
    at com.owncloud.android.operations.SynchronizeFolderOperation.run(SynchronizeFolderOperation.java:131)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
    at com.owncloud.android.services.SyncFolderHandler.doOperation(SyncFolderHandler.java:106)
    at com.owncloud.android.services.SyncFolderHandler.handleMessage(SyncFolderHandler.java:79)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.os.HandlerThread.run(HandlerThread.java:67)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300690`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `g0s`
* Model: `SM-S906B`
* Id: `UP1A.231005.007`
* Product: `g0sxxx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S906BXXUDEXK5`

**Comment by joshtrichards** [comment] 2024-12-28 15:12
Duplicate of  #13784

**Closed by joshtrichards** 2024-12-28 15:12 UTC
