### ISSUE TITLE
Program Nextcloud crashed

### ISSUE THREAD

**Issue by khartahk** [nextcloud/android#7217] opened 2020-11-03 07:42 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{99e800d u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1946)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Nokia
Device: PNX_sprout
Model: Nokia 8.1
Id: QKQ1.190828.002
Product: Phoenix_00WW

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 00WW_4_30J

**Comment by AndyScherzinger** [comment] 2020-11-03 08:14
Duplicate of #6905

**Closed by AndyScherzinger** 2020-11-03 08:14 UTC
