### ISSUE TITLE
Nextcloud App Crashes

### ISSUE THREAD

**Issue by IsaacDLS** [nextcloud/android#8902] opened 2021-08-26 15:47 UTC
### Steps to reproduce
1. Clicking the hamburger button 
2. 
3. 

### Expected behaviour
- Clicking the hamburger button should open option menu.

### Actual behaviour
- The app crashes

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: POCO
Device: vayu
Model: M2102J20SG
Id: RKQ1.200826.002
Product: vayu_global

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: V12.5.3.0.RJUMIXM

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Canvas: trying to draw too large(106328180bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:1018)
	at android.widget.ImageView.onDraw(ImageView.java:1436)
	at android.view.View.draw(View.java:22505)
	at android.view.View.updateDisplayListIfDirty(View.java:21367)
	at android.view.View.draw(View.java:22229)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
	at android.view.View.draw(View.java:22509)
	at android.view.View.updateDisplayListIfDirty(View.java:21367)
	at android.view.View.draw(View.java:22229)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
	at android.view.View.updateDisplayListIfDirty(View.java:21358)
	at android.view.View.draw(View.java:22229)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
	at android.view.View.draw(View.java:22509)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
	at android.view.View.updateDisplayListIfDirty(View.java:21367)
	at android.view.View.draw(View.java:22229)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
	at android.view.View.draw(View.java:22509)
	at com.google.android.material.internal.ScrimInsetsFrameLayout.draw(ScrimInsetsFrameLayout.java:109)
	at android.view.View.updateDisplayListIfDirty(View.java:21367)
	at android.view.View.draw(View.java:22229)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
	at android.view.View.draw(View.java:22509)
	at android.view.View.updateDisplayListIfDirty(View.java:21367)
	at android.view.View.draw(View.java:22229)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
	at android.view.View.updateDisplayListIfDirty(View.java:21358)
	at android.view.View.draw(View.java:22229)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
	at android.view.View.updateDisplayListIfDirty(View.java:21358)
	at android.view.View.draw(View.java:22229)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
	at android.view.View.updateDisplayListIfDirty(View.java:21358)
	at android.view.View.draw(View.java:22229)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
	at android.view.View.updateDisplayListIfDirty(View.java:21358)
	at android.view.View.draw(View.java:22229)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
	at android.view.View.draw(View.java:22509)
	at com.android.internal.policy.DecorView.draw(DecorView.java:819)
	at android.view.View.updateDisplayListIfDirty(View.java:21367)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:567)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:651)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4273)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3978)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3239)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2065)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8502)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1076)
	at android.view.Choreographer.doCallbacks(Choreographer.java:897)
	at android.view.Choreographer.doFrame(Choreographer.java:826)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8056)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2021-09-09 09:03
Duplicate of #8862

**Closed by AlvaroBrey** 2021-09-09 09:03 UTC
Labels: bug
