### ISSUE TITLE
Deleting file results in stacktrace

### ISSUE THREAD

**Issue by hugot** [nextcloud/android#10708] opened 2022-09-02 18:38 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Navigate to a picture stored in a nextcloud folder to delete
2. Open/view the picture by tapping it
3. Open the context menu via the three dots top-right of the screen
4. Tap "delete"

### Expected behaviour

The picture gets deleted and I am returned to its parent directory.

### Actual behaviour

Crash/stacktrace:
```
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.services.OperationsService$OperationsServiceBinder.isSynchronizing(OperationsService.java:372)
    at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:498)
    at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:487)
    at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:195)
    at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:127)
    at com.owncloud.android.ui.preview.PreviewImageFragment.onPrepareOptionsMenu(PreviewImageFragment.java:381)
    at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:3253)
    at androidx.fragment.app.FragmentManager.dispatchPrepareOptionsMenu(FragmentManager.java:3051)
    at androidx.fragment.app.FragmentManager$2.onPrepareMenu(FragmentManager.java:466)
    at androidx.core.view.MenuHostHelper.onPrepareMenu(MenuHostHelper.java:63)
    at androidx.activity.ComponentActivity.onPreparePanel(ComponentActivity.java:498)
    at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3148)
    at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1936)
    at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2190)
    at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:273)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
    at android.view.Choreographer.doCallbacks(Choreographer.java:791)
    at android.view.Choreographer.doFrame(Choreographer.java:722)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7386)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20220820`
* Build flavor: `versionDev`

### Device information
* Brand: `alps`
* Device: `k63v2_64_bsp`
* Model: `Volla Phone`
* Id: `QP1A.190711.020`
* Product: `full_k63v2_64_bsp`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `mp1V9135`
```

### Android version

10

### Device brand and model

Volla Phone

### Stock or custom OS?

Stock

### Nextcloud android app version

20220820

### Nextcloud server version

24.0.3

### Using a reverse proxy?

Yes

### Android logs

I have been able to reproduce this on multiple devices so I doubt you need my logs. If you really do need a log, please reach out and I will find time to figure out how to work with logcat.

### Server error logs

```bash
No logs available
```

### Additional information

It is the VollaPhone with Volla OS installed, not ubports.

**Comment by AlvaroBrey** [comment] 2022-09-03 15:07
Duplicate of #10580

**Closed by AlvaroBrey** 2022-09-03 15:07 UTC
Labels: bug
