### ISSUE TITLE
IllegalStateException on upload

### ISSUE THREAD

**Issue by Raymo111** [nextcloud/android#7793] opened 2021-01-08 05:23 UTC
### Steps to reproduce
1. Open the app
2. Tap the bottom right upload button

### Expected behaviour
- it should not crash

### Actual behaviour
- it crashed

Nextcloud server version: 20.0.4

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5131)
	at android.view.ViewGroup.addView(ViewGroup.java:4960)
	at android.view.ViewGroup.addView(ViewGroup.java:4900)
	at android.view.ViewGroup.addView(ViewGroup.java:4873)
	at com.owncloud.android.ui.fragment.OCFileListBottomSheetDialog.onCreate(OCFileListBottomSheetDialog.java:131)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:421)
	at android.app.Dialog.show(Dialog.java:315)
	at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$registerFabListener$2$OCFileListFragment(OCFileListFragment.java:442)
	at com.owncloud.android.ui.fragment.-$$Lambda$OCFileListFragment$aYkoWPoxzAOahKL5AVjT06NhcnM.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7201)
	at android.view.View.performClickInternal(View.java:7170)
	at android.view.View.access$3500(View.java:806)
	at android.view.View$PerformClick.run(View.java:27582)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140251
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7T
Model: HD1905
Id: 
Product: OnePlus7T

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2011052234

```

**Comment by tobiasKaminsky** [comment] 2021-01-14 06:38
Duplicate of #7796

**Closed by tobiasKaminsky** 2021-01-14 06:38 UTC
Labels: bug
