### ISSUE TITLE
Media view error

### ISSUE THREAD

**Issue by mebitek** [nextcloud/android#11203] opened 2022-12-26 09:02 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Open nextcloud
Enter media view

### Expected behaviour

View all media

### Actual behaviour

Nextcloud stucked then crash

### Android version

12

### Device brand and model

Xiaomi redmi note 9 pro joyeuse

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.23.1

### Nextcloud server version

25.0.2

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Couldn't read row 694, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetString(Native Method)
    at android.database.CursorWindow.getString(CursorWindow.java:462)
    at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:54)
    at android.database.CursorWrapper.getString(CursorWrapper.java:141)
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:968)
    at com.owncloud.android.datamodel.FileDataStorageManager.getGalleryItems(FileDataStorageManager.java:2241)
    at com.owncloud.android.datamodel.FileDataStorageManager.getAllGalleryItems(FileDataStorageManager.java:2186)
    at com.owncloud.android.ui.adapter.GalleryAdapter.showAllGalleryItems(GalleryAdapter.kt:168)
    at com.owncloud.android.ui.fragment.GalleryFragment.showAllGalleryItems(GalleryFragment.java:380)
    at com.owncloud.android.ui.fragment.GalleryFragment.handleSearchEvent(GalleryFragment.java:213)
    at com.owncloud.android.ui.fragment.GalleryFragment.onRefresh(GalleryFragment.java:183)
    at androidx.swiperefreshlayout.widget.SwipeRefreshLayout$1.onAnimationEnd(SwipeRefreshLayout.java:208)
    at androidx.swiperefreshlayout.widget.CircleImageView.onAnimationEnd(CircleImageView.java:121)
    at android.view.ViewGroup.finishAnimatingView(ViewGroup.java:7134)
    at android.view.View.draw(View.java:22613)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.draw(View.java:22707)
    at android.view.View.updateDisplayListIfDirty(View.java:21579)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.updateDisplayListIfDirty(View.java:21570)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.updateDisplayListIfDirty(View.java:21570)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.draw(View.java:22707)
    at android.view.View.updateDisplayListIfDirty(View.java:21579)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.updateDisplayListIfDirty(View.java:21570)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.draw(View.java:22707)
    at android.view.View.updateDisplayListIfDirty(View.java:21579)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.updateDisplayListIfDirty(View.java:21570)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.updateDisplayListIfDirty(View.java:21570)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.updateDisplayListIfDirty(View.java:21570)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.updateDisplayListIfDirty(View.java:21570)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.draw(View.java:22707)
    at com.android.internal.policy.DecorView.draw(DecorView.java:819)
    at android.view.View.updateDisplayListIfDirty(View.java:21579)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:4531)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4251)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3374)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8793)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
    at android.view.Choreographer.doCallbacks(Choreographer.java:845)
    at android.view.Choreographer.doFrame(Choreographer.java:780)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230190`
* Build flavor: `generic`

### Device information
* Brand: `Redmi`
* Device: `joyeuse`
* Model: `Redmi Note 9 Pro`
* Id: `SQ3A.220705.004`
* Product: `lineage_miatoll`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `eng.root.20221201.110719`

**Comment by AlvaroBrey** [comment] 2022-12-28 18:09
Duplicate of #9948

**Closed by AlvaroBrey** 2022-12-28 18:09 UTC
Labels: bug
