### ISSUE TITLE
App crashed while moving files

### ISSUE THREAD

**Issue by nerdyCamel** [nextcloud/android#6708] opened 2020-08-16 12:30 UTC
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 1134, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetString(Native Method)
	at android.database.CursorWindow.getString(CursorWindow.java:465)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
	at android.database.CursorWrapper.getString(CursorWrapper.java:137)
	at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:964)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:874)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:156)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:432)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:369)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:228)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:357)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus3
Model: ONEPLUS A3003
Id: PKQ1.181203.001
Product: OnePlus3

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1911042107

**Comment by tobiasKaminsky** [comment] 2020-08-28 09:49
Possible duplicate of #6436 
If not please re-open.

**Closed by tobiasKaminsky** 2020-08-28 09:49 UTC
Labels: bug

**Comment by nerdyCamel** [comment] 2020-08-31 19:01
It could be related. From a folder containing nearly 5000 files I was moving quantities of 10-100 files into sub-folders.
Side note: I'm still running Nextcloud 16. I'm planning to move my cloud to a new machine running the current version. I just don't know when I'll find the time to get it done, yet.
