### ISSUE TITLE
Multithreaded Uploads

### ISSUE THREAD

**Issue by OfficialMuffin** [nextcloud/android#11195] opened 2022-12-23 00:48 UTC
When uploading 500+ files it's annoyingly slow.
I would like to see some kind of multithreaded upload feature to be implemented e.g. client able to upload 4-5 files at a time. Same goes for the desktop clients as well.

**Comment by AlvaroBrey** [comment] 2022-12-23 08:36
Duplicate of #10124

**Closed by AlvaroBrey** 2022-12-23 08:36 UTC
Labels: enhancement
