### ISSUE TITLE
Opening PDF crashes Nextcloud-Android-App

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/android#7275] opened 2020-11-09 22:18 UTC
### Steps to reproduce
1. Open a PDF for the first time on your mobile
2. The App will crash
3. Try it again, it will open, 'cause now it has the green arrow (synchronized)

### Expected behaviour
Usually the PDF should open directly

### Actual behaviour
Android-Nextcloud-App crashes ...

### Environment data
Android version: 10

Device model: Note 10+

Stock or customized system: Stock / rooted

Nextcloud app version: 3.14.0 RC1

Nextcloud server version: 19.0.3

Reverse proxy: NGINX

**Comment by AndyScherzinger** [comment] 2020-11-09 22:23
Duplicate of #7188

**Comment by AndyScherzinger** [comment] 2020-11-09 22:24
Fix will ship with the upcoming second release candidate, thanks for the report, this is highly appreciated ❤️

**Closed by AndyScherzinger** 2020-11-09 22:23 UTC
Labels: bug

**Comment by kangaroo72** [comment] 2020-11-09 22:25
Thank you  @AndyScherzinger
