### ISSUE TITLE
Sharing to Nextcloud doesn't upload the file

### ISSUE THREAD

**Issue by natema** [nextcloud/android#7698] opened 2020-12-19 20:21 UTC
### Steps to reproduce
1. Select to share a pdf file from an app such as Telegram or the system's file manager
2. Select the Nextcloud app icon
3. Navigate to a Nextcloud folder and select `upload`

### Expected behaviour
- the file should appear in the selected Nextcloud folder

### Actual behaviour
- The file does not appear in the selected folder

### Environment data
Android version: 10

Device model: SM-T865

Stock or customized system: 

Nextcloud app version: 3.14.1

Nextcloud server version: 20.0.3

**Comment by subterfugium** [comment] 2020-12-19 22:31
Reproduced with oneplus 5T and Nokai 8.1

This might be related:
```
12-20 00:27:44.738 I/ActivityTaskManager( 1485): START u0 {act=android.intent.action.SEND typ=image/* flg=0xb080001 cmp=com.nextcloud.client/com.owncloud.android.ui.activity.ReceiveExternalFilesActivity clip={image/* U:content://media/external/images/media/114072} (has extras)} from uid 10040
12-20 00:27:44.747 I/DropBoxManagerService( 1485): add tag=system_server_strictmode isTagEnabled=true flags=0x2
12-20 00:27:44.751 W/ActivityThread(23814): handleWindowVisibility: no activity for token android.os.BinderProxy@a76ce6
12-20 00:27:44.764 D/ReceiveExternalFilesActivity(23814): onCreate(Bundle) starting
12-20 00:27:44.783 D/ImageWallpaper( 3184): wallpaper visibility changes to: true
12-20 00:27:44.790 D/ImageWallpaper( 3184): wallpaper visibility changes to: false
12-20 00:27:44.798 D/ReceiveExternalFilesActivity(23814): onStart() starting
12-20 00:27:44.767 I/chatty  ( 1485): uid=1000(system) android.io identical 7 lines
12-20 00:27:44.769 I/DropBoxManagerService( 1485): add tag=system_server_strictmode isTagEnabled=true flags=0x2
12-20 00:27:44.829 E/NotificationService( 1485): Suppressing notification from package by user request.
12-20 00:27:44.833 V/ArbitraryDataProvider(23814): Updating arbitrary data with cloud id: global key: APP_OPENED_COUNT value: 3
12-20 00:27:44.857 D/ReceiveExternalFilesActivity(23814): Populating view with content of : /oneplus5t/
12-20 00:27:44.956 D/ReceiveExternalFilesActivity(23814): onResume() starting
12-20 00:27:44.957 W/DrawerActivity(23814): setDrawerMenuItemChecked has been called with invalid menu-item-ID
12-20 00:27:44.960 D/OperationsService(23814): Creating service
12-20 00:27:44.994 D/FileActivity(23814): Operations service connected
12-20 00:27:44.999 I/ActivityTaskManager( 1485): Displayed com.nextcloud.client/com.owncloud.android.ui.activity.ReceiveExternalFilesActivity: +270ms
12-20 00:27:45.002 W/extcloud.clien(23814): Accessing hidden field Landroid/widget/TextView;->mCursorDrawableRes:I (greylist-max-p, reflection, denied)
12-20 00:27:45.002 W/extcloud.clien(23814): Accessing hidden field Landroid/widget/Editor;->mSelectHandleLeft:Landroid/graphics/drawable/Drawable; (greylist-max-p, reflection, denied)
12-20 00:27:45.002 E/ThemeUtils(23814): Error setting TextView handles color
12-20 00:27:45.002 E/ThemeUtils(23814): java.lang.NoSuchFieldException: No field mSelectHandleLeft in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes3.dex)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at java.lang.Class.getDeclaredField(Native Method)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at com.owncloud.android.utils.ThemeUtils.setTextViewHandlesColor(ThemeUtils.java:838)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at com.owncloud.android.utils.ThemeUtils.setEditTextColor(ThemeUtils.java:588)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at com.owncloud.android.utils.ThemeUtils.themeSearchView(ThemeUtils.java:601)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onCreateOptionsMenu(ReceiveExternalFilesActivity.java:1042)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at android.app.Activity.onCreatePanelMenu(Activity.java:4092)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:324)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3070)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at android.os.Handler.handleCallback(Handler.java:883)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at android.os.Looper.loop(Looper.java:214)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at java.lang.reflect.Method.invoke(Native Method)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
12-20 00:27:45.002 E/ThemeUtils(23814): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
12-20 00:27:45.022 V/StateManager(20863): saveState
12-20 00:27:45.022 V/StateManager(20863): saveState class com.android.gallery3d.app.TimeLinePage
12-20 00:27:46.096 D/ReceiveExternalFilesActivity(23814): Uploading file to dir /oneplus5t/
12-20 00:27:46.106 D/FileActivity(23814): show loading dialog
12-20 00:27:46.127 E/CopyAndUploadContentUrisTask(23814): Exception while copying content://media/external/images/media/114072 to temporary file
12-20 00:27:46.127 E/CopyAndUploadContentUrisTask(23814): java.lang.IllegalArgumentException: column 'last_modified' does not exist. Available columns: [instance_id, duration, description, picasa_id, latitude, orientation, height, is_drm, bucket_display_name, owner_package_name, volume_name, date_modified, date_expires, _display_name, datetaken, mime_type, _id, _data, _hash, _size, title, width, longitude, is_trashed, group_id, document_id, is_pending, date_added, mini_thumb_magic, primary_directory, secondary_directory, isprivate, original_document_id, bucket_id, relative_path]
12-20 00:27:46.127 E/CopyAndUploadContentUrisTask(23814): 	at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:352)
12-20 00:27:46.127 E/CopyAndUploadContentUrisTask(23814): 	at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:91)
12-20 00:27:46.127 E/CopyAndUploadContentUrisTask(23814): 	at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:156)
12-20 00:27:46.127 E/CopyAndUploadContentUrisTask(23814): 	at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:49)
12-20 00:27:46.127 E/CopyAndUploadContentUrisTask(23814): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
12-20 00:27:46.127 E/CopyAndUploadContentUrisTask(23814): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-20 00:27:46.127 E/CopyAndUploadContentUrisTask(23814): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
12-20 00:27:46.127 E/CopyAndUploadContentUrisTask(23814): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-20 00:27:46.127 E/CopyAndUploadContentUrisTask(23814): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-20 00:27:46.127 E/CopyAndUploadContentUrisTask(23814): 	at java.lang.Thread.run(Thread.java:919)
```

**Comment by steve-s-71** [comment] 2020-12-20 09:25
Reproduced with :
Samsung Galaxy S7 (2016)
Samsung Galaxy Tab 2
Samsung Galaxy S10
Samsung Galaxy Tab 5e

Nextcloud 20.0.3
Nextcloud app version: 3.14.1

**Comment by AndyScherzinger** [comment] 2020-12-20 13:49
Duplicate of #7587

**Closed by AndyScherzinger** 2020-12-20 13:49 UTC
Labels: bug
