### ISSUE TITLE
Crash after clicking + button

### ISSUE THREAD

**Issue by bigherc18** [nextcloud/android#13832] opened 2024-10-20 20:01 UTC
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.isEncrypted()' on a null object reference
    at com.owncloud.android.ui.fragment.OCFileListBottomSheetDialog.onCreate(OCFileListBottomSheetDialog.java:101)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:461)
    at android.app.Dialog.show(Dialog.java:339)
    at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$registerFabListener$2(OCFileListFragment.java:497)
    at com.owncloud.android.ui.fragment.OCFileListFragment.$r8$lambda$EjOMs-FB2wKRJ0sXOp3WfmJzcbY(Unknown Source:0)
    at com.owncloud.android.ui.fragment.OCFileListFragment$$ExternalSyntheticLambda12.onClick(D8$$SyntheticClass:0)
    at android.view.View.performClick(View.java:7740)
    at android.view.View.performClickInternal(View.java:7710)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(View.java:30629)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:257)
    at android.os.Looper.loop(Looper.java:368)
    at android.app.ActivityThread.main(ActivityThread.java:8839)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OP557AL1`
* Model: `CPH2399`
* Id: `UKQ1.230924.001`
* Product: `CPH2399EEA`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S.194be10_1`

**Comment by joshtrichards** [comment] 2024-10-20 20:08
Duplicate of #12163

**Closed by joshtrichards** 2024-10-20 20:08 UTC
Labels: bug, performance: NPE :no_entry_sign:, stable-3.29
