### ISSUE TITLE
Add tag support

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/android#11887] opened 2023-08-08 05:47 UTC
Currently the tags are not supported in the android version. So, it is not possible to assign tags to files. This is consequently limits the smooth experience working with the nextcloud both from mobile app and the webUI, eg adding system it collaborative tags, using file processing workflows based on the tags etc.

Please, add the tags support to the android app.

**Comment by AndyScherzinger** [comment] 2023-08-08 07:09
Duplicate of #11875

**Closed by AndyScherzinger** 2023-08-08 07:09 UTC
Labels: enhancement
