### ISSUE TITLE
DEV version: auto upload remove original file not working

### ISSUE THREAD

**Issue by DemoFreak** [nextcloud/android#1312] opened 2017-08-11 08:50 UTC
### Actual behaviour
Files stay on device after successful upload, despite its configured to delete them

### Expected behaviour
Delete files after successful upload

### Steps to reproduce
1. configure auto upload to remove files after upload
2. take photo
3. wait for file to be uploaded, after that open gallery and see the file still on the device

### Environment data
Android version: 6.0.1
Device model: Note4
Stock or customized system: stock
Nextcloud app version: 20170810
Nextcloud server version: 12.0.0

**Comment by tobiasKaminsky** [comment] 2017-08-11 12:15
Where are the photos stored? On external or internal storage?

**Comment by DemoFreak** [comment] 2017-08-11 14:06
Both internal (serial photos) and external (single photo and video).

**Comment by tobiasKaminsky** [comment] 2017-08-16 08:23
Can you try it with 2.0 RC2 as this will the version we want to release.
You can register for this on google play store: https://play.google.com/apps/testing/com.nextcloud.client

**Comment by DemoFreak** [comment] 2017-08-16 22:16
Tried it with 2.0 RC2, the issue remains.

The taken picture is instantly uploaded after a "force rescan", but still visible with Quickpic (my favourite gallery app) and with a filemanager (Solid Explorer).
Somewhat odd: the android gallery app don't show this picture after the upload, despite it's still there (as verified with the filemanager).

**Comment by tobiasKaminsky** [comment] 2017-08-17 11:17
Seems as the deletion of the original file fails. 

> the android gallery app don't show this picture after the upload

The explanation for this is that the android gallery app uses the media scanner to get a list of the images. We de-register the image from there. So this is working as intended.

**Comment by DemoFreak** [comment] 2017-08-17 18:38
> Seems as the deletion of the original file fails.

Something I can do in this regard? I love the idea not having to sort the pics/vids twice, as they are stored only once at a given moment. Preferably in the cloud. ;)

**Comment by tobiasKaminsky** [comment] 2018-01-03 13:47
For some reasons the external sdcard is on some devices readonly, that means that NC app is not allowed to remove a file from it.
The only workaround I know is to move the camera storage to the internal storage.

**Comment by tobiasKaminsky** [comment] 2018-02-22 12:24
Is the above suggestion/workaround working?

**Comment by DemoFreak** [comment] 2018-02-22 15:16
Sry, I changed the setting to "move to apps folder", so I can't say.

**Comment by tobiasKaminsky** [comment] 2018-02-23 07:59
Ok, as you were the only one reporting this, I'll close it.
Thanks for responding.

**Closed by tobiasKaminsky** 2018-02-23 07:59 UTC
Labels: AutoUpload, bug, needs info/discussion
