### ISSUE TITLE
App won't instant upload anymore 

### ISSUE THREAD

**Issue by Titan-OX** [nextcloud/android#10207] opened 2022-05-08 19:40 UTC
### Steps to reproduce
1. Use app normally with instant uploads (Autoupload photos). 
2. 
3. 

### Expected behaviour
- pictures taken with the phone should automatically be uploaded to Nextcloud when in home wifi without having to open the app

### Actual behaviour
Photos did not show up in Nextcloud on PC browser. App said "could not connect to server" or similar above the folders. This was fixed by update through Google play store but it still won't upload my pictures (also new ones taken after the update and reboot.

### Can you reproduce this problem on 
I won't try uploading my camera folder from my phone to a test instance 

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'com.owncloud.android.utils.FileSortOrder$SortType com.owncloud.android.utils.FileSortOrder.getType()' on a null object reference
    at com.owncloud.android.ui.adapter.OCFileListAdapter.getPopupText(OCFileListAdapter.java:905)
    at me.zhanghai.android.fastscroll.RecyclerViewHelper.getPopupText(RecyclerViewHelper.java:136)
    at me.zhanghai.android.fastscroll.FastScroller.onPreDraw(FastScroller.java:198)
    at me.zhanghai.android.fastscroll.FastScroller.$r8$lambda$fhoCEu3yFeBM02d2QCiuR_Ev5oo(Unknown Source:0)
    at me.zhanghai.android.fastscroll.FastScroller$$ExternalSyntheticLambda1.run(Unknown Source:2)
    at me.zhanghai.android.fastscroll.RecyclerViewHelper$1.onDraw(RecyclerViewHelper.java:52)
    at androidx.recyclerview.widget.RecyclerView.onDraw(RecyclerView.java:4668)
    at android.view.View.draw(View.java:21982)
    at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
    at android.view.View.updateDisplayListIfDirty(View.java:20859)
    at android.view.View.draw(View.java:21714)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.draw(View.java:21985)
    at android.view.View.updateDisplayListIfDirty(View.java:20859)
    at android.view.View.draw(View.java:21714)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.updateDisplayListIfDirty(View.java:20850)
    at android.view.View.draw(View.java:21714)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.updateDisplayListIfDirty(View.java:20850)
    at android.view.View.draw(View.java:21714)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.draw(View.java:21985)
    at android.view.View.updateDisplayListIfDirty(View.java:20859)
    at android.view.View.draw(View.java:21714)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.updateDisplayListIfDirty(View.java:20850)
    at android.view.View.draw(View.java:21714)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.draw(View.java:21985)
    at android.view.View.updateDisplayListIfDirty(View.java:20859)
    at android.view.View.draw(View.java:21714)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.updateDisplayListIfDirty(View.java:20850)
    at android.view.View.draw(View.java:21714)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.updateDisplayListIfDirty(View.java:20850)
    at android.view.View.draw(View.java:21714)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.updateDisplayListIfDirty(View.java:20850)
    at android.view.View.draw(View.java:21714)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.updateDisplayListIfDirty(View.java:20850)
    at android.view.View.draw(View.java:21714)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
    at android.view.View.draw(View.java:21985)
    at com.android.internal.policy.DecorView.draw(DecorView.java:808)
    at android.view.View.updateDisplayListIfDirty(View.java:20859)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:581)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:587)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:664)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:3767)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3495)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2779)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7772)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
    at android.view.Choreographer.doCallbacks(Choreographer.java:791)
    at android.view.Choreographer.doFrame(Choreographer.java:726)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7356)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `Xiaomi`
* Device: `davinci`
* Model: `Mi 9T`
* Id: `QQ3A.200805.001`
* Product: `aosp_davinci`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `0229737af9`
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:
23.0.3
From Hetzer

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by pachulo** [comment] 2022-05-08 22:06
This looks like a duplicate of #10200

**Comment by AlvaroBrey** [comment] 2022-05-09 07:40
Duplicate of #10200

**Closed** 2022-05-09 09:00 UTC
Labels: bug
