### ISSUE TITLE
Custom storage path

### ISSUE THREAD

**Issue by hockeymikey** [nextcloud/android#5476] opened 2020-02-15 00:33 UTC
### Describe the solution you'd like
I would like the ability to set a custom storage path instead of having to decide between the predetermined default ones. I want to set it to something like /storage/XXX/Nextcloud. Let the user figure out if the folder is writeable too. I'll make sure the path I put is writeable but I want that freedom to chose. Just add it on the bottom of the defaults as "custom path" and then add a dialog popup type it in. I think it would be the simplest and best solution.

**Comment by john-soda** [comment] 2020-06-09 22:40
I really would like to see this feature. There are many things that are not perfect in the Nextcloud app. But this is a must have.
Up to now I stay with syncthing because it has folder, not only file, sync and I can choose freely which folders should be synced.
To have everything you want to sync and access with other apps, except autoupload, in /storage/emulated/0/Android/media/com.nextcloud.client/files/USER@EMAIL@SERVER/USER-FOLDERS is really an inefficient design!!!! Who comes up with something like that?

**Comment by dundunn** [comment] 2020-11-09 10:47
Sorry but why does this have no priority at all? The current implemetation looks amateurish or if someone didn't complete his task 😕

**Comment by WarmChocolateCake** [comment] 2021-04-30 08:12
Just adding a +1 here.
I have my external (micro)SD card explicitly for storage (formatted as "portable" - if I've remembered the term correctly) - when transferring files to another device I'd prefer /Nextcloud on the card, rather than the long (Android default?) path (as shown by @john-soda )
When browsing for the destination I'm prompted to give access to the card, so I'm presuming we need an additional step to then define / create a custom folder.?

**Comment by kojid0** [comment] 2022-01-08 16:40
The app doesn't have storage permission so it can only save to its own dedicated app folder. I agree that this feature should be added.

**Comment by joshtrichards** [comment] 2023-12-21 23:10
Duplicate of #4223

**Closed by joshtrichards** 2023-12-21 23:10 UTC
Labels: enhancement, hotspot: device storage
