### ISSUE TITLE
Nextcloud app ->media->pic->details->crash

### ISSUE THREAD

**Issue by Borph** [nextcloud/android#14207] opened 2024-12-19 21:03 UTC
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to read from field 'com.google.android.material.tabs.TabLayout com.owncloud.android.databinding.FileDetailsFragmentBinding.tabLayout' on a null object reference in method 'void com.owncloud.android.ui.fragment.FileDetailFragment.lambda$setupViewPager$0()'
    at com.owncloud.android.ui.fragment.FileDetailFragment.lambda$setupViewPager$0(FileDetailFragment.java:355)
    at com.owncloud.android.ui.fragment.FileDetailFragment.$r8$lambda$Sp-VmtMx2q_HeyzGV0P1GEAXBvw(Unknown Source:0)
    at com.owncloud.android.ui.fragment.FileDetailFragment$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:991)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8826)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
    at com.android.internal.os.ExecInit.main(ExecInit.java:50)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300690`
* Build flavor: `generic`

### Device information
* Brand: `google`
* Device: `husky`
* Model: `Pixel 8 Pro`
* Id: `AP4A.241205.013`
* Product: `husky`

### Firmware
* SDK: `35`
* Release: `15`
* Incremental: `2024121200`

**Comment by JanisPlayer** [comment] 2024-12-20 11:40
Same problem, the error just looks a little different for me.

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to read from field 'com.google.android.material.tabs.TabLayout com.owncloud.android.databinding.FileDetailsFragmentBinding.tabLayout' on a null object reference in method 'void com.owncloud.android.ui.fragment.FileDetailFragment.lambda$setupViewPager$0()'
    at com.owncloud.android.ui.fragment.FileDetailFragment.lambda$setupViewPager$0(FileDetailFragment.java:355)
    at com.owncloud.android.ui.fragment.FileDetailFragment.$r8$lambda$Sp-VmtMx2q_HeyzGV0P1GEAXBvw(Unknown Source:0)
    at com.owncloud.android.ui.fragment.FileDetailFragment$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:257)
    at android.os.Looper.loop(Looper.java:368)
    at android.app.ActivityThread.main(ActivityThread.java:8839)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300690`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus8T`
* Model: `KB2003`
* Id: `UKQ1.230924.001`
* Product: `OnePlus8T_EEA`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `R.1a46c89-1_1`

**Comment by joshtrichards** [comment] 2024-12-28 15:09
Duplicate of  #13933

**Closed by joshtrichards** 2024-12-28 15:09 UTC
