### ISSUE TITLE
Android client crashes on startup after reinstalling server

### ISSUE THREAD

**Issue by chrsmth** [nextcloud/android#8804] opened 2021-08-04 05:50 UTC
My home server died and took down my Nextcloud instance with it. I reinstalled a fresh instance of Nexcloud on a new server. I manually restored my user account with the same username & password as it had previously. The eNxcloud Android client now crashes on startup. This did not happen with the old server.

Workaround was to delete the app and reinstall. Deleting all app data did not resolve the issue.

### Expected behaviour
- Should not crash

### Actual behaviour
- Crashes on startup

### Environment data
Android version:
11

Device model: 
Pixel 4a

Stock or customized system:
Stock

Nextcloud app version:
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

Nextcloud server version:
Nextcloud 22.0.0 (Stable)

Reverse proxy:
No

### Logs

```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: sunfish
Model: Pixel 4a
Product: sunfish

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 7380771
```
#### Web server error log
This web server error might be associated with the app crash. It appears to happen at around the same time.
```
TypeError: Argument 3 passed to OCA\Files\Service\TagService::__construct() must be an instance of OCP\ITags, null given, called in /var/www/nextcloud/apps/files/lib/AppInfo/Application.php on line 106

    1. /var/www/nextcloud/apps/files/lib/AppInfo/Application.php - line 106:
    OCA\Files\Service\TagService->__construct(OC\User\Session {}, OC\Activity\Manager {}, null, null, OC\EventDisp ... {})

    2. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 160:
    OCA\Files\AppInfo\Application->OCA\Files\AppInfo\{closure}("*** sensiti ... *")

    3. /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php - line 118:
    OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")

    4. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 127:
    Pimple\Container->offsetGet("OCA\\Files\ ... e")

    5. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 454:
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\Files\ ... e")

    6. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 432:
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\Files\ ... e")

    7. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 56:
    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Files\ ... e")

    8. /var/www/nextcloud/apps/files/lib/AppInfo/Application.php - line 86:
    OC\AppFramework\Utility\SimpleContainer->get("OCA\\Files\ ... e")

    9. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 160:
    OCA\Files\AppInfo\Application->OCA\Files\AppInfo\{closure}("*** sensiti ... *")

    10. /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php - line 118:
    OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")

    11. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 127:
    Pimple\Container->offsetGet("APIController")

    12. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 454:
    OC\AppFramework\Utility\SimpleContainer->query("APIController")

    13. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 432:
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("APIController")

    14. /var/www/nextcloud/lib/private/AppFramework/App.php - line 129:
    OC\AppFramework\DependencyInjection\DIContainer->query("APIController")

    15. /var/www/nextcloud/lib/private/Route/Router.php - line 301:
  .   OC\AppFramework\App::main("APIController", "getThumbnail", "*** sensiti ... *", { x: "256",y ... "})

    16. /var/www/nextcloud/lib/base.php - line 1000:
    OC\Route\Router->match("/apps/files ... d")

    17. /var/www/nextcloud/index.php - line 36: 
    OC::handleRequest()
```

**Comment by mat-l** [comment] 2021-08-05 06:43
Same for me. Had to setup my Nextcloud Docker (as described here: https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache) environment. Now the App crashes if I want to connect to the server:

************ CAUSE OF ERROR ************


java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password

at okhttp3.Credentials.basic(Unknown Source:8)

at okhttp3.Credentials.basic$default(Credentials.kt:28)

at okhttp3.Credentials.basic(Unknown Source:2)

at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)

at com.owncloud.android.operations.RefreshFolderOperation.updateUserProfile(RefreshFolderOperation.java:283)

at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:231)

at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)

at java.lang.Thread.run(Thread.java:784)


************ APP INFORMATION ************

ID: com.nextcloud.client

Version: 30160190

Build flavor: generic


************ DEVICE INFORMATION ************

Brand: HUAWEI

Device: HWAGS2

Model: AGS2-W09

Id: HUAWEIAGS2-W09

Product: AGS2-W09EEA


************ FIRMWARE ************

SDK: 26

Release: 8.0.0

Incremental: 317(OCEC431)

**Comment by AndyScherzinger** [comment] 2021-08-11 21:37
Duplicate of #8370

**Closed by AndyScherzinger** 2021-08-11 21:37 UTC
Labels: bug
