### ISSUE TITLE
an error appeared during synchronization

### ISSUE THREAD

**Issue by Slawa79** [nextcloud/android#13321] opened 2024-07-26 06:15 UTC
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at com.owncloud.android.ui.adapter.OCFileListAdapter.limitToPersonalFiles(OCFileListAdapter.java:1074)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:741)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1343)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1292)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1281)
    at com.owncloud.android.ui.activity.FileDisplayActivity.updateListOfFilesFragment(FileDisplayActivity.java:672)
    at com.owncloud.android.ui.activity.FileDisplayActivity$UploadFinishReceiver.onReceive(FileDisplayActivity.java:1382)
    at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
    at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:240)
    at android.os.Looper.loop(Looper.java:351)
    at android.app.ActivityThread.main(ActivityThread.java:8370)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290190`
* Build flavor: `generic`

### Device information
* Brand: `realme`
* Device: `RMX3191`
* Model: `RMX3191`
* Id: `SP1A.210812.016`
* Product: `RMX3191RU`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `R.1830654+77f55`

**Comment by joshtrichards** [comment] 2024-08-05 17:31
Duplicate of #13086
Fixed in #12930

**Closed by joshtrichards** 2024-08-05 17:31 UTC
