### ISSUE TITLE
Photos List is displaying late

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/android#2457] opened 2018-04-11 09:14 UTC
Photo list appears too late. I wait for a minimum of 5 minutes but iOS is also displayed instantly. I think there's a bug here.

(I'm not talking about thumbnails)
 
![screenshot_20180411-121035](https://user-images.githubusercontent.com/297968/38607696-075e190a-3d82-11e8-84ce-89c609b31a4d.png)
_(*Yükleniyor: Loading)_

### Steps to reproduce
1.  Nextcloud App
2. Photos Tab  

### Environment data
Android version: 7.0

Device model: Samsung A5 (2017)

Nextcloud app version: 3.0.3

Nextcloud server version: 13.0.1

**Comment by AndyScherzinger** [comment] 2018-04-11 10:54
@tobiasKaminsky @mario any idea why iOS is doing this way faster (just checked) I am aware that they have the images sorted by date which is something we also want to implement but that has been flagged Nextcloud 14. So do we know the approach the iOS app is taking since that seems to be the way faster approach :)

**Comment by fzirker** [comment] 2018-04-23 08:41
I think this is a duplicate of #1682.

**Comment by AndyScherzinger** [comment] 2018-04-23 13:36
Thanks for the hint @fzirker - thus closing in favor of #1682.

**Closed by AndyScherzinger** 2018-04-23 13:36 UTC
