### ISSUE TITLE
Nextcloud Client on Amazon Fire Tablet

### ISSUE THREAD

**Issue by santasonic** [nextcloud/android#5907] opened 2020-04-21 05:52 UTC
### Steps to reproduce
1. Starting client

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@b7ccbd4
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1419)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6734)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=26106, uid=1010227 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3919)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1382)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1408)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1409)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:22242)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:183)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3323)
	at android.os.Binder.execTransact(Binder.java:731)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Amazon
Device: maverick
Model: KFMAWI
Id: PS7312
Product: maverick

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 0017884837764

**Comment by tobiasKaminsky** [comment] 2020-04-21 06:18
> Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=26106, uid=1010227 requires android.permission.BROADCAST_STICKY

This is the same error.
Duplicate of #5709

**Closed by tobiasKaminsky** 2020-04-21 06:18 UTC
Labels: bug

**Comment by AndyScherzinger** [comment] 2020-10-12 15:33
Duplicate of #6654
