### ISSUE TITLE
F-Droid upgrade from 2.0.0 to 2.0.1 not working (signing key changed?)

### ISSUE THREAD

**Issue by ttamttam** [nextcloud/android#1705] opened 2017-10-22 15:41 UTC
### Actual behaviour

F-Droid does not want to install the 2.0.1 version without removing the older one (2.0.0).

I'm reluctant to do that because:
- I'm not sure my configuration would not be lost
- I found no mention of this new key in the Changelog

### Expected behaviour

Transparent upgrade :-)
 
### Steps to reproduce
1. Upgrade from F-Droid

### Environment data
Android version: 4.4.2

Device model: Samsung GT-I9505 (Galaxy S4, I think)

Stock or customized system: Stock, I would say

Nextcloud app version: 2.0.0 -> 2.0.1

Nextcloud server version: NA

**Comment by AndyScherzinger** [comment] 2017-10-22 15:51
@mario @tobiasKaminsky @Bubu any ideas? Nextcloud isn't building the app for f-droid but f-droid does it themselves.

For the release I only tagged the release.... Implying f-droid would pick up the right build target.

**Comment by AndyScherzinger** [comment] 2017-10-22 15:52
@ttamttam you would loose your Config when reinstalling as for the signing key that is a question for f-droid since we only provide the source, building is done by f-droid.

**Comment by ttamttam** [comment] 2017-10-22 15:55
OK. Thanks for the precision. I'm first going to wait a little. If the problem remains in some days, I'll try to find out where to report that to f-droid.

**Comment by Bubu** [comment] 2017-10-22 18:57
I just did this upgrade via f-droid on my phone and it worked as intended.

@ttamttam not sure what's happening, you currently have the 2.0.0 version also installed via f-droid?

Can try updating again when connected via adb and share the error message?

**Comment by ttamttam** [comment] 2017-10-22 19:14
>  you currently have the 2.0.0 version also installed via f-droid?

Yes.

> Can try updating again when connected via adb and share the error message?

I'll try that when I'll have some time. But I will have to install android tools for that. It's a long time since I last did that :-)

**Comment by Terrox** [comment] 2017-10-22 20:18
Mine says 

The new version is signed with a different key to the old one. To install the new version, the old one must be uninstalled first. Please do this and try again. (Note that uninstalling will erase any internal data stored by the application)

Running CarbonROM 4.4.4.

**Comment by Bubu** [comment] 2017-10-23 10:45
I compared the signing certificates, they are identical for both versions:
```
$ apksigner verify --print-certs com.nextcloud.client_20000099.apk 
Signer #1 certificate DN: CN=FDroid, OU=FDroid, O=fdroid.org, L=ORG, ST=ORG, C=UK
Signer #1 certificate SHA-256 digest: 5709576f9d6c6a7687dd5d56b269d1fa5e379702b91bc83f39fd7b7c597c1b83
```

```
$ apksigner verify --print-certs com.nextcloud.client_20000199.apk 
Signer #1 certificate DN: CN=FDroid, OU=FDroid, O=fdroid.org, L=ORG, ST=ORG, C=UK
Signer #1 certificate SHA-256 digest: 5709576f9d6c6a7687dd5d56b269d1fa5e379702b91bc83f39fd7b7c597c1b83
```.
As this apparently affects multiple people something is apparetly going on, but I have no idea what...

**Comment by ttamttam** [comment] 2017-10-24 06:54
Oh. I'm terribly sorry.

It appears that the 2.0.0 version installed on my phone is marked as (translated from french):

Version 2.0.0
Installed (from Google Play Store)
Repository: F-Droid
Added on 2017-10-21

I'm not sure how it is possible, but it is certainly a mistake of mine…

@Terrox Could you check this?

**Comment by tobiasKaminsky** [comment] 2018-01-02 08:23
Closing, if this happens again, please feel free to reopen.

**Closed by tobiasKaminsky** 2018-01-02 08:23 UTC
Labels: bug
