### ISSUE TITLE
delay before autoupload

### ISSUE THREAD

**Issue by laquiche-secu** [nextcloud/android#7249] opened 2020-11-06 19:36 UTC
Hello

Add the possibility of having a delay before the autoupload.

Thus by configuring a period of 24h for example, it is possible to delete unnecessary photos before the good photos are automatically uploaded to the server

**Comment by tobiasKaminsky** [comment] 2020-11-11 09:32
Duplicate of #2922

**Closed by tobiasKaminsky** 2020-11-11 09:32 UTC
Labels: enhancement
