### ISSUE TITLE
Crash after trying to place widget

### ISSUE THREAD

**Issue by Emporea** [nextcloud/android#10859] opened 2022-10-20 14:26 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Install new 3.22 update
Try to place widget
Get an error

### Expected behaviour

Widget should be placed

### Actual behaviour

Error

### Android version

12.1

### Device brand and model

alioth xiamoi

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.22

### Nextcloud server version

25

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to start receiver com.nextcloud.client.widget.DashboardWidgetProvider: java.lang.IllegalArgumentException: com.nextcloud.client: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:4339)
    at android.app.ActivityThread.access$1600(ActivityThread.java:257)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7833)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: Exception in thread "main" java.lang.IllegalArgumentException: com.nextcloud.client: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
    at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
    at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
    at android.app.PendingIntent.getActivity(PendingIntent.java:444)
    at android.app.PendingIntent.getActivity(PendingIntent.java:408)
    at com.nextcloud.client.widget.DashboardWidgetUpdater.setPendingClick(DashboardWidgetUpdater.kt:107)
    at com.nextcloud.client.widget.DashboardWidgetUpdater.updateAppWidget(DashboardWidgetUpdater.kt:78)
    at com.nextcloud.client.widget.DashboardWidgetProvider.onUpdate(DashboardWidgetProvider.kt:48)
    at android.appwidget.AppWidgetProvider.onReceive(AppWidgetProvider.java:66)
    at com.nextcloud.client.widget.DashboardWidgetProvider.onReceive(DashboardWidgetProvider.kt:59)
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:4330)
    at android.app.ActivityThread.access$1600(ActivityThread.java:257)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7833)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220090`
* Build flavor: `generic`

### Device information
* Brand: `POCO`
* Device: `alioth`
* Model: `M2012K11AG`
* Id: `SQ3A.220705.004`
* Product: `lineage_alioth`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `1665824073`

### Server error logs

```bash
None
```

**Comment by AlvaroBrey** [comment] 2022-10-20 14:44
Duplicate of #10826

**Closed by AlvaroBrey** 2022-10-20 14:44 UTC
Labels: bug
