### ISSUE TITLE
Start Issue

### ISSUE THREAD

**Issue by lavenetz** [nextcloud/android#7655] opened 2020-12-13 10:08 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalArgumentException: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.
	at android.app.ActivityThread.installProvider(ActivityThread.java:7278)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6813)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6699)
	at android.app.ActivityThread.access$2000(ActivityThread.java:273)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: java.lang.IllegalArgumentException: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.
	at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(Unknown Source:8)
	at com.google.firebase.iid.FirebaseInstanceId.checkRequiredFirebaseOptions(com.google.firebase:firebase-iid@@20.2.3:52)
	at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@20.2.3:2)
	at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@20.2.3:1)
	at com.google.firebase.iid.Store.checkForRestore(com.google.firebase:firebase-iid@@20.2.3:15)
	at com.google.firebase.iid.Store.<init>(com.google.firebase:firebase-iid@@20.2.3:5)
	at com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase:firebase-iid@@20.2.3:16)
	at com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase:firebase-iid@@20.2.3:8)
	at com.google.firebase.iid.Registrar.lambda$getComponents$0$Registrar(com.google.firebase:firebase-iid@@20.2.3:26)
	at com.google.firebase.iid.Registrar$$Lambda$0.create(Unknown Source:0)
	at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
	at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
	at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(com.google.firebase:firebase-components@@16.0.0:158)
	at com.google.firebase.FirebaseApp.initializeAllApis(com.google.firebase:firebase-common@@19.3.0:563)
	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:304)
	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:268)
	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:253)
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@19.3.0:51)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1949)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1923)
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@19.3.0:45)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7273)
	... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWLON
Model: LON-L29
Id: HUAWEILON-L29
Product: LON-L29

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 254C432

**Comment by AndyScherzinger** [comment] 2020-12-14 09:54
Duplicate of #7616

**Closed by AndyScherzinger** 2020-12-14 09:54 UTC
