### ISSUE TITLE
Error in android

### ISSUE THREAD

**Issue by IsmaStifler** [nextcloud/android#13967] opened 2024-11-06 14:40 UTC
### Cause of error
```java
Exception in thread "Thread-4" java.lang.IllegalArgumentException: Trying to execute a sync operation with a storage manager for an anonymous account
    at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:49)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$fetchExternalLinks$9(DrawerActivity.java:1231)
    at com.owncloud.android.ui.activity.DrawerActivity.$r8$lambda$oHM2j1MZkviAIdyIFWoI2kSeF9c(Unknown Source:0)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `Sony`
* Device: `XQ-EC54`
* Model: `XQ-EC54`
* Id: `69.0.A.2.49`
* Product: `XQ-EC54_EEA`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `069000A002004900522519484`

**Comment by joshtrichards** [comment] 2024-11-06 15:18
Duplicate of #13323

**Closed by joshtrichards** 2024-11-06 15:18 UTC
