### ISSUE TITLE
Leaving shares has unclear UX

### ISSUE THREAD

**Issue by thgoebel** [nextcloud/android#11750] opened 2023-06-18 15:41 UTC
### Is your feature request related to a problem? Please describe.

It is unclear how I can leave a share on Android.

I have a folder that someone shared with me.
On iOS and web, the overflow menu for this shared folder has an option "Leave share" but no option "Delete".
On Android, there is no option "Leave share" but there is an option "Delete" for the shared folder.

As a user I have no idea what will happen if I press "Delete". Will I leave the share? Will it delete the files in the owner's account? It's very confusing.

### Describe the solution you'd like

Android should have the same as iOS and web: no delete option, but a "Leave share" option in the overflow menu of the folder.

### Describe alternatives you've considered

Leave it unclear.

### Additional context

Files for Android 3.25.0
Nextcloud Server 26.0.2

**Comment by joshtrichards** [comment] 2023-12-23 15:19
Duplicate of #7612

**Closed by joshtrichards** 2023-12-23 15:19 UTC
Labels: enhancement, feature: sharing
