### ISSUE TITLE
Nextcloud Android 10 Issue

### ISSUE THREAD

**Issue by axheli** [nextcloud/android#6061] opened 2020-05-13 02:37 UTC
I currently have a Oneplus 7 Pro and due to the way the Nextcloud app that the below info can explaine is casing issues that all my notification on the phone go away. and this is due to Nextcloud and Android 10  

For anyone wondering about this still: The issue in my case is an app using a deprecated Android API to scan media files. In my case the Nextcloud client app was using the following code:

Code:
public static void triggerMediaScan(String path) {
  if (path != null) {
  Intent intent = new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE);
  intent.setData(Uri.fromFile(new File(path)));
  MainApp.getAppContext().sendBroadcast(intent);
  }
}
Apparently, Android 10 does not like this. I've sent it to the support crew here in hopes that they can fix it as well. Most likely if you are having this issue, there's an app using similarly structured code to scan for media files in this manner which is deprecated in Android 10 (which is what the current version of OxygenOS is based on).

My advice is to find the app causing the issue and also report the problem to the app developer or customer support.

**Comment by AndyScherzinger** [comment] 2020-05-13 04:54
@tobiasKaminsky didn't you fix this already? For 3.12?

**Comment by axheli** [comment] 2020-05-13 11:11
@AndyScherzinger I'm on 3.12 RC1 and just tried it and same issue.

**Comment by tobiasKaminsky** [comment] 2020-05-13 12:38
Yes, it is a duplicate of #5039 
@axheli thanks for reporting (and also reporting the cause of the issue). It took me quite very long to find it.
Do you have an example code how to do the media scanning instead?
If so, please comment in #5039

**Closed by tobiasKaminsky** 2020-05-13 12:38 UTC
Labels: bug

**Comment by skeletor-spills** [comment] 2020-05-15 01:46
@tobiasKaminsky Well this is hilarious. I posted that exact text to the OnePlus forums a few days ago after reading about the issue in #5039 and posted your code along with the rest of the text in hopes people using other apps trying to do the same media scan can fix the problem with their apps as well. I've been following the issue here waiting for a good build. Full circle here :)

**Comment by axheli** [comment] 2020-05-15 02:13
@skeletor-spills Hahahaha yup once i seen your post one OnePlus forums i copied it to created a issue on here. Good to know there's someone else that wants this fixed
