### ISSUE TITLE
Android APP failure after move files in WEB client

### ISSUE THREAD

**Issue by Robert91911** [nextcloud/android#5759] opened 2020-03-28 13:08 UTC
### Steps to reproduce
1. Syncronice data with andoid client and close app
2. Move files into another directory using web interface 
3. Open the android app

### Expected behaviour
- The android app show the Syncronice the changes with the web interface 

### Actual behaviour
- The android app is blocked

### Environment data
Android version: 10

Device model: Xiaomi Mi9

Stock or customized system: MIUI

Nextcloud app version: 3.11.0

Nextcloud server version: 18.0.1

#### Web server error log
```
Fatal	webdav	OCP\Files\NotFoundException:
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=3398, totalRows=1439
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:942)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:163)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:131)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:249)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:287)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:190)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:332)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:309)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:670)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2126)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:371)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:532)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:520)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1891)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:407)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:478)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:369)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:228)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:357)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: cepheus
Model: MI 9
Id: QKQ1.190825.002
Product: cepheus_eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V11.0.8.0.QFAEUXM

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2020-03-28 20:19
Do you know how big the folder in question was?

**Comment by mindrunner** [comment] 2020-05-03 11:12
I have the same issue.

**Comment by tobiasKaminsky** [comment] 2020-05-12 08:38
Can you give me additional info what you did? @mindrunner 
Currently I have no idea how to reproduce this reliable…

**Comment by mindrunner** [comment] 2020-05-12 08:40
No, I cannot give any precise explanation. I moved/deleted a big bunch of files/folders around and since then, I am constantly getting the error in the android app.

**Comment by tobiasKaminsky** [comment] 2020-05-20 15:05
Duplicate of #5926

**Closed by tobiasKaminsky** 2020-05-20 15:05 UTC
Labels: bug, needs info/discussion
