### ISSUE TITLE
Android app crash on server side app update

### ISSUE THREAD

**Issue by tryallthethings** [nextcloud/android#7064] opened 2020-10-07 15:36 UTC
I'm not 100% sure but the timing was too good to not bring this into relation.

### Steps to reproduce
1. Update app on server
2. Nextcloud client will crash

### Expected behaviour
- App should not crash

### Actual behaviour
- App crashes

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 8.0.0
Device model: Samsung Galaxy S7 (SM-G930F)
Stock or customized system: Stock
Nextcloud app version: 3.13.1
Nextcloud server version: 19.0.3
Reverse proxy: No

#### Client crash log
```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/data/app/com.nextcloud.client-K2HEOwgdVOtqcoRHXMruPA==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-K2HEOwgdVOtqcoRHXMruPA==/lib/arm64, /data/app/com.nextcloud.client-K2HEOwgdVOtqcoRHXMruPA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: herolte
Model: SM-G930F
Id: R16NW
Product: heroltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G930FXXS7ETA8
```

**Comment by AndyScherzinger** [comment] 2020-10-07 15:46
Duplicate of #4675

**Closed by AndyScherzinger** 2020-10-07 15:46 UTC
Labels: bug

**Comment by AndyScherzinger** [comment] 2020-10-07 15:48
Hi @tryallthethings, 

the server update shouldn't have anything to do with it but who knows it might have healed push notifications on the serve -side while then the client would have been broken before...

There is a fix that will ship with the next feature release of the Android client 🚀
