### ISSUE TITLE
Trouble comnecting to server

### ISSUE THREAD

**Issue by pine-serpent** [nextcloud/android#10894] opened 2022-10-23 02:41 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open nextcloud android app
2. Type in local server IP and port
3. Click sign in
4. Get error

### Expected behaviour

Connecting into server asking for credentials

### Actual behaviour

Crashes when connecting to server and gives error.

### Android version

13

### Device brand and model

Google Pixel 5a

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.22.1

### Nextcloud server version

24.0.4

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.LinearLayout com.owncloud.android.databinding.SslUntrustedCertLayoutBinding.getRoot()' on a null object reference
    at com.owncloud.android.ui.dialog.SslUntrustedCertDialog.onCreateDialog(SslUntrustedCertDialog.java:173)
    at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665)
    at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579)
    at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1752)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7904)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ExecInit.main(ExecInit.java:49)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220190`
* Build flavor: `generic`

### Device information
* Brand: `google`
* Device: `barbet`
* Model: `Pixel 5a`
* Id: `TP1A.221005.002`
* Product: `barbet`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `2022101800`

### Additional information

Using Grapheneos. Have used nextcloud many times before without issue. Just reinstalled after a phone wipe. Nextcloud from browser works perfectly.

**Comment by nottheend** [comment] 2022-10-23 06:06
Samw here with Google Pixel 6 but same OS (Android 13). I thought it is the server but Web UI is fine.

I finally got logged in to server via App but crashes continue. I can't remove the nextcloud account from the app anymore, it keeps crashing. And it seems to use all my memory and CPU because phone keeps getting warm unless uninstalling the nextcloud app

**Comment by AlvaroBrey** [comment] 2022-10-23 09:34
Duplicate of #10868, fix will release tomorrow

**Closed by AlvaroBrey** 2022-10-23 09:34 UTC
Labels: bug

**Comment by nottheend** [comment] 2022-10-23 15:10
Thanks a lot @AlvaroBrey! I am reading sth in #10868 that it is only happening to self signed certificates. This is not the case for me, I am using let's encrypt.
But will check again fter the new release.
