### ISSUE TITLE
File (davx5-info.txt) is having a permanent upload conflict

### ISSUE THREAD

**Issue by kofaysi** [nextcloud/android#6506] opened 2020-07-21 22:34 UTC
### Steps to reproduce
1. Saved a Debug info into a folder
2. NC app tries to upload
3. Sync conflict dialogue comes up
4. user choose all option: keep local, keep server, keep both and rename

### Expected behaviour
- files is synced

### Actual behaviour
- file is uploaded with numerical increment (2), (3),... but sync conflict dialogue comes up again within an hour time

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 7.1.3

Device model: LG-H850

Stock or customized system: OSe

Nextcloud app version: Dev channel 20200721

Nextcloud server version: 18 ecloud.global

Reverse proxy:

### Logs
![Screenshot_20200722-002437](https://user-images.githubusercontent.com/17022173/88113886-fef04d80-cbb2-11ea-8cbc-ab40e18e3ba5.png)
The file creating conflict is to be supplied privately. It is a Debug info.
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2020-07-22 06:17
Duplicate of #6510

**Closed by tobiasKaminsky** 2020-07-22 06:17 UTC
Labels: bug
