### ISSUE TITLE
show/hide toolbar on scroll down/up

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#190] opened 2016-08-03 12:16 UTC
Since we now have the toolbar in place (which replaced the legacy action bar) we can start implementing further material design thing like show/hide of the toolbar as described here: http://android-developers.blogspot.de/2014/10/material-design-on-android-checklist.html

> App bar
> Where appropriate, upon scrolling down, the app bar can scroll off the screen, leaving more vertical space for content. Upon scrolling back up, the app bar should be shown again.

If this general behavior is approved I would start working on an implementation on the main list which shows the files on server/on device as a first implementation. If that is done we can then think about adopting this also on other screens like file picker for upload I probably wouldn't implemented it on all screens but may on all list or just most lists...not sure though.

any feedback/comments? @tobiasKaminsky @jancborchardt @przybylski ?

You can see this behavior in Chrome on Android for example.

**Comment by tobiasKaminsky** [comment] 2016-08-03 15:51
This is a really cool feature :+1: 
But let's wait for @jancborchardt ;)

**Comment by jancborchardt** [comment] 2016-08-12 17:01
Yeah, this is also in place in Firefox and the Play Store. :) Let’s test out if it works nicely for us as well.

**Comment by joshtrichards** [comment] 2023-12-09 22:42
Duplicate of #6238 
Fixed by #6262

**Closed by joshtrichards** 2023-12-09 22:42 UTC
Labels: enhancement, design, approved
