### ISSUE TITLE
Android client crashed twice in Dex on Note 10+

### ISSUE THREAD

**Issue by ironjohn** [nextcloud/android#4574] opened 2019-09-27 21:44 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{a7348f3 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1918)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7263)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: d2q
Model: SM-N975U
Id: PPR1.180610.011
Product: d2qsq

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: N975USQU1ASHB

**Comment by tobiasKaminsky** [comment] 2019-10-09 13:42
Duplicate of #2010

**Closed by tobiasKaminsky** 2019-10-09 13:42 UTC
Labels: bug
