### ISSUE TITLE
Uploading and "Set as available offline" should be available for folders and not only single files

### ISSUE THREAD

**Issue by mark-orion** [nextcloud/android#1611] opened 2017-10-01 18:25 UTC
### Actual behaviour
-Uploading and "Set as available offline" are not available for folders

### Expected behaviour
-You can upload an entire folder tree in one go and you can make an entire folder tree available for offline use.

**Comment by xXSTrikeXx** [comment] 2017-10-19 11:36
Hasn´t it already implemented by the sync button? Or is the user forced there to press all time to sync to have an up to date directory?

**Comment by AndyScherzinger** [comment] 2017-10-19 17:09
this not related to the file list sync but available offline for folders not just files, thus a duplicate of #93

**Closed by AndyScherzinger** 2017-10-19 17:09 UTC
Labels: enhancement
