### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Axxxolotl** [nextcloud/android#4543] opened 2019-09-23 11:12 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e832bd7 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HONOR
Device: HWCOL
Model: COL-L29
Id: HUAWEICOL-L29
Product: COL-L29RU

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 325C10

**Comment by tobiasKaminsky** [comment] 2019-10-09 13:42
Duplicate of #2010

**Closed by tobiasKaminsky** 2019-10-09 13:42 UTC
Labels: bug
