### ISSUE TITLE
Download folder (Data Storage Folder)

### ISSUE THREAD

**Issue by Tobias-Lauerbach** [nextcloud/android#10038] opened 2022-04-03 11:01 UTC
### Is your feature request related to a problem? Please describe.
not easily finding by files downloaded in the NC-App

### Describe the solution you'd like
It would be grate to be able to set any folder on the system as the folder were downloaded files are stored (storage folder)
### Describe alternatives you've considered
Setting the download folder as default folder for downloads in the app

adding this or a way to select any folder there

![IMG_20220403_130451](https://user-images.githubusercontent.com/62332598/161424729-421a5591-71d6-4c72-b462-e69dd31b81f2.jpg)

**Comment by Frxhb** [comment] 2022-04-07 19:05
Yea, please. 👍

**Comment by Knusper** [comment] 2022-06-03 22:57
Indeed, a very good request.  The current choice for possible locations is quite limited... :/

**Comment by joshtrichards** [comment] 2023-12-21 23:00
Duplicate of #4223

**Closed by joshtrichards** 2023-12-21 23:00 UTC
Labels: enhancement, hotspot: device storage
