### ISSUE TITLE
Error after use a player média coming back to thé directory

### ISSUE THREAD

**Issue by rodinux** [nextcloud/android#8942] opened 2021-09-06 10:22 UTC
### Steps to reproduce
1. Listen a sound with media player on a smartphone
2. Try coming back on the directory where médias were found with the arrow
3. 

### Expecepted 
Coming back on thé directory with the files.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: 
Dogee

Stock or customized system: 
LineageOS

Nextcloud app version:
3.17.0

Nextcloud server version:
21.0.3

Reverse proxy:

#### Web server error log

```
```

#### Nextcloud log (data/nextcloud.log) thé client on thé smartphone
```
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{521e42b u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: DOOGEE
Device: S40
Model: S40
Id: QQ3A.200605.001
Product: S40

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: eng.crossg.20200607.060543


```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2021-09-06 14:03
@rodinux Is this 100% reproducible for you? i.e. it happens every time?

**Comment by AlvaroBrey** [comment] 2021-09-07 10:48
Duplicate of #8686

**Closed by AlvaroBrey** 2021-09-07 10:48 UTC
Labels: bug
