### ISSUE TITLE
Exception after going back from "setup: enter hostname" page to normal file view from already logged in account

### ISSUE THREAD

**Issue by DF3LX** [nextcloud/android#13288] opened 2024-07-18 11:34 UTC
After doing the "back" swipe gesture on my Pixel 6a, Android 14 with the current Version from the Google Play Store (30290290) the app crashed.

This behavior is reproducible.

Steps to reproduce:

-  launch Nextcloud app with already added account
- click in the profile picture in the upper right corner 
- click on the add account button
- swipe the "back" gesture 

*crash*

If there is a need for any additional information, I'm happy to help!

Logs exported from the app:
### Cause of error
```java
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property currentAccount has not been initialized
    at com.nextcloud.client.mixins.SessionMixin.getCurrentAccount(SessionMixin.kt:32)
    at com.nextcloud.client.mixins.SessionMixin.onRestart(SessionMixin.kt:100)
    at com.nextcloud.client.mixins.MixinRegistry.onRestart(MixinRegistry.kt:48)
    at com.owncloud.android.ui.activity.BaseActivity.onRestart(BaseActivity.java:118)
    at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1711)
    at android.app.Activity.performRestart(Activity.java:9086)
    at android.app.ActivityThread.performRestartActivity(ActivityThread.java:5729)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:352)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:307)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:289)
    at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:213)
    at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8592)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `bluejay`
* Model: `Pixel 6a`
* Id: `AP2A.240605.024`
* Product: `bluejay`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `11860263`

**Comment by joshtrichards** [comment] 2024-07-19 12:38
Duplicate of #13241 
Fixed in #13248

**Closed by joshtrichards** 2024-07-19 12:38 UTC
