### ISSUE TITLE
Possibility of creating shortcuts to folders or sections of the app

### ISSUE THREAD

**Issue by albertooka** [nextcloud/android#4184] opened 2019-06-27 11:10 UTC
I would like to have the possibility to create shortcuts of folders or sections of the Nextcloud app.

**Comment by andreaskern** [comment] 2021-05-29 12:15
this is probably a duplicate of #3175

**Comment by AndyScherzinger** [comment] 2021-05-29 16:33
Duplicate of #3175

**Closed by AndyScherzinger** 2021-05-29 16:33 UTC
Labels: enhancement
