### ISSUE TITLE
Drawer: account name cut of due to notch

### ISSUE THREAD

**Issue by RavengamerSpace** [nextcloud/android#3689] opened 2019-02-28 23:07 UTC
### Actual behaviour
- Display issue with the domain/server name

### Expected behaviour
- The text must be displayed correctly
 
### Steps to reproduce
1.  Just deploy the hamburger menu

### Environment data
Android version: Android 9

Device model: POCOPHONE F1

Stock or customized system: MIUI 10 (Xiaomi Android version)

Nextcloud app version: 3.5.0

Nextcloud server version: 15.0.4

### Image
![screenshot_2019-02-28-23-58-10-403_com nextcloud client](https://user-images.githubusercontent.com/28545669/53604801-cfa00180-3bb5-11e9-99b7-aca2282752b7.png)

**Comment by tobiasKaminsky** [comment] 2019-03-04 10:44
This seems to happen on Android >=9.0…

**Comment by tobiasKaminsky** [comment] 2019-03-04 11:01
Strange, I know that I had this from time to time on my 9.0 emulator, but now I cannot reproduce it.
@AndyScherzinger do you have an idea?

**Comment by AndyScherzinger** [comment] 2019-03-04 12:58
@tobiasKaminsky #3695 might solve it. My guess is that this is related to a slightly larger systembar, so my fix may or may not work, can't say for sure :(

**Comment by tobiasKaminsky** [comment] 2019-03-05 07:48
This will be in our dev version next day.

Maybe you want to try it (you can install it in parallel): 
https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release

**Comment by AndyScherzinger** [comment] 2019-03-05 08:06
@RavengamerSpace Any test would be highly appreciated since I can't reproduce this behavior so some feedback about the fix actually solving the issue is highly appreeciated ❤️

**Comment by RavengamerSpace** [comment] 2019-03-05 18:39
Hey, I'm back.
So as you said, I installed the Nextcloud dev version that I found on Fdroit.
But unfortunately, I still got the same issue.

![screenshot_2019-03-05-19-35-09-055_com nextcloud android beta](https://user-images.githubusercontent.com/28545669/53828551-4c4c2a80-3f7e-11e9-92d3-68c686cb1a09.png)
![screenshot_2019-03-05-19-35-13-699_com miui securitycenter](https://user-images.githubusercontent.com/28545669/53828552-4c4c2a80-3f7e-11e9-8dc1-6422aed3af06.png)

**Comment by RavengamerSpace** [comment] 2019-03-05 18:40
Maybe it's a studip thing but do the notch can cause this issue. Because my phone have a notch

**Comment by AndyScherzinger** [comment] 2019-03-05 22:04
Hmmm, the notch might be a cause, don't know. The dev version you run is to old. Can you check the apps settings page for the latest build? 
20190301 doesn't contain the fix. 20290305 might or 20190306 build tonight.

**Comment by tobiasKaminsky** [comment] 2019-03-06 08:09
Indeeed.
Notch is the problem:
![2019-03-06-090806](https://user-images.githubusercontent.com/5836855/53865390-5eb27c80-3fef-11e9-8253-1cc04bd8adaa.png)

**Comment by tobiasKaminsky** [comment] 2019-03-06 08:30
https://developer.android.com/guide/topics/display-cutout

when I add 
< item name="android:windowLayoutInDisplayCutoutMode">never< /item>
to styles.xml, I do get

![2019-03-06-093026](https://user-images.githubusercontent.com/5836855/53866712-7c351580-3ff2-11e9-9d8c-d24f58c8c0b8.png)

**Comment by AndyScherzinger** [comment] 2019-03-06 21:11
Oh dear, so this seems to be a bigger issue then :/

**Comment by RavengamerSpace** [comment] 2019-03-09 06:40
The problem has been solved with the 7 March 2019 Version
![Screenshot_2019-03-09-07-37-07-903_com nextcloud android beta](https://user-images.githubusercontent.com/28545669/54067262-6156e100-423e-11e9-98d2-5c171bd9953b.png)
![Screenshot_2019-03-09-07-40-06-865_com miui securitycenter](https://user-images.githubusercontent.com/28545669/54067288-99f6ba80-423e-11e9-9c74-64444b3b79b4.png)

**Comment by AndyScherzinger** [comment] 2019-03-09 07:54
Thanks for the feedback @RavengamerSpace, then my fix did indeed work @tobiasKaminsky :) so 3.6.0 will fix this.

**Comment by AndyScherzinger** [comment] 2019-03-27 23:28
3.6.0RC1 is tagged, so I'll close the issue.

**Closed by AndyScherzinger** 2019-03-27 23:28 UTC
Labels: approved, bug
