### ISSUE TITLE
File filter for automatic uploads

### ISSUE THREAD

**Issue by supermar1010** [nextcloud/android#9788] opened 2022-01-31 18:35 UTC
### Is your feature request related to a problem? Please describe.

The problem is the nextcloud app uploads all files in the selected folder. This can be problematic for example with signal backups which first creates a tmp file, this file should not be uploaded. The same is true for the recycle bin for pictures. Nextcloud syncs the trash which is unnecessary in my opinion. I would like to exclude these files, for example in a similar way as in the desktop app.

### Describe the solution you'd like

A possible implementation approach could be, taking the same route as in the desktop app, using patterns to define files to ignore. The auto upload feature would then need to scan the found files for the defined patterns and filter these. There should also be an option whether to delete the preexisting, now ignored files.

### Describe alternatives you've considered

I can not really think of alternative solutions. There might be more user friendly solutions than just adding a some patterns, for example having a preview to show the excluded files, but this is a more advanced and not crucial feature.

### Additional context

See #3418, at least a few people want it too.

**Comment by AlvaroBrey** [comment] 2022-02-01 09:14
@supermar1010 please don't duplicate existing issues, even if it is with a more detailed translation. The correct approach is to just add info to existing issues, if appropriate.

**Comment by AlvaroBrey** [comment] 2022-02-01 09:14
Duplicate of #3418

**Closed by AlvaroBrey** 2022-02-01 09:14 UTC
Labels: enhancement
