### ISSUE TITLE
Can not see complete file name

### ISSUE THREAD

**Issue by BuZZ-dEE** [nextcloud/android#5737] opened 2020-03-24 21:49 UTC
Can not see complete file name. There are dots "..." in the file name. If there are more than one file with a the same beginning and the same end, I can not differentiate between those files, because the relevant part is killed by the dots.

**Comment by joshtrichards** [comment] 2023-10-16 13:55
Duplicate of #2305 

Let's consolidate tracking this work there.

**Closed by joshtrichards** 2023-10-16 13:55 UTC
Labels: enhancement
