### ISSUE TITLE
Can not navigate to "On device" from "Uploads"

### ISSUE THREAD

**Issue by nielstron** [nextcloud/android#13660] opened 2024-10-01 01:13 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open the Uploads tab from the burger menu
2. open the On device tab from the burger menu
(assumes a set-up sync connection, files on Server and files on device, did not test other configurations)

### Expected behaviour

The "On device" view should open.

### Actual behaviour

The title changes to "On device" but the content of the window does not change.

### Android version

14

### Device brand and model

Pixel 6 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.30.0

### Nextcloud server version

Nextcloud Hub 8 (29.0.6)

### Using a reverse proxy?

Yes

**Comment by joshtrichards** [comment] 2024-10-04 13:08
Duplicate of #9538

**Closed by joshtrichards** 2024-10-04 13:08 UTC
Labels: bug, 1. to develop, hotspot: navigation, stable-3.30
