### ISSUE TITLE
Setting to start auto-upload only in favorite WIFI

### ISSUE THREAD

**Issue by schbrongx** [nextcloud/android#8481] opened 2021-05-26 06:55 UTC
In this case the title says it all: Give users zhe option to fav a Wifi and restrict auto-upload to that specific Wifi.

Use-case: Users zhat have not enabled external access to their cloud.

**Comment by tobiasKaminsky** [comment] 2021-05-26 08:23
A current workaround would be to restrict auto upload to non metered wifi and set only your favorite wifi to non-metered.

**Comment by joshtrichards** [comment] 2023-12-22 22:40
Duplicate of #3671

**Closed by joshtrichards** 2023-12-22 22:40 UTC
Labels: enhancement, feature: auto upload, feature: data usage
