### ISSUE TITLE
Android app is a battery hog 

### ISSUE THREAD

**Issue by topo03** [nextcloud/android#10957] opened 2022-10-29 16:55 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Do absolutely nothing, e.g. like leave your phone sitting in standby. 
Obviously the Nextcloud Android app should be installed on your phone. 

### Expected behaviour

Nothing should happen. Particularly the app should not get active in the background. 

### Actual behaviour

I see the Nextcloud app appearing in my battery stats with values around 3-6% (avg. 4-5%) of battery consumption per load cycle. This even happens if I don't take pictures/videos. My app is setup to auto uploaded pics/vids. 

### Android version

12 and now 13

### Device brand and model

Samsung Galaxy S22 and Xiaomi M5 (LOS18.1)

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22 but had same issue with all previous

### Nextcloud server version

23

### Using a reverse proxy?

No

### Additional information

Error log:
Sorry I have no data folder. 
I had a look at logcat but I'm not sure how to use it in this case. Am I supposed to let it run the entire day to get an understanding of the apps background activity? Please let me know if that would be feasible and helpful.

**Comment by AlvaroBrey** [comment] 2022-10-30 19:29
Duplicate of #7663

**Closed by AlvaroBrey** 2022-10-30 19:29 UTC
Labels: bug
