### ISSUE TITLE
Delay on internal picture viewer

### ISSUE THREAD

**Issue by maxaustria** [nextcloud/android#219] opened 2016-08-17 00:17 UTC
Delay on internal picture viewer:

Test scenario:
- in a folder with 28 files, all below one megabyte I open a jpeg file with 400kb, all files in the folder are downloaded
- the client process has been stopped manual
- server software is oc 9
- I start my android client, navigate three folder levels down and then click on the image to show

behavior in NC client 1.2.0
- first time I click picture opens in 22seconds!
- second time I open the picture it opens in 4 seconds
- third time it opens in 4 seconds
- on further tests it stays between 4 and 6 seconds, as user experience not nice

behavior in oc client 2.1.0
- first time I click picture opens in below a second
- second time I open it seems even a little bit faster
- both times it seems fast enough to have a good user experience

other test beside:
- I open a txt file, 2kb, downloaded, on oc immediately open, on NC it takes 2 sec to display the content
- I open a mp3 file, 19kb, downloaded, same behaviour in both clients

**Comment by strugee** [comment] 2016-08-17 05:47
I can reproduce this on latest F-Droid beta. It seems this doesn't happen when the images aren't downloaded.

**Comment by AndyScherzinger** [comment] 2016-08-17 08:35
cc @tobiasKaminsky - I can also reproduce this and given the performance issue here ranked it a high priority bug.

**Comment by tobiasKaminsky** [comment] 2017-02-14 09:10
Is this still happening? I remember that there was a bug in the beta version that lead to download the remote/resized images instead of displaying the local one.

**Comment by strugee** [comment] 2017-02-16 01:55
I can't reproduce anymore.

**Comment by tobiasKaminsky** [comment] 2017-02-16 18:46
Thank you for replying @strugee 
I close this issue for now, if you experience it again, please re-open.

**Closed** 2017-02-18 07:38 UTC
Labels: bug, high
