### ISSUE TITLE
Picture Upload ends with exception on android

### ISSUE THREAD

**Issue by almhirte** [nextcloud/android#7617] opened 2020-12-06 18:51 UTC
### Steps to reproduce
1. Try to Upload pictures using the nextcloud Android app

### Expected behaviour
- Pictures are being uploaded

### Actual behaviour
- Exception comes up

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
10
Device model: 
Xperia 10II
Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Fragment IndeterminateProgressDialog{7bfe3a3} (77675672-1a21-4842-9962-2c19a90b950d)} not associated with a fragment manager.
	at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:945)
	at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:271)
	at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:228)
	at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:437)
	at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:72)
	at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:34)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:359)
	at android.app.ActivityThread.main(ActivityThread.java:7407)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: XQ-AU52
Model: XQ-AU52
Id: 59.0.A.8.45
Product: XQ-AU52_EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 059000A008004502956232951

Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by rmallah** [comment] 2020-12-06 20:04
I also could not upload pictures using "Share" function in the gallery. Although i did not get any crashdump but it failed silently.

**Comment by AndyScherzinger** [comment] 2020-12-07 08:56
@rmallah your issue is a duplicate of #7587 and not related to @almhirte's report

**Comment by tobiasKaminsky** [comment] 2020-12-16 12:34
@almhirte do you see any kind of dialog?

**Comment by mathiasconradt** [comment] 2020-12-17 06:55
I am having upload issues with the latest Android app on Huawei Mate Pro 20, Android 10, using an old NC12 server where the upload via app worked for years until recently. When I try to upload a photo, I see a message/alert "Copying file to private storage" for a split of a second but that's all. No other error / nothing on the server log, because I think it doesn't even get that far.

**Comment by AndyScherzinger** [comment] 2020-12-17 08:56
@mathiasconradt are you sharing the image via Android to Nextcloud's mobile app or do you trigger the upload within the app. Sharing to Nextcloud does have a known bug in the latest release. Fix for that would be https://github.com/nextcloud/android/pull/7649

**Comment by mathiasconradt** [comment] 2020-12-17 09:01
@AndyScherzinger Yes, sharing from Android image gallery to NC mobile app. Thanks for the info.

**Closed** 2020-12-18 07:19 UTC
Labels: approved, bug, pr exists
