### ISSUE TITLE
Constant app crashes when Syncing (>6k) WhatsAPP Pictures

### ISSUE THREAD

**Issue by cholzer79** [nextcloud/android#6004] opened 2020-05-05 05:17 UTC
### Steps to reproduce
1. autosync WhatsApp Pictures with >6000 pictures inside
2. nextcloud app responds very slowly during the sync, you will get the "app has stopped responding" warning a **LOT**
3. nextcloud app crashes (crash log below) constantly and has to be restarted over and over again to eventually finish the sync

**NOTE**
This only happens when the folder to sync has several thousand files inside. 
Syncing folders with less than 2000 pictures/videos works fine.

### Expected behaviour
- App must not crash, even when syncing several thousand files 😅

### Actual behaviour
- app crashes constantly and has to be restarted many times to eventually get everything synced

### Environment data
Android version: 10

Device model: OnePlus 6T, but the same issue occurs on Sony Experia XZ2, Xiaomi Mi A2 and a Samsung Galaxy S7

Stock or customized system: stock

Nextcloud app version: 3.11.1

Nextcloud server version: 18.0.4 ("NX20" hosted by www.hetzner.de, but I had the exact same issue with a self hosted instance of nextcloud which is why i tried a hosted instance hoping that this would fix the issue)

### Logs
Crash Log from nextcloud Android App
**** CAUSE OF ERROR ****

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.SecurityException: Caller no longer running, last stopped +11s207ms because: timed out while starting
	at android.os.Parcel.createException(Parcel.java:2071)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:292)
	at android.app.job.JobParameters.dequeueWork(JobParameters.java:248)
	at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
	at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobServiceContext.assertCallerLocked(JobServiceContext.java:493)
	at com.android.server.job.JobServiceContext.doDequeueWork(JobServiceContext.java:371)
	at com.android.server.job.JobServiceContext$JobCallback.dequeueWork(JobServiceContext.java:160)
	at android.app.job.IJobCallback$Stub.onTransact(IJobCallback.java:169)
	at android.os.Binder.execTransactInternal(Binder.java:1032)

**** APP INFORMATION ****
ID: com.nextcloud.client
Version: 30110190
Build flavor: gplay

**** DEVICE INFORMATION ****
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6013
Id: QKQ1.190716.003
Product: OnePlus6T

**** FIRMWARE ****
SDK: 29
Release: 10
Incremental: 2002220019

**Comment by tobiasKaminsky** [comment] 2020-05-05 05:43
Duplicate of #5805

**Closed by tobiasKaminsky** 2020-05-05 05:43 UTC
Labels: bug
