### ISSUE TITLE
":" crashes the app

### ISSUE THREAD

**Issue by FernandoPizzardo** [nextcloud/android#9472] opened 2021-12-06 20:01 UTC
### Steps to reproduce
1. Add a new account
2. Input URL of the server
3. I insert 192.168.15.5:8283 which my Truenas server deploys next cloud
4.it gives me this message

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2021-12-09 10:20
Duplicate of #9338

**Closed by AlvaroBrey** 2021-12-09 10:20 UTC
Labels: bug
