### ISSUE TITLE
Client starts Bruteforce on invalid credentials

### ISSUE THREAD

**Issue by User65481** [nextcloud/android#7807] opened 2021-01-11 08:49 UTC
### Steps to reproduce
1. Create User in AD
2. Login with user on Mobile Client. Set up sync.
3. Disable user in AD

### Expected behaviour
- Client tries to sync
- Client gets reply login failed
- Client pauses sync and asks user to confirm username/password OR delays sync, retries after 15 Minutes and asks for username/password if login still fails

### Actual behaviour
- Client tries to login for each file/folder it tries to sync

### Can you reproduce this problem on https://try.nextcloud.com?
- No since its not possible to login there

### Environment data
Android version: 9, 10

Device model: various, as far we observe all models are affected

Stock or customized system: stock

Nextcloud app version: all, most failed logins from 3.14.1

Nextcloud server version: 20.0.4

### Logs
![grafik](https://user-images.githubusercontent.com/77266803/104160748-ea6a7080-53f1-11eb-85b2-4e91592da9e1.png)

As you can see one single user created over 1500 failed logins in 48h.

We are aware of the brute force protection from serverside and the possibility to block it from the firewall; still this is a bug from client side. It clogs logs and makes it harder to spot legitimate brute force attempts.

**Comment by joshtrichards** [comment] 2023-12-11 22:25
Duplicate of #9341
And also related to #893 

Let's consolidate there.

**Closed by joshtrichards** 2023-12-11 22:25 UTC
Labels: bug, approved, feature: authentication, hotspot: auth failure mgmt
