### ISSUE TITLE
App crash on Start

### ISSUE THREAD

**Issue by goldengel** [nextcloud/android#6615] opened 2020-08-02 14:18 UTC
### Steps to reproduce
1. Start Android App
2. Upload pending count is over 3000 since server Version update from 18 to 19.
3. App does not response > kill after 5 minutes
4. Start App

### Expected behaviour
- App should not crash

### Actual behaviour
- App crashes

**Comment by goldengel** [comment] 2020-08-03 16:29
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:355)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.SecurityException: Caller no longer running, last stopped +1s876ms because: timed out while starting
	at android.os.Parcel.createException(Parcel.java:1953)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:195)
	at android.app.job.JobParameters.dequeueWork(JobParameters.java:243)
	at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
	at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$2.call(AsyncTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobServiceContext.assertCallerLocked(JobServiceContext.java:490)
	at com.android.server.job.JobServiceContext.doDequeueWork(JobServiceContext.java:368)
	at com.android.server.job.JobServiceContext$JobCallback.dequeueWork(JobServiceContext.java:161)
	at android.app.job.IJobCallback$Stub.onTransact(IJobCallback.java:83)
	at android.os.Binder.execTransact(Binder.java:739)


************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWANE
Model: ANE-LX1
Id: HUAWEIANE-L21
Product: ANE-LX1

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.306C432

**Comment by tobiasKaminsky** [comment] 2020-08-05 08:58
Duplicate of #5805

**Closed by tobiasKaminsky** 2020-08-05 08:58 UTC
Labels: bug
