### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by putrizulfa** [nextcloud/android#10296] opened 2022-05-29 07:51 UTC
### Cause of error
```java
Exception in thread "AsyncTask #6" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:415)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:923)
Caused by: Exception in thread "AsyncTask #6" java.lang.RuntimeException: Accessing result data after operation failed!
    at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:512)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.doInBackground(GallerySearchTask.java:102)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.doInBackground(GallerySearchTask.java:48)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:923)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a50`
* Model: `SM-A505F`
* Id: `RP1A.200720.012`
* Product: `a50dd`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `A505FDDS9CVC1`

**Comment by AlvaroBrey** [comment] 2022-05-30 07:43
Duplicate of #10198

**Closed by AlvaroBrey** 2022-05-30 07:43 UTC
