### ISSUE TITLE
Nextcloud crashes randomly on Android 10

### ISSUE THREAD

**Issue by Aurnytoraink** [nextcloud/android#4888] opened 2019-11-25 22:56 UTC
### Actual behaviour
- The app crashes randomly, and also when unlocking an account using 2FA notification method

### Expected behaviour
- Well, just normally work
 
### Steps to reproduce
1. Log-in from another device
2. Select notification 2FA methods
3. And you get an android pop-up warning you that nextcloud crashes.

### Environment data
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: beryllium
Model: POCO F1
Id: QD1A.190821.014
Product: beryllium

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: eng.ninad.20191124.152630

Nextcloud server version: 17.0.0.1

#### Nextcloud log (data/nextcloud.log)
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
 at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
 at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
 at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
 at com.google.firebase.iid.zzg.run(Unknown Source:4)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
 at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.AnalyticsConnector
 ... 8 more
```

**Comment by AndyScherzinger** [comment] 2019-12-02 07:35
Duplicate of #4675, so closing in favor

Brand: Huawei
Device: hwALE-H
Model: ALE-L21

**Closed by AndyScherzinger** 2019-12-02 07:35 UTC
Labels: bug
