### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Timojl1** [nextcloud/android#10468] opened 2022-07-02 23:23 UTC
### Cause of error
```java
Exception in thread "FinalizerWatchdogDaemon" java.util.concurrent.TimeoutException: android.media.MediaMetadataRetriever.finalize() timed out after 10 seconds
    at android.media.MediaMetadataRetriever.native_finalize(Native Method)
    at android.media.MediaMetadataRetriever.finalize(MediaMetadataRetriever.java:696)
    at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
    at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
    at java.lang.Daemons$Daemon.run(Daemons.java:137)
    at java.lang.Thread.run(Thread.java:919)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `CUBOT`
* Device: `P40`
* Model: `P40`
* Id: `QP1A.190711.020`
* Product: `P40_EEA`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `20200518`

**Comment by strugee** [comment] 2022-07-04 20:22
Duplicate of #10274

**Closed by strugee** 2022-07-04 20:22 UTC
Labels: bug
