### ISSUE TITLE
Calendar and contacts backup should also be created weekly/monthly

### ISSUE THREAD

**Issue by Markoise** [nextcloud/android#12742] opened 2024-03-25 21:51 UTC
I would very much like to use the "Calendar and contacts backup" function. 

Daily backup creates a backup file for each day, it would also be useful if you could set how many backups you want to keep, e.g. the last 10 backups.

A weekly or monthly backup would perhaps also be quite good.

**Comment by vince-from-nice** [comment] 2024-04-14 00:09
I fully agree, keeping only the last few backups would be a very nice feature (as well to choose the backup folders).

**Comment by joshtrichards** [comment] 2024-10-19 16:57
Duplicate of #2296

**Closed by joshtrichards** 2024-10-19 16:57 UTC
Labels: enhancement, feature: contacts/calendars
