### ISSUE TITLE
Two factor verification could not login

### ISSUE THREAD

**Issue by rubenverhoef** [nextcloud/android#243] opened 2016-09-05 17:14 UTC
### Actual behaviour

App password for two factor verification not working
### Expected behaviour

Password created with nextcloud TOTP should work.
### Steps to reproduce
1.  enable two factor verification TOTP
2. generate a app password in nextcloud webgui
3. Login with generated password
4. The app says unknown error!
### Environment data

Android version: 6.0.1

Device model: Nexus 5

Stock or customized system: Stock

Nextcloud app version: 1.2.0

Nextcloud server version: 10.0

UPDATE:
Nextcloud desktop client and webdav are working fine.

**Comment by AndyScherzinger** [comment] 2016-09-05 20:42
@rubenverhoef  thanks for reporting this issue. @LukasReschke @MorrisJobke do we have a test instance where we can debug this matter?

**Comment by MorrisJobke** [comment] 2016-09-06 07:02
> do we have a test instance where we can debug this matter?

No. But you can setup a local test instance if you want to test this. (or you could simply use your own instance if it is upgraded to Nextcloud 10 already)

**Comment by AndyScherzinger** [comment] 2016-09-06 07:18
My instance is running Nextcloud 10 (but on a a "normal" hosting space, so no command line etc. if that matters).

**Comment by MorrisJobke** [comment] 2016-09-06 07:27
> My instance is running Nextcloud 10 (but on a a "normal" hosting space, so no command line etc. if that matters).

This is not needed. Just go to your personal settings. There is now a category "app passwords" where you can generate those passwords and use them as alternative credentials.

**Comment by AndyScherzinger** [comment] 2016-09-06 08:03
@rubenverhoef I tested it according to @MorrisJobke's description and it is working fine for me. Did you also include the dashes ("-")?

**Comment by rubenverhoef** [comment] 2016-09-06 15:56
@AndyScherzinger  Yes I have include the "-".  Thanks for testing, now I think it has something to do with my nginx reverse proxy. I have a look into that!

**Comment by kirakishin** [comment] 2017-01-14 11:40
I have the same troubleshooting but the generated app password doesn't work with the android app

**Comment by maximiliankaul** [comment] 2017-01-14 15:04
@kirakishin Did you set the option "allow filesystem access" (it’s on by default, I think). I turned it off once and couldn’t use the Android app until I allowed it again.

**Comment by kirakishin** [comment] 2017-01-14 22:44
i had to do the password generation a second time and it works! but i don't know really why.

**Comment by mario** [comment] 2017-02-08 15:44
Since we can't reliably reproduce, closing for now. Let me know if you experience it again!

**Closed by mario** 2017-02-08 15:44 UTC
Labels: need info
