### ISSUE TITLE
Music files downloaded via Nextcloud app are not show in music players

### ISSUE THREAD

**Issue by llucax** [nextcloud/android#1082] opened 2017-06-11 22:02 UTC
### Actual behaviour
Music files downloaded from the Nextcloud app are not show in the Android media library (not detected by any music player)

### Expected behaviour
When downloding files with owncloud that contains music, they should appear in the Android media library and be playable by any music player.
 
### Steps to reproduce
1. Download a music file (mp3 for example)
2. Go to the music app
3. The song is not shown

I even tried programs to re-scan media files and restarting the phone and nothing.

### Environment data
Android version: 7.0

Device model: Elephone P9000

Stock or customized system: Stock

Nextcloud app version: 1.4.3

Nextcloud server version: 11.0.3.2

#### Web server error log
It's a phone local thing.

**Comment by llucax** [comment] 2017-06-11 22:03
BTW, I switched Nextcloud to store files in the external SD card. Maybe that's relevant too.

Previously to use the Nextcloud app, I copied the same audio files to the same SD and never had any issues with songs not showing in media players, only when I removed all the files and did a sync via Nextcloud, the files stopped showing in music players.

**Comment by sf-janz** [comment] 2017-06-14 09:09
Is there, by chance, a ``.nomedia`` file in the path hierarchy?

**Comment by leandro-lucarella-sociomantic** [comment] 2017-06-14 12:58
I checked for that, but I double-checked and yes, I found one in `SD/Android/data` and this is where the nextcloud app put their files. I think removing that `.nomedia` will be troublesome, as it will affect all other android apps. Is there a way to mark the nextcloud directory as `.yesmedia` or something? This is not normally something the user should be messing with.

**Comment by sf-janz** [comment] 2017-06-14 13:16
Then I believe your issue is a duplicate of #429 
There's a comment from @AndyScherzinger stating:

> This will likely be made possible again in the future but I don't have any specific dates yet. [...]
https://github.com/nextcloud/android/issues/429#issuecomment-283983452

As for a workaround:
You could try MediaMonkey for Android, you can specify certain folders to be scanned there.

**Comment by leandro-lucarella-sociomantic** [comment] 2017-06-14 13:23
Yes, it looks like a duplicate. Thanks.

**Comment by leandro-lucarella-sociomantic** [comment] 2017-06-14 13:26
> You could try MediaMonkey for Android, you can specify certain folders to be scanned there.

Yeah, VLC too, any media player that can access files through the filesystem directly work, but it's not the ideal.

**Comment by tobiasKaminsky** [comment] 2017-06-16 14:28
The external storage path will be /SD/Android/media and not "/SD/Android/data" to allow other apps to access the download files.
This will be part of the next version.

**Closed by tobiasKaminsky** 2017-06-16 14:28 UTC

**Comment by Oclair** [comment] 2018-07-05 16:47
NC13 this is still a problem

**Comment by AndyScherzinger** [comment] 2018-07-05 16:53
@Oclair Did you check the storage path used by the app (in the app's settings screen?), see @tobiasKaminsky's comment https://github.com/nextcloud/android/issues/1082#issuecomment-309040799
