### ISSUE TITLE
Crash in background

### ISSUE THREAD

**Issue by kalon33** [nextcloud/android#4986] opened 2019-12-11 14:18 UTC
### Actual behaviour
- Tell us what happens
Crash
### Expected behaviour
- Tell us what should happen
Not crash
 ************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-MYXVk8dcIRxfyLmdfqRViQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-MYXVk8dcIRxfyLmdfqRViQ==/lib/arm64, /data/app/com.nextcloud.client-MYXVk8dcIRxfyLmdfqRViQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: dipper
Model: MI 8
Id: PKQ1.180729.001
Product: dipper

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V11.0.6.0.PEAMIXM

**Comment by AndyScherzinger** [comment] 2019-12-12 07:44
Duplicate of #4675

**Closed by AndyScherzinger** 2019-12-12 07:44 UTC
Labels: bug
