### ISSUE TITLE
Document selection in android app is broken

### ISSUE THREAD

**Issue by stodge** [nextcloud/android#6219] opened 2020-06-04 19:07 UTC
### Steps to reproduce
1. Fresh install of NextCloud 19.0
2. Start app, connect to server and login
3. Go to Documents in app
4. Hold down finger on first document to select
5. Select each document in turn
6. **Last document cannot be selected**
7. De-select all documents
8. Try to select any documents
9. It's random whether I can select any document or not - there's no logic to whether the selection works or not. Totally broken.

Actually, it's different every time I try to as to whether I can select documents or not.

### Expected behaviour
- Document selection/unselection should work

### Actual behaviour
- It's random whether you I can select any document or not - there's no logic to whether the selection works or not. Totally unusable

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: Google Pixel 2

Stock or customized system: Stock

Nextcloud app version: 3.11.1

Nextcloud server version: 19.0

Reverse proxy: no

#### Web server error log
```
Nothing of relevance
```

#### Nextcloud log (data/nextcloud.log)
```
Nothing of relevance
```

**Comment by AndyScherzinger** [comment] 2020-06-04 19:14
Hi @stodge and thanks for the report. this has already been fixed and will ship with 3.12. The latest release candidate is already available via GPlay beta program.

**Comment by AndyScherzinger** [comment] 2020-06-04 19:14
Duplicate of #5970

**Comment by AndyScherzinger** [comment] 2020-06-04 19:15
Fix is #5978

**Closed by AndyScherzinger** 2020-06-04 19:14 UTC
Labels: bug

**Comment by stodge** [comment] 2020-06-04 19:17
Apologies, I did a quick search but missed the referenced fix.

**Comment by AndyScherzinger** [comment] 2020-06-05 05:24
No worries, a duplicate report is better than an unreported issue 👍
