### ISSUE TITLE
App Crashes while navigating thorugh Photos folder

### ISSUE THREAD

**Issue by LotusAxt** [nextcloud/android#7415] opened 2020-11-21 06:35 UTC
### Steps to reproduce
1. Start app
2. Navigate through Photos folder
3. App Crashes

### Expected behaviour
- Tell us what should happen
App didn't Crash. 🙃

### Actual behaviour
- Tell us what happens
App Crashes😩

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=2865, totalRows=4
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:942)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:161)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:131)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:249)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:281)
	at android.database.CursorWrapper.moveToNext(CursorWrapper.java:206)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:911)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:183)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:938)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1278)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1231)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onBrowseUp(OCFileListFragment.java:855)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onBackPressed(FileDisplayActivity.java:1076)
	at android.app.Activity.onKeyUp(Activity.java:3641)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2825)
	at android.app.Activity.dispatchKeyEvent(Activity.java:3958)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:569)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:367)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5591)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5454)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4957)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5010)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4976)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5116)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4984)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5173)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4957)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5010)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4976)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4984)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4957)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5010)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4976)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5149)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5314)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3064)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2607)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2598)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3041)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Nokia
Device: CO2N_sprout
Model: Nokia 5.1
Id: QP1A.190711.020
Product: Core2_00WW

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 00WW_4_16A

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2020-11-23 09:58
Duplicate of #6688

**Closed by tobiasKaminsky** 2020-11-23 09:58 UTC
Labels: bug
