### ISSUE TITLE
Student.

### ISSUE THREAD

**Issue by Elebus76** [nextcloud/android#14110] opened 2024-12-01 05:10 UTC
### Cause of error
```java
Exception in thread "Thread-3" java.lang.IllegalArgumentException: Trying to execute a sync operation with a storage manager for an anonymous account
    at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:49)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$fetchExternalLinks$9(DrawerActivity.java:1231)
    at com.owncloud.android.ui.activity.DrawerActivity.$r8$lambda$oHM2j1MZkviAIdyIFWoI2kSeF9c(Unknown Source:0)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `motorola`
* Device: `cuscoi`
* Model: `motorola edge 50 fusion`
* Id: `U2UUIS34.40-108-3-2`
* Product: `cuscoi_g`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `95f252-58eef5`

**Comment by msviba** [comment] 2024-12-09 14:22
duplikates to https://github.com/nextcloud/android/issues/14112

**Comment by joshtrichards** [comment] 2024-12-28 14:57
Duplicate of #13323

**Closed by joshtrichards** 2024-12-28 14:57 UTC
Labels: 0. Needs triage
