### ISSUE TITLE
> Task :compileGenericDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by FrancoFasano** [nextcloud/android#4257] opened 2019-07-24 17:53 UTC
### Actual behaviour
- I clone the android project, import in android Studio 3.4 and try to build a debug generic version. Unfortunatly the build failed because of an error:
> Task : compileGenericDebugJavaWithJavac FAILED

### Expected behaviour
- a successfull genericDebug build 
 
### Steps to reproduce
1. clone git project
2. open in android studio 3.4
3. build the project
[bug nextcloud.txt](https://github.com/nextcloud/android/files/3428117/bug.nextcloud.txt)

### Environment data
Android version: build from 14 to 28

Nextcloud app version: 3.8.0.0

Nextcloud server version: 15.0.10

#### Java Compiler
```
D:/Renelgitlab/nextcloud-android_base |  src/main/java |  
com/owncloud/android/ui/activity/DrawerActivity.java |  
error: cannot find symbol variable CONTENT_TYPE_SEARCH |  
error: cannot find symbol variable CONTENT_TYPE_SEARCH |  
error: cannot find symbol variable CONTENT_TYPE_SEARCH |  
com/owncloud/android/ui/fragment/OCFileListFragment.java |  
error: cannot find symbol variable CONTENT_TYPE_SEARCH |  
error: cannot find symbol variable CONTENT_TYPE_SEARCH |  
error: cannot find symbol variable CONTENT_TYPE_SEARCH |  
```

#### Android Studio event log
```
org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:52)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:100)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:52)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
	at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:51)
	at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:37)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:39)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilerFactory$2.execute(IncrementalCompilerFactory.java:110)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilerFactory$2.execute(IncrementalCompilerFactory.java:106)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringCompiler.execute(IncrementalResultStoringCompiler.java:59)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringCompiler.execute(IncrementalResultStoringCompiler.java:43)
	at org.gradle.api.internal.tasks.compile.CompileJavaBuildOperationReportingCompiler$2.call(CompileJavaBuildOperationReportingCompiler.java:59)
	at org.gradle.api.internal.tasks.compile.CompileJavaBuildOperationReportingCompiler$2.call(CompileJavaBuildOperationReportingCompiler.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:315)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:305)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:101)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.compile.CompileJavaBuildOperationReportingCompiler.execute(CompileJavaBuildOperationReportingCompiler.java:51)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:154)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:122)
	at com.android.build.gradle.tasks.AndroidJavaCompile.compile(AndroidJavaCompile.kt:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:47)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:284)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:273)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:258)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:145)
	at org.gradle.internal.execution.impl.steps.ExecuteStep.execute(ExecuteStep.java:49)
	at org.gradle.internal.execution.impl.steps.CancelExecutionStep.execute(CancelExecutionStep.java:34)
	at org.gradle.internal.execution.impl.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:69)
	at org.gradle.internal.execution.impl.steps.TimeoutStep.execute(TimeoutStep.java:49)
	at org.gradle.internal.execution.impl.steps.CatchExceptionStep.execute(CatchExceptionStep.java:33)
	at org.gradle.internal.execution.impl.steps.CreateOutputsStep.execute(CreateOutputsStep.java:50)
	at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:43)
	at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:29)
	at org.gradle.internal.execution.impl.steps.CacheStep.executeWithoutCache(CacheStep.java:134)
	at org.gradle.internal.execution.impl.steps.CacheStep.lambda$execute$3(CacheStep.java:83)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:82)
	at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:36)
	at org.gradle.internal.execution.impl.steps.PrepareCachingStep.execute(PrepareCachingStep.java:33)
	at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:38)
	at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:23)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
	at java.util.Optional.map(Optional.java:215)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:34)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:119)
	at org.gradle.api.internal.tasks.execution.ResolvePreviousStateExecuter.execute(ResolvePreviousStateExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:93)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:45)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:94)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:315)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:305)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:101)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
```

#### Build output
```
Executing tasks: [:generateGenericDebugSources, :generateGenericDebugAndroidTestSources, :createMockableJar, :compileGenericDebugAndroidTestSources, :compileGenericDebugUnitTestSources, :compileGenericDebugSources]

> Configure project :
nextcloud-android_base: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'org.projectlombok:lombok:1.18.8'.

> Task :preBuild UP-TO-DATE
> Task :preGenericDebugBuild UP-TO-DATE
> Task :compileGenericDebugAidl UP-TO-DATE
> Task :checkGenericDebugManifest UP-TO-DATE
> Task :compileGenericDebugRenderscript NO-SOURCE
> Task :generateGenericDebugBuildConfig UP-TO-DATE
> Task :prepareLintJar UP-TO-DATE
> Task :generateGenericDebugSources UP-TO-DATE
> Task :preGenericDebugAndroidTestBuild SKIPPED
> Task :compileGenericDebugAndroidTestAidl NO-SOURCE
> Task :createGenericDebugCompatibleScreenManifests UP-TO-DATE
> Task :mainApkListPersistenceGenericDebug UP-TO-DATE
> Task :processGenericDebugManifest UP-TO-DATE
> Task :processGenericDebugAndroidTestManifest UP-TO-DATE
> Task :compileGenericDebugAndroidTestRenderscript NO-SOURCE
> Task :generateGenericDebugAndroidTestBuildConfig UP-TO-DATE
> Task :generateGenericDebugAndroidTestSources UP-TO-DATE
> Task :createMockableJar UP-TO-DATE
> Task :generateGenericDebugResValues UP-TO-DATE
> Task :generateGenericDebugResources UP-TO-DATE
> Task :mergeGenericDebugResources UP-TO-DATE
> Task :processGenericDebugResources UP-TO-DATE
> Task :kaptGenerateStubsGenericDebugKotlin UP-TO-DATE
> Task :kaptGenericDebugKotlin UP-TO-DATE
> Task :compileGenericDebugKotlin UP-TO-DATE
> Task :javaPreCompileGenericDebug UP-TO-DATE

> Task :compileGenericDebugJavaWithJavac
D:\Renelgitlab\nextcloud-android_base\src\main\java\com\owncloud\android\ui\activity\DrawerActivity.java:435: error: cannot find symbol
                handleSearchEvents(new SearchEvent("image/%", SearchRemoteOperation.SearchType.CONTENT_TYPE_SEARCH,
                                                                                              ^
  symbol:   variable CONTENT_TYPE_SEARCH
  location: class SearchType
D:\Renelgitlab\nextcloud-android_base\src\main\java\com\owncloud\android\ui\activity\DrawerActivity.java:483: error: cannot find symbol
                handleSearchEvents(new SearchEvent("%", SearchRemoteOperation.SearchType.CONTENT_TYPE_SEARCH,
                                                                                        ^
  symbol:   variable CONTENT_TYPE_SEARCH
  location: class SearchType
D:\Renelgitlab\nextcloud-android_base\src\main\java\com\owncloud\android\ui\activity\DrawerActivity.java:495: error: cannot find symbol
                handleSearchEvents(new SearchEvent("video/%", SearchRemoteOperation.SearchType.CONTENT_TYPE_SEARCH,
                                                                                              ^
  symbol:   variable CONTENT_TYPE_SEARCH
  location: class SearchType
D:\Renelgitlab\nextcloud-android_base\src\main\java\com\owncloud\android\ui\fragment\OCFileListFragment.java:364: error: cannot find symbol
            } else if (SearchRemoteOperation.SearchType.CONTENT_TYPE_SEARCH.equals(event.getSearchType())) {
                                                       ^
  symbol:   variable CONTENT_TYPE_SEARCH
  location: class SearchType
D:\Renelgitlab\nextcloud-android_base\src\main\java\com\owncloud\android\ui\fragment\OCFileListFragment.java:372: error: cannot find symbol
            } else if (SearchRemoteOperation.SearchType.RECENTLY_ADDED_SEARCH.equals(event.getSearchType())) {
                                                       ^
  symbol:   variable RECENTLY_ADDED_SEARCH
  location: class SearchType
D:\Renelgitlab\nextcloud-android_base\src\main\java\com\owncloud\android\ui\fragment\OCFileListFragment.java:1354: error: cannot find symbol
            if (SearchRemoteOperation.SearchType.CONTENT_TYPE_SEARCH.equals(event.getSearchType())) {
                                                ^
  symbol:   variable CONTENT_TYPE_SEARCH
  location: class SearchType
D:\Renelgitlab\nextcloud-android_base\src\main\java\com\owncloud\android\ui\fragment\OCFileListFragment.java:1362: error: cannot find symbol
            } else if (SearchRemoteOperation.SearchType.RECENTLY_ADDED_SEARCH.equals(event.getSearchType())) {
                                                       ^
  symbol:   variable RECENTLY_ADDED_SEARCH
  location: class SearchType
D:\Renelgitlab\nextcloud-android_base\src\main\java\com\owncloud\android\ui\fragment\OCFileListFragment.java:1381: error: cannot find symbol
            } else if (event.getSearchType() == SearchRemoteOperation.SearchType.CONTENT_TYPE_SEARCH) {
                                                                                ^
  symbol:   variable CONTENT_TYPE_SEARCH
  location: class SearchType
D:\Renelgitlab\nextcloud-android_base\src\main\java\com\owncloud\android\ui\fragment\OCFileListFragment.java:1389: error: cannot find symbol
            } else if (SearchRemoteOperation.SearchType.RECENTLY_ADDED_SEARCH == event.getSearchType()) {
                                                       ^
  symbol:   variable RECENTLY_ADDED_SEARCH
  location: class SearchType
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
9 errors

> Task :compileGenericDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGenericDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 30s
18 actionable tasks: 1 executed, 17 up-to-date

```

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ezaquarii** [comment] 2019-07-24 18:51
Youp, I can confirm. This is probably due to a changes in library.

@tobiasKaminsky is it the lib again? :)

**Comment by coderzstas** [comment] 2019-07-24 20:12
same for me

**Comment by ezaquarii** [comment] 2019-07-24 21:23
You'll need to switch to source library, which is not a hassle-free process.

@tobiasKaminsky Can we fix it with highest priority? This issue effectively blocks development for all, as snapshots are not accessible.

Is there a way to use older version of library in case I'm doing something on a branch that is few days behind? Gradle refers to `master-SNAPSHOT`. Ideally I'd like to pin the library version to a daily build that worked for me, something like `master-20190722` or similar.

**Comment by ezaquarii** [comment] 2019-07-24 21:51
@tobiasKaminsky @AndyScherzinger Library is not in sync with app again. Can we fix it ASAP, as it blocks the world?

I tried to use the source version, but it still complains about missing symbols - I suspect that you have some commits that were not merged yet.

Gradle script references `master-SNAPSHOT` wich is - I believe - a daily build of the library. The trouble is that we're consitently having issues with keeping app `master` and library `master` in sync and snapshot tend to regularly break all PRs that are being worked on, by forcing world to use newest library version that is incompatible with the app code (or the other way around).

For an OSS contributor like me, that just happens to have time **today** to work on something, this basically stops a business for a week, even if you fix it tomorrow morning.

What I want to say is those breakages are very disruptive for all external contributors.

There are couple of solutions we could try to improve the situation:

1) pin the library version on app master to some rc or daily build that works
2) merge app and library into a monorepo that would be kept in sync and build library out of it
3) keep the snapshot, but still provide timestamped library builds, so I can switch to something that works for me in case of breakage
4) use git submodules and default to source library

Currently the newest tagged version is 1.5.0-rc2 witch doesn't work with app `master`.

**Comment by AndyScherzinger** [comment] 2019-07-25 08:51
> keep the snapshot, but still provide timestamped library builds, so I can switch to something that works for me in case of breakage

```
dependencies {
	        implementation 'com.github.nextcloud:android-library:-1.2.0-g8f57cbd-196'
	}
```
should do the trick

**Comment by tobiasKaminsky** [comment] 2019-07-25 09:01
I created also a discussion here: #4259 
Fix is https://github.com/nextcloud/android-library/pull/322 and will be merged asap.

As I also wrote some ideas in #4259, I'll c&p @ezaquarii ideas there and answer.

**Comment by tobiasKaminsky** [comment] 2019-07-25 09:21
> For an OSS contributor like me, that just happens to have time **today** to work on something, this basically stops a business for a week, even if you fix it tomorrow morning.

Sorry to hear that. I really appreciate all the work you and other contributor do and of course this is big problem.

**Comment by tobiasKaminsky** [comment] 2019-07-25 09:23
Master should now build again.
(still with master-snapshot, but this will be changed soon).

**Comment by tobiasKaminsky** [comment] 2019-07-25 09:23
For discussion please go to #4259

**Closed by tobiasKaminsky** 2019-07-25 09:23 UTC
Labels: bug
