### ISSUE TITLE
video auto-upload only while charging

### ISSUE THREAD

**Issue by mirlang** [nextcloud/android#355] opened 2016-10-23 11:54 UTC
### Actual behaviour
videos are only auto-uploaded while device is charging, no matter if this option is selected in settings or not (i only selected "upload via wifi only")

### Expected behaviour
videos should be uploaded if device is connected via wifi, but connecting charger cable shouldn't be needed
auto-uploading pictures is working properly, btw
 
### Steps to reproduce
1. select "only upload via wifi" for videos
2. deselect "only upload while charging" for videos
3. try it

### Environment data
Android version: 

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by AndyScherzinger** [comment] 2016-10-27 13:20
Hi @mirlang - this is a duplicate of #300 and will be fixed in the next stable release (1.4.0).

**Closed by AndyScherzinger** 2016-10-27 13:20 UTC
