### ISSUE TITLE
Nextcloud on /e/ closes

### ISSUE THREAD

**Issue by WaltherP5c** [nextcloud/android#10289] opened 2022-05-26 13:17 UTC
### Cause of error
```java
Exception in thread "Thread-6" java.lang.IllegalStateException: network interceptor com.nextcloud.common.IPv4FallbackInterceptor@3472f82 must call proceed() exactly once
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:99)
    at com.nextcloud.common.IPv4FallbackInterceptor.retryWithIPv4(IPv4FallbackInterceptor.kt:74)
    at com.nextcloud.common.IPv4FallbackInterceptor.intercept(IPv4FallbackInterceptor.kt:54)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
    at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
    at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:171)
    at com.nextcloud.client.network.ConnectivityServiceImpl.isInternetWalled(ConnectivityServiceImpl.java:81)
    at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:239)
    at com.owncloud.android.utils.FilesSyncHelper$$ExternalSyntheticLambda0.run(Unknown Source:10)
    at java.lang.Thread.run(Thread.java:923)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `generic`

### Device information
* Brand: `google`
* Device: `sunfish`
* Model: `Pixel 4a`
* Id: `RQ3A.211001.001`
* Product: `sunfish`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `eng.root.20220405.060341`

**Comment by AlvaroBrey** [comment] 2022-05-27 08:42
Duplicate of #10039

**Closed by AlvaroBrey** 2022-05-27 08:42 UTC
