### ISSUE TITLE
Crash while  updating photo folder

### ISSUE THREAD

**Issue by anlicata** [nextcloud/android#10277] opened 2022-05-23 07:39 UTC
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: FragmentManager has been destroyed
    at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1585)
    at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
    at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
    at androidx.fragment.app.DialogFragment.show(DialogFragment.java:278)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onSyncFolderSettingsClick(SyncedFoldersActivity.kt:571)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$load$1$1.invokeSuspend(SyncedFoldersActivity.kt:315)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8663)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `q2q`
* Model: `SM-F926B`
* Id: `SP1A.210812.016`
* Product: `q2qxeea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `F926BXXS1CVD2`

**Comment by svenb1234** [comment] 2022-06-07 21:27
Dup of #10273?

**Comment by AlvaroBrey** [comment] 2022-06-08 09:16
Looks like @svenb1234 , thanks

**Comment by AlvaroBrey** [comment] 2022-06-08 09:16
Duplicate of #10273

**Closed by AlvaroBrey** 2022-06-08 09:16 UTC
Labels: bug
