### ISSUE TITLE
nextcloud crashing with stacktrace

### ISSUE THREAD

**Issue by Wiggum127** [nextcloud/android#10704] opened 2022-09-02 09:57 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Open the
Explore files for a while
Application crashes

### Expected behaviour

Continue working

### Actual behaviour

Application crashes

### Android version

7

### Device brand and model

lg g5

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.1

### Nextcloud server version

unknown

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.services.OperationsService$OperationsServiceBinder.isSynchronizing(OperationsService.java:372)
    at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:532)
    at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:521)
    at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:201)
    at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:133)
    at com.owncloud.android.ui.preview.PreviewImageFragment.onPrepareOptionsMenu(PreviewImageFragment.java:381)
    at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:3253)
    at androidx.fragment.app.FragmentManager.dispatchPrepareOptionsMenu(FragmentManager.java:3051)
    at androidx.fragment.app.FragmentManager$2.onPrepareMenu(FragmentManager.java:466)
    at androidx.core.view.MenuHostHelper.onPrepareMenu(MenuHostHelper.java:63)
    at androidx.activity.ComponentActivity.onPrepareOptionsMenu(ComponentActivity.java:497)
    at android.app.Activity.onPreparePanel(Activity.java:3253)
    at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3148)
    at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1936)
    at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2190)
    at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:273)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
    at android.view.Choreographer.doCallbacks(Choreographer.java:683)
    at android.view.Choreographer.doFrame(Choreographer.java:616)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6311)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210190`
* Build flavor: `generic`

### Device information
* Brand: `lge`
* Device: `alicee`
* Model: `LG-H840`
* Id: `NRD90U`
* Product: `alicee_global_com`

### Firmware
* SDK: `24`
* Release: `7.0`
* Incremental: `1808720391303`

**Comment by AlvaroBrey** [comment] 2022-09-02 10:14
Did this happen after deleting a picture? Ref #10580

**Comment by Wiggum127** [comment] 2022-09-02 13:03
Yup.

**Comment by AlvaroBrey** [comment] 2022-09-02 13:43
Duplicate of #10580 then

**Closed by AlvaroBrey** 2022-09-02 13:43 UTC
Labels: bug, needs info
