### ISSUE TITLE
Crash when opening Android app with deactivated account

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [nextcloud/android#8836] opened 2021-08-09 14:42 UTC
### Steps to reproduce
1. Get your user account deactivated
2. Try opening the NextCloud android app

### Expected behaviour
- Non-cryptic error message

### Actual behaviour
- Crash; see below

### Environment data
Android version: 12 (Beta SPB3.210618.016)

Others see below

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:920)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: bramble
Model: Pixel 4a (5G)
Id: SPB3.210618.016
Product: bramble

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: 7566885

```

**Comment by AndyScherzinger** [comment] 2021-08-11 21:37
Duplicate of #8370

**Closed by AndyScherzinger** 2021-08-11 21:37 UTC
Labels: bug
