### ISSUE TITLE
Open the audio player when clicking on the notification

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#7410] opened 2020-11-20 21:14 UTC
Currently, when an audio file is played,a notification appears allowing only to stop t playback. Nothing more.

At the same time, it might be hard to get back to the file that is being played. 

I believe that clicking on the notification should bring us back to the file being played.

**Comment by joshtrichards** [comment] 2023-10-16 19:47
Duplicate of #6782 

Let's centralize discussion/tracking there for this enhancement.

**Closed by joshtrichards** 2023-10-16 19:47 UTC
Labels: enhancement, feature: activity and notification, feature: media player
