### ISSUE TITLE
Beta 20170218 crash after moving directories for autoupload

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/android#669] opened 2017-02-18 21:34 UTC
### Actual behaviour
- From the server move the autoupload directory somewhere else
- From the app open autoupload settings to change
- App hangs while refreshing new content list 
- App crashes
- App won't reopen

### Expected behaviour
- Allow the change with no fuss.
 
### Steps to reproduce
See above. Also video: 

https://www.youtube.com/watch?v=bUiMs8ZqaM8

Just to add it corrected itself and opens again fine, now but it shouldn't have crashed in the first place. No logs available within the app.

### Environment data
Android version: 6.0

Device model: VFD 700

Stock or customized system: Stock

Nextcloud app version: 20170218

Nextcloud server version: 11.0.1

**Comment by tobiasKaminsky** [comment] 2017-02-19 07:59
@mario or @AndyScherzinger (as this might be an old bug and more related to UI)

**Comment by jasonbayton** [comment] 2017-02-19 08:21
A similar scenario:

Try to open a file in a folder that hasn't finished loading yet (dashes still moving across the top) and the app crashes. Wait for it to finish our go to a folder that has previously listed and it's fine.

https://youtu.be/bi9mEI8H3Eo

**Comment by tobiasKaminsky** [comment] 2017-02-19 13:00
Similar yes but not the same. Can you please open up a new issue for this?

**Comment by jasonbayton** [comment] 2017-02-19 13:31
Ok, it seemed to be the same sort of app not fully synced and receiving user input crash.

**Comment by mario** [comment] 2017-02-19 13:43
I'll take a look at the original issue you've mentioned @jasonbayton, but this is probably an old bug.

**Comment by mario** [comment] 2017-02-19 17:00
Cannot reproduce this at all,sorry :(

**Comment by OlivierS1** [comment] 2017-02-22 00:47
I have noticed this since Autoupload has been functionig on the Beta verison.
It seems to me as the crash is happening when the Autoupload folder has been emptied after transfer has been completed.
No log possible for the past 2 weeks or so.
Autoupload seems to crash when "Moved to folder app" is enabled and entire content has been moved to server.
If I use Camera folder, enable Autopuload and "Move to folder app" then upon taking a picture, upload will take place.
Going back to "autoupload" menu will cause the app to crash.

Uninstalling app, or updating it with newer APK will allow app to open normally.
Going back to "Autoupload" and Camaera folder doesn't exist anymore, until pictures are taken again.

**Comment by mario** [comment] 2017-02-22 07:20
OlivierS1, thank you for reporting this. I don't really have the time for such things anymore, but I'll try to take a look. Can you just confirm it happens with this apk as well? (Haven't changed any code for that, but who knows).

https://github.com/nextcloud/android/blob/auto-upload-apk/apks/android-debug.apk?raw=true

**Comment by mario** [comment] 2017-02-22 09:48
Ok, new apk ready - please test the one I posted above!

**Comment by OlivierS1** [comment] 2017-02-22 21:12
Tried app referenced under 1.4.2 RC1 and I did not see any crashes. However, Camera folder do not get emptied entirely.
As far I can tell, behavior is slightly different from Beta.
With Beta, once folder is enable for autoupload and files will be moved to app folder, then upon taking a picture or video (for the camera folder anyway), only the file taken will upload, not the ones previous;y taken that have not been uploaded yet. Not an issue.
Removing all files from camera folder, then taking a picture wil have the corresponding  file uploaded then the folder it originated from becomes empty again.
Folder does remain in the list of Autouploads, which is good as it is possible to edit the corresponding folder options.
No crash then.
So I can say, the issue is resolved.
Beta 20170222 doesn't seem to have this implemented yet.

**Comment by OlivierS1** [comment] 2017-02-23 16:43
Update on 1.4.2 RC1:
Results seems to have been premature. 
It appears more files have been uploaded to the server overnight.
One of the error message poped-up with "Upload failed" and now app is crashing.

I will try the new apk and see how this one works.

**Comment by mario** [comment] 2017-02-23 16:44
@OlivierS1 yes. New APK fixes this - found the issue in the mean time :)

**Comment by mario** [comment] 2017-02-23 16:45
But I can close this issue since this particular issue *is* solved :)

**Closed by mario** 2017-02-23 16:45 UTC
Labels: bug
