### ISSUE TITLE
Disable battery performance at auto upload

### ISSUE THREAD

**Issue by mariannevanharten** [nextcloud/android#14252] opened 2024-12-27 23:25 UTC
### Cause of error
```java
Exception in thread "main" android.content.res.Resources$NotFoundException: Resource ID #0x7f0a0420 type #0x12 is not valid
    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2535)
    at android.content.res.Resources.getLayout(Resources.java:1335)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
    at androidx.appcompat.app.AlertController.setupCustomContent(AlertController.java:644)
    at androidx.appcompat.app.AlertController.setupView(AlertController.java:475)
    at androidx.appcompat.app.AlertController.installContent(AlertController.java:233)
    at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:278)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:810)
    at android.app.Dialog.show(Dialog.java:453)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.showPowerCheckDialog(SyncedFoldersActivity.kt:234)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onDisablePowerSaveCheckClicked(SyncedFoldersActivity.kt:218)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onCreateOptionsMenu$lambda$1(SyncedFoldersActivity.kt:211)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.$r8$lambda$q58-_n5tvnvo7t7SwBQVBpaIAdU(Unknown Source:0)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$$ExternalSyntheticLambda4.onMenuItemClick(D8$$SyntheticClass:0)
    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:984)
    at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
    at android.widget.AdapterView.performItemClick(AdapterView.java:376)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1282)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3528)
    at android.widget.AbsListView.onTouchUp(AbsListView.java:4708)
    at android.widget.AbsListView.onTouchEvent(AbsListView.java:4423)
    at android.widget.ListView.onTouchEvent(ListView.java:1709)
    at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:230)
    at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:138)
    at android.view.View.dispatchTouchEvent(View.java:15076)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3917)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3581)
    at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:10706)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
    at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2947)
    at android.view.View.dispatchPointerEvent(View.java:15335)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7820)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7593)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6927)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6984)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6950)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7148)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6958)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7205)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6931)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6984)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6950)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6958)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6931)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10422)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10270)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10226)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10554)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:335)
    at android.os.Looper.loopOnce(Looper.java:186)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8751)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300690`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `beyond0`
* Model: `SM-G970F`
* Id: `SP1A.210812.016`
* Product: `beyond0lteeea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `G970FXXSGHWC1`

**Comment by joshtrichards** [comment] 2024-12-28 14:54
Duplicate of #13404

**Closed by joshtrichards** 2024-12-28 14:54 UTC
