### ISSUE TITLE
Error Android Samsung a12

### ISSUE THREAD

**Issue by crickxson** [nextcloud/android#8755] opened 2021-07-22 09:01 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList.sort(ArrayList.java:1472)
	at java.util.Collections.sort(Collections.java:206)
	at com.owncloud.android.utils.FileSortOrderByName.sortCloudFiles(FileSortOrderByName.java:52)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.setData(OCFileListAdapter.java:985)
	at com.owncloud.android.ui.fragment.OCFileListFragment$2.doInBackground(OCFileListFragment.java:1567)
	at com.owncloud.android.ui.fragment.OCFileListFragment$2.doInBackground(OCFileListFragment.java:1549)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a12
Model: SM-A125F
Id: RP1A.200720.012
Product: a12nseea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: A125FXXU1BUF9

**Comment by tobiasKaminsky** [comment] 2021-07-23 07:46
Duplicate of https://github.com/nextcloud/android/issues/7782

**Closed by tobiasKaminsky** 2021-07-23 07:46 UTC
Labels: bug
