### ISSUE TITLE
Android app crashed

### ISSUE THREAD

**Issue by monoclecat** [nextcloud/android#13853] opened 2024-10-22 13:12 UTC
### Cause of error
```java
Exception in thread "main" android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{647bed2 u0 com.nextcloud.client/androidx.work.impl.foreground.SystemForegroundService}
    at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315)
    at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286)
    at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8919)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300190`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `dm1q`
* Model: `SM-S911B`
* Id: `UP1A.231005.007`
* Product: `dm1qxeea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S911BXXS6CXGA`

**Comment by joshtrichards** [comment] 2024-10-22 13:42
Duplicate of #13798

**Closed by joshtrichards** 2024-10-22 13:42 UTC
