### ISSUE TITLE
Cannot open Collabora dependant files

### ISSUE THREAD

**Issue by BiglifeMatt** [nextcloud/android#12412] opened 2024-01-26 16:08 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I can view all of my files by folders and lists but cannot open files that would be dependant on Collabora whether they are open extensions or MS extensions.  I can open .md files or images.  I can create new Collabora files such as .docx and edit and save them but cannot open them back up within the app.  It just spins and never loads them.  On the Nextcloud broswer, I can see and edit all of the mentioned files even ones created on the mobile app.  Even deleted and reinstalled the app.  Also connected to three different Nextcloud servers just in case it was the server.

### Expected behaviour

All file types open for viewing and editing just like they do in the website.

### Actual behaviour

Only files that do not require Collabora are opening in the mobile app.  However new files that require Collabora can be created, edited, and saved initially in the mobile app.  They cannot be opened once they are initially created and closed.

### Android version

12

### Device brand and model

OnePlus N200

### Stock or custom OS?

Stock

### Nextcloud android app version

3.27.0

### Nextcloud server version

27.1.3, 28.0.1RC, 28.0.1

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment] 2024-01-26 19:02
Duplicate of #12338 
Fixed in #12350 
Will be in v3.27.1

It was a regression specific to v3.27.0.

**Closed** 2024-01-26 19:02 UTC
Labels: bug
