### ISSUE TITLE
Instant app crash after entering local IP into server address field (self-signed cert)

### ISSUE THREAD

**Issue by Kerbalnut** [nextcloud/android#10888] opened 2022-10-22 02:50 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Fresh TrueNAS 12 install, immediately upgraded to TrueNAS-13.0-U2 (bare metal)
2. Nextcloud auto-install via TrueNAS Jails web GUI (Nextcloud 24.0.6)
3. Install NextCloud 3.22.1 app via Play Store on Android 10, Samsung Note 9 SM-N960U
4. All devices connected to LAN (WLAN)
5. Launch app, Tap Login button
6. Type 192.168.0.7:8283 into server address field and press enter. 
    - Alternatively, scan QR code from Nextcloud web interface: Settings > (Personal) Security > Devices & sessions.
8.  With either method, instant crash. I could kinda make out a very momentary message (appearing right below server address field before crash) about "Could not verify identity of SSL server" or something like that, right before crash screen. Had to repeat many times to work it out, and still not 100% if that's the exact message.

### Expected behaviour

I already know I'm running a self-signed certificate (the default TrueNAS/Nextcloud one(s), so far I've changed very little of any defaults). But most SSL help guides online are about exposing your Nextcloud to the internet, and getting a cert from a real CA. I'm only trying to connect the app to the server via the local ip address with SSL, from the LAN.

I was hoping to get a warning dialog telling me this server uses self-signed cert, and asking if I want to "accept the risks" and proceed with caution. And from what I can make out from the error text, it kinda seems like the app tried to do that? 

Instead, instant crash, everytime. I was kinda expecting some SSL trouble with the whole self-signed part, and would be willing to try setting up my own CA if necessary, but this error makes it sound more like a java error, idk.

FYI, the same local address https://192.168.0.7:8283 for the web interface also works fine from the Android Firefox app, on same Samsung device. (Warns you to proceed with caution first). The Nextcloud file app just seems really cool, I'd love to get it working with proper encryption, even if it's just on my local network. 

### Actual behaviour

Nextcloud crashed

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.LinearLayout com.owncloud.android.databinding.SslUntrustedCertLayoutBinding.getRoot()' on a null object reference
    at com.owncloud.android.ui.dialog.SslUntrustedCertDialog.onCreateDialog(SslUntrustedCertDialog.java:173)
    at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665)
    at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579)
    at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1752)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:8167)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220190`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `crownqltesq`
* Model: `SM-N960U`
* Id: `QP1A.190711.020`
* Product: `crownqltesq`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `N960USQU9FVG2`

### Android version

10

### Device brand and model

Samsung Note 9 SM-N960U

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.1

### Nextcloud server version

24.0.6

### Using a reverse proxy?

No

### Android logs

Attached in comment below.

### Server error logs

```bash
I can post either Nextcloud or TrueNAS error logs here if you like. Full disclosure, the biggest change I made from pure defaults is adding an email client account to Nextcloud, and now the logs are polluted with lots of email errors. I'll remove the email account for now and give it some time to clean up, then try the app a few more times, see if it generates any messages.
```

### Additional information

Because this whole setup is so new, I would (reluctantly) be willing to wipe the whole server side with fresh installs, reset everything to defaults, whatever it takes. There's literally no data on it yet. But idk, this seems more like a java bug or something, or something directly on the phone, as far as I can tell.

**Comment by Kerbalnut** [comment] 2022-10-22 03:35
Android logcat output:

[logcatOutput_issue10888.txt](https://github.com/nextcloud/android/files/9843499/logcatOutput_issue10888.txt)

**Comment by Samalbert977** [comment] 2022-10-22 06:45
Seeing the same issue when entering the IP of the server.

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.LinearLayout com.owncloud.android.databinding.SslUntrustedCertLayoutBinding.getRoot()' on a null object reference
    at com.owncloud.android.ui.dialog.SslUntrustedCertDialog.onCreateDialog(SslUntrustedCertDialog.java:173)
    at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665)
    at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579)
    at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1752)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```
###Using custom OS ?
Yes. LineageOS 19.1 Nightly 20221018

### App information
* ID: `com.nextcloud.client`
* Version: `30220190`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus6`
* Model: `ONEPLUS A6003`
* Id: `SQ3A.220705.004`
* Product: `OnePlus6`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `c39661b4fa`

**Comment by AlvaroBrey** [comment] 2022-10-22 08:05
Duplicate of #10868, will release a fix on Monday

**Closed by AlvaroBrey** 2022-10-22 08:05 UTC
Labels: bug

**Comment by Kerbalnut** [comment] 2022-10-22 22:53
Thank you kindly, you guys are awesome! 👍
