### ISSUE TITLE
Error when registering an old account.

### ISSUE THREAD

**Issue by storm1er** [nextcloud/android#8870] opened 2021-08-19 09:10 UTC
### Steps to reproduce
1. Delete an existing account
2. Reconnect the same account
3. Error appears

### Expected behaviour
We should be connected properly

### Actual behaviour
An error screen appears

### Can you reproduce this problem on https://try.nextcloud.com?
Don't know yet

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

### Logs

<details>

```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:7)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updateUserProfile(RefreshFolderOperation.java:285)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:231)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:363)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6
Model: ONEPLUS A6003
Id: RQ3A.210805.001.A1
Product: OnePlus6

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 433f8f7480
```

</details>

**Comment by AndyScherzinger** [comment] 2021-08-19 15:34
Duplicate of #8370

**Comment by AndyScherzinger** [comment] 2021-08-19 15:35
^ @tobiasKaminsky this might help you reproduce the issue

**Closed by AndyScherzinger** 2021-08-19 15:34 UTC
Labels: bug
