### ISSUE TITLE
Rename files uploaded by sharing with Nextcloud app

### ISSUE THREAD

**Issue by qoheniac** [nextcloud/android#7104] opened 2020-10-16 11:48 UTC
I quite often upload files by sharing them from another app (gallery, email, etc.) with the Nextcloud app. This is super handy! Unfortunately these files (photos, email attachments, etc.) often have quite cryptic names so that I want to rename them. To do so I have to open the Nextcloud app, navigate to the location to which I just uploaded the file and rename it, making the whole upload-by-sharing feature significantly less comfortable. So would it be possible to change the upload-by-sharing feature in such a way that it allows renaming? Maybe the app could ask if one wishes to rename the file or there could be an additional "rename and upload" button or something like that.

**Comment by Chouffy** [comment] 2022-07-07 09:53
This looks like a duplicate of #9215

**Comment by qoheniac** [comment] 2022-07-07 10:00
Yes, they're asking for the same thing. I still think this would be very useful.

**Comment by joshtrichards** [comment] 2023-10-11 14:56
Duplicate of #9215

**Closed by joshtrichards** 2023-10-11 14:56 UTC
Labels: enhancement, needs info
