### ISSUE TITLE
Search for Tags

### ISSUE THREAD

**Issue by ralfi** [nextcloud/android#10551] opened 2022-07-21 16:35 UTC
Hi nextclouders,

it would be very helpful to see (in a file related tab) and search for tags, f.i. autogenerated picture tags in this app.

Best regards!

**Comment by joshtrichards** [comment] 2023-10-19 16:47
Duplicate of #8958 

Let's consolidate tracking of this feature there. Feel free to subscribe/upvote that issue. Thanks for your contribution!

**Closed by joshtrichards** 2023-10-19 16:47 UTC
Labels: enhancement, feature: search, feature: tags
