### ISSUE TITLE
App crashes when moving many files

### ISSUE THREAD

**Issue by ternite** [nextcloud/android#6003] opened 2020-05-04 19:59 UTC
### Steps to reproduce
1. Browse cloud files (not local files) 
2. Open an images folder with 618 images (can't tell how many files you need to reproduce - I have 618 and can reliably reproduce the bug) . This folder also contains another folder named '2020'.
3. Long press any image file.
4. Choose the menu button on the upper right corner. 
5. Choose select all. 
6. Manually deselect the folder '2020'.
7. Choose the menu button in the upper right corner, again. 
8. The app crashes. 

### Expected behaviour
- The app should show a selection screen to choose the folder to move the files into. 

### Actual behaviour
- The app crashes. 

### Can you reproduce this problem on https://try.nextcloud.com?
- Not applicable, as this is clearly a problem exclusively related to the app, not the web frontend.
- I even tried nevertheless, but there are simply not enough files to test. 

### Environment data
Android version: 9.1.0
Device model: HUAWEI P30 Pro
Stock or customized system: Stock

Nextcloud app version: 3.11.1

Nextcloud server version: 18.0.4.2

Reverse proxy:? 

#### Web server error log
```
Need info on where to get this. 
```

#### Nextcloud log (data/nextcloud.log)
```
Need info on where to get this. 
```

**Comment by ternite** [comment] 2020-05-04 20:08
1. If I select a subset of 74 images manually, the app does not crash.
2. For completeness: a screenshot of my app the moment before I try to move the selected files. 
![Screenshot_20200504_220706](https://user-images.githubusercontent.com/7860777/81008704-a6cb6a00-8e53-11ea-9a56-33bcf838d312.jpg)

**Comment by ternite** [comment] 2020-05-04 20:18
This might be interesting: I manually selected two sets of images and moved them. Afterwards, there were 495 images left in said folder. I could move them, using the described process, i. e. by using "Select all" and then select "Move".

**Comment by tobiasKaminsky** [comment] 2020-05-05 05:47
![2020-05-05-074655](https://user-images.githubusercontent.com/5836855/81037904-9b545f00-8ea4-11ea-92ef-7863cda6036a.png)

For me this does not happen.
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by tobiasKaminsky** [comment] 2020-05-05 05:48
Ah. You have to click move…
So moving 6k images will crash with
```
   Process: com.nextcloud.client, PID: 6616
    java.lang.RuntimeException: Failure from system
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1711)
        at android.app.Activity.startActivityForResult(Activity.java:5192)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
        at android.app.Activity.startActivityForResult(Activity.java:5150)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
        at com.owncloud.android.ui.fragment.OCFileListFragment.onFileActionChosen(OCFileListFragment.java:1151)
        at com.owncloud.android.ui.fragment.OCFileListFragment$MultiChoiceModeListener.onActionItemClicked(OCFileListFragment.java:687)
        at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2604)
        at androidx.appcompat.view.SupportActionModeWrapper$CallbackWrapper.onActionItemClicked(SupportActionModeWrapper.java:172)
```

**Comment by tobiasKaminsky** [comment] 2020-05-05 05:49
I assume that passing too many values via intent will just crash…

**Comment by ezaquarii** [comment] 2020-05-05 18:50
On Mon, May 04, 2020 at 10:49:12PM -0700, Tobias Kaminsky wrote:
> Ah. You have to click move…
> So moving 6k images will crash with

Is this internal application intent? If so, we can probably try
2 approaches:

1. try content compression
2. pass the list as a key to an off-intent argument store

**Comment by joshtrichards** [comment] 2024-10-27 13:40
Duplicate of #7978

**Closed by joshtrichards** 2024-10-27 13:40 UTC
Labels: bug, approved, performance: general/non-specific
