### ISSUE TITLE
Readme.md header gets stuck sometimes 

### ISSUE THREAD

**Issue by exploids** [nextcloud/android#11347] opened 2023-02-05 11:51 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Tap any Readme.md header to view the entire thing
2. It's now duplicated and stuck like this:

https://user-images.githubusercontent.com/32574654/216816999-59acc4ce-4ae2-456c-939a-a0f3655ba75a.mp4

### Expected behaviour

It shouldn't do that.

### Actual behaviour

It does do that.

### Android version

10

### Device brand and model

Huawei MAR-LX1B

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.0 RC2

### Nextcloud server version

24.0.8

### Using a reverse proxy?

I don't know

### Additional information

There is no log file and I'm not installing adb.

**Comment by AlvaroBrey** [comment] 2023-02-06 11:27
Duplicate of #9701

**Closed by AlvaroBrey** 2023-02-06 11:27 UTC
Labels: bug
