### ISSUE TITLE
Nextcloud crash on large upload

### ISSUE THREAD

**Issue by Echelon101** [nextcloud/android#5104] opened 2020-01-06 19:33 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e099df8 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6013
Id: QKQ1.190716.003
Product: OnePlus6T

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 1912142009

**Comment by AndyScherzinger** [comment] 2020-01-09 14:54
duplicate of #2010

**Closed by AndyScherzinger** 2020-01-09 14:54 UTC
Labels: bug
