### ISSUE TITLE
[dev] App crashes while deleting a file

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#7115] opened 2020-10-20 11:15 UTC
### Steps to reproduce

1. Create a file.
2. Delete file.
3. Select "Deleted Files" from the menu.
4. Delete file.

```
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e3ecbad u0 com.nextcloud.android.beta/com.nextcloud.client.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2313)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201020
Build flavor: versionDev
```

### Environment data
Android version: 10

Nextcloud app version: 20200120 Dev

Nextcloud server version: 20.0.0

**Comment by zeeshanbeg** [comment] 2020-10-28 14:11
does app crashes on deleting any type of file or specific type ?

**Comment by AndyScherzinger** [comment] 2020-10-28 14:14
@Valdnet can you constantly/consistently reproduce this?

Just asking since your error message refers to 
com.nextcloud.android.beta/com.nextcloud.client.media.PlayerService
and starting foreground services, none of which has anything to do with file deletions :/

**Comment by Valdnet** [comment] 2020-10-28 14:41
@AndyScherzinger I double-checked again and the app crashes right after deleting the file from the recycle bin. The file is deleted and after a while the application crashes. It is like this every time.

**Comment by AndyScherzinger** [comment] 2020-10-28 17:52
@Valdnet if it happens after a while the question is if it would happen even without you deleting a file from the recycle bin

**Comment by Valdnet** [comment] 2020-10-30 12:21
@AndyScherzinger I noticed that this also happens without deleting the file. Just choose "Deleted Files" from the menu and wait for a while. With dev-20201030, this isn't always the case.

**Comment by tobiasKaminsky** [comment] 2020-11-11 08:36
Duplicate of #6905, as it is the same root cause.

**Closed by tobiasKaminsky** 2020-11-11 08:36 UTC
Labels: bug, needs info/discussion
