### ISSUE TITLE
App randomly starts to crash, Android 13, LineageOS 20

### ISSUE THREAD

**Issue by macearl** [nextcloud/android#11329] opened 2023-01-30 14:20 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I can't fully reproduce this, so I'll try to explain when and how the crashes started for me:

I recently upgraded to LineageOS 20 (Android 13) after that the issues started, with Los 19 / Android 12 I had no problems. 

The issue exists with 3.23.1 and 3.23.0 (I did not try downgrading to older versions than that) 

After setting up the app everything seems to work for a couple of days, I can use the files and news app without a problem. 

Then after a few days without changing anything the app can start to crash repeatedly, I had this happen while just trying to launch the Files app, as well as while trying to start the news app, which just shows an error, that the files app is not responding, after that I cannot open the files app anymore. It just keeps repeatedly crashing, even without clicking on the app again.  E.g.
1. I try to open the file or news app
2. The files app crashes
3. Seemingly the files app is started again in the background and crashes instantly

While trying to grab a stack trace through `scoop` this leads to hundreds of notifications for every crash, the uncontrollable crashes only stop if I reboot my phone. 

### Expected behaviour

The app should start without a crash

### Actual behaviour

The app repeatedly crashes

### Android version

13

### Device brand and model

Xiaomi Pocophone F1

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.2.1

### Nextcloud server version

25.0.3

### Using a reverse proxy?

No

### Android logs
```
FATAL EXCEPTION: WM.task-1
Process: com.nextcloud.client, PID: 10897
java.lang.IllegalArgumentException: context is null
	at android.accounts.AccountManager.get(AccountManager.java:593)
	at com.owncloud.android.lib.common.OwnCloudAccount.<init>(OwnCloudAccount.java:75)
	at com.nextcloud.client.account.UserAccountManagerImpl.createUserFromAccount(UserAccountManagerImpl.java:198)
	at com.nextcloud.client.account.UserAccountManagerImpl.getUser(UserAccountManagerImpl.java:240)
	at com.owncloud.android.utils.theme.MaterialSchemesProviderImpl.getMaterialSchemesForCurrentUser(MaterialSchemesProviderImpl.kt:63)
	at com.nextcloud.client.di.ThemeModule$Companion.provideMaterialSchemes(ThemeModule.kt:55)
	at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.provideMaterialSchemes(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:40)
	at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.get(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:30)
	at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.get(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:13)
	at com.owncloud.android.utils.theme.ViewThemeUtils_Factory.get(ViewThemeUtils_Factory.java:32)
	at com.owncloud.android.utils.theme.ViewThemeUtils_Factory.get(ViewThemeUtils_Factory.java:12)
	at com.nextcloud.client.jobs.BackgroundJobFactory.createMediaFoldersDetectionWork(BackgroundJobFactory.kt:214)
	at com.nextcloud.client.jobs.BackgroundJobFactory.createWorker(BackgroundJobFactory.kt:95)
	at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:83)
	at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:245)
	at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137)
	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

## Additional Information
I'm running LineageOS 20 instead of a vendor or stock AOSP ROM

If I uninstall the files app and start setting it up again from scratch everything works again for a couple of days, after which the app always crashes until I do another complete reinstall

**Comment by AlvaroBrey** [comment] 2023-01-30 14:24
3.2.0? That is a really old version, do you mean 3.23.0?

**Comment by macearl** [comment] 2023-01-30 14:27
Sorry, yes I meant 3.23.0 and 3.23.1

**Comment by AlvaroBrey** [comment] 2023-02-22 14:09
Duplicate of #11026

**Closed by AlvaroBrey** 2023-02-22 14:09 UTC
Labels: bug

**Comment by whatever88oi** [comment] 2025-12-30 21:37
game app (MLBB) keep crashing on GSI LineageOS 20 android 13. there is this " tab to restart app in full screen " bottom right secreen with four arrow comming out and the app restart or just log out by it self. always happend in rank mode just before or after i pick my hero then the crash/restart/log out happend. even thou i didt push the 4 arrow button. any clue on how to fix this. tq and sorry for the trouble just new in this and still learning. need some help.
