### ISSUE TITLE
Autoupload not working in Andorid 7

### ISSUE THREAD

**Issue by jamfx** [nextcloud/android#612] opened 2017-01-31 17:42 UTC
### Actual behaviour
-Take a Photo. Wait for upload. Die...

### Expected behaviour
-Take a Photo. Looking how it loads up. Be happy. :)
 
### Steps to reproduce
1. Install NextCloud App (even with Beta)
2. Take a Photo.
3. Wait for upload, which never happens... :(

### Environment data
Android version:
Android 7.0 Patchlevel, 1. December 2016

Device model: 
Honor 8, no root.

Stock or customized system:
Nothing customized. No Root. Just a simple Phone. (But also happened on my Nexus 5x with Android 7)

Nextcloud app version:
Nextcloud Beta Version 20170130

Nextcloud server version:
Nextcloud 11.0.0

Surely this issue is reported already, but I couldn't find it. So please feel free to merge / close. But please, do something about this issue soon! Thanks a lot!

**Comment by tobiasKaminsky** [comment] 2017-01-31 20:28
Have you configured AutoUpload the right way?
Can you test a 3rd party camera app? (there are some vendors that cause some problems with their stock camera)

**Comment by jamfx** [comment] 2017-01-31 20:41
Yes, I configured it right away. I double checked now. Everything as I think it should.
I tried the following Cam Apps:
a) Build-In Camera
b) Google Camera (Extra App from Google-Play Store)
c) Perfectly Clear App

None of these triggered an upload. :(

**Comment by bekl101** [comment] 2017-02-01 09:14
Same problem with Galaxy S7 7.0.
No upload action after taking a picture, neither taking a screenshot.
upload is only working when i copy a picture manually to "/storage/emulated/0/DCIM/Screenshots with a file-manager.
there is also no action when the build in camera-app uses the SD-CARD as storage.

**Comment by jamfx** [comment] 2017-02-01 09:59
Nice points! I have my pictues on the SD-Card, too! Screenshots have never been uploaded. Also, the upload is not triggered, if I copy the image somewhere. Upload just never starts.

**Comment by KekcuHa** [comment] 2017-02-01 13:55
Confirm that, no autoupload at nextcloud android app beta 20170130 at SGS7.

**Comment by KekcuHa** [comment] 2017-02-01 14:00
Seems to be double of #498 ([link](https://github.com/nextcloud/android/issues/498))

**Comment by mario** [comment] 2017-02-01 21:36
@KekcuHa SGS7 has only Android 6 though, right?

**Comment by bekl101** [comment] 2017-02-02 04:42
@mario
No, since last week 7.0 is rolled out by Vodafone on SGS7

**Comment by KekcuHa** [comment] 2017-02-02 08:01
@mario, no, SGS7 now on Android 7.0 as been already pointed by @bekl101 
The same situation (no autoupload at beta client) at LG G Pro2 running on Android 5.0.1.

**Comment by mario** [comment] 2017-02-02 08:02
Thanks for letting me know - there is SGS7 among my phones, but no Android 7 yet on it. Anyway, I'm looking into the issues. As for now, AutoUpload is only on 7 (we hope to bring it to 5 and 6), and 4,5,6 use InstantUpload (older version).

That being said, AutoUpload does have it's issues that I'm currently correcting.

**Comment by bekl101** [comment] 2017-02-02 08:42
is there a temporary workaround to sync photos taken on my mobile with the nextcloud server until the Autoupload problem is fixed?
@mario 
if you need logs from the beta let me know.

**Comment by kubjo** [comment] 2017-02-02 10:40
Same issue with LG G5 Android 7.0   Nextcloud Beta 20170130

**Comment by mario** [comment] 2017-02-02 11:05
Hello,

it looks like I've determined the root cause of the problem, but I have to figure out how/if it's easy to fix or not.

Thank you for your patience!

**Comment by daymr** [comment] 2017-02-02 14:06
Can confirm.. verizon galaxy s7 android 7.0 beta 2 Nov 22 build.. autoupload is ENTIRELY broken and does not function with any camera app or storage location. Please fix. Thanks for the awesome dev work!

**Comment by mario** [comment] 2017-02-02 20:46
So it seems that the problem is bigger than we thought - some phones (Galaxy ones in particular) just don't emit the right information that we need to make autoupload work. As such, we need to rethink how we're gonna handle uploads in the future and pave a way to true two-way sync.

**Comment by jamfx** [comment] 2017-02-02 21:04
Hi Mario,
for my Side, I don't need a two-way-sync on my phone. I just would love to have a Picture Upload. Maybe this can be reviewed in a first way?
If I can help for this somehow, let me know.

**Comment by mario** [comment] 2017-02-02 22:52
I have strong reasons to believe the Auto upload will be fixed soon as I am working on rewriting our upload service, and will be brought to Android 5.x and 6.x as well. 4.x can be expected, but I do now know when - until then, Instant upload can be used there (when it works(.

**Comment by mario** [comment] 2017-02-02 23:34
Fix ready (https://github.com/nextcloud/android/pull/615), we'll hopefully have it in beta soon!

**Comment by mario** [comment] 2017-02-05 00:16
Few issues with the fix, working on it!

**Comment by daymr** [comment] 2017-02-05 03:14
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
	at android.os.Parcel.readException(Parcel.java:1701)
	at android.os.Parcel.readException(Parcel.java:1646)
	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:158)
	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
	at com.owncloud.android.services.FileAlterationMagicListener.onFileCreate(FileAlterationMagicListener.java:103)
	at org.apache.commons.io.monitor.FileAlterationObserver.doCreate(FileAlterationObserver.java:379)
	at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:345)
	at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:304)
	at org.apache.commons.io.monitor.FileAlterationMonitor.run(FileAlterationMonitor.java:182)
	at java.lang.Thread.run(Thread.java:761)

************ DEVICE INFORMATION ***********
Brand: Verizon
Device: heroqltevzw
Model: SM-G930V
Id: NRD90M
Product: heroqltevzw

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: G930VVRU4ZPKC

**Comment by daymr** [comment] 2017-02-05 04:02
Unrecoverable crash screen appears every 10 seconds! Even on reboot.. guess clear program data?

**Comment by mario** [comment] 2017-02-05 11:18
Working on a new beta. Hopefully Tuesday.

**Comment by JSoko** [comment] 2017-02-06 09:52
I have also that crashscreen on SGS 7 nougat with beta 170204:
```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
at android.os.Parcel.readException(Parcel.java:1701)
at android.os.Parcel.readException(Parcel.java:1646)
at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:158)
at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
at com.owncloud.android.services.FileAlterationMagicListener.onFileCreate(FileAlterationMagicListener.java:103)
at org.apache.commons.io.monitor.FileAlterationObserver.doCreate(FileAlterationObserver.java:379)
at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:345)
at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:304)
at org.apache.commons.io.monitor.FileAlterationMonitor.run(FileAlterationMonitor.java:182)
at java.lang.Thread.run(Thread.java:762)

************ DEVICE INFORMATION ***********
Brand: samsung
Device: herolte
Model: SM-G930F
Id: NRD90M
Product: heroltexx

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: G930FXXU1DPLT
```

**Comment by mario** [comment] 2017-02-06 09:54
170206 should fix it.

**Comment by bekl101** [comment] 2017-02-06 11:14
crashscreen after installing 170206 with a previous app version (170204). 
after removing 170204 and installing 170206 no crashscreen.
autoupload tested with a few new piktures seems to work as expected.

**Comment by jamfx** [comment] 2017-02-06 18:19
I tried Nextcloud 20170206 beta and still have no auto upload on my Phone. I didn't had crashes in earlier versions... Just no Auto Upload at all.

**Comment by mario** [comment] 2017-02-06 18:20
That sounds strange @jamfx - have you configured this in the Auto Upload screen?

**Comment by jamfx** [comment] 2017-02-06 18:34
Yes, where else could this be configured?

**Comment by bekl101** [comment] 2017-02-06 18:39
really strange, after successfull testing a few hours ago. Now i took a pikture and nothing happens. Nothing changed. Mobile rebooted an now AutoUpload works again, like nothing went wrong before.
Maby a powersafe problem in Nougat?

**Comment by jamfx** [comment] 2017-02-06 18:54
Hmm, shouldn't it start uploading when I get back to the Nextcloud App? I will have a look at the power savings. And will get back to you.

**Comment by tobiasKaminsky** [comment] 2017-02-06 19:00
No, it uses the doze mode. So the upload is "registered" to the android job scheduler. And if android decides to execute the job the file will be uploaded.

**Comment by bekl101** [comment] 2017-02-06 19:07
@tobiasKaminsky 
thanks for the explanation. Mh, maybe i didn´t wait long enough. I will test it tomorrow morning again and give you a response if it works or not

**Comment by bekl101** [comment] 2017-02-06 19:10
i´m not in a hurry. I´m happy that this feature will work again. 
great work

**Comment by jamfx** [comment] 2017-02-06 19:17
Even if I wait about 5 Minutes it doesn't start. Although the picture is shown in the auto upload preview, where I can select the folders. 
I double checked the Battery Saving Settings and the app is not on the "close" list.

**Comment by bekl101** [comment] 2017-02-07 04:54
Tested again, without changing anything. works as expected.

**Comment by jamfx** [comment] 2017-02-07 06:34
@bekl101 I did the following: 
Downloaded the latest version (20170207) this morning. Just switched on Auto Upload. Took a Picture, waited. Nothing happened. BUT after a about 10 seconds the upload started! So it worked somehow. I will try to confiugure my other settings (i.e. default Path of App, subfolders on auto upload...) and will leave another comment here. A BIG THANKS FOR YOUR WORK! <3 :1st_place_medal:

**Comment by jamfx** [comment] 2017-02-07 06:42
Okay, hold on once more. I found another bug in this Version. It starts uploading the picture TWICE! So first upload goes through, but second upload fails. The App just recognizes the picture twice and tries to upload both pictures with the same name. So second upload fails.

**Comment by mario** [comment] 2017-02-07 07:14
Hello, there will be another version tomorrow with bugfixes. Once it's out, please delete the current beta and install the new one :)

**Comment by jamfx** [comment] 2017-02-07 07:16
@mario Nice! Just drop me a line to test it again! So far I will use the "buggy" App. I prefere to use this and delete the "double" upload, than having none... :)

**Comment by mario** [comment] 2017-02-07 07:16
Yea, well ... the "other" upload of the same image won't work anyway due to a different bug :p cc @tobiasKaminsky

**Comment by bekl101** [comment] 2017-02-07 08:00
clean installed 20170207 upload works. but possible onother bug.
first i used the default place to store picture uploads (SoforUpload/Camera) it work correct (exept known double upload).
Afterwards i changed the destination to another folder on my NC, took a picture and it was transfered to the default place again.
Uninstalled and new installed, i changed the path before taking a picture, than changed target folder but this had no effect . The pictures were stored in the first selected place

**Comment by JSoko** [comment] 2017-02-07 08:22
At sgs7 nougat with 20170207 instant upload now works to the SofortUpload folder :-)

**Comment by mario** [comment] 2017-02-07 08:23
@bekl101 known bug, will hopefully be fixed by the time 20170208 lands :)

**Comment by bekl101** [comment] 2017-02-07 08:26
ok, if you know it .
@mario sorry for OT
do you know something about the problem saving files for offline use to sd-card on a SGS7?

**Comment by mario** [comment] 2017-02-07 12:51
@bekl101 what issue number? I can test this directly since I have that phone :)

**Comment by mario** [comment] 2017-02-07 12:51
Folks, new build coming up tomorrow!

**Comment by bekl101** [comment] 2017-02-07 13:36
@mario 
#612 
You can see that the file is downloadet to a temp directoy but no move to card afterwards.

**Comment by bekl101** [comment] 2017-02-08 06:53
tested 20170208 after clean install.
Autoupload seems to work , no doble uploads like yesterday.
but i didn´t find a log file, neither in the app, nor on filesystem.

**Comment by jamfx** [comment] 2017-02-08 08:11
This Version (20170208) works for me! No double Uploads and Uploads start quite quickly. Nice! Thanks a lot!

**Comment by bekl101** [comment] 2017-02-08 08:39
@jamfx 
do you see the log within the app?
sync seems to be stable

**Comment by jamfx** [comment] 2017-02-08 08:50
As far as I can see, nope... sorry, no logs.

**Comment by mario** [comment] 2017-02-08 10:01
@bekl101 what does "Nextcloud beta wird wiederholt beendet App schließen" means?

**Comment by mario** [comment] 2017-02-08 10:03
@bekl101 I just noticed you linked me to this issue, instead of the one relevant for SD card? :)

**Comment by bekl101** [comment] 2017-02-08 10:04
That means, there comes a popup which told you that the application stops working several times and will be closed

**Comment by mario** [comment] 2017-02-08 10:04
Niiice! :) Will investigate.

**Comment by mario** [comment] 2017-02-08 10:10
As for logs ... dunno, my code shouldn't affect logs at all.

**Comment by bekl101** [comment] 2017-02-08 10:11
you´re right #476 is the right issue.
sorry for confusing you :)

**Comment by JSoko** [comment] 2017-02-08 14:23
Hello, 
on sgs7 nougat 20170208 works for me. Autouploads are working an no double uploads...
Thank You! 👍 

The logs window in the app is empty, but the currentLog.txt has 143 kb

**Comment by mario** [comment] 2017-02-08 15:21
Glad this is working, thanks folks!

There will be some changes tomorrow to auto-upload so please test it as well.

I will close this ticket now, but please feel free to re-open it if issues crop up again.

**Closed by mario** 2017-02-08 15:21 UTC
Labels: pr exists

**Comment by RogerSik** [comment] 2017-02-12 20:48
Sorry for re-opening. When we can count with Version 1.4.2?

**Comment by mario** [comment] 2017-02-13 08:29
@RogerSik RC1 soon hopefully :)

**Comment by mario** [comment] 2017-02-13 08:31
@bekl101 new beta!!

https://github.com/nextcloud/android/raw/beta/apks/latest.apk

**Comment by bekl101** [comment] 2017-02-13 12:27
@mario 
shot question to Autoupload.
Is it correct that when i activate "delete file after upload" the taken picture is stored on my NC, in the folder on my local SD-Card and the original file in DCIM is deleted?
If yes maby i have a small issue. Everything works but the file is not deleted.

**Comment by tobiasKaminsky** [comment] 2017-02-13 15:32
@bekl101 if you choose "delete file after upload" there should be no file left on the device after a successful upload. It is the same as uploading it and then delete the local copy AND the original file.

**Comment by mario** [comment] 2017-02-13 20:03
@tobiasKaminsky it doesn't do that. Can you look into it tomorrow please, if you have the time?

**Comment by bekl101** [comment] 2017-02-14 05:21
ok, also it wasn´t my fault.
Same problem if you choose "move file to app folder"

**Comment by tobiasKaminsky** [comment] 2017-02-14 07:08
Is the source file on an external storage? I remember that this can lead to problems where the file cannot be deleted and fails silently. This would explain why both is not working as the file needs to be deleted in both cases.

**Comment by bekl101** [comment] 2017-02-14 08:29
Yes, source is an external storage (sd-card). Later i can test with pictures seved to internal storage.

**Comment by Wikinaut** [comment] 2017-03-01 21:52
Same problem Android 7.0 on HUAWEI P8 LITE 2017 (Auto backup does not work)

**Comment by mario** [comment] 2017-03-01 21:52
What version @Wikinaut ?

**Comment by mario** [comment] 2017-03-01 21:52
All should be fixed in beta.

**Comment by Wikinaut** [comment] 2017-03-01 21:53
Android Nextcloud 1.4.1

**Comment by mario** [comment] 2017-03-01 21:54
Cool. Should be fixed in beta and 1.4.2 so worry not :)

**Comment by Wikinaut** [comment] 2017-03-01 22:52
@mario I compiled the beta, but the App-PIN entry does not work when trying to contact my instance in the 1.4.2RC1 version.... and so I cannot contact my server with this beta version..... :-1:

**Comment by datasmurfen** [comment] 2017-07-25 22:29
I am haveing the same issue :-1:
