### ISSUE TITLE
Low FPS on media screen

### ISSUE THREAD

**Issue by exploids** [nextcloud/android#11346] opened 2023-02-05 11:29 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Go to the media screen
2. Wait for the thumbnails to load
3. Scroll to observe the incredibly low frame rate (under 5 FPS in my case)

### Expected behaviour

I'd expect the frame rate on the media screen to be roughly the same (60 FPS, I guess) as on any other screen in the app.

### Actual behaviour

It's incredibly low, as soon as the thumbnails are loaded.

### Android version

10

### Device brand and model

Huawei MAR-LX1B

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.0 RC2

### Nextcloud server version

24.0.8

### Using a reverse proxy?

I don't know

### Additional information

There is no log file and I'm not installing adb.

**Comment by AlvaroBrey** [comment] 2023-02-06 13:07
Duplicate of #10882

**Closed by AlvaroBrey** 2023-02-06 13:07 UTC
Labels: bug
