### ISSUE TITLE
App colors white on white

### ISSUE THREAD

**Issue by vincentstans** [nextcloud/android#1747] opened 2017-11-05 13:04 UTC
### Actual behaviour
I see no folders as the map tile is white and the background is also white.
When selecting multiple files to upload, selected box is not become blue, the line becomes gray but so are a lot of unselected lines.
This has annoyed me for months and am suprised no has his web color to white.

### Expected behaviour
Logic coloring
 
### Steps to reproduce
1. Through the web interface change the theme color to white #FFFFFF
2. when i today decided to change that color to blue all the colors were correct in the android app.
3. Didnt know that the web colors affected the app.

### Environment data
Android version:
6 & 7
Device model: 
Samsung tablet a6
Huawei p8
Umi digi z

Stock or customized system:
Stock

Nextcloud app version:
2.0.0 aswell as beta version

Nextcloud server version:
12.0.0

### Logs
Irrelevant

#### Web server error log
No errors
Insert your webserver log here
Nothing to log

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2017-11-06 06:58
Starting with 2.0 we use the server color for theming.
This is a duplicate of #1308, thanks for reporting.

**Closed by tobiasKaminsky** 2017-11-06 06:58 UTC
Labels: bug, design
