### ISSUE TITLE
Grey squares in image gallery after photos autoupload

### ISSUE THREAD

**Issue by dmitry-podporinov** [nextcloud/android#7347] opened 2020-11-17 13:57 UTC
### Steps to reproduce
1. Set up camera folder autoupload
2. Make photo
3. Wait for photo upload to server

### Actual behaviour
After success sync any gallery app or multimedia storage shows that folder Pictures contains 0-bytes size synced photo file with the same name as synced photo, and gallery shows grey square

### Can you reproduce this problem on https://try.nextcloud.com?
Not applicable. It's just android application problem.

### Environment data
Android version: Android 10 AOSP, Android 10 samsung OneUI core 2.1

Device model: 
Xiaomi redmi 4 prime, Samsung Galaxy M51

Stock or customized system:
OneUI 2.1 - stock, AOSP - customized

Nextcloud app version:
3.13.1
Nextcloud server version:
19.0.4
Reverse proxy:
none
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by aqaqsubin** [comment] 2020-11-17 15:12
This 0 byte file seems to be the ghost file shown in #6558.
I think it's a duplicate error.

**Comment by AndyScherzinger** [comment] 2020-11-17 15:25
Duplicate of #6558

**Comment by AndyScherzinger** [comment] 2020-11-17 15:26
You're right @aqaqsubin 👍 It's a duplicate

**Closed by AndyScherzinger** 2020-11-17 15:25 UTC
Labels: bug
