### ISSUE TITLE
Endless loading of a file

### ISSUE THREAD

**Issue by GambaJo** [nextcloud/android#13224] opened 2024-07-03 10:24 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I sync my keepass file to my 2 android devices.

### Expected behaviour

The file is synced in the background.

### Actual behaviour

Sometimes a notification apperas, that only says "Downloading...". And nothing happans. I can't swipe the notification away, it stays untill I restart the device or kill the Nextclod Android app.

![grafik](https://github.com/nextcloud/android/assets/1378907/968a95a3-2654-4a5e-ba63-0542cbe652f5)

### Android version

12 & 14

### Device brand and model

Samsung Galaxy S10 & Samsung Galaxy Tab S7 FE

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.1

### Nextcloud server version

Nextcloud Hub 8 (29.0.2)

### Using a reverse proxy?

I don't know

**Comment by GambaJo** [comment] 2024-07-05 10:27
Today I have for the first time even 2 of this notifications:
![grafik](https://github.com/nextcloud/android/assets/1378907/149912f7-f980-4a06-9cc3-d788e1590f98)

**Comment by joshtrichards** [comment] 2024-07-07 20:55
Duplicate of #12711 
Fixed in #13145

**Closed by joshtrichards** 2024-07-07 20:55 UTC
Labels: bug
