### ISSUE TITLE
App crashes after returning from lockscreen after audio ended playing

### ISSUE THREAD

**Issue by NicolasGoeddel** [nextcloud/android#8852] opened 2021-08-12 11:44 UTC
### Steps to reproduce
1. Go to a folder with an audio file, e.g. a MP3 and play it with the internal player
2. Put your phone into standby, so it plays the music in the background
3. Wait until the song has ended
4. Unlock your phone again
5. You will see the player with the warning "Der interne Player kann die Mediendatei nicht abspielen"
5. Try to tap on the top left arrow to get back to the folder view
5. Nextcloud crashes instantly

Reproducible every time.

### Expected behaviour
- After coming back from the lockscreen you should be able to play the audio again or to go back to the folder view

### Actual behaviour
- First an error is popping up, then the whole app crashes

### Can you reproduce this problem on https://try.nextcloud.com?
- This has nothing to do with the server backend

### Environment data
Android version: 10
OxygenOS-Version: 10.0.1
Device model: Oneplus A5000
Stock or customized system: OxygenOS
Nextcloud app version: 3.17.0 RC3
Nextcloud server version: 20.0.11
Reverse proxy: Apache 2.4.46

### Error screen
![image](https://user-images.githubusercontent.com/1520064/129191218-0b5e17d6-1eff-4187-9e15-1b83dd5af25e.png)

### Related
Maybe related to https://github.com/nextcloud/android/issues/8840

**Comment by AlvaroBrey** [comment] 2021-09-09 09:11
Duplicate of #8686

**Closed by AlvaroBrey** 2021-09-09 09:11 UTC
Labels: bug
