### ISSUE TITLE
Crash browsing through external storage

### ISSUE THREAD

**Issue by ksd73429udmn** [nextcloud/android#7232] opened 2020-11-04 18:47 UTC
### Steps to reproduce
1. Open App
2. Browse External mounted storage (HDD)

### Expected behaviour
You should be able to sync the folders. I was able to browse through it before. I recently added extra columns and rows as nextcloud suggested to do at the web interface and added two components to php.

added:
occ db:add-missing-indices
occ db:add-missing-columns

added:
php7.3-gmp
php7.3-bcmath

Also I recently renamed a folder on the external storage form "Backups" to "+++Backups+++"

### Actual behaviour
The app chrashes, I am not able to browse through the folders.
No problems on other plattforms (same app version on LOS 17 Tablet works)

### Environment data

************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=2565, totalRows=924
at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:895)
at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:157)
at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:190)
at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:299)
at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:320)
at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:474)
at android.content.ContentResolver.applyBatch(ContentResolver.java:1627)
at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:435)
at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:490)
at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:372)
at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:231)
at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: lilac
Model: G8441
Id: PQ3A.190801.002
Product: lilac

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.asn.20200211.095357

------------------
Nextcloud log:

fseek() expects parameter 2 to be int, float given at /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php#82

**Comment by tobiasKaminsky** [comment] 2020-11-12 14:55
Duplicate of #6688

**Closed by tobiasKaminsky** 2020-11-12 14:55 UTC
Labels: bug
