### ISSUE TITLE
Crash on Android 10 while syncing an folder 

### ISSUE THREAD

**Issue by Paule89DE** [nextcloud/android#6038] opened 2020-05-10 07:52 UTC
Error syncing folder with mobile. I think caused by special bars on filename. 

Problem caused on try sync an 700mb mp3 folder. File list can be requested by message. 

- sorry I am new on github, I hope this Informations can help you to debug our app. 
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start service com.owncloud.android.services.OperationsService@9316e8c with Intent { act=SYNC_FOLDER cmp=com.nextcloud.client/com.owncloud.android.services.OperationsService (has extras) }: java.lang.ClassCastException: com.nextcloud.client.account.RegisteredUser cannot be cast to android.accounts.Account
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4346)
	at android.app.ActivityThread.access$1800(ActivityThread.java:269)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2042)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7860)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
Caused by: java.lang.ClassCastException: com.nextcloud.client.account.RegisteredUser cannot be cast to android.accounts.Account
	at com.owncloud.android.services.OperationsService.onStartCommand(OperationsService.java:196)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4328)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a6plte
Model: SM-A605FN
Id: QP1A.190711.020
Product: a6pltexx

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: A605FNXXU5CTC8

**Comment by ezaquarii** [comment] 2020-05-10 17:37
Duplicate of #6020.
Fixed by #6023.

@Paule89DE I believe @tobiasKaminsky is planning to make a bugfix release shortly.

**Closed by ezaquarii** 2020-05-10 17:37 UTC
Labels: bug
