### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException

### ISSUE THREAD

**Issue by DasMuelli** [nextcloud/android#11326] opened 2023-01-30 09:14 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Download the client from F-Droid Store (stable net dev)
2. Start the App and setup the client for uploading Pictures.
3. Switch to an other App 
4. Switch back to Android and you get the error.

### Expected behaviour

Successful start of the App without Error. 

### Actual behaviour

Crash after start the Android App.

### Android version

13

### Device brand and model

Google Pixel 6 Pro

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

Android 13

### Nextcloud server version

25.0.3

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Couldn't read row 677, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetString(Native Method)
    at android.database.CursorWindow.getString(CursorWindow.java:465)
    at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:54)
    at android.database.CursorWrapper.getString(CursorWrapper.java:141)
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:968)
    at com.owncloud.android.datamodel.FileDataStorageManager.getGalleryItems(FileDataStorageManager.java:2241)
    at com.owncloud.android.datamodel.FileDataStorageManager.getAllGalleryItems(FileDataStorageManager.java:2186)
    at com.owncloud.android.ui.adapter.GalleryAdapter.showAllGalleryItems(GalleryAdapter.kt:168)
    at com.owncloud.android.ui.fragment.GalleryFragment.showAllGalleryItems(GalleryFragment.java:380)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.onPostExecute(GallerySearchTask.java:126)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.onPostExecute(GallerySearchTask.java:48)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7867)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230190`
* Build flavor: `generic`

### Device information
* Brand: `google`
* Device: `raven`
* Model: `Pixel 6 Pro`
* Id: `TQ1A.230105.001.A2`
* Product: `raven`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `eng.nobody.20230109.163456`

### Additional information

I using Android 13 with the Bliss custom ROM based and Android 13 AOSP.

**Comment by AlvaroBrey** [comment] 2023-01-30 10:25
Duplicate of #9948

**Closed by AlvaroBrey** 2023-01-30 10:25 UTC
Labels: bug
