### ISSUE TITLE
Nextcloud error while syncing

### ISSUE THREAD

**Issue by Zheltyy** [nextcloud/android#5062] opened 2019-12-24 16:50 UTC
### Steps to reproduce
1.  Click on the folder u want to sync
2.  Wait until its synced
3.  The error happens while syncing.

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{482711b u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1918)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7263)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: d2s
Model: SM-N975F
Id: PPR1.180610.011
Product: d2seea

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: N975FXXS1ASKA

**Comment by AndyScherzinger** [comment] 2020-01-09 15:01
duplicate of #2010

**Closed by AndyScherzinger** 2020-01-09 15:01 UTC
Labels: bug
