### ISSUE TITLE
Impossible to upload any file from Android 

### ISSUE THREAD

**Issue by Kalle73kw** [nextcloud/android#10770] opened 2022-09-29 11:27 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Open Nextcloud App on Android
Select "+" to add and upload a file
Select any file, doesn't matter what type

### Expected behaviour

The app should add the file to nextcloud and load it up to the server

### Actual behaviour

An error occurs, which says the file is already existing, you should use the conflict dialog to resolve it
When trying to open the conflict dialog it says, error creating it.

On the server is a log entry: failed to locate the file.

It doesn't matter which way I try, it'absolutely impossible to upload something from my phone. 
Creating files in the app is no problem. 

### Android version

12 / One Ui Version 4.1 

### Device brand and model

Samsung Galaxy S10

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.2

### Nextcloud server version

24.0.5

### Using a reverse proxy?

No

### Android logs

Can't find any log on my android... :/ And also no setting to enable the logging? 

### Server error logs

```bash
Sabre\DAV\Exception\NotFound: File with name /Charlotte Events/2021_11_18 Family Gathering/PromoPacks/xxxxxxx.zip could not be located
/var/www/virtual/xxxxxxx/html/3rdparty/sabre/dav/lib/DAV/Tree.php - line 78:

OCA\DAV\Connector\Sabre\Directory->getChild("xxxxxxx... p")

/var/www/virtual/lottserv/html/apps/dav/lib/DAV/ViewOnlyPlugin.php - line 75:

Sabre\DAV\Tree->getNodeForPath("files/xxxxxxx... p")

/var/www/virtual/xxxxxxx/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

OCA\DAV\DAV\ViewOnlyPlugin->checkViewOnly(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/virtual/xxxxxxx/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 472:

Sabre\DAV\Server->emit("method:GET", [ Sabre\HTTP ... }])

/var/www/virtual/xxxxxxx/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 251:

Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {}, false)

/var/www/virtual/xxxxxxx/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

Sabre\DAV\CorePlugin->httpHead(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/virtual/xxxxxxx/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 472:

Sabre\DAV\Server->emit("method:HEAD", [ Sabre\HTTP ... }])

/var/www/virtual/xxxxxxx/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 253:

Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/virtual/xxxxxxx/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 321:

Sabre\DAV\Server->start()

/var/www/virtual/xxxxxxx/html/apps/dav/lib/Server.php - line 358:

Sabre\DAV\Server->exec()

/var/www/virtual/xxxxxxx/html/apps/dav/appinfo/v2/remote.php - line 35:

OCA\DAV\Server->exec()

/var/www/virtual/xxxxxxx/html/remote.php - line 166:

require_once("/var/www/vi ... p")
```

### Additional information

I don'tr know exactly when it startetd, but it now about half a year or something like this... There have been different updates to android/nextcloud app & server, but it didn't got fixed. Un- and reinstall the app also didn't work.  :/

**Comment by AlvaroBrey** [comment] 2022-09-29 14:39
If you have control over the server setup, try the `.htaccess` modification  in https://github.com/nextcloud/android/issues/10423 and see if that helps please.

If you want to get logs from your device, instructions are here: https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat-mag

**Comment by Kalle73kw** [comment] 2022-09-29 20:13
I go nuts! It Works... :) Thank you for the hint! So many tries... 🥇 

And also for the logging info!

**Comment by AlvaroBrey** [comment] 2022-09-30 08:26
Thanks for reporting back @Kalle73kw , closing this as a duplicate of #10423 then

**Closed by AlvaroBrey** 2022-09-30 08:26 UTC
Labels: bug, needs info
