### ISSUE TITLE
Regression: app creates invalid folder when moving files to app folder

### ISSUE THREAD

**Issue by svenb1234** [nextcloud/android#9328] opened 2021-11-20 12:07 UTC
### Steps to reproduce
1. Update android app to 3.18
2. Let auto upload upload and move files to app folder
3. 

### Expected behaviour
- pictures should be moved to the app's folder (android/media.... At least before the update)
- pictures should show up in Google's photos app.

### Actual behaviour
- The app creates a folder which shows up as invalid
- photos are not found/shown by the photos app

### Environment data
Android version: 12

Device model: pixel 4a

Stock or customized system: stock

Nextcloud app version: 3.18.0

Nextcloud server version: 21.0.6

Reverse proxy: no

![Screenshot_20211120-125904](https://user-images.githubusercontent.com/46424536/142725710-b5fc14f1-4ad4-450e-af67-ad8bd74e6c15.png)

**Comment by Bob-le-pirate** [comment] 2021-11-20 14:18
Dear @svenb1234, you are not alone. I am facing the same issue.
Downgrading to previous version 3.17.1 solves it temporary.

**Comment by simonspa** [comment] 2021-11-25 18:05
Same here, my gallery app also shows empty thumbnails for pictures the Nextcloud app has moved. 

![Screenshot_20211125-190338](https://user-images.githubusercontent.com/1677436/143486240-be18d51c-18dc-432c-b7da-33e2d6c90170.png)

**Comment by ksarnelli** [comment] 2021-11-28 20:10
Same issue here.  It also happens when downloading files (only tested with images) from cloud to local via the app.  The empty folders created at the bottom of the "(invalid)" directory tree are causing the real files to not be found by other picture apps.

**Comment by redoranges** [comment] 2021-12-07 17:41
I'm seeing the same thing

Android version: 11

Device model: Motorola one 5G ace

Stock or customized system: stock

Nextcloud app version: 3.18.0

Nextcloud server version: 21.0.3

Reverse proxy: yes

**Comment by simonspa** [comment] 2021-12-10 17:06
@AlvaroBrey is there a way we can help to debug this and find the root cause? I'd love to have that fixed - maybe even in 3.18.1 :innocent: since my default use case (auto-upload photos and move to Nextcloud app folder) is terribly broken - only empty images are displayed by gallery apps...

**Comment by svenb1234** [comment] 2021-12-10 21:29
IMHO the fix should not only fix it for future uploads but also fix it for those uploads 3.18 messed up. I.e. it should move the pictures to the correct folders and remove the invalid folder.

**Comment by simonspa** [comment] 2021-12-11 07:51
I played a bit around with this and the issue is *not* connected to Auto-Upload but the same problem ahead when manually uploading files and selecting the "move file to Nextcloud folder" option.

**Comment by thejohnha** [comment] 2021-12-12 03:23
I just tried manually uploading some PDFs and the invalid folder was *not* created

**Comment by AlvaroBrey** [comment] 2021-12-13 11:11
Just reproduced this in Android 12, although I haven't had time to debug it completely. Some findings:

* Only happens for media files (which is why PDF was fine).
* Only happens in android 11+, so it's probably _yet another_ unintended consequence of the `targetSDK` update.
* There is a literal folder called `(invalid)` at the storage root, it's not just a placeholder.  It contains _folders_ with the name of the files, instead of actual files.
* The files also get copied to the proper path `/storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/{username}/`, so the problem may be when we notify Android of the new media, rather than in the actual move operation.

**Comment by AlvaroBrey** [comment] 2021-12-13 11:14
Oh, this is related to https://github.com/nextcloud/android/issues/6150, sorry for not finding it earlier.

**Comment by simonspa** [comment] 2021-12-13 11:47
> Oh, this is related to #6150, sorry for not finding it earlier.

Hm, I agree that they are somewhat related, but the current very odd behavior only started with the upgrade to 3.18 (and the corresponding targetSDK maybe?). The other issue still is there, too.

**Comment by mist** [comment] 2021-12-30 16:13
As my gallery app refuses to add the pictures which also exist as folders inside `(invalid)` I tried creating a file called `(invalid)` so no folders can be created. This leads to Nexctloud-Android showing countless upload-error-messages and renaming all images to `$imagename (2) (2) (2) (2) (2) (2) (2)....jpg` and so on until I manually delete the upload request. Then the uploading works (with the completely broken name).

For me this bug really is breaking my flow of image uploading.

**Comment by simonspa** [comment] 2021-12-30 16:31
I indeed also hoped this would have been solved in 13.8.1 since it breaks anything with image handling for all users with Android > 10 afaiunderstand. @AlvaroBrey did you get any further digging into the underlying scoped storage issue?

**Comment by markqvist** [comment] 2021-12-30 21:32
Also seing the same behaviour on 3.18.1 on Android 11.

**Comment by markqvist** [comment] 2021-12-30 21:54
After a little further investigation, this might be related to permissions not being granted correctly.

When NextCloud is first started, the app asks for the file management permission, and even though it is granted, the app does not show up in Androids permission manager as having acquired the file management permission.

This is probably why the "(invalid)" folder is created under the default shared storage path.

Downgrading to 13.7.0 also removes the problem for me.

**Comment by MaxPowers1337** [comment] 2021-12-30 23:12
> After a little further investigation, this might be related to permissions not being granted correctly.
> 
> When NextCloud is first started, the app asks for the file management permission, and even though it is granted, the app does not show up in Androids permission manager as having acquired the file management permission.
> 
> This is probably why the "(invalid)" folder is created under the default shared storage path.
> 
> Downgrading to 13.7.0 also removes the problem for me.

Same here. In my Android 12 the nextcloud app doesn't show up in the list of all apps with permissions on storage although I granted it at the very beginning.

**Comment by larwood** [comment] 2021-12-31 00:00
On my Pixel 6 Pro (Android 12) the Files and Media permission doesn't show under App Info either. However if you navigate to Settings > Apps > Special app access > All files access, I see Nextcloud is Allowed.

**Comment by mase76** [comment] 2022-01-02 22:32
I am also on 13.8.1 with Android 11. File permissions are granted. Image movements into the app folder and downloads end up in the (invalid) folder.

**Comment by markqvist** [comment] 2022-01-04 18:48
> On my Pixel 6 Pro (Android 12) the Files and Media permission doesn't show under App Info either. However if you navigate to Settings > Apps > Special app access > All files access, I see Nextcloud is Allowed.

I missed that. Upon checking that, NextCloud does indeed have the All Files Access granted here as well.

**Comment by LenKiMo** [comment] 2022-01-24 02:16
I found Nextcloud will create multi folders for media files. No sure if it's duplicate with this.

See #9732

**Comment by AlvaroBrey** [comment] 2022-01-24 10:33
For reference, this is likely caused by the app adding the files to `MediaScanner` but `MediaScanner` not being able to access the files because they're on the app's internal storage, rather than the app actually creating a directory named `(invalid)`. Some more info is in #6150, where some attempts at fixing it were made but neither was finished.

We'll get to this issue as soon as we can but we currently don't have enough time. Sorry for the delay, and of course PRs or solution proposals are always welcome.

**Comment by ant0nwax** [comment] 2022-02-02 18:54
Thank you for your time and work!

**Comment by Sewdohe** [comment] 2022-03-04 20:23
Any word on a fix being merged soon? This  issue is very frustrating 😖

**Comment by EukalyptusX** [comment] 2022-04-09 09:55
I'd also like to know when this fix is getting merged. This issue drives me. 😔
Thanks!!

**Comment by szabolcs-szilagyi** [comment] 2022-05-07 08:17
Reading through #6150 and getting to PR #9981, this issue is really old.

Is there a bug bounty program or any way we could raise the incentive for fixing this issue? How could the user community raise the priority of this in a helpful way?

**Comment by Rorschach1010** [comment] 2022-05-07 09:28
Since this started for me (was it with Android 11 or 12, I don't remember), the client got unusable and I have it just installed to use it for Single SignOn for other nextcloud apps. I am well aware that these things are done for free and in their freetime. Additionally, I like it how users use a bounty system. However, with this bug, the app gets practically unusable for newer android versions so shouldn't this automatically have a high priority?

**Comment by svenb1234** [comment] 2022-05-07 11:28
If you need a bounty to fix regressions then there is something really wrong with the project.

**Comment by szabolcs-szilagyi** [comment] 2022-05-08 13:19
> If you need a bounty to fix regressions then there is something really wrong with the project.

Didn't say that anybody needs a bounty, but was asking if there's anyway we (users) can help including donation in some form. Since I don't pay for using nextcloud think this is a reasonable offer from my point.

About if its a regression or not: reading the other threads this is caused by android changing. So the developers working on this app didn't caused it themselves, but there was a change outside of their control. After that maybe the team got resources issues and they are juggling to complete customer request from those customers who are actually paying for some services from them.

Me as a free user I wouldn't jump on judging the project if it's bad or good.

**Comment by svenb1234** [comment] 2022-05-08 20:46
Leaving aside that android does not change over night but announces changes months in advance, how come this bug was introduced with a change in the nextcloud client version and not with a change/update in an android version? No matter what the reason for commiting the breaking change is, this bug is a plain regression which was missed by QA. Shit happens. The change that caused this in the client could have been reverted - or fixed - in the last five months. There is a reason why the branch is called "stable". 

Most of Nextcloud (core+clients) is not a spare time hobby project but a professional, commercial project developed by paid developers. The company uses the many "free" users (private servers) as a USP/advertising argument and alpha, beta and RC testing team. Users invest time by testing, filing bug reports and supporting users on the forum. Thus I see no reason to value the "paying with time" users any less than those "paying with money" when it comes to regressions - not talking about feature or support requests etc.

In fact, this has nothing to do with free or not free. Fixing regressions having the highest priority simply values your users.

Since @AlvaroBrey works on the client it seems to get better though!

**Comment by danielb42** [comment] 2022-05-16 14:18
@svenb1234 Do you know which version introduced the bug? I'm considering downgrading since currently it's just not usable as a photo cloud any longer.

**Comment by danielb42** [comment] 2022-05-16 17:32
> AFAIK 3.18 from the end of November 2021 introduced the regression.

Yeah, I noticed the (invalid) folder appearing around then. However the heavy issue I'm experiencing now (downloaded files not accessible through other apps, e.g. Galleries) did arise not more than probably a week ago. Devs of third party apps also stated this is due to Nextcloud not adding files to the MediaScanner (?) properly. Since it worked fine up to a week ago, I'd assume the problem really unfolded with one of the very recent updates..

**Comment by alaincao** [comment] 2022-05-16 20:51
Just to add my 5cents here, it appears to me the files *are* correctly moved to the right destination folder. It's only when the app is trying to "declare" those files against the MediaStore thing that it fails and create this "(invalid)" folder.
But when I reboot my device, the MediaStore seems to trigger a rescan and my files eventually appears in the gallery etc.

So, your mileage may vary, but it's not *that* end of the world for me. A reboot fixes. But still a regression, though.

**Comment by danielb42** [comment] 2022-05-16 21:56
> Just to add my 5cents here, it appears to me the files are correctly moved to the right destination folder. It's only when the app is trying to "declare" those files against the MediaStore thing that it fails and create this "(invalid)" folder.

This exactly. Files are placed correctly, but "declaration" is defect.

> A reboot fixes

Also correct, but you cannot expect people with busy cloud shares to reboot their phone several times a day.

**Comment by ant0nwax** [comment] 2022-05-17 03:19
Hi folks,

i see that still many are struggeling with Nextcloud for Gallery upload of Photos from Android.

I struggeled too. I had the same issues like what you described.

After researching my possibilities I integrated another cloud service JUST for photos. Nextcloud is not a Photo storage (yet). Kindly let me suggest to take a look at Photoprism (and I am not a developer of their server based on premises AI solution, but a very happy user). It has also an uploader for you Android phone.

Also in the Google Workspace the Official support does not really help you with the Photos, but with Drive.
so you see Photo Cloud could be a different one than what Nextcloud offers.

I would be curious about how to integrate Nextcloud with Photoprism. I guess this first must be designed by a Product Team, I just added my opinion here.

**Comment by toqov** [comment] 2022-05-19 17:01
I have been downgraded on 3.17.1 for a few months and it works fine aside from a few bugs related to that version. 

It is a joke a company that claims to offer an enterprise worthy solution has core functionality broken for 6 months because they improperly implemented android 12 standards.

**Comment by ant0nwax** [comment] 2022-05-19 18:08
Hi toqov is it maybe better to have parts slowly developed than if a company sells your private data for advertising reasons and with that revenue could employ more people?

**Comment by AlvaroBrey** [comment] 2022-05-20 07:15
> I think it's escalating over here. But it shows how important this feature is for all of us. It would be great if a dev can tell us when things will get fixed.

Unfortunately the best I can do is "whenever we can". I started working on this via #9981 but priorities got shifted and I can't give an ETA right now. Sorry for the inconvenience, we're a small team with a lot to do :disappointed:

**Comment by svenb1234** [comment] 2022-05-20 08:24
So why not revert the commits that lead to the regression between 3.17 and 3.18 and wait until it is properly finished before commiting again?

**Comment by svenb1234** [comment] 2022-05-20 08:26
> Hi toqov is it maybe better to have parts slowly developed than if a company sells your private data for advertising reasons and with that revenue could employ more people?

That's not the point. Commit to stable branch only if your code is stable. Revert or fix if your code was not stable and caused a regression. That's the point.

**Comment by danielb42** [comment] 2022-05-20 08:31
> So why not revert the commits that lead to the regression between 3.17 and 3.18 and wait until it is properly finished before commiting again?

As far as I understand the issue, there is no version of Nextcloud left at this time that doesn't suffer from the bug because Android started to enforce stuff in late 2021. The fact that you deem 3.17 unaffected is because Android didn't enforce back then, but does now. So even pinning or downgrading to 3.17 won't help you in an up-to-date Android environment.

However I agree that it's really weird to prioritize *anything* over defects and regressions. I think everyone understands that @AlvaroBrey and team have a lot on their hands and is thankful for their efforts, but fixing defects that break core functionality should take precedence over anything else.

**Comment by AlvaroBrey** [comment] 2022-05-20 09:26
> So why not revert the commits that lead to the regression between 3.17 and 3.18 and wait until it is properly finished before commiting again?

As @danielb42 explained, we can't. We were forced to make changes (specifically updating the `targetSDK`) before November 2021 in order to be able to publish updates to Google Play. These changes included a lot of side effects dealing with storage, some of which were adressed at the same time, and others later when they were detected. We can't just undo this, as we would not be able to update the app.

This particular issue is harder to address than others, as it requires 
a) changing a bunch of code points throughout the app due to technical debt and the way the mediascanner works
b) making some compromises (there's no way that the app will keep working exactly as before, with the new storage restrictions)
It's unfortunately not a couple-of-hours fix, nor is it easy to even plan.

The root of this issue is that with the new `targetSDK` and in devices on Android >=10, the `MediaScanner` won't accept media contained in an application's private folder, which is where Nextcloud stores downloaded files and files that are copied/moved when uploaded.  Instead of crashing, the system does this weird invalid folder thing instead.
I technically could do a quick PR to just disable the media scanner on Android >=10, but while that would prevent the invalid folder, it would not fix the pictures not showing up in the gallery. That's why in #9981 I started to work towards allowing the "Downloads" folder to be the place where nextcloud stores files instead. I'll see if we can do at least that part quickly.


> However I agree that it's really weird to prioritize anything over defects and regressions

Keep in mind that Nextcloud is a company, and priorities for a company are not always the same as their end users'. I would love to fix this properly ASAP, but things are more complicated than that :cry:

**Comment by Thovi98** [comment] 2022-05-20 10:01
Thanks @AlvaroBrey for your explanation and for all your work so far 🤩

**Comment by svenb1234** [comment] 2022-05-20 10:27
> I have been downgraded on 3.17.1 for a few months and it works fine aside from a few bugs related to that version.

> The fact that you deem 3.17 unaffected is because Android didn't enforce back then, but does now. So even pinning or downgrading to 3.17 won't help you in an up-to-date Android environment.

How does this fit together?

**Comment by AlvaroBrey** [comment] 2022-05-20 11:47
> How does this fit together?

* Before  3.18 -> `targetSdk` was 29
* After 3.18 -> `targetSdk` is 30
* `targetSdk` 30 imposes restrictions on storage on devices with android >= 10
* `targetSdk` >= 30 required for updates in Google Play after November 2021

**Comment by ant0nwax** [comment] 2022-05-20 14:23
if it makes you happy since my android 12 update even my banking app authentication is broken and my bank does not care, you are discussing about nextcloud, i guess you have a lot of time :)

**Comment by toqov** [comment] 2022-05-20 16:24
> if it makes you happy since my android 12 update even my banking app authentication is broken and my bank does not care, you are discussing about nextcloud, i guess you have a lot of time :)

@ant0nwax people are allowed to be upset with poor management choices in products they use. No ill will towards the devs whatsoever; this is Nextcloud management not understanding core functionality being broken in a major product being a big deal. My bank actually implemented all android 12 standards properly and in a timely manner, and I am a member of a tiny credit union. Like with many services, if my bank app did not work I would simply switch banks.

>This particular issue is harder to address than others, as it requires
>a) changing a bunch of code points throughout the app due to technical debt and the way the mediascanner works
>b) making some compromises (there's no way that the app will keep working exactly as before, with the new storage restrictions)
>It's unfortunately not a couple-of-hours fix, nor is it easy to even plan.

Crazy to me if that much work is required to push a compatible update (just like everyone has dealt with porting to android 12) that a totally broken update would be pushed 6 months ago that now cannot be fixed because it was rushed and not handled properly in the first place. What was pushed back then if all of this was required?

After totally breaking an advertised product to the point it is not usable, other things are more important. Like with any other big company, it seems the only way real issues will get a response is by users throwing a fit.

**Comment by SquirrelSenpai** [comment] 2022-05-30 12:49
@AlvaroBrey  Hello there.  Hope you are well.  I appreciate that your resources are limited.   How much money would it take for your product owner to move this bug into a sooner sprint?   Would you be willing to farm out the work to skilled users? 

Thanks

**Comment by edonnachie** [comment] 2022-06-05 13:29
I have the same problem. I'm surprised the issue is not being given greater priority, because it reflects very poorly on Nextcloud as a whole.

**Closed** 2022-06-10 13:56 UTC
Labels: bug, approved

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2022-06-15 19:49
@duanenewman, I expect that that is why this issue was closed.

**Comment by svenb1234** [comment] 2022-06-15 20:10
What should one do about that folder. It still exists on my android and has pictures in it. Do I have to move it?

Should not the app update have done something with it, if there was a fix for not having an )invalid) folder from now on?

**Comment by heyheyhello** [comment] 2022-06-15 20:13
@svenb1234 I've been deleting it for weeks now.

**Comment by svenb1234** [comment] 2022-06-15 20:17
Thanks for the feedback. So now I know what to do. What about all those that do not read GitHub? Will it at least be part of the release notes and published on nextcloud's blog. Or will the next update take care of cleaning up what the regression left behind?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2022-06-15 22:10
@AlvaroBrey, shall the subsequent update remove the folder?

**Comment by AlvaroBrey** [comment] 2022-06-16 09:19
> @AlvaroBrey, shall the subsequent update remove the folder?

I've pushed a draft migration in https://github.com/nextcloud/android/pull/10400 to remove the folder. It will only work if the app has external storage permissions, however, and won't delete the fake images from gallery apps (they will be automatically removed by the media scanner next time it runs, or when rebooting).

However I feel uneasy about this, as we're deleting a folder that we didn't create; after all this is a bug in Android itself, even if triggered by incorrect API usage by us. It feels like overreaching on our part, this is why I initially didn't implement this.  To mitigate this, I've made sure to only delete the `(invalid)` folder if it has no other children than the `com.nextcloud.client` folder.
