### ISSUE TITLE
Error deleting a photo displayed in full screen

### ISSUE THREAD

**Issue by Moyounnet37** [nextcloud/android#10684] opened 2022-08-27 10:34 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

From the "All Files" or "Media" tabs, display a photo in full screen and try to delete it

Deleting photos from their thumbnails works.

### Expected behaviour

Photo is delete.

### Actual behaviour

Error message

### Android version

10

### Device brand and model

Samsung Galaxy A6

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.0

### Nextcloud server version

24.0.4

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.services.OperationsService$OperationsServiceBinder.isSynchronizing(OperationsService.java:372)
    at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:497)
    at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:486)
    at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:194)
    at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:126)
    at com.owncloud.android.ui.preview.PreviewImageFragment.onPrepareOptionsMenu(PreviewImageFragment.java:381)
    at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:3253)
    at androidx.fragment.app.FragmentManager.dispatchPrepareOptionsMenu(FragmentManager.java:3051)
    at androidx.fragment.app.FragmentManager$2.onPrepareMenu(FragmentManager.java:466)
    at androidx.core.view.MenuHostHelper.onPrepareMenu(MenuHostHelper.java:63)
    at androidx.activity.ComponentActivity.onPrepareOptionsMenu(ComponentActivity.java:497)
    at android.app.Activity.onPreparePanel(Activity.java:4150)
    at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3148)
    at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1936)
    at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2190)
    at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:273)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
    at android.view.Choreographer.doCallbacks(Choreographer.java:794)
    at android.view.Choreographer.doFrame(Choreographer.java:725)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:7948)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a6lte`
* Model: `SM-A600FN`
* Id: `QP1A.190711.020`
* Product: `a6ltexx`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `A600FNXXU9CVB1`

**Comment by AlvaroBrey** [comment] 2022-08-29 13:00
Duplicate of #10580

**Closed by AlvaroBrey** 2022-08-29 13:00 UTC
Labels: bug
