### ISSUE TITLE
Play music from App directly

### ISSUE THREAD

**Issue by MegaV0lt** [nextcloud/android#3102] opened 2018-09-28 16:17 UTC
### Actual behaviour
- not possible to play music, folders of music with nextcloud app without downloding first

### Expected behaviour
- should be possible to play/stream musi fom nextcloud app directly with possibility to play folders content

### Environment data
Android version: 6

Device model: HomTom HT16 Pro

Stock or customized system: ? with root

Nextcloud app version: Actual stable 3.x

Nextcloud server version: 13.x

**Comment by gradinaruvasile** [comment] 2018-09-29 20:42
This is already implemented in the 3.3.0 version actually but you need the server version 14 at least.

**Comment by MegaV0lt** [comment] 2018-09-30 06:34
Great! I will upgrade server on Monday and test it. Client 3.3.0 is the stable one?

**Comment by AndyScherzinger** [comment] 2018-09-30 06:53
Yes, 3.3.0 is the latest stable version of the Android app, 14.0.1.1 the latest stable of the server.

**Comment by MegaV0lt** [comment] 2018-10-01 12:42
Have tried, but sadly is only possible to play one file at a time. Playlist (m3u) is not recognized ;-(

**Comment by yasuoiwakura** [comment] 2020-03-02 11:05
Hi there,
"folder playback" is not yet possible, right?

**Comment by joshtrichards** [comment] 2023-10-13 21:20
Duplicate of #1038

Also related to #5555

**Closed by joshtrichards** 2023-10-13 21:20 UTC
Labels: enhancement
