### ISSUE TITLE
runtime exception

### ISSUE THREAD

**Issue by kr4z33** [nextcloud/android#9263] opened 2021-11-14 16:31 UTC
### Steps to reproduce
1. Unknown

### Expected behaviour
- next cloud does not crash

### Actual behaviour
- occasional crashing, I do not know how to reproduce this

### Error message

```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Attempt to read from field 'androidx.viewpager.widget.ViewPager com.owncloud.android.databinding.FileDetailsFragmentBinding.pager' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
	at android.app.ActivityThread.access$900(ActivityThread.java:177)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5942)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.NullPointerException: Attempt to read from field 'androidx.viewpager.widget.ViewPager com.owncloud.android.databinding.FileDetailsFragmentBinding.pager' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailFragment.getFileDetailSharingFragment(FileDetailFragment.java:158)
	at com.owncloud.android.ui.activity.FileActivity.getShareFileFragment(FileActivity.java:855)
	at com.owncloud.android.ui.activity.FileActivity.getFile(FileActivity.java:297)
	at com.owncloud.android.ui.activity.FileDisplayActivity.updateActionBarTitleAndHomeButton(FileDisplayActivity.java:1625)
	at com.owncloud.android.ui.activity.ToolbarActivity.setupToolbar(ToolbarActivity.java:103)
	at com.owncloud.android.ui.activity.ToolbarActivity.setupHomeSearchToolbarWithSortAndListButtons(ToolbarActivity.java:127)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onCreate(FileDisplayActivity.java:264)
	at android.app.Activity.performCreate(Activity.java:6288)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
	... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: hltetmo
Model: SM-N900T
Id: LRX21V
Product: hltetmo

************ FIRMWARE ************
SDK: 21
Release: 5.0
Incremental: N900TUVUFQD2
```

**Comment by zachdecook** [comment] 2021-11-15 18:56
I get this on every launch:

```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Attempt to read from field 'androidx.viewpager.widget.ViewPager com.owncloud.android.databinding.FileDetailsFragmentBinding.pager' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2733)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2819)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6321)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.NullPointerException: Attempt to read from field 'androidx.viewpager.widget.ViewPager com.owncloud.android.databinding.FileDetailsFragmentBinding.pager' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailFragment.getFileDetailSharingFragment(FileDetailFragment.java:156)
	at com.owncloud.android.ui.activity.FileActivity.getShareFileFragment(FileActivity.java:855)
	at com.owncloud.android.ui.activity.FileActivity.getFile(FileActivity.java:297)
	at com.owncloud.android.ui.activity.FileDisplayActivity.updateActionBarTitleAndHomeButton(FileDisplayActivity.java:1635)
	at com.owncloud.android.ui.activity.ToolbarActivity.setupToolbar(ToolbarActivity.java:103)
	at com.owncloud.android.ui.activity.ToolbarActivity.setupHomeSearchToolbarWithSortAndListButtons(ToolbarActivity.java:127)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onCreate(FileDisplayActivity.java:266)
	at android.app.Activity.performCreate(Activity.java:6760)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2686)
	... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus3T
Model: ONEPLUS A3000
Id: NMF26F
Product: OnePlus3

************ FIRMWARE ************
SDK: 25
Release: 7.1.1
Incremental: 136
```

**Comment by AlvaroBrey** [comment] 2021-11-17 13:56
Duplicate of #9084

**Closed by AlvaroBrey** 2021-11-17 13:56 UTC
Labels: bug
