### ISSUE TITLE
tmp folder is filled by auto upload

### ISSUE THREAD

**Issue by raceface2nd** [nextcloud/android#2505] opened 2018-04-23 20:30 UTC
### Actual behaviour
When activating auto upload all files are copied into the folder /internal/nextcloud/tmp and left there after the upload. After some months of taking fotos and videos with my phone this is wasting more than 6GB of data. Deleting the files in the tmp folder causes a complete re-upload of all fotos and videos. My fotos and videos are stored by default on an SD card.

### Expected behaviour
I expected that the tmp folder will be cleared after the upload.
 
### Steps to reproduce
1. Choose a folder on an SD card for auto upload

### Environment data
Android version: 7.0 Security Patch 01.02.2018

Device model: Samsung J5 2017

Stock or customized system: Stock system

Nextcloud app version: 3.1.0

Nextcloud server version: 13.0.0

**Comment by raceface2nd** [comment] 2018-04-24 20:16
I leave the original file in the original folder.

**Comment by tobiasKaminsky** [comment] 2018-04-26 09:04
Normally the tmp folder should be cleaned and testing it on a Samsung S5 Neo with external sdcard, it also works.
Do you see anything that the remaining files have in common? Are those files where the upload failed?
As it is within NC's own folder it should be no read/write permission problem…

@mario maybe you have an idea?

**Comment by raceface2nd** [comment] 2018-04-26 19:07
The only thing that these files have in common is that they are stored on the SD card and are jpg, png or mp4 files. I do not believe that the upload of these files created any errors on uploading because it's hundreds of files. Also all of them have been uploaded.

I now recognized that the files in the tmp folder are deleted as soon as I delete an original file.

**Comment by mario** [comment] 2018-04-26 19:08
Right. It's because if you're on an SD card we generate a temporary file which is then uploaded.  Uh.

**Comment by tobiasKaminsky** [comment] 2018-04-27 09:39
Yes, but after a successful upload we delete the temp file:
https://github.com/nextcloud/android/blob/3af569988db3af37936e152b04e03a25a0b0f1fb/src/main/java/com/owncloud/android/operations/UploadFileOperation.java#L868-L870

@raceface2nd can you try to manually upload a file from external sd card, also with option "Keep file in source folder"?
Does this then also remain in tmp folder?

**Comment by brokensbone** [comment] 2018-05-11 06:42
I'm also experiencing this behaviour. Exactly as described above.

Environment data

Android version: 7.0 Security Patch 01.12.2017

Device model: Motorola Moto G4

Stock or customized system: Stock system

Nextcloud app version: 3.1.0

Nextcloud server version: 13 (not sure of minor version details, if any)

Happy to give any more information if its useful.

**Comment by ardevd** [comment] 2018-05-11 07:01
@tobiasKaminsky Well, you never check the return value from the file delete() call, so perhaps it fails for some reason? Or perhaps the if statement encapsulating it is tricking us. I'll see if I can reproduce the issue.

**Comment by ardevd** [comment] 2018-05-11 07:01
@brokensbone Just out of curiosity. Have you tried re-installing the NextCloud app?

**Comment by ardevd** [comment] 2018-05-11 09:57
Update: Disregard above post. In my case the temporalFile is never created and I dont get any files in the Nextcloud temp folder.

**Comment by brokensbone** [comment] 2018-05-11 16:18
@ardevd reinstalled and replicated. Uninstalling got rid of all the old ones but the first photo I've taken since is now in the camera directory and the nextcloud client tmp dir.

**Comment by tobiasKaminsky** [comment] 2018-05-14 12:16
Potential fix is in #2577, which will be soon in dev version.
Can you then try this?

My assumption, which might be wrong, is, that 
- temp file is only created/used when uploading a file from sdcard
- temp file is currently created also on sdcard, which might not get deleted

So the fix is to use an internal location for temp file and after each upload try to delete the file.

**Comment by brokensbone** [comment] 2018-05-14 12:33
For my case, your assumptions are spot on.

I'll install the dev version after that's gone in.

**Comment by gohrner** [comment] 2018-09-27 15:55
I just made a fresh install of NextCloud 14.0 and the Android client version 3.3.0, so older software versions and migrations are definitely not involved.

After testing uploading a bit, I also noticed that the tmp-directory is filled with tons of files (I think about 70-80% of the files I uploaded / synced). However, auto-syncing / auto-uploading is disabled in my case, I triggered the uploads manually.

My phone does not have an external sdcard, only internal memory, even though I'm not entirely sure  how it's organized. The device is a Nokia 8 Sirocco with Android One, i.e. a stock Android 8.1 Oreo.

Is this the same issue and will be fixed, shall I open a new issue concerning this or will the files in tmp disappear automagically after a while?

I noticed the leftover files as Google Fotos is showing them in addition to the images in the "real" NextCloud folder.

**Comment by CMThF** [comment] 2019-01-12 17:30
Occurs also on Samsung A3 2015, with SD card. 
This is really annoying, because this phone has very limited internal memory, which is basically needed for Android alone. Due to this bug the device runs into out of storage warnings all the time.

**Comment by yhtang** [comment] 2019-01-13 23:41
I can confirm that this issue is still there with client version 3.4.1 running on Android 9.

**Comment by gohrner** [comment] 2019-01-14 06:45
> Is this the same issue and will be fixed, shall I open a new issue concerning this or will the files in tmp disappear automagically after a while? (Ah, and, BTW, may I savely remove those tmp-files without causing data loss or a re-upload of the fotos as mentioned above in this issue?)

They do not automatically disappear, and the "duplicate file cleaner" introduced with Android Pie (I just upgraded) makes matters worse:

It will detect the original fotos in the Nextcloud folder *as duplicates* of the files in the tmp folder (as the files in the `tmp` folder are more recent and the cleanup application uses the strange logic that it will keep the most recent copies of duplicates instead of the oldest, original copy...) and if you chose to clean duplicates would happily delete the real files, only leaving the copies im `tmp`.

This means that after doing this, the files will disappear from the server, and after deinstalling the NextCloud client and/or a fixed NextCloud client which cleans up the `tmp` directory, the photos will be gone for good, leading to nice data loss... :-(

**Comment by gohrner** [comment] 2019-01-14 06:48
Maybe someone could update the issue description, indicating, that not only auto-uploads, but also manual uploads are affected?

Also, in my case no external SD card is involved, my phone only has internal memory.

Contrary to @raceface2nd, I'm also using the strategy "Move files to nextcloud folder.", not "keep files". So the bug seems to be a general problem, or I'm hitting a different bug with exactly the same symptoms.

**Closed** 2019-01-21 18:57 UTC
Labels: AutoUpload, bug, pr exists
