### ISSUE TITLE
Crash on return from PWA

### ISSUE THREAD

**Issue by HappyHepo** [nextcloud/android#9430] opened 2021-12-02 07:42 UTC
### Steps to reproduce
1. Be in Contacts Backup Settings
2. Open PWA (Chrome/Hardwareluxx.de forum) from Notification
3. Come back
May be related to #9324 ?

### Expected behaviour
- No Crash

### Actual behaviour
- Crash:
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to read from field 'com.google.android.material.button.MaterialButton com.owncloud.android.databinding.BackupFragmentBinding.contactsDatepicker' on a null object reference
	at com.owncloud.android.ui.fragment.contactsbackup.BackupFragment$1.onPostExecute(BackupFragment.java:281)
	at com.owncloud.android.ui.fragment.contactsbackup.BackupFragment$1.onPostExecute(BackupFragment.java:252)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7045)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

### Environment data
```
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: greatlte
Model: SM-N950F
Product: greatltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: N950FXXU5DSB2
```

**Comment by AlvaroBrey** [comment] 2021-12-02 09:28
Duplicate of #9324, but thanks for the additional info!

**Closed by AlvaroBrey** 2021-12-02 09:28 UTC
Labels: bug
