### ISSUE TITLE
Notifications not working on /e/OS (with MicroG)

### ISSUE THREAD

**Issue by ne20002** [nextcloud/android#10751] opened 2022-09-20 08:31 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Use a phone with /e/OS (or MicroG)

While other Apps like e.g. WhatsApp, Signal, SBB, ZVV, MeteoSwiss do work with Firebase Cload Messaging the Nextcloud app does not.
Indeed, on the notifications tab in the app a message box appears claiming that Google services are not available.

### Expected behaviour

Nextcloud Android app should work with MicroG and not depend on Google services directly but use the correct API.

### Actual behaviour

Notifications not working

### Android version

10 /e/OS

### Device brand and model

Samsung S9

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.21.2

### Nextcloud server version

24.0.5

### Using a reverse proxy?

Yes

### Android logs

N/A

### Server error logs

```bash
N/A
```

### Additional information

Please see also #https://github.com/nextcloud/android/issues/8684

**Comment by strugee** [comment] 2022-09-23 01:52
Possible duplicate of #3333. @ne20002, please provide your `adb logcat` logs. Thanks for contributing to Nextcloud!

**Comment by ne20002** [comment] 2022-09-26 07:30
Not sure where I get adb logcat logs. 
I just realized on my /e/OS phone (which I now use as primarily phone) that the Nextcloud app is complainin about missing propriatraty Google services.
Other apps can handle this.

**Comment by AlvaroBrey** [comment] 2022-09-30 08:53
> Not sure where I get adb logcat logs.

Instructions here: https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat-mag

**Comment by AlvaroBrey** [comment] 2022-09-30 09:54
Just quickly installed /e/OS on a spare phone to test this. I am not very familiar with this ROM, but it appears that the included app store will install the Nextcloud FDroid build and not the one from Google Play. 

The F-Droid build does not include any FCM code (which explains the "Google services not available" message). You may want to check the "gplay-release" APKS from the GitHub releases page. 

This is then not a bug but expected behaviour.

**Closed by AlvaroBrey** 2022-09-30 09:54 UTC
Labels: bug
