### ISSUE TITLE
NullPointerException: App crashes at startup after showing Folders

### ISSUE THREAD

**Issue by noresistence** [nextcloud/android#8732] opened 2021-07-19 07:52 UTC
### Steps to reproduce
1. Open the Android app. The folder list ist shown.
2. Folder list is automatically refreshed.

I have two accounts in the app, and right before this error started to happen, in fast succession, I changed between these and furthermore the dialog to add a new account opened briefly (not on purpose, i believe i might have touched the wrong menu option when trying to switch the account again) and was aborted.

### Expected behaviour
- App shows folders and does not crash

### Actual behaviour
- App crashes with NullpointerException: Parameter password is null.

### Can you reproduce this problem on https://try.nextcloud.com?
- no, it's a problem with the Android app and i can't change the accounts there anyway as it crashes now each time right after startup. The problem occurs even in flight mode.

### Environment data
Android version: 7.0

Device model: see below

Stock or customized system: stock

Nextcloud app version: 3.16.1

Nextcloud server version: unknown

Reverse proxy: unknown

#### Web server error log
```
Problem occurs in flight mode. No access to server.
```

#### Android App Error report
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Credentials.kt)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Credentials.kt)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updateUserProfile(RefreshFolderOperation.java:283)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:231)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:776)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWVNS-H
Model: HUAWEI VNS-L31
Id: HUAWEIVNS-L31
Product: VNS-L31

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: C432B418
```

**Comment by noresistence** [comment] 2021-07-19 07:57
Seems to be related to https://github.com/nextcloud/android/issues/8728, only that I did not try to change the password

**Comment by AndyScherzinger** [comment] 2021-07-19 09:08
Duplicate of #8370

**Closed by AndyScherzinger** 2021-07-19 09:08 UTC
Labels: bug
