### ISSUE TITLE
Add support for v12 login

### ISSUE THREAD

**Issue by mario** [nextcloud/android#1145] opened 2017-06-27 09:37 UTC
V12 adds a login via nc:// mechanism. Now, in order to support this we need to do the following:

- if server isn't preconfigured completely via setup.xml, show logo and server input field (middle of the screen)

- once user inputs server, if the server is fine and if it's V12+, show webview for login, otherwise do animation to put server field where it belong and show username/password fields & connect button

PR: #1148 
Server: https://github.com/nextcloud/server/issues/5693

**Comment by tobiasKaminsky** [comment] 2017-06-27 13:56
So this is basically working right now, but it does not show directly the login, but instead this right after entering a nc12 server url:
![filecvlls4](https://user-images.githubusercontent.com/5836855/27590944-89ca378a-5b50-11e7-8d35-06f27922beb6.png)

If we want to have this flogin flow enabled for all our (private) android client user I think we should directly show the login form? Otherwise it breaks the login experience that the users are used to...

**Comment by mario** [comment] 2017-06-27 14:01
I'm not sure I understand? Yes, for our private users we should show this website directly if NC >= 12 and server url is configured.

**Comment by tobiasKaminsky** [comment] 2017-06-27 14:13
At least on my test instances it is:

Open app:
![filewuxujo](https://user-images.githubusercontent.com/5836855/27591845-3513b68c-5b53-11e7-86d1-e1daad4fd545.png)
--> enter server url.

If >=NC12, it shows first this:
![filecvlls4](https://user-images.githubusercontent.com/5836855/27590944-89ca378a-5b50-11e7-8d35-06f27922beb6.png)

after clicking "grant access" it shows this:
![fileypkf78](https://user-images.githubusercontent.com/5836855/27591848-396a8eea-5b53-11e7-9ea6-8a243f832daf.png)
-> then enter user& pass, short "redirect" is shown and then the file listing of the account is shown.

The second screen is my "problem" as this will break the UX of an average user and he might "fear" that it is something wrong...

**Comment by mario** [comment] 2017-06-27 14:19
This is IHMO the right UX both flow and security wise, but hmm ... let me
check this one of these days. You have other bugs to attend to then :P

**Comment by mario** [comment] 2017-06-27 14:21
Have you done a branch or something?

**Comment by tobiasKaminsky** [comment] 2017-06-28 07:12
PR is #1148

Please have a look at
https://nextcloud.kaminsky.me/index.php/s/RfHb9Rn9gjLx8Jd

For me this breaks completely the UI/anrdoid experience if we open the login page...
@jancborchardt

**Comment by jancborchardt** [comment] 2017-06-28 22:01
Could we open the webview as a modal instead of fullscreen? Isn't that how for example apps who provide log in via Facebook Connect do it?

And yeah the flow is a bit confusing. I would expect:

1. Put server address in
2. If Nextcloud 12, get modal with the username/pass log in. Or if you are logged in on the mobile device browser already, directly show step 3
3. Show the "Grant access" page

Right?

**Comment by mario** [comment] 2017-06-29 04:10
@jancborchardt  Modal? No, at least not in your sense of words ... In most cases, "modal" on a phone would be full screen with animation from the bottom, and that's about it :D

As for your expectation of us knowing what you did on the device mobile browser ... well, that's going too far :)

@tobiasKaminsky all corporations prefer the model suggested here, and is used pretty much everywhere. It reduces the attack vector in the fact that it requires you to login on a website rather than an app. This is the *native* and *one true way* (tm) :)

@jancborchardt I agree usually "Grant access" goes after the login, but this is server-side, and we can fix for 12.0.1 or 12.0.2, but is nothing critical.

**Comment by tobiasKaminsky** [comment] 2017-06-29 05:58
My idea was to login with the website, but do not show the website as a webview but instead show native android forms and "just" post the data to the new login flow. So it would have been still a native UI feeling for the user.

But if we want to go this way, then let us improve it in the way that "grant access" should be shown after login and, if possible show a better description for "grant access":
Instead of 
> "you are about to grant 'Mozilla/5.0 (Android *ownCloud-android/1.4.3" access to your Nextcloud account"

show

>  "you are about to grant 'Android Nextcloud App 1.4.3" access to your Nextcloud account"

(small but at least for me important difference to not confuse the user...)

**Comment by jancborchardt** [comment] 2017-06-29 08:55
> As for your expectation of us knowing what you did on the device mobile browser ... well, that's going too far :)

I was under the impression that a webview opening a website has access to the same session as the browser does. :/ If not, nevermind :)

**Comment by mario** [comment] 2017-06-29 12:47
@tobiasKaminsky that's not how this was imagined :D This would lead to nightmares in case login site ever gets changed.

Let's work with what we have, and this same approach will work regardless how it gets improved on the server side.

**Comment by LukasReschke** [comment] 2017-06-29 12:57
Seconding @mario. For UX improvements to the display and login layout please file issues in the server repo and we can discuss this there. But that's a server part as mario said :)

**Comment by daedroza** [comment] 2017-07-01 17:38
Any progress on this or any version that I can test this from? I'm using the app from Play store.
Here is the problem :
`07-01 23:06:14.967 32327 32327 D OperationsService: Starting command with id 24
07-01 23:06:14.968 32327 32361 D SimpleFactoryManager: getClientFor(OwnCloudAccount ... : 
07-01 23:06:14.975 32327 32361 D OwnCloudClient #23: Creating OwnCloudClient
07-01 23:06:14.975 32327 32361 V SimpleFactoryManager:     new client {@192.168.0.100:8080, 27996941}
07-01 23:06:14.992 32327 32361 D OwnCloudClient #23: REQUEST GET /status.php
07-01 23:06:14.993 32327 32361 D AdvancedSslSocketFactory: Creating SSL Socket with remote 192.168.0.100:8080, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@9bbf979
07-01 23:06:14.994 32327 32361 D AdvancedSslSocketFactory:  ... with connection timeout 5000 and socket timeout 5000
07-01 23:06:14.996 32327 32361 I ServerNameIndicator: SNI done, hostname: 192.168.0.100
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: Connection check at https://192.168.0.100:8080: SSL exception
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: javax.net.ssl.SSLHandshakeException: Handshake failed
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:429)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at com.owncloud.android.lib.common.network.AdvancedSslSocketFactory.verifyPeerIdentity(AdvancedSslSocketFactory.java:248)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at com.owncloud.android.lib.common.network.AdvancedSslSocketFactory.createSocket(AdvancedSslSocketFactory.java:185)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:222)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:192)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at com.owncloud.android.lib.resources.status.GetRemoteStatusOperation.tryConnection(GetRemoteStatusOperation.java:87)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at com.owncloud.android.lib.resources.status.GetRemoteStatusOperation.run(GetRemoteStatusOperation.java:196)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at com.owncloud.android.operations.GetServerInfoOperation.run(GetServerInfoOperation.java:81)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at com.owncloud.android.services.OperationsService$ServiceHandler.nextOperation(OperationsService.java:482)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at com.owncloud.android.services.OperationsService$ServiceHandler.handleMessage(OperationsService.java:418)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at android.os.Looper.loop(Looper.java:154)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x9adc8a40: Failure in SSL library, usually a protocol error
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (external/boringssl/src/ssl/tls_record.c:192 0xa906b872:0x00000000)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
07-01 23:06:15.016 32327 32361 E GetRemoteStatusOperation: 	... 20 more
07-01 23:06:15.021 32327 32361 D GetRemoteStatusOperation: establishing secure connection failed, trying non secure connection
07-01 23:06:15.023 32327 32361 D OwnCloudClient #23: REQUEST GET /status.php
07-01 23:06:15.067 32327 32361 D RemoteOperationResult: RemoteOperationResult has processed UNHANDLED_HTTP_CODE: 400
07-01 23:06:15.072 32327 32361 D RemoteOperationResult: RemoteOperationResult has processed UNHANDLED_HTTP_CODE: 400
07-01 23:06:15.072 32327 32361 E GetRemoteStatusOperation: Connection check at http://192.168.0.100:8080: Operation finished with HTTP status code 400 (fail)
07-01 23:06:15.077 32327 32361 D OperationsService: Called 1 listeners
07-01 23:06:15.077 32327 32361 D OperationsService: Stopping after command with id 24
`

**Comment by tobiasKaminsky** [comment] 2017-07-04 06:42
@daedroza no, it is currently developed, but right after the merge into master you can use it in the dev version.

**Comment by AndyScherzinger** [comment] 2017-07-16 14:59
merged to master for v1.5.0

**Closed by AndyScherzinger** 2017-07-16 14:59 UTC
Labels: enhancement, pr exists

**Comment by Biont** [comment] 2017-11-30 14:52
Is there documentation available for this? I would like to add a similar workflow to my app and have a hard time finding and useful info on how this is supposed to work, other that reading through all of AuthenticatorActivity and it's dependencies

**Comment by AndyScherzinger** [comment] 2017-12-01 12:42
Afaik no, but maybe @tobiasKaminsky knowns since he did the implementation.

**Comment by tobiasKaminsky** [comment] 2017-12-01 13:01
Well, as the linked issue suggests, there is no documentation, but I hope someone will write it j-)

**Comment by Biont** [comment] 2017-12-01 13:46
Thanks for the update. I keep an eye on that issue and hope it will lead to something in the future. Cheers

**Comment by CharlesMAtkinson** [comment] 2018-03-16 15:41
I have no fear ;p but since Nextcloud upgraded itself to 3.0.3 I have not been able to authenticate however many times I enter user name and password.  The user name and password are correct because a) they worked once when the UI let me "Revert to the old login method" and b) they work on the Nextcloud website.

The Nextcloud server is 12.0.3, administered by myself (so the behaviour may be caused by settings I have made)

The 3.0.3 UI is scary!  What does "You are about to grant * access to your nextcloud account" mean?  It sounds like more than the old logon but no information is given to the user on the UI.  What are "App token"s?  IMHO there is too much that is new **and** unexplained in the new UI.

**Comment by mario** [comment] 2018-03-16 15:56
@CharlesMAtkinson well, that's bad cc @tobiasKaminsky. But I hear 12.0.5 might fix it if I remember correctly?

**Comment by CharlesMAtkinson** [comment] 2018-03-16 16:13
Thanks Mario :)  I tried upgrading the server via the web GUI (to 12.0.6 via the stable channel) but got the dreaded "core/shipped.json is not available" so now phone and server are both borked.  At least they are consistent!

**Comment by mario** [comment] 2018-03-16 20:25
Well this is bad :( Do you have a way to revert?

**Comment by mario** [comment] 2018-03-16 20:31
Or do a manual update?

**Comment by CharlesMAtkinson** [comment] 2018-03-20 02:32
Thanks for suggestions, Mario.  Finally I did a fresh install of 13.0.1 on the server and 3.0.3 on the Android then copied files from backup on one of the Debian clients.

Getting back to topic, initialising 3.0.3 was confusing (what's an app token?  Do I want to revert to the previous method?) but I went ahead with "Grant access" (because it was in the biggest font) and it authenticated user name and password successfully after which it did not present another authentication dialog.

**Comment by AndyScherzinger** [comment] 2018-03-20 07:19
The app token get generated during the login+granting access you did. This way the client works with an access token. You can see all granted accesses in the profile on the web interface within your account settings and can revoke individual tokens. This way you can revoke a clients access by deleting the token not by having to change your user's password :)

**Comment by CharlesMAtkinson** [comment] 2018-03-20 10:48
Thanks Andy but I did not find.  The web interface on the NC server (as opposed to the android client improbably using a web interface)?  Logged on as the user or the admin (I tried both)?

There's a closed issue  for "New" weblogin flow needs documentation #620 linked above but IIUC that provides developer documentation only.

The Android client doc is https://docs.nextcloud.com/android/ and is for version 1.0.0.

Mostly Android apps are written to be intuitively obvious so no docs are needed but Android Nextcloud client 3.0.3 (3.x?) is complex enough to need documentation, ideally at the point of use (a "What is this?" button on the UI).
