### ISSUE TITLE
Unable to share with Android nextcloud app

### ISSUE THREAD

**Issue by Oceania2301** [nextcloud/android#7630] opened 2020-12-07 21:54 UTC
### Steps to reproduce
1.  Open any pdf with the reader
2. Send to and choose nextcloud
3. Load file in any server folder
No file is uploaded
No error shown

### Expected behaviour
- Tell us what should happen
With the previous version all was running fine
### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 
Xiaomi note 8
Stock or customized system:
Stock
Nextcloud app version:
3.14.1
Nextcloud server version:
Nextcloud pi 1.32.1

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by msundin** [comment] 2020-12-07 21:58
Same problem. Worked well before last update.

**Comment by AndyScherzinger** [comment] 2020-12-07 23:19
Duplicate of #7587

**Closed by AndyScherzinger** 2020-12-07 23:19 UTC
Labels: bug
