### ISSUE TITLE
App crashes while auto-uploading

### ISSUE THREAD

**Issue by Maarico** [nextcloud/android#6279] opened 2020-06-12 08:12 UTC
### Steps to reproduce
1. Have the app auto-upload an image folder 

### Expected behaviour
- It uploads the images

### Actual behaviour
- If run in the background it just stops uploading after a few images, if run in the foreground it becomes inresponsive and crashes after a few  seconds.
[error.txt](https://github.com/nextcloud/android/files/4769553/error.txt)

**Comment by ezaquarii** [comment] 2020-06-13 20:22
@Maarico Which version of the app are you using? A similar problem has been fixed in 3.12 which is available on google play for +/- 2 days, so there is a good change this problem is already solved for you.

**Comment by trbmchs** [comment] 2020-07-03 05:22
Same issue 3.12, when loading large image set, ~450 pics

**Comment by tobiasKaminsky** [comment] 2020-07-03 14:03
Duplicate of #5805

**Closed by tobiasKaminsky** 2020-07-03 14:03 UTC
Labels: bug, needs info/discussion
