### ISSUE TITLE
nextcloud crashed

### ISSUE THREAD

**Issue by gittyhub888** [nextcloud/android#13863] opened 2024-10-23 06:22 UTC
### Cause of error
```java
Exception in thread "main" android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{745d33b u0 com.nextcloud.android.beta/androidx.work.impl.foreground.SystemForegroundService}
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2234)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:254)
    at android.app.ActivityThread.main(ActivityThread.java:8219)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20241008`
* Build flavor: `versionDev`

### Device information
* Brand: `realme`
* Device: `RMX1931L1`
* Model: `RMX1931`
* Id: `RKQ1.200928.002`
* Product: `RMX1931EEA`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `1634728216537`

**Comment by joshtrichards** [comment] 2024-10-23 14:25
Duplicate of #13798

**Closed by joshtrichards** 2024-10-23 14:25 UTC
Labels: stable-3.31 (upcoming/still dev)
