### ISSUE TITLE
crash at launch - java error ?

### ISSUE THREAD

**Issue by mblublu** [nextcloud/android#12599] opened 2024-02-25 12:00 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Launch the soft on Android 

### Expected behaviour

Accessing my files

### Actual behaviour

Error message 

### Android version

10

### Device brand and model

Motorola one zoom

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.28.0

### Nextcloud server version

?

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Stack
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3455)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3598)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2164)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:241)
    at android.app.ActivityThread.main(ActivityThread.java:7582)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Caused by: Exception in thread "main" java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Stack
    at com.owncloud.android.ui.activity.FileDisplayActivity.loadSavedInstanceState(FileDisplayActivity.java:296)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onCreate(FileDisplayActivity.java:269)
    at android.app.Activity.performCreate(Activity.java:7822)
    at android.app.Activity.performCreate(Activity.java:7811)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1328)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3598)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2164)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:241)
    at android.app.ActivityThread.main(ActivityThread.java:7582)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30280090`
* Build flavor: `gplay`

### Device information
* Brand: `motorola`
* Device: `parker`
* Model: `motorola one zoom`
* Id: `QPHS30.29-Q3-28-13-10-10`
* Product: `parker_amzeu`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `4623b`

**Comment by joshtrichards** [comment] 2024-03-26 16:42
Duplicate of #12528

**Closed by joshtrichards** 2024-03-26 16:42 UTC
Labels: bug, Version/3028
