### ISSUE TITLE
Synchronizing big folder problem / Download fails due to Doze

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#57] opened 2016-06-23 07:43 UTC
### Actual behaviour

While synchronizing 34GB of PDFs split in varying sizes
When android locks the screen, some time later a synchronization error occurs
### Expected behaviour

synchronization of all files 
### Steps to reproduce
1. use Nextcloud app to Synchronize folder
2. wait till android locks itself
3. sometime later the error will occur
### Environment data

Android version: 6.0.1

Device model: Oneplus Two

Stock or customized system: Stock OxygenOS

Nextcloud app version: 1.0.1

Nextcloud server version: 9.0.5
#### Web server error log

```
 PHP Fatal error:  Uncaught Error: Class 'OCP\Lock\ILockingProvider' not found in /var/www/html/nextcloud/lib/private/files/view.php:1129\nStack trace:\n#0 [internal function]: OC\Files\View->OC\Files\{closure}()\n#1 /var/www/html/nextcloud/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#2 [internal function]: Icewind\Streams\CallbackWrapper->stream_close()\n#3 {main}\n  thrown in /var/www/html/nextcloud/lib/private/files/view.php on line 1129
```

#### Nextcloud log (data/nextcloud.log)

```
{"reqId":"V0jILJKYwueE9Su-ZbfgbgAAAAQ","remoteAddr":"91.89.175.28","app":"PHP","message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) at \/var\/www\/html\/owncloud\/lib\/private\/image.php#515","level":3,"time":"2016-05-27T22:20:28+00:00"}
{"reqId":"V0jIUO3itPpacSu-O54@rAAAAAE","remoteAddr":"91.89.175.28","app":"PHP","message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) at \/var\/www\/html\/owncloud\/lib\/private\/image.php#515","level":3,"time":"2016-05-27T22:21:04+00:00"}
{"reqId":"V0jIURy28ueo4f-A6vlOCAAAAAY","remoteAddr":"91.89.175.28","app":"PHP","message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) at \/var\/www\/html\/owncloud\/lib\/private\/image.php#515","level":3,"time":"2016-05-27T22:21:05+00:00"}
{"reqId":"V0jIUUomMaBSwMQSnqmq4QAAAAI","remoteAddr":"91.89.175.28","app":"PHP","message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) at \/var\/www\/html\/owncloud\/lib\/private\/image.php#515","level":3,"time":"2016-05-27T22:21:05+00:00"}
{"reqId":"V0jIxITPfEMsNLHZffD@hAAAAAc","remoteAddr":"91.89.175.28","app":"PHP","message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) at \/var\/www\/html\/owncloud\/lib\/private\/image.php#515","level":3,"time":"2016-05-27T22:23:00+00:00"}
{"reqId":"V0jIyFzzmAMglKDzKD4aAwAAAAg","remoteAddr":"91.89.175.28","app":"PHP","message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) at \/var\/www\/html\/owncloud\/lib\/private\/image.php#515","level":3,"time":"2016-05-27T22:23:04+00:00"}
{"reqId":"V0jIyNGclq16mLy4OmP9AwAAAAo","remoteAddr":"91.89.175.28","app":"PHP","message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) at \/var\/www\/html\/owncloud\/lib\/private\/image.php#515","level":3,"time":"2016-05-27T22:23:04+00:00"}
{"reqId":"V0oq4VzzmAMglKDzKD4aTgAAAAg","remoteAddr":"91.89.175.28","app":"PHP","message":"Uncaught LogicException: Class OCP\Lock\ILockingProvider could not be loaded in \/var\/www\/html\/owncloud\/lib\/private\/files\/view.php:1091\nStack trace:\n#0 [internal function]: spl_autoload('OCP\\Lock\\ILocki...')\n#1 \/var\/www\/html\/owncloud\/lib\/private\/files\/view.php(1091): spl_autoload_call('OCP\\Lock\\ILocki...')\n#2 [internal function]: OC\Files\View->OC\Files\{closure}()\n#3 \/var\/www\/html\/owncloud\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/var\/www\/html\/owncloud\/lib\/private\/files\/view.php#1091","level":3,"time":"2016-05-28T23:33:53+00:00"}
{"reqId":"V1W5kKdL5xcj55T-JSM@bwAAAAc","remoteAddr":"134.3.106.30","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(_) = 0' with params [\\"files\\\\/dfbde41fea47c823d82ae317abe77801\\", 1, 1465239456, \\"files\\\\/dfbde41fea47c823d82ae317abe77801\\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'files\\/dfbde41fea47c823d82ae317abe77801' for key 'lock_key_index'\",\"Exception\":\"Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(205): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO`oc...', Array, Array)\n#3 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/db\\/adapter.php(93): OC\\DB\\Connection->executeUpdate('INSERT INTO `oc...', Array)\n#4 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/db\\/connection.php(243): OC\\DB\\Adapter->insertIfNotExist('_PREFIX_file_lo...', Array, Array)\n#5 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/lock\\/dblockingprovider.php(113): OC\\DB\\Connection->insertIfNotExist('_PREFIX_file_lo...', Array, Array)\n#6 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/lock\\/dblockingprovider.php(158): OC\\Lock\\DBLockingProvider->initLockField('files\\/dfbde41fe...', 1)\n#7 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/files\\/storage\\/common.php(663): OC\\Lock\\DBLockingProvider->acquireLock('files\\/dfbde41fe...', 1)\n#8 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/files\\/storage\\/wrapper\\/wrapper.php(577): OC\\Files\\Storage\\Common->acquireLock('files\\/DSA\\/25. T...', 1, Object(OC\\Lock\\DBLockingProvider))\n#9 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/files\\/storage\\/wrapper\\/wrapper.php(577): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\\/DSA\\/25. T...', 1, Object(OC\\Lock\\DBLockingProvider))\n#10 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/files\\/view.php(1849): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\\/DSA\\/25. T...', 1, Object(OC\\Lock\\DBLockingProvider))\n#11 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/files\\/view.php(1956): OC\\Files\\View->lockPath('\\/DSA\\/25. Tools', 1)\n#12 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/files\\/view.php(1230): OC\\Files\\View->lockFile('DSA\\/25. Tools\\/h...', 1)\n#13 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/files\\/view.php(1277): OC\\Files\\View->getCacheEntry(Object(OCA\\Files_Trashbin\\Storage), 'files\\/DSA\\/25. T...', 'DSA\\/25. Tools\\/h...')\n#14 \\/var\\/www\\/html\\/owncloud\\/apps\\/dav\\/lib\\/connector\\/sabre\\/objecttree.php(155): OC\\Files\\View->getFileInfo('\\/Administrator\\/...')\n#15 \\/var\\/www\\/html\\/owncloud\\/apps\\/dav\\/lib\\/connector\\/sabre\\/lockplugin.php(58): OCA\\DAV\\Connector\\Sabre\\ObjectTree->getNodeForPath('DSA\\/25. Tools\\/h...')\n#16 [internal function]: OCA\\DAV\\Connector\\Sabre\\LockPlugin->getLock(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#17 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#18 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#19 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#20 \\/var\\/www\\/html\\/owncloud\\/apps\\/dav\\/appinfo\\/v1\\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#21 \\/var\\/www\\/html\\/owncloud\\/remote.php(138): require_once('\\/var\\/www\\/html\\/o...')\n#22 {main}\",\"File\":\"\\/var\\/www\\/html\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/AbstractMySQLDriver.php\",\"Line\":66,\"User\":\"Administrator\"}","level":4,"time":"2016-06-06T17:57:36+00:00"}
{"reqId":"V1bwpKjwTDwgkR4k9K9HnQAAAAw","remoteAddr":"134.3.106.30","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(_) = 0' with params [\\"files\\\\/ce6ec4f462fbb3c867ed183861e22e28\\", 1, 1465319093, \\"files\\\\/ce6ec4f462fbb3c867ed183861e22e28\\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'files\\/ce6ec4f462fbb3c867ed183861e22e28' for key 'lock_key_index'\",\"Exception\":\"Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(205): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO`oc...', Array, Array)\n#3 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/db\\/adapter.php(93): OC\\DB\\Connection->executeUpdate('INSERT INTO `oc...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(243): OC\\\\DB\\\\Adapter->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/lock\\\/dblockingprovider.php(113): OC\\\\DB\\\\Connection->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/lock\\\/dblockingprovider.php(158): OC\\\\Lock\\\\DBLockingProvider->initLockField('files\\\/ce6ec4f46...', 1)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(663): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/ce6ec4f46...', 1)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(577): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/DSA', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(577): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/DSA', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1849): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/DSA', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1956): OC\\\\Files\\\\View->lockPath('\\\/DSA', 1)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1230): OC\\\\Files\\\\View->lockFile('DSA\\\/25. Tools\\\/h...', 1)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1277): OC\\\\Files\\\\View->getCacheEntry(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files\\\/DSA\\\/25. T...', 'DSA\\\/25. Tools\\\/h...')\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/objecttree.php(155): OC\\\\Files\\\\View->getFileInfo('\\\/Administrator\\\/...')\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/lockplugin.php(58): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('DSA\\\/25. Tools\\\/h...')\\n#16 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\LockPlugin->getLock(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#18 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#19 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#20 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#21 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":66,\"User\":\"Administrator\"}","level":4,"time":"2016-06-07T16:04:53+00:00"}
{"reqId":"V1cI@JU7Bkt0cmgPOaoxIQAAAAg","remoteAddr":"134.3.106.30","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'INSERT INTO`oc_file_locks`(`key`,`lock`,`ttl`) SELECT ?,?,? FROM`oc_file_locks`WHERE`key`= ? HAVING COUNT(*) = 0' with params [\\\"files\\\\\\\/ce6ec4f462fbb3c867ed183861e22e28\\\", 1, 1465325321, \\\"files\\\\\\\/ce6ec4f462fbb3c867ed183861e22e28\\\"]:\\n\\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'files\\\/ce6ec4f462fbb3c867ed183861e22e28' for key 'lock_key_index'\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\UniqueConstraintViolationException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO`oc...', Array)\n#2 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/db\\/connection.php(205): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/db\\\/adapter.php(93): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO`oc...', Array)\n#4 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/db\\/connection.php(243): OC\\DB\\Adapter->insertIfNotExist('_PREFIX_file_lo...', Array, Array)\n#5 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/lock\\/dblockingprovider.php(113): OC\\DB\\Connection->insertIfNotExist('_PREFIX_file_lo...', Array, Array)\n#6 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/lock\\/dblockingprovider.php(158): OC\\Lock\\DBLockingProvider->initLockField('files\\/ce6ec4f46...', 1)\n#7 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/files\\/storage\\/common.php(663): OC\\Lock\\DBLockingProvider->acquireLock('files\\/ce6ec4f46...', 1)\n#8 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/files\\/storage\\/wrapper\\/wrapper.php(577): OC\\Files\\Storage\\Common->acquireLock('files\\/DSA', 1, Object(OC\\Lock\\DBLockingProvider))\n#9 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/files\\/storage\\/wrapper\\/wrapper.php(577): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\\/DSA', 1, Object(OC\\Lock\\DBLockingProvider))\n#10 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/files\\/view.php(1849): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\\/DSA', 1, Object(OC\\Lock\\DBLockingProvider))\n#11 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/files\\/view.php(1956): OC\\Files\\View->lockPath('\\/DSA', 1)\n#12 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/files\\/view.php(1230): OC\\Files\\View->lockFile('DSA\\/25. Tools\\/h...', 1)\n#13 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/files\\/view.php(1277): OC\\Files\\View->getCacheEntry(Object(OCA\\Files_Trashbin\\Storage), 'files\\/DSA\\/25. T...', 'DSA\\/25. Tools\\/h...')\n#14 \\/var\\/www\\/html\\/owncloud\\/apps\\/dav\\/lib\\/connector\\/sabre\\/objecttree.php(155): OC\\Files\\View->getFileInfo('\\/Administrator\\/...')\n#15 \\/var\\/www\\/html\\/owncloud\\/apps\\/dav\\/lib\\/connector\\/sabre\\/lockplugin.php(58): OCA\\DAV\\Connector\\Sabre\\ObjectTree->getNodeForPath('DSA\\/25. Tools\\/h...')\n#16 [internal function]: OCA\\DAV\\Connector\\Sabre\\LockPlugin->getLock(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#17 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#18 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#19 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#20 \\/var\\/www\\/html\\/owncloud\\/apps\\/dav\\/appinfo\\/v1\\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#21 \\/var\\/www\\/html\\/owncloud\\/remote.php(138): require_once('\\/var\\/www\\/html\\/o...')\n#22 {main}\",\"File\":\"\\/var\\/www\\/html\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/AbstractMySQLDriver.php\",\"Line\":66,\"User\":\"Administrator\"}","level":4,"time":"2016-06-07T17:48:41+00:00"}
```

**Comment by c0fe** [comment] 2016-06-23 16:15
Confirmed using images of various sizes some being as little a few kilobytes and others being around hundred megabytes each. All JPEG, using Google Nexus 6P. NextCloud Version 1.0.1, Android 6.0.1, Android is not customized in anyway. Owncloud server: 9.0.2

**Comment by AndyScherzinger** [comment] 2016-06-23 16:21
Well the synchronisation error is yet unknown, but from the server logs it seems you are having a server side memory problem, so pinging @MorrisJobke @schiessle

**Comment by tobiasKaminsky** [comment] 2017-05-15 12:33
@Elukir @c0fe is this happening with latest server (nextcloud ;-) ) and app version?
If so, please reopen.

**Comment by c0fe** [comment] 2017-05-15 13:09
I have a server running with 64GB of memory and this happens with a folder of 300GB or more with files that are 400MB or larger.

**Comment by tobiasKaminsky** [comment] 2017-05-15 14:10
@c0fe can you maybe give us a test account where this is reproducable? Maybe you have some dummy files that are not that much private...
(email: android at nextcloud dot com)

**Comment by c0fe** [comment] 2017-05-15 15:36
I will have to generate the account and get back to you.

**Comment by tobiasKaminsky** [comment] 2017-05-19 08:22
While thinking about it, I think this might be related to the new battery saving mechanism (doze).
Android will just kill long-running background processes if the device is idle.

@c0fe does this happen to you only if the device is idle/ screen is turned off?

**Comment by c0fe** [comment] 2017-05-19 12:40
It happens with screen off

**Comment by tobiasKaminsky** [comment] 2017-07-11 09:29
@mario solution would be to move the synchronizing operation to our job scheduler system and make it bullet-proof, that it can terminate and be restarted every time, agree?

**Comment by mario** [comment] 2017-07-11 09:33
Yup but upload and downloading need changes before that

**Comment by xXSTrikeXx** [comment] 2017-10-19 11:40
Can we close this?

**Comment by joshtrichards** [comment] 2023-12-14 14:09
Too many relevant PRs to name, but 99% confident this is fixed.
Okay I'm making 99% up, but *many* things have changed since this was opened. Re-open/create a new report if this behavior returns.

**Closed by joshtrichards** 2023-12-14 14:09 UTC
Labels: bug, approved, feature: sync and upload, feature: power management
