### ISSUE TITLE
app crashing when reciving notfication

### ISSUE THREAD

**Issue by 2L3R4** [nextcloud/android#5317] opened 2020-01-26 12:31 UTC
### Steps to reproduce
1. login on a new device
2. choose "Two-Factor Authentication via Nextcloud notification" as second factor
3. watch the app crash ...

### Expected behaviour
- show notification or similar to allow/reject login

### Actual behaviour
- App crashed

### Environment data
Android version: 7.1.2

Device model: SM-G920F 

Stock or customized system: lineage OS 14.1

Nextcloud app version: 3.10.0

Nextcloud server version: 17.0.2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source)
	at com.google.firebase.iid.zzc.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/data/app/com.nextcloud.client-2/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-2/lib/arm64, /data/app/com.nextcloud.client-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Samsung
Device: zeroflte
Model: SM-G920F
Id: NJH47F
Product: zerofltexx

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: e0d6ab2e56

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-01-26 19:21
Duplicate of #4675

**Closed by AndyScherzinger** 2020-01-26 19:21 UTC
Labels: bug
