### ISSUE TITLE
Additional file permissions to auto upload from directory /storage/emulated/0/Android/data/

### ISSUE THREAD

**Issue by devang1993** [nextcloud/android#9013] opened 2021-09-27 08:48 UTC
### Steps to reproduce
1. Open Nextcloud settings and select auto upload
2. Select set up a custom folder
3. For local folder path, navigate to /storage/emulated/0/Android/data/

### Expected behaviour
- folders should be visible and available to select for auto upload

### Actual behaviour
- /storage/emulated/0/Android/data/ directory is empty

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model: Moto G5S Plus

Stock or customized system: Customized system - Pixel Experience

Nextcloud app version: 3.17.0

Nextcloud server version: 22.1.1

Reverse proxy: 

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by smacz42** [comment] 2021-12-06 07:37
Hey all,

Just wanted to chime in too and say this was one of the things I was hoping to accomplish with the app. I can't auto-upload the directories in this directory.

However, it does show one image in that directory? So is this a permissions issue? Or is this something else?

Below are my OS details. Let me know if I can help in debugging anything.

![Screenshot_20211206-023522_Settings](https://user-images.githubusercontent.com/10110994/144806009-0e00d8c5-1e57-4141-89da-a98524354f2a.png)

**Comment by smacz42** [comment] 2021-12-06 07:40
Also, I believe this issue should have the flag `feature:AutoUpload`.

**Comment by RuofengX** [comment] 2021-12-06 09:15
Possible solution: *DocumentsProvider mechanism*  
I found it here https://github.com/zhanghai/MaterialFiles/issues/480

**Comment by AlvaroBrey** [comment] 2021-12-09 09:44
[This is currently limited by Android](https://developer.android.com/about/versions/11/privacy/storage#app-specific-external) since version 11.

We'd have to take a look at the `DocumentsProvider` option, although I believe it wouldn't allow reading from `Android/data` either.

**Comment by AlvaroBrey** [comment] 2022-03-04 16:34
Confirmed that this is impossible on Android >= 11, due to platform limitations, with any of the storage mechanisms available.  Closing as `wontfix`.

**Closed by AlvaroBrey** 2022-03-04 16:34 UTC
Labels: bug
