### ISSUE TITLE
deleting a notification

### ISSUE THREAD

**Issue by buxit** [nextcloud/android#6100] opened 2020-05-18 07:44 UTC
deleting a notification i side nextcloud by pressing the x causes nexcloud client to crash:

```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.AnalyticsConnector
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Nokia
Device: PNX_sprout
Model: Nokia 8.1
Id: QKQ1.190828.002
Product: Phoenix_00WW

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 00WW_4_30C

```

**Comment by buxit** [comment] 2020-05-18 07:48
adding a new notification (by sending a message through talk) while the nextcloud app is opened leads to the same error.

**Comment by tobiasKaminsky** [comment] 2020-05-20 15:08
Duplicate of #5579

**Closed by tobiasKaminsky** 2020-05-20 15:08 UTC
Labels: bug
