### ISSUE TITLE
Data is being deleted when trying to access it in Nexcloud on Android

### ISSUE THREAD

**Issue by thwlgit** [nextcloud/android#3638] opened 2019-02-16 08:26 UTC
Hi all,

since the last update of the Nextcloud app for Android (2019-02-13) the following behaviour occurs: 

When trying to access data stored in the Nexlcoud app (doesn't matter if photos, PDFs, Keepass database or whatever) Nextcloud suggests the appropriate app to open this kind of data. So far, so good. Same behaviour as before. 
But when then trying to open it a message appears saying something like "File not found". An indeed the photo, PDF, etc. doesn't exist any longer in this location. How come? 

Tested on an Honor 8x, Android 8.1.0. 

Please find a fix, since in this state Nextcloud is not useable at all. 

Many thanks in advance! 

Regards,
Thomas

**Comment by AndyScherzinger** [comment] 2019-02-16 08:38
Hi Thomas,
Do you mean v3.5.0 (see the app's settings) or the dev version from the 13th?

It tested your use case and it is working for me on Android 9.0. Could you do a pull to refresh on the list first and check in Android's Settings of the app if the app has the storage permission granted please? ❤️

**Comment by thwlgit** [comment] 2019-02-16 21:38
Hi Andy,

yes, it's version 3.5.0, the one which was updated on my phone on the 13th. 

I just did some tests again a few minutes ago. The strange thing is now it seems to be working again? I had these issues the last two days and it was reproducible every time. But it's still the same version and now it's working. Weird ... 

Well, thanks for your reply, Andy!  :-)

**Comment by tessus** [comment] 2019-02-17 03:11
@thwlgit maybe you hit an edge case. see #3642

**Comment by tanvir1414** [comment] 2019-02-18 10:21
It is actually happening without wifi and mobile data.

**Comment by thwlgit** [comment] 2019-02-18 15:30
Yes, that's correct. Today I was able to reproduce this error: 

As long as I am connected to my Nextcloud at home (via WiFi) everything is working fine. But when I try to access my files OFFLINE (e.g. at work with no connection to my home network or somewhere else) files disappear as described initially. 

So, obviously all OFFLINE data is removed. Once I'm connected to my network again, all files are being synced to my mobile. 

Any ideas?

**Comment by thwlgit** [comment] 2019-02-18 15:32
@tessus Yes, exactly the same behaviour!

**Comment by topas-rec** [comment] 2019-02-18 19:35
Have the same problem:

> When trying to access data stored in the Nexlcoud app (doesn't matter if photos, PDFs, Keepass database or whatever) Nextcloud suggests the appropriate app to open this kind of data. So far, so good. Same behaviour as before.
But when then trying to open it a message appears saying something like "File not found".

Version 3.5.0
Android 7.1.2 (LG G4)

Issue with big consequences in my eyes. Should be fixed as separate hotfix as soon as possible to prevent data loss.

#3642 seems to be a duplicate.

**Comment by topas-rec** [comment] 2019-02-18 19:48
As @tanvir1414 mentioned it in #3642 : Somehow the menu item "Set available as offline" is also missing.
This might be an extra issue or planned behaviour, but it might be related to this issue.

**Comment by AndyScherzinger** [comment] 2019-02-18 20:25
cc @tobiasKaminsky :exclamation:

**Comment by AndyScherzinger** [comment] 2019-02-18 20:27
> Somehow the menu item "Set available as offline" is also missing

This is a planned behavior

**Comment by thwlgit** [comment] 2019-02-27 12:23
Well, don't know whether it's a new issue. But this case resulted in data loss as well: 

Connected to my WiFi at home all data was available on my Android mobile. But this time I opened the "Hamburger" menu and chose "On this device" (assuming this would provide access to data that is definitely stored on the mobile). 
Immediately the sync process started and a few seconds later the appropriate file was not deleted, but at a size of 0 KB! Unfortunately the was my Keepass database containing all my passwords ... 
So I had a 0 KB file on my mobile, a 0 KB file on my laptop and a 0 KB file on the Nextcloud server. Well, at least syncing works fine ...

Luckily I was able to restore this file from my external backup. But in such state my trust in Nextcloud is gone and I'm going to stop using it from now on. 

Summary: 
Data loss #1: When trying to access offline data this file will be deleted. 
Data loss #2: When trying to access online data via "On this device" the apropriate file remains empty.

**Comment by tobiasKaminsky** [comment] 2019-03-05 12:52
Duplicate of #3642 and fixed by #3706

**Closed by tobiasKaminsky** 2019-03-05 12:52 UTC
Labels: bug, high

**Comment by tobiasKaminsky** [comment] 2019-03-05 12:54
> So I had a 0 KB file on my mobile, a 0 KB file on my laptop and a 0 KB file on the Nextcloud server. Well, at least syncing works fine ...

You should still have the last file version accessible via versioning, either on web ui or within the app on details of the file:

![2019-03-05-135349](https://user-images.githubusercontent.com/5836855/53806751-1e4ef200-3f4e-11e9-80ed-cc24196274fa.png)

Just click on the "restore" arrow and the file gets replaced by this version.
