### ISSUE TITLE
Auto Upload on Android app creates strange `(invalid)` folder

### ISSUE THREAD

**Issue by thejohnha** [nextcloud/android#9436] opened 2021-12-02 20:36 UTC
### Steps to reproduce
1. Set up auto-upload on android app
2. Allow app to auto upload some files according to the previously set up folder
3. In the main storage folder, there is a new folder called `(invalid)`

### Expected behaviour
- There should not be a new folder called `(invalid)`

### Actual behaviour
- In the main storage folder, there is a new folder called `(invalid)`

### Environment data
Android version: 12

Device model: Pixel 4a

Stock or customized system: Stock

Nextcloud app version: 3.18.0

Nextcloud server version: 22.2.3

Reverse proxy: haproxy 2.0.19-1~bpo10+1 2020/11/07

I suspect this has to do with Android 12 as I don't remember this happening with Android 11.

**Comment by Thovi98** [comment] 2021-12-02 20:46
> I suspect this has to do with Android 12 as I don't remember this happening with Android 11.

No, I have this on Android 11 as well, I think it’s more about the new storage mecanism...

**Comment by AlvaroBrey** [comment] 2021-12-03 08:59
Duplicate of #9328

**Closed by AlvaroBrey** 2021-12-03 08:59 UTC
Labels: bug
