### ISSUE TITLE
error in application

### ISSUE THREAD

**Issue by pflippo** [nextcloud/android#13837] opened 2024-10-21 06:41 UTC
### Cause of error
```java
Exception in thread "main" android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{ef4bbe0 u0 com.nextcloud.client/androidx.work.impl.foreground.SystemForegroundService}
    at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2006)
    at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1977)
    at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2242)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7932)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300190`
* Build flavor: `generic`

### Device information
* Brand: `Fairphone`
* Device: `FP4`
* Model: `FP4`
* Id: `TKQ1.230127.002`
* Product: `FP4eea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `TP2L`

**Comment by pflippo** [comment] 2024-10-21 07:18
I get these error messages as notifications ![Image](https://github.com/user-attachments/assets/75eafc73-e809-4d30-8af3-89fc79706704)

**Comment by joshtrichards** [comment] 2024-10-21 12:50
Duplicate of #13798

**Closed by joshtrichards** 2024-10-21 12:50 UTC
