### ISSUE TITLE
Repeated Background App Crashes On Modified Android (microG)

### ISSUE THREAD

**Issue by Brat-Wurscht** [nextcloud/android#6852] opened 2020-08-29 09:48 UTC
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-xmH0rSCgkYDUfNNqvo-8RA==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-xmH0rSCgkYDUfNNqvo-8RA==/lib/arm64, /data/app/com.nextcloud.client-xmH0rSCgkYDUfNNqvo-8RA==/base.apk!/lib/arm64-v8a, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: star2lte
Model: SM-G965F
Id: PPR1.180610.011
Product: star2ltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G965FXXS7CSK4

**Comment by Natalcia** [comment] 2020-08-30 17:00
I think this should be reported to MicroG developers, not here.

**Comment by Brat-Wurscht** [comment] 2020-08-30 17:07
Hi Natalcia! Thanks for your comment.
I'm using microG quite a while now already and what I see is that only the Nextcloud app crashes. No other app has that problem. That's why I think, that the Nextcloud app seems to treat that particular situation somehow differently (less robust) than the others

**Comment by Natalcia** [comment] 2020-08-30 17:42
Ok actually that's duplicate of #4675

**Comment by tobiasKaminsky** [comment] 2020-08-31 07:54
Yes, it is a duplcate of #4675 and it is not related to MicroG, but I cannot find the cause… :-(

**Closed** 2020-08-31 07:54 UTC
Labels: bug

**Comment by Brat-Wurscht** [comment] 2020-08-31 12:17
Thanks for the feedback and the effort in general anyway!
