### ISSUE TITLE
Client auth certificate 

### ISSUE THREAD

**Issue by YodaCa** [nextcloud/android#10796] opened 2022-10-13 08:50 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Client auth with certificate not implemented or not work 

### Expected behaviour

Please check or implement 

### Actual behaviour

.

### Android version

Any

### Device brand and model

Any

### Stock or custom OS?

Stock

### Nextcloud android app version

3x

### Nextcloud server version

2.2x

### Using a reverse proxy?

No

**Comment by AlvaroBrey** [comment] 2022-10-13 10:54
This is a) an enhancement, not a bug, and b) a duplicate of #603

**Closed by AlvaroBrey** 2022-10-13 10:54 UTC
Labels: bug
