### ISSUE TITLE
App crashing on new folder creation

### ISSUE THREAD

**Issue by nicrame** [nextcloud/android#5106] opened 2020-01-07 00:36 UTC
### Steps to reproduce
1. Go to automatic upload. 
2. Add own folder (custom) 
3. When selecting folder on Nextcloud choose creat new. 
4. After entering new folder name "Rozmowy" app crashing. 

### Expected behaviour
Creat folder. 

### Actual behaviour
App crashing with many errors:

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
 at com.owncloud.android.ui.dialog.CreateFolderDialogFragment.onClick(CreateFolderDialogFragment.java:139)
 at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:224)
 at android.app.ActivityThread.main(ActivityThread.java:7520)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: cepheus
Model: MI 9 Transparent Edition
Id: QKQ1.190825.002
Product: cepheus_eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V11.0.6.0.QFAEUXM

### Environment data
Android version: 10

Device model: Xiaomi Mi9 

Stock or customized system: MIUI 11 Global EU

Nextcloud app version: 3.9.2

Nextcloud server version: 17.0.2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-01-09 14:55
@nicrame does this happen in any "place" you does this happen in the root-folder only or also if you create on in a sub-directory?

**Comment by AndyScherzinger** [comment] 2020-01-09 15:15
other than than duplicate of #4792 - please comment over there so we have all info in one central place.

**Closed by AndyScherzinger** 2020-01-09 15:15 UTC
Labels: bug
