### ISSUE TITLE
Bug: Can't upload photos directly from my gallery any more

### ISSUE THREAD

**Issue by blu-IT** [nextcloud/android#7508] opened 2020-11-26 12:01 UTC
Hello,

I am using NC client 3.14.1 RC1 on Android 9 and dicovered, that I can't mark and upload any photos from the phone gallery directly into Nexctloud. When I do so, nothing happens.

I have to open the Nexcloud client instead, go to the synced folder and click "+" here and select "Upload content from other app". Then the upload works.

Regards
### Steps to reproduce
1. Open the photo gallery on Android device
2. Select and mark a picture
3. Select "Share"
4. Select nextcloud app
5. Select folder and confirm "upload"

### Expected behaviour
- The piture(s) should be uploaded 

### Actual behaviour
- Tell us what happens: Nothing.

### Environment data
Android version: 9

Device model: Samsung Galaxy J5 (2017)

Stock or customized system:

Nextcloud app version: 3.14.1 RC1 

Nextcloud server version: 19.0.4

Reverse proxy: -

**Comment by toobie83** [comment] 2020-11-26 13:32
This bug still exists on the Rc2

**Comment by tobiasKaminsky** [comment] 2020-11-27 08:52
Is this also happening if you only share one image? Or if you use another app?

**Comment by blu-IT** [comment] 2020-11-27 08:58
> Is this also happening if you only share one image? Or if you use another app?

Yes, it also happens when I select aonly one picture. Also tried to change upload diretory, but still the same issue.

Sharing pictures with other apps (e.g. Signal Messanger) works...

**Comment by pilsnerbeer** [comment] 2020-11-29 16:14
Works for me with one pic. With more however, (needed to upload ~200 pics to NC) nothing happens - app closes and that's it.

**Comment by toobie83** [comment] 2020-11-29 18:17
> Is this also happening if you only share one image? Or if you use another app?

Using f-stop gallery since years. I tried  one Video or ten, doesn't matter how much. Nothing happens, the files are not in the queue.
Auto upload from camera or so is working well.

**Comment by tobiasKaminsky** [comment] 2020-11-30 09:10
I think it is a duplicate of https://github.com/nextcloud/android/issues/3301
There is already an idea how to "solve" this, but unfortunately I did not yet found time…

**Closed by tobiasKaminsky** 2020-11-30 09:10 UTC
Labels: bug, needs info/discussion
