### ISSUE TITLE
Nextcloud App crashing on Android 10

### ISSUE THREAD

**Issue by hviridis** [nextcloud/android#8561] opened 2021-06-11 00:34 UTC
### Steps to reproduce
1. I added 4 Nextcloud server accounts and could work with the app for several weeks
2. Today I switched to another account and the app crashed
3. Even If I force to stop the Nextcloud app it always crashed after part of a second
4. There is no chance to switch the account before the crash. Even if I cut the internet connection using NetGuard the app always crashed

### Expected behaviour
- Nextcloud should load the file list from server or tell if the server does not respond

### Actual behaviour
- after starting the app the blue logo screen vanishes and the previous file list with rotating circle (hourglass cursor) appears.
- home path of my account at https://mark.nl.tab.digital is displayed
- approx. 0.5 seconds later a white error report with overlay text "Loading..." appears; the message is:

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Fairphone
Device: FP3
Model: FP3
Id: 8901.3.A.0107.20210513
Product: FP3

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 05131326

- when switching to another app the app disappears from app switcher menu
- unders Android settings - apps I can still select the app and invoke "force stop"

### Can you reproduce this problem on https://try.nextcloud.com?
- No, probably the error will be gone if I restart Android or if I remove the app and reinstall it.

### Environment data
Android version: 10 (8901.3.A.0107.20210513)

Device model: Fairphone 3

Stock or customized system: Stock

Nextcloud app version: 3.16.1

Nextcloud server version: scan.nextclod.com says 20.0.9.1 with latest patch level and major version still supported

Reverse proxy: no

#### Web server error log
I am just user. If the service is unable or buggy I just want to deactivate it. But that is not possible without completely wiping the app and configuration data.

#### Nextcloud log (data/nextcloud.log)
I am just user.

**Comment by AndyScherzinger** [comment] 2021-06-11 20:56
Duplicate of #8370

**Closed by AndyScherzinger** 2021-06-11 20:56 UTC
Labels: bug
