### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Mas7ro** [nextcloud/android#9539] opened 2021-12-12 21:07 UTC
Nexcloud crashes on file upload and freez when i open It on wifi:

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1881)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: hero2lte
Model: SM-G935F
Id: R16NW
Product: hero2ltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G935FXXS8ETC3

**Comment by AlvaroBrey** [comment] 2021-12-13 11:58
Duplicate of #9491

**Closed by AlvaroBrey** 2021-12-13 11:58 UTC
Labels: bug
