### ISSUE TITLE
Folder names all the same

### ISSUE THREAD

**Issue by InfamousUser** [nextcloud/android#4902] opened 2019-11-29 15:51 UTC
### Actual behaviour
Opening a folder in list view with same beginning and ending in the name shows folder with same named contents.

### Expected behaviour
Contents should be differentiateable by name.
 
### Steps to reproduce
1. Install Nextcloud on Android
2. Connect to your server
3. Have contents with same beggining and ending in the name of sufficient length on your server
4. Try to view the folder content from 3. in list view and select a specific one from the list.

### Environment data
Android version: 10

Device model: Pixel 2

Stock or customized system: stock

Nextcloud app version: 3.9

Nextcloud server version: 17.0.1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by InfamousUser** [comment] 2019-12-27 17:25
You can close the issue, it's fixed.

Just kidding, fire the bot please.

**Comment by AndyScherzinger** [comment] 2020-01-08 07:31
cc @tobiasKaminsky and @nextcloud/designers - if you have long file names with same beginning/ending than due to the middlie-ellipsizing you can distinguish them.

Any idea how to resolve this, for me a to-be-close since "by design"

**Comment by tobiasKaminsky** [comment] 2020-01-08 08:55
I have no idea.
Some apps use auto scroll for long names, but while this might work for one or two items, it will not be good looking if all entries are scrolling.

Maybe designers have an idea.

**Comment by InfamousUser** [comment] 2020-01-08 09:16
It's really frustrating, I tried to watch some entertainment and, first, you can't distinguish a folder with about 40 files - all look identical, and, second, streaming doesn't work (open the issue as well).

Can you have it look at the name and display start and then parts that are definitely different, double ellipsizing the rest?
Or just being able to manually scroll the text with your finger (the whole list should scroll in sync) would already be better as I have currently found no way to view the full name except by "Rename".

**Comment by jancborchardt** [comment] 2020-01-12 08:22
Manually scrolling the text with the finger is going to be very precise and not discoverable so that’s not really proper.

But your suggestion with actually checking for sets of similarly-named files/folders and ellipsizing them accordingly sounds good.

Is this possible @tobiasKaminsky @AndyScherzinger?

**Comment by InfamousUser** [comment] 2020-01-12 10:35
Currently the only scrolling that happens is vertical  AFAIS so if you could make any horizontal scrolling on the page scroll all long item names in unison, that wouldn't be too hard I would think. But double ellipsizing if possible would be great.

**Comment by AndyScherzinger** [comment] 2020-01-13 20:37
> But your suggestion with actually checking for sets of similarly-named files/folders and ellipsizing them accordingly (either middle or end) sounds good.

> Is this possible @tobiasKaminsky @AndyScherzinger?

That depends on how to cluster the names and how to decide on the ellipsizing variant. Beware that ellipsizing is done by the OS itself, which can just specify the variant.

Horizontal scrolling within a list, I agree, is counter-intuitive since that would rather be a swipe triggering a swipe action on a list item.

**Comment by InfamousUser** [comment] 2020-02-11 04:29
Understood about horizontal scrolling.
So either ellipsizing or auto scroll for longer items, which isn't ideal solution. But then again if a file has an unusual name, even with smart ellipsizing it would be impossible to differentiate.
I would suggest smart(er) ellipsizing, with auto scroll if the proper ellipsizing cannot be determined properly

**Comment by InfamousUser** [comment] 2020-02-11 04:30
Accidental close.

**Comment by InfamousUser** [comment] 2020-03-10 12:46
.

**Comment by joshtrichards** [comment] 2023-10-16 12:12
Duplicate of #2305 

Let's centralize discussion/tracking there.

**Closed by joshtrichards** 2023-10-16 12:12 UTC
Labels: bug, approved
