### ISSUE TITLE
Auto Upload becomes Syncing

### ISSUE THREAD

**Issue by trymeouteh** [nextcloud/android#4330] opened 2019-08-16 00:56 UTC
On the desktop clients you are able to sync a folder on your computer to a folder in your cloud and as long as the client is running it will sync files and folders between these folders.

On android it is called Auto Upload. Which is handy since it will automatically upload files. I think this should be renamed to Syncing and allow you to automatically upload and download files and folders to and from the cloud on your android device. To limit its bandwidth on mobile I would like to suggest having options on how often it will sync such as every 5 minutes, 10 minutes, 30 minutes, hourly, and so on.

Also the Syncing should not be just for pictures or videos, it should be for any files and folders and I would like to suggest removing the thumbnails of the files in the auto upload menu.

**Comment by tobiasKaminsky** [comment] 2019-08-16 07:56
This is a duplicate of https://github.com/nextcloud/android/issues/285
Please comment there.

**Closed by tobiasKaminsky** 2019-08-16 07:56 UTC
Labels: enhancement
