### ISSUE TITLE
Nextcloud app drains the battery up to 39%

### ISSUE THREAD

**Issue by BLu85** [nextcloud/android#11213] opened 2022-12-31 09:40 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Battery dies before the end of the day. Nextcloud uses more CPU than any other app (Android OS itself uses 14%).
Auto-upload is enable (as it always was) but there is nothing to upload.
I have had Nextcloud for a couple of years and have never experience this.
There shouldn't be any task for Nextcloud to do.

### Expected behaviour

Go to idle when there is nothing to sync and don't drain the battery.

### Actual behaviour

Battery dies because of Nextcloud killing it.

### Android version

7.0

### Device brand and model

Huawei Nova

### Stock or custom OS?

Stock

### Nextcloud android app version

3.23.1

### Nextcloud server version

24.0.5

### Using a reverse proxy?

No

**Comment by AlvaroBrey** [comment] 2023-01-03 10:27
Duplicate of #7663

**Closed** 2023-01-08 22:56 UTC
Labels: bug
