### ISSUE TITLE
Crash with two-factor auth via notifications.

### ISSUE THREAD

**Issue by GeneriumMadness** [nextcloud/android#6776] opened 2020-08-21 15:38 UTC
### Steps to reproduce
0. Set up Russian language on your phone
1. Install two-factor auth via notifications
2. Put login and password in browser
3. Get notification
4. Confirm login and get crash

### Expected behaviour
Login confirmation

### Actual behaviour
- Login confirmation and app crashes after it

### Environment data
Android version: 10

Device model: Realme 6 pro

Stock or customized system: Stock

Nextcloud app version: 3.12.1

Nextcloud server version: 19.0.1

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
 at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
 at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
 at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
 at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
 at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.AnalyticsConnector
 ... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: realme
Device: RMX2063L1
Model: RMX2063
Id: QKQ1.191222.002
Product: RMX2063RU

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 1591676689

**Comment by tobiasKaminsky** [comment] 2020-08-24 06:58
Do you think the language matters?
If so please try it with english, otherwise it is a duplicate of #6269

**Comment by GeneriumMadness** [comment] 2020-08-24 13:42
How to change language in app?

**Comment by tobiasKaminsky** [comment] 2020-08-25 06:30
Change the language of your device.

**Comment by GeneriumMadness** [comment] 2020-08-25 09:47
Yes, everything works fine with english language, but it's still a problem with another languages.

**Comment by tobiasKaminsky** [comment] 2020-08-26 08:59
Thanks, this is strange, but maybe this helps us.
I asked in the overall issue #4675 and therefore will close this one.

**Closed by tobiasKaminsky** 2020-08-26 08:59 UTC
Labels: bug, needs info/discussion
