### ISSUE TITLE
Media Tab not showing thumbnails of photos

### ISSUE THREAD

**Issue by chrissi5120** [nextcloud/android#11431] opened 2023-02-28 17:08 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Set up app and select media folder
2. Open Media Tab
3. No Pictures Shown

### Expected behaviour

Pictures should show up when opening media tab

### Actual behaviour

https://user-images.githubusercontent.com/11377607/221923241-94782f6d-d4b7-41a7-a3fd-fe35f98228f2.mp4

### Android version

13

### Device brand and model

Google Pixel 6A

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.1

### Nextcloud server version

25.0.4

### Using a reverse proxy?

Yes

### Server error logs

```bash
phone_IP - user [28/Feb/2023:18:05:05 +0100] "DELETE /ocs/v2.php/apps/notifications/api/v2/push HTTP/1.1" 200 138 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.24.1"
phone_IP - user [28/Feb/2023:18:05:05 +0100] "GET /ocs/v2.php/cloud/user?format=json HTTP/1.1" 200 457 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.24.1"
phone_IP - user [28/Feb/2023:18:05:07 +0100] "OPTIONS /remote.php/dav HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.24.1"
phone_IP - user [28/Feb/2023:18:05:07 +0100] "SEARCH /remote.php/dav HTTP/1.1" 207 172464 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.24.1"
phone_IP - user [28/Feb/2023:18:05:10 +0100] "OPTIONS /remote.php/dav HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.24.1"
phone_IP - user [28/Feb/2023:18:05:10 +0100] "SEARCH /remote.php/dav HTTP/1.1" 207 172456 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.24.1"

This is all traffic while pulling down to refresh in Media-Tab 3 times!
```

### Additional information

Manual Workaround:

1. After Step one, manually browse ALL Folders and Subfolders involved, forcing the app to pull thumbs
2. Open Media Tab
3. Pictures are Shown

The behaviour repeats itsels as soon as media is added, I have to manually browse the corresponding folders again, causing the thumbs in media-tab to show up.

You can clearly see that there is NO server-traffic going on in this timeframe (see logs above), it seems as the client isnt even trying to pull the thumbs.

This Happens for ALL my Android devices for years now and is beyond annoying. 

I tested:

- Galaxy S8
- Multiple Xaiomi Redmi Phones
- Pixel 6a
- Galaxy Tab 7

IOS has no Issue.

**Comment by AlvaroBrey** [comment] 2023-03-01 08:27
Duplicate of #10389

**Closed by AlvaroBrey** 2023-03-01 08:27 UTC
Labels: bug
