### ISSUE TITLE
App crashes when playing a video

### ISSUE THREAD

**Issue by sangaman** [nextcloud/android#7414] opened 2020-11-21 05:57 UTC
### Steps to reproduce
1. Play a video within the app

### Expected behaviour
Video plays. 

### Actual behaviour
Video plays for a few seconds and then crashes the app with the following message.

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3590964 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2050)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7470)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWBLA
Model: BLA-A09
Id: HUAWEIBLA-A09
Product: BLA-A09

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 277C567R1

### Environment data
Android version: 9

Nextcloud app version: 3.14.0

**Comment by AndyScherzinger** [comment] 2020-11-23 09:08
Duplicate of #6905

**Closed by AndyScherzinger** 2020-11-23 09:08 UTC
Labels: bug
