### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by drewblasphemepatchwork** [nextcloud/android#7292] opened 2020-11-10 18:50 UTC
### Steps to reproduce
1. Create an account with webo.hosting
2. Login to the account with the Android client from F-Droid
3. Batch delete the premade documents

### Expected behaviour

- Tell us what should happen
Files should get deleted

### Actual behaviour
- Tell us what happens

App crashed at the middle of deleting
### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{295b9f5 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus3
Model: ONEPLUS A3003
Id: QQ3A.200805.001
Product: lineage_oneplus3

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: eng.root.20201109.222239

**Comment by tobiasKaminsky** [comment] 2020-11-11 08:35
Duplicate of #6905, as it is the same root cause.

**Closed by tobiasKaminsky** 2020-11-11 08:35 UTC
