### ISSUE TITLE
Crash when change theme blank to white

### ISSUE THREAD

**Issue by fakiehmaulana** [nextcloud/android#8953] opened 2021-09-07 15:37 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to pause activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@df6efe8
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4873)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4819)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4767)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:228)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:58)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5563)
	at android.app.ActivityThread.access$3500(ActivityThread.java:257)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2145)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@df6efe8
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1439)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1652)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:726)
	at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.onInactive(UsbConnectionDispatcher.java:131)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.ensureStateInactive(SecurityKeyManager.java:316)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.refreshActiveState(SecurityKeyManager.java:290)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.onActivityPaused(SecurityKeyManager.java:333)
	at android.app.Application.dispatchActivityPaused(Application.java:468)
	at android.app.Activity.dispatchActivityPaused(Activity.java:1466)
	at android.app.Activity.onPause(Activity.java:2424)
	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:388)
	at com.owncloud.android.ui.activity.BaseActivity.onPause(BaseActivity.java:84)
	at com.owncloud.android.ui.activity.FileActivity.onPause(FileActivity.java:253)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onPause(FileDisplayActivity.java:1254)
	at android.app.Activity.performPause(Activity.java:8344)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1511)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4863)
	... 16 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: POCO
Device: alioth
Model: M2012K11AG
Id: RKQ1.200826.002
Product: alioth_id

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: V12.5.2.0.RKHIDXM

**Comment by AndyScherzinger** [comment] 2021-09-07 15:39
@AlvaroBrey guess this one is fixed by your lib-downgrade, no?

**Comment by kangaroo72** [comment] 2021-09-07 20:55
I can confirm the issue on my Samsung Note 10+

**Comment by AlvaroBrey** [comment] 2021-09-08 10:03
> @AlvaroBrey guess this one is fixed by your lib-downgrade, no?

Yes, this is a duplicate of #8585 and should be fixed by https://github.com/nextcloud/android/pull/8941

**Comment by AlvaroBrey** [comment] 2021-09-08 10:03
Duplicate of  #8585

**Closed by AlvaroBrey** 2021-09-08 10:03 UTC
Labels: bug, needs info/discussion
