### ISSUE TITLE
0

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#2295] opened 2018-03-05 22:04 UTC
0

**Comment by xXSTrikeXx** [comment] 2018-03-05 23:08
Try latest v. 3.0.3 ;)

**Comment by procyon12lotor** [comment] 2018-03-06 00:06
Just upgraded to 3.0.2. I'll have to wait until 3.0.3 drops in F-Droid, but this issue persists in 3.0.2

**Comment by khaosjrm** [comment] 2018-03-06 14:20
I think the bug goes beyond. My Android phone got updated to version Android 7 and autoupload does not work for me, neither wifi, internet, vpn or whatever :( I thought it was a Nextcloud version issue, so I updated my server to 13.0 and still same issue. It looks it's an App problem.

**Comment by khaosjrm** [comment] 2018-03-06 14:27
I had the same problem, confirmed it worked fine again with 3.0.3...pheeewww!!!

**Comment by mario** [comment] 2018-03-06 14:28
VPN is probably a known issue and reported elsewhere already. Will fix when I get to it.

**Comment by tobiasKaminsky** [comment] 2018-03-08 13:54
So this can be closed as it is working for @khaosjrm?

**Comment by mario** [comment] 2018-03-08 13:56
Nah can't. VPN really doesn't work.

**Comment by procyon12lotor** [comment] 2018-03-08 17:48
Cool. It's not a big deal as you can set Nextcloud as an excluded app.

Just FYI. It DID work in Lineage 14.1 (Android 7.1) and the same setup (Always on OpenVPN imported from .ovpn with default settings) no longer works when I upgraded to 15.1. The only problem is that Nextcloud doesn't know that WiFi+VPN is still WiFi. If you turn off "only upload on WiFi", it uploads as it should.

What's with the mismatch in F-droid version which is currently at 3.0.2?

**Comment by pedrxd** [comment] 2018-03-11 20:59
For me still not working, using vpn can't auto-upload. Using vpn is the unique way for connect to my server. Any solution?

**Comment by albirs** [comment] 2018-03-13 11:32
it could be an LineageOS 15.1 problem. I have read ([here ](https://forum.xda-developers.com/android/apps-games/app-netguard-root-firewall-t3233012/post75734284#post75734284)) that the VPN implementation in LOS 15.1 doesn't work properly...

**Comment by mario** [comment] 2018-03-19 18:08
Well, to be honest - the settings in auto upload is "Upload on unmetered wifi". When you're on VPN, you don't have unmetered bandwith...

So not sure if this is a bug after thinking about it.

**Comment by procyon12lotor** [comment] 2018-03-19 22:22
@mario In my Auto-upload settings menu, the option is "Only upload on Wi-Fi". 
The point of this setting is to not waste metered cellular bandwidth which is a finite and expensive resource, but instead to wait to upload on WiFi which is usually an unlimited resource. That is the only reason that setting exists. The existence of the VPN should be and IS irrelevant.

In my case, I have a VPN at my house so all traffic when I am not at home appears to come from my house because I frequently use public WiFi. An added benefit of this is that it is an easy way to connect to the Nextcloud server from within my home subnet. It seems like @pedrxd uses this as the only way to access their server. I have been setting Nextcloud for Android as an excluded app from within OpenVPN, but this is not an option for those like @pedrxd.

I guess it is theoretically possible to connect to a VPN that is metered? That is not the intention of that setting. Every other app that has a setting like this (including THIS app on Android 7.1!) ignores the VPN.

**Comment by procyon12lotor** [comment] 2018-03-20 02:58
@mario This is probably a Lineage 15.1 (or Android 8.1?) bug.
[https://jira.lineageos.org/browse/BUGBASH-1495](url)

**Comment by pedrxd** [comment] 2018-03-20 06:09
@procyon12lotor I am using lineage 15.1 . It can be the problem

**Comment by mario** [comment] 2018-03-20 06:40
@procyon12lotor we changed the wording in MASTER since "Only upload on unmetered Wi-Fi" is more correct for what the toggle does. I can detect VPN (of course!), and see if you're also on Wi-Fi (of course!), but cannot detect if the Wifi you're on is unmetered at the same time since it's not the active network :( 

But hmm...

@procyon12lotor that bug looks rejected?

**Comment by procyon12lotor** [comment] 2018-03-21 06:20
I understand now, thanks! I think you can close it. Some apps can either distinguish, or consider all WiFi to be unmetered, but others (Nextcloud, OsmAnd) are having the same thing.

@mario The Lineage guys only deal with bug reports on weekends, so it will probably get reopened then.

**Comment by procyon12lotor** [comment] 2018-04-06 22:15
@mario @pedrxd Is there any way you guys can remove my @username from your comments above? Thanks!!

**Comment by comradekingu** [comment] 2018-04-07 08:55
@procyon12lotor Edited them so you don't get notifications, will do so with this one too.

**Comment by procyon12lotor** [comment] 2018-04-08 20:27
@comradekingu I mean completely remove. I'm trying to get this username to not be indexed by search engines. Thanks.

**Comment by AndyScherzinger** [comment] 2018-04-08 20:33
@procyon12lotor that is not possible since Github doesn't allow complete deletions in any way

**Closed by AndyScherzinger** 2018-04-08 20:33 UTC
Labels: bug

**Comment by procyon12lotor** [comment] 2018-04-10 00:48
@AndyScherzinger 
**https://help.github.com/articles/deleting-a-comment/ 
"People with write access to a repository can delete comments on issues, pull requests, and commits. Organization owners, team maintainers, and the comment author can delete a comment on a team page."**

@AndyScherzinger 
**https://help.github.com/articles/editing-a-comment/
"People with write access to a repository can edit comments on issues, pull requests, and commits. Organization owners, team maintainers, and the comment author can edit a comment on a team page.

It's appropriate to edit a comment and remove content that doesn't contribute to the conversation and violates your community's code of conduct or GitHub's Community Guidelines."**

@comradekingu ALREADY edited my username. @pedrxd ALREADY deleted my username as I asked. Keep the comment, but change the username in ANY way, that is what I'm asking. I just want my username to not be indexed by search engines. Instead the number of instances of my username in the thread is currently multiplying. You are either going to do it or not. I would hate to reduce the value of this important issue: 
Subject: "0 #2295" 
Author: ghost 
Body: "0"

**Comment by AndyScherzinger** [comment] 2018-04-10 07:37
I'll now delete all your comments as requested.
