### ISSUE TITLE
Auto upload/sync not working for some devices on latest Android app 3.14.1

### ISSUE THREAD

**Issue by Mazvy** [nextcloud/android#7627] opened 2020-12-07 20:30 UTC
### Steps to reproduce
1. Add folder to auto sync

### Expected behaviour
- Auto upload

### Actual behaviour
- Nothing happens

### Environment data
Android version: 10

Device model: Oppo F11 Pro

Stock or customized system: stock

Nextcloud app version: 3.14.1

Nextcloud server version: 20.0.2

Reverse proxy: no

#### Web server error log
No errors in apache, php or the nextcloud admin panel.

Auto sync/upload from Oppo F11 Pro will not work for any folder, however multiple different Samsung devices work without any issues and immediately start uploading once the cloud icon has been pressed.

I requested the user to install a dev build (nextcloud-dev-20201205) and here are the logs from the device 
[logs.txt](https://github.com/nextcloud/android/files/5655138/logs.txt)

**Comment by wiswedel** [comment] 2020-12-07 20:56
duplicate of https://github.com/nextcloud/android/issues/7617

**Comment by Mazvy** [comment] 2020-12-07 21:00
Not sure why this is a duplicate of #7617 as manual uploads for files & pictures work just fine, only auto sync doesn't work.

**Comment by artiomamerhanov** [comment] 2020-12-08 01:52
Same problem with Android 9 on Huawei.

**Comment by hardwareadictos** [comment] 2020-12-08 12:00
Same issue here on Android 11, Pixel 4 XL

![Screenshot_20201208-124013~2](https://user-images.githubusercontent.com/20403906/101481342-4e15ff80-3955-11eb-9d73-b40e66a5c9c6.png)
![Screenshot_20201208-125139](https://user-images.githubusercontent.com/20403906/101481280-33438b00-3955-11eb-8fad-6048d152c492.png)
[nextcloud_log.txt](https://github.com/nextcloud/android/files/5659111/nextcloud_log.txt)

Tried using another remote directory, seems to happen when i upload files with a major size of 1MB.

**Comment by Mazvy** [comment] 2020-12-08 12:16
@wiswedel manual file uploads work regardless of file size, type or how many are uploaded at once - auto sync is what doesn't work for certain devices, this is not the same issue you referred to. 

Samsung S7, S8 and S9 all running different versions of android (7, 8, 10 respectively) all have auto sync working perfectly on the same Nextcloud server, however the Oppo phone no matter of power settings will not auto sync however manual uploads work just fine from within the app.

**Comment by artiomamerhanov** [comment] 2020-12-08 12:20
Just installed previous version, 3.14.0. Seems working fine. Android 9 on Huawei.

**Comment by Mazvy** [comment] 2020-12-08 15:34
The user downgraded to 3.14.0 and 3.13.1 and auto sync didn't work on any version.

**Comment by Valdnet** [comment] 2020-12-08 17:32
Re-opened due to #7634.

**Comment by AndyScherzinger** [comment] 2020-12-08 17:39
@Mazvy 
```
2020-12-07T21:58:39.559+0200;V;SyncedFolderProvider;Storing synced folder id1 with enabled=true
2020-12-07T21:58:39.562+0200;V;SyncedFolderProvider;Updating /storage/emulated/0/DCIM/Camera with enabled=true
```

looks good. 

* Is Nextcloud excluded from battery optimization?
* Does it upload newly taken pictures _after_ activating it for the folder
* Does the upload view show any entries related to the camera folder after that or is it just empty

Depending on the phone it might take up to 15 minutes until sheduling kicks in.

**Comment by Mazvy** [comment] 2020-12-08 17:50
>     * Is Nextcloud excluded from battery optimization?
Yes - "disable" is selected when the popup appears when activating the folder
>     * Does it upload newly taken pictures _after_ activating it for the folder
No
>     * Does the upload view show any entries related to the camera folder after that or is it just empty
For regular folders (screenshots, IM apps) - nothing. For the Camera folder it appears that various .bin files related the the camera (front_camera_SN.bin and similar) where in fact uploaded at some point.

> Depending on the phone it might take up to 15 minutes until sheduling kicks in.
24+ hours and nothing on the latest version, 2+ hours for the previous versions I mentioned - nothing.

**Comment by AndyScherzinger** [comment] 2020-12-08 20:12
.bin files shouldn't be uploaded for standard folders. Did you simply activate folders shown in the auto upload view or did you create a custom folder setup?

**Comment by Mazvy** [comment] 2020-12-08 20:21
> 
> 
> .bin files shouldn't be uploaded for standard folders. Did you simply activate folders shown in the auto upload view or did you create a custom folder setup?

Activated only standard folders shown in the auto upload list.

**Comment by AndyScherzinger** [comment] 2020-12-08 21:01
@tobiasKaminsky any ideas what to look for?

**Comment by Mazvy** [comment] 2020-12-09 12:23
@AndyScherzinger I _think_ this can be closed. The user disabled battery optimizations _manually_ in **Android settings** as per instructions [here ](https://support.getfindster.com/hc/en-us/articles/360000666497-Disabling-battery-optimization-on-Android-smartphones-for-Findster-Duo-) and it seems auto sync is working for old and new photos for the camera feed, not yet tested for IM, screenshots and other folders. I can report back on that in the next 24 hours or so. Tested in dev-20201208.

I'm guessing the popup in the app to disable battery optimizations isn't working on some Android handsets? I'd suggest perhaps introducing some kind of logic to detect if a folder isn't properly syncing in some period of time and inform the user that they might need to go to Android settings and disable battery optimization manually there (with a link to a guide similar to what I linked above). As no errors or information is provided by Nextcloud it's hard for end users to troubleshoot this issue - they pressed the "disable battery optimizations" button and I'd wager most don't even know where to find that in Android settings or that it even is a thing. I asked multiple times if the user disabled battery optimization and they said yes thinking the button in the popup was all they needed to press. The information in the popup is a bit vague and with no clear instructions for end users. 

Regarding the .bin files - it was confirmed that only the default picture folders where added to auto sync, something might worth investigating on your end perhaps.

**Comment by AndyScherzinger** [comment] 2020-12-09 12:33
Well, the pop-up is just an info that this needs to be done and would redirect you to the Android Battery Optimization screen as far as I know. So it needs to be done manually anyways.

As for the bin file, that is tricky to analyze now since I can't say when this has been uploaded since the latest changes to auto upload added further file type and folder filtering logic.
It would be interesting though to get this reported again if this happens again.

**Closed by AndyScherzinger** 2020-12-09 12:33 UTC
Labels: bug

**Comment by Mazvy** [comment] 2020-12-09 14:09
> 
> 
> Well, the pop-up is just an info that this needs to be done and would redirect you to the Android Battery Optimization screen as far as I know. So it needs to be done manually anyways.
> 
> As for the bin file, that is tricky to analyze now since I can't say when this has been uploaded since the latest changes to auto upload added further file type and folder filtering logic.
> It would be interesting though to get this reported again if this happens again.

@AndyScherzinger pressing "disable" in the popup just closes the popup on all devices tested (listed in a previous post) without opening android settings, which is why I assume users interpret this as if they've successfully disabled battery optimization. If opening the battery optimization options isn't reliable (as it appears to be the case).

I'd suggest replacing "disable" in the popup or just adding another buttton "guide how to disable" linking to something similar as in my previous post. This combined with simple logic to detect if a folder isn't syncing would mitigate this issue - if a folder isn't syncing in a given time frame - inform the user and link to a guide on how to disable battery optimization in the android settings.
