### ISSUE TITLE
Automated bug report after app crash

### ISSUE THREAD

**Issue by BasJ93** [nextcloud/android#8764] opened 2021-07-24 11:51 UTC
### Steps to reproduce
1. Upload a bunch of files
2. Wait
3. 

### Expected behaviour
- The files should be uploaded

### Actual behaviour
- The entire app crashes

### Can you reproduce this problem on https://try.nextcloud.com?
- No, I can't even reproduce the bug again on my own server.

### Environment data
Android version: 10

Device model: GS290

Stock or customized system: Stock

Nextcloud app version: 3.16.1

Nextcloud server version: 20.0.7

Reverse proxy: yes

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1844)
		at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1884)
			at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:329)
				at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:294)
					at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:355)
						at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:307)
							at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:442)
								at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:72)
									at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:34)
										at android.os.AsyncTask.finish(AsyncTask.java:755)
											at android.os.AsyncTask.access$900(AsyncTask.java:192)
												at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
													at android.os.Handler.dispatchMessage(Handler.java:107)
														at android.os.Looper.loop(Looper.java:214)
															at android.app.ActivityThread.main(ActivityThread.java:7417)
																at java.lang.reflect.Method.invoke(Native Method)
																	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
																		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Gigaset
Device: GS290
Model: GS290
Id: QP1A.190711.020
Product: GS290_EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 1620883903
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2022-03-03 14:46
Closing because it can't be reproduced

**Closed by AlvaroBrey** 2022-03-03 14:46 UTC
Labels: bug
