### ISSUE TITLE
3.15.0 RC1 Media section shows wrong/no media

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#7851] opened 2021-01-15 21:10 UTC
Tested with different smartphones (Oneplus, Huawei) on different servers.
On one account I see no data at all before the update there were a lot
Or I see only videos
Or a log of pics are missing but some are shown and some vids, too. 

The iOS App works good here, maybe we can copy the query from there?

**Comment by JSkier21** [comment] 2021-02-03 22:57
With the release of 3.15, I'm seeing this as well. Some (not all) older pictures and videos show up, nothing from past couple of week though. Very odd behavior. I'm using OnePlus 5 and Android 10.

**Comment by kuzmos** [comment] 2021-02-09 13:12
Same here - Samsung s10+, after update to 3.15 no photos or videos in Media are displayed. When I browse in All files, the content is shown. Using only External storage.

**Comment by tobiasKaminsky** [comment] 2021-02-10 09:54
@AndyScherzinger do you have an idea? I remember that you changed how/which folders are detected?

**Comment by AndyScherzinger** [comment] 2021-02-10 12:54
@tobiasKaminsky wrong area ;) I changes the media detection for the auto upload screen. This issue is about the media screen (formally photos) which you changed to show images/videos and is related to the changed server query. --> #6820

**Comment by tobiasKaminsky** [comment] 2021-02-18 07:13
Duplicate of #7245

**Closed by tobiasKaminsky** 2021-02-18 07:13 UTC
Labels: bug, needs info/discussion

**Comment by saywebsolutions** [comment] 2021-02-23 20:44
Is this actually a duplicate of #7245 ? That one is about failing to load additional entries after scrolling to the bottom.

This issue which I and a lot of others are experiencing does not have to do with scrolling to the bottom and loading additional media entries, but rather that only a small subset of old photos/videos are now shown in the 'Media' tab of the app and none of the user's recent photos show up. Anyways something has seriously gone awry separate to the issue in #7245 it seems.

Maybe stemming from the same server side issue/changes that you've mentioned though, in any case will the broken updates be rolled back until the server side is fixed? Or what's the best thing to do for user's with broken 'Media' area of app now? Thank you

**Comment by kuzmos** [comment] 2021-02-24 10:04
My displayed subset in Media tab is so small that it is actually zero :)

**Comment by tobiasKaminsky** [comment] 2021-02-24 12:11
Showing wrong items and/or taking too long to load is the same cause: a suboptimal query for pictures, thus I want to track it both in the same issue.

**Comment by kuzmos** [comment] 2021-03-01 11:08
After updating the Nextcloud server to 21 a new error started appearing in server log while trying to display Media from Android app:
`Doctrine\DBAL\Query\QueryException: More than 1000 expressions in a list are not allowed on Oracle.`
