### ISSUE TITLE
Upload conflict: Keep existing file does not terminate upload

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/android#9318] opened 2021-11-19 09:52 UTC
### Steps to reproduce
1. Upload a file for sake of testing
2. Trigger the same upload again to create a conflict
3. Go to the upload list in the app
4. Click on the failed upload (manual conflict resolution)
5. Mark _Keep current version_ and click ok

### Expected behaviour
The conflict should be resolved and the message should no longer be present in the upload list.

### Actual behaviour
The conflict keeps reappearing and one needs to manually select _Remove_ in order to clean up the upload list.

When uploading the new version (with or without keeping the existing one), the conflict is solved and after the upload moved to the _Done_ section.

### Can you reproduce this problem on https://try.nextcloud.com?
Not tested as a pure UI issue

### Environment data
Android version: 10

Device model: Doogee S96 Pro

Stock or customized system: Stock

Nextcloud app version: 3.18.0 RC6

Nextcloud server version: 22.2.3

Reverse proxy: Apache

#### Web server error log
No relevant logs found.

#### Nextcloud log (data/nextcloud.log)
No relevant logs found.

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2021-11-30 09:09
Duplicate of #7905

**Closed by AlvaroBrey** 2021-11-30 09:09 UTC
Labels: bug
