### ISSUE TITLE
Notification Text didn't show

### ISSUE THREAD

**Issue by Dtrieb** [nextcloud/android#11454] opened 2023-03-14 02:53 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

If I get a notification I only see variable text.
See screenshot 

### Expected behaviour

Show the right notification 

### Actual behaviour

![Screenshot_20230314-034316~2](https://user-images.githubusercontent.com/3650284/224880687-513c94eb-9a30-451a-aa43-1a06e5334e2d.png)

### Android version

12

### Device brand and model

Gigaset GX4

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.1

### Nextcloud server version

X

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment] 2023-03-16 22:20
Weird. Do the same bogus strings show up under Notifications section in the app itself (i.e. while in the NC client swipe left and select Notifications)?

**Comment by RoepLuke** [comment] 2023-05-08 15:33
I too have this problem, every time I get any serverside Notification and i do not have the Nextcloud-App in focus while recieving it. I think using App-PIN set to 'Device Logindata' also played a role in it. I'll test again. Already had seen this problem a long time ago but didn't bother to create an issue back then.

**Comment by petrcech** [comment] 2023-06-15 11:05
Hi, I've got the same problem. Using Oneplus 8T Android 13

**Comment by joshtrichards** [comment] 2023-10-07 22:59
Duplicate of #1964

**Closed by joshtrichards** 2023-10-07 22:59 UTC
Labels: bug
