### ISSUE TITLE
Crash of client after upgrade from NC18 to NC22

### ISSUE THREAD

**Issue by wbxqm** [nextcloud/android#9076] opened 2021-10-08 19:19 UTC
### Steps to reproduce
1. no idea, sorry. The app keeps crashing ever since I upgraded to NC22
2. upon starting the app, it run for ca. 3 seconds, then freezes
3. sometimes the trace window pops up, offering to create a bug report.

### Expected behaviour
- Tell us what should happen
I used to be able to open the app and browse my NC instance

### Actual behaviour
- Tell us what happens
The app opens, and reacts normally for 2-3 seconds. If I am quick, I can open sttings before the app freezes, or browse to a subfolder. Once the app freezes, it will not als ake anymore.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
lineageos ginkgo based on android 10
Device model: 
redmi note 8)
Stock or customized system:
customized, I think
Nextcloud app version:
dev 20210928
Nextcloud server version:
22

************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 1085, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:332)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:309)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:675)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2117)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:371)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:532)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:520)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1875)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:438)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:529)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:408)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:238)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:363)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210928
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: ginkgo
Model: Redmi Note 8
Id: QQ3A.200805.001
Product: ginkgo

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: eng.me1.20200810.094723

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2022-03-03 16:38
Duplicate of #6103

**Closed by AlvaroBrey** 2022-03-03 16:38 UTC
Labels: bug
