### ISSUE TITLE
Crash on video playback

### ISSUE THREAD

**Issue by goldengel** [nextcloud/android#7193] opened 2020-11-01 10:08 UTC
### Steps to reproduce
1. Upload new MP4 on Windows client
2. select new folders and MP4 file on Android App
3. play the video 
4. After Playback of 5 seconds
5.  click in video 
6. the app crashes 

### Error log of Android app

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b3ba260 u0 com.nextcloud.android.beta/com.nextcloud.client.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1946)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201014
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Nokia
Device: B2N_sprout
Model: Nokia 7 plus
Id: QKQ1.190828.002
Product: Onyx_00WW

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 00WW_4_15H

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-11-01 13:46
@goldengel can you reliably reproduce this crash this way? Cause this might help a lot since talking to @ezaquarii @tobiasKaminsky made it clear we lack a consistent description of steps to produce this error.

**Comment by goldengel** [comment] 2020-11-01 14:19
I think it's when there is no video Caches on first Playback and it starts to play video. I had no more crash when downloading the same video.


here again the log of another video. I ve tested with 12 videos. 

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{9ed460c u0 com.nextcloud.android.beta/com.nextcloud.client.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1946)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201014
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Nokia
Device: B2N_sprout
Model: Nokia 7 plus
Id: QKQ1.190828.002
Product: Onyx_00WW

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 00WW_4_15H

**Comment by rbwrightjr91** [comment] 2020-11-07 23:32
Not sure if useful, but I am also seeing this issue:

```
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{365fa36 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: redfin
Model: Pixel 5
Id: RD1A.201105.003.C1
Product: redfin

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 6886399
```

**Comment by tobiasKaminsky** [comment] 2020-11-11 08:36
Duplicate of #6905, as it is the same root cause.

**Closed by tobiasKaminsky** 2020-11-11 08:36 UTC
Labels: bug
