### ISSUE TITLE
Add action to a text file in the current directory

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#417] opened 2016-12-01 15:54 UTC
From the play store reviews:

> A feature to quickly create a text file in the current directory would be very handy!

What do you think @nextcloud/android and @jancborchardt @eppfel from a UI/UX perspective? We would then have to add this to the 3-dot menu (since I vote for not putting it into the FAB button actions, since I do not consider it a "primary action").

**Comment by strugee** [comment] 2016-12-01 18:25
I think it makes sense in the FAB. The label is a plus icon, which in terms of iconography makes it the obvious place to find it. You use the FAB to add a folder, add a file, or add a text file.

**Comment by tobiasKaminsky** [comment] 2016-12-02 11:48
What would be the use case of adding an empty text file?
AFAIK there is a PR (or maybe it is already included) which allows sending text snippets to nextcloud app.
Unless we have a real, but maybe limited, text editor I do not see the purpose of adding empty text files...

**Comment by eppfel** [comment] 2016-12-02 20:31
Yeah, use-case would be important. If it is about Notes, we have to think, how to integrate such a workflow.

The FAB would be the right place, but we already have 3 options (2 of them quite similar), so right now. I am unsure, if we should pursue this...

**Comment by strugee** [comment] 2016-12-02 22:46
@tobiasKaminsky it makes sense to do this if we can create the file and then open it in a third-party app. Not sure exactly how that'd work, technically speaking.

(Which doesn't necessarily mean I support this feature, just that if we _did_ add it, that's what makes sense IMHO.)

**Comment by tobiasKaminsky** [comment] 2016-12-03 08:43
For this use case my workflow would be:
- write text in an external app
- share it to nextcloud app

After that the text file can of course be opened in our app and choose the the external editor.

**Comment by eppfel** [comment] 2016-12-03 19:01
So, if we can do what @strugee proposed, we could implement it. Otherwise :-1:

What @tobiasKaminsky proposed is already possible, right?

**Comment by jancborchardt** [comment] 2016-12-05 13:38
Totally agree with @tobiasKaminsky here:

> Unless we have a real, but maybe limited, text editor I do not see the purpose of adding empty text files

I also would say though that we should indeed have basic text editing in the app (just a big textarea and only plaintext). Because it’s a pretty basic file manipulation action.

Also cc @stefan-niedermann of the Android Notes app.

**Comment by AndyScherzinger** [comment] 2016-12-05 14:42
If we go for having text editing capabilities we still need to set some rules. I case we create plain text files that they should then always be let's say UTF-8 encoded, and we will also have to deal with with handling encoding right, to not mess up text files and yes @stefan-niedermann with all his knowledge would be a great help with this matter.

**Comment by joshtrichards** [comment] 2023-10-12 21:06
Added in #4915 / #4890

And #4930 sort of a duplicate of this issue (mentioning merely for reference - it was already closed out by the above PRs).

**Closed by joshtrichards** 2023-10-12 21:06 UTC
Labels: enhancement, low, needs info
