### ISSUE TITLE
App crashes when trying to login with 2FA notifications enabled

### ISSUE THREAD

**Issue by major-mayer** [nextcloud/android#5453] opened 2020-02-11 17:18 UTC
### Steps to reproduce
1. Open Nextcloud Android App
2. Start Login Process in a new browser window with 2FA activated and notifications activated
3. See what happens to the android app

### Expected behaviour
- App should not crash, but show the notification to accept the login

### Actual behaviour
- App Crashes

### Environment data
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.AnalyticsConnector
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: dipper
Model: MI 8
Id: QQ1D.200105.002
Product: dipper

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: eng.zenix.20200201.164126

Nextcloud server version: 17.0.2

#### Web server error log
```
[notifications] Info: GuzzleHttp\Exception\ClientException: Client error: `POST https://push-notifications.nextcloud.com/notifications` resulted in a `400 Bad Request` response:


 at <<closure>>

 0. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 66
    GuzzleHttp\Exception\RequestException::create(GuzzleHttp\Psr7\Request {}, "*** sensitive parameter replaced ***")
 1. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 203
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 2. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 156
    GuzzleHttp\Promise\Promise::callHandler(1, "*** sensitive parameter replaced ***", [GuzzleHttp\Prom ... l])
 3. /var/www/html/3rdparty/guzzlehttp/promises/src/TaskQueue.php line 47
    GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 246
    GuzzleHttp\Promise\TaskQueue->run(true)
 5. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 223
    GuzzleHttp\Promise\Promise->invokeWaitFn()
 6. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 267
    GuzzleHttp\Promise\Promise->waitIfPending()
 7. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 225
    GuzzleHttp\Promise\Promise->invokeWaitList()
 8. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 62
    GuzzleHttp\Promise\Promise->waitIfPending()
 9. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php line 131
    GuzzleHttp\Promise\Promise->wait()
10. /var/www/html/lib/private/Http/Client/Client.php line 212
    GuzzleHttp\Client->request("post", "https://push-no ... s", {proxy: null,ver ... e})
11. /var/www/html/apps/notifications/lib/Push.php line 143
    OC\Http\Client\Client->post("https://push-no ... s", {form_params: {n ... }})
12. /var/www/html/apps/notifications/lib/App.php line 50
    OCA\Notifications\Push->pushToDevice(78, OC\Notification\Notification {})
13. /var/www/html/lib/private/Notification/Manager.php line 214
    OCA\Notifications\App->notify(OC\Notification\Notification {})
14. /var/www/html/custom_apps/twofactor_nextcloud_notification/lib/Service/NotificationManager.php line 62
    OC\Notification\Manager->notify(OC\Notification\Notification {})
15. /var/www/html/custom_apps/twofactor_nextcloud_notification/lib/Service/TokenManager.php line 99
    OCA\TwoFactorNextcloudNotification\Service\NotificationManager->newNotification(OCA\TwoFactorNex ... 1})
16. /var/www/html/custom_apps/twofactor_nextcloud_notification/lib/Provider/NotificationProvider.php line 98
    OCA\TwoFactorNextcloudNotification\Service\TokenManager->generate("****")
17. /var/www/html/core/Controller/TwoFactorChallengeController.php line 158
    OCA\TwoFactorNextcloudNotification\Provider\NotificationProvider->getTemplate(OC\User\User {})
18. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 170
    OC\Core\Controller\TwoFactorChallengeController->showChallenge("twofactor_nextcloud_notification", null)
19. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OC\Core\Controll ... {}, "showChallenge")
20. /var/www/html/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Controll ... {}, "showChallenge")
21. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OC\\Core\\Contr ... r", "showChallenge", OC\AppFramework\ ... {}, {challengeProvid ... "})
22. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({challengeProvid ... "})
23. /var/www/html/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {challengeProvid ... "})
24. /var/www/html/lib/base.php line 997
    OC\Route\Router->match("/login/challeng ... n")
25. /var/www/html/index.php line 42
    OC::handleRequest()

GET /login/challenge/twofactor_nextcloud_notification
from 94.114.48.226 by **** at 2020-02-11T17:05:23+00:00
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-02-11 22:00
Duplicate of #4675

**Closed** 2020-02-11 22:01 UTC
Labels: bug
