### ISSUE TITLE
### Cause of error
```java
Exception in thread "Thread-3" java.lang.IllegalArgumentException: Trying to execute a sync operation with a storage manager for an anonymous account
    at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:49)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$fetchExternalLinks$9(DrawerActivity.java:1231)
    at com.owncloud.android.ui.activity.DrawerActivity.$r8$lambda$oHM2j1MZkviAIdyIFWoI2kSeF9c(Unknown Source:0)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `OPPO`
* Device: `OP4FA7L1`
* Model: `CPH2237`
* Id: `TP1A.220905.001`
* Product: `CPH2237`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `R.18f2f27-1`


### ISSUE THREAD

**Issue by ChumVeha** [nextcloud/android#13803] opened 2024-10-17 17:00 UTC
### Cause of error
```java
Exception in thread "Thread-3" java.lang.IllegalArgumentException: Trying to execute a sync operation with a storage manager for an anonymous account
    at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:49)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$fetchExternalLinks$9(DrawerActivity.java:1231)
    at com.owncloud.android.ui.activity.DrawerActivity.$r8$lambda$oHM2j1MZkviAIdyIFWoI2kSeF9c(Unknown Source:0)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `OPPO`
* Device: `OP4FA7L1`
* Model: `CPH2237`
* Id: `TP1A.220905.001`
* Product: `CPH2237`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `R.18f2f27-1`

**Comment by joshtrichards** [comment] 2024-10-18 14:13
Duplicate of #13323

**Closed by joshtrichards** 2024-10-18 14:13 UTC
