### ISSUE TITLE
App crash when entering first letter of new spreadsheet name

### ISSUE THREAD

**Issue by CodeArtha** [nextcloud/android#11240] opened 2023-01-09 22:01 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Server configured with onlyoffice for handling office documents. Nextcloud android app v3.23.1 running on Android 10.
2. On the app in one of the folders hit the '+' button to show the create new document/folder menu. Select 'add a spreadsheet'
3. A dialog opens asking for the name of the new .ods document. When entering the first letter of the name the app hardcrashes going straight to the following log

### Expected behaviour

Let me enter the name and then create and open said document.

### Actual behaviour

Cfr "steps to reproduce"
Note that opening a document that already exists works without problem.

### Android version

10

### Device brand and model

Xiaomi 9T pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.23.1

### Nextcloud server version

23.0.2

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.lib.common.Template.getExtension()' on a null object reference
    at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.checkEnablingCreateButton(ChooseTemplateDialogFragment.kt:254)
    at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.access$checkEnablingCreateButton(ChooseTemplateDialogFragment.kt:69)
    at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$onCreateDialog$2.afterTextChanged(ChooseTemplateDialogFragment.kt:154)
    at android.widget.TextView.sendAfterTextChanged(TextView.java:10588)
    at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13429)
    at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1277)
    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
    at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:315)
    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:507)
    at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:305)
    at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:49)
    at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:843)
    at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:616)
    at android.view.inputmethod.InputConnectionWrapper.setComposingText(InputConnectionWrapper.java:142)
    at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:393)
    at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:224)
    at android.app.ActivityThread.main(ActivityThread.java:7560)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230191`
* Build flavor: `gplay`

### Device information
* Brand: `Xiaomi`
* Device: `raphael`
* Model: `Mi 9T Pro`
* Id: `QKQ1.190825.002`
* Product: `raphael_eea`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `V12.0.4.0.QFKEUXM`

**Comment by AlvaroBrey** [comment] 2023-01-17 13:56
Duplicate of #10668

**Closed by AlvaroBrey** 2023-01-17 13:56 UTC
Labels: bug
