### ISSUE TITLE
App crashes [OOM] when trying to move pictures to another folder

### ISSUE THREAD

**Issue by OnkelTomsHuette** [nextcloud/android#11912] opened 2023-08-22 10:22 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Select some (~20) pictures in my autoupload folder
2. Move them to a new folder
3. Apply

### Expected behaviour

App moves the pictures to the new destination.

### Actual behaviour

The App moves some pictures and then crashes with the shown error log.

### Android version

13

### Device brand and model

OnePlus 6T (Fajita)

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

30250090

### Nextcloud server version

Nextcloud Hub 5 (27.0.0)

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "Thread-53" java.lang.OutOfMemoryError: Failed to allocate a 5920 byte allocation with 2175184 free bytes and 2124KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
    at org.apache.jackrabbit.webdav.MultiStatus.getResponses(MultiStatus.java:128)
    at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.readData(ReadFolderRemoteOperation.java:151)
    at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:88)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:205)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:405)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:239)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30250090`
* Build flavor: `generic`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus6T`
* Model: `ONEPLUS A6013`
* Id: `TQ3A.230605.012`
* Product: `OnePlus6T`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `eng.root.20230704.184435`

### Additional information

Im using Lineageos 20-20230704-microG-fajita

**Comment by joshtrichards** [comment] 2024-07-10 20:19
Duplicate of #9903

**Closed by joshtrichards** 2024-07-10 20:19 UTC
Labels: bug, performance: OOM :brain:, Version/3025
