### ISSUE TITLE
`TransactionTooLargeException` in `onCheckAvailableSpaceFinish()`

### ISSUE THREAD

**Issue by lucasrs09** [nextcloud/android#13399] opened 2024-08-11 12:16 UTC
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2469128 bytes
    at android.app.ActivityClient.finishActivity(ActivityClient.java:167)
    at android.app.Activity.finish(Activity.java:6849)
    at android.app.Activity.finish(Activity.java:6866)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:524)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:58)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:20)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loopOnce(Looper.java:238)
    at android.os.Looper.loop(Looper.java:357)
    at android.app.ActivityThread.main(ActivityThread.java:8088)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
Caused by: Exception in thread "main" android.os.TransactionTooLargeException: data parcel size 2469128 bytes
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(BinderProxy.java:584)
    at android.app.IActivityClientController$Stub$Proxy.finishActivity(IActivityClientController.java:1446)
    at android.app.ActivityClient.finishActivity(ActivityClient.java:164)
    at android.app.Activity.finish(Activity.java:6849)
    at android.app.Activity.finish(Activity.java:6866)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:524)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:58)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:20)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loopOnce(Looper.java:238)
    at android.os.Looper.loop(Looper.java:357)
    at android.app.ActivityThread.main(ActivityThread.java:8088)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `motorola`
* Device: `dubai`
* Model: `motorola edge 30`
* Id: `T1RDS33.116-33-15-8`
* Product: `dubai_g`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `5a543-33cdf1`

**Comment by joshtrichards** [comment] 2024-08-30 22:10
Duplicate of #10242

**Closed by joshtrichards** 2024-08-30 22:10 UTC
Labels: bug, performance: TTLE, Version/3029
