### ISSUE TITLE
Download new version doesn't work

### ISSUE THREAD

**Issue by bapjg** [nextcloud/android#8099] opened 2021-03-03 18:17 UTC
### Steps to reproduce
1. I use the  development android client downloaded on 28th feb
2. Yesterday, a button appears saying download more recent version. 
3. When I click on the button, it send me to the site where my nextcloud server is (in house server). 

### Expected behaviour
- I would have expected to send me to a github download site, or anywhere other than my personal documents in house nc server

### Actual behaviour
- see above

### Can you reproduce this problem on https://try.nextcloud.com?
- happens every time
- if I use get latest version from the settings menu, I get the same erroneous result

### Environment data
Android version: 9

Device model: honor v10

Stock or customized system:

Nextcloud app version:

Nextcloud server version: 21

Reverse proxy:

#### Web server error log
Not relevant
Insert your webserver log here
```Not relevant


#### Nextcloud log (data/nextcloud.log)
```Not relevant

Insert your Nextcloud log here
```Not relevant

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2021-03-05 06:43
Duplicate of #8100

**Closed by tobiasKaminsky** 2021-03-05 06:43 UTC
Labels: bug
