### ISSUE TITLE
Settings (Android apps)

### ISSUE THREAD

**Issue by BugProg** [nextcloud/android#4979] opened 2019-12-10 15:48 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.ui.activity.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
	at com.owncloud.android.ui.activity.SettingsActivity.setupGeneralCategory(SettingsActivity.java:712)
	at com.owncloud.android.ui.activity.SettingsActivity.onCreate(SettingsActivity.java:168)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20191206
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5T
Model: ONEPLUS A5010
Id: PQ3A.190605.003
Product: OnePlus5T

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: INFORMATION

https://www.home-cloud.fr/s/nRygwN7oA4yET4d
The link to watch the vidéo.

**Comment by AndyScherzinger** [comment] 2019-12-10 15:49
@BugProg can you please update to latest dev version? This should be fixed by the newer builds.

**Comment by BugProg** [comment] 2019-12-10 15:53
Thank you !
But for the moment I don't have the update.
I use F-Droid

**Comment by tobiasKaminsky** [comment] 2019-12-11 08:51
Duplicate of #4955

**Closed by tobiasKaminsky** 2019-12-11 08:51 UTC
Labels: bug
