### ISSUE TITLE
Mark / create issues for 2.0.1 milestone

### ISSUE THREAD

**Issue by mario** [nextcloud/android#1266] opened 2017-08-04 19:18 UTC
- minor improvement for existing features
- bug fixes
- UX improvements of existing features

Shall we keep this small? Say 4 weeks development time?

**Comment by AndyScherzinger** [comment] 2017-08-04 19:30
Sounds good, yeah! :+1:

**Comment by AndyScherzinger** [comment] 2017-08-04 21:03
@mario @tobiasKaminsky any opinion on shipping 1.5.0 beta to the play store if Google doesn't fix the build in the near future? Right now this seems to be the only thing blocking the new auto upload from being merged to master and being shipped. While the broken build tools also block f-droid :/

**Comment by mario** [comment] 2017-08-05 04:49
@tobiasKaminsky few issues remain. Empty view, cookies, and search stuff. After that, regardless of the toolchain, I'd upload a beta, yes.

**Comment by tobiasKaminsky** [comment] 2017-08-07 06:20
This will get us a lot of questions why it is not on fdroid...
Is there some expectation when google will release their non-alpha toolchain?

**Comment by mario** [comment] 2017-08-07 06:28
@tobiasKaminsky afaik, with my change of disabling aapt2, the build should work even on f-droid...

**Comment by tobiasKaminsky** [comment] 2017-08-07 08:12
I thought the problem is 
`
The android gradle plugin version 2.5.0-alpha-preview-02 is too old, please update to the latest version.
To override this check from the command line please set the ANDROID_DAILY_OVERRIDE environment variable to "b1d1dd5e04b214c9d03015fd26059447d1f207e6"
`
(as currently also on drone).

So yes, we/you can do a public beta for google play store, created by branch #797 (with all other 1.5 merges in it).
But still #797 may not be merged until the toolchain is non-alpha.

This way we can test the build, but will not break our CI.

**Comment by mario** [comment] 2017-08-07 08:20
@tobiasKaminsky we're actually using 3.0.0-alpha9. Dunno why Travis thinks otherwise...

Cool, so as soon as all other things are merged to master I can rebase and do a public beta.

But please, please - review that branch and merge others as soon as possible.

**Comment by AndyScherzinger** [comment] 2017-08-07 08:22
@mario the 3.0.0-alpha9 is imho not on the branch on github but still the 2.5.0-*

**Comment by AndyScherzinger** [comment] 2017-08-07 08:23
@tobiasKaminsky if we can fix the build on drone I'd guess we can get it to work on f-droid too while it might take some time for f-droid to provide the updated build tools.

**Comment by mario** [comment] 2017-08-07 08:23
@AndyScherzinger don't be silly? https://github.com/nextcloud/android/blob/mediaStoreAutoUpload/build.gradle

**Comment by AndyScherzinger** [comment] 2017-08-07 08:25
Ah, you did that during the last days, didn't have a laptop with me. Just saw just updated it 👍

**Comment by mario** [comment] 2017-08-07 08:26
@AndyScherzinger yea, so dunno why Travis thinks it's still 2.5 *shrug*

**Comment by AndyScherzinger** [comment] 2017-08-07 08:27
I'll check it out later today :)

**Comment by AndyScherzinger** [comment] 2017-10-20 15:07
Should we close this issue @mario?

**Comment by mario** [comment] 2017-10-20 15:20
Yes

**Closed** 2017-10-20 15:23 UTC
Labels: needs info/discussion
