### ISSUE TITLE
Mobile app 3.9.0 crashed looking at file details

### ISSUE THREAD

**Issue by Coleej** [nextcloud/android#4951] opened 2019-12-05 12:54 UTC
### Actual behaviour
Android app crashed when chevking file details

### Expected behaviour
look at details
 
### Steps to reproduce
1. open app
2. check file details

### Environment data
see below for bug output copy/pasted on mobile. contact me for more details

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at com.owncloud.android.utils.ThemeUtils.primaryColor(ThemeUtils.java:139)
	at com.owncloud.android.utils.ThemeUtils.primaryColor(ThemeUtils.java:125)
	at com.owncloud.android.ui.preview.PreviewTextFragment.getRenderedMarkdownText(PreviewTextFragment.java:284)
	at com.owncloud.android.ui.preview.PreviewTextFragment.setText(PreviewTextFragment.java:562)
	at com.owncloud.android.ui.preview.PreviewTextFragment.lambda$performSearch$0$PreviewTextFragment(PreviewTextFragment.java:270)
	at com.owncloud.android.ui.preview.-$$Lambda$PreviewTextFragment$8cnNMZfHrJC_BSC1jdHMw1eFOds.run(lambda)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: klteatt
Model: SAMSUNG-SM-G900A
Id: MMB29M
Product: klteuc

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: G900AUCS4DQD1

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by EmPeWe** [comment] 2020-01-01 20:03
I have this Bug too. F-Droid v3.9.2

**Comment by tobiasKaminsky** [comment] 2020-01-06 13:52
Hm. Which kind of file do you open?
I tried it with a wide variety of files and it did not yet crashed…

**Comment by EmPeWe** [comment] 2020-01-06 18:15
In my case it's details view of any folder. Not files, sorry for the mistake. At the moment, I'm running 3.9.2 from F-Droid.

**Comment by Coleej** [comment] 2020-01-06 22:30
It was a plain text file, specifically my contacts as exported by Android.

I think its called "Contacts.vcf"

**Comment by AndyScherzinger** [comment] 2020-01-13 07:29
it is, it's a duplicate of #4836 - thus closing in favor

**Closed by AndyScherzinger** 2020-01-13 07:29 UTC
Labels: bug
