### ISSUE TITLE
Scroll bar on large folders

### ISSUE THREAD

**Issue by jerkitu** [nextcloud/android#4665] opened 2019-10-12 08:09 UTC
Hi, could a scrollbar be implemented when moving through folders on Android?  In a folder with many photos, it is difficult to navigate.  
thanks

**Comment by maurerle** [comment] 2020-01-22 21:04
This is a duplicate of #47. I too hope that this will be implemented.
I think this issue can be closed.

**Comment by tobiasKaminsky** [comment] 2020-01-23 11:15
True, Duplicate of #47

**Closed by tobiasKaminsky** 2020-01-23 11:15 UTC
Labels: enhancement
