### ISSUE TITLE
App crashes when moving lots of files 

### ISSUE THREAD

**Issue by Licmeth** [nextcloud/android#10709] opened 2022-09-03 08:30 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Select files in one folder (mine had very many files in it, around 2000)
2. Choose move files from menu
3. Select destination folder
4. App crashes (see stack trace below) 

### Expected behaviour

Files should be moved instead of crash 

### Actual behaviour

App crashes and shows:

 ### Cause of error
```java
Exception in thread "Thread-31" java.lang.IllegalStateException: Couldn't read row 710, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetString(Native Method)
    at android.database.CursorWindow.getString(CursorWindow.java:462)
    at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:54)
    at android.database.CursorWrapper.getString(CursorWrapper.java:141)
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:967)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:894)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:189)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:241)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:398)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210190`
* Build flavor: `generic`

### Device information
* Brand: `Xiaomi`
* Device: `cupid`
* Model: `2201123G`
* Id: `SKQ1.211006.001`
* Product: `cupid_eea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `V13.0.19.0.SLCEUXM`

### Android version

12 SKQ1.211006.001

### Device brand and model

Xiaomi 12 (2201123G)

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.1

### Nextcloud server version

24.0.3

### Using a reverse proxy?

No

**Comment by AlvaroBrey** [comment] 2022-09-03 15:39
Duplicate of #9948

**Closed by AlvaroBrey** 2022-09-03 15:39 UTC
Labels: bug
