### ISSUE TITLE
Ability to specify a default external app when opening video files (mp4)

### ISSUE THREAD

**Issue by Dho100** [nextcloud/android#5374] opened 2020-02-02 17:58 UTC
On my Android 9 and 10 device, streaming mp4 videos is slow and choppy. I don't have issues streaming the videos when I use the "Stream with..." function to stream the video using the Photos app (Google Photos), and would prefer just to have the videos open in Photos instead of the Nextcloud app by default for all mp4 file extensions.

Request is to enable users to define default external apps to open specific file extensions with  by default.

Thank you!

**Comment by AndyScherzinger** [comment] 2020-02-05 14:23
@tobiasKaminsky please comment. Form my point of view we do have this for classic "open" while for streaming we can really implement this (since it is a link?) or is this also possible?

**Comment by joshtrichards** [comment] 2023-10-19 17:03
Duplicate of #378 

Let's consolidate tracking of this enhancement there. Feel free to subscribe and/or upvote and/or add to the discussion on that issue!

**Closed by joshtrichards** 2023-10-19 17:03 UTC
Labels: enhancement, needs info, feature: media player
