### ISSUE TITLE
Android App Crash when clicking on a document file. (No online office installed)

### ISSUE THREAD

**Issue by Beowulf2** [nextcloud/android#5319] opened 2020-01-26 19:19 UTC
### Steps to reproduce
1. Click in the app on a .doc file.
2. On the NextCloud Server Onlyoffice isn't install.
3. App crashes

### Expected behaviour
- The file should open in an extern Office App on the Phone

### Actual behaviour
- App crash

### Environment data
Android version: 9

Device model: moto G6

Stock or customized system: Stock

Nextcloud app version: 3.10.0

Nextcloud server version: 17.0.2

### Log
###App Log
************ CAUSE OF ERROR ************

javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@19831027@19.8.31 (100308-284611645):27)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
	at okhttp3.RealCall.execute(RealCall.java:93)
	at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:126)
	at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:67)
	at com.owncloud.android.lib.resources.activities.GetActivitiesRemoteOperation.run(GetActivitiesRemoteOperation.java:131)
	at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:63)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$5$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:331)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$N7POe6TZvoGcuV2qP-niPxY_7t4.run(Unknown Source:12)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:661)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:539)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.google.android.gms.org.conscrypt.Platform.checkTrusted(:com.google.android.gms@19831027@19.8.31 (100308-284611645):2)
	at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(:com.google.android.gms@19831027@19.8.31 (100308-284611645):1)
	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(:com.google.android.gms@19831027@19.8.31 (100308-284611645):7)
	at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@19831027@19.8.31 (100308-284611645):6)
	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@19831027@19.8.31 (100308-284611645):14)
	... 26 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	... 40 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: ali_n
Model: moto g(6)
Id: PPSS29.55-37-7-2
Product: ali_n

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 924b9

**Comment by Beowulf2** [comment] 2020-01-26 19:23
Ok it only crashes when the file isn't saved locale, when i download the file first and click then on it, it works fine.

**Comment by AndyScherzinger** [comment] 2020-01-26 19:23
@Beowulf2 My guess: you are using self-signed SSL certificates?

Other than that:

Duplicate of #5235

**Closed by AndyScherzinger** 2020-01-26 19:23 UTC
Labels: bug

**Comment by Beowulf2** [comment] 2020-01-26 19:31
How can I fix the problem, because I use NextCloud only in the local network and with a VPN for access from outside so I cannot use another SSL certifikcat, or?

**Comment by Beowulf2** [comment] 2020-01-26 20:20
And a lot of people use it like me and not everyone has this same problem... Why?

**Comment by AndyScherzinger** [comment] 2020-01-26 20:54
This issue needs to be fixed within the app in my opinion.

**Comment by Beowulf2** [comment] 2020-01-26 21:52
So I can do nothing and must wait for an update?

**Comment by AndyScherzinger** [comment] 2020-01-26 22:11
Don't know for sure, maybe @tobiasKaminsky knows.

**Comment by Beowulf2** [comment] 2020-01-27 18:35
Ok now I have a SSL Certificat from letsencrypt and now the app work fine.

**Comment by AndyScherzinger** [comment] 2020-01-27 18:56
Glad to hear, other than that there is a fix, that will be shipped with the upcoming bugfix release.
