### ISSUE TITLE
Crashes after update 

### ISSUE THREAD

**Issue by Goldentongue111** [nextcloud/android#11406] opened 2023-02-20 15:56 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Open app

### Expected behaviour

Should connect to server 

### Actual behaviour

Crashes upon opening app load 

### Android version

13

### Device brand and model

Samsung `SM-S908U`

### Stock or custom OS?

Stock

### Nextcloud android app version

30240090

### Nextcloud server version

30240090

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "Thread-11" java.lang.StringIndexOutOfBoundsException: begin 0, end 8, length 5
    at java.lang.String.checkBoundsBeginEnd(String.java:3942)
    at java.lang.String.substring(String.java:2467)
    at com.owncloud.android.datamodel.OCFile.getLocalId(OCFile.java:606)
    at com.owncloud.android.datamodel.FileDataStorageManager.createContentValuesBase(FileDataStorageManager.java:461)
    at com.owncloud.android.datamodel.FileDataStorageManager.createContentValuesForFolder(FileDataStorageManager.java:478)
    at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:392)
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:538)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:409)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:239)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `b0q`
* Model: `SM-S908U`
* Id: `TP1A.220624.014`
* Product: `b0qsqw`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `S908USQS2BWA2`

**Comment by AlvaroBrey** [comment] 2023-02-20 18:38
Duplicate of #11389

**Closed by AlvaroBrey** 2023-02-20 18:38 UTC
Labels: bug
