### ISSUE TITLE
Search input text gets cleared

### ISSUE THREAD

**Issue by TtuxX** [nextcloud/android#11542] opened 2023-04-19 14:10 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

When I open Nextcloud android app and go directly to the search bar without waiting, the first few letters I type inside it gets cleared. It happens juste once initial launch refresh has ended.
Thus I lose that I started typing and it gets frustrating needing to click again on the search bar and typing again what I just started typing.

On my android phone: 

1. Open Nextcloud android app. The initial refresh will automatically trigger.
2. Without waiting, click on the search bar
3. Start typing something
4. The letters you'll type will get reset very quickly and you are being kicked out of the search input field
5. You need to start over again from step 2 and this time (as the initial app refresh has ended), search will work 

### Expected behaviour

Whether the Nextcloud app triggers an initial refresh on launch or not, user should not get kicked-out of any search field and the refresh should happen in background in a non-blocking way.

### Actual behaviour

User has to fight the app a bit

### Android version

11

### Device brand and model

Samsung Galaxy A20e

### Stock or custom OS?

Stock

### Nextcloud android app version

Nextcloud Dev version 20230414 + Nextcloud vesion 3.24.1

### Nextcloud server version

Nextcloud 25.0.5

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment] 2023-12-23 15:41
Duplicate of #9481

**Closed by joshtrichards** 2023-12-23 15:41 UTC
Labels: bug, feature: search
