### ISSUE TITLE
Can't import nextcloud file to my download folder

### ISSUE THREAD

**Issue by AdvisedlyAlburn** [nextcloud/android#8266] opened 2021-04-11 23:05 UTC
I go to the nextcloud app on android, click on download some files. Instead of being downloaded in the download folders (or at least having an option to do so), they are downloaded into some obscure folder. Then I have to move the files from that folder to a public folder where my Gallery app for example can detect the images. 

I know it's related to the new way file access is handled by Android, but I'm pretty sure there is a way to make it happen. Too lazy to download Dropbox but I bet they have a way.

**Comment by AndyScherzinger** [comment] 2021-04-12 15:05
Duplicate of #1192

**Closed by AndyScherzinger** 2021-04-12 15:05 UTC
Labels: enhancement

**Comment by AndyScherzinger** [comment] 2021-04-12 15:06
@AdvisedlyAlburn In case you just want Android to index the downloaded media please check the Nextcloud app's settings for the storage location preference. Some locations are accessible to Android and its Gallery and some some don't yo you might be able to achieve this even without a downlaod to the Android download-folder option.

**Comment by AdvisedlyAlburn** [comment] 2021-04-12 15:29
@AndyScherzinger  Are you talking about the "Data storage folder" option in the settings? When I click on it, it only displays 3 options, all the 3 options are obscure folders like /storage/emulated/0/Android/media/... 
(I already gave nextcloud the file permissions)

**Comment by AndyScherzinger** [comment] 2021-04-12 15:45
To answer your question: yes! :)
