### ISSUE TITLE
unexpected crash right after installation

### ISSUE THREAD

**Issue by CorradoLanera** [nextcloud/android#9619] opened 2021-12-25 17:34 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.SecurityException: uid 10538 cannot get user data for accounts of type: nextcloud
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4907)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4944)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.SecurityException: uid 10538 cannot get user data for accounts of type: nextcloud
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
	at android.os.Parcel.createException(Parcel.java:2369)
	at android.os.Parcel.readException(Parcel.java:2352)
	at android.os.Parcel.readException(Parcel.java:2294)
	at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:1326)
	at android.accounts.AccountManager.getUserData(AccountManager.java:516)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.<init>(OCFileListAdapter.java:162)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onActivityCreated(OCFileListFragment.java:353)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2996)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:580)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:451)
	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:436)
	at com.owncloud.android.ui.activity.BaseActivity.onResume(BaseActivity.java:91)
	at com.owncloud.android.ui.activity.DrawerActivity.onResume(DrawerActivity.java:989)
	at com.owncloud.android.ui.activity.FileActivity.onResume(FileActivity.java:246)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1156)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
	at android.app.Activity.performResume(Activity.java:8353)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4897)
	... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.accounts.AccountManagerService.getUserData(AccountManagerService.java:1685)
	at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:453)
	at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1121)
	at android.os.Binder.execTransactInternal(Binder.java:1190)
	at android.os.Binder.execTransact(Binder.java:1159)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond1
Model: SM-G973F
Id: RP1A.200720.012
Product: beyond1lteeea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: G973FXXSEFUL1

**Comment by AlvaroBrey** [comment] 2021-12-26 16:09
Is this on a work profile?

**Comment by CorradoLanera** [comment] 2021-12-26 16:35
No, is on a private installation. It worked properly some days ago when I have installed it on rpi at home. Next, yesterday, the android app was totally freezed at the splash screen. Still freezed at startup even after reboot. So, I have deleted and reinstalled it, and at the first run it ask me to send you this report. Closed and reopened the app, now it seams to work properly, without any other intervention.

**Comment by AlvaroBrey** [comment] 2022-01-03 16:16
Ok, that is very strange. However I can't reproduce it, and if you can't anymore there isn't much we can do unless it pops up again.

**Comment by CorradoLanera** [comment] 2022-01-03 18:39
I can confirm that up to now it still works smoothly.

**Comment by AlvaroBrey** [comment] 2022-01-04 10:12
Alright, closing this, feel free to reopen if it comes back. Thank you!

**Closed by AlvaroBrey** 2022-01-04 10:12 UTC
Labels: bug, needs info/discussion
