### ISSUE TITLE
Favorites shows 'No files here' instead of 'Loading' before showing favorites

### ISSUE THREAD

**Issue by iGadget** [nextcloud/android#9408] opened 2021-11-30 23:35 UTC
### Steps to reproduce
1. Open Favorites (perhaps on a slow(er) NC server, mine is an LXC instance on a 3rd Gen i5)
2. 'No files here' is shown while the app downloads / syncs the favorites from the server, instead of 'Loading'
3. Favorites are shown.

### Expected behaviour
- The app should show 'Loading' when it's loading the list of files from the server.

### Actual behaviour
- 'No files here' is shown while the app downloads / syncs the favorites from the server, instead of 'Loading'. Please, *never* show 'No files here' when there is actually content on the server, as this is a) incorrect and b) really freaks people out.

### Can you reproduce this problem on https://try.nextcloud.com?
- Will set this all up if really needed.

### Environment data
Android version: 10

Device model: Fairphone 3+

Stock or customized system: stock

Nextcloud app version: 3.18.0

Nextcloud server version: 21.0.7

Reverse proxy: Nginx Proxy Manager v2.9.7

#### Web server error log
```
Will provide webserver logs if really needed
```

#### Nextcloud log (data/nextcloud.log)
```
Will provide Nextcloud logs if really needed
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

- Issue Template is not supported on NC 21.

**Comment by AlvaroBrey** [comment] 2021-12-01 09:20
Same issue as #9373, so I'm expanding that one to cover Favorites too, and closing this one. Thank you @iGadget .

**Comment by AlvaroBrey** [comment] 2021-12-01 09:21
Duplicate of #9373

**Closed by AlvaroBrey** 2021-12-01 09:21 UTC
Labels: bug
