### ISSUE TITLE
Ошибка при создании нового текстового документа в клиенте Nextcloud

### ISSUE THREAD

**Issue by Deboart** [nextcloud/android#5518] opened 2020-02-25 14:18 UTC
При попытке создания текстового документа из клиента

************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.IllegalStateException: Fragment ChooseTemplateDialogFragment{353478b (688bc7cc-9edb-4842-8b1f-8a2c527f89e9)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:774)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$CreateFileFromTemplateTask.doInBackground(ChooseTemplateDialogFragment.java:258)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$CreateFileFromTemplateTask.doInBackground(ChooseTemplateDialogFragment.java:211)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 5 
more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200213
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWELE
Model: ELE-L29
Id: HUAWEIELE-L29
Product: ELE-L29RU

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.186C10

### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2020-03-21 19:22
Duplicate of #5550

**Closed** 2020-03-21 19:22 UTC
Labels: bug
