### ISSUE TITLE
Crashed under picture upload

### ISSUE THREAD

**Issue by xsession** [nextcloud/android#13462] opened 2024-08-24 15:53 UTC
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Fragment PreviewMediaFragment{9ab47c1} (ae55d0af-20aa-4249-887b-5290fca32641) not attached to a context.
    at androidx.fragment.app.Fragment.requireContext(Fragment.java:972)
    at com.owncloud.android.ui.preview.PreviewMediaFragment.lambda$onStart$1(PreviewMediaFragment.java:351)
    at com.owncloud.android.ui.preview.PreviewMediaFragment.$r8$lambda$uDaoT5tCd_EnFoVGkfSYFCOoOr4(Unknown Source:0)
    at com.owncloud.android.ui.preview.PreviewMediaFragment$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:299)
    at android.app.ActivityThread.main(ActivityThread.java:8319)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `Redmi`
* Device: `joyeuse`
* Model: `Redmi Note 9 Pro`
* Id: `SKQ1.211019.001`
* Product: `joyeuse_eea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `V14.0.5.0.SJZEUXM`

**Comment by joshtrichards** [comment] 2024-08-30 22:51
Duplicate of #13256

**Closed by joshtrichards** 2024-08-30 22:51 UTC
Labels: bug, performance: ISE/IAE :confused:, stable-3.29
