### ISSUE TITLE
nextcloud app crashed during upload

### ISSUE THREAD

**Issue by Y-Gry** [nextcloud/android#5911] opened 2020-04-21 18:49 UTC
### Steps to reproduce
1. upload mutliple files automatically
2. If it starts uploading, open the NC App

************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 1011, col 1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetString(Native Method)
	at android.database.CursorWindow.getString(CursorWindow.java:438)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
	at android.database.CursorWrapper.getString(CursorWrapper.java:137)
	at com.owncloud.android.datamodel.UploadsStorageManager.createOCUploadFromCursor(UploadsStorageManager.java:321)
	at com.owncloud.android.datamodel.UploadsStorageManager.getUploads(UploadsStorageManager.java:302)
	at com.owncloud.android.datamodel.UploadsStorageManager.getFailedUploads(UploadsStorageManager.java:368)
	at com.owncloud.android.files.services.FileUploader.retryFailedUploads(FileUploader.java:1005)
	at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:222)
	at com.owncloud.android.utils.-$$Lambda$FilesSyncHelper$fa2LBpPOxRVQOm4F_Glue5u4hdM.run(Unknown Source:10)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: lucye
Model: LGUS997
Id: OPR1.170623.032
Product: lucye_nao_us_nr

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 1825415038997

**Comment by tobiasKaminsky** [comment] 2020-04-22 11:23
Do you know how many files you wanted to upload?

**Comment by Y-Gry** [comment] 2020-04-22 20:28
I added my Whatsapp folder to automatic upload, so is should be at least more than 1000 files

**Comment by tobiasKaminsky** [comment] 2020-04-23 07:45
Duplicate of #5891

**Closed by tobiasKaminsky** 2020-04-23 07:45 UTC
Labels: bug, needs info/discussion
