### ISSUE TITLE
Sync Folder error: upload service needs to be migrated to work manager

### ISSUE THREAD

**Issue by BigBen2003** [nextcloud/android#5679] opened 2020-03-17 20:20 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{7cddbd6 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7080)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gts4lwifi
Model: SM-T830
Id: PPR1.180610.011
Product: gts4lwifixx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: T830XXU4BTB2

**Comment by tobiasKaminsky** [comment] 2020-03-18 06:56
Is this happening all the time or only when you try to sync big folders?
It might me that starting the sync takes too long and thus the exception is thrown.

**Comment by BigBen2003** [comment] 2020-03-18 08:45
Hi there,
the error only occurs with large, extensive synchronizations.

**Comment by tobiasKaminsky** [comment] 2020-03-30 11:43
Ah, thanks for this info.
So the problem is that the upload service is not a work manager job and thus new Android versions complain.

**Comment by tobiasKaminsky** [comment] 2020-11-11 08:37
Duplicate of #6905, as it is the same root cause.

**Closed by tobiasKaminsky** 2020-11-11 08:37 UTC
Labels: approved, bug
