### ISSUE TITLE
App sometimes crashes when browsing menu items (usually Favorites)

### ISSUE THREAD

**Issue by Joe7new** [nextcloud/android#7782] opened 2021-01-05 13:39 UTC
### Steps to reproduce
When browsing the menu on mobile android device I sometimes get a crash. This happens mostly when I  open 'Favoriten' menu item (after 'Fotos' menu item).  Sometimes the **_favorites are shown twice or three times_** and **sometimes app crashes**. It looks as if this is a performance problem (but server could not be the problem: i5 6 cores 16 GB RAM,.. for testing with only one user !) and mobile device : Samsung Galaxy A51 (enough storage and performance I believe). wireless connection is fast too (LTE or wlan n standard).

Android version: 10

Device model: Samsung Galaxy A51

Stock or customized system:

Nextcloud app version: latest

Nextcloud server version: latest

#### log output on android device:
************ CAUSE OF ERROR ************
**_java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 5(offset:5).state:7_** 
.....................................................

No suspicious entries in apache log..  
Nexloud.log is really very, very long ..

Desktop clients, Nextcloud in Browser etc. works very well.

**_I wonder why this could happen with such an advanced version of android.._**  Thank you very much for your great work so far, but this should not happen in an advanced version !

regards,Joe

**Comment by Joe7new** [comment] 2021-01-05 17:16
I did a test with wlan (more speed), now the app crashes rarely, **_but favorites are still shown twice or three times_**, then I have to refresh page and then favorites are shown right- but that's really annoying (I had this behaviour nearly since app was developed, but I thought it was due to my old smartphone, but now it's still there with a new one).
Nevertheless not the desired behavior !

regards, Joe

**Comment by Joe7new** [comment] 2021-01-05 19:36
Testing LTE-Speed: Download: 9 MBit/s ; Upload: 5MBit/s - should be enough !?
**_Again error_**- always when openening menu entry point '**Favoriten**' (where are some pictures in it) and opening different menu items before relative quickly. The very most time it happens, when I was opening 'Fotos' menu item before (there are about 20 pictures in it).

************ CAUSE OF ERROR ************
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java: xxx)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java: xxx)
at java.util.concurrent.FutureTask.setException(FutureTask.java: xxx)
......

Is my Handy too slow ?

When no files in 'Favorites' the problem seems to disappear . 

**_What's up with that favorites_** ??

Again: Should not happen at this stage of development!

Joe

**Comment by tobiasKaminsky** [comment] 2021-02-04 14:49
I suspect that searching for favorites is too slow on server. It is not about sever cpu power, but how long search query on your database lasts. This increases with amount of files in your cloud.
If this takes too long, and you navigate away, and then the search results return, it crashes.

Therefore I see two enhancements
- speed up search on server
- better handle returning search results on favorites

**Comment by Joe7new** [comment] 2021-02-05 09:45
Thanks for answering. And, you're thinking about changing that, are you?
with kind regards, Joe

**Comment by ezaquarii** [comment] 2021-02-07 21:31
@Joe7new Could you post full stack trace? Those selected fragments are sadly enough to deduce the chain of actions leading to the crash.

**Comment by Joe7new** [comment] 2021-02-08 00:51
This happens on phone (android 10)
************ CAUSE OF ERROR ************

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 5(offset:5).state:7 com.owncloud.android.ui.EmptyRecyclerView{9325294 VFED..... ......ID 0,0-1080,2181 #7f09021e app:id/list_root}, adapter:com.owncloud.android.ui.adapter.OCFileListAdapter@20e713d, layout:androidx.recyclerview.widget.LinearLayoutManager@8d4fd32, context:com.owncloud.android.ui.activity.FileDisplayActivity@85b5cbd
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6183)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
at android.view.View.layout(View.java:23750)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
at android.view.View.layout(View.java:23750)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
at android.view.View.layout(View.java:23750)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23750)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
at android.view.View.layout(View.java:23750)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1996)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
at android.view.View.layout(View.java:23750)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
at android.view.View.layout(View.java:23750)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23750)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23750)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23750)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23750)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:1099)
at android.view.View.layout(View.java:23750)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3712)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3164)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9126)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
at android.view.Choreographer.doCallbacks(Choreographer.java:797)
at android.view.Choreographer.doFrame(Choreographer.java:732)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8167)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a51
Model: SM-A515F
Id: ................................
Product: ..................

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: ....

This happens when jumping from media-folder to favorites . Very often the files in favorites are shown twice or three times  before crash.. it seems that server is too slow ,but it isn't: CPU is strong  , only one testuser etc. 
And in very most times it happens when jumping from media folder to favorites! 

regards, Joe

**Comment by tobiasKaminsky** [comment] 2021-02-22 14:29
> This happens when jumping from media-folder to favorites . Very often the files in favorites are shown twice or three times before crash.. it seems that server is too slow ,but it isn't: CPU is strong , only one testuser etc.
> And in very most times it happens when jumping from media folder to favorites! Similar error on tablet Samsung Galaxy Tab S6 Lite.

Maybe this is the cause:
- open favorites, seach query is issued
- go to some where else
- search result returns
--> crash

This might be the same reason for media-folder then.

@Joe7new Can you wait for quite a long time before changing view? It then "should" hopefully not crash.

**Comment by Joe7new** [comment] 2021-02-22 17:28
When I wait a few seconds before jumping to next menu item the crash happens less often- but it crashes !
And still favorites are shown twice or three times- so something isn't working properly.
I did make a test just a few minutes ago and I jumped into media folder, waited about 3 seconds and then changed into favorites and nevertheless the crash happens. Although there is a different error output (see below):

************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:399)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: java.util.ConcurrentModificationException
at java.util.ArrayList.sort(ArrayList.java:1472)
at java.util.Collections.sort(Collections.java:206)
at com.owncloud.android.utils.FileSortOrderByName.sortCloudFiles(FileSortOrderByName.java:52)
at com.owncloud.android.ui.adapter.OCFileListAdapter.setData(OCFileListAdapter.java:984)
at com.owncloud.android.ui.fragment.OCFileListFragment$2.doInBackground(OCFileListFragment.java:1564)
at com.owncloud.android.ui.fragment.OCFileListFragment$2.doInBackground(OCFileListFragment.java:1546)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 3 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a51
Model: SM-A515F
Id: ..........
Product: ..........

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: ............

--

It seems that the problem are the favorites, because in the very,very most time the crash happens when jumping to favorites .
(p.s. I wonder that nobody else mentioned that problem, because I had the problem for quite a long time, quite a few versions back!)

But thank you very much for help and for working on it !
regards Joe

**Comment by joshtrichards** [comment] 2023-10-11 21:11
I'm unable to reproduce it myself (though I'm testing against the latest release version v3.26.0 and current reproduction steps are a bit fluid and sketchy).

Is anyone on this thread still experiencing this or able to reproduce it with the current release version these days?

**Comment by joshtrichards** [comment] 2023-10-15 15:32
Fixed in #11804

**Closed by joshtrichards** 2023-10-15 15:32 UTC
Labels: bug, approved, needs info, performance
