### ISSUE TITLE
App Crash When Viewing Details of Photos from Media Tab

### ISSUE THREAD

**Issue by ankur198** [nextcloud/android#14241] opened 2024-12-25 15:42 UTC
### Steps to Reproduce

1. Goto Media tab from sidebar
2. Select any "media"
3. From 3 dots, click on details and it crashes :(

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to read from field 'com.google.android.material.tabs.TabLayout com.owncloud.android.databinding.FileDetailsFragmentBinding.tabLayout' on a null object reference in method 'void com.owncloud.android.ui.fragment.FileDetailFragment.lambda$setupViewPager$0()'
    at com.owncloud.android.ui.fragment.FileDetailFragment.lambda$setupViewPager$0(FileDetailFragment.java:355)
    at com.owncloud.android.ui.fragment.FileDetailFragment.$r8$lambda$Sp-VmtMx2q_HeyzGV0P1GEAXBvw(Unknown Source:0)
    at com.owncloud.android.ui.fragment.FileDetailFragment$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8919)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300690`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a52sxq`
* Model: `SM-A528B`
* Id: `UP1A.231005.007`
* Product: `a52sxqxx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `A528BXXSAGXK1`

**Comment by joshtrichards** [comment] 2024-12-28 15:09
Duplicate of  #13933

**Closed by joshtrichards** 2024-12-28 15:09 UTC
