### ISSUE TITLE
Local picture info cause crash

### ISSUE THREAD

**Issue by MotoVi** [nextcloud/android#14253] opened 2024-12-28 06:05 UTC
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to read from field 'com.google.android.material.tabs.TabLayout com.owncloud.android.databinding.FileDetailsFragmentBinding.tabLayout' on a null object reference in method 'void com.owncloud.android.ui.fragment.FileDetailFragment.lambda$setupViewPager$0()'
    at com.owncloud.android.ui.fragment.FileDetailFragment.lambda$setupViewPager$0(FileDetailFragment.java:355)
    at com.owncloud.android.ui.fragment.FileDetailFragment.$r8$lambda$Sp-VmtMx2q_HeyzGV0P1GEAXBvw(Unknown Source:0)
    at com.owncloud.android.ui.fragment.FileDetailFragment$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:991)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8787)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300690`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `husky`
* Model: `Pixel 8 Pro`
* Id: `AP4A.241205.013`
* Product: `husky`

### Firmware
* SDK: `35`
* Release: `15`
* Incremental: `12621605`

**Comment by joshtrichards** [comment] 2024-12-28 15:09
Duplicate of  #13933

**Closed by joshtrichards** 2024-12-28 15:09 UTC
