### ISSUE TITLE
Cannot set due date while sharing folder - android app

### ISSUE THREAD

**Issue by mkriegl** [nextcloud/android#6628] opened 2020-08-03 13:28 UTC
### Steps to reproduce
1. Share Folder
2. Go to further settings
3. Tap on Due Date
4. Select date in calendar and OK

### Expected behaviour
- Due date is set without error

### Actual behaviour
- I get an error report, that the app has been stopped

### Can you reproduce this problem on https://try.nextcloud.com?
- I could reproduce it on a two Samsung devices. Galaxy S20 and Galaxy Tab S6

### Environment data
Android version: 10

Device model: Samsung Galaxy Tab S6 and S20

Stock or customized system: Stock

Nextcloud app version: 3.13.0 RC1

Nextcloud server version: 18.0.7

Reverse proxy: yes

#### Web server error log
`************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.lib.resources.shares.OCShare.getId()' on a null object reference
	at com.owncloud.android.ui.helpers.FileOperationsHelper.setExpirationDateToPublicShare(FileOperationsHelper.java:648)
	at com.owncloud.android.ui.dialog.ExpirationDatePickerDialogFragment.onDateSet(ExpirationDatePickerDialogFragment.java:181)
	at android.app.DatePickerDialog.onClick(DatePickerDialog.java:173)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:191)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8016)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gts6l
Model: SM-T865
Id: QP1A.190711.020
Product: gts6leea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: T865XXU3BTF2
``
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by splitt3r** [comment] 2020-08-03 18:44
Looks like a dulicate of #6568 😃.

**Comment by AndyScherzinger** [comment] 2020-08-03 18:48
Nice catch @splitt3r and thanks for reporting @mkriegl 

Duplicate of #6568

**Closed by AndyScherzinger** 2020-08-03 18:48 UTC
Labels: bug
