### ISSUE TITLE
crashed after switching

### ISSUE THREAD

**Issue by mischaelschill** [nextcloud/android#13789] opened 2024-10-15 06:10 UTC
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: FragmentManager is already executing transactions
    at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1717)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1776)
    at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:641)
    at com.owncloud.android.ui.activity.FileDisplayActivity.getOCFileListFragmentFromFile(FileDisplayActivity.java:626)
    at com.owncloud.android.ui.activity.FileDisplayActivity.showFile(FileDisplayActivity.java:2484)
    at com.owncloud.android.ui.fragment.UnifiedSearchFragment.showFile(UnifiedSearchFragment.kt:217)
    at com.owncloud.android.ui.fragment.UnifiedSearchFragment.access$showFile(UnifiedSearchFragment.kt:54)
    at com.owncloud.android.ui.fragment.UnifiedSearchFragment$setUpViewModel$6.invoke(UnifiedSearchFragment.kt:198)
    at com.owncloud.android.ui.fragment.UnifiedSearchFragment$setUpViewModel$6.invoke(UnifiedSearchFragment.kt:197)
    at com.owncloud.android.ui.fragment.UnifiedSearchFragment$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
    at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
    at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
    at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:483)
    at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:440)
    at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.jvm.kt:320)
    at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.jvm.kt:257)
    at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.jvm.kt:293)
    at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.jvm.kt:142)
    at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.jvm.kt:124)
    at androidx.fragment.app.Fragment.performStart(Fragment.java:3192)
    at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:628)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:290)
    at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
    at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
    at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2959)
    at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:274)
    at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:358)
    at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
    at com.owncloud.android.ui.activity.DrawerActivity.onStart(DrawerActivity.java:1203)
    at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:239)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2266)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1582)
    at android.app.Activity.performStart(Activity.java:9034)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4206)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2693)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:9063)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `q2q`
* Model: `SM-F926B`
* Id: `UP1A.231005.007`
* Product: `q2qxxx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `F926BXXU8IXH9`

**Comment by joshtrichards** [comment] 2024-10-15 13:30
Duplicate of #13107

**Closed by joshtrichards** 2024-10-15 13:30 UTC
Labels: bug, performance: ISE/IAE :confused:, stable-3.29
