### ISSUE TITLE
Blinking Thumbnails when refreshing

### ISSUE THREAD

**Issue by ldmpub** [nextcloud/android#734] opened 2017-03-11 15:55 UTC
Hi,

I'm running nightly since 2 weeks (with regular updates), currently I run version : 20170308.

I have noticed, in folders containing images, that refresh leads the thumbnails to blink wether I'm online or offline because the default image icon (with montains) is shortly displayed ... look at the attached zip screen video:
[ScreenRecord - Blinking Thumbnails.zip](https://github.com/nextcloud/android/files/835908/ScreenRecord.-.Blinking.Thumbnails.zip)

**Comment by elpraga** [comment] 2017-03-17 00:37
I can confirm the same issue. More so, if the app encounters a new thumbnail, __all thumbnails__ disappear. The thumbnails are obviously still there, but I just end up browsing a folder without any thumbnails. 

Then they appear for a little bit, and disappear again...

**Comment by AndyScherzinger** [comment] 2017-03-17 15:00
pinging @mario @tobiasKaminsky since you both work on preview view or thumbnail related topics :)

**Comment by ldmpub** [comment] 2017-04-30 11:14
Tested on dev version 20170427 ... thumbnails are not blinking anymore.
Does some change have been done? Can we definitively close this issue?

**Comment by tobiasKaminsky** [comment] 2017-05-02 07:32
I have built the dev app from scratch, so I guess there were just some merge problems.
I close it for now; please feel free to open up any new problem. 
This is valuable input as parts of the dev version will be included in the next version.

**Closed by tobiasKaminsky** 2017-05-02 07:32 UTC
Labels: dev version

**Comment by elpraga** [comment] 2017-05-02 23:09
@tobiasKaminsky I had to roll back to an old version of Nextcloud nightly client because of this blinking thubmails and https://github.com/nextcloud/android/issues/596 (I could basically see no thumbnails in neither of the apps, and I it wos unworkable for me), but if this issue is fixed, I could get back on track and help to report bugs again.

I just cannot find where the nightly builds are here on github. Can you please send me a link where to find them to install the current nighly?

Thanks a lot!

**Comment by elpraga** [comment] 2017-05-02 23:20
I found it now! It is at: https://download.nextcloud.com/android/nightly/ 

Thanks anyways @tobiasKaminsky

**Comment by elpraga** [comment] 2017-05-02 23:34
I am confused... It this link the correct one for the nightly? It did download correctly and upgraded over Nextcloud Nightly app, but the app doesn't show the photo previews (like the old beta and nightly did) and the pinch zoom doesn't work.

Do I have the correct link @tobiasKaminsky ?

P.S.
I am sorry to bother you so many times..

**Comment by tobiasKaminsky** [comment] 2017-05-03 11:02
This is correct.
Both will be soon available again in dev version. I had to rebuilt it and thus had no time to integrate it.

**Comment by elpraga** [comment] 2017-05-03 11:35
Ok. Thanks for the reply! I'm looking forward to see those features again!
