### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by get2him** [nextcloud/android#5348] opened 2020-01-29 06:45 UTC
### Steps to reproduce
1. Phone was in flight mode/energy safe mode during night
2. Disabled themin the morning. It connected to the Wi-Fi and mobile network 
3. Nextcloud crash just popped up.  

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data
Android version:
10 (Havoc 3.0)
Device model: 
Oneplus 6
Stock or customized system:
Yes 👍
Nextcloud app version:
3.10.0
Nextcloud server version:
17.0.2
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.AnalyticsConnector
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6
Model: ONEPLUS A6003
Id: QQ1B.191205.011
Product: OnePlus6

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: eng.havoc.20191223.154159

Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-01-31 07:27
Duplicate of #4675

**Closed by AndyScherzinger** 2020-01-31 07:27 UTC
Labels: bug
