### ISSUE TITLE
Repeated crashes (dev version)

### ISSUE THREAD

**Issue by c-torre** [nextcloud/android#8067] opened 2021-02-26 08:34 UTC
### Steps to reproduce
1. Install "Nextcoud Dev" from F-Droid (version 20210220)

### Expected behaviour
- The app continues to work in general.

### Actual behaviour
- App keeps crashing and restarting. It's not possible to use the device since it keeps switching to the new Nextcloud instance after every crash.
- Slowly making your way to settings to force stop the app does not work: keeps crashing and relaunching.

At the end I uninstalled the Dev version and installed the regular version from F-Droid (3.15.0), which works as expected.

### Can you reproduce this problem on https://try.nextcloud.com?

This URL on Android only shows the Nextcloud white logo on a blue background. Tapping the logo takes you to nextcloud.com

### Environment data
Android version: 7.1.2

Device model: LG-h870

Stock or customized system: LineageOS

Nextcloud app version: 20210220

### Logs
I won't be able to get logs or replicate since it renders my device unusable for long until uninstalled. Hope it still helps.

**Comment by it25fg** [comment] 2021-02-27 15:14
Hi, I'm experiencing the same behaviour: repeated crash with no chance to do something against. My data:

Also using Nextcloud DEV 20210220
Samsung Xcover 3 , SM-389GF
Android 6.0.1

I was able to stop the loop by switching WIFI off. Using Nextcloud on mobile data or even bluetooth works. The error I see in the debug screen (managed to do a screenshot, but currently can't transfer, so typing off the image, please excuse any typos):

```
java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "my.host.name": No address associated with hostname
at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:174)
at com.nextcloud.client.network.ConnectivityServiceImpl.IsInternetWalled(ConnectivityServiceImpl.java:75)
at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:207)
at com.owncloud.android.utils.-$$Lambda$FilesSyncHelper$78U1WN_nzr5HiGlrR2MTh3Famz8.run(lambda) ...
```

The host in question IS resolvable (I ssh into it frequently from this phone, so I'd have noticed any problem in hostname resolution). My guess is that the crash happens in the 'automatic upload' code because I have set it to only fire if the phone is connected via WIFI.

In my case, version 20210220 was the first one to exhibit this behaviour. Did an upgrade via bluetooth just an hour ago: 20210224 crashes the same way.

If you suspect a change in Googles framework (don't know about Lineage and the exact inheritance from Google) I would dig into it deeper: there were some framework updates in the last week.

Hope it helps nailing the problem.

I'm not experienced in Android debugging, but if you give precise instruction I could do something via ADB.

**Comment by NotSoImportant** [comment] 2021-02-27 17:17
Same restart loop for me. Device gets completely unusable, even reboot does not help. Only chance is to step by step (between the crashes) go to settings and force kill the app.

Previous bug #7909 was not fixed but instead it worsened so I felt the need to uninstall. 

![Screenshot_20210227-180055](https://user-images.githubusercontent.com/35758921/109394416-31bbaa80-7927-11eb-8f26-455a8f077be5.png)

**Comment by it25fg** [comment] 2021-02-27 22:12
I have read through #7996 but unfortunately I did not manage to get logs via clipboard. How can I get logs then?

**Comment by NotSoImportant** [comment] 2021-02-27 23:17
I just deinstalled and installed again. First was working and I could connect. Turned screen off. After turing screen on again crash-loop started. Disabling wifi stopped it and brought up the error:

************ CAUSE OF ERROR ************

java.lang.UnsupportedOperationException
	at java.util.AbstractList.set(AbstractList.java:132)
	at java.util.AbstractList$ListItr.set(AbstractList.java:426)
	at java.util.Collections.sort(Collections.java:247)
	at com.nextcloud.common.IPV6PreferringDNS.lookup(IPV6PreferringDNS.java:30)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:171)
	at com.nextcloud.client.network.ConnectivityServiceImpl.isInternetWalled(ConnectivityServiceImpl.java:75)
	at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:207)
	at com.owncloud.android.utils.-$$Lambda$FilesSyncHelper$78U1WN_nzr5HiGIrRZMThSEamz8.run(lambda)
	at java.lang.Thread.run(Thread.java:761)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210224
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Motorola
Device: athene_f
Model: Moto G4 Plus
Product: lineage_athene

************ FIRMWARE ************
SDK: 25
Release: 7.x.x

@it25fg in the top left there is a "share" icon. You can e.g. share with email app and copy from there or install "share to clipboard" app (available in f-droid)

**Comment by NotSoImportant** [comment] 2021-02-27 23:25
Another error gotten like this:

************ CAUSE OF ERROR ************

java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "REMOVED": No address associated with hostname
	at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:174)
	at com.nextcloud.client.network.ConnectivityServiceImpl.isInternetWalled(ConnectivityServiceImpl.java:75)
	at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:207)
	at com.owncloud.android.utils.-$$Lambda$FilesSyncHelper$78U1WN_nzr5HiGIrRZMThSEamz8.run(lambda)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.net.UnknownHostException: Unable to resolve host "REMOVED": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:125)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
	at java.net.InetAddress.getAllByName(InetAddress.java:752)
	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
	at com.nextcloud.common.IPV6PreferringDNS.lookup(IPV6PreferringDNS.java:29)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:171)
	... 4 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Posix.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:106)
	... 26 more

************ APP INFORMATION ************

**Comment by NotSoImportant** [comment] 2021-02-27 23:41
>The host in question IS resolvable (I ssh into it frequently from this phone, so I'd have noticed any problem in hostname resolution). 

I can confirm the same for my hostname. It is actually reachable from all others apps / devices. 

>My guess is that the crash happens in the 'automatic upload' code because I have set it to only fire if the phone is connected via WIFI.

I do not assume this as I do not have configured any auto-upload. 

> If you suspect a change in Googles framework (don't know about Lineage and the exact inheritance from Google) I would dig into it deeper: there were some framework updates in the last week.

I am running on Lineage and did not do a framwork update last week. 

Last: I am just a user trying to help by providing logs / how-to-reproduce but not involved in development of / fixing this app.

**Comment by tobiasKaminsky** [comment] 2021-03-01 13:29
Duplicate of #7400

**Closed by tobiasKaminsky** 2021-03-01 13:29 UTC
Labels: bug
