### ISSUE TITLE
mp3

### ISSUE THREAD

**Issue by mamboman777** [nextcloud/android#8995] opened 2021-09-22 11:21 UTC
### Steps to reproduce
1. Play 44.1 256kbps cbr mp3
2. After mp3 completes press back arrow
3. 

### Expected behaviour
- Tell us what should happen
I did be returned to previous menu.

### Actual behaviour
- Tell us what happens
App crashes.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{286bc10 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: bonito
Model: Pixel 3a XL
Id: 
Product: bonito

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 7511028

Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2021-09-22 12:31
Duplicate of #8686

**Closed by AlvaroBrey** 2021-09-22 12:31 UTC
Labels: bug
