### ISSUE TITLE
Stuck in activities menu

### ISSUE THREAD

**Issue by katacore** [nextcloud/android#2720] opened 2018-06-16 23:46 UTC
When I go to activities and want to swype with the drawer to photo, favorites, video, on device, share : nothing happens. If I press all files or notifications, it works.

### Environment data
Android version: 7

Device model: SM-M935F

Stock or customized system: STOCK

Nextcloud app version: 3.2.0

Nextcloud server version: 13

**Comment by tilosp** [comment] 2018-08-29 14:09
Duplicate of #2857

**Closed by tilosp** 2018-08-29 14:09 UTC
Labels: approved, bug
