### ISSUE TITLE
UNABLE TO SELECT REMOTE FOLDER.

### ISSUE THREAD

**Issue by MENOZE** [nextcloud/android#6609] opened 2020-08-01 16:59 UTC
************ CAUSE OF ERROR ************

java.lang.ClassCastException: com.owncloud.android.ui.activity.FolderPickerActivity cannot be cast to com.owncloud.android.ui.activity.FileDisplayActivity
	at com.owncloud.android.ui.fragment.OCFileListFragment.resetHeaderScrollingState(OCFileListFragment.java:1867)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:906)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.lambda$onBindViewHolder$1$OCFileListAdapter(OCFileListAdapter.java:379)
	at com.owncloud.android.ui.adapter.-$$Lambda$OCFileListAdapter$pouWgEOOHT1aDFHaHM0Ifm3xWtY.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7869)
	at android.view.View.performClickInternal(View.java:7838)
	at android.view.View.access$3600(View.java:886)
	at android.view.View$PerformClick.run(View.java:29362)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8125)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: starqltesq
Model: SM-G960U
Id: QP1A.190711.020
Product: starqltesq

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G960USQU7ETG3

**Comment by AndyScherzinger** [comment] 2020-08-03 18:57
Hi @MENOZE and thank you for the report.

This issue will be fixed via #6632 and ship with 3.13.0 RC3

Duplicate of #6616

**Closed by AndyScherzinger** 2020-08-03 18:57 UTC
Labels: bug

**Comment by MENOZE** [comment] 2020-08-03 19:02
Thanks. Looking into it.

**Comment by AndyScherzinger** [comment] 2020-08-03 19:07
> Looking into it.

RC3 hasn't been released (yet) ;)
