### ISSUE TITLE
NoClassDefFoundError: AnalyticsConnector

### ISSUE THREAD

**Issue by leenen** [nextcloud/android#4675] opened 2019-10-13 11:03 UTC
### Actual behaviour
- normal execution of app

### Expected behaviour
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source)
	at com.google.firebase.iid.zzc.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/data/app/com.nextcloud.client-1/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-1/lib/arm64, /vendor/lib64, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 8 more
	Suppressed: java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.AnalyticsConnector
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 9 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Huawei
Device: hwALE-H
Model: ALE-L21
Id: HuaweiALE-L21
Product: ALE-L21

************ FIRMWARE ************
SDK: 21
Release: 5.0.1
Incremental: C432B20

**Comment by alescdb** [comment] 2019-11-01 14:43
I got this too, multiple times a day for a while now, very annoying, basically every time I unlock my phone.
I seems it happens everytime the phone come out of sleep.

**Comment by AndyScherzinger** [comment] 2019-12-02 07:39
@tobiasKaminsky referenced and closed all duplicates, this seems to happen quite a lot.

**Comment by ananace** [comment] 2020-01-18 10:57
Having this happen to me too, almost the exact same backtrace too with the newest version of the app.

```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-LTiS90daWMmAsD_F7QRCGQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-LTiS90daWMmAsD_F7QRCGQ==/lib/arm64, /data/app/com.nextcloud.client-LTiS90daWMmAsD_F7QRCGQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: asus
Device: ASUS_X00QD
Model: ASUS_X00QD
Id: PPR1.180610.009
Product: WW_X00QD

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 16.0615.1908.109-0
```

Seems to often happen during the night for me, with the error message greeting me many mornings, as well as occasionally sometimes during the day when I unlock my phone.

**Comment by AndyScherzinger** [comment] 2020-01-20 21:18
@tobiasKaminsky can you have a look at this? It keeps getting reported over and over, so fixing might be important ❤️

**Comment by lazyfrosch** [comment] 2020-01-21 14:12
Happens on my Samsung tablet, but not on the Smartphone...

**Comment by Chartman123** [comment] 2020-02-01 08:35
Isn't this the same as #4586??

**Comment by tobiasKaminsky** [comment] 2020-02-03 13:11
To be honest, I have no clue.

We explicitly disable firebase as we do not want to have any tracking in our app:
https://github.com/nextcloud/android/blob/b8d042e1715586ea7a265db24ccb913290f6aaef/build.gradle#L51-L53
https://github.com/nextcloud/android/blob/533debfca04852c29b54a0ba745a2d7311039984/src/gplay/AndroidManifest.xml#L31-L36

Of course Gplay variant of NC app uses push notifications via firebase messaging, but this should all be self contained to work, otherwise a lot more user/devices would cause the trouble.

**Comment by tobiasKaminsky** [comment] 2020-02-03 13:14
![image](https://user-images.githubusercontent.com/5836855/73655939-5f381500-468f-11ea-84e0-079aff461959.png)

Analyzing recent apk also shows that this is in.

How and where did you installed the app?
Do you have some custom rom? Magisk etc?

**Comment by tobiasKaminsky** [comment] 2020-02-03 13:15
I only encountered this problem once, when I had an emulator with no google APIs at all and tried to launch Gplay variant of our app.

**Comment by Chartman123** [comment] 2020-02-03 13:29
> Do you have some custom rom? Magisk etc?

I'm on OmniRom 10 with Open GApps Nano and Magisk. Perhaps some missing Google apps in the nano package?

**Comment by lazyfrosch** [comment] 2020-02-03 13:51
I have this problem on a Samsung Galaxy Tab S4 with stock OS. Installed from Google Play, it does not crash on the Galaxy Smartphone.

**Comment by tobiasKaminsky** [comment] 2020-02-03 14:48
@Chartman123 Yeah, I fear that this is something with gapps / magisk.
"L" is just a wrong debug output.

@lazyfrosch which Android version do you run?

**Comment by lazyfrosch** [comment] 2020-02-03 14:53
@tobiasKaminsky that is an Android 9

**Comment by Chartman123** [comment] 2020-02-03 16:15
I'm not that deep into Android development, but could it also be, that with some SDK version the Firebase Analytics are required to run some of the code Nextcloud is using for the notifications?

I found this in the Firebase docs from Google:

> You no longer need to add the Android library com.google.firebase:firebase-core. This SDK included the Firebase SDK for Google Analytics. Now, to use Analytics (or any of the Firebase products that require or recommend the use of Analytics), you need to explicitly add the Analytics dependency: com.google.firebase:firebase-analytics:17.2.2.

https://firebase.google.com/docs/android/setup#add_firebase_to_your_app

**Comment by lazyfrosch** [comment] 2020-02-04 08:26
Detailed info:

```
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gts4llte
Model: SM-T835
Id: PPR1.180610.011
Product: gts4lltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: T835XXU4BSJ6
```

**Comment by Octav14n** [comment] 2020-02-11 08:31
This happens to me too. I have:
- Google Nexus 6P
- OS: LineageOS (Android 8.1)
- Open-GApps nano
- Magisk

```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/data/app/com.nextcloud.client-XIV3hreoVJQb7KqdFkoWdA==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-XIV3hreoVJQb7KqdFkoWdA==/lib/arm64, /data/app/com.nextcloud.client-XIV3hreoVJQb7KqdFkoWdA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: angler
Model: Nexus 6P
Id: OPM7.181205.001
Product: angler

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: fef9954632
```

**Comment by ximex** [comment] 2020-03-01 10:57
Same here:

```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
 at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
 at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
 at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
 at com.google.firebase.iid.zzg.run(Unknown Source:4)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
 at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-3J5837-wQ6ZBQIaMdCT0-Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-3J5837-wQ6ZBQIaMdCT0-Q==/lib/arm64, /data/app/com.nextcloud.client-3J5837-wQ6ZBQIaMdCT0-Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
 ... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: dreamlte
Model: SM-G950F
Id: PPR1.180610.011
Product: dreamltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G950FXXS6DTA1
```

**Comment by e-alfred** [comment] 2020-03-07 09:12
This error appears regularly on two phones having Lineageos 16 and ResurrectionRemix with MindtheGapps installed, but the Nextcloud client installed from F-Droid.

**Comment by tobiasKaminsky** [comment] 2020-03-09 08:50
> Nextcloud client 3.10.1 installed from F-Droid

If NC app is installed via Fdroid there is no Firebase at all. So it should(tm) not be causing this.

**Comment by mario** [comment] 2020-03-13 17:45
This is a bug in the Firebase libraries. If it doesn't get fixed by Google in the next minor release, I'll do a fix.

**Comment by ezaquarii** [comment] 2020-03-13 17:48
If crashes in proprietary code. How can we fix it?

**Comment by mario** [comment] 2020-03-13 17:50
Proprietary is a very "tricky" thing in the world of JVM :) 

Decompile, try-catch, compile back. Include it in the project.

Done :)

**Comment by ezaquarii** [comment] 2020-03-13 17:56
Maybe we could patch it in our global exception handler?

**Comment by mario** [comment] 2020-03-13 18:16
I guess you could try catching NoClassDefFoundError?

**Comment by mario** [comment] 2020-03-13 18:16
(where's the global exception handler btw?)

**Comment by ezaquarii** [comment] 2020-03-13 22:23
Crash handler. Check MainApp.java:246. I don't know if it can handle exceptions coming from firebase code, but we can try.

**Comment by AndyScherzinger** [comment] 2020-03-16 08:40
looping in @tobiasKaminsky since this keeps getting reported over and over again 😞

**Comment by cornercase** [comment] 2020-03-17 15:32
I can now reliably trigger this issue on my devices.  If I edit a calendar event in a shared calendar, the other calendar user's app will crash.  I'm not sure if this is at all helpful, but I'm happy to provide additional details if so.

**Comment by tobiasKaminsky** [comment] 2020-03-22 07:19
In Talk it seems to be fixed with bump to latest FCM version.
We will try the same :-)

**Comment by mario** [comment] 2020-03-22 07:39
I hope it was fixed at least since I don't have the issue myself :p

**Comment by leenen** [comment] 2020-03-22 10:32
No one seems to be able to solve this problem.

**Comment by mario** [comment] 2020-03-22 10:40
@leenen please do not close this issue. Like I/we wrote above, either google fixes it or we workaround it.

**Comment by Chartman123** [comment] 2020-03-26 18:22
Should this be fixed in latest Play Store beta release? 3.11

My app still crashes with the same error.

**Comment by AndyScherzinger** [comment] 2020-03-26 21:39
Hi Chartman, 

personally I am not 100% sure if the latest beta release did ship the fix but the final release of 3.11 should have (published some hours ago).

So does 3.11.0 still crash with this error?
also looping in @tobiasKaminsky who did the fix.

**Comment by Chartman123** [comment] 2020-03-26 22:05
My version number in the app info dialog says 3.11.0, so I think it should be the stable release.

**Comment by tobiasKaminsky** [comment] 2020-03-27 05:51
We updated to latest FCM, but it still seems to happen…
@mario sadly it does not help, it seems :/

**Comment by Chartman123** [comment] 2020-03-28 20:08
I uninstalled and re-installed the app and it seems to kind of work at the moment... I don't get the push notification at the moment, but the app doesn't crash when I interact with the notifications within the app.

**Comment by Chartman123** [comment] 2020-03-29 12:33
Strange thing: The app crashes only on notifications from two of my Nextcloud instances. From the third one everything works fine, even after a force close of the app. So it might not only be app related...

**Comment by e-alfred** [comment] 2020-03-29 15:14
The problem persists in 3.11, but strangely it doesn't happen on all clients.

**Comment by tobiasKaminsky** [comment] 2020-03-30 05:01
@Chartman123 can I get an account from the crashing one?
Can you create us a test account and send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by Chartman123** [comment] 2020-03-30 06:14
@tobiasKaminsky I've created an account for you on one of the crashing servers.

**Comment by Chartman123** [comment] 2020-04-02 07:38
@tobiasKaminsky Did you receive the invitation mail?

**Comment by cornercase** [comment] 2020-04-02 16:09
I'm also happy to establish test accounts on my instance.  I can do both LDAP and non-LDAP logins and am happy to make configuration changes to help test if that would be helpful.

**Comment by tylerstyle** [comment] 2020-04-06 17:34
Happens to me, too. 
Just happens at random on notification prompts or shortly thereafter.


---------------------
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-27VxS6aQ91yFJk_114JNPg==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-27VxS6aQ91yFJk_114JNPg==/lib/arm64, /data/app/com.nextcloud.client-27VxS6aQ91yFJk_114JNPg==/base.apk!/lib/arm64-v8a, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5T
Model: ONEPLUS A5010
Id: PKQ1.180716.001
Product: OnePlus5T

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 2002242012

**Comment by Chartman123** [comment] 2020-04-07 10:37
@tobiasKaminsky At the moment, without changing anything but recreating the connections in the app, all my servers work fine. I'll post an update, if this changes again.

**Comment by e-alfred** [comment] 2020-04-14 09:53
I can reproduce it if I get a notification from Nextcloud Talk. The Nextcloud client immediately crashes with the NoClassDefFoundError getting shown.

**Comment by ThePatzen** [comment] 2020-05-25 08:03
I can reproduce this too. If i get any notification (like 	Two-Factor Authentication via Nextcloud notification) this kills my app.

**Comment by minils** [comment] 2020-06-08 06:07
Any update on this? I think a lot of people experience this problem. Many issues were opened already.
Furthermore, it is a quite annoying bug because the app suddenly crashes in a lot of different situations.

**Comment by tobiasKaminsky** [comment] 2020-06-08 07:09
No real clue…unfortunately.
I do not have any device (out ouf 10 test devices) that is suffering from this.
So it is really hard to reproduce.
Furthermore it seems more to be a bug from firebase.

**Comment by tobiasKaminsky** [comment] 2020-06-15 13:57
I tested a bit.
When I switched app version / fcm version I could once reproduce this crash.

I created now a new version, signed with official NC key, which can be installed as an update to existing 3.12. version: https://cloud.nextcloud.com/s/5LqAMD7bp2N6a89

Can some of you please give it a try?
If this still crashes, please remove the app and reinstall it.

Thanks for helping!

**Comment by tobiasKaminsky** [comment] 2020-06-17 08:40
Any feedback? :-)

**Comment by minils** [comment] 2020-06-17 08:53
With the current Play Store Version (3.12.0) it does not happen to me any more.
I must admit, that I uninstalled, intalled the F-Droid Version and cleared all the settings in between.

**Comment by Chartman123** [comment] 2020-06-17 09:41
I didn't have any problems since my last post 👍

**Comment by keresztg** [comment] 2020-06-17 10:44
I can reliably reproduce the bug by sending a message with the following command:
`sudo -u www-data php occ notification:generate user testmessage`
The exception will occur either immediately upon receiving the push or after trying to delete the message in the Nextcloud app's Notifications menu.
And this happens both on my old Huawei P9 (Android 7) and on the new P30 Lite (Android 10).

Unfortunately the exception occurs also with the test app by @tobiasKaminsky.
Clearing the cache did not help. Now I will uninstall the app, reinstall the original 3.12.0 from Play Store and come back with the results.

**Comment by keresztg** [comment] 2020-06-17 11:22
After uninstall, reinstall the stock 3.12.0 and logging in with QR code, the exception reoccurred after trying to delete the message in the Nextcloud app's Notifications menu.
Crash log attached.
[Nextcloud crashed2.txt](https://github.com/nextcloud/android/files/4792083/Nextcloud.crashed2.txt)

Could this be caused by server side? I always had problems with push messages, receiving them quite irregularly...

**Comment by keresztg** [comment] 2020-06-17 11:32
Okay, so uninstalled again, reinstalled @tobiasKaminsky's version, logged in with QR code.
And now the exception _does not occur_ after trying to delete the message in the Nextcloud app's Notifications menu. So that seems to be fixed, at least on this phone.

Still the push is not received, but I guess that's a whole different problem...

**Comment by e-alfred** [comment] 2020-06-17 12:06
It seems like the problem is gone with Nextcloud 19 and the Android client 3.12.0 final. But as @keresztg said, notifications sometimes don't show up altogether which is another problem that might be connected to this one (?).

**Comment by keresztg** [comment] 2020-06-17 18:52
In the end some of the push messages came through and the exception did not reoccur. So that part seems to be fixed also. At least for me.

**Comment by tobiasKaminsky** [comment] 2020-06-18 04:46
@keresztg thanks for testing.

Can anyone else confirm the fix? I do not want to use it by only one vote…🙈

**Comment by cornercase** [comment] 2020-06-18 22:51
I tested on my wife's phone briefly and the crash seems to be gone.  I had to uninstall and reinstall to get it working, simply updating didn't fix the problem.  It also has not shown the notifications unless I actually open the nextcloud app, which is odd.  I'll do more testing this evening and get back to you.  FWIW, I recreated my account on my device weeks ago and the problem went away without an upgrade.

**Comment by DrekiDegga** [comment] 2020-08-04 00:54
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-AB0yY_gNZ-P3uHm8tDJPNA==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-AB0yY_gNZ-P3uHm8tDJPNA==/lib/arm64, /data/app/com.nextcloud.client-AB0yY_gNZ-P3uHm8tDJPNA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: G8142
Model: G8142
Id: 47.2.A.10.107
Product: G8142

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 172320177

**Comment by tobiasKaminsky** [comment] 2020-08-05 06:02
> Happens to me usually when I get a nextcloud talk message.

But Files Client is crashing?
Can you install Talk app and see if it then still happens? (the puss message should then go directly to Talk app)

**Comment by e-alfred** [comment] 2020-08-05 14:04
I can confirm that the app crashes if a Nextcloud Talk message is received.

**Comment by DrekiDegga** [comment] 2020-08-17 20:29
I removed the play store version and installed the f-droid version. I no longer get the crash because I no longer get anynotifications.  So perhaps a partial work around for now. At least it doesn't crash any more.

Apparently in order to do android notifications nextcloud requires proprietary components from Google which aren't included in the fdroid version. 

Is that the only way to do notifications in an android app? I think I've used other apps from fdroid that had  notifications.

**Comment by tobiasKaminsky** [comment] 2020-08-19 09:46
> > Happens to me usually when I get a nextcloud talk message.
> 
> But Files Client is crashing?
> Can you install Talk app and see if it then still happens? (the puss message should then go directly to Talk app)

@DrekiDegga can you please try and install Nextcloud Talk and see if this also crashes when receiving a message?

**Comment by tobiasKaminsky** [comment] 2020-08-26 08:59
@all that have the same problem and that have their device not set to english:
Can you try if this still happens if the device language is set to English?

(ref: https://github.com/nextcloud/android/issues/6776#issuecomment-679923458)

**Comment by tobiasKaminsky** [comment] 2020-08-28 09:02
After updating LineageOS on my private device, I suddenly also got those crashes, without having changed anything on NC app.
So I tried to install a debug version to get more infos on this crash.
But as soon as I re-installed the app, I could never triggered the crash again :/

Can one or two test if re-installing the app might help?

**Comment by tobiasKaminsky** [comment] 2020-09-29 10:15
@all can you please try https://cloud.nextcloud.com/s/mJ34deny3LicrgA
You can install this as an "upgrade" to your existing Nextcloud app.

This should prevent crashes.

"Downside" is that it included a bit more Firebase, but all is disabled:
https://github.com/nextcloud/android/blob/master/src/gplay/AndroidManifest.xml#L31-L36

According to https://firebase.google.com/docs/analytics/configure-data-collection?platform=android#temporarily_disable_collection_1

However Exodus will still show it as available tracker, as it is technically still part of our code.

**Comment by EricThi** [comment] 2020-09-29 12:04
@tobiasKaminsky : Nice work, i have upgrade my app and test with generate notification : don't crash :)

For me, it's based on firebase blocked on my dns (pihole) and my dns is set on my os (e.foundation) for wifi and 4g

For get notification, I have trust minimal request via microG (on os /e/ directly).

For next release, need to "upgrade" manually or next build can be upgrade via traditional channel ? (aurora store for me)

**Comment by b52** [comment] 2020-09-29 12:30
I second that. After simply reinstalling the app, the crashes do not appear anymore. Instead, push messages are successfully. shown.

**Comment by JensKuehnel** [comment] 2020-09-30 18:55
I second that also. After update from tobiasKaminsky yesterday. No problems any more with crashes and now I see messages as well, like app updates available.

**Comment by tobiasKaminsky** [comment] 2020-10-02 06:50
Thanks for testing.
Then let us get this in :+1:

**Closed** 2020-10-02 08:22 UTC
Labels: approved, bug, high, pr exists

**Comment by tmaex** [comment] 2020-12-20 09:55
Still an issue with the F-Droid dev version of the app: 20201216

```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lokio/Buffer;
 at okhttp3.ResponseBody.create(ResponseBody.java:210)
 at okhttp3.internal.Util.<clinit>(Util.java:62)
 at okhttp3.Credentials.basic(Credentials.java:30)
 at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
 at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:330)
 at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:304)
 at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:276)
 at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
 at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
 at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.ClassNotFoundException: okio.Buffer
 ... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201216
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWVOG
Model: VOG-L29
Id: HUAWEIVOG-L29
Product: VOG-L29EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.1.0.150C431
```

**Comment by Chartman123** [comment] 2020-12-20 10:18
As far as I can see, this is unrelated to this issue... The stack trace doesn't mention the AnalyticsConnector
