### ISSUE TITLE
Crash on login to local server with self-signed ssl certificate

### ISSUE THREAD

**Issue by kkaess** [nextcloud/android#10871] opened 2022-10-20 20:51 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Attempt to login to a local server with self-signed certificate.

### Expected behaviour

Successful login.

### Actual behaviour

Error message: 
### Cause of error
```java
Exception in thread "main" com.nextcloud.client.di.InjectorNotFoundException: Injector not registered for com.owncloud.android.ui.dialog.SslUntrustedCertDialog. Have you added it to com.nextcloud.client.di.ComponentsModule?
    at com.nextcloud.client.di.FragmentInjector.onFragmentPreAttached(FragmentInjector.java:43)
    at androidx.fragment.app.FragmentLifecycleCallbacksDispatcher.dispatchOnFragmentPreAttached(FragmentLifecycleCallbacksDispatcher.java:100)
    at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:463)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7880)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
Caused by: Exception in thread "main" java.lang.IllegalArgumentException: No injector factory bound for Class<com.owncloud.android.ui.dialog.SslUntrustedCertDialog>
    at dagger.android.DispatchingAndroidInjector.inject(DispatchingAndroidInjector.java:136)
    at dagger.android.support.AndroidSupportInjection.inject(AndroidSupportInjection.java:75)
    at dagger.android.support.AndroidSupportInjection.inject(AndroidSupportInjection.java:67)
    at com.nextcloud.client.di.FragmentInjector.onFragmentPreAttached(FragmentInjector.java:40)
    at androidx.fragment.app.FragmentLifecycleCallbacksDispatcher.dispatchOnFragmentPreAttached(FragmentLifecycleCallbacksDispatcher.java:100)
    at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:463)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7880)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220090`
* Build flavor: `gplay`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `00WW_3_31A`

### Android version

12

### Device brand and model

Nokia 5.4

### Stock or custom OS?

Stock

### Nextcloud android app version

30220090

### Nextcloud server version

24.0.6

### Using a reverse proxy?

I don't know

### Additional information

I don't have developer options enabled on my phone, so don't think I can access log files.

**Comment by AlvaroBrey** [comment] 2022-10-21 07:42
Duplicate of #10827 , update your app

**Closed by AlvaroBrey** 2022-10-21 07:42 UTC
Labels: bug

**Comment by meldra** [comment] 2022-10-21 19:40
In the past hour I installed, from both f-droid and play store, the app. I just updated nextcloud on my server. This still happens.

**Comment by andrei-inc** [comment] 2022-10-22 13:04
I'm encountering a similar problem.

In the last ~5 days, i couldn't use the android app to access my nextcloud server. (everything works in the browser)

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.LinearLayout com.owncloud.android.databinding.SslUntrustedCertLayoutBinding.getRoot()' on a null object reference
    at com.owncloud.android.ui.dialog.SslUntrustedCertDialog.onCreateDialog(SslUntrustedCertDialog.java:173)
    at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665)
    at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579)
    at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1752)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:245)
    at android.app.ActivityThread.main(ActivityThread.java:8024)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220190`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `Nord`
* Model: `AC2003`
* Id: `RP1A.201005.001`
* Product: `Nord_EEA`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `2205252126`
