### ISSUE TITLE
Progress when uploading multiple files

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/android#6865] opened 2020-08-31 19:44 UTC
### Is your feature request related to a problem? Please describe.
uploading a bunch of files (photos/videos from vacation.) is a usual thing to do using the android app. when doing so, the upload notification should reflect on global progress of the process. Current solution doesnt inform the user on how many files are left to upload.

### Describe the solution you'd like
A simple text clue will do. For instance: _24/50_ or _3 files left_ etc. Place in the notification area.

**Comment by tobiasKaminsky** [comment] 2020-09-01 06:01
Duplicate of #6008, also by you ;-)

**Closed by tobiasKaminsky** 2020-09-01 06:01 UTC
Labels: enhancement
