### ISSUE TITLE
Crashing app while posting comments 

### ISSUE THREAD

**Issue by cvarad96** [nextcloud/android#12663] opened 2024-03-09 07:45 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Open app
Go to a random file (for example pdf)
Before load of file is complete if you post a comment the app is crashing

### Expected behaviour

Keep in load state
Or 
Don't allow comments

###  Cause of error
```java
Exception in thread "AsyncTask #2" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:415)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
    at java.util.concurrent.FutureTask.run(FutureTask.java:269)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)
Caused by: Exception in thread "AsyncTask #2" java.lang.IllegalArgumentException: Trying to execute a remote operation with a NULL OwnCloudClient
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:201)
    at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment$SubmitCommentTask.doInBackground(FileDetailActivitiesFragment.java:489)
    at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment$SubmitCommentTask.doInBackground(FileDetailActivitiesFragment.java:468)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30280090`
* Build flavor: `gplay`

### Device information
* Brand: `POCO`
* Device: `munch`
* Model: `22021211RI`
* Id: `TKQ1.220807.001`
* Product: `munch_in`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `V
![Screenshot_2024-03-09-13-13-03-953_com nextcloud client](https://github.com/nextcloud/android/assets/24322090/ce7b388f-0ee2-4b5c-a5c1-46878915b245)
![Screenshot_2024-03-09-13-13-01-671_com nextcloud client](https://github.com/nextcloud/android/assets/24322090/12e3fcdf-db54-465f-a2c6-b22bdd1561b5)
14.0.8.0.TLMINXM`

### Android version

13

### Device brand and model

Xiaomi poco f4

### Stock or custom OS?

Stock

### Nextcloud android app version

V3.2.8

### Nextcloud server version

25.3

### Using a reverse proxy?

Yes

**Comment by joshtrichards** [comment] 2024-03-10 20:21
Duplicate of #12353

**Closed** 2024-03-10 20:21 UTC
Labels: bug
