### ISSUE TITLE
crash switching accounts

### ISSUE THREAD

**Issue by neelusR** [nextcloud/android#14220] opened 2024-12-22 09:32 UTC
I was uploading photos from my android phone gallery to the nextcloud app. I wanted to switch accounts, i selected the correct account, but it did bot switch. I have seen this before. Subsequently i accidentally went down a folder and it mentioned the folder did not exist. I tried to cancel and it crashed

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.canWrite()' on a null object reference
    at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onCreateOptionsMenu(ReceiveExternalFilesActivity.java:1047)
    at android.app.Activity.onCreatePanelMenu(Activity.java:4119)
    at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.kt:470)
    at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3413)
    at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
    at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
    at android.view.Choreographer.doCallbacks(Choreographer.java:797)
    at android.view.Choreographer.doFrame(Choreographer.java:728)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:8167)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300690`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `starlte`
* Model: `SM-G960F`
* Id: `QP1A.190711.020`
* Product: `starltexx`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `G960FXXUHFVG4`

**Comment by joshtrichards** [comment] 2024-12-28 15:11
Duplicate of #13348

**Closed by joshtrichards** 2024-12-28 15:11 UTC
Labels: bug, 0. Needs triage, feature: authentication, performance: NPE :no_entry_sign:, stable-3.30
