### ISSUE TITLE
Frequent Crashes on Nokia 7.2

### ISSUE THREAD

**Issue by jeyk** [nextcloud/android#5356] opened 2020-01-30 19:57 UTC
### Steps to reproduce
1. I don't know what causes it. The app simply crashes sporadically.
2. I am pretty sure it only happens when the screen is off.

### Expected behaviour
- No crashes

### Actual behaviour
- Full screen crash notification appears
- Stack trace:
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-sFUCr3tcpzZGIGXhx9vFIA==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-sFUCr3tcpzZGIGXhx9vFIA==/lib/arm64, /data/app/com.nextcloud.client-sFUCr3tcpzZGIGXhx9vFIA==/base.apk!/lib/arm64-v8a, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Nokia
Device: DDV_sprout
Model: Nokia 7.2
Id: PKQ1.190118.001
Product: Daredevil_00EEA

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 00WW_1_400

**Comment by AndyScherzinger** [comment] 2020-01-31 07:27
Duplicate of #4675

**Closed by AndyScherzinger** 2020-01-31 07:27 UTC
Labels: bug
