### ISSUE TITLE
I can't start app, screen is locked

### ISSUE THREAD

**Issue by guettli** [nextcloud/android#8595] opened 2021-06-17 15:58 UTC
### Steps to reproduce
1. I start the app
2. I see the error message. See text below
3. I can't use the app. The error message can't be skipped

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:784)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWANE
Model: ANE-LX1
Id: HUAWEIANE-L21
Product: ANE-LX1

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.368C432

**Comment by tobiasKaminsky** [comment] 2021-06-21 07:28
Duplicate of #8730

**Closed by tobiasKaminsky** 2021-06-21 07:28 UTC
Labels: bug
