### ISSUE TITLE
Nextcloud crashes in the background

### ISSUE THREAD

**Issue by Sergeij2000** [nextcloud/android#6499] opened 2020-07-21 04:53 UTC
### Steps to reproduce
process crashes sporadically w/o interaction

### Can you reproduce this problem on https://try.nextcloud.com?
no

### Environment data
Android version: see nextcloud log

Device model: Lenovo Chromebook C340-11

Nextcloud app version: see Nextcloud log

Nextcloud server version: 19.0.1

Reverse proxy: no

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-z1MW4tZZUHyfe83VHzCbYg==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-z1MW4tZZUHyfe83VHzCbYg==/lib/x86_64, /data/app/com.nextcloud.client-z1MW4tZZUHyfe83VHzCbYg==/base.apk!/lib/x86_64, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: octopus_cheets
Model: octopus
Id: R83-13020.87.0
Product: octopus

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 6612792

**Comment by tobiasKaminsky** [comment] 2020-07-21 05:09
Duplicate of #6269

**Closed by tobiasKaminsky** 2020-07-21 05:09 UTC
Labels: bug
