### ISSUE TITLE
Nextcloud Android App can't connect, crashes afterwards

### ISSUE THREAD

**Issue by ezrajensen** [nextcloud/android#8920] opened 2021-08-31 19:51 UTC
### Steps to reproduce
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to pause activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@689038e
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4580)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4531)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4480)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:228)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.andr
![Screenshot_2021-08-31-22-49-05-417_com nextcloud client](https://user-images.githubusercontent.com/89780012/131566912-654d5bff-9f63-4bde-b66c-e476b3c568ef.jpg)
oid.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@689038e
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1433)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1553)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:674)
	at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.onInactive(UsbConnectionDispatcher.java:131)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.ensureStateInactive(SecurityKeyManager.java:316)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.refreshActiveState(SecurityKeyManager.java:290)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.onActivityPaused(SecurityKeyManager.java:333)
	at android.app.Application.dispatchActivityPaused(Application.java:491)
	at android.app.Activity.dispatchActivityPaused(Activity.java:1332)
	at android.app.Activity.onPause(Activity.java:2272)
	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:388)
	at com.owncloud.android.ui.activity.BaseActivity.onPause(BaseActivity.java:84)
	at com.owncloud.android.ui.activity.FileActivity.onPause(FileActivity.java:253)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onPause(FileDisplayActivity.java:1254)
	at android.app.Activity.performPause(Activity.java:8096)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1508)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4570)
	... 13 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: joyeuse
Model: Redmi Note 9 Pro
Id: QKQ1.191215.002
Product: joyeuse_global

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.3.0.QJZMIXM
![Screenshot_2021-08-31-22-49-05-417_com nextcloud client](https://user-images.githubusercontent.com/89780012/131566818-c404285e-673f-4b01-9759-3f9efdadea84.jpg)
![Screenshot_2021-08-31-22-49-05-417_com nextcloud client](https://user-images.githubusercontent.com/89780012/131566846-c0f023ce-d93f-4514-bcdb-685b651f96ac.jpg)

2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to pause activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@689038e
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4580)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4531)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4480)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:228)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@689038e
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1433)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1553)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:674)
	at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.onInactive(UsbConnectionDispatcher.java:131)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.ensureStateInactive(SecurityKeyManager.java:316)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.refreshActiveState(SecurityKeyManager.java:290)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.onActivityPaused(SecurityKeyManager.java:333)
	at android.app.Application.dispatchActivityPaused(Application.java:491)
	at android.app.Activity.dispatchActivityPaused(Activity.java:1332)
	at android.app.Activity.onPause(Activity.java:2272)
	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:388)
	at com.owncloud.android.ui.activity.BaseActivity.onPause(BaseActivity.java:84)
	at com.owncloud.android.ui.activity.FileActivity.onPause(FileActivity.java:253)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onPause(FileDisplayActivity.java:1254)
	at android.app.Activity.performPause(Activity.java:8096)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1508)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4570)
	... 13 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: joyeuse
Model: Redmi Note 9 Pro
Id: QKQ1.191215.002
Product: joyeuse_global

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.3.0.QJZMIXM

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2021-09-02 13:28
Duplicate of https://github.com/nextcloud/android/issues/8585

**Closed by AlvaroBrey** 2021-09-02 13:28 UTC
Labels: bug
