### ISSUE TITLE
Nextcloup app crash

### ISSUE THREAD

**Issue by sub26nico** [nextcloud/android#13829] opened 2024-10-20 12:23 UTC
### Cause of error
```java
Exception in thread "main" android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{1f2fd22 u0 com.nextcloud.client/androidx.work.impl.foreground.SystemForegroundService}
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
    at android.os.Handler.dispatchMessage(Handler.java:112)
    at android.os.Looper.loop(Looper.java:216)
    at android.app.ActivityThread.main(ActivityThread.java:7625)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300190`
* Build flavor: `generic`

### Device information
* Brand: `HUAWEI`
* Device: `HWMRD-M1`
* Model: `MRD-LX1`
* Id: `HUAWEIMRD-LX1`
* Product: `MRD-L21AEEA`

### Firmware
* SDK: `28`
* Release: `9`
* Incremental: `9.1.0.327C431`

**Comment by joshtrichards** [comment] 2024-10-20 13:00
Duplicate of #13798

**Closed by joshtrichards** 2024-10-20 13:00 UTC
