### ISSUE TITLE
Googleplay has version 3.29.2 but latest release is 3.30.5

### ISSUE THREAD

**Issue by msviba** [nextcloud/android#14083] opened 2024-11-24 08:42 UTC
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

On Google play is not latest release. There is 3.29.2 from 10. July. But now is ending November.

### Expected behaviour

Googleplay should have more fixed versions.

### Actual behaviour

On Google play is not latest release. There is 3.29.2 from 10. July. But now is ending November.

Has autoupload issue and i can't try newer version 

### Android version

14

### Device brand and model

Xiaomi 14

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.2

### Nextcloud server version

29

### Using a reverse proxy?

No

### Server error logs

```bash

```

**Comment by Olen** [comment] 2024-11-25 07:13
Duplicate of #13871

**Comment by joshtrichards** [comment] 2024-11-26 23:36
Duplicate of #13871

**Closed by joshtrichards** 2024-11-26 23:36 UTC
Labels: bug, 0. Needs triage
