### ISSUE TITLE
Auto Sync it's so bad

### ISSUE THREAD

**Issue by Tom60chat** [nextcloud/android#9615] opened 2021-12-23 14:52 UTC
### Steps to reproduce
1. Sync a wrong destination folder
2. Change the destination folder to sync
3. NextCloud still sync the wrong destination folder event if you restart the sync or the app.
4. Have enough and reset the app.
5. Crash.

### Expected behaviour
- First that changing sync would sync on the new folder.
- For the real issue: That the app reset (and maybe stop the sync).

### Actual behaviour
- I click the reset data button while sync in background.

### Can you reproduce this problem on https://try.nextcloud.com?
Yes, I can.

### Environment data
Android version: 11

Device model: Redmi Note 8T

Stock or customized system: MIUI (Customized by brand ?)

Nextcloud app version: 30180190

Nextcloud server version: 23.0.0

Reverse proxy: wat ? (No DNS, no proxy)

#### Nextcloud log (data/nextcloud.log)
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032 SQLITE_READONLY_DBMOVED)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:890)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1806)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1752)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:669)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:642)
	at android.content.ContentProvider.update(ContentProvider.java:1830)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:457)
	at android.content.ContentResolver.update(ContentResolver.java:2384)
	at android.content.ContentResolver.update(ContentResolver.java:2346)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUpload(UploadsStorageManager.java:131)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadInternal(UploadsStorageManager.java:173)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadStatus(UploadsStorageManager.java:208)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateDatabaseUploadResult(UploadsStorageManager.java:579)
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:659)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1415)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.os.HandlerThread.run(HandlerThread.java:67)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: willow
Model: Redmi Note 8T ---
Id: RKQ1.201004.002
Product: willow_eea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: V12.0.2.0.RCXEUXM

**Comment by AlvaroBrey** [comment] 2022-01-26 08:41
Duplicate of #8985

**Closed by AlvaroBrey** 2022-01-26 08:41 UTC
Labels: bug
