### ISSUE TITLE
Calendar/Contact sync can't be set up on Unihertz Titan Pocket

### ISSUE THREAD

**Issue by ieure** [nextcloud/android#9540] opened 2021-12-13 05:53 UTC
### Steps to reproduce
1. Install DAVx5 from F-Droid.
2. From a logged-in Nextcloud app, tap the hamburger menu at the upper-left.
3. Tap Settings.
4. Tap "Sync calendar & contacts."

### Expected behaviour
- I should go through the DAVx5 account setup flow, be asked to log in, etc.

### Actual behaviour
- I get prompted to "Open with Google Play Store" (or can choose F-Droid).
- The authorization / setup flow never starts, so I can't sync my contacts or calendars.

The same flow works fine on a Pixel 3a running CalyxOS, and has worked on other phones in the past, so I assume this is something the weirdphone being weird.  But, I'd still really like if it worked, since it's my daily driver.

### Can you reproduce this problem on https://try.nextcloud.com?
- I'm not able to add the account to my Nextcloud app, but it's not a server issue.

### Environment data
Android version: 11

Device model: Unihertz Titan Pocket

Stock or customized system: Stock

Nextcloud app version: 3.18.0

Nextcloud server version: 22.2.3

Reverse proxy: Nginx

### Logs

n/a

**Comment by AlvaroBrey** [comment] 2021-12-13 11:59
Duplicate of #9339

**Comment by AlvaroBrey** [comment] 2021-12-13 11:59
Will be fixed in 3.18.1

**Closed by AlvaroBrey** 2021-12-13 11:59 UTC
Labels: bug
