### ISSUE TITLE
(Auto sync) App crashes when trying to create a folder for auto upload

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#5454] opened 2020-02-11 17:28 UTC
Hi,

When you want to automatically synchronize your files in "Auto upload", and specify you want to create a folder instead of using default "remote folder", it opens an "explorer instance" in which you can create or choose a folder.

If you try to create a folder, the app crashes and indicates this error :

```
2020-02-11 18:27:43.753 19347-19347/com.nextcloud.client E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nextcloud.client, PID: 19347
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
        at com.owncloud.android.ui.dialog.CreateFolderDialogFragment.onClick(CreateFolderDialogFragment.java:140)
        at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
``` 

So, you can't create a folder in which auto-sync your pictures

**Comment by AndyScherzinger** [comment] 2020-02-11 21:53
Duplicate of #4792

**Comment by AndyScherzinger** [comment] 2020-02-11 21:55
You are very welcome to work on this while I'll close this issue in favor of #4792 (which already references a wide selection of duplicate reports :disappointed:)

**Closed by AndyScherzinger** 2020-02-11 21:55 UTC
Labels: bug
