### ISSUE TITLE
"Server not available" since latest Android App Update

### ISSUE THREAD

**Issue by nerzlakai96** [nextcloud/android#10182] opened 2022-05-06 09:46 UTC
### Steps to reproduce
1. Just open the latest version of Nextcloud Android App

### Expected behaviour
Nextcloud Android App should show me all my files as usual after startup.

### Actual behaviour
A gray message pops up just below the search bar with a text like "Server not available".

### Can you reproduce this problem
I am very sure that this issue is related to Usernames being "Forename Surname". Last year 2021 in october the Nextcloud Android App had exact the same issue which was fixes a week after in another Android App Update.

### Environment data
Android version: 11

Device model: Samsung Galaxy A70

Stock or customized system: Stock

Nextcloud app version: Latest Version 3.20.0

Nextcloud server version: 23.0.2

Thanks in advance and kind regards.

**Comment by AlvaroBrey** [comment] 2022-05-06 09:50
Duplicate of #10170

**Closed by AlvaroBrey** 2022-05-06 09:50 UTC
Labels: bug
