### ISSUE TITLE
Crash application

### ISSUE THREAD

**Issue by mszuyev** [nextcloud/android#4877] opened 2019-11-22 21:27 UTC
### Actual behaviour
- The application crashed while running in a background. 

### Expected behaviour
- It should not have any issues with connection to Firebase (due to log data) and should work as usual
 
### Steps to reproduce
I don't know exact reason of this crash, but it probably was
0. Install Android app, just use it, nothing special
1. Install Ubuntu desktop client, log in onto it, synchronize your files
2. Unlock your phone (the app just ran in a background, it was NOT opened)
3. See this error 

### Logs

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-nG9XDiE0GYrZMU00edbFWQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-nG9XDiE0GYrZMU00edbFWQ==/lib/arm64, /data/app/com.nextcloud.client-nG9XDiE0GYrZMU00edbFWQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond2q
Model: SM-G9750
Id: PPR1.180610.011
Product: beyond2qltezh

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G9750ZHS2ASJU

#### Nextcloud log (data/nextcloud.log)

```
no nextcloud.log in data and any subfllder of com.nextcloud.client
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2019-12-02 07:35
Duplicate of #4675, so closing in favor

Brand: Huawei
Device: hwALE-H
Model: ALE-L21

**Closed by AndyScherzinger** 2019-12-02 07:35 UTC
Labels: bug
