### ISSUE TITLE
Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#2010] opened 2018-01-19 14:56 UTC
Highest number of reports for ANRs since 2.0.0 in the Dev console - Android 8 only - >5K reports in 60 days

Reason I found google-ing: https://stackoverflow.com/questions/44425584/context-startforegroundservice-did-not-then-call-service-startforeground

> From Google's docs on Android 8.0 behavior changes:
> The system allows apps to call Context.startForegroundService() even while the app is in the background. However, the app must call that service's startForeground() method within five seconds after the service is created.

--> https://developer.android.com/about/versions/oreo/android-8.0-changes.html

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{fb59be8 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6718)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: lge
Device: joan
Model: LG-H932
Id: PQ3A.190605.003
Product: joan_tmo_us

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.markus.20190610.202830

**Comment by paulpv** [comment] 2018-03-21 23:44
https://issuetracker.google.com/issues/76112072

**Comment by dark-chocolate** [comment] 2019-01-02 10:57
@AndyScherzinger Have you guys found some solution for this?

**Comment by AndyScherzinger** [comment] 2019-01-02 15:12
Not that I am aware of

**Comment by tobiasKaminsky** [comment] 2019-10-09 13:41
Re-opening as there are some new reports, and this is the issue with most background infos.

**Comment by tobiasKaminsky** [comment] 2019-10-09 13:46
@all when is this happening?
We use startForegroundService() on
- upload file
- document storage provider
- sync folder
- sync file

**Comment by AndyScherzinger** [comment] 2019-10-30 14:37
```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{9cb193 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HONOR
Device: HWBKL
Model: BKL-L09
Id: HUAWEIBKL-L09S
Product: BKL-L09

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 329C432

```

**Comment by AndyScherzinger** [comment] 2019-10-30 14:38
```
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{a4dde14 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
at android.os.Handler.dispatchMessage(Handler.java:112)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7625)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HONOR
Device: HWBKL
Model: BKL-L09
Id: HUAWEIBKL-L09S
Product: BKL-L09

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 329C432
```

**Comment by AndyScherzinger** [comment] 2019-12-03 15:02
@tobiasKaminsky I added all remaining issues regarding this stack trace and closed them in favor of this one.

**Comment by hao41815w** [comment] 2019-12-15 09:24
So how did you fix this issue?
Can you help me?
This is my code, but it has this issue when the app is running.

~~~~~~
@Override
    public void onCreate() {
        Log.i(TAG, "service create");
        startForeground(NOTIFICATION_ID, createNotification(this));
         ....
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
            ContextCompat.startForegroundService(this, new Intent(this, HideNotificationService.class));
        }
}

**Comment by AndyScherzinger** [comment] 2019-12-20 07:30
@tobiasKaminsky I added all new issues regarding this stack trace and closed them in favor of this one. Als marked it as `high` since we keep getting reports for it. Your list of areas https://github.com/nextcloud/android/issues/2010#issuecomment-540008236 seems complete for the moment.

**Comment by rcdailey** [comment] 2020-01-09 17:39
I don't think we need a notification per file downloaded either. Just overall progress.

**Comment by IgorGanapolsky** [comment] 2020-06-03 21:10
The solution to this issue is to call `startForeground` in the **onCreate()** method

**Comment by tobiasKaminsky** [comment] 2020-06-04 10:11
https://github.com/nextcloud/android/blob/dd1a192650113bf1238bb674710971e7d2cd5f27/src/main/java/com/owncloud/android/files/services/FileUploader.java#L927-L931

We are explicitly using startForegroundService here.
Doc says:
>Similar to startService(Intent), but with an implicit promise that the Service will call startForeground(int, android.app.Notification) once it begins running. The service is given an amount of time comparable to the ANR interval to do this, otherwise the system will automatically stop the service and declare the app ANR.
Unlike the ordinary startService(Intent), this method can be used at any time, regardless of whether the app hosting the service is in a foreground state.

So it "just" seems that time between starting FileUploader via startForegroundService and the real
https://github.com/nextcloud/android/blob/dd1a192650113bf1238bb674710971e7d2cd5f27/src/main/java/com/owncloud/android/files/services/FileUploader.java#L282

is too long.
But onStartCommand seems to be started directly after startForegroundService(…), at least for me.


@IgorGanapolsky onCreate is used only once on app start, as far as I can see.

**Comment by InfamousUser** [comment] 2020-07-12 15:52
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d94dde5 u0 com.nextcloud.client/com.owncloud.android.files.services.FileUploader}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by InfamousUser** [comment] 2020-07-24 08:14
Still happening on 3.13 RC1, app unusable for months due to an abundance of bugs, crashes and ANRs.

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{895d5b4 u0 com.nextcloud.client/com.owncloud.android.files.services.FileUploader}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by InfamousUser** [comment] 2020-09-15 02:50
Any news on this?

**Comment by tobiasKaminsky** [comment] 2020-09-15 06:04
Do you know when exactly this is happening?
We have this foreground service in many places

**Comment by InfamousUser** [comment] 2020-09-15 11:28
Well I can tell you about one time it happens consistently. If I open up uploads menu, it almost always crashes, but the report dialogue with the error only appears maybe every 5th - 10th time. It lags and freezes and then just crashes. I presume it's the same error.

**Comment by tobiasKaminsky** [comment] 2020-09-16 08:42
> uploads menu

Do you mean the view where you can see all outstanding/failed uploads?

**Comment by InfamousUser** [comment] 2020-09-16 13:16
Yes. A single place in the universe where I can go when I want to guarantee a crash!

**Comment by tobiasKaminsky** [comment] 2020-09-17 15:01
> So it "just" seems that time between starting FileUploader via startForegroundService and the real
> 
> https://github.com/nextcloud/android/blob/dd1a192650113bf1238bb674710971e7d2cd5f27/src/main/java/com/owncloud/android/files/services/FileUploader.java#L282

I tried to trigger this and added 30s delay in onStartCommand(…).
On Android 10 I "only" get a "app not responding", but no crash.

@InfamousUser which device do you use? Maybe I can reproduce it there…

**Comment by InfamousUser** [comment] 2020-09-17 16:43
Google Pixel 2. I do get a lot of ANRs and ~app stopped~ in the background when it is uploading. I plug the charger in (which triggers autoupload) and it pops up every so often. I think it slowed down on the last RC1 release or penultimate release, I had the app force stopped for several months because it was unusable so I wasn't paying so much attention anymore. If you need any more details I'm happy to help get this resolved for me and everyone who might be having the same issue.

**Comment by tobiasKaminsky** [comment] 2020-09-18 08:38
Can you see how many pending uploads you have?
While it can happen that the app does not respond (ANR) it should not kill using rest of your device.
Can you reboot, make sure that none other apps are open and see if this somehow performs better?

**Comment by InfamousUser** [comment] 2020-09-19 14:42
There's about 120, there's always around that number, it goes through them one by one. If I keep the uploads menu open, it goes towards zero slowly, it's very slow, I never actually waited more than until maybe 70. But when I'm not on that tab/I'm in the background, it queues the uploads up to around 110-120 queued. Sometimes if I don't touch anything, it keeps showing that screen and slowly uploading (approx. 0.1 item/s), if I try to scroll, it lags/freezes and eventually crashes/doesn't respond.

I tried the following: close all the apps from the recent or overview or whateverItsCalled list, reboot, wait until it fully powers up and starts, then wait 2 mins to make sure it has stabilized, still nothing in recent apps list. I then open Nextcloud, go to uploads, it now "waits to exit power saving mode", I plug the charger in and it  goes out of power saving mode and starts uploading -> Nextcloud immediately crashes to begin with. Then I open up Nextcloud and go to uploads menu, it freezes again, whole OS doesn't respond to input, power button will work and fingerprint sensor works to turn off and on the phone, but the touchscreen interface is frozen, after about 20 seconds it unlocks and I get to use my phone again.

Amusingly it says that Nextcloud has stopped/keeps stopping but I cannot interact with the dialogue box to close it because Nextcloud is keeping the phone from being used for half a minute until it's ready to be used again.

**Comment by InfamousUser** [comment] 2020-11-14 01:54
Still happening on 3.14 RC2. Just opened the app to find one file.

**Comment by tobiasKaminsky** [comment] 2020-11-17 11:09
There is an APK file in PR #7340, which you can install in parallel to your existing Nextcloud app.
It would be great if you can verify the fix.

**Comment by willpyshan13** [comment] 2020-11-19 17:38
when i remove a file it will be appear

in version stable-3.14.0

**Closed** 2020-11-20 20:27 UTC
Labels: approved, bug, help wanted, high, pr exists

**Comment by InfamousUser** [comment] 2020-11-20 20:36
Finally this is getting fixed! Good job everyone!

**Comment by AndyScherzinger** [comment] 2020-11-20 20:50
@InfamousUser to be sure please try the QA build in #7340 if you can spare some time 🙏

**Comment by InfamousUser** [comment] 2020-11-21 03:17
> @InfamousUser to be sure please try the QA build in #7340 if you can spare some time 🙏

Yeah, sure. I updated over the previous QA version and it seems to behave the same as described in this comment:
https://github.com/nextcloud/android/pull/7340#issuecomment-729687183.
and here
https://github.com/nextcloud/android/issues/7378#issuecomment-731207375

In essence, the original problem seems fixed, only receiving ANRs all the time now.

**Comment by InfamousUser** [comment] 2021-01-12 03:18
I'm afraid to say it's still happening on 3.14.2 RC1 for FileUploader.

**Comment by InfamousUser** [comment] 2021-01-13 15:31
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{933be3d u0 com.nextcloud.client/com.owncloud.android.files.services.FileUploader}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by InfamousUser** [comment] 2021-02-01 02:17
Still happening on 3.15.0 RC1.
