### ISSUE TITLE
Too slow app and facing error

### ISSUE THREAD

**Issue by mitexleo** [nextcloud/android#13659] opened 2024-10-01 00:58 UTC
### Cause of error
```java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
    at java.util.ArrayList.set(ArrayList.java:455)
    at com.owncloud.android.ui.fragment.OCFileListFragment.updateOCFile(OCFileListFragment.java:1388)
    at com.owncloud.android.ui.activity.FileActivity.onCreateShareViaLinkOperationFinish(FileActivity.java:807)
    at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:393)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1629)
    at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:786)
    at com.owncloud.android.services.OperationsService$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.ActivityThread.main(ActivityThread.java:8633)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `m40`
* Model: `SM-M405F`
* Id: `RP1A.200720.012`
* Product: `m40dd`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `M405FDDU2CXE1`

**Comment by joshtrichards** [comment] 2024-10-01 14:06
Duplicate of #13014

**Closed by joshtrichards** 2024-10-01 14:06 UTC
