### ISSUE TITLE
3.18.0 RC5: search crashing

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#9254] opened 2021-11-12 09:41 UTC
tried different searches, get almost every time this crash:

************ CAUSE OF ERROR ************

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:641)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	... 1 more
Caused by: com.nextcloud.client.network.ClientFactory$CreationException: com.owncloud.android.lib.common.accounts.AccountUtils$AccountNotFoundException: Error receiving password token
	at com.nextcloud.client.network.ClientFactoryImpl.createNextcloudClient(ClientFactoryImpl.java:64)
	at com.owncloud.android.ui.unifiedsearch.UnifiedSearchRemoteRepository.fetchProviders(UnifiedSearchRemoteRepository.kt:108)
	at com.owncloud.android.ui.unifiedsearch.UnifiedSearchRemoteRepository.queryAll(UnifiedSearchRemoteRepository.kt:45)
	at com.owncloud.android.ui.unifiedsearch.UnifiedSearchViewModel.initialQuery(UnifiedSearchViewModel.kt:124)
	at com.owncloud.android.ui.fragment.UnifiedSearchFragment.onCreate(UnifiedSearchFragment.kt:91)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	... 3 more
Caused by: com.owncloud.android.lib.common.accounts.AccountUtils$AccountNotFoundException: Error receiving password token
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:218)
	at com.nextcloud.client.network.ClientFactoryImpl.createNextcloudClient(ClientFactoryImpl.java:62)
	... 18 more
Caused by: java.lang.IllegalStateException: calling this from your main thread can lead to deadlock
	at android.accounts.AccountManager.ensureNotOnMainThread(AccountManager.java:2181)
	at android.accounts.AccountManager.access$500(AccountManager.java:164)
	at android.accounts.AccountManager$AmsTask.internalGetResult(AccountManager.java:2287)
	at android.accounts.AccountManager$AmsTask.getResult(AccountManager.java:2325)
	at android.accounts.AccountManager$AmsTask.getResult(AccountManager.java:2240)
	at android.accounts.AccountManager.blockingGetAuthToken(AccountManager.java:1529)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:211)
	... 19 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180055
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7T
Model: HD1903
Id: RKQ1.201022.002
Product: OnePlus7T_EEA

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2108182246

**Comment by AlvaroBrey** [comment] 2021-11-12 10:10
Duplicate of https://github.com/nextcloud/android/issues/9244

**Closed by AlvaroBrey** 2021-11-12 10:10 UTC
Labels: bug
