### ISSUE TITLE
Feature request: Slider to browse quickly through folder.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#538] opened 2017-01-13 23:37 UTC
### Actual behaviour
-Tell us what happens
This is a feature request to add a slider on the side on the side of the display to be able to scroll through document quiclky.
Currently, sweeping the finger downward on the display seem to be the only solution to scroll down documents under the active folder.
There is on the right side of the display a small slider, which is just to display relative position within the folder. There is no way to interact with it.
So, when a folder contains hundreds or thousands of photos, it requires many, many sweep to reach the intended files.

### Expected behaviour
-Tell us what should happen
A slider, should be added on the side of the display to be able to scroll up or down the slider in a single motion.

**Comment by tobiasKaminsky** [comment] 2017-02-10 16:09
Seems to be a duplicate of #47 
Please confirm @OlivierS1 and then close.

**Comment by OlivierS1** [comment] 2017-02-10 20:41
@tobiasKaminsky #47 seems to be a better implementation of my idea, but would it work well with folder containing photos which all start with DSC_NNNN or 2017_NNNN (Talking about the alphabetical indexing )?
The fruit example in the link http://androidopentutorials.com/android-listview-fastscroll/ doesn't have the same requirements as having photo folders where thousands of files use the same prefix denomination.

**Comment by tobiasKaminsky** [comment] 2017-02-11 13:34
This will be very difficult in all implementations, or?
Image you have DSC_0001-DSC_1000 and IMG_201701xx...It would be very hard to guess the right prefix and strip this off.
If you have such inconsistent names I would sort the folder by date and then the fast scroll should show the dates.

**Comment by AndyScherzinger** [comment] 2017-02-12 19:55
Imho having just a simple fast scroll for starters would improve the UI.

**Comment by tobiasKaminsky** [comment] 2017-06-27 14:38
Closing this in favor of #47, with the limitation of too many same starting file names.

**Closed by tobiasKaminsky** 2017-06-27 14:38 UTC
Labels: enhancement
