### ISSUE TITLE
error when switching to media view

### ISSUE THREAD

**Issue by yajo** [nextcloud/android#10176] opened 2022-05-05 14:26 UTC
### Cause of error
```java
Exception in thread "AsyncTask #8" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:415)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:923)
Caused by: Exception in thread "AsyncTask #8" java.lang.NullPointerException: Attempt to invoke interface method 'com.owncloud.android.datamodel.FileDataStorageManager com.owncloud.android.ui.fragment.FileFragment$ContainerActivity.getStorageManager()' on a null object reference
    at com.owncloud.android.ui.fragment.GalleryFragment.showAllGalleryItems(GalleryFragment.java:273)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.doInBackground(GallerySearchTask.java:103)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.doInBackground(GallerySearchTask.java:46)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:923)

```

1. Open media view.
2. before thumbnails are loaded, open one picture 
3. before it is loaded, gp back 

### App information
* ID: `com.nextcloud.client`
* Version: `30200090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `gts4lvwifi`
* Model: `SM-T720`
* Id: `RP1A.200720.012`
* Product: `gts4lvwifieea`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `T720XXU2DVC3`

**Comment by AlvaroBrey** [comment] 2022-05-05 14:35
Duplicate of #10169 but I'll keep this one since it has more info

**Comment by AlvaroBrey** [comment] 2022-05-05 14:36
cc @tobiasKaminsky

**Closed as completed** 2022-05-06 11:47 UTC
Labels: bug, pr exists
