### ISSUE TITLE
Crash after pressing back on login screen

### ISSUE THREAD

**Issue by jotoho** [nextcloud/android#8797] opened 2021-08-01 11:59 UTC
### Steps to reproduce
1. Somehow get forcefully logged out (I suspect this happened because my home networks dynamic IPv4 address changed and my DynDNS script hadn't kicked in yet.)
2. Get presented with login screen
3. Press back button to return to file list
4. Wait a few seconds for crash to happen (loading circle was showing)

### Expected behaviour
- App should never crash

### Actual behaviour
- App crashed after I tapped back on login screen and upon opening the app again hours later

### Environment data
Android version: 9

Device model: Huawei P Smart

Stock or customized system: Standard OS that came with device

Nextcloud app version: 3.17.0 RC1 (f-droid)

Nextcloud server version: Nextcloud 22 deployed via docker; Running on https://nextcloud.jotoho.de

Docker image hash: `sha256:38b05bd65d88aa0a01532e2eeb7fb8d40ac145044bf3a53c4222e2941f43088b`

Reverse proxy: Yes, Caddy.

#### Web server error log
```
(Unavailable right now. Writing this from my phone after being asked by app to report the crash. If necessary, I can probably fill this in later.)
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:7)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updateUserProfile(RefreshFolderOperation.java:285)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:231)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:363)
	at java.lang.Thread.run(Thread.java:784)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170051
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWFIG-H
Model: FIG-LX1
Id: HUAWEIFIG-L31
Product: FIG-LX1

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.216C432
```

**Comment by AndyScherzinger** [comment] 2021-08-11 21:37
Duplicate of #8370

**Closed by AndyScherzinger** 2021-08-11 21:37 UTC
Labels: bug
