### ISSUE TITLE
Android mobil app

### ISSUE THREAD

**Issue by eteete** [nextcloud/android#5093] opened 2020-01-05 06:04 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{ec3f073 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond1
Model: SM-G973F
Id: QP1A.190711.020
Product: beyond1ltexx

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G973FXXU3BSKO

**Comment by AndyScherzinger** [comment] 2020-01-09 17:29
duplicate of #2010

**Closed by AndyScherzinger** 2020-01-09 17:29 UTC
Labels: bug
