### ISSUE TITLE
android.app.RemoteServiceException: Context.startForegroundService() did not then call 

### ISSUE THREAD

**Issue by bapjg** [nextcloud/android#4634] opened 2019-10-09 08:43 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{1d139ca u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HONOR
Device: HWBKL
Model: BKL-L09
Id: HUAWEIBKL-L09S
Product: BKL-L09

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 329C432

### Actual behaviour
- got error message : Nextcloud crashed

### Expected behaviour
None in particular
 
### Steps to reproduce
Just happened

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2019-10-09 13:43
Duplicate of #2010

**Closed by tobiasKaminsky** 2019-10-09 13:43 UTC
Labels: bug

**Comment by hao41815w** [comment] 2019-12-13 20:44
How can I fix this issue?

**Comment by hao41815w** [comment] 2019-12-13 20:45
"Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{86e437c u0 com.nccloud.client/com.owncloud.android.utils.tracking.TrackingService}
android.app.ActivityThread$H.handleMessage"?

**Comment by bapjg** [comment] 2019-12-13 21:23
I’ve no idea. The app broke and autaically sent on the bug report.
Hasn’t reoccurred since

Cordialement

André Davis
andre@bapjg.com
Dom :             +33 4 7928 5014
GSM :             +33 6 8290 7233

De : Haoming <notifications@github.com>
Envoyé : vendredi 13 décembre 2019 21:45
À : nextcloud/android <android@noreply.github.com>
Cc : Andre Davis <Andre.Davis@Bapjg.com>; Author <author@noreply.github.com>
Objet : Re: [nextcloud/android] android.app.RemoteServiceException: Context.startForegroundService() did not then call (#4634)


How can I fix this issue?
