### ISSUE TITLE
Instant crash when switching to "raster mode"

### ISSUE THREAD

**Issue by Frank1967** [nextcloud/android#2471] opened 2018-04-15 16:07 UTC
### Actual behaviour
When you switch to "raster view" in a folder with photos, the app instantly crashes.
Restarting the app and revisiting the same folder keeps crashing the app.
However, visiting other folders still  "list view" is still possible, so it seems the raster setting is a per folder setting.

### Expected behaviour
It does not crash and displays the photos as it should.
 
### Steps to reproduce
1. Go to a folder with photos in it
2. Select "rasterindeling" (this is Dutch, i do not know the exact wording in English) from the options menu (3 dots on the right top of the screen)
3. "Nextcloud is stopped" appears and you can submit a report

### Environment data
Android version: 6.0.1

Device model:  samsung s5

Stock or customized system: stock

Nextcloud app version: 3.0.1

Nextcloud server version: 13

#### Web server error log
Nothing at the time of error

#### Nextcloud log (data/nextcloud.log)
Nothing at the time of error

**Comment by ardevd** [comment] 2018-04-15 16:30
I'm assuming you're referring to the grid view? I'm not able to replicate this issue. 

Please provide a stack trace (using adb logcat) of the crash in order for us to investigate the issue further.

**Comment by Frank1967** [comment] 2018-04-15 16:35
Hi,

"Raster view" was a loose translation of the Dutch word, likely it is 
called grid view in English :-)
I can reliable reproduce the bug, so I'm glad to help.
Unfortunately, a don't know how to make a stack trace.
Where can I find the instruction how to do this?
Thanks for your help.

Kind regards,

Frank

Op 15-4-2018 om 18:30 schreef ardevd:

**Comment by Frank1967** [comment] 2018-04-15 18:29
It took me a while to figure out how debugging works, but I think this 
is what you require.
Hope it helps....

Regards,

Frank

04-15 20:21:00.014  5127  5127 E AndroidRuntime: FATAL EXCEPTION: main

04-15 20:21:00.014  5127  5127 E AndroidRuntime: Process: 
com.nextcloud.client, PID: 5127

04-15 20:21:00.014  5127  5127 E AndroidRuntime: 
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.support.v7.widget.GridLayoutManager.calculateItemBorders(GridLayoutManager.java:324)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.support.v7.widget.GridLayoutManager.calculateItemBorders(GridLayoutManager.java:309)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.support.v7.widget.GridLayoutManager.updateMeasurements(GridLayoutManager.java:280)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.support.v7.widget.GridLayoutManager.onAnchorReady(GridLayoutManager.java:355)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:575)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.View.layout(View.java:17938)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.ViewGroup.layout(ViewGroup.java:5814)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:610)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.View.layout(View.java:17938)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.ViewGroup.layout(ViewGroup.java:5814)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1166)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:851)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.View.layout(View.java:17938)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.ViewGroup.layout(ViewGroup.java:5814)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.View.layout(View.java:17938)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.ViewGroup.layout(ViewGroup.java:5814)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.FrameLayout.onLayout(FrameLayout.java:281)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.View.layout(View.java:17938)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.ViewGroup.layout(ViewGroup.java:5814)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1731)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.LinearLayout.onLayout(LinearLayout.java:1496)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.View.layout(View.java:17938)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.ViewGroup.layout(ViewGroup.java:5814)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.LinearLayout.onLayout(LinearLayout.java:1494)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.View.layout(View.java:17938)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.ViewGroup.layout(ViewGroup.java:5814)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.View.layout(View.java:17938)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.ViewGroup.layout(ViewGroup.java:5814)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.FrameLayout.onLayout(FrameLayout.java:281)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.View.layout(View.java:17938)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.ViewGroup.layout(ViewGroup.java:5814)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.FrameLayout.onLayout(FrameLayout.java:281)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.View.layout(View.java:17938)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.ViewGroup.layout(ViewGroup.java:5814)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.FrameLayout.onLayout(FrameLayout.java:281)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.View.layout(View.java:17938)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.ViewGroup.layout(ViewGroup.java:5814)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.LinearLayout.onLayout(LinearLayout.java:1494)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.View.layout(View.java:17938)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.ViewGroup.layout(ViewGroup.java:5814)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.widget.FrameLayout.onLayout(FrameLayout.java:281)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3193)

04-15 20:21:00.014  5127  5127 E AndroidRuntime:     at 
android.view.View.layout(View.java:17938)

**Comment by ardevd** [comment] 2018-04-16 06:17
This might be a duplicate of #2461.

**Comment by Frank1967** [comment] 2018-04-16 11:38
Indeed, looks the same thing.
I do not mind if you close this issue and track everything in #2461.
I can reliable reproduce this if needed.

Regards,

Frank



Op 16-4-2018 om 8:17 schreef ardevd:

**Comment by AndyScherzinger** [comment] 2018-04-16 12:55
seems like, thus closing in favor of #2461

**Closed by AndyScherzinger** 2018-04-16 12:55 UTC
