### ISSUE TITLE
android.database.sqlite.SQLiteBlobTooBigException

### ISSUE THREAD

**Issue by daking88** [nextcloud/android#9211] opened 2021-11-05 20:09 UTC
### Steps to reproduce
1. Open a folder with many photos within the app 

### Expected behaviour
- content is shown

### Actual behaviour
- error ist thrown:
- 
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=13, totalRows=14
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1003)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:123)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:255)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:287)
	at android.database.CursorWrapper.moveToNext(CursorWrapper.java:206)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:913)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:185)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:815)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1258)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1211)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:961)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.lambda$onBindViewHolder$1$OCFileListAdapter(OCFileListAdapter.java:373)
	at com.owncloud.android.ui.adapter.-$$Lambda$OCFileListAdapter$pRXKS49K02w2aUjenAF837XLVt4.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7441)
	at android.view.View.performClickInternal(View.java:7418)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28676)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: redfin
Model: Pixel 5
Id: SP1A.210812.015
Product: redfin

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: 7679548

### Can you reproduce this problem on https://try.nextcloud.com?
- no, folder not yet tried

### Environment data
Android version: 12

Device model: Pixel 5, see above

Stock or customized system: stock

Nextcloud app version: see above

Nextcloud server version: 20.3.

Reverse proxy: Apache2

#### Web server error log
No errors

#### Nextcloud log (data/nextcloud.log)
No errors

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by daking88** [comment] 2021-11-05 20:12
It is working fine on iPhone. However on all my Android Phones/Tablets it is not working (Android 8/11/12).

**Comment by AlvaroBrey** [comment] 2021-11-08 10:34
Duplicate of #5926

**Closed by AlvaroBrey** 2021-11-08 10:34 UTC
Labels: bug
