### ISSUE TITLE
Bug with qloud

### ISSUE THREAD

**Issue by rullydotcom** [nextcloud/android#9029] opened 2021-09-28 17:01 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Canvas: trying to draw too large(106328180bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:1018)
	at android.widget.ImageView.onDraw(ImageView.java:1436)
	at android.view.View.draw(View.java:21979)
	at android.view.View.updateDisplayListIfDirty(View.java:20856)
	at android.view.View.draw(View.java:21711)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
	at android.view.View.draw(View.java:21982)
	at android.view.View.updateDisplayListIfDirty(View.java:20856)
	at android.view.View.draw(View.java:21711)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
	at android.view.View.updateDisplayListIfDirty(View.java:20847)
	at android.view.View.draw(View.java:21711)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
	at android.view.View.draw(View.java:21982)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
	at android.view.View.updateDisplayListIfDirty(View.java:20856)
	at android.view.View.draw(View.java:21711)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
	at android.view.View.draw(View.java:21982)
	at com.google.android.material.internal.ScrimInsetsFrameLayout.draw(ScrimInsetsFrameLayout.java:109)
	at android.view.View.updateDisplayListIfDirty(View.java:20856)
	at android.view.View.draw(View.java:21711)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
	at android.view.View.draw(View.java:21982)
	at android.view.View.updateDisplayListIfDirty(View.java:20856)
	at android.view.View.draw(View.java:21711)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
	at android.view.View.updateDisplayListIfDirty(View.java:20847)
	at android.view.View.draw(View.java:21711)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
	at android.view.View.updateDisplayListIfDirty(View.java:20847)
	at android.view.View.draw(View.java:21711)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
	at android.view.View.updateDisplayListIfDirty(View.java:20847)
	at android.view.View.draw(View.java:21711)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
	at android.view.View.updateDisplayListIfDirty(View.java:20847)
	at android.view.View.draw(View.java:21711)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
	at android.view.View.draw(View.java:21982)
	at com.android.internal.policy.DecorView.draw(DecorView.java:808)
	at android.view.View.updateDisplayListIfDirty(View.java:20856)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:587)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:664)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3764)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3492)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2776)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1742)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7778)
	at android.view.Choreog
rapher$CallbackRecord.run(Choreographer.java:1041)
	at android.view.Choreographer.doCallbacks(Choreographer.java:864)
	at android.view.Choreographer.doFrame(Choreographer.java:798)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7398)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: vince
Model: Redmi 5 Plus
Id: QQ3A.200905.001
Product: rr_vince

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: eng.xzanxz.20210426.142159

**Comment by AlvaroBrey** [comment] 2021-09-29 07:21
Duplicate of #8862

**Closed by AlvaroBrey** 2021-09-29 07:21 UTC
Labels: bug
