### ISSUE TITLE
two accounts autoupload folder mixes content

### ISSUE THREAD

**Issue by tsr8** [nextcloud/android#11467] opened 2023-03-21 18:50 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. I have two Nextcloud accounts configured on Android app.
2. I have chosen my camera folder to autoupload on the first account.
3. My camera folder has been sybchronized on both!
4. Additionally some content from one account (no autoupload) infiltrate to the second one. This is big safety issue!

### Expected behaviour

Accounts should be separated from each other.

### Actual behaviour

Content mixes, depends on switching between two (or potentially more) accounts.

### Android version

11

### Device brand and model

Xiaomi mi10

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.1

### Nextcloud server version

25.0.4

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment] 2023-03-21 20:26
Hi @tsr8: 

Couple questions to make it easier to either replicate or troubleshoot this issue:

* Are the accounts on distinct NC servers?
* When you select the *second* account profile (the one that you do *not* want getting your camera photos) then go to `Settings` -> `Auto upload` does your Camera folder show the cloud symbol solid (blue) or crossed out (empty)?
* Are all camera photos being uploaded to the second account (the wrong one) or just some of them?
* Are all camera photos being uploaded to the first account (the desired one) properly or are some missing?

**Comment by tsr8** [comment] 2023-03-22 06:10
- One NC server.

- On the first acount the cloud is blue, on the second it stays grey.

- Nearly all photos are uploaded, some missing but after long time its almoast all on two accounts. I think NC client upload photos to the selected account at the moment.

**Comment by joshtrichards** [comment] 2023-03-22 14:02
It certainly shouldn't. And, at least for me, that's not how it behaves.

1. Do you have any auto uploads configured on the second account?
2. Is the destination folder for the auto upload configured for sharing?

**Comment by tsr8** [comment] 2023-03-22 18:24
1. No.
2. No. It synchronizes with desktop app.

**Comment by s0riak** [comment] 2023-04-12 17:40
I experience exactly the same issue. This is a security nightmare!

**Comment by joshtrichards** [comment] 2023-08-20 03:58
Closing in favor of consolidating the tracking of root cause analysis and progress in #11088.

**Closed** 2023-08-20 03:59 UTC
Labels: bug

**Comment by joshtrichards** [comment] 2024-10-27 14:27
Fixed in #12516 (awhile back now; just updating for those not on the other Issue)
