### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Myrsikus** [nextcloud/android#9096] opened 2021-10-14 05:28 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to pause activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@e42c27
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4580)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4531)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4480)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:228)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@e42c27
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1433)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1553)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:674)
	at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.onInactive(UsbConnectionDispatcher.java:131)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.ensureStateInactive(SecurityKeyManager.java:316)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.refreshActiveState(SecurityKeyManager.java:290)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.onActivityPaused(SecurityKeyManager.java:333)
	at android.app.Application.dispatchActivityPaused(Application.java:491)
	at android.app.Activity.dispatchActivityPaused(Activity.java:1332)
	at android.app.Activity.onPause(Activity.java:2272)
	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:388)
	at com.owncloud.android.ui.activity.BaseActivity.onPause(BaseActivity.java:84)
	at com.owncloud.android.ui.activity.FileActivity.onPause(FileActivity.java:253)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onPause(FileDisplayActivity.java:1254)
	at android.app.Activity.performPause(Activity.java:8096)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1508)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4570)
	... 13 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: polaris
Model: Mi MIX 2S
Id: QKQ1.190828.002
Product: polaris_ru

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.2.0.QDGRUXM

**Comment by AlvaroBrey** [comment] 2021-10-14 06:18
Duplicate of #8585

**Closed by AlvaroBrey** 2021-10-14 06:18 UTC
Labels: bug
