### ISSUE TITLE
Error when accepting two factor notification on Android app

### ISSUE THREAD

**Issue by luisgonzalezgonzalez** [nextcloud/android#4820] opened 2019-11-11 19:32 UTC
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.AnalyticsConnector
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: blueline
Model: Pixel 3
Id: QP1A.191005.007
Product: blueline

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 5878874

**Comment by AndyScherzinger** [comment] 2019-12-02 07:35
Duplicate of #4675, so closing in favor

Brand: Huawei
Device: hwALE-H
Model: ALE-L21

**Closed by AndyScherzinger** 2019-12-02 07:35 UTC
Labels: bug
