### ISSUE TITLE
Upload Bug in NC Android V3.14.1

### ISSUE THREAD

**Issue by robertangelov78** [nextcloud/android#7598] opened 2020-12-04 08:53 UTC
Hello,

I am using NC client 3.14.1  on Android 10 and dicovered, that I can't mark and upload any photos from the phone gallery directly into Nexctloud. When I do so, nothing happens.

I have to open the Nexcloud client instead, go to the synced folder and click "+" here and select "Upload content from other app". Then the upload works.

Regards

Steps to reproduce
Open the photo gallery on Android device
Select and mark a picture
Select "Share"
Select nextcloud app
Select folder and confirm "upload"
Expected behaviour
The piture(s) should be uploaded
Actual behaviour
Tell us what happens: Nothing.
Environment data
Android version: 9

Device model: Xiaomi  Mi 9 Lite 

Stock or customized system:

Nextcloud app version: 3.14.1

Nextcloud server version: 14.0.4

Reverse proxy: -

**Comment by dim2on** [comment] 2020-12-04 09:16
Same problem user reported, 
so I take new tablet configured and same problem.
Tablet, Samsung SM-T825 Android 9
NC client 3.14.1 Server 19.0.5

**Comment by joekerna** [comment] 2020-12-04 13:31
I think this is a duplicate of #7589

**Comment by AndyScherzinger** [comment] 2020-12-04 15:06
exactly! Thanks for mentioning @joekerna

**Comment by AndyScherzinger** [comment] 2020-12-04 15:06
Duplicate of #7587

**Closed by AndyScherzinger** 2020-12-04 15:06 UTC
Labels: bug
