### ISSUE TITLE
Add WiFi selection for auto upload

### ISSUE THREAD

**Issue by luckyhandler** [nextcloud/android#3671] opened 2019-02-24 13:23 UTC
It is already possible to only upload images from WiFi instead from the mobile network. It would be great to add a WiFi selection for those who do not expose their nextcloud to another network than their own local one.

**Comment by j-ed** [comment] 2019-02-25 16:46
I think this [**idea**](https://github.com/nextcloud/android/issues/436) has already been rejected.

**Comment by itsmortoncornelius** [comment] 2019-02-26 14:06
Another thing probably worth mentioning but another bug ticket is that even when being connected to the mobile net only nextcloud keeps trying to sync.

**Comment by itsmortoncornelius** [comment] 2019-02-26 14:07
![](https://i.imgur.com/gimDXCN.jpg)

**Comment by AndyScherzinger** [comment] 2019-02-26 16:08
@itsmortoncornelius please open another issue for that and also ping @tobiasKaminsky your screenshots hints to a timeout issue between client and server

**Comment by tobiasKaminsky** [comment] 2019-04-12 06:51
Regarding wifi selection: isn't it enough to mark the network as restricted in Android?

**Comment by LunkSnee** [comment] 2019-04-12 18:55
> Regarding wifi selection: isn't it enough to mark the network as restricted in Android?
If I have 15 wifi networks that I connect to in various locations, you are saying to mark every one of those as restricted just to stop nextcloud from syncing? I don't think that's a reasonable ask.
Right now, I connect to the airport wifi, nextcloud tries to sync, I connect to the airplane wifi, nextcloud tries to sync, etc. 
What you describe would also restrict various other apps from using the wifi. What I think @itsmortoncornelius is asking for is to have the option for auto-upload to only happen at home, for example, on the home wifi. I'm with him - I don't need my phone using battery and background wifi data throughout the day for this purpose. It would be perfect to have the option to only have it happen at home, without restricting every other wifi network.

**Comment by joshtrichards** [comment] 2023-12-22 22:40
A possible workaround in the meantime is suggested here: https://github.com/nextcloud/android/issues/8481#issuecomment-848572646

**Comment by joshtrichards** [comment] 2024-10-15 16:01
Duplicate of #821

**Closed by joshtrichards** 2024-10-15 16:01 UTC
Labels: enhancement, feature: auto upload, connectivity, feature: data usage
