### ISSUE TITLE
Fix actionbar color in image preview on error

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#837] opened 2017-04-17 17:49 UTC
follow up for #607

> One minor thing, could we get the system bar back and make the bars blue in case of "the image can't be displayed"? If it is too much work I'd say we postpone it but open an issue to not forget it.

![device-2017-04-03-233332](https://cloud.githubusercontent.com/assets/1315170/24632847/01292368-18c6-11e7-86c7-c5d03a405f3a.png)

**Comment by tobiasKaminsky** [comment] 2017-05-15 09:50
@AndyScherzinger maybe you can do this? :-D

**Comment by AndyScherzinger** [comment] 2017-05-15 09:54
@tobiasKaminsky maybe, yes. Need to find the time to do so... But I can have a look

**Comment by tobiasKaminsky** [comment] 2017-06-28 07:54
Duplicate of #812

**Closed by tobiasKaminsky** 2017-06-28 07:54 UTC
