### ISSUE TITLE
automatically delete local copies of files which are older than 30 days

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/android#9037] opened 2021-09-29 22:02 UTC
### Is your feature request related to a problem? Please describe.
I want local copies of my recent pictures on my device, so I choose "move to application folder" for automatic upload. But then it fills up my device storage and I have to manually delete local copies regularily.

### Describe the solution you'd like
new setting (_either_ only for automatic upload _or_ for the whole android app): automatically delete local copies of files which are older than 30 days
I think this is a sensible default (see design guidelines of Nextcloud), so it should be enabled by default?!

### Describe alternatives you've considered
-

### Additional context
-

**Comment by kerlue** [comment] 2021-11-06 22:36
I would like to work on this if approved.

**Comment by sanchosk** [comment] 2023-10-08 20:05
I would volunteer to test the feature and buy a coffee for the dev doing this.

**Comment by joshtrichards** [comment] 2023-12-14 20:31
Duplicate of #2323 

I suggest subscribing to that issue to track progress and/or giving it an upvote :+1:

**Closed by joshtrichards** 2023-12-14 20:31 UTC
Labels: enhancement, feature: auto upload
