### ISSUE TITLE
Indicate if connected to server and what the app is currently busy with

### ISSUE THREAD

**Issue by topo03** [nextcloud/android#10351] opened 2022-06-07 07:58 UTC
I'm always frustrated when trying to figure out if my phone is connected to my home server and if my auto upload should work. 

### Describe the solution you'd like
A clear and concise description of what you want to happen:
To me it would be a great help if the app would tell me about its connection status AND current activities (like 'syncing folder xyz', or 'auto uploading new videos from folder DCIM/Camera', or 'connected but idle', or 'connecting to server', etc..). The solution could be a Status Line at the top of the screen. 

### Describe alternatives you've considered:
Syncthing

**Comment by svenb1234** [comment] 2022-06-07 21:47
For me the app shows a notification while it uploads. It does also show "not connected to server". So if the latter is not shown it is connected.

**Comment by topo03** [comment] 2022-06-08 06:16
You are right about the notifications, thanks for pointing this out. They are indeed helpful. 

I looked again but I can't find any message/indication when not connected to the server. Would you be so kind and let me know where to look? I can't find any manual or help page (is there only the forum?).

**Comment by svenb1234** [comment] 2022-06-08 07:41
Found a screenshot in the help forum: https://help.nextcloud.com/uploads/default/original/3X/2/9/295571e21ce5988883c4ad86ac209fd9bb372f22.jpeg

It shows "server not available" at the top.

**Comment by topo03** [comment] 2022-06-09 09:43
This message never appears in my app (3.20.1). Ever after waiting a view minutes for time outs.

**Comment by joshtrichards** [comment] 2023-10-08 03:53
Are you still not seeing this message when your NC Server is offline? It's definitely there and works for me:

https://github.com/search?q=repo%3Anextcloud%2Fandroid+%22host_not_available%22&type=code

Can you try reproducing with a current client version and explain how you're testing?

**Comment by joshtrichards** [comment] 2024-08-13 14:32
Closing per https://github.com/nextcloud/android/issues/10351#issuecomment-1751911436

**Closed by joshtrichards** 2024-08-13 14:32 UTC
Labels: enhancement, needs info, connectivity
