### ISSUE TITLE
Unable to upload .pdf files to NC server via NC App

### ISSUE THREAD

**Issue by OfficialMuffin** [nextcloud/android#10622] opened 2022-08-12 01:20 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Have latest android NC Client App v3.21.0 and NC Server version 24.03
2. Upload any .pdf file using either android file system or from inside android NC client app

### Expected behaviour

To ba able to upload pdf to server with no issues

### Actual behaviour

When uploading .pdf to server using android NC Client app, an error occurred.

`Could not copy file to temporary folder`

### Android version

12

### Device brand and model

Samsung Galaxy Note20

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.0

### Nextcloud server version

24.03

### Using a reverse proxy?

No

### Android logs

Unable to access data folder

### Server error logs

```bash
No warning/error logs present.
```

**Comment by AlvaroBrey** [comment] 2022-08-12 07:03
Does it work with an older version of the app? What about with files in formats other than PDF?

**Comment by OfficialMuffin** [comment] 2022-08-13 11:19
Seems like only image files (jpg, png) and mp4 files can only be uploaded to server. F-droid will not let me downgrade app to older version unfortunately

**Comment by AlvaroBrey** [comment] 2022-08-13 12:10
Then this is a duplicate of #10616, closing

**Closed by AlvaroBrey** 2022-08-13 12:10 UTC
Labels: bug, needs info
