### ISSUE TITLE
Unknown bug

### ISSUE THREAD

**Issue by michael1999crypto** [nextcloud/android#8687] opened 2021-07-11 11:50 UTC
### Steps to reproduce
1. 
2. ************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:7)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updateUserProfile(RefreshFolderOperation.java:285)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:231)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:363)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210707
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Android
Device: blueline
Model: Pixel 3
Id: RQ3A.210705.001
Product: aosp_blueline

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2021.07.07.19

3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ezaquarii** [comment] 2021-07-11 20:28
Looking at the stack trace, it looks like it failed to pull password or username from the account manager.
Since this is asynchronous operation and the stack trace does not show where this operation was scheduled, we don't really know where the `Account` object came from.

@michael1999crypto is it a one off issue or happening regularly?

**Comment by AndyScherzinger** [comment] 2021-07-12 10:50
Duplicate of #8370

**Comment by AndyScherzinger** [comment] 2021-07-12 10:50
@ezaquarii there is an open PR: https://github.com/nextcloud/android-library/pull/638 while I am not an expert on this topic :/

**Closed by AndyScherzinger** 2021-07-12 10:50 UTC
Labels: bug
