### ISSUE TITLE
Using pad Lenevo. After starting NC

### ISSUE THREAD

**Issue by Altau38650** [nextcloud/android#8621] opened 2021-06-24 05:29 UTC
### Steps to reproduce
1. Just after starting NC
2. 
3. 

### Expected behaviour
- message NC stops

### Actual behaviour
- null

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Lenovo
Device: X606F
Model: Lenovo TB-X606F
Id: QP1A.190711.020
Product: LenovoTB-X606F_EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: TB-X606F_USR_S300249_2105081505_V9.56_BMP_ROW

**Comment by AndyScherzinger** [comment] 2021-06-24 08:12
Duplicate of #8370

**Closed by AndyScherzinger** 2021-06-24 08:12 UTC
Labels: bug
