### ISSUE TITLE
crashed 

### ISSUE THREAD

**Issue by Baturax** [nextcloud/android#13478] opened 2024-08-28 00:07 UTC
### Cause of error
```java
Exception in thread "main" android.content.res.Resources$NotFoundException: Resource ID #0x7f0a0402 type #0x12 is not valid
    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2560)
    at android.content.res.Resources.getLayout(Resources.java:1270)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:460)
    at androidx.appcompat.app.AlertController.setupCustomContent(AlertController.java:644)
    at androidx.appcompat.app.AlertController.setupView(AlertController.java:475)
    at androidx.appcompat.app.AlertController.installContent(AlertController.java:233)
    at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:278)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:436)
    at android.app.Dialog.show(Dialog.java:325)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.showPowerCheckDialog(SyncedFoldersActivity.kt:233)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onDisablePowerSaveCheckClicked(SyncedFoldersActivity.kt:217)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onCreateOptionsMenu$lambda$1(SyncedFoldersActivity.kt:210)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.$r8$lambda$q58-_n5tvnvo7t7SwBQVBpaIAdU(Unknown Source:0)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$$ExternalSyntheticLambda4.onMenuItemClick(D8$$SyntheticClass:0)
    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:984)
    at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
    at android.widget.AdapterView.performItemClick(AdapterView.java:330)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1273)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3286)
    at android.widget.AbsListView.onTouchUp(AbsListView.java:4242)
    at android.widget.AbsListView.onTouchEvent(AbsListView.java:4005)
    at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:230)
    at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:138)
    at android.view.View.performOnTouchCallback(View.java:16266)
    at android.view.View.dispatchTouchEvent(View.java:16223)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3119)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2792)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
    at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2569)
    at android.view.View.dispatchPointerEvent(View.java:16548)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7564)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7331)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6723)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6780)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6746)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6912)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6754)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6969)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6727)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6780)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6746)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6754)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6727)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9831)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9782)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9751)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9973)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:295)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:349)
    at android.os.Looper.loopOnce(Looper.java:189)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8594)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20240825`
* Build flavor: `versionDev`

### Device information
* Brand: `Xiaomi`
* Device: `ginkgo`
* Model: `Redmi Note 8`
* Id: `AP2A.240705.005`
* Product: `ginkgo`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `97`

**Comment by joshtrichards** [comment] 2024-08-30 22:48
Duplicate of #13404

**Closed by joshtrichards** 2024-08-30 22:48 UTC
Labels: bug, performance: general/non-specific, stable-3.30
