### ISSUE TITLE
Supported Android versions

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#2026] opened 2018-01-22 16:46 UTC
Looking at the actual Play store stats and the offline discussions I'd like to raise this topic:
Which Android versions should we support?

Right now we support 4.0.x - 8.x (aka latest)

The Play store stats for the bottom ranking Android versions are:
* Android version - active devices (total) - active devices (%)
* Android 4.4 - 5,928 - 3.9%
* Android 4.2 - 1,152 - 0.8%
* Android 4.1 - 865 - 0.6%
* Android 4.3 - 532 - 0.4%
* Android 4.0.x - 229 - 0.2%

This adds up to 5,9 percent or >8000 devices. 

I suggest to drop 4.0.x (no proper font support) at least or even 4.1 (no proper RTL support). 
To be discussed could be to drop all of the above mentioned and go for minimum version Android 5.

In any case I would vote for doing this after 3.1 hoping that E2E will then be shipping increment 2 and we have the second release with Nc13 support, so people could still use that release until Nc14 comes out (roughly a year) until then 4.x numbers should be even lower.

What do you think @tobiasKaminsky @mario @nextcloud/android ?

**Comment by mario** [comment] 2018-01-22 17:46
Like I mentioned...
1) 4.x doesn't support many of the modern SSL ciphers, including those used by the push infrastructure
2) At least 4.1 crashes on bunch of occasions (say, when you try to open the sidebar). I assume same is true for all other 4.x.
3) Bunch of provisions in the code don't even work properly even if they're meant for 4.x

I vote for removing 4.x in 3.0.

**Comment by mario** [comment] 2018-01-22 17:52
To summarize, rather no support than the current level of support. None of us tests on 4.x so it's broken beyond repair.

**Comment by mario** [comment] 2018-01-22 19:41
In addition, the UI is broken.

**Comment by tobiasKaminsky** [comment] 2018-01-23 09:26
I tried 4.4.2 on my S3 Neo and it is working really great, even AutoUpload :-)
4.1: 
- weblogin looks weird -> nothing we can do
- drawer indeed crashes if you click on the "open" button, if you swipe to the right it is working.

As of ssl3 problems: this must be a "problem" with our push server as the connection to my server is working.

I'll give it a try :-)

**Comment by AndyScherzinger** [comment] 2018-01-23 09:30
@tobiasKaminsky can you provide me with a stack trace for the drawer crash?

**Comment by tobiasKaminsky** [comment] 2018-01-23 09:34
SSL3: according to ssl labs our current ssl ciphers are not supported for <4.4.

So for me the only remaining "real" problem is that opening drawer is crashing.

**Comment by tobiasKaminsky** [comment] 2018-01-23 10:25
I found the cause of crashing drawer: https://github.com/nextcloud/android/pull/2028

**Comment by AndyScherzinger** [comment] 2018-01-23 11:58
@tobiasKaminsky nice, merged.

@tobiasKaminsky Can you comment on removing support for certain Android versions + Nc App release version? Basically there are to opinions at the moment (a third is of course welcome 😁 ):

* Mario: With release 3.0.0 the App is Android 5+
* Andy_:  With release 3.2.x the App is Android 4.2+

**Comment by AndyScherzinger** [comment] 2018-01-23 12:01
I would also agree to Release 3.2.x is Android 5+ since then if everything goes according to plan with 3.2. we would have shipped Nc13 support _and_ E2E M2 to all users and then make the cut.

...And yes I know 4.4. has been release October 31, 2013 😋

**Comment by tobiasKaminsky** [comment] 2018-01-23 12:54
As long as we do not have to (e.g. due to libs or something else), I think we should keep the min api version as long as possible.
--> keep 4.2+

**Comment by AndyScherzinger** [comment] 2018-01-23 13:34
> --> keep 4.2+

@tobiasKaminsky for app version >=3.2 or >03.0 ?!

**Comment by mario** [comment] 2018-01-23 13:40
Does that means you volunteer to test 4.x extensively before every release? :P

**Comment by tobiasKaminsky** [comment] 2018-01-23 13:59
Well, I did ;-)
At least the basics :-) And as long as there is a significant amount of users...yes.

**Comment by AndyScherzinger** [comment] 2018-01-23 14:32
No, why :P We shipped it in the past, it runs on RCs, enough for me to be honestly. 

To me there is a difference between making it "available for" (as-in minSdk) and "supporting" (spending efforts). While yes that might mean that we

**Comment by tobiasKaminsky** [comment] 2018-02-02 13:05
I think we can close this.

**Closed by tobiasKaminsky** 2018-02-02 13:05 UTC
Labels: needs info/discussion
