### ISSUE TITLE
java.lang.NullPointerException in DocumentsProvider

### ISSUE THREAD

**Issue by jmue** [nextcloud/android#3901] opened 2019-04-15 11:08 UTC
### Actual behaviour
- account is not shown in DocumentsUI as result of java.lang.NullPointerException

### Expected behaviour
- no crash should happen
 
### Steps to reproduce
1. Open StoragePicker after fresh deployment on device

### Environment data
Android version: 8.1

Device model: Android Emulator

Stock or customized system:

Nextcloud app version: dev-20190414

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
2019-04-15 12:59:33.492 27887-27919/com.nextcloud.client E/DatabaseUtils: Writing exception to parcel
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
        at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:537)
        at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:526)
        at com.nextcloud.client.preferences.AppPreferencesImpl.fromContext(AppPreferencesImpl.java:76)
        at com.owncloud.android.providers.DocumentsStorageProvider.queryRoots(DocumentsStorageProvider.java:108)
        at android.provider.DocumentsProvider.query(DocumentsProvider.java:786)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:240)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
        at android.os.Binder.execTransact(Binder.java:697)
2019-04-15 12:59:33.753 27887-27919/com.nextcloud.client E/DatabaseUtils: Writing exception to parcel
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
        at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:537)
        at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:526)
        at com.nextcloud.client.preferences.AppPreferencesImpl.fromContext(AppPreferencesImpl.java:76)
        at com.owncloud.android.providers.DocumentsStorageProvider.queryRoots(DocumentsStorageProvider.java:108)
        at android.provider.DocumentsProvider.query(DocumentsProvider.java:786)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:240)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
        at android.os.Binder.execTransact(Binder.java:697)```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2019-04-15 12:15
Fancy taking a look @ezaquarii? ❤️

**Comment by ezaquarii** [comment] 2019-04-15 17:17
on it

**Comment by ezaquarii** [comment] 2019-04-15 18:02
@jmue Could you please clarify steps to reproduce? What **EXACTLY** are the steps to reproduce it, including any swipes, taps, showing recent apps, going back to launcher, etc.

We're dealing with a timing issue around app lifecycle here. It is going to be tricky to reproduce, although I have a theory.

**Comment by ezaquarii** [comment] 2019-04-15 18:41
`DocumentsStorageProvider` is created and called **before** `MainApp.onCreate()`, where DI is initialized. With uninitialized DI, there is no injection.

I can't reproduce this problem on master, but I know that I hit it some time ago myself and fixed it.

@AndyScherzinger @tobiasKaminsky 
I hit similar issue and fixed DI init on 19-03-2019. I believe 3.7.0 has been branched before that, right?

**Comment by jmue** [comment] 2019-04-15 18:57
I'm on tag 'dev-20190414' and having it there. To reproduce it try one of these scenarios:

A:
- Open app switcher, close all apps
- Got to settings, apps, nextcloud, force stop
- Open Files App/DocumentsUI

B:
- Build an run the app via Android Studio
- Open Files App/DocumentsUI and navigate to some nextcloud folder
- Build and run the app via Android Studio again

**Comment by AndyScherzinger** [comment] 2019-04-15 19:01
@ezaquarii 3.6 has been branched, 3.7 will be a future version of the master branch. So the dev build would need to already ship your change.

**Comment by ezaquarii** [comment] 2019-04-15 20:24
Youp. I fixed my junk, but this is not using injection yet - it's a legacy path.
```
        Context context = MainApp.getAppContext();
        AppPreferences preferences = AppPreferencesImpl.fromContext(context);
```

The thing is, `getAppContext()` is returning `null` until `MainApp.onCreate()` is called, which unfortunately will happen after `ContentProvider` is created and called.

I'll migrate it to injection - that should fix it.

**Comment by ezaquarii** [comment] 2019-04-15 21:09
Now it crashes here:
```
    //  From AccountAuthenticator
    //  public static final String AUTHORITY = "org.owncloud";
    public static String getAuthority() {
        return getAppContext().getResources().getString(R.string.authority);
    }
```

This is a rabbit hole. `MainApp` static APIs and a lot of other static utilities/helpers/doers/performers/providers that depend on `MainApp.getAppContext()` (which is *A LOT*) are going to silently NPE in `ContentProvider`s in general, as `ContentProvider`s start before `MainApp.onCreate()`.

Quite frankly, I'm wondering if this could be the problem with the frequent issues around app syncing reported on Samsung devices, which are known for aggressive process termination.

The thing is, ContentProvider will work ok when the process is up and running, as the `MainApp` is initialized and context is available, but will fail silently with NPE when the process needs to be brought up.

To fix it permanently we need to kill those static utilities that infested the whole app, which is ongoing epic #3600. :)

@tobiasKaminsky @AndyScherzinger could you verify if `ContentProvider`s are involved in any auto-upload? I'm not familiar with that code path.

**Comment by ezaquarii** [comment] 2019-04-28 18:17
@jmue it should be working ok by now. Could you pls confirm that the latest daily build fixed the problem for you?

**Comment by AndyScherzinger** [comment] 2019-04-28 18:31
@ezaquarii sorry for not getting back to you earlier, been on vacation. I am not too famailair with the auto upload code while that part should be based on the job-api implementation (currently via the evernote lib). It has been implemented by @mario :)

**Comment by jmue** [comment] 2019-04-29 11:08
> @jmue it should be working ok by now. Could you pls confirm that the latest daily build fixed the problem for you?

Looks good!

**Comment by ezaquarii** [comment] 2019-05-03 20:59
@AndyScherzinger @tobiasKaminsky  Shall we close then?

**Comment by AndyScherzinger** [comment] 2019-05-04 05:42
Since it seems fixed in the dev build I think so, yes. Good catch!

@jmue please reopen if it happens again after the 3.7 release (still some time to go)

**Closed by AndyScherzinger** 2019-05-04 05:42 UTC
Labels: bug
