### ISSUE TITLE
Random crashes on more than one device

### ISSUE THREAD

**Issue by cornercase** [nextcloud/android#5441] opened 2020-02-10 01:50 UTC
### Steps to reproduce
This crash occurs without app interaction.

The same crash occurs on a OnePlus 6T running OxygenOS and a 6T running LineageOS.

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-BTjtDF_dtYx3reOWB-ccDw==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-BTjtDF_dtYx3reOWB-ccDw==/lib/arm64, /data/app/com.nextcloud.client-BTjtDF_dtYx3reOWB-ccDw==/base.apk!/lib/arm64-v8a, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6013
Id: PQ3A.190801.002
Product: OnePlus6T

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 20c8fda321

### Expected behaviour
- No crash

### Actual behaviour
- Random crashes in background

### Environment data
Android version:  Pie (OxygenOS and LineageOS)

Device model:  OnrPlus 6T

Stock or customized system:  both

Nextcloud app version:  see above

Nextcloud server version:  18

#### Web server error log
```
will check and update ticket
```

#### Nextcloud log (data/nextcloud.log)
```
Will check and update ticket
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by remcoboerma** [comment] 2020-02-10 06:14
Same here, added different phone model 
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/..... 

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: herolte
Model: SM-G930F
Id: R16NW
Product: heroltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G930FXXS7ETA4

**Comment by AndyScherzinger** [comment] 2020-02-10 10:38
Duplicate of #4675

**Closed by AndyScherzinger** 2020-02-10 10:38 UTC
Labels: bug
