### ISSUE TITLE
Can't stop the sync

### ISSUE THREAD

**Issue by cieska** [nextcloud/android#8172] opened 2021-03-16 07:55 UTC
### Expected behaviour
To have more control on files that in transit. To have options to stop the sync that works?

### Actual behaviour
If the file are in auto upload folder and is in the transit, and you want to stop upload (as for example if it is very large file). You chase it where is it in files on server and trying to cancel sync. But it still in transit and keeps syncing. 

In my case I'm on mobile network and it cost for me to upload 2GB file but there is no option to stop it. 

![Screenshot_20210316-072753](https://user-images.githubusercontent.com/41318524/111273751-1988a280-862c-11eb-821a-6c2976c5f5e3.jpg)
In the task bar there is no option to stop it. And you can see that my network monitors shows about 2Mb/s traffic. 
![Screenshot_20210316-072717](https://user-images.githubusercontent.com/41318524/111273966-548ad600-862c-11eb-9316-022aaca5a21b.jpg)
And the actual file is already in the server because this is related to #8134 in this case I have chosen to keep server version and file keeps downloading.

**Comment by tobiasKaminsky** [comment] 2021-03-17 06:10
Totally true, this is something we need: have pause/resume for any upload.

**Comment by cieska** [comment] 2021-03-26 08:12
.

**Comment by daufinsyd** [comment] 2022-09-03 09:54
Hi I have the same error.
I synced a large folder but couldn't stop the sync, despite canceling the sync and having removed the auto-send configuration for the folder.

Even restarting the app/switching the wifi off didn't helped.

I had to rename the local folder for the app to stop trying to sync every files.

**Comment by joshtrichards** [comment] 2023-12-22 21:28
Duplicate of #383

**Closed by joshtrichards** 2023-12-22 21:28 UTC
Labels: enhancement, feature: auto upload, feature: sync and upload
