### ISSUE TITLE
Android Nextcloud App crashing while uploading files via share option into a moved directory

### ISSUE THREAD

**Issue by TheLastChosenOne** [nextcloud/android#11442] opened 2023-03-07 21:05 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Create a directory on your nextcloud server.
Upload something into that directory, so it will be default next time you try to upload something via android share button inside an App.
Move that directory on your nextcloud instance.
Upload a file via Android share option in an app. The old directory will be selected default (content will be listed) but nextcloud won't upload files even if you try to. If you try to go to the upper directory to select the new correct path, the app will crash.

### Expected behaviour

Nextcloud app should upload the file automatically into the new directory path(after moving it) or it should be able to select a different directory without crashing.

### Actual behaviour

App crasheswwhile trying to select a different directory with following message:

### Cause of error
```java
Exception in thread "Thread-12" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240190`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `r8s`
* Model: `SM-G780F`
* Id: `TP1A.220624.014`
* Product: `r8seea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `G780FXXSAEWB3

### Android version

13

### Device brand and model

Samsung S20 FE

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.1

### Nextcloud server version

25.0.4

### Using a reverse proxy?

No

### Android logs

No log file found, searched via TotalCommander on Android

**Comment by AlvaroBrey** [comment] 2023-03-08 08:05
Duplicate of #11207

**Closed by AlvaroBrey** 2023-03-08 08:05 UTC
Labels: bug
