### ISSUE TITLE
Delayed deletion after autoupload

### ISSUE THREAD

**Issue by markum** [nextcloud/android#9931] opened 2022-03-07 22:06 UTC
### Describe the solution you'd like
I have configured the Android app to Autoupload to Nextcloud and delete after the Autoupload. In general I want this, so that my mobile is not filled with pictures. The disadvantage of this solution is: Pictures disappear to fast. Sometimes I would like to send a picture via messenger after taking a picture or during the day. I would like an option to have a delayed deletion after autoupload and that time to be configurable.

### Describe alternatives you've considered
Doing it manually, would be not so useful.

**Comment by r-sweet-codes** [comment] 2022-04-14 13:02
This is what i am missing since months, because my family refuses to have autoupload enabled because of this. (hello fellow family admins)

If you can point me to the right direction (file), i could take a look at it, although i am not an android dev. But i want this asap :D

**Comment by Licmeth** [comment] 2022-04-18 16:49
I think this is basically the same enhancement as requested in #9037

I would also like to see such a feature :)

**Comment by joshtrichards** [comment] 2023-10-10 16:18
Duplicate of #9037
I encourage you to subscribe yourself to that issue to track progress and/or contribution to the feature development discussion. Also helps to give a :+1: to determine interest level.

**Closed as not planned by joshtrichards** 2023-10-10 16:18 UTC
Labels: enhancement, feature: auto upload
