### ISSUE TITLE
NullPointerException upload in Android App

### ISSUE THREAD

**Issue by JakobGode** [nextcloud/android#11360] opened 2023-02-08 08:48 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Upload a file via nextcloud Android App
2. Renamed the top-topfolder 
3. Try to upload another File
4. Screen shows old place where uploaded the first file. If you try to go a step back there's the exception

### Expected behaviour

Jump to Main directory

### Actual behaviour

Show Error

### Android version

10

### Device brand and model

Samsung Galaxy S9

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.0 RC2

### Nextcloud server version

25.0.3

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "Thread-21" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:919)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240052`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `starlte`
* Model: `SM-G960F`
* Id: `QP1A.190711.020`
* Product: `starltexx`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `G960FXXUHFVG4`

**Comment by Rexaris** [comment] 2023-02-20 19:45
same here. Do you have any Workaround for this?

my App information

    ID: com.nextcloud.client
    Version: 30240090
    Build flavor: gplay

Device information

    Brand: Redmi
    Device: joyeuse
    Model: Redmi Note 9 Pro
    Id: SKQ1.211019.001
    Product: joyeuse_eea

Firmware

    SDK: 31
    Release: 12
    Incremental: V13.0.2.0.SJZEUXM

**Comment by JakobGode** [comment] 2023-02-20 19:54
Yes, i resetted the nextcloud app. Like uninstall and reinstall. That makes me possible to login again and the standart upload folder from android is now in home-directory. This ist not deletable. I just made this 1h ago and it worked. 

Maybe you can try to reconstruct the deleted folder-structure and then it will work to upload a file and bring the last-upload-location to an existing directory.
In the error-message you should find the missing folder.
Please try and share your experiance.

**Comment by Rexaris** [comment] 2023-02-20 21:15
Thanks for your fast reply.
I used the reset Method, which worked. 
I couldn't find the missing folder in the error-message and couldn't remember the original structure.

**Comment by AlvaroBrey** [comment] 2023-02-21 10:12
Duplicate of #11207

**Closed by AlvaroBrey** 2023-02-21 10:12 UTC
Labels: bug
