### ISSUE TITLE
Allow to configure ignored extensions or prefixes for auto-upload

### ISSUE THREAD

**Issue by Nowaker** [nextcloud/android#13590] opened 2024-09-21 20:27 UTC
### Is your feature request related to a problem? Please describe.

Nextcloud tries to upload files that aren't meant to be uploaded, even though they reside in the auto-upload directory.

![image](https://github.com/user-attachments/assets/985b7ddf-fbef-4533-bd88-248eb6297fb5)

### Describe the solution you'd like

Allow to configure ignored extensions or prefixes for auto-upload. 
In this case, that would be: `.pending*` to ignore.

### Describe alternatives you've considered

There are no alternatives.

### Additional context

That kind of setting belongs to per-directory settings. Not global ones. This is because `.pending` could be a legitimate file I want uploaded if present in a different directory.

![image](https://github.com/user-attachments/assets/163b689f-4cac-4928-9d75-64bc94cd8290)

**Comment by apparle** [comment] 2024-09-24 07:59
It'll be useful for ignoring `.trashed*` also, which are generated by Google Photos app when it deletes the photos.

A generic ability to ignore specific regex of files will be very useful

**Comment by joshtrichards** [comment] 2024-10-01 14:22
Duplicate of #10645 & #13648

**Closed by joshtrichards** 2024-10-01 14:22 UTC
Labels: enhancement
