### ISSUE TITLE
mobile client keeps crashing once a day

### ISSUE THREAD

**Issue by dicenl** [nextcloud/android#4811] opened 2019-11-09 12:53 UTC
The client does work but i get a crash report

### Actual behaviour
- crash of client about once a day

### Expected behaviour
- not crashing
 
### Steps to reproduce
1. Just have the client open
2. Do have gpslogger installed
3. And talk and passwords

### Environment data
Android version: latest

Device model: samsung s9

Stock or customized system: stock

Nextcloud app version: latest

Nextcloud server version: 17.1

### Logs

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-ROlkwQsdMw_HC9OO-k01fA==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-ROlkwQsdMw_HC9OO-k01fA==/lib/arm64, /data/app/com.nextcloud.client-ROlkwQsdMw_HC9OO-k01fA==/base.apk!/lib/arm64-v8a, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: starlte
Model: SM-G960F
Id: PPR1.180610.011
Product: starltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G960FXXS7CSJ3

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2019-12-02 07:36
Duplicate of #4675, so closing in favor

Brand: Huawei
Device: hwALE-H
Model: ALE-L21

**Closed by AndyScherzinger** 2019-12-02 07:36 UTC
Labels: bug
