### ISSUE TITLE
Error while deleting file in next cloud

### ISSUE THREAD

**Issue by josemichael-nov** [nextcloud/android#13778] opened 2024-10-13 09:01 UTC
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Fragment PreviewMediaFragment{2ef1c8b} (65fb0f0d-9e09-4579-bd50-fb19e27acff8) not attached to a context.
    at androidx.fragment.app.Fragment.requireContext(Fragment.java:972)
    at com.owncloud.android.ui.preview.PreviewMediaFragment.lambda$onStart$1(PreviewMediaFragment.java:351)
    at com.owncloud.android.ui.preview.PreviewMediaFragment.$r8$lambda$uDaoT5tCd_EnFoVGkfSYFCOoOr4(Unknown Source:0)
    at com.owncloud.android.ui.preview.PreviewMediaFragment$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:1000)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loopOnce(Looper.java:242)
    at android.os.Looper.loop(Looper.java:362)
    at android.app.ActivityThread.main(ActivityThread.java:8448)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `motorola`
* Device: `cuscoi`
* Model: `motorola edge 50 fusion`
* Id: `U2UUI34.40-108-3`
* Product: `cuscoi_g`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `17e97f-924ed4`

**Comment by joshtrichards** [comment] 2024-10-15 13:36
Duplicate of #13256

**Closed by joshtrichards** 2024-10-15 13:36 UTC
Labels: bug, performance: ISE/IAE :confused:, stable-3.29
