### ISSUE TITLE
Reconnect Markdown Editor not possible

### ISSUE THREAD

**Issue by strangmann** [nextcloud/android#13085] opened 2024-06-08 14:58 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Create a .md File in Nextcloud-App
2. Leave Nextcloud-App (running in background)
3. Reopen Nextcloud-App after two minutes
4. "Reconnect" Button not working

### Expected behaviour

After clicking reconnect it should be possible to edit the Markdown file

### Actual behaviour

The window is blank, and at the top is the non-working Reconnect banner.

### Android version

14

### Device brand and model

Samsung Galaxy Tab S8+ (SM-X800)

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.0

### Nextcloud server version

28.0.5

### Using a reverse proxy?

No

**Comment by strangmann** [comment] 2024-06-08 15:22
\* The reconnect button in the webinterface works correctly.

**Comment by joshtrichards** [comment] 2024-06-10 19:25
Duplicate of #12138

**Closed by joshtrichards** 2024-06-10 19:25 UTC
Labels: bug
