### ISSUE TITLE
20230121 fingerprint reading is in endless loop

### ISSUE THREAD

**Issue by gerroon** [nextcloud/android#11306] opened 2023-01-26 16:37 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Download this version

Enable fingerprint security on your device 

Make sure this app uses it

Test it on Android LineageOS 20

### Expected behaviour

It should open the app

### Actual behaviour

When I open the app it asks for my fingerprint (which is something I set up)  Normally NC app would have no propblem with this, I have been using it for a long time  with NC mobile app until this last update I got. When I open the app, it asks for the finger print, I touch my finger on the reader then it asks again then again and again. The app is in endless loop of asking for finger print reading. 

This was not used to be the case in the prior versions, I cant tell you which version worked exactly, but  bug showed up very recently.

### Android version

LIneage OS 20

### Device brand and model

Pixel

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

20230121

### Nextcloud server version

23.0.9

### Using a reverse proxy?

I don't know

### Android logs

ID: com.nextcloud.android.beta
Version: 20230121
Build flavor: versionDev
Device information
Brand: google
Device: bramble
Product: bramble
Firmware
SDK: 33
Release: 13
Incremental: 01aa5a9067

**Comment by AlvaroBrey** [comment] 2023-01-27 10:41
Thanks for your report, but I can't reproduce it. Can you get a logcat from the Android device so we can see if there's any errors? Instructions here: https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat-mag

Feel free to search and replace the server URL, username and other file names in the output.

**Comment by gerroon** [comment] 2023-01-27 17:06
I get some kind of crash after couople tries and swiping the app. Let me know if clears it up. If not I will try to get the logcat

I cant even use "use pattern" it does the same thing, so this does not seem to be a finger print reader thing,t he security unlocking has some issues in the latest version. LIke I said all other apps have no isse with this,


```

Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:907)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:138)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByEncryptedRemotePath(FileDataStorageManager.java:122)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:118)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2423)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1543)
    at android.app.Activity.performStart(Activity.java:8330)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3670)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7872)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
App information
ID: com.nextcloud.android.beta
Version: 20230121
Build flavor: versionDev
Device information


```

**Comment by AlvaroBrey** [comment] 2023-01-30 10:03
Ah, then this is a duplicate of #11305. Known bug in the dev version, which should be fixed soon hopefully. You may have to reinstall the app though.

**Comment by AlvaroBrey** [comment] 2023-01-30 10:04
Duplicate of #11305

**Closed by AlvaroBrey** 2023-01-30 10:03 UTC
Labels: bug, dev version, needs info
