### ISSUE TITLE
20200320 crash report

### ISSUE THREAD

**Issue by trackmastersteve** [nextcloud/android#5747] opened 2020-03-26 16:17 UTC
### Steps to reproduce
1. Hamburger menu. Go to Auto-upload.
2. Then settings for a folder.
3. Check "also upload existing files" and save.

### Expected behaviour
- Tell us what should happen
Should set settings.

### Actual behaviour
- Tell us what happens
Freezes, then Force closes.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
10
Device model: 
Pixel 3 XL
Stock or customized system:
Stock
Nextcloud app version:
20200320
Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tryallthethings** [comment] 2020-03-26 22:50
Can confirm this on my Samsung Galaxy S7 as well.
Keeps on crashing every time I exit any Auto-Upload folder after making changes. I've got a couple of thousand pictures on my phone though.

**Comment by tobiasKaminsky** [comment] 2020-03-27 05:18
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by AndyScherzinger** [comment] 2020-03-27 07:20
@tobiasKaminsky like mentioned in the other issue (can't find it right now) and discussed with @ArisuOngaku we do run into crashes (as in freezes+termination) for upload existing in cases where users have large image volumes :/

**Comment by tobiasKaminsky** [comment] 2020-03-27 08:48
Ah, right.
But this can also happen if you try to upload 500 files on your own…
So it is only triggered by the new feature.

**Comment by tobiasKaminsky** [comment] 2020-03-27 08:49
Solution would be to have the upload process as a work manager job.

**Comment by tobiasKaminsky** [comment] 2020-03-27 08:49
Duplicate of #5613

**Closed by tobiasKaminsky** 2020-03-27 08:49 UTC
Labels: bug, needs info/discussion
