### ISSUE TITLE
Null Pointer exception when trying to get user quota on login

### ISSUE THREAD

**Issue by thebaron06** [nextcloud/android#2192] opened 2018-02-17 08:45 UTC
Description | Version or Model
--- | ---
Device | LG G3 |
Android | LineageOS 14.1, which is basically 7.1.2 (Build 20180122)
Server | 10.0.6 (stable)
App | 3.0.1 (14.02.2018)

When trying to initially connect the app with the nc server a null pointer is dereferenced when trying to get the user account quota.

This issue is related to the [android-library](https://github.com/nextcloud/android-library) project, see logcat dump. If necessary please move this issue to the according project.
The following commit might be the reason for this: https://github.com/nextcloud/android-library/commit/fbd9392030dfe29353c4a79f504cc9be6554d391

Issue maybe related to this: https://github.com/nextcloud/android/issues/2133

I tried to retrieve the account details manually using curl and there is no quota object within the response:
`curl -u <userid>:<userpass> -G 'https://<nc-host>/ocs/v1.php/cloud/user' -d format=json`
```json
{
    "ocs": {
        "data": {
            "display-name": "<username>",
            "email": "<usermail>",
            "id": "<userid>"
        },
        "meta": {
            "message": null,
            "status": "ok",
            "statuscode": 100
        }
    }
}
```

Here is a dump of logcat:
```
02-16 18:11:48.160  8895  6713 D OwnCloudClient #9: Creating OwnCloudClient
02-16 18:11:48.161  8895  6713 D OwnCloudClient #9: REQUEST HEAD /remote.php/webdav/
02-16 18:11:48.380  8895  6713 D ExistenceCheckRemoteOperation: Existence check for https://<nc-host>/remote.php/webdav/ targeting for  existence finished with HTTP status 200
02-16 18:11:48.381  8895  6713 D OwnCloudClient #9: REQUEST GET /ocs/v1.php/cloud/user
02-16 18:11:48.628  8895  6713 E GetRemoteUserInfoOperation: Exception while getting OC user information
02-16 18:11:48.628  8895  6713 E GetRemoteUserInfoOperation: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.lib.common.Quota.getQuota()' on a null object reference
02-16 18:11:48.628  8895  6713 E GetRemoteUserInfoOperation: 	at com.owncloud.android.lib.resources.users.GetRemoteUserInfoOperation.run(GetRemoteUserInfoOperation.java:130)
02-16 18:11:48.628  8895  6713 E GetRemoteUserInfoOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:151)
02-16 18:11:48.628  8895  6713 E GetRemoteUserInfoOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:155)
02-16 18:11:48.628  8895  6713 E GetRemoteUserInfoOperation: 	at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:84)
02-16 18:11:48.628  8895  6713 E GetRemoteUserInfoOperation: 	at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:41)
02-16 18:11:48.628  8895  6713 E GetRemoteUserInfoOperation: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
02-16 18:11:48.628  8895  6713 E GetRemoteUserInfoOperation: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-16 18:11:48.628  8895  6713 E GetRemoteUserInfoOperation: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
02-16 18:11:48.628  8895  6713 E GetRemoteUserInfoOperation: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-16 18:11:48.628  8895  6713 E GetRemoteUserInfoOperation: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-16 18:11:48.628  8895  6713 E GetRemoteUserInfoOperation: 	at java.lang.Thread.run(Thread.java:761)
```

**Comment by AndyScherzinger** [comment] 2018-02-19 08:31
cc @tobiasKaminsky @mario

**Comment by xXSTrikeXx** [comment] 2018-02-19 09:57
Sry, but isnt v10.0.6 EOL?

**Comment by AndyScherzinger** [comment] 2018-02-19 12:02
Nc10 is EOL since 08/2017 while the Quota itself is available via the services since Nc9 so the issue is still valid.

**Comment by tobiasKaminsky** [comment] 2018-02-20 07:39
@thebaron06 thank you for your fix :+1: 
I tested it and added one missing import. It will be in next version :-)

**Closed** 2018-02-20 08:29 UTC
Labels: bug, high, pr exists

**Comment by AndyScherzinger** [comment] 2018-02-20 08:33
@tobiasKaminsky will this be 3.0.2 or 3.1.0 ?

**Comment by tobiasKaminsky** [comment] 2018-02-20 09:47
Both, as the fix is in library and we do not have stable-3.0.x branch on library.

**Comment by AndyScherzinger** [comment] 2018-02-20 10:04
true :+1:
