### ISSUE TITLE
Keep a resized (smaller) copy of pictures after auto upload

### ISSUE THREAD

**Issue by jakommo** [nextcloud/android#8194] opened 2021-03-20 20:55 UTC
### Is your feature request related to a problem? Please describe.
I take many pictures and videos and use auto upload with nextcloud. When my storage space on the phone gets low I deleted the oldest pictures and videos, but from time to time I want to show one of those to family or friends and then going through the Media tab or folders in the nextcloud app is not very fast and convenient as it takes a long time to load previews.   

### Describe the solution you'd like
It would be nice if pictures (and preferably videos as well, but that might be too resource intense) would be resized prior to uploading them. Then upload the original sized version and delete it after successful upload, but keep the smaller / resized file on the device.
Doing so, one could keep a much bigger collection of media locally for quick browsing/viewing, without the high storage needs. 

### Describe alternatives you've considered
I was looking into achieving something like this with tasker or a similar app, but haven't found anything that would automatically resize / scale down pictures or videos without user interaction.

**Comment by joshtrichards** [comment] 2023-12-12 13:35
Duplicate of #1490

**Closed by joshtrichards** 2023-12-12 13:35 UTC
Labels: enhancement, feature: auto upload, feature: previews and thumbnails
