### ISSUE TITLE
Allow to ignore Google Photo app generated `.trashed` files in auto upload

### ISSUE THREAD

**Issue by codetalker78** [nextcloud/android#13162] opened 2024-06-20 17:05 UTC
### Is your feature request related to a problem? Please describe.

The Google photo app (on my Pixel android phone) deletes photos by renaming them with the prefix "_.trashed-_". This allows to recover deleted photos from the trash for a couple of days, before they are really deleted. 

The nextcloud app auto upload uploads all these _.trashed_ files happily to the nextcloud server, but of course there, they just pile up and take up space, but they are never needed and never automatically cleaned up like they are on device. 

### Describe the solution you'd like

The auto upload configuration should allow to define a file pattern that should be ignored. 

This would already solve the problem that files that are marked as deleted are uploaded. 

To support my use case of taking pictures, reviewing them and deleting the non-keepers ideally, it would be nice to add the option to delay the upload of new files for a while. This would solve the problem that a new photo is upload before I switch from camera to gallery to delete it. 
Adding the option to configure a minimum file age would be a solution for this. 

Both options together would ideally support the common _take pictures, review them, delete the non-keepers and only upload the keepers_ photography workflow. 

### Describe alternatives you've considered

Not really. Maybe an automated workflow on the server that deletes the _.trashed_ files after upload?

**Comment by codetalker78** [comment] 2024-06-23 06:16
While writing the description, I added a second aspect, that could be a separate ticket - the minimum age for upload. Should I move this to a separate ticket?

**Comment by joshtrichards** [comment] 2024-07-09 13:08
Duplicate of #10645

**Comment by joshtrichards** [comment] 2024-07-09 13:08
> While writing the description, I added a second aspect, that could be a separate ticket - the minimum age for upload. Should I move this to a separate ticket?

For that, see #2323

**Closed** 2024-07-09 18:53 UTC
Labels: enhancement, feature: auto upload
