### ISSUE TITLE
Backup Contacts View can't be closed 

### ISSUE THREAD

**Issue by aleister09** [nextcloud/android#931] opened 2017-05-02 21:32 UTC
### Actual behaviour
After download and open a Restore-Backup (.vcf file) The Contact BackUp Activity can't be closed 

### Steps to reproduce
1. Open App
2. Open Contacts-Backup folder
3. Open a Restore-Backup File(.vcf)
4. Press Back Button 

### Environment data
Android version:7.1.2

Device model: 

Nextcloud app version:Master

Nextcloud server version:12

**Comment by mario** [comment] 2017-05-03 03:48
So I just tested this and it works for me. Can you post a video please? Are you sure it's the latest master? :)

**Comment by tobiasKaminsky** [comment] 2017-05-03 12:26
Also working for me on latest master.

**Comment by aleister09** [comment] 2017-05-03 15:04
It is happening after the first login and I'm sure that it is the latest master =) 

![ezgif com-video-to-gif 5](https://cloud.githubusercontent.com/assets/25756086/25666976/ad9de3b2-2fe7-11e7-9e29-45ff62eaaf3c.gif)

**Comment by tobiasKaminsky** [comment] 2017-05-04 11:39
Indeed, if the app is started fresh, I could reproduce it 100%, during regular runtime not always.
I created a PR for it.

**Comment by AndyScherzinger** [comment] 2017-05-04 12:56
merged to master to be shipped with 1.5.0

**Closed by AndyScherzinger** 2017-05-04 12:56 UTC
Labels: bug, pr exists
