### ISSUE TITLE
Share feature on android crashes 

### ISSUE THREAD

**Issue by dvb7836** [nextcloud/android#7974] opened 2021-02-13 15:12 UTC
### Steps to reproduce
1. Open mobile app
2. Press share button on a folder/file
3. Select account to share with

### Expected behaviour
- Share feature should work as it does on web

### Actual behaviour
- Share feature on android crashes

### Can you reproduce this problem on https://try.nextcloud.com?
Android app problem

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:486)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForCreateShareOperations(ErrorMessageAdapter.java:254)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForResultAndOperation(ErrorMessageAdapter.java:143)
	at com.owncloud.android.utils.ErrorMessageAdapter.getErrorCauseMessage(ErrorMessageAdapter.java:79)
	at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:380)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1704)
	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:734)
	at com.owncloud.android.services.-$$Lambda$OperationsService$KsB1LbjHjlEBSp0h7XO24czs-OQ.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:215)
	at android.app.ActivityThread.main(ActivityThread.java:6939)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: nash
Model: Moto Z (2)
Id: PPX29.159-24
Product: nash

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: e78f1

**Comment by tobiasKaminsky** [comment] 2021-02-17 08:12
Duplicate of https://github.com/nextcloud/android/issues/7987
Fix is in: #7992

**Closed by tobiasKaminsky** 2021-02-17 08:12 UTC
Labels: bug
