### ISSUE TITLE
Android Dev app crashed, trying to play a video.

### ISSUE THREAD

**Issue by jordan33134** [nextcloud/android#6941] opened 2020-09-12 22:09 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{a21221 u0 com.nextcloud.android.beta/com.nextcloud.client.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2141)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8016)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200912
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond1q
Model: SM-G973U1
Id: QP1A.190711.020
Product: beyond1qlteue

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G973U1UES4DTG1

**Comment by tobiasKaminsky** [comment] 2020-09-14 11:59
Duplicate of #6798

**Closed by tobiasKaminsky** 2020-09-14 11:59 UTC
Labels: bug
