### ISSUE TITLE
Please utilise the default browser of Android during initial authentication.

### ISSUE THREAD

**Issue by rokejulianlockhart** [nextcloud/android#10165] opened 2022-05-04 14:20 UTC
### Is your feature request related to a problem? Please describe.
Initial authentication by Nextcloud is slow. Additionally, I am unable to utilize the features that my browser is able to provide alternatively.

### Describe the solution you'd like
Please utilize the default browser of Android during initial authentication.

### Additional context
[This](http://user-images.githubusercontent.com/42837531/166698475-d19c5161-2379-4ef7-9a42-e3037fec4d93.png) demonstrates what should be utilized during initial authentication. This method is utilized during addition to Davx5.

[This](http://user-images.githubusercontent.com/42837531/166698490-7d9a38ca-91e2-4089-bf80-fdf522e74658.png) is what is utilized during initial authentication. The interface and speed of it is objectively inferior.

**Comment by AlvaroBrey** [comment] 2022-11-23 17:59
Duplicate of #1723

**Closed by AlvaroBrey** 2022-11-23 17:59 UTC
Labels: enhancement
