### ISSUE TITLE
Configuring first access

### ISSUE THREAD

**Issue by sercasbh** [nextcloud/android#13860] opened 2024-10-22 21:16 UTC
### Cause of error
```java
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 9
    at java.lang.String.checkBoundsBeginEnd(String.java:4466)
    at java.lang.String.substring(String.java:2517)
    at com.nextcloud.client.account.UserAccountManagerImpl.exists(UserAccountManagerImpl.java:119)
    at com.nextcloud.client.mixins.SessionMixin.onRestart(SessionMixin.kt:100)
    at com.nextcloud.client.mixins.MixinRegistry.onRestart(MixinRegistry.kt:48)
    at com.owncloud.android.ui.activity.BaseActivity.onRestart(BaseActivity.java:118)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onRestart(FileDisplayActivity.java:2352)
    at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1592)
    at android.app.Activity.performRestart(Activity.java:8850)
    at android.app.ActivityThread.performRestartActivity(ActivityThread.java:5575)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:250)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:187)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2548)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loopOnce(Looper.java:242)
    at android.os.Looper.loop(Looper.java:362)
    at android.app.ActivityThread.main(ActivityThread.java:8407)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300190`
* Build flavor: `generic`

### Device information
* Brand: `motorola`
* Device: `bangkk`
* Model: `moto g84 5G`
* Id: `U1TC34.22-64-19-4`
* Product: `bangkk_ge`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `159e87-1cb5d`

**Comment by joshtrichards** [comment] 2024-10-23 14:30
Duplicate of #13828

**Closed by joshtrichards** 2024-10-23 14:30 UTC
