### ISSUE TITLE
With 3.25.0 RC1 all autoupload settings were reset to their default

### ISSUE THREAD

**Issue by NicolasGoeddel** [nextcloud/android#11641] opened 2023-05-22 12:41 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

There are no special steps involved. Since 17.05.2023 no pictures were uploaded to my cloud automatically anymore.
Today I looked into my Autoupload settings and saw that all settings are gone and restored to their default.

### Expected behaviour

After an update the settings should not be touched!

### Actual behaviour

The settings were reset.
After setting them up again the app now tries to upload thousands of pictures and videos again. -.-

You can see all the requests to the service since 14:15 today because of that.
![image](https://github.com/nextcloud/android/assets/1520064/bcc6264f-de15-49fb-940d-edd09779b16b)

### Android version

13

### Device brand and model

Google Pixel 6 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.25.0 RC1

### Nextcloud server version

Nextcloud Hub 3 (25.0.5)

### Using a reverse proxy?

Yes

### Android logs

The log has a size of 4 MB and contains sensible information. I will not attach it here.

**Comment by NicolasGoeddel** [comment] 2023-05-22 14:39
Nextcloud still tries to upload thousands of images, then it seems to fail in between and starts from the beginning. This is happening now since over 2 hours.

**Comment by NicolasGoeddel** [comment] 2023-05-22 15:52
I quit the developer program in the Play Store and reinstalled the app so I may get the old version instead of RC1. But it did not change anything. I still have the same version as before now and even more annoying: All my settings were lost... 🙄
Is that the usual behaviour after a reinstall?

**Comment by NicolasGoeddel** [comment] 2023-05-22 15:53
And as you can image, the upload madness starts from the beginning now...

**Comment by NicolasGoeddel** [comment] 2023-05-22 16:03
It just finished all its uploads. Now I am waiting if it wants to start over again. I added a few new screenshots that should be uploaded with the next sync run. Hopefully nothing more.

Was the beta program the difference in the end although the version is still the same? Can that be?

**Comment by NicolasGoeddel** [comment] 2023-05-22 16:06
It just added thousands uploads to list again. All of them are screenshots but only 3 are new.

It seems like an additional file in a folder triggers a sync of the complete folder. If the reason for that is the option "Vorhandene Dateien ebenfalls hochladen" (roughly translated: "Upload existing files as well"), then this is a bug in my opinion.  Only because one file changes it should not try to upload every other file in that folder.

**Comment by NicolasGoeddel** [comment] 2023-05-22 16:34
Nothing is happening anymore. I took a few new photos but since half an hour no photo was uploaded.

Do you know any other app that is able to upload files according to their file creation date to a WebDAV folder and put them in a folder structure like `%Y/%m` like the Nextcloud app does it? In this case I could just stop using the auto upload feature since it often had problems in the past now...

**Comment by BLu85** [comment] 2023-05-23 07:46
Can it be similar to #11263 ?

Some people are switching to FolderSync to upload their files, as Nextcloud Auto Upload is not working properly (you well know it). I wonder if anyone is working on fixing this. In a Cloud App this is the the main feature that should always work.

**Comment by CaixaNegraPT** [comment] 2023-05-23 18:02
Same thing happen to 2 x Android phones ... i have thousands of image files in the phone that auto sync and all the config is gone. I have setup resync but experience tells me that the Nextcloud android client will take hours to parse every single file one by one.... last time i did this, only took me 2 days :(

**Comment by kareiva** [comment] 2023-05-24 19:37
Maybe I misunderstand the mainstream use cases for the Android app, but my primary reason for having the app on the phone in the first place, is to make sure important things are automatically uploaded from the phone to the nextcloud server. 

Normally I open the app on android a few times a month and I would probably care less if it just worked. Now with every bit of breeze such as an app update or a vpn disconnect, I always feel unsure if the app did what it was supposed to do. 

I totally do not trust nextcloud on android, despite the fact that I run a handful of terabyte-sized instances of nextcloud server for a few years already and those seem to do fine.

So the lack of stability on android just kills the whole idea of a road warrior phone as a nextcloud client. I have written a few apps for Android a long time ago, so I will probably be little to no use as a developer, but at this point I am either joining to help with few lines of code/testing/anything, or just ditching the whole stack.

**Comment by szaimen** [comment] 2023-05-24 21:35
I can reproduce this. Cc @tobiasKaminsky

**Comment by NicolasGoeddel** [comment] 2023-05-25 08:21
> I can reproduce this. Cc @tobiasKaminsky

If you knew how much that calms me down. 🙂

**Comment by szaimen** [comment] 2023-05-26 08:56
@tobiasKaminsky does https://github.com/nextcloud/android/pull/11660 fix this?

**Comment by tobiasKaminsky** [comment] 2023-05-26 10:01
It cannot fix it, as the database is gone.
But for other users, that update from 3.24 to 3.25.0 RC2 or final it will work without problems.

**Comment by szaimen** [comment] 2023-05-26 10:02
> But for other users, that update from 3.24 to 3.25.0 RC2 or final it will work without problems.

That is good to hear. Closing then.

**Closed by szaimen** 2023-05-26 10:02 UTC
Labels: bug, regression, 1. to develop

**Comment by Rgquintas** [comment] 2023-05-27 11:23
Same issue but worse... I've installed RC2 and just upload one photo. After that, stops working again.
Disabled and enbled autoupload settings, unisntall, wipe and reinstall latest dev app... Nothing works
Anoying....

**Comment by bjo81** [comment] 2023-05-27 17:05
Just took a look into my 3.25.0 RC1 and all settings are gone. I will test 3.25.0 RC2.

**Comment by georg-mayer** [comment] 2023-05-31 17:19
I have exactly the same problem. When logging my server I see that the app tries since days to upload these files (which are already there and don't need an upload) and this results in literally millions of requests. It drains the battery of my phone, it uses up my mobile data. 

I found out about it today and find not other way to stop it than to uninstall the app. 

Can somebody please point me to the version 3.25.0 RC2 - I looked all around and cannot find it. I would like to give it a try.

Thanks for your support!
