### ISSUE TITLE
app not syncing auto upload folder and crashing sometimes

### ISSUE THREAD

**Issue by netphantm** [nextcloud/android#4984] opened 2019-12-11 11:18 UTC
### Actual behaviour
- Tell us what happens
app not syncing auto upload folder and crashing sometimes

### Expected behaviour
- Tell us what should happen
 autosync camera folder
### Steps to reproduce
1. Open app
2. click on folder
3. ... sync now

### Environment data
Android version: 9

Device model: a5y17lte
Stock or customized system: ressurection remix 7.0.0

Nextcloud app version: 3.9.2

Nextcloud server version: 17.0.1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{1121196 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1746)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6723)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a5y17lte
Model: SM-A520F
Id: PQ2A.190205.001
Product: a5y17ltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.faham.20190210.021912

**Comment by AndyScherzinger** [comment] 2019-12-20 07:28
Duplicate of #2010

**Closed by AndyScherzinger** 2019-12-20 07:28 UTC
Labels: bug
