### ISSUE TITLE
Mr moses

### ISSUE THREAD

**Issue by M0977** [nextcloud/android#13864] opened 2024-10-23 10:06 UTC
### Cause of error
```java
Exception in thread "Thread-7" java.lang.IllegalArgumentException: Trying to execute a sync operation with a storage manager for an anonymous account
    at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:49)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$fetchExternalLinks$9(DrawerActivity.java:1231)
    at com.owncloud.android.ui.activity.DrawerActivity.$r8$lambda$oHM2j1MZkviAIdyIFWoI2kSeF9c(Unknown Source:0)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:784)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `HUAWEI`
* Device: `HWMAR`
* Model: `MAR-LX2`
* Id: `HUAWEIMAR-L22A`
* Product: `MAR-LX2`

### Firmware
* SDK: `28`
* Release: `9`
* Incremental: `9.1.0.293C185`

**Comment by joshtrichards** [comment] 2024-10-23 14:24
Duplicate of #13323

**Closed by joshtrichards** 2024-10-23 14:24 UTC
