### ISSUE TITLE
Trashed photo are uploaded

### ISSUE THREAD

**Issue by Aohzan** [nextcloud/android#13052] opened 2024-05-28 11:34 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Configure upload in the camera directory
2. Trash a photo in Google Photo app
3. Nextcloud app will upload the .trashed_xx file

### Expected behaviour

Trashed photo are not uploaded

### Actual behaviour

Trashed photo seems to only be rename pictures from xxx to .trashed_xxx

### Android version

14

### Device brand and model

Google Pixel 5

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.0

### Nextcloud server version

29.0.a

### Using a reverse proxy?

Yes

### Additional information

Photo x will be reuploaded as file seems to be renamed

**Comment by march42** [comment] 2024-06-06 16:51
I think this is a duplicate of #10645 
I'm having the same issue and I'm currently deleting both files, if md5sum matches.

**Comment by Aohzan** [comment] 2024-06-06 19:02
Yes indeed

**Closed** 2024-07-22 16:38 UTC
Labels: bug
