### ISSUE TITLE
Proxy support in app 

### ISSUE THREAD

**Issue by user858753257** [nextcloud/android#1712] opened 2017-10-25 08:03 UTC
Is there a solution to configure a proxy in the android app ?

**Comment by AndyScherzinger** [comment] 2017-10-25 14:39
At this moment, no. There is a discussion here: #606 but "normal" proxies can be configured in NAdroid in the network settings itself...

**Comment by Spindletop** [comment] 2018-02-10 09:21
Even without in-app support of proxy settings, there are problems using Android/system proxy settings:

- application does not support proxies which require authorization (browsers like Firefox for Android do support this) - **enhancement** as not many apps support this, even _davdroid_ as mentioned in #606 does not support this
- proxy exclusions ("Bypass proxy for") are ignored - clearly a **bug**. _davdroid_ as mentioned in #606 does support it. For reference, the problem still applies in Owncloud app: App uses Android proxy setting but ignores exclusions (https://github.com/owncloud/android/issues/793)

**Comment by joshtrichards** [comment] 2024-10-19 01:36
Duplicate of #606

**Closed by joshtrichards** 2024-10-19 01:36 UTC
Labels: enhancement, connectivity
