### ISSUE TITLE
sync works fine, upload doesn't

### ISSUE THREAD

**Issue by bruderb** [nextcloud/android#7626] opened 2020-12-07 20:02 UTC
### Steps to reproduce
1. tag file to be shared
2. share with nextcloud

### Expected behaviour
file should be uploaded and be listed in Uploads

### Actual behaviour
extremely short flashing screen message (non-readable), not uploading, no entry in Uploads

### Environment data
Android version: 10

Device model: 
Samsung SM-T510

Stock or customized system:
stock

Nextcloud app version:
3.14.1

Nextcloud server version:
20.0.2

Reverse proxy:
no

#### Web server error log
apache is not reached by requests

Insert your webserver log here
apache is not reached by requests

#### Nextcloud log (data/nextcloud.log)
no entry

Insert your Nextcloud log here
no log entry 

Comment:
I read about ipv6 being the preferred layer. Is this a good idea?
I stopped ip6 in my WLAN yesterday and had temporary success with uploads.
Tablet is rebooted and connected with ip4 only (sync works fine)

Is there a log somewhere in the filesystem of the tab?

**Comment by AndyScherzinger** [comment] 2020-12-07 20:07
Log is only present in non stable releases.

Could you check #7587 in case you are sharing to the Nextcloud app via another app or do you mean upload files from within the Nextcloud app?

**Comment by bruderb** [comment] 2020-12-07 20:16
OK. Sharing from another app fails, uploading from within NC app works.
Thanks for caring!

**Comment by AndyScherzinger** [comment] 2020-12-07 20:21
I'll close this one then and thanks for the quick feedback

**Comment by AndyScherzinger** [comment] 2020-12-07 20:21
Duplicate of #7587

**Closed by AndyScherzinger** 2020-12-07 20:21 UTC
Labels: bug, needs info/discussion
