### ISSUE TITLE
不能播放视频

### ISSUE THREAD

**Issue by leehonys** [nextcloud/android#7031] opened 2020-09-30 02:25 UTC
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{486cab0 u0 com.nextcloud.android.beta/com.nextcloud.client.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1769)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200927
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: sagit
Model: MI 6
Id: PKQ1.190118.001
Product: sagit

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V11.0.5.0.PCACNXM
``
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2020-09-30 07:08
Duplicate of #2010

**Closed by tobiasKaminsky** 2020-09-30 07:08 UTC
Labels: bug
