### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Mcrold2001** [nextcloud/android#13433] opened 2024-08-21 12:10 UTC
### Cause of error
```java
Exception in thread "Thread-4" java.lang.IllegalArgumentException: Trying to execute a sync operation with a storage manager for an anonymous account
    at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:49)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$fetchExternalLinks$9(DrawerActivity.java:1231)
    at com.owncloud.android.ui.activity.DrawerActivity.$r8$lambda$oHM2j1MZkviAIdyIFWoI2kSeF9c(Unknown Source:0)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a34x`
* Model: `SM-A346E`
* Id: `UP1A.231005.007`
* Product: `a34xdxx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `A346EXXS8CXG4`

**Comment by joshtrichards** [comment] 2024-08-21 18:04
Duplicate of #13323

**Closed by joshtrichards** 2024-08-21 18:04 UTC
