### ISSUE TITLE
Crash when exiting folder (I think)

### ISSUE THREAD

**Issue by xXChampionsXx** [nextcloud/android#12743] opened 2024-03-26 01:32 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I think this is what I did before it crashed:
1) Go into a Folder
2) Open a Video
3) Go back to root directory

### Expected behaviour

Show root directory

### Actual behaviour

Crash (Screen with error message)

### Android version

12

### Device brand and model

OnePlus 7T

### Stock or custom OS?

Stock

### Nextcloud android app version

30280090

### Nextcloud server version

28.0.3

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Stack
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3780)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3942)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:109)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:233)
    at android.os.Looper.loop(Looper.java:344)
    at android.app.ActivityThread.main(ActivityThread.java:8212)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
Caused by: Exception in thread "main" java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Stack
    at com.owncloud.android.ui.activity.FileDisplayActivity.loadSavedInstanceState(FileDisplayActivity.java:296)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onCreate(FileDisplayActivity.java:269)
    at android.app.Activity.performCreate(Activity.java:8129)
    at android.app.Activity.performCreate(Activity.java:8109)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3749)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3942)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:109)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:233)
    at android.os.Looper.loop(Looper.java:344)
    at android.app.ActivityThread.main(ActivityThread.java:8212)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30280090`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus7T`
* Model: `HD1903`
* Id: `SKQ1.211113.001`
* Product: `OnePlus7T_EEA`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `Q.202303230244`

### Additional information

I put the error message from the app as the log, is this enough or do I really need to fight with adb? Cause I really don't want to...

**Comment by xXChampionsXx** [comment] 2024-03-26 01:37
This could be the same as #12528 I think, but somebody who actually knows what they're doing should look at this and tell me xD

**Comment by joshtrichards** [comment] 2024-03-26 16:40
Agreed. :)
Duplicate of #12528
Fix merged. Should be gone in >=v3.28.1

**Closed by joshtrichards** 2024-03-26 16:40 UTC
Labels: bug
