### ISSUE TITLE
Nextcloud Android keeps failing with OOM

### ISSUE THREAD

**Issue by Digit-al** [nextcloud/android#10999] opened 2022-11-07 09:49 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Keep the nextcloud client running with several folder to synchronize 

### Expected behaviour

Synchro works for all

### Actual behaviour

All the img and videos in the whatsapp folder are in error 
Many OOM appearing on the Android screen, nextcloud app reported unresponsive by the system 

### Cause of error
```java
Exception in thread "WM.task-1" java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 976336 free bytes and 953KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.addConditionWaiter(AbstractQueuedSynchronizer.java:1896)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2077)
    at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
    at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220390`
* Build flavor: `gplay`

### Device information
* Brand: `POCO`
* Device: `alioth`
* Model: `M2012K11AG`
* Id: `SKQ1.211006.001`
* Product: `alioth_eea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `V13.0.8.0.SKHEUXM`

### Android version

12

### Device brand and model

POCO F3

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.3

### Nextcloud server version

25.0.1

### Using a reverse proxy?

Yes

**Comment by AlvaroBrey** [comment] 2022-11-23 12:16
Duplicate of #10653

**Closed by AlvaroBrey** 2022-11-23 12:16 UTC
Labels: bug
