### ISSUE TITLE
[v3.17.0 RC2] Activity stream: add icon (and others) are too small

### ISSUE THREAD

**Issue by strassan** [nextcloud/android#7786] opened 2021-01-05 16:27 UTC
### Steps to reproduce
1. Add a file to Nextcloud
2. Look into the activities
3. The plus symbol is tiny

### Expected behaviour
- The plus symbol should be as big as the other symbols

### Actual behaviour
- The plus symbol is tiny

![Screenshot_20210105-121843_Nextcloud](https://user-images.githubusercontent.com/62120554/103671297-034ece00-4f7b-11eb-838e-4a24ad4036d6.jpg)

### Can you reproduce this problem on https://try.nextcloud.com?
Haven't tried.

### Environment data
Android version: 8.0.0

Device model: Samsung Galaxy S7

Stock or customized system: stock

Nextcloud app version: 3.14.1

Nextcloud server version: 20.0.4

Reverse proxy: Apache

#### Web server error log
None

#### Nextcloud log (data/nextcloud.log)
None

**Comment by AndyScherzinger** [comment] 2021-01-05 18:30
Also happening for other icons, running against Nc20 latest and with Android client master @tobiasKaminsky

**Comment by tobiasKaminsky** [comment] 2021-01-06 09:54
https://github.com/nextcloud/server/blob/master/apps/files/img/add-color.svg
https://github.com/nextcloud/server/blob/master/apps/files/img/change.svg

both svg have 
```
viewBox="0 0 16 16" width="16" height="16"
```

so I fail to find the difference.

@nextcloud/designers can you help me why this might be rendered differently?
@nickvergessen as this svg thingie causes lots of trouble, is there a way to get png instead of svg?

**Comment by nickvergessen** [comment] 2021-01-07 09:21
> as this svg thingie causes lots of trouble, is there a way to get png instead of svg?

https://github.com/nextcloud/activity/blob/d3bc6cf1af844ef482c3a96f06e4075a38a119de/lib/Controller/APIv2Controller.php#L260

**Comment by szaimen** [comment] 2021-07-18 14:38
This problem is still reproducible on v3.17.0 RC2

**Comment by Remsboys** [comment] 2022-03-13 19:21
@nickvergessen @tobiasKaminsky 
Any updates on this? It's still an issue in NC Android v3.19.1
Tried it with the current Android release from GitHub and a demo account from try.nextcloud.com
![grafik](https://user-images.githubusercontent.com/71826922/158075488-aa57ee28-495e-4cb4-b0a9-ea4ef83bbe6d.png)

**Comment by tobiasKaminsky** [comment] 2022-03-15 07:19
> https://github.com/nextcloud/server/blob/master/apps/files/img/add-color.svg https://github.com/nextcloud/server/blob/master/apps/files/img/change.svg
> 
> both svg have
> 
> ```
> viewBox="0 0 16 16" width="16" height="16"
> ```
> 
> so I fail to find the difference.
> 
> @nextcloud/designers can you help me why this might be rendered differently?

This is caused by svg provided by server.



> > as this svg thingie causes lots of trouble, is there a way to get png instead of svg?
> 
> https://github.com/nextcloud/activity/blob/d3bc6cf1af844ef482c3a96f06e4075a38a119de/lib/Controller/APIv2Controller.php#L260

This would also be a valid bugfix, but requires a change on Android side too.

**Comment by Remsboys** [comment] 2022-10-20 16:37
@strassan The new update for Android (3.22.0) fixed the issue. You can therefore close it.

**Comment by szaimen** [comment] 2022-10-20 16:48
Can confirm

**Closed by szaimen** 2022-10-20 16:48 UTC
Labels: bug, approved, release candidate
