### ISSUE TITLE
Android app crash when syncing folder

### ISSUE THREAD

**Issue by riesinger** [nextcloud/android#6028] opened 2020-05-08 13:02 UTC
### Steps to reproduce
1. Open Android app
2. Click sync on one foldee
3. Crash

```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start service com.owncloud.android.services.OperationsService@7df5cce with Intent { act=SYNC_FOLDER cmp=com.nextcloud.client/com.owncloud.android.services.OperationsService (has extras) }: java.lang.ClassCastException: com.nextcloud.client.account.RegisteredUser cannot be cast to android.accounts.Account
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4235)
	at android.app.ActivityThread.access$2200(ActivityThread.java:231)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1997)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7695)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.ClassCastException: com.nextcloud.client.account.RegisteredUser cannot be cast to android.accounts.Account
	at com.owncloud.android.services.OperationsService.onStartCommand(OperationsService.java:196)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4217)
	... 8 more

```

### Expected behaviour
- Folder should sync, this has worked perfectly fine before

### Actual behaviour
- App crashes with above log

### Can you reproduce this problem on https://try.nextcloud.com?

Untested, I will do so on-demand

### Environment data

Android version: 10 (SDK 29)
Brand: OnePlus
Device: OnePlus7Pro
Model: GM1913
Product: OnePlus7Pro_EEA

Stock or customized system: Stock

Nextcloud app version: 
ID: com.nextcloud.client
Version: 30120051
Build flavor: gplay

Nextcloud server version: 18.0.3 (Docker, Apache version) 

Reverse proxy: Traefik -> Apache

**Comment by ezaquarii** [comment] 2020-05-08 14:06
Duplicate of https://github.com/nextcloud/android/issues/6020.
Fix pending: https://github.com/nextcloud/android/pull/6023

**Closed by ezaquarii** 2020-05-08 14:06 UTC
Labels: bug
