### ISSUE TITLE
Add 'force sync' button

### ISSUE THREAD

**Issue by codereptile** [nextcloud/android#9978] opened 2022-03-16 13:42 UTC
On the desktop client, there is a very helpful button 'Force sync now'. In my opinion this should be added to the mobile version too. I know that when you swipe down in 'Uploads', there is a force check. But it only checks for new files. I constantly add folders for sync and only about 10% start uploading existing files right away. For other 90% it just won't start and there is no way to find out why or force it too. In the end, some random actions may help, but not always. Please add a button that would check all auto upload folders and all existing files. This issue has been for several years with tens of issues on it, but I just don't understand why it wasn't fixed, since there way no explanation why it's impossible/hard to do, yet the public desire for such a feature is immense.

**Comment by cquick7** [comment] 2022-03-18 17:16
This feature is essential.  It would correct the problem with some photos not auto-uploading as well, where you can just force sync and add anything that was missed.  This, coupled with the fix where large file upload queues tend to crash the app.

Device: Oneplus 7t HD1905, Android 11, Oxygen OS 11.0.6.1.HD65AA

**Comment by TuRDMaN** [comment] 2022-08-16 01:38
Yes please! This is badly needed!

**Comment by oucil** [comment] 2023-08-28 15:59
Seriously didn't expect to find a feature request for something as straightforward as force sync. Such a pita not being able to snap an image of a doc with my phone that I need to attach to an email I'm working on on the PC because it hasn't synced.

**Comment by codereptile** [comment] 2023-08-29 08:08
> Seriously didn't expect to find a feature request for something as straightforward as force sync. Such a pita not being able to snap an image of a doc with my phone that I need to attach to an email I'm working on on the PC because it hasn't synced.

Let's hope this will be done at some point...

**Comment by w-vi** [comment] 2023-10-15 14:59
I am now manually picking server version for 465 files :facepalm:  I really need the force push and bulk resolution. I think this job will take me couple of days to resolve manually

**Comment by joshtrichards** [comment] 2023-12-11 20:17
Duplicate of #7019 

Let's consolidate tracking there.

**Closed by joshtrichards** 2023-12-11 20:17 UTC
Labels: enhancement, feature: auto upload, feature: sync and upload
