### ISSUE TITLE
Prompt if file already exists

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#3235] opened 2018-11-05 16:32 UTC
Via Google review:
> It seems that Android version still not support prompt for upload files if it is duplicated name, but just keep both with (1), (2),.....while iOS version did prompt to ask for decision.

@marinofaggiana how do you check this? Only if a file with the same filename exists?

**Comment by marinofaggiana** [comment] 2018-11-05 17:20
@tobiasKaminsky yes, if the the file already exists a prompt ask if rewrite or cancel

**Comment by tobiasKaminsky** [comment] 2018-11-06 06:04
And how do you check this? "Only" via file name?
On Android the problem is that some cameras start again with IMG_0001.jpg, so even if the filename is the same, it does not mean that it is the same file.

Do you also show previews for images?

**Comment by marinofaggiana** [comment] 2018-11-07 11:55
luckily in iOS the progressive number do not reset and I check only the filename :-) 

Toby I think that the show of preview is not a good idea...

**Comment by tobiasKaminsky** [comment] 2018-11-08 06:56
Checking only the filename might not be enough, if you have e.g. documents or other files.

This is what dolphin (kde file browser) is showing:
![image](https://user-images.githubusercontent.com/5836855/48182503-b257d680-e32b-11e8-9cf9-e0a32a269bf2.png)

Why do you think this is not a good idea?

**Comment by marinofaggiana** [comment] 2018-11-08 09:57
oh, I had understood only the new image, yes with together image is good, if the preview exists otherwise only the normal message.

**Comment by nickvergessen** [comment] 2019-03-18 13:27
Duplicate of #431

**Closed by nickvergessen** 2019-03-18 13:27 UTC
Labels: enhancement
