### ISSUE TITLE
Getting an error upon moving selected photos

### ISSUE THREAD

**Issue by Frameworms** [nextcloud/android#10449] opened 2022-06-28 10:09 UTC
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Failure from system
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1759)
    at android.app.Activity.startActivityForResult(Activity.java:4803)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:588)
    at android.app.Activity.startActivityForResult(Activity.java:4743)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onFileActionChosen(OCFileListFragment.java:1183)
    at com.owncloud.android.ui.fragment.OCFileListFragment$MultiChoiceModeListener.onActionItemClicked(OCFileListFragment.java:757)
    at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2747)
    at androidx.appcompat.view.SupportActionModeWrapper$CallbackWrapper.onActionItemClicked(SupportActionModeWrapper.java:172)
    at androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImpl.java:2709)
    at androidx.appcompat.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:140)
    at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
    at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
    at android.widget.AdapterView.performItemClick(AdapterView.java:321)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1234)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3234)
    at android.widget.AbsListView$3.run(AbsListView.java:4210)
    at android.os.Handler.handleCallback(Handler.java:907)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:216)
    at android.app.ActivityThread.main(ActivityThread.java:7625)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: Exception in thread "main" android.os.TransactionTooLargeException: data parcel size 2541732 bytes
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(Binder.java:1149)
    at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3732)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1753)
    at android.app.Activity.startActivityForResult(Activity.java:4803)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:588)
    at android.app.Activity.startActivityForResult(Activity.java:4743)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onFileActionChosen(OCFileListFragment.java:1183)
    at com.owncloud.android.ui.fragment.OCFileListFragment$MultiChoiceModeListener.onActionItemClicked(OCFileListFragment.java:757)
    at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2747)
    at androidx.appcompat.view.SupportActionModeWrapper$CallbackWrapper.onActionItemClicked(SupportActionModeWrapper.java:172)
    at androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImpl.java:2709)
    at androidx.appcompat.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:140)
    at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
    at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
    at android.widget.AdapterView.performItemClick(AdapterView.java:321)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1234)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3234)
    at android.widget.AbsListView$3.run(AbsListView.java:4210)
    at android.os.Handler.handleCallback(Handler.java:907)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:216)
    at android.app.ActivityThread.main(ActivityThread.java:7625)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `HUAWEI`
* Device: `HWYAL`
* Model: `YAL-L21`
* Id: `HUAWEIYAL-L61`
* Product: `YAL-L21H`

### Firmware
* SDK: `28`
* Release: `9`
* Incremental: `9.1.0.195C636`

**Comment by AlvaroBrey** [comment] 2022-06-28 10:23
Was this a very large amount of selected photos?

**Comment by Frameworms** [comment] 2022-06-28 16:41
> Was this a very large amount of selected photos?

I did move a large amount of photos that were took from my camera, but i'm getting this error for screenshot photos - maybe because of the quality? Some screenshots are "long" as I took it from my phone. Could this be the root cause?

**Comment by AlvaroBrey** [comment] 2022-07-04 16:38
Duplicate of #7978

**Closed by AlvaroBrey** 2022-07-04 16:38 UTC
Labels: bug
