### ISSUE TITLE
Crash report window just appeared

### ISSUE THREAD

**Issue by tryallthethings** [nextcloud/android#7034] opened 2020-09-30 17:18 UTC
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tryallthethings** [comment] 2020-09-30 17:21
Well, that's not very helpful. Nextcloud client crashed (client wasn't open - must've happened while doing a background task) on my Samsung Galaxy S7 and offered me to raise a GitHub ticket. But apparently none of the information is transferred to the ticket? Is there any way to retrieve the crash details?

**Comment by AndyScherzinger** [comment] 2020-09-30 20:22
Not at a later point in time, but if it happens again and the crash screen comes up again, die error log is auto copied to your clipboard so you can post it here 😀

**Comment by tobiasKaminsky** [comment] 2020-10-01 11:44
> auto copied to your clipboard so you can post it here grinning

It seems that this is just not mentioned…

**Comment by tryallthethings** [comment] 2020-10-02 20:25
The crash didn't appear again so far. It seems like Nextcloud client is using some kind of crash reporter. Couldn't it automatically post the error message into the ticket? From other app crashes on Android I'm used to pressing a button and it would open my Email-Client and send the information to the developers. I was expecting the same here.


> > auto copied to your clipboard so you can post it here grinning
> 
> It seems that this is just not mentioned…

I honestly didn't read the message and just pressed the button for the ticket.

**Comment by ezaquarii** [comment] 2020-10-03 12:13
I thought it just opens an email client with crash stack trace in body message. Isn't it?

**Comment by tryallthethings** [comment] 2020-10-03 17:32
************ CAUSE OF ERROR ************

android.database.SQLException: ERROR content://org.nextcloud/arbitrary_data
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:364)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:255)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:270)
	at android.content.ContentResolver.insert(ContentResolver.java:1545)
	at com.owncloud.android.datamodel.ArbitraryDataProvider.storeOrUpdateKeyValue(ArbitraryDataProvider.java:88)
	at com.owncloud.android.utils.PushUtils.pushRegistrationToServer(PushUtils.java:252)
	at com.owncloud.android.services.firebase.NCFirebaseMessagingService.onNewToken(NCFirebaseMessagingService.java:68)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:107)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: herolte
Model: SM-G930F
Id: R16NW
Product: heroltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G930FXXS7ETA8

**Comment by tryallthethings** [comment] 2020-10-03 17:37
Crash happened again - see comment above. 
And here's how the error reporting looks like. The popup message "Copied to clipboard" is visible for maybe 1 second. I see some room for improvement here :smile: 

![Screenshot_20201003-193113_Nextcloud](https://user-images.githubusercontent.com/11146296/94998104-c5bf5b00-05af-11eb-8a7c-7dfc378fb1b6.jpg)
![Screenshot_20201003-193125_GitHub](https://user-images.githubusercontent.com/11146296/94998105-c6f08800-05af-11eb-8a27-293ec858b8cb.jpg)

**Comment by mipla23** [comment] 2020-10-03 17:57
Just happend here:

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-DWCQwqoDlvVatcP9KDz2Aw==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-DWCQwqoDlvVatcP9KDz2Aw==/lib/arm64, /data/app/com.nextcloud.client-DWCQwqoDlvVatcP9KDz2Aw==/base.apk!/lib/arm64-v8a, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: d2x
Model: SM-N976B
Id: PPR1.180610.011
Product: d2xxx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: N976BXXU1ASHE

**Comment by tobiasKaminsky** [comment] 2020-10-16 05:06
> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;

This is fixed with next version.
Please re-open if it happens with 3.14 again.

**Closed by tobiasKaminsky** 2020-10-16 05:06 UTC
Labels: bug, needs info/discussion
