### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by nowshed-imran** [nextcloud/android#8979] opened 2021-09-15 05:38 UTC
### Steps to reproduce
1. Open app(Backend Qloud)
2. Go to the settings menu
3. 

### Expected behaviour
- I should see the menu without any error.

### Actual behaviour
- App Crash.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
8.1.0
Device model: 
Sm-j710fn
Stock or customized system:

Nextcloud app version:
3.17
Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Canvas: trying to draw too large(106328180bytes) bitmap.
	at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
	at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:1016)
	at android.widget.ImageView.onDraw(ImageView.java:1367)
	at android.view.View.draw(View.java:20483)
	at android.view.View.updateDisplayListIfDirty(View.java:19428)
	at android.view.View.draw(View.java:20206)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4459)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4245)
	at android.view.View.draw(View.java:20486)
	at android.view.View.updateDisplayListIfDirty(View.java:19428)
	at android.view.View.draw(View.java:20206)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4459)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4245)
	at android.view.View.updateDisplayListIfDirty(View.java:19419)
	at android.view.View.draw(View.java:20206)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4459)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4245)
	at android.view.View.draw(View.java:20486)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
	at android.view.View.updateDisplayListIfDirty(View.java:19428)
	at android.view.View.draw(View.java:20206)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4459)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4245)
	at android.view.View.draw(View.java:20486)
	at com.google.android.material.internal.ScrimInsetsFrameLayout.draw(ScrimInsetsFrameLayout.java:109)
	at android.view.View.updateDisplayListIfDirty(View.java:19428)
	at android.view.View.draw(View.java:20206)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4459)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4245)
	at android.view.View.draw(View.java:20486)
	at android.view.View.updateDisplayListIfDirty(View.java:19428)
	at android.view.View.draw(View.java:20206)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4459)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4245)
	at android.view.View.updateDisplayListIfDirty(View.java:19419)
	at android.view.View.draw(View.java:20206)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4459)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4245)
	at android.view.View.updateDisplayListIfDirty(View.java:19419)
	at android.view.View.draw(View.java:20206)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4459)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4245)
	at android.view.View.updateDisplayListIfDirty(View.java:19419)
	at android.view.View.draw(View.java:20206)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4459)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4245)
	at android.view.View.updateDisplayListIfDirty(View.java:19419)
	at android.view.View.draw(View.java:20206)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4459)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4245)
	at android.view.View.draw(View.java:20486)
	at com.android.internal.policy.DecorView.draw(DecorView.java:990)
	at android.view.View.updateDisplayListIfDirty(View.java:19428)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:719)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:725)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:833)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3632)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3419)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2954)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1863)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8072)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7025)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: j7xelte
Model: SM-J710F
Id: M1AJQ
Product: j7xeltexx

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: J710FXXS6CTJ1

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2021-09-15 07:11
Duplicate of #8862

**Closed by AlvaroBrey** 2021-09-15 07:11 UTC
Labels: bug
