### ISSUE TITLE
NC app crashes after enabling automatic upload for big folder

### ISSUE THREAD

**Issue by MVerdin** [nextcloud/android#11032] opened 2022-11-14 19:26 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Enable automatic upload for a folder containing more than 1000 high res (16 MP) photos, enabling the option to "Upload existing items".
2. Wait for uploads to show in "Uploads" screen.
3. Wait 5-10 minutes for error to show up

### Expected behaviour

Photos should be uploaded without the app crashing 

### Actual behaviour

App crashes after 5-10 minutes of starting folder upload

### Android version

13

### Device brand and model

Pixel 5

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.3

### Nextcloud server version

25.0.1

### Using a reverse proxy?

No

### Additional information

Error message shown in app:
### Cause of error
```java
Exception in thread "WM.task-4" java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 4702680 free bytes and 4592KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.addConditionWaiter(AbstractQueuedSynchronizer.java:1896)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2077)
    at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
    at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220390`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `redfin`
* Model: `Pixel 5`
* Id: `TP1A.221105.002`
* Product: `redfin`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `9080065`

**Comment by AlvaroBrey** [comment] 2022-11-15 09:19
Did you have the "Uploads" screen open when this crash happened?

**Comment by AlvaroBrey** [comment] 2022-11-23 12:14
Duplicate of #10653

**Closed by AlvaroBrey** 2022-11-23 12:14 UTC
Labels: bug, needs info
