### ISSUE TITLE
Crash while moving multiple picture to folder

### ISSUE THREAD

**Issue by Miloune** [nextcloud/android#11184] opened 2022-12-19 16:54 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Select multiple files
Choose "Move" action
Select a folder
Crash

### Expected behaviour

Move images to folder

### Actual behaviour

The application display a stack trace

### Android version

12

### Device brand and model

Huawei p30 pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.23.0

### Nextcloud server version

24.0.6

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "Thread-69" java.lang.IllegalStateException: Couldn't read row 916, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetString(Native Method)
    at android.database.CursorWindow.getString(CursorWindow.java:469)
    at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
    at android.database.CursorWrapper.getString(CursorWrapper.java:141)
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:968)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:895)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:189)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:240)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:929)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230090`
* Build flavor: `gplay`

### Device information
* Brand: `HUAWEI`
* Device: `HWVOG`
* Model: `VOG-L29`
* Id: `HUAWEIVOG-L29`
* Product: `VOG-L29EEA`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `10.1.0.150C431`

**Comment by AlvaroBrey** [comment] 2022-12-20 09:31
Duplicate of #9948

**Closed by AlvaroBrey** 2022-12-20 09:31 UTC
Labels: bug
