### ISSUE TITLE
Nextcloud crashed on logging in

### ISSUE THREAD

**Issue by Falkgeist** [nextcloud/android#8559] opened 2021-06-10 18:02 UTC
### Steps to reproduce
1. I logged out of a previously added user
2. I logged in and was asked to grant access
3. After granting access the error message below appears
4. After opening the app again (not force stopped), I can see my files as expected. 

### Expected behaviour
I see my files (directly)

### Actual behaviour
I see the error, before seeing my files (after closing and reopening the app)

### Can you reproduce this problem on https://try.nextcloud.com?
Not checked

### Environment data
Android version: 11

Device model: SM-A705FN

Stock or customized system: Stock

Nextcloud app version: 30160190

Nextcloud server version: 21

Reverse proxy: don't know

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a70q
Model: SM-A705FN
Id: xxxx.xxxxxx.xxx
Product: a70qeea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: A705FNXXS5DUD1

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Falkgeist** [comment] 2021-06-10 18:08
It might be, that this is an issue with my server, but since I just updated to 21 and solved as many issues (had no critical ones) as possible on the server, I am getting the feeling, that the app is not working very stable for me. Also, uploads and sync is weird sometimes, either taking very long or showing a 100% sync as notification, that is almost to get rid of (only when force stopping).

**Comment by AndyScherzinger** [comment] 2021-06-11 20:57
Duplicate of #8370

**Closed by AndyScherzinger** 2021-06-11 20:57 UTC
Labels: bug

**Comment by Falkgeist** [comment] 2021-06-11 21:03
I'm sorry, I don't see how to fix this problem for me from reading the other issue. can you please help me to figure out what to do to get this resolved? I am not so much bugged about the crash itself, but more about the failing uploads and the repeated appearance of the persistent notification.

**Comment by AndyScherzinger** [comment] 2021-06-11 21:07
You can't workaround it since the ,matter isn't fixed but this is a "duplicate report of the same issue", so best follow: https://github.com/nextcloud/android-library/pull/638 and wait for it to be merged/closed and assigned to a (future) release.

**Comment by Falkgeist** [comment] 2021-06-11 21:12
ah, sorry just skimmed for a solution, if only a workaround, must've skipped the "open" blindly as well. my bad, thanks!
