### ISSUE TITLE
#Gmail.com

### ISSUE THREAD

**Issue by sagorkhalifa247** [nextcloud/android#14155] opened 2024-12-10 15:03 UTC
### Cause of error
```java
Exception in thread "Thread-3" java.lang.IllegalArgumentException: Trying to execute a sync operation with a storage manager for an anonymous account
    at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:49)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$fetchExternalLinks$9(DrawerActivity.java:1231)
    at com.owncloud.android.ui.activity.DrawerActivity.$r8$lambda$oHM2j1MZkviAIdyIFWoI2kSeF9c(Unknown Source:0)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `vivo`
* Device: `2111`
* Model: `V2111`
* Id: `SP1A.210812.003_NONFC`
* Product: `2111N`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `compiler10220125`

- [ ]

**Comment by joshtrichards** [comment] 2024-12-28 14:57
Duplicate of #13323

**Closed by joshtrichards** 2024-12-28 14:57 UTC
Labels: 0. Needs triage
