### ISSUE TITLE
Nextcloud does not detect existing DAVx5 account

### ISSUE THREAD

**Issue by Solarer** [nextcloud/android#9416] opened 2021-12-01 10:25 UTC
### Steps to reproduce
1. Install DAVx5 and connect to nextcloud for sync. 
2. Install Nextcloud and go to settings. 
3. I can still click on "configure DAVx5 for your account" even though it is already. 

### Expected behaviour
- Nextcloud should recognize that DAVx5 has already been configured for this account and display this visually. 

### Actual behaviour
- I can reconfigure my connection (which does not work because my email address is already in use for another DAVx5 account). 
- Even after deleting the existing DAVx5 account and following the steps of the nextcloud wizard to create a new configuration via nextcloud the visuals of the button does not update and allows me to create another configuration yet again. 

### Can you reproduce this problem on https://try.nextcloud.com?
- Not yet, will do. 

### Environment data
Android version: Lineage OS 17.1 build 21th November 2021.

Device model: SMA510-F

Stock or customized system: Lineage

Nextcloud app version: 3.18.0

Nextcloud server version: 22.2.3 fpm Docker

Reverse proxy: nginx

**Comment by AlvaroBrey** [comment] 2021-12-01 10:46
Likely a duplicate of #9339, because DAVx5 integration is fundamentally broken in 3.18.0. Let's see if 3.18.1 fixes this when released.

**Comment by AlvaroBrey** [comment] 2022-08-26 08:41
Should be fixed by #9342

**Closed by AlvaroBrey** 2022-08-26 08:41 UTC
Labels: bug
