### ISSUE TITLE
Upload does not respect wlan cost settings

### ISSUE THREAD

**Issue by meimi039** [nextcloud/android#8875] opened 2021-08-20 16:38 UTC
When configuring an upload folder, you can set it to "upload on free wifi only" (thats how I would translate it :-) ). 
If you are connected to a wlan that is not free, the folder gets uploaded anyway.

**Comment by AndyScherzinger** [comment] 2021-08-21 07:49
@meimi039 did you mark the wifi in the OS settings as metered (non-free)?

**Comment by meimi039** [comment] 2021-08-21 16:47
Hi Andy!

Thanks for the quick reply.
Yes, the wifi has been marked as metered. That was the reason, why I opened the ticked.

Greetings

Michael Meister

21.08.2021 09:49:52 Andy Scherzinger ***@***.***>:

**Comment by codeswhite** [comment] 2021-08-21 21:26
Confirmed on latest (v3.17.0)
Set WiFi as metered, choose auto-upload only on unmetered.
Still uploads.

**Comment by AndyScherzinger** [comment] 2021-08-22 11:44
@codeswhite by "still uploads" do you mean you started the uploads _before_ you changed the settings?

**Comment by codeswhite** [comment] 2021-08-22 11:56
No.
From idle connection, performing modification to a file on client (in directory marked as "upload over unmetered only")
Supposed to "do nothing" when connected to metered wifi.
Actual behavior is that the modification triggers a new upload process.

**Comment by meimi039** [comment] 2021-08-22 13:20
Hi Andy!

Sorry for being so unprezise. I am on vacation currently.
I set up the folder to upload on free wifi and power connected.
I was connected to my other phone via metered wifi. As soon as I plugged in power, I noticed from the statusbar that nextcloud was uploading all the new videos, which was quite an amount of data :-)
I could reproduce this behaviour on my other phones that I have currently with me, so I decided to inform the developers.
So again: Thank you for having a look at it.

Greetings

Michael

22.08.2021 13:44:54 Andy Scherzinger ***@***.***>:

**Comment by AndyScherzinger** [comment] 2021-08-22 13:55
Thanks for the details @codeswhite and @meimi039.

Looping in @tobiasKaminsky, didn't find the time yet to try to reproduce this.

**Comment by felix-walter** [comment] 2021-11-26 09:58
I can confirm this issue. I run a nightly backup job (~400M) that places files in a directory which gets automatically uploaded. Even if the used wifi is set to metered the uploads are taking place and I have to manually turn off the auto-upload setting as long as I am using metered wifi. If you need any support in reproducing the issue I am happy to help.

**Comment by nottheend** [comment] 2023-01-07 19:08
I can confirm this bug as valid in v3.23.1

**Comment by AlvaroBrey** [comment] 2023-01-09 16:00
Closing as duplicate of #6851

**Closed by AlvaroBrey** 2023-01-09 16:00 UTC
Labels: bug
