### ISSUE TITLE
Nextcloud App crashing since several days

### ISSUE THREAD

**Issue by FlavML** [nextcloud/android#8420] opened 2021-05-16 11:58 UTC
This is my first bug report. I did my best to follow the template...still some information I don't know. Let me know what else is important and/or relevant: I will look for it. I want and like to learn. I am happy to start a bit on GitHub :+)
Wishing all a nice week!
F

### Steps to reproduce
1. Starting app Nextcloud
2. Starting navigating in folders, looking for a file
3. Nextcloud crashes

### Expected behaviour
- Nextcloud should not crash while navigating through files and folders. This behaviour is new, since several days.

### Actual behaviour
- Nextcloud crashes. I wonder what happened to my setup to come to this current problem? I can't think of the reason.

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:764)

### Can you reproduce this problem on https://try.nextcloud.com?

This is too advanced for me today. I will try this perhaps soon.

[- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum]

"Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password"
Looks like a password issue? But the app doesn't let me enough time to access my Nextcloud App Settings...

### Environment data
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: SHIFT
Device: SHIFT6m
Model: SHIFT6m
Id: O00623
Product: SHIFT6m_EEA

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 1592466613

Android version: 8.0.0

Stock or customized system: shift6m

Nextcloud server version: I don't know

Reverse proxy: I don't know

#### Web server error log
```
Insert your webserver log here : I don't know
```

#### Nextcloud log (data/nextcloud.log)
```
I don't find it. In shift6m/ file search for "nextcloud.log" returns "no matches"
```

**Comment by AndyScherzinger** [comment] 2021-05-17 09:37
Duplicate of #8370

**Comment by AndyScherzinger** [comment] 2021-05-17 09:37
Thanks for the report @FlavML - this has been reported already thus closing in favor for the other issue

**Closed by AndyScherzinger** 2021-05-17 09:37 UTC
Labels: bug
