### ISSUE TITLE
little Crush 

### ISSUE THREAD

**Issue by Zeroocooloverride** [nextcloud/android#13861] opened 2024-10-23 01:48 UTC
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 4733896 bytes
    at android.app.ActivityClient.finishActivity(ActivityClient.java:181)
    at android.app.Activity.finish(Activity.java:6904)
    at android.app.Activity.finish(Activity.java:6921)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onConfirmation(UploadFilesActivity.java:662)
    at com.owncloud.android.ui.dialog.ConfirmationDialogFragment.onCreateDialog$lambda$0(ConfirmationDialogFragment.kt:84)
    at com.owncloud.android.ui.dialog.ConfirmationDialogFragment.$r8$lambda$muH3dEu1HilHA9TTFMeZwUDJ3mM(Unknown Source:0)
    at com.owncloud.android.ui.dialog.ConfirmationDialogFragment$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
    at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:211)
    at android.os.Looper.loop(Looper.java:300)
    at android.app.ActivityThread.main(ActivityThread.java:8503)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: Exception in thread "main" android.os.TransactionTooLargeException: data parcel size 4733896 bytes
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(BinderProxy.java:643)
    at android.app.IActivityClientController$Stub$Proxy.finishActivity(IActivityClientController.java:1409)
    at android.app.ActivityClient.finishActivity(ActivityClient.java:178)
    at android.app.Activity.finish(Activity.java:6904)
    at android.app.Activity.finish(Activity.java:6921)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onConfirmation(UploadFilesActivity.java:662)
    at com.owncloud.android.ui.dialog.ConfirmationDialogFragment.onCreateDialog$lambda$0(ConfirmationDialogFragment.kt:84)
    at com.owncloud.android.ui.dialog.ConfirmationDialogFragment.$r8$lambda$muH3dEu1HilHA9TTFMeZwUDJ3mM(Unknown Source:0)
    at com.owncloud.android.ui.dialog.ConfirmationDialogFragment$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
    at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:211)
    at android.os.Looper.loop(Looper.java:300)
    at android.app.ActivityThread.main(ActivityThread.java:8503)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `Redmi`
* Device: `veux`
* Model: `2201116SG`
* Id: `TKQ1.221114.001`
* Product: `veux_eea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `V816.0.4.0.TKCEUXM`

**Comment by joshtrichards** [comment] 2024-10-26 17:38
Duplicate of #10626

**Closed by joshtrichards** 2024-10-26 17:38 UTC
Labels: bug, performance: TTLE, stable-3.29
