### ISSUE TITLE
Calendar & contact synchronization leads to the Playstore

### ISSUE THREAD

**Issue by mjolnier05** [nextcloud/android#9404] opened 2021-11-30 20:43 UTC
### Steps to reproduce
1. Open Nextcloud App
2. Go to settings
3. Hit Calendar & Contacts synchronisation

### Expected behaviour
- when DAVx5 is already installed, DAVx5 will be opened
- when DAVx5 is **NOT** installed, Playstore will be opened

### Actual behaviour
- leads to the Playstore in any case

#### 1st Phone
Android version: Android 11
Device model: Samsung Galaxy Note 4 (SM-N910F)
Stock or customized system: Lineageos 18.1
Nextcloud app version: 3.18.0
Nextcloud server version: 22.2.3
Reverse proxy: nginx

#### 2nd Phone
Android version: Android 11
Device model: Samsung Galaxy Note 10+ (SM-N975F)
Stock or customized system: Samsung Stock Rom
Nextcloud app version: 3.18.0
Nextcloud server version: 22.2.3
Reverse proxy: nginx

**Comment by iGadget** [comment] 2021-11-30 23:18
Can't reproduce this on my Fairphone 3+ / Android 10 stock.
- First time it asks me to install DAVx5 (I chose to install it from F-Droid)
- Second time it took me right to the account setup via DAVx5.

**Comment by AlvaroBrey** [comment] 2021-12-01 09:13
Duplicate of #9339

**Comment by AlvaroBrey** [comment] 2021-12-01 09:13
This will be fixed in 3.18.1

**Closed by AlvaroBrey** 2021-12-01 09:13 UTC
Labels: bug
