### ISSUE TITLE
crash new setting with QR Code

### ISSUE THREAD

**Issue by vandman** [nextcloud/android#14237] opened 2024-12-24 23:58 UTC
### Cause of error
```java
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 9
    at java.lang.String.checkBoundsBeginEnd(String.java:4466)
    at java.lang.String.substring(String.java:2517)
    at com.nextcloud.client.account.UserAccountManagerImpl.exists(UserAccountManagerImpl.java:121)
    at com.nextcloud.client.mixins.SessionMixin.onRestart(SessionMixin.kt:100)
    at com.nextcloud.client.mixins.MixinRegistry.onRestart(MixinRegistry.kt:48)
    at com.owncloud.android.ui.activity.BaseActivity.onRestart(BaseActivity.java:137)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onRestart(FileDisplayActivity.java:2448)
    at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1592)
    at android.app.Activity.performRestart(Activity.java:9140)
    at android.app.ActivityThread.performRestartActivity(ActivityThread.java:6062)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:250)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:187)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2693)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:9063)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20241218`
* Build flavor: `versionDev`

### Device information
* Brand: `samsung`
* Device: `b0q`
* Model: `SM-S908N`
* Id: `UP1A.231005.007`
* Product: `b0qksx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S908NKSS6EXL1`

**Comment by joshtrichards** [comment] 2024-12-28 15:05
Duplicate of #13828

**Closed by joshtrichards** 2024-12-28 15:05 UTC
