### ISSUE TITLE
????

### ISSUE THREAD

**Issue by Thomas0862** [nextcloud/android#13880] opened 2024-10-25 21:20 UTC
### Cause of error
```java
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property currentAccount has not been initialized
    at com.nextcloud.client.mixins.SessionMixin.getCurrentAccount(SessionMixin.kt:32)
    at com.nextcloud.client.mixins.SessionMixin.onRestart(SessionMixin.kt:100)
    at com.nextcloud.client.mixins.MixinRegistry.onRestart(MixinRegistry.kt:48)
    at com.owncloud.android.ui.activity.BaseActivity.onRestart(BaseActivity.java:118)
    at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1592)
    at android.app.Activity.performRestart(Activity.java:8767)
    at android.app.ActivityThread.performRestartActivity(ActivityThread.java:5559)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:250)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2535)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8376)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:640)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `Teclast`
* Device: `P50_EEA`
* Model: `P50`
* Id: `UP1A.231005.007`
* Product: `P50_EEA`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `20240523`

**Comment by joshtrichards** [comment] 2024-10-25 22:57
Duplicate of #13241

**Closed by joshtrichards** 2024-10-25 22:57 UTC
