### ISSUE TITLE
Nextcloud Android Client crash on accessing file details

### ISSUE THREAD

**Issue by muchahagrande** [nextcloud/android#5391] opened 2020-02-03 13:44 UTC
### Steps to reproduce
1. Open Nextcloud
2. Select any file or folder detail
3. The app crash

### Expected behaviour
- File detail view should be seen

### Actual behaviour
- The app crashs offering debug info

### Environment data
Android version: 6.0.1

Device model: Samsung S5 Neo

Stock or customized system: Stock

Nextcloud app version: 3.10.0

Nextcloud server version: Nextcloud Hub 18

#### Web server error log
```
No error on web server error log
```

#### Nextcloud log (data/nextcloud.log)
```
******** CAUSE OF ERROR ********

javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
 at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@20104018@20.1.04 (040308-288960190):27)
 at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
 at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
 at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
 at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
 at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
 at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
 at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
 at okhttp3.RealCall.execute(RealCall.java:93)
 at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:126)
 at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:67)
 at com.owncloud.android.lib.resources.activities.GetActivitiesRemoteOperation.run(GetActivitiesRemoteOperation.java:131)
 at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:63)
 at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$5$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:331)
 at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$N7POe6TZvoGcuV2qP-niPxY_7t4.run(lambda)
 at java.lang.Thread.run(Thread.java:818)
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
 at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:324)
 at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:225)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.google.android.gms.org.conscrypt.Platform.checkTrusted(:com.google.android.gms@20104018@20.1.04 (040308-288960190):2)
 at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(:com.google.android.gms@20104018@20.1.04 (040308-288960190):3)
 at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(:com.google.android.gms@20104018@20.1.04 (040308-288960190):7)
 at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
 at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@20104018@20.1.04 (040308-288960190):6)
 at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@20104018@20.1.04 (040308-288960190):14)
 ... 26 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
 ... 35 more

******** APP INFORMATION ********
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

******** DEVICE INFORMATION ********
Brand: samsung
Device: s5neolte
Model: SM-G903M
Id: MMB29K
Product: s5neolteub

******** FIRMWARE ********
SDK: 23
Release: 6.0.1
Incremental: G903MUBS1BSB1
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ezaquarii** [comment] 2020-02-03 15:46
This looks like a genuine network error. It looks like we assume that the network op always succeed and there no error path handler.

@tobiasKaminsky I'd accept this - probably fairly easy to fix.

**Comment by muchahagrande** [comment] 2020-02-03 15:56
I'm also getting "IO error" while accessing activities list. But no error log.

**Comment by muchahagrande** [comment] 2020-02-03 16:49
UPDATE:
The problem seem to happen only with self signed certificates.

In the meantime I set up Let's Encrypt and now the error is nos happening.

Also, the IO error mentioned later, does'n happen anymore.

**Comment by AndyScherzinger** [comment] 2020-02-03 17:22
Duplicate of #5235 (ships with 3.10.1)

**Closed by AndyScherzinger** 2020-02-03 17:22 UTC
Labels: bug
