### ISSUE TITLE
crash when opening markdown file details

### ISSUE THREAD

**Issue by atsag** [nextcloud/android#5171] opened 2020-01-13 07:23 UTC
### Steps to reproduce
1. Visit a markdown file and open it
2. Open the details field from the available options on the upper right

### Expected behaviour
- View file details
### Actual behaviour
- Nextcloud crashes
### Environment data
Android version: 7.1.1

Device model: J5 2016

Stock or customized system: Stock

Nextcloud app version:

Nextcloud server version: 15

### Logs

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at com.owncloud.android.utils.ThemeUtils.primaryColor(ThemeUtils.java:139)
	at com.owncloud.android.utils.ThemeUtils.primaryColor(ThemeUtils.java:125)
	at com.owncloud.android.ui.preview.PreviewTextFragment.getRenderedMarkdownText(PreviewTextFragment.java:284)
	at com.owncloud.android.ui.preview.PreviewTextFragment.setText(PreviewTextFragment.java:562)
	at com.owncloud.android.ui.preview.PreviewTextFragment.lambda$performSearch$0$PreviewTextFragment(PreviewTextFragment.java:270)
	at com.owncloud.android.ui.preview.-$$Lambda$PreviewTextFragment$8cnNMZfHrJC_BSC1jdHMw1eFOds.run(lambda)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: j5xnlte
Model: SM-J510FN
Id: NMF26X
Product: j5xnltexx

************ FIRMWARE ************
SDK: 25
Release: 7.1.1
Incremental: J510FNXXS3BSH2

**Comment by AndyScherzinger** [comment] 2020-01-13 07:29
it is, it's a duplicate of #4836 - thus closing in favor

**Closed by AndyScherzinger** 2020-01-13 07:29 UTC
Labels: bug
