### ISSUE TITLE
Crash during video playback streaming 

### ISSUE THREAD

**Issue by bakerd89** [nextcloud/android#7406] opened 2020-11-20 19:07 UTC
### Steps to reproduce
1. Play video and touch or rotate screen
2. Attempt to use "stream with..." option in menu before playing video
3. 

### Expected behaviour
- Tell us what should happen

Should play video and not crash

### Actual behaviour
- Tell us what happens
Black screen or crash screen with debug log see below:
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{1f5c3a8 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1855)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6986)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: starqltesq
Model: SM-G960U
Id: PPR1.180610.011
Product: starqltesq

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G960USQS7CSI5

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-11-23 09:08
Duplicate of #6905

**Closed by AndyScherzinger** 2020-11-23 09:08 UTC
Labels: bug

**Comment by bakerd89** [comment] 2020-11-23 14:50
Thanks, sorry for the duplicate post.

**Comment by AndyScherzinger** [comment] 2020-11-23 16:17
No worries 3.14.1 RC1 has been released to gplay containing a fix
