### ISSUE TITLE
App frequently hangs upon syncing and occasionally crashes at exit

### ISSUE THREAD

**Issue by omegasupreme3** [nextcloud/android#3431] opened 2019-01-08 20:36 UTC
### Actual behaviour
The app frequently hangs when synchronising files/folders. The system shows a dialog with a question to either close the app or wait (I guess for it to become responsive again?). If I select "wait" the app is responsive and I can interact with it as expected. However due to it hanging often I have got situations where files were partially synchronised. At first it seems ok (showing green icons), but restarting the app shows red icons with an X for the files that were not synchronised correctly. This makes it highly unreliable.

Additionally the app occasionally crashes when I exit it. I don't know what the consequences are.

Note 1: that it doesn't matter which files or folders are synced.
Note 2: resyncing the files/folders that were not done correctly before solves it everytime.

### Expected behaviour
The app should synchronise files without the behavior I described above. On my Nexus 5 (Google Android 6.0) it works flawless for years now.
 
### Steps to reproduce
1. Start the app
2. Synchronise a file or folder

### Environment data
Android version: 8.1.0 (stock)

Device model: Samsung Galaxy Tab S4 (stock, up-to-date and non-rooted)

Stock or customized system: Stock

Nextcloud app version: 3.4.1

Nextcloud server version: 15.0

#### Web server error log
```
Not yet available.
```

#### Nextcloud log (data/nextcloud.log)
```
Not yet available.
```

**Comment by omegasupreme3** [comment] 2019-01-09 10:55
In case it is helpful, this is the logcat from my tablet. You can clearly see messages about the application not being responsive and there is also a possible reason for this you can see almost at the bottom: 'Context.startForegroundService() did not then call Service.startForeground()'.

```
01-09 09:49:16.731   729   729 I SurfaceFlinger:      Device | 0x77a3e3f380 | 0002 | RGBA_8888 |   0.0    0.0 2560.0 1600.0 |    0    0 2560 1600 | com.nextcloud.client/com.owncloud.an[...]ctivity.FileDisplayActivity[11003]#0
01-09 09:49:18.359  2891  2972 D ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = com.nextcloud.client,userId = 0
01-09 09:49:18.359  2891  2972 D ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = com.nextcloud.client,userId = 0
01-09 09:49:18.363  3458  3458 D StatusBar: addNotification key=0|com.nextcloud.client|412|null|10166 fullscreen:false
01-09 09:49:18.369  2891  4197 D ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = com.nextcloud.client,userId = 0
01-09 09:49:18.369  2891  4197 D ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = com.nextcloud.client,userId = 0
01-09 09:49:18.377  3458  3458 D StatusBar: addNotification key=0|com.nextcloud.client|2131886321|null|10166 fullscreen:false
01-09 09:49:18.421   729   729 I SurfaceFlinger:      Device | 0x77a3e3f380 | 0002 | RGBA_8888 |   0.0    0.0 2560.0 1600.0 |    0    0 2560 1600 | com.nextcloud.client/com.owncloud.an[...]ctivity.FileDisplayActivity[11003]#0
01-09 09:49:18.571  2891  3469 D ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = com.nextcloud.client,userId = 0
01-09 09:49:18.572  2891  3469 E NotificationService: Package enqueue rate is 5.68561. Shedding 0|com.nextcloud.client|2131886321|null|10166. package=com.nextcloud.client
01-09 09:49:18.575  2891  6373 D ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = com.nextcloud.client,userId = 0
01-09 09:49:18.994  2891  6914 D ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = com.nextcloud.client,userId = 0
01-09 09:49:18.995  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2508 RxPkts=7478 TxBytes=431214 RxBytes=9777199 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=84356 rxBytes=8936751
01-09 09:49:18.998  2891  6914 D ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = com.nextcloud.client,userId = 0
01-09 09:49:19.052  2891  3469 D ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = com.nextcloud.client,userId = 0
01-09 09:49:19.054 11003 11046 I DownloadRemoteFileOperation: Download of /MyTestDir/blaupunkt-bluebot-xsmart-vcbbxs1.pdf to /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/tmp/johndoe@mydomain.com/MyTestDir/blaupunkt-bluebot-xsmart-vcbbxs1.pdf: Operation finished with HTTP status code 200 (success)
01-09 09:49:19.055 11003 11046 I DownloadFileOperation: Download of /MyTestDir/blaupunkt-bluebot-xsmart-vcbbxs1.pdf to /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/johndoe@mydomain.com/MyTestDir/blaupunkt-bluebot-xsmart-vcbbxs1.pdf: Operation finished with HTTP status code 200 (success)
01-09 09:49:19.097  2891  4197 D ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = com.nextcloud.client,userId = 0
01-09 09:49:19.097  2891  4197 D ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = com.nextcloud.client,userId = 0
01-09 09:49:19.132  3458  3458 D StatusBar: addNotification key=0|com.nextcloud.client|2131886323|null|10166 fullscreen:false
01-09 09:49:20.000  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2539 RxPkts=7606 TxBytes=443845 RxBytes=9953995 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=96987 rxBytes=9113547
01-09 09:49:21.005  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2560 RxPkts=7626 TxBytes=456923 RxBytes=9971075 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=110065 rxBytes=9130627
01-09 09:49:21.157  2891  4197 D SamsungAlarmManager: Cancel Alarm calling from uid:10166 pid :11003 / op:PendingIntent{ca868b4: PendingIntentRecord{2d39cdd com.nextcloud.client broadcastIntent}}
01-09 09:49:21.158  2891  3469 D SamsungAlarmManager: Cancel Alarm calling from uid:10166 pid :11003 / op:PendingIntent{dd35052: PendingIntentRecord{6de5f23 com.nextcloud.client broadcastIntent}}
01-09 09:49:21.161  2891  4197 D SamsungAlarmManager: Cancel Alarm calling from uid:10166 pid :11003 / op:PendingIntent{5bd5c20: PendingIntentRecord{2d39cdd com.nextcloud.client broadcastIntent}}
01-09 09:49:21.162  2891  4197 D SamsungAlarmManager: Cancel Alarm calling from uid:10166 pid :11003 / op:PendingIntent{47229d9: PendingIntentRecord{6de5f23 com.nextcloud.client broadcastIntent}}
01-09 09:49:22.013  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2577 RxPkts=7644 TxBytes=466586 RxBytes=9986912 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=119728 rxBytes=9146464
01-09 09:49:23.020  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2595 RxPkts=7662 TxBytes=477325 RxBytes=10002631 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=130467 rxBytes=9162183
01-09 09:49:24.025  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2618 RxPkts=7683 TxBytes=490821 RxBytes=10020258 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=143963 rxBytes=9179810
01-09 09:49:25.030  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2639 RxPkts=7701 TxBytes=500885 RxBytes=10034366 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=154027 rxBytes=9193918
01-09 09:49:26.035  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2662 RxPkts=7725 TxBytes=514513 RxBytes=10055472 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=167655 rxBytes=9215024
01-09 09:49:26.131  2891  2972 E ActivityManager: ANR in com.nextcloud.client
01-09 09:49:26.131  2891  2972 E ActivityManager: Reason: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{49224b2 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
01-09 09:49:26.131  2891  2972 E ActivityManager:   19% 11003/com.nextcloud.client: 12% user + 6.1% kernel / faults: 33093 minor 2 major
01-09 09:49:26.138  2891  2972 W ActivityManager: anr : com.nextcloud.client,0
01-09 09:49:26.198  2891  2973 V WindowManager: Relayout Window{e93d61a u0 Application Not Responding: com.nextcloud.client}: viewVisibility=0 req=1067x657 WM.LayoutParams{(0,0)(wrapxwrap) gr=#11 sim=#120 ty=2003 fl=#1820002 pfl=0x1000110 fmt=-3 wanim=0x10302ec vsysui=0x10 surfaceInsets=Rect(5, 5 - 5, 5) needsMenuKey=2 colorMode=0 naviIconColor=0}
01-09 09:49:26.201   729   729 I SurfaceFlinger: id=62 createSurf (1077x667),1 flag=4, Application Not Responding: com.nextcloud.client[2891]#0
01-09 09:49:26.318  2891  2973 D WindowManager: finishDrawingWindow: Window{e93d61a u0 Application Not Responding: com.nextcloud.client} mDrawState=DRAW_PENDING
01-09 09:49:26.324  2891  2973 D WindowManager: finishDrawingWindow: Window{e93d61a u0 Application Not Responding: com.nextcloud.client} mDrawState=HAS_DRAWN
01-09 09:49:26.370   729   729 I SurfaceFlinger:      Device | 0x77a1bd4080 | 0002 | RGBA_8888 |   0.0    0.0 2560.0 1600.0 |    0    0 2560 1600 | com.nextcloud.client/com.owncloud.an[...]ctivity.FileDisplayActivity[11003]#0
01-09 09:49:26.370   729   729 I SurfaceFlinger:      Device | 0x77a3e58080 | 0000 | RGBA_8888 |   0.0    0.0  667.0 1077.0 |  946  306 1559 1296 | Application Not Responding: com.nextcloud.client[2891]#0
01-09 09:49:26.386   729   729 I SurfaceFlinger:      Device | 0x77a1bd4080 | 0002 | RGBA_8888 |   0.0    0.0 2560.0 1600.0 |    0    0 2560 1600 | com.nextcloud.client/com.owncloud.an[...]ctivity.FileDisplayActivity[11003]#0
01-09 09:49:26.386   729   729 I SurfaceFlinger:      Device | 0x77a3e58080 | 0000 | RGBA_8888 |   0.0    0.0  667.0 1077.0 |  939  295 1566 1307 | Application Not Responding: com.nextcloud.client[2891]#0
01-09 09:49:26.500 11257 11269 W PkgUtils: p: com.nextcloud.client, u:0
01-09 09:49:27.041  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2682 RxPkts=7744 TxBytes=526983 RxBytes=10071770 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=180125 rxBytes=9231322
01-09 09:49:28.046  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2699 RxPkts=7762 TxBytes=536893 RxBytes=10087623 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=190035 rxBytes=9247175
01-09 09:49:29.051  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2719 RxPkts=7781 TxBytes=547811 RxBytes=10103334 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=200953 rxBytes=9262886
01-09 09:49:29.599  2891  2973 D InputEventReceiver: channel 'e93d61a Application Not Responding: com.nextcloud.client (client)' ~ Disposing input event receiver.
01-09 09:49:29.599  2891  2973 D InputEventReceiver: channel 'e93d61a Application Not Responding: com.nextcloud.client (client)' ~NativeInputEventReceiver.
01-09 09:49:29.849   729   729 I SurfaceFlinger:      Device | 0x77a3e3f380 | 0002 | RGBA_8888 |   0.0    0.0 2560.0 1600.0 |    0    0 2560 1600 | com.nextcloud.client/com.owncloud.an[...]ctivity.FileDisplayActivity[11003]#0
01-09 09:49:29.849   729   729 I SurfaceFlinger:      Device | 0x77a3e58000 | 0000 | RGBA_8888 |   0.0    0.0  667.0 1077.0 |  971  348 1533 1255 | Application Not Responding: com.nextcloud.client[2891]#0
01-09 09:49:29.898  2891  3190 I WindowManager: Destroying surface #c3fc1ce: Surface(name=Application Not Responding: com.nextcloud.client) called by com.android.server.wm.WindowStateAnimator.destroySurface:2617 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:1026 com.android.server.wm.WindowState.destroyOrSaveSurfaceUnchecked:3821 com.android.server.wm.RootWindowContainer.performSurfacePlacement:870 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:225 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:173 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:163 com.android.server.wm.WindowSurfacePlacer.lambda$-com_android_server_wm_WindowSurfacePlacer_6552:136 
01-09 09:49:29.898   729   774 I SurfaceFlinger: id=62 Removed Application Not Responding: com.nextcloud.client[2891]#0 (4/6)
01-09 09:49:29.898   729   774 I SurfaceFlinger: id=62 Removed Application Not Responding: com.nextcloud.client[2891]#0 (-2/6)
01-09 09:49:29.900   729   729 I SurfaceFlinger:      Device | 0x77a3e3f380 | 0002 | RGBA_8888 |   0.0    0.0 2560.0 1600.0 |    0    0 2560 1600 | com.nextcloud.client/com.owncloud.an[...]ctivity.FileDisplayActivity[11003]#0
01-09 09:49:29.913   729   729 I Layer   : id=62 onRemoved Application Not Responding: com.nextcloud.client[2891]#0 
01-09 09:49:30.058  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2751 RxPkts=7811 TxBytes=563992 RxBytes=10124605 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=217134 rxBytes=9284105
01-09 09:49:31.062  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2773 RxPkts=7830 TxBytes=573927 RxBytes=10140551 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=227069 rxBytes=9300051
01-09 09:49:32.068  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2787 RxPkts=7844 TxBytes=582408 RxBytes=10152906 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=235550 rxBytes=9312406
01-09 09:49:33.074  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2805 RxPkts=7862 TxBytes=593159 RxBytes=10168431 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=246301 rxBytes=9327931
01-09 09:49:34.084  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2824 RxPkts=7881 TxBytes=602909 RxBytes=10180865 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=256051 rxBytes=9340365
01-09 09:49:35.089  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2841 RxPkts=7905 TxBytes=612544 RxBytes=10196491 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=265686 rxBytes=9355991
01-09 09:49:36.182  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2857 RxPkts=7921 TxBytes=622277 RxBytes=10210312 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=275419 rxBytes=9369812
01-09 09:49:36.413  2891  2972 E ActivityManager: ANR in com.nextcloud.client
01-09 09:49:36.413  2891  2972 E ActivityManager: Reason: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{49224b2 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
01-09 09:49:36.413  2891  2972 E ActivityManager:   67% 11003/com.nextcloud.client: 49% user + 17% kernel / faults: 28093 minor 74 major
01-09 09:49:36.415  2891  2972 W ActivityManager: anr : com.nextcloud.client,0
01-09 09:49:36.456 11257 11278 W PkgUtils: p: com.nextcloud.client, u:0
01-09 09:49:36.473  2891  2973 V WindowManager: Relayout Window{a8a0bea u0 Application Not Responding: com.nextcloud.client}: viewVisibility=0 req=1067x657 WM.LayoutParams{(0,0)(wrapxwrap) gr=#11 sim=#120 ty=2003 fl=#1820002 pfl=0x1000110 fmt=-3 wanim=0x10302ec vsysui=0x10 surfaceInsets=Rect(5, 5 - 5, 5) needsMenuKey=2 colorMode=0 naviIconColor=0}
01-09 09:49:36.477   729   729 I SurfaceFlinger: id=63 createSurf (1077x667),1 flag=4, Application Not Responding: com.nextcloud.client[2891]#0
01-09 09:49:36.538  2891  2973 D WindowManager: finishDrawingWindow: Window{a8a0bea u0 Application Not Responding: com.nextcloud.client} mDrawState=DRAW_PENDING
01-09 09:49:36.589   729   729 I SurfaceFlinger:      Device | 0x77a10e3b00 | 0002 | RGBA_8888 |   0.0    0.0 2560.0 1600.0 |    0    0 2560 1600 | com.nextcloud.client/com.owncloud.an[...]ctivity.FileDisplayActivity[11003]#0
01-09 09:49:36.589   729   729 I SurfaceFlinger:      Device | 0x77a3e3fb00 | 0000 | RGBA_8888 |   0.0    0.0  667.0 1077.0 |  946  306 1559 1296 | Application Not Responding: com.nextcloud.client[2891]#0
01-09 09:49:36.606   729   729 I SurfaceFlinger:      Device | 0x77a10e3b00 | 0002 | RGBA_8888 |   0.0    0.0 2560.0 1600.0 |    0    0 2560 1600 | com.nextcloud.client/com.owncloud.an[...]ctivity.FileDisplayActivity[11003]#0
01-09 09:49:36.606   729   729 I SurfaceFlinger:      Device | 0x77a3e3fb00 | 0000 | RGBA_8888 |   0.0    0.0  667.0 1077.0 |  939  295 1566 1307 | Application Not Responding: com.nextcloud.client[2891]#0
01-09 09:49:37.186  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2877 RxPkts=7938 TxBytes=631128 RxBytes=10222779 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=284270 rxBytes=9382279
01-09 09:49:38.190  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2898 RxPkts=7952 TxBytes=639940 RxBytes=10234831 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=293082 rxBytes=9394331
01-09 09:49:38.335  2891  2973 D InputEventReceiver: channel 'a8a0bea Application Not Responding: com.nextcloud.client (client)' ~ Disposing input event receiver.
01-09 09:49:38.335  2891  2973 D InputEventReceiver: channel 'a8a0bea Application Not Responding: com.nextcloud.client (client)' ~NativeInputEventReceiver.
01-09 09:49:38.578   729   729 I SurfaceFlinger:      Device | 0x77a1bd4080 | 0002 | RGBA_8888 |   0.0    0.0 2560.0 1600.0 |    0    0 2560 1600 | com.nextcloud.client/com.owncloud.an[...]ctivity.FileDisplayActivity[11003]#0
01-09 09:49:38.578   729   729 I SurfaceFlinger:      Device | 0x77a3e3fb00 | 0000 | RGBA_8888 |   0.0    0.0  667.0 1077.0 |  971  347 1533 1255 | Application Not Responding: com.nextcloud.client[2891]#0
01-09 09:49:38.626  2891  3190 I WindowManager: Destroying surface #eb5c74a: Surface(name=Application Not Responding: com.nextcloud.client) called by com.android.server.wm.WindowStateAnimator.destroySurface:2617 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:1026 com.android.server.wm.WindowState.destroyOrSaveSurfaceUnchecked:3821 com.android.server.wm.RootWindowContainer.performSurfacePlacement:870 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:225 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:173 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:163 com.android.server.wm.WindowSurfacePlacer.lambda$-com_android_server_wm_WindowSurfacePlacer_6552:136 
01-09 09:49:38.626   729   774 I SurfaceFlinger: id=63 Removed Application Not Responding: com.nextcloud.client[2891]#0 (4/6)
01-09 09:49:38.627   729   774 I SurfaceFlinger: id=63 Removed Application Not Responding: com.nextcloud.client[2891]#0 (-2/6)
01-09 09:49:38.628   729   729 I SurfaceFlinger:      Device | 0x77a1bd4080 | 0002 | RGBA_8888 |   0.0    0.0 2560.0 1600.0 |    0    0 2560 1600 | com.nextcloud.client/com.owncloud.an[...]ctivity.FileDisplayActivity[11003]#0
01-09 09:49:38.641   729   729 I Layer   : id=63 onRemoved Application Not Responding: com.nextcloud.client[2891]#0 
01-09 09:49:39.195  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=2926 RxPkts=7977 TxBytes=653495 RxBytes=10254056 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=306637 rxBytes=9413556
01-09 09:49:53.284  2891  3256 D WifiTrafficPoller: TrafficStats TxPkts=3162 RxPkts=8185 TxBytes=771733 RxBytes=10420298 , Foreground uid=10166 pkgName=com.nextcloud.client txBytes=424875 rxBytes=9579594
01-09 09:49:54.053  2891 10419 W MultiScreenManagerService: moveTaskBackToDisplayIfNeeded(): root activity or app is null, task=TaskRecord{fa163f0 #161 A=com.nextcloud.client U=0 StackId=1 sz=1}, rootActivity=null
01-09 09:49:54.130  2891  3190 V WindowManager: Setting visibility of Window{9cc17ba u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: false, mViewVisibilityUpdateCompleted=false, caller=com.android.server.wm.WindowContainer.sendAppVisibilityToClients:443 com.android.server.wm.AppWindowToken.setClientHidden:400 com.android.server.wm.AppWindowToken.setVisibility:411 com.android.server.wm.WindowSurfacePlacer.handleClosingApps:525 com.android.server.wm.WindowSurfacePlacer.handleAppTransitionReadyLocked:384 
01-09 09:49:54.156  2891 10419 V WindowManager: Relayout Window{9cc17ba u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: viewVisibility=8 req=1600x2560 WM.LayoutParams{(0,0)(fillxfill) sim=#110 ty=1 fl=#81810100 pfl=0x1020000 wanim=0x10302fc vsysui=0x710 needsMenuKey=2 colorMode=0 naviIconColor=0}
01-09 09:49:54.164   729   729 I SurfaceFlinger:      Device | 0x77a10e3b00 | 0002 | RGBA_8888 |   0.0    0.0 2560.0 1600.0 |   22    1 2559 1586 | com.nextcloud.client/com.owncloud.an[...]ctivity.FileDisplayActivity[11003]#0
01-09 09:49:54.181  3458  3872 I ApplicationPackageManager: return adaptive icon for com.nextcloud.client
01-09 09:49:54.459  2891  3190 E WindowManager: win=Window{9cc17ba u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8, caller=com.android.server.wm.AppWindowToken.destroySurfaces:748 com.android.server.wm.AppWindowToken.destroySurfaces:732 com.android.server.wm.WindowState.onExitAnimationDone:5523 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:517 com.android.server.wm.AppWindowToken.stepAppWindowsAnimation:1745 
01-09 09:49:54.460  2891  3190 I WindowManager: Destroying surface #7320e9b: Surface(name=com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2617 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:1026 com.android.server.wm.WindowState.destroyOrSaveSurfaceUnchecked:3821 com.android.server.wm.WindowState.destroySurface:3767 com.android.server.wm.AppWindowToken.destroySurfaces:748 com.android.server.wm.AppWindowToken.destroySurfaces:732 com.android.server.wm.WindowState.onExitAnimationDone:5523 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:517 
01-09 09:49:54.460   729   775 I SurfaceFlinger: id=55 Removed com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity[11003]#0 (2/6)
01-09 09:49:54.462   729   775 I SurfaceFlinger: id=55 Removed com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity[11003]#0 (-2/6)
01-09 09:49:54.475   729   729 I Layer   : id=55 onRemoved com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity[11003]#0 
01-09 09:49:54.491 11003 11003 D InputEventReceiver: channel '9cc17ba com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity (client)' ~ Disposing input event receiver.
01-09 09:49:54.491 11003 11003 D InputEventReceiver: channel '9cc17ba com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity (client)' ~NativeInputEventReceiver.
01-09 09:49:56.505  2891  2972 W ActivityManager: Bringing down service while still waiting for start foreground: ServiceRecord{49224b2 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
01-09 09:49:56.638 11003 11045 E AndroidRuntime: Process: com.nextcloud.client, PID: 11003
01-09 09:49:56.642  2891 10394 W ActivityManager: crash : com.nextcloud.client,0
01-09 09:49:56.648  2891  2973 I ActivityManager: Showing crash dialog for package com.nextcloud.client u0
01-09 09:49:56.680  2891  2973 V WindowManager: Relayout Window{e0d055e u0 Application Error: com.nextcloud.client}: viewVisibility=0 req=1067x387 WM.LayoutParams{(0,0)(wrapxwrap) gr=#11 sim=#120 ty=2003 fl=#1820002 pfl=0x1000110 fmt=-3 wanim=0x10302ec vsysui=0x10 surfaceInsets=Rect(5, 5 - 5, 5) needsMenuKey=2 colorMode=0 naviIconColor=0}
01-09 09:49:56.685   729   729 I SurfaceFlinger: id=65 createSurf (1077x397),1 flag=4, Application Error: com.nextcloud.client[2891]#0
01-09 09:49:56.691  2891  2972 E ActivityManager: ANR in com.nextcloud.client
01-09 09:49:56.691  2891  2972 E ActivityManager: Reason: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{49224b2 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
01-09 09:49:56.691  2891  2972 E ActivityManager:   47% 11003/com.nextcloud.client: 34% user + 13% kernel / faults: 23813 minor 3 major
01-09 09:49:56.692  2891  2972 W ActivityManager: anr : com.nextcloud.client,0
01-09 09:49:56.693  2891  2972 I ActivityManager: Killing 11003:com.nextcloud.client/u0a166 (adj 200): bg anr
01-09 09:49:56.750 11257 11268 W PkgUtils: p: com.nextcloud.client, u:0
01-09 09:49:56.760  2891  2973 D WindowManager: finishDrawingWindow: Window{e0d055e u0 Application Error: com.nextcloud.client[2891]#0
01-09 09:49:56.750 11257 11268 W PkgUtils: p: com.nextcloud.client, u:0
01-09 09:49:56.813   729   729 I SurfaceFlinger:      Device | 0x77a1bd4600 | 0000 | RGBA_8888 |   0.0    0.0  397.0 1077.0 | 1070  306 1435 1296 | Application Err
```

**Comment by omegasupreme3** [comment] 2019-01-10 19:32
Thank you for your answer. Do you think there is a good chance the issue I described is then fixed? Or do you think there could be another reason for this?

**Comment by tobiasKaminsky** [comment] 2019-01-14 06:45
Yes, then it will be fixed.
The downside on this is that it can happen that Android stalls an upload if you turn off your device to save battery.
But we will inform user somehow.

**Comment by omegasupreme3** [comment] 2019-01-15 06:18
Ok, thank you!

**Comment by tobiasKaminsky** [comment] 2019-10-09 13:42
Duplicate of #2010

**Closed by tobiasKaminsky** 2019-10-09 13:42 UTC
Labels: approved, bug
