### ISSUE TITLE
Bug Report From Crash

### ISSUE THREAD

**Issue by tylerjwoodfin** [nextcloud/android#6874] opened 2020-09-02 03:17 UTC
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032 SQLITE_READONLY_DBMOVED)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:831)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
	at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1667)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:197)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:438)
	at android.content.ContentResolver.delete(ContentResolver.java:1989)
	at com.owncloud.android.datamodel.FileDataStorageManager.removeFolderInDb(FileDataStorageManager.java:621)
	at com.owncloud.android.datamodel.FileDataStorageManager.removeFolder(FileDataStorageManager.java:596)
	at com.owncloud.android.operations.RefreshFolderOperation.removeLocalFolder(RefreshFolderOperation.java:390)
	at com.owncloud.android.operations.RefreshFolderOperation.checkForChanges(RefreshFolderOperation.java:351)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:227)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus8Pro
Model: IN2025
Id: QKQ1.191222.002
Product: OnePlus8Pro

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2008080018

**Comment by tobiasKaminsky** [comment] 2020-09-02 06:01
Duplicate of #6436

**Closed by tobiasKaminsky** 2020-09-02 06:01 UTC
Labels: bug
