### ISSUE TITLE
Error while trying to access Media tab

### ISSUE THREAD

**Issue by danielvrsek** [nextcloud/android#10278] opened 2022-05-23 09:35 UTC
Android 12.0, Nextcloud behind VPN

### Cause of error
```java
Exception in thread "AsyncTask #2" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$AsyncFutureTask.done(AsyncTask.java:429)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:929)
Caused by: Exception in thread "AsyncTask #2" java.lang.RuntimeException: Accessing result data after operation failed!
    at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:512)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.doInBackground(GallerySearchTask.java:102)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.doInBackground(GallerySearchTask.java:48)
    at android.os.AsyncTask$3.call(AsyncTask.java:389)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:929)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `HUAWEI`
* Device: `HWELE`
* Model: `ELE-L29`
* Id: `HUAWEIELE-L29`
* Product: `ELE-L29EEA`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `10.1.0.150C431`

**Comment by AlvaroBrey** [comment] 2022-05-23 09:57
Duplicate of #10198

**Closed by AlvaroBrey** 2022-05-23 09:57 UTC
