### ISSUE TITLE
OOM in Android app

### ISSUE THREAD

**Issue by priyankub** [nextcloud/android#13930] opened 2024-11-02 02:57 UTC
### Cause of error
```java
Exception in thread "Thread-30" java.lang.OutOfMemoryError: Failed to allocate a 26912 byte allocation with 71648 free bytes and 69KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
    at org.apache.jackrabbit.webdav.MultiStatus.getResponses(MultiStatus.java:128)
    at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.readData(ReadFolderRemoteOperation.java:133)
    at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:70)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:413)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:247)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:387)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `caiman`
* Model: `Pixel 9 Pro`
* Id: `AP3A.241105.008`
* Product: `caiman`

### Firmware
* SDK: `35`
* Release: `15`
* Incremental: `12485168`

**Comment by joshtrichards** [comment] 2024-11-02 13:06
Duplicate of #13161

**Closed by joshtrichards** 2024-11-02 13:06 UTC
