### ISSUE TITLE
Deleted Storage path in Android produces Null pointer

### ISSUE THREAD

**Issue by FelixKoerner** [nextcloud/android#11870] opened 2023-08-05 13:41 UTC
### Steps to reproduce

1. Create a path like `/InstantUploud/Camera` on the Nextcloud
2. Use the *Share with Nextcloud* function in Android to upload a file 
3. Choice in the Nextcloud App the path `/InstantUpload/Camera` 
4. Delete in the Nextcloud path `/InstantUpload/Camera `
5. Use the *Share with Nextcloud* function in Android to upload a file
5.1 **try to upload instantly**
5.1.1 click the upload button
5.2 **try to change directory**
5.2.1 click the back arrow in the upper left corner
5.2.2 App shows crash because of NullPointerException
 

### Expected behaviour

5.1.2 Test before upload if path exists. If the path does not exist, show error message to user and change to root directory.
5.2.2 Recover from missing path. Show error message and switch to root directory.

### Actual behaviour

5.1.2 nothing happens
5.2.2 App shows crash because of NullPointerException

### Android version

13

### Device brand and model

Poco F3

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.25.0

### Nextcloud server version

25.0.9

### Using a reverse proxy?

No

### Additional information

Custom ROM: [Evolution X](https://evolution-x.org/)

**Comment by t3pfaffe** [comment] 2023-08-16 20:19
I have encountered this as well in app version 3.25.0 on Android 13. Hitting the "directory backwards" button in the share->save dialogue in a now renamed/deleted folder would result in the app crash as OP described.

Thankfully I did come up with a temporary solution to get around this error. I remade the parent directory tree it was looking for (in my case it was just one folder I had to rename) so that I can hit back and save a file somewhere else. 

I didn't test it but perhaps clearing the app cache could remove the previously used directory avoiding the problem as well.

A permanent fix to this problem would seem to be implementing a check when triggering the share dialogue to make sure the directory it remembers being used last time, actually still exists.

**Comment by llucax** [comment] 2023-10-06 15:44
This is probably the same:

* #12004

**Comment by llucax** [comment] 2023-10-06 15:45
Cleaning the cache doesn't help.

**Comment by llucax** [comment] 2023-10-06 15:52
I tried recreating the directories but it doesn't seem to help either, but I'm not 100% certain I'm re-creating the correct path because I didn't find a way to see the full path in the upload screen. The only workaroud I see is to completely remove the account or reset the app data, but I will lose all the autoupload configuration, which is really annoying.

**Comment by llucax** [comment] 2023-10-06 17:59
I case it helps anyone, I had to go to the nexcloud app and refresh the recreated directories then it worked and I could finally change the current directory.

**Comment by joshtrichards** [comment] 2023-10-07 16:48
Duplicate of #11207

Fixed in #11410

Released in v3.26.

**Closed** 2023-10-07 16:48 UTC
Labels: bug
