### ISSUE TITLE
README files overlap when editing them, and the back button takes us back to the cloud root folder

### ISSUE THREAD

**Issue by SofianeLasri** [nextcloud/android#10991] opened 2022-11-05 10:39 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Add a readme file to the cloud root folder
2. Go to another folder with a Readme file
3. Edit this folder's readme file
4. Quit the editor

### Expected behaviour

It should shows us the root folder after exiting the editor, but the parent folder of the edited file. Plus, even if it have to shows us the root folder, it doesn't have to overlap the two readme files.

### Actual behaviour

The app will shows you the root folder with it's readme file, and the edited readme file.

### Android version

12

### Device brand and model

Samsung Galaxy S21 5G - SM-G991B/DS

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.3

### Nextcloud server version

24.0.7

### Using a reverse proxy?

No

### Android logs

[logcatOutput.txt](https://github.com/nextcloud/android/files/9943567/logcatOutput.txt)

### Additional information

https://user-images.githubusercontent.com/43948827/200115441-46d6e34d-9637-4963-bce6-fd54a354a445.mp4

**Comment by Gifford47** [comment] 2023-01-25 11:00
I can confirm the Bug! I have the same issue on Android 12/ Galaxy S21.

**Comment by AlvaroBrey** [comment] 2023-01-27 10:11
Duplicate of #9701

**Closed by AlvaroBrey** 2023-01-27 10:11 UTC
Labels: bug
