### ISSUE TITLE
Nextcloud keeps stopping on Android 13 (LOS20) 

### ISSUE THREAD

**Issue by heinhuiz** [nextcloud/android#11558] opened 2023-04-26 07:39 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Have Nextcloud Android installed on Android 12 (LOS19.1). 
2. Update to Android 13 (LOS20). 

### Expected behaviour

App should be running normally. 

### Actual behaviour

App crashes constantly. Most of the times (99%) a 'Nextcloud keeps stopping' message is displayed, which disappears almost immediately. Sometimes (0,95%) the message stays, waiting for input to 'Wait' or 'Close the app'. Seldom (0.05%) a log is created, which I used now to create this bug report. 

### Android version

13

### Device brand and model

Xiaomi Redmi K30 Pro Zoom Edition 

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.24.1

### Nextcloud server version

25.0.5

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "WM.task-1" java.lang.IllegalArgumentException: context is null
    at android.accounts.AccountManager.get(AccountManager.java:593)
    at com.owncloud.android.lib.common.OwnCloudAccount.<init>(OwnCloudAccount.java:75)
    at com.nextcloud.client.account.UserAccountManagerImpl.createUserFromAccount(UserAccountManagerImpl.java:199)
    at com.nextcloud.client.account.UserAccountManagerImpl.getUser(UserAccountManagerImpl.java:241)
    at com.owncloud.android.utils.theme.MaterialSchemesProviderImpl.getMaterialSchemesForCurrentUser(MaterialSchemesProviderImpl.kt:63)
    at com.nextcloud.client.di.ThemeModule$Companion.provideMaterialSchemes(ThemeModule.kt:55)
    at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.provideMaterialSchemes(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:40)
    at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.get(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:30)
    at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.get(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:13)
    at com.owncloud.android.utils.theme.ViewThemeUtils_Factory.get(ViewThemeUtils_Factory.java:32)
    at com.owncloud.android.utils.theme.ViewThemeUtils_Factory.get(ViewThemeUtils_Factory.java:12)
    at com.nextcloud.client.jobs.BackgroundJobFactory.createMediaFoldersDetectionWork(BackgroundJobFactory.kt:220)
    at com.nextcloud.client.jobs.BackgroundJobFactory.createWorker(BackgroundJobFactory.kt:100)
    at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:83)
    at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:245)
    at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137)
    at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240190`
* Build flavor: `generic`

### Device information
* Brand: `Redmi`
* Device: `lmipro`
* Model: `Redmi K30 Pro Zoom Edition`
* Id: `TQ2A.230305.008.C1`
* Product: `lineage_lmi`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `eng.root.20230412.150939`

### Additional information

I updated from LOS 19.1 to LOS 20, both LineageOS for MicroG.
App is the latest available version on F-Droid (and GitHub).

**Comment by joshtrichards** [comment] 2023-04-28 14:17
Three different things to try that come to mind:
* Wipe all data from the app (from the app info screen) and grant the app all permissions. Then restart the app.
* Go into the phone's AccountManager and remove the Nextcloud entry (you'll have to re-authenticate next time you open the app)
* Try the Nextcloud Dev build: https://f-droid.org/en/packages/com.nextcloud.android.beta/

**Comment by heinhuiz** [comment] 2023-04-30 12:31
Thanks for your reply. I tried all 3 suggestions. Wiping data and removing the account proved to be impossible, because for those actions the app needs to be opened but it crashes immediately again.
Then I u installed the normal version and installed the Dev version from F-Droid. Also to no avail, it keeps crashing.

### Cause of error
```java
Exception in thread "WM.task-4" java.lang.IllegalArgumentException: context is null
    at android.accounts.AccountManager.get(AccountManager.java:593)
    at com.owncloud.android.lib.common.OwnCloudAccount.<init>(OwnCloudAccount.java:75)
    at com.nextcloud.client.account.UserAccountManagerImpl.createUserFromAccount(UserAccountManagerImpl.java:199)
    at com.nextcloud.client.account.UserAccountManagerImpl.getUser(UserAccountManagerImpl.java:241)
    at com.owncloud.android.utils.theme.MaterialSchemesProviderImpl.getMaterialSchemesForCurrentUser(MaterialSchemesProviderImpl.kt:63)
    at com.nextcloud.client.di.ThemeModule$Companion.provideMaterialSchemes(ThemeModule.kt:55)
    at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.provideMaterialSchemes(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:42)
    at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.get(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:32)
    at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.get(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:13)
    at com.owncloud.android.utils.theme.ViewThemeUtils_Factory.get(ViewThemeUtils_Factory.java:34)
    at com.owncloud.android.utils.theme.ViewThemeUtils_Factory.get(ViewThemeUtils_Factory.java:12)
    at com.nextcloud.client.jobs.BackgroundJobFactory.createFilesUploadWorker(BackgroundJobFactory.kt:254)
    at com.nextcloud.client.jobs.BackgroundJobFactory.createWorker(BackgroundJobFactory.kt:106)
    at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:83)
    at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:243)
    at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:145)
    at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20230425`
* Build flavor: `versionDev`

### Device information
* Brand: `Redmi`
* Device: `lmipro`
* Model: `Redmi K30 Pro Zoom Edition`
* Id: `TQ2A.230305.008.C1`
* Product: `lineage_lmi`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `eng.root.20230412.150939`

**Comment by bipox** [comment] 2023-06-21 16:05
Same issue, Android 13 LOS 20, on a rooted Oneplus 6T

```
### Cause of error
```java
Exception in thread "WM.task-4" java.lang.IllegalArgumentException: context is null
    at android.accounts.AccountManager.get(AccountManager.java:593)
    at com.owncloud.android.lib.common.OwnCloudAccount.<init>(OwnCloudAccount.java:75)
    at com.nextcloud.client.account.UserAccountManagerImpl.createUserFromAccount(UserAccountManagerImpl.java:201)
    at com.nextcloud.client.account.UserAccountManagerImpl.getUser(UserAccountManagerImpl.java:243)
    at com.owncloud.android.utils.theme.MaterialSchemesProviderImpl.getMaterialSchemesForCurrentUser(MaterialSchemesProviderImpl.kt:63)
    at com.nextcloud.client.di.ThemeModule$Companion.provideMaterialSchemes(ThemeModule.kt:55)
    at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.provideMaterialSchemes(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:42)
    at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.get(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:32)
    at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.get(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:13)
    at com.owncloud.android.utils.theme.ViewThemeUtils_Factory.get(ViewThemeUtils_Factory.java:34)
    at com.owncloud.android.utils.theme.ViewThemeUtils_Factory.get(ViewThemeUtils_Factory.java:12)
    at com.nextcloud.client.jobs.BackgroundJobFactory.createMediaFoldersDetectionWork(BackgroundJobFactory.kt:217)
    at com.nextcloud.client.jobs.BackgroundJobFactory.createWorker(BackgroundJobFactory.kt:101)
    at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:83)
    at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:243)
    at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:145)
    at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30250090`
* Build flavor: `generic`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus6T`
* Model: `ONEPLUS A6013`
* Id: `TQ2A.230505.002`
* Product: `OnePlus6T`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `bb99f4f0bb`
```

**Comment by joshtrichards** [comment] 2023-08-21 16:59
Duplicate of #11026

**Closed** 2023-08-21 17:03 UTC
Labels: bug
