### ISSUE TITLE
Nextcloud crash when auto upload big folder on android

### ISSUE THREAD

**Issue by bomcz** [nextcloud/android#10802] opened 2022-10-14 11:59 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

It crashes when I try to auto upload photo folder about 18gb.
Tried to clear cache and restart phone but still not work.
Samsung note 10.

### Expected behaviour

It's should auto upload 

### Actual behaviour

Freeze and crash

### Android version

Android 12

### Device brand and model

Samsung note 10

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.2

### Nextcloud server version

24.0.6

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "Thread-23" java.lang.OutOfMemoryError: Failed to allocate a 80 byte allocation with 2128384 free bytes and 2078KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
    at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
    at java.lang.StringBuilder.<init>(StringBuilder.java:102)
    at libcore.reflect.GenericSignatureParser.scanIdentifier(GenericSignatureParser.java:493)
    at libcore.reflect.GenericSignatureParser.parseClassTypeSignature(GenericSignatureParser.java:312)
    at libcore.reflect.GenericSignatureParser.parseClassSignature(GenericSignatureParser.java:239)
    at libcore.reflect.GenericSignatureParser.parseForClass(GenericSignatureParser.java:126)
    at java.lang.Class.getTypeParameters(Class.java:809)
    at com.google.gson.internal.$Gson$Types.resolveTypeVariable($Gson$Types.java:453)
    at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:365)
    at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:396)
    at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:343)
    at com.google.gson.internal.$Gson$Types.getSupertype($Gson$Types.java:288)
    at com.google.gson.internal.$Gson$Types.getCollectionElementType($Gson$Types.java:307)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52)
    at com.google.gson.Gson.getAdapter(Gson.java:501)
    at com.google.gson.Gson.toJson(Gson.java:739)
    at com.google.gson.Gson.toJson(Gson.java:726)
    at com.google.gson.Gson.toJson(Gson.java:681)
    at com.google.gson.Gson.toJson(Gson.java:661)
    at com.owncloud.android.datamodel.FileDataStorageManager.createContentValuesBase(FileDataStorageManager.java:471)
    at com.owncloud.android.datamodel.FileDataStorageManager.createContentValuesForFile(FileDataStorageManager.java:494)
    at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:342)
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:533)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:409)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:239)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:398)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `d1`
* Model: `SM-N970F`
* Id: `SP1A.210812.016`
* Product: `d1eea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `N970FXXU8HVGA`

### Server error logs

```bash
### Cause of error

Exception in thread "Thread-23" java.lang.OutOfMemoryError: Failed to allocate a 80 byte allocation with 2128384 free bytes and 2078KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
    at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
    at java.lang.StringBuilder.<init>(StringBuilder.java:102)
    at libcore.reflect.GenericSignatureParser.scanIdentifier(GenericSignatureParser.java:493)
    at libcore.reflect.GenericSignatureParser.parseClassTypeSignature(GenericSignatureParser.java:312)
    at libcore.reflect.GenericSignatureParser.parseClassSignature(GenericSignatureParser.java:239)
    at libcore.reflect.GenericSignatureParser.parseForClass(GenericSignatureParser.java:126)
    at java.lang.Class.getTypeParameters(Class.java:809)
    at com.google.gson.internal.$Gson$Types.resolveTypeVariable($Gson$Types.java:453)
    at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:365)
    at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:396)
    at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:343)
    at com.google.gson.internal.$Gson$Types.getSupertype($Gson$Types.java:288)
    at com.google.gson.internal.$Gson$Types.getCollectionElementType($Gson$Types.java:307)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52)
    at com.google.gson.Gson.getAdapter(Gson.java:501)
    at com.google.gson.Gson.toJson(Gson.java:739)
    at com.google.gson.Gson.toJson(Gson.java:726)
    at com.google.gson.Gson.toJson(Gson.java:681)
    at com.google.gson.Gson.toJson(Gson.java:661)
    at com.owncloud.android.datamodel.FileDataStorageManager.createContentValuesBase(FileDataStorageManager.java:471)
    at com.owncloud.android.datamodel.FileDataStorageManager.createContentValuesForFile(FileDataStorageManager.java:494)
    at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:342)
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:533)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:409)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:239)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:398)
    at java.lang.Thread.run(Thread.java:920)



### App information
* ID: `com.nextcloud.client`
* Version: `30210290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `d1`
* Model: `SM-N970F`
* Id: `SP1A.210812.016`
* Product: `d1eea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `N970FXXU8HVGA`
```

**Comment by AlvaroBrey** [comment] 2022-11-23 12:06
Duplicate of #10653

**Closed by AlvaroBrey** 2022-11-23 12:06 UTC
Labels: bug
