### ISSUE TITLE
Crash when viewing folder with some videos

### ISSUE THREAD

**Issue by Derkades** [nextcloud/android#7187] opened 2020-10-30 23:19 UTC
I am writing this quickly on my phone, some information is missing for right now. I'll edit with more info later.

### Steps to reproduce
I unfortunately cannot provide exact instructions to reproduce. It seems to happen when quickly opening folders that have not been cached yet. I got the error multiple times by just randomly clicking around, but was never to get it to crash again when opening the same folder afterwards. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
Crash, see below

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model: Pixel 3a

Stock or customized system: stock

Nextcloud app version: 3.14.0 RC 1

Nextcloud server version: 20.something

Reverse proxy: nginx

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{19c7d0 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: sargo
Model: Pixel 3a
Id: RP1A.201005.004
Product: sargo

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 6782484
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Derkades** [comment] 2020-10-31 09:32
Probably duplicate of #7185

**Comment by Derkades** [comment] 2020-10-31 10:19
I can now reliably reproduce by opening any video file, it crashes a few seconds into playback.

**Comment by AndyScherzinger** [comment] 2020-10-31 17:39
cc @tobiasKaminsky @ezaquarii for feedback

**Comment by AndyScherzinger** [comment] 2020-11-03 08:16
Duplicate of #6905

**Closed by AndyScherzinger** 2020-11-03 08:16 UTC
Labels: bug
