### ISSUE TITLE
Nexcloud android app, add configuable delay in autoupload functionality

### ISSUE THREAD

**Issue by balvie** [nextcloud/android#12906] opened 2024-04-19 09:47 UTC
As a exited ambassador to the NC software, I help people to see how great its features are. One of them is the Auto Upload (AU), it simply releases a lot of memory onm the device and creates a safe storage of your files. 
Many times this immediate effect of the AU functionality is a nuisance as I cannot show people my photo's directly after they have been taken, Auto Upload is or has has allready been taken care of them. They are gone already from my device.
Therefore I now often switch off my wifi in order to prevent AU doing so.

Would it be great to have the AU functionality  extended with a configuarable delay.  I can envision a parameter in the settings named "Delay" located just above the parameter setting for "Original file will be..." that allows specification of such a delay in:
- hours, 
- days, 
- weeks, 
- months or 
- None.

Then AU is started on files as soon as this delay, based on file modification date, has elapsed.

In the app is now not something that resembles this idea/functionality.

**Comment by joshtrichards** [comment] 2024-07-09 13:04
Duplicate of #2323

**Closed by joshtrichards** 2024-07-09 13:04 UTC
Labels: enhancement, feature: auto upload
