### ISSUE TITLE
hang when swithing on internet acces

### ISSUE THREAD

**Issue by lcdcinq** [nextcloud/android#9952] opened 2022-03-10 11:12 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) } in com.owncloud.android.utils.ReceiversHelper$1@8b1be7e
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1572)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8019)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.SecurityException: Package android does not belong to 10259
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
	at android.os.Parcel.createException(Parcel.java:2360)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.os.Parcel.readException(Parcel.java:2285)
	at android.net.IConnectivityManager$Stub$Proxy.getNetworkCapabilities(IConnectivityManager.java:2456)
	at android.net.ConnectivityManager.getNetworkCapabilities(ConnectivityManager.java:1410)
	at com.nextcloud.client.network.ConnectivityServiceImpl.getConnectivity(ConnectivityServiceImpl.java:118)
	at com.owncloud.android.utils.ReceiversHelper$1.onReceive(ReceiversHelper.java:58)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1562)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.AppOpsManager.checkPackage(AppOpsManager.java:7794)
	at com.android.server.ConnectivityService.getNetworkCapabilities(ConnectivityService.java:1779)
	at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:978)
	at android.os.Binder.execTransactInternal(Binder.java:1159)
	at android.os.Binder.execTransact(Binder.java:1123)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: sunny
Model: M2101K7AG
Id: RKQ1.201022.002
Product: sunny_global

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: V12.5.5.0.RKGMIXM

**Comment by AlvaroBrey** [comment] 2022-03-10 12:15
Duplicate of #9849

**Closed by AlvaroBrey** 2022-03-10 12:15 UTC
Labels: bug
