### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by HuiiBuh** [nextcloud/android#7702] opened 2020-12-20 18:05 UTC
I wanted to try the dev version of nextcloud and I cloud login, but as soon as the login screen went away I got this exception.  

I also have the non dev version installed, perhaps this changes something... 

``` 
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lokio/Buffer;
	at okhttp3.ResponseBody.create(ResponseBody.java:210)
	at okhttp3.internal.Util.<clinit>(Util.java:62)
	at okhttp3.Credentials.basic(Credentials.java:30)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:330)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:304)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:276)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: okio.Buffer
	... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201216
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: beryllium
Model: POCO F1
Id: QQ3A.200805.001
Product: beryllium

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 12
```

**Comment by Unpublished** [comment] 2020-12-21 12:29
Duplicate of #7699

**Closed by Unpublished** 2020-12-21 12:29 UTC
Labels: bug
