### ISSUE TITLE
No password, no app

### ISSUE THREAD

**Issue by sualko** [nextcloud/android#8252] opened 2021-04-08 10:11 UTC
### Steps to reproduce
1. Add account
2. Something gets wrong and you have to reenter the password
3. Go back from that "enter password" dialog
4. You can't access the app anymore

### Expected behaviour
- I can enter the password

### Actual behaviour
- App crashes

### Environment data
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
  at okhttp3.Credentials.basic(Unknown Source:8)
  at okhttp3.Credentials.basic$default(Credentials.kt:28)
  at okhttp3.Credentials.basic(Unknown Source:2)
  at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
  at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
  at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
  at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
  at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
  at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
  at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: doha_n
Model: moto g(8) plus
Id: QPIS30.28-Q3-28-26-3-4
Product: doha_reteu_n

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 19343

**Comment by tobiasKaminsky** [comment] 2021-05-05 11:18
> * Something gets wrong and you have to reenter the password
> 
> *

When does this happpen?

**Comment by sualko** [comment] 2021-05-07 14:57
> When does this happpen?

From time to time the client is forgetting the password/authentication. I don't know why that happens, but it could be related to my custom user backend. Nonetheless if you skip that dialog as explained, the app can not be used anymore. Since I have multiple accounts connected with a ton of watched folders and so on, I don't want to delete the app data and I'm hopping for a solution in one of the next beta releases.

**Comment by AndyScherzinger** [comment] 2021-05-17 09:38
Duplicate of #8370

**Closed by AndyScherzinger** 2021-05-17 09:38 UTC
Labels: bug, needs info/discussion
