### ISSUE TITLE
Add "Play folder" for media files

### ISSUE THREAD

**Issue by TechupBusiness** [nextcloud/android#7063] opened 2020-10-07 15:03 UTC
### Is your feature request related to a problem? Please describe.
When I have a folder full of single MP3s, I need to start every file manually. It's not possible to create a playlist. And as I cant download folders to my local filesystem I'm unable to play these files automatically after each other.

### Describe the solution you'd like
Add a "Play folder" or "Open folder with" or "Stream folder to" functionality to folder context menu.

**Comment by tobiasKaminsky** [comment] 2020-10-16 04:56
> And as I cant download folders to my local filesystem

What is the problem with this? You should be able to click on three dots next to folder and select sync.

**Comment by joshtrichards** [comment] 2023-10-13 22:09
Duplicate of #1038

Also related: #5555

**Closed by joshtrichards** 2023-10-13 22:09 UTC
Labels: enhancement

**Comment by TechupBusiness** [comment] 2023-10-14 09:08
A pity. Then at least make it more convenient please, to find the synchronised local folder without reading docs, at least display its path somewhere.
