### ISSUE TITLE
Data storage folder selection

### ISSUE THREAD

**Issue by GEkuL** [nextcloud/android#10426] opened 2022-06-22 12:08 UTC
Hi there,

It would be nice to set a Nextcloud folder on your own, not just picking from several options.

Not sure if it's hard to implement (many apps do that), so it would be nice to set the path of saving nextcloud files exclusively.

**Comment by joshtrichards** [comment] 2023-12-21 23:02
Duplicate of #4223

**Closed by joshtrichards** 2023-12-21 23:02 UTC
Labels: enhancement, hotspot: device storage
