### ISSUE TITLE
Error while using App or/and syncing

### ISSUE THREAD

**Issue by corincorvus** [nextcloud/android#5377] opened 2020-02-02 21:52 UTC
Hi, 

If i Sync items or browse in the App, it crashes sometimes. While syncing the App often freeze. 

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e1b2b07 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7TPro
Model: HD1913
Id: QKQ1.190716.003
Product: OnePlus7TPro

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 1912060020

Nextcloud Server Version
17.0.2

Nothing in Server logs. 

If you need more Information, Tell me.

**Comment by corincorvus** [comment] 2020-02-04 07:19
Server System-Info
Here is my System detail:
https://cloud.c-lab.one/nextcloud/s/JEy9Cso7FqgJj9P
vEe7opdNdTjic53gbqE9

**Comment by thgoebel** [comment] 2020-03-05 09:12
Duplicate of #2010 ?

**Comment by AndyScherzinger** [comment] 2020-03-10 09:02
Duplicate of #2010

**Comment by AndyScherzinger** [comment] 2020-03-10 09:03
thanks @thgoebel, it is a duplicate

**Closed by AndyScherzinger** 2020-03-10 09:02 UTC
Labels: bug
