### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GabrielLinharesBozzon** [nextcloud/android#13300] opened 2024-07-19 16:21 UTC
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at com.owncloud.android.ui.adapter.OCFileListAdapter.limitToPersonalFiles(OCFileListAdapter.java:1074)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:741)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1359)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1308)
    at com.owncloud.android.ui.fragment.OCFileListFragment.refreshDirectory(OCFileListFragment.java:1304)
    at com.owncloud.android.ui.activity.FileDisplayActivity.showFiles(FileDisplayActivity.java:2224)
    at com.owncloud.android.ui.activity.DrawerActivity.onNavigationItemClicked(DrawerActivity.java:497)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$setupDrawerMenu$4(DrawerActivity.java:459)
    at com.owncloud.android.ui.activity.DrawerActivity.$r8$lambda$avHXP34Kh0TDBHMWmR2kRM7pnyQ(Unknown Source:0)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:7860)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a6plte`
* Model: `SM-A605GN`
* Id: `QP1A.190711.020`
* Product: `a6plteub`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `A605GNUBU8CUK1`

**Comment by joshtrichards** [comment] 2024-07-19 16:39
Duplicate of #13086
Fixed in #12930

**Closed by joshtrichards** 2024-07-19 16:39 UTC
