### ISSUE TITLE
Share from Write on PDF (samsung) 

### ISSUE THREAD

**Issue by cl3f3** [nextcloud/android#7910] opened 2021-01-31 22:19 UTC
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Do not call this method before initializing mStorageManager
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.initTargetFolder(ReceiveExternalFilesActivity.java:1002)
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onStart(ReceiveExternalFilesActivity.java:251)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
	at android.app.Activity.performStart(Activity.java:7986)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3677)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: gta4xlwifi
Model: SM-P610
Id: QP1A.190711.020
Product: gta4xlwifieea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: P610XXU2BTK2

**Comment by tobiasKaminsky** [comment] 2021-02-23 07:28
Duplicate of #7912

**Closed by tobiasKaminsky** 2021-02-23 07:28 UTC
Labels: bug
