### ISSUE TITLE
Crash app after delete notification.

### ISSUE THREAD

**Issue by kofe88** [nextcloud/android#5769] opened 2020-03-29 20:58 UTC
### Steps to reproduce
1. Delete notification.
2. Crash.

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-PDGr7gG865lLhSBMieg5cw==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-PDGr7gG865lLhSBMieg5cw==/lib/arm64, /data/app/com.nextcloud.client-PDGr7gG865lLhSBMieg5cw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a7y18lte
Model: SM-A750FN
Id: PPR1.180610.011
Product: a7y18lteser

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: A750FNPUS4BTB2

**Comment by tobiasKaminsky** [comment] 2020-03-30 05:00
Duplicate of #4675

**Closed by tobiasKaminsky** 2020-03-30 05:00 UTC
Labels: bug
