### ISSUE TITLE
Disable automatic upload folder

### ISSUE THREAD

**Issue by gl-dev** [nextcloud/android#11190] opened 2022-12-21 18:07 UTC
"Automatic upload" folders overview is a mess because each folder found in the local file system is displayed and offered for sync.

There should be an option to disable and clear the list of folders found.
Sorting by latest folders and so on and a search bar would be very helpful.
By pressing a folder name, the picture list below should dissapear and another press should bring it back ("peek" feature). This user configured behavior/view should be store automatically in the app.

**Comment by AlvaroBrey** [comment] 2022-12-22 08:24
Duplicate of #9684

**Closed by AlvaroBrey** 2022-12-22 08:24 UTC
Labels: enhancement
