### ISSUE TITLE
Login failed from ldap account

### ISSUE THREAD

**Issue by lgwapnitsky** [nextcloud/android#8297] opened 2021-04-18 15:50 UTC
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: timelm
Model: LM-V600
Id: RKQ1.201105.002
Product: timelm

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2106019215455

**Comment by mightymop** [comment] 2021-06-05 09:08
This PR should fix it: https://github.com/nextcloud/android-library/pull/638

**Comment by tobiasKaminsky** [comment] 2021-06-21 07:30
Duplicate of #8370

**Closed by tobiasKaminsky** 2021-06-21 07:30 UTC
Labels: approved, bug, pr exists
