### ISSUE TITLE
Directories are not displayed correctly

### ISSUE THREAD

**Issue by ffeiler** [nextcloud/android#8282] opened 2021-04-14 18:54 UTC
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- App should use entire screen (tablet, portrait mode)

### Actual behaviour
- size of list of files/folders so narrow that not even filenames can be read (around 30% of available width)

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model: Galaxy Tab S6 Lite

Stock or customized system:

Nextcloud app version: 3.15.1

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by szaimen** [comment] 2021-04-14 19:29
Duplicate of #8281

**Closed by szaimen** 2021-04-14 19:29 UTC
Labels: bug
