### ISSUE TITLE
Folder deleted No Upload 

### ISSUE THREAD

**Issue by Plagwitzer** [nextcloud/android#11524] opened 2023-04-13 17:16 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Picture select
Sende to
Nextcloud
Deleted Folder
Back Back
Error

### Expected behaviour

I can Not geht Out of the deleted folder

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.canWrite()' on a null object reference
    at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onCreateOptionsMenu(ReceiveExternalFilesActivity.java:1034)
    at android.app.Activity.onCreatePanelMenu(Activity.java:4307)
    at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:521)
    at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3429)
    at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
    at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1076)
    at android.view.Choreographer.doCallbacks(Choreographer.java:897)
    at android.view.Choreographer.doFrame(Choreographer.java:822)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:236)
    at android.app.ActivityThread.main(ActivityThread.java:8061)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240290`
* Build flavor: `gplay`

### Device information
* Brand: `Xiaomi`
* Device: `grus`
* Model: `Mi 9 SE`
* Id: `RKQ1.200826.002`
* Product: `grus`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `V12.5.1.0.RFBMIXM`

### Android version

11

### Device brand and model

Xiaomi Mi 9

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.2

### Nextcloud server version

25.0.5

### Using a reverse proxy?

I don't know

**Comment by joshtrichards** [comment] 2023-10-07 22:48
Duplicate of #9321

**Closed by joshtrichards** 2023-10-07 22:48 UTC
Labels: bug
