### ISSUE TITLE
[3.5.0 RC1] Loading of activities fails and an "Unexpected exception" is displayed

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#3530] opened 2019-01-30 15:48 UTC
### Actual behavior
If you select the Activities tab a spinning wheel is shown for a moment and after some time an "Unexpected exception" message is shown on the screen.

### Expected behavior
Load and display all available activities.
 
### Steps to reproduce
1. Open the Nextcloud app and select the Activities tab.
-> An "Unexpected exception" is displayed.

### Environment data
Android version: 8.0
Device model: Samsung Galaxy S7
Stock or customized system: Stock ROM
Nextcloud app version: 3.5.0 RC1
Nextcloud server version: 15.0.2

**Comment by AndyScherzinger** [comment] 2019-01-30 17:00
@tobiasKaminsky I can't reproduce this with the latest master which should be quite close to 3.5.0RC1 also running Nc15, Android 9.

**Comment by ne20002** [comment] 2019-01-30 18:09
I can confirm the Bug. I have a tablet, nextcloud installed with two Accounts. One is listing activities, other not but displaying Unexpected Exception.

- [ ]

**Comment by AndyScherzinger** [comment] 2019-01-30 23:39
Can anybody experiencing this exception provide a stack trace or rather a logcat so we can find out what is actually causes this? :)

**Comment by tobiasKaminsky** [comment] 2019-01-31 11:31
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by j-ed** [comment] 2019-01-31 15:20
@tobiasKaminsky I've just create a test account and checked the activities tab. Unfortunately I couldn't reproduce the problem  with the newly created account. I think I have to wait for the next RC.

**Comment by j-ed** [comment] 2019-01-31 15:32
@tobiasKaminsky I've just installed Nextcloud on a different phone. If I use the same account which has the problem on that phone, it is instantly displayed too. So if you would send my an app version with the logger enabled, I could install it and try to fetch the information you need to get hold of the problem.

**Comment by tobiasKaminsky** [comment] 2019-02-01 06:49
I "fear" that there is something in the activity that cannot be parsed and thus it just shows nothing. On a fresh account this then will not happen.
3.5.0RC2 will have logger enabled and will be available today.

Do you see any special activities when browsing on web?

**Comment by j-ed** [comment] 2019-02-01 07:47
I cannot find any "special" activities. There are e.g.
- Calendar update change activities.
- Document change activities.
- File move activities.
- Calendar event deletion activities.
etc.

I think we have to wait for the RC2 app release.

**Comment by ne20002** [comment] 2019-02-02 08:13
2019/02/02 09:00:53
GetActivitiesRemoteOperation: Exception while getting remote activities Exception: [com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226), com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41), com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82), com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61), com.google.gson.Gson.fromJson(Gson.java:927), com.google.gson.Gson.fromJson(Gson.java:994), com.owncloud.android.lib.resources.activities.GetActivitiesRemoteOperation.parseResult(GetActivitiesRemoteOperation.java:197), com.owncloud.android.lib.resources.activities.GetActivitiesRemoteOperation.run(GetActivitiesRemoteOperation.java:154), com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145), com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:149), com.owncloud.android.ui.activities.data.activities.ActivitiesServiceApiImpl$GetActivityListTask.doInBackground(ActivitiesServiceApiImpl.java:87), com.owncloud.android.ui.activities.data.activities.ActivitiesServiceApiImpl$GetActivityListTask.doInBackground(ActivitiesServiceApiImpl.java:56), android.os.AsyncTask$2.call(AsyncTask.java:316), java.util.concurrent.FutureTask.run(FutureTask.java:237), android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607), java.lang.Thread.run(Thread.java:776)]

2019/02/02 09:00:53
ActivitiesServiceApiImpl: Unexpected exception

2019/02/02 09:00:57
ActivitiesActivity: onPause() ending

2019/02/02 09:00:57
BaseActivity: onNewIntent() start

2019/02/02 09:00:57
BaseActivity: onNewIntent() stop

2019/02/02 09:00:57
FileDisplayActivity: Unexpected intent Intent { flg=0x4000000 cmp=com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity }

2019/02/02 09:00:57
BaseActivity: onRestart() start

**Comment by ne20002** [comment] 2019-02-02 08:44
The json of the activities seems to look ok on the first view. But it's not small.

**Comment by AndyScherzinger** [comment] 2019-02-02 19:00
@ne20002 according to your stack trace there is indeed an issue parsing your activities jason :/

**Comment by j-ed** [comment] 2019-02-02 19:04
I've sent my log trace to Tobias by email.

**Comment by ne20002** [comment] 2019-02-02 20:19
According to nglint the JSON is ok. I can't send the JSON without requesting permission as it is the account of a friend.
Btw, there has been no error with 3.4.0 and the list of activities has not changed these days.

**Comment by tobiasKaminsky** [comment] 2019-02-04 08:54
> I've sent my log trace to Tobias by email.

Hm. I did not received a mail. Can you send it again tobias at nextcloud dot com with a reference to this issue?

**Comment by tobiasKaminsky** [comment] 2019-02-04 08:56
> According to nglint the JSON is ok

While technically the json might be ok, it still can happen that parsing is not working, e.g. if you expect to have "name" as a string, but instead you have "name: ,", then it crashes.

However I thought that I did some enhancements so that only the failing activity is not shown, but in your cases no activity at all is shown :/

**Comment by j-ed** [comment] 2019-02-04 09:20
@tobiasKaminsky I've resent the email.

**Comment by ne20002** [comment] 2019-02-06 19:32
Exception occurs on a second account.
@Tobias, do you need another JSON?

**Comment by tobiasKaminsky** [comment] 2019-02-07 16:11
It is fixed on server side via https://github.com/nextcloud/activity/pull/346 and on Android side via https://github.com/nextcloud/android-library/pull/236
 
@ne20002 can you maybe try out our dev version, there the fix should be included by tomorrow (version >= 20190703)

**Comment by tobiasKaminsky** [comment] 2019-02-07 16:31
It will also be in next version (3.5.0) via new library 1.3.1.

**Comment by ne20002** [comment] 2019-02-08 18:55
Activities are back. :)

**Comment by tobiasKaminsky** [comment] 2019-02-11 19:09
Thanks for reporting back!

**Closed** 2019-02-11 19:08 UTC
Labels: bug, release candidate
