### ISSUE TITLE
Main and Nightly Version crashing all time on LG G4

### ISSUE THREAD

**Issue by Bullnados** [nextcloud/android#760] opened 2017-03-18 23:56 UTC
LG G4 6.0 stock
After a while browsing through folders app crash immediately.
Here is the logcat while app is crashing
Logcat:

```
03-19 00:37:24.679 29912 29971 D FileDataStorageManager: Sending 19 operations to FileContentProvider
03-19 00:37:24.680 29912 29971 D FileContentProvider: applying batch in provider com.owncloud.android.providers.FileContentProvider@9240735 (temporary: false)
03-19 00:37:24.742 29912 29971 D FileContentProvider: applied batch in provider com.owncloud.android.providers.FileContentProvider@9240735
03-19 00:37:24.743 29912 29971 D RefreshFolderOperation: Send broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED
03-19 00:37:24.748 29912 29912 D FileDisplayActivity: Received broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED
03-19 00:37:24.787 29912 29912 D FileDisplayActivity: Setting progress visibility to false
03-19 00:37:24.868  1321  2875 D InputDispatcher: notifyMotion - action=ACTION_DOWN(0), id=0, tooltype=1, deviceId=4, source=0x1002, policyFlags=0x0, flags=0x0, metaState=0x0, buttonState=0x0, edgeFlags=0x0, eventTime=105169966644000, downTime=105169966644000,
03-19 00:37:24.868  1321  2874 D InputTransport: channel 'ff1d008 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity (server)' : action=ACTION_DOWN(0), id=0, tooltype=1, deviceId=4, source=0x1002, flags=0x0, edgeFlags=0x0, metaState=0x0, buttonState=0x0, downTime=105169966644000, eventTime=105169966644000, pointerCount=1
03-19 00:37:24.868 29912 29912 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
03-19 00:37:24.869  1321  2874 D PowerManagerServiceAO: updateUserActivitySummaryLocked: mBaseService.mWakefulness=Awake, mUserActivitySummary=0x1, nextTimeout=93213407 (11956561 ms ago)
03-19 00:37:24.900  1321  2875 D InputDispatcher: notifyMotion - action=ACTION_UP(0), id=0, tooltype=1, deviceId=4, source=0x1002, policyFlags=0x0, flags=0x0, metaState=0x0, buttonState=0x0, edgeFlags=0x0, eventTime=105169999123000, downTime=105169966644000,
03-19 00:37:24.900  1321  2874 D InputTransport: channel 'ff1d008 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity (server)' : action=ACTION_UP(0), id=0, tooltype=1, deviceId=4, source=0x1002, flags=0x0, edgeFlags=0x0, metaState=0x0, buttonState=0x0, downTime=105169966644000, eventTime=105169999123000, pointerCount=1
03-19 00:37:24.902 29912 29912 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
03-19 00:37:25.001 29912 29912 D AndroidRuntime: Shutting down VM
03-19 00:37:25.003 29912 29912 E AndroidRuntime: FATAL EXCEPTION: main
03-19 00:37:25.003 29912 29912 E AndroidRuntime: Process: com.nextcloud.client, PID: 29912
03-19 00:37:25.003 29912 29912 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Invalid index 5, size is 1
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at java.util.ArrayList.get(ArrayList.java:308)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.widget.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:164)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.widget.AbsListView.onInitializeAccessibilityNodeInfoForItem(AbsListView.java:2525)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.widget.ListView.onInitializeAccessibilityNodeInfoForItem(ListView.java:3949)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.widget.AbsListView$ListItemAccessibilityDelegate.onInitializeAccessibilityNodeInfo(AbsListView.java:2452)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.view.View.onInitializeAccessibilityNodeInfo(View.java:6079)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.view.View.createAccessibilityNodeInfoInternal(View.java:6040)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:22348)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.view.View.createAccessibilityNodeInfo(View.java:6023)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:145)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.view.View.onInitializeAccessibilityEventInternal(View.java:5977)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.view.View$AccessibilityDelegate.onInitializeAccessibilityEvent(View.java:22260)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.view.View.onInitializeAccessibilityEvent(View.java:5963)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5830)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:22199)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.view.View.sendAccessibilityEventUnchecked(View.java:5813)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.view.View.sendAccessibilityEventInternal(View.java:5792)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.view.View$AccessibilityDelegate.sendAccessibilityEvent(View.java:22157)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.view.View.sendAccessibilityEvent(View.java:5757)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.widget.AdapterView.performItemClick(AdapterView.java:317)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.widget.AbsListView.performItemClick(AbsListView.java:1188)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3100)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.widget.AbsListView$3.run(AbsListView.java:4091)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5525)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
03-19 00:37:25.003 29912 29912 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
03-19 00:37:25.006  1321  3364 W ActivityManager:   Force finishing activity com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity
03-19 00:37:25.007  1321  3364 V WindowManager: Set focused app to: AppWindowToken{4e23e2b token=Token{fdea67a ActivityRecord{c4b52a5 u0 com.lge.launcher2/.Launcher t1876}}} old focus=AppWindowToken{45ee1bc token=Token{d917224 ActivityRecord{ea4bab7 u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity t2069}}} moveFocusNow=true
03-19 00:37:25.008  1321  3364 V WindowManager: Looking for focus: 13 = Window{5e9a4f1 u0 StatusBar}, flags=-2122055608, canReceive=false
```

**Comment by AndyScherzinger** [comment] 2017-03-19 09:53
Hi @Bullnados this is already documented in #251 while this has been in the app ever since the fork and even I guess for quite a while in the ownCloud Android app. So closing this one in favor of the older issue already open. @mario @tobiasKaminsky any idea how to reproduce this? I tried again browsing through my folders like a monkey but no crashes ever (since version 1.0 I never had one!) while I have to say I am running Android 7+ (which is probably the "fix")

I checked the Play console and it is one of the most reported issues but it is also a Android 6 only reported issue (no other Android version reported this issue!!!)

**Closed by AndyScherzinger** 2017-03-19 09:53 UTC
