### ISSUE TITLE
App crashes when trying to select details or share for a file or directory

### ISSUE THREAD

**Issue by mikoladz** [nextcloud/android#13632] opened 2024-09-26 20:02 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open the app and tap the options menu for any file or directory.
2. Select share or details from the menu.

### Expected behaviour

The app shows the details of the file or directory or presents options for sharing (select user etc.)

### Actual behaviour

The app crashes with a crash report.

### Android version

Android 14

### Device brand and model

Google Pixel 8

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.30.0

### Nextcloud server version

29.0.7

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
    at com.owncloud.android.datamodel.OCFile.isInternalFolderSync(OCFile.java:1058)
    at com.owncloud.android.datamodel.FileDataStorageManager.isPartOfInternalTwoWaySync(FileDataStorageManager.java:2504)
    at com.owncloud.android.ui.fragment.FileDetailFragment.updateFileDetails(FileDetailFragment.java:572)
    at com.owncloud.android.ui.fragment.FileDetailFragment.onViewCreated(FileDetailFragment.java:266)
    at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3152)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:608)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2059)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:702)
    at android.os.Handler.handleCallback(Handler.java:959)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8592)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300090`
* Build flavor: `generic`

### Device information
* Brand: `google`
* Device: `shiba`
* Model: `Pixel 8`
* Id: `AP2A.240705.005`
* Product: `shiba`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `eng.root.20240827.184412`

### Additional information

Android 14/Lineage OS 21-20240827-microG-shiba

**Comment by joshtrichards** [comment] 2024-09-27 00:24
Duplicate of #13502

**Closed by joshtrichards** 2024-09-27 00:24 UTC
Labels: bug, 0. Needs triage
