### ISSUE TITLE
There are no descriptions in strings.xml

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#3647] opened 2019-02-18 11:10 UTC
None to be translated into transifex:
`Retry failed uploads`
`Clear successful uploads`
`Force rescan`

**None in the file** `strings.xml`.

From this `Uploads` editing menu there is only:
`<string name="action_clear_failed_uploads">Clear failed uploads</string>`.

### Actual behaviour
- There are no translated menu descriptions in `Uploads` edition.

### Expected behaviour
- Translated descriptions in the application in the `Uploads` edition.
 
### Steps to reproduce
1. Open from the menu `Uploads`.
2. Open the edit menu with `:`.

### Environment data
Android version:
Android 6

Nextcloud app version:
3.5.0

**Comment by AndyScherzinger** [comment] 2019-02-18 11:25
Duplicate of #3626 while the strings are already gone (for the next release 3.6.0) and @tobiasKaminsky is looking into a way to fix such constellations where the development has already further progressed than the next stable release (which is what happened for 3.5.x)

**Closed by AndyScherzinger** 2019-02-18 11:25 UTC
Labels: bug

**Comment by Valdnet** [comment] 2019-02-18 12:12
@AndyScherzinger thanks 👍 

@tobiasKaminsky I have a question. The edition of translated subtitles is blocked in Transifex. How can you change a bad description?
Descriptions in Polish translation must change: https://github.com/nextcloud/android/blob/master/src/main/res/values-pl/strings.xml
`<string name="drawer_item_trashbin">Usunięto pliki</string>` ->
`<string name="drawer_item_trashbin">Usunięte pliki</string>`

`<string name="trashbin_activity_title">Usunięto pliki</string>` ->
`<string name="trashbin_activity_title">Usunięte pliki</string>`

`<string name="action_empty_trashbin">Pusty kosz</string>` ->
`<string name="action_empty_trashbin">Opróżnij kosz</string>`

**Comment by AndyScherzinger** [comment] 2019-02-18 12:40
@Valdnet what is your user/name on transifex? I can then add you as a reviewer to the Polish language. This way you can change reviewed strings :)

**Comment by Valdnet** [comment] 2019-02-18 13:03
@AndyScherzinger my login for Transifex is Valdnet.
Thanks 😉

**Comment by AndyScherzinger** [comment] 2019-02-18 14:20
@Valdnet Done, you should have gotten a reviewer invitation 😃

**Comment by Valdnet** [comment] 2019-02-18 14:56
@AndyScherzinger thanks. It was missing 😉

**Comment by Valdnet** [comment] 2019-02-21 09:15
@AndyScherzinger why can not I translate new descriptions into Polish in transifex:
```
Could not sync 1%$d files (conflicts: 2%$d)
Failed to copy 1%$d files from the 2%$d folder into
1%$d folders
1%$d files
%d selected
```

**Comment by AndyScherzinger** [comment] 2019-02-21 12:55
did you check that for these that you need to translate them "twice" for "1" and for "other", if both values are translated, than it can be saved, else it can't

**Comment by Valdnet** [comment] 2019-02-21 13:04
Sorry for the problem. I overlooked "few" and "many" 😉
