### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by PapyPoc** [nextcloud/android#7363] opened 2020-11-18 18:22 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{686615d u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWJNY
Model: JNY-LX1
Id: HUAWEIJNY-L21
Product: JNY-LX1

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.1.0.243C432

**Comment by it4csl** [comment] 2020-11-18 20:23
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{69b2820 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1978)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7565)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: POCO
Device: surya
Model: M2007J20CG
Id: QKQ1.200512.002
Product: surya_global

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.4.0.QJGMIXM

**Comment by tobiasKaminsky** [comment] 2020-11-19 07:24
Duplicate of #7364, and others.

**Closed by tobiasKaminsky** 2020-11-19 07:24 UTC
Labels: bug
