### ISSUE TITLE
App Crashes in start

### ISSUE THREAD

**Issue by achlys75** [nextcloud/android#7715] opened 2020-12-22 10:26 UTC
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: Shiftphone 6qm

Stock or customized system: custom

Nextcloud app version: dev20201215 20201216

Nextcloud server version: 19.0.6

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lokio/Buffer;
	at okhttp3.ResponseBody.create(ResponseBody.java:210)
	at okhttp3.internal.Util.<clinit>(Util.java:62)
	at okhttp3.Credentials.basic(Credentials.java:30)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:330)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:304)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:276)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: okio.Buffer
	... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201216
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: SHIFT
Device: axolotl
Model: SHIFT6mq
Id: QQ2A.200501.001.B3
Product: axolotl

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 20201111

**Comment by AndyScherzinger** [comment] 2020-12-22 10:35
Duplicate of #7699

**Comment by AndyScherzinger** [comment] 2020-12-22 10:35
Thanks for the report @achlys75, fix will ship with the next dev build

**Closed by AndyScherzinger** 2020-12-22 10:35 UTC
Labels: bug
