### ISSUE TITLE
App opens itself and crashes then

### ISSUE THREAD

**Issue by Flole998** [nextcloud/android#4556] opened 2019-09-26 01:28 UTC
Since the last update I get random crashes out of nowhere, the App opens itself and displays this message:

************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.SecurityException: Caller no longer running, last stopped +3s780ms because: timed out while starting
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:195)
	at android.app.job.JobParameters.dequeueWork(JobParameters.java:243)
	at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
	at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobServiceContext.assertCallerLocked(JobServiceContext.java:481)
	at com.android.server.job.JobServiceContext.doDequeueWork(JobServiceContext.java:359)
	at com.android.server.job.JobServiceContext$JobCallback.dequeueWork(JobServiceContext.java:160)
	at android.app.job.IJobCallback$Stub.onTransact(IJobCallback.java:83)
	at android.os.Binder.execTransact(Binder.java:752)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus3
Model: ONEPLUS A3003
Id: PKQ1.181203.001
Product: OnePlus3

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1907311932

Also sometimes the App opens itself to ask for Fingerprint/Password. It doesn't accept the password fingerprint though and asks again. This happened 10 times while writing this.

**Comment by Flole998** [comment] 2019-10-25 00:32
All Details already provided, so this is just a *push*

**Comment by tobiasKaminsky** [comment] 2019-10-25 11:31
Do you have battery saving mechanism enabled?

**Comment by Flole998** [comment] 2019-10-25 11:33
Yes that is enabled and nextcloud is not on the exception list at the moment.

**Comment by Flole998** [comment] 2019-11-22 13:39
Not stale

**Comment by myroad94** [comment] 2019-12-24 23:48
Hi, do we have some workaround? Maybe putting nextcloud on the whitelist of battery mechanism, or reverting to an old version (which one)?

**Comment by tobiasKaminsky** [comment] 2020-04-14 06:17
Duplicate of #5805

**Closed by tobiasKaminsky** 2020-04-14 06:17 UTC
Labels: approved, bug
