### ISSUE TITLE
Automatic upload on android app for large amount of conflicts hangs 

### ISSUE THREAD

**Issue by burner-** [nextcloud/android#6906] opened 2020-09-08 08:22 UTC
### Steps to reproduce
1. Cause lot of conflicts
2. Enable auto resolve by overwriting
3. Enable "Also upload exsisting files

### Expected behaviour
- App should slowly upload all files one by one

### Actual behaviour
- App stop uploading anything. If I open uploads window to foreground it hangs.

Most probably app will do all checkings and uploads in one tight loop without yielding ui thread between each file/operation.

**Comment by burner-** [comment] 2020-09-08 10:19
Hmm actually now I play around two more hours with this and looks that thing is that if I remove autoupload from folder what is not fullu synced some of uploads will stay in queue. When that autoupload try upload that kind file it goes to "waiting for wifi" state  and then application hangs. So those conficted files most probably does not have nothing to do with this problem but real problem is those files what are queue but their folder autoupload setting is disabled.

**Comment by tobiasKaminsky** [comment] 2020-09-10 06:04
This is solved with next version, or with 3.13.1 RC1 which is in beta phase.

Duplicate of #6887

**Closed by tobiasKaminsky** 2020-09-10 06:04 UTC
Labels: bug
