### ISSUE TITLE
Unexpected Crash 

### ISSUE THREAD

**Issue by kpleines** [nextcloud/android#5170] opened 2020-01-13 06:58 UTC
### Steps to reproduce
1. Don't know exactly. App opened the crash log automatically 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens
App opened the log window 
### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Nextcloud android app logs

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/data/app/com.nextcloud.client-0Un1KqLaHTXQZseztMLqSg==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-0Un1KqLaHTXQZseztMLqSg==/lib/arm64, /data/app/com.nextcloud.client-0Un1KqLaHTXQZseztMLqSg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: hero2lte
Model: SM-G935F
Id: R16NW
Product: hero2ltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G935FXXS7ESK7

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-01-13 15:59
duplicate of #4675

**Closed by AndyScherzinger** 2020-01-13 15:59 UTC
Labels: bug
