### ISSUE TITLE
Trying to add account keeps crashing

### ISSUE THREAD

**Issue by TengoMan** [nextcloud/android#14172] opened 2024-12-12 21:37 UTC
### Cause of error
```java
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property currentAccount has not been initialized
    at com.nextcloud.client.mixins.SessionMixin.getCurrentAccount(SessionMixin.kt:32)
    at com.nextcloud.client.mixins.SessionMixin.onRestart(SessionMixin.kt:100)
    at com.nextcloud.client.mixins.MixinRegistry.onRestart(MixinRegistry.kt:48)
    at com.owncloud.android.ui.activity.BaseActivity.onRestart(BaseActivity.java:118)
    at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1466)
    at android.app.Activity.performRestart(Activity.java:8294)
    at android.app.ActivityThread.performRestartActivity(ActivityThread.java:5347)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:244)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2260)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:299)
    at android.app.ActivityThread.main(ActivityThread.java:8168)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `Redmi`
* Device: `sweet`
* Model: `M2101K6G`
* Id: `SKQ1.210908.001`
* Product: `sweet_eea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `V13.0.16.0.SKFEUXM`

**Comment by joshtrichards** [comment] 2024-12-28 15:00
Duplicate of #13241

**Closed by joshtrichards** 2024-12-28 15:00 UTC
Labels: 0. Needs triage
