### ISSUE TITLE
error

### ISSUE THREAD

**Issue by william-ling** [nextcloud/android#13531] opened 2024-09-08 04:24 UTC
### Cause of error
```java
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property currentAccount has not been initialized
    at com.nextcloud.client.mixins.SessionMixin.getCurrentAccount(SessionMixin.kt:32)
    at com.nextcloud.client.mixins.SessionMixin.onRestart(SessionMixin.kt:100)
    at com.nextcloud.client.mixins.MixinRegistry.onRestart(MixinRegistry.kt:48)
    at com.owncloud.android.ui.activity.BaseActivity.onRestart(BaseActivity.java:118)
    at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1480)
    at android.app.Activity.performRestart(Activity.java:8243)
    at android.app.ActivityThread.performRestartActivity(ActivityThread.java:5440)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:244)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:233)
    at android.os.Looper.loop(Looper.java:344)
    at android.app.ActivityThread.main(ActivityThread.java:8186)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OP516EL1`
* Model: `NE2210`
* Id: `SKQ1.211019.001`
* Product: `NE2210`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `S.202203062359`

**Comment by joshtrichards** [comment] 2024-09-09 12:04
Duplicate of #13241

**Closed by joshtrichards** 2024-09-09 12:04 UTC
