### ISSUE TITLE
"Ghost" copies of (picture) files after upload

### ISSUE THREAD

**Issue by masteralarm** [nextcloud/android#6558] opened 2020-07-27 18:30 UTC
When uploading a picture, a ghostfile in `/storage/emulated/0/Pictures` appears, shown in gallery apps, having the same name as the uploaded file. Apps show no preview and can't open the file. File explorer shows that there is actually no file with that name there. Deleting the file in the gallery apps somehow works (ghostfile no longer shown).

Might be connected to #6150 (media scanner in Android 10)?

### Steps to reproduce
1. Take picture
2. Check picture in Google Gallery or Gallery Go App
3. Upload picture to nextcoud (auto-upload or manually)
4. Check pictures in Google Gallery or Gallery Go App
5. New picture and "ghost" picture appear in Gallery App 

### Expected behaviour
- No "ghost" files should appear

### Actual behaviour
- "Ghost" files appear

### Environment data
Android version: 10

Device model: Pixel 4

Stock or customized system: Stock

Nextcloud app version: 3.12.1

Nextcloud server version: 19

**Comment by invario** [comment] 2020-07-29 05:55
I have been experiencing this as well.

**Comment by invario** [comment] 2020-08-01 12:56
Doing as massive autoupload op right now and these files keep popping in and out of existence.

![Screenshot_20200801-085408_Gallery](https://user-images.githubusercontent.com/67800603/89102183-abf97000-d3d4-11ea-80b2-78de0b2b9b3d.jpg)
![Screenshot_20200801-085354_Gallery](https://user-images.githubusercontent.com/67800603/89102184-ac920680-d3d4-11ea-9d98-b65fc9845b8e.jpg)
![Screenshot_20200801-085547_Gallery](https://user-images.githubusercontent.com/67800603/89102205-cfbcb600-d3d4-11ea-92ac-90590d330b5e.jpg)

**Comment by tobiasKaminsky** [comment] 2020-08-05 13:52
>     3\. Upload picture to nextcoud (auto-upload or manually)

Do you move the file? Or is it only copied while uploading?

**Comment by masteralarm** [comment] 2020-08-05 14:09
> > ```
> > 3\. Upload picture to nextcoud (auto-upload or manually)
> > ```
> 
> Do you move the file? Or is it only copied while uploading?

I do not move the file. And it seems it is only copied while uploading. 

I also tried to look into the _Pictures_ folder while the upload is running, but file explorer does not show the new file there (neither while uploading nor afterwards)

**Comment by invario** [comment] 2020-08-07 02:10
> > > ```
> > > 3\. Upload picture to nextcoud (auto-upload or manually)
> > > ```
> > 
> > 
> > Do you move the file? Or is it only copied while uploading?
> 
> I do not move the file. And it seems it is only copied while uploading.
> 
> I also tried to look into the _Pictures_ folder while the upload is running, but file explorer does not show the new file there (neither while uploading nor afterwards)

Yes, I noticed this too. But try this in the file explorer or manager: search for one of the ghost files by the filename. You will find a zero byte file in the Pictures folder. Very strange.

**Comment by masteralarm** [comment] 2020-08-08 14:25
Strange, now the 0-byte files are actually shown even in die Files-App, creation date seems to be set to start of Unix epoch.![Screenshot_20200808-162330.png](https://user-images.githubusercontent.com/1875852/89712846-c82c7c80-d993-11ea-9f0e-5048014a232a.png)

**Comment by invario** [comment] 2020-08-09 02:07
![20200808_220630](https://user-images.githubusercontent.com/67800603/89723383-76034f80-d9c3-11ea-801e-3151c6838752.jpg)
Here's mine just now.  The files seem to randomly delete themselves eventually.

**Comment by tobiasKaminsky** [comment] 2020-08-27 05:30
So the original file seems to remain.
When we move original file to NC folder, we do a regular move on file system, so I do not understand why the 0 byte remains…

**Comment by Natalcia** [comment] 2020-08-27 06:46
These files don't actually exist in filesystem, but only in android media storage or whatever it is called.  It also happens when I have setup autoupload to keep original file in original path. 
And as I said in another issue, these galleries always show /storage/emulated/0/Pictures/(correct name) path even if I uploaded from for example /storage/emulated/0/Download

**Comment by invario** [comment] 2020-08-31 01:55
Yes, exactly. It doesn't matter where the photo is originally. The ghost 0 byte file is ALWAYS created in the Pictures folder shown above.

**Comment by Natalcia** [comment] 2020-10-20 14:15
I've uploaded few files today for test and looks like ghost files aren't appearing now on latest build? Can someone else confirm?

**Comment by antoinevth** [comment] 2020-11-12 08:38
I still have this issue with a Huawei Mate 20 Pro running Android 10 with Nextcloud app 3.13.1.

**Comment by aqaqsubin** [comment] 2020-11-12 12:34
The same error continues to appear for me. 

- Device Model : SamSung Galaxy S9 
- Android version : Android 10 
- Nextcloud app version : NextCloud App 3.13.1
![image](https://user-images.githubusercontent.com/28510311/98940807-e1af0880-252e-11eb-92ef-43e51e00ab2b.png)

**Comment by dmitry-podporinov** [comment] 2020-11-18 13:28
As temporary solutions - downgrading client to version 3.11 resolves this issue.

**Comment by zhanghai** [comment] 2022-04-02 11:41
I've  been debugging this at https://github.com/zhanghai/MaterialFiles/issues/740 and found this issue via a search. FYI I think might have figured out the root cause - it's a bug in the new `ModernMediaScanner` in Android 10 that prevents media scanning from removing files that no longer exists, and the bug is fixed in Android 11. The fix is https://cs.android.com/android/_/android/platform/packages/providers/MediaProvider/+/637d133d90f49dd18bda5de219184bfa9d6c2deb if anyone is interested.

**Comment by zhanghai** [comment] 2022-04-02 15:04
Please see https://github.com/zhanghai/MaterialFiles/commit/5a9bf48958c531ac37cfeb98455674cbb1c065d4 for a workaround of this issue. Note that if you don't want hidden API access, you may copy the `MediaStore.getVolumeName(File)` implementation into your app from [its source code](https://android.googlesource.com/platform/frameworks/base/+/android10-release/core/java/android/provider/MediaStore.java#1493).

**Comment by AlvaroBrey** [comment] 2022-04-04 08:20
> I've been debugging this at [zhanghai/MaterialFiles#740](https://github.com/zhanghai/MaterialFiles/issues/740) and found this issue via a search. FYI I think might have figured out the root cause - it's a bug in the new `ModernMediaScanner` in Android 10 that prevents media scanning from removing files that no longer exists, and the bug is fixed in Android 11. The fix is https://cs.android.com/android/_/android/platform/packages/providers/MediaProvider/+/637d133d90f49dd18bda5de219184bfa9d6c2deb if anyone is interested.
> 
> I'm stil trying to find a workaround for this system bug.

Thank you for this info, however our bug is most likely not caused by that, but instead is the same as https://github.com/nextcloud/android/issues/9328, which is causes by trying to scan files that are in Nextcloud's private directory.

**Comment by AlvaroBrey** [comment] 2022-06-15 14:45
Fixed in #10353

**Closed by AlvaroBrey** 2022-06-15 14:45 UTC
Labels: bug, approved

**Comment by SebStaeubert** [comment] 2024-04-07 10:30
This issue appears again in Android 14. ref
See https://github.com/nextcloud/android/issues/10353#issuecomment-2041382765

**Comment by rexxmagnus** [comment] 2024-04-07 14:38
I'm also experiencing this, trying to sync a pdf from the server to android so I can open it. It downloads the file and ends up creating it with 0 byte size and won't open. I have removed and re-added my nextcloud account just to rule out an issue with a recently changed password.

**Comment by anytimesoon** [comment] 2024-04-07 19:37
I'm having the same thing on android 14 on app version 3.28.1

**Comment by SebStaeubert** [comment] 2024-04-09 14:31
Can anybody reopen the issue?

**Comment by rnalrd** [comment] 2024-04-09 14:37
Same problem here, Android 14, v3.28.1

**Comment by rnalrd** [comment] 2024-04-09 14:56
Looks like that this is issue is now tracked here: https://github.com/nextcloud/android/issues/12822 and fixed in 3.28.2

**Comment by SebStaeubert** [comment] 2024-04-09 15:02
3.28.2 is not released yet. But i will report here after release 3.28.2 is available.

**Comment by brvier** [comment] 2024-04-14 07:22
Same here, empty file on download on Android 10 P30 Pro, nextcloud 3.28.1
