### ISSUE TITLE
Crash on change folder after sharing

### ISSUE THREAD

**Issue by AlbrechtK** [nextcloud/android#11511] opened 2023-04-08 09:21 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Share from any android app to next cloud android app
2. Change folder in next cloud app
3. Crash of android next cloud app

### Expected behaviour

No crash

### Actual behaviour

Crash 

### Android version

12

### Device brand and model

Pixel 3a

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.2

### Nextcloud server version

25.0.3

### Using a reverse proxy?

No

### Server error logs

```bash
### Cause of error

Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.canWrite()' on a null object reference
    at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onCreateOptionsMenu(ReceiveExternalFilesActivity.java:1034)
    at android.app.Activity.onCreatePanelMenu(Activity.java:4280)
    at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:521)
    at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3429)
    at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
    at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
    at android.view.Choreographer.doCallbacks(Choreographer.java:845)
    at android.view.Choreographer.doFrame(Choreographer.java:775)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)



### App information
* ID: `com.nextcloud.client`
* Version: `30240290`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `sargo`
* Model: `Pixel 3a`
* Id: `SP2A.220505.008`
* Product: `sargo`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `8782922`
```

**Comment by joshtrichards** [comment] 2023-04-09 15:07
Are you using E2E (encryption) by chance?

**Comment by joshtrichards** [comment] 2023-04-09 15:16
Dup of #9321 ?

**Comment by AlbrechtK** [comment] 2023-04-09 17:10
No, no  folder e2e protection (https://nextcloud.com/endtoend/) active.

**Comment by joshtrichards** [comment] 2023-10-07 22:41
Duplicate of #9321

**Closed by joshtrichards** 2023-10-07 22:41 UTC
Labels: bug
