### ISSUE TITLE
Delete file 30/60/90 days after auto uploaded

### ISSUE THREAD

**Issue by AlexandreMarkus** [nextcloud/android#13303] opened 2024-07-20 12:03 UTC
### Describe the solution you'd like

I would like to be able to select to delete the auto uploaded file after some days (30,60,90) in order the free up space on my device.

### Additional context

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by joshtrichards** [comment] 2024-07-20 20:22
Duplicate of #2323

**Comment by joshtrichards** [comment] 2024-07-20 20:23
I suggest subscribing to that issue and, perhaps, upvoting :+1: it for prioritization.

**Closed by joshtrichards** 2024-07-20 20:23 UTC
