### ISSUE TITLE
Nextcloud wont auto-delete synched files

### ISSUE THREAD

**Issue by ACCGAGTT** [nextcloud/android#11104] opened 2022-11-28 02:19 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Latest version of NC for Android 3.22.3 and Android 13 TD1A.220804
2. Take a photo 
3. Wait for sync
4. Photo sync to server but the original stays on phone

### Expected behaviour

After syncing, the new picture should be deleted when the option to remove the picture from device is chosen.

### Actual behaviour

1. Latest version of NC for Android 3.22.3 and Android 13 TD1A.220804
2. Take a photo 
3. Wait for sync
4. Photo sync to server but the original stays on phone

### Android version

13 TD1A.220804

### Device brand and model

Pixel5 , Pixel 7 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.3

### Nextcloud server version

25.0.0

### Using a reverse proxy?

No

### Additional information

Not able to provide logs at the moment as no compatible computer available

**Comment by AlvaroBrey** [comment] 2022-11-28 12:21
Can't reproduce here, files are deleted correctly if "delete" is chosen as an option in the autoupload properties. 

Is your autoupload set to upload on wifi only?

**Comment by ACCGAGTT** [comment] 2022-11-28 14:46
> Can't reproduce here, files are deleted correctly if "delete" is chosen as an option in the autoupload properties.
> 
> Is your autoupload set to upload on wifi only? In fact, please take a screenshot of the autoupload folder settings for that folder, if possible.

Correct the delete option is chosen from each folder that is selected for automatic upload and I have upload on wifi de-selected as I want auto uploadeverywhere. This used to work flawlessly under Android 13 around mid October (I would love to give you the version number of that but still looking). Are you running **Android 13 TD1A.220804** ? I think something changed with the app itself around mid october. Kind chicken or the egg thing going on, not entirely sure it is the app vs os issue

`11-28 04:09:14.359  1741  1880 D ActivityManager: freezing 28782 com.nextcloud.client
11-28 04:41:09.010  1741  1741 D ActivityManager: sync unfroze 28782 com.nextcloud.client
11-28 06:44:58.958  1741  1880 D ActivityManager: freezing 28782 com.nextcloud.client
11-28 07:22:23.792  1741  1741 D ActivityManager: sync unfroze 28782 com.nextcloud.client
11-28 07:32:51.037  1741  1880 D ActivityManager: freezing 28782 com.nextcloud.client
11-28 07:49:36.790  1741  3725 D ActivityManager: sync unfroze 28782 com.nextcloud.client
11-28 07:49:38.094  1741  3726 W JobScheduler: Job didn't exist in JobStore: 5accfc8 #u0a312/291 com.nextcloud.client/androidx.work.impl.background.systemjob.SystemJobService
11-28 07:59:38.100  1741  1880 D ActivityManager: freezing 28782 com.nextcloud.client
11-28 08:04:36.822  1741  1741 D ActivityManager: sync unfroze 28782 com.nextcloud.client
11-28 08:14:36.874  1741  1880 D ActivityManager: freezing 28782 com.nextcloud.client
11-28 08:19:37.041  1741  1741 D ActivityManager: sync unfroze 28782 com.nextcloud.client
11-28 08:29:37.173  1741  1880 D ActivityManager: freezing 28782 com.nextcloud.client
11-28 08:34:37.333  1741  1741 D ActivityManager: sync unfroze 28782 com.nextcloud.client
11-28 08:34:37.381  1741  1756 W JobScheduler: Job didn't exist in JobStore: 3ad3439 #u0a312/290 com.nextcloud.client/androidx.work.impl.background.systemjob.SystemJobService
11-28 08:44:37.744  1741  1880 D ActivityManager: freezing 28782 com.nextcloud.client
11-28 08:49:16.315  1741  1775 D ActivityManager: sync unfroze 28782 com.nextcloud.client
11-28 09:01:54.525  1741  1880 D ActivityManager: freezing 28782 com.nextcloud.client
11-28 09:04:37.930  1741  1741 D ActivityManager: sync unfroze 28782 com.nextcloud.client
11-28 09:12:51.740  1741  2361 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity bnds=[228,330][435,645]} from uid 10218
11-28 09:12:51.789  1741  2319 D CoreBackPreview: Window{e5bf7d1 u0 Splash Screen com.nextcloud.client}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@eea7537, mPriority=0}
11-28 09:12:51.971  1741  2319 D CoreBackPreview: Window{6fcc5e7 u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@ac4383d, mPriority=0}
11-28 09:12:52.432  1741  5005 D CoreBackPreview: Window{e5bf7d1 u0 Splash Screen com.nextcloud.client EXITING}: Setting back callback null
11-28 09:12:57.804  1741  5005 I ActivityTaskManager: START u0 {cmp=com.nextcloud.client/com.owncloud.android.ui.activity.SettingsActivity} from uid 10312
11-28 09:12:57.871  1741  5034 D CoreBackPreview: Window{e36690a u0 com.nextcloud.client/com.owncloud.android.ui.activity.SettingsActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@fb12f98, mPriority=0}
11-28 09:12:59.681  1741  5005 I ActivityTaskManager: START u0 {cmp=com.nextcloud.client/com.owncloud.android.ui.activity.SyncedFoldersActivity} from uid 10312
11-28 09:12:59.757  1741  5034 D CoreBackPreview: Window{8b251cc u0 com.nextcloud.client/com.owncloud.android.ui.activity.SyncedFoldersActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@54c5b2a, mPriority=0}
11-28 09:13:02.281  1741  3144 D CoreBackPreview: Window{f6894bb u0 com.nextcloud.client/com.owncloud.android.ui.activity.SyncedFoldersActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@b17536d, mPriority=0}
11-28 09:13:11.851  1741  1755 D CoreBackPreview: Window{f6894bb u0 com.nextcloud.client/com.owncloud.android.ui.activity.SyncedFoldersActivity}: Setting back callback null
11-28 09:13:26.024  1741  5036 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:13:26.027  1741  5020 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:13:26.028  1741  5020 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:13:26.030  1741  5020 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:13:26.035  1741  5020 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:13:26.037  1741  5020 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:13:26.039  1741  5020 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:13:26.041  1741  5020 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:13:26.043  1741  5020 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:13:26.045  1741  5020 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:13:26.046  1741  5020 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:13:26.048  1741  5020 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:13:26.050  1741  5020 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:13:26.051  1741  5020 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:13:26.053  1741  5020 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:13:27.704  1741  3857 E NotificationService: Package enqueue rate is 5.0251217. Shedding 0|com.nextcloud.client|412|null|10312. package=com.nextcloud.client
11-28 09:13:32.343  1741  5034 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity bnds=[228,330][435,645]} from uid 10218
11-28 09:13:35.754  1741  4984 D CoreBackPreview: Window{8b251cc u0 com.nextcloud.client/com.owncloud.android.ui.activity.SyncedFoldersActivity}: Setting back callback null
11-28 09:13:36.025  1741  3857 W ActivityTaskManager: Duplicate finish request for r=ActivityRecord{1e45714 u0 com.nextcloud.client/com.owncloud.android.ui.activity.SettingsActivity} t206 f}}
11-28 09:13:36.640  1741  3855 D CoreBackPreview: Window{e36690a u0 com.nextcloud.client/com.owncloud.android.ui.activity.SettingsActivity}: Setting back callback null
11-28 09:13:38.365  1741  4984 I ActivityTaskManager: START u0 {flg=0x4000000 cmp=com.nextcloud.client/com.owncloud.android.ui.activity.UploadListActivity} from uid 10312
11-28 09:13:38.467  1741  4984 D CoreBackPreview: Window{729cab0 u0 com.nextcloud.client/com.owncloud.android.ui.activity.UploadListActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@b4e18ae, mPriority=0}
11-28 09:23:15.422 21403 21403 W ProcStatsManager: No process com.nextcloud.client/10312 for service com.owncloud.android.files.services.FileDownloader
11-28 09:23:15.422 21403 21403 W ProcStatsManager: No process com.nextcloud.client/10312 for service com.owncloud.android.services.OperationsService
11-28 09:23:15.422 21403 21403 W ProcStatsManager: No process com.nextcloud.client/10312 for service com.owncloud.android.files.services.FileUploader
11-28 09:23:15.422 21403 21403 W ProcStatsManager: No process com.nextcloud.client/10312 for service androidx.work.impl.background.systemjob.SystemJobService
11-28 09:23:15.661 21403 25194 W ProcStatsManager: No process com.nextcloud.client/10312 for service com.owncloud.android.files.services.FileDownloader
11-28 09:23:15.661 21403 25194 W ProcStatsManager: No process com.nextcloud.client/10312 for service com.owncloud.android.services.OperationsService
11-28 09:23:15.661 21403 25194 W ProcStatsManager: No process com.nextcloud.client/10312 for service com.owncloud.android.files.services.FileUploader
11-28 09:23:15.661 21403 25194 W ProcStatsManager: No process com.nextcloud.client/10312 for service androidx.work.impl.background.systemjob.SystemJobService
11-28 09:23:17.968 21403 25198 W ProcStatsManager: No process com.nextcloud.client/10312 for service com.owncloud.android.files.services.FileDownloader
11-28 09:23:17.968 21403 25198 W ProcStatsManager: No process com.nextcloud.client/10312 for service com.owncloud.android.services.OperationsService
11-28 09:23:17.968 21403 25198 W ProcStatsManager: No process com.nextcloud.client/10312 for service com.owncloud.android.files.services.FileUploader
11-28 09:23:17.968 21403 25198 W ProcStatsManager: No process com.nextcloud.client/10312 for service androidx.work.impl.background.systemjob.SystemJobService
11-28 09:32:51.143  1741  1880 D ActivityManager: freezing 28782 com.nextcloud.client
11-28 09:34:10.071  1741  1741 D ActivityManager: sync unfroze 28782 com.nextcloud.client
11-28 09:34:10.680 28782 28800 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=48403c64-31f2-4e0e-8618-8b23f2a03dbc, tags={ com.nextcloud.client.jobs.MediaFoldersDetectionWork, *, name:immediate_media_folder_detection, timestamp:1669646050174 } ]
11-28 09:34:12.110  1741  5034 W JobScheduler: Job didn't exist in JobStore: e59007f #u0a312/319 com.nextcloud.client/androidx.work.impl.background.systemjob.SystemJobService
11-28 09:34:12.449 28782 28810 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=fbe7a3cc-d98a-4a33-8566-4e1c52b4e601, tags={ com.nextcloud.client.jobs.MediaFoldersDetectionWork, *, timestamp:1669646052055, name:immediate_media_folder_detection } ]
11-28 09:34:13.327 28782 28813 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=b6d2b75a-3c15-42ee-8762-16764df4ae4a, tags={ com.nextcloud.client.jobs.FilesSyncWork, timestamp:1669646050160, *, name:immediate_files_sync } ]
11-28 09:34:15.343  1741  4984 E NotificationService: Package enqueue rate is 5.857375. Shedding 0|com.nextcloud.client|412|null|10312. package=com.nextcloud.client
11-28 09:34:15.813 28782 28822 D ChunkedFileUploadRemoteOperation: Upload of /data/user/0/com.nextcloud.client/files/nextcloud/tmp/me@192.168.1.25%3A9090/InstantUpload/Raw/2022/11/PXL_20221128_143408501.dng to /InstantUpload/Raw/2022/11/PXL_20221128_143408501.dng, chunk from 0000000000000000 to 0000000010239999 size: 10240000, HTTP result status 201
11-28 09:34:16.112 28782 28822 D ChunkedFileUploadRemoteOperation: Upload of /data/user/0/com.nextcloud.client/files/nextcloud/tmp/me@192.168.1.25%3A9090/InstantUpload/Raw/2022/11/PXL_20221128_143408501.dng to /InstantUpload/Raw/2022/11/PXL_20221128_143408501.dng, chunk from 0000000010240000 to 0000000013077566 size: 2837567, HTTP result status 201
11-28 09:34:16.520  3744  3961 I MediaProvider: Deleted 0 0 0 0 0 0 0 items on external_primary due to com.nextcloud.client
11-28 09:34:16.536  3744 28881 I MediaProvider: Deleted 0 0 0 0 0 0 0 items on external due to com.nextcloud.client
11-28 09:34:16.868 28782 28814 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=aa6ddd54-7cc1-4cf3-a57f-5857127ae218, tags={ timestamp:1669646053289, user:me@192.168.1.25:9090, com.nextcloud.client.jobs.FilesUploadWorker, *, name:files_upload me@192.168.1.25:9090 } ]
11-28 09:34:33.025 28782 28813 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=a0cdf804-c62c-4146-8c6e-0c91b77470cf, tags={ com.nextcloud.client.jobs.MediaFoldersDetectionWork, timestamp:1669646072521, *, name:immediate_media_folder_detection } ]
11-28 09:34:34.658 28782 28813 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=c0a55781-9e29-4a2e-a731-0139ac786790, tags={ com.nextcloud.client.jobs.MediaFoldersDetectionWork, timestamp:1669646074313, *, name:immediate_media_folder_detection } ]
11-28 09:34:35.903 28782 28810 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=db0bab87-c5f2-47e5-a571-a8f32778892f, tags={ timestamp:1669646072521, com.nextcloud.client.jobs.FilesSyncWork, *, name:immediate_files_sync } ]
11-28 09:34:36.971  1741  5035 E NotificationService: Package enqueue rate is 6.3172836. Shedding 0|com.nextcloud.client|412|null|10312. package=com.nextcloud.client
11-28 09:34:37.654 28782 28816 D ChunkedFileUploadRemoteOperation: Upload of /data/user/0/com.nextcloud.client/files/nextcloud/tmp/me@192.168.1.25%3A9090/InstantUpload/Raw/2022/11/PXL_20221128_143430945.dng to /InstantUpload/Raw/2022/11/PXL_20221128_143430945.dng, chunk from 0000000000000000 to 0000000010239999 size: 10240000, HTTP result status 201
11-28 09:34:37.808 28782 28816 D ChunkedFileUploadRemoteOperation: Upload of /data/user/0/com.nextcloud.client/files/nextcloud/tmp/me@192.168.1.25%3A9090/InstantUpload/Raw/2022/11/PXL_20221128_143430945.dng to /InstantUpload/Raw/2022/11/PXL_20221128_143430945.dng, chunk from 0000000010240000 to 0000000011647644 size: 1407645, HTTP result status 201
11-28 09:34:38.124  1741  1772 D ConnectivityService: requestNetwork for uid/pid:10312/28782 activeRequest: null callbackRequest: 1716 [NetworkRequest [ REQUEST id=1717, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10312 RequestorUid: 10312 RequestorPkg: com.nextcloud.client UnderlyingNetworks: Null] ]] callback flags: 0 order: 2147483647
11-28 09:34:38.133  1741  2034 D WifiNetworkFactory: got request NetworkRequest [ REQUEST id=1717, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10312 RequestorUid: 10312 RequestorPkg: com.nextcloud.client UnderlyingNetworks: Null] ]
11-28 09:34:38.134  1741  2034 D UntrustedWifiNetworkFactory: got request NetworkRequest [ REQUEST id=1717, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10312 RequestorUid: 10312 RequestorPkg: com.nextcloud.client UnderlyingNetworks: Null] ]
11-28 09:34:38.134  1741  2034 D OemPaidWifiNetworkFactory: got request NetworkRequest [ REQUEST id=1717, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10312 RequestorUid: 10312 RequestorPkg: com.nextcloud.client UnderlyingNetworks: Null] ]
11-28 09:34:38.134  1741  2034 D MultiInternetWifiNetworkFactory: got request NetworkRequest [ REQUEST id=1717, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10312 RequestorUid: 10312 RequestorPkg: com.nextcloud.client UnderlyingNetworks: Null] ]
11-28 09:34:38.153 28782 28810 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=de49b9f6-bb4a-4d5b-952a-2a2bf48a5ac3, tags={ timestamp:1669573662061, com.nextcloud.client.jobs.OfflineSyncWork, *, name:periodic_offline_sync } ]
11-28 09:34:38.237  3744  9389 I MediaProvider: Deleted 0 0 0 0 0 0 0 items on external_primary due to com.nextcloud.client
11-28 09:34:38.256  3744  1921 I MediaProvider: Deleted 0 0 0 0 0 0 0 items on external due to com.nextcloud.client
11-28 09:34:38.632 28782 28810 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=6c9420eb-9343-4371-81fb-17b81a0c0029, tags={ com.nextcloud.client.jobs.MediaFoldersDetectionWork, timestamp:1669573662067, *, name:periodic_media_folder_detection } ]
11-28 09:34:40.146 28782 28816 D ChunkedFileUploadRemoteOperation: Upload of /data/user/0/com.nextcloud.client/files/nextcloud/tmp/me@192.168.1.25%3A9090/InstantUpload/Camera/2022/11/PXL_20221128_143408501.jpg to /InstantUpload/Camera/2022/11/PXL_20221128_143408501.jpg, chunk from 0000000000000000 to 0000000004509840 size: 4509841, HTTP result status 201
11-28 09:34:40.421  3744  9394 I MediaProvider: Deleted 0 0 0 0 0 0 0 items on external_primary due to com.nextcloud.client
11-28 09:34:40.435  3744  9343 I MediaProvider: Deleted 0 0 0 0 0 0 0 items on external due to com.nextcloud.client
11-28 09:34:40.633 28782 28814 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=c2de48c3-bac4-4223-97b2-af8965f9f17b, tags={ timestamp:1669646075832, user:me@192.168.1.25:9090, com.nextcloud.client.jobs.FilesUploadWorker, *, name:files_upload me@192.168.1.25:9090 } ]
11-28 09:34:43.401 28782 28810 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=e724c557-02ba-45f4-98a3-d7c57d244c5d, tags={ name:periodic_files_sync, timestamp:1669608455663, com.nextcloud.client.jobs.FilesSyncWork, * } ]
11-28 09:34:50.820  1741  4979 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity bnds=[228,330][435,645]} from uid 10218
11-28 09:34:50.896 11302 11302 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1876 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.nextcloud.client fieldId=-1 fieldName=null extras=null}, false)
11-28 09:34:50.913 11302 11302 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1876 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.nextcloud.client fieldId=-1 fieldName=null extras=null}, false)
11-28 09:34:53.553 28782 28813 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=0f25a4d1-92c6-4860-8110-fa907c679e6d, tags={ com.nextcloud.client.jobs.FilesSyncWork, *, name:immediate_files_sync, timestamp:1669646093089 } ]
11-28 09:34:53.603 28782 28800 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=c7650906-ec11-4ff4-ab40-9a3acbc7ef8e, tags={ user:me@192.168.1.25:9090, timestamp:1669646083358, com.nextcloud.client.jobs.FilesUploadWorker, *, name:files_upload me@192.168.1.25:9090 } ]
11-28 09:34:53.624  1741  2173 W JobScheduler: Job didn't exist in JobStore: b9e1519 #u0a312/330 com.nextcloud.client/androidx.work.impl.background.systemjob.SystemJobService
11-28 09:34:56.031 28782 28810 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=d004597c-6e8f-46ce-a399-fe34c38e321c, tags={ timestamp:1669646095648, com.nextcloud.client.jobs.FilesSyncWork, *, name:immediate_files_sync } ]
11-28 09:34:56.549  1741  5015 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.550  1741  5020 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.551  1741  1773 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.552  1741  2291 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.615  1741  1773 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.617  1741  1773 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.619  1741  1773 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.621  1741  1773 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.623  1741  1773 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.624  1741  1773 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.626  1741  1773 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.628  1741  1773 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.629  1741  1773 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.632  1741  1773 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.634  1741  1773 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.636  1741  1773 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.637  1741  1773 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.639  1741  1773 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.640  1741  1773 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.641  1741  1773 E NotificationService: Package has already posted or enqueued 50 notifications.  Not showing more.  package=com.nextcloud.client
11-28 09:34:56.686  1741  2291 E NotificationService: Package enqueue rate is 5.338685. Shedding 0|com.nextcloud.client|412|null|10312. package=com.nextcloud.client
11-28 09:34:56.924 28782 28815 D ChunkedFileUploadRemoteOperation: Upload of /data/user/0/com.nextcloud.client/files/nextcloud/tmp/me@192.168.1.25%3A9090/InstantUpload/Camera/2022/11/PXL_20221128_143430945.jpg to /InstantUpload/Camera/2022/11/PXL_20221128_143430945.jpg, chunk from 0000000000000000 to 0000000003599156 size: 3599157, HTTP result status 201
11-28 09:34:57.254  3744  3957 I MediaProvider: Deleted 0 0 0 0 0 0 0 items on external_primary due to com.nextcloud.client
11-28 09:34:57.260  3744  9344 I MediaProvider: Deleted 0 0 0 0 0 0 0 items on external due to com.nextcloud.client
11-28 09:34:57.400 28782 28800 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=0e8f3673-37da-4eca-b606-ada5dbbcb831, tags={ timestamp:1669646096065, user:me@192.168.1.25:9090, com.nextcloud.client.jobs.FilesUploadWorker, *, name:files_upload me@192.168.1.25:9090 } ]
11-28 09:34:57.412  1741  5020 W JobScheduler: Job didn't exist in JobStore: 8bbe28b #u0a312/334 com.nextcloud.client/androidx.work.impl.background.systemjob.SystemJobService
11-28 09:35:06.882 11302 11302 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1876 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.nextcloud.client fieldId=-1 fieldName=null extras=null}, false)`

Looks like it tries to delete but does nothing: **11-28 09:34:57.254  3744  3957 I MediaProvider: Deleted 0 0 0 0 0 0 0 items on external_primary due to com.nextcloud.client
11-28 09:34:57.260  3744  9344 I MediaProvider: Deleted 0 0 0 0 0 0 0 items on external due to com.nextcloud.client**

**Comment by ACCGAGTT** [comment] 2022-12-02 22:58
were you able to reproduce?

**Comment by ACCGAGTT** [comment] 2022-12-11 21:51
any updates on this issue?

**Comment by AlvaroBrey** [comment] 2022-12-12 11:24
No updates so far and I wasn't able to reproduce. will have to come around to it at a later date

**Comment by tonytonyistony** [comment] 2023-01-07 06:54
Confirming Im having this issue as well. Just fresh install from the APK in this git.
```
Phone: Pixel6a
OS: GrapheneOS
All app permission allowed
Battery restrictions lifted
```
![image](https://user-images.githubusercontent.com/53504611/211135406-077b3bbc-c90a-4fbc-bbe9-cec5061f3db5.png)

**Comment by palegrand** [comment] 2023-02-01 07:42
same problem on a oneplus9pro (running LOS 20 / A13). Turned out I had to grant additional permissions (Storage)  in privacy - permission manager. App did not ask for it...
After setting that permission  both 'delete' and 'move to app' do work as expected

**Comment by tonytonyistony** [comment] 2023-02-04 20:06
My current setup.
![image](https://user-images.githubusercontent.com/53504611/216787495-b9bc3f88-88f7-408d-9e17-0acdf118ab4c.png)
![image](https://user-images.githubusercontent.com/53504611/216787505-339e44c0-075e-4ad4-8af6-8e5bf976dd39.png)

I went to what you were talking about
![image](https://user-images.githubusercontent.com/53504611/216787410-fbef8a68-b35c-4760-aea7-c5ec16059c53.png)
![image](https://user-images.githubusercontent.com/53504611/216787424-29157406-21e5-4289-9d50-56e78729ff30.png)
![image](https://user-images.githubusercontent.com/53504611/216787430-8dbdff90-2b68-4042-80c0-d9db521f190c.png)
![image](https://user-images.githubusercontent.com/53504611/216787441-0c320ca0-5a10-4310-92a9-91768cebeed7.png)

I have now enabled this setting. Will test again and report back.

**Comment by tonytonyistony** [comment] 2023-02-05 01:59
Id like to state that it seems the app works even though these messages prompt in my logs and the empty directories arent being deleted. But having to set my logs to critical only is not optimal for server management. If these errors are benign, maybe we could just downgrade these logs to info.

I would like to know why this app doesnt have permission to delete folder or why it thinks the folder isnt empty.

Thought: Is it possible the deletion process is happening too fast and the files are still present when it tries. Then the files are removed and its already moved to the next file?

**Comment by ACCGAGTT** [comment] 2023-02-05 02:45
> Id like to state that it seems the app works even though these messages prompt in my logs and the empty directories arent being deleted. But having to set my logs to critical only is not optimal for server management. If these errors are benign, maybe we could just downgrade these logs to warning.
> 
> I would like to know why this app doesnt have permission to delete folder or why it thinks the folder isnt empty.
> 
> Thought: Is it possible the deletion process is happening too fast and the files are still present when it tries. Then the files are removed and its already moved to the next folder?

I can confirm going through the Permission Manager solved the issue. The app is working now as intended. I believe the issue is the new way Android 13 manages permissions. The App doesnt ask to allow file access. I think this workaround solves the bug , but would still be nice if we could get a notification. Not sure if its the app responsibility or Androids to pop the prompt . Thanks to tony for pointing the Permission Manager

**Comment by joshtrichards** [comment] 2023-10-28 20:01
Closing this as the original reporter's issue was reported as fixed above. 

@tonytonyistony Those server-side errors are unrelated or something else... Either way they likely not a client matter. I suggest looking for Issues in https://github.com/nextcloud/server/ and reporting if you don't find one. It may have something to do with the underlying filesystem server-side - e.g. https://github.com/nextcloud/server/issues/17980

**Closed by joshtrichards** 2023-10-28 20:01 UTC
Labels: bug, feature: auto upload
