### ISSUE TITLE
Error  Feedback 

### ISSUE THREAD

**Issue by rotdrop** [nextcloud/android#11373] opened 2023-02-12 12:36 UTC
### Cause of error
```java
Exception in thread "Thread-7" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getDecryptedRemotePath()' on a null object reference
    at com.owncloud.android.utils.FileStorageUtils.checkEncryptionStatus(FileStorageUtils.java:468)
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:458)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:408)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:238)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:764)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230190`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `herolte`
* Model: `SM-G930F`
* Id: `R16NW`
* Product: `heroltexx`

### Firmware
* SDK: `26`
* Release: `8.0.0`
* Incremental: `G930FXXU8EVG3`

**Comment by AlvaroBrey** [comment] 2023-02-13 09:13
Duplicate of #11316

**Closed by AlvaroBrey** 2023-02-13 09:13 UTC
Labels: bug
