### ISSUE TITLE
Download notification/progress bar stays at 100%

### ISSUE THREAD

**Issue by alexjung** [nextcloud/android#8651] opened 2021-07-02 09:36 UTC
### Steps to reproduce
1. Synchronize a file (e.g. `.md`) on device (green check-mark on the file in the Nextcloud App).
2. Change the file on your computer or in the Nextcloud Web-Interface.
3. Nextcloud App automatically synchronizes the file and the download indicator/notification stays at 100% (and doesn't disappear) until another synchronized file is changed off-device and synchronized or the App is stopped via the App-Info menu.

### Expected behaviour
- The download notification should disappear as soon as the file is synchronized.

### Actual behaviour
- The download notification stays in the pull-down notification bar.
- The notification disappears if you stop the app from the App-Info menu or some other file gets changed off device and is synchronized.

### Can you reproduce this problem on https://try.nextcloud.com?
Yes I can. I created a test account and added it to the Android App. Synchronized the `Example.md` file on the device, changed it in the Web Interface and when the App downloads the changed version the notification stays there at 100%.

The notification even stays there after the test account was automatically deleted after one hour and I removed it from the Android App.

### Environment data
Android version: 11

Device model: Samsung S10 (SM-G973F/DS)

Stock or customized system: Stock

Nextcloud app version: 3.16.1

Nextcloud server version: 20.0.4

**Comment by AndyScherzinger** [comment] 2021-07-02 11:15
Duplicate of #8308

**Comment by AndyScherzinger** [comment] 2021-07-02 11:15
If everything goes according to plan than a fix ships with the next release! 🚀

**Closed by AndyScherzinger** 2021-07-02 11:15 UTC
Labels: bug
