### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dimitar8080** [nextcloud/android#10270] opened 2022-05-20 12:22 UTC
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.canWrite()' on a null object reference
    at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onCreateOptionsMenu(ReceiveExternalFilesActivity.java:1039)
    at android.app.Activity.onCreatePanelMenu(Activity.java:4346)
    at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:263)
    at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3106)
    at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
    at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
    at android.view.Choreographer.doCallbacks(Choreographer.java:866)
    at android.view.Choreographer.doFrame(Choreographer.java:792)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8663)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a52sxq`
* Model: `SM-A528B`
* Id: `SP1A.210812.016`
* Product: `a52sxqeea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `A528BXXS1CVD1`

**Comment by joshtrichards** [comment] 2023-04-09 15:12
Another dup of #9321 ?

**Comment by joshtrichards** [comment] 2023-10-07 22:39
Duplicate of #9321

**Closed by joshtrichards** 2023-10-07 22:39 UTC
Labels: bug
