### ISSUE TITLE
App ist suddenly crashing when running in background

### ISSUE THREAD

**Issue by Bodenseematze** [nextcloud/android#5889] opened 2020-04-16 10:04 UTC
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-QIafJp8i-2P9nNAtRqp-PA==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-QIafJp8i-2P9nNAtRqp-PA==/lib/arm64, /data/app/com.nextcloud.client-QIafJp8i-2P9nNAtRqp-PA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: bq
Device: zangyapro_sprout
Model: Aquaris X2 Pro
Id: PKQ1.190723.001
Product: zangyapro_bq

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1221

### Steps to reproduce
Unknown - the Nextcloud app is just running in the background - and when I switch my Screen on I see the crash message...

### Expected behaviour
- no crash should happen

### Environment data
Android version:
See above

Device model: 
See. above
Stock or customized system:
customized (Magisk)

Nextcloud app version:
See above

Nextcloud server version:
17.0.5

**Comment by tobiasKaminsky** [comment] 2020-04-16 10:47
Duplicate of #4675

**Closed by tobiasKaminsky** 2020-04-16 10:47 UTC
Labels: bug
