### ISSUE TITLE
Crash when copying flies rpi dietpi server from sd to USB drive

### ISSUE THREAD

**Issue by Sliglet** [nextcloud/android#13874] opened 2024-10-24 15:56 UTC
### Cause of error
```java
Exception in thread "Thread-36" java.lang.IllegalStateException: Couldn't read row 579, col 20 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetLong(Native Method)
    at android.database.CursorWindow.getLong(Unknown Source:9)
    at android.database.AbstractWindowedCursor.getLong(Unknown Source:7)
    at com.nextcloud.client.database.dao.FileDao_Impl.getFolderContent(FileDao_Impl.java:2025)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:919)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:227)
    at com.owncloud.android.datamodel.FileDataStorageManager.prepareRemoveSharesInFolder(FileDataStorageManager.java:1582)
    at com.owncloud.android.datamodel.FileDataStorageManager.saveSharesInFolder(FileDataStorageManager.java:1527)
    at com.owncloud.android.operations.RefreshFolderOperation.refreshSharesForFolder(RefreshFolderOperation.java:819)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:270)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:387)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `Redmi`
* Device: `veux`
* Model: `2201116SG`
* Id: `TKQ1.221114.001`
* Product: `veux_global`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `V816.0.3.0.TKCMIXM`

**Comment by joshtrichards** [comment] 2024-10-26 17:35
Duplicate of #13001

**Closed by joshtrichards** 2024-10-26 17:35 UTC
