### ISSUE TITLE
Nextcloud share with crash

### ISSUE THREAD

**Issue by AviationAce** [nextcloud/android#11420] opened 2023-02-26 14:54 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Just trying to use the Android share function in Gallery to copy a picture to a NC folder. 

### Expected behaviour

File gets copied to NC folder. 

### Actual behaviour

NC crashes. 

### Android version

13

### Device brand and model

Samsung Galaxy S22 Ultra

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.1

### Nextcloud server version

25.0.3

### Using a reverse proxy?

Yes

### Additional information

The log location do not show up in my File Manager

**Comment by AviationAce** [comment] 2023-02-26 15:01
![2023-02-26 08 51 30](https://user-images.githubusercontent.com/25482844/221418588-dd4b4889-2e24-48ea-a5c0-c552370fcbf9.jpg)

**Comment by strugee** [comment] 2023-03-01 00:15
Duplicate of #9613

**Closed by strugee** 2023-03-01 00:15 UTC
Labels: bug
