### ISSUE TITLE
IO error when opening Nextcloud activity tab

### ISSUE THREAD

**Issue by sowoi** [nextcloud/android#5508] opened 2020-02-23 14:22 UTC
I am using Nextcloud App v3.10.1 with Android 9 and Nextcloud Server 18.
Recently I noticed that I get an IO error when I try to open activity. Since I don't use those feature often, I am not sure when it first occured. Everything is working fine on my server itself and the logs doesn't state any issues.
The same issue is discussed here and marked as solved: https://help.nextcloud.com/t/io-error-android-app/69185/2
But I already have the newest  app installed on my device

**Comment by milu-milu** [comment] 2020-02-23 16:02
Same happens with android 10  and NC Server 18.0.1.
Android APP is the latest 3.10.1. Any suggestion?

**Comment by AndyScherzinger** [comment] 2020-02-24 12:24
Hi folk, can you post a stack-trace / error message please? ❤️

**Comment by milu-milu** [comment] 2020-02-24 15:15
Sorry, nothing happens... Only fet IO Error. App stucks accessing favorites...

************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:399)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
at java.util.TimSort.mergeHi(TimSort.java:899)
at java.util.TimSort.mergeAt(TimSort.java:516)
at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
at java.util.TimSort.sort(TimSort.java:254)
at java.util.Arrays.sort(Arrays.java:1492)
at java.util.ArrayList.sort(ArrayList.java:1470)
at java.util.Collections.sort(Collections.java:208)
at com.owncloud.android.utils.FileSortOrderByName.sortCloudFiles(FileSortOrderByName.java:52)
at com.owncloud.android.ui.adapter.OCFileListAdapter.setData(OCFileListAdapter.java:851)
at com.owncloud.android.ui.fragment.OCFileListFragment$3.doInBackground(OCFileListFragment.java:1584)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWELE
Model: ELE-L29
Id: HUAWEIELE-L29
Product: ELE-L29EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.186C431

**Comment by AndyScherzinger** [comment] 2020-02-24 17:00
@milu-milu that is another area and another issue not related to the initially reported error :/

**Comment by sowoi** [comment] 2020-02-24 17:02
Where/How du I get the stack trace on android?
Error message is just "IO error" and a blank activity tab.

**Comment by AndyScherzinger** [comment] 2020-02-24 21:09
That is tricky. It either crashes than a pop up should come up. Could you post a screenshot maybe? That might give @tobiasKaminsky a hint.

**Comment by milu-milu** [comment] 2020-02-25 07:02
![Screenshot_20200224_221103_com nextcloud client](https://user-images.githubusercontent.com/28803436/75222738-29291500-57a5-11ea-9fc5-7298b4cce30b.jpg)

**Comment by sowoi** [comment] 2020-02-25 07:27
![SmartSelect_20200225-082608_Nextcloud](https://user-images.githubusercontent.com/10256263/75224329-3394e000-57a0-11ea-9f79-6a66bd30afb7.jpg)

**Comment by AndyScherzinger** [comment] 2020-02-25 08:29
@tobiasKaminsky any ideas?

**Comment by milu-milu** [comment] 2020-03-20 09:45
Dear all,

recently I changed my installation from Apache with mod_php to NGINX and PHP-FPM...

And it works as expected. Thus I understand there is a mistake on the apache configuration.

Thanks,
  Saxa

**Comment by tobiasKaminsky** [comment] 2020-03-21 20:06
glad to here, thus closing.

**Closed by tobiasKaminsky** 2020-03-21 20:06 UTC
Labels: bug, needs info/discussion
