### ISSUE TITLE
Simpletask crashes randomly

### ISSUE THREAD

**Issue by ago** [nextcloud/android#7049] opened 2020-10-05 09:01 UTC
### Steps to reproduce
1. Open Simpletask.
2. Observe a crash occasionally. Couldn't find any particular steps to reproduce. 

### Expected behaviour
- No crashes. 

### Actual behaviour
- There are crashes.

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-z6asgEDONLTa7M_ErJ4cbQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-z6asgEDONLTa7M_ErJ4cbQ==/lib/arm64, /data/app/com.nextcloud.client-z6asgEDONLTa7M_ErJ4cbQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWANE
Model: ANE-LX1
Id: HUAWEIANE-L21
Product: ANE-LX1RU

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.315C10

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-10-05 14:47
Duplicate of #4675

**Comment by AndyScherzinger** [comment] 2020-10-05 14:47
fixed via #7030

**Closed by AndyScherzinger** 2020-10-05 14:47 UTC
Labels: bug
