### ISSUE TITLE
App looping on FirstRunActivity

### ISSUE THREAD

**Issue by ademar111190** [nextcloud/android#6155] opened 2020-05-26 13:03 UTC
### Steps to reproduce
1. Fresh install
2. Open the app
3. Touch the back button

### Expected behaviour
- The application should close

### Actual behaviour
- The app reopens the FirstRunActivity

### Environment data
Android version: 10

Device model: 
- Xiaomi mi A2 
- Emulator 

Stock or customized system:
- No

Nextcloud app version:
3.11.1

### Logs
![loop](https://user-images.githubusercontent.com/1225438/82903881-03dcac00-9f38-11ea-9c75-ade3d7ce566a.gif)

**Comment by joshtrichards** [comment] 2023-10-16 17:42
Duplicate of #11392 

The bulk of discussion about this functionality is going on over there so let's consolidate discussion/tracking there as well.

**Closed by joshtrichards** 2023-10-16 17:42 UTC
Labels: bug, approved
