### ISSUE TITLE
Error while disabling "Power Save Check" in the Auto Upload options: `android.content.res.Resources$NotFoundException: Resource ID #0x7f0a0403 type #0x12 is not valid`

### ISSUE THREAD

**Issue by Rex-0x7CB** [nextcloud/android#13922] opened 2024-10-31 09:31 UTC
### Cause of error
```java
Exception in thread "main" android.content.res.Resources$NotFoundException: Resource ID #0x7f0a0403 type #0x12 is not valid
    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2628)
    at android.content.res.Resources.getLayout(Resources.java:1337)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:542)
    at androidx.appcompat.app.AlertController.setupCustomContent(AlertController.java:644)
    at androidx.appcompat.app.AlertController.setupView(AlertController.java:475)
    at androidx.appcompat.app.AlertController.installContent(AlertController.java:233)
    at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:278)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:833)
    at android.app.Dialog.show(Dialog.java:453)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.showPowerCheckDialog(SyncedFoldersActivity.kt:233)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onDisablePowerSaveCheckClicked(SyncedFoldersActivity.kt:217)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onCreateOptionsMenu$lambda$1(SyncedFoldersActivity.kt:210)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.$r8$lambda$q58-_n5tvnvo7t7SwBQVBpaIAdU(Unknown Source:0)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$$ExternalSyntheticLambda4.onMenuItemClick(D8$$SyntheticClass:0)
    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:984)
    at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
    at android.widget.AdapterView.performItemClick(AdapterView.java:376)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1362)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3658)
    at android.widget.AbsListView.onTouchUp(AbsListView.java:4861)
    at android.widget.AbsListView.onTouchEvent(AbsListView.java:4556)
    at android.widget.ListView.onTouchEvent(ListView.java:1717)
    at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:230)
    at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:138)
    at android.view.View.dispatchTouchEvent(View.java:16225)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3322)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2982)
    at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:11397)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
    at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2890)
    at android.view.View.dispatchPointerEvent(View.java:16489)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8602)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:8353)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7682)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7739)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7705)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7908)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7713)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7965)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7686)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7739)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7705)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7713)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7686)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:11250)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:11119)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:11075)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:11384)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:337)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:335)
    at android.os.Looper.loopOnce(Looper.java:187)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8919)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300390`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `m33x`
* Model: `SM-M336BU`
* Id: `UP1A.231005.007`
* Product: `m33xins`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `M336BUXXS9EXH1`![Image](https://github.com/user-attachments/assets/b2dd4fbf-64e2-4807-b041-1a3f9f782a6a)

**Comment by joshtrichards** [comment] 2024-11-08 16:49
Duplicate of #13404

**Closed by joshtrichards** 2024-11-08 16:49 UTC
Labels: bug, feature: auto upload, stable-3.30
