### ISSUE TITLE
Please help, thanks

### ISSUE THREAD

**Issue by klemnjeklemn** [nextcloud/android#8962] opened 2021-09-09 18:08 UTC
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (Sqlite code 14), (OS error - 24:Too many open files)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:866)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:851)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
	at android.content.ContentResolver.query(ContentResolver.java:560)
	at android.content.ContentResolver.query(ContentResolver.java:476)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadStatus(UploadsStorageManager.java:196)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateDatabaseUploadStart(UploadsStorageManager.java:598)
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:612)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1402)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.os.HandlerThread.run(HandlerThread.java:61)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HONOR
Device: HNNEM-H
Model: NEM-L21
Id: HONORNEM-L21
Product: NEM-L21

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: C432B361

**Comment by AlvaroBrey** [comment] 2022-03-03 16:41
Duplicate of #9172

**Closed by AlvaroBrey** 2022-03-03 16:41 UTC
Labels: bug
