### ISSUE TITLE
Crash playing mp3

### ISSUE THREAD

**Issue by ecejuan** [nextcloud/android#8909] opened 2021-08-28 09:13 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{69311a4 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2240)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a50
Model: SM-A505FN
Id: RP1A.200720.012
Product: a50eea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: A505FNXXS9CUF1

**Comment by AlvaroBrey** [comment] 2021-09-07 10:47
Duplicate of #8686

**Closed by AlvaroBrey** 2021-09-07 10:47 UTC
Labels: bug
