### ISSUE TITLE
Nextcloud Android App Crash in Media View

### ISSUE THREAD

**Issue by mlsxlist** [nextcloud/android#10437] opened 2022-06-25 10:23 UTC
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Couldn't read row 845, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetString(Native Method)
    at android.database.CursorWindow.getString(CursorWindow.java:469)
    at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
    at android.database.CursorWrapper.getString(CursorWrapper.java:141)
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:957)
    at com.owncloud.android.datamodel.FileDataStorageManager.getGalleryItems(FileDataStorageManager.java:2224)
    at com.owncloud.android.datamodel.FileDataStorageManager.getAllGalleryItems(FileDataStorageManager.java:2169)
    at com.owncloud.android.ui.adapter.GalleryAdapter.showAllGalleryItems(GalleryAdapter.kt:149)
    at com.owncloud.android.ui.fragment.GalleryFragment.showAllGalleryItems(GalleryFragment.java:262)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.onPostExecute(GallerySearchTask.java:127)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.onPostExecute(GallerySearchTask.java:48)
    at android.os.AsyncTask.finish(AsyncTask.java:797)
    at android.os.AsyncTask.access$900(AsyncTask.java:195)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:814)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8668)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `HUAWEI`
* Device: `HWVOG`
* Model: `VOG-L29`
* Id: `HUAWEIVOG-L29`
* Product: `VOG-L29EEA`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `10.1.0.150C431`

**Comment by tobiasKaminsky** [comment] 2022-06-27 08:27
Might be fixable with #10213

**Comment by AlvaroBrey** [comment] 2022-06-27 08:59
Duplicate of #9948

**Closed by AlvaroBrey** 2022-06-27 08:59 UTC
Labels: bug
