### ISSUE TITLE
Extremely slow upload speed to server

### ISSUE THREAD

**Issue by windows10luke** [nextcloud/android#2761] opened 2018-06-26 23:03 UTC
### Actual behaviour
When uploading any size file, the chunk size is only 1MB and cannot be increased

### Expected behaviour
Increase the chunk size to 100MB or more for LANs or a custom number depending on network speed
 
### Steps to reproduce
1. Upload any size file in the app
2. Watch the tmp folder for small 1MB chunks of data

### Environment data
Android version:
8 (Oreo)
Device model: 
LG V30+
Stock or customized system:
Stock

**Comment by tobiasKaminsky** [comment] 2018-06-28 05:43
Thank you for reporting.
Duplicate of #1238.

**Closed by tobiasKaminsky** 2018-06-28 05:43 UTC
