### ISSUE TITLE
The nextcloud app does not support IPv6

### ISSUE THREAD

**Issue by husthyx** [nextcloud/android#9457] opened 2021-12-05 02:59 UTC
Two servers are built by ourselves. The nextcloud domain name is www.xxxx.cn and the emby domain name is tv.xxxx.cn. These two domain names only provide IPv6 addresses without IPv4 addresses.

The version of nextcloud app is nexcloud dev android app, version 20211202. When WiFi connection is used, nextcloud app only uses IPv4 parsing, not IPv6 parsing. It is provided as “server not available”, while emby app can be used normally and parsed with IPv6.Enter www.xxxx.cn in the mobile browser, which can be parsed and accessed normally
![1](https://user-images.githubusercontent.com/53302525/144731727-d5999f14-6639-4e88-b058-469a3ca304a0.png)

![2](https://user-images.githubusercontent.com/53302525/144731717-64b12ae0-39c8-4eaa-9e1f-bd93d6c9ce6c.jpg)

**Comment by AlvaroBrey** [comment] 2021-12-09 09:33
Duplicate of #7400

**Closed by AlvaroBrey** 2021-12-09 09:33 UTC
