### ISSUE TITLE
Thumbnail for heic formats + ability to view GPS EXIF info

### ISSUE THREAD

**Issue by windspeeder88** [nextcloud/android#11282] opened 2023-01-21 10:15 UTC
It is frustrating when the Android mobile app does not show thumbnails of heic formatted images (while iOS can). Users can't scan through their images without having to open every single one, even though the mobile device takes the same pics in heic format. Furthermore, heic images do have thumbnails in the Uploads function. Why can't this be done if viewed in the Media or Files function

Secondly, additional information such as date/time and GPS information can be seen in the iOS app version but not Android.

As a cloud back up service, the two features above are necessary for most users

**Comment by joshtrichards** [comment] 2023-11-20 19:18
Thumbnails of HEIC: Closing as a duplicate of #11274 

Metadata info added in v3.26 in #11897

**Closed by joshtrichards** 2023-11-20 19:18 UTC
Labels: enhancement, feature: previews and thumbnails
