### ISSUE TITLE
Can not stop 2 way sync

### ISSUE THREAD

**Issue by nielstron** [nextcloud/android#14034] opened 2024-11-15 21:12 UTC
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I recently got notified by the system that my local storage is filling up. I suspected NextCloud since it used to duplicate auto upload data locally. I deleted the local files.

That was a few days ago, I checked again today and notice storage is filling up again. I noticed that I could "cancel sync" for the folder that was being downloaded and did that. Afterwards I checked the settings and found that "internal 2 way sync" had been enabled, I never turned this setting on and it somehow selected my 300 GB external storage to sync.

Worst of all, the syncing did not stop. I still got notifications about downloads and I noticed my wifi being slow due to the high volume of downloads. I eventually had to delete the app to stop syncing, neither turning off the sync in the settings nor via the context menu helped.

### Expected behaviour

2 way sync should not spontaneously start and should stop when cancelled.

### Actual behaviour

2 way sync started spontaneously and did not stop.

### Android version

14

### Device brand and model

Pixel 6 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.30.4

### Nextcloud server version

29.0.9

### Using a reverse proxy?

I don't know

### Server error logs

```bash

```

### Additional information
EDIT
Although I am not sure, this must have been using the latest FDroid build since the latest play store version does not support 2 way sync (I installed NextCloud again now and configured it...)

**Comment by skylarmt** [comment] 2024-11-16 18:25
I'm also having this issue. Mine is also downloading files in folders shared with me.

**Comment by skylarmt** [comment] 2024-11-16 18:34
Uninstalling the app and reinstalling fixed it, in that the auto-upload folder list was empty on a fresh install.

**Comment by joshtrichards** [comment] 2024-11-17 21:48
Duplicate of #13872

**Closed by joshtrichards** 2024-11-17 21:48 UTC
Labels: bug, 0. Needs triage
