### ISSUE TITLE
App crash during sync of folder

### ISSUE THREAD

**Issue by myxor** [nextcloud/android#4603] opened 2019-10-02 18:33 UTC
### Actual behaviour
- App crashes when syncing a folder in background

### Expected behaviour
- should sync the folder without crash
 
### Steps to reproduce
1. Sync folder
2. Put client into background
3. 

### Environment data
Android version:

9

Device model: 

OnePlus 5

Stock or customized system:

Nextcloud app version:

30080151

Nextcloud server version:

16.04

### Logs

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{61de375 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1863)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080151
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5
Model: ONEPLUS A5000
Id: PKQ1.180716.001
Product: OnePlus5

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1906100000

**Comment by tobiasKaminsky** [comment] 2019-10-09 13:42
Duplicate of #2010

**Closed by tobiasKaminsky** 2019-10-09 13:42 UTC
Labels: bug
