### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shenwei101623** [nextcloud/android#7428] opened 2020-11-21 16:48 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{c9dc069 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2004)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7594)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: cezanne
Model: M2006J10C
Id: QP1A.190711.020
Product: cezanne

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.13.0.QJNCNXM

**Comment by AndyScherzinger** [comment] 2020-11-23 09:07
Duplicate of #6905

**Closed by AndyScherzinger** 2020-11-23 09:07 UTC
Labels: bug
