### ISSUE TITLE
Crash when uploading file and share doesn't existe anymore

### ISSUE THREAD

**Issue by freak007** [nextcloud/android#11292] opened 2023-01-25 10:23 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Remove a previously shared folder with another user
2. Use Android gallery and share one picture with nexcloud. When nextcloud IS launched, it shows latest shared folder. If this folder is not anymore shared, going black producer crash.
3. It was impossible to sync to new shared folder even If it was refreshed into nexcloud client.
4. All accounts have the same errors. It was impossible to use Android sharing from gallery.
5. Uninstalling and reconfiguring nextcloud account do not solve the problem.

### Expected behaviour

When sharing picture from gallery, and shared with nextcloud, client must refresh directory structure and allow to navigate through shared if previously shared folder doesn't exist anymore, allow to go to to main file directory without crashing.

### Actual behaviour

Nextcloud crash when previously shared folder doesn't exist anymore. Unable to go black to main folder/ home file.

### Android version

Android 10/11/12

### Device brand and model

Realme narzo 50a prime/ Poco M3/ Xiaomi redmi 9

### Stock or custom OS?

Stock

### Nextcloud android app version

3.23.1

### Nextcloud server version

25.0.3

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "Thread-10" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:919)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230191`
* Build flavor: `gplay`

### Device information
* Brand: `POCO`
* Device: `citrus`
* Model: `M2010J19CG`
* Id: `QKQ1.200830.002`
* Product: `citrus_eea`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `V12.0.5.0.QJFEUXM`

**Comment by AlvaroBrey** [comment] 2023-01-25 11:29
Duplicate of #11207

**Closed by AlvaroBrey** 2023-01-25 11:29 UTC
Labels: bug
