### ISSUE TITLE
Unable to display Photos in Android App (17k of Photos)

### ISSUE THREAD

**Issue by apg1980** [nextcloud/android#7397] opened 2020-11-20 11:41 UTC
### Steps to reproduce
1. Open Nextcloud Android App 3.14 (doesnt work in older versions eather)
2. Go into Photos 

### Expected behaviour
- Photos should be displayed

### Actual behaviour
- Photos are scaned with "Loading" until "No Photos" appears
- php-fpm is growing to 3gb with 100% CPU

### Environment data
Android version: 10 on Galaxy S20 Ultra (doesnt work on other Smartphones with my Account)

Device model: Samsung Galaxy S20 Ultra

Stock or customized system: Stock

Nextcloud app version: 3.14

Nextcloud server version: 20.02

Reverse proxy: Sophos UTM 9

Nextcloud Server:
Ubuntu 20.04 LTS
Apache2
PHP7.4-FPM
MARIADB

#### Web server error log
```
No logs
```

#### Nextcloud log (data/nextcloud.log)
```
No Log
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2020-11-23 10:32
Duplicate of / similar to #7245

**Closed by tobiasKaminsky** 2020-11-23 10:32 UTC
Labels: bug
