### ISSUE TITLE
Auto upload: Hide suggested folders

### ISSUE THREAD

**Issue by bertwesarg** [nextcloud/android#3429] opened 2019-01-07 16:24 UTC
### Is your feature request related to a problem? Please describe.
Yes. The Auto upload screen shows to many suggested folders. Thats because my photo app creates sub directories for 'burst pictures' Thus the list of suggested folders is constantly increasing. And because custom upload folders are at the end of the list. It is getting more more cumbersome to get to these folder.

### Describe the solution you'd like
1. Put custom folders at the top of the 'Auto upload' list
1. Add option to 'Auto upload' screen to hide folder suggestions

**Comment by AndyScherzinger** [comment] 2019-01-07 16:30
cc @tobiasKaminsky @jancborchardt

1. Matter of sorting while active should be at the top, then followed by inactive both sorted alphabetically with custom folders at the top of both groups.

2. completely different topic which should be discussed separately and falls in to the discussion we are already having regarding a smarter filter for which folders to show and which to hide.

**Comment by bertwesarg** [comment] 2019-01-07 17:57
>     1. Matter of sorting while active should be at the top, then followed by inactive both sorted alphabetically with custom folders at the top of both groups.

I think also inactive custom folders should be on top.

**Comment by bertwesarg** [comment] 2019-01-08 09:38
> > ```
> > 1. Matter of sorting while active should be at the top, then followed by inactive both sorted alphabetically with custom folders at the top of both groups.
> > ```
> 
> I think also inactive custom folders should be on top.

Looks like a reload already put the custom folders to the top.

**Comment by jancborchardt** [comment] 2019-01-08 16:33
This seems to be a duplicate of https://github.com/nextcloud/android/issues/3263 ?

> Matter of sorting while active should be at the top, then followed by inactive both sorted alphabetically with custom folders at the top of both groups

Yes, as we discussed in the other issue.
- Step 1: Sort the folders in auto upload by most recent activity. That way the most relevant stuff is on top. (Alphabetic sorting makes little sense here)
- Special folders like Camera and Screenshots (if they exist) could always be at the top
- Additionally, we could hide completely irrelevant folders like music albums where there’s only one "cover.jpg" in it.

**Comment by AndyScherzinger** [comment] 2019-01-08 16:33
Yes it does, while it still sorts for active first then on each group puts custom folders on the top.
The reload is indeed a bug then and the sorting should be triggered right after the activation of the folder :/
Would you mind opening an issue for the refresh part please? ❤️

**Comment by bertwesarg** [comment] 2019-01-14 10:12
> Yes it does, while it still sorts for active first then on each group puts custom folders on the top.
> The reload is indeed a bug then and the sorting should be triggered right after the activation of the folder :/
> Would you mind opening an issue for the refresh part please? heart

Done in #3456

**Comment by AndyScherzinger** [comment] 2019-10-26 10:14
Hiding of auto detected folders from the list is now best described in #3263, so closing this one.

**Closed by AndyScherzinger** 2019-10-26 10:14 UTC
Labels: enhancement
