### ISSUE TITLE
Fatal exception during click on ignore battery optimization 



### ISSUE THREAD

**Issue by msviba** [nextcloud/android#14091] opened 2024-11-25 20:04 UTC
### Cause of error
```java
Exception in thread "main" android.content.res.Resources$NotFoundException: Resource ID #0x7f0a0420 type #0x12 is not valid
    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2711)
    at android.content.res.Resources.getLayout(Resources.java:1371)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:464)
    at androidx.appcompat.app.AlertController.setupCustomContent(AlertController.java:644)
    at androidx.appcompat.app.AlertController.setupView(AlertController.java:475)
    at androidx.appcompat.app.AlertController.installContent(AlertController.java:233)
    at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:278)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:450)
    at android.app.Dialog.show(Dialog.java:339)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.showPowerCheckDialog(SyncedFoldersActivity.kt:233)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onDisablePowerSaveCheckClicked(SyncedFoldersActivity.kt:217)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onCreateOptionsMenu$lambda$1(SyncedFoldersActivity.kt:210)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.$r8$lambda$q58-_n5tvnvo7t7SwBQVBpaIAdU(Unknown Source:0)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$$ExternalSyntheticLambda4.onMenuItemClick(D8$$SyntheticClass:0)
    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:984)
    at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
    at android.widget.AdapterView.performItemClick(AdapterView.java:330)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1285)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3318)
    at android.widget.AbsListView.onTouchUp(AbsListView.java:4312)
    at android.widget.AbsListView.onTouchEvent(AbsListView.java:4044)
    at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:230)
    at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:138)
    at android.view.View.performOnTouchCallback(View.java:16679)
    at android.view.View.dispatchTouchEvent(View.java:16632)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2808)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3158)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2826)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3158)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2826)
    at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2568)
    at android.view.View.dispatchPointerEvent(View.java:16972)
    at com.xiaomi.mirror.MiuiMirrorImpl.isHandled(MiuiMirrorImpl.java:152)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8915)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:8657)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:8009)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:8066)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:8032)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:8198)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:8040)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:8255)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:8013)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:8066)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:8032)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:8040)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:8013)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:11325)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:11276)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:11237)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:11503)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:337)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:355)
    at android.os.Looper.loopOnce(Looper.java:203)
    at android.os.Looper.loop(Looper.java:337)
    at android.app.ActivityThread.main(ActivityThread.java:9561)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300590`
* Build flavor: `gplay`

### Device information
* Brand: `Xiaomi`
* Device: `houji`
* Model: `23127PN0CG`
* Id: `AQ3A.240627.003`
* Product: `houji_eea`

### Firmware
* SDK: `35`
* Release: `15`
* Incremental: `V816.1.4.0.VNCEUXM`

**Comment by msviba** [comment] 2024-12-09 14:20
Bug still presents in Version: `30300690`

**Comment by joshtrichards** [comment] 2024-12-28 14:43
Duplicate of #13404

**Closed by joshtrichards** 2024-12-28 14:43 UTC
