### ISSUE TITLE
Upload activity crashes in empty folder

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/android#221] opened 2016-08-18 07:01 UTC
### Steps to reproduce
1. Create an empty folder on your phone (Not via the nextcloud app)
2. Open nextcloud app
3. ➕
4. Upload (top icon in the menu)
5. Navigate to the empty folder
6. Go inside the empty folder

### Actual behaviour
Crashes

### Expected behaviour
Should not crash but show "empty list"
 

### Environment data
Android version: 6.0

Device model: Huawei P8 lite

Stock or customized system: stock

Nextcloud app version: 1.2

Nextcloud server version: 9.0.53

**Comment by AndyScherzinger** [comment] 2016-08-18 07:23
@tobiasKaminsky can you look into this? My Android N device is complete broken when it comes to this which also need to be investigated... (newly created empty folders show files from other places and the also show camera pictures as folders, see #220 :cry: )

Thanks for the report @nickvergessen !

**Comment by michalmiddleton** [comment] 2016-08-24 14:11
I have Nexus 6P with Android 7.0 and I am having the same issue with crash on an empty folder. I'm pretty sure it was happening even on 6.0.1 before the update.

**Comment by AndyScherzinger** [comment] 2016-08-30 13:26
@michalmiddleton and @nickvergessen just tried it with my Nexus5X running the latest Android 7.0 stable and couldn't reproduce this error. Can you try it out again using the beta version from f-droid and posting the stack trace from the log file? That would help us finding the issue here :)

**Comment by michalmiddleton** [comment] 2016-08-30 13:43
@AndyScherzinger I tested beta 20160809 and it doesn't crash anymore. 
I saw some funny behavior while browsing folders tho. It looked like after entering a parent folder it listed it as a child folder inside itself as well. Not sure if this is relevant or not..

**Comment by AndyScherzinger** [comment] 2016-08-30 14:21
Yes, that is also happening to me with the 1.2.0 version on Android 7 and is something we need to have a look into.

**Comment by nickvergessen** [comment] 2016-08-30 14:46
Sorry, I just posted this, it was reported by someone on IRC, forgot to note down the name thou :(

**Comment by AndyScherzinger** [comment] 2016-08-30 15:15
@nickvergessen no worries. I'll close this issue and we can reopen it, in case this happens again and gets reported (can't be reproduced at the moment). 
As for the empty folder showing "a" parent I opened a PR #229

**Closed by AndyScherzinger** 2016-08-30 15:15 UTC
Labels: bug, need info
