### ISSUE TITLE
Message error

### ISSUE THREAD

**Issue by heglas** [nextcloud/android#13328] opened 2024-07-27 10:42 UTC
### Cause of error
```java
Exception in thread "Thread-16" java.lang.NullPointerException: Attempt to invoke virtual method 'org.apache.commons.httpclient.HostConfiguration com.owncloud.android.lib.common.OwnCloudClient.getHostConfiguration()' on a null object reference
    at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:116)
    at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$6(FileDetailActivitiesFragment.java:295)
    at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.$r8$lambda$fzpi7kO8PpXaUSSQob84vDVuOjs(Unknown Source:0)
    at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment$$ExternalSyntheticLambda5.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:923)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `motorola`
* Device: `odessa`
* Model: `moto g(9) plus`
* Id: `RPAS31.Q2-59-17-4-3-9`
* Product: `odessa_retail`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `412e48`

**Comment by joshtrichards** [comment] 2024-08-05 17:35
Duplicate of #13114

**Closed by joshtrichards** 2024-08-05 17:35 UTC
