### ISSUE TITLE
[Android App] Change domain of account

### ISSUE THREAD

**Issue by mxzgithub** [nextcloud/android#9325] opened 2021-11-20 07:30 UTC
### Is your feature request related to a problem? Please describe.
If you have already set up an account on the Android app you're unable to change the domain which it is associated with.
If you change the domain of the server you have to add a new account and redo all the settings.

### Describe the solution you'd like
Allow a domain change in an already set up account.

### Describe alternatives you've considered
Make your settings for backups etc exportable, so you can import it with a new account. Might even beneficial of you set up another or a new device.

### Additional context

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2021-12-14 09:32
Duplicate of #3877

**Closed by AlvaroBrey** 2021-12-14 09:32 UTC
Labels: enhancement

**Comment by PascalHeynmoeller** [comment] 2023-01-27 11:34
Yes it's an duplicate but the altenative solution to export the profile settings is an new approach to support users to not configure every single uploadfolder and the state of synced files. @AlvaroBrey Do we need to make an new feature request for this solution?
