### ISSUE TITLE
Nextcloud crash

### ISSUE THREAD

**Issue by euneira** [nextcloud/android#7791] opened 2021-01-07 16:50 UTC
### Steps to reproduce
1. I put in Nextcloud folder at desktop many folders and files in order to syncronize it to the cloud webo hosting, UP to 20 Gb, and renamed some of them and change of folder. 
2. Nextcloud didn't get all the staff and didn't change some of the files renamed. 
3. I deleted all these files and folders at desktop folder and at Nextcloud webo hosting.
4. I tried to create a folder at Nextcloud Android apk and I get a message saying that Nextcloud Android apk is blocked. I desinstallated the apk and reinstall but the bug goes on. 
5. I reseted the Android Phone and the bug goes on.
6. I am not and expert at all. I am Just a user. 

### Environment data
Android version: Android 10

Device model: Samsung Galaxy A50

Stock or customized system:

Nextcloud app version: 3.0.3

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5958)
	at android.view.ViewGroup.addView(ViewGroup.java:5777)
	at android.view.ViewGroup.addView(ViewGroup.java:5717)
	at android.view.ViewGroup.addView(ViewGroup.java:5690)
	at com.owncloud.android.ui.fragment.OCFileListBottomSheetDialog.onCreate(OCFileListBottomSheetDialog.java:131)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:702)
	at android.app.Dialog.show(Dialog.java:424)
	at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$registerFabListener$2$OCFileListFragment(OCFileListFragment.java:442)
	at com.owncloud.android.ui.fragment.-$$Lambda$OCFileListFragment$aYkoWPoxzAOahKL5AVjT06NhcnM.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7862)
	at android.view.View.performClickInternal(View.java:7831)
	at android.view.View.access$3600(View.java:879)
	at android.view.View$PerformClick.run(View.java:29359)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140251
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a50
Model: SM-A505FN
Id: QP1A.190711.020
Product: a50eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: A505FNXXU5BTK5

**Comment by tobiasKaminsky** [comment] 2021-01-14 06:39
Duplicate of #7796

**Closed by tobiasKaminsky** 2021-01-14 06:39 UTC
Labels: bug
