### ISSUE TITLE
App crashes when creating password for shared folder via link

### ISSUE THREAD

**Issue by mayonezo** [nextcloud/android#6853] opened 2020-08-30 13:38 UTC
### Steps to reproduce
1. Share a folder via link
2. Add a password
3. App crashes

### Expected behaviour
- App should not crash

### Actual behaviour
- App crashes

### Logs
```************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.lib.resources.shares.OCShare.getId()' on a null object reference
	at com.owncloud.android.ui.helpers.FileOperationsHelper.setPasswordToPublicShare(FileOperationsHelper.java:592)
	at com.owncloud.android.ui.dialog.SharePasswordDialogFragment.setPassword(SharePasswordDialogFragment.java:198)
	at com.owncloud.android.ui.dialog.SharePasswordDialogFragment.onClick(SharePasswordDialogFragment.java:175)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loop(Unknown Source:242)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: beryllium
Model: POCOPHONE F1
Id: QKQ1.190828.002
Product: beryllium

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.0.3.QEJMIXM

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2020-08-31 08:06
Duplicate of #6749

**Closed by tobiasKaminsky** 2020-08-31 08:06 UTC
Labels: bug
