### ISSUE TITLE
Change default auto upload remote folder

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/android#1741] opened 2017-11-03 10:48 UTC
The new functions with version 2 are very great and there is not much to miss anymore. 1 think I really miss is a option to set a default root folder instead of "instenduploads" folder. Would be nice to have the option to change this folder once and if there will be a new source to upload, I have only to check the cloud symbol and not also change the upload path.

**Comment by joshtrichards** [comment] 2023-11-17 19:53
Duplicate of #1310

**Closed by joshtrichards** 2023-11-17 19:53 UTC
Labels: enhancement, feature: auto upload
