### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by IngoBelka** [nextcloud/android#13813] opened 2024-10-18 12:51 UTC
### Cause of error
```java
Exception in thread "main" android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f9a7a8a u0 com.nextcloud.client/androidx.work.impl.foreground.SystemForegroundService}
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
    at android.os.Handler.dispatchMessage(Handler.java:112)
    at android.os.Looper.loop(Looper.java:216)
    at android.app.ActivityThread.main(ActivityThread.java:7625)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300190`
* Build flavor: `generic`

### Device information
* Brand: `HUAWEI`
* Device: `HWSHT`
* Model: `SHT-W09`
* Id: `HUAWEISHT-W09`
* Product: `SHT-W09`

### Firmware
* SDK: `28`
* Release: `9`
* Incremental: `9.1.0.335C432`

**Comment by joshtrichards** [comment] 2024-10-18 14:11
Duplicate of #13798

**Closed by joshtrichards** 2024-10-18 14:11 UTC
