### ISSUE TITLE
Handle app token in app

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#3937] opened 2019-04-29 05:29 UTC
Handle app token like on web UI
- show
- delete / manage
- create 

As like on web ui this should only be allowed after re-entering the login password.
@rullzer are those endpoints already accessible for clients?

**Comment by rullzer** [comment] 2019-04-29 07:16
> @rullzer are those endpoints already accessible for clients?

Nope

**Comment by joshtrichards** [comment] 2023-12-11 22:02
Duplicate of #1897

**Closed by joshtrichards** 2023-12-11 22:02 UTC
Labels: enhancement, feature: authentication
