### ISSUE TITLE
Untrusted certificate causes application crash

### ISSUE THREAD

**Issue by centromere** [nextcloud/android#10942] opened 2022-10-26 18:34 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Use the Android client to connect to a server which is using a self-signed certificate.

### Expected behaviour

It should not crash.

### Actual behaviour

It crashes.

### Android version

13

### Device brand and model

Pixel 4a

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.22.1

### Nextcloud server version

25.0.0

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.LinearLayout com.owncloud.android.databinding.SslUntrustedCertLayoutBinding.getRoot()' on a null object reference
at com.owncloud.android.ui.dialog.SslUntrustedCertDialog.onCreateDialog(SslUntrustedCertDialog.java:173)
at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665)
at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579)
at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1752)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7904)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ExecInit.main(ExecInit.java:49)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
```

### App information
* ID: `com.nextcloud.client`
* Version: `30220190`
* Build flavor: `generic`

### Device information
* Brand: `google`
* Device: `sunfish`
* Model: `Pixel 4a`
* Id: `TP1A.221005.002`
* Product: `sunfish`
* GrapheneOS

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `2022102300`

**Comment by AlvaroBrey** [comment] 2022-10-27 07:33
Duplicate of #10868, should be fixed in 3.22.2

**Closed by AlvaroBrey** 2022-10-27 07:33 UTC
Labels: bug
