### ISSUE TITLE
RC6 queues and subsequently overwrites files already previously uploaded

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/android#1541] opened 2017-09-13 14:11 UTC
### Actual behaviour
Installed RC6
Removed existing account
Re-added account
Setup autoupload with alllllll my folders
700+ photos immediately queued, most of which already exist on the server and are therefore overwritten

### Expected behaviour
1. Shouldn't be uploading anything by design but:
1.1 Could validate the remote folder against the local if it's going to try to upload ALL THE THINGS out of the blue to avoid this problem
1.2 Could duplicate rather than overwrite as there's no guarantee the images won't corrupt after extended time on SD.
 
### Steps to reproduce
1. Upgrade from RC5 to RC6 via Play
2+ See actual behaviour

### Environment data
Android version: 7.1.2

Device model: Moto Z

Stock or customized system: Stock

Nextcloud app version: RC6

Nextcloud server version: 12.0.2

**Comment by mario** [comment] 2017-09-13 17:06
@AndyScherzinger can you try to reproduce pls?

**Comment by AndyScherzinger** [comment] 2017-09-13 17:11
I'll have to see, but can't say for sure since this week is crazy busy at work...

**Comment by xXSTrikeXx** [comment] 2017-09-14 09:33
Happen to me, too :D But then missing files was uploaded rightly :D

**Comment by jasonbayton** [comment] 2017-09-14 09:36
I like that it does indeed upload the missing (I noticed one additional file it previously missed last night) however I'm concerned eventual SD card file corruption will cause it to overwrite good files with crap.. so if this is the way forward I'll have to re-evaluate how I store stuff on SD.

**Comment by mario** [comment] 2017-09-14 09:37
Kind sirs. I will investigate this.

**Comment by mario** [comment] 2017-09-14 14:27
I think this was an issue only because the account name changed, and we didn't delete everything. We'll see.

PR https://github.com/nextcloud/android/pull/1547

**Comment by jasonbayton** [comment] 2017-09-14 14:39
Lovely ta.

It appears to have affected only two of the 15 folders I've set to autoupload

**Comment by mario** [comment] 2017-09-14 14:40
Your phones are always strange :D

**Comment by enoch85** [comment] 2017-09-15 12:04
> Your phones are always strange :D

Mine too in that case. I can confirm this behavior after the RC5 warning about re-adding account.

**Comment by mario** [comment] 2017-09-15 12:20
@enoch85 yea, I'm not saying yours is normal :) My assumption is what I said above, but I don't know why it'd trigger for only two out of 15 folders. We'll see with the next RC...

**Comment by xXSTrikeXx** [comment] 2017-09-15 15:45
For me was it one folder. But not the default Camera & Video folder. Wicked :D

**Comment by tobiasKaminsky** [comment] 2017-09-22 12:25
PR merged, releasing RC7 soon.
If it occurs again, please re-open.

**Closed by tobiasKaminsky** 2017-09-22 12:25 UTC
Labels: bug, pr exists

**Comment by enoch85** [comment] 2017-09-22 14:23
> RC7

Release it already! ;)
