### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by witecat** [nextcloud/android#14221] opened 2024-12-22 11:22 UTC
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Fragment PreviewMediaFragment{489f564} (5b24283d-6d55-48fd-b29f-c4d4d09d52be) not attached to a context.
    at androidx.fragment.app.Fragment.requireContext(Fragment.java:972)
    at com.owncloud.android.ui.preview.PreviewMediaFragment.lambda$onStart$1(PreviewMediaFragment.java:351)
    at com.owncloud.android.ui.preview.PreviewMediaFragment.$r8$lambda$uDaoT5tCd_EnFoVGkfSYFCOoOr4(Unknown Source:0)
    at com.owncloud.android.ui.preview.PreviewMediaFragment$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7884)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `Lenovo`
* Device: `TB-J616F`
* Model: `Lenovo TB-J616F`
* Id: `SP1A.210812.016`
* Product: `TB-J616F_EEA`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `TB-J616F_S240253_241016_ROW`

**Comment by joshtrichards** [comment] 2024-12-28 15:02
Duplicate of #13256

**Closed by joshtrichards** 2024-12-28 15:02 UTC
