### ISSUE TITLE
Crashed opening media 

### ISSUE THREAD

**Issue by cakonopka** [nextcloud/android#10727] opened 2022-09-10 17:51 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Opened nextcloud app
Clicked media
Stayed in files page
Crashed

### Expected behaviour

Media to opwn

### Actual behaviour

Crashed 

### Android version

12

### Device brand and model

Oneplus9Pro 

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.2

### Nextcloud server version

24.0.2

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.ui.adapter.OCFileListAdapter.setGridView(boolean)' on a null object reference
    at com.owncloud.android.ui.fragment.OCFileListFragment.switchLayoutManager(OCFileListFragment.java:1458)
    at com.owncloud.android.ui.fragment.OCFileListFragment.switchToListView(OCFileListFragment.java:1414)
    at com.owncloud.android.ui.fragment.OCFileListFragment.setListAsPreferred(OCFileListFragment.java:1409)
    at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$onActivityCreated$1$com-owncloud-android-ui-fragment-OCFileListFragment(OCFileListFragment.java:400)
    at com.owncloud.android.ui.fragment.OCFileListFragment$$ExternalSyntheticLambda7.onClick(Unknown Source:2)
    at android.view.View.performClick(View.java:7488)
    at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1194)
    at android.view.View.performClickInternal(View.java:7464)
    at android.view.View.access$3700(View.java:841)
    at android.view.View$PerformClick.run(View.java:28905)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:233)
    at android.os.Looper.loop(Looper.java:344)
    at android.app.ActivityThread.main(ActivityThread.java:8210)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210290`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus9Pro`
* Model: `LE2123`
* Id: `RKQ1.211119.001`
* Product: `OnePlus9Pro_EEA`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `R.GDPR.202206251226`

**Comment by JehanPatwa** [comment] 2022-09-11 11:15
Can I give it a try to solve this issue by removing the bug as it will help me in acedamics and your issue will be solved.

**Comment by strugee** [comment] 2022-09-23 01:54
Duplicate of #10499

**Closed by strugee** 2022-09-23 01:54 UTC
Labels: bug
