### ISSUE TITLE
Offline file creation crash next loud app

### ISSUE THREAD

**Issue by erickeller** [nextcloud/android#11252] opened 2023-01-14 01:01 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

0. Be offline (airplane mode)
1. Open next loud app
2. Create a new file (+ icon create a new document)
3. Get the crash with following stack trace
```
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.lib.common.Template.getExtension()' on a null object reference
    at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.checkEnablingCreateButton(ChooseTemplateDialogFragment.kt:254)
    at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.access$checkEnablingCreateButton(ChooseTemplateDialogFragment.kt:69)
    at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$onCreateDialog$2.afterTextChanged(ChooseTemplateDialogFragment.kt:154)
    at android.widget.TextView.sendAfterTextChanged(TextView.java:10626)
    at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13467)
    at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1292)
    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:592)
    at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:315)
    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:522)
    at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:305)
    at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:49)
    at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:843)
    at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:616)
    at android.view.inputmethod.InputConnectionWrapper.setComposingText(InputConnectionWrapper.java:142)
    at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:393)
    at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7697)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230191`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus5`
* Model: `ONEPLUS A5000`
* Id: `QKQ1.191014.012`
```
* Product: `OnePlus5`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `2010292059`

### Expected behaviour

Be able to create a text file offline
Be able to edit a new document with rich text decoration offline.

### Actual behaviour

The offline creation is impossible.
Did not test offline edit though.

### Android version

10

### Device brand and model

Oneplus5

### Stock or custom OS?

Stock

### Nextcloud android app version

3.23.1

### Nextcloud server version

25.0.2snap1

### Using a reverse proxy?

No

### Android logs

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.lib.common.Template.getExtension()' on a null object reference
    at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.checkEnablingCreateButton(ChooseTemplateDialogFragment.kt:254)
    at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.access$checkEnablingCreateButton(ChooseTemplateDialogFragment.kt:69)
    at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$onCreateDialog$2.afterTextChanged(ChooseTemplateDialogFragment.kt:154)
    at android.widget.TextView.sendAfterTextChanged(TextView.java:10626)
    at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13467)
    at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1292)
    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:592)
    at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:315)
    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:522)
    at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:305)
    at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:49)
    at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:843)
    at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:616)
    at android.view.inputmethod.InputConnectionWrapper.setComposingText(InputConnectionWrapper.java:142)
    at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:393)
    at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7697)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230191`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus5`
* Model: `ONEPLUS A5000`
* Id: `QKQ1.191014.012`
* Product: `OnePlus5`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `2010292059`

### Server error logs

```bash
Did not connect to server yet the file creation works when online having network.
```

### Additional information

Let me know if more logs are required or not reproducible.
I did not find any duplicate in open or closed issues.

**Comment by AlvaroBrey** [comment] 2023-01-17 13:55
Duplicate of #10668

**Closed by AlvaroBrey** 2023-01-17 13:55 UTC
Labels: bug
