### ISSUE TITLE
Crash when sharing from other app and previous upload folder no longer exist

### ISSUE THREAD

**Issue by maumad** [nextcloud/android#11380] opened 2023-02-13 15:34 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Upload to server folder from other app sharing example photo gallery.
Now delete or move from server the previous folder.
Now upload to server from other app sharing. By default it will try to upload to previous selected folder that no longer exist, trying to navigate back, the only option available, the app will crash.

### Expected behaviour

It should present to upload to root folder.

### Actual behaviour

Navigate back will crash.
No solution to continuing upload from other app in system.

### Android version

10

### Device brand and model

Samsung galaxy note 9

### Stock or custom OS?

Stock

### Nextcloud android app version

3.23.1

### Nextcloud server version

25.0.3

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "Thread-29" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:919)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230191`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `crownlte`
* Model: `SM-N960F`
* Id: `QP1A.190711.020`
* Product: `crownltexx`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `N960FXXU9FVH1`

**Comment by AlvaroBrey** [comment] 2023-02-13 18:21
Duplicate of #11207

**Closed by AlvaroBrey** 2023-02-13 18:21 UTC
Labels: bug
