### ISSUE TITLE
Suspend auto upload as a menu option

### ISSUE THREAD

**Issue by dschwerdel** [nextcloud/android#10788] opened 2022-10-09 15:51 UTC
### Is your feature request related to a problem? Please describe.
I'm abroad right know. For connection to the mobile internet I'm using another mobile phone with local, limited data as a hotspot.
I don't want to waste the mobile data for background auto upload. Upload later over hotel wireless is good enough.

My main phone with the nextcloud app is connected to this "local" phone hotspot via wireless network.
The option "only use wireless" to auto upload / sync my folders on the phone isn't enough to limit waste.
Right know I set my auto upload folders to "only upload when charging".
(I'm getting anyway Notifications that files can't be uploaded, with the setting "only upload while charging". 
Even when the phone isn't charging. But that's another issue)

### Describe the solution you'd like
I wish for a setting in the menu where I can set "**suspend auto upload**". As long as this option is activated.
And when the option is unset: a start of the upload of all files that been new / changed since the activation of the option.

### Describe alternatives you've considered
I tried to deactivate the auto folder upload when I don't want files uploaded. 
It is not very convenient to activate / deactivate multiple folders.  
And newly generated files aren't synced if they're generated while the sync was off.
(I don't like syncing the whole folder. So I upload the new files by hand. Prone to mistakes.)
 
### Additional context
Nextcloud Android app 3.21.2
Pixel 4a, Android 13

**Comment by joshtrichards** [comment] 2023-12-22 21:27
Duplicate of #383

**Closed by joshtrichards** 2023-12-22 21:27 UTC
Labels: enhancement, feature: auto upload
