### ISSUE TITLE
Nextcloud android client error. 

### ISSUE THREAD

**Issue by Jasper56** [nextcloud/android#9795] opened 2022-02-03 08:15 UTC
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 2062)
#################################################################
Error Code : 2062 (SQLITE_CANTOPEN_EMFILE)
Caused By : Application has opened too many files. Maximum of available file descriptors in one process is 1024 in default.
	(unable to open database file (code 2062))
#################################################################
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1018)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:152)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:141)
	at android.content.ContentResolver.query(ContentResolver.java:779)
	at android.content.ContentResolver.query(ContentResolver.java:710)
	at android.content.ContentResolver.query(ContentResolver.java:668)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadStatus(UploadsStorageManager.java:195)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateDatabaseUploadResult(UploadsStorageManager.java:579)
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:659)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1415)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a5y17lte
Model: SM-A520F
Id: R16NW
Product: a5y17ltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: A520FXXUGCTKA

**Comment by AlvaroBrey** [comment] 2022-02-03 09:21
Duplicate of #9172

**Closed by AlvaroBrey** 2022-02-03 09:21 UTC
