### ISSUE TITLE
Crash while idle (OOM)

### ISSUE THREAD

**Issue by Crell** [nextcloud/android#11009] opened 2022-11-08 18:25 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I had a feed open (Phandroid) in the News app, and despite not tapping anything the following stack trace popped up. 

### Expected behaviour

No exception thrown. 

### Cause of error
```java
Exception in thread "WM.task-2" java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 5103208 free bytes and 4983KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.addConditionWaiter(AbstractQueuedSynchronizer.java:1882)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2063)
    at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
    at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220390`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `crosshatch`
* Model: `Pixel 3 XL`
* Id: `SP1A.210812.016.C1`
* Product: `crosshatch`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `8029091`

### Android version

12

### Device brand and model

Pixel 3 XL

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.3

### Nextcloud server version

24?

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment] 2024-08-19 17:29
Looks similar to #10999 & #11032.

Duplicate of #10653

**Closed by joshtrichards** 2024-08-19 17:29 UTC
Labels: bug, Version/3022, performance: OOM :brain:
