### ISSUE TITLE
Application freezing when reads large folder

### ISSUE THREAD

**Issue by ok2zar** [nextcloud/android#7608] opened 2020-12-04 22:24 UTC
### Steps to reproduce
1.  Copy nerly 23 000 photo files having ~ 260 GB on to server
2.  Install android application
3.  Try to view remote photo files

### Expected behaviour
- Read remote files previews in batches and loading on-demand to prevent freezing

### Actual behaviour
- I've installed NextCloud server (last version), copied whole DCIM folder (22 000 photo + 1000 video files together nearly 216 GB) from old phone via SCP to next cloud (and into new phone), reassign to www-data user and called "sudo -u www-data php occ files:scan --all". Files are there and are browsable when using web interface. Then I've loged-in from android client and tried to view the files. But remote client is freezing on any attempt.

Second boring thing happend when I've marked DCIM folder in my phone to be synchronized - client still asking me for decision due to "File name conflict" and is not possible to tick somewhere "apply for all files" or "do not ask me again". Is asking me for every single video file. And when I choose an option "Keep older one" then download remote file from cloud and say "Download operation haven't been finished due to server is not available".

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10.1.0.171

Device model: Huawei P30 Pro (VOG-L29)

Stock or customized system: Stock

Nextcloud app version: 3.14.1 (today update from Google Play)

Nextcloud server version: 20.0.2

Reverse proxy:

#### Web server error log
[Fri Dec 04 00:00:06.982132 2020] [mpm_prefork:notice] [pid 14853] AH00163: Apache/2.4.38 (Debian) OpenSSL/1.1.1d configured -- resuming normal operations
[Fri Dec 04 00:00:06.982150 2020] [core:notice] [pid 14853] AH00094: Command line: '/usr/sbin/apache2'
[Fri Dec 04 00:07:02.088809 2020] [mpm_prefork:notice] [pid 14853] AH00169: caught SIGTERM, shutting down
[Fri Dec 04 00:07:02.186007 2020] [mpm_prefork:notice] [pid 32060] AH00163: Apache/2.4.38 (Debian) OpenSSL/1.1.1d configured -- resuming normal operations
[Fri Dec 04 00:07:02.186063 2020] [core:notice] [pid 32060] AH00094: Command line: '/usr/sbin/apache2'

#### Nextcloud log (data/nextcloud.log)
>>> File is empty <<<

**Comment by tobiasKaminsky** [comment] 2020-12-16 09:51
You have 23k files in one folder?

**Comment by ok2zar** [comment] 2020-12-16 21:37
Yes. All photos since 2010. Its "DCIM/Camera" folder used by Android.

**Comment by tobiasKaminsky** [comment] 2020-12-18 07:08
Then it is a duplicate of #6688

**Closed by tobiasKaminsky** 2020-12-18 07:08 UTC
Labels: bug, needs info/discussion
