### ISSUE TITLE
Error in Samsung Note 9

### ISSUE THREAD

**Issue by joinof** [nextcloud/android#8911] opened 2021-08-29 16:06 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to pause activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@5f2a8b3
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4993)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4944)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4896)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:228)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@5f2a8b3
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1501)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1605)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:678)
	at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.onInactive(UsbConnectionDispatcher.java:131)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.ensureStateInactive(SecurityKeyManager.java:316)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.refreshActiveState(SecurityKeyManager.java:290)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.onActivityPaused(SecurityKeyManager.java:333)
	at android.app.Application.dispatchActivityPaused(Application.java:485)
	at android.app.Activity.dispatchActivityPaused(Activity.java:1327)
	at android.app.Activity.onPause(Activity.java:2251)
	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:388)
	at com.owncloud.android.ui.activity.BaseActivity.onPause(BaseActivity.java:84)
	at com.owncloud.android.ui.activity.FileActivity.onPause(FileActivity.java:253)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onPause(FileDisplayActivity.java:1254)
	at android.app.Activity.performPause(Activity.java:8150)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1508)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4983)
	... 13 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: crownqltechn
Model: SM-N9600
Id: QP1A.190711.020
Product: crownqltezh

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: N9600ZHU8FUG6

**Comment by AlvaroBrey** [comment] 2021-09-02 13:22
Duplicate of https://github.com/nextcloud/android/issues/8585

**Closed by AlvaroBrey** 2021-09-02 13:22 UTC
Labels: bug
