### ISSUE TITLE
IllegalStateException in UploadFilesActivity.onStop

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#3776] opened 2019-03-21 09:00 UTC
GPlay:
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performStopActivityInner (ActivityThread.java:4805)
  at android.app.ActivityThread.handleStopActivity (ActivityThread.java:4858)
  at android.app.ActivityThread.-wrap25 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2028)
  at android.os.Handler.dispatchMessage (Handler.java:108)
  at android.os.Looper.loop (Looper.java:166)
  at android.app.ActivityThread.main (ActivityThread.java:7529)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:245)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:921)
Caused by: java.lang.IllegalStateException: 
  at androidx.fragment.app.FragmentManagerImpl.checkStateLoss (FragmentManager.java:2080)
  at androidx.fragment.app.FragmentManagerImpl.enqueueAction (FragmentManager.java:2106)
  at androidx.fragment.app.FragmentManagerImpl.popBackStack (FragmentManager.java:846)
  at androidx.fragment.app.DialogFragment.dismissInternal (DialogFragment.java:215)
  at androidx.fragment.app.DialogFragment.dismiss (DialogFragment.java:191)
  at com.owncloud.android.ui.activity.UploadFilesActivity.onStop (UploadFilesActivity.java:706)
  at android.app.Instrumentation.callActivityOnStop (Instrumentation.java:1386)
  at android.app.Activity.performStop (Activity.java:7587)
  at android.app.ActivityThread.performStopActivityInner (ActivityThread.java:4802)
```

**Comment by AndyScherzinger** [comment] 2019-04-04 07:06
Still happens sind AppCOmpat/AndroidX implementations don't seem to work so we might need to handle this via the fragment manager ourself, PR to follow.

**Comment by AndyScherzinger** [comment] 2019-04-04 07:42
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performStopActivityInner (ActivityThread.java:4241)
  at android.app.ActivityThread.handleStopActivity (ActivityThread.java:4290)
  at android.app.ActivityThread.-wrap28 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1665)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6682)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
Caused by: java.lang.IllegalStateException: 
  at androidx.fragment.app.FragmentManagerImpl.checkStateLoss (FragmentManager.java:2080)
  at androidx.fragment.app.FragmentManagerImpl.enqueueAction (FragmentManager.java:2106)
  at androidx.fragment.app.FragmentManagerImpl.popBackStack (FragmentManager.java:846)
  at androidx.fragment.app.DialogFragment.dismissInternal (DialogFragment.java:215)
  at androidx.fragment.app.DialogFragment.dismissAllowingStateLoss (DialogFragment.java:201)
  at com.owncloud.android.ui.activity.UploadFilesActivity.onStop (UploadFilesActivity.java:710)
  at android.app.Instrumentation.callActivityOnStop (Instrumentation.java:1297)
  at android.app.Activity.performStop (Activity.java:7168)
  at android.app.ActivityThread.performStopActivityInner (ActivityThread.java:4238)
```
maybe using
```
getFragmentManager().beginTransaction().add(dialog).commitAllowingStateLoss();
```
might solve the issue, dont know for sure. No tested yet.

**Comment by tobiasKaminsky** [comment] 2019-07-03 10:24
How can you reproduce this?

**Comment by AndyScherzinger** [comment] 2019-07-03 10:46
I can't actually, just saw the stacktraces on gplay...

**Comment by tobiasKaminsky** [comment] 2020-11-24 11:45
If we cannot reproduce it, we have to close it :/

**Closed by tobiasKaminsky** 2020-11-24 11:45 UTC
Labels: approved, bug
