### ISSUE TITLE
Dashboard Mail Unread shows Trash

### ISSUE THREAD

**Issue by Emporea** [nextcloud/android#10873] opened 2022-10-21 00:44 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Place Widget on homescreen
Select unread Email
Hit refresh or wait

### Expected behaviour

Shows unread emails

### Actual behaviour

Shows the Trash (3 random mails so far) of one of my mail boxes

### Android version

12.1

### Device brand and model

POCO alioth

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.22.1

### Nextcloud server version

25.0.0

### Using a reverse proxy?

Yes

**Comment by AlvaroBrey** [comment] 2022-10-21 07:45
@Emporea can you check what it shows in the web dashboard?

**Comment by Emporea** [comment] 2022-10-21 09:12
Yeah. Everything is correct on the web.

**Comment by jakobroehrl** [comment] 2022-10-21 10:40
I can confirm this bug. 
It seams to me there is no filter to INBOX and unread. All mails are shown

**Comment by Emporea** [comment] 2022-10-21 13:32
@AlvaroBrey Do you have tried it with an empty unread list?
At first its empty on android widget aswell, but if i hit the refresh icon it shows 3 random trash emails of one of my 4 mailboxes.

Every real unread mail just gets added to those 3 random mails ontop.

**Comment by Emporea** [comment] 2022-10-21 13:38
Web interface:
![IMG_20221021_153243](https://user-images.githubusercontent.com/21969523/197209089-7fe46a44-bcee-4727-8c75-8cec40b65cc1.jpg)

And the widget at the same time.
![IMG_20221021_153332_1](https://user-images.githubusercontent.com/21969523/197209107-2e116cd4-fead-4688-9c9f-4097b9e8c19e.jpg)

**Comment by AlvaroBrey** [comment] 2022-10-21 13:44
Thanks, managed to reproduce it by leaving some unread messages in the Trash and one in the Inbox. As you say, all of them appear in the Android widget, but only the one in Inbox appears in the web dashboard.

**Comment by AlvaroBrey** [comment] 2022-10-21 13:45
Looks like a server problem, will report in the Mail app.

**Comment by joshtrichards** [comment] 2023-12-14 03:05
Closing in favor of nextcloud/mail#7475 and because there's nothing to be done here in the Android client.

Hopefully some of the recent isolation steps posted there (in https://github.com/nextcloud/mail/issues/7475#issuecomment-1824047710) will lead to someone digging into what the cause is.

**Closed by joshtrichards** 2023-12-14 03:05 UTC
Labels: bug, approved, feature: dashboard and widgets
