### ISSUE TITLE
Autosync settings do not collapse pictures (visual bug) 

### ISSUE THREAD

**Issue by Solarer** [nextcloud/android#9417] opened 2021-12-01 10:39 UTC
### Steps to reproduce
1. Go to the settings of Autosync. 
2. It looks like this:
![Screenshot_20211201-112858_Nextcloud](https://user-images.githubusercontent.com/2805109/144218589-c718754f-da18-4713-a6ea-9037fcd95995.png)

and this:
![Screenshot_20211201-113818_Nextcloud](https://user-images.githubusercontent.com/2805109/144219635-c94ae197-c027-4207-8a59-865e69335658.png)

### Expected behaviour
- only the first x pictures of a folder should be displayed followed by a SINGLE box with a number that shows how many pictures are contained in the folder. 

### Actual behaviour
- I can see the first x pictures followed by all other pictures each overlayed with the total number. Very annoying in big folders (1000+ images) 

### Can you reproduce this problem on https://try.nextcloud.com?
Will try. 

### Environment data
Android version: 10

Device model: SM-510F

Stock or customized system: Lineage OS 17.1 build from 21th November 2021

Nextcloud app version: 3.18.0

Nextcloud server version: 22.2.3 fpm docker 

Reverse proxy: nginx

**Comment by AlvaroBrey** [comment] 2021-12-01 10:56
Duplicate of #9311

**Closed by AlvaroBrey** 2021-12-01 10:56 UTC
Labels: bug
