### ISSUE TITLE
What is this

### ISSUE THREAD

**Issue by 0796665100** [nextcloud/android#13439] opened 2024-08-22 12:28 UTC
### Cause of error
```java
Exception in thread "Thread-4" java.lang.IllegalArgumentException: Trying to execute a sync operation with a storage manager for an anonymous account
    at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:49)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$fetchExternalLinks$9(DrawerActivity.java:1231)
    at com.owncloud.android.ui.activity.DrawerActivity.$r8$lambda$oHM2j1MZkviAIdyIFWoI2kSeF9c(Unknown Source:0)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `dm3q`
* Model: `SM-S918B`
* Id: `UP1A.231005.007`
* Product: `dm3qxxx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S918BXXS6CXG8`

**Comment by 0796665100** [comment] 2024-08-22 12:28
What is this

**Comment by joshtrichards** [comment] 2024-08-22 14:44
Duplicate of #13323

**Closed by joshtrichards** 2024-08-22 14:44 UTC
