### ISSUE TITLE
Auto upload files previously disallowed from using mobile network will not sync over mobile network after reconfiguring to allow over mobile network

### ISSUE THREAD

**Issue by sadr0b0t** [nextcloud/android#4312] opened 2019-08-12 09:59 UTC
### Actual behaviour
- Take some photos without wifi connected and sync over mobile internet switched off
- See, that new photos are added to sync queue with "waiting for wifi connection to be synced" status (this is ok)
- Go to sync setting and allow sync over mobile internet
- Make some additional photos after that
- Go to Nextcloud sync status queue and see that new photos are synced over mobile network and old photos still do not sync with "waiting for wifi connection to be synced" status

### Expected behaviour
- Old photos added earlier to sync queue should also sync over mobile network when allowed to sync over mobile internet network

### Environment data
Android version: 
8.0.0
Device model: 
Xiaomi
Stock or customized system:
stock
Nextcloud app version:
3.7.1

**Comment by tobiasKaminsky** [comment] 2019-08-12 12:16
Indeed this is a known bug (maybe there is even an issue for it), it also has a PR: https://github.com/nextcloud/android/pull/2257

**Comment by joshtrichards** [comment] 2023-11-07 23:21
Duplicate of #2018

Let's consolidate tracking/discussion there. Feel free to subscribe to that issue (or upvote it to express your interest in it).

**Closed by joshtrichards** 2023-11-07 23:21 UTC
Labels: bug, approved, pr exists, feature: auto upload, connectivity, feature: data usage
