### ISSUE TITLE
auto upload doesn`t auto upload files 

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [nextcloud/android#3378] opened 2018-12-16 10:13 UTC
### Actual behaviour
- If you create some files in folder and after it you create auto upload rule for this folder.
- Auto upload works only for new created files in this folder. Old files never uploaded.
- Force rescan don`t work. 

### Expected behaviour
auto upload must work for all files in folder 
 
### Steps to reproduce
1. make any folder
2. make some files in this folder 
3. create auto upload rule for this folder 
4. create new file in this folder
5. check nextcloud server you will see only file from step number 4. 
6. go to android Uploads and choose Force rescan you see no effect

### Environment data
Android version: 8.1.0

Device model: Cat S61 

Stock or customized system: Stock

Nextcloud app version: latest 

Nextcloud server version: latest

### Logs
Not related

**Comment by AndyScherzinger** [comment] 2018-12-16 11:12
Yet another duplicate of #285, please follow up there.

**Closed by AndyScherzinger** 2018-12-16 11:12 UTC
Labels: bug

**Comment by AndyScherzinger** [comment] 2020-02-18 17:22
to be released with 3.11. via #4788
