### ISSUE TITLE
Exception on opening PDF file

### ISSUE THREAD

**Issue by ne20002** [nextcloud/android#13720] opened 2024-10-06 13:20 UTC
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
    at com.owncloud.android.datamodel.OCFile.isInternalFolderSync(OCFile.java:1058)
    at com.owncloud.android.ui.fragment.FileDetailFragment.updateFileDetails(FileDetailFragment.java:569)
    at com.owncloud.android.ui.fragment.FileDetailFragment.onViewCreated(FileDetailFragment.java:266)
    at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3152)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:608)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2059)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:702)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7924)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300090`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `gts4lvwifi`
* Model: `SM-T720`
* Id: `TQ3A.230901.001`
* Product: `gts4lvwifixx`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `eng.root.20240925.150233`

**Comment by joshtrichards** [comment] 2024-10-06 14:48
Duplicate of #13502

**Closed by joshtrichards** 2024-10-06 14:48 UTC

**Comment by ne20002** [comment] 2024-10-06 16:52
@joshtrichards 

Yes, kind of. Sorry. But I wanted to give a bit more information.

This happened reproducable (for me) when trying to open a pdf file in the app.

- click on the pdf
- download starts (as indicated by icon in notification bar) and
- at the same time, before the pdf file has been downloaded, this exception occures
- there is no download/details page shown with the download progress bar

If I download the file to the device first, then opening the pdf works without problems.
Also, this is not poping up by all pdf files but reproducable with the same files (delete on device, try again).
