### ISSUE TITLE
Adding AutoUpload folders causes Android app to be unresponsive and crash on reopening

### ISSUE THREAD

**Issue by keithallenjackson** [nextcloud/android#5878] opened 2020-04-15 16:40 UTC
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
************ CAUSE OF ERROR ************

android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@2635c10 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1056)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:381)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
	at android.app.Dialog.show(Dialog.java:470)
	at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
	at com.owncloud.android.ui.activity.SyncedFoldersActivity.showBatteryOptimizationInfo(SyncedFoldersActivity.java:876)
	at com.owncloud.android.ui.activity.SyncedFoldersActivity.onSyncStatusToggleClick(SyncedFoldersActivity.java:627)
	at com.owncloud.android.ui.adapter.SyncedFolderAdapter.lambda$onBindHeaderViewHolder$0$SyncedFolderAdapter(SyncedFolderAdapter.java:272)
	at com.owncloud.android.ui.adapter.-$$Lambda$SyncedFolderAdapter$fshxXiWHiKTHftgwCe26UEsEx80.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:7356)
	at android.view.View.performClickInternal(View.java:7322)
	at android.view.View.access$3200(View.java:846)
	at android.view.View$PerformClick.run(View.java:27804)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7073)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: dream2qlteue
Model: SM-G955U1
Id: PPR1.180610.011
Product: dream2qlteue

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G955U1UES7DTC1

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by InfamousUser** [comment] 2020-04-15 18:22
There's a ton of these issues showing up.

**Comment by ezaquarii** [comment] 2020-04-15 21:47
Possibly related to https://github.com/nextcloud/android/issues/5882

**Comment by ezaquarii** [comment] 2020-04-15 21:48
> There's a ton of these issues showing up.

@tobiasKaminsky I assume it is related to https://github.com/nextcloud/android/issues/5882

**Comment by tobiasKaminsky** [comment] 2020-04-16 07:08
From stacktrace this is related to showing a dialog.
But yes, might be due to hanging UI, which will be fixed via #5885 

This will be in upcoming 3.11.1. (RC1 available on beta channel today or tomorrow)
Can you test this and then report back?

**Comment by keithallenjackson** [comment] 2020-04-16 16:15
Absolutely! Let me know when it is available within the beta and how to
obtain it and I will definitely report back!

**Comment by InfamousUser** [comment] 2020-04-17 14:06
It is available now on Play Store as beta.
Now able to open app. Opening uploads from menu which is full of autouploads crashes the app.

**Comment by ezaquarii** [comment] 2020-04-17 17:22
On Fri, Apr 17, 2020 at 07:06:19AM -0700, InfamousUser wrote:
> Now able to open app. Opening uploads from menu which is full of autouploads crashes the app.

Do you have a stacktrace?

**Comment by InfamousUser** [comment] 2020-04-17 19:52
Sorry I don't know what that is, I looked it up but I don't know how to access the stack on Android, not a programmer.

**Comment by ezaquarii** [comment] 2020-04-17 19:59
@InfamousUser There should be a popup with a stacktrace. If there is no pop-up, you are referring to a different bug than this issue describes (please see stacktrace in the ticket description).

**Comment by keithallenjackson** [comment] 2020-04-17 21:06
Downloaded beta and the freezing is fixed! However, no uploads ever start
(this was true for the non-beta as well).

**Comment by InfamousUser** [comment] 2020-04-18 01:48
> @InfamousUser There should be a popup with a stacktrace. If there is no pop-up, you are referring to a different bug than this issue describes (please see stacktrace in the ticket description).

I will open a different issue.

**Comment by InfamousUser** [comment] 2020-04-18 02:13
Another error on uploads screen:

************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.SecurityException: Caller no longer running, last stopped +2s613ms because: timed out while starting
	at android.os.Parcel.createException(Parcel.java:2071)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:292)
	at android.app.job.JobParameters.dequeueWork(JobParameters.java:248)
	at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
	at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobServiceContext.assertCallerLocked(JobServiceContext.java:493)
	at com.android.server.job.JobServiceContext.doDequeueWork(JobServiceContext.java:371)
	at com.android.server.job.JobServiceContext$JobCallback.dequeueWork(JobServiceContext.java:160)
	at android.app.job.IJobCallback$Stub.onTransact(IJobCallback.java:169)
	at android.os.Binder.execTransactInternal(Binder.java:1021)

**Comment by tobiasKaminsky** [comment] 2020-04-21 06:32
> Downloaded beta and the freezing is fixed!

Nice. Then this bug is fixed.



> However, no uploads ever start (this was true for the non-beta as well).

Can you open up a new issue (or search for an existing one?)



> Another error on uploads screen (on RC):

This is unrelated, I guess.

**Closed by tobiasKaminsky** 2020-04-21 06:32 UTC
Labels: bug, needs info/discussion
