### ISSUE TITLE
[Feature request] Add ability to edit the backup path prior to turning backup on

### ISSUE THREAD

**Issue by samolego** [nextcloud/android#13216] opened 2024-07-01 20:13 UTC
### Is your feature request related to a problem? Please describe.
Currently auto backup works in an inconvenient way. When you want to add e.g. new album to be uploaded to /Photos/, you have to turn it on, edit the path to /Photos/, wait for backup to complete, then move files manually. I've tried cancelling the upload (so the job would be redone with the new path), but it didn't come back then. 

### Describe the solution you'd like
Currently the field fpr serring backup path is disabled if the backup is disabled. I'd like to be able to set the path prior to turning on backup option (so the job gets the right path first time).
Alternatively , what could be even better, would be setting all photos default path?

### Describe alternatives you've considered
Currently a workaround that I think works in turning off internet connection, turning on backup, editing the path, then tuening on the connection.

**Comment by joshtrichards** [comment] 2024-07-02 20:55
Duplicate of #8418 

Note, toggling on doesn't start any uploads. You can modify the destination folder/etc. Until you click the *Save* button nothing will start.

**Closed by joshtrichards** 2024-07-02 20:55 UTC
Labels: enhancement
