### ISSUE TITLE
Upload folder selection doesn't work

### ISSUE THREAD

**Issue by achmetinternet** [nextcloud/android#10564] opened 2022-07-27 21:20 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Open app, then go to settings and try to modify the folders that will be synced to the cloud.

### Expected behaviour

Should show the folders to be uploaded from.

### Actual behaviour

Error

### Android version

11

### Device brand and model

Xiaomi Mi9 SE

### Stock or custom OS?

Stock

### Nextcloud android app version

3.20.3

### Nextcloud server version

Latest

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "DefaultDispatcher-worker-1" java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.TimSort.mergeHi(TimSort.java:899)
    at java.util.TimSort.mergeAt(TimSort.java:516)
    at java.util.TimSort.mergeCollapse(TimSort.java:441)
    at java.util.TimSort.sort(TimSort.java:245)
    at java.util.Arrays.sort(Arrays.java:1424)
    at com.owncloud.android.utils.SyncedFolderUtils.getFileList(SyncedFolderUtils.java:233)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.createSyncedFolderWithoutMediaFolder(SyncedFoldersActivity.kt:366)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.mergeFolderData(SyncedFoldersActivity.kt:359)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.access$mergeFolderData(SyncedFoldersActivity.kt:82)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$load$1.invokeSuspend(SyncedFoldersActivity.kt:306)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `Xiaomi`
* Device: `grus`
* Model: `Mi 9 SE`
* Id: `RKQ1.200826.002`
* Product: `grus_eea`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `V12.5.1.0.RFBEUXM`

**Comment by AlvaroBrey** [comment] 2022-08-03 13:13
The stack trace is  a duplicate of #9638

**Closed by AlvaroBrey** 2022-08-03 13:13 UTC
Labels: bug
