### ISSUE TITLE
Unexpected Crash

### ISSUE THREAD

**Issue by JahidFariz** [nextcloud/android#8970] opened 2021-09-11 11:24 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to pause activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@102aaaf9
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4322)
	at android.app.ActivityThread.access$1000(ActivityThread.java:188)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1536)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:210)
	at android.app.ActivityThread.main(ActivityThread.java:5839)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@102aaaf9
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:786)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1856)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:522)
	at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.onInactive(UsbConnectionDispatcher.java:131)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.ensureStateInactive(SecurityKeyManager.java:316)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.refreshActiveState(SecurityKeyManager.java:290)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.onActivityPaused(SecurityKeyManager.java:333)
	at android.app.Application.dispatchActivityPaused(Application.java:225)
	at android.app.Activity.onPause(Activity.java:1491)
	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:388)
	at com.owncloud.android.ui.activity.BaseActivity.onPause(BaseActivity.java:84)
	at com.owncloud.android.ui.activity.FileActivity.onPause(FileActivity.java:253)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onPause(FileDisplayActivity.java:1254)
	at android.app.Activity.performPause(Activity.java:6288)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1321)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2705)
	... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: OPPO
Device: X9009
Model: X9009
Id: LMY47I
Product: X9009

************ FIRMWARE ************
SDK: 22
Release: 5.1
Incremental: 1584563916

**Comment by AlvaroBrey** [comment] 2021-09-11 19:16
Duplicate of #8585

**Closed by AlvaroBrey** 2021-09-11 19:16 UTC
Labels: bug
