### ISSUE TITLE
Crash on operations

### ISSUE THREAD

**Issue by mcjak97** [nextcloud/android#12638] opened 2024-03-03 21:11 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Moving files from one folder to another.

### Expected behaviour

Files should moving without crash the app.

### Actual behaviour

Files disappear from initial location and not appear on the final location.

### Android version

14

### Device brand and model

Google Pixel 7

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.0

### Nextcloud server version

28.0.3

### Using a reverse proxy?

No

### Android logs

[Error nextcloud.txt](https://github.com/nextcloud/android/files/14474602/Error.nextcloud.txt)

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.Stack.push(java.lang.Object)' on a null object reference
    at com.owncloud.android.ui.activity.FileDisplayActivity.setSortListGroup(FileDisplayActivity.java:2496)
    at com.owncloud.android.ui.activity.FileDisplayActivity.setLeftFragment(FileDisplayActivity.java:616)
    at com.owncloud.android.ui.activity.FileDisplayActivity.startDownloadForPreview(FileDisplayActivity.java:2145)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:1101)
    at com.owncloud.android.ui.adapter.OCFileListDelegate.setItemLayoutOnClickListeners$lambda$3(OCFileListDelegate.kt:287)
    at com.owncloud.android.ui.adapter.OCFileListDelegate.$r8$lambda$DobHPKcHFAOyPw3I9tHUhxGMBtQ(Unknown Source:0)
    at com.owncloud.android.ui.adapter.OCFileListDelegate$$ExternalSyntheticLambda1.onClick(Unknown Source:4)
    at android.view.View.performClick(View.java:7658)
    at android.view.View.performClickInternal(View.java:7635)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(View.java:30167)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8248)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30280090`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `panther`
* Model: `Pixel 7`
* Id: `UQ1A.240205.002`
* Product: `panther`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `11224170`

**Comment by joshtrichards** [comment] 2024-06-13 14:55
Duplicate of #12649

**Closed by joshtrichards** 2024-06-13 14:55 UTC
Labels: bug
