### ISSUE TITLE
Auto upload does not work: Upload failed

### ISSUE THREAD

**Issue by xolyu** [nextcloud/android#11440] opened 2023-03-07 01:33 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. launch Nextcloud app
2. auto upload starts automatically
3. for all files waiting to be uploaded, an error message will appear (notification)

### Expected behaviour

Newly recognized photos should be uploaded successfully.

### Actual behaviour

1. the "Camera" folder is configured for auto upload (_since several years_)
2. New photos are recognized correctly
3. upload fails (_of automatically recognized photos_)

* Message in the Notification
  > **Upload failed**: The operation cannot be completed because...

  The notification cannot be expanded so the text is not fully visible, the display ends with "...".

* Uploads section in the app
  > Connection error

### Android version

8

### Device brand and model

Huawei Mate 10 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.1

### Nextcloud server version

25.0.4

### Using a reverse proxy?

Yes

### Android logs

```
[...]
03-07 01:57:54.397  7258  7544 D UploadsStorageManager: updateDatabaseUploadResult uploadResult: RemoteOperationResult{mSuccess=false, mHttpCode=-1, mHttpPhrase='null', mException=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getDecryptedRemotePath()' on a null object reference, mCode=HOST_NOT_AVAILABLE, message='null', getLogMessage='Unexpected exception'} upload: com.owncloud.android.operations.UploadFileOperation@f3830af
03-07 01:57:54.412  7258  7544 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/IMG_20230304_200608.jpg with status:UPLOAD_FAILED and result:NETWORK_CONNECTION (old:/storage/emulated/0/DCIM/Camera/IMG_20230304_200608.jpg status:UPLOAD_IN_PROGRESS result:-1)
03-07 01:57:54.412  7258  7544 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/IMG_20230304_200608.jpg with status=UPLOAD_FAILED
03-07 01:57:54.441  7258  7544 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20230304_200608.jpg
03-07 01:57:54.442  7258  7544 D UploadsStorageManager: notifyObserversNow
03-07 01:57:54.448  7258  7544 D FileUploader: NotifyUploadResult with resultCode: HOST_NOT_AVAILABLE
03-07 01:57:54.551  7258  7544 D FileUploader: Stopping command after id 814
03-07 01:57:54.603  7258  7544 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/IMG_20230306_235057.jpg with status:UPLOAD_IN_PROGRESS and result:UNKNOWN (old:/storage/emulated/0/DCIM/Camera/IMG_20230306_235057.jpg status:UPLOAD_IN_PROGRESS result:-1)
03-07 01:57:54.603  7258  7544 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/IMG_20230306_235057.jpg with status=UPLOAD_IN_PROGRESS
03-07 01:57:54.638  7258  7544 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20230306_235057.jpg
03-07 01:57:54.638  7258  7544 D UploadsStorageManager: notifyObserversNow
03-07 01:57:54.692  7258  7544 D UploadsStorageManager: Retrieve job com.owncloud.android.db.OCUpload@f6128cb for id 6744
03-07 01:57:54.693  7258  7544 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/IMG_20230306_235057.jpg with status=UPLOAD_IN_PROGRESS
03-07 01:57:54.711  7258  7544 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20230306_235057.jpg
03-07 01:57:54.711  7258  7544 D UploadsStorageManager: notifyObserversNow
03-07 01:57:54.867  7258  7544 E FileUploader: Error uploading
03-07 01:57:54.867  7258  7544 E FileUploader: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getDecryptedRemotePath()' on a null object reference
03-07 01:57:54.867  7258  7544 E FileUploader:  at com.owncloud.android.utils.FileStorageUtils.checkEncryptionStatus(FileStorageUtils.java:469)
03-07 01:57:54.867  7258  7544 E FileUploader:  at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:435)
03-07 01:57:54.867  7258  7544 E FileUploader:  at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:205)
03-07 01:57:54.867  7258  7544 E FileUploader:  at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:637)
03-07 01:57:54.867  7258  7544 E FileUploader:  at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1380)
03-07 01:57:54.867  7258  7544 E FileUploader:  at android.os.Handler.dispatchMessage(Handler.java:108)
03-07 01:57:54.867  7258  7544 E FileUploader:  at android.os.Looper.loop(Looper.java:166)
03-07 01:57:54.867  7258  7544 E FileUploader:  at android.os.HandlerThread.run(HandlerThread.java:65)
03-07 01:57:54.867  7258  7544 D UploadsStorageManager: updateDatabaseUploadResult uploadResult: RemoteOperationResult{mSuccess=false, mHttpCode=-1, mHttpPhrase='null', mException=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getDecryptedRemotePath()' on a null object reference, mCode=HOST_NOT_AVAILABLE, message='null', getLogMessage='Unexpected exception'} upload: com.owncloud.android.operations.UploadFileOperation@bb5efc1
03-07 01:57:54.909  7258  7544 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/IMG_20230306_235057.jpg with status:UPLOAD_FAILED and result:NETWORK_CONNECTION (old:/storage/emulated/0/DCIM/Camera/IMG_20230306_235057.jpg status:UPLOAD_IN_PROGRESS result:-1)
03-07 01:57:54.909  7258  7544 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/IMG_20230306_235057.jpg with status=UPLOAD_FAILED
03-07 01:57:54.917  7258  7544 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20230306_235057.jpg
03-07 01:57:54.917  7258  7544 D UploadsStorageManager: notifyObserversNow
03-07 01:57:54.918  7258  7544 D FileUploader: NotifyUploadResult with resultCode: HOST_NOT_AVAILABLE
03-07 01:57:54.946  7258  7544 D FileUploader: Stopping command after id 815
03-07 01:57:54.983  7258  7544 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/IMG_20230306_235042.jpg with status:UPLOAD_IN_PROGRESS and result:UNKNOWN (old:/storage/emulated/0/DCIM/Camera/IMG_20230306_235042.jpg status:UPLOAD_IN_PROGRESS result:-1)
03-07 01:57:54.983  7258  7544 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/IMG_20230306_235042.jpg with status=UPLOAD_IN_PROGRESS
03-07 01:57:54.997  7258  7544 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20230306_235042.jpg
03-07 01:57:54.997  7258  7544 D UploadsStorageManager: notifyObserversNow
03-07 01:57:55.036  7258  7544 D UploadsStorageManager: Retrieve job com.owncloud.android.db.OCUpload@bf0c6fd for id 6743
03-07 01:57:55.036  7258  7544 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/IMG_20230306_235042.jpg with status=UPLOAD_IN_PROGRESS
03-07 01:57:55.053  7258  7544 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20230306_235042.jpg
03-07 01:57:55.056  7258  7544 D UploadsStorageManager: notifyObserversNow
03-07 01:57:55.135  7258  7544 E FileUploader: Error uploading
03-07 01:57:55.135  7258  7544 E FileUploader: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getDecryptedRemotePath()' on a null object reference
03-07 01:57:55.135  7258  7544 E FileUploader:  at com.owncloud.android.utils.FileStorageUtils.checkEncryptionStatus(FileStorageUtils.java:469)
03-07 01:57:55.135  7258  7544 E FileUploader:  at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:435)
03-07 01:57:55.135  7258  7544 E FileUploader:  at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:205)
03-07 01:57:55.135  7258  7544 E FileUploader:  at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:637)
03-07 01:57:55.135  7258  7544 E FileUploader:  at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1380)
03-07 01:57:55.135  7258  7544 E FileUploader:  at android.os.Handler.dispatchMessage(Handler.java:108)
03-07 01:57:55.135  7258  7544 E FileUploader:  at android.os.Looper.loop(Looper.java:166)
03-07 01:57:55.135  7258  7544 E FileUploader:  at android.os.HandlerThread.run(HandlerThread.java:65)
[...]
```

### Additional information

Accessing Nextcloud via app works. Files can be downloaded, as well as the "manual" upload when sharing files to the Nextcloud app. Only the automatic upload of recognized files does not work.

**Comment by asonix** [comment] 2023-03-07 19:46
Having the same bug on Lineage OS 20 (Android 13) without gapps on OnePlus 9 Pro
Nextcloud 25.0.4
Client 3.24.1

```
3-07 13:41:42.506  9240  6511 D FilesUploadHelper: retry upload
03-07 13:41:42.506  9240  6511 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/2023-03-07-12-57-03-768.jpg with status=UPLOAD_IN_PROGRESS
03-07 13:41:42.510  9240  6511 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/2023-03-07-12-57-03-768.jpg
03-07 13:41:42.510  9240  6511 D UploadsStorageManager: notifyObserversNow
03-07 13:41:42.519  9240  9844 D UploadsStorageManager: QUERY: status==0 OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 AND account_name== ? ROWID: -1
03-07 13:41:42.520  9240  9844 D FilesUploadWorker: Handling 1 uploads for account asonix@cloud.asonix.dog
03-07 13:41:42.523  9240  9844 D UploadsStorageManager: Retrieve job com.owncloud.android.db.OCUpload@a047bf2 for id 331
03-07 13:41:42.523  9240  9844 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/2023-03-07-12-57-03-768.jpg with status=UPLOAD_IN_PROGRESS
03-07 13:41:42.523  9240  9844 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/2023-03-07-12-57-03-768.jpg
03-07 13:41:42.523  9240  9844 D UploadsStorageManager: notifyObserversNow
03-07 13:41:42.528  9240  9844 E FilesUploadWorker: Error uploading
03-07 13:41:42.528  9240  9844 E FilesUploadWorker: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getDecryptedRemotePath()' on a null object reference
03-07 13:41:42.528  9240  9844 E FilesUploadWorker: 	at com.owncloud.android.utils.FileStorageUtils.checkEncryptionStatus(FileStorageUtils.java:469)
03-07 13:41:42.528  9240  9844 E FilesUploadWorker: 	at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:435)
03-07 13:41:42.528  9240  9844 E FilesUploadWorker: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:205)
03-07 13:41:42.528  9240  9844 E FilesUploadWorker: 	at com.nextcloud.client.jobs.FilesUploadWorker.upload(FilesUploadWorker.kt:158)
03-07 13:41:42.528  9240  9844 E FilesUploadWorker: 	at com.nextcloud.client.jobs.FilesUploadWorker.handlePendingUploads(FilesUploadWorker.kt:106)
03-07 13:41:42.528  9240  9844 E FilesUploadWorker: 	at com.nextcloud.client.jobs.FilesUploadWorker.doWork(FilesUploadWorker.kt:89)
03-07 13:41:42.528  9240  9844 E FilesUploadWorker: 	at androidx.work.Worker$1.run(Worker.java:86)
03-07 13:41:42.528  9240  9844 E FilesUploadWorker: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
03-07 13:41:42.528  9240  9844 E FilesUploadWorker: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
03-07 13:41:42.528  9240  9844 E FilesUploadWorker: 	at java.lang.Thread.run(Thread.java:1012)
03-07 13:41:42.528  9240  9844 D UploadsStorageManager: updateDatabaseUploadResult uploadResult: RemoteOperationResult{mSuccess=false, mHttpCode=-1, mHttpPhrase='null', mException=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getDecryptedRemotePath()' on a null object reference, mCode=HOST_NOT_AVAILABLE, message='null', getLogMessage='Unexpected exception'} upload: com.owncloud.android.operations.UploadFileOperation@56680c0
03-07 13:41:42.529  9240  9844 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/2023-03-07-12-57-03-768.jpg with status:UPLOAD_FAILED and result:NETWORK_CONNECTION (old:/storage/emulated/0/DCIM/Camera/2023-03-07-12-57-03-768.jpg status:UPLOAD_IN_PROGRESS result:-1)
03-07 13:41:42.530  9240  9844 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/2023-03-07-12-57-03-768.jpg with status=UPLOAD_FAILED
03-07 13:41:42.532  9240  9844 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/2023-03-07-12-57-03-768.jpg
```

**Comment by AlvaroBrey** [comment] 2023-03-08 08:06
Duplicate of #11316

**Closed by AlvaroBrey** 2023-03-08 08:06 UTC
Labels: bug
