### ISSUE TITLE
Change account URL

### ISSUE THREAD

**Issue by ErinVoid** [nextcloud/android#12210] opened 2023-11-28 17:27 UTC
### Is your feature request related to a problem? Please describe.
It would be very useful to be able to change the URL of an existing account that's setup in the app..  Especially useful for those who use DDNS addresses which sometimes disappear.

### Describe the solution you'd like
As above.  In the manage account dialogue, option to change URLs to the same Nextcloud instance.

### Describe alternatives you've considered
There are none.  Only option appears to be delete the account and create a new one which means setting up auto-upload folders etc which can be very arduous!

### Additional context
Checked the forum etc.  Happen to use the Fdroid app but not sure it makes any difference.

**Comment by joshtrichards** [comment] 2024-09-05 15:49
Duplicate of #4157

**Closed by joshtrichards** 2024-09-05 15:49 UTC
Labels: enhancement, feature: authentication
