### ISSUE TITLE
Crash on displayed picture deletion

### ISSUE THREAD

**Issue by Apodasch** [nextcloud/android#10757] opened 2022-09-23 05:49 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Display any picture
2. Select delete from the menu
3. Application deletes the picture succesfully but it crashes

![Screenshot_2022-09-23-06-16-58-720_com nextcloud client](https://user-images.githubusercontent.com/69112899/191898760-c0fd7d22-3822-450b-ad3b-be0a3598246a.jpg)

![Screenshot_2022-09-23-06-17-11-461_com nextcloud client](https://user-images.githubusercontent.com/69112899/191898767-3dec48fb-d7cd-4ebb-b073-1696b73197c6.jpg)

![Screenshot_2022-09-23-06-17-15-120_com nextcloud client](https://user-images.githubusercontent.com/69112899/191898820-e4be411f-b6ac-41f1-b2ee-db41deb40ddf.jpg)

![Screenshot_2022-09-23-06-17-23-626_com nextcloud client](https://user-images.githubusercontent.com/69112899/191898841-f9aaad95-2ecf-46af-897d-da88d8d92cac.jpg)

### Expected behaviour

Picture should be deleted, next picture in the row should be displayed or if there is no more pictures, it should return to the folder content view.

### Actual behaviour

Picture is deleted, application crashes.

### Android version

11

### Device brand and model

Xiaomi Mi 9 SE

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.2

### Nextcloud server version

FileRun server used - unknown version

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.services.OperationsService$OperationsServiceBinder.isSynchronizing(OperationsService.java:372)
    at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:532)
    at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:521)
    at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:201)
    at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:133)
    at com.owncloud.android.ui.preview.PreviewImageFragment.onPrepareOptionsMenu(PreviewImageFragment.java:381)
    at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:3253)
    at androidx.fragment.app.FragmentManager.dispatchPrepareOptionsMenu(FragmentManager.java:3051)
    at androidx.fragment.app.FragmentManager$2.onPrepareMenu(FragmentManager.java:466)
    at androidx.core.view.MenuHostHelper.onPrepareMenu(MenuHostHelper.java:63)
    at androidx.activity.ComponentActivity.onPrepareOptionsMenu(ComponentActivity.java:497)
    at android.app.Activity.onPreparePanel(Activity.java:4325)
    at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3148)
    at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1936)
    at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2190)
    at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:273)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1076)
    at android.view.Choreographer.doCallbacks(Choreographer.java:897)
    at android.view.Choreographer.doFrame(Choreographer.java:822)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:236)
    at android.app.ActivityThread.main(ActivityThread.java:8061)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210290`
* Build flavor: `gplay`

### Device information
* Brand: `Xiaomi`
* Device: `grus`
* Model: `Mi 9 SE`
* Id: `RKQ1.200826.002`
* Product: `grus_eea`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `V12.5.1.0.RFBEUXM`

**Comment by AlvaroBrey** [comment] 2022-09-23 09:27
Duplicate of #10580

**Closed by AlvaroBrey** 2022-09-23 09:27 UTC
Labels: bug

**Comment by Apodasch** [comment] 2022-09-23 11:44
Hello AlvaroBrey,
Will you be working on this, or is that already fixed in the next version?
Thank you very much!

**Comment by AlvaroBrey** [comment] 2022-09-23 12:33
@Apodasch fixed in the next version

**Comment by Apodasch** [comment] 2022-09-23 15:56
Thank you for quick response!
