### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Zeroocooloverride** [nextcloud/android#13434] opened 2024-08-21 12:46 UTC
### Cause of error
```java
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property currentAccount has not been initialized
    at com.nextcloud.client.mixins.SessionMixin.getCurrentAccount(SessionMixin.kt:32)
    at com.nextcloud.client.mixins.SessionMixin.onRestart(SessionMixin.kt:100)
    at com.nextcloud.client.mixins.MixinRegistry.onRestart(MixinRegistry.kt:48)
    at com.owncloud.android.ui.activity.BaseActivity.onRestart(BaseActivity.java:118)
    at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1581)
    at android.app.Activity.performRestart(Activity.java:8705)
    at android.app.ActivityThread.performRestartActivity(ActivityThread.java:5575)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:245)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2426)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:211)
    at android.os.Looper.loop(Looper.java:300)
    at android.app.ActivityThread.main(ActivityThread.java:8503)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `Redmi`
* Device: `veux`
* Model: `2201116SG`
* Id: `TKQ1.221114.001`
* Product: `veux_eea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `V816.0.3.0.TKCEUXM`

**Comment by joshtrichards** [comment] 2024-08-21 18:02
Duplicate of #13241

**Closed by joshtrichards** 2024-08-21 18:02 UTC
