### ISSUE TITLE
Crash on back in "on this device" view

### ISSUE THREAD

**Issue by Vinschni** [nextcloud/android#5449] opened 2020-02-11 04:52 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{defe6df u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7
Model: GM1903
Id: QKQ1.190716.003
Product: OnePlus7_EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 1912061900

### Steps to reproduce
1. Hit back Button while in "on this device" view.

**Comment by thgoebel** [comment] 2020-03-05 09:12
Duplicate of #2010 ?

**Comment by AndyScherzinger** [comment] 2020-03-09 09:52
Duplicate of #2010

**Closed by AndyScherzinger** 2020-03-09 09:52 UTC
Labels: bug
