### ISSUE TITLE
3.0.2 auto upload with subfolder ==> fails new subfolder not created

### ISSUE THREAD

**Issue by fyah** [nextcloud/android#2272] opened 2018-03-03 09:10 UTC
### Actual behaviour
-when new subfoder needs to be created (i.e 03 under 2018) it is not created and auto upload fails

### Expected behaviour
-when new subfolder is needed, it shall be created (it was before)
 
### Steps to reproduce
1. enable auto upload for a folder, enable the subfolder option
2. wait for month to change
3. new subfolder for new month is not created, upload fails with reason server connection failed

creating the subfolder manually fixes the errors, and files gets retried and uploaded ok

### Environment data
Android version: 8.0.0

Device model: oneplus 3

Stock or customized system: stock

Nextcloud app version: 3.0.2

Nextcloud server version:13.0.0

**Comment by bes1967** [comment] 2018-03-03 09:39
Same here. Even after manual creating directory autoupload fails with connection error. Everything was ok till 28 february.

**Comment by llucax** [comment] 2018-03-03 11:00
I can confirm this. I got "Connection error" for all March uploads. I couldn't figure out what was going on as any other service with my server worked (even within the Nextcloud app). Server logs said nothing (only `/status.php` was hit in apache logs when I used the "Retry failed" option, but not when hitting a single file). Also no logs produced when retrying uploads in the App logs.

Besides fixing the bug, it might be useful to improve logging in the App, as it was virtually impossible to find out what was going on!

Thanks!

Android: 7.0
Device: LG G6 stock
Nextcloud App: 3.0.3
Nextcloud Server: 12.0.5

**Comment by rtfmjoey** [comment] 2018-03-03 11:04
Same here, creating the 03 folder manually solved the upload issue for now.

**Comment by wlp7s0** [comment] 2018-03-03 11:06
Same here. Manually creating subfolder doesn't help, fails with connection error. 
Workaround is to disable "Use subfolders" option in parameters. Actually, according to server logs, connection is never requested. Manual upload to the same subfolder of the same file works. 
Nextcloud server: 13.0.0
Nextcloud app: 3.0.2

Android app logs (not very usefull):

> 2018/03/03 03:22:15
> UploadsStorageManager : notifyObserversNow
> 
> 2018/03/03 03:22:15
> UploadsStorageManager : Updating /storage/emulated/0/DCIM/Camera/IMG_20180303_031838.jpg with status:UPLOAD_IN_PROGRESS and result:UNKNOWN (old:/storage/emulated/0/DCIM/Camera/IMG_20180303_031838.jpg status:UPLOAD_IN_PROGRESS result:-1)
> 
> 2018/03/03 03:22:15
> UploadsStorageManager : Updating /storage/emulated/0/DCIM/Camera/IMG_20180303_031838.jpg with status=UPLOAD_IN_PROGRESS
> 
> 2018/03/03 03:22:15
> UploadsStorageManager : updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20180303_031838.jpg
> 
> 2018/03/03 03:22:15
> UploadsStorageManager : notifyObserversNow
> 
> 2018/03/03 03:22:15
> UploadsStorageManager : Updating /storage/emulated/0/DCIM/Camera/IMG_20180303_031838.jpg with status=UPLOAD_IN_PROGRESS
> 
> 2018/03/03 03:22:15
> ExpandableUploadListAdapter : refreshView
> 
> 2018/03/03 03:22:15
> ExpandableUploadListAdapter : loadUploadItemsFromDb
> 
> 2018/03/03 03:22:15
> UploadsStorageManager : updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20180303_031838.jpg
> 
> 2018/03/03 03:22:15
> UploadsStorageManager : notifyObserversNow
> 
> 2018/03/03 03:22:15
> FileUploader : Error uploading Exception : [com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:374), com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145), com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:149), com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:93), com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:1090), com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1023), android.os.Handler.dispatchMessage(Handler.java:102), android.os.Looper.loop(Looper.java:163), android.os.HandlerThread.run(HandlerThread.java:61)]
> 
> 2018/03/03 03:22:15
> UploadsStorageManager : updateDatabaseUploadResult uploadResult: com.owncloud.android.lib.common.operations.RemoteOperationResult@6f000f2 upload: com.owncloud.android.operations.UploadFileOperation@1a65343
> 
> 2018/03/03 03:22:15
> UploadsStorageManager : Updating /storage/emulated/0/DCIM/Camera/IMG_20180303_031838.jpg with status:UPLOAD_FAILED and result:NETWORK_CONNECTION (old:/storage/emulated/0/DCIM/Camera/IMG_20180303_031838.jpg status:UPLOAD_IN_PROGRESS result:-1)
> 
> 2018/03/03 03:22:15
> UploadsStorageManager : Updating /storage/emulated/0/DCIM/Camera/IMG_20180303_031838.jpg with status=UPLOAD_FAILED

**Comment by llucax** [comment] 2018-03-03 11:49
> Same here. Manually creating subfolder doesn't help, fails with connection error.

I have the feeling you might be experiencing a different (but maybe connected) issue, because I got nothing in the logs about any upload failing and manually creating the folder fixed the issue for the other people too.

**Comment by wlp7s0** [comment] 2018-03-03 11:55
@bes1967 in the second comment reported the same issue. Dunno if you are right, but disabling subfolder usage solved connection issue )

**Comment by pfinardi** [comment] 2018-03-03 16:16
Manually creating subfolder works for me.
Nextcloud server: 13.0.0
Nextcloud app: 3.0.2

**Comment by janipewter** [comment] 2018-03-03 16:59
Same problem here. Also "upload only when charging" and "upload only on WiFi" settings are not respected. Nextcloud immediately attempts to upload files even when not charging or on WiFi and fails with "connection error".

Creating the 03 folder manually is a successful workaround for me. But I'm still curious as to why I am getting "connection error" when it should not even be trying to upload.

**Comment by borekon** [comment] 2018-03-04 12:57
Same here. Creating folders by hand solves the problem

**Comment by ftoledo** [comment] 2018-03-04 21:09
i'm create all 03 subfolder into Camera,Facebook,Screenshots etc.. and work.

**Comment by wlp7s0** [comment] 2018-03-05 12:12
3.0.3 subfolder uploads works again.
Thank you!

**Comment by xXSTrikeXx** [comment] 2018-03-05 13:33
Since @wlp7s0 tested it, closing this issue. Feel free to reopen, when you have problems with subfolders, but version 3.0.3 should fix it.

**Closed** 2018-03-05 13:33 UTC
