### ISSUE TITLE
Sony X, Android, Nextcloud client: Every time error... =(

### ISSUE THREAD

**Issue by starklnx** [nextcloud/android#5863] opened 2020-04-13 09:16 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.SecurityException: Caller no longer running, last stopped +14s416ms because: timed out while starting
	at android.os.Parcel.readException(Parcel.java:1960)
	at android.os.Parcel.readException(Parcel.java:1899)
	at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:191)
	at android.app.job.JobParameters.dequeueWork(JobParameters.java:196)
	at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
	at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: F8132
Model: F8132
Id: 41.3.A.2.149
Product: F8132

************ FIRMWARE ************
SDK: 26
Release: 8.0.0

**Comment by tobiasKaminsky** [comment] 2020-04-14 06:13
Do you have any steps to reproduce?

**Comment by tobiasKaminsky** [comment] 2020-04-14 06:15
Duplicate of #5805

**Closed by tobiasKaminsky** 2020-04-14 06:15 UTC
Labels: bug, needs info/discussion
