### ISSUE TITLE
A more detailed dialog box when attempt to play a media fails - e.g. for failures due to self-signed certificates

### ISSUE THREAD

**Issue by karezza** [nextcloud/android#8692] opened 2021-07-14 02:20 UTC
In my case it took months to discover that if the nextcloud server is using self-signed certificates, that the android mobile app will not play any media when self-signed certificates are used.  The only error which is displayed is something like, "the local media player was unable to play the media".

At this point, being deeply technical, it should have been possible for me to track down the issue and fix it quickly.  But the error message did not lead to an obvious fix.

Some additional wording, or an error number, would have been so helpful.  Maybe even some sort of popup that remains on the main screen which says "invalid certificates" that when clicked displays, "the server you are connected to is using self-signed certificates, valid certificates (not-self signed) are required when playing media files".

**Comment by joshtrichards** [comment] 2023-11-25 18:21
Likely a duplicate of #9908
Was fixed in #9945
@karezza - If you are still experiencing this let me know and i"ll re-open.

**Closed by joshtrichards** 2023-11-25 18:21 UTC
Labels: enhancement, feature: media player, connectivity
