### ISSUE TITLE
Java crash, machine null object reference issue 

### ISSUE THREAD

**Issue by qcdebug** [nextcloud/android#12857] opened 2024-04-10 22:52 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Go back to home from looking at uploads screen 

### Expected behaviour

Goes to home screen

### Actual behaviour

Crashes with log below

### Android version

13

### Device brand and model

Samsung galaxy

### Stock or custom OS?

Stock

### Nextcloud android app version

30280190

### Nextcloud server version

28.0.3

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.Stack.push(java.lang.Object)' on a null object reference
    at com.owncloud.android.ui.activity.FileDisplayActivity.setSortListGroup(FileDisplayActivity.java:2497)
    at com.owncloud.android.ui.activity.FileDisplayActivity.setLeftFragment(FileDisplayActivity.java:616)
    at com.owncloud.android.ui.activity.FileDisplayActivity.setLeftFragment(FileDisplayActivity.java:604)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onNewIntent(FileDisplayActivity.java:571)
    at android.app.Activity.performNewIntent(Activity.java:8607)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1484)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1497)
    at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:4365)
    at android.app.ActivityThread.handleNewIntent(ActivityThread.java:4372)
    at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8762)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30280190`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `c1q`
* Model: `SM-N981U`
* Id: `TP1A.220624.014`
* Product: `c1qsqw`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `N981USQS6HXA1`

**Comment by alperozturk96** [comment] 2024-04-12 08:16
@qcdebug This problem should be solved via latest version of Android app

**Comment by joshtrichards** [comment] 2024-06-13 14:13
Duplicate of #12649

**Closed by joshtrichards** 2024-06-13 14:13 UTC
Labels: bug, needs info, performance: NPE :no_entry_sign:, Version/3028
