### ISSUE TITLE
Synchronization crash

### ISSUE THREAD

**Issue by piojan** [nextcloud/android#4517] opened 2019-09-16 21:19 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{eb5c589 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWBLA
Model: BLA-L29
Id: HUAWEIBLA-L29S
Product: BLA-L29

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 306C432

### Actual behaviour
- Folder sync had no proggress

### Expected behaviour
- sync should finish
 
### Steps to reproduce
1. Client already configured and have a synced folder
2. On specific folder menu selecting sync
3. Waiting few minutes for the crush

### Environment data
Android version: 9.1

Device model: 

Stock or customized system: stock

Nextcloud app version: 3.8.0

Nextcloud server version: 16

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by danielb42** [comment] 2019-09-27 11:28
```
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{a02b24b u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1879)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7063)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a40
Model: SM-A405FN
Id: PPR1.180610.011
Product: a40eea

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: A405FNXXU2ASG1
```

**Comment by tobiasKaminsky** [comment] 2019-10-09 13:42
Duplicate of #2010

**Closed by tobiasKaminsky** 2019-10-09 13:42 UTC
Labels: bug
