### ISSUE TITLE
crash when need to relogin

### ISSUE THREAD

**Issue by evilbulgarian** [nextcloud/android#8326] opened 2021-04-28 20:12 UTC
### Steps to reproduce
1. Click on invalid user prompt from notifications
2. Crash
3. 

### Expected behaviour
- login screen

### Actual behaviour
- crash

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model: oneplus 7t

Stock or customized system: stock

Nextcloud app version: beta user 

Nextcloud server version: 21.0.1

Reverse proxy: nginx

#### Web server error log
```
Insert your webserver log here
```

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7T
Model: HD1900
Id: RKQ1.201022.002
Product: OnePlus7T

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2104060845

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by evilbulgarian** [comment] 2021-04-28 20:13
![Uploading Screenshot_20210428-131306.jpg…]()

**Comment by tobiasKaminsky** [comment] 2021-05-04 08:20
>     1. Click on invalid user prompt from notifications

How did you managed to have such an invalid notification?

**Comment by evilbulgarian** [comment] 2021-05-04 14:45
> > ```
> > 1. Click on invalid user prompt from notifications
> > ```
> 
> How did you managed to have such an invalid notification?

I upgraded nextcloud docker instance?

**Comment by AndyScherzinger** [comment] 2021-05-17 09:39
Duplicate of #8370

**Closed by AndyScherzinger** 2021-05-17 09:39 UTC
Labels: approved, bug
