### ISSUE TITLE
add a share without note to recipient

### ISSUE THREAD

**Issue by Cellophile** [nextcloud/android#9576] opened 2021-12-16 20:57 UTC
In Nextcloud App v 3.18.0, we can share somthing by email adress, and it's so cool. But we have to let a note to the recipient, even if it's useless. Especially since two emails are sent to the recipient, one to say that there is a share, a second to say that with the share, there is a note...

1. Would it be possible to make this note optional  ?
2. Would it be possible to send only one email, when there is a note with the share ?

If I create a share by web interface, it is possible to share without note. 

![Screenshot_20211216-215037](https://user-images.githubusercontent.com/70097501/146447369-1eba6cdc-4a2d-4851-8b4b-a09129809d2c.png)

Thank you :)

**Comment by AlvaroBrey** [comment] 2021-12-17 08:17
Duplicate of #9308

**Closed by AlvaroBrey** 2021-12-17 08:17 UTC
Labels: enhancement
