### ISSUE TITLE
Tapping an item in the uploads menu causes interface to freeze for a couple of seconds.

### ISSUE THREAD

**Issue by InfamousUser** [nextcloud/android#5898] opened 2020-04-18 01:59 UTC
### Steps to reproduce
1.  Have uploads
2. Go to uploads menu
3. Scroll up and down 20+ times and observe no lag or freeze
4. Stop the scrollment
5. Tap an item (text or image, which have no action)
6. Immediately try to scroll up and down again

### Expected behaviour
3 and 6 should be identical.

### Actual behaviour
There is complete app interface freeze at 6 which doesn't happen at 3.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model:  Google Pixel

Stock or customized system: stock

Nextcloud app version: 3.11.1 RC1

Nextcloud server version: 18.0.3

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ezaquarii** [comment] 2020-04-18 13:02
For stable version, this should be fixed in https://github.com/nextcloud/android/pull/5885
For current development branch, this *will* be fixed in https://github.com/nextcloud/android/pull/5879

@InfamousUser you can use the built QA apk from https://github.com/nextcloud/android/pull/5879 to see if the problem is fixed for you there.

**Comment by ezaquarii** [comment] 2020-04-18 13:05
@InfamousUser There is a workaround for this problem - disable "Auto upload existing files" in folder configuration before enabling auto upload.

**Comment by InfamousUser** [comment] 2020-04-18 13:10
Doesn't need a workaround as it is just annoying, not limiting in any way, but the workaround does not work. Auto upload existing files was never enabled.

**Comment by InfamousUser** [comment] 2020-04-18 13:16
I tried to install the "QA" app but it is a separate app, I don't have previous uploads there, I cannot test it as the list is empty. I am signed up for beta, I can retest on next RC or on 3.11.1 releaase.

**Comment by ezaquarii** [comment] 2020-04-18 13:26
@tobiasKaminsky Can you guide the user regarding availability if this fix in installable apk?

**Comment by tobiasKaminsky** [comment] 2020-04-20 14:53
@ezaquarii I think you mix up "auto upload" and "upload".
@InfamousUser is having troubles in view for pending uploads.

@InfamousUser on which file type do you click?
It tries to open the file, if still available, and thus it queries the available apps.

**Comment by ezaquarii** [comment] 2020-04-20 15:32
On Mon, Apr 20, 2020 at 07:53:28AM -0700, Tobias Kaminsky wrote:
> @ezaquarii I think you mix up "auto upload" and "upload".

Yes, I was thinking about auto upload. My bad.

**Comment by InfamousUser** [comment] 2020-04-20 16:37
It crashed on startup now but it crashed uppn displaying the error, how do I view the error after opening it again now?

It crashed again, now I cannot open the app without crashing, the whole phone freezes up half the times.

I wasn't "clicking" on any file in particular - I didn't even know you could open the files from the uploads menu, it never did anything when I tapped the files there.

**Comment by tobiasKaminsky** [comment] 2020-04-21 06:24
For crashes:
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by InfamousUser** [comment] 2020-04-21 14:56
Following the instructions I get `'grep' is not recognized as an internal or external command, operable program or batch file.`

**Comment by Hilzerak** [comment] 2020-04-21 15:53
fyi: For me the switch to the betachannel for the android-App solves the problems with freezes or errormessages.
the upload self is brocken as before but the app wont freeze / close or anything like that.

**Comment by InfamousUser** [comment] 2020-04-21 16:01
I did switch to beta, yes, and this happens in 3.11.1 beta channel. They fixed the crashes upon startup but there's more of them, from before 3.11, that weren't fixed.

**Comment by tobiasKaminsky** [comment] 2020-04-22 11:44
>  For me the switch to the betachannel for the android-App solves the problems with freezes or errormessages.

Good to know.
Then let us track the other problems in the other issues.

**Closed by tobiasKaminsky** 2020-04-22 11:44 UTC
Labels: bug, needs info/discussion

**Comment by InfamousUser** [comment] 2020-04-22 12:15
So, what, this problem isn't going to be fixed??
