### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by marcogiannini** [nextcloud/android#5490] opened 2020-02-18 15:36 UTC
### Steps to reproduce
1. Random crash

### Actual behaviour
- Tell us what happens

### Environment data
Android version: 9

Device model: Xiaomi mi a2 lite

Stock or customized system: stock

Nextcloud app version: 3.10.1

Nextcloud server version:

### Logs

https://pastebin.com/GKF22XWb

**Comment by AndyScherzinger** [comment] 2020-02-18 16:06
Duplicate of #4675

**Closed by AndyScherzinger** 2020-02-18 16:06 UTC
Labels: bug
