### ISSUE TITLE
cannot copy/move files from subfolder to homefolder

### ISSUE THREAD

**Issue by Ziltoidium** [nextcloud/android#6422] opened 2020-07-06 20:03 UTC
### Steps to reproduce
1. create a folder, place a file into it, a pdf for example
2. choose this file and click "move" (or copy as well)
3. now opens by default the "homefolder"
4. when you click at this point "choose", to move the file to the homefolder, this won't happen. nothing will be moved
5. my workaround is, to navigate through 2-3 folders and then choose at the end the homefolder.  then the file will be moved as expected

### Expected behaviour
- file should be moved to default homefolder

### Actual behaviour
- it wont be moved. the homefolder is not accepted as destination. just after this workaround

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: Samsung Galaxy A50

Stock or customized system: stock

Nextcloud app version: 3.12.0

Nextcloud server version: 19.0.0

Reverse proxy: none

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2020-07-07 05:48
Duplicate of #6137

**Closed by tobiasKaminsky** 2020-07-07 05:48 UTC
Labels: bug
