### ISSUE TITLE
Error Traceback Caused by Exiting From Provider Login

### ISSUE THREAD

**Issue by cyberbread-ru** [nextcloud/android#14058] opened 2024-11-20 05:06 UTC
### Cause of error
```java
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property currentAccount has not been initialized
    at com.nextcloud.client.mixins.SessionMixin.getCurrentAccount(SessionMixin.kt:32)
    at com.nextcloud.client.mixins.SessionMixin.onRestart(SessionMixin.kt:100)
    at com.nextcloud.client.mixins.MixinRegistry.onRestart(MixinRegistry.kt:48)
    at com.owncloud.android.ui.activity.BaseActivity.onRestart(BaseActivity.java:118)
    at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1465)
    at android.app.Activity.performRestart(Activity.java:8399)
    at android.app.ActivityThread.performRestartActivity(ActivityThread.java:5866)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:244)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8751)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `KDDI`
* Device: `SCV41`
* Model: `SCV41`
* Id: `SP1A.210812.016`
* Product: `SCV41_jp_kdi`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `SCV41KDU1DWC1`

**Comment by joshtrichards** [comment] 2024-11-26 23:37
Duplicate of #13241

**Closed by joshtrichards** 2024-11-26 23:37 UTC
