### ISSUE TITLE
Errors when Nextcloud runs in background

### ISSUE THREAD

**Issue by besendorf** [nextcloud/android#5180] opened 2020-01-13 17:48 UTC
### Steps to reproduce
1. usw nextcloud an automatic uploading in nackground
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- This error shows over and over 

### Environment data
Android version: 9

Device model: Oneplus 5

Stock or customized system: LineageOS with microG

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 2055, col 1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetString(Native Method)
	at android.database.CursorWindow.getString(CursorWindow.java:465)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
	at android.database.CursorWrapper.getString(CursorWrapper.java:137)
	at com.owncloud.android.datamodel.UploadsStorageManager.createOCUploadFromCursor(UploadsStorageManager.java:320)
	at com.owncloud.android.datamodel.UploadsStorageManager.getUploads(UploadsStorageManager.java:301)
	at com.owncloud.android.datamodel.UploadsStorageManager.getFailedUploads(UploadsStorageManager.java:372)
	at com.owncloud.android.files.services.FileUploader$UploadRequester.retryFailedUploads(FileUploader.java:405)
	at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:246)
	at com.owncloud.android.utils.-$$Lambda$FilesSyncHelper$kKNrggliFpEukU1kV4bap8ektCs.run(Unknown Source:12)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5
Model: ONEPLUS A5000
Id: PQ3A.190705.003
Product: OnePlus5

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.root.20190729.061740

```

**Comment by gjedeer** [comment] 2020-04-16 10:44
Hi, please reopen this issue. My story: changed nextcloud instance to a new one. Nextcloud app hanged and was completely unusable after change, so I uninstalled it and installed again. Added account and - interesting fact - auto upload folders were already selected, so maybe there was some data left over?

Anyway, this keeps me from normally using the phone, the error pops up every minute or so.

```
java.lang.IllegalStateException: Couldn't read row 2102, col 1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetString(Native Method)
	at android.database.CursorWindow.getString(CursorWindow.java:438)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
	at android.database.CursorWrapper.getString(CursorWrapper.java:137)
	at com.owncloud.android.datamodel.UploadsStorageManager.createOCUploadFromCursor(UploadsStorageManager.java:321)
	at com.owncloud.android.datamodel.UploadsStorageManager.getUploads(UploadsStorageManager.java:302)
	at com.owncloud.android.datamodel.UploadsStorageManager.getFailedUploads(UploadsStorageManager.java:368)
	at com.owncloud.android.files.services.FileUploader.retryFailedUploads(FileUploader.java:1005)
	at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:222)
	at com.owncloud.android.utils.-$$Lambda$FilesSyncHelper$fa2LBpPOxRVQOm4F_Glue5u4hdM.run(lambda)
	at java.lang.Thread.run(Thread.java:761)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Lenovo
Device: P2a42
Model: Lenovo P2a42
Id: NRD90N
Product: kuntao_row

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: P2a42_S251_171107_ROW
```

**Comment by gjedeer** [comment] 2020-04-16 10:46
To provide more information: this is NOT happening when using the application, it's the background auto upload sync crashing and creating a popup above whatever other application is currently being used.

**Comment by gjedeer** [comment] 2020-04-16 10:49
I see there are a lot of duplicates: https://github.com/nextcloud/android/issues/5548 https://github.com/nextcloud/android/issues/5474 https://github.com/nextcloud/android/issues/5539 https://github.com/nextcloud/android/issues/4919 https://github.com/nextcloud/android/issues/5785 and many more automatically closed.

Please mention me if you need more info. Nothing crazy is being synced, just 2 or 3 years of photos from the phone, most already present on the server (copied from the old instance)

**Comment by tobiasKaminsky** [comment] 2020-04-16 10:53
How big is the folder with the images?

**Comment by gjedeer** [comment] 2020-04-16 10:58
Hard to tell which folder it's crashing on, but the biggest one is 57GB / 16k files

**Comment by gjedeer** [comment] 2020-04-16 11:58
I've made an adb backup and looking at the database file with sqlite3:

```
sqlite> select count(1) from list_of_uploads;
13420
sqlite> select count(1) from list_of_uploads where status == 1 or last_result in(9,13,11,14);
13203
```

If it helps, I can share the sqlite file privately, if you tell me how to anonymize instance url/login/password

**Comment by gjedeer** [comment] 2020-04-17 08:54
BTW, started a bounty if anyone wants to tackle this problem https://www.bountysource.com/issues/86912899-errors-when-nextcloud-runs-in-background

**Comment by tobiasKaminsky** [comment] 2020-04-21 06:35
> 13203

So you have 13k of files in your upload view…Is this correct?

TBH I never tried having that much in it.

**Comment by gjedeer** [comment] 2020-04-21 20:10
It's hard to tell, the app crashes on startup now. Loads for like 30 seconds then "stopped working". It showed "send your opinion" then i clicked through to "display details" and there was something about IllegalStateException. I could not send it because another error popup appeared and this one disappeared.

**Comment by tobiasKaminsky** [comment] 2020-04-22 11:43
Can you re-install the app?
Enable auto-upload, but uncheck the option "also upload existing files"

Please report if this then works

**Comment by tobiasKaminsky** [comment] 2020-04-23 07:46
Duplicate of #5891, as I wrote some debugging infos there.

**Closed by tobiasKaminsky** 2020-04-23 07:46 UTC
Labels: bug, needs info/discussion
