### ISSUE TITLE
Stuck in auth since fingerprint is enabled

### ISSUE THREAD

**Issue by oasisck** [nextcloud/android#3115] opened 2018-10-05 12:02 UTC
### Actual behaviour
- Stuck by drawing schema or fingerprint : 
    if schema/fingerprint right = loop in "Informations d'identification erroné" (have to back as many time as tries)
    if schema/fingerprint wrong = schema incorrect

### Expected behaviour
- not stuck
 
### Steps to reproduce
1. enable fingerprint auth when I reopen the app since days

### Environment data
Android version: 8.1.0

Device model: Xiaomi mi A1

Nextcloud app version: 3.3.0

Nextcloud server version: 14.0.1

#### Web server error log
```
no log about issue
```

#### Nextcloud log (data/nextcloud.log)
```
no log about issue
```

### Additionnals info
Try 1 => reinstall app => login by user and password => stuck
Try 2 => reinstall app => login by token => OK => close app => open app => stuck
Try 3 => reinstall app => login by token => OK => settings => lock to none => stuck

**Comment by joekerna** [comment] 2018-10-09 09:02
Duplicate of #3062 ?!

**Comment by tobiasKaminsky** [comment] 2018-10-31 11:12
We had a bug with fingerprint (un)lock mechansim. It affected only a few devices, e.g. Xiaomi, Motorola, …
As none of our test deices was affected, hunting this bug down took a while.

If any of you could download and install this apk (https://cloud.nextcloud.com/s/pCwRFo7rFF3MMjM) and test if it is now working better, I would appreciate it.
(the APK file is signed with the key for Google Play Store and is 3.3.2 Alpha 1, so this proves that it is an official version and can be easily upgraded. The up-to-come 3.3.2 version then can also just update this version).

**Closed** 2018-10-31 19:37 UTC
Labels: bug

**Comment by oasisck** [comment] 2018-11-03 09:52
Thanks guys it works !
