### ISSUE TITLE
sysing and downloading

### ISSUE THREAD

**Issue by cchalifo999** [nextcloud/android#9937] opened 2022-03-08 19:39 UTC
### Steps to reproduce

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.preview.PreviewImageActivity}: java.lang.ClassCastException: android.accounts.Account cannot be cast to com.nextcloud.client.account.User
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2690)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2755)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1495)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6196)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
Caused by: java.lang.ClassCastException: android.accounts.Account cannot be cast to com.nextcloud.client.account.User
	at com.owncloud.android.ui.activity.FileActivity.onCreate(FileActivity.java:209)
	at com.owncloud.android.ui.preview.PreviewImageActivity.onCreate(PreviewImageActivity.java:107)
	at android.app.Activity.performCreate(Activity.java:6698)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2643)
	... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30190090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: perry_f
Model: Moto E (4)
Id: NDQS26.69-64-11-16
Product: perry_verizon_f

************ FIRMWARE ************
SDK: 25
Release: 7.1.1
Incremental: 23

**Comment by AlvaroBrey** [comment] 2022-03-09 08:47
Duplicate of #9935

**Closed by AlvaroBrey** 2022-03-09 08:47 UTC
Labels: bug

**Comment by cchalifo999** [comment] 2022-03-09 16:04
> Duplicate of #9935

ty
