### ISSUE TITLE
Unable to upload files via the share button in Android

### ISSUE THREAD

**Issue by sriperinkulam** [nextcloud/android#7632] opened 2020-12-08 10:02 UTC
### Steps to reproduce
1. Select file in file viewer or image gallery
2. Press the share icon/share text and select Nextcloud in the share sheet.

### Expected behaviour
- Nexcloud shows the logo on the top left.
- On swiping down the notifications, Nextcloud shows that the files are uploading or waiting to upload based on server connectivity.
- Uploaded files show up on the server

### Actual behaviour
- Nothing happens after 'Nextcloud' is selected on the share sheet.
- Files are getting uploaded to the server if I press on the + icon while in the app and navigate to the file on my phone. So looks like the issue is something to do with the sharsheet. I also had no issues before the latest update.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
8.0.0

Device model: 
Samsung galaxy edge

Stock or customized system:

Nextcloud app version:
3.14.1

Nextcloud server version:
20.0.1

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-12-08 11:21
Duplicate of #7587

**Closed by AndyScherzinger** 2020-12-08 11:21 UTC
Labels: bug
