### ISSUE TITLE
Concurrent server requests

### ISSUE THREAD

**Issue by rarealphacat** [nextcloud/android#4558] opened 2019-09-26 05:38 UTC
### Is your feature request related to a problem? Please describe.
I host my Nextcloud server on Apache2 with qos mod enabled, limiting 50 concurrent requests. It worked flawlessly on the web client especially during the photo preview load, and load almost instantly. 
But when i try to preview the same folder on Android App, the preview loads one after one at the rate of two previews a second. So I went to check the server status and turns out the number of concurrent request was 1 when i browse with Android App compared to 30 concurrent requests when i browser on web client.

### Describe the solution you'd like
I'd like to know if the number of concurrent requests can be increased in Android App to enhance performance like the Web UI

### Describe alternatives you've considered
Send the serveral preview requests to server instead of one at a time?

**Comment by st3iny** [comment] 2022-02-07 10:13
Are there any news on this? There is a long running discussion about the slow preview loading on the PreviewGenerator app and I would like to give a statement there. It seems like previews are fetched one at a time.

**Comment by Superfish1000** [comment] 2023-10-29 07:40
I would like to add that I'm seeing this same poor behavior when attempting to create a new folder while a previous file copy command is in progress.  The new folder wont be created until the entire copy is complete.

This works fine on the web, but if you're copying anything then you will need to wait.  I have had to wait over an hour for the new folder to get created after initiating a large copy and then trying to make a new folder for a subsequent copy.

**Comment by joshtrichards** [comment] 2023-12-12 13:51
While this was the original issue, there's more info in the duplicate #6855 so let's consolidate tracking/discussion there.

**Comment by joshtrichards** [comment] 2023-12-12 13:51
Duplicate of #6855

**Closed by joshtrichards** 2023-12-12 13:51 UTC
Labels: enhancement, technical debt, feature: previews and thumbnails, performance 🚀
