### ISSUE TITLE
Crash unexpected

### ISSUE THREAD

**Issue by lampgnu** [nextcloud/android#9963] opened 2022-03-14 09:53 UTC
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int, int)' on a null object reference
	at com.owncloud.android.datamodel.OCFile.getLocalId(OCFile.java:555)
	at com.owncloud.android.ui.fragment.FileDetailSharingFragment.createInternalLink(FileDetailSharingFragment.java:263)
	at com.owncloud.android.ui.fragment.FileDetailSharingFragment.copyInternalLink(FileDetailSharingFragment.java:259)
	at com.owncloud.android.ui.adapter.InternalShareViewHolder.lambda$bind$0(InternalShareViewHolder.java:72)
	at com.owncloud.android.ui.adapter.InternalShareViewHolder$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7688)
	at android.view.View.performClickInternal(View.java:7661)
	at android.view.View.access$3600(View.java:837)
	at android.view.View$PerformClick.run(View.java:29028)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30190190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: galahad
Model: M2004J19C
Id: RP1A.200720.011
Product: galahad_eea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: V12.5.4.0.RJCEUXM

**Comment by AlvaroBrey** [comment] 2022-03-14 12:15
Duplicate of #9173

**Closed by AlvaroBrey** 2022-03-14 12:15 UTC
Labels: bug
