### ISSUE TITLE
Don't start Collabora Editor

### ISSUE THREAD

**Issue by koebi80** [nextcloud/android#11979] opened 2023-09-20 05:10 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Start NextCloud App 3.26.0
2. click on a office document (doc, docx, ods, ...)

### Expected behaviour

The office document is opend in the Collabora Editor within the NextCloud.

### Actual behaviour

The office document are downloaded to the device and then the "open with" dialog will apear.

In the last version of the app, the documents were opened for editing within the app without any problems.

### Android version

8.0.0

### Device brand and model

SHIFT5me

### Stock or custom OS?

Stock

### Nextcloud android app version

3.26.0

### Nextcloud server version

26.0.2 / 27.1.0

### Using a reverse proxy?

I don't know

### Additional information

These Apps are installed on the NextCloud Servers

Nextcloud Server 26.0.2:
- Collabora Online - Built-in CODE Server 23.5.301
- Nextcloud Office 8.0.4

Nextcloud Server 27.1.0:
- Collabora Online - Built-in CODE Server 23.5.301
- Nextcloud Office 8.2.0

**Comment by rzech** [comment] 2023-09-20 20:23
I can confirm this for a similar setup (NC 27.1.0, CODE 23.5.301, NC Office 8.2.0) on Android 13 (Nextcloud App 3.26.0)

**Comment by w9hdg** [comment] 2023-09-21 16:49
I believe this is a duplicate of https://github.com/nextcloud/android/issues/11975

**Comment by koebi80** [comment] 2023-09-21 16:55
It's not exactly the same. No error message apears.

21.09.2023 18:49:32 w9hdg ***@***.***>:

**Comment by rzech** [comment] 2023-09-21 20:33
i think it is the same issue as in #11975  because the mentioned workaround worked for me:

`sudo -u www-data php occ config:app:set richdocuments mobile_editing --value="yes"`

**Comment by zpackrat** [comment] 2023-09-22 02:45
Can confirm, latest updates to v26. The issue started with v3.26 of the client. 3.25 worked fine. Pixel 7 if it matters.

**Comment by thgoebel** [comment] 2023-09-22 06:33
For me it started with the upgrade from Server 26 to Server 27, keeping the Android version at 3.25.0.
Notably for me the iOS Files app (4.8.6.4) is NOT affected.

Another symptom of this is in the "Create new file"-picker, where "Create new document/spreadsheet/presentation" options are now missing:

<img src=https://github.com/nextcloud/android/assets/33295590/bff34648-2fc3-4348-bd4c-25206eddc173 width=50%>

The occ command above (`occ config:app:set richdocuments mobile_editing --value="yes"`) only fixed this symptom in the  "Create new file"-picker for me. When I click on an .ods file, it still does NOT open in Collabora, but Android prompts me to chose an app.

**Comment by koebi80** [comment] 2023-09-24 15:38
The parameter `config:app:set richdocuments mobile_editing --value="yes"` worked for me too.

Why has this parameter never had any influence on the ability to mobile edit Office documents before?

**Comment by BiglifeMatt** [comment] 2023-10-02 17:02
Same on my setup (NC 27.0.2, CODE 22.05.18.1, NC Office 8.2.0) on Android 12 (Nextcloud App 3.26.0).  No errors as others mention.  Just cannot open the files in Collabora anymore.  They want to open in local mobile apps.  And the option to create a file is only .md file types.

**Comment by joshtrichards** [comment] 2023-10-15 15:00
The issue was fully fixed here: nextcloud/richdocuments#3184. 

Hint to future readers: If `occ config:app:set richdocuments mobile_editing --value="yes"` does not fix the matter for you then you have a different issue and should look elsewhere / create a dedicated issue.

**Closed by joshtrichards** 2023-10-15 15:00 UTC
Labels: bug, feature: editor

**Comment by thgoebel** [comment] 2023-10-15 15:23
> then you have a different issue

FYI: I've narrowed my issue down to the fact that it appears when a file is downloaded (= set as available offline). I've opened https://github.com/nextcloud/android/issues/12039 for that.
