### ISSUE TITLE
Don't backup contacts on all connected accounts

### ISSUE THREAD

**Issue by oparoz** [nextcloud/android#3217] opened 2018-11-01 21:20 UTC
### Is your feature request related to a problem? Please describe.

I do not want to backup my contacts to all my Nextcloud accounts. A single one would suffice

### Describe the solution you'd like

Present all the accounts the app knows about and let users tick the boxes of the ones where a backup should be saved

### Describe alternatives you've considered

Let us pick a single account as a 1st step maybe? I just need a single account, but others may want to have multiple backups

### Additional context

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by joshtrichards** [comment] 2023-12-05 22:24
Duplicate of #1866 

Let's consolidate tracking there. I encourage you to subscribe to that issue as well as :+1: it (which it looks like you already have - hah). :)

**Closed by joshtrichards** 2023-12-05 22:24 UTC
Labels: enhancement, feature: contacts and calendar backup
