### ISSUE TITLE
android app crash on message receive, nextcloud talk

### ISSUE THREAD

**Issue by DrekiDegga** [nextcloud/android#6610] opened 2020-08-01 23:25 UTC
### Steps to reproduce
1. Receive a message on nextcloud talk.
2. 
3. 

### Expected behaviour
- get normal notification.

### Actual behaviour
-get nextcloud crash report. Can still load messages after reloading the talk app. Nextcloud app still works as expected.

### Can you reproduce this problem on https://try.nextcloud.com?
 I didn't try but it only seems to happen on my device. No one else connected to the same server has the same issue. They are all using different devices. Maybe only a problem on  sony g8142?

### Environment data
Android version: 9

Device model: Sony G8142

Stock or customized system: stock upgraded Sony android 9

Nextcloud app version:
nextcloud talk 8.0.9
3.12.1

Nextcloud server version:
18.0.7

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-AB0yY_gNZ-P3uHm8tDJPNA==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-AB0yY_gNZ-P3uHm8tDJPNA==/lib/arm64, /data/app/com.nextcloud.client-AB0yY_gNZ-P3uHm8tDJPNA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: G8142
Model: G8142
Id: 47.2.A.10.107
Product: G8142

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 172320177

I tried reinstalling both the nextcloud app and nextcloud talk android app. Still happens.

**Comment by AndyScherzinger** [comment] 2020-08-03 19:38
Duplicate of #4675

**Closed by AndyScherzinger** 2020-08-03 19:38 UTC
Labels: bug
