### ISSUE TITLE
Nextcloud Android App Crash when trying to download and open PDF file

### ISSUE THREAD

**Issue by massenmensch** [nextcloud/android#7288] opened 2020-11-10 14:02 UTC
### Steps to reproduce
1. Open Folder with PDF File
2. Click on PDF File once
3. App crashes

### Expected behaviour
- Open PDF File with PDF Viewer

### Actual behaviour
- App crashes

### Can you reproduce this problem on https://try.nextcloud.com?
No, as it's an error within the Android App

### Environment data
Android version: 10

Device model: Huawei SNE-LX1

Stock or customized system: Stock

Nextcloud app version: 3.14.0 RC1

Nextcloud server version: /

Reverse proxy: /

#### Web server error log
```
/
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.swiperefreshlayout.widget.SwipeRefreshLayout.setVisibility(int)' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.populateList(FileDetailActivitiesFragment.java:415)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$null$3$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:370)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$ZzLUj33qKg0e1Ki8Vd5bki8I6B4.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWSNE
Model: SNE-LX1
Id: HUAWEISNE-L21
Product: SNE-LX1

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.245C432

```

**Comment by AndyScherzinger** [comment] 2020-11-10 14:31
Duplciate of #7188

**Comment by AndyScherzinger** [comment] 2020-11-10 14:31
Fix ships with RC2 which has been submitted to Google Play and should arrive on your device within the next couple of hours :)

**Comment by AndyScherzinger** [comment] 2020-11-10 14:32
Duplicate of #7188

**Closed by AndyScherzinger** 2020-11-10 14:31 UTC
Labels: bug

**Comment by AndyScherzinger** [comment] 2020-11-10 14:34
Thanks for the report @massenmensch 👍
