### ISSUE TITLE
Nextcloud Android App crashes with java.lang.NullPointerException

### ISSUE THREAD

**Issue by cbwoog** [nextcloud/android#8578] opened 2021-06-14 08:29 UTC
### Steps to reproduce
1. Samsung S5 Neo (Android 6)
2. Nextcloud instance has changed using the same URL (reason mysql update)
3. Android app did not recognise the new instance correctly 
4. Cleared cache and data of the app to have the option to start with new url setting and new login data
5. Due to problems with the new instance switched back to the old instance on truenas 
6. Cleared the app cache and data again 
7. Now Opening the nextcloud App shows every time for an instant the application fronted with the user logged in. Then underneath copied error message appears

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum
Did not happen before the instance change. 

### Environment data
Android version: 6

Device model: Samsung S5 Neo

Stock or customized system: not rooted, standard version
Nextcloud app version: 30160190

Nextcloud server version: 21.0.1.1 on truenas 

Reverse proxy: nginx

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Credentials.kt)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Credentials.kt)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:818)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: s5neolte
Model: SM-G903F
Id: MMB29K
Product: s5neoltexx

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: G903FXXU2BRH2

**Comment by AndyScherzinger** [comment] 2021-06-14 11:45
Duplicate of #8370

**Closed by AndyScherzinger** 2021-06-14 11:45 UTC
Labels: bug
