### ISSUE TITLE
error_lenover-p11

### ISSUE THREAD

**Issue by kenonix** [nextcloud/android#9046] opened 2021-10-01 06:12 UTC
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to pause activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@74f69b3
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4556)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4507)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4459)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:228)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2029)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7510)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@74f69b3
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1428)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1543)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:664)
	at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.onInactive(UsbConnectionDispatcher.java:131)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.ensureStateInactive(SecurityKeyManager.java:316)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.refreshActiveState(SecurityKeyManager.java:290)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.onActivityPaused(SecurityKeyManager.java:333)
	at android.app.Application.dispatchActivityPaused(Application.java:466)
	at android.app.Activity.dispatchActivityPaused(Activity.java:1347)
	at android.app.Activity.onPause(Activity.java:2283)
	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:388)
	at com.owncloud.android.ui.activity.BaseActivity.onPause(BaseActivity.java:84)
	at com.owncloud.android.ui.activity.FileActivity.onPause(FileActivity.java:253)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onPause(FileDisplayActivity.java:1254)
	at android.app.Activity.performPause(Activity.java:8171)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1508)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4546)
	... 13 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Lenovo
Device: J606F
Model: Lenovo TB-J606F
Id: QKQ1.200730.002
Product: LenovoTB-J606F

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: TB-J606F_USR_S120217_2108052235_Q00287_ROW

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2021-10-01 06:56
Duplicate of #8585

**Closed by AlvaroBrey** 2021-10-01 06:56 UTC
Labels: bug
