### ISSUE TITLE
Feature: save a file to phone / tablet

### ISSUE THREAD

**Issue by Michael-Hennemann** [nextcloud/android#9975] opened 2022-03-16 09:10 UTC
### Is your feature request related to a problem? Please describe.
I'm always frustrated when I want to save a file from Nextcloud to my phone or tablet. 

### Describe the solution you'd like
There should be a feature to browse the loacal file system to save a file to your device
e.g. : open context menu of a file in nextcloud app -> select "save to device..." -> browse local file system and chose folder to save to

### Describe alternatives you've considered
I tried apps like "save to file" from play store that allow to save a file via sent-to function of android. It redirects sent-to to the local file system. It's only a workaround and IMHO it should be a built in function to exchange files between device and nextcloud

### Additional context
There is already a file browser to UPLOAD a file from your device to Nextcloud. IMHO it would just be obvious to use that dialog to DOWNLOAD or save a file to your phone/tablet :-) 

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2022-03-16 09:40
Duplicate of #9519

**Closed by AlvaroBrey** 2022-03-16 09:40 UTC
Labels: enhancement
