### ISSUE TITLE
Android nextcloud crashing repeatedly 

### ISSUE THREAD

**Issue by ABGoldblatt** [nextcloud/android#4985] opened 2019-12-11 14:07 UTC
### Actual behaviour
- Tell us what happens
Nextcloud client randomly crashes while doing background tasks.  I'm doing something else, unrelated, and the crash report interrupts what I'm doing.
### Expected behaviour
- Tell us what should happen
 Nextcloud should do its thing without crashing...
### Steps to reproduce
1. Install nextcloud client
2. Setup sync folders
3. Go about your other business

### Environment data
Android version:
9
Device model: 
Moto G6
Stock or customized system:
Stock
Nextcloud app version:
3.9.2
Nextcloud server version:
Don't know. 
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:798)
Caused by: java.lang.SecurityException: Caller no longer running, last stopped +11s458ms because: timed out while starting
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:195)
	at android.app.job.JobParameters.dequeueWork(JobParameters.java:243)
	at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
	at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobServiceContext.assertCallerLocked(JobServiceContext.java:481)
	at com.android.server.job.JobServiceContext.doDequeueWork(JobServiceContext.java:359)
	at com.android.server.job.JobServiceContext$JobCallback.dequeueWork(JobServiceContext.java:160)
	at android.app.job.IJobCallback$Stub.onTransact(IJobCallback.java:83)
	at android.os.Binder.execTransact(Binder.java:746)


************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: ali
Model: moto g(6)
Id: PPSS29.118-15-11-2
Product: ali

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 76e712

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2019-12-12 07:46
duplicate of #4556

**Closed by AndyScherzinger** 2019-12-12 07:46 UTC
Labels: bug
