### ISSUE TITLE
Deffered loading not working

### ISSUE THREAD

**Issue by fairking** [nextcloud/android#9625] opened 2021-12-27 12:41 UTC
Having 1000+ photos in folder the android app deffered loading is not working as expected. Slow performance.
It looks like it is trying to load all photos at ones, which is very bad coding practice. Please make a better deferred loading like every app has.

### Environment data
Android version: Android 10

Device model: Moto One Macro

Stock or customized system: stock

Nextcloud app version:  3.18.1

Nextcloud server version: 22.2.3

**Comment by AlvaroBrey** [comment] 2022-01-03 16:26
Duplicate of #5926

**Closed by AlvaroBrey** 2022-01-03 16:26 UTC
Labels: bug
