### ISSUE TITLE
Cannot create a new folder in share mode: `ReceiveExternalFilesActivity.onCreateOptionsMenu` `canWrite()`

### ISSUE THREAD

**Issue by TheBoegl** [nextcloud/android#13498] opened 2024-09-02 05:32 UTC
While sharing a file to Nextcloud I tried to create a new folder (after switching to another account and I got the following NPE after entering the name instead of the new folder:
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.canWrite()' on a null object reference
    at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onCreateOptionsMenu(ReceiveExternalFilesActivity.java:1014)
    at android.app.Activity.onCreatePanelMenu(Activity.java:4595)
    at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:520)
    at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3429)
    at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
    at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
    at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
    at android.view.Choreographer.doFrame(Choreographer.java:941)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
    at android.os.Handler.handleCallback(Handler.java:959)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8592)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `lynx`
* Model: `Pixel 7a`
* Id: `AP2A.240805.005`
* Product: `lynx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `12025142`

**Comment by joshtrichards** [comment] 2024-11-01 20:58
Duplicate of #13348

**Closed by joshtrichards** 2024-11-01 20:58 UTC
Labels: bug, feature: sharing to/from other apps, performance: NPE :no_entry_sign:, stable-3.29
