### ISSUE TITLE
Add setting to allow/disallow downloads (down sync) via mobile data?

### ISSUE THREAD

**Issue by kanunnikau** [nextcloud/android#11002] opened 2022-11-07 12:52 UTC
### Is your feature request related to a problem? Please describe.
Yes, oh yes. Lately some users are reporting weird things happening to auto upload. Once the mobile app uploads things to the server it then proceeds to download (sync) all of those things back to the app folder (Android/media/com.nextcloud.client/...). This is discussed in issue #10878 , for example.
I think this bug has come to bite me on the butt as I was using flaky wifi to upload local (mobile) changes. Upload is only allowed on wifi and that probably worked as intended. At some point at night the app finished uploading. Then the app decided to sync it all down (several GBs worth), but the WiFi had given up by then. And as there is no "use only WiFi" setting for down sync it proceeded to eat all of my mobile data and then drained my mobile account (which coincidentally had just been topped up to pay for the upcoming monthly charge). In the morning I had no mobile data + no money on the account to pay for it. I had to use the flaky wifi to fix that so that I could use my mobile on the way home from the trip.

### Describe the solution you'd like
An overall setting for app "Use mobile data/wifi when syncing changes to device?". Maybe for better UX the app could, like Google Play, ask for confirmation on manual sync attempt if there is no wifi connected — "This action might cost you money. Do you want to proceed?".

### Describe alternatives you've considered
I've set Android mobile data limit + "disable mobile data when limit reached" so that there is a smaller chance I'm again greeted in the morning by my phone that's not able to use internet. I'm also thinking whether I should disallow the Nextcloud app to use mobile data altogether, although this will cause some issues as I wouldn't even be able to navigate the folder structure without connecting to wifi or reenabling mobile data access.

### Additional context
Screenshots showing:
- excessive storage usage (I haven't chosen to sync 13.81GB of data to the device),
- excessive background mobile data usage on (the night of) Oct 31st,
- excessive background mobile data usage on (the early morning of) Nov 1st.
![Screenshot_2022-11-07-13-39-50-340_com miui securitycenter](https://user-images.githubusercontent.com/2588408/200313980-317a34bb-0e3a-4d7d-8c5e-ee365ca17736.jpg)
![Screenshot_2022-11-07-13-40-00-029_com miui securitycenter](https://user-images.githubusercontent.com/2588408/200313991-4a604f8c-6714-4b87-b2e7-83d167367043.jpg)
![Screenshot_2022-11-07-13-40-13-938_com miui securitycenter](https://user-images.githubusercontent.com/2588408/200313994-5a7c8aef-4e9f-479a-8f78-d77dbd3ac113.jpg)

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by joshtrichards** [comment] 2023-12-22 23:04
Duplicate of #2417

**Closed by joshtrichards** 2023-12-22 23:04 UTC
Labels: enhancement, feature: auto upload, connectivity, feature: data usage
