### ISSUE TITLE
Crash while browsing through Media: at OperationsServiceBinder.isSynchronizing in getRemotePath()

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/android#10498] opened 2022-07-08 15:33 UTC
Got this error when browsing throw the media tab i opened  up a photo scrolled to a different one and crashed. Im trying to replicate it no luck :( 

### Cause of error

```java

Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String [com.owncloud.android](http://com.owncloud.android/).datamodel.OCFile.getRemotePath()' on a null object reference

    at [com.owncloud.android.services](http://com.owncloud.android.services/).OperationsService$OperationsServiceBinder.isSynchronizing([OperationsService.java:372](http://operationsservice.java:372/))

    at [com.owncloud.android](http://com.owncloud.android/).files.FileMenuFilter.anyFileSynchronizing([FileMenuFilter.java:522](http://filemenufilter.java:522/))

    at [com.owncloud.android](http://com.owncloud.android/).files.FileMenuFilter.anyFileSynchronizing([FileMenuFilter.java:511](http://filemenufilter.java:511/))

    at [com.owncloud.android](http://com.owncloud.android/).files.FileMenuFilter.filter([FileMenuFilter.java:200](http://filemenufilter.java:200/))

    at [com.owncloud.android](http://com.owncloud.android/).files.FileMenuFilter.filter([FileMenuFilter.java:132](http://filemenufilter.java:132/))

    at [com.owncloud.android](http://com.owncloud.android/).ui.preview.PreviewImageFragment.onPrepareOptionsMenu([PreviewImageFragment.java:378](http://previewimagefragment.java:378/))

    at [androidx.fragment.app](http://androidx.fragment.app/).Fragment.performPrepareOptionsMenu([Fragment.java:3144](http://fragment.java:3144/))

    at [androidx.fragment.app](http://androidx.fragment.app/).FragmentManager.dispatchPrepareOptionsMenu([FragmentManager.java:2923](http://fragmentmanager.java:2923/))

    at [androidx.fragment.app](http://androidx.fragment.app/).FragmentController.dispatchPrepareOptionsMenu([FragmentController.java:414](http://fragmentcontroller.java:414/))

    at [androidx.fragment.app](http://androidx.fragment.app/).FragmentActivity.onPreparePanel([FragmentActivity.java:447](http://fragmentactivity.java:447/))

    at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel([WindowCallbackWrapper.java:99](http://windowcallbackwrapper.java:99/))

    at [androidx.appcompat.app](http://androidx.appcompat.app/).AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel([AppCompatDelegateImpl.java:3149](http://appcompatdelegateimpl.java:3149/))

    at [androidx.appcompat.app](http://androidx.appcompat.app/).AppCompatDelegateImpl.preparePanel([AppCompatDelegateImpl.java:1937](http://appcompatdelegateimpl.java:1937/))

    at [androidx.appcompat.app](http://androidx.appcompat.app/).AppCompatDelegateImpl.doInvalidatePanelMenu([AppCompatDelegateImpl.java:2191](http://appcompatdelegateimpl.java:2191/))

    at [androidx.appcompat.app](http://androidx.appcompat.app/).AppCompatDelegateImpl$2.run([AppCompatDelegateImpl.java:273](http://appcompatdelegateimpl.java:273/))

    at android.view.Choreographer$CallbackRecord.run([Choreographer.java:1108](http://choreographer.java:1108/))

    at android.view.Choreographer.doCallbacks([Choreographer.java:866](http://choreographer.java:866/))

    at android.view.Choreographer.doFrame([Choreographer.java:792](http://choreographer.java:792/))

    at android.view.Choreographer$FrameDisplayEventReceiver.run([Choreographer.java:1092](http://choreographer.java:1092/))

    at android.os.Handler.handleCallback([Handler.java:938](http://handler.java:938/))

    at android.os.Handler.dispatchMessage([Handler.java:99](http://handler.java:99/))

    at android.os.Looper.loopOnce([Looper.java:226](http://looper.java:226/))

    at android.os.Looper.loop([Looper.java:313](http://looper.java:313/))

    at [android.app](http://android.app/).ActivityThread.main([ActivityThread.java:8669](http://activitythread.java:8669/))

    at java.lang.reflect.Method.invoke(Native Method)

    at [com.android](http://com.android/).internal.os.RuntimeInit$MethodAndArgsCaller.run([RuntimeInit.java:571](http://runtimeinit.java:571/))

    at [com.android](http://com.android/).internal.os.ZygoteInit.main([ZygoteInit.java:1135](http://zygoteinit.java:1135/))

```

### App information

* ID: com.nextcloud.client

* Version: 30200390

* Build flavor: gplay

### Device information

* Brand: samsung

* Device: t2q

* Model: SM-G996U1

* Id: SP1A.210812.016

* Product: t2quew

### Firmware

* SDK: 31

* Release: 12

* Incremental: G996U1UEU5CVF1

**Comment by joshtrichards** [comment] 2023-12-11 14:32
Duplicate of #9860

**Closed by joshtrichards** 2023-12-11 14:32 UTC
Labels: bug, approved, feature: media tab
