### ISSUE TITLE
Generating thousands of conflict notifications each day

### ISSUE THREAD

**Issue by vKnmnn** [nextcloud/android#8591] opened 2021-06-16 09:40 UTC
### Steps to reproduce

- have conflicting files

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- there probably is an underlying issue for this. the second stage problem  started around one month ago. with v 3.16.0.
- the underlying issue is the inability to display the conflict dialogues for files, so i cannot chose what to do about my file conflicts. probably MiUI or dark system theme related?
- starting with v3.16.0, the app started showing me a notification for conflicted files every few seconds, ranging from 1000 to 9000 per day for this app alone. 

### Environment data
Android version: 10

Device model: Xiaomi Mi9

Stock or customized system:

Nextcloud app version: 3.16.0

Nextcloud server version: 20.0.8

Reverse proxy: nginx

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2021-06-17 08:33
>     * the underlying issue is the inability to display the conflict dialogues for files

What does happen there?

Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by vKnmnn** [comment] 2021-06-18 10:13
i think it’s the same stuff happening as in #7000 .
sadly (or less so) i resolved my conflicts now, so i'm not able to provide a logcat.

**Comment by ffflorian** [comment] 2021-07-28 16:45
I am experiencing the same problem. Clicking on the notification opens the nextCloud app but not the duplicate file dialog.

![Screenshot](https://user-images.githubusercontent.com/5497598/127362855-091ca2b5-b11b-4025-8a7c-8974b44d7fea.jpg)

**Comment by ffflorian** [comment] 2021-09-09 15:43
This issue is not fixed. Please reopen.

**Comment by bllngr** [comment] 2022-06-08 05:14
I keep having the same issue on (at least) 3.20. I noticed that if I try to open one of the notifications, a toast message "Error creating conflict dialog" appears.

@tobiasKaminsky, since the issue has been confirmed by multiple people, could you tell the bot to not close it? I will try to get a logcat log the next time it appears. But I suspect it might have something to do with the server not being accessible due to network issues or so.

**Comment by tobiasKaminsky** [comment] 2022-06-13 13:10
Working steps to reproduce are really needed here.
🤞🤞🤞 that you can narrow them down

**Comment by bllngr** [comment] 2022-07-08 10:09
@tobiasKaminsky, I don't know whether it's reproducible everywhere, but for me it always happens in this scenario:

1. Make sure auto upload is enabled for photos and screenshots
2. Take a photo or screenshot
3. Immediately edit the photo/screenshot (crop it, apply filters or so). On my device, I can do that from the notification.
4. Save the edited picture.
5. Observe a conflict notification being generated, and a second, third, fourth ... around every three to six minutes.

**Comment by bllngr** [comment] 2022-08-23 06:46
@tobiasKaminsky have you been able to narrow it down? The NC is is still generating masses of notifications everytime I edit a freshly taken picture or screenshot. Is there anything else you need?

**Comment by tobiasKaminsky** [comment] 2022-08-23 07:02
Can you show us your auto upload settings? I assume that you do not have "overwrite" enabled as conflict resolution?

**Comment by bllngr** [comment] 2022-08-23 07:21
Yes, "Ask me every time" is selected for conflict resolution.


![Screenshot_20220823-091225_Nextcloud](https://user-images.githubusercontent.com/303458/186096313-026be953-8882-4001-86ad-0407abe8335b.png)

**Comment by joshtrichards** [comment] 2024-11-09 20:33
There have been different reports with similar, but different root causes over time. In addition, in terms of the Android app, a lot of code has changed in these areas since these reports. This issue hasn't seen traffic for a couple years. If you're experiencing anything resembling this today, please create a dedicated Issue with your individual details. Thanks.

**Closed by joshtrichards** 2024-11-09 20:33 UTC
Labels: bug, feature: auto upload, hotspot: sync conflicts, hotspot: uploads tab and transfer notifications

**Comment by aeksto** [comment] 2025-02-15 12:05
Please reopen the issue. 

I have experienced it on the following devices:

Pixel 4a CalyxOS 5.14.x
Pixel 6a CalyxOS 6.4.0

This issue persisted across different versions of the app:

Nextcloud F-Droid (3.30.x)
Nextcloud Playstore (3.30.x)
Nextcloud Dev F-Droid (3.30.x)

So, maybe there is a problem with CalyxOS?

**Comment by joshtrichards** [comment] 2025-02-15 15:28
@aeksto As I stated:

>  If you're experiencing anything resembling this today, please create a dedicated Issue with your individual details. Thanks.
