### ISSUE TITLE
I deleted a photo in my Nextcloud. Nextcloud app crashed. 100% replicable.

### ISSUE THREAD

**Issue by yuukiAme** [nextcloud/android#10699] opened 2022-09-01 19:25 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Go into my Nextcloud dashboard.
2. Select a photo/file to delete on Android app.
3. Preview the photo.
4. Select "..." then Delete.
5. Confirm the deletion with "Delete".
6. Report prompt pop-up immediately.

### Expected behaviour

Deleting a photo in NextCloud does NOT crash the app.

### Actual behaviour

Deleting a photo in NextCloud **Crashed** the app immediately.

### Android version

12

### Device brand and model

SM-X806B

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.1

### Nextcloud server version

24.0.4

### Using a reverse proxy?

I don't know

### Additional information

I checked the whole storage on the Android device. I could not find the `nextcloud.log` anywhere

**Comment by AlvaroBrey** [comment] 2022-09-02 07:38
Duplicate of #10580

**Closed by AlvaroBrey** 2022-09-02 07:38 UTC
Labels: bug
