### ISSUE TITLE
No sync / very long sync delay

### ISSUE THREAD

**Issue by zweimalJack** [nextcloud/android#7853] opened 2021-01-16 15:04 UTC
Hey there, 
I just finished installing Nextcloud on my Raspberry Pi4, fileshare with my windows pc is excellent, but does not really work with my android devices.
Config:
Raspi 4, 4gb ram with nextcloud v.1.29.8
Samsung S7, nc app v.3.14.3
Samsung Galaxy Tab A, nc v.3.14.1

With different filetypes and -sizes,
Samsung S7 needs 2-3 hours for small 10 mb pdf or jpg or does not sync either,
Samsung Tab A needs 10-15 min or does also not sync.
Only windows 《》raspi does well.

- Maybe to many different nc version?
- How can i create a logfile / bugreport on my devices to gather more information?

Best regards

**Comment by gersoid** [comment] 2021-01-17 17:32
I see same issue. Brand new 3.15rc1 client Vs 20.5 server, running on android 11 / Pixel 3a. Photo / video upload has stopped since client update. Windows client update looks fine

**Comment by tobiasKaminsky** [comment] 2021-02-24 13:30
Do you see any info / delay in nextcloud.log on server?

**Comment by gersoid** [comment] 2021-02-24 13:57
Hi Tobias, issue fixed at my end (server firewall settings). Status of my item will be amended

**Comment by tobiasKaminsky** [comment] 2021-02-25 06:48
Can you share the root cause of it? And how you fixed it? 
(meanwhile I already close the issue)

**Closed by tobiasKaminsky** 2021-02-25 06:48 UTC
Labels: bug, needs info/discussion
