### ISSUE TITLE
App 3.14.1 does not upload via the "Share to" option anymore

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#7700] opened 2020-12-20 14:50 UTC
### Steps to reproduce
1. Open a file in any app
2. Select "Share to" from the menu
3. Select the Nextcloud app

### Expected behaviour
- File upload starts

### Actual behaviour
- File upload doesn't start

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

Yes

### Environment data
Android version: tested on 7.0 and 10.0

Device model: 
Redni Note 7 and Huawei MediaPad
Stock or customized system:

Nextcloud app version:
3.14.1
Nextcloud server version:
20.0.4
Reverse proxy:

#### Web server error log
```
[20/Dec/2020:15:49:04 +0100] "GET /apps/logreader/poll?lastReqId=p90mm3UornJUXAEyhgUG HTTP/1.1" 200 1649 "-" "Mozilla/5.0 (Linux; Android 7.0; AGS-W09) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36"                                                                           
```

#### Nextcloud log (data/nextcloud.log)
```
Deprecated event type for {"[object] (OCP\SabrePluginEvent)":{"*statusCode":200,"*message":"","*server":{"[object] (OCA\DAV\Connector\Sabre\Server)":{"tree":"[object] (OCA\DAV\Connector\Sabre\ObjectTree)","*baseUri":"/remote.php/webdav/","httpResponse":"[object] (Sabre\HTTP\Response)","httpRequest":"[object] (Sabre\HTTP\Request)","sapi":"[object] (Sabre\HTTP\Sapi)","*plugins":[],"transactionType":null,"protectedProperties":{"...":"Over 20 items, aborting normalization"},"debugExceptions":false,"resourceTypeMapping":[],"enablePropfindDepthInfinity":true,"xml":"[object] (Sabre\DAV\Xml\Service)","*listeners":{"...":"Over 20 items, aborting normalization"},"*wildcardListeners":[],"*listenerIndex":[],"*logger":null}},"Symfony\Contracts\EventDispatcher\EventpropagationStopped":false}}: null
```

**Comment by AndyScherzinger** [comment] 2020-12-20 22:16
Duplicate of #7587

**Closed by AndyScherzinger** 2020-12-20 22:16 UTC
Labels: bug
