### ISSUE TITLE
3.0RC1: Favorites and Photos loading for ever

### ISSUE THREAD

**Issue by steve-s-71** [nextcloud/android#1972] opened 2018-01-16 17:09 UTC
When selecting menu point "Favorites" or "Photos", the app shows "loading" and the "sandbox" circle does not stop spinning.  No content is shown.

**Comment by xXSTrikeXx** [comment] 2018-01-18 03:36
Have the same when clicking in the menu on photos.

**Comment by tobiasKaminsky** [comment] 2018-01-18 08:10
This is a known problem, if there are too many items.
For 5k images:
- fetch from server ~30s (as the server has to gather all information on each image/file)
- displaying ~2min as we still use the old ListView which is not really capable of handling such an amount.

We are working on it, but as this is not a regression of RC and needs a lot of changes, it will be not in 3.0.

**Comment by steve-s-71** [comment] 2018-01-18 08:17
@tobiasKaminsky I buy in you explanation in regards of photos - I have a lot there. But the same issue happens to the Favorites item - although I have only one (for testing).

**Comment by tobiasKaminsky** [comment] 2018-01-18 11:16
If you have only one favorite this is indeed strange.
How long did you wait?

Can you create us a test account and test if it happens also there and send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by xXSTrikeXx** [comment] 2018-01-18 11:59
I waited 5 mins for photos, but favorites are still Loading correctly.

**Comment by steve-s-71** [comment] 2018-01-20 23:02
Hi @tobiasKaminsky 

> How long did you wait? 
Approx. 10 Minutes.

> can you create us a test account 
I have done that. Under the test account I can immediately see the Photos that are stored by default and also the 2 Test Favorites. 

Is it possible that the issue depends on the total number of files stored under an account, rather than on the number of files that are marked as Favorite? Under my productive Account I have ~30000 files.

**Comment by tobiasKaminsky** [comment] 2018-01-22 09:41
> Is it possible that the issue depends on the total number of files stored under an account, rather than on the number of files that are marked as Favorite? Under my productive Account I have ~30000 files.

As you are our search expert, @icewind1991, can this make a difference?

**Comment by icewind1991** [comment] 2018-01-22 16:59
Does the same slowdown occur in the web interface, and if so please open an issue for this in the server repo

**Comment by steve-s-71** [comment] 2018-01-24 19:26
No @icewind1991, in the the web interface it works seamlessly

**Comment by tobiasKaminsky** [comment] 2018-02-13 11:06
We are currently working on a fix, which then will be in 3.1

**Comment by tobiasKaminsky** [comment] 2018-03-15 06:52
This requires some modification on server side, which will be in NC14, so we have to wait for them.

**Comment by asonix** [comment] 2019-07-05 15:16
Has there been any update on this? I feel like making individual queries for all potential photos on a nextcloud instance is probably the _wrong_ way to go about this. I have many gigabytes of photos on my server running on low-power hardware. There's no way the photos section of the app will ever work for me with the current implementation.

In contrast, the web photos app works fine (with some lag), since it doesn't query _every_ photo on the server, just photos in the current folder.

**Comment by tobiasKaminsky** [comment] 2019-07-18 08:13
There is now a PR ready to test (currently for photos only):
https://github.com/nextcloud/android/pull/2250#issuecomment-512712749

**Comment by tobiasKaminsky** [comment] 2019-07-23 07:41
To centralize this please report anything found in #2250.

**Closed by tobiasKaminsky** 2019-07-23 07:41 UTC
Labels: approved, bug, pr exists
