### ISSUE TITLE
Crash when creating a text file

### ISSUE THREAD

**Issue by Toover** [nextcloud/android#9282] opened 2021-11-16 15:34 UTC
### Steps to reproduce
1. Create text file

### Expected behaviour
- The file is created.

### Actual behaviour
- The file is not created and the application crashes.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

App error:
************ CAUSE OF ERROR ************

java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1330)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:676)
	at android.text.Selection.setSelection(Selection.java:94)
	at android.text.Selection.setSelection(Selection.java:78)
	at android.text.Selection.setSelection(Selection.java:153)
	at android.widget.EditText.setSelection(EditText.java:136)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.prefillFilenameIfEmpty(ChooseTemplateDialogFragment.java:252)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.onTemplateChosen(ChooseTemplateDialogFragment.java:243)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.access$200(ChooseTemplateDialogFragment.java:81)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$FetchTemplateTask.onPostExecute(ChooseTemplateDialogFragment.java:421)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$FetchTemplateTask.onPostExecute(ChooseTemplateDialogFragment.java:373)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180055
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Fairphone
Device: FP3
Model: FP3
Id: QQ3A.200805.001
Product: FP3

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: eng.root.20211027.011913

**Comment by Toover** [comment] 2021-11-16 17:28
Same as https://github.com/nextcloud/android/issues/9277

**Comment by AlvaroBrey** [comment] 2022-06-16 10:16
Duplicate of #9277

**Closed** 2022-06-16 10:17 UTC
Labels: bug
