### ISSUE TITLE
Crash at Autoupload

### ISSUE THREAD

**Issue by benginoe** [nextcloud/android#10166] opened 2022-05-04 15:38 UTC
### Steps to reproduce
1. Select multiple folders for Autoupload
### Expected Behaviour
Upload of pictures (around 70gb) 

### Actual Behaviour
Continuously becoming error that the app doesn't react.

Error Message: 
### Cause of error
```java
Exception in thread "main" android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f649d72 u0 com.nextcloud.client/com.owncloud.android.files.services.FileUploader}
    at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:1965)
    at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1936)
    at android.app.ActivityThread.access$2700(ActivityThread.java:256)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2190)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: Exception in thread "main" android.app.StackTrace: Last startServiceCommon() call for this service was made here
    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1876)
    at android.app.ContextImpl.startForegroundService(ContextImpl.java:1831)
    at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:779)
    at com.owncloud.android.files.services.FileUploader.retryUpload(FileUploader.java:1060)
    at com.owncloud.android.files.services.FileUploader.retryFailedUploads(FileUploader.java:1103)
    at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:240)
    at com.owncloud.android.utils.FilesSyncHelper$$ExternalSyntheticLambda0.run(Unknown Source:10)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200090`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `redfin`
* Model: `Pixel 5`
* Id: XXX
* Product: `redfin`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `8210211`

**Comment by orithena** [comment] 2022-06-12 09:17
Can confirm on Huawei P10 with nextcloud app from F-Droid.

Problem feels like it's related to UI threading (or a lack thereof?). It comes up when autouploading lots of images (jpg and dng). The UI then feels sluggish, but bearable. It becomes exponentially worse when checking the upload queue. It feels like it is the thumbnail generation that blocks the UI thread then.

**Comment by AlvaroBrey** [comment] 2022-07-01 07:57
Duplicate of #9617

**Closed by AlvaroBrey** 2022-07-01 07:57 UTC
Labels: bug, feature:AutoUpload

**Comment by benginoe** [comment] 2022-07-01 08:22
May I ask what not planned means as it is a severe bug which makes the app unusable for every circumstance?

**Comment by AlvaroBrey** [comment] 2022-07-01 08:29
> May I ask what not planned means as it is a severe bug which makes the app unusable for every circumstance?

means that it's a duplicate of #9617, which is still open
