### ISSUE TITLE
Refreshed media page and crashed app

### ISSUE THREAD

**Issue by cakonopka** [nextcloud/android#10736] opened 2022-09-14 19:22 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Open app
Go to media page
Pull down to refresh 

### Expected behaviour

Media to refresh and thumbnails to update

### Actual behaviour

Crashed app and no thumbnails 

### Android version

12

### Device brand and model

Oneplus9Pro 

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.2

### Nextcloud server version

24.0.2

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Couldn't read row 729, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetString(Native Method)
    at android.database.CursorWindow.getString(CursorWindow.java:462)
    at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:54)
    at android.database.CursorWrapper.getString(CursorWrapper.java:141)
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:967)
    at com.owncloud.android.datamodel.FileDataStorageManager.getGalleryItems(FileDataStorageManager.java:2234)
    at com.owncloud.android.datamodel.FileDataStorageManager.getAllGalleryItems(FileDataStorageManager.java:2179)
    at com.owncloud.android.ui.preview.PreviewImagePagerAdapter.<init>(PreviewImagePagerAdapter.java:124)
    at com.owncloud.android.ui.preview.PreviewImageActivity.initViewPager(PreviewImageActivity.java:148)
    at com.owncloud.android.ui.preview.PreviewImageActivity.onStart(PreviewImageActivity.java:208)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1470)
    at android.app.Activity.performStart(Activity.java:8154)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3803)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:233)
    at android.os.Looper.loop(Looper.java:344)
    at android.app.ActivityThread.main(ActivityThread.java:8210)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210290`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus9Pro`
* Model: `LE2123`
* Id: `RKQ1.211119.001`
* Product: `OnePlus9Pro_EEA`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `R.GDPR.202206251226`

**Comment by AlvaroBrey** [comment] 2022-09-15 07:36
Duplicate of #9948

**Closed by AlvaroBrey** 2022-09-15 07:36 UTC
Labels: bug
