### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by WastelandWanderer** [nextcloud/android#14094] opened 2024-11-27 05:04 UTC
### Cause of error
```java
Exception in thread "Syncfolder thread" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getEtag()' on a null object reference
    at com.owncloud.android.operations.SynchronizeFolderOperation.checkForChanges(SynchronizeFolderOperation.java:172)
    at com.owncloud.android.operations.SynchronizeFolderOperation.run(SynchronizeFolderOperation.java:131)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
    at com.owncloud.android.services.SyncFolderHandler.doOperation(SyncFolderHandler.java:106)
    at com.owncloud.android.services.SyncFolderHandler.handleMessage(SyncFolderHandler.java:79)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.os.HandlerThread.run(HandlerThread.java:67)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300590`
* Build flavor: `generic`

### Device information
* Brand: `Fairphone`
* Device: `FP5`
* Model: `FP5`
* Id: `UKQ1.230924.001`
* Product: `FP5`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `UT2E`

**Comment by joshtrichards** [comment] 2024-12-28 15:13
Duplicate of  #13784

**Closed by joshtrichards** 2024-12-28 15:13 UTC
