### ISSUE TITLE
Specify calendar and contacts backup directory

### ISSUE THREAD

**Issue by Emporea** [nextcloud/android#11025] opened 2022-11-12 09:30 UTC
It could be useful to specify the default directory for the auto Backup of Calendar and Contacts.

**Comment by joshtrichards** [comment] 2023-10-19 16:55
Duplicate of #4132 

Let's consolidate tracking this enhancement there. Feel free to subscribe and/or upvote that issue. Thanks for your note!

**Closed by joshtrichards** 2023-10-19 16:55 UTC
Labels: enhancement, feature: contacts and calendar backup
