### ISSUE TITLE
Video playback controls not functioning in 3.13 

### ISSUE THREAD

**Issue by seanthegeek** [nextcloud/android#6796] opened 2020-08-24 15:09 UTC
### Steps to reproduce
1. Start streaming a video (e.g. .mp4 file
2.  Attempt to use the playback control buttons

### Expected behaviour
- Playback controls should function
- Seek bar should appear
- Changing rotation or switching apps should not break the UI or return to the start of the video

### Actual behaviour
- Pause/rewind/fast-forward buttons and the video itself do not respond to taps
- Seek bar is missing
- Changing rotation or switching apps causes file browser UI elements to appear on top of the video UI, and also causes the video to seek to the start

### Can you reproduce this problem on https://try.nextcloud.com?
Not a server issue

### Environment data
Android version: 10

Device model: Pixel 3 XL

Stock or customized system: Stock

Nextcloud app version: 3.13

Nextcloud server version: Snap

Reverse proxy: Nginx

**Comment by ezaquarii** [comment] 2020-08-24 20:48
This seems to be duplicate of #6796

**Closed** 2020-08-25 06:12 UTC
Labels: bug

**Comment by agilob** [comment] 2020-09-01 07:30
@ezaquarii this is #6796 :D
