### ISSUE TITLE
android error

### ISSUE THREAD

**Issue by tkintenn** [nextcloud/android#5808] opened 2020-04-05 13:41 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
	at android.widget.Toast$TN.<init>(Toast.java:393)
	at android.widget.Toast.<init>(Toast.java:117)
	at android.widget.Toast.makeText(Toast.java:280)
	at android.widget.Toast.makeText(Toast.java:270)
	at android.widget.Toast.makeText(Toast.java:307)
	at com.owncloud.android.ui.activity.ConflictsResolveActivity.showErrorAndFinish(ConflictsResolveActivity.java:229)
	at com.owncloud.android.ui.activity.ConflictsResolveActivity.lambda$onStart$0$ConflictsResolveActivity(ConflictsResolveActivity.java:192)
	at com.owncloud.android.ui.activity.-$$Lambda$ConflictsResolveActivity$EM0Z1Vrhvmim7X4XXFnNqL4vK1A.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: KYOCERA
Device: E6910
Model: E6910
Id: 4.101VZ.0132.a
Product: VZW_E6910

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 4.101VZ.0132.a

**Comment by AndyScherzinger** [comment] 2020-04-05 15:22
Duplicate of #5758

**Closed by AndyScherzinger** 2020-04-05 15:22 UTC
Labels: bug
