### ISSUE TITLE
autoupload does not work since app update

### ISSUE THREAD

**Issue by tla-wedel** [nextcloud/android#10402] opened 2022-06-16 11:35 UTC
### Steps to reproduce
1. Android 12
2. Server 23.0.4
3. App 3.20.3

### Expected behaviour
- Camera Pics should be uploaded as before this app version

### Actual behaviour
- since june 13 (app update) the upload did not work anymore.

### Environment data
Android version: 12

Device model: Samsung Galaxy S20 plus

Stock or customized system: stock

Nextcloud app version: 3.20.3

Nextcloud server version: 23.0.4

Reverse proxy: traefik 2.7.1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2022-06-16 12:09
Duplicate of #10200

**Closed by AlvaroBrey** 2022-06-16 12:09 UTC
Labels: bug
