### ISSUE TITLE
Can't upload file

### ISSUE THREAD

**Issue by GreenMystic** [nextcloud/android#13252] opened 2024-07-09 03:17 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. open nextcloud (already logged in)
2. upload a file
3. error ( it's either will stuck in loading or immediately show error msg)

### Expected behaviour

it should work properly 

### Actual behaviour

error / stuck

### Android version

R(11)

### Device brand and model

Realme C21Y 

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.1

### Nextcloud server version

N/A

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to start receiver com.owncloud.android.files.services.FileUploader$UploadNotificationActionReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.files.services.FileUploader$FileUploaderBinder.cancel(java.lang.String, java.lang.String, com.owncloud.android.lib.common.operations.RemoteOperationResult$ResultCode)' on a null object reference
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:4126)
    at android.app.ActivityThread.access$1400(ActivityThread.java:260)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1966)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7950)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.files.services.FileUploader$FileUploaderBinder.cancel(java.lang.String, java.lang.String, com.owncloud.android.lib.common.operations.RemoteOperationResult$ResultCode)' on a null object reference
    at com.owncloud.android.files.services.FileUploader$UploadNotificationActionReceiver.onReceive(FileUploader.java:1401)
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:4114)
    at android.app.ActivityThread.access$1400(ActivityThread.java:260)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1966)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7950)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30280290`
* Build flavor: `generic`

### Device information
* Brand: `realme`
* Device: `RED8D1`
* Model: `RMX3263`
* Id: `RP1A.201005.001`
* Product: `RMX3263`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `1696918788000`

**Comment by joshtrichards** [comment] 2024-07-09 13:49
Duplicate of #12356

**Closed by joshtrichards** 2024-07-09 13:49 UTC
Labels: bug, performance: NPE :no_entry_sign:, Version/3028
