### ISSUE TITLE
app crashed

### ISSUE THREAD

**Issue by datongworld** [nextcloud/android#4525] opened 2019-09-19 09:31 UTC
### Actual behaviour
- Open Nextcloud app, Click login button crash

### Expected behaviour
- Be able to use the app without it crashing
 
### Steps to reproduce
1. Install Nextcloud dev app (2019-09-14)
2. Login
3. Crash

### Environment data
Android version:7.1.2

Device model: 

Stock or customized system:

Nextcloud app version: dev 2019-09-14

Nextcloud server version: 16

### Android App Crash Logs

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
	at android.widget.Editor.updateCursorPositionMz(Editor.java:7836)
	at android.widget.Editor.updateCursorsPositions(Editor.java:1963)
	at android.widget.TextView.getUpdatedHighlightPath(TextView.java:5783)
	at android.widget.TextView.onDraw(TextView.java:5969)
	at com.owncloud.android.ui.components.CustomEditText.onDraw(CustomEditText.java:71)
	at android.view.View.draw(View.java:17305)
	at android.view.View.updateDisplayListIfDirty(View.java:16282)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16277)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.draw(View.java:17308)
	at com.google.android.material.textfield.TextInputLayout.draw(TextInputLayout.java:1577)
	at android.view.View.updateDisplayListIfDirty(View.java:16282)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16277)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16277)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16277)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.draw(View.java:17308)
	at android.widget.ScrollView.draw(ScrollView.java:1743)
	at android.view.View.updateDisplayListIfDirty(View.java:16282)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16277)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16277)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16277)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16277)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.draw(View.java:17308)
	at com.android.internal.policy.DecorView.draw(DecorView.java:786)
	at android.view.View.updateDisplayListIfDirty(View.java:16282)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:661)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:667)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:775)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2837)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2639)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2241)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1276)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6483)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:888)
	at android.view.Choreographer.doCallbacks(Choreographer.java:700)
	at android.view.Choreographer.doFrame(Choreographer.java:635)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:874)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6381)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:829)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20190914
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Meizu
Device: M6Note
Model: M6 Note
Id: N2G47H
Product: meizu_M6Note_CN

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: m1721.Flyme_7.0.1555922707

**Comment by msecilmis** [comment] 2019-09-19 12:54
I can take this

**Comment by tobiasKaminsky** [comment] 2019-09-19 14:16
@msecilmis if you in idea, feel free :-) Any help is highly appreciated :+1: 
Sadly, from the stack trace I can only see Android related classes.

**Comment by msecilmis** [comment] 2019-09-19 14:48
this seems like a device specific problem and i do have some idea, although have no idea how to test the solution since i don't have that device, please assign it to me and maybe i can coordinate with @datongworld and test

**Comment by tobiasKaminsky** [comment] 2019-10-08 13:31
Duplicate of #4619

**Closed by tobiasKaminsky** 2019-10-08 13:31 UTC
Labels: bug
