### ISSUE TITLE
Android client crash on no longer accessible folder

### ISSUE THREAD

**Issue by garloff** [nextcloud/android#7908] opened 2021-01-30 05:16 UTC
### Steps to reproduce
1. Directory on Nextcloud Server is no longer accessible 
2. Android client thinks it's still there and display the folder 
3. Updating leads to the crash

### Expected behaviour
- Upon update, the folder should disappear 

### Actual behaviour
- Lovely backtrace

### Can you reproduce this problem on https://try.nextcloud.com?
- No

### Environment data
Android version: 10

Device model: Huawei LYA-29 (Mate20Pro) 

Stock or customized system: Stock 

Nextcloud app version: 3.14.3

Nextcloud server version: 20.0.5

Reverse proxy: Nope

### Logs

************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=2803, totalRows=1864
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:986)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:858)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:161)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:131)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:249)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:281)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:190)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:332)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:309)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2147)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:387)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:532)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:520)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1894)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:438)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:519)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:401)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:237)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:929)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140390
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWLYA
Model: LYA-L29
Id: HUAWEILYA-L29
Product: LYA-L29

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.1.0.289C432

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2021-02-23 07:29
Duplicate of #6688

**Closed by tobiasKaminsky** 2021-02-23 07:29 UTC
Labels: bug
