### ISSUE TITLE
Crash when changing theme color

### ISSUE THREAD

**Issue by jeanbruder** [nextcloud/android#8964] opened 2021-09-10 10:11 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to pause activity {com.nextcloud.client/com.owncloud.android.ui.activity.NotificationsActivity}: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@78c1e28
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3900)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2834)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4693)
	at android.app.ActivityThread.-wrap19(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1559)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@78c1e28
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1012)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1402)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:608)
	at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.onInactive(UsbConnectionDispatcher.java:131)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.ensureStateInactive(SecurityKeyManager.java:316)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.refreshActiveState(SecurityKeyManager.java:290)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.onActivityPaused(SecurityKeyManager.java:333)
	at android.app.Application.dispatchActivityPaused(Application.java:225)
	at android.app.Activity.onPause(Activity.java:1607)
	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:388)
	at com.owncloud.android.ui.activity.BaseActivity.onPause(BaseActivity.java:84)
	at android.app.Activity.performPause(Activity.java:6879)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1322)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3882)
	... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Blackview
Device: P6000
Model: P6000
Id: N4F26M
Product: P6000

************ FIRMWARE ************
SDK: 25
Release: 7.1.1
Incremental: 1515044724

**Comment by AndyScherzinger** [comment] 2021-09-10 13:13
Duplicate of #8585

**Closed by AndyScherzinger** 2021-09-10 13:13 UTC
Labels: bug
