### ISSUE TITLE
Crash directed me here

### ISSUE THREAD

**Issue by Scoth42** [nextcloud/android#6188] opened 2020-06-02 03:04 UTC
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/data/app/com.nextcloud.client-iauv6RvzHOhi8iFa4HFz0A==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-iauv6RvzHOhi8iFa4HFz0A==/lib/arm64, /data/app/com.nextcloud.client-iauv6RvzHOhi8iFa4HFz0A==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: joan
Model: LG-US998
Id: OPR1.170623.026
Product: joan_nao_us

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 190771042d27a

**Comment by AndyScherzinger** [comment] 2020-06-02 06:25
Thanks for taking the time to report the crash, this is highly appreciated ❤️

**Comment by AndyScherzinger** [comment] 2020-06-02 06:25
Duplicate of #4675

**Closed by AndyScherzinger** 2020-06-02 06:25 UTC
