### ISSUE TITLE
Error while playing media

### ISSUE THREAD

**Issue by pronoymukherjeewritescode** [nextcloud/android#8883] opened 2021-08-22 07:36 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{8c33c0a u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2240)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8538)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

************ APP INFORMATION ************

ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************

Brand: samsung
Device: gta3xlwifi
Model: SM-T510
Id: RP1A.200720.012
Product: gta3xlwifixx

************ FIRMWARE ************

SDK: 30
Release: 11
Incremental: T510XXU5CUF4

**Comment by shreelakshmijoshi** [comment] 2021-08-23 01:53
Hi @pronoymukherjeewritescode !
I am a new open source contributor and would like to solve this issue, could you help me understand the issue better by providing some extra references ? 
Is this is issue open to contribute ?

**Comment by pronoymukherjeewritescode** [comment] 2021-08-23 16:27
I was playing a video and then the error showed up

**Comment by tobiasKaminsky** [comment] 2021-08-30 06:17
Can you tell us more about this video?
Was it on disk (already downloaded) or streaming?

**Comment by AlvaroBrey** [comment] 2021-09-14 07:28
Duplicate of #8686

**Closed by AlvaroBrey** 2021-09-14 07:28 UTC
Labels: bug, needs info/discussion
