### ISSUE TITLE
Crash when syncing with ~40gb music folder

### ISSUE THREAD

**Issue by Sheepyhead** [nextcloud/android#5334] opened 2020-01-27 21:17 UTC
Seems to happen when trying to sync any folder of more than a gb or so

### Steps to reproduce
1. Have a folder with 10+GB of files on your nextcloud server
2. Open your android app that is paired with your nextcloud server
3. Press the three dots next to the folder from step 1. and press "sync"
4. The window with "this app has stopped responding" keeps popping up even if you press "wait"

### Expected behaviour
- I would expect nextcloud to sync the local folder with the remote one and keep both folders in sync after the initial download

### Actual behaviour
- The aforementioned "this app has stopped responding" pops up. If I don't press "wait" within a few seconds, the entire app closes. If I press "wait" enough times it seems to eventually start downloading something but will still pop up with that dialog and if I don't press "wait" it'll crash mid-download

### Environment data
Android version: OxygenOS 9.0.9

Device model: 
Brand: OnePlus
Device: OnePlus6
Model: ONEPLUS A6003
Id: PKQ1.180716.001
Product: OnePlus6

Stock or customized system: Stock

Nextcloud app version:
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

Nextcloud server version:
17.0.2.1 running on NextcloudPi v1.20.1 on an RPI3

#### Stack trace
```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{9343191 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1845)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6898)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
#### Nextcloud log (data/nextcloud.log)
[nextcloud.log](https://github.com/nextcloud/android/files/4119384/nextcloud.log)

**Comment by Sheepyhead** [comment] 2020-02-25 12:34
Nothing has changed, this issue is still an issue, and I'm unsure what more I could provide in terms of details. This is severely harming how useful the nextcloud app is to me.

**Comment by thgoebel** [comment] 2020-03-05 09:11
Duplicate of #2010 ?

**Comment by Sheepyhead** [comment] 2020-03-05 09:15
> 
> 
> Duplicate of #2010 ?

Seems so

**Comment by tobiasKaminsky** [comment] 2020-03-23 05:19
Yes, duplicate.

**Closed by tobiasKaminsky** 2020-03-23 05:19 UTC
Labels: bug
