### ISSUE TITLE
unresponsive 

### ISSUE THREAD

**Issue by HiPro-Solutions** [nextcloud/android#10452] opened 2022-06-29 10:55 UTC
### Cause of error
```java
Exception in thread "main" android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{c26d47 u0 com.nextcloud.client/com.owncloud.android.files.services.FileUploader}
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2006)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7701)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:610)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `Cat`
* Device: `S62Pro`
* Model: `S62 Pro`
* Id: `RKQ1.210406.002`
* Product: `S62Pro`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `1.018.00`

**Comment by AlvaroBrey** [comment] 2022-07-01 07:57
Duplicate of #9617

**Closed by AlvaroBrey** 2022-07-01 07:57 UTC
Labels: bug
