### ISSUE TITLE
App crashes instantly after opening

### ISSUE THREAD

**Issue by rschulzeLE** [nextcloud/android#8842] opened 2021-08-10 23:12 UTC
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: caymanslm
Model: LM-G910
Id: QKQ1.200412.002
Product: caymanslm_e

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 8450100210501.COM1_EU

**Comment by Entepotenz** [comment] 2021-08-11 07:09
I have the same crash:

```
************ CAUSE OF ERROR ************
 
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:919)
 
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay
 
************ DEVICE INFORMATION ************
Brand: samsung
Device: starlte
Model: SM-G960F
Id: QP1A.190711.020
Product: starltexx
 
************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G960FXXUFFUE1
```

**Comment by AndyScherzinger** [comment] 2021-08-11 21:36
Duplicate of #8370

**Closed by AndyScherzinger** 2021-08-11 21:36 UTC
