### ISSUE TITLE
Creating folder from auto upload folder selection causes crash

### ISSUE THREAD

**Issue by Klim314** [nextcloud/android#5183] opened 2020-01-14 05:12 UTC
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.ui.dialog.CreateFolderDialogFragment.onClick(CreateFolderDialogFragment.java:139)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7037)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond1
Model: SM-G973F
Id: PPR1.180610.011
Product: beyond1ltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G973FXXS3ASJG

Samsung s10

**Comment by AndyScherzinger** [comment] 2020-01-14 10:42
duplicate of #4792

@Klim314 where do you create the folder? in the root directory or a sub-directory of the user?

**Closed by AndyScherzinger** 2020-01-14 10:42 UTC
Labels: bug
