### ISSUE TITLE
App 3.14.0RC1 crashes at try to delete files

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/android#7257] opened 2020-11-08 14:38 UTC
Hi,
if I try to delete files in App, I get an full crash of the app.

```
\*\*\*\*\*\*\*\*\*\* **CAUSE OF ERROR** \*\*\*\*\*\*\*\*\*\*

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{6040a68 u0 com.nextcloud.client/.media.PlayerService}

	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)

	at android.os.Handler.dispatchMessage(Handler.java:107)

	at android.os.Looper.loop(Looper.java:214)

	at android.app.ActivityThread.main(ActivityThread.java:7682)

	at java.lang.reflect.Method.invoke(Native Method)

	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)

	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

\*\*\*\*\*\*\*\*\*\* **APP INFORMATION** \*\*\*\*\*\*\*\*\*\*

ID: com.nextcloud.client

Version: 30140051

Build flavor: gplay

\*\*\*\*\*\*\*\*\*\* **DEVICE INFORMATION** \*\*\*\*\*\*\*\*\*\*

Brand: OnePlus

Device: OnePlus6

Model: ONEPLUS A6003

Id: QKQ1.190716.003

Product: OnePlus6

\*\*\*\*\*\*\*\*\*\* **FIRMWARE** \*\*\*\*\*\*\*\*\*\*

SDK: 29

Release: 10

Incremental: 2010042216
```

**Comment by tobiasKaminsky** [comment] 2020-11-11 08:37
Duplicate of #6905, as it is the same root cause.

**Closed by tobiasKaminsky** 2020-11-11 08:37 UTC
Labels: bug
