### ISSUE TITLE
Update to 3.7.2 causes login loop

### ISSUE THREAD

**Issue by teddy19** [nextcloud/android#4351] opened 2019-08-20 05:40 UTC
Hello,

Tonight I got the update to 3.7.2 via the Playstore. This resulted in the app asking me to "Grant Access", which turned into a login loop. I could see the contents of the Cloud for approx. 2 seconds and would then asked to login again.
Deleting Cache and Storage would not fix this. Also reinstalling the app did not fix the behaviour.
The latest Dev-Version from F-Droid worked fine.
So I reinstalled the 3.7.1 version via F-Droid (sometimes it's good they are slower than Google :wink:). Everything works fine.
Lost my settings in the process, so leaving this here for people with the same problem.

I would suggest making a new release to fix this, even though I don't have the expertise to say which change fixed this.

**Comment by tobiasKaminsky** [comment] 2019-08-20 06:53
3.7.2 was just a fix in a library, so that should not be the cause.
We have #2267 and #3623, can you check back there and comment there?

Closing as duplicate.

**Closed by tobiasKaminsky** 2019-08-20 06:53 UTC
Labels: bug
