### ISSUE TITLE
Crash watching video 

### ISSUE THREAD

**Issue by Bekkenes** [nextcloud/android#7307] opened 2020-11-12 18:43 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{8614e5a u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1950)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:359)
	at android.app.ActivityThread.main(ActivityThread.java:7407)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: XQ-AS52
Model: XQ-AS52
Id: 58.0.A.22.21
Product: XQ-AS52_EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 058000A022002100442216154

**Comment by tobiasKaminsky** [comment] 2020-11-13 07:56
Duplicate of #6798

**Closed by tobiasKaminsky** 2020-11-13 07:56 UTC
Labels: bug
