### ISSUE TITLE
Problem when turn off battery warning

### ISSUE THREAD

**Issue by Perlover** [nextcloud/android#13925] opened 2024-10-31 23:47 UTC
### Cause of error
```java
Exception in thread "main" android.content.res.Resources$NotFoundException: Resource ID #0x7f0a0405 type #0x12 is not valid
    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2628)
    at android.content.res.Resources.getLayout(Resources.java:1337)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:542)
    at androidx.appcompat.app.AlertController.setupCustomContent(AlertController.java:644)
    at androidx.appcompat.app.AlertController.setupView(AlertController.java:475)
    at androidx.appcompat.app.AlertController.installContent(AlertController.java:233)
    at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:278)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:838)
    at android.app.Dialog.show(Dialog.java:454)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.showPowerCheckDialog(SyncedFoldersActivity.kt:233)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onDisablePowerSaveCheckClicked(SyncedFoldersActivity.kt:217)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onCreateOptionsMenu$lambda$1(SyncedFoldersActivity.kt:210)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.$r8$lambda$q58-_n5tvnvo7t7SwBQVBpaIAdU(Unknown Source:0)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$$ExternalSyntheticLambda4.onMenuItemClick(D8$$SyntheticClass:0)
    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:984)
    at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
    at android.widget.AdapterView.performItemClick(AdapterView.java:376)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1362)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3658)
    at android.widget.AbsListView.onTouchUp(AbsListView.java:4861)
    at android.widget.AbsListView.onTouchEvent(AbsListView.java:4556)
    at android.widget.ListView.onTouchEvent(ListView.java:1718)
    at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:230)
    at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:138)
    at android.view.View.dispatchTouchEvent(View.java:16234)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3346)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3006)
    at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:11467)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3352)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3022)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3352)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3022)
    at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2920)
    at android.view.View.dispatchPointerEvent(View.java:16498)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8676)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:8423)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7752)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7809)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7775)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7978)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7783)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:8035)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7756)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7809)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7775)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7783)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7756)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:11343)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:11212)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:11168)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:11477)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:337)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:335)
    at android.os.Looper.loopOnce(Looper.java:187)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:9063)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300490`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `q5q`
* Model: `SM-F946B`
* Id: `UP1A.231005.007`
* Product: `q5qxeea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `F946BXXS3DXI9`

**Comment by joshtrichards** [comment] 2024-11-01 12:10
Duplicate of #13922

**Closed by joshtrichards** 2024-11-01 12:10 UTC
