### ISSUE TITLE
Latest Android client 201022 stack trace navigating instant upload folder

### ISSUE THREAD

**Issue by fawbert** [nextcloud/android#10857] opened 2022-10-20 14:06 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Latest client version 201022
Open instant upload folder on Android client
Attempt to open a folder in that directory
Stack trace occurs
### Cause of error
```java
Exception in thread "main" java.lang.ClassCastException: com.owncloud.android.ui.adapter.OCFileListGridImageViewHolder cannot be cast to com.owncloud.android.ui.adapter.ListGridImageViewHolder
    at com.owncloud.android.ui.adapter.OCFileListAdapter.onBindViewHolder(OCFileListAdapter.java:362)
    at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
    at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
    at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
    at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:572)
    at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
    at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
    at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
    at android.view.View.layout(View.java:23330)
    at android.view.ViewGroup.layout(ViewGroup.java:6505)
    at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
    at android.view.View.layout(View.java:23330)
    at android.view.ViewGroup.layout(ViewGroup.java:6505)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
    at android.view.View.layout(View.java:23330)
    at android.view.ViewGroup.layout(ViewGroup.java:6505)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23330)
    at android.view.ViewGroup.layout(ViewGroup.java:6505)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
    at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1822)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
    at android.view.View.layout(View.java:23330)
    at android.view.ViewGroup.layout(ViewGroup.java:6505)
    at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
    at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
    at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2227)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
    at android.view.View.layout(View.java:23330)
    at android.view.ViewGroup.layout(ViewGroup.java:6505)
    at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
    at android.view.View.layout(View.java:23330)
    at android.view.ViewGroup.layout(ViewGroup.java:6505)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23330)
    at android.view.ViewGroup.layout(ViewGroup.java:6505)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23330)
    at android.view.ViewGroup.layout(ViewGroup.java:6505)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23330)
    at android.view.ViewGroup.layout(ViewGroup.java:6505)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:23330)
    at android.view.ViewGroup.layout(ViewGroup.java:6505)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:873)
    at android.view.View.layout(View.java:23330)
    at android.view.ViewGroup.layout(ViewGroup.java:6505)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3936)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3338)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2305)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9133)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1232)
    at android.view.Choreographer.doCallbacks(Choreographer.java:1029)
    at android.view.Choreographer.doFrame(Choreographer.java:934)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1217)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:233)
    at android.os.Looper.loop(Looper.java:344)
    at android.app.ActivityThread.main(ActivityThread.java:8212)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220090`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus8`
* Model: `IN2013`
* Id: `RKQ1.211119.001`
* Product: `OnePlus8_EEA`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `Q.GDPR.202208261325'

### Expected behaviour

Folder should open and show contents

### Actual behaviour

Stack trace as above

### Android version

12

### Device brand and model

Oneplus 8

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.00

### Nextcloud server version

23.0.8

### Using a reverse proxy?

No

### Android logs

I'm on a beach in Greece with just my mobile phone

### Server error logs

```bash
None
```

### Additional information

None

**Comment by AlvaroBrey** [comment] 2022-10-20 14:10
Duplicate of #10825

**Closed by AlvaroBrey** 2022-10-20 14:10 UTC
Labels: bug
