### ISSUE TITLE
Android App - Photos - None Showing 'upload some photos'

### ISSUE THREAD

**Issue by BASE813** [nextcloud/android#6138] opened 2020-05-23 19:37 UTC
![IMG_20200523_203829](https://user-images.githubusercontent.com/39741828/82739176-6a45ac80-9d35-11ea-9cc8-12c3ce6ee52d.jpg)
Pixel 2 XL running GrapheneOS QQ2A.200501.001.B3.2020.05.05.02

I can see photos on web access to my nextcloud instance, they do not show in the android app (I use auto upload to back up all images from phone).

**Comment by tobiasKaminsky** [comment] 2020-05-25 05:34
Duplicate of #1682

**Closed by tobiasKaminsky** 2020-05-25 05:34 UTC
