### ISSUE TITLE
Fast scrolling exception

### ISSUE THREAD

**Issue by RIS2000** [nextcloud/android#10607] opened 2022-08-08 11:37 UTC
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Fast scrolling big list of pictures in grid mode.

### Expected behaviour

subj

### Actual behaviour

Exception

### Android version

9

### Device brand and model

Huawei P30 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

302

### Nextcloud server version

22.2.1

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@8b5c643 rejected from java.util.concurrent.ThreadPoolExecutor@2a004c0[Running, pool size = 17, active threads = 17, queued tasks = 128, completed tasks = 7]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2104)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1413)
    at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:652)
    at com.owncloud.android.utils.DisplayUtils.setThumbnail(DisplayUtils.java:952)
    at com.owncloud.android.ui.adapter.OCFileListDelegate.bindGridViewHolder(OCFileListDelegate.kt:92)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.onBindViewHolder(OCFileListAdapter.java:366)
    at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
    at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
    at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
    at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:572)
    at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
    at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
    at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
    at android.view.View.layout(View.java:20960)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
    at android.view.View.layout(View.java:20960)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
    at android.view.View.layout(View.java:20960)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20960)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
    at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1831)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1597)
    at android.view.View.layout(View.java:20960)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
    at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
    at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2122)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
    at android.view.View.layout(View.java:20960)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
    at android.view.View.layout(View.java:20960)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20960)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20960)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20960)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
    at android.view.View.layout(View.java:20960)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:926)
    at android.view.View.layout(View.java:20960)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3037)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2545)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
    at android.view.Choreographer.doCallbacks(Choreographer.java:893)
    at android.view.Choreographer.doFrame(Choreographer.java:812)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
    at android.os.Handler.handleCallback(Handler.java:907)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:216)
    at android.app.ActivityThread.main(ActivityThread.java:7625)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `HUAWEI`
* Device: `HWVOG`
* Model: `VOG-L29`
* Id: `HUAWEIVOG-L29`
* Product: `VOG-L29RU`

### Firmware
* SDK: `28`
* Release: `9`
* Incremental: `9.1.0.241C10`

**Comment by AlvaroBrey** [comment] 2022-08-08 11:42
Duplicate of #10338

**Closed by AlvaroBrey** 2022-08-08 11:42 UTC
Labels: bug
