### ISSUE TITLE
Error using Nextcloud Android app

### ISSUE THREAD

**Issue by Henry221164** [nextcloud/android#7437] opened 2020-11-22 10:02 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{a3a4c4d u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1976)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7590)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: lavender
Model: Redmi Note 7
Id: QKQ1.190910.002
Product: lavender

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.1.0.QFGMIXM

**Comment by AndyScherzinger** [comment] 2020-11-23 09:07
Duplicate of #6905

**Closed by AndyScherzinger** 2020-11-23 09:07 UTC
