### ISSUE TITLE
crashes when pressing power check

### ISSUE THREAD

**Issue by deviltm** [nextcloud/android#14227] opened 2024-12-23 06:49 UTC
### Cause of error
```java
Exception in thread "main" android.content.res.Resources$NotFoundException: Resource ID #0x7f0a0420 type #0x12 is not valid
    at android.content.res.Resources.loadXmlResourceParser(Unknown Source:78)
    at android.content.res.Resources.getLayout(Unknown Source:2)
    at android.view.LayoutInflater.inflate(Unknown Source:15)
    at androidx.appcompat.app.AlertController.setupCustomContent(AlertController.java:644)
    at androidx.appcompat.app.AlertController.setupView(AlertController.java:475)
    at androidx.appcompat.app.AlertController.installContent(AlertController.java:233)
    at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:278)
    at android.app.Dialog.dispatchOnCreate(Unknown Source:4)
    at android.app.Dialog.show(Unknown Source:37)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.showPowerCheckDialog(SyncedFoldersActivity.kt:234)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onDisablePowerSaveCheckClicked(SyncedFoldersActivity.kt:218)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onCreateOptionsMenu$lambda$1(SyncedFoldersActivity.kt:211)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.$r8$lambda$q58-_n5tvnvo7t7SwBQVBpaIAdU(Unknown Source:0)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$$ExternalSyntheticLambda4.onMenuItemClick(D8$$SyntheticClass:0)
    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:984)
    at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
    at android.widget.AdapterView.performItemClick(Unknown Source:14)
    at android.widget.AbsListView.performItemClick(Unknown Source:190)
    at android.widget.AbsListView$PerformClick.run(Unknown Source:60)
    at android.widget.AbsListView.onTouchUp(Unknown Source:547)
    at android.widget.AbsListView.onTouchEvent(Unknown Source:193)
    at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:230)
    at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:138)
    at android.view.View.dispatchTouchEvent(Unknown Source:216)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:39)
    at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:521)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:80)
    at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:563)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:80)
    at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:563)
    at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(Unknown Source:22)
    at android.view.View.dispatchPointerEvent(Unknown Source:18)
    at com.xiaomi.mirror.MiuiMirrorImpl.isHandled(Unknown Source:20)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(Unknown Source:94)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(Unknown Source:131)
    at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:26)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:4)
    at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0)
    at android.view.ViewRootImpl$AsyncInputStage.forward(Unknown Source:10)
    at android.view.ViewRootImpl$InputStage.apply(Unknown Source:2)
    at android.view.ViewRootImpl$AsyncInputStage.apply(Unknown Source:7)
    at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:34)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:4)
    at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0)
    at android.view.ViewRootImpl$InputStage.apply(Unknown Source:2)
    at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:34)
    at android.view.ViewRootImpl.deliverInputEvent(Unknown Source:171)
    at android.view.ViewRootImpl.doProcessInputEvents(Unknown Source:65)
    at android.view.ViewRootImpl.enqueueInputEvent(Unknown Source:101)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(Unknown Source:161)
    at android.view.InputEventReceiver.dispatchInputEvent(Unknown Source:52)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(Unknown Source:17)
    at android.os.Looper.loopOnce(Unknown Source:6)
    at android.os.Looper.loop(Unknown Source:83)
    at android.app.ActivityThread.main(Unknown Source:123)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
    at com.android.internal.os.ZygoteInit.main(Unknown Source:378)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300690`
* Build flavor: `gplay`

### Device information
* Brand: `REDMI`
* Device: `mondrian`
* Model: `23013PC75G`
* Id: `UKQ1.230804.001`
* Product: `mondrian`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `V816.0.14.0.UMNCNXM`![Image](https://github.com/user-attachments/assets/c7484795-7547-4c0e-b36c-b6a687d77e59)
![Image](https://github.com/user-attachments/assets/7e4312b2-4069-42d3-9349-0dee5d76ac3f)

**Comment by joshtrichards** [comment] 2024-12-28 14:47
Duplicate of #13404

**Closed by joshtrichards** 2024-12-28 14:47 UTC
