### ISSUE TITLE
Background app crash

### ISSUE THREAD

**Issue by jakimfett** [nextcloud/android#4838] opened 2019-11-17 17:44 UTC
### Actual behaviour
When closing the background apps, Nextcloud reported a crash.

### Expected behaviour
- No crashing?
 
### Steps to reproduce
1. Open Nextcloud Dev (fdroid, v20191108)
2. Set a folder to sync.
3. Close app.
4. Use other apps.
5. Close allbackground apps.
6. Crash?

### Pasted crashdump provided by my device
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1788)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:169)
	at android.app.ActivityThread.main(ActivityThread.java:6595)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20191108
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: asus
Device: ASUS_Z01H_1
Model: ASUS_Z01HD
Id: OPR1.170623.026
Product: WW_Z01H

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: WW_80.30.76.74_20190319

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2019-12-03 15:01
duplicate of #2010, so closing in favor

**Closed by AndyScherzinger** 2019-12-03 15:01 UTC
Labels: bug
