### ISSUE TITLE
Unable to upload files from android client

### ISSUE THREAD

**Issue by jsanfe** [nextcloud/android#7623] opened 2020-12-07 11:42 UTC
### Steps to reproduce
1. Try to share any picture or file vía nextcloud
2. Device try to copy picture or file to a temporal folder before upload. Then, an error happen.
3. 

### Expected behaviour
- UPLOAD pictures/files without problems

### Actual behaviour
- Tell us what happens
Since last android client upgrade, i cant upload any file to my serves. I tryed many differents ways to upload but, nextcloud client give me same error: its unable to copy file to a temporal folder.
I cheked the file route, i give all permisions to the Nextcloud client... 
### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
10

Device model: 
Huawei P20
Stock or customized system:
EMUI 10.0.0

Nextcloud app version:
3.14.2
Nextcloud server version:
19.0.5

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-12-07 12:02
Duplicate of #7587

**Closed by AndyScherzinger** 2020-12-07 12:02 UTC
Labels: bug
