### ISSUE TITLE
[F - R] Auto delete uploaded files after X days

### ISSUE THREAD

**Issue by sanchosk** [nextcloud/android#11572] opened 2023-04-29 07:42 UTC
### Is your feature request related to a problem? Please describe.
The feature is not related to a problem.

### Describe the solution you'd like
When I auto-upload photos using Android Nextcloud client, it would be great if the app also did a "cleanup" - e.g. removing files that were backed up after 90 days from the phone. This would clean up local storage while ensuring I still do have my files.
Currently implemented "What to do after upload" only allows direct delete, this slows the actual usage of the photos when not at home.

### Describe alternatives you've considered
So far I am doing the same using ADB and few linux commands (find -mtime and adb pull).

### Additional context
N/A

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by socratesprime** [comment] 2023-08-25 21:48
Hello guys, I'm a total noob, but I'm interested in learning from scratch to contribute to this project. Where do I start?

**Comment by joshtrichards** [comment] 2023-10-08 20:02
Duplicate of #9037
I encourage you to subscribe yourself to that issue to track progress and/or contribution to the feature development discussion.

**Closed by joshtrichards** 2023-10-08 20:02 UTC
Labels: enhancement, feature: AutoUpload
