### ISSUE TITLE
File conflict desicion not stored

### ISSUE THREAD

**Issue by Waldmeisda** [nextcloud/android#9614] opened 2021-12-23 12:10 UTC
### Steps to reproduce
1.  Take a picture, modify the picture on your phone, save it (that replaces the old file).
2.  the nextcloud client pushed the first file already, detects the change and ask what file to keep.
3.  Select the server file to keep.

### Expected behavior
- The client should remember the decision and and don't ask again. And maybe store the new file on server with a certain suffix.

### Actual behavior
- The client asks again and again what to do until I delete the file locally or choose to overwrite the server version.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model: S10

Stock or customized system:Stock

Nextcloud app version: 3.18.0

Nextcloud server version: 23.0.0

Reverse proxy:

**Comment by AlvaroBrey** [comment] 2022-01-03 16:09
Duplicate of #7905

**Closed by AlvaroBrey** 2022-01-03 16:09 UTC
Labels: bug
