### ISSUE TITLE
Massive hiding.

### ISSUE THREAD

**Issue by piotrbujakowski** [nextcloud/android#13857] opened 2024-10-22 18:04 UTC
### Cause of error
```java
Exception in thread "FinalizerWatchdogDaemon" java.util.concurrent.TimeoutException: android.media.MediaMetadataRetriever.finalize() timed out after 10 seconds
    at android.media.MediaMetadataRetriever.native_finalize(Native Method)
    at android.media.MediaMetadataRetriever.finalize(MediaMetadataRetriever.java:1069)
    at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
    at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
    at java.lang.Daemons$Daemon.run(Daemons.java:139)
    at java.lang.Thread.run(Thread.java:923)

```

### App information
* ID: `tech.shadow.drive.android.client`
* Version: `30290090 (build #22647)`
* Build flavor: `gplay`

### Device information
* Brand: `Blackview`
* Device: `Tab11_EA`
* Model: `Tab 11`
* Id: `RP1A.201005.001`
* Product: `Tab11_EA`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `2022420`

**Comment by joshtrichards** [comment] 2024-10-22 18:46
Duplicate of #13324

**Closed by joshtrichards** 2024-10-22 18:46 UTC
