### ISSUE TITLE
While dealing with the 3.30.4 Fiasko disabling Internet causes a crash

### ISSUE THREAD

**Issue by pohuing** [nextcloud/android#13970] opened 2024-11-07 02:25 UTC
### Cause of error
```java
Exception in thread "main" android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{c70ed75 u0 com.nextcloud.client/androidx.work.impl.foreground.SystemForegroundService}
    at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2184)
    at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2155)
    at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2449)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:245)
    at android.os.Looper.loop(Looper.java:364)
    at android.app.ActivityThread.main(ActivityThread.java:8424)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
Caused by: Exception in thread "main" android.app.StackTrace: Last startServiceCommon() call for this service was made here
    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1952)
    at android.app.ContextImpl.startForegroundService(ContextImpl.java:1906)
    at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:837)
    at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:837)
    at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:1128)
    at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:700)
    at androidx.work.impl.Processor.startForeground(Processor.java:206)
    at androidx.work.impl.utils.WorkForegroundUpdater$1.run(WorkForegroundUpdater.java:100)
    at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300490`
* Build flavor: `generic`

### Device information
* Brand: `asus`
* Device: `ASUS_AI2302`
* Model: `ASUS_AI2302`
* Id: `UKQ1.230917.001`
* Product: `EU_AI2302`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `34.1004.0204.180`

**Comment by pohuing** [comment] 2024-11-07 02:30
I'll add a video tomorrow. Github fails at letting me upload a screencap and it's 3:30am

**Comment by pohuing** [comment] 2024-11-07 11:51
Since github is currently returning a http 422 when trying to upload videos I've uploaded the screen recording to https://youtu.be/Ao1GC05O8lU .

**Comment by pohuing** [comment] 2024-11-07 11:53
I probably won't be able to reproduce this any further. I've decided to reinstall nextcloud because I do need a working client

**Comment by joshtrichards** [comment] 2024-11-07 14:50
Looks like #12706

**Comment by pohuing** [comment] 2024-11-07 15:45
It sure does. Though my issue only occurs if I disable the internet connection in conjuction with having a lot of two way syncs queued.

I believe I spottet a reference to some max number of sync jobs at 20 where the 21st would throw but I don't have those logs anymore unfortunately. 

Am 7. November 2024 15:50:57 MEZ schrieb Josh ***@***.***>:

**Comment by pohuing** [comment] 2024-11-07 15:46
Oh hey never mind me. I do have a screenshot ![Image](https://github.com/user-attachments/assets/67d8db18-1f28-40c7-9e5d-aee65222f32a)

**Comment by AndyScherzinger** [comment] 2024-11-07 20:02
looping in @tobiasKaminsky and @alperozturk96 (who fixed a lot of things recently on this newly introduced feature)

**Comment by joshtrichards** [comment] 2024-12-28 15:42
Duplicate of #12706
Related to #13906

**Closed by joshtrichards** 2024-12-28 15:42 UTC
Labels: bug, 0. Needs triage, performance: misc, stable-3.30, feature: sync
