### ISSUE TITLE
This image cannot be shown

### ISSUE THREAD

**Issue by duckulaj** [nextcloud/android#1045] opened 2017-05-26 09:15 UTC
### Actual behaviour
Clicking on a photo displays black screen with warning triangle with caption This image cannot be shown 

### Expected behaviour
Display the photograph
 
### Steps to reproduce
1. Click on an image to view
2. 
3. 

### Environment data
Android version:
7.0
Device model: 
Galaxy S7
Stock or customized system:
Stock
Nextcloud app version:
1.4.3
Nextcloud server version:
11.0.3
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2017-05-26 12:57
Is there something special with this image? What kind of image it this? jpg? tiff? png?

**Comment by duckulaj** [comment] 2017-05-26 18:40
It's a jpeg. Also noticed it seems to be all images since 7th May

**Comment by tobiasKaminsky** [comment] 2017-05-27 06:07
And they are uploaded correctly? You can see them with the web browser or with your synced pc/laptop?

**Comment by duckulaj** [comment] 2017-05-27 08:47
I can see the images fine using the website.

**Comment by duckulaj** [comment] 2017-05-27 08:47
Meant to type WEBUI

**Comment by tobiasKaminsky** [comment] 2017-06-12 09:17
Can you try demo.nextcloud.com to see if it is working with another server?

**Comment by sheyll** [comment] 2017-06-12 16:14
I have the same problem...

**Comment by duckulaj** [comment] 2017-06-12 18:19
Worked fine. Demo image and one I uploaded. 

Not able to recreate problem reliably, but still exists. 

Next time it happens I will try to track down any debug information.

**Comment by j-ed** [comment] 2017-06-12 21:58
@duckulaj / @sheyll Where are the images stored on a local file system or on an external share?

**Comment by OlivierS1** [comment] 2017-06-12 23:34
Just a thought here:
- Trying to download an image when Wifi connection is diabled will cause the dark Warning triangle to appear with "Download failed" message.

Could this be a case when images have been corrupted during download?
Is it possible the cache is conflicting with the downloaded files causing the phone to load the wrong player?

**Comment by sheyll** [comment] 2017-06-13 00:52
@j-ed The images are stored on the builtin flash drive AND on the external SD card that I added. I get a grey triangle and the message "Dieses Bild kann nicht angezeigt werden".

But hey, count me out. I will not invest more energy into diagnosing the problem until I have settled on nextcloud. I will try to find better alternatives first, because
until now nextcloud did not leave the best impression on me, it was crazy complicated to install and leaves a bitter taste of insecurity - since I am not a PHP expert. Also the Android client seems very improvable: There are more than this issue, much worse than the fact, that I want to use it mainly to share photos, and it cant display fotos, is the issue that it ignored the upload only when charging and on wifi settings (which by the way were very unintuitive for me to find) - and has depleted both battery and data plan o-O ...

Otherwise, nextcloud is ... ok, but it might be benificial to look for other alternatives.

**Comment by duckulaj** [comment] 2017-06-13 05:40
My files are stored on external USB drive.

**Comment by tobiasKaminsky** [comment] 2017-06-28 11:38
If someone can reproduce, can he then create a test account, share this file to the new user and send the credentials with a reference to this issue to android at nextcloud dot com?

**Comment by tobiasKaminsky** [comment] 2017-06-29 08:51
After mailing with someone ho had the same problem, we could identify that the file is just 0b. So deleting this file and downloading it again resolved the problem.
It is now hard to reproduce why there was only a 0b file.
If someone has new infos on that, or it is not resolved by deleting the 0b file, please re-open.

**Closed by tobiasKaminsky** 2017-06-29 08:51 UTC
Labels: bug, needs info
