### ISSUE TITLE
does not Download files, when the @:: is in the directory name

### ISSUE THREAD

**Issue by AtheiAmal** [nextcloud/android#8993] opened 2021-09-21 13:43 UTC
### Steps to reproduce
1. create or rename directory with an "@::" inside of the name
2. put a picture file(maybe also others; "worked" with .jpg and .webp
3. try synchronizing the directory

### Expected behaviour
-downloading the directory

### Actual behaviour
- notice of failed downloading the files (for every file inside)

### Can you reproduce this problem on https://try.nextcloud.com?
- yes
- 
### Environment data
Android version: 11

Device model: oneplus6

Stock or customized system:Lineage OS - enchilda

Nextcloud app version: 3.17.0

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Telefza** [comment] 2021-12-01 08:48
noticed that it would not download from any folder that even just has a `:`  in it. Could this be the same bug as [this one](https://github.com/nextcloud/android/issues/8523) ?

**Comment by AlvaroBrey** [comment] 2021-12-01 09:40
Yeah, same issue  as #8523, consolidating in that one

**Comment by AlvaroBrey** [comment] 2021-12-01 09:40
Duplicate of #8523

**Closed by AlvaroBrey** 2021-12-01 09:40 UTC
Labels: bug, approved
