### ISSUE TITLE
Error in sync: android.database.sqlite.SQLiteCantOpenDatabaseException

### ISSUE THREAD

**Issue by xpro666** [nextcloud/android#9172] opened 2021-10-29 07:26 UTC
************ CAUSE OF ERROR ************
```java
android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 2062)
#################################################################
Error Code : 2062 (SQLITE_CANTOPEN_EMFILE)
Caused By : Application has opened too many files. Maximum of available file descriptors in one process is 1024 in default.
	(unable to open database file (code 2062))
#################################################################
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:717)
	at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:323)
	at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:298)
	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:663)
	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:574)
	at com.owncloud.android.providers.FileContentProvider.query(FileContentProvider.java:478)
	at android.content.ContentProvider.query(ContentProvider.java:1065)
	at android.content.ContentProvider.query(ContentProvider.java:1157)
	at android.content.ContentProvider$Transport.query(ContentProvider.java:245)
	at android.content.ContentResolver.query(ContentResolver.java:760)
	at android.content.ContentResolver.query(ContentResolver.java:710)
	at android.content.ContentResolver.query(ContentResolver.java:668)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadStatus(UploadsStorageManager.java:196)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateDatabaseUploadResult(UploadsStorageManager.java:580)
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:661)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1402)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a7y17lte
Model: SM-A720F
Id: R16NW
Product: a7y17ltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: A720FXXS9CTJ9

**Comment by hartelt** [comment] 2022-02-06 16:44
This affects me, too. Appears quite frequently since today.
Posting the error message, hoping to provide some further info:

************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 2062)
#################################################################
Error Code : 2062 (SQLITE_CANTOPEN_EMFILE)
Caused By : Application has opened too many files. Maximum of available file descriptors in one process is 1024 in default.
	(unable to open database file (code 2062))
#################################################################
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1018)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:152)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:141)
	at android.content.ContentResolver.query(ContentResolver.java:779)
	at android.content.ContentResolver.query(ContentResolver.java:710)
	at android.content.ContentResolver.query(ContentResolver.java:668)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadStatus(UploadsStorageManager.java:195)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateDatabaseUploadStart(UploadsStorageManager.java:597)
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:610)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1396)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30190090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: herolte
Model: SM-G930F
Id: R16NW
Product: heroltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G930FXXU8ETI2

**Comment by AlvaroBrey** [comment] 2022-02-07 08:27
It seems like both crashes are triggered at `updateUploadStatus`. Are you trying to upload (or auto-upload) a large amount of files? 

Just trying to figure out how to reproduce this.

**Comment by xpro666** [comment] 2022-02-07 09:36
Hi, I upload not large files, a few mb

**Comment by xpro666** [comment] 2022-02-07 09:39
Also I have problem with conflict window, it is not opened

**Comment by AlvaroBrey** [comment] 2022-02-07 10:46
> Hi, I upload not large files, a few mb

I meant a large _amount_ of files (as in, many files, several hundred or thousand files), not a large size

**Comment by xpro666** [comment] 2022-02-07 14:23
About 60 files was upload via auto-upload, and I try upload one file. I think, I haven't correct nginx setting on my server maybe

**Comment by hartelt** [comment] 2022-02-17 18:37
> It seems like both crashes are triggered at `updateUploadStatus`. Are you trying to upload (or auto-upload) a large amount of files?
> 
> Just trying to figure out how to reproduce this.

Yeah, for me it was triggered when I bulk-copied many files into an auto-upload folder. Since cancelling all the uploads, I have no further crashes. Hoping it stays that way.

**Comment by galoo** [comment] 2022-11-22 21:22
I have the exact same bug, trying to sync my media folder with a few hundreds of pictures on my android phone with the server. 
Do you have any advice on how to handle this ? Is the problem the number of files in the same folder ? Or the total number of files in directories and subdirectories ? Would it be better if I can reorganize the pictures ?

**Comment by joshtrichards** [comment] 2023-12-22 21:42
@galoo What device and OS version? Also what app version in your case?

**Comment by joshtrichards** [comment] 2024-10-27 14:12
Closing as this code path doesn't exist any longer and there haven't any further reports in ~2 years.

**Closed by joshtrichards** 2024-10-27 14:12 UTC
Labels: bug, feature: auto upload, performance: general/non-specific, stable-3.17
