### ISSUE TITLE
Android app crashes after changing password

### ISSUE THREAD

**Issue by copenhaus** [nextcloud/android#8728] opened 2021-07-18 00:44 UTC
### Steps to reproduce
1. Change password
2. Launch the app in Android 

### Expected behaviour
- Tell us what should happen - prompt you a password has changed
- Tell us what happens

************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:7)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.nextcloud.client.network.ClientFactoryImpl.createNextcloudClient(ClientFactoryImpl.java:62)
	at com.owncloud.android.ui.asynctasks.RetrieveStatusAsyncTask.doInBackground(RetrieveStatusAsyncTask.java:55)
	at com.owncloud.android.ui.asynctasks.RetrieveStatusAsyncTask.doInBackground(RetrieveStatusAsyncTask.java:39)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: z3q
Model: SM-G988U
Id: RP1A.200720.012
Product: z3qsqw

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: G988USQS2DUE2

**Comment by vdanjean** [comment] 2021-07-18 07:33
Perhaps, it is linked to #2833?

**Comment by Sp3ct21** [comment] 2021-07-18 13:28
Bug

**Comment by AndyScherzinger** [comment] 2021-08-11 21:38
Duplicate of #8370

**Closed by AndyScherzinger** 2021-08-11 21:38 UTC
Labels: bug
