### ISSUE TITLE
More faster user experience with Json API

### ISSUE THREAD

**Issue by developerfromjokela** [nextcloud/android#4011] opened 2019-05-13 06:52 UTC
### Is your feature request related to a problem? 
Hello! I tested yesterday on browser my new Nextcloud server on local network, and tried it on Android app, and I am disappointed for speeds, Web UI is faster than WebDAV or whatever is using Nextcloud app.

### Describe the solution you'd like
If WebUI is faster, then it will be nice idea to create Json API which will be as fast as WebUI, and supporting all features, but remaining fast.
Of course this should be Implemented first in Nextcloud server, and after that in Apps.

**Comment by AndyScherzinger** [comment] 2019-05-13 07:46
Except for actual file operations (WebDAV) or other calls are ReST/JSON based APIs.

**Comment by developerfromjokela** [comment] 2019-05-13 08:00
@AndyScherzinger Ok, good to know, but can we replace even file operations with JSON API?

**Comment by AndyScherzinger** [comment] 2019-05-13 17:00
pinging @tobiasKaminsky for his opinion and input. My guess:

> can we replace even file operations with JSON API?

very unlikely to happen

> But why there is some time difference between doing something in browser and app? I will investigate this thing this week.

That I don't know, depends on the operation I guess. Some stuff is differnet e.g. Android client doing chunked uploads. Server's client is by design always up-to-date data-wise (since client and server are more or less "one thing") while the Android clietn needs to sync (folder structure, file meta data)... So whatever you do, Android or any mobile client (not opening the webUI in the brower! of course) will be slower.

**Comment by developerfromjokela** [comment] 2019-05-13 17:03
Yes, I understand that. But if we compare Google Drive, these speeds are
about the same on browser and the Google Drive app, so I am assuming
something is wrong in app.

**Comment by AndyScherzinger** [comment] 2019-05-13 17:06
> so I am assuming something is wrong in app.

Maybe there are some performance issues or Google's client is doing some heavy pre-fetching in the background. Don't know.

**Comment by developerfromjokela** [comment] 2019-05-13 19:22
@AndyScherzinger about that pre-fetching, can be put caching to next level?

**Comment by ezaquarii** [comment] 2019-05-13 19:46
@developerfromjokela First of all, such claims require numbers to asses, ie. benchmarks.

WebDAV has an advantage of near-perfect interoperability, contrary to the proprietary Google Drive client. You don't need any special clients to use WebDAV-accessible resources, regardless of computing platform you use.

Migrating it to a proprietary interface means that you suddenly need to develop a proprietary client for every supported platform and 3rd party software, as a lot of software is WebDAV-aware (file managers, organizers, office software, etc, etc).

I personally believe that designing ownCloud/Nextcloud with WebDAV instead of some hipster API, was very smart product decision.

**Comment by AndyScherzinger** [comment] 2019-05-13 20:30
> about that pre-fetching, can be put caching to next level?

rather not since other things (like improving auto upload reliability) would definitely come first.

**Comment by developerfromjokela** [comment] 2019-05-13 21:01
I found out something interesting, after 2 days of use, it's as fast as
browser. Maybe that caching just requires some time?

**Comment by AndyScherzinger** [comment] 2019-05-13 21:06
Hard to tell, initially when you login the first time the client does trigger a background caching of the complete folder/file structure info (which takes a while). So that might have been what you experienced while I can only guess since I don't know which operations seemed to have taken a while...

**Comment by tobiasKaminsky** [comment] 2019-05-14 05:57
> pinging @tobiasKaminsky for his opinion and input. My guess:
> 
> > can we replace even file operations with JSON API?
> 
> very unlikely to happen

We are "limited" to what the server exposes. And this is webDav.
On the other hand I am not sure if switching the api is a win. 
On big folders the problem is not transferring the data, but storing and displaying it.

**Comment by tobiasKaminsky** [comment] 2019-05-14 05:58
> I found out something interesting, after 2 days of use, it's as fast as browser. Maybe that caching just requires some time?

Yeah, this is due to the fact that infos of most folders is now on device and as it is not changed, it can directly be shown.
(upon folder entry we check if there is a change, otherwise directly show the cached infos)

**Comment by ezaquarii** [comment] 2019-05-14 06:16
IMO the near perfect interoperability that WebDAV provides is a huge win. There might be some isolated niche use cases where it is a bottleneck.

**Comment by joshtrichards** [comment] 2023-10-15 18:53
Closing this as it's >4 years old and:

- the priority avenues for performance improvement are elsewhere
- the caching matter us known/covered elsewhere
- there's no remaining actionable bits here

**Closed by joshtrichards** 2023-10-15 18:53 UTC
Labels: enhancement, needs info
