### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by rafleo** [nextcloud/android#8525] opened 2021-06-05 07:19 UTC
### Steps to reproduce
1. Open Nextcloud app on Android

### Expected behaviour
- App opens up and shows folder list

### Actual behaviour
- App shows browser list for less than a second, then crashes and displays below's error log.
- App also shows failed upload notifications "Upload failed, log in again. Wrong username or password"

This behaviour has just randomly started, previously everything was working fine. No server updates recently, no change in users or account. Desktop apps and browser version work without problems.

### Can you reproduce this problem on https://try.nextcloud.com?
- No, but because I can no longer start the app to change login details or add an account.

### Environment data
Android version: 11

Device model: Google Pixel 4a (5G)

Stock or customized system: Stock

Nextcloud app version: 3.16.1 from Google Play Store

Nextcloud server version: 21.0.2

Reverse proxy: none

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: google
Device: bramble
Model: Pixel 4a (5G)
Id: RQ2A.210505.003
Product: bramble

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 7255357

**Comment by mightymop** [comment] 2021-06-05 09:03
This PR https://github.com/nextcloud/android-library/pull/638 should fix it

**Comment by AndyScherzinger** [comment] 2021-06-07 14:00
Duplicate of #8370

**Closed by AndyScherzinger** 2021-06-07 14:00 UTC
Labels: bug
