### ISSUE TITLE
InstantUpload: Only when auto-sync data is enabled!

### ISSUE THREAD

**Issue by gloschtla** [nextcloud/android#3221] opened 2018-11-04 12:13 UTC
This app should not start uploading when connected to an untrusted public wifi network. Android lets me define, which wifi SSIDs shall trigger the auto-sync mode. This way prevents my passwords being sent via unencrypted WiFi.

**Comment by flokli** [comment] 2019-01-02 12:36
How do you measure a "trusted" private wifi network? With disabled encryption, there's always ways to intercept traffic, and hijack sessions.

The reasonable fix is rolling out https, and with Letsencrypt being widely available, there shouldn't be much of a reason not to do.

Instead of complicating UI, we should probably discourage setting up non-https connections in first place.

We already show "Secure connection unavailable." during initial connection setup, maybe this warning should be made much more prominent, encouraging owncloud owners to roll out ssl?

**Comment by joshtrichards** [comment] 2023-12-22 22:38
Duplicate of #3671

**Closed by joshtrichards** 2023-12-22 22:38 UTC
Labels: enhancement, feature: auto upload, feature: data usage
