### ISSUE TITLE
Close app in Device Android A50 Samsung

### ISSUE THREAD

**Issue by masterchess** [nextcloud/android#5141] opened 2020-01-09 19:09 UTC
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-01-09 19:52
@masterchess can you please post the log cat infos with the stack trace please?

**Comment by masterchess** [comment] 2020-01-17 20:32
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of:
Lcom/google/firebase/analytics/connector/AnalyticsConnector;
at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
at
com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown
Source:2)
at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown
Source:50)
at com.google.firebase.iid.zzg.run(Unknown Source:4)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class
"com.google.firebase.analytics.connector.AnalyticsConnector" on path:
DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar",
zip file
"/data/app/com.nextcloud.client-hWvpScyJHLYXljzwKU4RqQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-hWvpScyJHLYXljzwKU4RqQ==/lib/arm64,
/data/app/com.nextcloud.client-hWvpScyJHLYXljzwKU4RqQ==/base.apk!/lib/arm64-v8a,
/system/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a50
Model: SM-A505FN
Id: PPR1.180610.011
Product: a50eea

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: A505FNXXU3ASL6



Il Gio 9 Gen 2020, 20:52 Andy Scherzinger <notifications@github.com> ha
scritto:

**Comment by masterchess** [comment] 2020-01-20 20:21
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of:
Lcom/google/firebase/analytics/connector/AnalyticsConnector;
at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
at
com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown
Source:2)
at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown
Source:50)
at com.google.firebase.iid.zzg.run(Unknown Source:4)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class
"com.google.firebase.analytics.connector.AnalyticsConnector" on path:
DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar",
zip file
"/data/app/com.nextcloud.client-NvvHnQKhdHeL_AQjLoB1Ag==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-NvvHnQKhdHeL_AQjLoB1Ag==/lib/arm64,
/data/app/com.nextcloud.client-NvvHnQKhdHeL_AQjLoB1Ag==/base.apk!/lib/arm64-v8a,
/system/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a50
Model: SM-A505FN
Id: PPR1.180610.011
Product: a50eea

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: A505FNXXU3ASL6

Il Ven 17 Gen 2020, 21:31 carlo ernesto <m45t3rch355@gmail.com> ha scritto:

**Comment by AndyScherzinger** [comment] 2020-01-20 21:17
@masterchess thanks for the logcat!

duplicate of #4675 - so closing in favor

**Closed by AndyScherzinger** 2020-01-20 21:17 UTC
Labels: bug, needs info/discussion
