### ISSUE TITLE
Current menu item is wrong when switching activities

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/android#4669] opened 2019-10-12 18:43 UTC
### Actual behaviour
- After switching to another activity and bavk, the highlighted menu item does not match the currently selected menu item

### Expected behaviour
- The highlighted entry should match the current selected entry
 
### Steps to reproduce
1. Open files app and click on "Favorites"
2. Switch to another app and back
3. Instead of "Favorites", the first item is highlighted

### Environment data

Nextcloud app version: 3.8.0

![ezgif-2-96d770b75e6e](https://user-images.githubusercontent.com/4741199/66706203-35e62880-ed30-11e9-91ce-412b2adb0947.gif)

PS: Maybe related:

Open files app, select "Fotos" in drawer, then select "Favorites", then select "All Files".

If you now switch to another app and back, i would expect "All Files" to be highlighted. Instead, "Favorites" is still highlighted.

I can provide a screen record or open another issue if needed.

**Comment by AndyScherzinger** [comment] 2019-10-13 07:44
If I am not mistaken than @tobiasKaminsky wanted to rewrite this part since the event bus stuff just doesn't work as we want it to, so the menu state gets confused in these areas...

**Comment by Shagequi** [comment] 2019-12-04 17:23
Good evening :)
Do you have some news about this issue ? @AndyScherzinger @tobiasKaminsky ?
I'm studying the subject, but if you have a specific way of doing it, I'll let you do it.

**Comment by joshtrichards** [comment] 2023-10-13 20:07
Let's consolidate tracking this into #3648

Duplicate of #3648

**Closed by joshtrichards** 2023-10-13 20:07 UTC
Labels: bug, approved
