### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference

### ISSUE THREAD

**Issue by kiplingw** [nextcloud/android#3273] opened 2018-11-17 19:05 UTC
I am using Nextcloud client stable release, 3.3.2. When I click login after entering my credentials the client crashes.

I've monitored the server side Apache logs and there isn't anything unusual:
```
...
[***scrubbed***] - - [17/Nov/2018:10:59:01 -0800] "GET /status.php HTTP/1.1" 200 4480 "-" "Mozilla/5.0 (Android) ownCloud-android/3.3.2" 
[***scrubbed***] - - [17/Nov/2018:10:59:01 -0800] "HEAD /remote.php/webdav/ HTTP/1.1" 401 1129 "-" "Mozilla/5.0 (Android) ownCloud-android/3.3.2" 
[***scrubbed***] - - [17/Nov/2018:10:59:02 -0800] "GET /index.php/login/flow HTTP/1.1" 200 11418 "-" "My Phone" 
[***scrubbed***] - - [17/Nov/2018:10:59:02 -0800] "GET /index.php/core/js/oc.js?v=5d804a4a HTTP/1.1" 200 4983 "-" "My Phone" 
[***scrubbed***] - - [17/Nov/2018:10:59:08 -0800] "GET /index.php/login/flow/redirect?stateToken=[***scrubbed***]&clientIdentifier= HTTP/1.1" 303 1200 "-" "My Phone" 
[***scrubbed***] - - [17/Nov/2018:10:59:08 -0800] "GET /index.php/login?redirect_url=/index.php/login/flow/redirect%3FstateToken%3D[***scrubbed***]%26clientIdentifier%3D HTTP/1.1" 200 8870 "-" "My Phone" 
[***scrubbed***] - - [17/Nov/2018:10:59:09 -0800] "GET /index.php/core/js/oc.js?v=5d804a4a HTTP/1.1" 200 4983 "-" "My Phone" 
[***scrubbed***] - - [17/Nov/2018:10:59:30 -0800] "POST /index.php/login?redirect_url=/index.php/login/flow/redirect%3FstateToken%3D[***scrubbed***]%26clientIdentifier%3D HTTP/1.1" 303 1285 "-" "My Phone" 
[***scrubbed***] - - [17/Nov/2018:10:59:32 -0800] "GET /index.php/login/flow/redirect?stateToken=[***scrubbed***]&clientIdentifier= HTTP/1.1" 200 6787 "-" "My Phone" 
[***scrubbed***] - - [17/Nov/2018:10:59:34 -0800] "GET /index.php/core/js/oc.js?v=5d804a4a HTTP/1.1" 200 5054 "-" "My Phone" 
[***scrubbed***] - - [17/Nov/2018:10:59:38 -0800] "POST /index.php/login/flow HTTP/1.1" 303 1047 "-" "My Phone" 
[***scrubbed***] - - [17/Nov/2018:10:59:43 -0800] "GET /status.php HTTP/1.1" 200 1315 "-" "Mozilla/5.0 (Android) ownCloud-android/3.3.2" 
[***scrubbed***] - - [17/Nov/2018:10:59:44 -0800] "HEAD /remote.php/webdav/ HTTP/1.1" 401 1131 "-" "Mozilla/5.0 (Android) ownCloud-android/3.3.2" 
[***scrubbed***] - - [17/Nov/2018:10:59:44 -0800] "HEAD /remote.php/webdav/ HTTP/1.1" 200 1062 "-" "Mozilla/5.0 (Android) ownCloud-android/3.3.2" 
[***scrubbed***] - - [17/Nov/2018:10:59:47 -0800] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 1545 "-" "Mozilla/5.0 (Android) ownCloud-android/3.3.2"
```

On the client side via adb I note the client seems to be raising some issues:
```
11-17 10:59:29.126  2072  2072 W InputMethodService: Window size has been changed. This may cause jankiness of resizing window: -1 -> -2
11-17 10:59:29.128 16702 17039 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
11-17 10:59:35.627  1550  1769 D bt_btif : BTHF: device_status_notification
11-17 10:59:35.627  1550  1739 D bt_btif : AG evt (hdl 0x0001): State 2, Event 0x0506
11-17 10:59:35.627  1550  1739 D bt_btif : bta_ag_hfp_result : res = 5
11-17 10:59:35.628  1550  1739 D bt_btif : AG evt (hdl 0x0001): State 2, Event 0x0506
11-17 10:59:35.628  1550  1739 D bt_btif : bta_ag_hfp_result : res = 5
11-17 10:59:35.628  1550  1739 D bt_btif : AG evt (hdl 0x0001): State 2, Event 0x0506
11-17 10:59:35.628  1550  1739 D bt_btif : bta_ag_hfp_result : res = 5
11-17 10:59:35.628  1550  1739 D bt_btif : AG evt (hdl 0x0001): State 2, Event 0x0506
11-17 10:59:35.629  1550  1739 D bt_btif : bta_ag_hfp_result : res = 5
11-17 10:59:36.780 16702 16702 I chromium: [INFO:CONSOLE(7)] "JQMIGRATE: Migrate is installed, version 1.4.0", source: https://[***scrubbed***]/core/vendor/core.js?v=5d804a4a-10 (7)
11-17 10:59:40.766  2657  3017 D BatchingTimer: Device timer is done.
11-17 10:59:40.766  2657  3017 D BatchingTimer: Device batch timer is started.
11-17 10:59:40.815  2657 18396 D BatchingTimer: Device timer time: 60
11-17 10:59:42.116 16702 16702 D OperationsService: Starting command with id 4
11-17 10:59:42.130 16702 16743 D OwnCloudClient #0: REQUEST GET /status.php
11-17 10:59:42.137 16702 16743 D AdvancedSslSocketFactory: Creating SSL Socket with remote [***scrubbed***]:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@c7413e3
11-17 10:59:42.140 16702 16743 D AdvancedSslSocketFactory:  ... with connection timeout 50000 and socket timeout 60000
11-17 10:59:42.146 16702 16743 I ServerNameIndicator: SNI done, hostname: [***scrubbed***]
11-17 10:59:43.036 16702 16743 W HttpMethodBase: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
11-17 10:59:43.043 16702 16743 I GetRemoteStatusOperation: Connection check at https://[***scrubbed***]: Operation finished with HTTP status code -1 (success)
11-17 10:59:43.044 16702 16743 D GetServerInfoOperation: Trying empty authorization to detect authentication method
11-17 10:59:43.047 16702 16743 D OwnCloudClient #0: REQUEST HEAD /remote.php/webdav/
11-17 10:59:43.336 16702 16743 I AuthChallengeProcessor: basic authentication scheme selected
11-17 10:59:43.337 16702 16743 I HttpMethodDirector: No credentials available for BASIC 'Cartesian Theatre'@[***scrubbed***]:443
11-17 10:59:43.338 16702 16743 D ExistenceCheckRemoteOperation: Existence check for https://[***scrubbed***]/remote.php/webdav/ targeting for  existence finished with HTTP status 401(FAIL)
11-17 10:59:43.338 16702 16743 D DetectAuthenticationMethodOperation: Authentication method found: BASIC_HTTP_AUTH
11-17 10:59:43.384 16702 16743 D OperationsService: Called 1 listeners
11-17 10:59:43.384 16702 16743 D OperationsService: Stopping after command with id 4
11-17 10:59:43.388 16702 18422 D OwnCloudClient #2: Creating OwnCloudClient
11-17 10:59:43.389 16702 18422 D OwnCloudClient #2: REQUEST HEAD /remote.php/webdav/
11-17 10:59:44.512  1550  1769 D bt_btif : BTHF: device_status_notification
11-17 10:59:44.513  1550  1739 D bt_btif : AG evt (hdl 0x0001): State 2, Event 0x0506
11-17 10:59:44.513  1550  1739 D bt_btif : bta_ag_hfp_result : res = 5
11-17 10:59:44.513  1550  1739 D bt_btif : AG evt (hdl 0x0001): State 2, Event 0x0506
11-17 10:59:44.513  1550  1739 D bt_btif : bta_ag_hfp_result : res = 5
11-17 10:59:44.513  1550  1739 D bt_btif : AG evt (hdl 0x0001): State 2, Event 0x0506
11-17 10:59:44.513  1550  1739 D bt_btif : bta_ag_hfp_result : res = 5
11-17 10:59:44.514  1550  1739 D bt_btif : AG evt (hdl 0x0001): State 2, Event 0x0506
11-17 10:59:44.514  1550  1739 D bt_btif : bta_ag_hfp_result : res = 5
11-17 10:59:46.521 16702 18422 D ExistenceCheckRemoteOperation: Existence check for https://[***scrubbed***]/remote.php/webdav/ targeting for  existence finished with HTTP status 200
11-17 10:59:46.524 16702 18422 D OwnCloudClient #2: REQUEST GET /ocs/v1.php/cloud/user
11-17 10:59:49.647  4257  3685 W WebSocketConnection: Sending keep alive...
11-17 10:59:49.661  4257  3685 W RealtimeSleepTimer: Setting alarm to wake up in 55000ms.
11-17 10:59:49.879  4257  3675 W WebSocketConnection: WSC onMessage()
11-17 10:59:49.879  4257  3675 W WebSocketConnection: Message Type: 2
11-17 10:59:52.411 16702 16702 D AuthenticatorActivity: Successful access - time to save the account
11-17 10:59:52.414  1900 26337 W AccountManagerService: insertAccountIntoDatabase: Account {name=[***scrubbed***]@[***scrubbed***], type=nextcloud}, skipping since the account already exists
11-17 10:59:52.430  1900  2401 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@94bb3b8 attribute=null, token = android.os.BinderProxy@cab0841
11-17 10:59:52.432 16702 16702 D AuthenticatorActivity: onPause() ending
11-17 10:59:52.444  1900 12271 I ActivityManager: START u0 {act=RESTART flg=0x4000000 cmp=com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity} from uid 10112 on display 0
11-17 10:59:52.448  1900  8224 I ActivityManager: moveTaskToBack: TaskRecord{e4dc591 #246 A=com.nextcloud.client U=0 StackId=1 sz=2}
11-17 10:59:52.484 16702 16702 V BaseActivity: onRestart() start
11-17 10:59:52.503  3016  3107 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
11-17 10:59:52.503  3016  3107 I OpenGLRenderer: Initialized EGL, version 1.4
11-17 10:59:52.503  3016  3107 D OpenGLRenderer: Swap behavior 1
11-17 10:59:52.504 16702 18457 D ExternalLinks: links disabled
11-17 10:59:52.537 16702 16702 V BaseActivity: onRestart() end
11-17 10:59:52.537 16702 16702 D FileDisplayActivity: onStart() starting
11-17 10:59:52.542 16702 16702 V FileDisplayActivity: onResume() start
11-17 10:59:52.542 16702 16702 D FileDisplayActivity: onResume() starting
11-17 10:59:52.554 16702 18462 D ExternalLinks: links disabled
11-17 10:59:52.614 16702 16702 V FileDisplayActivity: onResume() end
11-17 10:59:52.616 16702 16702 V FileDisplayActivity: onPause() start
11-17 10:59:52.618 16702 16702 D FileDisplayActivity: onPause() ending
11-17 10:59:52.619 16702 16702 V FileDisplayActivity: onPause() end
11-17 10:59:52.619 16702 16702 V BaseActivity: onNewIntent() start
11-17 10:59:52.620 16702 16702 V BaseActivity: onNewIntent() stop
11-17 10:59:52.624  1900  5056 I ActivityManager: START u0 {act=RESTART flg=0x4000000 cmp=com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity} from uid 10112 on display 0
11-17 10:59:52.625  1900  5056 W ActivityManager: startActivity called from finishing ActivityRecord{d94af44 u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity t246 f}; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { act=RESTART flg=0x4000000 cmp=com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity }
11-17 10:59:52.643  1900  1919 W InputMethodManagerService: Focus gain on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@c57108c (uid=10029 pid=3016)
11-17 10:59:52.644 16702 16702 V FileDisplayActivity: onResume() start
11-17 10:59:52.644 16702 16702 D FileDisplayActivity: onResume() starting
11-17 10:59:52.693 16702 16702 V FileDisplayActivity: onResume() end
11-17 10:59:52.695 16702 16702 V FileDisplayActivity: onPause() start
11-17 10:59:52.700 16702 16702 D FileDisplayActivity: onPause() ending
11-17 10:59:52.700 16702 16702 V FileDisplayActivity: onPause() end
11-17 10:59:52.701 16702 16702 D FileDisplayActivity: onStop() ending
11-17 10:59:52.807 16702 16714 I AccountAuthenticator: Adding account with type nextcloud and auth token null
11-17 10:59:52.824  1900  5057 I ActivityManager: START u0 {flg=0x10800004 cmp=com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity (has extras)} from uid 10112 on display 0
11-17 10:59:52.847 16702 16702 V FileDisplayActivity: onCreate() start
11-17 10:59:52.849 16702 16702 D FileDisplayActivity: onCreate(Bundle) starting
11-17 10:59:52.870 16702 16714 I AccountAuthenticator: Adding account with type nextcloud and auth token null
11-17 10:59:52.874  1900  5056 I ActivityManager: START u0 {flg=0x10800004 cmp=com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity (has extras)} from uid 10112 on display 0
11-17 10:59:52.901 16702 16702 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
11-17 10:59:52.974 16702 16702 D FileDisplayActivity: onStart() starting
11-17 10:59:52.991 16702 18470 D ExternalLinks: links disabled
11-17 10:59:53.014 16702 16702 E FileDisplayActivity: Access to unexisting list of files fragment!!
11-17 10:59:53.017 16702 16702 V FileDisplayActivity: onResume() start
11-17 10:59:53.017 16702 16702 D FileDisplayActivity: onResume() starting
11-17 10:59:53.018 16702 16702 I OCFileListFragment: onAttach
11-17 10:59:53.023 16702 16702 I OCFileListFragment: onCreateView() start
11-17 10:59:53.023 16702 16702 D ExtendedListFragment: onCreateView
11-17 10:59:53.048 16702 16707 I art     : Do full code cache collection, code=106KB, data=125KB
11-17 10:59:53.051 16702 16707 I art     : Starting a blocking GC JitCodeCache
11-17 10:59:53.052 16702 16707 I art     : After code cache collection, code=89KB, data=87KB
11-17 10:59:53.086 16702 16702 I OCFileListFragment: onCreateView() end
11-17 10:59:53.086 16702 16702 I OCFileListFragment: onActivityCreated() start
11-17 10:59:53.144 16702 16702 V FileDisplayActivity: onResume() end
11-17 10:59:53.159 16702 16702 D FileDisplayActivity: onDestroy() ending
11-17 10:59:53.164 16702 16707 I art     : Do partial code cache collection, code=92KB, data=91KB
11-17 10:59:53.168 16702 16707 I art     : After code cache collection, code=92KB, data=91KB
11-17 10:59:53.168 16702 16707 I art     : Increasing code cache capacity to 512KB
11-17 10:59:53.180 16702 16702 D AuthenticatorActivity: onStop() ending
11-17 10:59:53.182 16702 16702 D AuthenticatorActivity: onDestroy() ending
11-17 10:59:53.215 16702 16739 E chromium: [ERROR:gl_context_virtual.cc(39)] Trying to make virtual context current without decoder.
11-17 10:59:53.257 16702 16713 I art     : Background sticky concurrent mark sweep GC freed 50680(3MB) AllocSpace objects, 208(4MB) LOS objects, 31% free, 16MB/24MB, paused 9.094ms total 116.699ms
11-17 10:59:53.338  1900  1940 W ActivityManager: Activity pause timeout for ActivityRecord{f6e1c0b u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity t247}
11-17 10:59:53.356 16702 16702 V FileDisplayActivity: onPause() start
11-17 10:59:53.368 16702 16702 D FileDisplayActivity: onPause() ending
11-17 10:59:53.368 16702 16702 V FileDisplayActivity: onPause() end
11-17 10:59:53.369 16702 16702 D FileActivity: Operations service connected
11-17 10:59:53.370 16702 16702 D FileDisplayActivity: Download service connected
11-17 10:59:53.370 16702 16702 D FileDisplayActivity: Upload service connected
11-17 10:59:53.389 16702 16702 E ActivityThread: Activity com.owncloud.android.authentication.AuthenticatorActivity has leaked ServiceConnection com.owncloud.android.authentication.AuthenticatorActivity$OperationsServiceConnection@a0748 that was originally bound here
11-17 10:59:53.389 16702 16702 E ActivityThread: android.app.ServiceConnectionLeaked: Activity com.owncloud.android.authentication.AuthenticatorActivity has leaked ServiceConnection com.owncloud.android.authentication.AuthenticatorActivity$OperationsServiceConnection@a0748 that was originally bound here
11-17 10:59:53.389 16702 16702 E ActivityThread: 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1336)
11-17 10:59:53.389 16702 16702 E ActivityThread: 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1231)
11-17 10:59:53.389 16702 16702 E ActivityThread: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1450)
11-17 10:59:53.389 16702 16702 E ActivityThread: 	at android.app.ContextImpl.bindService(ContextImpl.java:1422)
11-17 10:59:53.389 16702 16702 E ActivityThread: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
11-17 10:59:53.389 16702 16702 E ActivityThread: 	at com.owncloud.android.authentication.AuthenticatorActivity.onResume(AuthenticatorActivity.java:1021)
11-17 10:59:53.389 16702 16702 E ActivityThread: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
11-17 10:59:53.389 16702 16702 E ActivityThread: 	at android.app.Activity.performResume(Activity.java:6788)
11-17 10:59:53.389 16702 16702 E ActivityThread: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3431)
11-17 10:59:53.389 16702 16702 E ActivityThread: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3494)
11-17 10:59:53.389 16702 16702 E ActivityThread: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
11-17 10:59:53.389 16702 16702 E ActivityThread: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-17 10:59:53.389 16702 16702 E ActivityThread: 	at android.os.Looper.loop(Looper.java:154)
11-17 10:59:53.389 16702 16702 E ActivityThread: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
11-17 10:59:53.389 16702 16702 E ActivityThread: 	at java.lang.reflect.Method.invoke(Native Method)
11-17 10:59:53.389 16702 16702 E ActivityThread: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
11-17 10:59:53.389 16702 16702 E ActivityThread: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
11-17 10:59:53.390  1900  1920 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@2269f40
11-17 10:59:53.391 16702 16702 E ActivityThread: Activity com.owncloud.android.authentication.AuthenticatorActivity has leaked ServiceConnection com.owncloud.android.authentication.AuthenticatorActivity$OperationsServiceConnection@560d21e that was originally bound here
11-17 10:59:53.391 16702 16702 E ActivityThread: android.app.ServiceConnectionLeaked: Activity com.owncloud.android.authentication.AuthenticatorActivity has leaked ServiceConnection com.owncloud.android.authentication.AuthenticatorActivity$OperationsServiceConnection@560d21e that was originally bound here
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1336)
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1231)
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1450)
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at android.app.ContextImpl.bindService(ContextImpl.java:1422)
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at com.owncloud.android.authentication.AuthenticatorActivity.onResume(AuthenticatorActivity.java:1021)
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at android.app.Activity.performResume(Activity.java:6788)
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3431)
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3494)
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2757)
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at android.os.Looper.loop(Looper.java:154)
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at java.lang.reflect.Method.invoke(Native Method)
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
11-17 10:59:53.391 16702 16702 E ActivityThread: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
11-17 10:59:53.392  1900  2971 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@c656d4b
11-17 10:59:53.394 16702 16702 E ActivityThread: Activity com.owncloud.android.authentication.AuthenticatorActivity has leaked ServiceConnection com.owncloud.android.authentication.AuthenticatorActivity$OperationsServiceConnection@bea6306 that was originally bound here
11-17 10:59:53.394 16702 16702 E ActivityThread: android.app.ServiceConnectionLeaked: Activity com.owncloud.android.authentication.AuthenticatorActivity has leaked ServiceConnection com.owncloud.android.authentication.AuthenticatorActivity$OperationsServiceConnection@bea6306 that was originally bound here
11-17 10:59:53.394 16702 16702 E ActivityThread: 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1336)
11-17 10:59:53.394 16702 16702 E ActivityThread: 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1231)
11-17 10:59:53.394 16702 16702 E ActivityThread: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1450)
11-17 10:59:53.394 16702 16702 E ActivityThread: 	at android.app.ContextImpl.bindService(ContextImpl.java:1422)
11-17 10:59:53.394 16702 16702 E ActivityThread: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
11-17 10:59:53.394 16702 16702 E ActivityThread: 	at com.owncloud.android.authentication.AuthenticatorActivity.onResume(AuthenticatorActivity.java:1021)
11-17 10:59:53.394 16702 16702 E ActivityThread: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
11-17 10:59:53.394 16702 16702 E ActivityThread: 	at android.app.Activity.performResume(Activity.java:6788)
11-17 10:59:53.394 16702 16702 E ActivityThread: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3431)
11-17 10:59:53.394 16702 16702 E ActivityThread: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3494)
11-17 10:59:53.394 16702 16702 E ActivityThread: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
11-17 10:59:53.394 16702 16702 E ActivityThread: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-17 10:59:53.394 16702 16702 E ActivityThread: 	at android.os.Looper.loop(Looper.java:154)
11-17 10:59:53.394 16702 16702 E ActivityThread: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
11-17 10:59:53.394 16702 16702 E ActivityThread: 	at java.lang.reflect.Method.invoke(Native Method)
11-17 10:59:53.394 16702 16702 E ActivityThread: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
11-17 10:59:53.394 16702 16702 E ActivityThread: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
11-17 10:59:53.394  1900 26337 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@b74981
11-17 10:59:53.521 16702 16702 D AuthenticatorActivity: onCreate(Bundle) starting
11-17 10:59:53.528  1900 12273 I ActivityManager: START u0 {cmp=com.nextcloud.client/com.owncloud.android.ui.activity.FirstRunActivity} from uid 10112 on display 0
11-17 10:59:53.577 16702 16702 I TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
11-17 10:59:53.593 16702 16702 I TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
11-17 10:59:53.598 16702 16702 I TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
11-17 10:59:53.603 16702 16702 I TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
11-17 10:59:53.610 16702 16702 I TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
11-17 10:59:53.618 16702 16702 D AuthenticatorActivity: onStart() starting
11-17 10:59:53.620 16702 16702 D AuthenticatorActivity: onNewIntent()
11-17 10:59:53.621 16702 16702 D AuthenticatorActivity: onResume() starting
11-17 10:59:53.665 16702 16702 D AndroidRuntime: Shutting down VM
11-17 10:59:53.666 16702 16702 E AndroidRuntime: FATAL EXCEPTION: main
11-17 10:59:53.666 16702 16702 E AndroidRuntime: Process: com.nextcloud.client, PID: 16702
11-17 10:59:53.666 16702 16702 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
11-17 10:59:53.666 16702 16702 E AndroidRuntime: 	at com.owncloud.android.utils.ThemeUtils.primaryColor(ThemeUtils.java:116)
11-17 10:59:53.666 16702 16702 E AndroidRuntime: 	at com.owncloud.android.utils.ThemeUtils.primaryColor(ThemeUtils.java:102)
11-17 10:59:53.666 16702 16702 E AndroidRuntime: 	at com.owncloud.android.ui.fragment.ExtendedListFragment$6.run(ExtendedListFragment.java:653)
11-17 10:59:53.666 16702 16702 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
11-17 10:59:53.666 16702 16702 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-17 10:59:53.666 16702 16702 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-17 10:59:53.666 16702 16702 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
11-17 10:59:53.666 16702 16702 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-17 10:59:53.666 16702 16702 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
11-17 10:59:53.666 16702 16702 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

I have the client installed on internal memory and not an external SD card. I am using LineageOS (Android 7.1.2).

**Comment by tobiasKaminsky** [comment] 2019-01-18 08:35
Closing as duplicate of #3151

**Closed by tobiasKaminsky** 2019-01-18 08:35 UTC
Labels: bug
