### ISSUE TITLE
Crash on restoring old version in preview

### ISSUE THREAD

**Issue by NobleWolf** [nextcloud/android#5801] opened 2020-04-03 16:36 UTC
### Steps to reproduce
1. Open app
2. Go to Photos
3. View several photos in full screen
4. Open a photo detail menu
5. Restore older version
6. Error occurs (Nextcloud does seem to restore the older version.

### Expected behaviour
- The app should not crash

### Actual behaviour
- the app crashes and most be restarted

### Can you reproduce this problem on https://try.nextcloud.com?
- Not applicable as this is an error in the Android app.

### Environment data
Android version: 10

Device model: pixel 3a

Stock or customized system: stock

Nextcloud app version: 3.11.0

Nextcloud server version: Nextcloud 18.0.3 Build:2020-03-31T23:01:59+00:00 b2c616cc607c9f9894ec3a92f620588f4a9d0e37

### Logs
####Android App Log
************ CAUSE OF ERROR ************
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:219)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:357)
	at java.lang.Thread.run(Thread.java:919)
```
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: sargo
Model: Pixel 3a
Id: QQ2A.200305.002
Product: sargo

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 6138846

#### Web server error log
```
Will update when I am at computer, currently on smartphone.
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Will update when I am at computer, currently on smartphone.
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by joshtrichards** [comment] 2023-10-09 00:02
Duplicate of #11207

Fixed in #11410

Released in v3.26.

**Closed by joshtrichards** 2023-10-09 00:02 UTC
Labels: bug, approved
