### ISSUE TITLE
green sync icon on folder icon

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#8000] opened 2021-02-16 20:46 UTC
having already implemented a blue icon that indicates a synchronization phase on folder icons, why not put a green icon when the synchronization ends as happens on files, to understand which folders have been completely synchronized?

![Screenshot_20210216-214519_Nextcloud](https://user-images.githubusercontent.com/35575744/108119636-61092680-70a0-11eb-8025-2c5e555ecc2b.jpg)

**Comment by TheYsconator** [comment] 2021-07-15 11:33
I second this request; it's currently practically impossible to see what directories are synced (successfully and completely).

**Comment by joshtrichards** [comment] 2023-12-14 16:17
Duplicate of #6785

**Closed by joshtrichards** 2023-12-14 16:17 UTC
Labels: enhancement, design, feature: sync and upload
