### ISSUE TITLE
Error random

### ISSUE THREAD

**Issue by Manuel1948** [nextcloud/android#13985] opened 2024-11-08 17:38 UTC
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.ui.activity.FileActivity.checkInternetConnection()' on a null object reference
    at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:982)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onOpenFileIntent(FileDisplayActivity.java:580)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onNewIntent(FileDisplayActivity.java:519)
    at android.app.Activity.performNewIntent(Activity.java:8413)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1503)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1516)
    at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:4046)
    at android.app.ActivityThread.handleNewIntent(ActivityThread.java:4053)
    at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:240)
    at android.os.Looper.loop(Looper.java:351)
    at android.app.ActivityThread.main(ActivityThread.java:8377)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OP515BL1`
* Model: `DN2103`
* Id: `TP1A.220905.001`
* Product: `DN2103EEA`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `R.19d85e1-1`

**Comment by joshtrichards** [comment] 2024-11-09 16:35
Duplicate of #13188

**Closed by joshtrichards** 2024-11-09 16:35 UTC
