### ISSUE TITLE
Can't login to my self-hosted Nextcloud server with my own self-signed SSL certificate

### ISSUE THREAD

**Issue by leap0x7b** [nextcloud/android#12197] opened 2023-11-25 00:25 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Create a self-signed key for my web server
```bash
openssl req -x509 -nodes -days 365 -newkey rsa:4096 -keyout /etc/ssl/nextcloud-selfsigned.pem -out /etc/ssl/nextcloud-selfsigned.pem
```
3. Set up Nextcloud
4. Add the self-signed certificate to Android
5. Login to your self-hosted instance

### Expected behaviour

Should log me in to the app.

### Actual behaviour

Just crashes for some reason.

### Android version

6.0.1

### Device brand and model

vivo 1606

### Stock or custom OS?

Stock

### Nextcloud android app version

3.25.0

### Nextcloud server version

27.1.3

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" android.util.AndroidRuntimeException: requestFeature() must be called before adding content
    at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:352)
    at android.app.Dialog.requestWindowFeature(Dialog.java:1126)
    at com.owncloud.android.ui.dialog.SslUntrustedCertDialog.onCreateDialog(SslUntrustedCertDialog.java:168)
    at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665)
    at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579)
    at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1755)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1901)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1819)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1762)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5619)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30250090`
* Build flavor: `generic`

### Device information
* Brand: `vivo`
* Device: `1606`
* Model: `vivo 1606`
* Id: `MMB29M`
* Product: `1606`

### Firmware
* SDK: `23`
* Release: `6.0.1`
* Incremental: `eng.compiler.20190105.211334`

**Comment by joshtrichards** [comment] 2023-11-25 14:50
Hi @leap0x7b - Thanks for your report. Looks like a duplicate of #11677. Let's consolidate tracking over there. I encourage you to upvote for prioritization - and subscribe if you wish to monitor.

**Closed by joshtrichards** 2023-11-25 14:50 UTC
Labels: bug, performance, connectivity
