### ISSUE TITLE
NC 3.22.1 crashes on Pixel 6 Pro running Android 13 after entering login URL

### ISSUE THREAD

**Issue by lightaffaire** [nextcloud/android#10879] opened 2022-10-21 12:13 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. install 3.22.1 on pixel 6 pro 256GB running Android 13 (update from 3.20 happened yesterday)
2. start app and enter login url  "https://site:port" and press enter
3. screen appears with Loading... and a crash traceback

did not happen running 3.20 on same phone and os.

### Expected behaviour

should login

### Actual behaviour

1. install 3.22.1 on pixel 6 pro 256GB running Android 13 (update from 3.20 happened yesterday)
2. start app and enter login url  "https://site:port" and press enter
3. screen appears with Loading... and a crash traceback

### Android version

13

### Device brand and model

pixel 6 pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.1

### Nextcloud server version

24  worked fine with 3.20 client for months

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.LinearLayout com.owncloud.android.databinding.SslUntrustedCertLayoutBinding.getRoot()' on a null object reference
    at com.owncloud.android.ui.dialog.SslUntrustedCertDialog.onCreateDialog(SslUntrustedCertDialog.java:173)
    at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665)
    at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579)
    at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1752)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7898)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220190`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `raven`
* Model: `Pixel 6 Pro`
* Id: `TP1A.221005.002`
* Product: `raven`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `9012097`

**Comment by AlvaroBrey** [comment] 2022-10-21 12:45
Duplicate of #10868

**Closed by AlvaroBrey** 2022-10-21 12:45 UTC
Labels: bug
