### ISSUE TITLE
Was updating the remote folder for auto uploads.

### ISSUE THREAD

**Issue by Phenix51** [nextcloud/android#14077] opened 2024-11-21 23:26 UTC
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at com.owncloud.android.ui.adapter.OCFileListAdapter.limitToPersonalFiles(OCFileListAdapter.java:1074)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:741)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1359)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1308)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1297)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onActivityCreated(OCFileListFragment.java:422)
    at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3156)
    at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:619)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
    at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3042)
    at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2952)
    at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
    at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
    at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
    at com.owncloud.android.ui.activity.DrawerActivity.onStart(DrawerActivity.java:1203)
    at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:239)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1701)
    at android.app.Activity.performStart(Activity.java:9045)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4073)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:270)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:250)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:222)
    at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:107)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8705)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `komodo`
* Model: `Pixel 9 Pro XL`
* Id: `AP3A.241105.008`
* Product: `komodo`

### Firmware
* SDK: `35`
* Release: `15`
* Incremental: `12485168`

**Comment by ZetaTom** [comment] 2024-11-22 09:18
Thank you for reporting this issue. This problem should be resolved by #12930 and #13377. The first release version to include these fixes should be version 3.29.3.

Duplicate of #12908

**Closed by ZetaTom** 2024-11-22 09:18 UTC
