### ISSUE TITLE
Just start from PlayMarket try login, crash

### ISSUE THREAD

**Issue by lexxai** [nextcloud/android#4561] opened 2019-09-26 16:20 UTC
### Actual behaviour
- Try login

### Expected behaviour
- Must be enter login menu to site
 
### Steps to reproduce
1. Play Market
2. Run
3. Login

### Environment data
Android version:6

Device model: meizu 5s

Stock or customized system:

Nextcloud app version:ID: com.nextcloud.client
Version: 30080090

Nextcloud server version:undefined

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
	at android.widget.Editor.updateCursorPositionMz(Editor.java:6986)
	at android.widget.Editor.updateCursorsPositions(Editor.java:1766)
	at android.widget.TextView.getUpdatedHighlightPath(TextView.java:5703)
	at android.widget.TextView.onDraw(TextView.java:5896)
	at com.owncloud.android.ui.components.CustomEditText.onDraw(CustomEditText.java:71)
	at android.view.View.draw(View.java:16539)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.draw(View.java:16551)
	at com.google.android.material.textfield.TextInputLayout.draw(TextInputLayout.java:1577)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.draw(View.java:16551)
	at android.widget.ScrollView.draw(ScrollView.java:1745)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15484)
	at android.view.View.draw(View.java:16293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2839)
	at android.view.View.draw(View.java:16551)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2820)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:286)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:292)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:327)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3056)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2860)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2469)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1342)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6824)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:896)
	at android.view.Choreographer.doCallbacks(Choreographer.java:698)
	at android.view.Choreographer.doFrame(Choreographer.java:633)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:882)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6009)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:840)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:730)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Meizu
Device: M5s
Model: M5s
Id: MRA58K
Product: meizu_M5s

************ FIRMWARE ************
SDK: 23
Release: 6.0
Incremental: 1551951703

```

**Comment by tobiasKaminsky** [comment] 2019-10-02 11:31
I fear this is some problem with this specific device, so we cannot really track this down…

**Comment by AndyScherzinger** [comment] 2019-10-02 11:38
@tobiasKaminsky what happens in
`com.owncloud.android.ui.components.CustomEditText.onDraw(CustomEditText.java:71)`?

**Comment by tobiasKaminsky** [comment] 2019-10-02 11:45
https://github.com/nextcloud/android/blob/master/src/main/java/com/owncloud/android/ui/components/CustomEditText.java#L71

Nothing spectacular.

**Comment by AndyScherzinger** [comment] 2019-10-02 11:57
Hmm, strange... That shouldn't lead to a crash, since it is Plattform code. Canvas can be null but since that is allowed Android should be able to deal with it. Cause then this is rather a device specific bug in the device's OEM Android version :/

**Comment by ezaquarii** [comment] 2019-10-02 21:10
@AndyScherzinger I checked the source code and defintely the superclass does not check for `null`, ie. the canvas is expected to be `@NonNull` (annotation-speaking).

Hard to say why `onDraw()` is called with `null` canvas tho.

**Comment by tobiasKaminsky** [comment] 2019-10-08 13:30
Duplicate of #4619

**Closed by tobiasKaminsky** 2019-10-08 13:30 UTC
Labels: bug

**Comment by lexxai** [comment] 2019-10-12 15:37
on new version 3.8.1 all OK!
