### ISSUE TITLE
File timestamps are not preserved on upload anymore

### ISSUE THREAD

**Issue by danielb42** [nextcloud/android#10900] opened 2022-10-23 22:11 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Upload a file with Nextcloud/Android v3.22.1.

### Expected behaviour

Timestamps of a file (i.e. creation date/time) should be preserved when uploading.

### Actual behaviour

Since the recent update, files uploaded to the server have the upload time set as creation timestamp, erasing the original creation metadata. This is _bad_, and only one of the more innocuous consequences is having "sort by newest" display files uploaded at the same time in a shuffled way..

### Android version

12

### Device brand and model

Galaxy A41

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.1

### Nextcloud server version

24.0.6

### Using a reverse proxy?

Yes

**Comment by Byter3** [comment] 2022-10-24 06:15
I concuer, I want to bump this too. It just caused me hedache with around 500 images now all over the timeline.

**Comment by AlvaroBrey** [comment] 2022-10-24 16:14
I cannot seem to reproduce this; the files I upload retain their creation timestamp as reported by the server. Can you tell me exact steps (as in, how are you checking the timestamp, etc)?

**Comment by Byter3** [comment] 2022-10-24 16:27
@AlvaroBrey 

I have set uo Nc client on my phone to auto upload, the photos taken with the phone, but only when the device is on Wifi. So in the evening, when I got back home, it started upload the photos. Now my photos are all over the place in terms of time, if I check them on Nextcloud webgui, there is no order to the photos. ie, pictures taken in the dark is behind pictures when the sun was still up, so it indivisble, that the timestamps got confused.
Also a I had tremendeaus issu with the new client. While it started the auto upload, the client crashed multiple times. And restarted the upload multiple times. It wasn't visible which file is currently being uploaded. The progress bar in the notification area poped up and dissappeared in fraction of a second. I never seen, such a strange behaviour with older version of the Nextcloud clien app on my phone.

So maybe this strange behaviour causing the time stamp issue(?)

Also I just wan't to flag it here as well since you closed my other topic, that the new version of nextcloud app, drains an ungodly amount of my battery. This wasn't the case with older version of the app.

**Comment by danielb42** [comment] 2022-10-24 16:30
Hi @AlvaroBrey, sure, but I'm afraid there are no special steps involved. My NC webinterface, and also the files downloaded through NC desktop client to my desktop just carry the upload timestamp now instead of the real creation timestamp.. 

So, for example: Yesterday I took a bunch of photos outside, say between 14:00 und 17:00. Those were not uploaded immediately as "WiFi only" is checked. When I got home at 18:23 and my phone connected to my WiFi, all the pics were uploaded through regular auto-upload, nothing special. Up to version 3.22.1, each file would have the original creation timestamp (anything between 14-17h) and this would show correctly in NC webinterface and also when downloading the files onto a computer. And now.. all files pretend to be created at 18:23, as shown in webinterface as well as after downloading.

**Comment by AlvaroBrey** [comment] 2022-10-24 16:35
Ok, so both of you are using autoupload and uploading later when connected to wifi, that gives me some clues. Can you check if a manually uploaded file preserves timestamp correctly?

**Comment by danielb42** [comment] 2022-10-24 16:39
Negative, manual uploads carry upload timestamp as well.

**Comment by danielb42** [comment] 2022-10-24 16:46
On server.. original timestamp of the file is as indicated in its filename (Apr 2020), manual upload was (today) 18:38.

```
# stat 20200704_175548.jpg
  File: 20200704_175548.jpg
  Size: 2976631         Blocks: 5816       IO Block: 4096   regular file
Device: fd02h/64770d    Inode: 5514201     Links: 1
Access: (0644/-rw-r--r--)  Uid: (   33/www-data)   Gid: (   33/www-data)
Access: 2022-10-24 18:38:31.777826633 +0200
Modify: 2022-10-24 18:38:28.000000000 +0200
Change: 2022-10-24 18:38:31.733827167 +0200
 Birth: -
```

**Comment by AlvaroBrey** [comment] 2022-10-24 20:20
Dang, that makes it harder for me, as I was testing manual uploads and they were preserving the correct timestamps.

**Comment by AlvaroBrey** [comment] 2022-10-24 20:22
Does the nextcloud app have the All Files permission, or does it have the media read-only one?

**Comment by andyxheli** [comment] 2022-10-24 20:31
@AlvaroBrey i can also confirm this. Auto upload or no auto upload same issue.  When i click in update files and i select a few photos that i took yesterday once the files upload to the server the photos say modified today at the time I uploaded the files but they should not say that it should keep the date and time when the file was taken on the phone etc. I tired the same steps via iOS nextcloud app and it kept the time and data

**Comment by danielb42** [comment] 2022-10-24 21:39
> Does the nextcloud app have the All Files permission, or does it have the media read-only one?

It has All Files permission.

**Comment by Byter3** [comment] 2022-11-01 03:20
> Does the nextcloud app have the All Files permission, or does it have the media read-only one?

It has all the permissions it can get.
Also didnát mentioned the phone: Samsunbg Galaxy S21 Ultra, Android 12

**Comment by danielb42** [comment] 2022-11-01 09:28
btw, here's a quirky little bash snippet to fix the timestamps according to the filenames.
Assuming photos are named `YYYYMMDD_hhmmss.jpg`, as Samsung DCIM does for example.

```
cd MyNextcloudPhotoFolder

for PIC in $(ls -1 ????????_??????.jpg); do
  Y=${PIC:0:4}
  M=${PIC:4:2}
  D=${PIC:6:2}
  h=${PIC:9:2}
  m=${PIC:11:2}
  s=${PIC:13:2}
  touch -m -t $Y$M$D$h$m.$s $PIC
done
```

**Comment by hbfrank** [comment] 2022-11-07 09:47
This bug is caused by the new (wrong) logic  of upload action, i.e., make a copy of the local file and then upload the **copy** whose lastModificationTimestamp is of the time-of-copying.

--------------------------------------------------------------------

BTW, the OC_X_OC_MTIME_HEADER of upload file in [library/src/main/java/com/owncloud/android/lib/resources/files/ChunkedFileUploadRemoteOperation.java](https://github.com/nextcloud/android-library/blob/b506a7cd33a1be2dd57ac0087778590015870b0e/library/src/main/java/com/owncloud/android/lib/resources/files/ChunkedFileUploadRemoteOperation.java#L210):
```
moveMethod.addRequestHeader(OC_X_OC_MTIME_HEADER, String.valueOf(file.lastModified() / 1000));
```
is different from in its super class [library/src/main/java/com/owncloud/android/lib/resources/files/UploadFileRemoteOperation.java](https://github.com/nextcloud/android-library/blob/b506a7cd33a1be2dd57ac0087778590015870b0e/library/src/main/java/com/owncloud/android/lib/resources/files/UploadFileRemoteOperation.java#L226).
```
putMethod.addRequestHeader(OC_X_OC_MTIME_HEADER, lastModificationTimestamp);
```
so this bug only appears on files uploaded by ChunkedFileUploadRemoteOperation, i.e., file size larger than the CHUNK_SIZE_WIFI (10240000 bytes) or CHUNK_SIZE_MOBILE (1024000 bytes).

**Comment by AlvaroBrey** [comment] 2022-11-08 12:30
Thanks for the research @hbfrank ! That timestamp is indeed incorrect.

However, I still can't reproduce this even with chunked files; I guess it's a matter of whether the specific device changes the modification date when copying the file or not.

In https://github.com/nextcloud/android/pull/11007, there should soon be a QA APK with this patched. Can any of the affected users use it to verify it's fixed? thanks!

**Comment by AlvaroBrey** [comment] 2022-11-09 17:05
Ping for affected users. APK is here: https://github.com/nextcloud/android/pull/11007#issuecomment-1307141176

Since I can't reproduce it, and the bug in the code was found and patched, if I don't see any reports of the contrary I'll consider this fixed when that PR is merged.

**Comment by andyxheli** [comment] 2022-11-09 17:14
@AlvaroBrey Just tested the APK and it looks good to me. If you use Signal on your phone setup backups to a nextlcoud folder and i think you'll be able to reproduce it. Every time my Signal app dose a back i get the error logs i changed  to folder dir to point to the QA app and did a backup no errors under server logs

**Comment by danielb42** [comment] 2022-11-09 17:34
@AlvaroBrey looks good!

```
# stat 20221109_182511.jpg
  File: 20221109_182511.jpg
  Size: 1719793         Blocks: 3360       IO Block: 4096   regular file
Device: fd00h/64768d    Inode: 7209167     Links: 1
Access: (0644/-rw-r--r--)  Uid: (   33/www-data)   Gid: (   33/www-data)
Access: 2022-11-09 18:30:21.774251583 +0100
Modify: 2022-11-09 18:25:15.000000000 +0100
Change: 2022-11-09 18:30:21.738252122 +0100

```

Everything (timestamp-wise) as it should be.

**Closed** 2022-11-16 11:37 UTC
Labels: bug
