### ISSUE TITLE
Crash when click Open with...

### ISSUE THREAD

**Issue by bpruneau** [nextcloud/android#13030] opened 2024-05-22 03:19 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open Nextcloud Android app
2. Click on a txt file (Ex: foobar.txt) to open it.
3. Open menu and click "Open with..."

### Expected behaviour

Show list of applications

### Actual behaviour

Crash report

### Android version

11

### Device brand and model

samsung galaxy s9

### Stock or custom OS?

Stock

### Nextcloud android app version

30290090

### Nextcloud server version

27

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Fragment FileActionsBottomSheet{d8a1826} (bd946151-fedc-448f-8a0e-1b9ef6801cd6) not associated with a fragment manager.
    at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:1112)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.dispatchActionClick(FileActionsBottomSheet.kt:299)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.access$dispatchActionClick(FileActionsBottomSheet.kt:50)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$onCreateView$2.invoke(FileActionsBottomSheet.kt:88)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$onCreateView$2.invoke(FileActionsBottomSheet.kt:87)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
    at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
    at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
    at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
    at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
    at com.nextcloud.ui.fileactions.FileActionsViewModel.onClick(FileActionsViewModel.kt:147)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.inflateActionView$lambda$9$lambda$8(FileActionsBottomSheet.kt:281)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.$r8$lambda$uchH_ll8ENOPxscjh3brNAOCY4U(Unknown Source:0)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$$ExternalSyntheticLambda1.onClick(D8$$SyntheticClass:0)
    at android.view.View.performClick(View.java:7448)
    at android.view.View.performClickInternal(View.java:7425)
    at android.view.View.access$3600(View.java:810)
    at android.view.View$PerformClick.run(View.java:28305)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7664)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `star2lte`
* Model: `SM-G965F`
* Id: `RQ3A.211001.001`
* Product: `star2ltexx`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `eng.root.20240506.224558`

**Comment by satvik2131** [comment] 2024-06-12 02:39
there is no option named open with in the android app , can you upload video @bpruneau

**Comment by joshtrichards** [comment] 2024-06-13 13:29
Duplicate of #11701

**Closed by joshtrichards** 2024-06-13 13:29 UTC
Labels: bug
