### ISSUE TITLE
Group folders should have appropriate folder icon in Android app (and not the regular one)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/android#10424] opened 2022-06-21 19:33 UTC
Hi !

### Is your feature request related to a problem? Please describe.
When I am in Nextcloud Files with my web browser, the group folders have a different icon than the other folders, allowing to recognize it. On the other hand, when I go in my folders with my Android application, the icon is the one of a normal folder. 

### Describe the solution you'd like
It would be more consistent and thus better in terms of UI/UX if the folder icon was the same in the Android application as in the web interface.

Web interface with the good group folder icon : 
![gf_icon_web](https://user-images.githubusercontent.com/33763786/174882587-891faeb5-b387-47f3-9d7f-42660a91f1e2.jpg)

Android interface with the wrong regular icon : 
![gf_icon_android](https://user-images.githubusercontent.com/33763786/174882737-d35bca17-7836-45f4-ae69-b5bb34a5c571.jpg)

Best regards,
Jérôme

**Comment by AlvaroBrey** [comment] 2022-06-22 07:24
Duplicate of #10234

**Closed by AlvaroBrey** 2022-06-22 07:24 UTC
Labels: enhancement
