### ISSUE TITLE
No instant Upload under android 7

### ISSUE THREAD

**Issue by niceyyy** [nextcloud/android#225] opened 2016-08-25 10:48 UTC
### Actual behaviour
Instant Upload Feature does not work with Android N (7)
It seems that the app don't recognize new fotos/videos 

### Environment data
Android version: 7.0

Device model: Nexus 5X
Stock or customized system: Stock
Nextcloud app version: 1.2.0
Nextcloud server version: 10.0 beta

### Logs
nothing to see in the logfiles.

**Comment by xraMsamohT** [comment] 2016-08-29 08:01
Duplicate of #110

**Comment by AndyScherzinger** [comment] 2016-08-30 14:40
thus closed. Please track any progress in #110.

**Closed by AndyScherzinger** 2016-08-30 14:40 UTC
