### ISSUE TITLE
Nextcloud Dev 20170705: "Settings" page for Passlock and "Show hidden files" confusion.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#1163] opened 2017-07-05 06:09 UTC
### Actual behaviour
-Tell us what happens

This new release of Nextcloud Dev seems to have a few graphical element being reworked.
One that is confusing is the "Passcode lock" and "Show hidden files" switch graphical representation.
I just can't make sense of the meaning of the gey'ish and darker grey color of the switch.
Which color correspond to the enabled vs disabled?
I am confused.

### Expected behaviour
-Tell us what should happen
A better, more meaningfull color coding stile should be used as not to misinterpret the status of the controls.

### Steps to reproduce
1. Go into "Settings"
2. Go to Details section and toggle the switches.
3. 

### Environment data
Android version:
6.0
Device model: 
LG-D852
Stock or customized system:
Stock
Nextcloud app version:
Nextcloud Dev 20170705

Nextcloud server version:
NC 12

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2017-07-05 07:09
@tobiasKaminsky this one is for you ;)

**Comment by tobiasKaminsky** [comment] 2017-07-05 07:31
The problem is that we cannot theme the preference toggle buttons with any arbitrary color as we can do with the rest. So we are using grey as a fallback for the toggle buttons in preference, and only there ;-)

As we do not change the overall UI/UX I thought it will still be clear what is "on" and what is "off"...

![2017-07-05-090326](https://user-images.githubusercontent.com/5836855/27852803-d4e347f0-6160-11e7-93e2-1719e9f072d0.png)


@jancborchardt @juliushaertl do you have any additional design ideas?

**Comment by mario** [comment] 2017-07-05 07:37
@tobiasKaminsky why not?

https://stackoverflow.com/questions/11253512/change-on-color-of-a-switch

**Comment by mario** [comment] 2017-07-05 07:48
@tobiasKaminsky can we use this?

https://stackoverflow.com/a/25635526

**Comment by tobiasKaminsky** [comment] 2017-07-05 07:50
No, we need to use a SwitchPreference <- TwoStatePreference <- Preference :-/

**Comment by AndyScherzinger** [comment] 2017-07-05 08:06
@tobiasKaminsky this might work https://stackoverflow.com/questions/26466577/apply-tint-to-preferenceactivity-widgets-with-appcompat-v21

**Comment by tobiasKaminsky** [comment] 2017-07-05 11:55
Can you give me a more detailled hint which I shall try? ;-)

**Comment by jancborchardt** [comment] 2017-07-05 12:12
If it’s not possible to theme, maybe we should go even darker, maybe full black (or whatever is used for text color) for the toggle?

**Comment by tobiasKaminsky** [comment] 2017-07-05 13:05
We can try it, but I think that the more important visual hint is if the round button is left (off) or right (on)...

**Comment by AndyScherzinger** [comment] 2017-07-05 16:48
> the more important visual hint is if the round button is left (off) or right (on)...

not for users from the r-t-l space ;)

**Comment by jancborchardt** [comment] 2017-07-06 10:24
Yeah, that is actually the case for anyone:  You don't necessarily know which direction is on and which is off, that's why it has to be unmistakably clear. :)

Let's try going darker or full black - or in the best case color it like @mario referenced above (if possible). :)

**Comment by OlivierS1** [comment] 2017-07-06 15:39
Full black wouldn't be a good idea I think.
I have played with the new color scheme and the text were "Nextcloud Dev" used to appear on the top menu and now being replaced with the slogan did show in black when I used my own string. It was disconcerting. Maybe that was expected due to some settings, but it seemed to me more like of having a bug where font is missing. Didn't like it at all.

**Comment by tobiasKaminsky** [comment] 2017-07-07 05:52
The color of the slogan should change depending on the background color: 
if it is a lighter color -> black
if it is a darker color -> white

![2017-07-07-074915](https://user-images.githubusercontent.com/5836855/27944684-dd5a00b6-62e8-11e7-9898-c629385f87d8.png) ![2017-07-07-074837](https://user-images.githubusercontent.com/5836855/27944691-e85bc0a8-62e8-11e7-9bb3-c474983f2b4f.png)

Please note that the discussion of the color is just only for the preferences screen, not for the entire/rest of the app.

**Comment by AndyScherzinger** [comment] 2017-07-07 07:57
@tobiasKaminsky @jancborchardt shouldn't we rather use the server name?! Our stable app also says Nextcloud and not "your data, your rules" or whatever. In my opinion this should be the server name branding wise... :)

**Comment by mario** [comment] 2017-07-07 07:58
Indeed

**Comment by jancborchardt** [comment] 2017-07-07 13:04
Absolutely, header should use the name, not slogan. The slogan is only used in the web interface really. :)

**Comment by tobiasKaminsky** [comment] 2017-07-10 12:18
> shouldn't we rather use the server name?!

I have changed this.

**Comment by tobiasKaminsky** [comment] 2017-07-11 09:46
It seems that we currently do not support r-t-l at all:
Forced rtl on emulator, left settings, right our app:
![2017-07-11-114353](https://user-images.githubusercontent.com/5836855/28062460-4d05d514-662e-11e7-918f-9e02655b91d5.png) ![2017-07-11-114336](https://user-images.githubusercontent.com/5836855/28062461-4d07b9f6-662e-11e7-8908-b7a08ee6c5d1.png)

I will open up an issue for this.


This is the toggle button with a slightly darker color. 
![2017-07-11-114121](https://user-images.githubusercontent.com/5836855/28062462-4d0daf6e-662e-11e7-9aac-89973b9244ab.png)

I will give the theming of this toggle button one last chance, otherwise we have to stay with this color.

**Comment by AndyScherzinger** [comment] 2017-07-11 10:22
Well, one way to "fix" it would be to revert back to checkboxes in the settings view. @mario changed it to use switches for material design alignment (thanks for also having an eye on material design 👍).  So Pinging you both @tobiasKaminsky 

cc: @jancborchardt

**Comment by AndyScherzinger** [comment] 2017-07-11 10:24
further remark: even GMail uses checkboxes... So I guess it would be still fine to go back to checkboxes and they would have a clear visual state then 💃

**Comment by tobiasKaminsky** [comment] 2017-07-11 10:27
I finally managed it :tada: 

![2017-07-11-122438](https://user-images.githubusercontent.com/5836855/28064259-38690a76-6634-11e7-8e77-c66cc0277195.png)

**Comment by jancborchardt** [comment] 2017-07-13 11:50
Nice work! :)

**Comment by tobiasKaminsky** [comment] 2017-07-14 10:05
Thanks, closing as the PR (#1031)  is also merged :tada:

**Closed by tobiasKaminsky** 2017-07-14 10:05 UTC
Labels: bug, design, pr exists
