### ISSUE TITLE
Introduce UnifiedPush support in f-droid versions of android apps

### ISSUE THREAD

**Issue by resoli** [nextcloud/android#11094] opened 2022-11-25 21:50 UTC
### Is your feature request related to a problem? Please describe.
F-droid versions of the official Nextcloud Android apps does not support push notifications; this is really inconvenient in particular for Talk 

### Describe the solution you'd like
[UnifiedPush](https://unifiedpush.org/) is emerging as a very nice solution, and there is server side support in Nextcloud itself thru [UnifiedPush Provider app in the appstore](https://apps.nextcloud.com/apps/uppush) 

### Additional context
[UnifiedPush support](https://unifiedpush.org/users/apps/) is already provided in F-Droid versions of **Element** (matrix client) and **Tusky** (mastodon client) and they work very well in combination with [NextPush distributor](https://unifiedpush.org/users/distributors/nextpush/) / [UnifiedPush Provider](https://apps.nextcloud.com/apps/uppush)

**Comment by darhma** [comment] 2022-11-25 22:15
For the notifications of the various nextcloud services there is already a solution: https://github.com/Andrewerr/NextcloudServices but I agree that it would not be a bad idea to add support to unifiedpush.org considering that nextpush works very well and if already used it would avoid the need to install an additional app

**Comment by resoli** [comment] 2022-11-25 22:18
Yes, given that [NextcloudServices](https://github.com/Andrewerr/NextcloudServices) does not really push notifications, but a polling ...

**Comment by Zocker1999NET** [comment] 2022-12-16 23:41
I think this one is a duplicate of #8684

**Comment by AlvaroBrey** [comment] 2022-12-17 14:54
> I think this one is a duplicate of #8684

yup

**Comment by AlvaroBrey** [comment] 2022-12-17 14:54
Duplicate of #8684

**Closed by AlvaroBrey** 2022-12-17 14:54 UTC
Labels: enhancement
