### ISSUE TITLE
Java null pointer exception when sharing to removed folder

### ISSUE THREAD

**Issue by projeqtor** [nextcloud/android#11256] opened 2023-01-15 09:00 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Hello,
I shared files from Android Gallery to a Nextcloud subfolder. Let say a/b/c.
All was ok.
Then, I renamed folders to a/d/e with my PC.
Now, when I want to share a file from Android Gallery, folder opened is c, which does not exist any more. And when I hit back to move to its parent, I get Java error
Thanks for your help.

### Cause of error
```java
Exception in thread "Thread-28" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230191`
* Build flavor: `gplay`

### Device information
* Brand: `Xiaomi`
* Device: `cupid`
* Model: `2201123G`
* Id: `TKQ1.220807.001`
* Product: `cupid_eea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `V13.2.4.0.TLCEUXM`

### Expected behaviour

List items of parent folder

### Actual behaviour

Java error null point exception

### Android version

13 TKQ1.220807.001

### Device brand and model

Xiaomi Mi 12

### Stock or custom OS?

Stock

### Nextcloud android app version

3.23.1

### Nextcloud server version

23.0.7

### Using a reverse proxy?

No

### Android logs

```java
Exception in thread "Thread-28" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230191`
* Build flavor: `gplay`

### Device information
* Brand: `Xiaomi`
* Device: `cupid`
* Model: `2201123G`
* Id: `TKQ1.220807.001`
* Product: `cupid_eea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `V13.2.4.0.TLCEUXM`

### Server error logs

```bash
Cannot reach
```

**Comment by AlvaroBrey** [comment] 2023-01-16 08:59
Duplicate of #11207

**Closed by AlvaroBrey** 2023-01-16 08:59 UTC
Labels: bug
