### ISSUE TITLE
Add a resync function to trigger automatic uploads

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#3489] opened 2019-01-23 10:20 UTC
### Actual behavior
By activating the automatic upload function all of your photos etc. are automatically uploaded to your Nextcloud server, what is fine. You're now deciding to temporarily deactivate the upload function, because e.g. you are traveling to a foreign country where mobile data rates are extremely high. On your return to your home country you reactivate the automatic upload function but non of the photos taken during the deactivation time are uploaded.

### Expected behavior
It would be nice to have a kind of resync function which allows to identify and automatically upload all photos taken during a deactivation phase and trigger the upload for them in one go.
 
### Steps to reproduce
1. Open the Nextcloud app and pause the automatic upload function.
2. Take some photos.
3. Reopen the Nextcloud app and reactivate the automatic upload function.
-> There is currently no way to automatically upload all photos taken during a deactivation phase.

### Environment data
Android version: 8.0
Device model: Samsung Galaxy S7
Stock or customized system: Stock ROM
Nextcloud app version: 3.4.2
Nextcloud server version: 15.0.2

**Comment by meika** [comment] 2019-11-29 21:17
totally needed because the auto-upload aint.

**Comment by b-pfl** [comment] 2021-08-17 23:48
To what extend does disabling & enabling the "also sync existing files" setting trigger this?

**Comment by AndyScherzinger** [comment] 2021-08-18 09:58
> To what extent does disabling & enabling the "also sync existing files" setting trigger this?

I think It'll pick them up, but maybe @ashpieboop can answer this better ❤️

**Comment by ashpieboop** [comment] 2021-08-19 16:02
Hi, sorry but it's been a long time since I worked on that. I can't remember much and don't have much time to get back into the project.

I think [these](https://github.com/nextcloud/android/commit/1b7bd72c494141fe51b25e6fb2e99ba76aadccc9#diff-ada409a30dbd2ab66518dda756eec63428e95b0e97b34d8cc9a6573d018b9c33R82-R109) are the relevant modifications. You might want to check [this](https://github.com/nextcloud/android/commit/1b7bd72c494141fe51b25e6fb2e99ba76aadccc9#diff-ada409a30dbd2ab66518dda756eec63428e95b0e97b34d8cc9a6573d018b9c33R183) too.

Hope this helps!

**Comment by joshtrichards** [comment] 2023-12-22 21:37
Duplicate of #383 & #1256

**Closed by joshtrichards** 2023-12-22 21:37 UTC
Labels: enhancement, feature: auto upload
