### ISSUE TITLE
App crashes randomly

### ISSUE THREAD

**Issue by alexdetsch** [nextcloud/android#5239] opened 2020-01-19 10:22 UTC
### Steps to reproduce
1. Do nothing, it just appears from time to time when the app is in background

### Expected behaviour
- no crashes

### Actual behaviour
- crashing
- seems like there is something wrong with the tracking

### Environment data
I currently cleaned the notifications-table in the database and logged of from this device in order to get rid of the HTTP 400 errors from Nextcloud push service. 

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-MaVKqs-ei3mvgK0aIWFrFA==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-MaVKqs-ei3mvgK0aIWFrFA==/lib/arm64, /data/app/com.nextcloud.client-MaVKqs-ei3mvgK0aIWFrFA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: joan
Model: LG-H930
Id: PKQ1.190414.001
Product: joan_global_com

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 193091504cde8

**Comment by AndyScherzinger** [comment] 2020-01-20 09:17
duplicate of #4675

**Closed by AndyScherzinger** 2020-01-20 09:17 UTC
Labels: bug
