### ISSUE TITLE
When press add folder button

### ISSUE THREAD

**Issue by sasiadstar** [nextcloud/android#7789] opened 2021-01-06 18:37 UTC
### Steps to reproduce
1. 
2. 
3. 
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5099)
	at android.view.ViewGroup.addView(ViewGroup.java:4930)
	at android.view.ViewGroup.addView(ViewGroup.java:4870)
	at android.view.ViewGroup.addView(ViewGroup.java:4843)
	at com.owncloud.android.ui.fragment.OCFileListBottomSheetDialog.onCreate(OCFileListBottomSheetDialog.java:131)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:610)
	at android.app.Dialog.show(Dialog.java:454)
	at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$registerFabListener$2$OCFileListFragment(OCFileListFragment.java:442)
	at com.owncloud.android.ui.fragment.-$$Lambda$OCFileListFragment$aYkoWPoxzAOahKL5AVjT06NhcnM.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:6659)
	at android.view.View.performClickInternal(View.java:6631)
	at android.view.View.access$3100(View.java:790)
	at android.view.View$PerformClick.run(View.java:26187)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140251
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HONOR
Device: HWJSN-H
Model: JSN-L21
Id: HONORJSN-L21
Product: JSN-L21

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.266C432

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2021-01-14 06:38
Duplicate of #7796

**Closed by tobiasKaminsky** 2021-01-14 06:38 UTC
Labels: bug, needs info/discussion
