### ISSUE TITLE
Avatars refresh issue

### ISSUE THREAD

**Issue by mario** [nextcloud/android#592] opened 2017-01-27 21:34 UTC
When you have multiple accounts, sometimes all the avatars have the same picture. Rotating the phone (or closing/reopening the app) fixes that as the activity is killed and recreated. Race condition somewhere?

**Comment by tobiasKaminsky** [comment] 2017-05-16 09:58
I cannot reproduce it and have never seen it, neither on emulator nor on real device.
@AndyScherzinger what about you?

**Comment by AndyScherzinger** [comment] 2017-05-16 10:04
@mario can you still reproduce this issue since I also never experienced this behavior nor was I able to enforce it somehow :/

**Comment by tobiasKaminsky** [comment] 2017-06-21 14:08
Closing, but please re-open if the problem occurs again.

**Closed by tobiasKaminsky** 2017-06-21 14:08 UTC
Labels: bug, need info
