### ISSUE TITLE
Add button to delete files tmp

### ISSUE THREAD

**Issue by Titi0603** [nextcloud/android#11419] opened 2023-02-25 19:35 UTC
### Is your feature request related to a problem? 
it can take up a lot of space.

### Describe the solution you'd like
Clear files tmp with a button or delete after x time.

### Describe alternatives you've considered
Compress files.

**Comment by joshtrichards** [comment] 2023-03-16 21:35
What files are you talking about?

You can already clear Deleted Files by going to Deleted Files-> Options (3 dots) -> Empty.

If you're referring to files you've chosen to have Sync'd (e.g. those with a green check mark), you can go the Options on any given sync'd file or folder and select Delete then "Local Only" to return only having the file stored on the server (and still being able retrieve/open it as needed from the client).

**Comment by joshtrichards** [comment] 2023-10-28 20:18
Duplicate of #10715 

And a bug since should not be things sticking around in `tmp`. It's not happening to everyone so we need to gather some log output. Anyhow, let's consolidate discussion/tracking in #10715.

**Closed by joshtrichards** 2023-10-28 20:18 UTC
Labels: enhancement, storage
