### ISSUE TITLE
Android application not working properly

### ISSUE THREAD

**Issue by DetonationEMS** [nextcloud/android#14062] opened 2024-11-20 16:02 UTC
I don't know if this ever has anything to do with it, but I logged into my local server in the Android application. Everything in the setup goes fine. But I keep getting login errors the app keeps trying to log in over and over and over again and failing even though I've already logged in properly. To the point where I have hundreds of failed logins in the logs.

### Cause of error
```java
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property currentAccount has not been initialized
    at com.nextcloud.client.mixins.SessionMixin.getCurrentAccount(SessionMixin.kt:32)
    at com.nextcloud.client.mixins.SessionMixin.onRestart(SessionMixin.kt:100)
    at com.nextcloud.client.mixins.MixinRegistry.onRestart(MixinRegistry.kt:48)
    at com.owncloud.android.ui.activity.BaseActivity.onRestart(BaseActivity.java:118)
    at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1711)
    at android.app.Activity.performRestart(Activity.java:9128)
    at android.app.ActivityThread.performRestartActivity(ActivityThread.java:5792)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:295)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:250)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:232)
    at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:170)
    at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8705)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `panther`
* Model: `Pixel 7`
* Id: `AP3A.241105.007`
* Product: `panther`

### Firmware
* SDK: `35`
* Release: `15`
* Incremental: `12470370`

**Comment by marianoju** [comment] 2024-11-24 16:15
I came here to report the same issue. I have succesfully logged in to my Nextcloud instance with my secondary Android¹ device several weeks ago. Now,  when I start the Nextcloud app, I get 
1. a display of the Nextcloud logo (maybe 3 seconds), 
2. a short display of my files (maybe 1 second), and then 
3. the login form. 

I have tried to login to my Nextcloud instance, but I have been informed that 
> An account for the same user and server already exists on the device.  

The app is working fine on my primary Android² device. 

1) Fire HD 10, Nextcloud 3.30.5
2) Fairphone 3+, Nextcloud 3.30.5

**Comment by joshtrichards** [comment] 2024-11-26 23:37
Duplicate of #13241

**Closed by joshtrichards** 2024-11-26 23:37 UTC

**Comment by OpenLogicEFI** [comment] 2024-11-26 23:40
idk if this helps but I no longer think this has anything to do with my original comment. The login error was actually my own fault. I rebuilt the server side and didn't realize I made a misspelling making the user name. 

Thanks! You all are the best!
