### ISSUE TITLE
!

### ISSUE THREAD

**Issue by sebastiencastermans** [nextcloud/android#7423] opened 2020-11-21 11:28 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{ba771bf u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1812)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6971)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: yuna_cheets
Model: Acer Chromebook 15 (CB5-571, C910)
Id: R87-13505.48.0
Product: yuna

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 6952429

**Comment by AndyScherzinger** [comment] 2020-11-23 09:07
Duplicate of #6905

**Closed by AndyScherzinger** 2020-11-23 09:07 UTC
Labels: bug
