### ISSUE TITLE
Upload not working 

### ISSUE THREAD

**Issue by sharicov** [nextcloud/android#7328] opened 2020-11-16 07:50 UTC
Showing message: Waiting for non-metered Wi-Fi
In Autoapload unmarked "Only upload on unmetered Wi-Fi
Connecting on home Wi-Fi via VPN or via cellular.
Contacts backup works properly.

**Comment by aqaqsubin** [comment] 2020-11-17 01:03
I think what you're trying to say is that you can upload only with unmetered Wi-Fi.
And I think this restriction should inform the user in advance.

![image](https://user-images.githubusercontent.com/28510311/99326854-02bf8280-28bc-11eb-9bc5-44d8ee8b23a2.jpeg)

![image](https://user-images.githubusercontent.com/28510311/99326880-11a63500-28bc-11eb-8b74-420b380b5321.jpeg)

**Comment by tobiasKaminsky** [comment] 2020-11-17 07:25
> I think what you're trying to say is that you can upload only with unmetered Wi-Fi.
> And I think this restriction should be informed the user in advance.

![2020-11-17-082414](https://user-images.githubusercontent.com/5836855/99358784-4f9c5c80-28ae-11eb-8139-990526c31678.png)

At least in English it is shown…?

**Comment by FFHUVDNENG** [comment] 2020-11-23 11:28
Hi,
I'm having the same issue.
I have explicitly configured my WIFI as a non-metered connection in Android. Makes no difference. 
The root cause is a VPN.
With a VPN app installed and the setting "always-on vpn" enabled, the upload doesn't work, wrongly assuming it is a metered connection.

**Comment by cvsickle** [comment] 2020-12-01 00:14
I can also confirm the behavior described by @SEARANATAT on versions 3.13.1 3.14.0, 3.14.1 RC 2.

I get the same behavior with both Mullvad and with ProtonVPN.

The weirdest part for me is that it ignores the "Only upload on unmetered Wi-Fi" toggle.

**Comment by tobiasKaminsky** [comment] 2020-12-02 11:03
> Edit2, the Dev Client (20201127) does not have this issue and works as expected.

Great, then it will be in 3.15.

**Closed by tobiasKaminsky** 2020-12-02 11:03 UTC
Labels: bug, needs info/discussion

**Comment by adi-dev** [comment] 2021-01-18 09:53
I just noticed same issue on my 3.15.0 RC1. It was refusing to upload untill... I plugged my phone into charger, then is started uploading files. No change to network type or anything.

**Comment by cvsickle** [comment] 2021-01-18 13:12
ProtonVPN updated the other day, and their update log said something about a change that prevented devices and apps from thinking the VPN connection was metered. I checked with 3.0.2-minimal, and the uploads work now.

I can't speak for the other VPN providers, as I no longer have those subscriptions.

**Comment by adi-dev** [comment] 2021-01-18 15:23
> ProtonVPN updated the other day, and their update log said something about a change that prevented devices and apps from thinking the VPN connection was metered. I checked with 3.0.2-minimal, and the uploads work now.
> 
> I can't speak for the other VPN providers, as I no longer have those subscriptions.

This was direct WiFi, no VPN.

But I remember, in the past, I had opposite behaviour, off the subject: I was on paid Wifi and ProtonVPN (for safety), before I realized, I used all my allowance because Nextcloud backed up my photos from all day.

**Comment by fabian727** [comment] 2024-09-30 17:55
I am trying to upload only via metered mobile network as I currently have dns problems.
It wont sync old and new pictures now for a month. I can browse through my existing files on the server and down/ upload anything I want, but auto-upload won't work. It did for the last years...

but it seems we are not the only one
https://help.nextcloud.com/t/auto-upload-on-android-not-uploading-anything/90253/28


Any advices?
I rechecked the unmetered box, restarted app and phone...
