### ISSUE TITLE
High battery usage

### ISSUE THREAD

**Issue by Byter3** [nextcloud/android#10904] opened 2022-10-24 06:34 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Use the Nextcloud client

### Expected behaviour

Not drain my battery in literllay half a day.

### Actual behaviour

It drains my battery like no tomorrow. I checked my battery consumption on my phone and hollycow, Nextcloud consumes everyday 20-30% of my battery, even when I did not cpature a single photo to upload it....

### Android version

12

### Device brand and model

Galaxy S21 Ultra

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.1

### Nextcloud server version

24

### Using a reverse proxy?

Yes

**Comment by AlvaroBrey** [comment] 2022-10-24 06:52
Duplicate of #7663

**Closed by AlvaroBrey** 2022-10-24 06:52 UTC
Labels: bug

**Comment by Byter3** [comment] 2022-10-24 06:58
@AlvaroBrey I really would like to emphesize, that this is something new, with the Nextcloud client. I did not have this issue prior to this release! I'm not gonna be able to use the Nextcloud client, since it almost cuts my battery hours in half.
Please reconsider, the closure of this ticket.
