### ISSUE TITLE
Random crashes from app

### ISSUE THREAD

**Issue by ryan77627** [nextcloud/android#4471] opened 2019-09-05 22:31 UTC
### Actual behaviour
- Nextcloud pops up and says it crashed, even when I'm not using it. The app wants me to report, so I will in case it helps

### Expected behaviour
- It should not.
 
### Steps to reproduce
?
I'm not sure, it pops up randomly

### Environment data
Android version:

Device model: Xiaomi mi 8

Stock or customized system: Lineage OS 16

```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-1-VWsCpT7mrjBLi_Ctcnqg==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-1-VWsCpT7mrjBLi_Ctcnqg==/lib/arm64, /data/app/com.nextcloud.client-1-VWsCpT7mrjBLi_Ctcnqg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080053
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: dipper
Model: MI 8
Id: PQ3A.190801.002
Product: dipper

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.root.20190817.084025


```

**Comment by tobiasKaminsky** [comment] 2019-10-08 13:04
Duplicate of #4586

**Closed by tobiasKaminsky** 2019-10-08 13:04 UTC
Labels: bug
