### ISSUE TITLE
app reports error when switching to grid view on folder with pictures

### ISSUE THREAD

**Issue by rportnoy2004** [nextcloud/android#10865] opened 2022-10-20 16:33 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. open app
2. navigate to a folder in the files section that contains pictures
3. click the grid icon in upper right corner to switch to grid view from list view

### Expected behaviour

view switches to larger icon grid view of files

### Actual behaviour

error reported and java traceback is displayed

### Android version

12

### Device brand and model

pixel 6 pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.0

### Nextcloud server version

23.0.10

### Using a reverse proxy?

Yes

### Android logs

unable to figure out how to get it from my phone

### Server error logs

```bash
no errors reported in server log
```

### Additional information

started happening after the October 19th app update to version 3.22.0

**Comment by Bauziii** [comment] 2022-10-20 18:18
Android version
11

Device brand and model
Cat S62 Pro

Stock or custom OS?
Stock

Nextcloud android app version
3.22.0

Nextcloud server version
24.0.6

Android logs
`Exception in thread "main" java.lang.ClassCastException: com.owncloud.android.ui.adapter.OCFileListGridImageViewHolder cannot be cast to com.owncloud.android.ui.adapter.ListGridImageViewHolder
    at com.owncloud.android.ui.adapter.OCFileListAdapter.onBindViewHolder(OCFileListAdapter.java:362)
    at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
    at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
    at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
    at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:572)
    at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
    at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
    at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
    at android.view.View.layout(View.java:22848)
    at android.view.ViewGroup.layout(ViewGroup.java:6389`

**Comment by AlvaroBrey** [comment] 2022-10-20 18:27
Duplicate of #10825, update your app to fix it

**Closed by AlvaroBrey** 2022-10-20 18:27 UTC
Labels: bug

**Comment by Bauziii** [comment] 2022-10-20 18:31
thank you
