### ISSUE TITLE
Reading vidéo crash

### ISSUE THREAD

**Issue by gabarchinco** [nextcloud/android#7191] opened 2020-11-01 00:13 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3d10caa u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1872)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: dream2lte
Model: SM-G955F
Id: PPR1.180610.011
Product: dream2ltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G955FXXSADTI1

**Comment by XueSheng-GIT** [comment] 2020-11-01 09:20
Video playback seems to be quite buggy on 3.14 RC1. Just playing the "Nextcloud intro.mp4" and nextcloud will crash when the video playback finishes. But it also crashes randomly if you start the video, tap to show the timeline, jump back again.
I never understood the video playback anyways (Start video, tap to show timeline, video restarts, rotate phone for horizontal playback, video stops and you have to restart manually, and so on... just confusing).

**Comment by AndyScherzinger** [comment] 2020-11-03 08:17
Duplicate of #6905

**Closed by AndyScherzinger** 2020-11-03 08:17 UTC
Labels: bug
