### ISSUE TITLE
NC Crashes while watching Sample video via app

### ISSUE THREAD

**Issue by schliemannosaurusrex** [nextcloud/android#7394] opened 2020-11-20 10:45 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{30c493d u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: flame
Model: Pixel 4
Id: RP1A.201105.002
Product: flame

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 6869500

**Comment by aqaqsubin** [comment] 2020-11-20 11:07
This has already been discussed in #2010.
And there is a PR (#7340) that solved this issue!

**Comment by schliemannosaurusrex** [comment] 2020-11-20 17:34
Thanks for the info. Sorry for any inconveniences. 🙋

Have a nice weekend.

Mit freundlichen Grüßen | Best regards

Daniel Schliemann
Sent from my Android

Subin Kim <notifications@github.com> schrieb am Fr., 20. Nov. 2020, 12:08:

**Comment by AndyScherzinger** [comment] 2020-11-23 09:08
Duplicate of #6905

**Closed by AndyScherzinger** 2020-11-23 09:08 UTC
Labels: bug
