### ISSUE TITLE
Crash on deleting photo from media

### ISSUE THREAD

**Issue by HerbCSO** [nextcloud/android#10726] opened 2022-09-09 10:40 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Go to Media
2. Delete one of the sample pictures Nextcloud comes with (e.g. the frog)
3. Crash happens (see stack trace in additional information)

### Expected behaviour

No crash ;]

### Actual behaviour

App crashes with supplied stack trace. Photo is deleted though.

### Android version

11

### Device brand and model

OnePlus 7 Pro

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

30210290

### Nextcloud server version

24.0.4

### Using a reverse proxy?

No

### Android logs

Not available

### Server error logs

```bash
Submitting this from Android, will try to add afterwards.
```

### Additional information

Can't retrieve android logs due to Android 11 security (and non-rooted device).

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.services.OperationsService$OperationsServiceBinder.isSynchronizing(OperationsService.java:372)
    at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:532)
    at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:521)
    at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:201)
    at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:133)
    at com.owncloud.android.ui.preview.PreviewImageFragment.onPrepareOptionsMenu(PreviewImageFragment.java:381)
    at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:3253)
    at androidx.fragment.app.FragmentManager.dispatchPrepareOptionsMenu(FragmentManager.java:3051)
    at androidx.fragment.app.FragmentManager$2.onPrepareMenu(FragmentManager.java:466)
    at androidx.core.view.MenuHostHelper.onPrepareMenu(MenuHostHelper.java:63)
    at androidx.activity.ComponentActivity.onPrepareOptionsMenu(ComponentActivity.java:497)
    at android.app.Activity.onPreparePanel(Activity.java:4230)
    at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3148)
    at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1936)
    at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2190)
    at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:273)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
    at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
    at android.view.Choreographer.doFrame(Choreographer.java:1040)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:233)
    at android.app.ActivityThread.main(ActivityThread.java:8010)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210290`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus7Pro`
* Model: `GM1917`
* Id: `RKQ1.201022.002`
* Product: `OnePlus7Pro`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `2206171030`

**Comment by svenb1234** [comment] 2022-09-10 09:55
It is not only from media but also from the file view. Despite the crash, the files are copied to the trash.

**Comment by AlvaroBrey** [comment] 2022-09-12 09:52
Duplicate of #10580

**Closed by AlvaroBrey** 2022-09-12 09:52 UTC
Labels: bug
