### ISSUE TITLE
Bubble on Video Player Progress Bar not visible

### ISSUE THREAD

**Issue by steve-s-71** [nextcloud/android#1761] opened 2017-11-07 19:05 UTC
While playing a Video, it appears that the progress bar is not showing progress:

![1](https://user-images.githubusercontent.com/17343515/32512168-77137390-c3f6-11e7-9d92-b8e28b175c07.png)

I identified this is really because the progress bar is thicker than the bubble and they both have the identical color. Thus the bubble is  there and functional, it is just not visible:

![skizze](https://user-images.githubusercontent.com/17343515/32512252-b85c619a-c3f6-11e7-8dad-dcdef3805740.png)

In full screen mode everything is fine, as the progress bar line is much thinner:

![3](https://user-images.githubusercontent.com/17343515/32512275-c90274f8-c3f6-11e7-8def-1620f21ee61f.png)

App Version 2.0.0.

@AndyScherzinger

**Comment by AndyScherzinger** [comment] 2017-11-07 20:17
Thanks for taking the time to analyze and report on such a detailed level!

Cc @mario @tobiasKaminsky

**Comment by AndyScherzinger** [comment] 2017-11-08 13:21
found the cause, PR will follow very soon

**Comment by tobiasKaminsky** [comment] 2017-11-08 13:24
Great, I was just about digging into it.

**Comment by tobiasKaminsky** [comment] 2017-11-08 13:25
The progress bar in normal view is tinted, whereas in fullscreen it not themed..

**Comment by AndyScherzinger** [comment] 2017-11-08 13:52
not sure if we can influence the full screen theme since I guess that is a native "screen" displayed by the operating system and not by the app itself...

**Comment by AndyScherzinger** [comment] 2017-11-08 14:05
PR is #1763

**Comment by steve-s-71** [comment] 2017-11-08 16:39
Awesome - and may thanks to @AndyScherzinger 

Just for my curiosity: when is v2.1.0 (beta) expected to be available in PlayStore?

**Comment by AndyScherzinger** [comment] 2017-11-08 16:52
@steve-s-71 you are very welcome as for as 2.1.0 that is joint discussion/decision between @mario, @tobiasKaminsky and me. Looking at https://github.com/nextcloud/android/pulls?q=is%3Aopen+milestone%3A%22Nextcloud+App+2.1.0%22+type%3Apr there are still 17 open pull requests while I can't tell if all of them will make it into 2.1.0 at this point.

**Comment by steve-s-71** [comment] 2017-11-08 17:18
Got it. Thanks again.

**Comment by AndyScherzinger** [comment] 2017-11-08 18:04
@steve-s-71 I'll keep the issue open (just re-opened it) until the fix is merged to the master branch. So the issue will close automatically when this happens. 😃

**Closed** 2017-11-09 07:50 UTC
Labels: bug, design, pr exists

**Comment by AndyScherzinger** [comment] 2018-02-13 11:14
@steve-s-71 3.0.0 is out (on Google Play), did it fix this issue for you (which it should)?

**Comment by steve-s-71** [comment] 2018-02-13 17:50
@AndyScherzinger yes, this is resolved in 3.0.0. Thank you!

What still does not work is [#1971 - Videoplayback in full-screen isn't really full-screen](https://github.com/nextcloud/android/issues/1971)

**Comment by AndyScherzinger** [comment] 2018-02-13 19:49
Thanks @steve-s-71 glad to hear. As for the other issue it is still on the radar but unfortunately my day job keeps me quite busy these days. So I haven't found the time yet but haven't forgot about it.
