### ISSUE TITLE
Nextcloud App crashes when opening side menu

### ISSUE THREAD

**Issue by woolmilkpigs** [nextcloud/android#8963] opened 2021-09-10 04:26 UTC
### Steps to reproduce
1. Completely reset and restart and login into the nextcloud app
2. Open the left side menu the first time (works fine)
3. Opening the side menu the second time leads to the crash even with killing and restarting the app

### Expected behaviour
- the side menu should appear

### Actual behaviour
- the app shows the error log

### Can you reproduce this problem on https://try.nextcloud.com?
- problem doesn't appear with a demo account but I'm also not able to add some external links to the menu bar there, because I have no rights to change settings for the external link app
- further information: with the previous version of the app the problem didn't not occur/the server configuration did not change
- one assumption: I've got some external links configured on the server -> maybe this leads to a "too small" side menu in the app to fit all of them?

### Environment data
Android version: see log below

Device model: see log below

Stock or customized system: stock

Nextcloud app version: see log below

Nextcloud server version: latest stable release (afaik 21.0.3)

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Canvas: trying to draw too large(212634660bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:1018)
	at android.widget.ImageView.onDraw(ImageView.java:1434)
	at android.view.View.draw(View.java:21547)
	at android.view.View.updateDisplayListIfDirty(View.java:20416)
	at android.view.View.draw(View.java:21276)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.draw(View.java:21550)
	at android.view.View.updateDisplayListIfDirty(View.java:20416)
	at android.view.View.draw(View.java:21276)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20407)
	at android.view.View.draw(View.java:21276)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.draw(View.java:21550)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
	at android.view.View.updateDisplayListIfDirty(View.java:20416)
	at android.view.View.draw(View.java:21276)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.draw(View.java:21550)
	at com.google.android.material.internal.ScrimInsetsFrameLayout.draw(ScrimInsetsFrameLayout.java:109)
	at android.view.View.updateDisplayListIfDirty(View.java:20416)
	at android.view.View.draw(View.java:21276)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.draw(View.java:21550)
	at android.view.View.updateDisplayListIfDirty(View.java:20416)
	at android.view.View.draw(View.java:21276)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20407)
	at android.view.View.draw(View.java:21276)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20407)
	at android.view.View.draw(View.java:21276)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20407)
	at android.view.View.draw(View.java:21276)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20407)
	at android.view.View.draw(View.java:21276)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.draw(View.java:21550)
	at com.android.internal.policy.DecorView.draw(DecorView.java:844)
	at android.view.View.updateDisplayListIfDirty(View.java:20416)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3716)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3511)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2848)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1801)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7763)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: pyxis
Model: Mi 9 Lite
Id: QKQ1.190828.002
Product: pyxis_eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.7.0.QFCEUXM

**Comment by AlvaroBrey** [comment] 2021-09-10 07:24
Duplicate of #8862

**Closed by AlvaroBrey** 2021-09-10 07:24 UTC
Labels: bug
