### ISSUE TITLE
Add a link to the Tasks app to the menu on the left

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#5389] opened 2020-02-03 10:15 UTC
### Is your feature request related to a problem? Please describe.
No, it is rather an idea for enhancement.

### Describe the solution you'd like
add a link to the Tasks app to the left menu of the Android app. It would open in a webview equally as Collabora does. It would make the app much fuller tool needing just minimal effort (I might be wrong here :) ).

**Comment by tobiasKaminsky** [comment] 2020-02-03 11:07
This is an often discussed feature request.
The problem is that you need to be authenticated to see tasks app. And this is not stored in web view.
Also if we would show it in webview, then there is the complete NC header (with files, contacts, etc.) visible, which is not that good ux wise.

If you want to do this, you can install and configure https://apps.nextcloud.com/apps/external

**Comment by tobiasKaminsky** [comment] 2020-02-03 11:09
Duplicate of https://github.com/nextcloud/android/issues/1164

**Closed by tobiasKaminsky** 2020-02-03 11:09 UTC
Labels: enhancement
