### ISSUE TITLE
Inside details of a file, activities view is broken

### ISSUE THREAD

**Issue by juanyunis** [nextcloud/android#12647] opened 2024-03-04 23:30 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open NextCloud Android apl
2. Select any file and click the 3 dots at the right side
3. Select Details
4.  Details is stuck like loading but it is not, and I don't see a url call to the server for that. 

### Expected behaviour

Like web, it should list all the activities related to that file. 

### Actual behaviour

I can't see any activities of a file when I click Details of any file. 
![Screenshot_20240304_150212_Nextcloud](https://github.com/nextcloud/android/assets/721132/b6614038-c20c-4859-96a1-301fc46a0d11)
![Screenshot_20240304_150222_Nextcloud](https://github.com/nextcloud/android/assets/721132/3e5f1758-1025-4931-90f9-2f9d461e94b9)
![Screenshot_20240304_150225_Nextcloud](https://github.com/nextcloud/android/assets/721132/8f1d3c23-620a-4945-aae5-19e207e9c53e)
![Screenshot_20240304_150229_Nextcloud](https://github.com/nextcloud/android/assets/721132/27a27c1a-c9ab-49f0-a798-705dcdabec51)

And this is in the web version, it does work.
![20240304_152426](https://github.com/nextcloud/android/assets/721132/95252f22-8500-4ed0-89b9-12bafe77b735)

### Android version

14

### Device brand and model

Samsung Galaxy S24 Ultra 5G (SM-S928U1) 

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.0

### Nextcloud server version

28.0.3

### Using a reverse proxy?

Yes

**Comment by joshtrichards** [comment] 2024-03-05 02:54
> 3.28.0

We know about this one, but thanks for reporting nonetheless!

You had me worried for a moment because I was certain we'd already fixed this. It *is* fixed in our dev builds. It appears it was merged, but is set for release in v3.28.1 via #12541. It just didn't make it in time for v3.28.0.

Duplicate of #12364

**Closed** 2024-03-05 02:54 UTC
Labels: bug
