### ISSUE TITLE
Nextcloud  client crash android

### ISSUE THREAD

**Issue by duese456** [nextcloud/android#9730] opened 2022-01-23 00:03 UTC
### Steps to reproduce
1. Open Nextcloud client 3.18.1
2. Choose Einstellungen or Benachrichtigungen or Upload
3. Nextcloud client crashes with error

### Expected behaviour
- subtopic menu should open and you can choose a parameter

### Actual behaviour
- crashes and aborts with error:

```
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1911728 bytes
	at android.app.ActivityClient.activityStopped(ActivityClient.java:86)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
Caused by: android.os.TransactionTooLargeException: data parcel size 1911728 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:635)
```

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
12
Device model: 
Samsung Galaxsy S10 SM-G973F/DS
Stock or customized system:

Nextcloud app version:
3.18.1
Nextcloud server version:
23.0.0.1
Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2022-05-30 07:41
Duplicate of #9621

**Closed by AlvaroBrey** 2022-05-30 07:41 UTC
Labels: bug
