### ISSUE TITLE
Uploading protocol to Nextcloud errors on beta

### ISSUE THREAD

**Issue by aronovgj** [nextcloud/android#535] opened 2017-01-12 20:28 UTC
### Actual behaviour
When uploading the protocol I get an error that I can upload instead

### Expected behaviour
Upload protocol
 
### Steps to reproduce
1. Go to settings/protocols
2. Send
3. Select Nextcloud beta as the app to send it with
4. Get error screen

### Environment data
Android version:
OOS 4.0 (Nougat)

Device model: 
Oneplus 3

Stock or customized system:
Stock/Rooted

Nextcloud app version:
beta 20170111

Nextcloud server version:
11

#### Web server error log
```
None
```

#### Nextcloud log (data/nextcloud.log)
```
None
```

#### App Error 
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 3291148 bytes
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3876)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6209)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: android.os.TransactionTooLargeException: data parcel size 3291148 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:651)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3814)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3849)
	... 7 more

************ DEVICE INFORMATION ***********
Brand: OnePlus
Device: OnePlus3
Model: ONEPLUS A3003
Product: OnePlus3

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: 89

```

**Comment by tobiasKaminsky** [comment] 2017-06-26 12:59
Duplicate of #1102

**Closed by tobiasKaminsky** 2017-06-26 12:59 UTC
Labels: bug
