### ISSUE TITLE
Keepass database is not synced/uploaded after editing

### ISSUE THREAD

**Issue by roundoutandabout** [nextcloud/android#9899] opened 2022-02-27 17:17 UTC
### Steps to reproduce
1. Open the Nextcloud app. Navigate to the Keepass database file (`.kdbx`) 
2. Open the file with KeePassDX
3. Edit the file with KeePassDX. Press "Save data"
4. Close the file.
5. In the Nextcloud app press "Sync" for the file

### Expected behaviour
- The updated file is uploaded to the server.
- The modification time of the file is updated

### Actual behaviour
- Message pops up "File contents already synchronized". The file is not uploaded
- The modification time of the file is not updated
- The Nextcloud app shows the updated file
- The server stores the old file

### Can you reproduce this problem on https://try.nextcloud.com?
- I could not reproduce the problem on the test account with the test Keepass database immediately.

### Environment data
Android version:
Android 11

Device model: 
Xiaomi Redmi Note 5

Stock or customized system:
Stock LineageOS 18.1

Nextcloud app version:
3.19.0

Keepass database format:
KDBX 4.0

Nextcloud server version:
Nextcloud 22.2.3 (Snap)

Additional info:
The only way I could make the Nextcloud app to actually sync the file was by installing the version `3.18.0`

Might be related:
Nextcloud android app also keeps showing the old version of the file, that has been edited and uploaded to the server from the desktop Nextcloud app. 

#### Nextcloud log (data/nextcloud.log)
Logs related only to Test.kdbx that I have problems with
[nextcloud.log](https://github.com/nextcloud/android/files/8149016/nextcloud.log)

**Comment by AlvaroBrey** [comment] 2022-03-01 12:24
@roundoutandabout Where is the keepasX database located? If it's under `Android/data`, we can no longer read or access files in that location due to storage limitations in Android 11.

**Comment by roundoutandabout** [comment] 2022-03-01 21:17
@AlvaroBrey hmm, I've installed 3.19.0 once again. The database is stored in `Android/media/com.nextcloud.client/...` according to KeepassDX. The issue is present: after editing the database and closing it, the database isn't synced.

**Comment by BornToBeRoot** [comment] 2022-03-03 17:19
Had the same with KeePass2Android. Couldn't open it via the app directly... I think it related to this: https://github.com/nextcloud/android/issues/9906

**Comment by roundoutandabout** [comment] 2022-03-04 22:59
> 
> Yeah, same problem; KeepassDX probably can't access the Nextcloud folder with write permissions. Will try to investigate this

Thanks!

**Comment by roundoutandabout** [comment] 2022-03-04 23:01
> Had the same with KeePass2Android. Couldn't open the kdbx via the keepass app directly... I think it related to this: #9906

I don't have the issue with the file manager that you mentioned. Not sure if it's related.

**Comment by CapSel** [comment] 2022-03-30 08:08
I have same problem and keepass remembers some integer instead of real folder name. Also same problem when I set signal to backup to nextcloud - first backup goes well but the path it shows consists of only integers.

**Comment by meldarionqeusse** [comment] 2022-04-21 17:41
I have the same issue have to force sync

**Comment by mwip** [comment] 2022-04-23 08:19
I have the same issue with a plain text file with the following setup:
- Android 8.1
- Nextcloud 23.0.2
- NC-Android 3.19.1
- File stored on `Android/media/...`

**Comment by mwip** [comment] 2022-05-07 16:49
Keeping this up to date: with NC-Android 3.20 this issue seems resolved for me

**Comment by AlvaroBrey** [comment] 2022-05-09 07:35
This issue is likely caused by #9906, and will be fixed once #10168 is merged

**Closed** 2022-05-09 08:03 UTC
Labels: bug
