### ISSUE TITLE
Folder sync

### ISSUE THREAD

**Issue by proninyaroslav** [nextcloud/android#668] opened 2017-02-18 15:24 UTC
Hello. Will the implemented ability to folder synchronize, as is done in the client for OwnCloud https://github.com/owncloud/android/issues/1136 ?

**Comment by JSoko** [comment] 2017-02-18 15:55
It's on the roadmap: #285

**Comment by mario** [comment] 2017-02-18 15:56
Either that or if I understood the request right, we also have "Set as available offline" already baked in.

**Comment by twixi** [comment] 2017-02-19 14:33
Very need full sync from Server to phone and vice versa too!

**Comment by tobiasKaminsky** [comment] 2017-02-19 15:19
This is already planned (and briefly described) here: #285

**Comment by AndyScherzinger** [comment] 2017-02-19 17:31
Well, the original request referes to oC's "set available offline" functionality for folders not just files which is slightly different. Whenever #285 comes to life for customer folders + 2-way sync we have a comparable offer which works slightly different. It wouldn't be a sync of a server folder to a local folder *within* Nextclouds storage path on the phone but any storage path on the device. 

Still fine with me and even more flexible.

**Comment by natrius** [comment] 2021-08-09 23:13
I hope https://github.com/nextcloud/android/issues/285 this will be finished soon as it seems it has the potential to solve some syncing problems with some apps as well. If i understand it correctly if 285 is in place, i can just choose to 2way sync the diary folder from https://github.com/billthefarmer/diary/issues/42 and there is no need for billthefarmer to implement a nextcloud sync by himself?

Many thanks for you work!

**Comment by joshtrichards** [comment] 2024-10-19 01:10
Duplicate of #269

**Closed by joshtrichards** 2024-10-19 01:10 UTC
Labels: enhancement, feature: sync
