### ISSUE TITLE
sync doesnt work 

### ISSUE THREAD

**Issue by jgh0721** [nextcloud/android#6077] opened 2020-05-14 23:22 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start service com.owncloud.android.services.OperationsService@e60302c with Intent { act=SYNC_FOLDER cmp=com.nextcloud.client/com.owncloud.android.services.OperationsService (has extras) }: java.lang.ClassCastException: com.nextcloud.client.account.RegisteredUser cannot be cast to android.accounts.Account
	at android.app.ActivityThread.handleServiceArgs(Unknown Source:134)
	at android.app.ActivityThread.access$1900(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:613)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loop(Unknown Source:249)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:282)
Caused by: java.lang.ClassCastException: com.nextcloud.client.account.RegisteredUser cannot be cast to android.accounts.Account
	at com.owncloud.android.services.OperationsService.onStartCommand(OperationsService.java:196)
	at android.app.ActivityThread.handleServiceArgs(Unknown Source:40)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: cmi
Model: Mi 10 Pro
Id: QKQ1.191117.002
Product: cmi

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 20.3.28

**Comment by AndyScherzinger** [comment] 2020-05-15 05:58
Duplicate of #6070

**Comment by AndyScherzinger** [comment] 2020-05-15 05:59
Hi @jgh0721 and thanks for the report.
This will be fixed with the next RC release 👍

**Closed by AndyScherzinger** 2020-05-15 05:59 UTC
Labels: bug
