### ISSUE TITLE
Try delete files

### ISSUE THREAD

**Issue by xcorella** [nextcloud/android#10506] opened 2022-07-11 20:12 UTC
I try delete 5 selected files in android app. 

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Couldn't read row 889, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetString(Native Method)
    at android.database.CursorWindow.getString(CursorWindow.java:469)
    at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
    at android.database.CursorWrapper.getString(CursorWrapper.java:141)
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:957)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:884)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:187)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:610)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1285)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1233)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1222)
    at com.owncloud.android.ui.activity.FileDisplayActivity.updateListOfFilesFragment(FileDisplayActivity.java:574)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoveFileOperationFinish(FileDisplayActivity.java:1719)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1652)
    at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:778)
    at com.owncloud.android.services.OperationsService$$ExternalSyntheticLambda0.run(Unknown Source:6)
    at android.os.Handler.handleCallback(Handler.java:900)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8668)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `HUAWEI`
* Device: `HWLYA`
* Model: `LYA-L29`
* Id: `HUAWEILYA-L29`
* Product: `LYA-L29`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `10.1.0.289C432`

**Comment by AlvaroBrey** [comment] 2022-07-12 11:46
Duplicate of #9948

**Closed by AlvaroBrey** 2022-07-12 11:46 UTC
