### ISSUE TITLE
Creating Folder in Strange Location by Sync

### ISSUE THREAD

**Issue by LenKiMo** [nextcloud/android#9732] opened 2022-01-23 09:14 UTC
### Steps to reproduce
1. Set App's data folder as `/data/user/0/com.nextcloud.client/files`
2. Sync any folder from Nextcloud server
3. Open any file manager in phone

### Expected behaviour
- App will create folder in the location was set in Step 1.

### Actual behaviour
- App create folder in `/storage/emulated/0/(invalid)/data/user/0/com.nextcloud.client/files/nextcloud`
- Also, there is a folder in `storage/emulated/0/nextcloud`. However, it's not the folder just created, it's created in sometime last sync and don't know how it move to here.

### Can you reproduce this problem on https://try.nextcloud.com?
Not suitable for this issue.

### Environment data
Android version: 12

Device model: Xiaomi MIX 4 (2106118C)

Stock or customized system: MIUI 13 22.1.19 (Beta Version)

Nextcloud app version: 3.18.1

Nextcloud server version: 22.2.3

Reverse proxy: nginx/1.18.0 (fpm-fcgi)

### Logs
Not sure if needed.

**Comment by AlvaroBrey** [comment] 2022-01-24 10:28
Duplicate of #9328

**Closed by AlvaroBrey** 2022-01-24 10:28 UTC
Labels: bug
