### ISSUE TITLE
unable to select Downloads folder for auto upload

### ISSUE THREAD

**Issue by bjo81** [nextcloud/android#8683] opened 2021-07-09 11:43 UTC
### Steps to reproduce
1. Try to select "Download" as local folder

### Expected behaviour
- Download folder is selected

### Actual behaviour
- If I enter the folder which shows as empty the select button does nothing
- If I select Download abd press the select button /storage/emulated/0 is selected

### Can you reproduce this problem on https://try.nextcloud.com?
- not tried as it seems to be an issue with the file management

### Environment data
Android version:
11
Device model: 
Redmi Note 7
Stock or customized system:
Lineage OS 18.1
Nextcloud app version:
3.17.0 RC1
Nextcloud server version:
22.0

**Comment by AlvaroBrey** [comment] 2021-09-20 08:06
Duplicate of #8940

**Closed by AlvaroBrey** 2021-09-20 08:06 UTC
Labels: bug
