### ISSUE TITLE
Error When "Open With" Button Pressed

### ISSUE THREAD

**Issue by wasv** [nextcloud/android#13852] opened 2024-10-22 12:43 UTC
Was trying to open a markdown document after updating to todays release.
This error was thrown after selecting "Open With" in the menu that pops up from the bottom in the document viewer, before the list of apps was shown.
This may have existed in previous patches to the minor release as well, I hadnt tried it since I disabled it while the syncing bug was present.

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Fragment FileActionsBottomSheet{b278f39} (45567cb1-2ea5-412f-b044-a56e1f80c4a1) not associated with a fragment manager.
    at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:1117)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.dispatchActionClick(FileActionsBottomSheet.kt:295)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.onCreateView$lambda$0(FileActionsBottomSheet.kt:88)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.$r8$lambda$HQOdD3b3CxoLu3wixbP6otxN-pU(Unknown Source:0)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
    at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
    at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
    at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
    at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
    at com.nextcloud.ui.fileactions.FileActionsViewModel.onClick(FileActionsViewModel.kt:138)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.inflateActionView$lambda$10$lambda$9(FileActionsBottomSheet.kt:277)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.$r8$lambda$X1bznCZWgiDSrY29Ez72rilRQ60(Unknown Source:0)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$$ExternalSyntheticLambda2.onClick(D8$$SyntheticClass:0)
    at android.view.View.performClick(View.java:7931)
    at android.view.View.performClickInternal(View.java:7908)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(View.java:30990)
    at android.os.Handler.handleCallback(Handler.java:959)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8592)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300390`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `barbet`
* Model: `Pixel 5a`
* Id: `AP2A.240805.005`
* Product: `barbet`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `12025142`

**Comment by joshtrichards** [comment] 2024-10-22 13:46
Duplicate of #11701

**Closed by joshtrichards** 2024-10-22 13:46 UTC
Labels: bug, performance: ISE/IAE :confused:, stable-3.30
