### ISSUE TITLE
Fehlerhafte Serververbindung

### ISSUE THREAD

**Issue by Lajos13** [nextcloud/android#9010] opened 2021-09-25 22:12 UTC
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to pause activity {com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity}: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@8ce16b4
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4284)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4239)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4191)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:187)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1950)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7073)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@8ce16b4
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1338)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1583)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:672)
	at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.onInactive(UsbConnectionDispatcher.java:131)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.ensureStateInactive(SecurityKeyManager.java:316)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.refreshActiveState(SecurityKeyManager.java:290)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.onActivityPaused(SecurityKeyManager.java:333)
	at android.app.Application.dispatchActivityPaused(Application.java:273)
	at android.app.Activity.onPause(Activity.java:1791)
	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:388)
	at com.owncloud.android.authentication.AuthenticatorActivity.onPause(AuthenticatorActivity.java:741)
	at android.app.Activity.performPause(Activity.java:7609)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1465)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4274)
	... 13 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: greatlte
Model: SM-N950F
Id: PPR1.180610.011
Product: greatltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: N950FXXSGDUG6

**Comment by AlvaroBrey** [comment] 2021-09-26 21:21
Duplicate of #8585

**Closed by AlvaroBrey** 2021-09-26 21:21 UTC
Labels: bug
