### ISSUE TITLE
Bruteforce protection and login

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/android#1502] opened 2017-09-06 13:29 UTC
* do a lot of failed logins
* try to login via Android
* expected: it takes long, but will log in (max penalty for this is 30 seconds on the server - so 40 seconds should be fine)
* actual: it says "Request takes too long" and fails

Maybe there could be a soft-fail: after 5 seconds a little hint that expands below the circle: "Yes, request is still running. Either the server is slow or the brute force protection (link) is triggered."

based on discussion https://twitter.com/robtranquillo/status/905411667139469312

@AndyScherzinger @tobiasKaminsky @robtranquillo

**Comment by MorrisJobke** [comment] 2017-09-06 13:33
Maybe this should be also improved in the server to clear the entries for a user from the IP, if the users logs properly in: https://github.com/nextcloud/server/issues/3156

**Comment by RobTranquillo** [comment] 2017-09-06 13:41
Minimum solution: 

-  hint at the login or at the admin console.
Better solution:

- hint at the login or at the admin console.
- the hint shows the penalty time
- the penalty is triggered later

Best Solution:

- hint at the login or at the admin console.
- the hint shows the penalty time
- the penalty is triggered later
- reset button (clears the oc_bruteforce_attempts of some users login fails)

**Comment by AndyScherzinger** [comment] 2017-09-06 14:26
@tobiasKaminsky if I remember correctly you already discussed this general matter with @LukasReschke and we don't have a way to detect the brute force penalty. So should we just raise the timeout while I thought we already did that...seems we didn't.

**Comment by MorrisJobke** [comment] 2017-09-06 17:53
> the penalty is triggered later

What does that mean?



> reset button (clears the oc_bruteforce_attempts of some users login fails)

nextcloud/server#3156 & nextcloud/server#3058

**Comment by RobTranquillo** [comment] 2017-09-06 18:31
>>     the penalty is triggered later
> 
> What does that mean?

Just raise the limits, that more logins can fail.

**Comment by joshtrichards** [comment] 2023-12-11 22:18
Duplicate of #893

**Closed by joshtrichards** 2023-12-11 22:18 UTC
Labels: enhancement, feature: authentication, hotspot: auth failure mgmt
