### ISSUE TITLE
error when accessing media section

### ISSUE THREAD

**Issue by sebthesun** [nextcloud/android#11133] opened 2022-12-03 14:37 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Just trying to open media section in the Nextbook app 

### Expected behaviour

The app should show picture thumbnail 

### Actual behaviour

The app crashed

### Android version

13

### Device brand and model

Google pixel 6 

### Stock or custom OS?

Stock

### Nextcloud android app version

30230090

### Nextcloud server version

25.0.1

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Fragment already added: GalleryFragmentBottomSheetDialog{44311f6} (78f498c2-6e40-4c39-8a59-f238b72cb878 tag=data)
    at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:92)
    at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1481)
    at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:387)
    at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:1965)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1873)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7898)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230090`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `oriole`
* Model: `Pixel 6`
* Id: `TP1A.221105.002`
* Product: `oriole`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `9080065`

**Comment by AlvaroBrey** [comment] 2022-12-12 15:31
Duplicate of #10614

**Closed by AlvaroBrey** 2022-12-12 15:31 UTC
Labels: bug
