### ISSUE TITLE
Nextcloud App crashes everytime one confirms a login

### ISSUE THREAD

**Issue by svenb1234** [nextcloud/android#7020] opened 2020-09-27 16:50 UTC
### Steps to reproduce
1. Login via the web interface with two factor authentication enabled. Nextcloud app notification as second factor.
2. Open the Nextcloud App and switch to notifications
3. Accept the login

### Expected behaviour
- The login on the web interface continues (it does) without the Nextcloud app crashing.

### Actual behaviour
- The Nextcloud app crashes everytime

### Environment data
Android version: 11 but happened on 10 as well

Device model: Pixel 3a

Stock or customized system: stock

Nextcloud app version: latest

Nextcloud server version: 19.0.3

#### Nextcloud app log 
```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.AnalyticsConnector
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: sargo
Model: Pixel 3a
Id: RP1A.200720.009
Product: sargo

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 6720564

```

**Comment by tobiasKaminsky** [comment] 2020-09-29 10:48
Duplicate of #6269

**Closed by tobiasKaminsky** 2020-09-29 10:48 UTC
Labels: bug
