### ISSUE TITLE
Crash after fresh install

### ISSUE THREAD

**Issue by ThaFacialHair** [nextcloud/android#10902] opened 2022-10-24 02:32 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Install app from Google Play store on Android 12 with a pixel 3
Launch the app and provide the IP address of my next loud server
Crash

### Expected behaviour

Give permission for login and get access to my files

### Actual behaviour

Crashes after inputting server IP.

### Android version

12

### Device brand and model

pixel 3

### Stock or custom OS?

Stock

### Nextcloud android app version

30220190

### Nextcloud server version

22.2.10

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.LinearLayout com.owncloud.android.databinding.SslUntrustedCertLayoutBinding.getRoot()' on a null object reference
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4761)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4794)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7842)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.LinearLayout com.owncloud.android.databinding.SslUntrustedCertLayoutBinding.getRoot()' on a null object reference
    at com.owncloud.android.ui.dialog.SslUntrustedCertDialog.onCreateDialog(SslUntrustedCertDialog.java:173)
    at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665)
    at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579)
    at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1752)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
    at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2985)
    at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2909)
    at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:285)
    at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:334)
    at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:323)
    at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:240)
    at android.app.Activity.performResume(Activity.java:8216)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4751)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4794)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7842)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220190`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `blueline`
* Model: `Pixel 3`
* Id: `SP1A.210812.016.C2`
* Product: `blueline`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `8618562`

### Additional information

Nextcloud server is running as a docker container.

**Comment by AlvaroBrey** [comment] 2022-10-24 06:54
Duplicate of #10868, fix will be out today

**Closed by AlvaroBrey** 2022-10-24 06:54 UTC
Labels: bug
