### ISSUE TITLE
Dev version not downladable

### ISSUE THREAD

**Issue by anizpoudel** [nextcloud/android#7571] opened 2020-12-01 04:16 UTC
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkCapabilities.hasCapability(int)' on a null object reference
	at com.nextcloud.client.network.ConnectivityServiceImpl.getConnectivity(ConnectivityServiceImpl.java:121)
	at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:207)
	at com.owncloud.android.utils.-$$Lambda$FilesSyncHelper$78U1WN_nzr5HiGIrRZMThSEamz8.run(Unknown Source:10)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201127
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: j7y17lte
Model: SM-J730F
Id: PPR1.180610.011
Product: j7y17ltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: J730FXWU7CTH2

**Comment by AndyScherzinger** [comment] 2020-12-01 08:25
Duplicate of #7560

**Comment by AndyScherzinger** [comment] 2020-12-01 08:26
Please update to latest dev build

**Comment by anizpoudel** [comment] 2020-12-01 12:45
this is the latest version

**Comment by AndyScherzinger** [comment] 2020-12-01 13:11
@anizpoudel thanks for the info
@tobiasKaminsky dev builds seems to not be created anymore - latest is 27.11.2020 while we have quite some changes on master _after_ that date which should have led to further dev releases :/ Fancy taking a look? :)

**Comment by tobiasKaminsky** [comment] 2020-12-02 10:43
https://download.nextcloud.com/android/dev/

There are versions up to day.

**Comment by tobiasKaminsky** [comment] 2020-12-02 10:44
Just tried it with my private mobile: click on get latest version downloaded the one from today.

**Comment by AndyScherzinger** [comment] 2020-12-02 10:45
@tobiasKaminsky the issue was that the fix has been merged after the 27th Nov but there hasn't been a new dev release before tonight...

**Closed by AndyScherzinger** 2020-12-02 10:45 UTC
Labels: bug, needs info/discussion
