### ISSUE TITLE
NC Client Unable to login

### ISSUE THREAD

**Issue by anhoh** [nextcloud/android#9704] opened 2022-01-15 19:58 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getResultData(RemoteOperationResult.java:503)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:80)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:45)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: gta4xlwifi
Model: SM-P610
Id: RQ3A.211001.001
Product: lineage_gta4xlwifi

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 10038399

**Comment by AlvaroBrey** [comment] 2022-01-17 14:15
hey @anhoh, does this happen when inputting the server URL, or later after inputting username and password?

**Comment by anhoh** [comment] 2022-01-17 17:08
Hi @AlvaroBrey This happens after I enter the username and password.

**Comment by AlvaroBrey** [comment] 2022-01-17 19:04
@anhoh is this a public server I can test, or is it private? I've been trying to track this bug down for a while now and I haven't been able to reproduce it.

**Comment by anhoh** [comment] 2022-01-17 19:29
Sorry, this is my private server.
It only happens via dyndns. With my local IP address it works fine.

**Comment by AlvaroBrey** [comment] 2022-01-17 19:40
> @AlvaroBrey Sorry, this is my private server. It only happens via dyndns. With my local IP address it works fine.

Ok, that's a start. By any chance does your domain have both A (IPv4) and AAAA (IPv6) records? If so, can you confirm that the server is accessible both via the IPv4 and IPv6 addresses?

Additionally, if at all possible please upload device logs (https://github.com/nextcloud/android#getting-debug-info-via-logcat-mag). Especially interested in sections containing the line: `Exception while getting OC user information`

**Comment by anhoh** [comment] 2022-01-17 20:35
@AlvaroBrey The domain has IPv4 and IPv6 entries but my provider does not natively support IPv6 addresses. The router generates an IPv6 connection with a tunnel protocol. The server is only accessible via IPv4.
Now I have disabled the IPv6 tunneling in the router and the connection to Nextcloud also works via dyndns.
Maybe this is the key.

**Comment by AlvaroBrey** [comment] 2022-01-18 08:33
@anhoh Nice! In an upcoming update, the app will fallback to IPv4 if IPv6 connection is not working properly (https://github.com/nextcloud/android-library/pull/793) so this would be working with no extra steps on your part.

When you have the IPv6 tunneling active, can you connect via IPv6 in a browser?

**Comment by anhoh** [comment] 2022-01-18 17:21
Very good. Thank you.
No, I can't connect with IPv6 in the browser either.

**Comment by AlvaroBrey** [comment] 2022-01-18 19:47
Okay, then this can be considered a duplicate of #7400 , and closed. Thank you!

**Closed by AlvaroBrey** 2022-01-18 19:47 UTC
Labels: bug, needs info/discussion
