### ISSUE TITLE
External page (Movim) does not allow login through app

### ISSUE THREAD

**Issue by poVoq** [nextcloud/android#1241] opened 2017-07-29 00:14 UTC
### Actual behaviour
I have Movim (movim.eu) installed as a external website in my Nextcloud 12 and it works fine both on a desktop browser and a mobile browser. However in the Nextcloud app the login button stays greyed out and it is not possible to log in.

### Expected behaviour
It should work just like in the normal mobile browser.
 
### Steps to reproduce
1. Install movim.eu (or a local instance) as an external page in Nextcloud
2. Open Nextcloud Android app
3. Try to log-in using your XMPP credentials

### Environment data
Android version: 7.1.2 (Linage OS)

Device model: Asus Zenfone2

Stock or customized system: Official Linage OS

Nextcloud app version: 1.4.2

Nextcloud server version: 12.0.0.

Also see:
https://github.com/movim/movim/issues/425

How can I view the logs on the Nextcloud Android App for external pages?

**Comment by tobiasKaminsky** [comment] 2017-07-29 07:06
I tried it with this site https://nl.movim.eu/?login and it seems as there is some kind of enabling the login button after loading the site.
Currently I do not have an idea what the problem is as we have enabled javascript...

**Comment by mario** [comment] 2017-08-01 11:46
Maybe the DOM thing we just worked on moments ago? We'll see ...

**Comment by tobiasKaminsky** [comment] 2017-08-01 12:18
Good hint :+1: 
I tried it with emulator and it works here.

**Comment by tobiasKaminsky** [comment] 2017-12-20 13:45
Closing as PR was merged.

**Closed by tobiasKaminsky** 2017-12-20 13:45 UTC
Labels: bug
