### ISSUE TITLE
No Upload with "Sharing"

### ISSUE THREAD

**Issue by michaelletzgus** [nextcloud/android#7637] opened 2020-12-09 11:50 UTC
### Steps to reproduce
1. Select a photo in the gallery
2. Select "share"
3. Select the Nextcloud App
4. Select the directory and/or confirm with "Upload"

### Expected behaviour
- File should be uploaded

### Actual behaviour
- Nothing

### Environment data
Android version: 7.1.1

Device model: SM-J510FN

Stock or customized system: Stock

Nextcloud app version: 3.14.1

Nextcloud server version: 20.0.2.2

Reverse proxy: no

#### Web server error log
```
Nothing happens on the server...

**Comment by jurviz** [comment] 2020-12-09 12:07
Same bug when trying to share a file from download folder.
Nextcload App: 3.14.1
Device Samsung Tab S2 (SM-T815)
Android 7.0
Nextcloud Server: 18.0.11

**Comment by AndyScherzinger** [comment] 2020-12-09 12:21
Duplicate of #7587

**Closed** 2020-12-09 12:21 UTC
Labels: bug
