### ISSUE TITLE
Nextcloud crash when browsing activities

### ISSUE THREAD

**Issue by Coryvmcs1** [nextcloud/android#6604] opened 2020-08-01 07:18 UTC
Open nextcloud app and click on activities. Start scrolling and app crashes. This is on plus 8 device. 

************ CAUSE OF ERROR ************

java.lang.NumberFormatException: For input string: "danielle"
at java.lang.Integer.parseInt(Integer.java:615)
at java.lang.Integer.parseInt(Integer.java:650)
at com.owncloud.android.ui.adapter.ActivityListAdapter.createThumbnailNew(ActivityListAdapter.java:269)
at com.owncloud.android.ui.adapter.ActivityListAdapter.onBindViewHolder(ActivityListAdapter.java:237)
at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7707)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus8TMO
Model: IN2017
Id: QKQ1.191222.002
Product: OnePlus8TMO

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2006102149

**Comment by tobiasKaminsky** [comment] 2020-08-05 08:55
Duplicate of #6643

**Closed by tobiasKaminsky** 2020-08-05 08:55 UTC
Labels: bug
