### ISSUE TITLE
My next cloud app crashed after turning on auto upload 

### ISSUE THREAD

**Issue by ss-ar** [nextcloud/android#13774] opened 2024-10-12 07:05 UTC
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at com.owncloud.android.ui.adapter.OCFileListAdapter.limitToPersonalFiles(OCFileListAdapter.java:1074)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:741)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1359)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1308)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1297)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onActivityCreated(OCFileListFragment.java:422)
    at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3156)
    at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:619)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
    at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:641)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onNewIntent(FileDisplayActivity.java:558)
    at android.app.Activity.performNewIntent(Activity.java:8113)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1409)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1422)
    at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3743)
    at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3755)
    at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:53)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7945)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `Nokia`
* Device: `MNR`
* Model: `Nokia C30`
* Id: `RP1A.201005.001`
* Product: `Monster_00WW`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `00WW_1_91C`

**Comment by joshtrichards** [comment] 2024-10-15 13:37
Duplicate of #12908 
Fixed in #12930

**Closed by joshtrichards** 2024-10-15 13:37 UTC
Labels: bug, performance: NPE :no_entry_sign:, stable-3.29
