### ISSUE TITLE
Crash on mp3 playback

### ISSUE THREAD

**Issue by ozzi-** [nextcloud/android#9313] opened 2021-11-19 07:18 UTC
### Steps to reproduce
1. Start playing an mp3 file with the apps media player (it does not matter if the file is downloaded or streamed)
2. Pause playback and lock screen (or wait until it locks itself)
3. Unlock phone and click play

### Expected behaviour
The playback should continue

### Actual behaviour
Toast message "the build-in media player is unable to play the media file"
When clicking on "back", the app crashes (see exception below)

### Environment data
Android version: 11

Device model:  Mi A3

Stock or customized system: Stock Android One

Nextcloud app version: 30170190

Nextcloud server version: 22.2.0

Reverse proxy: -

### Logs

```
********** CAUSE OF ERROR **********

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{7765573 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2006)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7698)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

********** APP INFORMATION **********
ID: com.nextcloud.client
Version: 30170190
Build flavor: generic

********** DEVICE INFORMATION **********
Brand: Xiaomi
Device: laurel_sprout
Model: Mi A3
Id: RKQ1.200903.002
Product: laurel_sprout_eea

********** FIRMWARE **********
SDK: 30
Release: 11
Incremental: V12.0.13.0.RFQEUXM
```

**Comment by AlvaroBrey** [comment] 2021-11-19 08:49
This is a duplicate of #8686, and also should be fixed in version 3.18.0, which was released yesterday. Please update your app :)

**Comment by AlvaroBrey** [comment] 2021-11-19 08:49
Duplicate of #8686

**Closed by AlvaroBrey** 2021-11-19 08:49 UTC
Labels: bug

**Comment by ozzi-** [comment] 2021-11-19 09:03
2 fast for me :) great looking forward
