### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by TimotheEmber** [nextcloud/android#7247] opened 2020-11-06 15:20 UTC
### Steps to reproduce
1. Install app on android
2. open app
3. start dark mode

### Expected behaviour
- it should look good

### Actual behaviour
- The colors are not correct on the buttons

**Comment by AndyScherzinger** [comment] 2020-11-06 15:27
@TimotheEmber could you please post a screenshot so we can see which buttons you think don't look good? We can`t guess them since we don't know if you set a server-side color, if it is all or just some buttons, which version of the Android app you are referring to.

**Comment by TimotheEmber** [comment] 2020-11-06 16:08
Hello
![screen](https://user-images.githubusercontent.com/50056377/98388162-ad30dd80-2052-11eb-86b2-ab75534fc1bb.jpeg)

Sorry for the previews description.
Android version: 10
Dark mode
When creating a folder the create and cancel buttons are barely visible.


Thank you
Tim

**Comment by AndyScherzinger** [comment] 2020-11-06 16:11
Ah, you have black (or a very, very dark grey set as primary color on the server, right?

**Comment by TimotheEmber** [comment] 2020-11-06 16:45
Yes

**Comment by aqaqsubin** [comment] 2020-11-12 15:42
It seems to be reported in 6680 Issue.
Duplicate of #6680

**Comment by AndyScherzinger** [comment] 2020-11-12 22:24
Very likely @aqaqsubin. So @TimotheEmber can you check if this changes if you switch between system setting and dark (given you set your system to dark of course).

I guess though that it works in this scenario and it is just that it may not be light enough.

**Closed** 2020-11-17 12:18 UTC
Labels: bug, needs info/discussion
