### ISSUE TITLE
Crash when opening settings for calender and contact backup

### ISSUE THREAD

**Issue by DKX47** [nextcloud/android#9324] opened 2021-11-20 06:30 UTC
### Steps to reproduce
1. Open the settings for contact and calendar backup repeatly
2. 
3. 

### Expected behaviour
- see buttons for doing the backup now and restoring 

### Actual behaviour
- only the button for doing the backup ist show, or
- the app crashes

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to read from field 'com.google.android.material.button.MaterialButton com.owncloud.android.databinding.BackupFragmentBinding.contactsDatepicker' on a null object reference
	at com.owncloud.android.ui.fragment.contactsbackup.BackupFragment$1.onPostExecute(BackupFragment.java:281)
	at com.owncloud.android.ui.fragment.contactsbackup.BackupFragment$1.onPostExecute(BackupFragment.java:252)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: gplay

**Comment by joshtrichards** [comment] 2023-10-14 00:18
Duplicate of #9595 
Fixed in #9606

**Closed by joshtrichards** 2023-10-14 00:18 UTC
Labels: bug, feature: contacts and calendar backup
