### ISSUE TITLE
Preview not available for custom mime type

### ISSUE THREAD

**Issue by fancycode** [nextcloud/android#3649] opened 2019-02-18 14:41 UTC
### Actual behaviour
- We have an app that adds preview support for a custom filetype with a dedicated mime-type through the regular preview API of Nextcloud (on the server).
- The preview thumbnails are shown in the web interface (files app) and the iOS app.
- The preview thumbnails are *not* shown in the Android app.

### Expected behaviour
- Preview thumbnails should also be visible in the Android app.

According to @marinofaggiana, he is checking a `hasPreview` property of the files to determine if he should load and show the thumbnail or not. He is not checking the mime-type or filename for known image formats.

**Comment by mario** [comment] 2019-02-18 15:10
So, I did check the hasPreview in the Talk app initially as well - the issue is it will be false if the preview generator didn't run yet as well. So I just ignore this value right now and try to fetch preview all the time, if it fails then I set the icon according to supported mimetypes in the NC server (basically, copy/paste of the supported mimetype icons - really, only a few mimetypes are properly supported).

No idea what we do in the Files app really as I haven't looked into this part of the code, but thought this might be relevant.

**Comment by AndyScherzinger** [comment] 2019-02-18 15:32
Probably @tobiasKaminsky knows afaik we just check the mime type at the moment to see if it is an image or a video and then call the server.

**Comment by tobiasKaminsky** [comment] 2019-02-19 07:08
We are also using "hasPreview".
@rullzer when is this value set to true? It should not be "has currently a preview available", but "there is a preview generator capable of doing a preview".

With later approach, even for first-time images "hasPreview" will be true, but then be generated on the fly and then shown in the app.

**Comment by mario** [comment] 2019-02-19 07:50
Ah ok, this would be good to know.

**Comment by rullzer** [comment] 2019-02-19 12:52
We check if a provider is available (else it also would nto work for jpg files that are just uploaded for example).

https://github.com/nextcloud/server/blob/ade61d8b433be7d1ebcc4e50e718993a125b97f1/lib/private/PreviewManager.php#L241

**Comment by fancycode** [comment] 2019-03-08 10:09
Without understanding too much of the Android code, here are two paths that check the mimetype to determine if a thumbnail is available:
https://github.com/nextcloud/android/blob/0cdcf970c6ae6d86ad7f2da85a943d7e96e7ef84/src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java#L218
https://github.com/nextcloud/android/blob/b784d841211e34f516b8d05768bcc1d5024380b5/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java#L704

So at least these don't evaluate the `hasPreview` flag. However I might be completely wrong and they are unrelated to showing thumbnails in the file list of the app.

@rullzer we register a provider for our files on the server and thumbnails are working both in the browser (regular files app) and the iOS app, so this is working fine.

**Comment by tobiasKaminsky** [comment] 2019-03-08 11:47
@fancycode the first code is for local files.
The second is used for really showing the full image.

What you are really looking for is:
https://github.com/nextcloud/android/blob/087ed97e1aaff3055a7d4b6971600958fccf3348/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java#L467

This is the adapter that renders the list for files on nextcloud.

**Comment by fancycode** [comment] 2019-03-08 11:52
Ah thanks :smiley:

However that also checks for `(MimeTypeUtil.isImage(file) || MimeTypeUtil.isVideo(file))` in the same condition:
https://github.com/nextcloud/android/blob/087ed97e1aaff3055a7d4b6971600958fccf3348/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java#L466

This fails for our mimetype which is `application/vnd.XXXX` for our vendor-specific file type.

**Comment by tobiasKaminsky** [comment] 2019-03-08 12:56
Hm. Right. It should be sufficient to have a check for remoteId (as we need this for creating the preview) and isPreviewAvailable().

Do you have a test server, where I quickly could check if this is enough?

**Comment by fancycode** [comment] 2019-03-08 13:06
Sure, I just sent you an email with further information.

**Comment by tobiasKaminsky** [comment] 2019-03-13 19:49
@fancycode I tested it on your web server and created a PR for it:
https://github.com/nextcloud/android/pull/3752

After merge it will be in next dev version and then in next 3.6.0 version.

**Closed** 2019-03-13 20:05 UTC
Labels: bug

**Comment by fancycode** [comment] 2019-03-14 09:44
@tobiasKaminsky great, thanks!
