### ISSUE TITLE
Couldn't read row 893, col 3 from CursorWindow

### ISSUE THREAD

**Issue by ways** [nextcloud/android#10223] opened 2022-05-10 04:49 UTC
Error from phone app on opening "media".

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Couldn't read row 893, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetString(Native Method)
    at android.database.CursorWindow.getString(CursorWindow.java:465)
    at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
    at android.database.CursorWrapper.getString(CursorWrapper.java:137)
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:957)
    at com.owncloud.android.datamodel.FileDataStorageManager.getGalleryItems(FileDataStorageManager.java:2220)
    at com.owncloud.android.datamodel.FileDataStorageManager.getAllGalleryItems(FileDataStorageManager.java:2165)
    at com.owncloud.android.ui.adapter.GalleryAdapter.showAllGalleryItems(GalleryAdapter.kt:149)
    at com.owncloud.android.ui.fragment.GalleryFragment.showAllGalleryItems(GalleryFragment.java:263)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.onPostExecute(GallerySearchTask.java:120)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.onPostExecute(GallerySearchTask.java:48)
    at android.os.AsyncTask.finish(AsyncTask.java:695)
    at android.os.AsyncTask.access$600(AsyncTask.java:180)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6718)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `generic`

### Device information
* Brand: `Fairphone`
* Device: `FP3`
* Model: `FP3`
* Id: `PQ3A.190801.002`
* Product: `FP3`

### Firmware
* SDK: `28`
* Release: `9`
* Incremental: `eng.root.20220328.163412`

**Comment by ways** [comment] 2022-05-10 04:51
Might be duplicate of  #10213

**Comment by AlvaroBrey** [comment] 2022-05-10 08:17
Actually a duplicate of #9948, but thank you @ways !

**Closed by AlvaroBrey** 2022-05-10 08:17 UTC
