### ISSUE TITLE
Android app crash on log in

### ISSUE THREAD

**Issue by Ben2424** [nextcloud/android#10896] opened 2022-10-23 18:49 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Open app
Input server IP address

### Expected behaviour

Putting server IP into login would result in getting username prompt

### Actual behaviour

App immediately crashes instead

### Android version

12

### Device brand and model

OnePlus 10t

### Stock or custom OS?

Stock

### Nextcloud android app version

Unavailable

### Nextcloud server version

Nextdoor hub II

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.LinearLayout com.owncloud.android.databinding.SslUntrustedCertLayoutBinding.getRoot()' on a null object reference
    at com.owncloud.android.ui.dialog.SslUntrustedCertDialog.onCreateDialog(SslUntrustedCertDialog.java:173)
    at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665)
    at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579)
    at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1752)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:238)
    at android.os.Looper.loop(Looper.java:349)
    at android.app.ActivityThread.main(ActivityThread.java:8241)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220190`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OP5552L1`
* Model: `CPH2417`
* Id: `SKQ1.220303.001`
* Product: `CPH2417`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `S.202209141911`

**Comment by AlvaroBrey** [comment] 2022-10-24 07:40
Duplicate of #10868

**Closed by AlvaroBrey** 2022-10-24 07:40 UTC
Labels: bug
