### ISSUE TITLE
Android app keeps crashing suddenly

### ISSUE THREAD

**Issue by webnar** [nextcloud/android#7291] opened 2020-11-10 18:29 UTC
### Steps to reproduce
1.  Open photo
2. Open video
3. Open ebook

### Expected behaviour
- opens media

### Actual behaviour
- app crashes

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
9
Device model: 
Samsung s10
Stock or customized system:
Stock
Nextcloud app version:
Beta
Nextcloud server version:
20.0.1
Reverse proxy:
Nginx
#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e5261f4 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2188)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond1
Model: SM-G973F
Id: QP1A.190711.020
Product: beyond1lteeea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G973FXXU8DTH7

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2020-11-11 08:36
Duplicate of #6905, as it is the same root cause.

**Closed by tobiasKaminsky** 2020-11-11 08:36 UTC
Labels: bug
