### ISSUE TITLE
Bug without having opened the app

### ISSUE THREAD

**Issue by Tojaw** [nextcloud/android#5673] opened 2020-03-16 21:52 UTC
### Steps to reproduce
1. App is installed

### Expected behaviour
- Nothing

### Actual behaviour
- It opens and shows the error message.

### Environment data
Android version: 8.0

Device model: Huawei P10 lite (WAS-TL 10)

Stock or customized system: EMUI 8.0

Nextcloud app version: 30110052

Nextcloud server version: ?

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/data/app/com.nextcloud.client-cF5pUkQO7LZxzzfC0SNe5Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-cF5pUkQO7LZxzzfC0SNe5Q==/lib/arm64, /data/app/com.nextcloud.client-cF5pUkQO7LZxzzfC0SNe5Q==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWWAS-H
Model: WAS-TL10
Id: HUAWEIWAS-TL10
Product: WAS-TL10

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 371(C636)

**Comment by AndyScherzinger** [comment] 2020-03-17 12:32
Duplicate of #4675

**Comment by AndyScherzinger** [comment] 2020-03-17 12:32
@Tojaw you likely received a push notification

**Closed by AndyScherzinger** 2020-03-17 12:32 UTC
Labels: bug
