### ISSUE TITLE
Crash on create folder, method custom folder

### ISSUE THREAD

**Issue by dtsoden** [nextcloud/android#5072] opened 2019-12-28 18:24 UTC
### Steps to reproduce
1. In auto uploads, setup custom folder
2. Pick local sync source
3. When choosing destination folder, create a new folder and the app crashes after folder name is given.

### Expected behaviour
- create new destination folder

### Actual behaviour
- app crashes

### Environment data
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.ui.dialog.CreateFolderDialogFragment.onClick(CreateFolderDialogFragment.java:139)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6990)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: crownqltesq
Model: SM-N960U
Id: PPR1.180610.011
Product: crownqltesq

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: N960USQS3CSK1

**Comment by AndyScherzinger** [comment] 2020-01-09 15:15
duplicate of #4792

@dtsoden where do you create the folder? in the root directory or a sub-directory of the user?

**Closed by AndyScherzinger** 2020-01-09 15:15 UTC
Labels: bug
