### ISSUE TITLE
Nextcloud crashing when opening the Media tab

### ISSUE THREAD

**Issue by masx14** [nextcloud/android#10410] opened 2022-06-19 09:28 UTC
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Couldn't read row 928, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetString(Native Method)
    at android.database.CursorWindow.getString(CursorWindow.java:469)
    at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
    at android.database.CursorWrapper.getString(CursorWrapper.java:141)
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:957)
    at com.owncloud.android.datamodel.FileDataStorageManager.getGalleryItems(FileDataStorageManager.java:2224)
    at com.owncloud.android.datamodel.FileDataStorageManager.getAllGalleryItems(FileDataStorageManager.java:2169)
    at com.owncloud.android.ui.preview.PreviewImagePagerAdapter.<init>(PreviewImagePagerAdapter.java:124)
    at com.owncloud.android.ui.preview.PreviewImageActivity.initViewPager(PreviewImageActivity.java:149)
    at com.owncloud.android.ui.preview.PreviewImageActivity.onStart(PreviewImageActivity.java:209)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1525)
    at android.app.Activity.performStart(Activity.java:8030)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3637)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:233)
    at android.app.ActivityThread.main(ActivityThread.java:8010)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus7Pro`
* Model: `GM1910`
* Id: `RKQ1.201022.002`
* Product: `OnePlus7Pro_EEA`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `2204061055`

**Comment by AlvaroBrey** [comment] 2022-06-20 10:36
Duplicate of #9948

**Closed by AlvaroBrey** 2022-06-20 10:36 UTC
