### ISSUE TITLE
App crashes on 2FA notification approve when Google analytics is blocked

### ISSUE THREAD

**Issue by schaze** [nextcloud/android#5370] opened 2020-02-01 20:30 UTC
### Steps to reproduce
1. Enable 2FA via Notification
2. Block all ad traffic with a pihole in your network
3. Login in Website
4. Open Android App
5. Open notifications
6. Approve --> login works
7. app crashes because Google analytics is not reachable

### Expected behaviour
- app does not crash

### Actual behaviour
- app crashes

### Environment data
Android version: 10

Device model: OnePlus 7T pro

Stock or customized system:

Nextcloud app version: latest

Nextcloud server version: 18

#### App error log
```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.AnalyticsConnector
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7TPro
Model: HD1913
Id: QKQ1.190716.003
Product: OnePlus7TPro_EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 1912060020

```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by microbrewer** [comment] 2020-02-02 11:55
I keep getting a very similar (the same?) error, but **I do not use 2FA**. I do, however, run LineageOS (Custom OS) with reduced GApps. Apart from the crashes, which are annoying, the Nextcloud App seems to work just fine otherwise.

```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-jC_4zvoCIFmrwmcd1g2Gwg==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-jC_4zvoCIFmrwmcd1g2Gwg==/lib/arm, /data/app/com.nextcloud.client-jC_4zvoCIFmrwmcd1g2Gwg==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Fairphone
Device: FP2
Model: FP2
Id: PQ3A.190801.002
Product: FP2

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 7a815e6105
```

**Comment by AndyScherzinger** [comment] 2020-02-03 09:43
Duplicate of #4675

**Closed by AndyScherzinger** 2020-02-03 09:43 UTC
Labels: bug
