### ISSUE TITLE
Android permission errors pile up for files blocked with Flow - File access control

### ISSUE THREAD

**Issue by solarjoe** [nextcloud/android#8653] opened 2021-07-04 11:13 UTC
### Steps to reproduce
1. Block file upload on the server with a Flow- File access control for a file on Android device
2. Wait

The issue is similar to https://github.com/nextcloud/android/issues/6570

see image
https://github.com/nextcloud/android/issues/6570#issuecomment-723544020

### Expected behaviour
No permission errors should pile up

### Actual behaviour
"Permission errors when writing to folder" or "Permission error" pile up on Android

### Environment data
Android version: 10

Device model: Nokia

Stock or customized system: Stock

Nextcloud app version: 3.16.1

Nextcloud server version: 20.0.9

Is there a solution to this?

**Comment by ChronosX88** [comment] 2021-07-04 23:34
I think it is something that related to Nextcloud Server, not the app. Because app receives "forbidden" error from server, when it shows "Permission error" on upload.

**Comment by solarjoe** [comment] 2021-07-21 15:08
Always 22 notifications pile up. Not sure if this is related to Android or NC app.

**Comment by rarealphacat** [comment] 2021-08-29 09:28
same behavior here. I was unable to upload aac files directly from Android to NC, no problem with my auto upload folder though. First I thought it was due to the file name characters, renamed still couldn't upload. 
Then I changed the file format from aac to mp3 manually and it works!
I wonder if NC has a list of file format whitelist.

**Comment by joshtrichards** [comment] 2024-11-01 22:27
Duplicate of #11372

**Closed by joshtrichards** 2024-11-01 22:27 UTC
Labels: bug, feature: transfers, hotspot: auth failure mgmt, stable-3.16
