### ISSUE TITLE
Ability to pause pending uploads

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#383] opened 2016-11-14 08:56 UTC
A user takes 100 photos and right after the device connects to wlan, all uploads are started (one by one). The user wants to pause the upload as the (slow, not metered) wlan traffic needs to be used somewhere else.

I would put it in the upload pane in the overflow menu as as checkbox "enabled/disabled".

cc: @AndyScherzinger @eppfel @jancborchardt

**Comment by vbauchart** [comment] 2018-04-28 08:36
Another use case : I'm temporary located in an area with very limited bandwith, I'd like to pause synchro

**Comment by jancborchardt** [comment] 2018-05-15 13:51
We could do it like in Netflix on Android and show a menu with:
- Retry (only show when it errored)
- Pause all (or »Pause« when this is the only upload)
- Cancel upload

**Comment by augustseptember** [comment] 2019-05-20 16:02
What are the recent plans or progresses on this feature request? I am really in the need for pausing the auto uploads. Unfortunately i cannot code it myself. 
Thanks for your work!

**Comment by tugcanolgun** [comment] 2021-01-14 20:18
I just wanted to bump this issue. Not having a pause button creates a big problem for me. I have a very limited bandwidth and I would like to be able to pause the uploads.

**Comment by PatriceVigier** [comment] 2021-02-23 15:12
Me too, I just wanted to bump this issue. Not having a pause button creates a big problem for me. I have a very limited bandwidth and I would like to be able to pause the uploads.

**Comment by andreapx** [comment] 2021-08-25 10:15
It would be a really useful option. Any news about it?
I would donate if there was a bounty

**Comment by eka249** [comment] 2021-11-23 20:31
Bumping this issue.
We upload very large files, so it's been a struggle to use Nextcloud.

**Comment by JamesTiberiusKirk** [comment] 2022-06-07 07:20
Bump, especially since half the time upload doesnt work peoperly. Should be able to at least pause it while the connection is flaky. 
When on holidays with bad connection and taking loads of pictures this really is a must.

If y'all open to it I could look into opening a PR in the future as well.

**Comment by much-doge** [comment] 2023-07-10 04:45
Bumping this issue once more, its a (i think) simple feature yet a very useful one as there are many use cases, e.g., when using phone internet data plan and the data is running out, I want to still be able to use my internet without worrying about Nextcloud uploading all the recent photos I took.

**Comment by much-doge** [comment] 2023-07-10 04:48
https://github.com/nextcloud/android/issues/6319 Relevant issue

**Comment by ConnectToTom** [comment] 2023-10-01 16:44
Still relevant issue. Temporary workaround coud be to manually stop the app when it attempts to auto-upload, but that's neither recommmandable (as it requires actively starting the app again) and is not reliable (seems the app is restarted again occasionally - maybe because the android app properies of nextcloud were still open on my device?).

Suggesting additional requirements:
- global option to take into consideration whether the network is metered (do not use metered connections) (this option seems to exist on per folder basis, however nextcloud does not register when the network metering classification is changed but connection is kept)
- whether android 'auto sync' option is enabled .

Thank you for consideration!

**Comment by JonasMayerDev** [comment] 2023-11-29 11:52
I am currently working on a pause function for uploads. I prototyped an implementation to pause single uploads. Furthermore, I plan on implementing a pause all button since this is the most requested feature as far as I am aware. I'm not really sure though how the pause functionality in general should behave. 

In my current implementation, mostly for testing, I added a second button (pause) beside the existing cancel button in the uploads tab. I think this is not optimal because it's easy to click on the wrong button, and it takes away space for displaying the name and (if it would work, currently working on it) the progress of the upload (see screenshots for reference). 
While testing, I asked myself if a pause and cancel for individual uploads is really necessary / if completely removing an upload on cancel should be the default. 

The Idea I came up with:
- add a pause all "toggle" button that pauses every current and future upload when on pause (maybe add a reminder notification to make sure you don't forget to resume again)
- for individual uploads, make pausing the default (I can't think of a case where it would be a problem to first pause and then remove the upload, maybe via a remove all paused?) -> The pause all / resume all button would then replace the current cancel all button?  
- Maybe it also makes sense to add a new group to separate paused from failed uploads  

I think an implementation should tackle all those issues here, where all this has been discussed to some extent:
https://github.com/nextcloud/android/issues/6823
https://github.com/nextcloud/android/issues/3931
https://github.com/nextcloud/android/issues/1256
https://github.com/nextcloud/android/issues/1142

Does this add too much complexity / are there better Ideas on how pausing should behave / could be implemented?
@nextcloud/designers @AndyScherzinger 

![Screenshot_2023-11-29-11-45-44-95_367f977887f4a5f4712ef04f9b973e21](https://github.com/nextcloud/android/assets/43114340/fb3cf65d-e60c-4bf4-b2c8-51e6bf320ab8)
![Screenshot_2023-11-29-12-15-44-72_367f977887f4a5f4712ef04f9b973e21](https://github.com/nextcloud/android/assets/43114340/c8a0188b-d3dd-4438-aba1-91914986fcd6)

**Comment by szaimen** [comment] 2023-11-30 10:58
I think what would be much more useful is being able to globally pause all uploads. So that would mean a different layout would be needed.

**Comment by AndyScherzinger** [comment] 2023-11-30 11:13
Well for the all action(s) the "x" icon could just be replaced with a 3-dot icon and a pop-up menu. Same could be done for the individual items

**Comment by JonasMayerDev** [comment] 2023-11-30 15:11
@AndyScherzinger So, replacing the "x" from the current group with a 3-dot menu where you can cancel and pause all current uploads? A global pause would also affect failed uploads (e.g. file conflict) in the future. Maybe it would make more sense to put a global pause in the top right corner, where right now the 3-dot menu is? Then it would make sense to move the "clear all failed" button from there to the failed group with a 3-dot menu since it is specifically for failed uploads...

**Comment by AndyScherzinger** [comment] 2023-11-30 15:35
the reason for the 3-dot menu is that by design if there is more than one action we usually group them in a menu instead of direct actions.
Grouping failed and Current sounds fine to me, while I would argue to order/group them that way, current first, failed second.

**Comment by JonasMayerDev** [comment] 2023-12-01 00:50
Ok, I've quickly sketched it out now. I think that makes it easier to understand what I mean. 
- Global pause would be at the top and would replace the "clear failed uploads" (which is moved to the corresponding group)
-> On Global pause, every upload when ready to upload (not failed) is moved to pause. Maybe also display a notification to warn the user that all uploads are paused?
- Pausing Uploads would be the default for "current" files

![featureRequest](https://github.com/nextcloud/android/assets/43114340/01256b43-8f09-44cf-a397-68ee3a3e05f5)

What do you think about that suggestion / "vision" of mine?
@AndyScherzinger @szaimen @tobiasKaminsky

**Comment by AndyScherzinger** [comment] 2023-12-01 16:17
@JonasMayerDev makes sense to me 👍 LGTM

**Comment by tobiasKaminsky** [comment] 2024-02-08 06:23
- global pause, nearly finished 
- individual cancel with resume

**Comment by JonasMayerDev** [comment] 2024-02-14 15:45
As @tobiasKaminsky suggested, I split this issue up in 2 parts:
- Individual upload pause functionality, which is implemented in a slightly different way than previously described in this issue. The big difference is that instead of pausing it is called cancellation, because cancellation is the behavior the user already knows, but the behavior is the same (see PR for more information). Merged in this PR: https://github.com/nextcloud/android/pull/12549  
- Global upload pause (including for future uploads) is implemented as described in this issue. Merged in this PR: https://github.com/nextcloud/android/pull/12527

**Closed by JonasMayerDev** 2024-02-14 15:45 UTC
Labels: enhancement, feature: auto upload, feature: sync and upload, connectivity, feature: data usage, 🍀 2024-Spring
