### ISSUE TITLE
Error when creating new folder from Android App

### ISSUE THREAD

**Issue by alcarnes** [nextcloud/android#5664] opened 2020-03-16 03:13 UTC
### Steps to reproduce
1. Go into auto upload
2. Enable a folder for auto upload
3. Select configure
4. Select remote folder
5. Click create folder
6. Type in new folder name and click ok

### Expected behaviour
- Tell us what should happen
Folder should be created for selection

### Actual behaviour
- Java exception

### Environment data

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.ui.dialog.CreateFolderDialogFragment.onClick(CreateFolderDialogFragment.java:140)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6013
Id: QKQ1.190716.003
Product: OnePlus6T

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2002220019
 version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-03-16 08:43
Duplicate of #4792

**Closed by AndyScherzinger** 2020-03-16 08:43 UTC
Labels: bug

**Comment by AndyScherzinger** [comment] 2020-03-16 08:44
@alcarnes Thanks for the report, like commented above I guess it only happens in the root/top folder, so this should be fixed with the next release of the app. We already released RC2 so in case you join as a tester on GPlay you can update to the release candidate and check if the fix is working for you.
