### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by blackfire9** [nextcloud/android#5080] opened 2019-12-30 15:48 UTC
************ CAUSE OF ERROR ************

android.view.InflateException: Binary XML file line #7: Error inflating class android.webkit.WebView
	at android.view.LayoutInflater.createView(LayoutInflater.java:640)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:689)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:748)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
	at com.owncloud.android.authentication.AuthenticatorActivity.onGetServerInfoFinish(AuthenticatorActivity.java:1310)
	at com.owncloud.android.authentication.AuthenticatorActivity.onRemoteOperationFinish(AuthenticatorActivity.java:1209)
	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:727)
	at com.owncloud.android.services.-$$Lambda$OperationsService$2BVgsxDpOpa4JqgzeD7OGZBLSiI.run(lambda)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5944)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:614)
	... 21 more
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x3040002
	at android.content.res.Resources.getText(Resources.java:1334)
	at android.content.res.Resources.getString(Resources.java:1428)
	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:702)
	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:619)
	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:758)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:608)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:546)
	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:312)
	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:97)
	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:264)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:124)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:111)
	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:108)
	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:261)
	at android.webkit.WebView.<init>(WebView.java:557)
	at android.webkit.WebView.<init>(WebView.java:492)
	at android.webkit.WebView.<init>(WebView.java:475)
	at android.webkit.WebView.<init>(WebView.java:462)
	... 24 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: trltechn
Model: SM-N9100
Id: LRX22C
Product: trlteduoszc

************ FIRMWARE ************
SDK: 21
Release: 5.0.1
Incremental: N9100ZCU1BOC5

**Comment by AndyScherzinger** [comment] 2020-01-09 17:30
duplicate of #4943

**Closed by AndyScherzinger** 2020-01-09 17:30 UTC
Labels: bug
