### ISSUE TITLE
"Sync" option only works manually

### ISSUE THREAD

**Issue by dusscloud** [nextcloud/android#5902] opened 2020-04-19 16:24 UTC
### Steps to reproduce
1. through android app, tap the "sync" option on a folder of your nextcloud instance
2. through any other interface (web, deskotp client) add a file "test" in the folder mentionned above
3. on android settings-> account-> nextcloud -> account sync -> files should be enabled 

### Expected behaviour
- the "test" file should be automatically downloaded on the Android phone. 

### Actual behaviour
- nothing happens unless the "sync" option is tapped again on the folder menu in nextcloud app.
If this is the intended behaviour, this should be named "manual sync". Anyway this is not clear as an end-user.

Maybe a time (ex: 30 Min, 1 hour. ..) setting for the app to fetch new files could be implemented if instantaneous sync is not possible ? That is how DavDroid seems to work for calDav/CarDav.

### Environment data
Android version: 9
Device model: Moto G6
Nextcloud app version: 3.11.0
Nextcloud server version: 18.0.3

**Comment by tobiasKaminsky** [comment] 2020-04-20 14:49
We do not have a 2way sync right now.
Only files that are already downloaded are kept up to date.


Duplicate of #19

**Closed by tobiasKaminsky** 2020-04-20 14:49 UTC
Labels: bug

**Comment by dusscloud** [comment] 2020-04-20 14:56
Automatic folder download is not necessary a 2 way sync, but a 1 way sync (is the same way we have today the automatic upload feature).
Anyway, as commented, if not supported this should not be label "sync" but "download" (in case of a folder only as it seems to be supported for a file)

**Comment by tobiasKaminsky** [comment] 2020-04-22 12:03
It is a sync, but a one time sync ;-)

**Comment by christianlupus** [comment] 2024-05-07 07:52
@tobiasKaminsky, am I correct that this is the line to define the label on the Sync button? This is what I get from reading the code. Just wanted to clarify.
