### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Devis168** [nextcloud/android#13878] opened 2024-10-25 18:15 UTC
### Cause of error
```java
Exception in thread "Thread-5" java.lang.IllegalArgumentException: Trying to execute a sync operation with a storage manager for an anonymous account
    at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:49)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$fetchExternalLinks$9(DrawerActivity.java:1231)
    at com.owncloud.android.ui.activity.DrawerActivity.$r8$lambda$oHM2j1MZkviAIdyIFWoI2kSeF9c(Unknown Source:0)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:764)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `lge`
* Device: `judypn`
* Model: `LM-V405`
* Id: `PKQ1.190202.001`
* Product: `judypn_lao_com`

### Firmware
* SDK: `28`
* Release: `9`
* Incremental: `1913500416e18.FGN`

**Comment by joshtrichards** [comment] 2024-10-25 21:11
Duplicate of #13323

**Closed by joshtrichards** 2024-10-25 21:11 UTC
