### ISSUE TITLE
Only folders shown on copy/move

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2220] opened 2018-02-22 13:24 UTC
![2018-02-22-142023](https://user-images.githubusercontent.com/5836855/36540682-99bb60e0-17db-11e8-9b19-39029e73d490.png) ![2018-02-22-142035](https://user-images.githubusercontent.com/5836855/36540680-99a07af0-17db-11e8-9eec-8ef5af7a9e18.png)

Left: source folder, file 1.txt is moved
Right: same folder as "target", but only folders are shown.

If you enter a folder with only files, it would show "no files here", which is wrong.
This activity is used widely across the app, from copy/move to folder picker for synced folders.

Can you imagine any scenario where it would be sane to hide/filter out all files?

@jancborchardt

**Comment by AndyScherzinger** [comment] 2018-02-22 14:18
> Can you imagine any scenario where it would be sane to hide/filter out all files?

Yes the scenario you just mentioned move/copy ;) While I'd say we just shouldn't show this message here but have a nicer visualization of the folder being empty (as in no further folder hierarchy levels)

**Comment by tobiasKaminsky** [comment] 2018-02-22 14:56
Hm. I assumed that it is important to see the files. As with the files you can see additionally check if you have chosen the right directory.

**Comment by AndyScherzinger** [comment] 2018-02-22 15:00
Afair we explicitly changed this due to @jancborchardt's feedback but this was probably years ago....

**Comment by xXSTrikeXx** [comment] 2018-02-23 05:37
Duplicate of #1412

**Comment by tobiasKaminsky** [comment] 2018-02-23 08:04
At least the scenario I pointed out above is "self-made" on android as we explicitly say that we only want to show folders, which is confusing, even for me xD

**Comment by xXSTrikeXx** [comment] 2018-02-23 09:33
@tobiasKaminsky So you mean the bug is: Showing 'no files here' when there still exist some files?
And it is so intentionally based on performance reasons to show only the folders?
So the Fix will be to change the 'no files here' message to 'here are X files, in the case there are still files?
What do you think and plan? Showing all files will be a good ux, but more data consumption?

**Comment by jancborchardt** [comment] 2018-02-25 23:12
The files should absolutely be shown in this view. :) It gives a sense of orientation, and does not cause confusion as to if they are still there or not.

**Comment by tobiasKaminsky** [comment] 2018-02-26 10:08
PR is in #2233

**Closed** 2018-03-14 20:51 UTC
Labels: enhancement, pr exists
