### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by krtpowa** [nextcloud/android#8542] opened 2021-06-07 13:24 UTC
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:929)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWYAL
Model: YAL-L21
Id: HUAWEIYAL-L61
Product: YAL-L21HEEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.1.0.249C431

**Comment by AndyScherzinger** [comment] 2021-06-07 14:00
Duplicate of #8370

**Closed by AndyScherzinger** 2021-06-07 14:00 UTC
Labels: bug
