### ISSUE TITLE
Unable to play video full time

### ISSUE THREAD

**Issue by JAGFx** [nextcloud/android#7216] opened 2020-11-03 07:02 UTC
### Steps to reproduce
1. Open Android app
2. Click on a video 
3. Wait few seconds of playing video

### Expected behaviour
- App crach with a stack trace. 
There mean the app can't play video on foreground.

This video are about 130 Moaned they are created from Blackvue dashcam. 

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: Oxygen 10

Device model: OnePlus 5

Stock or customized system: Stock

Nextcloud app version: 3.14 RC1

Nextcloud server version: 20.1

Reverse proxy: No

### Logs
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e079021 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2039)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5
Model: ONEPLUS A5000
Id: QKQ1.191014.012
Product: OnePlus5

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2006012143

**Comment by AndyScherzinger** [comment] 2020-11-03 08:17
Duplicate of #6905

**Closed by AndyScherzinger** 2020-11-03 08:17 UTC
Labels: bug
