### ISSUE TITLE
Error while moving file to final directory

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#391] opened 2016-11-21 10:42 UTC
From the forums: https://help.nextcloud.com/t/android-app-1-4-0-rc1-released/5203

___

hey,

i have an error with file download. the file is downloaded till 70%. than it display an error.

logcat show's:
```
    11-19 13:31:08.074 I/DownloadRemoteFileOperation(22709): Download of /own/backup/sysiphus/home-16-11-14.tar.bz2.gpg to /storage/emulated/0/nextcloud/tmp/xxxxx/own/backup/sysiphus/home-16-11-14.tar.bz2.gpg: Operation finished with HTTP status code 200 (success)11-19 13:31:08.080 I/DownloadFileOperation(22709): Download of /own/backup/sysiphus/home-16-11-14.tar.bz2.gpg to /storage/emulated/0/nextcloud/xxxxx@own/backup/sysiphus/home-16-11-14.tar.bz2.gpg: Error while moving file to final directory
    11-19 13:31:08.099 D/FileObserverService(22709): Received broadcast intent Intent { act=com.owncloud.android.files.services.FileDownloaderDOWNLOAD_FINISH flg=0x10 (has extras) }
```
the problem is in the latest two beta's and in 1.4.rc1.

here the complete log from the latest beta 20161111:
```
    2016/11/16 15:05:56
    FileObserverService : Starting command Intent { act=com.owncloud.android.services.observer.FileObserverService.action.START_OBSERVATION cmp=com.nextcloud.android.beta/com.owncloud.android.services.observer.FileObserverService }

    2016/11/16 15:05:56
    FileObserverService : Loading all kept-in-sync files from database to start watching them

    2016/11/16 15:05:56
    FolderObserver : Started watching parent folder /storage/emulated/0/nextcloud/GANZ_GEHEIM/own/backup/sysiphus/

    2016/11/16 15:05:56
    FileObserverService : Added /storage/emulated/0/nextcloud/GANZ_GEHEIM/own/backup/sysiphus/home-16-11-04.tar.bz2.gpg to list of observed children

    2016/11/16 15:05:56
    FileDisplayActivity : Received broadcast com.owncloud.android.syncadapter.FileSyncAdapter.EVENT_FULL_SYNC_START

    2016/11/16 15:05:56
    FileActivity : Operations service connected

    2016/11/16 15:05:56
    FileDisplayActivity : Upload service connected

    2016/11/16 15:05:56
    RemoteGetUserQuotaOperation : Exception while getting OC user information Exception : [org.json.JSON.typeMismatch(JSON.java:100), org.json.JSONObject.getJSONObject(JSONObject.java:613), com.owncloud.android.lib.resources.users.RemoteGetUserQuotaOperation.run(RemoteGetUserQuotaOperation.java:141), com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:118), com.owncloud.android.ui.activity.DrawerActivity$4.run(DrawerActivity.java:603), java.lang.Thread.run(Thread.java:818)]

    2016/11/16 15:05:57
    RemoteGetUserQuotaOperation : Exception while getting OC user information Exception : [org.json.JSON.typeMismatch(JSON.java:100), org.json.JSONObject.getJSONObject(JSONObject.java:613), com.owncloud.android.lib.resources.users.RemoteGetUserQuotaOperation.run(RemoteGetUserQuotaOperation.java:141), com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:118), com.owncloud.android.ui.activity.DrawerActivity$4.run(DrawerActivity.java:603), java.lang.Thread.run(Thread.java:818)]

    2016/11/16 15:05:58
    SimpleFactoryManager : getClientFor(OwnCloudAccount ... :

    2016/11/16 15:05:58
    OwnCloudClient #16 : Creating OwnCloudClient

    2016/11/16 15:05:58
    SimpleFactoryManager : new client {GANZ_GEHEIM, 207100085}

    2016/11/16 15:05:58
    Avatar : URI: https://owncloud.mdomann.tk/index.php/avatar/MichaDO/256

    2016/11/16 15:05:58
    OwnCloudClient #16 : REQUEST GET /index.php/avatar/MichaDO/256

    2016/11/16 15:05:58
    DownloadRemoteFileOperation : Download of /own/backup/sysiphus/home-16-11-04.tar.bz2.gpg to /storage/emulated/0/nextcloud/tmp/GANZ_GEHEIM/own/backup/sysiphus/home-16-11-04.tar.bz2.gpg: Operation cancelled by the caller Exception : [com.owncloud.android.lib.resources.files.DownloadRemoteFileOperation.downloadFile(DownloadRemoteFileOperation.java:128), com.owncloud.android.lib.resources.files.DownloadRemoteFileOperation.run(DownloadRemoteFileOperation.java:85), com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136), com.owncloud.android.operations.DownloadFileOperation.run(DownloadFileOperation.java:158), com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136), com.owncloud.android.files.services.FileDownloader.downloadFile(FileDownloader.java:430), com.owncloud.android.files.services.FileDownloader.access$500(FileDownloader.java:68), com.owncloud.android.files.services.FileDownloader$ServiceHandler.handleMessage(FileDownloader.java:382), android.os.Handler.dispatchMessage(Handler.java:102), android.os.Looper.loop(Looper.java:135), android.os.HandlerThread.run(HandlerThread.java:61)]

    2016/11/16 15:05:58
    DownloadFileOperation : Download of /own/backup/sysiphus/home-16-11-04.tar.bz2.gpg to /storage/emulated/0/nextcloud/GANZ_GEHEIM/own/backup/sysiphus/home-16-11-04.tar.bz2.gpg: Operation cancelled by the caller

    2016/11/16 15:05:58
    FileDownloader : Stopping after command with id 1

    2016/11/16 15:05:58
    FileDownloader : Account GANZ_GEHEIM exists

    2016/11/16 15:05:58
    SimpleFactoryManager : getClientFor(OwnCloudAccount ... :

    2016/11/16 15:05:58
    OwnCloudClient #17 : Creating OwnCloudClient

    2016/11/16 15:05:58
    SimpleFactoryManager : new client {GANZ_GEHEIM, 705157962}

    2016/11/16 15:05:58
    FileObserverService : Received broadcast intent Intent { act=com.owncloud.android.files.services.FileDownloaderDOWNLOAD_FINISH flg=0x10 (has extras) }

    2016/11/16 15:05:58
    OwnCloudClient #17 : REQUEST GET /remote.php/webdav/own/backup/sysiphus/etc-16-11-14.tar.bz2.gpg

    2016/11/16 15:05:59
    FileDisplayActivity : onPause() start

    2016/11/16 15:05:59
    FileDisplayActivity : onPause() ending

    2016/11/16 15:05:59
    FileDisplayActivity : onPause() end

    2016/11/16 15:05:59
    Preferences : onCreate(Bundle) starting

    2016/11/16 15:05:59
    Preferences : onStart() starting

    2016/11/16 15:05:59
    SimpleFactoryManager : getClientFor(OwnCloudAccount ... :

    2016/11/16 15:05:59
    OwnCloudClient #18 : Creating OwnCloudClient

    2016/11/16 15:05:59
    Preferences : onResume() starting

    2016/11/16 15:05:59
    SimpleFactoryManager : new client {GANZ_GEHEIM, 15857771}

    2016/11/16 15:06:00
    FileDisplayActivity : onSaveInstanceState() start

    2016/11/16 15:06:00
    FileDisplayActivity : onSaveInstanceState(Bundle) starting

    2016/11/16 15:06:00
    ExtendedListFragment : onSaveInstanceState()

    2016/11/16 15:06:00
    FileDisplayActivity : onSaveInstanceState() end

    2016/11/16 15:06:00
    FileDisplayActivity : onStop() start

    2016/11/16 15:06:00
    FileDisplayActivity : onStop() ending

    2016/11/16 15:06:00
    FileDisplayActivity : onStop() end

    2016/11/16 15:06:02
    Preferences : onPause() ending

    2016/11/16 15:06:02
    LogHistoryActivity : onCreate(Bundle) starting

    2016/11/16 15:06:02
    LogHistoryActivity : onStart() starting

    2016/11/16 15:06:02
    LogHistoryActivity : onResume() starting

    2016/11/16 15:06:02
    Preferences : onSaveInstanceState(Bundle) starting

    2016/11/16 15:06:02
    Preferences : onStop() ending

    2016/11/16 15:06:11
    DownloadRemoteFileOperation : Download of /own/backup/sysiphus/etc-16-11-14.tar.bz2.gpg to /storage/emulated/0/nextcloud/tmp/GANZ_GEHEIM/own/backup/sysiphus/etc-16-11-14.tar.bz2.gpg: Operation finished with HTTP status code 200 (success)

    2016/11/16 15:06:11
    DownloadFileOperation : Download of /own/backup/sysiphus/etc-16-11-14.tar.bz2.gpg to /storage/sdcard1/Android/data/com.nextcloud.android.beta/files/nextcloud/GANZ_GEHEIM/own/backup/sysiphus/etc-16-11-14.tar.bz2.gpg: Error while moving file to final directory

    2016/11/16 15:06:11
    FileDownloader : Stopping after command with id 2
```
whether the nextcloud nor the webserver log shows an error. but this is shared hosting so i can't
increase the loglevel from the webserver. My account is also the admin and i don't use quota'S.

Micha

**Comment by tobiasKaminsky** [comment] 2017-05-12 11:11
maybe some storage / disk usage problem.
Closing as we cannot reproduce it.

**Closed by tobiasKaminsky** 2017-05-12 11:11 UTC
Labels: bug
