### ISSUE TITLE
nextcloud crashes at startup

### ISSUE THREAD

**Issue by dl3it** [nextcloud/android#11313] opened 2023-01-27 13:25 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Install nextcloud-dev from f-droid, start app

### Expected behaviour

App starts

### Actual behaviour

App crashes

`
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:907)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:138)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByEncryptedRemotePath(FileDataStorageManager.java:122)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:118)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2423)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1511)
    at android.app.Activity.performStart(Activity.java:8495)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3800)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2363)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:299)
    at android.app.ActivityThread.main(ActivityThread.java:8109)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20230124`
* Build flavor: `versionDev`

### Device information
* Brand: `Xiaomi`
* Device: `zeus`
* Model: `2201122G`
* Id: `TKQ1.220807.001`
* Product: `zeus_eea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `V13.2.4.0.TLBEUXM`
* `

### Android version

13

### Device brand and model

Xiaomi Mi12Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

20230124

### Nextcloud server version

25.0.3

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:907)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:138)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByEncryptedRemotePath(FileDataStorageManager.java:122)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:118)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2423)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1511)
    at android.app.Activity.performStart(Activity.java:8495)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3800)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2363)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:299)
    at android.app.ActivityThread.main(ActivityThread.java:8109)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20230124`
* Build flavor: `versionDev`

### Device information
* Brand: `Xiaomi`
* Device: `zeus`
* Model: `2201122G`
* Id: `TKQ1.220807.001`
* Product: `zeus_eea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `V13.2.4.0.TLBEUXM`

### Server error logs

```bash
.
```

### Additional information

.

**Comment by AdamLeyshon** [comment] 2023-01-27 14:48
Same here
### App information
* ID: `com.nextcloud.android.beta`
* Version: `20230124`
* Build flavor: `versionDev`

### Device information
* Brand: `google`
* Device: `raven`
* Model: `Pixel 6 Pro`
* Id: `TQ1A.230105.002`
* Product: `raven`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `9325679`

**Comment by x4v13r0** [comment] 2023-01-28 08:23
Same with slightly earlier version 20230121 on older phone

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20230121`
* Build flavor: `versionDev`

### Device information
* Brand: `samsung`
* Device: `a5xeltexx`
* Model: `SM-A510F`
* Id: `QQ3A.200805.001`
* Product: `lineage_a5xelte`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `10039350`

**Comment by AlvaroBrey** [comment] 2023-01-30 10:07
Duplicate of #11305

**Closed by AlvaroBrey** 2023-01-30 10:07 UTC
Labels: bug, dev version
