### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by tomcat78** [nextcloud/android#7126] opened 2020-10-21 19:43 UTC
I just opened a directory

************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 1171, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProvider.delete(ContentProvider.java:1757)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:435)
	at android.content.ContentResolver.delete(ContentResolver.java:2289)
	at android.content.ContentResolver.delete(ContentResolver.java:2255)
	at com.owncloud.android.datamodel.FileDataStorageManager.removeFolderInDb(FileDataStorageManager.java:621)
	at com.owncloud.android.datamodel.FileDataStorageManager.removeFolder(FileDataStorageManager.java:596)
	at com.owncloud.android.operations.RefreshFolderOperation.removeLocalFolder(RefreshFolderOperation.java:390)
	at com.owncloud.android.operations.RefreshFolderOperation.checkForChanges(RefreshFolderOperation.java:351)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:227)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: taimen
Model: Pixel 2 XL
Id: RP1A.201005.004
Product: taimen

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 6782484

**Comment by tobiasKaminsky** [comment] 2020-10-27 11:41
Duplicate of #6688

**Closed by tobiasKaminsky** 2020-10-27 11:41 UTC
Labels: bug
