### ISSUE TITLE
file replacement during upload keeps asking what to do even after choosing

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#6676] opened 2020-08-08 06:15 UTC
when you upload a file and replace the existing one, the upload always remains and keeps asking you whether to replace files or leave the new one continuously, because even after choosing, the upload item in the app is not removed and I have to do it manually.

in practice if I choose replace with new version, everything seems ok replace, but after a few minutes the application continues the synchronization asking me again what to do.  I noticed that the upload item still bears the synchronization even having already chosen what to do.

**Comment by pawlosck** [comment] 2020-08-11 08:33
I have the same problem

**Comment by tobiasKaminsky** [comment] 2020-08-28 09:33
Duplicate of #6841

**Closed by tobiasKaminsky** 2020-08-28 09:33 UTC
Labels: bug

**Comment by tigernero79** [comment] 2020-10-24 17:30
@tobiasKaminsky in version 20.0.0.1 rc1 this bug has come back.
