### ISSUE TITLE
Play mp3 crash

### ISSUE THREAD

**Issue by ecejuan** [nextcloud/android#8937] opened 2021-09-03 21:48 UTC
### Steps to reproduce
1. Play mp3 and wait for phone sleep
2. 
3. 

### Expected behaviour
- Tell us what should happen
Juat play the same song

### Actual behaviour
- Tell us what happens
Crash

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{83d3432 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2240)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a50
Model: SM-A505FN
Id: RP1A.200720.012
Product: a50eea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: A505FNXXS9CUF1

**Comment by AlvaroBrey** [comment] 2021-09-06 14:52
Duplicate of #8909

**Closed by AlvaroBrey** 2021-09-06 14:52 UTC
Labels: bug
