### ISSUE TITLE
Error by upload

### ISSUE THREAD

**Issue by Stoony1** [nextcloud/android#10109] opened 2022-04-23 13:30 UTC
### Cause of error
```java
Exception in thread "main" android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{bd58030 u0 com.nextcloud.client/com.owncloud.android.files.services.FileUploader}
    at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2147)
    at android.app.ActivityThread.access$2900(ActivityThread.java:310)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2376)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8663)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200052`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `d2s`
* Model: `SM-N975F`
* Id: `SP1A.210812.016`
* Product: `d2seea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `N975FXXU7HVCH`

**Comment by AlvaroBrey** [comment] 2022-04-28 08:09
Hi @Stoony1, can you reproduce this bug reliably? If so, what are the steps to reproduce it?

**Comment by AlvaroBrey** [comment] 2022-05-20 07:26
Duplicate of #9617

**Closed by AlvaroBrey** 2022-05-20 07:26 UTC
Labels: bug, needs info/discussion
