### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by RetroRock** [nextcloud/android#7771] opened 2021-01-02 11:05 UTC
### Steps to reproduce
1. Install Nextcloud
2. Open app
3. Get an error

### Expected behaviour
- See sign up screen

### Actual behaviour
- Error message:
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalArgumentException: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.
	at android.app.ActivityThread.installProvider(ActivityThread.java:6747)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6289)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6204)
	at android.app.ActivityThread.access$1200(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.IllegalArgumentException: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.
	at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(Unknown Source:8)
	at com.google.firebase.iid.FirebaseInstanceId.checkRequiredFirebaseOptions(com.google.firebase:firebase-iid@@20.2.3:52)
	at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@20.2.3:2)
	at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@20.2.3:1)
	at com.google.firebase.iid.Store.checkForRestore(com.google.firebase:firebase-iid@@20.2.3:15)
	at com.google.firebase.iid.Store.<init>(com.google.firebase:firebase-iid@@20.2.3:5)
	at com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase:firebase-iid@@20.2.3:16)
	at com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase:firebase-iid@@20.2.3:8)
	at com.google.firebase.iid.Registrar.lambda$getComponents$0$Registrar(com.google.firebase:firebase-iid@@20.2.3:26)
	at com.google.firebase.iid.Registrar$$Lambda$0.create(Unknown Source:0)
	at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
	at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
	at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(com.google.firebase:firebase-components@@16.0.0:158)
	at com.google.firebase.FirebaseApp.initializeAllApis(com.google.firebase:firebase-common@@19.3.0:563)
	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:304)
	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:268)
	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:253)
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@19.3.0:51)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1940)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1915)
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@19.3.0:45)
	at android.app.ActivityThread.installProvider(ActivityThread.java:6742)
	... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: dreamlte
Model: SM-G950F
Id: PPR1.180610.011
Product: dreamltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G950FXXSBDTJ1

**Comment by AndyScherzinger** [comment] 2021-01-05 20:56
@tobiasKaminsky is this fixed with 3.14.2?

**Comment by tobiasKaminsky** [comment] 2021-02-04 14:27
@RetroRock does this still happen?

**Comment by tobiasKaminsky** [comment] 2021-02-11 07:01
Duplicate of #7616

**Closed by tobiasKaminsky** 2021-02-11 07:01 UTC
Labels: bug, needs info/discussion
