### ISSUE TITLE
error

### ISSUE THREAD

**Issue by IvanLeka** [nextcloud/android#13896] opened 2024-10-29 03:09 UTC
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: ScrollView can host only one direct child
    at android.widget.ScrollView.addView(ScrollView.java:597)
    at com.google.android.material.snackbar.BaseTransientBottomBar$SnackbarBaseLayout.addToTargetParent(BaseTransientBottomBar.java:1344)
    at com.google.android.material.snackbar.BaseTransientBottomBar.showView(BaseTransientBottomBar.java:783)
    at com.google.android.material.snackbar.BaseTransientBottomBar$1.handleMessage(BaseTransientBottomBar.java:262)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:9063)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `e3q`
* Model: `SM-S928B`
* Id: `UP1A.231005.007`
* Product: `e3qxxx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S928BXXS3AXHD`

**Comment by joshtrichards** [comment] 2024-10-29 12:48
Duplicate of #13003

**Closed by joshtrichards** 2024-10-29 12:48 UTC
Labels: bug, performance: ISE/IAE :confused:, stable-3.29
