### ISSUE TITLE
Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by NexusJLK** [nextcloud/android#11317] opened 2023-01-28 12:10 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Update NextCloud app

### Expected behaviour

Install new Version though download from f-droid repository 

### Actual behaviour

Error message appears (See log)

### Android version

7.1.2

### Device brand and model

Google Nexus 5

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

/e/OS 0.19-20211023142427

### Nextcloud server version

25.0.3

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6186)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:907)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:138)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByEncryptedRemotePath(FileDataStorageManager.java:122)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:118)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2423)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
    at android.app.Activity.performStart(Activity.java:6701)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2647)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6186)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20230124`
* Build flavor: `versionDev`

### Device information
* Brand: `google`
* Device: `hammerhead`
* Model: `Nexus 5`
* Id: `NJH47F`
* Product: `hammerhead`

### Firmware
* SDK: `25`
* Release: `7.1.2`
* Incremental: `09f5261854`

**Comment by AlvaroBrey** [comment] 2023-01-30 10:02
Duplicate of #11305

**Closed by AlvaroBrey** 2023-01-30 10:02 UTC
Labels: bug

**Comment by NexusJLK** [comment] 2023-02-03 09:51
Thank you for your fast reply.  I installed version 3.23.0 (APK download from F-Droid) and access to my Nextcloud service is now running smoothly again.
