### ISSUE TITLE
Connection fails if ipv6 connection do not work properly

### ISSUE THREAD

**Issue by zolokonst** [nextcloud/android#7839] opened 2021-01-14 19:16 UTC
### Steps to reproduce
1. Use ipv6-ready connection for both client and server. 
2. Simulate the ipv6 connection failure on router, so dns name of your server should be resolved on a client. But server should not be reachable by resolved ipv6 address. IPv4 connection should work fine. 
3. Go to login page in the android app and try to log in to your server. You'll see server error. If you already logged in, just try to upload something. You'll see the same error. 
![Screenshot_20210114-221302](https://user-images.githubusercontent.com/17275257/104637351-bcb54e00-56b5-11eb-9345-d86c8f65dedc.png)

### Expected behaviour
- App should use working ipv4 connection, if ipv6 fails. 

### Actual behaviour
- app doesnt communicate properly with the server. 

### Can you reproduce this problem on https://try.nextcloud.com
Yes
### Environment data
Android version:
7.1.1
Device model: 
Sony Xperia performance x F8132
Stock or customized system:
Stock
Nextcloud app version:
3.4.2
Nextcloud server version:
Don't care
Reverse proxy:
No
#### Web server error log
```
Insert your webserver log here
```
#### Nextcloud log (data/nextcloud.log)
```
I don't see the log file in the data folder. 

```

**Comment by zolokonst** [comment] 2021-01-15 21:09
I found this after updating app to the latest version. Ipv6 of my ICP isn't stable, but there was no such problem on a previous installed app version. Unfortunately, I can not say, which version was installed before updating.

**Comment by KopfKrieg** [comment] 2021-01-30 12:43
> I found this after updating app to the latest version. Ipv6 of my ICP isn't stable, but there was no such problem on a previous installed app version.

Same situation here. I can confirm that version 3.15.0 RC1 and 3.14.2 RC? both have this issue.

Using my intance's webinterface on the same device however works fine, so it's an issue with the app.

**Comment by Carsten1987** [comment] 2021-02-15 17:17
I have the same problem. Connect via Nextcloud-App is not possible. But Connect with Nextcloud-Talk is working!
Android 9
Kernel: 4.4.11

**Comment by Carsten1987** [comment] 2021-02-16 18:15
Did an additional test and Downloaded 3.13.1 from GitHub. With this Version Connect works fine!

**Comment by tobiasKaminsky** [comment] 2021-02-17 09:55
If IPv6 is available app uses it. So please configure your server correctly to work with v6 or disable it at all.
The app cannot try v6 and then use v4 for every new connection.

**Comment by KopfKrieg** [comment] 2021-02-17 17:47
> The app cannot try v6 and then use v4 for every new connection.

Please reopen the issue. IPv4/6 fallback in case the other address is not working is a common standard, the software should be able to handle it.

**Comment by zolokonst** [comment] 2021-02-18 04:08
> > The app cannot try v6 and then use v4 for every new connection.
> 
> Please reopen the issue. IPv4/6 fallback in case the other address is not working is a common standard, the software should be able to handle it.

Especially if it worked in previous versions.

**Comment by tobiasKaminsky** [comment] 2021-02-18 14:16
> Especially if it worked in previous versions.

It worked in previous version as there v4 was preferred, and only if no v4 was available it tried v6.

**Comment by tobiasKaminsky** [comment] 2021-02-18 14:18
>  IPv4/6 fallback in case the other address is not working is a common standard, the software should be able to handle it.

What is your suggestion? Have app trying v6 on each connection, failing, then trying v4?
This doubles the amount of connections for every request.

If you have a good way, we can surely discuss and implement this.

**Comment by KopfKrieg** [comment] 2021-02-18 19:39
> What is your suggestion? Have app trying v6 on each connection, failing, then trying v4?

If the DNS record returns both an IPv6 and IPv4 address then I'd first try the IPv6 address. If the request fails try the IPv4 address.

Maybe the result can be cached (which should also depend on the DNS lifetime) so we don't have to do this on every request (but only every 24 hours or so).

Using a single connection that is kept alive for multiple requests might also help.

> If you have a good way, we can surely discuss and implement this.

I'm not sure how browsers usually handle cases like this, I hope it's similar to what I've mentioned above.

Right now I would just like to keep the issue open, and discuss how this could be implemented, even if we don't find the perfect solution.

**Comment by Carsten1987** [comment] 2021-02-18 19:42
How does the Windows-App Manage this behavior? Or is it handled by OS?

**Comment by zolokonst** [comment] 2021-02-19 07:10
>What is your suggestion? Have app trying v6 on each connection, failing, then trying v4?`

I am not a developer. But in my mind @KopfKrieg provided good solution. May be some RFC describes this situation. 
If I want to do it simpler i'd tryed the next approach :
```
if (createConnection(..).status==CONN_TIMEOUT) {
    SessionProtocol.switch(next) ;
    if (createConnection(..).status==CONN_TIMEOUT) {
        ErrorHandler(CONN_TIMEOUT);
    } 
} 
```

It doubles timeout if connection lost. But if any of two protocols are available, connection establishes. If it difficult to implement SessionProtocol entity, it might be changed to already realized (as I can understand) PreferredProtocol.

**Comment by zolokonst** [comment] 2021-03-25 16:23
Up

**Comment by KopfKrieg** [comment] 2021-04-23 08:24
Bad bot. The issue is still relevant.

**Comment by Carsten1987** [comment] 2021-05-28 20:35
Bad bot. The issue is still relevant.

**Comment by laf0rge** [comment] 2021-06-03 08:15
I can confirm this issue is happening still with today's version of the nextcloud android app from the play store.  It's 100% reproducible.

The standard behavior of any client program with IPv6 support (as it has always been for the past 20 or so years as far as I recall) is to first try IPv6, and if that fails, fall back to IPv4. This works with any other software that I know of, whether on Linux, proprietary desktop OSs, or on Android.

The nextcloud android client is the only program I have ever seen exhibiting this bug.  Using IPv6 since the late 90ies I would think I am qualified to make such a statement.

I know close to nothing about Android APIs, but on the C library level on Linux you are using getnameinfo() to get all the DNS records for one given host name.  And then you iteratve over those, trying to establish a connection to each of them.

If you fail to do so and only try the first, this will create problems
* with IPv4 fallback if IPv6 DNS records exist
* with the common usage pattern of using round-robin DNS (multiple A records for one hostname) to distribute load among multiple servers.

**Comment by laf0rge** [comment] 2021-06-03 08:31
https://eng.libretexts.org/Bookshelves/Computer_Science/Book%3A_An_Introduction_to_Computer_Networks_(Dordal)/08%3A_IP_version_6/8.12%3A_Using_IPv6_and_IPv4_Together looks like a good basic text on the subject.

It also links to RFC 6724 (preferences of priority/ordering handled at OS/DNS level) and the optional alternative of RFC 8305 "happy eyeballs" of doing this more concurrently and less sequentially.

**Comment by laf0rge** [comment] 2021-06-03 08:39
> If IPv6 is available app uses it. So please configure your server correctly to work with v6 or disable it at all.

You are completely missing the point.  The server may very well have excellent and reliable IPv6 connectivity.  But then, you cannot control in which netwokrs a client, particularly a _mobile_ client is roaming around
* you might be connected to some hotspot that is either misconfigured or has a [temporary] IPv6 routing problem
* any intermediaten transit network might fail for IPv6 but not for IPv4

Those things happen all the time, everywere.

> The app cannot try v6 and then use v4 for every new connection.

Any other application (like all web browsers, for that matter) can, but the nextcloud client application cannot? To iterate some Android examples that work as expected in this scenario by doing proper v4 fallback: k9mail, Xabber, DAVx5, all Google apps, Amazon, Bandcamp, Chrome, DB Navigator, DB Tickets, eBay, F-Droid, Fennec, Jitsi meet, Mixcloud, NewPipe, Oeffi, OsmAnd (map downloads), Prime Video, Signal, Soundcloud, Speedtest, VLC, ...

btw, it seems that this issue already existed as early as 2014 (#616)

**Comment by Alex98234** [comment] 2021-06-04 15:26
I think #7400 is the same issue.

**Comment by mepreston** [comment] 2021-06-05 23:16
I'm piling on.  the function works just fine in 3.13.1 which all my android devices are running because my ISP is crap and up grading to any newer version breaks connecting to my nextcloud server. as mention in prior post, this app is the only one on my devices that will not fallback to ipv4 if ipv6 isn't working.    I don't get why it is taking so long to put the code back in that took care of this, it isn't like you are adding a new feature, you removed it when it was already there and working fine.

**Comment by AndyScherzinger** [comment] 2021-06-07 08:07
>  I don't get why it is taking so long to put the code back in that took care of this, it isn't like you are adding a new feature, you removed it when it was already there and working fine.

There was no code that took care and has been removed. The behavior changed from ipv4 with fallback to ipv6 which in an case the fallback only ever got triggered if no config had been present. So if ipv6 config is present but doesn't work than there is no ipv4 fallback. Same now if there is a ipv6 config provided via your DNS than it is used, if it doesn't work then there is no fallback, if DNS only provides ipv4 than that will be used (since ipv6 isn't present).

**Comment by Alex98234** [comment] 2021-07-01 09:58
A third issue - #7907 - which I think is the same thing.

**Comment by sndrr** [comment] 2021-07-30 13:13
My workaround is to set distinct IP versions in DNS and use the IPv4-version:
* cloud.4.example.com for IPv4
* cloud.6.example.com for IPv6
* cloud.example.com for both IPv4 and IPv6 (this one fails)

**Comment by mepreston** [comment] 2021-07-30 13:58
i'm very disappointed with nextcloud development that they can't fix this to work like firefox and chrome browsers to fall back from IPv6 to IPv4 when there is an issue connecting. i guess long time i'll only be using firefox on my device and remove the nextcloud client from my phone it doesn't seem that this will ever be addressed.  My ISP still isn't consistently working with IPv6.

**Comment by mm28ajos** [comment] 2021-09-02 10:54
> > IPv4/6 fallback in case the other address is not working is a common standard, the software should be able to handle it.
> 
> What is your suggestion? Have app trying v6 on each connection, failing, then trying v4?
> This doubles the amount of connections for every request.
> 
> If you have a good way, we can surely discuss and implement this.
Any update on the dicussion @tobiasKaminsky ?

**Comment by Alex98234** [comment] 2021-09-03 08:33
So far the only way to mitigate this issue was to remove the domain AAAA record entirely. With only a A record, only a IPv4 adress is available the the connection does not fail _all the time_.

2021 and I have to _disable_ IPv6, this is strange.

**Comment by mm28ajos** [comment] 2021-09-03 08:56
Indeed. The point is, that the behaviour can be triggered client side and not only server side issues. Had some users which turned out to have been connected to ipv6 routers for which ipv6 routing was from time to time not working and now they experience this issue.

**Comment by mepreston** [comment] 2021-09-03 12:00
seriously firefox mobile has never had an issue connecting my nextcloud server but  this client does. if they can do it way can't you?

**Comment by hofinger82** [comment] 2021-09-15 20:28
Any news here? The app is not usable with this bug.

**Comment by mepreston** [comment] 2022-01-06 15:32
this should not have been closed as this is still an issue.  I'm very disappointed that this app can't deal with ipv4/6 like other apps do.

**Comment by mepreston** [comment] 2022-01-06 15:33
can someone reopen this or point to a current open bug on this issue?

**Comment by laf0rge** [comment] 2022-01-06 21:23
@tobiasKaminsky pleaes kindly re-open this issue.  It is a real issue. Virtually any client application on this planet gets this right, just nextcloud is continuously refusing to fix an obvious bug in handling network scenarios where the IPv6 route is temporarily or permanently interrupted, while IPv4 is availalbe and works.

**Comment by laf0rge** [comment] 2022-01-06 21:30
For the record: I have had to remove the AAAA record of my nextcloud instance (server side) just to make the constant complaints frm users with flaky IPv6 routing go away. 

So basically, by closing this bug, the developers are saying: Either you use IPv5, or you use our android client.  But you cannot really have both [in a reliable way, with the proper fall-back]

**Comment by mepreston** [comment] 2022-01-07 01:03
it seems there are more than a few unhappy users of this app for other reasons besides this issues.  
https://www.reddit.com/r/NextCloud/comments/q6obpb/alternative_android_clients/
I guess i should also look at replacing this app with something else since on one wants to improve or fix issues with this app.   your giving NC server a black eye.

**Comment by tobiasKaminsky** [comment] 2022-01-07 07:07
We will discuss it next week.

**Comment by mepreston** [comment] 2022-01-11 19:15
these three issues all seem to be related. 
 prefer IPV6 addresses if available #503 
 ipv6 not reachable, app not fallback ipv4 #7400 
 Connection fails if ipv6 connection do not work properly #7839 

 The two open "bug"  have been opened more than an year 
and yet this issue still have not been resolved.  Is anyone 
doing project management for this product?  this is giving
NC server a black eye when the mobile client can't connect .
https://github.com/nextcloud/android/issues/7400
https://github.com/nextcloud/android/issues/7839

**Comment by AlvaroBrey** [comment] 2022-01-12 10:45
Closing in favor of #7400 to not have a duplicate issue. All subsequent discussion will be had there.

**Closed by AlvaroBrey** 2022-01-12 10:45 UTC
Labels: bug, needs info/discussion

**Comment by AlvaroBrey** [comment] 2022-01-13 09:33
For people subscribed to this issue: Can anyone test this APK https://github.com/nextcloud/android/issues/7400#issuecomment-1011913182 and see if it works under the circumstances described in this issue? Please direct all further feedback to #7400 to avoid duplicating conversations.
