### ISSUE TITLE
Android Client crash

### ISSUE THREAD

**Issue by gitschwarz** [nextcloud/android#13816] opened 2024-10-19 06:14 UTC
### Cause of error
```java
Exception in thread "Syncfolder thread" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getEtag()' on a null object reference
    at com.owncloud.android.operations.SynchronizeFolderOperation.checkForChanges(SynchronizeFolderOperation.java:169)
    at com.owncloud.android.operations.SynchronizeFolderOperation.run(SynchronizeFolderOperation.java:127)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
    at com.owncloud.android.services.SyncFolderHandler.doOperation(SyncFolderHandler.java:106)
    at com.owncloud.android.services.SyncFolderHandler.handleMessage(SyncFolderHandler.java:79)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.os.HandlerThread.run(HandlerThread.java:85)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300190`
* Build flavor: `generic`

### Device information
* Brand: `google`
* Device: `lynx`
* Model: `Pixel 7a`
* Id: `AP2A.240905.003`
* Product: `lynx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `d7d5efbf14`

**Comment by joshtrichards** [comment] 2024-10-19 12:18
Duplicate of #13784

**Closed by joshtrichards** 2024-10-19 12:18 UTC
