### ISSUE TITLE
Sync problem Xiaomi Poco X3 NFC

### ISSUE THREAD

**Issue by it4csl** [nextcloud/android#7309] opened 2020-11-13 00:14 UTC
### Steps to reproduce
1. Take a photo or screenshot
2. Synchronize via nextcloud app
3. Open any messenger or gmail
4. Send photo

Hello. Sorry for my bad english.
Faced such a problem.
After syncing the photo to the server, broken copies of files are created in the attachment gallery of any messenger or Gmail.
These files have the same names as the originals but with a size of 0b.
I tried to clear the cache and application data, but it does not help, broken files do not disappear.
These files are not found anywhere else. They are visible only if you open the "attach file" item.
And these files only appear after syncing.
If you turn off nextcloud app sync, no duplicates with size 0b appear.

### Environment data
Android version: 10 QKQ1.200512.002

Device model: Xiaomi Poco X3 NFC

Stock or customized system: stock

Nextcloud app version: 3.13.1

Nextcloud server version: 19.0.4

![Screenshot_2020_11_13_01_43_28_809_com_google_android_documentsui](https://user-images.githubusercontent.com/45635507/99010546-d53ca700-2552-11eb-9747-571495c8a9f7.jpg)
![Screenshot_2020-11-13-03-24-47-028_org telegram messenger](https://user-images.githubusercontent.com/45635507/99016588-299a5380-2560-11eb-982c-4967034730cb.jpg)
![Screenshot_2020-11-13-01-33-40-057_org telegram messenger](https://user-images.githubusercontent.com/45635507/99010548-d66dd400-2552-11eb-8ef4-45d75c7f084a.jpg)

**Comment by aqaqsubin** [comment] 2020-11-13 02:29
Do you only see these pictures attached by Gmail or messenger?

**Comment by it4csl** [comment] 2020-11-13 03:52
No, there are originals too, but this creates empty duplicates

пт, 13 нояб. 2020 г., 04:29 aqaqsubin <notifications@github.com>:

**Comment by aqaqsubin** [comment] 2020-11-13 04:15
> These files are not found anywhere else. They are visible only if you open the "attach file" item.

It seems to be the same error I saw, but this part is different.
And I can delete this ghost file, is it another error? #6558

**Comment by it4csl** [comment] 2020-11-13 04:20
For a better understanding of what is happening, I can make a screen
recording for you.  to do?

пт, 13 нояб. 2020 г., 04:29 aqaqsubin <notifications@github.com>:

**Comment by aqaqsubin** [comment] 2020-11-13 04:28
Oh yes, Thank you for your consideration!

**Comment by it4csl** [comment] 2020-11-13 05:07
https://drive.google.com/file/d/1-bcg3bIQOuEwIK3I789Oe6vlEdi4Vz1c/view?usp=drivesdk
пт, 13 нояб. 2020 г., 06:29 aqaqsubin <notifications@github.com>:

**Comment by aqaqsubin** [comment] 2020-11-13 06:01
I guess that the Ghost file path is '/storage/emulated/0/Pictures', right?
So, you can find these ghost file in the path not only attachment gallery of any Messenger or Gmail. And you could delete this file.
 I think this issue duplicated of #6558.

**Comment by it4csl** [comment] 2020-11-13 06:30
yes, the problem is similar, only in my case they are not visible in any
folder in the explorer.  they can be seen as I showed above and only in
Google photos they can be deleted

пт, 13 нояб. 2020 г., 08:02 aqaqsubin <notifications@github.com>:

**Comment by aqaqsubin** [comment] 2020-11-13 07:03
Oh, Even if you searched file name in file explorer?
![image](https://user-images.githubusercontent.com/28510311/99038833-85e58d80-25c9-11eb-8b05-518a1d7f1faf.png)

I take that back. Couldn't delete these file in file explorer...
> So, you can find these ghost file in the path not only attachment gallery of any Messenger or Gmail. And you could delete this file.

**Comment by tobiasKaminsky** [comment] 2020-11-13 07:18
I think it is a duplicate of #6558, but with another symptom, that Gallery/Mail is picking the old one…

**Closed by tobiasKaminsky** 2020-11-13 07:18 UTC
Labels: bug

**Comment by it4csl** [comment] 2020-11-13 12:01
Yes, of course, I tried searching and it does not find ghost files

пт, 13 нояб. 2020 г., 09:04 aqaqsubin <notifications@github.com>:
