### ISSUE TITLE
FAB appears on the media playback screen

### ISSUE THREAD

**Issue by aqaqsubin** [nextcloud/android#7356] opened 2020-11-18 11:21 UTC
### Steps to reproduce
1. Play media file (.mp3 or .mp4, etc)
2. Hit HOME (Minimizing App)
3. Re-Open it from Multitasking View

### Expected behaviour
the FAB shouldn't be visible in media playback sreen.

### Actual behaviour
FAB appears in this screen.

I think this error is discussed in #6782.
The problem at #6782 seems to have been solved and merged, but this problem continues to appear in my environment.

For a better understanding of what is happening, I attach screen recording video.
https://drive.google.com/file/d/1asJioZ1cBs4jj24PTZzYpF0bMx-n8zzV/view?usp=drivesdk

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: Samsung Galaxy s10e

Nextcloud app version: Nextcloud 3.14.0 RC2

Nextcloud server version:

**Comment by AndyScherzinger** [comment] 2020-11-18 15:23
@aqaqsubin thanks for taking the time to report this in a dedicated issue ❤️ 

@tobiasKaminsky I tought you already fixed this a while ago (but I might be mistaken), but it happens on 3.14/master (again?)

**Comment by tobiasKaminsky** [comment] 2020-11-19 08:55
This is somehow a duplicate of #6782 
We also agreed on a solution there.

**Closed by tobiasKaminsky** 2020-11-19 08:55 UTC
Labels: approved, bug

**Comment by aqaqsubin** [comment] 2020-11-19 09:43
@tobiasKaminsky I know it's a duplicate error
But shouldn't 3.14.0 RC2 be without this error?

**Comment by AndyScherzinger** [comment] 2020-11-19 14:21
@tobiasKaminsky I don't see a duplicate here. #6782 is about the media controls while this is about showing a FAB (where it should be hidden).

**Comment by tobiasKaminsky** [comment] 2020-11-20 09:07
It is not directly a duplicate, but it will be fixed with it https://github.com/nextcloud/android/issues/6782#issuecomment-679862035
