### ISSUE TITLE
Crashed app bug

### ISSUE THREAD

**Issue by GunManSK** [nextcloud/android#7158] opened 2020-10-28 11:37 UTC
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.AnalyticsConnector
	... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWPOT-H
Model: POT-LX1
Id: HUAWEIPOT-L21
Product: POT-LX1EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.238C431

**Comment by AndyScherzinger** [comment] 2020-10-28 14:00
Duplicate of #4675

**Comment by AndyScherzinger** [comment] 2020-10-28 14:00
Fix will roll out with upcoming feature release 3.14.0

**Closed by AndyScherzinger** 2020-10-28 14:00 UTC
Labels: bug

**Comment by GunManSK** [comment] 2020-10-30 00:06
Thanks!
