### ISSUE TITLE
Android 7.0 Nougat Instant Upload doesn't work

### ISSUE THREAD

**Issue by lenn1** [nextcloud/android#238] opened 2016-09-03 14:23 UTC
### Actual behaviour
After an Update to Android 7 the Instant Photo/Video Upload doesnt work

### Expected behaviour
After an Update to Android 7 the Instant Photo/Video Upload should work
 
### Steps to reproduce
1. Install and Configure App (Activate Upload for Photos)
2. Take a Photo and Wait.

### Environment data
Android version:7.0

Device model: Nexus 5X

Stock or customized system: Stock

Nextcloud app version: 1.2.0 (Playstore Version)

Nextcloud server version:  9.0.50 (stable)

**Comment by AndyScherzinger** [comment] 2016-09-03 15:47
Duplicate of #110 please track any progress there. This is unfortunately due to Google massively breaking APIs/Concepts (again).

**Closed by AndyScherzinger** 2016-09-03 15:47 UTC
