### ISSUE TITLE
Flash back? Please give priority to this problem

### ISSUE THREAD

**Issue by dxj728** [nextcloud/android#2111] opened 2018-02-07 03:22 UTC
### Actual behaviour
When you try to move the file elsewhere, the search option seems unfriendly on the new pop-up selection page, and if you do use the search, you will surely find that the program is crashing.

### Expected behaviour
I think you should search the target folder, don't you?
 
### Steps to reproduce
1. Click on a file and select move in actionbar
2. Then click search in the pop-up folder selection page
3. Search for any name, click on the keyboard to determine
4. It collapsed, didn't it?

### Environment data
Android version:
Android 6.0
Device model: 
Nexus 7
Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
I don't seem to know if there's a log, but it's definitely a problem.
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by AndyScherzinger** [comment] 2018-02-07 06:05
@dxj728 thanks for your report. Can you please let us know which app, Android and server versions you are using. I tried the latest development version and it worked like a charm...

**Comment by dxj728** [comment] 2018-02-07 06:15
@AndyScherzinger The android client, of course, and when you connect to the server and do the above, there will be a rout, every time.

**Comment by AndyScherzinger** [comment] 2018-02-07 06:20
Hi @dxj728, what I meant is the version of each of them as requested in the issue template:
* app version 
* server version 
* android version 

Since for my Android 8 OP3T phone running 3.0.0 RC3 with a 13.0.0 server, everything works just fine and the error can't be reproduced. Hence this information is crucial to resolve the matter.

**Comment by dxj728** [comment] 2018-02-07 06:58
@AndyScherzinger fine
app version:  2.0.1  I used your latest version of Android
server version:  nextcloud 12.0.0
android version:  Android 5.1.1
When you press long to select a file and click on the hidden movement option on action, search on the pop-up page, search for anything, and then make sure it happens. I do this every time.

**Comment by tobiasKaminsky** [comment] 2018-02-07 07:23
I remember a fix for upcoming 3.0 and a quick test did not crash.
The next version will be released tomorrow.
If you then still experience the bug, please re-open and we have to dig deeper into it.

**Closed by tobiasKaminsky** 2018-02-07 07:23 UTC
Labels: bug
