### ISSUE TITLE
When trying to open a docx file

### ISSUE THREAD

**Issue by adamingas** [nextcloud/android#13750] opened 2024-10-09 15:22 UTC
Please close if this is the wrong place to raise an issue. The app was lagging and eventually crashed. Nc Server seems to be doing fine

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at com.owncloud.android.ui.adapter.OCFileListAdapter.limitToPersonalFiles(OCFileListAdapter.java:1074)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:741)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1359)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1308)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onBrowseUp(OCFileListFragment.java:923)
    at com.owncloud.android.ui.activity.FileDisplayActivity.browseUp(FileDisplayActivity.java:1017)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onBackPressed(FileDisplayActivity.java:1010)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onOptionsItemSelected(FileDisplayActivity.java:826)
    at android.app.Activity.onMenuItemSelected(Activity.java:4719)
    at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.java:528)
    at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:264)
    at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:269)
    at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:110)
    at androidx.appcompat.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:188)
    at android.view.View.performClick(View.java:8055)
    at android.view.View.performClickInternal(View.java:8032)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(View.java:31923)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:9063)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `q5q`
* Model: `SM-F946B`
* Id: `UP1A.231005.007`
* Product: `q5qxeea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `F946BXXS3DXI3`

**Comment by joshtrichards** [comment] 2024-10-09 17:42
Duplicate of #12908 
Fixed in #12930

**Closed by joshtrichards** 2024-10-09 17:42 UTC
