### ISSUE TITLE
App crashes when trying to upload a file from external storage larger than remaining internal storage

### ISSUE THREAD

**Issue by MaxiMii05** [nextcloud/android#9196] opened 2021-11-03 20:13 UTC
possible duplicate of #8707

### Steps to reproduce
1. Have file on an SD card that is larger than your remaining internal storage
2. Upload this file with the app (read-only)
3. Agree to move file instead of copying because of insufficient space left

### Expected behaviour
- The file should preferably be uploaded to the Nextcloud server without being copied or moved anywhere. At least, the app should recognize that moving a file from an SD card to internal storage does not help when the internal storage is insufficient.

### Actual behaviour
- The app crashes and asks me to file a bug report.

### Can you reproduce this problem on https://try.nextcloud.com?
- Yes, I can reproduce this error

### Environment data
Android version: 10
Device model: SM-G965F
Stock or customized system: stock
Nextcloud app version: 30170190
Nextcloud server version: 22.2.0
Reverse proxy: Nginx

#### Web server error log
nothing noteworthy

#### Nextcloud log (data/nextcloud.log)
nothing noteworthy

Bug:
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=1, data=Intent { (has extras) }} to activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5360)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5401)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
	at com.owncloud.android.ui.activity.FileDisplayActivity.requestUploadOfFilesFromFileSystem(FileDisplayActivity.java:964)
	at com.owncloud.android.ui.activity.FileDisplayActivity.requestUploadOfFilesFromFileSystem(FileDisplayActivity.java:959)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onActivityResult(FileDisplayActivity.java:889)
	at android.app.Activity.dispatchActivityResult(Activity.java:8300)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5353)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: star2lte
Model: SM-G965F
Id: QP1A.190711.020
Product: star2ltexx

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G965FXXUGFUG4

**Comment by AlvaroBrey** [comment] 2021-11-09 08:53
Duplicate of #5910

**Closed by AlvaroBrey** 2021-11-09 08:53 UTC
Labels: bug
