### ISSUE TITLE
 double photo in the gallery

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/android#2100] opened 2018-02-04 20:47 UTC
One+5 Kernel 4.4.78 Oxygene 5.0.2 A5000_23_180129 // Nextcloud Dev 20180201

### Actual behaviour
browsing to the gallery. Double pics for all 

### Expected behaviour

should see on pic, not two 
 
### Steps to reproduce

same behavior in official 2.0.0

![p_20180204_214608](https://user-images.githubusercontent.com/8655165/35782205-0551b060-09f5-11e8-9588-5dac77d5b2fa.jpg)

**Comment by stratege1401** [comment] 2018-02-05 01:13
BTW, same thing for my asus zenpad s10 z500 ( WW_P027 REL 7.0.0 )
![img_20180205_020952](https://user-images.githubusercontent.com/8655165/35784627-1db56c62-0a1a-11e8-8e7d-6de3d408748e.jpg)

**Comment by AndyScherzinger** [comment] 2018-02-05 16:16
This is a duplicate of #1698 and also happens for favorites at the moment

**Closed by AndyScherzinger** 2018-02-05 16:16 UTC

**Comment by AndyScherzinger** [comment] 2018-05-12 19:36
PR is #2490
