### ISSUE TITLE
Crashes when clicking "Energiesparmodus deaktivieren"

### ISSUE THREAD

**Issue by 1mike10** [nextcloud/android#14100] opened 2024-11-29 07:13 UTC
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Im in settings>automatic uploads>3 dots> "Energiesparmodus deaktivieren" (deactivate power saving)
Then the app crashes

### Expected behaviour

Idk

### Actual behaviour

Crash

### Android version

9

### Device brand and model

Samsung galaxy note 8

### Stock or custom OS?

Stock

### Nextcloud android app version

3.30.5

### Nextcloud server version

Nextcloud hub 8 (29.0.8)

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "main" android.content.res.Resources$NotFoundException: Resource ID #0x7f0a0405 type #0x12 is not valid
    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2176)
    at android.content.res.Resources.getLayout(Resources.java:1170)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
    at androidx.appcompat.app.AlertController.setupCustomContent(AlertController.java:644)
    at androidx.appcompat.app.AlertController.setupView(AlertController.java:475)
    at androidx.appcompat.app.AlertController.installContent(AlertController.java:233)
    at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:278)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:550)
    at android.app.Dialog.show(Dialog.java:391)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.showPowerCheckDialog(SyncedFoldersActivity.kt:233)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onDisablePowerSaveCheckClicked(SyncedFoldersActivity.kt:217)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onCreateOptionsMenu$lambda$1(SyncedFoldersActivity.kt:210)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.$r8$lambda$q58-_n5tvnvo7t7SwBQVBpaIAdU(Unknown Source:0)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$$ExternalSyntheticLambda4.onMenuItemClick(D8$$SyntheticClass:0)
    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:984)
    at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
    at android.widget.AdapterView.performItemClick(AdapterView.java:362)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1689)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:4130)
    at android.widget.AbsListView$7.run(AbsListView.java:6612)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7073)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300590`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `greatlte`
* Model: `SM-N950F`
* Id: `PPR1.180610.011`
* Product: `greatltexx`

### Firmware
* SDK: `28`
* Release: `9`
* Incremental: `N950FXXUGDVG5`

### Server error logs

```bash
None
```

**Comment by msviba** [comment] 2024-12-09 14:18
duplicate to https://github.com/nextcloud/android/issues/14091

**Comment by joshtrichards** [comment] 2024-12-28 14:43
Duplicate of #13404

**Closed by joshtrichards** 2024-12-28 14:43 UTC
Labels: bug, 0. Needs triage
