### ISSUE TITLE
A crash

### ISSUE THREAD

**Issue by bdhcode** [nextcloud/android#5083] opened 2019-12-31 20:54 UTC
************ CAUSE OF ERROR ************

android.view.InflateException: Binary XML file line #7: Error inflating class android.webkit.WebView
	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
	at com.owncloud.android.authentication.AuthenticatorActivity.onNewIntent(AuthenticatorActivity.java:908)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1218)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1230)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2664)
	at android.app.ActivityThread.performNewIntents(ActivityThread.java:2676)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2685)
	at android.app.ActivityThread.access$1600(ActivityThread.java:178)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1542)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5624)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	... 24 more
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x2040003
	at android.content.res.Resources.getText(Resources.java:322)
	at android.content.res.Resources.getString(Resources.java:420)
	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:684)
	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:674)
	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:823)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:662)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:597)
	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:319)
	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:104)
	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:271)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:131)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:118)
	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:115)
	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:268)
	at android.webkit.WebView.<init>(WebView.java:590)
	at android.webkit.WebView.<init>(WebView.java:525)
	at android.webkit.WebView.<init>(WebView.java:508)
	at android.webkit.WebView.<init>(WebView.java:495)
	... 27 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: IRIS
Device: VOX_VERO
Model: VOX_VERO
Id: LMY47D
Product: VOX_VERO

************ FIRMWARE ************
SDK: 22
Release: 5.1
Incremental: 1458813057

**Comment by AndyScherzinger** [comment] 2020-01-09 17:30
duplicate of #4943

**Closed by AndyScherzinger** 2020-01-09 17:30 UTC
Labels: bug
