### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by FabianGabor** [nextcloud/android#10427] opened 2022-06-22 12:41 UTC
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException
    at com.owncloud.android.ui.activities.ActivitiesActivity$$ExternalSyntheticLambda0.get(Unknown Source:2)
    at com.nextcloud.java.util.Optional.orElseThrow(Optional.java:309)
    at com.owncloud.android.ui.activity.FileDisplayActivity$8.run(FileDisplayActivity.java:1995)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6762)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `xiaomi`
* Device: `tissot_sprout`
* Model: `Mi A1`
* Id: `PKQ1.180917.001`
* Product: `tissot`

### Firmware
* SDK: `28`
* Release: `9`
* Incremental: `V10.0.24.0.PDHMIXM`

**Comment by Tiam-Abderezai** [comment] 2022-06-23 12:23
Origin of the crash in FileDisplayActivity:

```java
// perform folder synchronization
RemoteOperation synchFolderOp = new RefreshFolderOperation(folder,
                                                             currentSyncTime,
                                                             false,
                                                             ignoreETag,
                                                             getStorageManager(),
========================================================>    getUser().orElseThrow(RuntimeException::new),
                                                             getApplicationContext()
                            );
```

**Comment by AlvaroBrey** [comment] 2022-06-23 13:00
Duplicate of #10076

**Closed by AlvaroBrey** 2022-06-23 13:00 UTC
Labels: bug
