### ISSUE TITLE
Crash after synchronize folder

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/android#4914] opened 2019-12-02 10:10 UTC
3-4 .mp4 (each <100kB) and 2-300 .jpg (each a few kB) were in the folder. After sync comoleted, app crashed.

```
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{a0740f3 u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: beryllium
Model: POCO F1
Id: PQ3A.190705.003
Product: beryllium

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 5d3e3c161a
```

**Comment by AndyScherzinger** [comment] 2019-12-03 15:01
duplicate of #2010, so closing in favor

**Closed by AndyScherzinger** 2019-12-03 15:01 UTC
Labels: bug
