### ISSUE TITLE
Retrieving any doc put on Nextcloud and downloading it to Android's local dowload folder not working

### ISSUE THREAD

**Issue by faxotherapy** [nextcloud/android#12841] opened 2024-04-07 19:17 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Since updating last week to Nextcloud app 3.28.1, I'm no longer able to retrieve any document from Nextcloud instance to Android's local folder (i.e. Download).

Example: I’ve got an EPUB in a Nextcloud folder. It’s very complicated to retrieve it and read it in my EPUB reader on my Pixel.

Using Files app and accessing the Nextcloud folder to retrieve the EPUB and put it inside my Pixel’s Downloads folder, I always have this error message: Couldn't copy 1 item. I did not have this issue before. It used to work. Now, it is impossible for me to repatriate any files locally.

Another way I found is navigating to the file inside the Nextcloud app and select the “Download” option for the item to download. Unfortunately, after selecting this option, the file size reset to 0 (as though the Nextcloud app attempted to modify it, hence a supposedly “new version” of the EPUB I haven't asked for) and nothing is downloaded inside my local Download folder. I have to pull down in order to refresh/reload the correct file size but still repeating previous steps, I’m still unable to retrieve the file.

### Expected behaviour

After choosing “Download”, the file that sits in my remote Nextcloud instance should be mirrored in my Pixel's Download folder.

### Actual behaviour

It doesn't do anything and says: “Couldn't copy 1 item”

### Android version

14

### Device brand and model

Pixel 4a (5G)

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.28.1 (with 3.12.3git (build 21830) on macOS)

### Nextcloud server version

27.1.7

### Using a reverse proxy?

No

### Android logs

Not an Android expert, here. Just a dumb user reporting an issue. I'm very sorry, but, using Files app on Android, I could not located any `storage` folder. I think you'll need to provide me with some guidance. Using Files app, I visited `Pixel 4a (5G)` item in the hope it would lead me to the root folder…

### Server error logs

No log writing server side when I attempt to download the file.

I visited `apache_access.log  apache_errors.log  mysql_errors.log  nextcloud.log  php_errors.log  php-fpm_errors.log  redis.log`, but a log write only happens for `apache_access.log`.

```bash
[07/Apr/2024:21:11:17 +0200] "GET /index.php/apps/files/api/v1/thumbnail/256/256/Partage/Documents/Fantastiques%20experiences%20de%20voyage%20astral%20-%20Esoterisme.epub HTTP/1.1" 404 845 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.28.1"
```

### Additional information

Custom ROM: CalyxOS

**Comment by sophom** [comment] 2024-04-07 23:19
I'm having the same issue with the same version of the android app (3.28.1) and the same version of the server (27.1.7) only running on Linux

**Comment by gmuellerinform** [comment] 2024-04-08 07:22
Same problem here with Nextcloud 28.0.4 and 3.28.1

**Comment by Floyd2000** [comment] 2024-04-08 15:56
Same here with Nextcloud app version 3.28.1 and Nextcloud server 28.0.3.
The issue does not occur with 3.28.0 (tested on another device that wasn't updated yet) nor does it occur with the iOS app on an iPhone, so the server obviously works fine.

**Comment by sirsarrio** [comment] 2024-04-08 21:42
A mí también me ocurre lo mismo.  O es problema del servidor pq desde otras plataformas veo sin problemas los documentos

**Comment by Duffkess** [comment] 2024-04-09 11:41
I can confirm that we have this problem also with over 100 devices since the Version was updated to 3.28.1.
If there is any chance to say how long it would take to fix this would be great, because I have the option to deploy a previous version via mobile device management as an alternative. Thanks!

**Comment by Floyd2000** [comment] 2024-04-09 12:39
In the other issue threads which I mentioned in my first post, people say that 3.28.2 fixed the problem.
Question is now when this new version will find its way to Google Play and/or F-Droid...
I've been checking both places continously on an hourly basis today, but nothing in sight yet. I don't know their workflows how to check/publish new versions.... Can anyone shed some light on this?

**Comment by Duffkess** [comment] 2024-04-12 07:43
For anyone who does not see it, the new version has now been released in the google playstore.

**Comment by sirsarrio** [comment] 2024-04-12 07:44
Gracias por avisar!!

**Closed** 2024-04-12 14:41 UTC
Labels: bug
