### ISSUE TITLE
Auto upload and overwrite remote version create sync conflict....

### ISSUE THREAD

**Issue by ArnaudD-FR** [nextcloud/android#6893] opened 2020-09-04 08:23 UTC
### Steps to reproduce
1. Configure Android WhatsApp folder as auto upload with "Overwrite remote version" option
![image](https://user-images.githubusercontent.com/5124331/92209304-0e8ad380-ee8d-11ea-8085-b965f92e2233.png)

2. Wait for files to upload (Nextcloud App is frozen many times while uploading)
3. new conflicts happens
![image](https://user-images.githubusercontent.com/5124331/92209379-2d896580-ee8d-11ea-9b66-a6a056b78d7d.png)
![image](https://user-images.githubusercontent.com/5124331/92209430-47c34380-ee8d-11ea-9076-4d22f0b2a0f2.png)

### Expected behaviour
 - Conflicts should not happen on identical files, same date, same size
 - Conflicts should be solved automatically by option "Overwrite remote version"

### Environment data
Android version: 10

Device model: Sony Xperia 10 (I4113)

Stock or customized system: Official sony Android version

Nextcloud app version: 3.13.0

Nextcloud server version: 18 and upgraded yesterday to 19

Reverse proxy: no

**Comment by qwertz22** [comment] 2020-09-04 17:01
I have this issue since the update, too. But I think the problem is on the server (19.00.2).

**Comment by ArnaudD-FR** [comment] 2020-09-04 17:18
I have the issue since I have upgraded the client application. Don't ask which version I had before I have no idea. I haven't upgraded my server version since quite a long time, so for me this is not related to server

**Comment by tobiasKaminsky** [comment] 2020-09-07 08:06
Duplicate of #6771

**Closed by tobiasKaminsky** 2020-09-07 08:06 UTC
Labels: bug
