### ISSUE TITLE
Adding stuff error

### ISSUE THREAD

**Issue by ilpukka** [nextcloud/android#7828] opened 2021-01-14 07:05 UTC
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- opennfilemabager from mobile i quess

### Actual behaviour
- wild error appears

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
10
Device model: 
Samsung s9
Stock or customized system:

Nextcloud app version:
3.14.2
Nextcloud server version:
Newsest
Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5958)
	at android.view.ViewGroup.addView(ViewGroup.java:5777)
	at android.view.ViewGroup.addView(ViewGroup.java:5717)
	at android.view.ViewGroup.addView(ViewGroup.java:5690)
	at com.owncloud.android.ui.fragment.OCFileListBottomSheetDialog.onCreate(OCFileListBottomSheetDialog.java:131)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:702)
	at android.app.Dialog.show(Dialog.java:424)
	at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$registerFabListener$2$OCFileListFragment(OCFileListFragment.java:442)
	at com.owncloud.android.ui.fragment.-$$Lambda$OCFileListFragment$aYkoWPoxzAOahKL5AVjT06NhcnM.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7862)
	at android.view.View.performClickInternal(View.java:7831)
	at android.view.View.access$3600(View.java:879)
	at android.view.View$PerformClick.run(View.java:29359)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: starlte
Model: SM-G960F
Id: QP1A.190711.020
Product: starltexx

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G960FXXSCFTK2

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2021-01-14 07:46
Duplicate of #7796

**Closed by AndyScherzinger** 2021-01-14 07:46 UTC
Labels: bug
