### ISSUE TITLE
app crash while viewing photos, out of memory error

### ISSUE THREAD

**Issue by atengen** [nextcloud/android#5766] opened 2020-03-29 14:45 UTC
### Steps to reproduce
1. open photos
2.  view a picture
3. Swipe left or right several times

### Expected behaviour
- Tell us what happens

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version: 3.11.0

Nextcloud server version: 18.0.3

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError: Failed to allocate a 37683212 byte allocation with 4194304 free bytes and 29MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:677)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:653)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:691)
	at com.owncloud.android.ui.adapter.DiskLruImageCache.getBitmap(DiskLruImageCache.java:121)
	at com.owncloud.android.datamodel.ThumbnailsCacheManager.getBitmapFromDiskCache(ThumbnailsCacheManager.java:225)
	at com.owncloud.android.ui.preview.PreviewImageFragment.onStart(PreviewImageFragment.java:254)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2632)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
	at androidx.fragment.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManagerImpl.java:713)
	at androidx.fragment.app.FragmentManagerImpl.startPendingDeferredFragments(FragmentManagerImpl.java:1325)
	at androidx.fragment.app.FragmentManagerImpl.doPendingDeferredStart(FragmentManagerImpl.java:2178)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1703)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:299)
	at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:259)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager$3.run(ViewPager.java:273)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
	at android.view.Choreographer.doCallbacks(Choreographer.java:696)
	at android.view.Choreographer.doFrame(Choreographer.java:628)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5765)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Lenovo
Device: A10-70F
Model: Lenovo TAB 2 A10-70F
Id: MRA58K
Product: LenovoTAB2A10-70F

************ FIRMWARE ************
SDK: 23
Release: 6.0
Incremental: A10-70F_S000216_170601_ROW

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2020-03-30 04:57
Duplicate of #4981

**Closed** 2020-03-30 04:57 UTC
Labels: bug
