### ISSUE TITLE
App crashing when using WebAuthn

### ISSUE THREAD

**Issue by LBreda** [nextcloud/android#12548] opened 2024-02-13 19:13 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open the app
2. Write down my server address
3. Log in
4. Select the WebAuthn second factor option
5. Confirm on the system intent my will to use a key

### Expected behaviour

Initiation of the key authorization process

### Actual behaviour

Application crash

### Android version

11

### Device brand and model

Xiaomi Mi 9T

### Stock or custom OS?

Stock

### Nextcloud android app version

3.27.0

### Nextcloud server version

Hub 7 (28.0.2)

### Using a reverse proxy?

Yes

**Comment by joshtrichards** [comment] 2024-02-15 14:11
Do you have the crash output/stack trace?

**Comment by LBreda** [comment] 2024-02-15 14:52
```
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Error receiving broadcast Intent { act=de.cotech.hw.ACTION_USB flg=0x10 pkg=com.nextcloud.client } in de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@dfceb0d
    at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1572)
    at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:236)
    at android.app.ActivityThread.main(ActivityThread.java:7876)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.usb.UsbDevice.getInterfaceCount()' on a null object reference
    at de.cotech.hw.internal.transport.usb.UsbDeviceManager.isRelevantDevice(UsbDeviceManager.java:163)
    at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.handleConnectedUsbDevice(UsbConnectionDispatcher.java:93)
    at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.access$100(UsbConnectionDispatcher.java:48)
    at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1.onReceive(UsbConnectionDispatcher.java:80)
    at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1562)
    at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:236)
    at android.app.ActivityThread.main(ActivityThread.java:7876)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30270090`
* Build flavor: `gplay`

### Device information
* Brand: `Xiaomi`
* Device: `davinci`
* Model: `Mi 9T`
* Id: `RKQ1.200826.002`
* Product: `davinci`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `V12.1.4.0.RFJMIXM`
```

**Comment by tobiasKaminsky** [comment] 2024-02-16 10:09
What key do you use and how is it connected? NFC or real USB?

**Comment by LBreda** [comment] 2024-02-16 10:44
It is a SoloKey version 2, connected via USB. No issue with the same key on other applications and websites, and no issue with the same key on the same NextCloud instance via browser (both the phone itself or a PC).

**Comment by tobiasKaminsky** [comment] 2024-02-16 10:59
I only have this one https://www.yubico.com/de/product/security-key-nfc-by-yubico/
I connected it via usb C -> Usb A connector.
And it works for me.

Can you point me to your exact key and specs?

**Comment by LBreda** [comment] 2024-02-16 11:04
https://solokeys.com/collections/all/products/solo-2a-nfc-security-key-built-with-trussed%C2%AE

It is a pretty normal FIDO key, I use it everywhere.

**Comment by tobiasKaminsky** [comment] 2024-02-19 09:43
Can you test NFC?

**Comment by LBreda** [comment] 2024-02-19 10:22
Oh, I didn't try before. Tried now, and it works.

**Comment by joshtrichards** [comment] 2024-09-01 15:13
Duplicate of #11385

**Closed by joshtrichards** 2024-09-01 15:13 UTC
Labels: bug, 0. Needs triage, feature: authentication, performance: NPE :no_entry_sign:, stable-3.27
