### ISSUE TITLE
App crashed when trying to refresh the Media Page

### ISSUE THREAD

**Issue by cakonopka** [nextcloud/android#10724] opened 2022-09-08 07:39 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open app
2. Go to media
3. Swipe down to refresh media screen

### Expected behaviour

Media to refresh

### Actual behaviour

Crashed app

### Android version

12

### Device brand and model

Oneplus9Pro 

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.2

### Nextcloud server version

24.0.2

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Couldn't read row 715, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetString(Native Method)
    at android.database.CursorWindow.getString(CursorWindow.java:462)
    at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:54)
    at android.database.CursorWrapper.getString(CursorWrapper.java:141)
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:967)
    at com.owncloud.android.datamodel.FileDataStorageManager.getGalleryItems(FileDataStorageManager.java:2234)
    at com.owncloud.android.datamodel.FileDataStorageManager.getAllGalleryItems(FileDataStorageManager.java:2179)
    at com.owncloud.android.ui.adapter.GalleryAdapter.showAllGalleryItems(GalleryAdapter.kt:171)
    at com.owncloud.android.ui.fragment.GalleryFragment.showAllGalleryItems(GalleryFragment.java:348)
    at com.owncloud.android.ui.fragment.GalleryFragment.handleSearchEvent(GalleryFragment.java:192)
    at com.owncloud.android.ui.fragment.GalleryFragment.onRefresh(GalleryFragment.java:162)
    at androidx.swiperefreshlayout.widget.SwipeRefreshLayout$1.onAnimationEnd(SwipeRefreshLayout.java:195)
    at androidx.swiperefreshlayout.widget.CircleImageView.onAnimationEnd(CircleImageView.java:107)
    at android.view.ViewGroup.finishAnimatingView(ViewGroup.java:7227)
    at android.view.View.draw(View.java:22706)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4608)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4361)
    at android.view.View.draw(View.java:22811)
    at android.view.View.updateDisplayListIfDirty(View.java:21662)
    at android.view.View.draw(View.java:22528)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4608)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4361)
    at android.view.View.updateDisplayListIfDirty(View.java:21653)
    at android.view.View.draw(View.java:22528)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4608)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4361)
    at android.view.View.updateDisplayListIfDirty(View.java:21653)
    at android.view.View.draw(View.java:22528)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4608)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4361)
    at android.view.View.draw(View.java:22811)
    at android.view.View.updateDisplayListIfDirty(View.java:21662)
    at android.view.View.draw(View.java:22528)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4608)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4361)
    at android.view.View.updateDisplayListIfDirty(View.java:21653)
    at android.view.View.draw(View.java:22528)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4608)
    at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4361)
    at android.view.View.draw(View.java:22811)
    at android.view.View.updateDisplayListIfDirty(View.java:21662)
    at android.view.View.draw(View.java:22528)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4608)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4361)
    at android.view.View.updateDisplayListIfDirty(View.java:21653)
    at android.view.View.draw(View.java:22528)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4608)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4361)
    at android.view.View.updateDisplayListIfDirty(View.java:21653)
    at android.view.View.draw(View.java:22528)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4608)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4361)
    at android.view.View.updateDisplayListIfDirty(View.java:21653)
    at android.view.View.draw(View.java:22528)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4608)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4361)
    at android.view.View.updateDisplayListIfDirty(View.java:21653)
    at android.view.View.draw(View.java:22528)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4608)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4361)
    at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:3017)
    at android.view.View.draw(View.java:22811)
    at com.android.internal.policy.DecorView.draw(DecorView.java:899)
    at android.view.View.updateDisplayListIfDirty(View.java:21662)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:620)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:4737)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4441)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3523)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2299)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9127)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1232)
    at android.view.Choreographer.doCallbacks(Choreographer.java:1029)
    at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:375)
    at android.view.Choreographer.doFrame(Choreographer.java:913)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1217)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:233)
    at android.os.Looper.loop(Looper.java:344)
    at android.app.ActivityThread.main(ActivityThread.java:8210)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210290`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus9Pro`
* Model: `LE2123`
* Id: `RKQ1.211119.001`
* Product: `OnePlus9Pro_EEA`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `R.GDPR.202206251226`

**Comment by AlvaroBrey** [comment] 2022-09-08 07:44
Duplicate of #9948

**Closed by AlvaroBrey** 2022-09-08 07:44 UTC
Labels: bug
