### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector

### ISSUE THREAD

**Issue by changbindu** [nextcloud/android#6269] opened 2020-06-11 01:49 UTC
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.AnalyticsConnector
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120053
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7
Model: GM1900
Id: QKQ1.190716.003
Product: OnePlus7_CH

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2005160129

**Comment by AndyScherzinger** [comment] 2020-06-12 10:13
Duplicate of #4675

**Closed by AndyScherzinger** 2020-06-12 10:13 UTC
Labels: bug
