### ISSUE TITLE
Text editor: GBoard Return key broken and may delete all text

### ISSUE THREAD

**Issue by kolAflash** [nextcloud/android#8945] opened 2021-09-06 12:53 UTC
The Google "GBoard" Android keyboard's Return key does not work with the Nextcloud app's builtin text editor.
https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin
It shows different broken behaviors.

**1. Does not return**
If the current line ends with a letter (a-z / A-Z), `Return` simply does not work. The cursor stays in the current line and no new line is being inserted.
See: [return_broken_-_text_correction_setting.mp4](https://user-images.githubusercontent.com/3355089/132218988-13b0d5ce-9755-4c49-9cb2-3f0a12cc0a4b.mp4)

**2. Jumps to start of file or start of paragraph**
Sometimes (about 1 in 10 times) instead of inserting a new line (or simply doing nothing) the cursor jumps to the start of the file or the current paragraph.
See: [return_broken_-_text_correction_setting.mp4](https://user-images.githubusercontent.com/3355089/132218988-13b0d5ce-9755-4c49-9cb2-3f0a12cc0a4b.mp4)

 **3. Deletes all text**
Rarely (about 1 in 30 times) `Return` deletes all text from the file.
See: [return_deletes_text.mp4](https://user-images.githubusercontent.com/3355089/132219036-f1d21331-70db-46c0-b6b4-de968bdb2d01.mp4)

&nbsp;

### Reproduction and Workarounds

The bugs only happen if at least one of the following GBoard settings is enabled.
See: [return_deletes_text.mp4](https://user-images.githubusercontent.com/3355089/132219036-f1d21331-70db-46c0-b6b4-de968bdb2d01.mp4)
Unfortunately the are enabled by default and considered pretty useful widely. Disabling all of those settings will workaround the bug.
- Text correction
  - Show suggestion strip
  - Auto-correction
  - Spell check

Alternatively you can switch to another keyboard like [OpenBoard](https://github.com/dslul/openboard). This is an AOSP keyboard fork with auto correction that works fine with the Nextcloud apps text editor.

&nbsp;

I reproduced the GBoard bug with two smartphones:
- [Google Pixel 4a](https://en.wikipedia.org/wiki/Pixel_4a) running the stock OS with GBoard as default keyboard.
- [Fairphone 3+](https://en.wikipedia.org/wiki/Fairphone_3#Fairphone_3+) running [e-Foundation /e/ OS](https://en.wikipedia.org/wiki//e/_(operating_system)) (a LineageOS fork).
  - GBoard can be installed via eOS-AppStore, [Aurora-Store](https://f-droid.org/de/packages/com.aurora.store/), [ApkMirror.com](https://www.apkmirror.com/apk/google-inc/gboard/), ...

&nbsp;

Maybe related:
[nextcloud/files_texteditor -> #104 Android keyboard (Gboard) adds backspace to some keystrokes when editing a file](https://github.com/nextcloud/files_texteditor/issues/104)

**Comment by AlvaroBrey** [comment] 2021-09-07 11:19
This is reproducible but it seems the problem is in https://github.com/nextcloud/files_texteditor/issues/104 (this app's editor opens a WebView with the web editor) so I don't think we can do much unless it's fixed upstream.

**Comment by AlvaroBrey** [comment] 2021-09-07 12:23
Closing this, waiting for the upstream fix.

**Closed by AlvaroBrey** 2021-09-07 12:23 UTC
Labels: bug, approved
