### ISSUE TITLE
Creating folder in remotea sync option raise NPE

### ISSUE THREAD

**Issue by TheHendla** [nextcloud/android#4904] opened 2019-11-30 08:59 UTC
### Actual behaviour
- Tell us what happens
Creating folder in remotea sync option raise 

### Expected behaviour
- Tell us what should happen
Folder created
 
### Steps to reproduce
1. Open syncoption
2. Click on the top right corner triple button
3. Slect remote sync folder
4. Create folder in root folder

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate
![Screenshot_20191130-100003](https://user-images.githubusercontent.com/13124213/69898323-53ab3380-1358-11ea-8fad-f6cbfd584d48.png)

**Comment by AndyScherzinger** [comment] 2019-12-02 07:51
Duplicate of #4792  so closing in favor.

Thanks for reporting.

**Closed by AndyScherzinger** 2019-12-02 07:51 UTC
Labels: bug
