### ISSUE TITLE
Crash during sync of all data

### ISSUE THREAD

**Issue by zeitisen** [nextcloud/android#13831] opened 2024-10-20 17:52 UTC
### Cause of error
```java
Exception in thread "binder:32292_7" java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 1759432 free bytes and 1718KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
    at android.os.ThreadLocalWorkSource.setUid(ThreadLocalWorkSource.java:68)
    at android.os.Binder.execTransact(Binder.java:1250)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300190`
* Build flavor: `generic`

### Device information
* Brand: `motorola`
* Device: `pstar`
* Model: `motorola edge 20 pro`
* Id: `T1RAS33.55-15-10-6`
* Product: `pstar_retaile`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `2b5db-18379`

**Comment by zeitisen** [comment] 2024-10-20 17:53
New Version. Nextcloud is syncing everything for three days now. Permanently empty battery, not stoppable

**Comment by panki27** [comment] 2024-10-20 18:04
Suddenly today, my Nextcloud Android app started doing weird stuff - not sure if this is related, but it seems like it's downloading all my files to the device, even though I did not tell it that.

Worse, it has used up all my mobile data for that even though I set it to WiFi only.

**Comment by JVT038** [comment] 2024-10-20 18:54
> Suddenly today, my Nextcloud Android app started doing weird stuff - not sure if this is related, but it seems like it's downloading all my files to the device, even though I did not tell it that.
> 
> Worse, it has used up all my mobile data for that even though I set it to WiFi only.

I have the same issue! Suddenly, I got a notification that Netxtcloud started syncing thousands of files, while I didn't do anything.

I literally just uninstalled the Nextcloud app for now, because I couldn't find a way to prevent the sync from happening.

Hopefully the devs will fix it soon.

**Comment by PetersOtto** [comment] 2024-10-20 19:35
Same issue here!

* Phone: Teracube 2e with Android 12 (/e/ OS)
* Nextcloud Hub 9 (30.0.1)
* Nextcloud Client 3.30.1

**Comment by cypx** [comment] 2024-10-20 20:06
Same here:

- ASUS ZenFone 8 (sake) 
- Android 13 / LineageOS 20 with MicroG (no Google services)
- Nextcloud Hub 9 (30.0.1)
- Nextcloud Client 3.30.1 (from F-Droid)

**Comment by panki27** [comment] 2024-10-20 20:48
Duplicate of https://github.com/nextcloud/android/issues/13738

**Comment by joshtrichards** [comment] 2024-10-20 21:42
> New Version. Nextcloud is syncing everything for three days now. Permanently empty battery, not stoppable

@zeitisen I'm going to close this as a duplicate of #13738 given this comment and to avoid confusion. I suspect the OOM only occurred due to #13738, which is the real issue.

**Closed by joshtrichards** 2024-10-20 21:42 UTC
