### ISSUE TITLE
TXT preview quits on focus change or block the screen

### ISSUE THREAD

**Issue by jedwabny** [nextcloud/android#4169] opened 2019-06-22 08:47 UTC
### Actual behaviour
Starting from opened txt file. On skipping for a second to another application or blocking screen, then on coming back to Nextcloud client the file preview is quickly closed and coming back to the files list. 

Due to this behavior, txt file has to be opened again and again during any activity. 

Unfortunately, I don't remember since which version it appears. 

### Expected behaviour
- Keep file preview opened until closed by user (or killed by Android abviously). 
 
### Steps to reproduce
1. Create txt file
2. Open it in Nextcloud client
3. Switch to another application or block screen. 
4. Come back to Nextcloud client - file is quickly closed without user intention. 

### Environment data
Android version: 8.1.0

Device model: Asus zc553kl 

Stock or customized system: Asus Android

Nextcloud app version: 3.6.2

Nextcloud server version: 15.0.8

**Comment by ezaquarii** [comment] 2019-06-22 14:56
I can confirm this problem on newest master. It looks like an Activity state loss. I'll take a look at this.

**Comment by jedwabny** [comment] 2019-06-23 05:53
Good to hear that.

Thank you in advance.

**Comment by ezaquarii** [comment] 2019-07-09 21:30
This is general issue in app framework and it is reproducible in media preview too, as we discovered in #4208.

**Comment by jedwabny** [comment] 2019-08-08 12:52
No stale

**Comment by AndyScherzinger** [comment] 2019-08-08 13:13
@tobiasKaminsky I can reproduce this behavior too

**Comment by tobiasKaminsky** [comment] 2020-06-09 12:24
I cannot reproduce this, neither with download file (local preview) nor with online text editing.

**Comment by AndyScherzinger** [comment] 2020-06-12 11:35
cannot reproduce it anymore, so I'd close it as fixed.

Please reopen if still happening with 3.12+

**Closed by AndyScherzinger** 2020-06-12 11:35 UTC
Labels: bug, needs info/discussion
