### ISSUE TITLE
Media Streaming Doesn't Work

### ISSUE THREAD

**Issue by windows10luke** [nextcloud/android#3061] opened 2018-09-19 17:38 UTC
### Actual behaviour
- Tell us what happens
When tapping on a media file in the latest version of the app(3.3.0), it opens a player in the app, and then says in a little popup "Could not play the file using the builtin media player" and then it gives up.
### Expected behaviour
- Tell us what should happen
 It should play mp3 and mp4 files when selecting them.
### Steps to reproduce
1.  Tap a media file in the Nextcloud app
2.  Media Player opens and produces the error

### Environment data
Android version: 8.0

Device model: LG V30

Stock or customized system: Stock

Nextcloud app version: 3.3.0

Nextcloud server version:14.0

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by gradinaruvasile** [comment] 2018-09-20 01:49
I can confirm this bug.
Although streaming works with VLC at least (if you have it installed) by selecting the "Stream with..." option.

**Comment by johninstockie** [comment] 2018-09-20 11:03
I can confirm this bug too, however I am experiencing the opposite in that the internal video player works if you use the stream with option, but not with normal behavior, and VLC does not work by any method.

**Comment by breisig** [comment] 2018-10-01 04:46
I am having this exact same issue even with mp3's. Have to either download the file for it to play or stream with 'vlc' to play.

**Comment by galosre** [comment] 2018-10-16 16:44
I completely with the above Plus it would be nice to play files by folder in case of multiple tracks (album)

**Comment by DPTJKKVH** [comment] 2018-10-16 16:49
Is there something I can provide aside from a logcat? I wanted to upload a logcat but noticed it contains lots of confidential information like folder names, sync names and such.

**Comment by BeGunman** [comment] 2018-11-06 11:48
can also confirm this bug! having this exact same issue even with mp3's. Have to either download the file for it to play or stream with 'vlc' to play.

**Comment by alkamen** [comment] 2018-11-13 04:43
I can confirm this bug.
Plays mp4 some Time, but not mp4, or wav.

**Comment by DPTJKKVH** [comment] 2019-01-14 12:47
Has any of you force password on share link enabled? I have a hunch that this is an issue. At least for us that cannot stream anything.

**Comment by tobiasKaminsky** [comment] 2019-01-21 08:43
@rullzer this should not be related, or?

**Comment by rullzer** [comment] 2019-01-22 14:23
Nope unrelated

**Comment by tiredthinker** [comment] 2019-02-17 00:40
Similar as above. Version 3.5. Video streaming will work until switching to HTTPS. Went through 2 setups, apache2 and nginx. Both worked within the Android App prior to enabling secure connections. Reverting back fixed the streaming issue. What would cause this?

**Comment by DPTJKKVH** [comment] 2019-05-09 23:45
Issue still persists, stale[bot]. So hush...

**Comment by breisig** [comment] 2019-05-13 21:32
Yeah, the problem still exists.

**Comment by ezaquarii** [comment] 2019-05-13 21:43
@breisig Can you share a link to a media file that won't play?

**Comment by susobaco** [comment] 2019-05-25 18:28
#3351

**Comment by DPTJKKVH** [comment] 2019-06-22 19:35
@stale[bot] No Stalebot. This stays open until it is fixed!

**Comment by ezaquarii** [comment] 2019-06-22 19:54
Can you share a little no to media that causes the issue? We can't fix it if we can't reproduce it.

**Comment by DPTJKKVH** [comment] 2019-06-22 20:13
@ezaquarii I can provide log file excerpts if you tell me what you need. I won't share full logs since I log to syslog which  contains a bit too much private information. 😉 Same applies to logcat on android.

**Comment by ezaquarii** [comment] 2019-06-22 20:43
@DPTJKKVH Sorry, autocorrection messed up my previous message.

Can you pls share a link to a media that causes the issue? Media streaming works ok for me - I'm affraid that we cannot help you if we don't have any chance to investigate the issue in the first place.

**Comment by DPTJKKVH** [comment] 2019-06-22 21:32
@ezaquarii is hello@ezaquarii.com your "personal" email address in the sense that only you have access to it? I will send you a private share link since I don't want to publicly post my server and have random people poke around at it.

I hope my rambling is somewhat comprehensible. Thanks for offering your help, btw. 👍

**Comment by ezaquarii** [comment] 2019-06-22 21:50
@DPTJKKVH Yes, this is the right address. Please provide your application version too. Optmial solution would be to test it on daily dev build, as then I can start debugging it directly using master source code.

**Comment by DPTJKKVH** [comment] 2019-06-22 23:29
When you say "application version" do you mean my android app version, the nextcloud server version or a specific server app version? (In case of the latter please specify which app you mean.)

Also did you receive my link yet? If not I will send it to you manually.

**Comment by DPTJKKVH** [comment] 2019-06-22 23:43
btw: The last password is the right password. I never used the share feature with outside users. I didn't know that the server is generating a suitable password by itself so I set one manually after sharing the file.

**Comment by ezaquarii** [comment] 2019-06-23 21:31
@DPTJKKVH I received the file, thank you. Generally when you report any bug they will require both versions: mobile app and server, including any HTTP server too.

I tested the mp3 file and I can confirm that I can play it just fine.
However, when I select the file and open "3 dots" menu, "Stream with...", nothing happens.

I tried to play ogg file and it launched the player but shown "Could not play the file using the builtin media player" pop-up error message.

@DPTJKKVH Can you pls describe exactly the steps you take to reproduce the problem? It looks like there are several issues here and we need to investigate all of them separately.

Nice tune, BTW. ;)

**Comment by ezaquarii** [comment] 2019-06-23 21:33
@tobiasKaminsky @AndyScherzinger Is Nextcloud app using OS player or some custom, built-in app to decode media? I'd expect my Android stock media player to be able to play OGG Vorbis files.

**Comment by DPTJKKVH** [comment] 2019-06-24 05:23
The tune is from Bensound. He offers very nice royalty free music. Guess I better link back to him, to comply with the creative commons license
 ;) https://www.bensound.com/

Also what do you mean with ogg file? I only shared a mp3 with you, didn't I?

Sorry for the following bad formatting but I'm on mobile right now:

I use Android 9 and my Nextcloud Android version is 3.6.2.

My nextcloud server Version is 16.0.1.1

Ubuntu Server 18.04

PHP 7.2.17

MySQL 5.7.26

Those are my activated server apps: https://pasteboard.co/IkQIL15.jpg

Reproducing the error is easy. I upload a audio or video to nextcloud. I navigate nextcloud for android to it. Either by directly tapping the file or choosing the three dots and saying stream with... I cannot stream the file. The nextcloud app built in player loads for a couple of moments and then says it cannot be played. The Android built in player loads infinitely and VLC says the source cannot be played. I described my errors in one of my posts above in greater detail if needed.

**Comment by AndyScherzinger** [comment] 2019-06-24 07:36
@ezaquarii we use the built in capabilities

**Comment by DPTJKKVH** [comment] 2019-06-25 07:42
@ezaquarii @AndyScherzinger  Just to make sure: Do you need additional information?

Also @ezaquarii when you say you were able to play the mp3 just fine you say that the streaming worked with the Nextcloud App, right?

Do you use the PlayStore variant or the OSS variant without proprietary Google code? I use the latter. Maybe the OSS variant is lacking codecs to play media files?

**Comment by ezaquarii** [comment] 2019-07-05 18:13
@DPTJKKVH thank you for all the information. I'm trying to debug it and it looks like playing media that is downloaded works ok. There is a problem with streaming audio only.

**Comment by ezaquarii** [comment] 2019-07-05 18:15
@DPTJKKVH it looks like the player is started without preparation. The callbacks are not firing.
I'm considering the fix for it now.

**Comment by breisig** [comment] 2019-07-05 19:37
Yeah, if the media is downloaded then it seems to play [mp3's tested] but it won't work with streaming audio.

**Comment by ezaquarii** [comment] 2019-07-07 20:05
I'm going to ship a completely rewritten media player soon.

**Comment by DPTJKKVH** [comment] 2019-07-07 20:56
@ezaquarii Thank you a million! I really was dreading the missing streaming feature since I could use is for leisure and work but wasn't able to. I'm looking forward to test your player.

**Comment by redtux** [comment] 2019-07-09 18:18
After reading this thread I have just tried to download the mp3 before playing and it turns out that it really works, so I can confirm that the bug is related to streaming. What about automatically downloading the file when it is missing locally?

**Comment by ezaquarii** [comment] 2019-07-09 19:19
> What about automatically downloading the file when it is missing locally?

I can imagine it being slow, so some people want to stream it.

**Comment by DPTJKKVH** [comment] 2019-07-09 19:42
Yes, downloading defeats the purpose of streaming. If I have a 300 MB video file I want to stream it so I can start watching while the rest is downloading in the background.

**Comment by KimmoJ** [comment] 2019-08-01 08:15
For what it's worth, my Android 8.1 based phone also doesn't play, or stream, with 3.7.1 of the app. Of course, at least for MP3's (haven't tried video) if you want to stream you can just use the bog standard web interface on the phone as well; I have the Audio plugin installed and that works great over Firefox on Android too. Hoping for good things with an improved player.

**Comment by fdambrosio** [comment] 2019-09-07 16:08
I've fixed streaming problem on Android 9 adding 

```
<network-security-config>
<base-config cleartextTrafficPermitted="true">
    <trust-anchors>
        <certificates src="system" />
    </trust-anchors>
</base-config>

<domain-config cleartextTrafficPermitted="true">
    <domain includeSubdomains="true">localhost</domain>
    <domain includeSubdomains="true">radioradicale.it</domain>
</domain-config> 

</network-security-config>

```
in network_security_config.xml under project-root/resources/android/xml

like explained here: https://stackoverflow.com/a/57108997/2527604

**Comment by AndyScherzinger** [comment] 2019-10-01 10:33
For 3.9.0 there will of course be a RC, other than that you can install tomorrow's Dev build which then ships the latest development version including this change and it is installed in parallel to the official build.

**Comment by DPTJKKVH** [comment] 2019-10-01 11:19
I see that compiled dev builds are published on f-droid with a couple days delay. I'll be using this version then. I don't have a google account (play store) and dev builds are only published as source code on github, right?

**Comment by AndyScherzinger** [comment] 2019-10-01 13:20
Dev builds are published on f-Droid only while you can check for new versions within the app's settings page I think.

While @tobiasKaminsky knows best!

**Comment by redtux** [comment] 2019-10-02 08:55
Great to see this issue has been fixed. Yes, the dev build is on F-Droid. It is a featured app, and it is easy to find. (Current version is from 24 September 2019 and does not yet contain the fix.)

**Comment by AndyScherzinger** [comment] 2019-10-02 10:59
The is rather part of 20191001 since it has been merged less that a day ago so it'll go into the next nightly build.

**Comment by DPTJKKVH** [comment] 2019-10-07 14:00
I tested with 20191005 and neither MP3 nor MP4 can be streamed. Tested with Nextcloud "built-in" media player, VLC and mpv-android.

The error is 100% the same. VLC is the most descriptive saying: "Cannot access resource at $URL"

**Comment by gradinaruvasile** [comment] 2019-10-07 14:25
It is partially working on Dev 20191005.
For some media it does work (for example the Nextcloud logo animation and some cropped videos i had), but for others it is not (example is HD videos from phones). Maybe it is related to codecs or resolution?
VLC works with everything.

**Comment by DPTJKKVH** [comment] 2019-10-07 15:14
I doubt it is related to resolution. I tried both HD and SD mp4 videos. Also mp3 is so common it works with basically everything nowadays.

As I said I tried to "Stream with..." VLC and it gave the error I quoted above.

To be honest I always doubted the access errors had anything to do with the actual player.

If you ask me it has to do with our server forcing passwords for link shares. At least for the "Stream with..." option Nextcloud is creating a share link as far as I can tell by the VLC error. Right from the start I wondered how they get around   the password requirement without creating a possible backdoor for creating passwordless share links on a forced password setup. (I hope that wasn't too confusing.)

So I want to raise this question again: Are you really 100% sure that forcing passwords for share links really does not conflict with the "Stream with..." option that (as far as I can tell) creates a share link for the external media player to use?

@AndyScherzinger @rullzer @tobiasKaminsky

**Comment by tobiasKaminsky** [comment] 2019-10-08 09:35
> Right from the start I wondered how they get around the password requirement without creating a possible backdoor for creating passwordless share links on a forced password setup. (I hope that wasn't too confusing.)

When requesting such a link, no regular share link is created, but a special password-less link that only lasts 24h. 
As the url is nowhere exposed and read-only for only the specific file this is a good solution security wise.
As the link always is 32 chars, chances are also very limited to guess/bruteforce it.

**Comment by gradinaruvasile** [comment] 2019-10-08 10:21
> As I said I tried to "Stream with..." VLC and it gave the error I quoted above.

VLC definitely works for me with anything i throw at it in both the stable and the dev version.

**Comment by DPTJKKVH** [comment] 2019-10-08 11:17
I'm looking for differences of your and my setup. @gradinaruvasile 

I use an app token (with file access activated of course) for the nextcloud android app. How do you authenticate with the android app?

@tobiasKaminsky Thanks for the explanation. When the link is passwordless what else could block access to the file when downloading it via nextcloud app works without issues? VLC is explicitly saying it cant access the resource at $URL (hostname + path + auth-key)

To preempt some questions: VLC and mpv-android have full internet and storage access in android permissions manager. There is no firewall blocking either. Accessing other online ressources works fine with VLC.

**Comment by gradinaruvasile** [comment] 2019-10-08 11:30
> I'm looking for differences of your and my setup. @gradinaruvasile
> 
> I use an app token (with file access activated of course) for the nextcloud android app. How do you authenticate with the android app?

I believe the same as you. I just created an app password and scanned the qr code with the NC app.

**Comment by tobiasKaminsky** [comment] 2019-10-08 12:06
> @tobiasKaminsky Thanks for the explanation. When the link is passwordless what else could block access to the file when downloading it via nextcloud app works without issues? VLC is explicitly saying it cant access the resource at $URL (hostname + path + auth-key)

Tricky question. It is a normal url, which goes to a special endpoint within Nextcloud.
@rullzer do you have an idea?

**Comment by rullzer** [comment] 2019-10-09 14:21
@DPTJKKVH are you using server side encryption by any chance? With user keys? because in that case it won't work. Since the token does not have your password hence it can't unlock your files.

**Comment by DPTJKKVH** [comment] 2019-10-09 16:02
@rullzer Yes I do have server side crypto with user keys.

But now I'm curious: Sharing files with third parties via link works without issues on my setup. So users can expose individual files or folders on demand, regardless of the current encryption.

Is there a reason why media streaming links are treated different from normal share links in this regard?

**Comment by rullzer** [comment] 2019-10-09 17:54
What effectively happens during link sharing is that the file gets encrypted with the system key that is why it can be decrypted without knowing your password.

This step is probably missing in the direct link creation.

**Comment by redtux** [comment] 2019-10-09 20:41
Streaming and playing in background is working for me with ogg, mp3, mp4, m4a (but, as already mentioned, not with aac) using server-side encryption. The only thing that is not working for me is the "Streaming with…" button in the menu. (Nothing happens when I click on it.)

**Comment by lftsy** [comment] 2019-10-23 21:14
I have a Debian 10 + apache2 + nextcloud 16 + Server side encryption and do have the 
 same problem: I cannot stream mp4 nor use external player

Workaround : If I create a public link, then use external Player, it is working

Info: Streaming via Web Player works and the ios app was also working 

Debug  : If needed, I can share an account via private message to allow you to reproduce it at will?

**Comment by mathieu2em** [comment] 2019-12-11 22:32
for me, on android, mp4 video files works well on the native nextcloud app but not on the stream with vlc.
for .mpk , it just gives sound on native and media player and load indefinitely on vlc

**Comment by mathieu2em** [comment] 2019-12-11 22:49
ok. After some research , I just found out that the player is the reason for what codec is supported. So for example for my mkv files the player KMplayer does well on android but vlc doesnt and the native app neither . for mp4 native does well and vlc doesnt but the other two works... Sooo thats it , if it doesnt work for you , just chack different video player supporting the codec and you will find one !

**Comment by lftsy** [comment] 2020-03-22 06:04
> I have a Debian 10 + apache2 + HTTPS + nextcloud 16 + Server side encryption and do have the same problem: I cannot stream mp4 nor use external player from Android app
> 
> Workaround : If I create a public link, then use external Player within the app, it is working
> 
> Info: Streaming via Web Player works and the ios app was also working
> 
> Debug : If needed, I can share an account via private message to allow you to reproduce it at will?

I have the exact same setup and symptoms  and workaround but with version 18.0.2.
1) Does problem come from the fact that we enabled encryption ? But it is working on iOS app and Web players
2) Since it doest affect everybody, I am wondering what is the source of the problem (encryption, cumulative upgrades, apache2 setup) should I test with nginx ? 
3) What debug info we should provide to help here
4) I can also share an account via PM

Best Regards

**Comment by titilambert** [comment] 2020-04-04 04:51
Can you try to mount the webdav share and play a video with a local player ? I suspect that the issue comes from webdav which reduce the traffic... So heavy videos as issue to load ....

**Comment by haadr** [comment] 2020-04-11 11:36
Hey all, I had this problem and saw someone mentioning this failing when they enabled TLS. My nextcloud server is behind a proxy, which handles TLS, and the proxy itself happens via http. When vlc failed to stream a file, I saw that the url it tried to load was actually incorrect. 

My problem went away when I configured my config.php according to https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html. 

Maybe it helps someone.

**Comment by tobiasKaminsky** [comment] 2021-03-08 12:41
There is an experimental switch to another video player in https://github.com/nextcloud/android/pull/8132#issuecomment-792722526

This apk can be installed in parallel. 
It would be great if you can give this a test, if it helps in your scenario.

**Closed** 2021-06-09 09:16 UTC
Labels: approved, bug, pr exists

**Comment by lexvx** [comment] 2022-10-29 08:17
The problem is still there. Streaming in android APP not working.
Just installed the old version of the app (v3.10) and everything works fine in it.
Streaming in the application for iPhone works correctly.
