### ISSUE TITLE
Instant upload for the not-currently active account

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#25] opened 2016-06-15 07:17 UTC
copied from the forum https://help.nextcloud.com/t/android-app-one-app-instance-for-each-account/605
As far as I understand the request the issue is that instant upload only works for the currently active account:

> Hello,
> sorry if this is the wrong place to post about the Android app. I've tried to use the mail address
> apps@nextcloud.com (proposed by the app itself) but got the answer "no such user".
> So this is my feature wish:
> 
> I've two owncloud accounts as a normal user (two
> more as admin) and would like to have different instances of the app
> each with it's own account assigned. Is that possible? At this time the
> automatic photo/video upload works only on the active account. I would
> like to assigned it to only one account and have this always active, so every
> uploaded photo will be stored under the same account. The other accounts should be
> active also at the same time.
> 
> Thank you
> Jürgen

Looping in @jancborchardt for UX aspects and @przybylski and @tobiasKaminsky for general discussion/approval of the feature request

**Comment by bes1002t** [comment] 2016-06-15 16:41
mh I don't know whether this is an good idea or not. In my opinion we should implement an account management system in our android application. That would be much cleaner than creating a new instance for every account.

**Comment by tobiasKaminsky** [comment] 2016-06-15 16:56
Multiple instances of the app are not possible.
I remember that there is a PR in ownCloud that, at least, shows to which account the instant upload is set.
Technical background: the instant upload is not always to the current accout, but to the account which was in use when the instant upload is defined.

So my proposal is to make the account to which instant upload is bound to easier to choose.
@jancborchardt for designing.

**Comment by tobiasKaminsky** [comment] 2016-06-15 16:57
https://github.com/owncloud/android/pull/1637
@LukeOwncloud maybe you want to help us here? I promise that your PR will be handled much faster :+1:

**Comment by jgrete** [comment] 2016-06-15 18:38
Hello,

I'm the OP from help.nextcloud.com.
I've learned multiple instances of an app are not possible. OK, an account managment would do also.
The following are just my thoughts:
- the active account should be visible all the time (maybe next to "Nextcloud" ?)
- choosing the active account is misplaced in the settings and would be better placed in the left  
  menu at toplevel as a dropdown, so changing an account is easier
- the account used for uploading should be marked as such in the dropdown
- if the upload account is not the active acount no instant upload would happen, wouldn't it?
  That was the reason many of my instant uploads didn't work. Is there a better solution?

As I said - just my thoughts :-)

Thank you very much
Jürgen

**Comment by LukeOwncloud** [comment] 2016-06-17 07:27
If I understant correctly, this should be handled by https://github.com/owncloud/android/pull/1637. @tobiasKaminsky Sorry, I cannot contribute in these days.

**Comment by jancborchardt** [comment] 2016-06-17 08:25
> choosing the active account is misplaced in the settings and would be better placed in the left
menu at toplevel as a dropdown, so changing an account is easier

@jgrete there is already a pull request for that and it will be in shortly I assume. :) cc @AndyScherzinger

**Comment by tobiasKaminsky** [comment] 2016-06-17 13:50
This seems a very easy PR, so adding it to next milestone.

**Comment by tobiasKaminsky** [comment] 2016-06-17 16:02
@LukeOwncloud the mentioned PR is only in your repository.
Can you push it to this repository. 
Then I can have a look, update it and so on.

**Comment by tobiasKaminsky** [comment] 2016-06-21 20:12
To get a 1.1.0 a little quicker we postpone this to 1.2.0

**Comment by jgrete** [comment] 2016-06-24 07:34
The latest beta2010621 works quite well - no crashes so far.
A minor bug seems to be that there is no "instant" update of the files list after choosing a different account from the dropdown. One have to wait until the screen gets locked. After unlocking the screen the files list is getting updated (caused by an event ?). Manually updating the account (via '...' menu) works well. In no case there's any visual feedback (except the changing files list) which might be suboptimal.

Thank you
Jürgen

**Comment by tobiasKaminsky** [comment] 2016-06-24 13:43
@jgrete this is is a different issue so please report it as a new issue

**Comment by AndyScherzinger** [comment] 2016-07-06 10:44
I moved Luke's changes to a branch within the nextcloud repo. I hope this is fine with you @LukeOwncloud ? --> #98

**Comment by LukeOwncloud** [comment] 2016-07-06 11:13
@AndyScherzinger Yes, of course! Thank you! @tobiasKaminsky Sorry for not pushing my changes. Too busy....

**Comment by AndyScherzinger** [comment] 2016-07-13 09:27
It seems one issue has been found with this one: If the user enables the instant upload and doesn't change the default folder, no account is saved as target account and the upload is not done. The broadcast receiver logs:

```07-13 11:07:55.544 14302-14302/com.owncloud.android W/com.owncloud.android.files.InstantUploadBroadcastReceiver: No account found for instant upload, aborting```

**Comment by mario** [comment] 2017-04-12 23:27
Fixed at least for Auto Upload, and that's pretty much all we care about anyway.

**Comment by tobiasKaminsky** [comment] 2017-04-30 07:39
To explain it to other users: we will replace InstantUpload on all devices with Auto Upload.

**Closed** 2017-04-30 07:40 UTC
