### ISSUE TITLE
Upload fails when last upload folder is removed

### ISSUE THREAD

**Issue by don-philipe** [nextcloud/android#11218] opened 2023-01-03 12:48 UTC
Hi,

I tried to upload a file from another app via the share button. The folder "A", where I uploaded last time to my Nextcloud, doesn't exist anymore on the server, as well as the folder "B" where "A" was in. Now, when trying to upload files, the last upload folder "A" is selected by default, but I can't switch to another folder (via the back-button in the upper left corner) because that action would be a switch to the folder "B" one level higher, that doesn't exist anymore. This back-action leads to the following error:

### Cause of error
```java
Exception in thread "Thread-4" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:761)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230190`
* Build flavor: `generic`

### Device information
* Brand: `Sony`
* Device: `suzuran`
* Model: `E5823`
* Id: `NJH47F`
* Product: `suzuran`

### Firmware
* SDK: `25`
* Release: `7.1.2`
* Incremental: `b7b736e064` 

It's an annoying bug, because I see no other way of dealing with it than recreating the removed folders.
I would love to see another solution to this :pray:

**Comment by AlvaroBrey** [comment] 2023-01-09 16:24
Duplicate of #11207

**Closed by AlvaroBrey** 2023-01-09 16:24 UTC
