### ISSUE TITLE
Nextcloud android app crash

### ISSUE THREAD

**Issue by lkjasdf9kl** [nextcloud/android#10979] opened 2022-11-03 12:25 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open nextcloud android app
2. Settings
3. Auto upload

### Expected behaviour

Be able to initiate Auto Upload of photos from my android phone. This will be uploaded to my self-hosted local nextcloud server.

### Actual behaviour

Nextcloud app crashes.

### Android version

13

### Device brand and model

Samsung galaxy s22

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.2

### Nextcloud server version

13.0.U3

### Using a reverse proxy?

I don't know

### Server error logs

```bash
Android error log:

### Cause of error

Exception in thread "DefaultDispatcher-worker-1" java.lang.IllegalStateException: Method addObserver must be called on the main thread
    at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:323)
    at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:178)
    at androidx.fragment.app.FragmentManager.setFragmentResultListener(FragmentManager.java:975)
    at com.owncloud.android.utils.PermissionUtil.showPermissionChoiceDialog(PermissionUtil.kt:216)
    at com.owncloud.android.utils.PermissionUtil.requestExternalStoragePermission(PermissionUtil.kt:127)
    at com.owncloud.android.datamodel.MediaProvider.checkPermissions(MediaProvider.java:180)
    at com.owncloud.android.datamodel.MediaProvider.getImageFolders(MediaProvider.java:79)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$load$1.invokeSuspend(SyncedFoldersActivity.kt:292)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)



### App information
* ID: `com.nextcloud.client`
* Version: `30220290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `r0q`
* Model: `SM-S901U`
* Id: `TP1A.220624.014`
* Product: `r0qNextcloud app crashes. Here is the error:

### Cause of error
```java
Exception in thread "DefaultDispatcher-worker-1" java.lang.IllegalStateException: Method addObserver must be called on the main thread
    at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:323)
    at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:178)
    at androidx.fragment.app.FragmentManager.setFragmentResultListener(FragmentManager.java:975)
    at com.owncloud.android.utils.PermissionUtil.showPermissionChoiceDialog(PermissionUtil.kt:216)
    at com.owncloud.android.utils.PermissionUtil.requestExternalStoragePermission(PermissionUtil.kt:127)
    at com.owncloud.android.datamodel.MediaProvider.checkPermissions(MediaProvider.java:180)
    at com.owncloud.android.datamodel.MediaProvider.getImageFolders(MediaProvider.java:79)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$load$1.invokeSuspend(SyncedFoldersActivity.kt:292)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `r0q`
* Model: `SM-S901U`
* Id: `TP1A.220624.014`
* Product: `r0qsqw`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `S901USQU2BVJA`sqw`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `S901USQU2BVJA`
```


### Additional information

_No response_

**Comment by AlvaroBrey** [comment] 2022-11-03 13:58
Duplicate of #10975

**Closed by AlvaroBrey** 2022-11-03 13:58 UTC
Labels: bug

**Comment by lkjasdf9kl** [comment] 2022-11-03 14:15
Thank you @AlvaroBrey !

**Comment by lkjasdf9kl** [comment] 2022-11-04 00:04
@AlvaroBrey the app successfully uploads after today's update! Thanks again!
