### ISSUE TITLE
Java error when trying to mark auto uploaded pics

### ISSUE THREAD

**Issue by WarpinWolf** [nextcloud/android#10949] opened 2022-10-27 16:12 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I open nextcloud. I go to auto uploaded folder. I try to scroll. Very much lag! I press and hold file. Nothing happens. Trying to scroll up and down. Pressing. Suddenly:
### Cause of error
```java
Exception in thread "main" 

### Expected behaviour

Possible to mark pics to share etc..

### Actual behaviour

### Cause of error
```java
Exception in thread "main" java.lang.OutOfMemoryError: Failed to allocate a 2064 byte allocation with 816368 free bytes and 797KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
    at com.google.gson.stream.JsonReader.<init>(JsonReader.java:229)
    at com.google.gson.Gson.newJsonReader(Gson.java:865)
    at com.google.gson.Gson.fromJson(Gson.java:1015)
    at com.google.gson.Gson.fromJson(Gson.java:959)
    at com.google.gson.Gson.fromJson(Gson.java:927)
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:1039)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:895)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:189)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:614)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1321)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1269)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1258)
    at com.owncloud.android.ui.activity.FileDisplayActivity.updateListOfFilesFragment(FileDisplayActivity.java:603)
    at com.owncloud.android.ui.activity.FileDisplayActivity$UploadFinishReceiver.onReceive(FileDisplayActivity.java:1408)
    at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
    at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220190`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `a52sxq`
* Model: `SM-A528B`
* Id: `SP1A.210812.016`
* Product: `a52sxqeea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `A528BXXS1CVI6`

### Android version

12

### Device brand and model

Samsung A52

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.1

### Nextcloud server version

24.0.6

### Using a reverse proxy?

No

**Comment by AlvaroBrey** [comment] 2022-11-23 12:15
Duplicate of #10624

**Closed by AlvaroBrey** 2022-11-23 12:15 UTC
Labels: bug, performance
