### ISSUE TITLE
Crash when accessing "notifications"

### ISSUE THREAD

**Issue by W0rmsy** [nextcloud/android#6532] opened 2020-07-24 08:55 UTC
### Steps to reproduce
1. Open the app
2. Go on menu->notifications->crash
3. I tried to clean notification, no more crash. When a new notification arrives like an update or a MFA approval -> crash (i can accept the MFA at least) 

### Expected behaviour
- no crash 

### Actual behaviour
- When a new notification arrives like an update or a MFA approval. If i go to the notification tab -> crash (i can accept the MFA at least) 

### Environment data
Android version:10

Device model: Samsung S10

Stock or customized system:Stock

Nextcloud app version:3.12.1

Nextcloud server version:18.0.7

Reverse proxy:none (served directly by apache2) 

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.AnalyticsConnector
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond1
Model: SM-G973F
Id: QP1A.190711.020
Product: beyond1ltexx

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G973FXXS7CTF3
```

**Comment by tobiasKaminsky** [comment] 2020-07-24 11:53
Duplicate of #4675

**Closed by tobiasKaminsky** 2020-07-24 11:54 UTC
Labels: bug
