### ISSUE TITLE
Cause of error ```java

### ISSUE THREAD

**Issue by 01Pebmann** [nextcloud/android#13765] opened 2024-10-10 22:43 UTC
### Cause of error
```java
Exception in thread "main" android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{1ee0174 u0 com.nextcloud.android.beta/androidx.work.impl.foreground.SystemForegroundService}
    at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2004)
    at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1978)
    at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2240)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7918)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20241008`
* Build flavor: `versionDev`

### Device information
* Brand: `SHIFT`
* Device: `axolotl`
* Model: `SHIFT6mq`
* Id: `TQ3A.230605.012`
* Product: `axolotl`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `20230621`

**Comment by 01Pebmann** [comment] 2024-10-10 22:44
Q

**Comment by joshtrichards** [comment] 2024-10-15 13:53
Duplicate of #12706

**Closed by joshtrichards** 2024-10-15 13:53 UTC
Labels: bug, performance: general/non-specific, stable-3.31 (upcoming/still dev)
