### ISSUE TITLE
bug at startup

### ISSUE THREAD

**Issue by galvalarzen** [nextcloud/android#11328] opened 2023-01-30 10:12 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Dont start crashes

### Expected behaviour

Chrash at startup

### Actual behaviour

Just chrashes

### Android version

lineageos 17

### Device brand and model

oneplus 5

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

dont know Newest update

### Nextcloud server version

dont know

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:907)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:138)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByEncryptedRemotePath(FileDataStorageManager.java:122)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:118)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2423)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
    at android.app.Activity.performStart(Activity.java:8018)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7664)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20230121`
* Build flavor: `versionDev`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus6T`
* Model: `ONEPLUS A6013`
* Id: `RQ3A.211001.001`
* Product: `OnePlus6T`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `2a9b90edcc`

**Comment by AlvaroBrey** [comment] 2023-01-30 10:14
Duplicate of #11305

**Closed by AlvaroBrey** 2023-01-30 10:14 UTC
Labels: bug, dev version

**Comment by galvalarzen** [comment] 2023-01-30 10:16
What to do?

mandag den 30. januar 2023 skrev Álvaro Brey ***@***.***>:
> Duplicate of #11305
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci5.googleusercontent.com/proxy/sAzTtcv37TXclyjwM9WK3Uxk1xksyvVP3ShErr50sltBukeAvi9WfMDr2s2vFViPJU_uLskxYQIlbED5x_5cHT2UVFBK7bfAJTDEe3s4o0yBXjpIaX1DAjkiBCzh05YEGo91-HycOdpFjFMSn3QJUQZt6xo40yypoKvTQDNBmMW3nBDWurkOdz9CGnNxKh6xjNBTJvpWZUaxlkKQVXIhjIHZ2DIN-eRVgzLroffUiylSXxL-ng=s0-d-e1-ft#https://github.com/notifications/beacon/A5RTWS2SAEPLEX6MUBZ4GETWU6IAZA5CNFSM6AAAAAAUK6MI6WWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTST6GF3O.gif>Message
ID: ***@***.***>
