### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by ScottLiu2019** [nextcloud/android#5713] opened 2020-03-23 00:04 UTC
************ CAUSE OF ERROR ************

android.view.InflateException: Binary XML file line #7: Error inflating class android.webkit.WebView
	at android.view.LayoutInflater.createView(LayoutInflater.java:642)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:727)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:786)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:851)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:510)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:420)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:371)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
	at com.owncloud.android.authentication.AuthenticatorActivity.onNewIntent(AuthenticatorActivity.java:919)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1220)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1232)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2535)
	at android.app.ActivityThread.performNewIntents(ActivityThread.java:2547)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2556)
	at android.app.ActivityThread.access$1700(ActivityThread.java:175)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1441)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5418)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:616)
	... 24 more
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x2040003
	at android.content.res.Resources.getText(Resources.java:318)
	at android.content.res.VivoResources.getText(VivoResources.java:123)
	at android.content.res.Resources.getString(Resources.java:404)
	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:694)
	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:618)
	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)
	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:780)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:619)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:556)
	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:312)
	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:264)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:261)
	at android.webkit.WebView.<init>(WebView.java:554)
	at android.webkit.WebView.<init>(WebView.java:489)
	at android.webkit.WebView.<init>(WebView.java:472)
	at android.webkit.WebView.<init>(WebView.java:459)
	... 27 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: vivo
Device: PD1602
Model: vivo X7
Id: LMY47V
Product: PD1602

************ FIRMWARE ************
SDK: 22
Release: 5.1.1
Incremental: eng.compiler.20190812.110850

**Comment by tobiasKaminsky** [comment] 2020-03-23 05:17
@Shagequi do you have an idea? I thought this should be fixed with you appcompat bump?

**Closed** 2020-03-23 05:44 UTC
Labels: approved, bug

**Comment by AndyScherzinger** [comment] 2020-03-23 08:35
@tobiasKaminsky yes this is the Androids 5 string bug and should be fixed with the appcompat bump

**Comment by Shagequi** [comment] 2020-03-26 11:11
The issue is closed, I think you no longer need me here x)
