### ISSUE TITLE
Infinite unlock loop, even persist in device lock screen

### ISSUE THREAD

**Issue by amalgame21** [nextcloud/android#13390] opened 2024-08-09 08:28 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. setup password
2. close the app
3. open the app, input password
2. goto an E2EE folder
4. select one of the .md file inside the encrypted folder
5. click 3-dot button, select "open with"
6. input password -> input password -> input password -> loop
7. press power button to lock the screen
8. press power button to wake up the phone
9. nextcloud  input password loop even if the phone is unlocked
10. sometime nextcloud crash which will end the loop, but sometimes it doesn't...

### Expected behaviour

no password loop

### Actual behaviour

password input loop

### Android version

14

### Device brand and model

pixel 5

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

30290190

### Nextcloud server version

29.0.4

### Using a reverse proxy?

Yes

### Additional information
GrapheneOS

**Comment by joshtrichards** [comment] 2024-11-25 21:19
Duplicate of #13572

**Closed by joshtrichards** 2024-11-25 21:19 UTC
Labels: bug, feature: authentication, feature: encryption (client-side), stable-3.29
