### ISSUE TITLE
can't login Android 6.0

### ISSUE THREAD

**Issue by kisloid124** [nextcloud/android#4585] opened 2019-09-30 22:19 UTC
### Actual behaviour
- app crashes after tap on login button

### Expected behaviour
- shows up login screen
 
### Steps to reproduce
1. Open app
2. Tap on login button
3. App crashes

### Environment data
Android version: 6.0

Device model: Meizu pro 6 (M570H) 

Stock or customized system:  Flyme 6.3.0.0G

Nextcloud app version: 3.8.0

Nextcloud server version: 16.0
#### Web server error log
```
I can't even input server address in app
```
#### Nextcloud log (data/nextcloud.log)
```
I can't even input server address in app
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by DIeMONdello** [comment] 2019-10-02 20:26
Me too

**Comment by AndyScherzinger** [comment] 2019-10-07 18:54
Any stack traces?

**Comment by tobiasKaminsky** [comment] 2019-10-08 07:57
I suspect this is a duplicate of #4619

**Closed** 2019-10-08 07:58 UTC
Labels: bug
