### ISSUE TITLE
critical bug

### ISSUE THREAD

**Issue by qxg299** [nextcloud/android#5365] opened 2020-01-31 17:26 UTC
************ CAUSE OF ERROR ************

android.view.InflateException: Binary XML file line #7: Error inflating class android.webkit.WebView
	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
	at android.view.LayoutInflater.inflate(<Xposed>)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
	at com.owncloud.android.authentication.AuthenticatorActivity.onGetServerInfoFinish(AuthenticatorActivity.java:1319)
	at com.owncloud.android.authentication.AuthenticatorActivity.onRemoteOperationFinish(AuthenticatorActivity.java:1218)
	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:716)
	at com.owncloud.android.services.-$$Lambda$OperationsService$2BVgsxDpOpa4JqgzeD7OGZBLSiI.run(lambda)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	... 25 more
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x2040003
	at android.content.res.Resources.getText(Resources.java:321)
	at android.content.res.XResources.getText(XResources.java:1063)
	at android.content.res.Resources.getString(Resources.java:407)
	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:684)
	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)
	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:780)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:619)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:556)
	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:311)
	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:263)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:260)
	at android.webkit.WebView.<init>(WebView.java:554)
	at android.webkit.WebView.<init>(WebView.java:489)
	at android.webkit.WebView.<init>(WebView.java:472)
	at android.webkit.WebView.<init>(WebView.java:459)
	... 28 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: hermes
Model: Redmi Note 2
Id: LMY48Y
Product: cm_hermes

************ FIRMWARE ************
SDK: 22
Release: 5.1.1
Incremental: 88cafaeebc

**Comment by AndyScherzinger** [comment] 2020-01-31 23:19
Duplicate of #4943

**Closed by AndyScherzinger** 2020-01-31 23:19 UTC
Labels: bug
