### ISSUE TITLE
Auto uploading with custom folders is not working

### ISSUE THREAD

**Issue by BradXiao** [nextcloud/android#9424] opened 2021-12-01 14:40 UTC
Auto uploading with custom folders is not working, whereas the **folders detected by app automatically work just fine**.

### Steps to reproduce
1. Click settings
2. Click auto uploading
3. Add a custom folder
4. Select a folder

### Expected behaviour
It should appear the folder I just selected.

### Actual behaviour
It only appears the root directory and the selected folder is not monitored at all.

### Environment data
Android version: 11

Device model: Galaxy Note10

Stock or customized system: stock

Nextcloud app version: 3.18.0

Nextcloud server version: 23.0.0

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### A few screenshots
These auto detected folders work just fine.
<img src="https://user-images.githubusercontent.com/20597547/144252277-36cf3064-a2e1-45ec-b696-224847d633c1.jpg" width="200" >

Add a custom folder and click the button to browse a folder.
<img src="https://user-images.githubusercontent.com/20597547/144252420-2c01b666-7526-469f-9e52-79805dfc03d0.png" width="200" >

Select the 'aaa' folder for example.
<img src="https://user-images.githubusercontent.com/20597547/144252580-4c667335-2966-48c4-b810-a1f0ed9b7212.jpg" width="200" >

After selecting a folder, the shown path is incorrect and will not work for auto uploading.
<img src="https://user-images.githubusercontent.com/20597547/144252723-db15658d-2879-4307-a6f7-a7947a87a5f8.png" width="200" >

**Comment by AlvaroBrey** [comment] 2021-12-02 09:17
Duplicate of #8940

**Closed by AlvaroBrey** 2021-12-02 09:17 UTC
Labels: bug
