### ISSUE TITLE
Android App crash [OOM]

### ISSUE THREAD

**Issue by markyman2975** [nextcloud/android#11627] opened 2023-05-15 19:47 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Starting App, when Upload the App Crash

### Expected behaviour

Upload Pictures

### Actual behaviour

The App crash

### Android version

12

### Device brand and model

OnePlus Nord 2

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.2

### Nextcloud server version

26

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "Thread-7" java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 4655328 free bytes and 4546KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
    at org.apache.harmony.xml.dom.InnerNodeImpl.getChildNodes(InnerNodeImpl.java:56)
    at org.apache.jackrabbit.webdav.xml.DomUtil.hasContent(DomUtil.java:377)
    at org.apache.jackrabbit.webdav.property.DefaultDavProperty.createFromXml(DefaultDavProperty.java:127)
    at org.apache.jackrabbit.webdav.MultiStatusResponse.createFromXml(MultiStatusResponse.java:463)
    at org.apache.jackrabbit.webdav.MultiStatus.createFromXml(MultiStatus.java:185)
    at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.processResponseBody(DavMethodBase.java:282)
    at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1749)
    at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
    at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
    at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
    at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:195)
    at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:80)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:205)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:405)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:239)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240290`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OP515BL1`
* Model: `DN2103`
* Id: `SP1A.210812.016`
* Product: `DN2103EEA`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `R.GDPR.f1ba30-5fd8`

**Comment by joshtrichards** [comment] 2024-07-10 20:17
Duplicate of #9903

**Closed by joshtrichards** 2024-07-10 20:17 UTC
Labels: bug, performance: OOM :brain:, Version/3024
