### ISSUE TITLE
OOM in `ReadFolderRemoteOperation`

### ISSUE THREAD

**Issue by MoradDerhourhi** [nextcloud/android#13477] opened 2024-08-27 23:50 UTC
### Cause of error
```java
Exception in thread "Thread-25" java.lang.OutOfMemoryError: Failed to allocate a 42184 byte allocation with 32016 free bytes and 31KB until OOM, target footprint 402653184, growth limit 402653184
    at org.apache.jackrabbit.webdav.MultiStatus.getResponses(MultiStatus.java:128)
    at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.readData(ReadFolderRemoteOperation.java:133)
    at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:70)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:413)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:247)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:387)
    at java.lang.Thread.run(Thread.java:929)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20240827`
* Build flavor: `versionDev`

### Device information
* Brand: `HUAWEI`
* Device: `HWELS`
* Model: `ELS-NX9`
* Id: `HUAWEIELS-N29`
* Product: `ELS-N29`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `102.0.0.386C432`

**Comment by joshtrichards** [comment] 2024-08-30 22:45
Duplicate of #13161 (possibly others, but that one for certain)

**Closed by joshtrichards** 2024-08-30 22:45 UTC
Labels: bug, performance: OOM :brain:, stable-3.30
