### ISSUE TITLE
 Open Office documents via MS Office Online

### ISSUE THREAD

**Issue by shaensel-ito** [nextcloud/android#8288] opened 2021-04-16 07:24 UTC
It should be possible to open Office documents (doc, docx, xls, xlsx ...) via the app if MS Office Online is used as the collobaration variant.

**Comment by joshtrichards** [comment] 2023-12-07 16:09
This requires the `officeonline` integration app to add a a direct editing api.

See nextcloud/officeonline#231

**Comment by joshtrichards** [comment] 2024-08-09 19:01
Duplicate of nextcloud/officeonline#231

**Closed by joshtrichards** 2024-08-09 19:01 UTC
Labels: enhancement, feature: editor, server
