### ISSUE TITLE
Logged in at reinstall

### ISSUE THREAD

**Issue by simonbison01** [nextcloud/android#8796] opened 2021-07-31 20:58 UTC
### Steps to reproduce
1. Log into app
2. Re- / uninstall Nextcloud
3. Refresh App

### Expected behaviour
- Throw the user back to the register screen

### Actual behaviour
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: mmh4p-pr
Model: LM-X520
Id: QKQ1.200531.002
Product: mmh4p-pr_f

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2107304000e9f

**Comment by AndyScherzinger** [comment] 2021-08-01 14:36
Duplicate of #8370

**Closed by AndyScherzinger** 2021-08-01 14:36 UTC
Labels: bug
