### ISSUE TITLE
Constant crashing on one of my android devices

### ISSUE THREAD

**Issue by declanmarks** [nextcloud/android#5526] opened 2020-02-26 22:30 UTC
Regularly receiving this error. This error only happens on one of my devices. This error pops up even when client is running in the background. I see it after returning to my device after a few hours.

```
************ CAUSE OF ERROR **********

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-_M1olP4K_ZG1epGCSJop8g==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-_M1olP4K_ZG1epGCSJop8g==/lib/arm64, /data/app/com.nextcloud.client-_M1olP4K_ZG1epGCSJop8g==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gts4lwifi
Model: SM-T830
Id: PPR1.180610.011
Product: gts4lwifixx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: T830XXU4BSJ6
```

### Environment data
Android version: Android 9.0
Device model: Samsung Tab S4 (SM-T830)
Stock or customized system: Stock ROM
Nextcloud app version: Current Beta version (3.10.1)
Nextcloud server version: 18.0.1

**Comment by AndyScherzinger** [comment] 2020-03-10 22:02
Duplicate of #4675

**Closed by AndyScherzinger** 2020-03-10 22:02 UTC
Labels: bug
