### ISSUE TITLE
Search crash the app

### ISSUE THREAD

**Issue by ralfi** [nextcloud/android#3951] opened 2019-05-05 18:21 UTC
Hi nextcloudies,

App crashes if i try to search for something. If i use browser access everything works. Nothing in protocol section, using latest dev 20190504 with  nc16 stable.

**Comment by ralfi** [comment] 2019-05-05 19:16
Crashes only with dev, 3.6 from GPlay works well

**Comment by tobiasKaminsky** [comment] 2019-05-06 12:04
This is the same root cause like #3949 and fixed with new library, starting tomorrow in dev and also in 3.6.1.

**Closed by tobiasKaminsky** 2019-05-06 12:04 UTC

**Comment by ralfi** [comment] 2019-05-06 12:31
Thank you, Tobias
