### ISSUE TITLE
Watching photos on Faiprhone

### ISSUE THREAD

**Issue by kaelte** [nextcloud/android#5665] opened 2020-03-16 06:37 UTC
### Steps to reproduce
1. Open folder on Nextcpud with photos
2. Watch photos by sliding through

### Expected behaviour
- Display photos

### Actual behaviour
- Crashes after having displaied several photos. Number differ

### Logs
************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError: Failed to allocate a 44826636 byte allocation with 8500744 free bytes and 8MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:646)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:622)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:660)
	at com.owncloud.android.ui.adapter.DiskLruImageCache.getBitmap(DiskLruImageCache.java:121)
	at com.owncloud.android.datamodel.ThumbnailsCacheManager.getBitmapFromDiskCache(ThumbnailsCacheManager.java:225)
	at com.owncloud.android.ui.preview.PreviewImageFragment.onStart(PreviewImageFragment.java:254)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2632)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManagerImpl.java:2619)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:257)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:551)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
	at com.owncloud.android.ui.activity.DrawerActivity.onStart(DrawerActivity.java:1430)
	at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:207)
	at com.owncloud.android.ui.preview.PreviewImageActivity.onStart(PreviewImageActivity.java:186)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
	at android.app.Activity.performStart(Activity.java:6740)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2629)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4520)
	at android.app.ActivityThread.-wrap19(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6128)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Fairphone
Device: FP2
Model: FP2
Id: 19.11.2
Product: FP2

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: sibon-24df0be9

**Comment by tobiasKaminsky** [comment] 2020-03-19 18:25
Are those images on disc?
How big are the images?

Do you know how many ram the FP has?

**Comment by kaelte** [comment] 2020-03-20 18:35
> Are those images on disc?

I do not know. I guess the app downloads the photos before trying to display.

> How big are the images?

Each image has between 2 and 9 MiB.
I can view a few photos before the app crashes. The number varies between 10 and 30.

> Do you know how many ram the FP has?

It says 1.8 GB. So I guess 2GB.

**Comment by tobiasKaminsky** [comment] 2020-03-21 18:56
> I do not know. I guess the app downloads the photos before trying to display.

you can see if the images have a green checkmark in file list.
If not, then it is just a screen adapted size, which is only 80-100kb big.
Then it would be even more surprising if it crashes due to OOM.

**Comment by tobiasKaminsky** [comment] 2020-03-23 14:02
Duplicate of #5479

**Closed** 2020-03-23 14:01 UTC
Labels: bug, needs info/discussion
