### ISSUE TITLE
In-App Text Editor

### ISSUE THREAD

**Issue by cwmke** [nextcloud/android#126] opened 2016-07-13 16:51 UTC
I would be great to be able to edit text, html, css and other text files in the app.  Currently we can view the file but in order to edit, you need to share with a text editor.  Thanks for any consideration.

**Comment by przybylski** [comment] 2016-07-13 17:13
Nextcloud android app is not all in one solution and it should stay that way. Beside it is at the core of Android ecosystem to make apps cooperate

**Comment by cwmke** [comment] 2016-07-13 17:55
I don't mean to imply that an entire app with a full suite of formating features should be implemented.  I just meant for a basic type, delete and save ability such as you can do in the nextCloud webapp.  The webapp doesn't implement any special features, it just makes it very convenient to make quick text corrections and additions.  

I don't feel like that would make full featured editors any less relevant.  If I'm reading a text note and I want to correct some error I detect, it would be nice to be able to do so from within the app.  I understand and appreciate your need not to turn nextCloud Android into a swiss army knife.

**Comment by AndyScherzinger** [comment] 2016-07-13 19:40
I agree with both of you. As for easily editing of files a writable document provider might solve this to some extend. As for the in app editing I also get the point. 
The problem might simply be the handling of edits since we most likely would have to deal with charsets and character encodings which is always a pain and leads to a lot of bug corrupting files until you finally have a properly working version.

**Comment by maxaustria** [comment] 2016-08-12 10:51
Another idea to this topic. Why not allow the user to manipulate the default opening behavior per file extension. An example: if I click on pictures I got shown the picture in the internal viewer. Maybe for some reason I don't like it and would love to open it by default with my favorite picture viewer. In the settings could be a map from file extension to opening behavior. That would solve all kind of different usability issues. 

My default use cases would be:
- open PDFs direct in pdf-viewer
- open txt file directly in my favorite editor
- open pictures in my favorite gallery
...

Right now sure there is the same behavior if I use the "open with" function but it's three clicks, every time you open the file. Sometimes I directly open stuff from the file commander but then I need to sync or rename it, back to the client.

**Comment by AndyScherzinger** [comment] 2016-08-12 11:22
Hi @maxaustria,

thanks for your input. To some extend this is already working in the actual version(s)

> open PDFs direct in pdf-viewer
That does already happen, but it opens in the pdf-viewer of your choice defined on the global/Android-OS level

> open txt file directly in my favorite editor
That does also already happen, but it opens in the text-viewer of your choice defined on the global/Android-OS level. Difference to the pdfs is that you need to select the text file and click on the open with icon in the toolbar at the top (rectangle with the top arrow). So yeah that is already mentioned in your last paragraph.

> open pictures in my favorite gallery ...
That is true. For pictures you don't have an option to open it with another app from within the Nc Android app

A general (better) solution is already in place though! We support the document provider so every app that also support this (e.g. the Adobe pdf viewer) is able to access the Nc Android app to open the files. So you don't even have to open the Nc Android app :)

**Comment by maxaustria** [comment] 2016-08-12 12:13
Thanks for the feedback, I did some testing with NC 1.2 client on Android 4.4.4. Here is what I found. (Warning... I have to admit that I have not the best Android knowledge yet, so please don't punish me too hard if I ask wired questions ;))

PDF:
- I set default PDF app
- I try to open PDF in file commander -> opens on click in PDF viewer
- I try to open PDF in next cloud client -> it asks me which PDF viewer I wanna chose, according to you there should be no asking, any idea what I did wrong?

Txt:
- I set my default txt editor (open txt file, choose program and say always open with xyz)
- open from file commander does open txt file directly in editor like expected
- open from NC ignore it and stills displays it like before in not editable internal viewer

Talking about the picture viewer (with a already downloaded jpeg with half mb)
- open speed in own cloud client below 1sec
- open in next cloud client more then 5sec???!!

In general: putting the open in app button in the top bar is great, also the document provider i start using sometimes. You guys keep up the good work :)

**Comment by AndyScherzinger** [comment] 2016-08-12 14:04
@maxaustria  thank you for the details and no worries, there are no weird questions!

PDF: you are right. I missed that details, b/c sometimes Android asks me if I always want tto use this app to open this file type (Android N). Here it doesn't. Needs to be investigated. :+1: 

TXT: same issue imho

As for the responsiveness with images. That is strange indeed. Any idea/experience with this @tobiasKaminsky @nextcloud/android ?

**Comment by tobiasKaminsky** [comment] 2016-08-16 06:58
Please open a new issue and describe it more exactly, e.g. how many files are in the folder, how big is the image, what kind is it, ...

**Comment by AndyScherzinger** [comment] 2016-08-16 07:53
@tobiasKaminsky is your comment regarding this issue?

**Comment by tobiasKaminsky** [comment] 2016-08-16 08:09
I was referring to this
> As for the responsiveness with images. That is strange indeed. Any idea/experience with this @tobiasKaminsky @nextcloud/android ? (tested it myself and Nc was ~1 sec and oC a lot below, Android N Nexus5X).

**Comment by maxaustria** [comment] 2016-08-17 00:19
New issue opened regarding picture open delay, see #219

**Comment by spectas** [comment] 2017-04-23 12:10
Hi everybody!
I would like to describe a bit more in detail, what is imho so difficult right now about editing text files.

How I would like NC app to handle text files:
- I click (one time) on a text file in the NC app. NC opens it directly in my preferred text editor.
- I edit and save the file, then close/leave the editor.
- NC app uploads my changes quietly in the background. No user action needed.
Actually this is how NC web client works, too.

What NC app works today:
- I do a long-press on the text file in the NC app
- I open the options menu (3 dots)
- I choose "open with"
- In the "open with" dialog I choose (every time again) my preferred external text editor
- I edit and save the file, then leave the editor
- in the NC app my text file is still selected, so I choose the options menu (3 dots) again
- I choose "synchronize" and NC uploads my changes.

Imho for a "simple" task like "There is a text file I want to edit quickly", there is a lot of user action needed. And a lot of mistakes a user can do, for example forgetting the final sync step so your changes are lost.

I am not an Android expert, so probably things are much more complicated than they look at first glance. Perhaps this behaviour is linked to a wider syncing problem in NC as described in this thead  #757. But perhaps, as long as the overall syncing problem is not solved, an in-app text editor would be a good solution to make it simpler to edit text files.

**Comment by michaelspunkt** [comment] 2018-03-27 10:10
Hi there,
the first post on this requested feature soon is 2 years old. I would like to ask whether there has been taken some action meanwhile to implement in-app text editing.
I do appreciate your work and can only honour it by spending a beer/coffee/donation but cannot contribute any code.
So, the iOS app is able to manage in-app text editing, maybe there is a possibility to use code snippets from its developer to shorten dev-time.

Thank you once again

[Android Nextcloud App 3.1.0 RC1, Android 7.1.2]

**Comment by jospoortvliet** [comment] 2018-03-27 10:14
I think we should try to make the workflow as described by @spectas easier rather than featuring a built-in text editor. What can we do to improve there?

**Comment by michaelspunkt** [comment] 2018-03-28 12:27
@jospoortvliet, I don't understand the point.
The feature is requested by users and the iOS app has it. What is to be said against this feature?

**Comment by tobiasKaminsky** [comment] 2018-03-29 05:35
We cannot "simply" use iOS code for android as both have different programming languages and the way they handle files, character encoding, etc. is different.

As implementing an in-app editor requires a lot of work, Jos suggested to improve the workflow and use an external text editor. It is simply a tradeoff between feature and men power.

This does not mean that this feature will never come, but priorities are not that high here...

**Comment by michaelspunkt** [comment] 2018-03-29 06:36
Thank you for your cleaning up. I thought there were sorts of SDKs with which it is possible to create an app and port it to different OSs.

What a pity regarding the priority ;) but I can wait.

Thanks a lot!

**Comment by itcrowd72** [comment] 2018-04-11 17:03
I also really want a simple text editor

**Comment by cwmke** [comment] 2018-04-11 18:24
Having to leave the Nextcloud app to make a quick edit to a text file is a tad annoying. It requires the user to have or find a text editing app (not a problem for me but my parents and family members?). 

I understand the logic behind what you're saying @ardevd about the editor on IOS but it is nice to have the same feature set on both devices. Other apps like Dropbox and I'm guessing Google Drive have an in-app text editor implemented on Android as well (they also have billions of dollars to do so 😉).

I'm extremely happy with the app either way but I think adding it would be very handy.

**Comment by tobiasKaminsky** [comment] 2018-04-19 13:29
Currently we/I see the app mostly as a "connector" between cloud and android device, with sharing, search, ...
So the scope of the app is currently to download/provide a file to an app which is capable of using it. The only exception of this is image & media.

The problem is currently men power for adding and maintaining more & more features.
So my focus is now on having trash bin, comments, tags, file versioning in the app.

At some point later it is valid to extend the app with such features.
I hope you understand why this is not our/my main priority.

(of course this feature remains open)

**Comment by guettli** [comment] 2018-05-18 07:48
I am willing to pay for an open source in-app text editor.

**Comment by jospoortvliet** [comment] 2018-08-10 15:13
>Maybe there is not need to re-invent the wheel. AFAIK there are open source text editors for android. Maybe it does not need much development, but integrating existing stuff.

That is done already - you can open any file in another text editor :see_no_evil:  that way you can edit video, word documents, view PDF and so on.

On iOS there is now also an easy way to access files between apps so I even expect the text editor might disappear, it isn't needed anymore.

Anyway, this can of course be done, but I don't think it is smart to make a 2 gb big Nextcloud Files app that can wash your cat... I would instead suggest we automatically recommend an open source text editor if none is installed.

**Comment by guettli** [comment] 2018-09-17 07:27
@schiessle thank you for your comment. I am very happy, that someone understands my "vision".

**Comment by blaster556** [comment] 2019-04-15 14:19
I agree with @schiessle 
I agree with @schiessle , the current situation is absolutely horrid. 
With Dropbox's recent device limit change, I'm quickly searching for a replacement.

Dropbox's Android client has it perfect...I tap on a .txt file, it asks me what editor I want to use, I can make it permanent, then I get dropped into a text editor, make my edits, save and exit. Done.

The Nextcloud app is not user friendly at all.  I trained my kids how to use it very quickly to update share family notes files.  There's no way I could unleash this app on my family.  It's horrid.

I tried looking at the Notes App, but it only allows working with notes in a single directory.  Not very useful if you have many shared folders with note files in different folders.

Please reconsider your priorities.

**Comment by blaster556** [comment] 2019-04-15 17:31
So it appears if you have a file with .odt extension, this works fairly well.  But .odt files don't work on the iOS or web clients.   Would it be a big deal to recognize .txt files the same as .odt files are?  It appears there's an internal editor now, the .txt file type just needs to be recognized.

**Comment by tobiasKaminsky** [comment] 2019-04-16 08:44
odt are opened in collabora, and this is also possible on web / iOS.

Text files can be opened with an external app (like you did with Dropbox) via three dots -> open with

**Comment by ezaquarii** [comment] 2019-04-16 14:52
@tobiasKaminsky I think they would also like to remember the choice for subsequent actions, so they don't have to Open With and select the app each time.

I think this is pretty easy to implement by scanning available mime type handlers and saving it in preferences.

Not sure about UI.

**Comment by tobiasKaminsky** [comment] 2019-04-17 11:55
Right, we can implement this. Best is to open up a new issue for this and ping nextcloud/designer group for design help.
But I assume that this is a standard component of Android.

**Comment by ardevd** [comment] 2019-04-17 11:58
I'm confused. Are we implementing an in-app text editor or not?

**Comment by tobiasKaminsky** [comment] 2019-04-17 12:03
Sorry @ardevd I changed my previous comment, so that it is clear that my answer is about remember "open with".

**Comment by blaster556** [comment] 2019-04-19 13:11
> > @tobiasKaminsky I think they would also like to remember the choice for subsequent actions, so they don't have to Open With and select the app each time.

What about saving data?  That's always been a real pain point as well.  It needs to be made seemless so when you leave the editor, updates are automatically synced back to the server w/o any other additional manual functions required.  It should be seemless like it is with the Dropbox client.

**Comment by blaster556** [comment] 2019-04-19 13:12
> odt are opened in collabora, and this is also possible on web / iOS.

Is Collabora built in?  It appears to be.  Why can't text files just be opened with Collabora, and just saved back as text files.

**Comment by tobiasKaminsky** [comment] 2019-04-29 08:47
> What about saving data? That's always been a real pain point as well. It needs to be made seemless so when you leave the editor, updates are automatically synced back to the server w/o any other additional manual functions required. It should be seemless like it is with the Dropbox client.

We support document storage (an android api) and if the editor also uses this, it should work.

> Is Collabora built in? It appears to be. Why can't text files just be opened with Collabora, and just saved back as text files.

txt files do not seem to be exposed, I'll check this on the richdocuments repository.

**Comment by jakobroehrl** [comment] 2019-05-14 08:14
> We support document storage (an android api) and if the editor also uses this, it should work.
Do you have a example editor for testing this?

> txt files do not seem to be exposed, I'll check this on the richdocuments repository.
I think that would be the best solution. Do you have any news on this?

Thanks!

**Comment by jakobroehrl** [comment] 2019-06-27 08:35
@tobiasKaminsky 

> We support document storage (an android api) and if the editor also uses this, it should work.

Do you have a example editor for testing this?

> txt files do not seem to be exposed, I'll check this on the richdocuments repository.

Do you have any news on this?
Thanks!

**Comment by jakobroehrl** [comment] 2019-07-04 07:02
It's obsolute with https://github.com/nextcloud/text/issues/1 I think.

**Comment by blaster556** [comment] 2019-10-26 05:11
Any update to this?  The current method is rather poor.  Even the IOS app gets this part right.

**Comment by jakobroehrl** [comment] 2019-10-26 05:29
Is planned for nc18, I think.

**Comment by blaster556** [comment] 2020-01-01 03:47
Curious as to why this is a server side issue?  IOS can already do it.

**Comment by AndyScherzinger** [comment] 2020-01-06 19:19
because we want to incorporate the servers editor capabilities while iOS implemented a local/client-side editor. So it is not a server-sice _issue_ but a different choice for the solution to the requirement of having an editor.

**Comment by blaster556** [comment] 2020-01-08 15:20
@AndyScherzinger Sounds like a cool implementation, I can't wait to see it.  However, as both an Android and IOS user, it would be nice to see consistent implementation across all platforms.

**Comment by AndyScherzinger** [comment] 2020-01-08 15:40
@blaster556 totally agree on the consistency argument, while I am not involved with thhe iOS project but maybre @tobiasKaminsky know if this will also be implemented on iOS.

**Comment by tobiasKaminsky** [comment] 2020-01-09 14:24
Android will get with NC18 an online collaborative text editor, same will iOS have.
It uses nextcloud/text app.

For now there are no plans to have an offline/local text editor in Android, as this can be done via other apps.

**Comment by brainchild0** [comment] 2020-06-16 09:54
So currently the behavior for the *edit* feature for a text or Markdown file is to run the Text web application from the server in the client application window, whereas editing locally requires using the *open with* feature? I would suggest the value of a clearer means to represent this difference.  Perhaps *edit online* would be a a good choice over simply *edit*, or *open collaborative editor*.

**Comment by tobiasKaminsky** [comment] 2022-01-14 07:38
- [ ] add editor https://noties.io/Markwon/docs/v4/editor/#getting-started-with-editor
- [ ] Behaviour
  - not downloaded -> open online
  - downloaded -> open read-only (same like online)
  - click on "edit/pencil" -> make it editable

**Comment by stefan-niedermann** [comment] 2022-02-02 07:17
@tobiasKaminsky Notes Android uses [`nextcloud-commons`](https://github.com/stefan-niedermann/nextcloud-commons/) which itself is based upon `Markwon` by `noties.io` with some additional convenience features, for example support for Nextcloud avatars. Let me know if if want to discuss an integration :slightly_smiling_face:.

**Comment by enoch85** [comment] 2023-04-03 11:39
From an Enterprise standpoint I think editing in the Nextloud app should be possible. An even better solution would be to open the document in an editor of your choice then save it back to Nextcloud - especially now with "file_lock" and "Edit locally" in the main GUI. But, I see the issues with that - supporting every text app on Google Play, so better make it in the Nextcloud app itself, using the already installed plugins on the server - Collabora Online, OnlyOffice or whatever.

But what do I know... 🤷‍♂️

**Comment by Discostu36** [comment] 2023-10-04 05:31
I guess this can be closed as completed? I can edit HTML, JS, MD etc. with the app.

**Comment by joshtrichards** [comment] 2023-12-06 15:35
> I guess this can be closed as completed? I can edit HTML, JS, MD etc. with the app.

@Discostu36 Well this issue has sort of morphed (online editor -> off-line editor too). :rofl: The former is done, however, yes.

**Comment by jospoortvliet** [comment] 2023-12-10 08:36
> > I guess this can be closed as completed? I can edit HTML, JS, MD etc. with the app.
> 
> @Discostu36 Well this issue has sort of morphed (online editor -> off-line editor too). 🤣 The former is done, however, yes.

The off-line editor does of course add quite some risks of file conflicts. I would think the Notes app (notes are usually not shared, though they can be since Nc 28/Hub 7) or using a local app is a much better, less risky solution. To me, the prio of this issue is quite low as most use cases are covered with the current Nextcloud Text editor.

**Comment by joshtrichards** [comment] 2024-10-03 20:29
The original intention of this Issue is implemented today via the in-app integration of the direct edit mode of `text`.

For the other scenarios, such as changing *Open with* behavior/etc... those are either covered elsewhere or out of scope for this Issue. So I'm closing as done to avoid confusion. :)

**Closed by joshtrichards** 2024-10-03 20:29 UTC
Labels: enhancement, feature: editor, needs review
