### ISSUE TITLE
Crash when openning after fresh install

### ISSUE THREAD

**Issue by diegorubert** [nextcloud/android#7672] opened 2020-12-16 01:28 UTC
### Steps to reproduce
1. Install
2. Open

### Actual behaviour
- Crash when openning after fresh install.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalArgumentException: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.
	at android.app.ActivityThread.installProvider(ActivityThread.java:6489)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5982)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5888)
	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalArgumentException: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.
	at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(Unknown Source:8)
	at com.google.firebase.iid.FirebaseInstanceId.checkRequiredFirebaseOptions(com.google.firebase:firebase-iid@@20.2.3:52)
	at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@20.2.3:2)
	at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@20.2.3:1)
	at com.google.firebase.iid.Store.checkForRestore(com.google.firebase:firebase-iid@@20.2.3:15)
	at com.google.firebase.iid.Store.<init>(com.google.firebase:firebase-iid@@20.2.3:5)
	at com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase:firebase-iid@@20.2.3:16)
	at com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase:firebase-iid@@20.2.3:8)
	at com.google.firebase.iid.Registrar.lambda$getComponents$0$Registrar(com.google.firebase:firebase-iid@@20.2.3:26)
	at com.google.firebase.iid.Registrar$$Lambda$0.create(Unknown Source:0)
	at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
	at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
	at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(com.google.firebase:firebase-components@@16.0.0:158)
	at com.google.firebase.FirebaseApp.initializeAllApis(com.google.firebase:firebase-common@@19.3.0:563)
	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:304)
	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:268)
	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:253)
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@19.3.0:51)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@19.3.0:45)
	at android.app.ActivityThread.installProvider(ActivityThread.java:6484)
	... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: tissot_sprout
Model: Mi A1
Id: PKQ1.180917.001
Product: tissot

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V10.0.24.0.PDHMIXM

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment] 2020-12-17 11:09
Duplicate of #7616

**Closed by AndyScherzinger** 2020-12-17 11:09 UTC
Labels: bug
