### ISSUE TITLE
nextcloud 3.14.1 no longer works upload via share button

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#7662] opened 2020-12-14 07:22 UTC
I have on two android phones the latest client version nectcloud 3.14.1 but I noticed that it no longer allows uploading files using the share button from other applications.  see file manager and similar.  before it was enough to press the icon of the 3 dots identified as share, choose nextcloud as application, choose the folder and click ok.  and the file was uploaded.  now nothing happens, the upload just doesn't start.  I am forced to open the application first, go to the folder and from the nexcloud application click on the + symbol.  and choose upload file.

**Comment by tigernero79** [comment] 2020-12-14 07:24
I also installed the latest release nextcloud server 20.0.3

**Comment by AndyScherzinger** [comment] 2020-12-14 08:39
Duplicate of #7587

**Closed by AndyScherzinger** 2020-12-14 08:39 UTC
Labels: bug
