### ISSUE TITLE
Home, back and app switch button hidden

### ISSUE THREAD

**Issue by bce000** [nextcloud/android#9004] opened 2021-09-24 15:27 UTC
### Steps to reproduce
1. Open app
2. can not see home, back and app switch button

### Expected behaviour
- Tell us what should happen
- to see home, back and app switch button at the bottom of the screen.

### Actual behaviour
- Tell us what happens
- home, back and app switch button are all hidden but working if I try to touch them in the area.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 7.1.1

Device model: SGP771

Stock or customized system:32.4.A.1.54

Nextcloud app version:3.17.0

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

![bild](https://user-images.githubusercontent.com/24691237/134700700-d20b2cc4-81cd-42c7-96cf-0b1c013da9c6.png)

**Comment by joshtrichards** [comment] 2023-10-10 01:56
Duplicate of #6958

**Closed by joshtrichards** 2023-10-10 01:56 UTC
Labels: bug
