### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by ibnuharisfawaid** [nextcloud/android#7434] opened 2020-11-22 03:58 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2a3b583 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:198)
	at android.app.ActivityThread.main(ActivityThread.java:6729)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Nokia
Device: PLE
Model: TA-1021
Id: PKQ1.181105.001
Product: TA-1021_00WW

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 00WW_6_19F

**Comment by AndyScherzinger** [comment] 2020-11-23 09:07
Duplicate of #6905

**Closed by AndyScherzinger** 2020-11-23 09:07 UTC
Labels: bug
