### ISSUE TITLE
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{dffef0b u0 

### ISSUE THREAD

**Issue by js-d-coder** [nextcloud/android#5088] opened 2020-01-02 15:17 UTC
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{dffef0b u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1743)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6693)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: santoni
Model: Redmi 4
Id: PQ3A.190801.002
Product: aosp_santoni

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 4a80e6dc7b

**Comment by AndyScherzinger** [comment] 2020-01-09 17:28
duplicate of #2010

**Closed by AndyScherzinger** 2020-01-09 17:28 UTC
Labels: bug
