### ISSUE TITLE
Already downloaded file is not updated

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#414] opened 2016-11-30 11:57 UTC
1. In the app, open a text document (or any file), it gets downloaded and you can view it
2. Update it on your computer or server
3. Refresh the file list on Android to get the new state, changed date on the document updates

Expected behavior: The new file is simply shown, especially if there have been no local changes.

What actually happens: The old downloaded file is shown with no indication it’s outdated. Even makes me think there’s a sync error. You need to manually use »Sync«, then it says there’s a conflict (which is not true) and you need to keep the server version. Or you need to delete the local file which is strange too.

cc @AndyScherzinger @tobiasKaminsky is this related to https://github.com/nextcloud/android/issues/285 or https://github.com/nextcloud/android/issues/231 maybe?

PR #1655

**Comment by AndyScherzinger** [comment] 2016-11-30 13:24
Hi Jan,
you could say it is related to #231, but not to #285. Your expected behavior is imho rather the expected result "new/actual file to be shown". Question is how should the client behave in order to accomplish that for different scenarios:
File has been downloaded, user browses to the folder and it...
*  has been changed locally (at some point in time): refresh downloaded files against the server (-> upload)? always/just on wifi? 
* has been changed on the server: redownload file? always/just on wifi?
* has been changed on the server and locally: just display local version?

Thing that needs to needs to be discussed and that is why I also removed the "bug" label even though it is true for the mentioned sync-issue: How should this work in detail, since (everyone loves when this argument is being used): it works as designed. The thing we need to discuss here is "open" (atm this means download once, no update, no nothing) Vs. "make available offline" (which is basically the sync item (which seems to do what you want it to be done).

So we need to discuss how should the client behave for 
* downloaded files (in general and in detail)
* "available offline" (sync, in general and in detail)

So thanks for the trigger and I get the "I just want it to work properly" but unfortunately this seems to be a larger issue/topic where much more needs to be (re-)defined in order to make this work properly and flawlessly :)

Looking forward to the discussion :)

**Comment by tobiasKaminsky** [comment] 2017-06-30 09:04
My opinion is if I download a file I always want to have it in the newest state when entering a folder.
1. download a file
2. file gets changed on server
3. enter folder, containing this file
4. - if file "set to available offlline" -> download it directly
   - for other files: update file on click

Showing the user an out of date file should never happen
@mario @AndyScherzinger @jancborchardt

**Comment by AndyScherzinger** [comment] 2017-06-30 09:47
agreed!

**Comment by jancborchardt** [comment] 2017-06-30 10:47
If possible, I would even say that:

- If file is set to »Available offline« or favorited & downloaded, update it on app start or via background check, regardless if you are in the folder
- If file was downloaded before: Update on entering the folder, as you said.

Because »Update file on click« basically happens for any file not downloaded already, as it gets downloaded the first time, in the current version. Files already downloaded have a higher importance, so should be updated via another mechanism with slightly higher priority. Do you know what I mean?

**Comment by tobiasKaminsky** [comment] 2017-06-30 11:19
> Because »Update file on click« basically happens for any file not downloaded already

I am only talking about files that were downloaded, then modified (either on server or local) and then clicked on them.

**Comment by tobiasKaminsky** [comment] 2017-12-06 14:41
This has a fix in #1655

**Comment by AndyScherzinger** [comment] 2017-12-06 17:58
With #1655 being merged this can imho be closed now

**Closed by AndyScherzinger** 2017-12-06 17:58 UTC
Labels: enhancement, needs info/discussion, pr exists
