### ISSUE TITLE
out of memery

### ISSUE THREAD

**Issue by snafu423** [nextcloud/android#10779] opened 2022-10-05 12:34 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

installed the app on a new phone with lots of existing photos (also on the server)
the app tries to sync with the server but then crashes after some time
looks like it always starts from scratch and does not continue from where it crahses

### Expected behaviour

does not complete the sync to server

### Actual behaviour

crash (see above)

### Android version

13

### Device brand and model

Pixel 6

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.2

### Nextcloud server version

nextcloud hub (does not show version number)

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "Thread-7" java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 730632 free bytes and 713KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
    at sun.security.util.DerValue.encode(DerValue.java:418)
    at sun.security.util.DerValue.toByteArray(DerValue.java:861)
    at sun.security.x509.RDN.<init>(RDN.java:241)
    at sun.security.x509.X500Name.parseDER(X500Name.java:803)
    at sun.security.x509.X500Name.<init>(X500Name.java:317)
    at javax.security.auth.x500.X500Principal.<init>(X500Principal.java:226)
    at com.android.org.conscrypt.OpenSSLX509Certificate.getSubjectX500Principal(OpenSSLX509Certificate.java:502)
    at okhttp3.internal.tls.BasicTrustRootIndex.<init>(BasicTrustRootIndex.kt:28)
    at okhttp3.internal.platform.Platform.buildTrustRootIndex(Platform.kt:163)
    at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.kt:160)
    at okhttp3.internal.platform.Android10Platform.buildCertificateChainCleaner(Android10Platform.kt:82)
    at okhttp3.internal.tls.CertificateChainCleaner$Companion.get(CertificateChainCleaner.kt:42)
    at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:870)
    at com.nextcloud.common.PlainClient$Companion.createDefaultClient(PlainClient.kt:62)
    at com.nextcloud.common.PlainClient$Companion.access$createDefaultClient(PlainClient.kt:47)
    at com.nextcloud.common.PlainClient.<init>(PlainClient.kt:45)
    at com.nextcloud.client.network.ClientFactoryImpl.createPlainClient(ClientFactoryImpl.java:94)
    at com.nextcloud.client.network.ConnectivityServiceImpl.isInternetWalled(ConnectivityServiceImpl.java:79)
    at com.owncloud.android.files.services.FileUploader.retryFailedUploads(FileUploader.java:1093)
    at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:240)
    at com.owncloud.android.utils.FilesSyncHelper$$ExternalSyntheticLambda0.run(Unknown Source:10)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210290`
* Build flavor: `generic`

### Device information
* Brand: `google`
* Device: `oriole`
* Model: `Pixel 6`
* Id: `TP1A.220905.004`
* Product: `oriole`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `8927612`

### Server error logs

```bash
not available
```

### Additional information

see above for error message from app

**Comment by AlvaroBrey** [comment] 2022-10-05 12:40
Duplicate of #10682

**Closed by AlvaroBrey** 2022-10-05 12:40 UTC
Labels: bug
