### ISSUE TITLE
Auto Upload: clarify "unknown error"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1783] opened 2017-11-14 15:22 UTC
Sometimes "unknown error" occurs in upload pane.
This not useful neither for us to debug nor for the user.

**Comment by AndyScherzinger** [comment] 2017-12-12 09:34
This is due to https://github.com/nextcloud/android/blob/master/src/main/java/com/owncloud/android/ui/adapter/ExpandableUploadListAdapter.java#L601 while I can't say for sure when this is set to unknown.

**Comment by joshtrichards** [comment] 2024-10-19 02:48
Duplicate of #260

**Closed by joshtrichards** 2024-10-19 02:48 UTC
Labels: enhancement, feature: auto upload
