### ISSUE TITLE
Newer user can't log in, getting "unknown error occurred"

### ISSUE THREAD

**Issue by souldessin** [nextcloud/android#415] opened 2016-11-30 22:00 UTC
### Actual behaviour
- When logging in a user that was created via the web interface on Nextcloud 10.0.1 I get a response of "unknown error occurred." These users were created on the server at its current version. Other users that can log in, were created on the same system, but with the 9 before the latest version was available.

### Expected behaviour
- The app should log in without issue.
 
### Steps to reproduce
1. Create user on version 10.0.1
2. Add user to nextcloud app
3. App returns "unknown error occurred"

### Environment data
Android version: 6.1

Device model: Samsung Galaxy S6

Stock or customized system: Stock

Nextcloud app version: 1.3.1
Nextcloud server version: 10.0.1

***Edit***
I signed up for beta access through the play store and now have version 1.4.0 RC3 and the issue is resolved. I will leave this ticket open to allow for the team to do as they wish. 

Thank you

**Comment by AndyScherzinger** [comment] 2016-12-01 14:35
hmmmm, let's keep it open for some more days.... 1.4.0 contains a login patch which is needed in order to be able to log into a v11 instance at all but shouldn't make any different for a v10 instance... So let's wait.

**Comment by Eloo** [comment] 2016-12-04 17:26
Currently tested latest beta from F-Droid.
Seems to work with the new version.

**Comment by AndyScherzinger** [comment] 2016-12-04 21:37
Hmm, we did not do any login changes with that beta. Did you do any server side changes?

**Comment by Eloo** [comment] 2016-12-04 23:09
With the android app version 1.3.1 i'm receiving the "unknown error occured" message.
We may should mention that the nextcloud instance seems to be correctly detected after entering the URL but after entering the credentials and trying to connect we receive this error.
Latest beta works fine.

**Comment by AndyScherzinger** [comment] 2016-12-05 09:01
@Eloo Than that is the issue. 1.3.1 Android client version is not compatible with the Server version 11. 1.4.0 is which is available as an release candidate on Google Play (you need to register as a tester on Google play in order to do that https://play.google.com/apps/testing/com.nextcloud.client RC4) or f-droid https://f-droid.org/repository/browse/?fdfilter=Nextcloud&fdid=com.nextcloud.client (RC2). We plan to release the final by mid of this week 7/8.12.

**Comment by Eloo** [comment] 2016-12-05 13:07
@AndyScherzinger Ah okay. So for my case it's all okay.
Thanks for clarification

**Comment by souldessin** [comment] 2016-12-05 22:26
Hello all, thank you to the team for looking into this. I can confirm that I haven't changed any of the server side code aside from adding the Rainloop app. I can also confirm that version 1.4.0 RC4 of the Android client continues to operate properly and log in everyone.

**Comment by AndyScherzinger** [comment] 2016-12-05 22:37
Hi @souldessin, happy to here everything is working again for you too. I'd say we keep this issue open until v11 of the server and 1.4.0 of the Android client are released and see if everything is still working fine for everyone and if so then close the issue.

**Comment by tobiasKaminsky** [comment] 2017-02-11 15:12
It seems to work for all? So closing.
(Feel free to re-open if needed)

**Comment by afrish** [comment] 2017-02-13 20:14
It's not working for me. On the latest 1.4.1. release, Nexus 5, I get error "Unknown error occurred"

**Comment by tobiasKaminsky** [comment] 2017-02-14 06:51
@afrish can you email us an test account to android AT nextcloud DO com ?
Then I will try to login and see what the problem is.

**Comment by afrish** [comment] 2017-02-14 09:40
@tobiasKaminsky I've sent email with details

**Comment by ddanielww** [comment] 2017-03-02 20:09
nightly build fixed this for me

**Comment by daveh86** [comment] 2017-03-16 01:39
Hi All,

I've run into this issue as well. Happy to create a user for you to check.

Steps to reproduce at the same as initial report.

I've tested the 1.4.0, 1.4.2 and nightly (at writing) client. Reproduces for all.

Server is on a Gentoo box, running the latest (11.0.2) but has been upgraded from 7.0 version of OwnCloud.

Let me know if you need anything else.

**Comment by AndyScherzinger** [comment] 2017-03-16 10:09
Hi @daveh86 a test user to check would be really helpful, yes :) You can send my the credentions+url via a PM on the forum (https://help.nextcloud.com) or ping @mario via mario@nextcloud.com

**Comment by tobiasKaminsky** [comment] 2017-04-04 07:29
any updates on this? @mario @daveh86

**Comment by hennow** [comment] 2017-04-09 12:27
I just issued this problem. Changed my phone to a new one (Android 7) and get unknown error when creating the account. Checking the URL say "secure connection established (Sichere Verbindung hergestellt) , adding the credentials, the login fails with unknown error.
The App used to work on my old Phone (Android 6.0.1) but after resetting it i get the same error on that device too. (Nextcloud Appversion 1.4.2)

My Apache Log show:
[09/Apr/2017:14:11:28 +0200] "HEAD /remote.php/webdav/ HTTP/1.1" 200 - "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
1.2.3.4 - henrik@domain.tld [09/Apr/2017:14:11:28 +0200] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 242 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
CentOS 7.2

**Comment by droidmahn** [comment] 2017-04-10 05:39
Getting the same issue Android 7.0.1 App Version 1.4.2

**Comment by hennow** [comment] 2017-04-10 19:41
Update on this one.
My problem seem to be server related... I am in the middle of migrating to another Vserver-Provider, and installed Nextcloud on that server. At least with the local admin account i dont have any issues (on my current server logging in with the local admin doesnt work too).
My Users are authenticated against a LDAP-Server on my current server. 
Looking in the Nextcloud Logs i can see some issue with MariaDB Syntax. Might have come with an Mariaupdate at some point!?
i dont know though,  if the login error is related to that SQL-error.
[error.txt](https://github.com/nextcloud/android/files/911261/error.txt)

**Comment by tobiasKaminsky** [comment] 2017-06-22 08:24
@daveh86 @droidmahn can you email us a test account to android at nextcloud dot com with reference to this issue?

**Comment by tobiasKaminsky** [comment] 2017-07-25 13:59
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.

**Closed by tobiasKaminsky** 2017-07-25 13:59 UTC
Labels: bug, needs info

**Comment by fransschreuder** [comment] 2018-09-09 12:10
I am having this issue today again. Galaxy S5. Version is 2.2.0, from January. It only stopped working 2 weeks ago after I changed my password
