### ISSUE TITLE
Nextcloud Android App 2.0.0RC4 no image preview at automatic upload

### ISSUE THREAD

**Issue by 90er** [nextcloud/android#1409] opened 2017-08-22 17:32 UTC
### Actual behaviour
When i'm using the Nextcloud Android App 2.0.0RC4, there is no image preview when switching to automatic upload in the menu. When i'm using the Nextcloud dev Android  App 20170727, the image preview is working correctly.

### Expected behaviour
Image preview should work :-)
 
### Steps to reproduce
1. Start Nextcloud Android App
2. Open Nav Drawer
3. Click on Automatic Upload

### Environment data
Android version: 7.0
Device model: Moto G5 Plus
Stock or customized system: Stock
Nextcloud app version: 2.0.0RC4
Nextcloud server version: 12.0.2

**Comment by AndyScherzinger** [comment] 2017-08-25 14:22
@90er is this still the case for you (also with dev version not being on the device)? Just asking because I tried to reproduce it on my phone and it works nicely (just had that issue with RC3).

**Comment by 90er** [comment] 2017-08-25 16:06
@AndyScherzinger i removed Nextcloud Dev Version (with data) -> Same issue using Nextcloud 2.0.0 RC4 only. After uninstall and reinstall Nextcloud 2.0.0 RC4 (with data) using Google Play Store, its working. It seems to be and issue using stable + dev version?! (both using Google Play Store).

**Comment by AndyScherzinger** [comment] 2017-08-25 17:27
@90er it shouldn't be and might be related to doing a complete re-installation (hard to tell afterwards). The dev version is only available via f-droid though.

**Comment by AndyScherzinger** [comment] 2017-08-25 17:27
I'd close it for now. Please re-open if it happens again.

**Closed by AndyScherzinger** 2017-08-25 17:27 UTC
