### ISSUE TITLE
Wtf

### ISSUE THREAD

**Issue by DannyKr89** [nextcloud/android#13764] opened 2024-10-10 18:31 UTC
### Cause of error
```java
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property currentAccount has not been initialized
    at com.nextcloud.client.mixins.SessionMixin.getCurrentAccount(SessionMixin.kt:32)
    at com.nextcloud.client.mixins.SessionMixin.onRestart(SessionMixin.kt:100)
    at com.nextcloud.client.mixins.MixinRegistry.onRestart(MixinRegistry.kt:48)
    at com.owncloud.android.ui.activity.BaseActivity.onRestart(BaseActivity.java:118)
    at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1603)
    at android.app.Activity.performRestart(Activity.java:9009)
    at android.app.ActivityThread.performRestartActivity(ActivityThread.java:5701)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:260)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:197)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:145)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2628)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:222)
    at android.os.Looper.loop(Looper.java:314)
    at android.app.ActivityThread.main(ActivityThread.java:8661)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `Xiaomi`
* Device: `aristotle`
* Model: `2306EPN60G`
* Id: `UP1A.230905.011`
* Product: `aristotle_ru`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `V816.0.6.0.UMFRUXM`

**Comment by joshtrichards** [comment] 2024-10-10 20:44
Duplicate of #13241

**Closed by joshtrichards** 2024-10-10 20:44 UTC
