### ISSUE TITLE
Nextcloud App: Server unavailable

### ISSUE THREAD

**Issue by JamalNewtron** [nextcloud/android#9366] opened 2021-11-26 07:49 UTC
### Steps to reproduce
1. update to 3.18.0
2. 
3. 

### Expected behaviour
- Nextcloud App should should build up normal connection to server.

### Actual behaviour
- Nextcloud app tells that the server in unavailable

### Can you reproduce this problem on https://try.nextcloud.com?
not tested

### Environment data
Android version: 12

Device model: Pixel 4

Stock or customized system: -

Nextcloud app version: 3.18.0

Nextcloud server version: 22.2.3

Reverse proxy: -

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment] 2021-11-26 08:03
Hi @JamalNewtron, do you happen to have whitespace in your username? If so, this is a duplicate of #9331 , which has a fix in the upcoming 3.18.1 release.

**Comment by JamalNewtron** [comment] 2021-11-26 08:08
Hello @AlvaroBrey : Thank you for your respond. Yes I have a white space in the username. I will waite for 3.18.1

**Comment by Wikinaut** [comment] 2021-11-26 09:35
@AlvaroBrey  Do you have an idea or plan, when 3.18.1 will become available?

**Comment by AlvaroBrey** [comment] 2021-11-26 09:43
> @AlvaroBrey Do you have an idea or plan, when 3.18.1 will become available?
RC1 is planned for next week, and then final release whenever we feel the RCs are ironed out enough (typically up to 2 weeks). However this is just a plan, and dates may move depending on various circumstances.

**Comment by AlvaroBrey** [comment] 2021-11-26 09:43
Duplicate of #9331

**Closed by AlvaroBrey** 2021-11-26 09:43 UTC
Labels: bug, needs info/discussion
