### ISSUE TITLE
Missing pictures

### ISSUE THREAD

**Issue by tom64100** [nextcloud/android#4601] opened 2019-10-02 14:57 UTC
Excellent application, However I notice a concern, some photos do not appear in the mobile application while they are present via the Web browser. These are photos that are sent automatically via the mobile application.

**Comment by ne20002** [comment] 2019-10-03 09:25
#4477

**Comment by ne20002** [comment] 2019-10-03 09:26
I can confirm this for 3.8.0. For me it's only photos uploaded with iOS-App affected.

**Comment by AndyScherzinger** [comment] 2019-10-07 19:58
@tobiasKaminsky @nextcloud/server-triage any idea why this could happen and how?

**Comment by tobiasKaminsky** [comment] 2019-10-08 07:25
> Those are the same issue:
> #4502

This indeed seems to be the same.


> #4477

This is about uploading files, so it is something different.

**Comment by tobiasKaminsky** [comment] 2019-10-08 07:26
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by AndyScherzinger** [comment] 2019-10-14 13:04
@tom64100 @ne20002 is this issue still present for you with v3.8.1 of the app?

**Comment by thomas64600** [comment] 2019-10-14 16:37
@andyscherzinger 
Hello, update 3.8.1 corrected the problem, the photos appear well. thank you very much.

**Comment by AndyScherzinger** [comment] 2019-10-14 17:01
Thanks for the feedback @thomas64600, highly appreciated and happy to hear the matter has been resolved in your case 🎉

**Closed** 2019-10-14 17:01 UTC
Labels: bug, needs info/discussion
