### ISSUE TITLE
[3.2.0RC1] Back from settings

### ISSUE THREAD

**Issue by marvicz** [nextcloud/android#2642] opened 2018-05-29 20:49 UTC
### Actual behaviour
- the arrow back in the settings panel dosn't get you back to the App menu

### Expected behaviour
- Tell us what should happen

### Environment data
Android version: 7

Device model: Galaxy S6

Stock or customized system: Stock

Nextcloud Android app version: 3.2.0RC1

Nextcloud server version: 13

**Comment by AndyScherzinger** [comment] 2018-05-29 20:56
Thanks for the report @marvicz - Can you check if the Android back button works?

@tobiasKaminsky this also got reported on the IRC channel. Only guess at the moment is that this might be related to the introduced singleTop launch flag for the share user search. It does work fine on my Android 8.0 device.

**Comment by marvicz** [comment] 2018-05-29 20:58
Yes, the Android button works well.

**Comment by tobiasKaminsky** [comment] 2018-05-30 06:08
I cannot reproduce this on rc1 with an emulator / android 8:
- open up app
- open settings
- press arrow left
and then I am in file list view of current account.

However on android 6 with a Samsung S5 I can reproduce it.

**Comment by tobiasKaminsky** [comment] 2018-05-30 12:58
Fixed for 3.2 with #2655

**Comment by AndyScherzinger** [comment] 2018-05-30 21:53
Closing since the fix is shipping with RC2.
@marvicz please reopen if you still have the issue with 3.2.0RC2

**Closed by AndyScherzinger** 2018-05-30 21:53 UTC
Labels: approved, bug, pr exists, release candidate
