### ISSUE TITLE
Option to activate/deactivate debug-logging

### ISSUE THREAD

**Issue by c0fe** [nextcloud/android#247] opened 2016-09-07 21:48 UTC
I would like to propose a feature, Debug Mode. This would allow me to set an email to use (ex. gmail or outlook) which would allow users to have automatic logs sent via email whenever an exception occurs.

Meaning, the Android App encounters an error and it sends automatically an email with the information of this error. I have had some issue saying "error while waiting on server" but beyond that no information and nothing in the server logs.

**Comment by AndyScherzinger** [comment] 2016-09-08 08:13
Hi @c0fe for a quick win, here is a slightly different idea which would still cover your feature request to some extend.

The app has logging implemented but that is deactivated in the stable releases. We could add an option in the settings to activate it to be able to support the bug hunting. So whenever some error occurs the user can simply go to the settings, activate the logging, reproduce the error and open the log. The log screen as of now has to options "delete" and "send", send will simply ask you how to do that offering you different available apps like GMail, Nextcloud and any other kind of app that can handle text. This way you would still have to type in the mail address, true. But depending on what you want to do it might even be enough to just look at the log since it might give you the information you need.

Not sure if this meets your requirements since if I understand you correctly you said you can set an email address for the user(s) so you would like to do that on the server side and the client (Android in this case) would pick this up and sends out mails. This has some downsides from my point of view, it would need a configured mail account on the phone/tablet to be able to send the mails, if it does it silently in the background it feels kind of shady, you would get any kind of error even the one which would be bugs to be fixed in the client implementation itself, the app's user doesn't have the choice to do so or not. Just some thought though and happy to discuss. Giving anyone the ability to activate logging on the client, having access to it and send it to any kind of text processing app would be very easy to activate.

For performance reasons the app might then require a restart so debug mode as flag can be cashed.

Any thoughts on my input @c0fe @nextcloud/android @nextcloud/designers ?

**Comment by strugee** [comment] 2016-09-08 18:24
@AndyScherzinger LGTM. IIUC the original proposal was that the email address would be configured in the app settings, not the server - which doesn't feel shady to me. But your proposal seems more useful (I for example would prefer to upload a stack trace to my cloud, not my email).

**Comment by AndyScherzinger** [comment] 2016-09-08 18:31
Upload to your nextcloud account would work out of the box :D
Configuring it in nextcloud client wouldn't be shady, true.

**Comment by LukasReschke** [comment] 2016-09-08 20:33
If that gets done one should also make sure that data is logged-in a private data storage and not simply on the external storage. Otherwise potential sensitive log data could be leaked to third-party apps 🙈

**Comment by c0fe** [comment] 2016-09-09 00:55
I am not that big of a fan of reproducing because I have come across generic exceptions but when I went to do that again it worked. Perhaps adding an option to inform developers of any occurring exceptions might be useful like Firefox does it. Additionally I propose the email option because if there is an issue with the app communicating with the server trying to send bug logs to it seems to be more self defeating.

I have other users (i.e. customers) who use my server (or particular directories), with that being said having the debug mode on server end for me would feel like a privacy violation.

**Closed** 2017-10-15 20:26 UTC
Labels: enhancement, needs info/discussion
