### ISSUE TITLE
Mobile app long file or directory names display issue

### ISSUE THREAD

**Issue by korosteleff** [nextcloud/android#11506] opened 2023-04-05 14:39 UTC
When working with a many count of files in the mobile client, there is a problem with displaying long file / folder names. Need an option for reduce font size and enable word wrapping or text scrolling.

**Comment by joshtrichards** [comment] 2023-10-15 23:34
Duplicate of #2305 

Let's centralize discussion/tracking there

**Closed by joshtrichards** 2023-10-15 23:34 UTC
Labels: enhancement, design
