### ISSUE TITLE
"No files in here..." request for clarity.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#623] opened 2017-02-04 20:44 UTC
### Actual behaviour
-Tell us what happens
When entering a folder which has not been synced yet, the following message will first pop-up:
"No files in here..."
However as soon as the request to the server is underway, the "Loading" animation will appear.

Upon completion of the request, the display will be either ""No files in here..." in the event there really is no files, or the content of the folder will be populated with files.

I would like to have this behavior changed slightly so as not to show "No files in here..." in the first instance when the folder has not been scanned yet and the status is simply unknown.
This doesn't makes much sense to me and in certain cases, makes me wonder what could have happened to files that normally would reside there.

### Expected behaviour
-Tell us what should happen
1: The first message that should ever appear while scanning for the content of a folder should be something like: "Retrieving folder content..."

2: Only when the request has been finalized, should we display either "No files in here..." or populate the list of files in the folder.
 
### Steps to reproduce
1. Go into folders which are not yet scanned.
2. 
3. 

### Environment data
Android version:
6.0

Device model: 
LG G3

Stock or customized system:
Stock

Nextcloud app version:
1.4.1 and Beta 20170204

Nextcloud server version:
NC 11.0.1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by tobiasKaminsky** [comment] 2017-02-05 08:57
I think this is a great idea

@jancborchardt further improvements?

**Comment by jancborchardt** [comment] 2017-02-13 16:19
For sure agree with @OlivierS1.

»No files in here« should _only ever_ show when there are 100% positively absolutely no files at all in the folder. Otherwise it seems like files are gone. So the loader should be shown. :)

**Comment by jancborchardt** [comment] 2017-02-13 16:20
Also tagging as bug because it’s a glitch and seems like an error in the UX.

**Comment by tobiasKaminsky** [comment] 2017-02-13 16:30
Labels "1." to "4." are only for PRs.
for issues we have approved, which has to be confirmed by 2 devs if it as a feature or by 1 dev if it is a bug.

**Comment by jancborchardt** [comment] 2017-02-14 13:30
Ah ok. I assumed "to develop" is basically "approved" since by definition if a PR exists it is "2. Developing". ;)

**Comment by ShaunCurrier** [comment] 2017-05-31 05:21
+1 Came here to create an issue like this.

**Comment by jancborchardt** [comment] 2017-06-02 12:39
@AndyScherzinger @tobiasKaminsky @mario any news here? This is still very disconcerting and confusing for a split second every time you open a folder where you _know_ files are in there and you think they are gone. ;)

**Comment by mario** [comment] 2017-06-02 12:45
This is fixed in master.

**Closed by mario** 2017-06-02 12:45 UTC
Labels: bug, design, medium

**Comment by jancborchardt** [comment] 2017-06-03 22:49
Thanks a lot! :)
