### ISSUE TITLE
Instant upload doesnʼt work since last update (6 May)

### ISSUE THREAD

**Issue by gergelypolonkai** [nextcloud/android#10346] opened 2022-06-06 17:49 UTC
### Steps to reproduce
Instant upload is enabled for Camera folder; created photos.

### Expected behaviour
Photos should sync immediately (or when i connect to WiFi, depending on settings).

### Actual behaviour
Photos didnʼt sync immediately, and not even later. Doesnʼt even start on charger, connected to WiFi. New photos not listed in the Uploads section.

### Can you reproduce this problem on https://try.nextcloud.com?
Sorry, but i wonʼt upload my personal photos to any server but mine.

### Environment data
Android version: 10

Device model: Huawei P20 Prq1o

Stock or customized system: Stock

Nextcloud app version: 3.20.1

Nextcloud server version: 24.0.1

Reverse proxy: nginx

**Comment by AlvaroBrey** [comment] 2022-06-07 06:46
Duplicate of #10200

**Closed by AlvaroBrey** 2022-06-07 06:46 UTC
Labels: bug
