### ISSUE TITLE
Autoupload / only in specific wlans

### ISSUE THREAD

**Issue by criwe** [nextcloud/android#5424] opened 2020-02-07 15:47 UTC
### Describe the solution you'd like
At the moment it is possible to restrict auto upload to free wlans (on/off).

It would be great to select one or more specific wlans where auto upload sould happen or as an alternative select some wlans where auto upload should not happen.

For example: allow auto upload at my home-wlan, but not via the wlan at work.

Thanks!
Best

**Comment by CardSnap** [comment] 2020-02-24 22:22
I think this would be a good idea.

**Comment by joshtrichards** [comment] 2023-12-22 22:39
Duplicate of #3671

**Closed by joshtrichards** 2023-12-22 22:39 UTC
Labels: enhancement, feature: auto upload, feature: data usage
