### ISSUE TITLE
They told me to file a big report... Don't know what happened.

### ISSUE THREAD

**Issue by hukipola** [nextcloud/android#8161] opened 2021-03-11 15:15 UTC
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Attempt to read from field 'androidx.viewpager.widget.ViewPager com.owncloud.android.databinding.FileDetailsFragmentBinding.pager' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.lang.NullPointerException: Attempt to read from field 'androidx.viewpager.widget.ViewPager com.owncloud.android.databinding.FileDetailsFragmentBinding.pager' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailFragment.getFileDetailSharingFragment(FileDetailFragment.java:156)
	at com.owncloud.android.ui.activity.FileActivity.getShareFileFragment(FileActivity.java:854)
	at com.owncloud.android.ui.activity.FileActivity.getFile(FileActivity.java:296)
	at com.owncloud.android.ui.activity.FileDisplayActivity.updateActionBarTitleAndHomeButton(FileDisplayActivity.java:1623)
	at com.owncloud.android.ui.activity.ToolbarActivity.setupToolbar(ToolbarActivity.java:100)
	at com.owncloud.android.ui.activity.ToolbarActivity.setupHomeSearchToolbarWithSortAndListButtons(ToolbarActivity.java:124)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onCreate(FileDisplayActivity.java:262)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150152
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Fairphone
Device: FP3
Model: FP3
Id: QQ3A.200805.001
Product: FP3

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: eng.root.20210126.003258

**Comment by hlovdal** [comment] 2021-03-14 14:16
This seems to be a duplicate of #8160, only that this is version 30150152 and that version is 30150190.

There is a slight difference near the top of the stack trace,

>at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
>at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)

vs

> at android.app.ActivityThread.-wrap11(Unknown Source:0)

but I assume that is just due to different versions.

**Comment by tobiasKaminsky** [comment] 2021-03-15 08:09
Let us track it in #8160

**Closed by tobiasKaminsky** 2021-03-15 08:09 UTC
