### ISSUE TITLE
Audio Player: play second track after playing the first track

### ISSUE THREAD

**Issue by guettli** [nextcloud/android#4016] opened 2019-05-13 17:27 UTC
### Is your feature request related to a problem?

I select the first (audio) file in a directory. The audio player of nextcloud plays it fine - I am happy.

But then it stops. It does not do the obvious thing. Why not play the second track after the first one has finished?

### Describe the solution you'd like

See above

### Describe alternatives you've considered

AFAIK there is no alternative.

**Comment by guettli** [comment] 2019-05-25 04:38
Hello, is there anybody out there who is missing this basic feature, too? I think it is very obvious that you don't want music playback to stop after playing one track. But maybe I am missing something....

**Comment by memen45** [comment] 2019-05-30 11:51
From the point of view of the nextcloud app playing an audio file is no different from opening a pdf file or any other file. It just shows you the file you selected.

I agree that having integrated music player functionality would be nice though!

Alternatives that you can use are:
1. install the music player app in the nextcloud server. This enables you to have a music player in the browser streaming your music files.
2. install an app like FolderSync, set up a folderpair from the remote folder that contains all your music to a local folder and start syncing. Drawback is of course that it requires downloading all of your music, but after that you can use any android music player you like.
3. there may be music players that support webdav, although often as a (partially) paid feature (I did not find any free ones, supporting both streaming and caching for offline playback while providing a decent looking interface, so if you find one please let me know)

The second solution is what I use now for a while and it works perfectly. Only thing I do miss is syncing playlists between devices (android and windows and webapp ideally)...

**Comment by guettli** [comment] 2019-06-01 17:51
Yes, solution2 (FolderSync) is what I use, too.

But nevertheless: Playing the next sound file after the first would be a nice feature.

**Comment by joshtrichards** [comment] 2023-10-16 19:36
Duplicate of #1038

Let's consolidate discussing and tracking of this enhancement there.

**Closed by joshtrichards** 2023-10-16 19:36 UTC
Labels: enhancement, feature: media player
