### ISSUE TITLE
java.lang.RuntimeException: Unable to pause activity 

### ISSUE THREAD

**Issue by JonasTaulienSolutions** [nextcloud/android#8930] opened 2021-09-02 10:07 UTC
Steps:
* Open newly installed App
* Click "Eigenen Server betreiben". Browser opens
* Go back to App. Following Error Message appears
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to pause activity {com.nextcloud.client/com.nextcloud.client.onboarding.FirstRunActivity}: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@cb9d703
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4612)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4563)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4512)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:228)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@cb9d703
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1433)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1554)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:674)
	at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.onInactive(UsbConnectionDispatcher.java:131)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.ensureStateInactive(SecurityKeyManager.java:316)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.refreshActiveState(SecurityKeyManager.java:290)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.onActivityPaused(SecurityKeyManager.java:333)
	at android.app.Application.dispatchActivityPaused(Application.java:491)
	at android.app.Activity.dispatchActivityPaused(Activity.java:1332)
	at android.app.Activity.onPause(Activity.java:2272)
	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:388)
	at com.owncloud.android.ui.activity.BaseActivity.onPause(BaseActivity.java:84)
	at android.app.Activity.performPause(Activity.java:8096)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1507)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4602)
	... 13 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: dandelion
Model: M2006C3LG
Id: QP1A.190711.020
Product: dandelion_eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.13.0.QCDEUXM
```

**Comment by AlvaroBrey** [comment] 2021-09-02 13:29
Duplicate of https://github.com/nextcloud/android/issues/8585

**Closed by AlvaroBrey** 2021-09-02 13:29 UTC
Labels: bug
