### ISSUE TITLE
Switch from view to edit mode not possible

### ISSUE THREAD

**Issue by cismypa** [nextcloud/android#5763] opened 2020-03-29 06:35 UTC
Presumably with the recent update, for text files the menu item 'edit' from within view mode does nothing anymore.

Also the default action when touching a text file in the file browser seemed to have changed from edit to view?!

**Comment by tobiasKaminsky** [comment] 2020-03-30 04:55
What type of text file is this? md or plain txt?


> Also the default action when touching a text file in the file browser seemed to have changed from edit to view?!

What changed and how changed it?

What do you have installed on server?
- Collabora
- OnlyOffice / Documentserver
- Text

**Comment by cismypa** [comment] 2020-03-30 05:25
It happens to both md and plain txt.
When touching such a file I got directly to edit mode in the past. Now it is a view only mode. I need to select edit from the popup/context menu instead.

On the server just "Text" is installed, no Collabora, no OnlyOffice, no Documentserver.

**Comment by tobiasKaminsky** [comment] 2020-03-30 05:47
Is this a download md/txt file?

**Comment by cismypa** [comment] 2020-03-30 08:42
That's the difference! Thanks! Non-downloaded files obviously have the familiar behavior. Ok, so I don't know whether this is still considered a bug. Though I won't use downloading ever again...

**Comment by tobiasKaminsky** [comment] 2020-03-30 14:44
Duplicate of #5335

**Closed by tobiasKaminsky** 2020-03-30 14:44 UTC
Labels: bug, needs info/discussion
