### ISSUE TITLE
nextcloud client crash when accessing a folder where some content have been deleted

### ISSUE THREAD

**Issue by iXo** [nextcloud/android#7108] opened 2020-10-19 03:02 UTC
### Steps to reproduce
1. Open a folder in the client so that it 'know' what is inside
2. Delete content from somewhere else
3. Open again the client and go to the folder, app crash

```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 1091, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:511)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:299)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:319)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:465)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1578)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:435)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:490)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:372)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:231)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gts28wifi
Model: SM-T710
Id: OPM7.181205.001
Product: gts28wifi

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 306907df37

```

**Comment by tobiasKaminsky** [comment] 2020-10-19 07:14
Duplicate of #6688

**Closed by tobiasKaminsky** 2020-10-19 07:14 UTC
Labels: bug
