### ISSUE TITLE
Confusing UI when playing a video file / audio file

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#7323] opened 2020-11-15 07:42 UTC
### Steps to reproduce
1. Open a downloaded video file
2. it appears **without** a progress bar (only seek and pause buttons are visible)
3. the progress bar appears only **after** the video is clicked again (after a quick refresh of the page)

### Expected behaviour
- the progress bar appears immediately when a video starts playing 

Android Naxtcloud app v. 3.13.1.

**Comment by aqaqsubin** [comment] 2020-11-16 01:37
I think the seek bar is hidden under the Soft Key.
Have you tried hiding Soft keys(Navigation Bar)??

![image](https://user-images.githubusercontent.com/28510311/99203992-9418f100-27f7-11eb-922b-fce61c62e693.png)

**Comment by tobiasKaminsky** [comment] 2020-11-16 06:46
Can you post some screenshots?
I think this is related to soft buttons of Android that cover/reduce actual display size and thus it overlaps.

**Comment by Kuuuna98** [comment] 2020-11-16 08:33
I checked the same error.

Android Naxtcloud app v. 3.13.1.
Device : Samsung Galaxy S7

Open a video file:
![Screenshot_20201116-171545_Nextcloud](https://user-images.githubusercontent.com/26339069/99229755-c2b3bd80-2831-11eb-8645-0e3053734266.jpg)


after a refresh:
![Screenshot_20201116-171616_Nextcloud](https://user-images.githubusercontent.com/26339069/99229631-9e57e100-2831-11eb-8c73-c9f8d68b0418.jpg)

**Comment by aqaqsubin** [comment] 2020-11-16 08:49
> I think this is related to soft buttons of Android that cover/reduce actual display size and thus it overlaps.

I changed the navigation bar option so that the soft keys disappear. 
However, when the video is streamed, the look bar is not visible.

![image](https://user-images.githubusercontent.com/28510311/99231473-01e30e00-2834-11eb-82bc-eddc1f083dd5.png)

**Comment by elpraga** [comment] 2020-11-16 21:14
I'm using navigation gestures. The issue is present as described originally.

**Comment by tobiasKaminsky** [comment] 2020-11-17 10:22
So this is due to our new scrolling toolbar feature.

There is an APK file in this PR #7339, which you can install in parallel to your existing Nextcloud app.
It would be great if you can verify the fix.

**Comment by Kuuuna98** [comment] 2020-11-17 10:41
Android: 8
Device: Samsung Galaxy S7

I downloaded and tested the APK file.
Both mp3 and mp4 files have a good view of the progress bar on the initial screen.👍🏻

**Comment by aqaqsubin** [comment] 2020-11-17 12:38
@tobiasKaminsky 
In my environment, the address bar and the plus button can overlap.
Tell me if this doesn't matter.

https://drive.google.com/file/d/1aqnbznihsg19bjQMMgtgoo1CTfq7iEjl/view?usp=sharing

**Comment by Kuuuna98** [comment] 2020-11-17 12:44
@aqaqsubin
Perhaps the problem is being discussed here(PROBLEM 2) https://github.com/nextcloud/android/issues/6782 .

**Comment by AndyScherzinger** [comment] 2020-11-17 15:29
> In my environment, the seek bar and the plus button can overlap.

It does matter but is unrelated to the mentioned issue here: The FAB (the + button) shouldn't be visible. @aqaqsubin which version are you testing on? This is afaik fixed with 3.14.0RC*

**Comment by aqaqsubin** [comment] 2020-11-18 00:56
@AndyScherzinger 
I tested on Nextcloud QA version 7339, And I also checked on Nextcloud 3.14.0 RC2
The problem of #6782 seems to have been solved and merged, but this problem continues to appear in my environment.
I will report this to #6782.

**Comment by tobiasKaminsky** [comment] 2020-11-18 07:13
Thanks for testing!

**Comment by elpraga** [comment] 2020-11-18 08:18
I've tested the QA version from https://github.com/nextcloud/android/pull/7339 and it works flawlessly (behaves as I'd expect it to) for both audio and video files on my Redmi Note 7 with Android 10 (MIUI 12) and gesture navigation (no soft keys).

Thank you for the quick fix @tobiasKaminsky !

P.S.
It also fixes dinner other playback issues that I do not need to report now :)

**Closed** 2020-11-18 16:27 UTC
Labels: approved, bug, pr exists
