### ISSUE TITLE
I get this error when uploading/moving more files

### ISSUE THREAD

**Issue by EULUSER** [nextcloud/android#13883] opened 2024-10-26 08:19 UTC
### Cause of error
```java
Exception in thread "Operations thread" java.lang.NullPointerException: Attempt to read from field 'java.util.concurrent.ConcurrentMap com.owncloud.android.services.OperationsService$OperationsServiceBinder.mBoundListeners' on a null object reference in method 'java.util.concurrent.ConcurrentMap com.owncloud.android.services.OperationsService$OperationsServiceBinder.-$$Nest$fgetmBoundListeners(com.owncloud.android.services.OperationsService$OperationsServiceBinder)'
    at com.owncloud.android.services.OperationsService$OperationsServiceBinder.-$$Nest$fgetmBoundListeners(Unknown Source:0)
    at com.owncloud.android.services.OperationsService.dispatchResultToOperationListeners(OperationsService.java:781)
    at com.owncloud.android.services.OperationsService$ServiceHandler.nextOperation(OperationsService.java:469)
    at com.owncloud.android.services.OperationsService$ServiceHandler.handleMessage(OperationsService.java:399)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.os.HandlerThread.run(HandlerThread.java:67)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a33x`
* Model: `SM-A336B`
* Id: `UP1A.231005.007`
* Product: `a33xnseea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `A336BXXS8DXA1`

**Comment by joshtrichards** [comment] 2024-10-26 17:32
Duplicate of #13341

**Closed by joshtrichards** 2024-10-26 17:32 UTC
