### ISSUE TITLE
Crash on the opening

### ISSUE THREAD

**Issue by philou69** [nextcloud/android#6171] opened 2020-05-28 10:54 UTC
### Steps to reproduce
1. Open the app

### Expected behaviour
- the app should open

### Actual behaviour
- The app crash with the message below.
The message pop multiple times.

```
**** CAUSE OF ERROR ****

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:355)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.SecurityException: Caller no longer running, last stopped +2s356ms because: timed out while starting
	at android.os.Parcel.createException(Parcel.java:1953)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:195)
	at android.app.job.JobParameters.dequeueWork(JobParameters.java:243)
	at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
	at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$2.call(AsyncTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobServiceContext.assertCallerLocked(JobServiceContext.java:490)
	at com.android.server.job.JobServiceContext.doDequeueWork(JobServiceContext.java:368)
	at com.android.server.job.JobServiceContext$JobCallback.dequeueWork(JobServiceContext.java:161)
	at android.app.job.IJobCallback$Stub.onTransact(IJobCallback.java:83)
	at android.os.Binder.execTransact(Binder.java:739)


**** APP INFORMATION ****
ID: com.nextcloud.client
Version: 30110190
Build flavor: gplay

**** DEVICE INFORMATION ****
Brand: HONOR
Device: HWSTF
Model: STF-L09
Id: HUAWEISTF-L09
Product: STF-L09

**** FIRMWARE ****
SDK: 28
Release: 9
Incremental: 210C432
```

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 9

Device model:  HONOR STF-L09

Stock or customized system: 

Nextcloud app version: 3.11.1

Nextcloud server version: 18.0.4

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Neamar** [comment] 2020-05-28 11:04
I manage the webserver for this device, here is the associated web log:

```
"GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 1331 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.1"
```

And nothing else.

**Comment by tobiasKaminsky** [comment] 2020-05-28 11:15
Duplicate of #5805

**Closed** 2020-05-28 11:15 UTC
Labels: bug
