### ISSUE TITLE
Auto-Upload Feature for pictures should bring delete on device as well

### ISSUE THREAD

**Issue by ediordna** [nextcloud/android#8899] opened 2021-08-25 20:17 UTC
### Is your feature request related to a problem? Please describe.
I try to replace Google Photos with Nextcloud as some kind of gallery app. I often take some pictures and sort them out later, so I delete some of them. Before I did the deletion in Google photos, now I want to do it in Nextcloud. But it doesn't delete the local stored pictures, only the one uploaded to Nextcloud. 

### Describe the solution you'd like
Implement a function to delete pictures locally and in Nextcloud with one tip.

**Comment by joshtrichards** [comment] 2023-12-20 15:49
Duplicate of #6617

I encourage you to add to the discussion there, subscribe to it, and/or upvote :+1: it.

**Closed by joshtrichards** 2023-12-20 15:49 UTC
Labels: enhancement, feature: auto upload
