### ISSUE TITLE
Share button does not have any effects

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#8063] opened 2021-02-25 20:44 UTC
nextcloud 3.15 when you click on the three dots for sharing on a file it no longer allows you to choose anything or an expiration or a password, when you click on the share and not link button, on a file it does not produce any option or effect.  otherwise if you do it with a folder.

![Screenshot_20210225-213901~2](https://user-images.githubusercontent.com/35575744/109214880-a7ead080-77b2-11eb-84de-52d04a6077c6.png)

**Comment by AndyScherzinger** [comment] 2021-02-25 20:52
This should be fixed with 3.15.1 RC1, available in beta program on gplay.
Can you test this? Else the stable 3.15.1. will be released next week.

Duplicate of #8052

**Comment by AndyScherzinger** [comment] 2021-02-25 20:52
Duplicate of #8052

**Closed by AndyScherzinger** 2021-02-25 20:52 UTC
Labels: bug
