### ISSUE TITLE
GPlay: android.os.FileUriExposedException - com.owncloud.android.ui.activity.UploadListActivity.openFileWithDefault

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#1320] opened 2017-08-11 14:44 UTC
Google Play Store:

android.os.FileUriExposedException
com.owncloud.android.ui.activity.UploadListActivity.openFileWithDefault

* Android: 7+
* Version: 1.4.1+

```
android.os.FileUriExposedException: 
  at android.os.StrictMode.onFileUriExposed (StrictMode.java:1816)
  at android.net.Uri.checkFileUriExposed (Uri.java:2350)
  at android.content.Intent.prepareToLeaveProcess (Intent.java:9076)
  at android.content.Intent.prepareToLeaveProcess (Intent.java:9037)
  at android.app.Instrumentation.execStartActivity (Instrumentation.java:1530)
  at android.app.Activity.startActivityForResult (Activity.java:4391)
  at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult (BaseFragmentActivityJB.java:48)
  at android.support.v4.app.FragmentActivity.startActivityForResult (FragmentActivity.java:77)
  at android.app.Activity.startActivityForResult (Activity.java:4335)
  at android.support.v4.app.FragmentActivity.startActivityForResult (FragmentActivity.java:859)
  at android.app.Activity.startActivity (Activity.java:4697)
  at android.app.Activity.startActivity (Activity.java:4665)
  at com.owncloud.android.ui.activity.UploadListActivity.openFileWithDefault (UploadListActivity.java:170)
  at com.owncloud.android.ui.activity.UploadListActivity.onUploadItemClick (UploadListActivity.java:153)
  at com.owncloud.android.ui.fragment.UploadListFragment.onChildClick (UploadListFragment.java:113)
  at android.widget.ExpandableListView.handleItemClick (ExpandableListView.java:740)
  at android.widget.ExpandableListView.performItemClick (ExpandableListView.java:679)
  at android.widget.AbsListView$PerformClick.run (AbsListView.java:3188)
  at android.widget.AbsListView$3.run (AbsListView.java:4131)
  at android.os.Handler.handleCallback (Handler.java:761)
  at android.os.Handler.dispatchMessage (Handler.java:98)
  at android.os.Looper.loop (Looper.java:156)
  at android.app.ActivityThread.main (ActivityThread.java:6524)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:941)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:831)
```

**Comment by tobiasKaminsky** [comment] 2017-08-16 09:43
On current master clicking on an item in the upload view does not do anything.
I guess this has changed.
Google play console reports it only in 1.4.x and not in 2, so this is maybe not a problem anylonger?

**Comment by tobiasKaminsky** [comment] 2017-08-17 06:36
Closing this as I cannot reproduce this error on 2.x.
If it still occurs, please reopen with steps to reproduce.

**Closed by tobiasKaminsky** 2017-08-17 06:36 UTC
Labels: bug
