### ISSUE TITLE
report

### ISSUE THREAD

**Issue by beniyas** [nextcloud/android#10349] opened 2022-06-07 04:55 UTC
### Cause of error
```java
Exception in thread "main" android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{1024a3d u0 com.nextcloud.client/com.owncloud.android.files.services.FileUploader}
    at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1973)
    at android.app.ActivityThread.access$2800(ActivityThread.java:265)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2198)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:299)
    at android.app.ActivityThread.main(ActivityThread.java:8166)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200251`
* Build flavor: `gplay`

### Device information
* Brand: `Redmi`
* Device: `sweet`
* Model: `M2101K6G`
* Id: `SKQ1.210908.001`
* Product: `sweet_global`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `V13.0.7.0.SKFMIXM`

**Comment by AlvaroBrey** [comment] 2022-06-07 07:31
Duplicate of #9617

**Closed by AlvaroBrey** 2022-06-07 07:31 UTC
Labels: bug
